"""DRAFT subtopic taxonomy for the 31 canonical chapters (Telugu + English), for review. NOT seeded in phase 1.

Keys are chapter numbers. Each entry is (slug suffix, English, Telugu); the full slug is ``<unit>-<chapter prefix>-<suffix>``
(for example ``u1-c04-economy-trade``). The suffix is derived from the approved English title and, once published, never changes.
Closely related items of the approved subtopic lists are grouped into one exam-friendly subtopic where noted by the wording.
"""
from .ap_canonical import CHAPTERS

DRAFT = {
    1: [("geography-extent", "Geographical extent and historical meaning of Andhradesa", "ఆంధ్రదేశ భౌగోళిక విస్తీర్ణం మరియు చారిత్రక అర్థం"),
        ("people-name-origin", "Andhra people and origin of the name", "ఆంధ్రులు మరియు పేరు పుట్టుక"),
        ("telugu-identity-language", "Development of Telugu identity and language", "తెలుగు గుర్తింపు మరియు భాష వికాసం"),
        ("literary-sources", "Literary sources", "సాహిత్య ఆధారాలు"),
        ("inscriptions", "Inscriptions", "శాసనాలు"),
        ("coins", "Coins", "నాణేలు"),
        ("archaeological-evidence", "Archaeological evidence", "పురావస్తు ఆధారాలు"),
        ("foreign-accounts", "Foreign accounts", "విదేశీయుల రచనలు"),
        ("important-sites", "Important historical sites", "ముఖ్య చారిత్రక స్థలాలు")],
    2: [("palaeolithic", "Palaeolithic", "పురా శిలాయుగం"),
        ("mesolithic", "Mesolithic", "మధ్య శిలాయుగం"),
        ("neolithic", "Neolithic", "నవీన శిలాయుగం"),
        ("chalcolithic", "Chalcolithic", "తామ్ర శిలాయుగం"),
        ("megalithic-iron-age", "Megalithic and Iron Age cultures", "మహాశిలా (మెగాలిథిక్) మరియు ఇనుప యుగ సంస్కృతులు"),
        ("tools-technology", "Tools and technologies", "పనిముట్లు మరియు సాంకేతికత"),
        ("pottery", "Pottery", "మట్టి పాత్రలు"),
        ("burial-practices", "Burial practices", "ఖననాచారాలు"),
        ("important-sites", "Important prehistoric sites in Andhra", "ఆంధ్రలోని ముఖ్య చరిత్రపూర్వ స్థలాలు")],
    3: [("assaka-asmaka", "Assaka / Asmaka", "అస్సక / అశ్మక"),
        ("early-andhra-references", "Early Andhra references", "ఆంధ్రుల తొలి ప్రస్తావనలు"),
        ("nandas-mauryas", "Nandas and Mauryas", "నందులు మరియు మౌర్యులు"),
        ("ashoka-inscriptions", "Ashoka's Andhra inscriptions", "ఆంధ్రలో అశోకుని శాసనాలు"),
        ("erragudi-rajulamandagiri", "Erragudi and Rajulamandagiri", "ఎర్రగుడి మరియు రాజులమందగిరి"),
        ("bhattiprolu", "Bhattiprolu", "భట్టిప్రోలు"),
        ("early-buddhism", "Early Buddhism", "తొలి బౌద్ధమతం"),
        ("amaravati-dhanyakataka-beginnings", "Amaravati / Dhanyakataka beginnings", "అమరావతి / ధాన్యకటకం ఆరంభాలు"),
        ("kharavela-hathigumpha", "Kharavela and the Hathigumpha inscription", "ఖారవేలుడు మరియు హాథీగుంఫా శాసనం"),
        ("early-local-rulers", "Early local rulers", "తొలి స్థానిక పాలకులు"),
        ("punch-marked-local-coinage", "Punch-marked and local coinage", "ఆహత (పంచ్-మార్క్డ్) మరియు స్థానిక నాణేలు")],
    4: [("origin-homeland", "Origin and homeland theories", "మూలం మరియు జన్మభూమి సిద్ధాంతాలు"),
        ("chronology", "Chronology", "కాలక్రమం"),
        ("political-history", "Political history", "రాజకీయ చరిత్ర"),
        ("important-rulers", "Important rulers", "ముఖ్య పాలకులు"),
        ("administration", "Administration", "పరిపాలన"),
        ("society", "Society", "సమాజం"),
        ("economy-trade", "Economy, agriculture, guilds and trade (including Indo-Roman trade)", "ఆర్థిక వ్యవస్థ, వ్యవసాయం, వర్తక శ్రేణులు మరియు వాణిజ్యం (ఇండో-రోమన్ వాణిజ్యంతో సహా)"),
        ("coinage", "Coinage", "నాణేల వ్యవస్థ"),
        ("religion", "Religion", "మతం"),
        ("literature", "Prakrit and literature", "ప్రాకృతం మరియు సాహిత్యం"),
        ("art-architecture", "Amaravati art and architecture", "అమరావతి కళ మరియు వాస్తుశిల్పం"),
        ("inscriptions", "Inscriptions", "శాసనాలు"),
        ("decline", "Decline", "పతనం")],
    5: [("origin-chronology", "Origin and chronology", "మూలం మరియు కాలక్రమం"),
        ("important-rulers", "Important rulers", "ముఖ్య పాలకులు"),
        ("vijayapuri-nagarjunakonda", "Vijayapuri and Nagarjunakonda", "విజయపురి మరియు నాగార్జునకొండ"),
        ("administration", "Administration", "పరిపాలన"),
        ("socio-economic-conditions", "Socio-economic conditions", "సామాజిక-ఆర్థిక పరిస్థితులు"),
        ("buddhism", "Buddhism", "బౌద్ధమతం"),
        ("brahmanism", "Brahmanism", "బ్రాహ్మణ మతం"),
        ("royal-women", "Royal women", "రాజవంశ స్త్రీలు"),
        ("literature-education", "Literature and education", "సాహిత్యం మరియు విద్య"),
        ("art-architecture", "Art and architecture", "కళ మరియు వాస్తుశిల్పం"),
        ("inscriptions", "Inscriptions", "శాసనాలు"),
        ("decline", "Decline", "పతనం")],
    6: [("brihatphalayanas", "Brihatphalayanas", "బృహత్‌ఫలాయనులు"),
        ("ananda-gotrikas", "Ananda Gotrikas", "ఆనంద గోత్రికులు"),
        ("salankayanas", "Salankayanas", "శాలంకాయనులు"),
        ("pallava-influence", "Pallava influence", "పల్లవుల ప్రభావం"),
        ("other-transitional-dynasties", "Other transitional dynasties", "ఇతర పరివర్తన రాజవంశాలు"),
        ("political-conditions", "Political conditions", "రాజకీయ పరిస్థితులు"),
        ("society-economy", "Society and economy", "సమాజం మరియు ఆర్థిక వ్యవస్థ"),
        ("religion", "Religion", "మతం"),
        ("inscriptions", "Inscriptions", "శాసనాలు"),
        ("art-architecture", "Art and architecture", "కళ మరియు వాస్తుశిల్పం")],
    7: [("origin-chronology", "Origin and chronology", "మూలం మరియు కాలక్రమం"),
        ("important-rulers", "Important rulers", "ముఖ్య పాలకులు"),
        ("political-expansion", "Political expansion", "రాజకీయ విస్తరణ"),
        ("administration", "Administration", "పరిపాలన"),
        ("society-economy", "Society and economy", "సమాజం మరియు ఆర్థిక వ్యవస్థ"),
        ("religion", "Religion", "మతం"),
        ("sanskrit-telugu-development", "Sanskrit and Telugu development", "సంస్కృతం మరియు తెలుగు వికాసం"),
        ("cave-temple-architecture", "Cave and temple architecture", "గుహలు మరియు దేవాలయ వాస్తుశిల్పం"),
        ("coins", "Coins", "నాణేలు"),
        ("inscriptions", "Inscriptions", "శాసనాలు"),
        ("decline", "Decline", "పతనం")],
    8: [("vengi-foundation", "Foundation of the Vengi kingdom", "వేంగి రాజ్య స్థాపన"),
        ("political-chronology", "Political chronology", "రాజకీయ కాలక్రమం"),
        ("important-rulers", "Important rulers", "ముఖ్య పాలకులు"),
        ("chola-chalukya-relations", "Chola–Chalukya relations and the Chalukya-Chola period", "చోళ–చాళుక్య సంబంధాలు మరియు చాళుక్య-చోళ యుగం"),
        ("administration", "Administration", "పరిపాలన"),
        ("society-economy", "Society and economy", "సమాజం మరియు ఆర్థిక వ్యవస్థ"),
        ("religion", "Religion", "మతం"),
        ("telugu-nannaya-literature", "Growth of Telugu; Nannaya and early Telugu literature", "తెలుగు వికాసం; నన్నయ మరియు తొలి తెలుగు సాహిత్యం"),
        ("art-architecture", "Art and architecture", "కళ మరియు వాస్తుశిల్పం"),
        ("temples-pancharamas", "Temples and Pancharamas", "దేవాలయాలు మరియు పంచారామాలు"),
        ("velanati-chodas", "Velanati Chodas", "వెలనాటి చోడులు"),
        ("nellore-telugu-chodas", "Nellore Telugu Chodas", "నెల్లూరు తెలుగు చోడులు"),
        ("palnadu-war", "Palnadu War", "పల్నాటి యుద్ధం"),
        ("inscriptions", "Inscriptions", "శాసనాలు"),
        ("decline-transition", "Decline and transition", "పతనం మరియు పరివర్తన")],
    9: [("origin-early-rulers", "Origin and early rulers", "మూలం మరియు తొలి పాలకులు"),
        ("rudradeva", "Rudradeva", "రుద్రదేవుడు"),
        ("mahadeva", "Mahadeva", "మహాదేవుడు"),
        ("ganapatideva", "Ganapatideva", "గణపతిదేవుడు"),
        ("rudramadevi", "Rudramadevi", "రుద్రమదేవి"),
        ("prataparudra", "Prataparudra", "ప్రతాపరుద్రుడు"),
        ("political-expansion", "Political expansion", "రాజకీయ విస్తరణ"),
        ("delhi-sultanate-invasions", "Delhi Sultanate invasions", "ఢిల్లీ సుల్తానుల దండయాత్రలు"),
        ("administration-nayankara", "Administration and the Nayankara system", "పరిపాలన మరియు నాయంకర వ్యవస్థ"),
        ("irrigation-agriculture", "Irrigation and agriculture", "నీటిపారుదల మరియు వ్యవసాయం"),
        ("crafts-trade-motupalli", "Crafts, trade and Motupalli", "చేతివృత్తులు, వాణిజ్యం మరియు మోటుపల్లి"),
        ("society", "Society", "సమాజం"),
        ("religion", "Religion", "మతం"),
        ("telugu-literature", "Telugu literature", "తెలుగు సాహిత్యం"),
        ("dance-music", "Dance and music", "నృత్యం మరియు సంగీతం"),
        ("art-architecture", "Art and architecture", "కళ మరియు వాస్తుశిల్పం"),
        ("decline", "Decline", "పతనం")],
    10: [("post-kakatiya-conditions", "Post-Kakatiya political conditions", "కాకతీయానంతర రాజకీయ పరిస్థితులు"),
         ("musunuri-nayakas", "Musunuri Prolaya Nayaka, Kapaya Nayaka and the liberation of Warangal", "ముసునూరి ప్రోలయ నాయకుడు, కాపయ నాయకుడు మరియు ఓరుగల్లు విముక్తి"),
         ("kondavidu-reddys", "Kondavidu Reddys", "కొండవీడు రెడ్డిలు"),
         ("rajahmundry-reddys", "Rajahmundry Reddys", "రాజమహేంద్రవరం రెడ్డిలు"),
         ("recharla-velamas", "Recharla Velamas (Rachakonda and Devarakonda)", "రేచర్ల వెలమలు (రాచకొండ మరియు దేవరకొండ)"),
         ("administration", "Administration", "పరిపాలన"),
         ("society-economy", "Society and economy", "సమాజం మరియు ఆర్థిక వ్యవస్థ"),
         ("religion", "Religion", "మతం"),
         ("telugu-literature", "Telugu literature", "తెలుగు సాహిత్యం"),
         ("art-architecture", "Art and architecture", "కళ మరియు వాస్తుశిల్పం"),
         ("regional-conflicts", "Regional conflicts", "ప్రాంతీయ సంఘర్షణలు")],
    11: [("foundation", "Foundation", "స్థాపన"),
         ("four-dynasties", "Four dynasties", "నాలుగు రాజవంశాలు"),
         ("important-rulers", "Important rulers", "ముఖ్య పాలకులు"),
         ("krishnadevaraya", "Sri Krishnadevaraya", "శ్రీకృష్ణదేవరాయలు"),
         ("andhra-campaigns-gajapati-bahmani", "Andhra campaigns; Gajapati and Bahmani conflicts", "ఆంధ్రలో సైనిక దండయాత్రలు; గజపతి మరియు బహమనీ సంఘర్షణలు"),
         ("administration-nayankara", "Administration and the Nayankara system", "పరిపాలన మరియు నాయంకర వ్యవస్థ"),
         ("economy-trade", "Economy and trade", "ఆర్థిక వ్యవస్థ మరియు వాణిజ్యం"),
         ("society", "Society", "సమాజం"),
         ("religion", "Religion", "మతం"),
         ("telugu-literature-ashtadiggajas", "Telugu literature and the Ashtadiggajas", "తెలుగు సాహిత్యం మరియు అష్టదిగ్గజాలు"),
         ("art-architecture", "Art and architecture", "కళ మరియు వాస్తుశిల్పం"),
         ("battle-of-talikota", "Battle of Talikota", "తళ్ళికోట యుద్ధం"),
         ("decline", "Decline", "పతనం")],
    12: [("gajapati-rule-influence", "Gajapati rule and influence in Andhra", "ఆంధ్రలో గజపతుల పాలన మరియు ప్రభావం"),
         ("bahmani-vijayanagara-rivalry", "Bahmani–Vijayanagara rivalry", "బహమనీ–విజయనగర వైరం"),
         ("coastal-andhra-conflicts", "Coastal Andhra conflicts", "తీరాంధ్ర సంఘర్షణలు"),
         ("minor-regional-powers", "Minor regional powers", "చిన్న ప్రాంతీయ శక్తులు"),
         ("forts-political-centres", "Forts and political centres", "కోటలు మరియు రాజకీయ కేంద్రాలు"),
         ("socio-cultural-influence", "Socio-cultural influence", "సామాజిక-సాంస్కృతిక ప్రభావం"),
         ("political-transition", "Political transition", "రాజకీయ పరివర్తన")],
    13: [("establishment", "Establishment of Qutb Shahi power", "కుతుబ్‌షాహీ అధికార స్థాపన"),
         ("sixteenth-century-rulers", "Important sixteenth-century rulers", "పదహారో శతాబ్దపు ముఖ్య పాలకులు"),
         ("expansion-into-andhra", "Expansion into Andhra", "ఆంధ్రలో విస్తరణ"),
         ("administration", "Administration", "పరిపాలన"),
         ("society-economy", "Society and economy", "సమాజం మరియు ఆర్థిక వ్యవస్థ"),
         ("trade-ports-golconda", "Trade, ports and Golconda commerce", "వాణిజ్యం, రేవులు మరియు గోల్కొండ వర్తకం"),
         ("religion", "Religion", "మతం"),
         ("telugu-dakhni-patronage", "Telugu and Dakhni patronage", "తెలుగు మరియు దక్కనీ భాషల పోషణ"),
         ("art-architecture", "Art and architecture", "కళ మరియు వాస్తుశిల్పం")],
    14: [("comparative-administration", "Comparative administration", "తులనాత్మక పరిపాలన"),
         ("social-structure", "Social structure", "సామాజిక నిర్మాణం"),
         ("economic-conditions", "Economic conditions", "ఆర్థిక పరిస్థితులు"),
         ("agriculture-irrigation", "Agriculture and irrigation", "వ్యవసాయం మరియు నీటిపారుదల"),
         ("trade", "Internal and overseas trade", "అంతర్గత మరియు విదేశీ వాణిజ్యం"),
         ("religious-movements", "Religious movements", "మత ఉద్యమాలు"),
         ("growth-of-telugu", "Growth of Telugu", "తెలుగు వికాసం"),
         ("authors-works", "Major authors and works", "ముఖ్య కవులు మరియు రచనలు"),
         ("sculpture", "Sculpture", "శిల్పకళ"),
         ("temple-architecture", "Temple architecture", "దేవాలయ వాస్తుశిల్పం"),
         ("forts", "Forts", "కోటలు"),
         ("music-dance", "Music and dance", "సంగీతం మరియు నృత్యం")],
    15: [("portuguese", "Portuguese", "పోర్చుగీసువారు"),
         ("dutch", "Dutch", "డచ్చివారు"),
         ("english", "English", "ఆంగ్లేయులు"),
         ("french", "French", "ఫ్రెంచివారు"),
         ("trading-centres-ports", "European trading centres and ports", "యూరోపియన్ వ్యాపార కేంద్రాలు మరియు రేవులు"),
         ("european-rivalries", "European rivalries", "యూరోపియన్ల మధ్య పోటీ"),
         ("northern-circars", "Northern Circars", "ఉత్తర సర్కారులు"),
         ("ceded-districts", "Ceded Districts", "దత్త మండలాలు"),
         ("company-administration", "Andhra under the East India Company", "ఈస్టిండియా కంపెనీ పాలనలో ఆంధ్ర"),
         ("revenue-systems", "Revenue systems", "శిస్తు (రెవెన్యూ) విధానాలు"),
         ("early-economic-social-impact", "Early economic and social impact", "తొలి ఆర్థిక మరియు సామాజిక ప్రభావం")],
    16: [("consolidation-of-administration", "Consolidation of British administration", "బ్రిటిష్ పరిపాలన స్థిరీకరణ"),
         ("zamindari-ryotwari", "Zamindari and Ryotwari systems", "జమీందారీ మరియు రైత్వారీ విధానాలు"),
         ("thomas-munro", "Thomas Munro", "థామస్ మన్రో"),
         ("arthur-cotton", "Arthur Cotton", "ఆర్థర్ కాటన్"),
         ("administrative-economic-effects", "Administrative and economic effects", "పరిపాలనా మరియు ఆర్థిక ప్రభావాలు"),
         ("revolt-of-1857", "Revolt of 1857", "1857 తిరుగుబాటు"),
         ("andhra-events-personalities-1857", "Events and personalities connected to Andhra", "ఆంధ్రకు సంబంధించిన సంఘటనలు మరియు వ్యక్తులు"),
         ("impact-of-1857", "Impact of 1857 on Andhra", "ఆంధ్రపై 1857 ప్రభావం")],
    17: [("western-education", "Western education", "పాశ్చాత్య విద్య"),
         ("missionary-activity", "Missionary activity", "క్రైస్తవ మిషనరీ కార్యకలాపాలు"),
         ("print-culture", "Print culture", "ముద్రణ సంస్కృతి"),
         ("social-reform", "Social reform", "సామాజిక సంస్కరణ"),
         ("veeresalingam", "Kandukuri Veeresalingam", "కందుకూరి వీరేశలింగం"),
         ("raghupati-venkataratnam-naidu", "Raghupati Venkataratnam Naidu", "రఘుపతి వెంకటరత్నం నాయుడు"),
         ("gurajada-apparao", "Gurajada Apparao", "గురజాడ అప్పారావు"),
         ("womens-reform", "Women's reform", "మహిళా సంస్కరణ"),
         ("modern-telugu-awakening", "Modern Telugu cultural awakening", "ఆధునిక తెలుగు సాంస్కృతిక చైతన్యం"),
         ("associations-institutions", "Important associations and institutions", "ముఖ్య సంఘాలు మరియు సంస్థలు")],
    18: [("non-brahmin-origins", "Origins of the Non-Brahmin movement", "బ్రాహ్మణేతర ఉద్యమ మూలాలు"),
         ("justice-party", "Justice Party", "జస్టిస్ పార్టీ"),
         ("important-leaders", "Important leaders", "ముఖ్య నాయకులు"),
         ("policies-social-impact", "Policies and social impact", "విధానాలు మరియు సామాజిక ప్రభావం"),
         ("self-respect-movement", "Self-Respect Movement", "ఆత్మగౌరవ ఉద్యమం"),
         ("influence-in-andhra", "Influence in Andhra", "ఆంధ్రలో ప్రభావం"),
         ("debates-limitations", "Debates and limitations", "చర్చలు మరియు పరిమితులు")],
    19: [("early-political-associations", "Early political associations", "తొలి రాజకీయ సంఘాలు"),
         ("congress-and-andhra", "Indian National Congress and Andhra", "భారత జాతీయ కాంగ్రెస్ మరియు ఆంధ్ర"),
         ("swadeshi-vandemataram", "Swadeshi and Vandemataram", "స్వదేశీ మరియు వందేమాతర ఉద్యమాలు"),
         ("home-rule", "Home Rule", "స్వపరిపాలన (హోమ్ రూల్) ఉద్యమం"),
         ("non-cooperation", "Non-Cooperation", "సహాయ నిరాకరణ"),
         ("chirala-perala-pedanandipadu", "Chirala–Perala and Pedanandipadu", "చీరాల–పేరాల మరియు పెదనందిపాడు"),
         ("civil-disobedience-salt-satyagraha", "Civil Disobedience and Salt Satyagraha", "శాసనోల్లంఘన మరియు ఉప్పు సత్యాగ్రహం"),
         ("individual-satyagraha", "Individual Satyagraha", "వ్యక్తిగత సత్యాగ్రహం"),
         ("quit-india", "Quit India", "క్విట్ ఇండియా ఉద్యమం"),
         ("prominent-leaders", "Prominent leaders", "ప్రముఖ నాయకులు"),
         ("regional-centres-events", "Regional centres and events", "ప్రాంతీయ కేంద్రాలు మరియు సంఘటనలు")],
    20: [("socialists", "Socialist organisations and leaders", "సోషలిస్టు సంస్థలు మరియు నాయకులు"),
         ("communist-movement", "Communist movement", "కమ్యూనిస్టు ఉద్యమం"),
         ("peasant-organisation", "Peasant organisation", "రైతు సంఘటన"),
         ("anti-zamindari-struggles", "Anti-Zamindari struggles", "జమీందారీ వ్యతిరేక పోరాటాలు"),
         ("kisan-sabhas", "Kisan Sabhas", "కిసాన్ సభలు"),
         ("ng-ranga", "N. G. Ranga", "ఎన్. జి. రంగా"),
         ("labour-mobilisation", "Labour mobilisation", "కార్మిక సమీకరణ"),
         ("regional-agrarian-struggles", "Important regional agrarian struggles", "ముఖ్య ప్రాంతీయ రైతాంగ పోరాటాలు"),
         ("relation-to-national-movement", "Relationship with the national movement", "జాతీయోద్యమంతో సంబంధం")],
    21: [("nationalist-poetry", "Nationalist poetry", "జాతీయ కవిత్వం"),
         ("revolutionary-writings", "Revolutionary writings", "విప్లవ రచనలు"),
         ("poets-authors", "Important poets and authors", "ముఖ్య కవులు మరియు రచయితలు"),
         ("newspapers-publications", "Newspapers and literary publications", "వార్తాపత్రికలు మరియు సాహిత్య ప్రచురణలు"),
         ("drama-organisations", "Drama organisations", "నాటక సంస్థలు"),
         ("nataka-samasthalu", "Nataka Samasthalu", "నాటక సమాజాలు"),
         ("praja-natya-mandali", "Praja Natya Mandali", "ప్రజా నాట్య మండలి"),
         ("maa-bhoomi", "Maa Bhoomi", "మా భూమి"),
         ("folk-performance-mobilisation", "Folk performance in political mobilisation", "రాజకీయ చైతన్యంలో జానపద ప్రదర్శనలు")],
    22: [("women-reformers", "Women social reformers", "మహిళా సంఘ సంస్కర్తలు"),
         ("swadeshi-home-rule", "Women in Swadeshi and Home Rule", "స్వదేశీ మరియు హోమ్ రూల్ ఉద్యమాల్లో మహిళలు"),
         ("gandhian-movements", "Women in Gandhian movements", "గాంధేయ ఉద్యమాల్లో మహిళలు"),
         ("revolutionary-peasant-movements", "Women in revolutionary and peasant movements", "విప్లవ మరియు రైతాంగ ఉద్యమాల్లో మహిళలు"),
         ("organisations", "Organisations", "సంస్థలు"),
         ("prominent-women", "Prominent women", "ప్రముఖ మహిళలు"),
         ("regional-events", "Regional events", "ప్రాంతీయ సంఘటనలు"),
         ("social-consequences", "Social consequences", "సామాజిక పరిణామాలు")],
    23: [("linguistic-identity-roots", "Roots of linguistic identity", "భాషా గుర్తింపు మూలాలు"),
         ("demand-for-andhra-province", "Demand for a separate Andhra province", "ప్రత్యేక ఆంధ్ర ప్రాంతం కోసం డిమాండ్"),
         ("early-organisations", "Early organisations", "తొలి సంస్థలు"),
         ("important-conferences", "Important conferences", "ముఖ్య సభలు"),
         ("andhra-provincial-congress", "Andhra Provincial Congress", "ఆంధ్ర ప్రాంతీయ కాంగ్రెస్"),
         ("andhra-university", "Andhra University", "ఆంధ్ర విశ్వవిద్యాలయం"),
         ("major-resolutions", "Major resolutions", "ముఖ్య తీర్మానాలు"),
         ("sri-bagh-pact", "Sri Bagh Pact", "శ్రీబాగ్ ఒడంబడిక"),
         ("political-cultural-dimensions", "Political and cultural dimensions", "రాజకీయ మరియు సాంస్కృతిక కోణాలు")],
    24: [("origin-sessions", "Origin and sessions of the Andhra Mahasabhas", "ఆంధ్ర మహాసభల ఆవిర్భావం మరియు సమావేశాలు"),
         ("resolutions", "Resolutions", "తీర్మానాలు"),
         ("organisational-development", "Organisational development", "సంస్థాగత అభివృద్ధి"),
         ("major-leaders", "Major leaders", "ప్రముఖ నాయకులు"),
         ("ideological-differences", "Ideological differences", "సైద్ధాంతిక భేదాలు"),
         ("contribution-to-state-formation", "Contribution to state formation", "రాష్ట్ర ఏర్పాటుకు తోడ్పాటు")],
    25: [("krishna-patrika", "Krishna Patrika", "కృష్ణా పత్రిక"),
         ("andhra-patrika", "Andhra Patrika", "ఆంధ్ర పత్రిక"),
         ("other-newspapers", "Other newspapers", "ఇతర పత్రికలు"),
         ("journalists-editors", "Journalists and editors", "పాత్రికేయులు మరియు సంపాదకులు"),
         ("press-political-mobilisation", "Press and political mobilisation", "పత్రికలు మరియు రాజకీయ చైతన్యం"),
         ("library-movement", "Library Movement", "గ్రంథాలయోద్యమం"),
         ("ayyanki-venkata-ramanayya", "Ayyanki Venkata Ramanayya", "అయ్యంకి వెంకటరమణయ్య"),
         ("andhra-desa-library-association", "Andhra Desa Library Association", "ఆంధ్ర దేశ గ్రంథాలయ సంఘం"),
         ("language-literary-organisations", "Language and literary organisations", "భాషా మరియు సాహిత్య సంస్థలు"),
         ("libraries-public-awakening", "Libraries as centres of public awakening", "ప్రజా చైతన్య కేంద్రాలుగా గ్రంథాలయాలు")],
    26: [("folk-traditions", "Folk traditions of Andhra", "ఆంధ్ర జానపద సంప్రదాయాలు"),
         ("harikatha", "Harikatha", "హరికథ"),
         ("burrakatha", "Burrakatha", "బుర్రకథ"),
         ("tholu-bommalata", "Tholu Bommalata", "తోలుబొమ్మలాట"),
         ("regional-dance-performance", "Regional dance and performance traditions", "ప్రాంతీయ నృత్య మరియు ప్రదర్శన సంప్రదాయాలు"),
         ("major-tribal-communities", "Major tribal communities", "ప్రధాన గిరిజన తెగలు"),
         ("tribal-customs-festivals", "Tribal customs and festivals", "గిరిజన ఆచారాలు మరియు పండుగలు"),
         ("tribal-resistance", "Tribal resistance (where directly relevant)", "గిరిజన ప్రతిఘటన (నేరుగా సంబంధించిన చోట)"),
         ("identity-mobilisation", "Role in social identity and mobilisation", "సామాజిక గుర్తింపు మరియు చైతన్యంలో పాత్ర")],
    27: [("constitutional-political-background", "Constitutional and political background", "రాజ్యాంగ మరియు రాజకీయ నేపథ్యం"),
         ("dhar-commission", "Dhar Commission", "ధార్ కమిషన్"),
         ("jvp-committee", "JVP Committee", "జె.వి.పి. కమిటీ"),
         ("swami-sitaram", "Swami Sitaram", "స్వామి సీతారాం"),
         ("potti-sriramulu", "Potti Sriramulu", "పొట్టి శ్రీరాములు"),
         ("madras-question", "Madras question", "మద్రాసు సమస్య"),
         ("fast-and-death", "Potti Sriramulu's fast and death", "పొట్టి శ్రీరాములు నిరాహార దీక్ష మరియు మరణం"),
         ("public-response", "Public response", "ప్రజా స్పందన"),
         ("formation-of-andhra-state", "Formation of Andhra State", "ఆంధ్ర రాష్ట్ర ఏర్పాటు"),
         ("kurnool-capital", "Kurnool as capital", "కర్నూలు రాజధానిగా"),
         ("tanguturi-prakasam", "Tanguturi Prakasam", "టంగుటూరి ప్రకాశం"),
         ("consequences", "Consequences", "పరిణామాలు")],
    28: [("visalandhra-idea", "Visalandhra idea", "విశాలాంధ్ర భావన"),
         ("linguistic-political-arguments", "Linguistic and political arguments", "భాషా మరియు రాజకీయ వాదనలు"),
         ("visalandhra-mahasabha", "Visalandhra Mahasabha", "విశాలాంధ్ర మహాసభ"),
         ("supporters-opponents", "Prominent supporters and opponents", "ప్రముఖ మద్దతుదారులు మరియు వ్యతిరేకులు"),
         ("andhra-telangana-merger-debate", "Andhra–Telangana merger debate", "ఆంధ్ర–తెలంగాణ విలీన చర్చ"),
         ("meetings-resolutions", "Important meetings and resolutions", "ముఖ్య సమావేశాలు మరియు తీర్మానాలు")],
    29: [("formation-members", "Formation and members", "ఏర్పాటు మరియు సభ్యులు"),
         ("terms-of-reference", "Terms of reference", "విధివిధానాలు (నిబంధనలు)"),
         ("andhra-telangana-evidence", "Andhra and Telangana evidence", "ఆంధ్ర మరియు తెలంగాణ సాక్ష్యాలు"),
         ("recommendations", "Recommendations", "సిఫారసులు"),
         ("arguments-separate-telangana", "Arguments for a separate Telangana", "ప్రత్యేక తెలంగాణ కోసం వాదనలు"),
         ("conditions-for-merger", "Conditions suggested for merger", "విలీనానికి సూచించిన షరతులు"),
         ("political-responses", "Political responses", "రాజకీయ స్పందనలు")],
    30: [("negotiations", "Negotiations", "చర్చలు"),
         ("signatories", "Signatories", "సంతకందారులు"),
         ("provisions", "Provisions", "ఒప్పంద నిబంధనలు"),
         ("regional-safeguards", "Regional safeguards", "ప్రాంతీయ రక్షణలు"),
         ("merger-process", "Merger process", "విలీన ప్రక్రియ"),
         ("formation-1-november-1956", "Formation on 1 November 1956", "1956 నవంబరు 1న ఏర్పాటు"),
         ("hyderabad-capital", "Hyderabad as capital", "హైదరాబాద్ రాజధానిగా"),
         ("implementation-issues", "Implementation issues", "అమలులో సమస్యలు"),
         ("long-term-significance", "Long-term significance", "దీర్ఘకాలిక ప్రాధాన్యం")],
    31: [("official-language-telugu", "Official language and Telugu development", "అధికార భాష మరియు తెలుగు అభివృద్ధి"),
         ("education-universities", "Education and universities", "విద్య మరియు విశ్వవిద్యాలయాలు"),
         ("literature", "Literature", "సాహిత్యం"),
         ("theatre", "Theatre", "రంగస్థలం"),
         ("cinema", "Cinema", "సినిమా"),
         ("visual-performing-arts", "Visual and performing arts", "చిత్ర మరియు ప్రదర్శన కళలు"),
         ("cultural-institutions", "Cultural institutions", "సాంస్కృతిక సంస్థలు"),
         ("dalit-social-movements", "Dalit and social movements", "దళిత మరియు సామాజిక ఉద్యమాలు"),
         ("womens-movements", "Women's movements", "మహిళా ఉద్యమాలు"),
         ("civil-society-movements", "Civil-society movements", "పౌర సమాజ ఉద్యమాలు"),
         ("telangana-movement-1969", "Telangana movement of 1969", "1969 తెలంగాణ ఉద్యమం"),
         ("jai-andhra-1972", "Jai Andhra Movement of 1972", "1972 జై ఆంధ్ర ఉద్యమం"),
         ("regional-identity-movements", "Regional identity movements", "ప్రాంతీయ గుర్తింపు ఉద్యమాలు"),
         ("cultural-developments-to-2014", "Major cultural developments up to 2014", "2014 వరకు ముఖ్య సాంస్కృతిక పరిణామాలు")],
}

# Subtopics for the three supplementary chapters are deliberately not drafted: they are reference material, not question targets.


def expanded():
    """{chapter_slug: [(full_slug, English, Telugu), ...]} with full slugs built from the stable chapter prefix."""
    out = {}
    for _unit, num, slug, _en, _te, _cls in CHAPTERS:
        prefix = "-".join(slug.split("-")[:2])
        out[slug] = [(f"{prefix}-{suffix}", en, te) for suffix, en, te in DRAFT.get(num, [])]
    return out
