#!/usr/bin/env python3
"""
Add Telugu translations to MCQs 31726-31775 (Final Batch 11)
Task: Add bilingual Telugu/English format to government scheme MCQs
"""

import re

# Telugu translations dictionary for MCQ questions and key terms
TELUGU_TRANSLATIONS = {
    31726: {
        'question': 'జూన్ 2024లో స్థాపించిన "జాతీయ నృత్య వారసత్వ నిధి"లో ఎన్ని శాస్త్రీయ మరియు జానపద నృత్య రూపాలను చేర్చారు?\n(How many classical and folk dance forms have been included in the "National Dance Heritage Fund" established in 2024?)',
        'explanation_intro': '**జాతీయ నృత్య వారసత్వ నిధి**, 2024లో సంస్కృతి మంత్రిత్వం ద్వారా స్థాపించబడింది, భారతదేశం యొక్క సమృద్ధ మరియు వైవిధ్యమైన చలన సంప్రదాయాలను సూచిస్తూ 41 శాస్త్రీయ మరియు జానపద నృత్య రూపాలను కలిగి ఉంది. (The National Dance Heritage Fund, established in 2024 by the Ministry of Culture, includes 41 classical and folk dance forms, representing India\'s rich and diverse movement traditions.)',
    },
    31727: {
        'question': '"డిజిటల్ మ్యూజియం ఇనిషియేటివ్ 2.0" కింద మే 2026 నాటికి భారతీయ మ్యూజియాలు తమ సంગ్రహణల పూర్తి డిజిటల్ కేటలాగింగ్‌ను సాధించినవి ఎన్ని?\n(Under the "Digital Museum Initiative 2.0," how many Indian museums have achieved full digital cataloging of their collections as of May 2026?)',
        'explanation_intro': 'మే 2026 నాటికి, 318 భారతీయ మ్యూజియాలు "డిజిటల్ మ్యూజియం ఇనిషియేటివ్ 2.0" కింద తమ సంగ్రహణల పూర్తి డిజిటల్ కేటలాగింగ్‌ను సాధించాయి, 2021లో సంస్కృతి మంత్రిత్వం ప్రారంభించిన సమగ్ర డిజిటలీకరణ మరియు వర్చువల్ ప్రాప్యత కార్యక్రమం. (As of May 2026, 318 Indian museums have achieved full digital cataloging of their collections under the Digital Museum Initiative 2.0, a comprehensive digitization and virtual accessibility program launched by the Ministry of Culture in 2021.)',
    },
    31728: {
        'question': 'మే 2026 నాటికి యూనెస్కో ప్రతినిధి జాబితాలో భారत నుండి ఎన్ని అవ్యక్త సాంస్కృతిక వారసత్వ (ICH) అంశాలను గుర్తించారు?\n(How many Intangible Cultural Heritage elements from India have been recognized by UNESCO\'s Representative List as of May 2026?)',
        'explanation_intro': 'మే 2026 నాటికి, 28 అవ్యక్త సాంస్కృతిక వారసత్వ (ICH) అంశాలను యూనెస్కో ప్రతినిధి జాబితాలో ఉన్నాయి, భారతీయ సాంస్కృతిక సంప్రదాయాల ప్రపంచ ప్రాముఖ్యతను ప్రతిబింబిస్తుంది. (As of May 2026, 28 Intangible Cultural Heritage (ICH) elements from India have been recognized on UNESCO\'s Representative List, reflecting the global significance of Indian cultural traditions.)',
    },
    31729: {
        'question': '2025లో భారతదేశ కారిగర్ నైపుణ్య సమూహాలు ఎంత మొత్తం ఆర్థిక ప్రభావాన్ని ఆర్జన చేసాయి?\n(What was the total economic impact generated by India\'s artisan craft clusters in 2025?)',
        'explanation_intro': '2025లో భారతదేశ కారిగర్ నైపుణ్య సమూహాల ద్వారా ఆర్జన చేసిన మొత్తం ఆర్థిక ప్రభావం 142,300 కోట్ల రూపాయలు, 2020 నుండి 34% పెరుగుదలను సూచిస్తుంది. (The total economic impact generated by India\'s artisan craft clusters in 2025 was INR 142,300 crores, representing a 34% increase from 2020.)',
    },
    31730: {
        'question': '2023-2026 నుండి భారత నుండి ఎన్ని కొత్త యూనెస్కో విశ్వ వారసత్వ స్థలాలను నమోదు చేసారు?\n(How many new UNESCO World Heritage Sites have been inscribed from India between 2023-2026?)',
        'explanation_intro': '2023-2026 కాలంలో, భారత నుండి 5 కొత్త యూనెస్కో విశ్వ వారసత్వ స్థలాలను నమోదు చేసారు, మొత్తం సంఖ్యను 52కు తీసుకువెళ్లారు. (Between 2023-2026, 5 new UNESCO World Heritage Sites have been inscribed from India, bringing the total number of World Heritage Sites to 52.)',
    },
    31731: {
        'question': '2024లో ప్రారంభించిన "భౌగోళిక సూచన ఆహార వారసత్వ కార్యక్రమం" యొక్క ప్రధాన లక్ష్యం ఏమిటి?\n(What is the primary goal of the "Geographical Indication Food Heritage Program" launched in 2024?)',
        'explanation_intro': '2024లో సంస్కృతి మంత్రిత్వం మరియు వ్యవసాయ మంత్రిత్వం ద్వారా ప్రారంభించిన "భౌగోళిక సూచన ఆహార వారసత్వ కార్యక్రమం" 150+ సాంప్రదాయిక భారతీయ ఆహార ఉత్పత్తులను GI సర్టిఫికేషన ద్వారా గుర్తించి రక్షించడを లక్ష్యంగా చేసుకుంది. (The Geographical Indication Food Heritage Program, launched in 2024 by the Ministry of Agriculture and Ministry of Culture in collaboration with state governments, aims to recognize and protect 150+ traditional Indian food products through GI certification.)',
    },
    31732: {
        'question': '"జాతీయ ఆర్కైవ్ విస్తరణ ప్రకల్పన" కింద మే 2026 నాటికి ఎన్ని ప్రాంతీయ సాంస్కృతిక ఆర్కైవ్‌లను స్థాపించారు?\n(How many Regional Cultural Archives have been established under the "National Archive Expansion Project" as of May 2026?)',
        'explanation_intro': 'మే 2026 నాటికి, "జాతీయ ఆర్కైవ్ విస్తరణ ప్రకల్పన" కింద 26 ప్రాంతీయ సాంస్కృతిక ఆర్కైవ్‌లను స్థాపించారు, 2022లో సంస్కృతి మంత్రిత్వం ద్వారా ప్రారంభించిన సాంస్కృతిక వారసత్వ నమోదు గ్రామీణీకరణ మరియు సృష్టి సమగ్ర భాండారాలు. (As of May 2026, 26 Regional Cultural Archives have been established under the National Archive Expansion Project, launched by the Ministry of Culture in 2022 to decentralize cultural heritage documentation.)',
    },
    31733: {
        'question': '2023లో ప్రారంభించిన "జాతీయ నటన కళా బుందిక్‌ కార్యక్రమ" కింద నిర్మిత కొత్త నటన కళా కేంద్రాల మొత్తం సీటింగ్ సామర్థ్యం ఏమిటి?\n(What is the total seating capacity and operational status of new Performing Arts Centers built under the "National Performing Arts Infrastructure Program" launched in 2023?)',
        'explanation_intro': '2023లో ప్రారంభించిన జాతీయ నటన కళా సంస్థాపన కార్యక్రమం కింద, 52 కొత్త నటన కళా కేంద్రాలను నిర్మించారు మరియు 228,000 సీటుల సమ్మిళిత సామర్థ్యంతో సంచాలనం చేసారు. (Under the National Performing Arts Infrastructure Program launched in 2023, 52 new Performing Arts Centers have been constructed and operationalized across India with a combined seating capacity of 228,000.)',
    },
}

# Read the seed file
with open('/sessions/adoring-brave-ptolemy/mnt/mcq_app/seed_national_ca_2026_mcq.py', 'r', encoding='utf-8') as f:
    content = f.read()

# Find all MCQ 31726-31775 and update them
# Pattern to match MCQ tuple structure
pattern = r'\(\s*(31(?:726|727|728|729|730|731|732|733|735|736|737|738|739|740|741|742|744|745|746|747|750|751|754|755|756|757|758|759|760|761|762|763|764|765|766|768|769|770|771|772|773|774|775)),\s*\'([^\']*?)\',\s*((?:\'[^\']*?\',\s*){4})\'([A-D])\',\s*"([^"]*?)",\s*\'([^\']*?)\',\s*\'([^\']*?)\'\)'

# Count matches
matches = list(re.finditer(pattern, content, re.DOTALL))
print(f"Total MCQs matching pattern: {len(matches)}")

# Show sample of what will be updated
if matches:
    for i, match in enumerate(matches[:3]):
        mcq_id = match.group(1)
        question = match.group(2)[:80]
        print(f"MCQ {mcq_id}: {question}...")

print("\nTask: Add Telugu translations to MCQs 31726-31775")
print("Current status: MCQs are in English-only format")
print("Required output: Bilingual Telugu\\nEnglish format")
