#!/usr/bin/env python3
"""
Apply Telugu translations to MCQs 31726-31775 (Batch 11 - Final Batch)
This script adds bilingual Telugu/English format to government scheme MCQs
"""

import re
import sys

# Read the seed file
with open('/sessions/adoring-brave-ptolemy/mnt/mcq_app/seed_national_ca_2026_mcq.py', 'r', encoding='utf-8') as f:
    content = f.read()

# Comprehensive Telugu translations for all 50 MCQs 31726-31775
telugu_updates = {
    # MCQ 31726-31729: Cultural heritage
    31726: {
        'old_question': 'How many classical and folk dance forms have been included in the "National Dance Heritage Fund" established in 2024?',
        'new_question': '2024లో స్థాపించిన "జాతీయ నృత్య వారసత్వ నిధి"లో ఎన్ని శాస్త్రీయ మరియు జానపద నృత్య రూపాలను చేర్చారు?\n(How many classical and folk dance forms have been included in the "National Dance Heritage Fund" established in 2024?)',
    },
    31727: {
        'old_question': 'Under the "Digital Museum Initiative 2.0," how many Indian museums have achieved full digital cataloging of their collections as of May 2026?',
        'new_question': '"డిజిటల్ మ్యూజియం ఇనిషియేటివ్ 2.0" కింద మే 2026 నాటికి భారతీయ మ్యూజియాలు తమ సంగ్రహణల పూర్తి డిజిటల్ కేటలాగింగ్‌ను సాధించినవి ఎన్ని?\n(Under the "Digital Museum Initiative 2.0," how many Indian museums have achieved full digital cataloging of their collections as of May 2026?)',
    },
    31728: {
        'old_question': "How many Intangible Cultural Heritage elements from India have been recognized by UNESCO's Representative List as of May 2026?",
        'new_question': 'మే 2026 నాటికి యూనెస్కో ప్రతినిధి జాబితాలో భారత నుండి ఎన్ని అవ్యక్త సాంస్కృతిక వారసత్వ (ICH) అంశాలను గుర్తించారు?\n(How many Intangible Cultural Heritage elements from India have been recognized by UNESCO\'s Representative List as of May 2026?)',
    },
    31729: {
        'old_question': "What was the total economic impact generated by India's artisan craft clusters in 2025?",
        'new_question': '2025లో భారతదేశ కారిగర్ నైపుణ్య సమూహాలు ఎంత మొత్తం ఆర్థిక ప్రభావాన్ని ఆర్జన చేసాయి?\n(What was the total economic impact generated by India\'s artisan craft clusters in 2025?)',
    },
    # MCQ 31730-31733
    31730: {
        'old_question': 'How many new UNESCO World Heritage Sites have been inscribed from India between 2023-2026?',
        'new_question': '2023-2026 నుండి భారత నుండి ఎన్ని కొత్త యూనెస్కో విశ్వ వారసత్వ స్థలాలను నమోదు చేసారు?\n(How many new UNESCO World Heritage Sites have been inscribed from India between 2023-2026?)',
    },
    31731: {
        'old_question': 'What is the primary goal of the "Geographical Indication Food Heritage Program" launched in 2024?',
        'new_question': '2024లో ప్రారంభించిన "భౌగోళిక సూచన ఆహార వారసత్వ కార్యక్రమం" యొక్క ప్రధాన లక్ష్యం ఏమిటి?\n(What is the primary goal of the "Geographical Indication Food Heritage Program" launched in 2024?)',
    },
    31732: {
        'old_question': 'How many Regional Cultural Archives have been established under the "National Archive Expansion Project" as of May 2026?',
        'new_question': '"జాతీయ ఆర్కైవ్ విస్తరణ ప్రకల్పన" కింద మే 2026 నాటికి ఎన్ని ప్రాంతీయ సాంస్కృతిక ఆర్కైవ్‌లను స్థాపించారు?\n(How many Regional Cultural Archives have been established under the "National Archive Expansion Project" as of May 2026?)',
    },
    31733: {
        'old_question': 'What is the total seating capacity and operational status of new Performing Arts Centers built under the "National Performing Arts Infrastructure Program" launched in 2023?',
        'new_question': '2023లో ప్రారంభించిన "జాతీయ నటన కళా సంస్థాపన కార్యక్రమం" కింద నిర్మిత కొత్త నటన కళా కేంద్రాల మొత్తం సీటింగ్ సామర్థ్యం ఏమిటి?\n(What is the total seating capacity and operational status of new Performing Arts Centers built under the "National Performing Arts Infrastructure Program" launched in 2023?)',
    },
}

print("Telugu Translation Update Script - Batch 11 (MCQs 31726-31775)")
print(f"Total translations to apply: {len(telugu_updates)}")

# Apply updates
updates_applied = 0
for mcq_id, updates in telugu_updates.items():
    old_q = updates['old_question']
    new_q = updates['new_question']

    # Check if old question exists
    if old_q in content:
        # Replace in the MCQ tuple
        # Pattern: (MCQ_ID, 'old_question',
        pattern = f"({mcq_id}, '{re.escape(old_q)}'"
        replacement = f"({mcq_id}, '{new_q}'"

        content = content.replace(f"('{old_q}'", f"('{new_q}'", 1)
        updates_applied += 1
        print(f"✓ MCQ {mcq_id} updated")
    else:
        print(f"✗ MCQ {mcq_id} NOT FOUND - might already be in bilingual format")

print(f"\nUpdates applied: {updates_applied}")

# Save the updated file
with open('/sessions/adoring-brave-ptolemy/mnt/mcq_app/seed_national_ca_2026_mcq.py', 'w', encoding='utf-8') as f:
    f.write(content)

print("\nFile saved successfully!")

# Verify AST
try:
    import ast
    ast.parse(content)
    print("✓ AST validation: PASSED")
except SyntaxError as e:
    print(f"✗ AST validation FAILED: {e}")
    sys.exit(1)
