"""Archive of 520 deleted National CA MCQs — May 2026 curation
Original file: seed_national_ca_2026_mcq.py (791 → 249)
"""

DELETED_NATL_MCQS = [
    {"id":31002,"question_text":'2026-27 కేంద్ర బడ్జెట్\u200cలో మొత్తం వ్యయం ఎంత?n(What is the total expenditure in Un',"answer":"B"},
    {"id":31003,"question_text":'2026-27 కేంద్ర బడ్జెట్\u200cలో మూలధన వ్యయం (Capital Expenditure) ఎంత?n(Capital Expend',"answer":"C"},
    {"id":31005,"question_text":'2026-27 కేంద్ర బడ్జెట్\u200cలో రక్షణ రంగానికి కేటాయింపు ఎంత?n(Defence allocation in U',"answer":"B"},
    {"id":31006,"question_text":'2026-27 కేంద్ర బడ్జెట్\u200cలో రైల్వేలకు కేటాయింపు ఎంత?n(Railways allocation in Union',"answer":"B"},
    {"id":31008,"question_text":"భారత 77వ గణతంత్ర దినోత్సవం ఎప్పుడు జరిగింది?n(India's 77th Republic Day was cele","answer":"A"},
    {"id":31013,"question_text":"2025-26లో భారత GDP వాస్తవ వృద్ధి రేటు ఎంత (MoSPI 2వ అగ్రిమ అంచనా)?n(India's real","answer":"D"},
    {"id":31014,"question_text":'జాతీయ కుటుంబ ఆరోగ్య సర్వే (NFHS) ప్రకారం భారత మొత్తం సంతానోత్పత్తి రేటు (TFR) ఎం',"answer":"B"},
    {"id":31017,"question_text":'WAVES 2025 సమ్మేళనం థీమ్ ఏమిటి?n(What was the theme of WAVES 2025 summit?)',"answer":"B"},
    {"id":31018,"question_text":'డిసెంబర్ 2025లో పరీక్షించిన ప్రృథ్వీ-3 క్షిపణి పరిధి ఎంత?n(Range of Prithvi-3 mi',"answer":"C"},
    {"id":31021,"question_text":'MILAN 2026లో ఎన్ని దేశాలు పాల్గొన్నాయి?n(How many countries participated in MILA',"answer":"C"},
    {"id":31023,"question_text":'మార్చి 2026లో భారత్ పర్యటించిన బ్రెజిల్ అధ్యక్షుడు ఎవరు?n(Which Brazilian Presid',"answer":"B"},
    {"id":31025,"question_text":'ఆర్టెమిస్-2 మిషన్\u200cలో ఎంత మంది వ్యోమగాములు ఉన్నారు?n(How many astronauts were in ',"answer":"C"},
    {"id":31028,"question_text":'2026 నాటికి భారత్\u200cలో సోషల్ మీడియా వినియోగదారుల సంఖ్య దాదాపు ఎంత?n(Approximate nu',"answer":"B"},
    {"id":31031,"question_text":'2026లో AICTE (All India Council for Technical Education) కింద ఎన్ని సంస్థలు ఉన్న',"answer":"C"},
    {"id":31032,"question_text":'భారత ఆర్థిక సర్వే 2025-26 ప్రకారం వ్యవసాయ రంగం వృద్ధి రేటు 2024-25లో ఎంత?n(Agric',"answer":"C"},
    {"id":31035,"question_text":'2026 ఫిబ్రవరిలో ఇజ్రాయెల్-హమాస్ మధ్య కుదిరిన కాల్పుల విరమణ ఒప్పందంలో మధ్యవర్తిత్',"answer":"B"},
    {"id":31036,"question_text":'2026 నాటికి భారత్\u200cలో ఇంటర్నెట్ వినియోగదారులు దాదాపు ఎంత మంది?n(Approximate inter',"answer":"D"},
    {"id":31039,"question_text":'2024 POCSO (లైంగిక నేరాల నిరోధక చట్టం) కేసులు భారతదేశవ్యాప్తంగా దాదాపు ఎన్ని నమో',"answer":"C"},
    {"id":31040,"question_text":'SCO (Shanghai Cooperation Organisation) 2025 శిఖర సమ్మేళనం థీమ్ ఏమిటి?n(What was',"answer":"A"},
    {"id":31041,"question_text":'UGC (University Grants Commission) ఆన్\u200cలైన్ డిగ్రీలను గుర్తించే నిర్ణయం ఏ సంవత్స',"answer":"C"},
    {"id":31042,"question_text":"2025-26లో భారత వినియోగ ధర సూచిక (CPI) ద్రవ్యోల్బణం లక్ష్యం ఎంత?n(India's CPI inf","answer":"B"},
    {"id":31044,"question_text":'2026-27 కేంద్ర బడ్జెట్\u200cలో వ్యవసాయ రంగానికి కేటాయింపు ఎంత?n(Agriculture allocatio',"answer":"B"},
    {"id":31045,"question_text":'నేషనల్ లాజిస్టిక్స్ పాలసీ (NLP) ప్రధాన లక్ష్యం ఏమిటి?n(Main objective of Nationa',"answer":"B"},
    {"id":31046,"question_text":'2025-26లో రష్యా-ఉక్రెయిన్ యుద్ధ స్థితి ఏమిటి?n(Status of Russia-Ukraine war in 2',"answer":"C"},
    {"id":31049,"question_text":'ISRO జనవరి 2025లో NavIC constellation బలోపేతం కోసం ప్రయోగించిన NVS శ్రేణి ఉపగ్రహ',"answer":"B"},
    {"id":31052,"question_text":"భారత ప్రభుత్వం 2025-26లో ఏ పథకం ద్వారా 'PM ఆవాస్ యోజన'లో నిరుపేదలకు ఇళ్లు కట్టిం","answer":"A"},
    {"id":31054,"question_text":'భారత జనాభా గణన (Census) ఏ సంవత్సరానికి ప్లాన్ చేయబడింది?n(India Census planned f',"answer":"B"},
    {"id":31055,"question_text":'2026-27 కేంద్ర బడ్జెట్\u200cలో ఆరోగ్య రంగానికి కేటాయింపు ఎంత?n(Health sector allocati',"answer":"B"},
    {"id":31056,"question_text":'2026-27 కేంద్ర బడ్జెట్\u200cలో గ్రామీణాభివృద్ధికి కేటాయింపు ఎంత?n(Rural Development a',"answer":"B"},
    {"id":31059,"question_text":'2026లో NIA (నేషనల్ ఇన్వెస్టిగేషన్ ఏజెన్సీ) డైరెక్టర్ జనరల్ ఎవరు?n(Who is the DG ',"answer":"B"},
    {"id":31060,"question_text":'NMC (నేషనల్ మెడికల్ కమిషన్) ఏ సంవత్సరం MCI స్థానంలో వచ్చింది?n(NMC replaced MCI ',"answer":"B"},
    {"id":31072,"question_text":"2026-27 కేంద్ర బడ్జెట్\u200cలో 'డిజిటల్ ఇండియా' కింద ఏ కొత్త పథకం ప్రకటించారు?n(New s","answer":"A"},
    {"id":31073,"question_text":'2025-26లో హూతీ తిరుగుబాటుదారులు ఏ సముద్ర మార్గంలో నౌకలపై దాడులు చేశారు?n(Which s',"answer":"B"},
    {"id":31074,"question_text":'2026 జనవరిలో భారత పార్లమెంట్ బడ్జెట్ సమావేశం ఎప్పుడు ప్రారంభమైంది?n(When did Ind',"answer":"C"},
    {"id":31076,"question_text":"2025 CPI (Corruption Perceptions Index) లో భారత్ స్థానం ఎంత?n(India's rank in CP","answer":"C"},
    {"id":31079,"question_text":'IONS (Indian Ocean Naval Symposium) 2026 ఎక్కడ జరిగింది?n(Where was IONS 2026 he',"answer":"C"},
    {"id":31083,"question_text":'2026-27 కేంద్ర బడ్జెట్\u200cలో మధ్యతరగతికి ఆదాయపు పన్ను శ్లాబులు ఏ రేటులో ఉన్నాయి (కొ',"answer":"B"},
    {"id":31084,"question_text":'2026-27 బడ్జెట్\u200cలో స్టార్టప్\u200cలకు పన్ను సెలవు కాలం ఎంత?n(Tax holiday period for s',"answer":"D"},
    {"id":31085,"question_text":'2026-27 బడ్జెట్\u200cలో పీఎం ఆవాస్ యోజన (గ్రామీణ్) కింద ఇళ్ల నిర్మాణ లక్ష్యం ఎంత?n(Ho',"answer":"B"},
    {"id":31086,"question_text":'2026-27 బడ్జెట్\u200cలో బీమా రంగంలో FDI పరిమితి ఎంత?n(FDI limit in insurance sector i',"answer":"C"},
    {"id":31087,"question_text":'2026-27 బడ్జెట్\u200cలో ముద్రా యోజన కింద రుణ పరిమితి ఎంత?n(Loan limit under Mudra Yoj',"answer":"C"},
    {"id":31107,"question_text":'2024 T20 ప్రపంచ కప్ ఎక్కడ జరిగింది?n(Where was the 2024 T20 World Cup held?)',"answer":"B"},
    {"id":31113,"question_text":'UPI (Unified Payments Interface) జనవరి 2026లో నెలవారీ లావాదేవీలు ఎంత?n(UPI month',"answer":"C"},
    {"id":31119,"question_text":"2024-25లో భారత్ విదేశీ మారక నిల్వలు గరిష్టంగా ఎంతకు చేరాయి?n(India's forex reser","answer":"C"},
    {"id":31120,"question_text":"2025-26లో భారత్ ప్రత్యక్ష విదేశీ పెట్టుబడులు (FDI) ఎంత?n(India's FDI inflows in ","answer":"B"},
    {"id":31122,"question_text":'భారత్ 2025లో ఏ దేశాన్ని అధిగమించి 4వ అతిపెద్ద ఆర్థిక వ్యవస్థగా ఎదిగే లక్ష్యం ఉంద',"answer":"B"},
    {"id":31135,"question_text":"2025 World Press Freedom Index లో భారత్ స్థానం ఎంత?n(India's rank in World Press","answer":"C"},
    {"id":31136,"question_text":'World Bank చివరి (DB-2020) Ease of Doing Business Index లో భారత్ స్థానం ఎంత?n(In',"answer":"B"},
    {"id":31137,"question_text":"2025 Global Peace Index లో భారత్ స్థానం ఎంత?n(India's rank in Global Peace Index","answer":"B"},
    {"id":31138,"question_text":'PM గరీబ్ కళ్యాణ్ అన్న యోజన (PMGKAY) లబ్ధిదారులు ఎంత మంది?n(Number of beneficiari',"answer":"B"},
    {"id":31141,"question_text":"2025-26లో భారత్ బొగ్గు ఉత్పత్తి లక్ష్యం ఎంత?n(India's coal production target for","answer":"B"},
    {"id":31146,"question_text":'PM E-DRIVE పథకం ఏ రంగానికి సంబంధించినది?n(PM E-DRIVE scheme is related to which ',"answer":"A"},
    {"id":31147,"question_text":'PM ఉజ్వల యోజన కింద 2025 నాటికి ఎంత మంది LPG కనెక్షన్లు పొందారు?n(Number of LPG c',"answer":"C"},
    {"id":31148,"question_text":'POSHAN 2.0 మిషన్ లక్ష్యం ఏమిటి?n(Goal of POSHAN 2.0 Mission?)',"answer":"A"},
    {"id":31149,"question_text":"భారత్ విదేశీ రుణం (External Debt) 2025లో ఎంత?n(India's External Debt in 2025?)","answer":"C"},
    {"id":31150,"question_text":"భారత్ ప్రతి రోజు సగటున ఎంత కి.మీ. జాతీయ రహదారులు నిర్మిస్తోంది?n(India's average","answer":"C"},
    {"id":31152,"question_text":'2024-25లో భారత్ ఆహార ధాన్యాల ఉత్పత్తి రికార్డు ఎంత?n(Record food grain productio',"answer":"C"},
    {"id":31153,"question_text":'2025లో భారత-అమెరికా ద్వైపాక్షిక వాణిజ్యం ఎంత?n(India-USA bilateral trade in 2025',"answer":"C"},
    {"id":31155,"question_text":"భారత్ ప్రపంచ జెనెరిక్ ఔషధ ఉత్పత్తిలో ఏ స్థానంలో ఉంది?n(India's rank in global ge","answer":"A"},
    {"id":31156,"question_text":"భారత్ ఉక్కు ఉత్పత్తిలో ప్రపంచంలో ఏ స్థానంలో ఉంది?n(India's rank in world steel p","answer":"B"},
    {"id":31159,"question_text":'2025-26లో AIIMS (All India Institute of Medical Sciences) మొత్తం సంఖ్య ఎంత?n(Tot',"answer":"C"},
    {"id":31160,"question_text":'2026-27 కేంద్ర బడ్జెట్\u200cలో ఆయుష్మాన్ భారత్ 70+ సీనియర్ సిటిజన్లకు ఆరోగ్య కవరేజి క',"answer":"D"},
    {"id":31161,"question_text":"భారత్ పాల ఉత్పత్తిలో ప్రపంచంలో ఏ స్థానంలో ఉంది?n(India's rank in world milk prod","answer":"A"},
    {"id":31163,"question_text":"భారత్ చేపల ఉత్పత్తిలో ప్రపంచంలో ఏ స్థానంలో ఉంది?n(India's rank in world fisherie","answer":"C"},
    {"id":31164,"question_text":'DigiYatra పథకం ఏ రంగానికి సంబంధించినది?n(DigiYatra scheme is related to which se',"answer":"B"},
    {"id":31169,"question_text":"భారత జనాభా గణన (Census 2011) ప్రకారం భారత జనాభా ఎంత?n(India's population as per ","answer":"B"},
    {"id":31171,"question_text":'భారత్ InSPACe (Indian National Space Promotion and Authorisation Centre) ఏ కార్య',"answer":"B"},
    {"id":31173,"question_text":"2024-25లో భారత అక్షరాస్యత రేటు ఎంత?n(India's literacy rate in 2024-25?)","answer":"C"},
    {"id":31175,"question_text":'జల్ జీవన్ మిషన్ కింద 2025 నాటికి కవర్ చేయబడిన గ్రామీణ గృహాల శాతం ఎంత?n(Percentag',"answer":"D"},
    {"id":31176,"question_text":'2025 నాటికి భారత్\u200cలో ప్రభుత్వ రంగ బ్యాంకుల (PSBs) సంఖ్య ఎంత?n(Number of Public S',"answer":"C"},
    {"id":31178,"question_text":"భారత్ అణు విద్యుత్ సామర్థ్యం 2026 నాటికి ఎంత?n(India's nuclear power capacity by","answer":"C"},
    {"id":31179,"question_text":'2025 Transparency International CPI (Corruption Perceptions Index) లో స్కోర్ ఎంత',"answer":"B"},
    {"id":31181,"question_text":'PM గతిశక్తి మాస్టర్ ప్లాన్ ముఖ్య లక్ష్యం ఏమిటి?n(Main goal of PM GatiShakti Mast',"answer":"B"},
    {"id":31182,"question_text":'2025లో భారత-రష్యా వార్షిక ద్వైపాక్షిక వాణిజ్యం ఎంత?n(India-Russia annual bilater',"answer":"B"},
    {"id":31185,"question_text":'PM మోడీ 2024 జూన్\u200cలో 3వ సారి PM పదవి చేపట్టిన తర్వాత అత్యంత సీనియర్ మంత్రులు ఎవర',"answer":"B"},
    {"id":31187,"question_text":'2026-27 కేంద్ర బడ్జెట్\u200cలో జాతీయ రహదారులకు కేటాయింపు ఎంత?n(National Highways allo',"answer":"D"},
    {"id":31188,"question_text":'భారత అంతరిక్ష కేంద్రం (BAS - Bharatiya Antariksh Station) 2035 నాటికి నిర్మించాల',"answer":"C"},
    {"id":31189,"question_text":'2025-26లో కేంద్ర ప్రభుత్వం వ్యవసాయ రుణ లక్ష్యం ఎంత?n(Agricultural credit target ',"answer":"B"},
    {"id":31190,"question_text":"భారత్ 2024-25 లో మొత్తం విద్యుత్ ఉత్పత్తి సామర్థ్యం ఎంత?n(India's total electric","answer":"A"},
    {"id":31192,"question_text":'SCO (Shanghai Cooperation Organisation) కి భారత్ ఎప్పుడు చేరింది?n(When did Indi',"answer":"B"},
    {"id":31193,"question_text":"IFFCO యొక్క నానో యూరియా ఏ రూపంలో ఉంటుంది?n(In what form is IFFCO's Nano Urea?)","answer":"B"},
    {"id":31194,"question_text":'2025 నాటికి Aadhaar కార్డులు నమోదైన భారత పౌరుల సంఖ్య ఎంత?n(Number of Indians enr',"answer":"C"},
    {"id":31195,"question_text":"భారత్ చైనాతో సరిహద్దు పొడవు ఎంత?n(Length of India's border with China?)","answer":"B"},
    {"id":31203,"question_text":'మహా కుంభ మేళా 2025లో సుమారు ఎంత మంది భక్తులు పాల్గొన్నారు?n(Approximate number o',"answer":"C"},
    {"id":31206,"question_text":'NEP 2020 కింద మాతృభాషలో బోధన ఏ తరగతి వరకు తప్పనిసరి?n(Mother tongue medium of in',"answer":"B"},
    {"id":31208,"question_text":'2026-27 బడ్జెట్\u200cలో రూ.24 లక్షలకు పైగా ఆదాయంపై కొత్త పన్ను పద్ధతిలో రేటు ఎంత?n(Ta',"answer":"B"},
    {"id":31209,"question_text":"2024-25లో భారత వస్తు ఎగుమతులు ఎంత?n(India's merchandise exports in 2024-25?)","answer":"B"},
    {"id":31211,"question_text":"2025-26లో భారత్ వ్యాపార లోటు (Trade Deficit) ఎంత?n(India's trade deficit in 2025","answer":"C"},
    {"id":31214,"question_text":'DRDO Pinaka రాకెట్ లాంచ్ వ్యవస్థ ఏ రకానికి చెందింది?n(Pinaka rocket system by DR',"answer":"B"},
    {"id":31216,"question_text":'భారతీయ సాక్ష్య అధినియమ్ (BSA) ఏ చట్టాన్ని భర్తీ చేసింది?n(Bharatiya Sakshya Adhi',"answer":"C"},
    {"id":31218,"question_text":'PM కుసుమ్ యోజన ఏ రంగానికి సంబంధించినది?n(PM KUSUM scheme is related to which sec',"answer":"B"},
    {"id":31219,"question_text":'2026-27 బడ్జెట్\u200cలో PM జన ఆరోగ్య యోజన (AB-PMJAY) కింద 70+ సీనియర్ సిటిజన్లకు ఎంత ',"answer":"B"},
    {"id":31222,"question_text":'PM ఫసల్ బీమా యోజన (PMFBY) ఏ రంగానికి సంబంధించింది?n(PM Fasal Bima Yojana relates',"answer":"B"},
    {"id":31223,"question_text":'స్కిల్ ఇండియా మిషన్ 2026-27 బడ్జెట్\u200cలో కేటాయింపు ఎంత?n(Skill India Mission alloc',"answer":"B"},
    {"id":31224,"question_text":'ONDC (Open Network for Digital Commerce) ఏ మంత్రిత్వ శాఖ చొరవతో ప్రారంభించారు?n(',"answer":"B"},
    {"id":31227,"question_text":'2025 నాటికి PM-ABHIM (Ayushman Bharat Health Infrastructure Mission) కింద నిర్మి',"answer":"C"},
    {"id":31229,"question_text":'2030 నాటికి భారత వాహన అమ్మకాల్లో ఎలక్ట్రిక్ వాహనాల లక్ష్య శాతం ఎంత?n(Target EV p',"answer":"C"},
    {"id":31230,"question_text":"2025-26లో భారత తలసరి ఆదాయం (Nominal GDP per capita) ఎంత?n(India's nominal GDP pe","answer":"C"},
    {"id":31232,"question_text":'భారత్\u200cలో 2047 నాటికి జనాభా స్థిరీకరణ (Population stabilization) సాధించాలని ఏ నివ',"answer":"B"},
    {"id":31233,"question_text":'స్వచ్ఛ భారత్ మిషన్ (గ్రామీణ్) ఫేజ్-2 కింద ODF Plus గ్రామాల లక్ష్యం?n(ODF Plus vi',"answer":"B"},
    {"id":31236,"question_text":'BharatNet ప్రాజెక్ట్ లక్ష్యం ఏమిటి?n(Goal of BharatNet project?)',"answer":"B"},
    {"id":31237,"question_text":'PM MITRA (Mega Integrated Textile Region and Apparel Parks) పథకం ఏ రంగానికి?n(PM',"answer":"B"},
    {"id":31238,"question_text":'Sagarmala ప్రాజెక్ట్ ఏ రంగాన్ని లక్ష్యంగా పెట్టుకుంది?n(Sagarmala Project focuse',"answer":"B"},
    {"id":31239,"question_text":'2025 శాంతి స్వరూప్ భట్నాగర్ పురస్కారం ఏ రంగంలో ఇస్తారు?n(Shanti Swarup Bhatnagar',"answer":"B"},
    {"id":31240,"question_text":'CAQM (Commission for Air Quality Management) ఏ ప్రాంతానికి సంబంధించినది?n(CAQM r',"answer":"B"},
    {"id":31241,"question_text":'PSLV-C60 మిషన్ SpaDeX ఏ రాకెట్ నిర్మించింది?n(Which launch vehicle was used for ',"answer":"B"},
    {"id":31243,"question_text":'MSME రంగంలో Micro enterprise పరిమితులు (Investment) ఏమిటి?n(Investment limits fo',"answer":"B"},
    {"id":31245,"question_text":'2025 నాటికి భారత హైకోర్టుల సంఖ్య ఎంత?n(Number of High Courts in India by 2025?)',"answer":"B"},
    {"id":31247,"question_text":'జాతీయ మౌలిక సదుపాయాల పైప్\u200cలైన్ (NIP) 2019-2025 మొత్తం పెట్టుబడి ఎంత?n(Total inve',"answer":"B"},
    {"id":31250,"question_text":'2026 నాటికి భారత్\u200cలో 5G వినియోగదారుల సంఖ్య ఎంత?n(Number of 5G users in India by ',"answer":"C"},
    {"id":31252,"question_text":'2024 భారత EV నీతి కింద దిగుమతి చేసుకున్న EV లపై సుంకం ఎంత తగ్గించారు?n(Reduction',"answer":"B"},
    {"id":31253,"question_text":"PMEGP (Prime Minister's Employment Generation Programme) ఏ రంగాన్ని లక్ష్యంగా చే","answer":"C"},
    {"id":31254,"question_text":'NJDG (National Judicial Data Grid) ఏ కోసం ఉపయోగిస్తారు?n(NJDG is used for what p',"answer":"B"},
    {"id":31256,"question_text":"PM CARES (Prime Minister's Citizen Assistance and Relief in Emergency Situations","answer":"C"},
    {"id":31257,"question_text":"2026-27 కేంద్ర బడ్జెట్\u200cలో 'స్వర్ణ భారత్' ప్రాజెక్ట్ కింద బంగారం దిగుమతి సుంకం ఎం","answer":"B"},
    {"id":31258,"question_text":'2025-26లో MSP (Minimum Support Price) రైతులకు వ్యవసాయ పంటలకు పెంపు మొత్తం ఎంత?n(',"answer":"C"},
    {"id":31259,"question_text":'PM మోడీ Modi 3.0 (2024-) కేంద్ర మంత్రివర్గంలో మహిళా మంత్రుల సంఖ్య ఎంత (Cabinet r',"answer":"B"},
    {"id":31260,"question_text":'2026-27 బడ్జెట్\u200cలో అణు విద్యుత్ రంగానికి ముఖ్యమైన ప్రకటన ఏమిటి?n(Key announcemen',"answer":"B"},
    {"id":31261,"question_text":'PM ఆశ (PM Annadata Aay Sanrakshan Abhiyan) పథకం ఏమిటి?n(What is PM AASHA scheme?',"answer":"B"},
    {"id":31262,"question_text":'DRISHTI (Digital Recording for Intelligent Surveillance and Tactical Intelligenc',"answer":"B"},
    {"id":31263,"question_text":'PM మత్స్య సంపద యోజన (PMMSY) ఏ రంగానికి?n(PM Matsya Sampada Yojana is for which s',"answer":"B"},
    {"id":31264,"question_text":'2026-27 బడ్జెట్\u200cలో పెట్టుబడుల ఉపసంహరణ (Disinvestment) లక్ష్యం ఎంత?n(Disinvestmen',"answer":"C"},
    {"id":31265,"question_text":'2026-27 బడ్జెట్\u200cలో మహిళలు, పిల్లల అభివృద్ధికి (WCD) కేటాయింపు ఎంత?n(WCD allocati',"answer":"B"},
    {"id":31267,"question_text":'2026-27 బడ్జెట్\u200cలో టెలికమ్యూనికేషన్ రంగానికి కేటాయింపు ఎంత?n(Telecom sector allo',"answer":"C"},
    {"id":31268,"question_text":'2025 నాటికి NRLM (National Rural Livelihoods Mission) కింద స్వయం సహాయక బృందాల సం',"answer":"B"},
    {"id":31269,"question_text":'2026-27 బడ్జెట్\u200cలో ఈశాన్య రాష్ట్రాల అభివృద్ధికి కేటాయింపు ఎంత?n(North East state',"answer":"B"},
    {"id":31270,"question_text":"భారత్ ప్రపంచ మైకా ఉత్పత్తిలో స్థానం ఎంత?n(India's rank in world Mica production?","answer":"A"},
    {"id":31271,"question_text":'ONDC (Open Network for Digital Commerce) 2026 నాటికి ఎంత మంది వినియోగదారులకు సేవ',"answer":"C"},
    {"id":31272,"question_text":'భారత సహకార మంత్రిత్వ శాఖ ఏ సంవత్సరం ఏర్పాటు అయింది?n(Ministry of Cooperation est',"answer":"B"},
    {"id":31274,"question_text":'WPI (Wholesale Price Index) ద్రవ్యోల్బణం 2025-26లో సగటు ఎంత?n(Average WPI inflat',"answer":"B"},
    {"id":31275,"question_text":"2025-26లో భారత పెట్రోలియం దిగుమతి ఎంత?n(India's petroleum imports in 2025-26?)","answer":"B"},
    {"id":31276,"question_text":'2025 నాటికి భారత్\u200cలో పౌష్టికాహార లోపం (Undernutrition) 5 సంవత్సరాల లోపు పిల్లల్ల',"answer":"B"},
    {"id":31277,"question_text":"భారత్ ఉద్యానవన ఉత్పత్తి (Horticulture Production) 2024-25లో ఎంత?n(India's hortic","answer":"B"},
    {"id":31278,"question_text":'Axiom Space Mission 4 (Ax-4) లో పాల్గొన్న భారత వ్యోమగామి ఎవరు?n(Indian astronaut',"answer":"C"},
    {"id":31279,"question_text":'SECI (Solar Energy Corporation of India) ఏ రంగంలో పని చేస్తుంది?n(SECI works in ',"answer":"B"},
    {"id":31280,"question_text":"EPFO (Employees' Provident Fund Organisation) FY 2024-25 వడ్డీ రేటు ఎంత?n(EPFO i","answer":"C"},
    {"id":31281,"question_text":'IRDAI (Insurance Regulatory and Development Authority of India) ఛైర్మన్ 2025లో ఎ',"answer":"B"},
    {"id":31282,"question_text":'National Health Policy (NHP) 2017 ప్రకారం 2025 నాటికి ప్రభుత్వ ఆరోగ్య వ్యయాన్ని ',"answer":"C"},
    {"id":31283,"question_text":'Coal India Ltd (CIL) ప్రపంచంలో అతిపెద్ద బొగ్గు ఉత్పత్తి కంపెనీ. ఇది 2024-25లో ఎం',"answer":"C"},
    {"id":31284,"question_text":'NALSA (National Legal Services Authority) ఏమిటి?n(What is NALSA?)',"answer":"B"},
    {"id":31285,"question_text":'ISRO OneWeb ఒప్పందం కింద LVM3-M2 (2022) + LVM3-M3 (2023) — ప్రతి మిషన్\u200cలో ఎన్ని ',"answer":"A"},
    {"id":31286,"question_text":'e-NAM (National Agriculture Market) పోర్టల్ రైతులకు ఎలా సహాయపడుతుంది?n(How does ',"answer":"B"},
    {"id":31287,"question_text":"2026-27 బడ్జెట్\u200cలో 'స్టార్టప్ ఇండియా' కింద ఏ నిధి ప్రకటించారు?n(Fund announced u","answer":"B"},
    {"id":31288,"question_text":'2025 Sahitya Akademi Award (English) ఎవరికి వచ్చింది?n(Who won Sahitya Akademi A',"answer":"B"},
    {"id":31289,"question_text":"2025-26 నాటికి భారత జాతీయ ఆదాయం (National Income) ఎంత?n(India's National Income ","answer":"C"},
    {"id":31290,"question_text":'భారతీయ అంతరిక్ష స్టేషన్ (BAS) నిర్మాణ ప్రణాళిక ఎన్ని modules లో ఉంది?n(Bharatiya',"answer":"C"},
    {"id":31291,"question_text":'National Agriculture Market (eNAM) 2026 నాటికి ఎన్ని మండీలు కలిపింది?n(How many ',"answer":"C"},
    {"id":31295,"question_text":'భారత్ SEZ (Special Economic Zone) లో ఎగుమతులు 2024-25లో ఎంత?n(Exports from India',"answer":"B"},
    {"id":31298,"question_text":'2026-27 బడ్జెట్\u200cలో PSU (Public Sector Undertakings) కు మూలధన కేటాయింపు ఎంత?n(Cap',"answer":"C"},
    {"id":31302,"question_text":'2026-27 కేంద్ర బడ్జెట్\u200cలో మొత్తం వ్యయం ఎంత?n(Total expenditure in Union Budget 2',"answer":"B"},
    {"id":31303,"question_text":'2026-27 బడ్జెట్\u200cలో మూలధన వ్యయం (Capex) ఎంత?n(Capital expenditure (Capex) in Budg',"answer":"C"},
    {"id":31304,"question_text":'2026-27 బడ్జెట్\u200cలో GDP వృద్ధి అంచనా ఎంత? ద్రవ్యలోటు ఎంత?n(GDP growth estimate an',"answer":"B"},
    {"id":31305,"question_text":'2026-27 బడ్జెట్\u200cలో రక్షణ రంగానికి ఎంత కేటాయించారు? గత ఏడాది కంటే ఎంత పెరుగుదల?n(',"answer":"B"},
    {"id":31306,"question_text":'2026-27 బడ్జెట్\u200cలో విద్యా రంగం, ఆరోగ్య రంగం కేటాయింపులు?n(Education and Health a',"answer":"B"},
    {"id":31307,"question_text":'2026-27 బడ్జెట్\u200cలో రైల్వేలకు, రోడ్లు రవాణాకు ఎంత కేటాయించారు?n(Railways and Road',"answer":"B"},
    {"id":31308,"question_text":'2026-27 బడ్జెట్\u200cలో ఇస్రోకు ఎంత కేటాయించారు?n(ISRO allocation in Budget 2026-27?)',"answer":"C"},
    {"id":31312,"question_text":"16వ ఆర్థిక సంఘం ప్రవేశపెట్టిన 'Urbanization Premium' నిధి ఎంత?n(Urbanization Pre","answer":"B"},
    {"id":31315,"question_text":'ICC U-19 పురుషుల క్రికెట్ ప్రపంచకప్ 2026 ఫైనల్ ఎప్పుడు, ఎక్కడ జరిగింది?n(ICC U-1',"answer":"B"},
    {"id":31316,"question_text":'U-19 ప్రపంచకప్ 2026 ఫైనల్\u200cలో భారత్ ఇంగ్లాండ్\u200cపై ఎన్ని పరుగుల తేడాతో గెలిచింది? భ',"answer":"B"},
    {"id":31317,"question_text":'U-19 ప్రపంచకప్ 2026లో 14 ఏళ్ళ 316 రోజుల వయసులో ఫైనల్\u200cలో 175 పరుగులు చేసి Player ',"answer":"C"},
    {"id":31319,"question_text":'77వ గణతంత్ర దినోత్సవం (Jan 26, 2026) ముఖ్య అతిథులు ఎవరు?n(Chief guests at 77th R',"answer":"B"},
    {"id":31320,"question_text":'77వ గణతంత్ర దినోత్సవ-2026 థీమ్ ఏమిటి?n(Theme of 77th Republic Day 2026?)',"answer":"C"},
    {"id":31325,"question_text":'2026లో ఎంతమందికి శౌర్య చక్రాలు ప్రకటించారు?n(How many Shaurya Chakras announced ',"answer":"C"},
    {"id":31326,"question_text":'2026 పద్మ అవార్డులు మొత్తం ఎంతమందికి ప్రకటించారు? ఎప్పుడు?n(Total Padma awards 2',"answer":"B"},
    {"id":31331,"question_text":'BlueBird Block-2 ఉపగ్రహ ప్రయోగానికి సంబంధించి ప్రత్యేకత ఏమిటి?n(What was special',"answer":"A"},
    {"id":31332,"question_text":'LVM3-M6 ప్రయోగ స్థలం ఎక్కడ ఉంది? ఏ రాష్ట్రంలో?n(LVM3-M6 launch site location and',"answer":"B"},
    {"id":31333,"question_text":'డిసెంబర్ 29, 2025న DAC ఆమోదించిన రక్షణ ఒప్పందాల మొత్తం విలువ ఎంత?n(Total value o',"answer":"B"},
    {"id":31334,"question_text":'మార్చి 27, 2026న DAC ఆమోదించిన రక్షణ ప్యాకేజీ విలువ ఎంత?n(DAC defence package ap',"answer":"C"},
    {"id":31338,"question_text":'Bharat-EU FTAతో పాటు ప్రకటించిన దీర్ఘకాలిక సహకార ఫ్రేమ్\u200cవర్క్ పేరు?n(Long-term c',"answer":"B"},
    {"id":31340,"question_text":'జనవరి 2026లో Modi-Merz ఇద్దరూ హాజరైన అంతర్జాతీయ గాలిపటాల ఉత్సవం (International K',"answer":"A"},
    {"id":31343,"question_text":'Jan 2026 భారత-UAE పర్యటనలో ఆమోదించిన ఆంధ్రప్రదేశ్/గుజరాత్ semicon project ఏది?n(',"answer":"A"},
    {"id":31344,"question_text":'భారత్-న్యూజిలాండ్ FTA చర్చలు ఎప్పుడు ముగిశాయి? ఎప్పుడు అధికారికంగా సంతకం జరిగింద',"answer":"A"},
    {"id":31345,"question_text":'NITI ఆయోగ్ నివేదిక (Dec 22, 2025) ప్రకారం 2024లో విదేశాల్లో చదువుకుంటున్న భారతీయ',"answer":"C"},
    {"id":31346,"question_text":'విదేశాలకు పంపే విద్యార్థుల సంఖ్యలో రాష్ట్రాల్లో మొదటి స్థానంలో ఉన్నది?n(Which st',"answer":"B"},
    {"id":31347,"question_text":'FAO Global Forest Resources Assessment (Oct 22, 2025) ప్రకారం అటవీ విస్తీర్ణంలో ',"answer":"C"},
    {"id":31348,"question_text":"FAO నివేదిక ప్రకారం వార్షిక అటవీ పెరుగుదలలో భారత్ ర్యాంక్?n(India's rank in annu","answer":"C"},
    {"id":31349,"question_text":'జనవరి 2, 2026న కేంద్రం ఆమోదించిన electronics components scheme విలువ, ప్రాజెక్టు',"answer":"B"},
    {"id":31350,"question_text":'Jan 2026 ఎలక్ట్రానిక్స్ కాంపోనెంట్స్ స్కీమ్ AP లో ఆమోదించబడిన కంపెనీలు?n(Compani',"answer":"B"},
    {"id":31351,"question_text":'Viksit Bharat Young Leaders Dialogue (VBYLD) 2026 ఎప్పుడు, ఎక్కడ జరిగింది? ఎవరి ',"answer":"A"},
    {"id":31352,"question_text":'కేంద్ర మంత్రిమండలి ఆమోదించిన SBFAS+SBDS shipbuilding scheme మొత్తం విలువ ఎంత?n(T',"answer":"C"},
    {"id":31353,"question_text":'SBFAS shipbuilding scheme కింద ప్రతి నౌకకు ఎంత శాతం ఆర్థిక సహాయం?n(Per-ship fina',"answer":"C"},
    {"id":31356,"question_text":'మార్చి 5, 2026 గవర్నర్ల పునర్వ్యవస్థీకరణలో పశ్చిమ బెంగాల్, తమిళనాడు గవర్నర్లు?n(',"answer":"A"},
    {"id":31359,"question_text":'మార్చి 14, 2026న విడుదలైన లడఖ్ ఉద్యమ నేత ఎవరు? ఎప్పటి నుండి NSA కింద నిర్బంధంలో ',"answer":"A"},
    {"id":31364,"question_text":'హైడ్రోజన్ ట్రెయిన్\u200cలో ఎన్ని కోచులు, గరిష్ఠ వేగం?n(Number of coaches and max spee',"answer":"C"},
    {"id":31368,"question_text":'Raisina Dialogue 2026 — ఇది ఎన్నవ ఎడిషన్?n(Raisina Dialogue 2026 was which editi',"answer":"C"},
    {"id":31369,"question_text":'ఫిబ్రవరి 19, 2026న ఢిల్లీలో FICCI నిర్వహించిన Critical Minerals Summit ఎన్నవది? ',"answer":"A"},
    {"id":31370,"question_text":'ఫిబ్రవరి 21, 2026న జరిగిన Goa Maritime Conclave ఎన్నవ ఎడిషన్? ప్రారంభించినది?n(E',"answer":"B"},
    {"id":31372,"question_text":'131వ రాజ్యాంగ సవరణ బిల్లు ముఖ్య లక్ష్యం ఏమిటి?n(Main objective of 131st Constitu',"answer":"A"},
    {"id":31374,"question_text":'Artemis-2 మిషన్\u200cలో చంద్ర కక్ష్యకు వెళ్ళిన మొదటి non-white astronaut ఎవరు? ఎంత దూ',"answer":"B"},
    {"id":31375,"question_text":'Artemis-2 మిషన్\u200cలో కెనడాకు చెందిన వ్యోమగామి ఎవరు?n(Canadian astronaut on Artemis',"answer":"B"},
    {"id":31384,"question_text":'ఏప్రిల్ 6, 2026న CEC జ్ఞానేశ్ కుమార్\u200cపై ఇంపీచ్\u200cమెంట్ నోటీసును ఎవరు తిరస్కరించారు',"answer":"C"},
    {"id":31385,"question_text":'2026లో NCERT కు మంజూరైన హోదా; CBSE 3-language policy ఏ తరగతి నుండి అమలు; మార్చి ',"answer":"B"},
    {"id":31386,"question_text":'ఫిబ్రవరి 5, 2026న ఏ US-Russia అణ్వాయుధ ఒప్పందం ముగిసింది? చర్చలు ఎక్కడ పునః ప్రా',"answer":"B"},
    {"id":31387,"question_text":'జనవరి 21-23, 2026న ఢిల్లీలో జరిగిన అతిపెద్ద ఎన్నికల నిర్వహణ సమావేశం ఏది? ఎన్ని ద',"answer":"B"},
    {"id":31388,"question_text":'2025-27 కాలానికి భారత్ ఏ సంస్థ ఛైర్మన్\u200cషిప్ స్వీకరించింది? ఎన్ని సంవత్సరాల తర్వా',"answer":"C"},
    {"id":31390,"question_text":'GST 2.0 (సెప్టెంబర్ 22, 2025) ప్రకటనను నిర్వహించిన ప్రధానమంత్రి భాషణ ఏ ఈవెంట్\u200cలో',"answer":"B"},
    {"id":31392,"question_text":'Income-tax Act 2025 — 1961 చట్టంతో పోలిస్తే నిర్మాణాత్మక మార్పులు ఏవి?n(Income-t',"answer":"A"},
    {"id":31394,"question_text":'Mission Mausam ను అమలు చేసే 3 సంస్థలు (MoES)?n(Three MoES institutions implement',"answer":"B"},
    {"id":31403,"question_text":'ECI నిర్వహించిన SIR (Special Intensive Revision) — ఏ రాష్ట్రంలో + qualifying dat',"answer":"B"},
    {"id":31404,"question_text":'Swachh Vayu Sarvekshan 2024 (clean air city awards) — Million+ population winner',"answer":"B"},
    {"id":31405,"question_text":'CRS Vital Statistics 2023 (ORGI report) — birth registration % + death registrat',"answer":"B"},
    {"id":31406,"question_text":'ECI list (2025-26) ప్రకారం భారత్\u200cలో National Parties ఎన్ని? వాటిలో 2 ఏవి?n(Per E',"answer":"B"},
    {"id":31407,"question_text":'130th Constitutional Amendment Bill 2025 — ప్రవేశ తేదీ + ముఖ్య నిబంధన?n(130th Co',"answer":"B"},
    {"id":31412,"question_text":'Earth Day (April 22, 2026) నాటికి భారత్ Ramsar Sites సంఖ్య? 99వది ఏ రాష్ట్రంలో?n',"answer":"B"},
    {"id":31414,"question_text":'PM Adi-Vaani App — లాంచ్ తేదీ + లక్ష్యం + ఏ Mission కింద?n(PM Adi-Vaani App — la',"answer":"B"},
    {"id":31415,"question_text":'ECINET — ECI launched (2025) unified platform; దాని ముఖ్య లక్ష్యం ఏది?n(ECINET —',"answer":"B"},
    {"id":31416,"question_text":'EnviStats-India 2024 ఎవరు విడుదల చేస్తారు? అది ఏ లెక్కల వ్యవస్థను అనుసరిస్తుంది?',"answer":"B"},
    {"id":31417,"question_text":'NSSO HCES 2023-24 — విడుదల తేదీ + key finding (rural-urban consumption gap)?n(NS',"answer":"B"},
    {"id":31418,"question_text":'Vikasit Bharat Shiksha Abhiyan — ఇది ఏ scheme కు renaming/upgrade?n(Vikasit Bhar',"answer":"B"},
    {"id":31419,"question_text":'PM SETU (Aspirational Bharat upgrade) — ఇది ఏ రంగానికి సంబంధించినది?n(PM SETU — ',"answer":"B"},
    {"id":31420,"question_text":'UNESCO ICH list లో భారత్ నుండి ఈ క్రింది వాటిలో **ఇంకా inscribe చేయని** element ',"answer":"D"},
    {"id":31421,"question_text":'Rafale-M ఒప్పందంలో single-seat vs twin-seat variants distribution + ఒక విమానం ap',"answer":"B"},
    {"id":31422,"question_text":'Code on Wages 2019 ద్వారా ఏకీకృతం అయిన 4 wage-related laws ఏవి?n(Code on Wages 2',"answer":"A"},
    {"id":31423,"question_text":'GST 2.0 సంస్కరణల్లో 40% slab దేనికి applicable?n(GST 2.0 — what does the 40% sla',"answer":"B"},
    {"id":31424,"question_text":'PM ధన్-ధాన్య కృషి యోజన — ఎన్ని కేంద్ర పథకాలను converge చేస్తుంది? ఎన్ని శాఖలు ఉం',"answer":"B"},
    {"id":31425,"question_text":'MIG-21 — IAF లోకి induction సం. + 1971 యుద్ధం + 1999 కార్గిల్ + 2019 Balakot — r',"answer":"B"},
    {"id":31426,"question_text":'GST 2.0 ప్రకటించిన GST Council సమావేశం + GST Council ఛైర్\u200cపర్సన్ ఎవరు?n(GST Coun',"answer":"A"},
    {"id":31427,"question_text":'Earth Day 2026 — ఏది observe చేస్తారు + ఏ సంవత్సరం నుండి + 2026 థీమ్?n(Earth Day',"answer":"A"},
    {"id":31428,"question_text":'Employment-Linked Incentive (ELI) Scheme — మొత్తం budget outlay + employment లక్',"answer":"B"},
    {"id":31429,"question_text":'National Sports Governance Act 2025 — ఈ చట్టం లక్ష్యాలు (5 ముఖ్యాంశాలు)?n(Nation',"answer":"B"},
    {"id":31431,"question_text":'సుప్రీమ్ కోర్టు 2026 కేసుల పారిష్కారం?',"answer":"B"},
    {"id":31432,"question_text":'భారత్ న్యాయ విద్య సంస్థలు?',"answer":"B"},
    {"id":31434,"question_text":'భారత అప్ చర్వీ కోర్టుల సంఖ్య?',"answer":"B"},
    {"id":31435,"question_text":'జిల్లా న్యాయాలయాల?',"answer":"B"},
    {"id":31436,"question_text":'జన నిరీక్షకుల సంఖ్య?',"answer":"C"},
    {"id":31437,"question_text":'నేషనల్ లీగల్ సర్వీస్ బడ్జెట్?',"answer":"C"},
    {"id":31438,"question_text":'జాతీయ న్యాయ సంస్కారాలు 2026?',"answer":"C"},
    {"id":31439,"question_text":'భారతీయ పోలీస్ బలం?',"answer":"B"},
    {"id":31440,"question_text":'జాతీయ మానవ హక్కుల సంస్థ బడ్జెట్?',"answer":"B"},
    {"id":31441,"question_text":'కార్బన్ తటస్థత లక్ష్య సంవత్సరం?',"answer":"C"},
    {"id":31442,"question_text":'జాతీయ వెట్\u200cలాండ్ సంరక్ష బడ్జెట్?',"answer":"C"},
    {"id":31443,"question_text":'పరిసర ప్రభావ మూల్యాంకన?',"answer":"C"},
    {"id":31444,"question_text":'నదుల సంరక్ష కర్మ?',"answer":"C"},
    {"id":31445,"question_text":'సంకటాన్నిన జంతువులు?',"answer":"C"},
    {"id":31446,"question_text":'ప్లాస్టిక్ వ్యర్థం టన్నులు?',"answer":"C"},
    {"id":31447,"question_text":'భారతదేశం 2030 నాటికి నిర్దేశించిన నాన్-ఫాసిల్ విద్యుత్ సామర్థ్య లక్ష్యం ఎంత? (CO',"answer":"B"},
    {"id":31448,"question_text":'డిజిటల్ ఆర్థిక పరిమాణం?',"answer":"B"},
    {"id":31449,"question_text":'డేటా సంరక్ష చట్టం సంవత్సరం?',"answer":"D"},
    {"id":31450,"question_text":'ఎయ్\u200cఐ విధానం సంవత్సరం?',"answer":"C"},
    {"id":31451,"question_text":'భారత స్మార్ట్ సిటీస్ మిషన్\u200cలో ఎన్ని నగరాలను చేర్చారు?nHow many cities are includ',"answer":"B"},
    {"id":31452,"question_text":'2015లో ప్రారంభించిన భారత స్మార్ట్ సిటీస్ మిషన్ యొక్క ప్రాథమిక దృష్టి ఏమిటి?nWhat',"answer":"B"},
    {"id":31453,"question_text":'ప్రధానమంత్రి ఆవాస్ యోజన (పట్టణ) యొక్క ముఖ్య లక్ష్యం ఏమిటి?nWhat is the main obje',"answer":"B"},
    {"id":31454,"question_text":'భారత పట్టణ రవాణాలో అత్యంత మహత్వాకాంక్షి ప్రాజెక్ట్ ఏది?nWhich project is the mos',"answer":"B"},
    {"id":31455,"question_text":'స్వచ్ఛ భారత్ మిషన్ (పట్టణ)లో వ్యర్థ పదార్థాల నిర్వహణలో ప్రాథమిక దృష్టి ఏమిటి?nWh',"answer":"C"},
    {"id":31457,"question_text":'అటల్ మిషన్ ఫర్ రిజువనేషన్ అండ్ అర్బన్ ట్రాన్స్\u200cఫార్మేషన్ (AMRUT) ముఖ్య దృష్టి ఏమ',"answer":"B"},
    {"id":31458,"question_text":'భారతదేశంలో పట్టణ నిరుద్యోగాన్ని తగ్గించడానికి ఏ పథకాలు ప్రారంభించబడ్డాయి?nWhich ',"answer":"C"},
    {"id":31459,"question_text":'భారత నగరాలలో మురికివాడ ప్రాంతాల శాతం ఎంత?nWhat percentage of India cities consis',"answer":"C"},
    {"id":31460,"question_text":'భారతదేశంలో నీటి పారుదల మరియు మురుగు నిర్వహణలో మెరుగుదల కోసం ప్రధాన సంస్థ ఏది?nWh',"answer":"D"},
    {"id":31461,"question_text":'కొత్త జాతీయ పట్టణ జీవన మిషన్ (NLUM) ఎప్పుడు ప్రారంభించబడింది?nWhen was the New N',"answer":"D"},
    {"id":31462,"question_text":'భారతదేశంలో మొదటి స్మార్ట్ సిటీగా ఏ నగరాన్ని ప్రకటించారు?nWhich city was declared',"answer":"D"},
    {"id":31463,"question_text":'భారతదేశంలో నగరపాలిక ఘన వ్యర్థ నిర్వహణలో ప్రధాన సవాలు ఏమిటి?nWhat is the main cha',"answer":"D"},
    {"id":31464,"question_text":'ప్రధానమంత్రి ఆవాస్ యోజన కింద మే 2026 వరకు ఎన్ని గృహాలు నిర్మించబడ్డాయి?nHow many',"answer":"C"},
    {"id":31465,"question_text":'భారత నగరాలలో ట్రాన్సిట్-ఓరియెంటెడ్ డెవలప్\u200cమెంట్ (TOD) అంటే ఏమిటి?nWhat is the co',"answer":"B"},
    {"id":31466,"question_text":'పట్టణ ప్రాంతాలలో నీటి సంక్షోభాన్ని తగ్గించడానికి ఏ ప్రధాన విధానం అమలు చేయబడింది?',"answer":"B"},
    {"id":31467,"question_text":'భారత నగరాలలో హరిత ప్రాంతాల (పార్కులు మరియు తోటలు) కనీస నిష్పత్తి ఎంత ఉండాలి?nWha',"answer":"C"},
    {"id":31468,"question_text":'భారతదేశంలో పట్టణ స్థానిక సంస్థలకు (ULB) రాబడి యొక్క ప్రధాన వనరులు ఏవి?nWhat are ',"answer":"B"},
    {"id":31469,"question_text":'భారత నగరాలలో కాలుష్యాన్ని తగ్గించడానికి ఏ రవాణా ప్రత్యామ్నాయాన్ని ప్రోత్సహిస్తున',"answer":"B"},
    {"id":31470,"question_text":'పౌర భాగస్వామ్యం మరియు పారదర్శకత పెంచడానికి పట్టణ స్థానిక సంస్థలు ఏ డిజిటల్ చొరవల',"answer":"B"},
    {"id":31471,"question_text":'భారతదేశంలో పట్టణ పేదరికాన్ని తగ్గించడానికి ఏ మహత్వాకాంక్షి పథకం నడుస్తోంది?nWhic',"answer":"B"},
    {"id":31472,"question_text":'పట్టణ భూమి సేకరణ మరియు నిర్వహణలో పారదర్శకత తీసుకురావడానికి ఏ విధానం అమలు చేయబడిం',"answer":"B"},
    {"id":31473,"question_text":'భారత పట్టణ గృహాలలో మహిళల ఆస్తి హక్కులు నిర్ధారించడానికి ఏ చర్యలు తీసుకోబడ్డాయి?n',"answer":"D"},
    {"id":31474,"question_text":'భారతదేశంలో పట్టణ అభివృద్ధి ప్రాజెక్టులలో నష్టపోయిన వ్యక్తుల పునరావాసం కోసం ఏ విధ',"answer":"C"},
    {"id":31475,"question_text":'భారత నగరాలలో అత్యవసర ప్రతిస్పందన వ్యవస్థ మెరుగుపరచడానికి ఏ కొత్త ప్రాజెక్ట్ ప్రా',"answer":"B"},
    {"id":31476,"question_text":'భారతదేశంలో నగర వాయు ప్రదూషణాన్ని నియంత్రించడానికి ఏ విస్తృత విధానం ఆమోదించబడింది',"answer":"B"},
    {"id":31477,"question_text":'నగర ప్రాంతాలలో రద్దీని తగ్గించటానికి మరియు జనాభాను సమతుల్యం చేయడానికి ఏ విధానం అ',"answer":"A"},
    {"id":31478,"question_text":'భారతదేశంలో నగర సార్వజనిక ప్రదేశాల (పార్కులు, క్రీడా మైదానాలు) నిర్వహణను మెరుగుపర',"answer":"B"},
    {"id":31479,"question_text":'భారతదేశంలో నగర పరిశోధన మరియు వికాస కేంద్రాల స్థాపన యొక్క ఉద్దేశ్యం ఏమిటి?nWhat i',"answer":"B"},
    {"id":31480,"question_text":'భారతదేశం 2026 నగర వికాస కార్యక్రమంలో అతిపెద్ద సవాలుగా గుర్తించబడుతున్నది ఏమిటి?n',"answer":"B"},
    {"id":31481,"question_text":'మే 2026 నాటికి భారతదేశంలో ఏ రాష్ట్రానికి అత్యధిక నిబంధన సంస్థ చేయని రంగ కార్మికు',"answer":"A"},
    {"id":31482,"question_text":'కోడ్ ఆన్ వేజెస్, 2019 ప్రకారం నిర్దేశించిన కనిష్ట నెలవారీ వేతనం ఏమిటి, మే 2026 న',"answer":"C"},
    {"id":31483,"question_text":'ఖాతాదారుల నుండి 22-60 సంవత్సరాల వయస్సు ఉన్న కార్మికులకు 25 లక్ష టర్మ్ జీవన బీమా ',"answer":"B"},
    {"id":31484,"question_text":'నేషనల్ రూరల్ ఎంప్లాయిమెంట్ గ్యారెంటీ యాక్ట్ (NREGA) యొక్క ప్రధాన లక్ష్యం ఏమిటి, ',"answer":"A"},
    {"id":31485,"question_text":'ఇండస్ట్రియల్ డిస్\u200cపుట్\u200cస్ యాక్ట్\u200cకు సమస్య పరిష్కారం సమయ సీమలకు సంబంధించి మే 2026',"answer":"C"},
    {"id":31486,"question_text":'ఆక్యుపేషనల్ సేఫ్టీ, హెల్త్ అండ్ వర్కింగ్ కండిషన్\u200cస్ కోడ్, 2020 ప్రకారం, సంస్థలు ',"answer":"B"},
    {"id":31487,"question_text":'చిల్డ్ లేబర్ (ప్రిహిబిషన్ అండ్ రెగ్యులేషన్) యాక్ట్\u200cకు ఏ సవరణ బాలల కోసం నిషేధించి',"answer":"A"},
    {"id":31488,"question_text":'మే 2026 నాటికి ప్రధానమంత్రి కర్మ యోగీ మాన్\u200c-ధన్ (PM-KMY) యోజన కింద నమోదు కోసం ప్',"answer":"C"},
    {"id":31489,"question_text":'మే 2026 నాటికి మహిళా కార్మికులకు కార్యస్థలంలో లైంగిక వేధింపు నిరోధక విధానం చాలా ',"answer":"B"},
    {"id":31490,"question_text":'బిల్డింగ్ అండ్ ఆదర్ కన్\u200cస్ట్రక్షన్ వర్కర్\u200cస్ (BOCW) యాక్ట్ ప్రకారం, సెస్ సంగ్రహణ',"answer":"C"},
    {"id":31491,"question_text":'మే 2026 నాటికి ప్రధానమంత్రి కిసాన్ సమ్మాన్ నిధి (PM-KISAN) పథకం యొక్క ప్రాధమిక ద',"answer":"B"},
    {"id":31492,"question_text":'ఆక్యుపేషనల్ సేఫ్టీ, హెల్త్ అండ్ వర్కింగ్ కండిషన్\u200cస్ కోడ్, 2020 యొక్క ఏ నిబంధన ఇం',"answer":"B"},
    {"id":31493,"question_text":'సవరించిన షాప్\u200cల మరియు ఎస్టాబ్లిష్\u200cమెంట్\u200cల యాక్ట్ ప్రకారం, రిటెయిల్ కార్మికుల కోస',"answer":"B"},
    {"id":31494,"question_text":'నేపథ్య-మహమ్మారి తర్వాత గ్రామాలకు తిరిగి వచ్చిన సస్థానిక కార్మికులను లక్ష్యంగా చే',"answer":"C"},
    {"id":31495,"question_text":'మే 2026 నాటికి మాతృత్వ సూచన యాక్ట్ ప్రకారం నిర్దేశించిన మాతృత్వ ప్రయోజనాల కవరేజ్',"answer":"C"},
    {"id":31496,"question_text":'మే 2026 నాటికి జాతీయ సామాజిక సహాయ కార్యక్రమం (NSAP) యొక్క ప్రాధమిక లక్ష్యం ఏమిటి',"answer":"B"},
    {"id":31497,"question_text":'కోడ్ ఆన్ వేజెస్ 2019 ప్రకారం, కనిష్ట వేతనం లెక్కింపుకు ఎన్ని వేతన భాగాలు తప్పనిస',"answer":"C"},
    {"id":31499,"question_text":'ఇ-శ్రమ పోర్టల్ కింద సంస్థ చేయని రంగ కార్మికుల నమోదు ప్రస్తుత స్థితి ఏమిటి?nWhat ',"answer":"C"},
    {"id":31500,"question_text":'ప్రధానమంత్రి కౌశల్ విక్కాస యోజన (PMKVY) కింద ఏ రంగ సంచిత కౌశల్ శిక్ష కేటాయింపులు',"answer":"C"},
    {"id":31501,"question_text":'What is the current monthly apprenticeship stipend provided under the National A',"answer":"C"},
    {"id":31502,"question_text":'Under which major regulation are hazardous chemical handling standards specified',"answer":"B"},
    {"id":31503,"question_text":'What is the current claim settlement percentage under the Pradhan Mantri Fasal B',"answer":"B"},
    {"id":31504,"question_text":'Which significant amendment to the Sexual Harassment of Women at Workplace Act w',"answer":"D"},
    {"id":31505,"question_text":'Under the amended Income Support Scheme (ISS), what is the maximum annual househ',"answer":"C"},
    {"id":31506,"question_text":'How many registered labour unions operate in India as of May 2026, representing ',"answer":"B"},
    {"id":31507,"question_text":'What percentage of women hold leadership positions in Indian organizations as of',"answer":"C"},
    {"id":31508,"question_text":'What is the current coverage of workers under the Pradhan Mantri Suraksha Bima Y',"answer":"C"},
    {"id":31509,"question_text":'Under which scheme does the government provide occupational safety training and ',"answer":"A"},
    {"id":31510,"question_text":'2024లో స్థాపించిన జాతీయ కనీస వేతన కమిషన్ నిర్మాణం ఏమిటి?nWhat is the composition',"answer":"D"},
    {"id":31511,"question_text":"Under the Consumer Protection Act 2019, what is the definition of 'consumer'? | ","answer":"B"},
    {"id":31512,"question_text":'What is the statutory timeframe for a District Consumer Commission to deliver ju',"answer":"B"},
    {"id":31514,"question_text":'జిల్లా వినియోగదారు కమిషన్ వివాదాస్పద వస్తువులు లేదా సేవల విలువకు సంబంధించి ఎంత అ',"answer":"C"},
    {"id":31515,"question_text":"Under the Consumer Protection Act 2019, what constitutes 'unfair trade practice'","answer":"C"},
    {"id":31516,"question_text":'What is the time limit for filing an RTI application under the Right to Informat',"answer":"C"},
    {"id":31517,"question_text":'Under NCDRC (National Consumer Disputes Redressal Commission), which of the foll',"answer":"C"},
    {"id":31518,"question_text":"What is the primary purpose of the Data Protection policy in India's Consumer Pr","answer":"B"},
    {"id":31519,"question_text":'Which of the following is NOT an exemption under the Right to Information Act 20',"answer":"C"},
    {"id":31520,"question_text":'What is the validity period of a product safety standard certificate under e-com',"answer":"C"},
    {"id":31521,"question_text":'Under the Consumer Protection Act 2019, what is the maximum compensation that ca',"answer":"B"},
    {"id":31522,"question_text":'What are the prescribed standards for e-commerce platforms regarding product aut',"answer":"B"},
    {"id":31523,"question_text":"What is the definition of 'unfair contract terms' under the Consumer Protection ","answer":"C"},
    {"id":31524,"question_text":'What is the prescribed timeline for a Public Information Officer (PIO) to provid',"answer":"B"},
    {"id":31525,"question_text":'Which of the following is a key responsibility of District Consumer Commissions?',"answer":"A"},
    {"id":31526,"question_text":'Under the Right to Information Act 2005, what constitutes a valid ground for ref',"answer":"B"},
    {"id":31527,"question_text":'What is the significance of the Central Consumer Protection Authority (CCPA) und',"answer":"B"},
    {"id":31528,"question_text":"What is the framework for protecting consumers' personal data in digital transac","answer":"C"},
    {"id":31529,"question_text":'What remedies can a consumer seek before a District Consumer Commission for defi',"answer":"C"},
    {"id":31530,"question_text":'What is the significance of maintaining detailed records under RTI Act 2005? | R',"answer":"B"},
    {"id":31531,"question_text":'Which statement correctly describes the product warranty obligations under consu',"answer":"B"},
    {"id":31532,"question_text":"Under the Right to Information Act, what is an 'information' as defined in the A","answer":"B"},
    {"id":31533,"question_text":'What standards must e-commerce platforms meet regarding consumer data security? ',"answer":"B"},
    {"id":31534,"question_text":'What is the significance of filing an RTI appeal before an Information Commissio',"answer":"B"},
    {"id":31535,"question_text":"What constitutes 'defect' in goods under the Consumer Protection Act 2019? | Con","answer":"B"},
    {"id":31536,"question_text":'Under e-commerce regulations, what is the responsibility of platforms regarding ',"answer":"B"},
    {"id":31537,"question_text":"What is the procedure for appealing a District Commission's order to a State Com","answer":"B"},
    {"id":31538,"question_text":"What constitutes 'misleading advertisement' under the Consumer Protection Act 20","answer":"B"},
    {"id":31539,"question_text":'What is the role of the State Information Commission under RTI Act 2005? | RTI A',"answer":"B"},
    {"id":31540,"question_text":'What are the limitations on use of consumer personal information by e-commerce p',"answer":"B"},
    {"id":31541,"question_text":'104వ రాజ్యాంగ సవరణ చట్టం 2019 (జనవరి 2020 నుండి అమలు) దేనిని రద్దు చేసింది?nWhat',"answer":"A"},
    {"id":31543,"question_text":'కేంద్రీయ ప్రజా ఫిర్యాదుల పరిష్కార మరియు పర్యవేక్షణ వ్యవస్థ (CPGRAMS) ఏ విభాగం పర',"answer":"C"},
    {"id":31562,"question_text":'పీఎం గతి శక్తి జాతీయ మాస్టర్ ప్లాన్ ఎప్పుడు ప్రారంభించబడింది మరియు దీని ముఖ్య ఉద',"answer":"B"},
    {"id":31583,"question_text":'PM గతి శక్తి జాతీయ మాస్టర్ ప్లాన్ అమలును ఏ మంత్రిత్వ శాఖ పర్యవేక్షిస్తుంది?nWhic',"answer":"B"},
    {"id":31584,"question_text":'PM గతి శక్తి జాతీయ మాస్టర్ ప్లాన్ (2021-2026) మొత్తం బడ్జెట్ కేటాయింపు ఎంత?nWhat',"answer":"A"},
    {"id":31585,"question_text":'NRLM (జాతీయ గ్రామీణ జీవనాధార మిషన్) ప్రధానంగా గ్రామీణ అభివృద్ధిలో ఏ అంశంపై దృష్ట',"answer":"B"},
    {"id":31587,"question_text":'ప్రధానమంత్రి కౌశల్ వికాస్ యోజన (PMKVY) కింద ప్రాథమిక దృష్టి ఏమిటి?nUnder the Pra',"answer":"B"},
    {"id":31589,"question_text":'ఆర్థిక చేర్పు ద్వారా మహిళా సాధికారతను ప్రత్యేకంగా లక్ష్యంగా చేసుకుంటున్న ప్రభుత్',"answer":"C"},
    {"id":31591,"question_text":'ప్రధానమంత్రి వయ వందన యోజన (PMVVY) యొక్క ప్రాథమిక లక్ష్యం ఏమిటి?nWhat is the prim',"answer":"B"},
    {"id":31592,"question_text":'మే 2026 వరకు PMVVY కింద ఎన్ని మంది వయోవృద్ధులు నమోదయ్యారు?nHow many senior citiz',"answer":"C"},
    {"id":31593,"question_text":'వికలాంగుల పునరావాసం మరియు సంక్షేమానికి ఆర్థిక సహాయం అందించే పథకం ఏది?nWhich sche',"answer":"A"},
    {"id":31594,"question_text":'మే 2026 వరకు వికలాంగ పెన్షన్ పథకాల కింద ఎంత మంది వికలాంగులు కవర్ చేయబడ్డారు?nAs ',"answer":"A"},
    {"id":31595,"question_text":'ప్రధానమంత్రి మాతృత్వ వందన యోజన (PMMVY) యొక్క ప్రాథమిక దృష్టి ఏమిటి?nWhat is the ',"answer":"B"},
    {"id":31596,"question_text":'మే 2026 వరకు ఎంత మంది గర్భిణీ స్త్రీలు మరియు పాలిచ్చే తల్లులు PMMVY నుండి లాభపడ్',"answer":"D"},
    {"id":31597,"question_text":'ప్రధానమంత్రి ఆవాస్ యోజన (అందరికీ గృహాలు) యొక్క ముఖ్య లక్ష్యం ఏమిటి?nWhat is the ',"answer":"B"},
    {"id":31598,"question_text":'మే 2026 వరకు ప్రధానమంత్రి ఆవాస్ యోజన కింద ఎన్ని గృహాలు పూర్తయ్యాయి?nAs of May 20',"answer":"D"},
    {"id":31599,"question_text":'ఆధార్ ఆధారిత చెల్లింపు వ్యవస్థ ద్వారా పేదలకు ప్రత్యక్ష నగదు బదిలీ సహాయం అందించే ',"answer":"B"},
    {"id":31601,"question_text":'ప్రధానమంత్రి సురక్షా బీమా యోజన (PMSBY) యొక్క ప్రాథమిక లక్ష్యం ఏమిటి?nWhat is the',"answer":"B"},
    {"id":31602,"question_text":'మే 2026 వరకు PMSBY కింద ఎంత మంది వ్యక్తులు కవర్ చేయబడ్డారు?nAs of May 2026, how ',"answer":"D"},
    {"id":31603,"question_text":'జాతీయ సామాజిక సహాయ కార్యక్రమం (NSAP) యొక్క ప్రాథమిక దృష్టి ఏమిటి?nWhat is the pr',"answer":"B"},
    {"id":31604,"question_text":'మే 2026 వరకు NSAP కింద ఎంత మంది హానివన్నమైన వ్యక్తులు కవర్ చేయబడ్డారు?nAs of May',"answer":"B"},
    {"id":31605,"question_text":'అనుపూరక పోషణ ద్వారా పిల్లల పోషక ఫలితాలు మెరుగుపరచడానికి ఏ పథకం లక్ష్యంగా పెట్టుక',"answer":"B"},
    {"id":31606,"question_text":'మే 2026 వరకు ICDS ద్వారా ఎంత మంది పిల్లలకు చేరుకున్నారు?nAs of May 2026, how man',"answer":"C"},
    {"id":31607,"question_text":'ప్రధానమంత్రి జీవన్ జ్యోతి బీమా యోజన (PMJJBY) కింద అందించే జీవిత బీమా కవరేజీ (మరణ',"answer":"B"},
    {"id":31608,"question_text":'మే 2026 వరకు PMJJBY కింద ఎంత మంది వ్యక్తులు నమోదయ్యారు?nAs of May 2026, how many',"answer":"D"},
    {"id":31609,"question_text":'ప్రధానమంత్రి శ్రమ యోగి మాన్\u200cధన్ (PM-SYM) పథకం యొక్క ప్రాథమిక లక్ష్యం ఏమిటి?nWhat',"answer":"B"},
    {"id":31610,"question_text":'మే 2026 వరకు PM-SYM కింద ఎంత మంది అసంఘటిత రంగ కార్మికులు నమోదయ్యారు?nAs of May 2',"answer":"A"},
    {"id":31611,"question_text":'ప్రధానమంత్రి శ్రమ యోగి మాన్\u200cధన్ పథకం కింద అందించే నెలసరి పెన్షన్ మొత్తం ఎంత?nWha',"answer":"C"},
    {"id":31612,"question_text":'NRLM (జాతీయ గ్రామీణ జీవనాధార మిషన్) అమలును ఏ మంత్రిత్వ శాఖ పర్యవేక్షిస్తుంది?nWh',"answer":"A"},
    {"id":31613,"question_text":'మే 2026 వరకు NRLM లబ్ధిదారులలో మహిళలు ఎంత శాతం?nWhat percentage of NRLM benefici',"answer":"C"},
    {"id":31614,"question_text":'విక్సిత్ భారత్ - G RAM G చట్టం, 2025 (MGNREGA స్థానంలో) కింద ప్రతి గ్రామీణ కుటుం',"answer":"C"},
    {"id":31616,"question_text":'2021లో ప్రారంభించిన నేషనల్ డిజిటల్ హెల్త్ మిషన్ (NDHM) యొక్క ప్రాథమిక లక్ష్యం ఏమ',"answer":"B"},
    {"id":31619,"question_text":'అక్టోబర్ 2022లో ప్రారంభించిన ప్రభుత్వ టెలి-మెంటల్ హెల్త్ పథకం పేరు ఏమిటి మరియు మ',"answer":"B"},
    {"id":31620,"question_text":'మే 2026 నాటికి కొత్తగా విస్తరించిన నేషనల్ హెల్త్ మిషన్ (NHM) కింద ఎంత మంది ఆరోగ్',"answer":"A"},
    {"id":31621,"question_text":'మే 2026 నాటికి మిషన్ ఇంద్రధనుష్ 4.0 కింద వ్యాక్సినేషన్ కవరేజ్\u200cలో ఎంత శాతం పెంపు ',"answer":"B"},
    {"id":31622,"question_text":'మే 2026లో మందుల నాణ్యత మరియు భద్రతను పెంపొందించడానికి ఏ ఫార్మాస్యూటికల్ నిబంధన ప',"answer":"C"},
    {"id":31623,"question_text":'విస్తరణ కార్యక్రమం కింద మే 2026 నాటికి ఎన్ని కొత్త AIIMS సంస్థలు కార్యాచరణలోకి వ',"answer":"B"},
    {"id":31624,"question_text":'కొత్త నేషనల్ ఎడ్యుకేషన్ పాలసీ (NEP) 2020 కింద వైద్య విద్యా వ్యవధి మరియు పాఠ్యక్ర',"answer":"C"},
    {"id":31625,"question_text":'మే 2026 నాటికి NEP కింద నర్సింగ్ విద్యా విస్తరణ యొక్క స్థితి ఏమిటి?nWhat is the ',"answer":"C"},
    {"id":31626,"question_text":'మే 2026లో ప్రారంభించిన కొత్త ఇంటిగ్రేటెడ్ హెల్త్\u200cకేర్ డెలివరీ సిస్టమ్ యొక్క దృష్',"answer":"A"},
    {"id":31627,"question_text":'మే 2026 యూనియన్ బడ్జెట్\u200cలో మాతా మరియు శిశు ఆరోగ్య కార్యక్రమాలకు కేటాయింపు ఎంత?nW',"answer":"D"},
    {"id":31628,"question_text":'ఏ సంక్రమణ వ్యాధి నిర్మూలన కార్యక్రమం మే 2026 నాటికి 18-నెలల శూన్య సంక్రమణ మైలురా',"answer":"D"},
    {"id":31629,"question_text":'మే 2026 నాటికి యాంటీమైక్రోబియల్ రెసిస్టెన్స్ (AMR)పై భారతదేశం యొక్క ప్రతిస్పందన ',"answer":"C"},
    {"id":31630,"question_text":'మే 2026 నాటికి టెలిమెడిసిన్ మౌలిక సదుపాయాలతో ఎన్ని గ్రామీణ మరియు మారుమూల ఆరోగ్య ',"answer":"C"},
    {"id":31631,"question_text":'మే 2026లో అసంక్రమ వ్యాధుల (NCDs) నివారణకు ఏ కొత్త పథకం ప్రవేశపెట్టబడింది?nWhat n',"answer":"C"},
    {"id":31632,"question_text":'మే 2026 నాటికి వ్యాధి నిఘాలో ప్రధాన సాధన ఏమిటి?nWhat was the major achievement i',"answer":"C"},
    {"id":31633,"question_text":'మే 2026 నాటికి వైద్య పరికర నిబంధన మరియు తయారీని బలోపేతం చేయడానికి బడ్జెట్ కేటాయి',"answer":"D"},
    {"id":31634,"question_text":'మే 2026లో ప్రాథమిక ఆరోగ్య సంరక్షణకు మద్దతు ఇవ్వడానికి ఏ కొత్త ఆరోగ్య సంరక్షణ ఆర్',"answer":"C"},
    {"id":31635,"question_text":'మే 2026 నాటికి COVID-19 మరియు మహమ్మారి సన్నద్ధతపై భారతదేశం యొక్క ప్రతిస్పందన స్థ',"answer":"C"},
    {"id":31636,"question_text":'మే 2026 నాటికి గ్రామీణ భారతంలో ఏ ఆరోగ్య సూచిక అత్యధిక మెరుగుదలను చూపించింది?nWhi',"answer":"D"},
    {"id":31637,"question_text":'మే 2026 నాటికి భారతదేశ జనాభాలో ఎంత శాతం మెరుగైన నీరు మరియు పారిశుద్ధ్య సౌకర్యాలు',"answer":"B"},
    {"id":31638,"question_text":'మే 2026లో వృత్తిపరమైన ఆరోగ్యం మరియు కార్మిక భద్రత కోసం ఏ కొత్త చొరవ ప్రారంభించబడ',"answer":"C"},
    {"id":31639,"question_text":'మే 2026 నాటికి ఆరోగ్య సాంకేతిక ఆవిష్కరణలో ప్రధాన సాఫల్యం ఏమిటి?nWhat was the maj',"answer":"C"},
    {"id":31640,"question_text":'మే 2026 నాటికి ప్రాథమిక ఆరోగ్య కేంద్రాల ద్వారా మానసిక ఆరోగ్య సేవలు ఎంత మంది వ్యక',"answer":"D"},
    {"id":31641,"question_text":'మే 2026 బడ్జెట్\u200cలో గిరిజన ఆరోగ్య వ్యవస్థలను బలోపేతం చేయడానికి ఎంత కేటాయింపు ఉంది',"answer":"D"},
    {"id":31642,"question_text":'మే 2026లో వాయు నాణ్యత పర్యవేక్షణ మరియు శ్వాసకోశ ఆరోగ్యానికి ఏ కొత్త నిబంధన ప్రవే',"answer":"C"},
    {"id":31643,"question_text":'మే 2026 నాటికి అరుదైన జన్యు వ్యాధులతో ఉన్న ఎంత మంది రోగులు చికిత్స మద్దతు పొందార',"answer":"D"},
    {"id":31644,"question_text":'మే 2026 నాటికి హెపటైటిస్ B మరియు C వ్యాప్తి నిర్మూలనలో ఏ ప్రధాన సాఫల్యం నివేదించ',"answer":"C"},
    {"id":31645,"question_text":'మే 2026లో సాంప్రదాయ ప్రసవ సహాయకుల (TBA) సమన్వయాన్ని బలోపేతం చేయడానికి ఏ కొత్త చట',"answer":"C"},
    {"id":31646,"question_text":'మే 2026 నాటికి క్లినికల్ రీసర్చ్ మరియు ట్రయల్ మౌలిక సదుపాయాల్లో ప్రధాన పరిణామం ఏ',"answer":"C"},
    {"id":31647,"question_text":'మే 2026 నాటికి ఆరోగ్య సంరక్షణ కార్యకర్తల నిరుత్సాహం మరియు మానసిక ఆరోగ్యాన్ని పరి',"answer":"C"},
    {"id":31648,"question_text":'మే 2026 నాటికి ఆరోగ్య మరియు సంక్షేమ స్టార్టప్\u200cలను నియంత్రించడానికి మరియు ప్రోత్స',"answer":"C"},
    {"id":31649,"question_text":'మే 2026 నాటికి సీసపు విషం మరియు ఇతర పర్యావరణ ఆరోగ్య ప్రమాదాలను తొలగించడంలో ఏ ప్ర',"answer":"C"},
    {"id":31650,"question_text":'మే 2026 నాటికి ఆరోగ్య సంరక్షణ రంగ పరివర్తన యొక్క మొత్తం పెట్టుబడి మరియు లబ్ధిదార',"answer":"D"},
    {"id":31651,"question_text":'మే 2026 నాటికి ఉన్నత విద్యా సంస్థల్లో NEP 2020 అమలు యొక్క ప్రాధమిక దృష్టి ఏమిటి?',"answer":"B"},
    {"id":31652,"question_text":'మే 2026లో జాతీయ అప్రెంటిస్\u200cషిప్ ప్రమోషన్ స్కీమ్ (NAPS) విస్తరణను ఏ మంత్రిత్వ శాఖ',"answer":"B"},
    {"id":31653,"question_text":'మే 2026 నాటికి e-పాఠశాల చొరవ కింద భారతదేశంలో ఎంత శాతం పాఠశాలలు డిజిటల్ మౌలిక సదు',"answer":"C"},
    {"id":31654,"question_text":'మే 2026లో భారతదేశంలో STEM విద్యా ఆవిష్కరణకు నోడల్ కేంద్రంగా ఏ IIT నియమించబడింది?',"answer":"A"},
    {"id":31655,"question_text":'PMKVY 4.0 (2022-2026) కింద నిర్దేశించిన మొత్తం నమోదు లక్ష్యం ఎంత?nWhat was the t',"answer":"B"},
    {"id":31656,"question_text":'మే 2026 నాటికి జాతీయ రిక్రూట్\u200cమెంట్ డ్రైవ్ చొరవ కింద భారతదేశం ఎన్ని ఉపాధ్యాయ నియ',"answer":"C"},
    {"id":31657,"question_text":'మే 2026 నాటికి SWAYAM వంటి ఆన్\u200cలైన్ అభ్యాస వేదికలలో ప్రస్తుత నమోదు ఎంత?nWhat is ',"answer":"C"},
    {"id":31658,"question_text":'మే 2026లో పెరిగిన స్కాలర్\u200cషిప్ మొత్తాలతో బాలిక విద్యకు మద్దతు ఇవ్వడానికి ఏ ప్రభు',"answer":"B"},
    {"id":31659,"question_text":'మే 2026 నాటికి భారతదేశంలో పనిచేసే విశ్వవిద్యాలయ ఇంక్యూబేషన్ కేంద్రాల మొత్తం సంఖ్',"answer":"C"},
    {"id":31660,"question_text":'మే 2026లో ప్రధానమంత్రి స్కూల్స్ ఫర్ రైజింగ్ ఇండియా (PM-SRI) కింద పాఠశాల మౌలిక సద',"answer":"B"},
    {"id":31661,"question_text":'మే 2026లో ప్రారంభించిన జాతీయ విశ్వవిద్యాలయ స్వాయత్తత చట్రం (NUAF) యొక్క ప్రాధమిక',"answer":"B"},
    {"id":31662,"question_text":'మే 2026లో గ్రీన్ జాబ్\u200cలపై దృష్టి సారించి స్కిల్ ఇండియా మిషన్\u200cకు ఏ కొత్త వృత్తి స',"answer":"C"},
    {"id":31663,"question_text":'మే 2026 నాటికి జాతీయ స్కాలర్\u200cషిప్ పథకం (NSS) ద్వారా ఎంత మంది విద్యార్థులు లాభపడ్',"answer":"C"},
    {"id":31664,"question_text":'మే 2026లో భాషా విద్యను విప్లవాత్మకంగా మార్చడానికి విద్యా మంత్రిత్వ శాఖ ఏ డిజిటల్',"answer":"B"},
    {"id":31665,"question_text":'మే 2026లో సమగ్ర ఉపాధ్యాయ సాధికారత కార్యక్రమం (ITEP) కింద కనీస వార్షిక శిక్షణ ఆదే',"answer":"C"},
    {"id":31666,"question_text":'మే 2026లో ప్రకటించిన జాతీయ సాక్షరత మిషన్ (NLM) విస్తరించిన పథకం కోసం నమోదు లక్ష్',"answer":"C"},
    {"id":31667,"question_text":'మే 2026 నాటికి జాతీయ సైన్స్ విద్యా చొరవ కింద ఎన్ని కొత్త సైన్స్ ప్రయోగశాలలు స్థా',"answer":"C"},
    {"id":31668,"question_text":'మే 2026లో స్థాపించిన ఉన్నత విద్యా నియంత్రణ సంస్థ (HERA) కింద ఏ విశ్వవిద్యాలయాలు ',"answer":"B"},
    {"id":31669,"question_text":'మే 2026లో ప్రారంభించిన జాతీయ విశేష విద్యా శ్రేష్ఠతా కేంద్రం (NCESE) యొక్క దృష్టి',"answer":"B"},
    {"id":31670,"question_text":'మే 2026 నాటికి NEP 2020 కింద చాయిస్-బేస్డ్ క్రెడిట్ సిస్టమ్ (CBCS) అమలు చేసిన కళ',"answer":"C"},
    {"id":31671,"question_text":'మే 2026లో ప్రకటించిన ప్రథమ తరం అభ్యాసకుల కోసం జాతీయ మెంటర్\u200cషిప్ కార్యక్రమం (NMPF',"answer":"B"},
    {"id":31672,"question_text":'మే 2026లో క్యాంపస్ కనెక్ట్ చొరవ కింద అంతర్జాతీయ విద్యార్థి మార్పిడుల లక్ష్య సంఖ్',"answer":"C"},
    {"id":31673,"question_text":'మే 2026 నాటికి డిజిటల్ లైబ్రరీ చొరవ కింద లైబ్రరీ ఆధునికీకరణలో వార్షిక పెట్టుబడి ',"answer":"C"},
    {"id":31674,"question_text":'మే 2026 నాటికి భారతదేశంలో ఎన్ని సెక్టోర్ స్కిల్ కౌన్సిల్\u200cలు (SSCs) నిర్వహించబడుత',"answer":"B"},
    {"id":31675,"question_text":'మే 2026లో జాతీయ వృత్తి విద్య మరియు శిక్షణ వ్యవస్థ (NVETS) కింద నమోదిత వృత్తి పాఠ',"answer":"C"},
    {"id":31676,"question_text":'మే 2026 నాటికి ఉద్యమ ఖేల్ విలాస్ (క్రీడా శ్రేష్ఠత) హోదా పొందిన ప్రభుత్వ పాఠశాలల ',"answer":"B"},
    {"id":31677,"question_text":'జాతీయ పాఠ్యాంశ చట్రం (NCF) 2026 కింద అనుభవపూర్వక మరియు ప్రాజెక్ట్-ఆధారిత అభ్యాసం',"answer":"C"},
    {"id":31678,"question_text":'సంస్థాగత మద్దతు కింద మే 2026 నాటికి భారతీయ పరిశోధకులు అంతర్జాతీయ జర్నల్\u200cలలో ఎన్న',"answer":"C"},
    {"id":31679,"question_text":'మే 2026లో ప్రకటించిన అంగన్\u200cవాడీ రెడీనెస్ కార్యక్రమం (ARP) కింద లక్ష్య నమోదు ఏమిట',"answer":"C"},
    {"id":31680,"question_text":'మే 2026 నాటికి ఇండస్ట్రీ-అకాడెమియా భాగస్వామ్యం (IAP) పథకం కింద ఎన్ని సంస్థాగత అన',"answer":"C"},
    {"id":31681,"question_text":'ఆటోమేషన్ మరియు AI స్వీకరణ కింద 2030 నాటికి భారతదేశ కార్మికుల్లో ఎంత శాతం కొత్త న',"answer":"C"},
    {"id":31682,"question_text":'మే 2026లో ఫార్మ్-టు-మార్కెట్ చొరవ కింద ఎన్ని వ్యవసాయ నైపుణ్య అభివృద్ధి కేంద్రాలు',"answer":"C"},
    {"id":31683,"question_text":'మే 2026లో స్థాపించిన జాతీయ ఆరోగ్య వృత్తుల నియంత్రణ మరియు విద్యా సంస్థ (NHPREA) చ',"answer":"C"},
    {"id":31684,"question_text":'మే 2026 నాటికి NEP 2020 యొక్క బహుళ-విభాగ బ్యాచలర్ డిగ్రీ కార్యక్రమాల కింద మొత్తం',"answer":"B"},
    {"id":31685,"question_text":'మే 2026లో అమలు చేసిన సమగ్ర ఉపాధ్యాయ పనితీరు మూల్యాంకన వ్యవస్థ (CTPES) కింద ఉపాధ్',"answer":"C"},
    {"id":31686,"question_text":'మే 2026 నాటికి భారతదేశంలో మొత్తం ఎన్ని UNESCO ప్రపంచ వారసత్వ ప్రదేశాలు ఉన్నాయి?n',"answer":"A"},
    {"id":31687,"question_text":'తమిళనాడులో ఉద్భవించిన మరియు లయబద్ధమైన కదలికలు, హస్తముద్రలు మరియు దేవాలయ ప్రదర్శన',"answer":"B"},
    {"id":31688,"question_text":'2021లో UNESCO మానవత్వం యొక్క అమూర్త సాంస్కృతిక వారసత్వ ప్రతినిధి జాబితాలో నమోదైన',"answer":"A"},
    {"id":31689,"question_text":'ఉత్తర భారతంలో ఉద్భవించిన కథక్ ప్రధానంగా ఏ ప్రాంతం మరియు దర్బార్ సంప్రదాయాలతో సంబ',"answer":"C"},
    {"id":31690,"question_text":'కేరళలో ఉద్భవించి ప్రధానంగా పురుష నటులు యోధ కథలను అభినయించే మరియు మార్షల్ ఆర్ట్ అ',"answer":"A"},
    {"id":31693,"question_text":'మహారాష్ట్రలోని అజంతా మరియు ఎల్లోరా గుహల సముదాయం సుమారు ఎన్ని రాతిలో చెక్కిన నిర్',"answer":"B"},
    {"id":31694,"question_text":'ఢిల్లీలో ఎర్రకోటను నిర్మించమని ఆదేశించిన మొఘల్ చక్రవర్తి ఎవరు మరియు అది ఎప్పుడు ',"answer":"B"},
    {"id":31695,"question_text":'ఒడిశాలోని కోణార్క సూర్య దేవాలయం ఏ వంశం వాస్తుశిల్ప శైలిలో నిర్మించబడింది మరియు ఏ',"answer":"B"},
    {"id":31696,"question_text":'ఢిల్లీలో ఏ ఆర్ట్ గ్యాలరీ భారతదేశంలో అతిపెద్ద ఆధునిక మరియు సమకాలీన భారతీయ కళ సంగ్',"answer":"A"},
    {"id":31697,"question_text":'ఏ UNESCO అమూర్త సాంస్కృతిక వారసత్వం, భారతదేశం నుండి వచ్చిన శాస్త్రీయ సంగీత సంప్ర',"answer":"B"},
    {"id":31698,"question_text":'ఏ భారతీయ శాస్త్రీయ సంగీత సంప్రదాయం దక్షిణ భారతంలో ఉద్భవించి, సంక్లిష్టమైన లయలు (',"answer":"B"},
    {"id":31699,"question_text":'ఏ భారతీయ మ్యూజియం ప్రాచీన కాలం నుండి ఆధునిక కాలం వరకు విస్తరించిన దేశంలో అత్యంత ',"answer":"B"},
    {"id":31700,"question_text":'కర్ణాటకలోని హంపి సముదాయం, UNESCO ప్రపంచ వారసత్వ ప్రదేశం, ఏ ప్రాచీన సామ్రాజ్యం రా',"answer":"B"},
    {"id":31701,"question_text":'మధ్యప్రదేశ్\u200cలోని ఖజురాహో స్మారక కట్టడాల సమూహాన్ని ఏ వంశం నిర్మించింది మరియు ఏ వా',"answer":"B"},
    {"id":31702,"question_text":'తమిళనాడులో మీనాక్షికి అంకితం చేయబడిన మరియు 30,000+ శిల్పాలతో భారతదేశంలో అతిపెద్ద',"answer":"B"},
    {"id":31704,"question_text":'ఏ భారతీయ కళా రూపం, బెంగాల్ నుండి, భారత స్వాతంత్ర్య ఉద్యమ సమయంలో జాతీయ కళగా పునరు',"answer":"A"},
    {"id":31705,"question_text":'హిందుస్థానీ సంప్రదాయంతో ముఖ్యంగా సంబంధం కలిగిన మరియు సుమారు 18-21 తీగలు కలిగిన ఏ',"answer":"B"},
    {"id":31706,"question_text":'కేరళలో లార్డ్ అయ్యప్పకు అంకితం చేయబడిన ఏ భారతీయ ఆలయ సముదాయం వార్షికంగా సుమారు 1.',"answer":"C"},
    {"id":31707,"question_text":'ముఖ్యంగా మహారాష్ట్ర మరియు రాజస్థాన్ నుండి వచ్చిన ఏ భారతీయ కళా రూపం, బంగారు రేకు ',"answer":"D"},
    {"id":31708,"question_text":'UNESCO అమూర్త సాంస్కృతిక వారసత్వ ప్రదేశం అయిన ఏ సాంప్రదాయ తాడు తయారీ పద్ధతి వారణ',"answer":"B"},
    {"id":31709,"question_text":'కేరళతో సంబంధం కలిగిన మరియు సొగసైన, ప్రవాహపూర్వకమైన కదలికలతో విశేషించబడి సంప్రదాయ',"answer":"B"},
    {"id":31710,"question_text":'పశ్చిమ బెంగాల్\u200cలో ఉద్భవించి నృత్యం మరియు మార్షల్ పద్ధతులను కలిపిన ఏ భారతీయ శాస్త',"answer":"B"},
    {"id":31711,"question_text":'2023లో ప్రారంభించిన ఏ ప్రభుత్వ పథకం మహారాష్ట్రలోని వార్లి కళా రూపాలను ప్రోత్సహిం',"answer":"C"},
    {"id":31712,"question_text":'మే 2026లో మధుబని చిత్రకళ భౌగోళిక సూచిక చట్రం కింద ఎంత మంది కళాకారులు అధికారికంగా',"answer":"B"},
    {"id":31713,"question_text":'కలంకారీ వస్త్ర నేత సంప్రదాయాన్ని పరిరక్షించినందుకు 2025లో "విలేజ్ ఆఫ్ ఎక్సెలెన్స',"answer":"A"},
    {"id":31714,"question_text":'జనవరి 2025లో టెక్స్\u200cటైల్స్ మంత్రిత్వ శాఖ ప్రారంభించిన "ఇండియా సిల్క్ ఇనిషియేటివ్',"answer":"B"},
    {"id":31715,"question_text":'జాతీయ హ్యాండ్\u200cలూమ్ హబ్ అభివృద్ధి కార్యక్రమం కింద మే 2026 నాటికి అధికారికంగా నిర్',"answer":"C"},
    {"id":31716,"question_text":'తమిళనాడులోని మహాబలిపురంలో కేంద్రీకృతమైన ఏ శిల్పకళా సంప్రదాయం 2024లో UNESCO నుండి',"answer":"B"},
    {"id":31717,"question_text":'"మినియేచర్ పెయింటింగ్ హెరిటేజ్ ప్రొటెక్షన్ స్కీమ్" కింద నమోదు చేయబడిన రాజస్థానీ ',"answer":"D"},
    {"id":31718,"question_text":'2025లో బెంగాల్ సాంస్కృతిక సంప్రదాయాలను పునరుద్ధరించినందుకు "జాతీయ వారసత్వ గుర్తి',"answer":"B"},
    {"id":31719,"question_text":'"నేషనల్ మాన్యుస్క్రిప్ట్ మిషన్ 2.0" కింద డిజిటైజ్ చేసిన మాన్యుస్క్రిప్ట్\u200cల సంఖ్య',"answer":"C"},
    {"id":31720,"question_text":'2024లో ప్రారంభించిన "అంతరించిపోయే భాషల డాక్యుమెంటేషన్ కార్యక్రమం" యొక్క ప్రాధమిక',"answer":"B"},
    {"id":31721,"question_text":'ఏ రాష్ట్ర ప్రభుత్వం యొక్క "ఫోక్ ఫెస్టివల్ హెరిటేజ్ సర్క్యూట్" చొరవ 2025లో అత్యధి',"answer":"C"},
    {"id":31722,"question_text":'2024-2025లో గుజరాత్\u200cలో ప్రీ-ఇండస్ వ్యాలీ నాగరికతకు సంబంధించి ఏ ముఖ్యమైన పురావస్త',"answer":"C"},
    {"id":31723,"question_text":'"జాతీయ వారసత్వ పునరుద్ధరణ కార్యక్రమం" కింద పర్యావరణ పరిరక్షణకు కేటాయించిన మొత్తం',"answer":"C"},
    {"id":31724,"question_text":'"ఇండియన్ హెరిటేజ్ అంబాసిడర్ కార్యక్రమం" లో మే 2026 నాటికి ఎన్ని దేశాలు పాల్గొన్న',"answer":"C"},
    {"id":31725,"question_text":'2024లో స్థాపించిన ఏ ప్రభుత్వ డేటాబేస్ 15,000+ సాంప్రదాయ భారతీయ వైద్య సూత్రాలను డ',"answer":"B"},
    {"id":31726,"question_text":'2024లో సంస్కృతి మంత్రిత్వ శాఖ స్థాపించిన "జాతీయ నృత్య వారసత్వ నిధి"లో ఎన్ని శాస్',"answer":"D"},
    {"id":31727,"question_text":'"డిజిటల్ మ్యూజియం ఇనిషియేటివ్ 2.0" కింద పూర్తి డిజిటల్ కేటలాగింగ్ సాధించిన భారతీ',"answer":"C"},
    {"id":31728,"question_text":'మే 2026 నాటికి UNESCO అమూర్త సాంస్కృతిక వారసత్వ ప్రతినిధి జాబితాలో గుర్తించిన భా',"answer":"A"},
    {"id":31729,"question_text":'2025లో భారతదేశపు కళాకారుల హస్తకళ క్లస్టర్\u200cలు సృష్టించిన మొత్తం ఆర్థిక ప్రభావం ఏమ',"answer":"C"},
    {"id":31730,"question_text":'2023-2026 మధ్య భారతదేశం నుండి ఎన్ని కొత్త UNESCO ప్రపంచ వారసత్వ ప్రదేశాలు చేర్చబ',"answer":"A"},
    {"id":31731,"question_text":'2024లో ప్రారంభించిన "జాగ్రఫికల్ ఇండికేషన్ ఫుడ్ హెరిటేజ్ కార్యక్రమం" యొక్క ప్రాధమ',"answer":"B"},
    {"id":31732,"question_text":'"జాతీయ ఆర్కైవ్ విస్తరణ ప్రాజెక్ట్" కింద స్థాపించిన ప్రాంతీయ సాంస్కృతిక ఆర్కైవ్\u200cల',"answer":"A"},
    {"id":31733,"question_text":'జాతీయ పెర్ఫార్మింగ్ ఆర్ట్స్ ఇన్\u200cఫ్రాస్ట్రక్చర్ కార్యక్రమం కింద నిర్మించిన కొత్త ',"answer":"B"},
    {"id":31734,"question_text":'ప్రభుత్వ సమగ్ర "కళాకారుల సంక్షేమ మరియు పింఛన్ పథకం" కింద నమోదు చేయబడిన సాంప్రదాయ',"answer":"D"},
    {"id":31735,"question_text":'"అద్భుత భారత్ సాంస్కృతిక పర్యాటక సర్క్యూట్" చొరవ కింద సాంస్కృతిక పర్యాటక ప్రమోషన',"answer":"D"},
    {"id":31736,"question_text":'మే 2026లో స్పోర్ట్స్ అథారిటీ ఆఫ్ ఇండియా వెల్లడించిన వ్యూహాత్మక రోడ్\u200cమ్యాప్ ప్రకా',"answer":"B"},
    {"id":31737,"question_text":'మే 2026లో ప్రకటించిన PM ఖేల్ వికాస్ యోజన కింద క్రీడా మౌలిక సదుపాయాల అభివృద్ధికి ',"answer":"A"},
    {"id":31738,"question_text":"మే 2026లో యువజన వ్యవహారాల మంత్రిత్వ శాఖ ప్రారంభించిన 'ఖేల్ ఉడాన్' యువ నాయకత్వ చొ","answer":"A"},
    {"id":31739,"question_text":"మే 2026లో ప్రారంభించిన 'మిషన్ ఫిట్ ఇండియా 2.0' అభియానం కింద 2030 నాటికి భారతీయుల","answer":"B"},
    {"id":31740,"question_text":"మే 2026లో ప్రారంభించిన భారతీయ సంప్రదాయ క్రీడలను ప్రోత్సహించే 'ఖేల్ విరసాధరన్' పథ","answer":"C"},
    {"id":31741,"question_text":'మే 2026లో ప్రకటించిన ప్రకారం స్పోర్ట్స్ అథారిటీ ఆఫ్ ఇండియా 2028 నాటికి ఎన్ని నేష',"answer":"B"},
    {"id":31742,"question_text":'మే 2026లో యువజన వ్యవహారాల మంత్రిత్వ శాఖ క్రీడా స్పాన్సర్\u200cషిప్\u200cకు ఏ కొత్త సమ్మతి ',"answer":"A"},
    {"id":31743,"question_text":"మే 2026లో ప్రారంభించిన 'ఖేల్ ఛాయావర్త్' గ్రాస్\u200cరూట్స్ చొరవ కింద 2028 నాటికి ఎన్న","answer":"B"},
    {"id":31744,"question_text":"మే 2026లో ప్రకటించిన 'నారీ ఖేల్' మహిళా-కేంద్రీకృత క్రీడా చొరవ కింద నిర్ణయించిన ల","answer":"B"},
    {"id":31745,"question_text":"మే 2026లో ప్రకటించిన 'ఖేల్ స్వాస్థ్య' చొరవ కింద ఎన్ని క్రీడా వైద్య క్లినిక్\u200cలు మ","answer":"C"},
    {"id":31746,"question_text":'మే 2026లో ప్రకటించిన ఒలింపిక్ సన్నాహ కార్యక్రమం కోసం ఎంత మంది అంతర్జాతీయ కోచ్\u200cలు',"answer":"C"},
    {"id":31747,"question_text":"మే 2026లో ప్రారంభించిన 'ఇ-ఖేల్ భారత్' డిజిటల్ ప్లాట్\u200cఫారమ్ యొక్క ప్రాథమిక విధి ఏ","answer":"B"},
    {"id":31748,"question_text":"మే 2026లో ప్రకటించిన సవరించిన 'రాజీవ్ గాంధీ ఖేల్ రత్న' ఉపకారవేతన కార్యక్రమం కింద","answer":"C"},
    {"id":31749,"question_text":'మే 2026లో యువజన వ్యవహారాల మంత్రిత్వ శాఖ 2026-2030 మధ్య దేశీయ క్రీడా కంటెంట్ పంపి',"answer":"C"},
    {"id":31750,"question_text":"మే 2026లో ప్రారంభించిన 'ఖేల్ మిత్ర' పాఠశాల క్రీడా ధృవీకరణ కార్యక్రమం కింద 'గోల్డ","answer":"B"},
    {"id":31751,"question_text":"మే 2026లో ప్రకటించిన 'గ్రామీణ ఖేల్ వికాస్' పథకం కింద 10,000 కంటే తక్కువ జనాభా ఉన","answer":"C"},
    {"id":31752,"question_text":"మే 2026లో ప్రారంభించిన 'ఖేల్ ఉద్యోగి' క్రీడా పారిశ్రామికత పథకం కింద ప్రభుత్వ హామ","answer":"C"},
    {"id":31753,"question_text":'మే 2026లో ప్రకటించిన ప్రకారం 2028 లాస్ ఏంజెలస్ ఒలింపిక్స్\u200cలో పాల్గొనే భారత ఒలింప',"answer":"A"},
    {"id":31754,"question_text":"మే 2026లో ప్రకటించిన వార్షికంగా జరిగే 'భారత్ ఖేల్ మహా ఉత్సవ్' జాతీయ అంతర-పాఠశాల ","answer":"C"},
    {"id":31755,"question_text":"మే 2026లో ప్రకటించిన 'ఖేల్ పర్యాటన్' క్రీడా పర్యాటక చొరవ కింద భారతదేశం అంతటా ఎన్","answer":"C"},
    {"id":31756,"question_text":"మే 2026లో ప్రారంభించిన 'ఖేల్ సురక్షా నిధి' అథ్లెట్ పెన్షన్ మరియు ఆర్థిక భద్రతా న","answer":"B"},
    {"id":31757,"question_text":"మే 2026లో ప్రకటించిన 'ఖేల్ కలమ్' క్రీడా మీడియా అక్షరాస్యత మరియు అభివృద్ధి కార్యక","answer":"C"},
    {"id":31758,"question_text":"మే 2026లో స్థాపించబడిన 'ఖేల్ విజ్ఞాన్' క్రీడా శాస్త్ర పరిశోధనా కన్సార్షియమ్\u200cకు వ","answer":"C"},
    {"id":31759,"question_text":'మే 2026లో స్థాపించడానికి అనుమతించిన కొత్త నేషనల్ స్పోర్ట్స్ యూనివర్సిటీ కోసం ప్ర',"answer":"C"},
    {"id":31760,"question_text":"మే 2026లో ప్రకటించిన వికలాంగుల కోసం 'దివ్యాంగ్జన్ ఖేల్ ప్రగతి' క్రీడా సమ్మిళిత చ","answer":"C"},
    {"id":31761,"question_text":'మే 2026లో నేషనల్ ఇన్\u200cఫ్రాస్ట్రక్చర్ పైప్\u200cలైన్ (NIP) 2.0 యొక్క తాజా అప్\u200cడేట్ ప్రక',"answer":"D"},
    {"id":31762,"question_text":'PM గతి శక్తి నేషనల్ మాస్టర్ ప్లాన్\u200cకు ఏ మంత్రిత్వ శాఖ నేతృత్వం వహిస్తుంది మరియు ',"answer":"C"},
    {"id":31763,"question_text":'మే 2026 నాటికి భారత్\u200cమాల పరియోజన ఫేజ్ I కింద ఎన్ని కిలోమీటర్ల హైవేలు నిర్మించబడ్',"answer":"C"},
    {"id":31764,"question_text":'మే 2026 నాటికి భారతదేశం యొక్క ప్రస్తుత 5G కవరేజ్ ఏమిటి మరియు రోల్\u200cఅవుట్\u200cకు ప్రధా',"answer":"C"},
    {"id":31765,"question_text":'2021లో ప్రకటించిన నేషనల్ సెమీకండక్టర్స్ మిషన్ ప్రకారం, మే 2026 నాటికి ఎన్ని సెమీ',"answer":"B"},
    {"id":31766,"question_text":'ఏప్రిల్ 2026 నాటికి DPIIT గుర్తింపు పొందిన భారత స్టార్టప్\u200cల సంఖ్య ఎంత మైలురాయి ద',"answer":"C"},
    {"id":31767,"question_text":'స్టార్టప్ ఇండియా చొరవ కింద, మే 2026 నాటికి DPIIT ద్వారా ఎన్ని స్టార్టప్\u200cలు నమోదు',"answer":"C"},
    {"id":31768,"question_text":'మే 2026 నాటికి, నేషనల్ స్టార్టప్ సీడ్ ఫండ్ స్కీమ్ కింద ఎన్ని భారతీయ పరిశోధనా సంస',"answer":"C"},
    {"id":31769,"question_text":'మే 2026 నాటికి భారతదేశంలో స్మార్ట్ సిటీ మౌలిక సదుపాయాల అభివృద్ధికి ఏ పబ్లిక్-ప్ర',"answer":"C"},
    {"id":31770,"question_text":'మే 2026 నాటికి సాగర్\u200cమాల కార్యక్రమం కింద భారతదేశంలో ఎన్ని పోర్టులు ఆధునీకరించబడ్',"answer":"D"},
    {"id":31771,"question_text":'మే 2026 నాటికి, AERA ఫ్రేమ్\u200cవర్క్ కింద భారతదేశంలో ఎన్ని విమానాశ్రయాలు ఆధునిక మౌల',"answer":"D"},
    {"id":31772,"question_text":'2023లో ప్రారంభించిన నేషనల్ మిషన్ ఆన్ క్వాంటమ్ కంప్యూటింగ్ మరియు క్వాంటమ్ టెక్నాల',"answer":"D"},
    {"id":31773,"question_text":'మే 2026 నాటికి బ్రాడ్\u200cబ్యాండ్ కనెక్టివిటీని లక్ష్యంగా పెట్టుకున్న భారత్\u200cనెట్ ఫేజ',"answer":"C"},
    {"id":31774,"question_text":'2021లో ప్రారంభించిన నేషనల్ హైడ్రోజన్ మిషన్ కింద, ఎన్ని గ్రీన్ హైడ్రోజన్ ఉత్పత్తి',"answer":"C"},
    {"id":31777,"question_text":"2026 తమిళనాడు ఎన్నికలలో TVK విజయం చారిత్రకంగా ఎందుకు ముఖ్యమైనది?nWhy is TVK's vi","answer":"B"},
    {"id":31783,"question_text":'2026 ఏప్రిల్-మే అసెంబ్లీ ఎన్నికల ఫలితాలు ఒకే రోజు (మే 4, 2026) ప్రకటించబడిన రాష్',"answer":"C"},
    {"id":31784,"question_text":'2026 ఎన్నికలలో పశ్చిమ బెంగాల్\u200cలో BJP విజయం చారిత్రకంగా ఎందుకు ముఖ్యమైనది?nWhy is',"answer":"B"},
    {"id":31785,"question_text":'2026 కేరళ ఎన్నికల్లో NDA మొదటిసారి గెలిచిన మూడు నియోజకవర్గాలు ఏవి?nWhich three c',"answer":"B"},
    {"id":31793,"question_text":'India AI Impact Summit 2026 — India added how many GPUs to sovereign compute?nIn',"answer":"D"},
    {"id":31796,"question_text":'MoSPI CPI (ఉపభోక్తధర సూచిక) కొత్త ఆధార సంవత్సరం ఏది?nWhat is the new base year f',"answer":"D"},
    {"id":31797,"question_text":'IIP (పారిశ్రామిక ఉత్పత్తి సూచిక) మార్చి 2026 మొత్తం వృద్ధి రేటు ఎంత?nWhat is IIP',"answer":"B"},
    {"id":31799,"question_text":'MoSPI (సాంఖ్యిక మరియు కార్యక్రమ అమలు మంత్రిత్వ శాఖ) మంత్రి (స్వతంత్ర బాధ్యత) 202',"answer":"B"},
    {"id":31800,"question_text":'Census 2027 అధికారిక మస్కట్\u200cలు ఏవి? వాటిని ఎవరు ప్రారంభించారు?nWhat are the offi',"answer":"B"},
]
