#!/usr/bin/env python3
"""
Complete Chunk 2 Insertion Script (MCQs 31451-31500)
Urban Development, Smart Cities, Housing, Infrastructure Topics
50 MCQs with bilingual Telugu+English format
Run this script to insert Chunk 2 into seed_national_ca_2026_mcq.py
"""

import sys
import os

# All 50 MCQs for Chunk 2 (31451-31500)
CHUNK_2_MCQS = """        # ════════════════════════════════════════════════════════════════════════════════════════
        # NATIONAL CA EXPANSION 2026 (31451-31500) — Chunk 2
        # Urban Development, Smart Cities, Housing, Infrastructure
        # ════════════════════════════════════════════════════════════════════════════════════════

        (31451, "స్మార్ట్ సిటీస్ మిషన్‌లో ఎన్ని నగరాలు చేర్చారు?\\nHow many cities in Smart Cities Mission?", "75 cities", "100 cities", "125 cities", "150 cities", "B", "స్మార్ట్ సిటీస్ మిషన్ 2015లో 100 నగరాలకు ఆరంభం, డిజిటల్ ఆధారిత నగర అభివృద్ధి.\\nSmart Cities Mission (June 2015) includes 100 cities nationwide for digital-enabled sustainable urban development with improved citizen services.", "AP_HC", "National_Current_Affairs_2026"),
        (31452, "PM ఆవాస్ యోజన్ (నగరం) లక్ష్యం?\\nPM Housing Scheme (Urban) objective?", "High-cost housing", "Affordable housing for poor and middle-class", "Industrial zones", "Agricultural land", "B", "PM ఆవాస్ 2015లో ఆరంభం, అన్ని నగర కుటుంబాలకు సస్తా పక్కా ఇండ్ల సరఫరా.\\nPM Housing Scheme (June 2015) targets all urban families with affordable, sustainable housing; supports EWS and LIG groups with subsidies.", "AP_HC", "National_Current_Affairs_2026"),
        (31453, "నగర పరివహన అత్యంత చేతన ప్రాజెక్టు?\\nMost ambitious urban transport project?", "Bus expansion", "Metro rail network", "Taxi services", "Walking paths", "B", "మెట్రో రైల్ నెట్‌వర్క్ అత్యంత చేతన, ఆరు ప్రధాన నగరాలలో విస్తరణ.\\nMetro Rail is most ambitious with expansion across Delhi, Mumbai, Bangalore, Hyderabad, Kolkata, Chennai; reduces congestion and pollution.", "AP_HC", "National_Current_Affairs_2026"),
        (31454, "స్వచ్ఛ భారత్ చెత్త నిర్వహణ దృష్టి?\\nSwachh Bharat waste management focus?", "Waste burial only", "Waste burning only", "Recycling and waste-to-energy", "Waste collection only", "C", "పునర్‌చక్రణ, చెత్త-నుండి-శక్తి, జీవ-శక్తి సంయంత్రాలపై దృష్టి, 100% పునర్‌చక్రణ లక్ష్యం.\\nSwachh Bharat focuses on recycling centers, waste-to-energy plants, biomethane facilities; target 100% waste diversion by 2030.", "AP_HC", "National_Current_Affairs_2026"),
        (31455, "74వ సంవిధాన సవరణ (నగర నిర్వహణ) సంవత్సరం?\\n74th Amendment (Municipal) year?", "1990", "1992", "1994", "1996", "B", "74వ సవరణ 1992 డిసెంబర్‌లో, త్రిస్తరీయ నగర వ్యవస్థ స్థాపన, మహిళా ఎస్సీ/ఎస్టీ సంరక్షణ.\\n74th Amendment (Dec 1992) established 3-tier municipal system with reservations for women, SCs, STs; ensured local autonomy.", "AP_HC", "National_Current_Affairs_2026"),
        (31456, "AMRUT ప్రధాన ఆధ్యంశం?\\nAMRUT main focus?", "Road repairs only", "Water and sewage systems", "Environmental conservation", "Industrial development", "B", "AMRUT (మే 2015) నీరు, సీవేజ్, రోడ్లు, రవాణ, హరిత బేలభూమిపై దృష్టి, 500+ నగరాలలో.\\nAMRUT (May 2015) focuses on water supply, sewage management, roads, public transport, green spaces across 500+ cities.", "AP_HC", "National_Current_Affairs_2026"),
        (31457, "నగర నిరుద్యోగం తగ్గించే పథకాలు?\\nSchemes for urban unemployment?", "Skill development only", "Business loans only", "Both skill and business support", "Agricultural schemes", "C", "PM కౌశల్‌ వికాస (PMKVS) - వృత్తి శిక్షణ, PM లఘువ వ్యాపార రుణ (PMEGP) - ఆత్‌మ-ఆధారిత.\\nPM Skill Development (PMKVS) and PM Business Loan (PMEGP) both create urban employment; millions have benefited.", "AP_HC", "National_Current_Affairs_2026"),
        (31458, "నగరాలలో ఝుప్పడీ జనాభా శాతం?\\nSlum population percentage in cities?", "5-10%", "10-15%", "20-25%", "30-35%", "C", "నగర జనాభాలో 20-25% ఝుప్పడీలో నివసిస్తుంది, PM ఆవాస్ కర్మ పురోగమనం.\\nApproximately 20-25% of urban population lives in slums; PM Housing schemes providing better housing to millions.", "AP_HC", "National_Current_Affairs_2026"),
        (31459, "నీటి నిర్గమన నిర్వహణ సంస్థ?\\nWater-sewage management institution?", "NITI Aayog", "Ganga Mission", "Housing Council", "NIUA", "D", "జాతీయ నగర విషయ సంస్థ (NIUA) నీరు, సీవేజ్, నగర నిర్వహణ పరిశోధన, సలహా.\\nNational Institute of Urban Affairs (NIUA) leads research and technical support for water, sewage, governance improvements.", "AP_HC", "National_Current_Affairs_2026"),
        (31460, "నూతన జాతీయ నగర జీవన మిషన్ సంవత్సరం?\\nNew National Urban Mission year?", "2015", "2020", "2023", "2025", "D", "నూతన జాతీయ నగర జీవన మిషన్ 2025లో ఆరంభం, నగర అభివృద్ధి సమ్మిళిత కర్మ.\\nNew National Urban Mission (2025) consolidates previous initiatives; targets integrated urban development across all cities.", "AP_HC", "National_Current_Affairs_2026"),
        (31461, "భారత్ మొదటి స్మార్ట్ సిటీ?\\nIndia's first Smart City?", "Delhi", "Bangalore", "Pune", "All designated together", "D", "మొదటి 20 స్మార్ట్ సిటీలు ఏకకాలంలో నిర్ణీతం, దిల్లీ, బెంగళూరు, ముంబై సహా.\\nFirst 20 Smart Cities designated simultaneously in Jan 2015, including Delhi, Bangalore, Mumbai; each has unique development focus.", "AP_HC", "National_Current_Affairs_2026"),
        (31462, "నగర ఠోస చెత్త నిర్వహణ సవాలు?\\nMunicipal solid waste challenges?", "Funding shortage", "Technical knowledge gap", "Public awareness gap", "All above", "D", "నిధుల కొరత, సాంకేతిక నైపుణ్యం, పౌర సచేతనత లేవు - అన్నీ సవాలు.\\nMunicipal waste management faces challenges: funding gaps, technical expertise shortage, and insufficient public awareness for waste segregation.", "AP_HC", "National_Current_Affairs_2026"),
        (31463, "PM ఆవాస్ నిర్మిత ఇండ్ల సంఖ్య?\\nPM Housing homes constructed?", "50 lakh", "75 lakh", "100 lakh", "125 lakh", "C", "PM ఆవాస్ 100 లక్షకు ఎక్కువ ఇండ్లు నిర్మాణం కంప్లీట్ లేదా నిర్మాణాధీన.\\nPM Housing has constructed/sanctioned 100+ lakh homes, successfully empowering millions with pucca houses.", "AP_HC", "National_Current_Affairs_2026"),
        (31464, "ట్రాన్సిట్-ఓరియంటెడ్ డెవలప్‌మెంట్ భావన?\\nTransit-Oriented Development concept?", "Only road widening", "Population centers around public transport", "Mandatory high-rise buildings", "Closing train stations", "B", "ట్రాన్సిట్-ఓరియంటెడ్ డెవలప్‌మెంట్ - రవాణ నెట్‌వర్కుల చుట్టూ జనాభా కేంద్రీకరణ.\\nTransit-Oriented Development concentrates housing, commerce around public transport; reduces car dependency, cuts emissions.", "AP_HC", "National_Current_Affairs_2026"),
        (31465, "నగర సవారీ సేవలో సాధారణ చట్టం?\\nCommon Law in urban mobility?", "Vehicle ownership only", "Public transport prioritization", "Metro expansion only", "Bus service reduction", "B", "నగర సవారీలో ప్రజా రవాణ ప్రాధాన్యత, కారు ఆధారపడకకు తగ్గిక.\\nPublic transport prioritization reduces car dependency, traffic congestion, pollution; emphasizes integrated mobility solutions.", "AP_HC", "National_Current_Affairs_2026"),
        (31466, "నగర ఖాళీ స్థలాల భూమిక?\\nUrban green spaces role?", "Only recreation", "Environmental and health benefits", "Property value only", "No significance", "B", "నగర ఖాళీ స్థలాలు - ఎయిర్ క్వాలిటీ, సుస్థలీకరణ, సామాజిక సంబంధాలు, వ్యాయామ సఠానాలు.\\nUrban green spaces improve air quality, provide recreation, enhance mental health, support biodiversity, cool urban heat islands.", "AP_HC", "National_Current_Affairs_2026"),
        (31467, "నగర జలసంభరణ చక్రం నిర్వహణ?\\nUrban water cycle management?", "Groundwater extraction only", "Rainwater harvesting and recycling", "Surface water diversion", "Desalination only", "B", "వర్షానికరణ సంభరణ, జలపునర్‌వినియోగం, భూమిలో నీటి పునరూజ్జీవనం.\\nRainwater harvesting, water recycling, groundwater recharge essential for urban water security and sustainability.", "AP_HC", "National_Current_Affairs_2026"),
        (31468, "నగర అభివృద్ధి ప్రధాన సూచిక?\\nUrban development key indicator?", "Population only", "Infrastructure, services, livelihood", "Buildings only", "Roads only", "B", "నగర అభివృద్ధి - కూలంకషణ, సేవలు, జీవిక, పర్యావరణ, సామాజిక సమానత్వం సమన్వయం.\\nUrban development measured by infrastructure, services, livelihood opportunities, environmental quality, and social equality.", "AP_HC", "National_Current_Affairs_2026"),
        (31469, "జిల్లా స్థరపు నగర పథకాలు?\\nDistrict-level urban schemes?", "State-led only", "District administration coordination", "Central only", "Private sector only", "B", "జిల్లా స్థరపు సమన్వయం - జిల్లా పరిపాలన, స్థానిక సంస్థలు, సమాజం చేర్చిక.\\nDistrict administration coordinates with local bodies and communities for effective urban development implementation.", "AP_HC", "National_Current_Affairs_2026"),
        (31470, "నగర ఆర్థిక గ్రోత్ కారకాలు?\\nUrban economic growth factors?", "Real estate only", "Businesses, employment, technology", "Population only", "Government spending only", "B", "నగర ఆర్థిక గ్రోత్ - చిన్న వ్యాపారాలు, ఎన్ఎमएస్, డిజిటల్, సేవాలు, పర్యటకం.\\nUrban economic growth driven by SMEs, startups, digital economy, services, tourism, foreign investments.", "AP_HC", "National_Current_Affairs_2026"),
        (31471, "నగర సామాజిక సంబంధాల సవాలు?\\nUrban social cohesion challenges?", "Only communal harmony", "Inequality, migration, diversity management", "Only crime", "Only education", "B", "నగర సామాజిక సంబంధాలు - అసమానత, గలిపట్టు, సాంస్కృతిక సంరక్షణ, సమానత్వం.\\nUrban social cohesion challenged by inequality, migration, cultural diversity; needs inclusive policies and community engagement.", "AP_HC", "National_Current_Affairs_2026"),
        (31472, "నగర గరిబీ నిర్మూలన పద్ధతి?\\nUrban poverty alleviation method?", "Employment only", "Housing, skills, livelihoods combined", "Cash transfers only", "Migration only", "B", "నగర గరిబీ నిర్మూలన - ఇండ్లు, వృత్తి శిక్షణ, జీవిక సుందరీకరణ, సామాజిక సహాయ.\\nUrban poverty alleviation requires housing, skill training, livelihood support, and social assistance programs combined.", "AP_HC", "National_Current_Affairs_2026"),
        (31473, "నగర స్వచ్ఛత సూచిక రేటింగ్?\\nUrban Cleanliness Index rating?", "Waste collection percentage", "Waste processing efficiency", "Behavioral change metrics", "All aspects combined", "D", "స్వచ్ఛత సూచిక - చెత్త సంభరణ, ప్రక్రియకరణ, వర్గీకరణ, పౌర భాగీదారీ, ఆచార్యవత్.\\nCleanliness Index rates waste management infrastructure, processing efficiency, citizen participation, and behavioral change.", "AP_HC", "National_Current_Affairs_2026"),
        (31474, "నగర శిక్షణ మేధావిత్ రేటు?\\nUrban education literacy rates?", "Below 50%", "50-70%", "Above 85%", "100%", "C", "నగర శిక్షణ - 85% పై సాక్షరత, కిందటి మధ్యతరగతికి విద్య సమానత్వం సమస్య.\\nUrban literacy above 85%, but education quality and equitable access remain challenges for lower-income groups.", "AP_HC", "National_Current_Affairs_2026"),
        (31475, "నగర ఆరోగ్య సేవలు సమస్య?\\nUrban health services challenge?", "Supply shortage only", "Unequal access and quality gaps", "Demand only", "Affordability only", "B", "నగర ఆరోగ్య సేవలు - సమాన సమాధాన, గుణమానం, సామర్థ్య అందనీయత.\\nUrban health challenges: unequal access between rich and poor areas, quality variations, and affordability issues.", "AP_HC", "National_Current_Affairs_2026"),
        (31476, "నగర విపత్తు నిర్వహణ సన్నిహిత?\\nUrban disaster management priority?", "Emergency response only", "Prevention and preparedness", "Recovery only", "Infrastructure only", "B", "విపత్తు నిర్వహణ - నిర్థారణ, సన్నిహిత-త, ప్రతిస్పందన, పునరుద్ధరణ సమన్వయం.\\nDisaster management needs prevention, preparedness, early warning systems, emergency response, and community resilience building.", "AP_HC", "National_Current_Affairs_2026"),
        (31477, "నగర భూ వినియోగం నియంత్రణ?\\nUrban land use regulation?", "No regulation needed", "Zoning and master planning", "Private development only", "Government takeover", "B", "నగర భూ వినియోగం - జోనింగ్, మాస్టర్ ప్లాన్, సర్వసాధారణ భూమి సంరక్షణ.\\nUrban land use regulated through zoning, master plans, public land preservation, and property rights protection.", "AP_HC", "National_Current_Affairs_2026"),
        (31478, "నగర సంక్రమణ సేవలు?\\nUrban transition services?", "Industrial only", "Formal to informal conversion", "All sectors coordination", "Government only", "C", "నగర సంక్రమణ - అసంఘటిత సంక్రమణ, నైతిక-కర్మ, సర్వసాధారణ సేవలు.\\nUrban transition services help informal workers, migrants, displaced persons through skill training and livelihood support.", "AP_HC", "National_Current_Affairs_2026"),
        (31479, "నగర సంస్కృతి సంరక్షణ?\\nUrban cultural preservation?", "Heritage sites only", "Heritage, traditions, festivals, arts", "Monuments only", "Modern development only", "B", "నగర సంస్కృతి - ఐతిహ్య సైట్‌లు, సాంప్రదాయక కళలు, సంగీతం, పర్యటన.\\nUrban cultural preservation includes heritage sites, traditional arts, festivals, and community cultural spaces.", "AP_HC", "National_Current_Affairs_2026"),
        (31480, "నగర భవిష్యత్ కథ?\\nUrban future narrative?", "Only technology-driven", "Inclusive, sustainable, resilient cities", "Only growth-focused", "Status quo", "B", "నగర భవిష్యత్ - సమక్రమిక, టిక్కుబడి, స్థితిస్థాపక, సూచిక సాంస్కృతిక నగరాలు.\\nUrban future vision: inclusive growth, environmental sustainability, social equity, digital integration, and cultural vibrancy.", "AP_HC", "National_Current_Affairs_2026"),
        (31481, "నగర సేవా సరఫరా నిధులు?\\nUrban services funding sources?", "Government only", "Mixed: government, private, community", "Private only", "International aid only", "B", "నగర సేవలు - ప్రభుత్వ నిధులు, ప్రైవేట్ పెట్టుబడులు, సమాజ భాగీదారీ, ఉపకర.\\nUrban services funded through government budget, private investments, community contributions, and user fees combined.", "AP_HC", "National_Current_Affairs_2026"),
        (31482, "నగర నిర్వహణ స్థానిక సంస్థల?\\nUrban governance local bodies?", "NGOs only", "Municipalities, corporations, assemblies", "Government only", "Private companies", "B", "నగర నిర్వహణ - నగర సంస్థలు, స్థానిక సర్వసాధారణ సంస్థలు, పరిచయ సభలు.\\nUrban governance through municipalities, corporations, local assemblies with community participation and transparency.", "AP_HC", "National_Current_Affairs_2026"),
        (31483, "నగర నిర్వహణ పారదర్శకత చర్యలు?\\nUrban governance transparency measures?", "No transparency needed", "Online portals, public participation, grievance systems", "Information hiding", "Autocratic decisions", "B", "నగర నిర్వహణ పారదర్శకత - ఆన్‌లైన్ పోర్టల్‌లు, సర్వసాధారణ భాగీదారీ, ఫిర్యాదు.\\nTransparency through online government portals, citizen participation mechanisms, grievance redressal systems.", "AP_HC", "National_Current_Affairs_2026"),
        (31484, "నగర మహిళా సంరక్షణ కార్యక్రమాలు?\\nUrban women safety programs?", "No specific programs", "Safe transport, police presence, emergency systems", "Only awareness", "Male vigilance", "B", "మహిళా సంరక్షణ - సురక్షితమైన రవాణ, నైతిక కర్మ, అత్యవసర వ్యవస్థలు.\\nWomen safety through safe public transport, police presence, emergency systems, community awareness, and law enforcement.", "AP_HC", "National_Current_Affairs_2026"),
        (31485, "నగర శిశ్వాలు పల్లెవలు?\\nUrban children's play areas?", "Not needed", "Parks, playgrounds, recreational facilities", "Schools only", "Private clubs", "B", "శిశువుల ఆటపండుకు - సర్వసాధారణ ఉద్యానవనాలు, ఆట భూమి, విశ్రామ.\\nChildren's recreational spaces through parks, playgrounds, community centers, and safe public spaces.", "AP_HC", "National_Current_Affairs_2026"),
        (31486, "నగర వృద్ధుల సంరక్షణ నీతి?\\nUrban elderly care policy?", "Family only", "Multi-approach: family, community, institutions", "Government institutions", "Private care only", "B", "వృద్ధుల సంరక్షణ - కుటుంబ, సమాజ సేవా, స్వాస్థ్య సేవలు, సమాజ సదస్సులు.\\nElderly care through family support, community centers, healthcare services, pension schemes, and social security.", "AP_HC", "National_Current_Affairs_2026"),
        (31487, "నగర నిరుద్యోగ సుపరిచయ?\\nUrban unemployment safeguards?", "No safeguards", "Skill training, job placement, social security", "Charity only", "Migration only", "B", "నిరుద్యోగ సుపరిచయ - వృత్తి శిక్షణ, ఉద్యోగ ప్లేస్‌మెంట్, సామాజిక సహాయ.\\nUnemployment safeguards through skill training, job placement assistance, social security, and income support schemes.", "AP_HC", "National_Current_Affairs_2026"),
        (31488, "నగర సామాజిక మూల్యాంకన?\\nUrban social assessment?", "Not important", "Health, education, livelihood, safety metrics", "Income only", "Population only", "B", "సామాజిక మూల్యాంకన - ఆరోగ్య, శిక్షణ, జీవిక, సామర్థ్య సూచిక పరీక్ష.\\nSocial assessment through health indicators, education quality, livelihood opportunities, and human development indices.", "AP_HC", "National_Current_Affairs_2026"),
        (31489, "నగర భారీ కరాయ విధానం?\\nUrban property tax policy?", "No taxes", "Progressive taxation with exemptions", "Flat rates", "Confiscatory rates", "B", "ఆస్తి కర - విభిన్న చర్వణ, నిర్ధారణ, సలహాయ, పుజారీ ఉపయోగం.\\nUrban property tax through progressive rates, exemptions for lower-income property, transparent assessment, and revenue reinvestment.", "AP_HC", "National_Current_Affairs_2026"),
        (31490, "నగర పర్యావరణ నీతి వాస్తవీకరణ?\\nUrban environmental policy implementation?", "Voluntary only", "Regulations, monitoring, community participation", "No enforcement", "Industry self-regulation", "B", "పర్యావరణ నీతి - నియమాలు, పర్యవేక్షణ, సమాజ భాగీదారీ, కారణ సిద్ధతలు.\\nEnvironmental policy enforced through regulations, monitoring systems, community participation, and compliance mechanisms.", "AP_HC", "National_Current_Affairs_2026"),
        (31491, "నగర సరఫరా చైన్ ప్రభావం?\\nUrban supply chain impact?", "Only producers", "Consumer access, affordability, employment", "Only retailers", "Only transporters", "B", "నగర సరఫరా చైన్ - సమీప సరఫరా, సస్తా ఆహారం, ఉద్యోగ సృష్టి.\\nUrban supply chains impact consumer prices, food availability, employment generation, and economic growth.", "AP_HC", "National_Current_Affairs_2026"),
        (31492, "నగర వ్యాపారం చిన్న సంస్థలు?\\nUrban business SMEs?", "No significance", "Backbone of urban economy", "Only support services", "Government run only", "B", "చిన్న వ్యాపారాలు - నగర ఆర్థిక మేధస్సు, ఉద్యోగ సృష్టి, స్థానిక అభివృద్ధి.\\nSMEs are backbone of urban economy, creating jobs, driving innovation, and supporting local communities.", "AP_HC", "National_Current_Affairs_2026"),
        (31493, "నగర ఖాతా ఆధారిత ఆర్థిక వ్యవస్థ?\\nUrban digital financial system?", "Cash only", "Digital payments, digital wallets, banking", "Credit cards only", "Government monopoly", "B", "డిజిటల్ ఆర్థిక - ఆన్‌లైన్ చెల్లింపు, డిజిటల్ ఖాతాలు, సూక్ష్మమైన ఆర్థిక.\\nDigital financial system through online payments, digital wallets, mobile banking enabling financial inclusion.", "AP_HC", "National_Current_Affairs_2026"),
        (31494, "నగర నిర్మాణ సామగ్రី సరఫరా?\\nUrban construction material supply?", "Only cement", "Diverse materials, sustainable options", "Only bricks", "Only concrete", "B", "నిర్మాణ సామగ్రి - సిమెంట్, ఇటుకలు, రంగు, లోహాలు, సెరామిక్‌లు, సస్టెయిన్‌బుల్ ఎంపిక.\\nUrban construction uses diverse materials including cement, bricks, steel, ceramics with increasing focus on sustainable options.", "AP_HC", "National_Current_Affairs_2026"),
        (31495, "నగర విద్యుత్ సరఫరా పవర్\\nUrban electricity supply power?", "Only coal", "Diverse sources including renewables", "Only solar", "Only hydro", "B", "విద్యుత్ సరఫరా - కోల్‌, గ్యాస్, నవీకరణ శక్తి, సంకర శక్తి సమన్వయం.\\nUrban electricity supplied through diverse sources: coal, gas, solar, wind combined for reliable sustainable supply.", "AP_HC", "National_Current_Affairs_2026"),
        (31496, "నగర సందర్శక ఆకర్షణలు?\\nUrban tourism attractions?", "Only historical sites", "Diverse: culture, nature, adventure, food", "Only museums", "Only amusement parks", "B", "నగర పర్యటకం - ఐతిహ్య, సంస్కృతి, ఆహారం, స్పోర్ట్‌లు, అనుభవాలు సమ్మిళిత.\\nUrban tourism attractions include heritage, cultural sites, street food, adventure activities, art galleries combined.", "AP_HC", "National_Current_Affairs_2026"),
        (31497, "నగర పర్యటక ఆదాయ సరఫరా?\\nUrban tourism revenue benefits?", "Only government", "Jobs, business growth, local economy", "Only hotels", "Only restaurants", "B", "పర్యటక ఆదాయ - ఉద్యోగ, చిన్న వ్యాపారాలు, స్థానిక ఆర్థిక, విద్యేశ డబ్బు.\\nTourism revenue creates jobs, supports local businesses, generates foreign exchange, strengthens local economy.", "AP_HC", "National_Current_Affairs_2026"),
        (31498, "నగర ఆహారం సంస్కృతి?\\nUrban food culture?", "Only modern food", "Diverse: traditional, fusion, international", "Only fast food", "Only traditional", "B", "నగర ఆహారం - సాంప్రదాయక, సంలయన, అంతర్జాతీయ, వీధి ఆహారం, వంటకలు.\\nUrban food culture diverse: traditional cuisines, fusion cooking, international cuisines, street food, fine dining.", "AP_HC", "National_Current_Affairs_2026"),
        (31499, "నగర కళా-సంస్కృతి కేంద్రాలు?\\nUrban arts-culture centers?", "Only government run", "Multi-platform: public, private, community", "Only private", "Only NGO", "B", "కళా సంస్కృతి - ప్రభుత్వ సంస్థలు, ప్రైవేట్ నిర్వాహణలు, సమాజ సంస్థలు సమన్వయం.\\nUrban arts-culture sustained through government venues, private galleries, community cultural centers combined.", "AP_HC", "National_Current_Affairs_2026"),
        (31500, "నగర సరఫరా శృంఖల సమస్యలు?\\nUrban supply chain challenges?", "Transportation only", "Last-mile delivery, cold chain, pricing", "Storage only", "Packaging only", "B", "సరఫరా శృంఖల సమస్యలు - చివరి వారం డెలివరీ, ఫ్రిజ్ వ్యవస్థ, ధర నియంత్రణ.\\nUrban supply chain challenges: last-mile delivery, cold chain maintenance, price stability, logistics optimization.", "AP_HC", "National_Current_Affairs_2026"),
"""

def main():
    seed_file = '/sessions/adoring-brave-ptolemy/mnt/mcq_app/seed_national_ca_2026_mcq.py'

    # Read the current file
    with open(seed_file, 'r', encoding='utf-8') as f:
        content = f.read()

    # Find insertion point (before closing ])
    insert_pos = content.rfind('    ]')
    if insert_pos == -1:
        print("ERROR: Could not find insertion point in seed file")
        return False

    # Insert Chunk 2
    new_content = content[:insert_pos] + CHUNK_2_MCQS + '\n' + content[insert_pos:]

    # Write back
    with open(seed_file, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print("✓ Chunk 2 (MCQs 31451-31500) inserted successfully")
    print(f"File size: {len(new_content)} bytes")
    print(f"MCQs added: 50")

    # Verify syntax
    try:
        import ast
        ast.parse(new_content)
        print("✓ AST validation passed - file syntax correct")
        return True
    except SyntaxError as e:
        print(f"✗ Syntax error at line {e.lineno}: {e.msg}")
        return False

if __name__ == '__main__':
    success = main()
    exit(0 if success else 1)
