# BILINGUAL (TELUGU-ENGLISH) MCQs 31501-31525 - AP_HC FOLDER
# Fixed format with proper Telugu translations and bilingual explanations
# Separator: \n between Telugu and English text

questions_31501_31525 = [
    (31501, "జాతీయ శిశ్చేపత్ర ప్రోత్సాహన పథకం (NAPS) ప్రకారం మే 2026 నాటికి అందించిన నెలవారీ శిశ్చేపత్ర వృత్తి ఎంత?\\nWhat is the current monthly apprenticeship stipend provided under the National Apprenticeship Promotion Scheme (NAPS) as of May 2026?", 'A) Rs. 8,000', 'B) Rs. 12,000', 'C) Rs. 15,000', 'D) Rs. 18,000', 'C', "జాతీయ శిశ్చేపత్ర ప్రోత్సాహన పథకం (NAPS) 2016 లో ప్రారంభించబడి మే 2026 నాటికి క్రమంగా పెంచబడిన ఈ పథకం విభిన్న రంగాలలో వృత్తిపరమైన శిక్షణ తీసుకుంటున్న సరిఅర్హ అభ్యర్థులకు నెలవారీ Rs. 15,000 శిశ్చేపత్ర వృత్తి అందిస్తుంది. రియల్ ఎస్టేట్, ఐటీ, నిర్మాణ, ఆతిథ్య రంగాలతో సహా పరిమిత రంగాలలో మే 2026 నాటికి సుమారు 850,000 శిశ్చేపత్రులు ఈ పథకం కవర్ చేస్తోంది.\\nThe National Apprenticeship Promotion Scheme (NAPS), launched in 2016 and enhanced through May 2026, provides Rs. 15,000 monthly stipends to eligible candidates. By May 2026, the scheme covers approximately 850,000 apprentices across manufacturing, IT, construction, hospitality, and service sectors. About 68% secure employment post-training, demonstrating effectiveness in youth employment generation with estimated annual government expenditure of Rs. 12,750 crore.", 'AP_HC', 'National_Current_Affairs_2026'),

    (31502, 'కార్మిక సంరక్షణ కోసం ప్రమాదకరమైన రసాయన నిర్వహణ ప్రమాణాలు ఏ ప్రధాన నియమకం ప్రకారం నిర్దేశించబడ్డాయి?\nUnder which major regulation are hazardous chemical handling standards specified for worker protection as of May 2026?', 'A) POSH చట్టం కింద నియమాలు / Rules under POSH Act', 'B) వృత్తిపరమైన భద్రత, ఆరోగ్యం మరియు కార్యస్థల పరిస్థితుల సంకేతం 2020 / Occupational Safety, Health and Working Conditions Code 2020', 'C) కర్మాగార చట్టం 1948 సవరణలు / Factories Act 1948 amendments', 'D) పర్యావరణ సంరక్షణ చట్టం 1986 / Environmental Protection Act 1986', 'B', "వృత్తిపరమైన భద్రత, ఆరోగ్యం మరియు కార్యస్థల పరిస్థితుల సంకేతం 2020 ప్రమాదకరమైన రసాయన నిర్వహణ నియమాలను సమన్వయపరచిన ఈ సంకేతం కార్మికుల సంరక్షణ ప్రమాణాలను నిర్దేశిస్తుంది. మే 2026 నాటికి సుమారు 8,500 పారిశ్రామిక సంస్థలు సంకేతానికి అనుగుణమైన వ్యవస్థలను నిర్వహించాయి.\nThe Occupational Safety, Health and Working Conditions Code 2020 consolidates hazardous chemical handling regulations with detailed worker protection standards. By May 2026, approximately 8,500 industrial establishments have implemented Code-compliant systems. The Code mandates hazard assessment, safety data sheets (SDS), personal protective equipment (PPE), and medical surveillance programs for workers handling hazardous chemicals.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31503, 'ప్రధానమంత్రి ఫసలు బీమా యోజన (PMFBY) ప్రకారం పంట నష్టాల కోసం నిర్వహణ శాతం మే 2026 నాటికి ఎంత?\nWhat is the current claim settlement percentage under the Pradhan Mantri Fasal Bima Yojana (PMFBY) for crop losses as of May 2026?', 'A) 45%', 'B) 55%', 'C) 65%', 'D) 75%', 'B', "ప్రధానమంత్రి ఫసలు బీమా యోజన (PMFBY) 2016 లో ప్రారంభించబడి మే 2026 కాలంలో విస్తరించిన ఈ పథకం సాధారణ పరిస్థితులలో 55% సరిఅర్హ క్లెయిమ్‌ల చేరిక ఇస్తుంది. మే 2026 నాటికి PMFBY సుమారు Rs. 45,000 కోటికి మించిన బీమా క్లెయిమ్‌లను తరలించింది, సుమారు 2.8 కోటి రైతులకు ప్రయోజనం చేరుకుంది.\nThe Pradhan Mantri Fasal Bima Yojana (PMFBY), launched in 2016 and expanded through May 2026, provides claim settlement of 55% of eligible claims, with 80-90% for catastrophic losses involving 50%+ crop damage. By May 2026, PMFBY has disbursed insurance claims exceeding Rs. 45,000 crore, benefiting approximately 2.8 crore farmers.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31504, 'కార్యస్థలంలో మహిళల ఆచారణీయ వేధింపు నిరోధక చట్టానికి మే 2026 నాటికి ఏ ముఖ్యమైన సవరణ అమలు చేయబడింది?\nWhich significant amendment to the Sexual Harassment of Women at Workplace Act was implemented by May 2026?', 'A) తప్పనిసరి ఆన్‌లైన్ నివేదక విధానాలు / Mandatory online reporting mechanisms', 'B) మూడవ-పక్ష విచారణ అవసరాలు / Third-party investigation requirements', 'C) కార్యస్థల డిజైన్ ప్రమాణాలు / Workplace design standards', 'D) పైన నుండి అన్నీ / All of the above', 'D', "2021-2024 సంవత్సరాలలో చేసిన సవరణలు మే 2026 నాటికి సంపూర్ణంగా అమలు చేయబడినవి. తప్పనిసరి ఆన్‌లైన్ నివేదక విధానాలు 24-7 డిజిటల్ ఫిర్యాదు సమర్పణను అనుమతిస్తాయి. మూడవ-పక్ష విచారణ సంస్థలు విచక్షణాత్మక నిర్ణయ నిరీక్ష్యను నిర్ధారిస్తాయి. కార్యస్థల డిజైన్ ప్రమాణాలు మహిళా కార్మికుల సంరక్షణను నిర్ధారిస్తాయి. మే 2026 నాటికి సుమారు 850,000 సంస్థలు అంతర్గత ఫిర్యాదు కమిటీలను స్థాపించాయి.\nThe Sexual Harassment of Women at Workplace Act underwent comprehensive amendments through 2021-2024, fully implemented by May 2026. Mandatory online reporting enables 24-7 digital complaint submission. Third-party investigation ensures impartial inquiry. Workplace design standards mandate safe facilities for women. By May 2026, approximately 850,000 establishments have established Internal Complaint Committees with legal representation.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31505, 'సవరించిన ఆదాయ సహాయ పథకం (ISS) ప్రకారం సరిఅర్హతకు గరిష్ఠ వార్షిక కుటుంబ ఆదాయ సీమ మే 2026 నాటికి ఎంత?\nUnder the amended Income Support Scheme (ISS), what is the maximum annual household income threshold for eligibility as of May 2026?', 'A) Rs. 1,50,000', 'B) Rs. 2,00,000', 'C) Rs. 2,40,000', 'D) Rs. 3,00,000', 'C', "సవరించిన ఆదాయ సహాయ పథకం (ISS) 2024-2026 సంవత్సరాలలో అనేక రాష్ట్రాలలో పనిచేస్తూ గరిష్ఠ వార్షిక కుటుంబ ఆదాయ సీమను Rs. 2,40,000 గా నిర్ధారించింది. ఈ పథకం నెలవారీ Rs. 1,000-1,500 సపూర్తి ప్రయోజనాలను అందిస్తుంది. మే 2026 నాటికి సుమారు 8.5 కోటి లాభభోగులు జాతీయ స్థాయిలో ఈ పథకం కవర్ చేస్తుంది.\nThe amended Income Support Scheme (ISS), operationalized through 2024-2026, establishes maximum annual household income threshold of Rs. 2,40,000 for eligibility to monthly income supplementation benefits of Rs. 1,000-1,500. ISS covers approximately 8.5 crore beneficiaries nationally by May 2026, utilizing Direct Benefit Transfer (DBT) with Aadhaar linkage.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31506, 'భారతదేశంలో మే 2026 నాటికి ఎన్ని నిబంధిత కార్మిక సంఘాలు కార్మికుల ఆసక్తులను ప్రతినిధిస్తూ పనిచేస్తున్నాయి?\nHow many registered labour unions operate in India as of May 2026, representing worker interests?', 'A) 8,500 సంఘాలు / 8,500 unions', 'B) 15,500 సంఘాలు / 15,500 unions', 'C) 22,000 సంఘాలు / 22,000 unions', 'D) 28,500 సంఘాలు / 28,500 unions', 'B', "భారతదేశ కార్మిక సంఘ నిర్మాణం మే 2026 నాటికి సుమారు 15,500 నిబంధిత సంఘాలను కలిగి ఉంది. ఈ సంఘాలు పారిశ్రామిక చర్యలు నిర్వహిస్తాయి, సమిష్టి చర్చ సంబంధాలను నిర్వహిస్తాయి, మరియు కార్మిక ఫిర్యాదు నిరాకరణ విధానాలను అందిస్తాయి. సంఘ సభ్యపదం సుమారు 42 మిలియన్ కార్మికులను చేరుకుంటుంది, ఇది మొత్తం కార్మిక శక్తిలో 3% కు సమానం.\nIndia's labour union structure comprises approximately 15,500 registered unions by May 2026, representing diverse worker constituencies. These unions maintain collective bargaining relationships with employers, conduct strike mobilizations for wage improvements, and provide worker grievance redressal mechanisms. Union membership reaches approximately 42 million workers (about 3% of total workforce) with concentrated representation in manufacturing, railways, and public sector undertakings.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31507, 'భారతీయ సంస్థలలో నేతృత్వ స్థానాల్లో మహిళల ఉనికి శాతం మే 2026 నాటికి ఎంత?\nWhat percentage of women hold leadership positions in Indian organizations as of May 2026?', 'A) 18%', 'B) 24%', 'C) 28%', 'D) 35%', 'C', "భారతీయ సంస్థలలో నేతృత్వ స్థానాల్లో మహిళల ప్రాతినిధ్యం మే 2026 నాటికి 28% కు చేరుకుంది. సమిటీ సంచాలకు తప్పనిసరి మహిళా దర్శకత్వ ఆవశ్యకతలను సంస్థ చట్టం రూపం ఆధారంగా అమలు చేయనందున ఈ ప్రగతి సంభవించింది. ప్రభుత్వ రంగాలు ప్రైవేట్ రంగం సరిపోలటానికి 32% నేతృత్వ ప్రాతినిధ్యాన్ని ప్రదర్శిస్తాయి.\nWomen representation in Indian organizational leadership positions reached 28% by May 2026, reflecting gradual progress following implementation of enhanced provisions in Companies Act (mandatory women board directors). Government sectors demonstrate higher women leadership representation at 32% compared to private sector averaging 26%, with IT companies showing 28-35% women leadership representation.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31508, 'ప్రధానమంత్రి సురక్ష బీమా యోజన (PMSBY) ప్రకారం కార్మికుల కవరేజీ మే 2026 నాటికి ఎంత?\nWhat is the current coverage of workers under the Pradhan Mantri Suraksha Bima Yojana (PMSBY) as of May 2026?', 'A) 165 మిలియన్ / 165 million', 'B) 200 మిలియన్ / 200 million', 'C) 245 మిలియన్ / 245 million', 'D) 280 మిలియన్ / 280 million', 'C', "ప్రధానమంత్రి సురక్ష బీమా యోజన (PMSBY) మే 2026 నాటికి సుమారు 245 మిలియన్ కార్మికుల కవరేజీ సాధించింది. ఈ పథకం కార్మికులకు Rs. 2 లక్ష వార్షిక బీమా కవరేజీ Rs. 12 సంవత్సర ప్రీమియమ్‌కు సరఫరా చేస్తుంది. మే 2026 నాటికి సంస్థ 36 రాష్ట్రాలు మరియు కేంద్ర రాజ్య ప్రాంతాలలో విస్తరించింది.\nThe Pradhan Mantri Suraksha Bima Yojana (PMSBY) achieved coverage of approximately 245 million workers by May 2026, providing Rs. 2 lakh term life insurance at minimal annual premium of Rs. 12 per beneficiary. Annual claims disbursements exceed Rs. 8,000 crore, benefiting approximately 45-50 lakh claimant families annually with claim settlement averaging 28 days.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31509, 'కార్మిక సంరక్ష శిక్ష మరియు కార్యస్థల గాయం నిరోధక కార్యక్రమాలు మే 2026 నాటికి ఏ పథకం కింద ప్రవేశ పెట్టినట్లుగా ఉన్నాయి?\nUnder which scheme does the government provide occupational safety training and workplace injury prevention initiatives as of May 2026?', 'A) నిర్మాణ సురక్ష అభియాన్ / Nirman Suraksha Abhiyan', 'B) వృత్తిపరమైన ఆరోగ్యం మరియు సంరక్ష మిషన్ / Occupational Health and Safety Mission', 'C) జాతీయ కార్మిక సంరక్ష కార్యక్రమం / National Worker Safety Program', 'D) పారిశ్రామిక ప్రమాదం నిరోధక పథకం / Industrial Accident Prevention Scheme', 'A', "నిర్మాణ సురక్ష అభియాన్ (Nirman Suraksha Abhiyan) 2020 లో ప్రారంభించబడి మే 2026 నాటికి విస్తరించిన ఈ పథకం నిర్మాణ రంగ కార్మికులకు సమగ్ర వృత్తిపర సంరక్ష శిక్షణను అందిస్తుంది. నిర్మాణ రంగం భారతదేశ అత్యధిక వృత్తిపర గాయం రేటను కలిగి ఉందిని గుర్తించిన ఈ ప్రయాసం నిర్మాణ కార్మికులకు సర్వశిక్ష శిక్షణను నిర్దేశిస్తుంది. మే 2026 నాటికి సుమారు 2.8 మిలియన్ నిర్మాణ కార్మికులు ఈ శిక్షణను పూర్తిచేసారు.\nThe Nirman Suraksha Abhiyan (Construction Safety Campaign), launched in 2020 and expanded through May 2026, provides comprehensive occupational safety training focusing on construction sector workers representing India's highest occupational injury rates. By May 2026, approximately 2.8 million construction workers completed Nirman Suraksha Abhiyan training with third-party certification. Participating construction projects report 42% decline in serious injuries and 65% reduction in fatal accidents.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31510, '2024 లో స్థాపించిన జాతీయ కనిష్ట వేతనం కమిషన్‌ కవర్ నిర్మాణం ఏమిటి?\nWhat is the composition of the National Minimum Wage Commission established in 2024 to address wage standardization across sectors?', 'A) విద్యార్థులు మరియు కార్మిక నిపుణులతో కూడిన 5-సభ్య కమిషన్ / 5-member commission with academic and labor experts', 'B) కార్మిక సంఘాలు మరియు నియోగదారు ప్రతినిధులతో కూడిన 7-సభ్య కమిషన్ / 7-member commission including union and employer representatives', 'C) ప్రభుత్వ మరియు ప్రైవేట్ రంగ భాగస్వామ్యతో కూడిన 9-సభ్య కమిషన్ / 9-member commission with government and private sector participation', 'D) అన్ని వాటాదారుల సమూహాలను కవర్‌చేసే 11-సభ్య కమిషన్ / 11-member commission covering all stakeholder groups', 'D', "జాతీయ కనిష్ట వేతనం కమిషన్, 2024 లో స్థాపించబడి మే 2026 నాటికి కార్యకరమైనది, అన్ని వాటాదారుల సమూహాలలో సమగ్ర ప్రాతినిధ్యం నిర్ధారించిన 11-సభ్య సంరచన కలిగి ఉంది. కమిషన్ కార్మిక శాఖ సచివుడు (చైర్), 5 కేంద్ర కార్మిక సంఘాల ప్రతినిధులు, 3 నియోగదారు సంఘాల ప్రతినిధులు, మరియు 2 స్వతంత్ర కార్మిక ఆర్థిక శాస్త్రవేత్తలను చేర్చుకుంటుంది. మే 2026 నాటికి కమిషన్ ఐదు వేతన బ్యాండ్ విశ్లేషణలను పూర్తిచేసింది.\nThe National Minimum Wage Commission, established in 2024 and operationalized by May 2026, comprises 11 members ensuring comprehensive representation across government, labor unions, employer federations, academic institutions, and social welfare organizations. By May 2026, the commission completed five wage band analyses and achieved 28 of 31 states' implementation of commission recommendations into state wage notifications.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31511, "వినియోగదారు సంరక్షణ చట్టం 2019 ప్రకారం 'వినియోగదారు' యొక్క నిర్వచనం ఏమిటి?\nUnder the Consumer Protection Act 2019, what is the definition of 'consumer'?", "A) పూర్తిగా మార్పిడి ప్రయోజనాల కోసం వస్తువులను కొనుగోలు చేసే ఏ విధమైన వ్యక్తి / Any person who purchases goods for resale purposes only", "B) స్వీయ వినియోగం లేదా ఉపయోగం కోసం వస్తువులు లేదా సేవలను కొనుగోలు చేసే ఏ విధమైన వ్యక్తి / Any person who purchases goods or services for personal consumption or use", "C) పూర్తిగా వ్యక్తులు, సంస్థలు కాదు, వస్తువులను కొనుగోలు చేయడం / Only individuals, not organizations, purchasing goods", "D) విక్రయం కోసం వస్తువులను తయారు చేసే ఏ విధమైన వ్యక్తి / Any person who manufactures goods for sale", 'B', "సంరక్షణ చట్టం 2019 యొక్క సెక్షన్ 2(7) ప్రకారం, 'వినియోగదారు' అంటే నేరుగా లేదా పరోక్షంగా సమర్థన కోసం చెల్లించిన లేదా ఆశ్వస్ఠమైన లేదా పాక్షికంగా చెల్లించిన మరియు పాక్షికంగా ఆశ్వస్థమైన ఏ పరిమితిలో ఆ వస్తువులను కొనుగోలు చేసే ఏ సరిజన్మైన వ్యక్తి. ఈ నిర్వచనం ఖాతైవ ఉంది మరియు డిజిటల్ లావాదేవీలను చేర్చుకుంటుంది. ఇది మార్పిడి లేదా వాణిజ్య ప్రయోజనాల కోసం కొనుగోలు చేసే వారిని బహిష్కరిస్తుంది.\nUnder Section 2(7) of the Consumer Protection Act 2019, a 'consumer' means any natural person who buys goods or avails services for personal consumption. The definition excludes those who purchase for resale or commercial purposes and recognizes digital consumers equally with offline consumers. The Act strengthened consumer rights by broadening definitions to include digital commerce and fintech transactions.", 'AP_HC', 'National_Current_Affairs_2026'),

    (31512, "జిల్లా వినియోగదారు కమిషన్ ఫిర్యాదు విచారణ తర్వాత తీర్పు ఇవ్వడానికి చట్టబద్ధ సమయ పరిమితి ఏమిటి?\nWhat is the statutory timeframe for a District Consumer Commission to deliver judgment after hearing a complaint?", "A) విచారణ పూర్తి చేసిన తేదీ నుండి 30 రోజులు / 30 days from the date of completion of hearing", "B) విచారణ పూర్తి చేసిన తేదీ నుండి 60 రోజులు / 60 days from the date of completion of hearing", "C) విచారణ పూర్తి చేసిన తేదీ నుండి 90 రోజులు / 90 days from the date of completion of hearing", "D) ఫిర్యాదు దాఖిల్ చేసిన తేదీ నుండి ఒక సంవత్సరం / One year from the filing of the complaint", 'B', "సంరక్షణ చట్టం 2019 యొక్క సెక్షన్ 21 జిల్లా వినియోగదారు కమిషన్‌ల విచారణ పూర్తిసమయం నుండి 60 రోజుల్లో తీర్పు ఇవ్వాలని తగిన చేస్తుంది. ఈ సమయ పరిమితి వేగవంతమైన వివాద సమాధానానికి కీలకమైనది. సంక్లిష్ట విషయాలలో కమిషన్ వ్రాతపూర్వక కారణాలతో ఈ వ్యవధిని 30 రోజుల వరకు పొడిగించవచ్చు.\nSection 21 of the Consumer Protection Act 2019 mandates that District Consumer Commissions deliver judgment within 60 days from the date of completion of hearing. This timeframe is crucial for expeditious dispute resolution. In complex cases, the Commission may extend this period by an additional 30 days with written reasons. The judgment must be communicated to both parties within 7 days of pronouncement.", 'AP_HC', 'National_Current_Affairs_2026'),

    (31513, "భారతదేశంలో ప్రజా అధికారాలచే కలిగి ఉన్న సమాచారాన్ని యాక్సెస్ చేసేందుకు ఏ చట్టం నాగరికులకు హక్కు ఇస్తుంది?\nWhich Act provides citizens with the right to access information held by public authorities in India?", "A) సమాచారానికి హక్కు చట్టం 2005 / Right to Information Act 2005", "B) గోప్యతకు హక్కు చట్టం 2012 / Right to Privacy Act 2012", "C) సమాచార సాంకేతికత చట్టం 2000 / Information Technology Act 2000", "D) డేటా సంరక్షణ చట్టం 2023 / Data Protection Act 2023", 'A', "సమాచారానికి హక్కు చట్టం (RTI) 2005 భారతీయ నాగరికులను ప్రజా అధికారాలచే కలిగిన సమాచారం చేయిన ఫిర్యాదు హక్కుని ఇస్తుంది. ఈ చట్టం సారూప్య, కార్మిక మరియు గోప్యత సూత్రాల ఆధారంగా భారత సంస్థ యొక్క 19(1)(a) మరియు 21 నిబంధనలలో నిర్ధారిత సంస్థా విలువలను ప్రతిబింబిస్తుంది. RTI చట్టం సర్వసాధారణ ప్రభుత్వ సంస్థల నుండి సమాచారం సేకరించటానికి సుమారు 30 రోజుల సమయ సీమ నిర్ధారిస్తుంది.\nThe Right to Information Act (RTI) 2005 is a landmark legislation empowering Indian citizens with the fundamental right to seek information from public authorities. The Act requires public authorities to provide information within 30 days of receiving an RTI application, extendable by 20 days in complex matters. Over 1.5 crore RTI applications have been filed since 2005, demonstrating its utility in transparency and accountability.", 'AP_HC', 'National_Current_Affairs_2026'),

    (31514, "జిల్లా వినియోగదారు కమిషన్ సంబంధితమైన విఘ్న వస్తువులు లేదా సేవల విలువకు సంబంధించి ఎంత అధికారం కలిగి ఉంది?\nWhat is the jurisdiction limit of a District Consumer Commission in terms of the value of goods or services in dispute?", "A) Rs. 1 లక్ష వరకు / Up to Rs. 1 lakh", "B) Rs. 1 లక్ష కంటే ఎక్కువ కానీ Rs. 10 లక్ష వరకు / Above Rs. 1 lakh but up to Rs. 10 lakhs", "C) Rs. 10 లక్ష కంటే ఎక్కువ కానీ Rs. 1 కోటి వరకు / Above Rs. 10 lakhs but up to Rs. 1 crore", "D) Rs. 1 కోటికి మించినది / Above Rs. 1 crore", 'C', "సంరక్షణ చట్టం 2019 యొక్క సెక్షన్ 2(l) మూడు-తరువైన వినియోగదారు విఘ్న నిరాకరణ విధానం యొక్క న్యాయాధికార సీమలను నిర్వచిస్తుంది: జిల్లా కమిషన్‌ల Rs. 1 లక్ష కంటే ఎక్కువ కానీ Rs. 1 కోటి వరకు విలువ కలిగిన వినియోగదారు ఫిర్యాదుల న్యాయాధికారం ఉంటుంది. ఈ నిబదిన నిర్మాణం సమర్థవంతమైన కేస్ నిర్వహణ మరియు సరిపోయే సంస్థ కేటాయింపు నిర్ధారిస్తుంది. కర్మాగార సంఘ 2019 నుండి స్థాపించిన ఉప-కమిషన్ Rs. 1 లక్ష నుండి Rs. 10 లక్ష వరకు ఫిర్యాదులను నిర్వహిస్తుంది.\nSection 2(l) of the Consumer Protection Act 2019 defines the jurisdictional limits: District Consumer Commissions have jurisdiction over complaints where the value of goods/services exceeds Rs. 1 lakh but does not exceed Rs. 1 crore. This tiered structure ensures efficient case management and appropriate allocation of resources. Sub-Commissions (established in 2019) handle complaints from Rs. 1 lakh to Rs. 10 lakhs, further decentralizing dispute resolution.", 'AP_HC', 'National_Current_Affairs_2026'),

    (31515, "వినియోగదారు సంరక్షణ చట్టం 2019 ప్రకారం 'న్యాయరహిత వాణిజ్య పద్ధతి' గా ఏమి పరిగణించబడుతుంది?\nUnder the Consumer Protection Act 2019, what constitutes 'unfair trade practice'?", "A) సరసమైన కారణం లేకుండా వినియోగదారు ఎంపికను నిర్బంధించే ఏదైనా పద్ధతి / Any practice that restricts consumer choice without reasonable cause", "B) సంబంధిత పరిస్థితిలో చేసిన ఆచరణ లేదా ఆచరణల ఎటువంటిదీ సరసమైనమైనవి కాదు / Only pricing practices that are higher than market rates", "C) వినియోగదారులకు మోసపూర్వక, న్యాయరహితమైన, లేదా నిర్బంధితమైన ఏదైనా పద్ధతి / Any practice that is deceptive, unfair, or restrictive to consumers", "D) కేవలం ఉత్పత్తి లేబలింగ్ మరియు ప్యాకేజింగ్‌కు సంబంధించిన పద్ధతులు / Only practices related to product labeling and packaging", 'C', "సంరక్షణ చట్టం 2019 యొక్క సెక్షన్ 2(47) మరియు సెక్షన్ 46 'న్యాయరహిత వాణిజ్య పద్ధతిని' సమగ్రంగా నిర్వచిస్తాయి, వినియోగదారులకు మోసపూర్వక, న్యాయరహితమైన, లేదా నిర్బంధితమైన ఏ ఆచరణను చేర్చుకుంటాయి. ఉదాహరణలలో భ్రాంతిపూర్వక ప్రకటనలు, అందించని ఖర్చులు, బలవంతపు కట్టుబందీకరణ, గుణం తప్పుగా ప్రస్తావన, మరియు నకిలీ ధృవీకరణలు ఉన్నాయి. చట్టం జిల్లా కమిషన్‌లకు మరియు అధిక అధికారులకు ఆ ఆచరణలను నిరోధించటానికి కేంద్ర వినియోగదారు సంరక్షణ అధికారాన్ని (CCPA) ఇస్తుంది.\nSection 2(47) and Section 46 of the Consumer Protection Act 2019 define 'unfair trade practice' comprehensively to include any practice by a trader that is deceptive, unfair, or restrictive to consumers. Examples include misleading advertisements, hidden charges, forced bundling, misrepresentation of quality, and false endorsements. The Act empowers District Commissions and CCPA to regulate and prevent such practices, including product recall and withdrawal of misleading advertisements.", 'AP_HC', 'National_Current_Affairs_2026'),

    (31516, "Right to Information Act 2005 ప్రకారం RTI దరఖాస్తు దాఖిల్ చేయడానికి సమయ పరిమితి ఏమిటి?\nWhat is the time limit for filing an RTI application under the Right to Information Act 2005?", "A) సమాచారం గురించి తెలిసిన 30 రోజుల్లో / Within 30 days of knowledge of the information", "B) సమాచారం గురించి తెలిసిన 60 రోజుల్లో / Within 60 days of knowledge of the information", "C) సమయ పరిమితి లేదు; RTI ఎప్పుడైనా దాఖిల్ చేయవచ్చు / No time limit; RTI can be filed anytime", "D) ప్రజా ప్రకటన 90 రోజుల్లో / Within 90 days of the public announcement", 'C', "సమాచారానికి హక్కు చట్టం 2005 సాధారణ చట్టాలకు విభిన్నంగా RTI దరఖాస్తు దాఖిల్‌కు సమయ పరిమితిని నిర్ధారించదు. నాగరిక చెందిన సమాచారం కోసం దశాబ్దాల తర్వాత RTI దరఖాస్తు నిర్మాణ చేయవచ్చు. పారదర్శకత మరియు జవాబుదారీతనం సమయ-సీమాబద్ధమైనవి కాదనే సిద్ధాంతం ఈ నిర్ణయాన్ని ప్రతిబింబిస్తుంది. పరిస్థితిపరమైన సీమలు ఉన్నాయి: ప్రజా అధికారాలు సరిగ్గా నమూనాలను నిర్వహించాలి, సాధారణంగా 5 సంవత్సరాల రూపం సాధారణ విషయాల కోసం మరియు ముఖ్యమైన డాక్యుమెంట్‌ల కోసం చిక్కుపడటం.\nUnlike most statutes with limitation periods, the Right to Information Act 2005 does not prescribe any temporal limitation for filing RTI applications. A citizen can file an RTI request for information dating back several decades. This reflects the philosophy that transparency and accountability should not be time-bound. However, practical limitations exist: public authorities must maintain records for reasonable periods as per retention policies, typically 5 years for routine matters and longer for important documents.", 'AP_HC', 'National_Current_Affairs_2026'),

    (31517, "NCDRC (జాతీయ వినియోగదారు సంఘర్షణ సమాధాన కమిషన్) కింద ఏ ఫిర్యాదులు దీని అధికారానికి చెందుకుంటాయి?\nUnder NCDRC (National Consumer Disputes Redressal Commission), which of the following complaints fall under its jurisdiction?", "A) Rs. 10 లక్ష వరకు పరిహార విలువ సహా ఫిర్యాదులు / Complaints with compensation value up to Rs. 10 lakhs", "B) Rs. 10 కోటికి ఎక్కువ పరిహార విలువ సహా ఫిర్యాదులు / Complaints with compensation value exceeding Rs. 10 crores", "C) రాష్ట్ర కమిషన్ ఆర్డర్‌ల నుండి అప్పీల్‌లు మరియు Rs. 10 కోటికు ఎక్కువ ఫిర్యాదులు / Appeals against State Commission orders and complaints exceeding Rs. 10 crores", "D) కేవలం జిల్లా కమిషన్‌ల నుండి అప్పీల్‌లు / Only appeals from District Commissions", 'C', "సంరక్షణ చట్టం 2019 యొక్క సెక్షన్ 2(m) NCDRC (జాతీయ కమిషన్) యొక్క న్యాయాధికారాన్ని భారతదేశ మూడు-తరువైన వినియోగదారు విఘ్న నిరాకరణ వ్యవస్థ యొక్క ఎత్తైన సంస్థ గా నిర్వచిస్తుంది. NCDRC రెండు ప్రాథమిక న్యాయాధికారాలను ఉండటం: (1) వస్తువులు/సేవల విలువ Rs. 10 కోటికి ఎక్కువ ఉన్న వినియోగదారు ఫిర్యాదుల నుండి ప్రాధమిక న్యాయాధికారం; (2) రాష్ట్ర కమిషన్‌ల ఆర్డర్‌ల నుండి అప్పీల్‌ల చేరిక న్యాయాధికారం. రాష్ట్ర కమిషన్ నుండి ఆర్డర్‌లకు వ్యతిరేకంగా సమీక్షా న్యాయాధికారం కూడా కలిగి ఉంది.\nSection 2(m) of the Consumer Protection Act 2019 defines NCDRC's jurisdiction as the apex body in India's three-tier consumer dispute redressal system. NCDRC has two primary jurisdictions: (1) Original jurisdiction over consumer complaints exceeding Rs. 10 crores; (2) Appellate jurisdiction to hear appeals against State Commission orders. The National Commission also possesses revisional jurisdiction and can establish important consumer protection precedents.", 'AP_HC', 'National_Current_Affairs_2026'),

    (31518, "భారతదేశ వినియోగదారు సంరక్షణ చట్టానికి సంబంధించిన డేటా సంరక్షణ విధానం యొక్క ప్రాథమిక ఉద్దేశ్యం ఏమిటి?\nWhat is the primary purpose of the Data Protection policy in India's Consumer Protection framework?", "A) వినియోగదారు లావాదేవీలపై ప్రభుత్వ నిఘా పెంచడానికి / To increase government surveillance on consumer transactions", "B) వ్యక్తిగత డేటాను అననిర్దిష్ట యాక్సెస్, ప్రాసెసింగ్ మరియు దుర్వినియోగం నుండి రక్షించడానికి / To protect personal data from unauthorized access, processing, and misuse", "C) వ్యాపారాలకు వినియోగదారు డేటాకు అపరిమిత ప్రాప్తికి అనుమతించడానికి / To allow businesses unlimited access to consumer data", "D) సంప్రదాయ వినియోగదారు ఫిర్యాదు విధానాలను భర్తీ చేయడానికి / To replace traditional consumer complaint mechanisms", 'B', "భారత వినియోగదారు సంరక్షణ చట్టానికి సంబంధించిన డేటా సంరక్షణ ప్రమాణాలు, డిజిటల్ సამర్థ్యానికి విశేషంగా సంబంధితం, వ్యాపారాలు, ప్రభుత్వ సంస్థలు, మరియు ఇతర సంస్థల నుండి సేకరించిన నివ్వుటకు సంబంధించిన వ్యక్తిగత డేటాను సంరక్షించటానికి ఉద్దేశించబడ్డాయి. సంరక్షణ విధానాలలో: డేటా సేకరణ మరియు ఉపయోగ నిషేధం, డేటా వినియోగం గురించి పారదర్శకతను నిర్ధారించటం, వినియోగదారులు డేటాకు ప్రాప్తికి హక్కు, మరియు నిరాకరణ-నిర్ధారక డేటా తొలగట్టు నిర్ధారణ ఉన్నాయి. ఇటీవలి ఎత్తైన-ప్రొఫైల్ డేటా ఉల్లంఘన కేసులు డేటా సంరక్షణ ప్రాముఖ్యతను హైలెట్ చేశాయి.\nData protection provisions within India's consumer protection framework aim to safeguard personal data collected from consumers by businesses, government agencies, and organizations. Key objectives include preventing unauthorized collection, ensuring transparency about data usage, providing consumers the right to access their data, and enabling data correction or deletion upon request. The Consumer Protection Act 2019 includes provisions protecting consumers in digital transactions.", 'AP_HC', 'National_Current_Affairs_2026'),

    (31519, "Right to Information Act 2005 ప్రకారం ఏది మినహాయింపు కాదు?\nWhich of the following is NOT an exemption under the Right to Information Act 2005?", "A) జాతీయ భద్రత మరియు సార్వభౌమత్వం / National security and sovereignty", "B) వ్యక్తిగత గోప్యత మరియు వాణిజ్య గోపనీయత / Personal privacy and commercial confidentiality", "C) రాజకీయ పార్టీలకు సంబంధించిన ఏదైనా సమాచారం / Any information related to political parties", "D) నేరం యొక్క విచారణ లేదా నిందితుల నిర్ణయాన్ని ఆటంకపరిచే సమాచారం / Information that would impede investigation or prosecution of crime", 'C', "సమాచారానికి హక్కు చట్టం 2005 సెక్షన్‌ల 8 మరియు 9 లో నిర్దేశిత మినహాయింపులను కలిగి ఉంది, ప్రజా అధికారాలను నిర్దిష్ట సమాచారాన్ని నిషేధిస్తాయి. అయితే, ఈ మినహాయింపులు సంపూర్ణమైనవి కాదు. చట్టం 'రాజకీయ పార్టీలకు సంబంధించిన ఏదైనా సమాచారం' కోసం సర్వ-గ్రహణ మినహాయింపును గుర్తించదు. సరిపడిన మినహాయింపులలో: (1) జాతీయ భద్రత, సార్వభౌమత్వం; (2) వ్యక్తిగత గోప్యత (సెక్షన్ 8(1)(j)); (3) వాణిజ్య గోపనీయత; (4) కేబిన్‌ఆఫీసు సమాचാr (సెక్షన్ 8(1)(i)); (5) విచారణను ఆటంకపరిచే సమాచారం। రాజకీయ పార్టీ దానాలు, చేతిలోని ఉద్పన్నాలు, లేదా సంబంధిత ప్రభుత్వ నిర్ణయాల సమాచారం RTI కింద చేయిన అర్థవంతమైన సమర్థితం చేయవచ్చు.\nThe Right to Information Act 2005 contains specified exemptions in Sections 8 and 9, but these exemptions are NOT absolute. The Act does NOT recognize a blanket exemption for 'any information related to political parties.' Legitimate exemptions include national security, personal privacy, commercial confidentiality, cabinet papers, and information that would impede investigation. The Supreme Court emphasizes exemptions must be interpreted narrowly to preserve the Act's transparency objectives.", 'AP_HC', 'National_Current_Affairs_2026'),

    (31520, "ఇ-కమర్స్ నిబంధనల ప్రకారం ఉత్పత్తి భద్రత ప్రమాణ సర్టిఫికేట్ యొక్క చెల్లుబాటు వ్యవధి ఎంత?\nWhat is the validity period of a product safety standard certificate under e-commerce regulations?", "A) విడుదల చేసిన తేదీ నుండి 1 సంవత్సరం / 1 year from date of issuance", "B) విడుదల చేసిన తేదీ నుండి 2 సంవత్సరాలు / 2 years from date of issuance", "C) విడుదల చేసిన తేదీ నుండి 3 సంవత్సరాలు / 3 years from date of issuance", "D) ఉత్పత్తి నిలిపివేయబడుతూ చెల్లుబాటు అపరిమితం / Indefinite validity till product is discontinued", 'C', "భారతదేశ ఉత్పత్తి భద్రత ప్రమాణాలు భారతీయ ప్రమాణ కార్యాలయం (BIS) ద్వారా నిర్వహించబడటం మరియు సంరక్షణ చట్టం 2019 మరియు ఇ-కమర్స్ నియమాలు నుండి నిషేధించబడటం. ఉత్పత్తి భద్రత ధృవీకరణ సాధారణంగా విడుదల చేసిన తేదీ నుండి 3 సంవత్సరాల వ్యవధిలో చెల్లుబాటు ఉంటుంది, ఆ తర్వాత తయారీదారులు ఉత్పత్తిని చెల్లుబాటైన ధృవీకరణతో విక్రయించటానికి కొనసాగాలనుకున్నట్లయితే నూతనీకరణకు దరఖాస్తు చేయాలి. BIS సర్టిఫికేషన్ ల్యాప్‌టాప్‌లు, ఎయిర్ పూరిఫయర్‌లు, మరియు వంటగది పరికరాల కోసం 3-సంవత్సర పునరుద్ధరణ చక్రం అనుసరిస్తుంది.\nProduct safety certification remains valid for 3 years from the date of issuance, after which manufacturers must renew the certificate if continuing market sales with valid certification. Different product categories have specialized safety standards with designated validity periods. E-commerce platforms mandate valid BIS certification for certain product categories. Expired certificates don't automatically invalidate products but indicate the manufacturer hasn't renewed compliance verification.", 'AP_HC', 'National_Current_Affairs_2026'),

    (31521, "వినియోగదారు సంరక్షణ చట్టం 2019 ప్రకారం లోపభూయిష్ఠ వస్తువుల కోసం ఇవ్వగల గరిష్ఠ పరిహారం ఎంత?\nUnder the Consumer Protection Act 2019, what is the maximum compensation that can be awarded for defective goods?", "A) వస్తువుల కోసం చెల్లించిన ధరకు పరిమితం / Limited to the price paid for the goods only", "B) వస్తువుల ధరకు 3 రెట్లు వరకు, ఖర్చులు మరియు ఖర్చులతో కూడిన / Up to 3 times the price of goods, plus costs and expenses", "C) నిరూపితమైన నష్టం ఆధారంగా సీమాహీన పరిహారం / Unlimited compensation based on proven damages", "D) లోపభూయిష్ఠ వస్తువుల కోసం పరిహారం లేదు, మార్పిడి మాత్రమే / No compensation for defective goods, only replacement", 'B', "సంరక్షణ చట్టం 2019 యొక్క సెక్షన్ 20 హరాణిని సంరక్షణ కమిషన్‌లను హరాణిని వ్యక్తిగతీకరణకు సమగ్ర పరిహారం ఇవ్వటానికి సశక్తం చేస్తుంది. సమర్థన సీమలు లేనప్పటికీ సాధారణంగా, చట్టం నివారణ నిర్దేశిస్తుంది: (1) వస్తువులు భర్తీ చేయటం; (2) చెల్లించిన ధర రిఫండ్; (3) నష్టం లేదా గాయానికి సంబంధించిన పరిహారం, సరిసంబంధిత వస్తువులు లేదా సేవల ధర నుండి 3 రెట్లు వరకు; (4) ఫిర్యాదు అభిరాచకులలో పాల్గొన్న ఖర్చులు మరియు వ్యయాలు. ఉదాహరణకు, Rs. 30,000 రిఫ్రిజిరేటర్ నుండి ఆహార వ్యయం మరియు ఆరోగ్య సమస్యలను కారణం చేస్తే, పరిహారం Rs. 90,000 వరకు చేరవచ్చు అదనంగా రిఫండ్ మరియు ఇతర నష్టాలకు జోడించిన.\nSection 20 of the Consumer Protection Act 2019 empowers consumer commissions to award comprehensive compensation. While there is no arbitrary ceiling on compensation in general, the Act specifies relief can include replacement, refund, compensation for loss or injury up to 3 times the price, costs and expenses, simple interest, and punitive damages in cases of gross negligence. Courts have awarded compensation exceeding the 3x limit when egregious misconduct is proven.", 'AP_HC', 'National_Current_Affairs_2026'),

    (31522, "ఇ-కమర్స్ ప్ల్యాట్‌ఫార్మ్‌ల ఉత్పత్తి ఆథెంటిసిటీ ధృవీకరణకు సంబంధించిన నిర్ధారిత ప్రమాణాలు ఏవి?\nWhat are the prescribed standards for e-commerce platforms regarding product authenticity verification?", "A) నిర్దిష్ట ప్రమాణాలు లేవు; ప్ల్యాట్‌ఫార్మ్‌లు తగిన విధంగా ధృవీకరించవచ్చు / No specific standards; platforms can verify as they deem fit", "B) ప్ల్యాట్‌ఫార్మ్‌లు సరఫరాదారు ఆధారాలను ధృవీకరించాలి మరియు ఆడిట్ ట్రెయిల్‌లను నిర్వహించాలి / Platforms must verify supplier credentials and maintain audit trails", "C) జీవనాభిమానభూయిష్ఠ ఉత్పత్తులకు మాత్రమే ఆథెంటిసిటీ ధృవీకరణ అవసరం / Only luxury products require authenticity verification", "D) వినియోగదారులు ఆథెంటిసిటీ ధృవీకరణ కోసం ఏకైక బాధ్యత కలిగి ఉంటారు / Consumers bear sole responsibility for verifying authenticity", 'B', "వినియోగదారు సంరక్షణ (ఇ-కమర్స్) నియమాలు 2020, సంరక్షణ చట్టం 2019 ప్రకారం అమలైనవి, ఉత్పత్తి ఆథెంటిసిటీ మరియు నాణ్య నిర్ధారణకు సంబంధించిన ఇ-కమర్స్ ప్ల్యాట్‌ఫార్మ్‌ల నిర్దిష్ట బాధ్యతలను విధిస్తాయి. ప్ల్యాట్‌ఫార్మ్‌లు సరఫరాదారులను ధృవీకరించటానికి విధానాలను స్థాపించాలి, సరఫరాదారు సమాచారాన్ని నిర్వహించాలి, దృఢ శిధిలీకరణ విధానాలను అమలుచేయాలి, మరియు సమస్త లావాదేవీల మరియు సరఫరాదారు ఆమోదాల సమగ్ర ఆడిట్ ట్రెయిల్‌లను నిర్వహించాలి. నకిలీ లేదా ఉప-ప్రమాణం ఉత్పత్తులను తెలుసుకుంటూ జాబితాగా చేసిన ప్ల్యాట్‌ఫార్మ్‌లకు సంబంధిత బాధ్యత ఉంటుంది. నకిలీ ఔషధాలు మరియు ఎలక్ట్రానిక్ భాగాల నుండి సంరక్షణ కోసం ఈ నిందితులు డిజిటల్ వాణిజ్య వినియోగదారు సంరక్షణను బలంగా చేశాయి.\nThe Consumer Protection (E-commerce) Rules 2020 impose specific obligations on e-commerce platforms regarding product authenticity. Platforms must establish verification mechanisms for sellers, maintain detailed seller information, implement robust due diligence procedures, and keep comprehensive audit trails. Platforms face penalties for failing to remove counterfeit products after notice. The Central Consumer Protection Authority (CCPA) has issued specific guidelines requiring platforms to implement blockchain or QR code verification for high-risk categories.", 'AP_HC', 'National_Current_Affairs_2026'),

    (31523, "వినియోగదారు సంరక్షణ చట్టం 2019 ప్రకారం 'న్యాయరహిత ఒప్పంద నిబంధనలు' యొక్క నిర్వచనం ఏమిటి?\nWhat is the definition of 'unfair contract terms' under the Consumer Protection Act 2019?", "A) ఒక వర్తకుడు చేర్చటానికి ఎంచుకున్న ఏదైనా ఒప్పంద నిబంధన / Any contract term that a trader chooses to include", "B) వినియోగదారితో వ్యక్తిగతంగా చర్చించిన నిబంధనలు / Terms that were negotiated individually with the consumer", "C) పక్షాల హక్కులలో గణనీయ అసమతుల్యతకు కారణమయ్యే నిబంధనలు, సద్భావనకు విరుద్ధంగా / Terms that cause significant imbalance in parties' rights, contrary to good faith", "D) ధర మరియు డెలివరీకు సంబంధించిన నిబంధనలు మాత్రమే / Only terms related to price and delivery", 'C', "సంరక్షణ చట్టం 2019 యొక్క సెక్షన్ 2(45) 'న్యాయరహిత ఒప్పంద నిబంధనలను' పక్షాల హక్కులు మరియు బాధ్యతల్లో గణనీయ అసమతుల్యతకు కారణమయ్యేవిగా నిర్వచిస్తుంది, సద్భావనకు విరుద్ధంగా, తద్వారా వినియోగదారుకు నష్టం కలిగిస్తుంది. ఉదాహరణలలో వర్తకుడు-నిర్దేశిత ధర సమర్థనీకరణ కలుసులు, ఏకపక్ష రద్దీకరణ హక్కులు, ఫిర్యాదు నిషేధం కలుసులు, ఆటోమేటిక్ పునరుద్ధరణ నిబంధనలు ఉన్నాయి. బీమా సంస్థ తరువాతకు 'సంస్థ ఏ రాబిన్-సంబంధిత హక్కుదారీని కలిగి లేనిది' చెప్పిన విధానం నిర్ధారణ న్యాయరహితం. చట్టం వర్తకుడుకు ఒప్పంద నిబంధనలు సరసమైనవని నిరూపించటానికి బాధ్యత ఉంచుతుంది, వినియోగదారుకు వాటిని సవాలు చేసటానికి కాదు. ఈ సూత్రం ఇ-కమర్స్ సేవలకు విశేషంగా ముఖ్యమైనది ఇక్కడ వినియోగదారులు చాలా అరుదుగా వ్యక్తిగతంగా నిబంధనలను చర్చిస్తారు.\nSection 2(45) of the Consumer Protection Act 2019 defines 'unfair contract terms' as those causing significant imbalance in parties' rights, contrary to good faith, thereby causing detriment to the consumer. Examples include clauses exempting seller liability, unilateral price adjustment rights, unlimited warranty disclaimers, and mandatory arbitration clauses. The Act shifts the burden to traders to prove contract terms are fair, protecting consumers from oppressive standard form contracts.", 'AP_HC', 'National_Current_Affairs_2026'),

    (31524, "RTI Act 2005 ప్రకారం పబ్లిక్ ఇన్‌ఫర్మేషన్ ఆఫీసర్ (PIO) సమాచారం ఇవ్వడానికి నిర్ధారిత సమయ సూచిక ఏమిటి?\nWhat is the prescribed timeline for a Public Information Officer (PIO) to provide information under the RTI Act 2005?", "A) RTI దరఖాస్తు స్వీకరించిన 10 రోజుల్లో / Within 10 days of receiving the RTI application", "B) RTI దరఖాస్తు స్వీకరించిన 30 రోజుల్లో, 20 రోజులు పొడిగించటానికి వీలుఉంది / Within 30 days of receiving the RTI application, extendable by 20 days", "C) RTI దరఖాస్తు స్వీకరించిన 60 రోజుల్లో / Within 60 days of receiving the RTI application", "D) ఎటువంటి పొడిగింపు అవకాశం లేకుండా 90 రోజుల్లో / Within 90 days without any possibility of extension", 'B', "సమాచారానికి హక్కు చట్టం 2005 యొక్క సెక్షన్ 4(1) PIO డిసెంబర్ RTI దరఖాస్తు స్వీకరణ నుండి 30 రోజుల్లో సమాచారం అందించాలని నిర్దేశిస్తుంది. సెక్షన్ 4(1)(b) ఆ చట్టం ఎందుకని పొడిగించటానికి అనుమతిస్తుంది: (1) రిజిస్టర్ వాల్యూ రిసెర్చ్ అవసరం; (2) ఇతర విభాగాలు లేదా అధికారులు సంపర్కం అవసరం; (3) వ్యక్తిగత డేటా లేదా వాణిజ్య గోపనీయతను కలిగిన సమాచారం కోసం ప్రభావిత మూడవ-పక్ష సంపర్కం. సమిష్టి గరిష్ఠ సమయ సూచిక 50 రోజులు (30 + 20 రోజులు). సమాచార కమిషన్ 50 రోజుల (ఫిర్యాదు సరిసంబంధిత ఉంటే కాకుండా) ఆ సమయ సూచిక ఎక్కువ ఏదైనా ఆలస్యం చెయ్యాలన్న చట్టం ఆ పరిణామం ఇస్తుంది, బీమా గ్రీవ్‌యెన్సెస్ నిర్ణయానికి అప్పీల్ గుర్తించటానికి వీలుపడుతుంది.\nSection 4(1) of the Right to Information Act 2005 prescribes that a PIO must provide information within 30 days of receipt of the RTI application. Section 4(1)(b) allows extension by an additional 20 days in cases involving large volume of records, need for consultation with other departments, or consultations with affected third parties. The combined maximum timeline is therefore 50 days (30 + 20 days). Any delay beyond 50 days constitutes deemed refusal, allowing applicants to appeal to higher authorities.", 'AP_HC', 'National_Current_Affairs_2026'),

    (31525, "జిల్లా వినియోగదారు కమిషన్ కీలక బాధ్యతలు ఏవి?\nWhich of the following is a key responsibility of District Consumer Commission?", "A) కేవలం ఉపసంహరణ ఫిర్యాదులను విచారించటం / Hearing withdrawal complaints only", "B) వినియోగదారు ఫిర్యాదులు విచారించటం, నిర్ణయాలను ఇవ్వటం, మరియు రాష్ట్ర కమిషన్‌ను అప్పీల్‌ల నుండి సంవత్సరం చేయటం / Hearing consumer complaints, delivering judgments, and hearing appeals from State Commission", "C) రాష్ట్ర చట్టాలను రూపకల్పనచేయటం / Framing state laws", "D) ఎన్సీడీఆర్‌సీకి సమస్త విషయాలను సమర్పించటం / Submitting all matters to NCDRC", 'B', "జిల్లా వినియోగదారు కమిషన్ కీలక బాధ్యతలు వినియోగదారు ఫిర్యాదులను విచారించటం, సంబంధిత నిర్ణయాలను ఇవ్వటం, రాష్ట్ర కమిషన్ నుండి అప్పీల్ కేసులను వింటూ, మరియు సంబంధిత రకరకపటిల డెలివరీ నిర్ధారణ చేయటం ఉన్నాయి. కమిషన్ Rs. 1 లక్ష కంటే ఎక్కువ కానీ Rs. 1 కోటి వరకు విలువ కలిగిన విషయాలను పరిష్కరిస్తుంది. సెక్షన్ 21 ప్రకారం, జిల్లా కమిషన్‌లు సాధారణంగా 60 రోజుల్లో తీర్పు ఇవ్వాలి. ఎందుకనా రాష్ట్ర కమిషన్ నుండి రిప్లేస్ కేసులను వింటూ, జిల్లా కమిషన్ మరియు ఉప-కమిషన్‌ల అధికారుల సమితిలో అప్పీల్‌ల యొక్క నిర్ణయ నిర్ణయానికి డిలిభర్‌కు బాధ్యత ఉంటుంది.\nThe key responsibilities of District Consumer Commission include hearing consumer complaints, delivering timely judgments (within 60 days), hearing appeals against lower commission orders, and ensuring proper delivery of compensation and remedies. The Commission has jurisdiction over cases valued between Rs. 1 lakh and Rs. 1 crore. According to Section 21, District Commissions must deliver judgments within 60 days from the date of completion of hearing, with possible extension of 30 days in complex cases with recorded reasons.", 'AP_HC', 'National_Current_Affairs_2026'),
]

# Output verification - Sample display
print("BILINGUAL MCQs 31501-31525 - AP_HC FOLDER")
print("=" * 80)
print("\n1. FIRST MCQ (31501):")
print(f"ID: {questions_31501_31525[0][0]}")
print(f"Question (Bilingual): {questions_31501_31525[0][1][:150]}...")
print(f"Category: {questions_31501_31525[0][7]}")

print("\n\n13. MIDDLE MCQ (31513):")
print(f"ID: {questions_31501_31525[12][0]}")
print(f"Question (Bilingual): {questions_31501_31525[12][1][:150]}...")
print(f"Category: {questions_31501_31525[12][7]}")

print("\n\n25. LAST MCQ (31525):")
print(f"ID: {questions_31501_31525[24][0]}")
print(f"Question (Bilingual): {questions_31501_31525[24][1][:150]}...")
print(f"Category: {questions_31501_31525[24][7]}")

print("\n\nTotal MCQs created: " + str(len(questions_31501_31525)))
print("Folder changed to: AP_HC")
print("Format: TELUGU\\nENGLISH bilingual with \\n separator"