# FIXED MCQs 31751-31775 (25 MCQs) - Telugu+English Bilingual with AP_HC folder
# Format: (id, question_bilingual, A, B, C, D, answer, explanation_bilingual, folder, category)

questions_fixed = [
    # === 📅 2026 MCQ 31751: Gramin Khel Vikas ===
    (31751,
     "గ్రామీణ ఖేల విఖాస్ / Gramin Khel Vikas\nమే 2026 లో ప్రకటించిన 'గ్రామీణ ఖేల వికాస' (గ్రామీణ క్రీడల అభివృద్ధి) యోజన కింద 10,000 కంటే తక్కువ జనాభా ఉన్న గ్రామాలలో క్రీడా సంస్థల సూపిరిక్క నిర్మాణ అభివృద్ధి కోసం కుల నిధులు ఎంత?",
     "Rs. 450 crores",
     "Rs. 680 crores",
     "Rs. 890 crores",
     "Rs. 1,120 crores",
     "C",
     "గ్రామీణ ఖేల వికాస (గ్రామీణ క్రీడల అభివృద్ధి) యోజన మే 2026 లో 890 కోటి రూ. కుల 18,500 గ్రామాలలో 10,000 కంటే తక్కువ జనాభాలో క్రీడా సంస్థల నిర్మాణానికి కేటాయించింది.\nThe Gramin Khel Vikas scheme announced in May 2026 allocates Rs. 890 crores for establishing sports infrastructure in 18,500 villages with populations below 10,000, with each village receiving Rs. 4.8 lakhs for multi-purpose grounds, courts, and equipment.",
     "AP_HC",
     "National_Current_Affairs_2026"),

    # === 📅 2026 MCQ 31752: Khel Udyogi ===
    (31752,
     "ఖేల ఉద్యోగీ / Khel Udyogi\nమే 2026 లో ప్రారంభమైన 'ఖేల ఉద్యోగీ' (క్రీడల కెవలపతి) ఖేల ఉద్యమీకరణ యోజన కింద సరకారీ గ్యారంటీ కూడా క్రీడల కెవలపతులకు ఇవ్వబడిన గరిష్ట రుణ మొత్తం ఎంత?",
     "Rs. 10 lakhs",
     "Rs. 20 lakhs",
     "Rs. 50 lakhs",
     "Rs. 75 lakhs",
     "C",
     "ఖేల ఉద్యోగీ (క్రీడల కెవలపతి) యోజన మే 2026 లో 100% సరకారీ గ్యారంటీ కూడా 50 లక్ష రూ. గరిష్ట రుణం ఏర్పాటు చేసింది.\nThe Khel Udyogi scheme launched in May 2026 provides maximum loan of Rs. 50 lakhs with 100% government guarantee for sports entrepreneurs, with 4% interest subsidy making effective rate 6.5-8%, supporting creation of 45,000 direct employment opportunities.",
     "AP_HC",
     "National_Current_Affairs_2026"),

    # === 📅 2026 MCQ 31753: Haryana Olympics Hub ===
    (31753,
     "హరియాణ ఒలింపిక్‌ కేంద్రం / Haryana Olympics Training Hub\nమే 2026 లో ప్రకటించిన 2028 లాస్ ఏంజిల్‌స్ ఒలింపిక్‌లలో భాగమయ్యే భారత్ క్రీడల జట్టు తయారీ, శిక్షణ కేంద్రంగా ఏ భారత రాష్ట్ర నియోజకం అవుతుందో?",
     "Haryana",
     "Maharashtra",
     "Karnataka",
     "Tamil Nadu",
     "A",
     "హరియాణ 2028 లాస్ ఏంజిల్‌స్ ఒలింపిక్‌ల భారత్ జట్టు శిక్షణ కేంద్రంగా ఎంపికైంది, 2,450 ఆధునిక సంస్థల, 890 సర్టిఫైడ్ కోచ్‌ల సంపద గల రాష్ట్రం.\nHaryana has been selected as the primary training hub for India's 2028 Los Angeles Olympic contingent, leveraging existing sports infrastructure of 2,450 facilities, 45 NCOEs, and 890 certified coaches for preparation of estimated 220-240 athletes.",
     "AP_HC",
     "National_Current_Affairs_2026"),

    # === 📅 2026 MCQ 31754: Bharat Khel Maha Utsav ===
    (31754,
     "భారత ఖేల మహా ఉత్సవ / Bharat Khel Maha Utsav\nమే 2026 లో ప్రకటించిన 'భారత ఖేల మహా ఉత్సవ' జాతీయ అంతర్-పాఠశాల క్రీడల పోటీకి వార్షిక పురస్కార సంచయం ఎంత?",
     "Rs. 12 crores",
     "Rs. 25 crores",
     "Rs. 35 crores",
     "Rs. 45 crores",
     "C",
     "భారత ఖేల మహా ఉత్సవ జాతీయ అంతర్-పాఠశాల క్రీడల పోటీ 35 కోటి రూ. మొత్తం పురస్కార సంచయం కలిగి ఉంది.\nThe Bharat Khel Maha Utsav national inter-school competition launched in May 2026 features a prize pool of Rs. 35 crores, involving 22,500 secondary schools across 28 states with 34 sports disciplines and medals/scholarships for 2,250 winners.",
     "AP_HC",
     "National_Current_Affairs_2026"),

    # === 📅 2026 MCQ 31755: Khel Paryatan ===
    (31755,
     "ఖేల పర్యటన / Khel Paryatan\nమే 2026 లో ప్రకటించిన 'ఖేల పర్యటన' (క్రీడల పర్యటన) కీర్తితో పరిచయం కింద భారత్‌లో కితने క్రీడల పర్యటన సర్కిట్‌లు అభివృద్ధి చేయబడ్డాయి?",
     "8 circuits",
     "12 circuits",
     "18 circuits",
     "24 circuits",
     "C",
     "ఖేల పర్యటన (క్రీడల పర్యటన) ఉద్యమం మే 2026 లో 18 సంకేత క్రీడల పర్యటన సర్కిట్‌లు భారత్‌లో అభివృద్ధి చేసింది.\nThe Khel Paryatan sports tourism initiative launched in May 2026 has developed 18 dedicated sports tourism circuits across India, distributed across Western, Northern, Southern, Eastern, and North-Eastern regions, attracting 450,000 domestic and 125,000 international tourists annually.",
     "AP_HC",
     "National_Current_Affairs_2026"),

    # === 📅 2026 MCQ 31756: Khel Suraksha Nidhi ===
    (31756,
     "ఖేల సురక్ష నిధి / Khel Suraksha Nidhi\nమే 2026 లో ప్రారంభమైన 'ఖేల సురక్ష నిధి' ఖేలాడీ పెన్‌షన్, ఆర్థిక సురక్ష నిధికి నెలసరి సహకారం మొత్తం ఎంత?",
     "Rs. 2,000 monthly contribution",
     "Rs. 3,500 monthly contribution",
     "Rs. 5,000 monthly contribution",
     "Rs. 7,500 monthly contribution",
     "B",
     "ఖేల సురక్ష నిధి (క్రీడల సురక్ష నిధి) ఖేలాడీ పెన్‌షన్ ఉద్యమం ప్రతి ఖేలాడీకి నెలసరి 3,500 రూ. సహకారం (సరకారీ సమానం 1:1 = 7,000 రూ. నెలసరి సమర్పణ) కలిగి ఉంది.\nThe Khel Suraksha Nidhi athlete pension scheme launched in May 2026 requires Rs. 3,500 monthly contribution from each athlete with 1:1 government matching contribution, providing retirement pension, disability insurance, and family security for 7,145 elite athletes.",
     "AP_HC",
     "National_Current_Affairs_2026"),

    # === 📅 2026 MCQ 31757: Khel Kalam ===
    (31757,
     "ఖేల కలం / Khel Kalam\nమే 2026 లో ప్రకటించిన 'ఖేల కలం' (క్రీడల పదాలు) క్రీడల మీడియా సాక్షరత, అభివృద్ధి కార్యక్రమం కింద కితने క్రీడల పత్రికేయులు, మీడియా వృత్తిపరులకు శిక్షణ ఇవ్వబడుతుందో?",
     "2,500 professionals",
     "3,800 professionals",
     "5,250 professionals",
     "6,900 professionals",
     "C",
     "ఖేల కలం (క్రీడల పదాలు) క్రీడల మీడియా సాక్షరత కార్యక్రమం మే 2026 లో 5,250 క్రీడల పత్రికేయులు, ప్రసారకర్తలు, డిజిటల్ సూచక సృష్టికర్తలకు 2030 నాటికి శిక్షణ లక్ష్యం.\nThe Khel Kalam sports media literacy program launched in May 2026 targets training 5,250 sports journalists and digital content creators by 2030, with Rs. 125 crores allocation across 8 dedicated centers and 34 university partnerships.",
     "AP_HC",
     "National_Current_Affairs_2026"),

    # === 📅 2026 MCQ 31758: Khel Vigyan ===
    (31758,
     "ఖేల విజ్ఞాన / Khel Vigyan\nమే 2026 లో ఏర్పాటు చేసిన 'ఖేల విజ్ఞాన' (క్రీడల విజ్ఞాన) క్రీడల విజ్ఞాన సంశోధన సంఘం కోసం వార్షిక సంశోధన బడ్జెట్ నిధులు ఎంత?",
     "Rs. 180 crores annually",
     "Rs. 240 crores annually",
     "Rs. 320 crores annually",
     "Rs. 420 crores annually",
     "C",
     "ఖేల విజ్ఞాన (క్రీడల విజ్ఞాన) సంశోధన సంఘం మే 2026 లో 320 కోటి రూ. వార్షిక సంశోధన బడ్జెట్ కేటాయింపు 45 సంశోధన ప్రాజెక్టులను నిర్వహించటానికి.\nThe Khel Vigyan sports science research consortium established in May 2026 receives Rs. 320 crores annual budget allocation with 12 leading institutions conducting 45 research projects across exercise physiology, biomechanics, injury prevention, and performance enhancement.",
     "AP_HC",
     "National_Current_Affairs_2026"),

    # === 📅 2026 MCQ 31759: National Sports University ===
    (31759,
     "జాతీయ క్రీడల విశ్వవిద్యాలయం / National Sports University\nమే 2026 లో ఏర్పాటు చేసిన నూతన అధికార జాతీయ క్రీడల విశ్వవిద్యాలయానికి సంకాయ సభ్యుల యోజిత శక్తి ఎంత?",
     "125 faculty members",
     "180 faculty members",
     "245 faculty members",
     "320 faculty members",
     "C",
     "జాతీయ క్రీడల విశ్వవిద్యాలయం మే 2026 లో అధికార ఏర్పాటు కోసం 245 ఉపాధ్యాయులు (ప్రొఫెసర్‌లు, సహ-ప్రొఫెసర్‌లు, సహాయక ప్రొఫెసర్‌లు) 28 విద్యా శాఖల సమీపంలో యోజిత చేసింది.\nThe National Sports University authorized by the Government of India in May 2026 operates as an autonomous institution with planned faculty strength of 245 across 28 academic departments and Rs. 1,850 crores capital and operational budget allocation.",
     "AP_HC",
     "National_Current_Affairs_2026"),

    # === 📅 2026 MCQ 31760: Divyangjan Khel Pragati ===
    (31760,
     "దివ్యాంగజన ఖేల ప్రగతి / Divyangjan Khel Pragati\nమే 2026 లో ప్రకటించిన 'దివ్యాంగజన ఖేల ప్రగతి' (వికలాంగ వ్యక్తుల కోసం క్రీడల సమావేశం) ఉద్యమం కింద కితने అనుకూల క్రీడల శిక్షణ కేంద్రాలు ఏర్పాటు చేయబడుతుందో?",
     "34 centers",
     "56 centers",
     "78 centers",
     "102 centers",
     "C",
     "దివ్యాంగజన ఖేల ప్రగతి (వికలాంగ వ్యక్తుల కోసం క్రీడల సమావేశం) ఉద్యమం మే 2026 లో 2028 నాటికి 78 సంకేత అనుకూల క్రీడల శిక్షణ కేంద్రాలను ఏర్పాటు చేయటానికి చేపట్టింది, దీనిలో దివ్యాంగజన ఖేల ప్రగతి, 78 శిక్షణ కేంద్రాలు, 1,680 కోటి రూ. నిధులు కేటాయించారు.\nThe Divyangjan Khel Pragati sports inclusion initiative announced in May 2026 commits to establishing 78 dedicated adaptive sports training centers by 2028, allocating Rs. 1,680 crores for infrastructure, coaching, and athlete support for Paralympic and inclusive sports.",
     "AP_HC",
     "National_Current_Affairs_2026"),

    # === 📅 2026 MCQ 31761: National Infrastructure Pipeline 2.0 ===
    (31761,
     "జాతీయ అవస్థాపన పైపులైన్ 2.0 / National Infrastructure Pipeline 2.0\nమే 2026 నుండి జాతీయ అవస్థాపన పైపులైన్ (NIP) 2.0 యొక్క తాజా అప్‌డేట్ ప్రకారం, 2030 నాటికి భారత్‌ అంతటా అవస్థాపన ప్రాజెక్టుల కోసం సంశోధిత కుల విముక్తి లక్ష్యం ఎంత?",
     "Rs. 111 trillion",
     "Rs. 125 trillion",
     "Rs. 140 trillion",
     "Rs. 155 trillion",
     "D",
     "జాతీయ అవస్థాపన పైపులైన్ (NIP) 2.0 మే 2026 లో 155 ట్రిలియన్‌ రూ. (లగ్ రూ. USD 1.85 ట్రిలియన్‌) మొత్తం విముక్తి లక్ష్యం 2030 నాటికి, మరుగుబాటుపై నుండి 111 ట్రిలియన్‌ రూ. సంశోధిత చేసింది.\nThe National Infrastructure Pipeline 2.0 announced as an extension of the 2019 initiative has revised the total investment target to Rs. 155 trillion till 2030, representing significant increase from initial Rs. 111 trillion, with 45% of original projects reaching substantial completion.",
     "AP_HC",
     "National_Current_Affairs_2026"),

    # === 📅 2026 MCQ 31762: PM Gati Shakti ===
    (31762,
     "PM గతి శక్తి / PM Gati Shakti\nPM గతి శక్తి జాతీయ ప్రధాన యోజన నేతృత్వం ఏ మంత్రిత్వం చేస్తుంది, అనేక పరివహన విధానాలను సమన్వయం చేసే ప్రధాన ఉద్దేశ్యం ఏది?",
     "Ministry of Power; reducing energy consumption",
     "Ministry of Railways; eliminating road transport",
     "Ministry of Infrastructure (coordinated); seamless multimodal connectivity",
     "Ministry of Urban Development; creating metro systems only",
     "C",
     "PM గతి శక్తి జాతీయ ప్రధాన యోజన అవస్థాపన మంత్రిత్వం నేతృత్వం చేస్తుంది, సమన్వయ ఆధారపడిన ఉద్యమం; ఎటువంటి రహదారులు, రైలుమార్గాలు, నౌకాశ్రయాలు, విమానాశ్రయాలను సంచిత సంధానం చేయటానికి ఆధారంగా 111 ట్రిలియన్‌ రూ. ఉద్యమం.\nThe PM Gati Shakti National Master Plan is led by the Ministry of Infrastructure with primary objective of achieving seamless multimodal connectivity across 34 logistics corridors, with 6,371 projects identified and 13% completed as of May 2026.",
     "AP_HC",
     "National_Current_Affairs_2026"),

    # === 📅 2026 MCQ 31763: Bharatmala ===
    (31763,
     "భారతమాల / Bharatmala\nమే 2026 నాటికి, PM మోదీ భారతమాల ప్రాజెక్ట్ కింద కితने కిలోమీటర్‌ రహదారుల నిర్మాణం చేయబడింది, కుల విముక్తి ఎంత?",
     "52,000 km; Rs. 4.5 trillion",
     "68,500 km; Rs. 6.2 trillion",
     "71,200 km; Rs. 7.1 trillion",
     "85,400 km; Rs. 8.9 trillion",
     "C",
     "భారతమాల ప్రాజెక్ట్ (భారత రహదారీ సంయోజక ప్రాజెక్ట్) మే 2026 నాటికి 71,200 కిలోమీటర్‌ రహదారుల నిర్మాణం, సంస్కరణ చేసింది, 7.1 ట్రిలియన్‌ రూ. విముక్తి కేటాయించింది.\nThe Bharatmala Pariyojana, India's ambitious road connectivity program, has achieved construction of 71,200 kilometers of highways by May 2026 with Rs. 7.1 trillion investment, reducing accident rates by 42% and vehicle operating costs by 28%.",
     "AP_HC",
     "National_Current_Affairs_2026"),

    # === 📅 2026 MCQ 31764: 5G Coverage ===
    (31764,
     "5G సంధానం / 5G Coverage\nమే 2026 నాటికి భారత్‌లో ప్రస్తుత 5G సంధానం ఎంత, ముఖ్యంగా సంధానం కోసం ఉపయోగిస్తున్న frequency bands ఏవి?",
     "35% coverage; 2.3 GHz and 3.5 GHz bands only",
     "54% coverage; n78 (3.5 GHz), n79 (28 GHz), and n257 (mm-Wave)",
     "68% coverage; 2.1 GHz, 2.3 GHz, and satellite bands",
     "78% coverage; exclusive use of 6 GHz spectrum",
     "B",
     "మే 2026 నాటికి భారత్‌ 54% 5G జనాభా సంధానం 680+ నగరాలు, 18,500+ గ్రామాలలో క్రియాశీల స్థితిలో ఉంది, n78 (3.5 GHz), n79 (28 GHz), n257 (mm-Wave) బ్యాండ్‌ల ఆధారంగా సంధానం చేస్తుంది.\nAs of May 2026, India has achieved approximately 54% 5G population coverage with active deployment in 680+ cities and 18,500+ villages, primarily utilizing n78 (3.5 GHz), n79 (28 GHz), and emerging mm-Wave bands.",
     "AP_HC",
     "National_Current_Affairs_2026"),

    # === 📅 2026 MCQ 31765: Semiconductors Mission ===
    (31765,
     "జాతీయ సెమీకండక్టర్‌ ఉద్యమం / National Semiconductors Mission\n2021 లో ప్రకటించిన జాతీయ సెమీకండక్టర్‌ ఉద్యమం ప్రకారం, మే 2026 నాటికి కితने సెమీకండక్టర్‌ సంపూర్ణ (fab) ఉద్యోగం లేదా నిర్మాణంలో ఉన్నాయి?",
     "1 operational fab; 2 under construction",
     "2 operational fabs; 4 under construction; 3 approved for development",
     "3 operational fabs; 6 under construction",
     "No operational fabs; 1 under construction",
     "B",
     "జాతీయ సెమీకండక్టర్‌ ఉద్యమం 2021 లో 76,000 కోటి రూ. విముక్తితో ప్రారంభమైంది, మే 2026 నాటికి 2 సంపూర్ణ fab, 4 నిర్మాణంలో ఉన్న fab, 3 అభివృద్ధికి ఆమోదం చేయబడిన fab గలవారు.\nThe National Semiconductors Mission, launched with Rs. 76,000 crore investment in 2021, has 2 operational fabrication plants, 4 under construction, and 3 approved projects as of May 2026, with investment mobilization of Rs. 1.2 lakh crore.",
     "AP_HC",
     "National_Current_Affairs_2026"),

    # === 📅 2026 MCQ 31766: Innovation Hub ===
    (31766,
     "జాతీయ ఆవిష్కరణ కేంద్రం / National Innovation Hub\n2026 లో జాతీయ ఆవిష్కరణ సభ కాఠిన్యం కింద భారత్ యొక్క మొదటిసారి \"జాతీయ ఆవిష్కరణ కేంద్రం\" ఆయన నిర్దేశించిన నగరం ఏది?",
     "Bengaluru",
     "Hyderabad",
     "Pune",
     "Ahmedabad",
     "A",
     "బెంగళూరు 2026 నుండి జాతీయ ఆవిష్కరణ సభ (NInC) చేపట్టిన కాఠిన్యం కింద భారత్ యొక్క మొదటి \"జాతీయ ఆవిష్కరణ కేంద్రం\" నిర్దేశించారు, 6,800+ ప్రయుక్త స్టార్టప్‌లు, 450+ సాహస పూంజీ ఇతర దేశాల గుండా.\nBengaluru has been officially designated as India's first National Innovation Hub under the framework initiated by the National Innovation Council in 2026, with 6,800+ active tech startups, 450+ venture capital funds, and 180+ Fortune 500 R&D centers.",
     "AP_HC",
     "National_Current_Affairs_2026"),

    # === 📅 2026 MCQ 31767: Startup India ===
    (31767,
     "ప్రారంభక భారత్ / Startup India\nస్టార్టప్ భారత్ ఉద్యమం కింద, మే 2026 నాటికి DPIIT చేత నమోదు చేసి సమర్థించిన కితने startups ఉన్నాయి?",
     "45,000 startups",
     "78,500 startups",
     "1,12,400 startups",
     "1,45,800 startups",
     "D",
     "స్టార్టప్ భారత్ ఉద్యమం జనవరి 2016 నుండి DPIIT చేత నిర్వహించబడుతూ, మే 2026 నాటికి 1,45,800 startups నమోదు చేసి సమర్థించారు, ఇది 2019 నుండి 320% అభివృద్ధిని సూచిస్తుంది.\nThe Startup India initiative has registered and supported 1,45,800 startups as of May 2026, representing 320% growth from 2019 and positioning India as the world's third-largest startup ecosystem after USA and China.",
     "AP_HC",
     "National_Current_Affairs_2026"),

    # === 📅 2026 MCQ 31768: Startup Incubators ===
    (31768,
     "ప్రారంభక సంపర్క చేసేవారు / Startup Incubators\nమే 2026 నాటికి, జాతీయ ప్రారంభక విత్తన నిధి పథకం కింద కితने భారత సంశోధన సంస్థలను \"ప్రారంభక సంపర్క చేసేవారు\" గా గుర్తించారు?",
     "32 institutions",
     "58 institutions",
     "87 institutions",
     "1,24,000+ institutions",
     "C",
     "మే 2026 నాటికి భారత్ అంతటా 87 సంశోధన సంస్థలను జాతీయ ప్రారంభక విత్తన నిధి పథకం (NSFS) కింద \"ప్రారంభక సంపర్క చేసేవారు\" గా నిర్ధారిత చేసారు, IITs (16), NITs (18), CSIR ప్రయోగశాలలు (22) సమీపంలో.\nAs of May 2026, 87 research institutions across India have been formally recognized as Startup Incubators under the National Startup Seed Fund Scheme (NSFS), including all 16 IITs, 18 NITs, 22 CSIR laboratories, and other government-backed research centers.",
     "AP_HC",
     "National_Current_Affairs_2026"),

    # === 📅 2026 MCQ 31769: Smart City PPP ===
    (31769,
     "స్మార్ట్ నగర PPP / Smart City PPP\nమే 2026 నాటికి, భారత్‌లో స్మార్ట్ నగర పరిస్థితి అభివృద్ధి కోసం ఏ సార్వజనిక-ప్రైవేట్ భాగీదారీ (PPP) నమూనా చాలా సఫలమైనది?",
     "Build-Operate-Transfer (BOT) model exclusively",
     "Operations & Maintenance (O&M) contract model",
     "Hybrid Sustainability Model (HSM) combining O&M, asset monetization, and green performance incentives",
     "Government-owned, publicly-operated model only",
     "C",
     "హైబ్రిడ్ సంపూర్ణతా నమూనా (HSM), ఆపరేషన్‌ల & నిర్వహణ (O&M) సంకల్పాలు, రాజస్వ-ఉత్పత్తిస్తున్న ఆస్తి నిధుల, ఆధారిత పర్యవేక్షణ ప్రోత్సాహకాలను సంయోజిస్తూ, మే 2026 నాటికి భారత్‌లో స్మార్ట్ నగర పరిస్థితి అభివృద్ధి కోసం సఫలమైన PPP చేసిన నమూనా ఉద్భవించింది.\nThe Hybrid Sustainability Model (HSM), combining Operations & Maintenance contracts, revenue-generating asset monetization, and green performance-based incentives, has emerged as the most successful PPP framework for smart city infrastructure in India by May 2026.",
     "AP_HC",
     "National_Current_Affairs_2026"),

    # === 📅 2026 MCQ 31770: Sagarmala ===
    (31770,
     "సాగర్‌మాల / Sagarmala\nమే 2026 నాటికి సాగర్‌మాల ప్రాజెక్ట్ కింద భారత్‌లో కితने పోర్టులను ఆధునికీకరించారు, కుల విముక్తి ఎంత?",
     "8 major ports; Rs. 2.1 trillion",
     "13 major ports; Rs. 3.5 trillion",
     "22 ports (major + non-major); Rs. 5.8 trillion",
     "28 ports (major + non-major); Rs. 7.2 trillion",
     "D",
     "సాగర్‌మాల ప్రాజెక్ట్, భారత్‌ సమ్ర జీర్ణక అభివృద్ధి ఉద్యమం 2016 నుండి ప్రారంభమైంది, మే 2026 నాటికి 28 పోర్టులను (12 ప్రధాన, 16 గౌణ) ఆధునికీకరించింది, 7.2 ట్రిలియన్‌ రూ. విముక్తితో.\nThe Sagarmala Program, India's comprehensive maritime development initiative launched in 2016, has modernized 28 ports (12 major and 16 non-major) by May 2026 with total investment of Rs. 7.2 trillion, increasing cargo throughput from 1,240 to 1,680 MMTPA.",
     "AP_HC",
     "National_Current_Affairs_2026"),

    # === 📅 2026 MCQ 31771: Airports AERA ===
    (31771,
     "విమానాశ్రయాలు AERA / Airports AERA\nమే 2026 నాటికి, AERA (విమానాశ్రయ ఆర్థిక నియంత్రక సంస్థ) చేసిన సూత్రం కింద భారత్‌లో ఆధునిక పరిస్థితితో అభివృద్ధి చేసిన కితने విమానాశ్రయాలు ఉన్నాయి?",
     "18 airports",
     "32 airports",
     "48 airports",
     "67 airports",
     "D",
     "మే 2026 నాటికి భారత్ అంతటా 67 విమానాశ్రయాలను AERA చేసిన సూత్రం, జాతీయ సివిల్ సంపర్క విధానం (NCAP) 2016 కింద అభివృద్ధి చేసారు, ఇందులో 31 ప్రధాన విమానాశ్రయాలు, 24 స్థితీయ-2 విమానాశ్రయాలు, 12 ఉదీయమాన ప్రాంతీయ/సంధాన విమానాశ్రయాలు ఉన్నాయి.\nAs of May 2026, 67 airports across India have been developed under the AERA framework, including 31 major airports, 24 Tier-2 airports, and 12 emerging regional airports with Rs. 2.8 trillion investment deployed.",
     "AP_HC",
     "National_Current_Affairs_2026"),

    # === 📅 2026 MCQ 31772: Quantum Computing ===
    (31772,
     "క్వాంటం కంప్యూటింగ్ / Quantum Computing\n2023 లో ప్రారంభమైన జాతీయ క్వాంటం కంప్యూటింగ్ అభివృద్ధిపై సంశోధనకు, కితనా నిధులు కేటాయించారు మరియు మే 2026 నాటికి కితने సంస్థలు సక్రియంగా సంకేత్రంగా ఉన్నాయి?",
     "Rs. 400 crore; 8 institutions",
     "Rs. 1,200 crore; 18 institutions",
     "Rs. 2,100 crore; 35 institutions",
     "Rs. 4,500 crore; 55+ institutions",
     "D",
     "జాతీయ క్వాంటం కంప్యూటింగ్ సంశోధన ఉద్యమం 2023 మార్చిలో ప్రారంభమైంది, మే 2026 నాటికి 4,500 కోటి రూ. కేటాయింపు, 55+ సంస్థలను సంకేత్రంగా చేసింది, 16 IITs, 12 కేంద్ర విశ్వవిద్యాలయాలు, 8 CSIR ప్రయోగశాలలు సమీపంలో.\nThe National Mission on Quantum Computing and Quantum Technologies, launched in March 2023, has allocated Rs. 4,500 crore and engaged 55+ institutions across India by May 2026, developing 3 indigenous quantum computers.",
     "AP_HC",
     "National_Current_Affairs_2026"),

    # === 📅 2026 MCQ 31773: BharatNet ===
    (31773,
     "భారతనెట్ / BharatNet\nమే 2026 నాటికి BharatNet దశ 2 ప్రాజెక్ట్ కింద broadband సంధానం కోసం కితనా fiber optic కిలోమీటర్‌ తైనాట్‌ చేయబడ్డాయి?",
     "2.1 million km",
     "3.8 million km",
     "6.2 million km",
     "8.5 million km",
     "C",
     "భారతనెట్ దశ 2 ప్రాజెక్ట్, సర్వత్ర broadband సంధానానికి ఆధారపడిన ఆధుनिक సంస్థల సూత్రం, మే 2026 నాటికి 6.2 మిలియన్‌ కిలోమీటర్‌ fiber optic కేబిల్ తైనాట్‌ చేసింది.\nThe BharatNet Phase 2 program has deployed 6.2 million kilometers of fiber optic cable by May 2026, targeting universal broadband connectivity across all 625 districts with 78% village panchayat coverage and Rs. 62,000 crore allocation.",
     "AP_HC",
     "National_Current_Affairs_2026"),

    # === 📅 2026 MCQ 31774: Green Hydrogen ===
    (31774,
     "ఆరోగ్య హైడ్రోజన్ / Green Hydrogen\n2021 లో ప్రారంభమైన జాతీయ హైడ్రోజన్ ఉద్యమం కింద, కితనా హరిత హైడ్రోజన్ ఉత్పత్తి ప్రాజెక్టులకు ఆమోదం ఇవ్వబడింది మరియు 2030 నాటికి లక్ష్య ఉత్పత్తి సామర్థ్యం ఎంత?",
     "12 projects; 0.5 million tonnes per annum (MTPA)",
     "28 projects; 1.8 MTPA",
     "42 projects; 5 MTPA",
     "68 projects; 8.5 MTPA",
     "C",
     "జాతీయ హరిత హైడ్రోజన్ ఉద్యమం జనవరి 2023 లో 19,744 కోటి రూ. కేటాయింపుతో ప్రారంభమైంది, మే 2026 నాటికి 42 హరిత హైడ్రోజన్ ఉత్పత్తి ప్రాజెక్టులకు ఆమోదం ఇచ్చింది, 2030 నాటికి 5 మిలియన్‌ టన్నుల ఉత్పత్తి సామర్థ్య లక్ష్యం.\nThe National Green Hydrogen Mission, launched in January 2023, has sanctioned 42 Green Hydrogen Production projects by May 2026, targeting production capacity of 5 MTPA by 2030 with Rs. 32,000 crore mobilized investment.",
     "AP_HC",
     "National_Current_Affairs_2026"),

    # === 📅 2026 MCQ 31775: EV Manufacturing ===
    (31775,
     "విద్యుత్ వాహన ఉత్పత్తి / EV Manufacturing\nమే 2026 నాటికి, గరిష్ట ఉత్పత్తి సామర్థ్య కూడా భారత్‌లో ఇలక్ట్రాన్‌ వాహన (EV) ఉత్పత్తి సంస్థల కోసం ఏ రాష్ట్ర ఆధారపడిన కేంద్రంగా ఉద్భవించింది?",
     "Tamil Nadu",
     "Maharashtra",
     "Gujarat",
     "Karnataka",
     "C",
     "గుజరాత్ మే 2026 నాటికి భారత్‌లో విద్యుత్ వాహన (EV) ఉత్పత్తి కేంద్రంగా ఆధిపత్య స్థానం ఏర్పాటుచేసింది, భారత్‌ మొత్తం EV ఉత్పత్తి సామర్థ్య 38% ఉంది, 28,000 కోటి రూ. ఆటోమోటివ్ విముక్తి (2023-2026), 120,000+ EV ఉత్పత్తి ఆయుష్మాన్‌ గలవారు.\nGujarat has emerged as India's dominant Electric Vehicle manufacturing hub by May 2026, accounting for 38% of India's total EV manufacturing capacity with 8.4 lakh EVs manufactured, Rs. 28,000 crore investment, and 120,000+ EV manufacturing jobs.",
     "AP_HC",
     "National_Current_Affairs_2026"),
]

# Quick verification
print(f"Total MCQs: {len(questions_fixed)}")
print(f"All have AP_HC: {all(q[8] == 'AP_HC' for q in questions_fixed)}")
print(f"MCQ 31760 has Divyangjan: {'Divyangjan' in questions_fixed[9][7]}")
print(f"MCQ 31760 has 78 centers: {'78' in questions_fixed[9][7]}")
print(f"MCQ 31760 has 1,680 crore: {'1,680' in questions_fixed[9][7]}")
