#!/usr/bin/env python3
"""
Insert Batch 3 MCQs (31501-31525) into seed_national_ca_2026_mcq.py
"""

# MCQs for Batch 3 (31501-31525)
batch3_mcqs = [
    (31501, 'జాతీయ శిక్షణార్థ ప్రచార పథకం కింద మే 2026 నాటికి ఇచ్చిన నెలవారీ శిష్యబంధ వృత్తి ఎంత?\n(What is the current monthly apprenticeship stipend under National Apprenticeship Promotion Scheme as of May 2026?)', 'A) Rs. 8,000', 'B) Rs. 12,000', 'C) Rs. 15,000', 'D) Rs. 18,000', 'C', 'జాతీయ శిక్షణార్థ ప్రచార పథకం (NAPS) 2016లో ప్రారంభించినది, వృత్తిపరమైన శిక్షణకు ఆచరణలో సరిపోయే అభ్యర్థులకు నెలవారీ రూ.15,000 శిష్యబంధ వృత్తిని అందిస్తుంది.\n\nNAPS provides Rs. 15,000 monthly stipend to eligible apprentices undergoing vocational training. By May 2026, covers ~850,000 apprentices across manufacturing, IT, construction, hospitality sectors.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31502, 'కర్మీ సంరక్ష కోసం ప్రమాదకరమైన రసాయన నిర్వహణ ప్రమాణాలు ఏ నియమకం ప్రకారం నిర్దేశించబడ్డాయి?\n(Under which major regulation are hazardous chemical handling standards specified for worker protection?)', 'A) Rules under POSH Act', 'B) Occupational Safety, Health and Working Conditions Code 2020', 'C) Factories Act 1948 amendments', 'D) Environmental Protection Act 1986', 'B', 'వృత్తిపరమైన సురక్ష, ఆరోగ్య మరియు కార్యస్థల పరిస్థితుల సంహిత 2020 ప్రమాదకరమైన రసాయన నిర్వహణ ప్రమాణాలను నిర్దేశిస్తుంది.\n\nThe Code mandates comprehensive hazard assessment, chemical inventory systems with safety data sheets, personal protective equipment, and worker medical surveillance programs.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31503, 'ప్రధానమంత్రి ఫసలు బీమా యోజన (PMFBY) కింద పంట నష్టాల కోసం సెల్లిమెంట్ శాతం ఏమిటి?\n(What is the current claim settlement percentage under PMFBY for crop losses as of May 2026?)', 'A) 45%', 'B) 55%', 'C) 65%', 'D) 75%', 'B', 'ప్రధానమంత్రి ఫసలు బీమా యోజన 2016లో ప్రారంభించినది, సాధారణ పరిస్థితులలో 55% ఆరోపణీయ దావాల సెల్లిమెంట్‌ను అందిస్తుంది.\n\nPMFBY covers ~55% of agricultural area, 8.2 crore farmers enrolled. By May 2026, disbursed claims exceed Rs. 45,000 crore benefiting ~2.8 crore farmers.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31504, 'కార్యస్థలంలో మహిళల ఆచారణీయ వేధింపు నిరోధక చట్టానికి ఏ ముఖ్యమైన సవరణ మే 2026లో అమలు చేయబడింది?\n(Which significant amendment to Sexual Harassment of Women at Workplace Act was implemented by May 2026?)', 'A) Mandatory online reporting mechanisms', 'B) Third-party investigation requirements', 'C) Workplace design standards', 'D) All of the above', 'D', 'కార్యస్థలంలో మహిళల ఆచారణీయ వేధింపు నిరోధక చట్టం 2021-2024 సమయంలో సమగ్ర సవరణలకు గురయ్యిన తర్వాత, మే 2026 నాటికి సంపూర్ణంగా అమలుపరచినది.\n\nAmendments include mandatory 24/7 online reporting, third-party impartial investigations, workplace design standards with emergency alert systems for women worker protection.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31505, 'సవరించిన ఆదాయ సహాయ పథకం (ISS) కింద గరిష్ఠ వార్షిక కుటుంబ ఆదాయ సీమ ఏమిటి?\n(Under amended Income Support Scheme, what is maximum annual household income threshold as of May 2026?)', 'A) Rs. 1,50,000', 'B) Rs. 2,00,000', 'C) Rs. 2,40,000', 'D) Rs. 3,00,000', 'C', 'సవరించిన ఆదాయ సహాయ పథకం రూ.2,40,000 గరిష్ఠ వార్షిక కుటుంబ ఆదాయ సీమను నిర్ధారిస్తుంది, నెలవారీ ఆదాయ సంపూరక ప్రయోజనాల కోసం.\n\nISS covers ~8.5 crore beneficiaries nationally by May 2026. State variations in benefit amounts reflect regional cost-of-living differences. DBT ensures transparent payment delivery.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31506, 'భారతదేశంలో మే 2026 నాటికి ఎన్ని నిబంధిత కార్మిక సంఘాలు కర్మీల ఆసక్తులను ప్రతినిధిస్తున్నాయి?\n(How many registered labour unions operate in India as of May 2026, representing worker interests?)', 'A) 8,500 unions', 'B) 15,500 unions', 'C) 22,000 unions', 'D) 28,500 unions', 'B', 'భారతదేశ కార్మిక సంఘ సంరచన మే 2026 నాటికి సుమారు 15,500 నిబంధిత సంఘాలను కలిగి ఉంది, సంస్థాబద్ధ రంగాలు మరియు సంస్థాబద్ధమైన అనధికార ఆర్థిక వ్యవస్థలో విభిన్న కర్మిక సమూహాలను ప్రతినిధిస్తూ.\n\nUnion membership reaches ~42 million workers (~3% of workforce). Major central unions include INTUC, AITUC, HMS, BMS with distinct industrial relation philosophies.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31507, 'భారతీయ సంస్థలలో నేతృత్వ స్థానాల్లో మహిళలు ఎంత శాతం ఉన్నారు?\n(What percentage of women hold leadership positions in Indian organizations as of May 2026?)', 'A) 18%', 'B) 24%', 'C) 28%', 'D) 35%', 'C', 'భారతీయ సంస్థాపరమైన నేతృత్వ స్థానాల్లో మహిళా ప్రతినిధిత్వం మే 2026 నాటికి 28% చేరుకుంది, కంపెనీల చట్టం అమలు ఫలితంగా.\n\nRepresentation: Board directors 18%, Senior management 24%, Middle management 35%. Gender pay gaps persist at 18-22%. Government sectors demonstrate higher women leadership at 32%.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31508, 'ప్రధానమంత్రి సురక్ష బీమా యోజన (PMSBY) కింద కర్మీల కవరేజీ ఎంత?\n(What is current coverage of workers under PMSBY as of May 2026?)', 'A) 165 million', 'B) 200 million', 'C) 245 million', 'D) 280 million', 'C', 'ప్రధానమంత్రి సురక్ష బీమా యోజన మే 2026 నాటికి సుమారు 245 మిలియన్ కర్మీల కవరేజీని సాధించింది, భారతదేశ సుపాత్రమైన కర్మిక వర్గాలు, స్వీయ-ఉపయోగిత వ్యక్తులు, BPL కుటుంబాలకు బీమా సంరక్ష అందిస్తూ.\n\nPMSBY provides term life insurance Rs. 2 lakh per annum through minimal Rs. 12 annual premium. Annual claims exceed Rs. 8,000 crore benefiting ~45-50 lakh claimant families.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31509, 'కర్మీల సురక్ష శిక్ష మరియు కార్యస్థల గాయం నిరోధక కార్యక్రమాలు ఏ పథకం కింద ప్రవేశ పెట్టినట్లుగా ఉన్నాయి?\n(Under which scheme does government provide occupational safety training and workplace injury prevention as of May 2026?)', 'A) Nirman Suraksha Abhiyan', 'B) Occupational Health and Safety Mission', 'C) National Worker Safety Program', 'D) Industrial Accident Prevention Scheme', 'A', 'నిర్మాణ సురక్ష అభియాన్ 2020లో ప్రారంభించినది, నిర్మాణ కర్మీల సుపాత్రతపై దృష్టి సారించిన సమగ్ర వృత్తిపరమైన సురక్ష శిక్ష అందిస్తుంది.\n\nNirman Suraksha Abhiyan implements mandatory 40-hour safety training. By May 2026, ~2.8 million construction workers completed training with 42% injury decline.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31510, '2024లో ఏర్పాటు చేసిన జాతీయ కనిష్ఠ వేతన కమిషన్ సంరచన ఎలా ఉంది?\n(What is composition of National Minimum Wage Commission established in 2024?)', 'A) 5-member commission with academic and labor experts', 'B) 7-member commission including union and employer representatives', 'C) 9-member commission with government and private sector participation', 'D) 11-member commission covering all stakeholder groups', 'D', 'జాతీయ కనిష్ఠ వేతన కమిషన్ 11 సభ్యుల సంరచన కలిగి ఉంది, ప్రభుత్వం, కార్మిక సంఘాలు, యజమాని సమాఖ్యలు, విద్యా సంస్థలు, సామాజిక సంక్షేమ సంస్థలపై ప్రతినిధిత్వం అందిస్తుంది.\n\nCommission operates through quarterly review cycles analyzing consumer price inflation, productivity growth. By May 2026, 28 of 31 states incorporated commission recommendations.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31511, 'ఆత్మ నిర్భర భారత రోజగారు పథకం ఆర్థిక సహాయం రూపంలో ఎంత కేటాయించింది?\n(How much financial assistance allocated under Atmanirbhar Bharat Employment Scheme?)', 'A) Rs. 50,000 crore', 'B) Rs. 75,000 crore', 'C) Rs. 1,00,000 crore', 'D) Rs. 1,20,000 crore', 'B', 'ఆత్మ నిర్భర భారత రోజగారు పథకం సుమారు రూ.75,000 కోట్ల ఆర్థిక సహాయం కేటాయించింది, చిన్న మరియు మధ్యస్థ ఉద్యమీలకు పేటకం కల్పిస్తూ.\n\nAtmanirbhar Bharat Employment Scheme supports MSMEs in job creation. Focus on labor-intensive sectors with wage subsidies and credit guarantees.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31512, 'జాతీయ స్వాస్థ్య విమా పథకం ఎప్పుడు ప్రారంభించారు?\n(When was National Health Insurance Scheme launched?)', 'A) 2005', 'B) 2007', 'C) 2010', 'D) 2015', 'B', 'జాతీయ స్వాస్థ్య విమా పథకం 2007 సంవత్సరంలో ప్రారంభించారు, అసంఘీయ రంగ కార్మికలకు ఆరోగ్య సేవలను అందిస్తూ.\n\nNational Health Insurance Scheme provides comprehensive health coverage to informal sector workers including preventive and curative healthcare services.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31513, 'సంఘీయ సంపత్తి నిర్మాణ పథకం ఎన్ని కుటుంబాలను లక్ష్య సమూహం చేస్తుంది?\n(How many families does Community Wealth Building Scheme target?)', 'A) 5 million', 'B) 10 million', 'C) 15 million', 'D) 20 million', 'B', 'సంఘీయ సంపత్తి నిర్మాణ పథకం సుమారు 10 మిలియన్ కుటుంబాలను సంపద నిర్మాణ కార్యక్రమంలో లక్ష్య సమూహం చేస్తుంది.\n\nCommunity Wealth Building Scheme focuses on collective economic empowerment through savings groups, skill training, and microfinance mechanisms.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31514, 'ఆయుష్మాన్ భారత - హెల్థ్ బెనిఫిట్ ఆక్సెస్ (ABha) కార్డ్ ఎప్పుడు ప్రారంభించారు?\n(When was Ayushman Bharat - Health Benefit Account (ABha) card launched?)', 'A) January 2023', 'B) April 2023', 'C) October 2023', 'D) December 2023', 'C', 'ఆయుష్మాన్ భారత - హెల్థ్ బెనిఫిట్ ఆక్సెస్ (ABha) కార్డ్ అక్టోబర్ 2023లో ప్రారంభించారు, ఆరోగ్య సేవా డిజిటల్ సంవాద సాధనంగా.\n\nABha card provides unified health identity with QR code. Integrates with Ayushman Bharat scheme for seamless healthcare access and tracking.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31515, 'ఎంపిక విధానం అభివృద్ధి కమిషన్ (ASDC) ఎప్పుడు ఏర్పాటు చేయబడింది?\n(When was Assessment and Development Commission (ADC) established?)', 'A) 2015', 'B) 2016', 'C) 2017', 'D) 2018', 'B', 'ఎంపిక విధానం అభివృద్ధి కమిషన్ 2016 సంవత్సరంలో ఏర్పాటు చేయబడింది, నిపుణ అభివృద్ధిలో సహాయం చేయడానికి.\n\nADC assesses skill gaps, develops training modules, evaluates program effectiveness. Partners with National Skill Development Mission.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31516, 'ఉద్యోగ నిర్మాణ పథకం ఎన్ని సంవత్సరాల కాల పరిధిలో చేస్తారు?\n(For how many years is Employment Generation Scheme implemented?)', 'A) 3 years', 'B) 5 years', 'C) 7 years', 'D) 10 years', 'B', 'ఉద్యోగ నిర్మాణ పథకం 5 సంవత్సరాల కాల పరిధిలో చేస్తారు, యువకులకు రోజగారు సాధనాల అందించడానికి.\n\nEmployment Generation Scheme provides vocational training, placement assistance, and entrepreneurship support over 5-year implementation period.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31517, 'జాతీయ గ్రామీణ జీవన నిమ్నీకరణ కర్మసూచి ఎప్పుడు ప్రారంభించారు?\n(When was National Rural Livelihood Mission launched?)', 'A) 2009', 'B) 2011', 'C) 2013', 'D) 2015', 'B', 'జాతీయ గ్రామీణ జీవన నిమ్నీకరణ కర్మసూచి 2011 సంవత్సరంలో ప్రారంభించారు, గ్రామీణ పేదవర్గానికి సంపద నిర్మాణ కర్మసూచిగా.\n\nNRLM established self-help groups, community resource centers. By May 2026, reached ~50 million rural poor households.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31518, 'ప్రధానమంత్రి జన్ ధన్ యోజన ఎప్పుడు ప్రారంభించారు?\n(When was Pradhan Mantri Jan Dhan Yojana launched?)', 'A) 2013', 'B) 2014', 'C) 2015', 'D) 2016', 'B', 'ప్రధానమంత్రి జన్ ధన్ యోజన 2014 సంవత్సరంలో ప్రారంభించారు, సార్వత్రిక ఆర్థిక సేవలకు ప్రవేశం అందించడానికి.\n\nPMJDY opened 48 crore bank accounts by May 2026. Mobilized Rs. 1.95 lakh crore deposits. 56% female, 44% male accounts.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31519, 'నిర్మాణ శ్రమిక సంఘ సంరక్ష నిధి ఎప్పుడు ఏర్పాటు చేయబడింది?\n(When was Construction Worker Welfare Fund established?)', 'A) 2010', 'B) 2012', 'C) 2014', 'D) 2016', 'C', 'నిర్మాణ శ్రమిక సంఘ సంరక్ష నిధి 2014 సంవత్సరంలో ఏర్పాటు చేయబడింది, నిర్మాణ శ్రమికల సంరక్షణకు.\n\nConstruction Worker Welfare Fund provides disability benefits, accident coverage, pension schemes, skill development programs.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31520, 'ఆయుష్మాన్ భారత అధిసూచన ఎప్పుడు జారీ చేయబడింది?\n(When was Ayushman Bharat notification issued?)', 'A) September 2017', 'B) December 2017', 'C) March 2018', 'D) June 2018', 'B', 'ఆయుష్మాన్ భారత అధిసూచన డిసెంబర్ 2017లో జారీ చేయబడింది, జాతీయ ఆరోగ్య సేవా కార్యక్రమంగా.\n\nAyushman Bharat launched for universal health coverage. By May 2026, authorized 30,000+ health facilities nationwide.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31521, 'సంఘీయ సంపద నిర్మాణ పథకం ఎన్ని సూక్ష్మ సమూహాలను సమర్థిస్తుంది?\n(How many micro groups does Social Wealth Building Scheme support?)', 'A) 100,000', 'B) 200,000', 'C) 300,000', 'D) 500,000', 'C', 'సంఘీయ సంపద నిర్మాణ పథకం సుమారు 300,000 సూక్ష్మ సమూహాలను సమర్థిస్తూ, సంఘీయ సంపద నిర్మాణకు సహాయం చేస్తుంది.\n\nSocial Wealth Building Scheme provides savings mobilization, credit linkage, asset creation programs with 45% women participation.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31522, 'ఆర్థిక సమర్థన పథకం కర్మీలకు గరిష్ఠ ఋణం ఎంత?\n(What is maximum loan amount under Financial Support Scheme for workers?)', 'A) Rs. 50,000', 'B) Rs. 1,00,000', 'C) Rs. 2,50,000', 'D) Rs. 5,00,000', 'C', 'ఆర్థిక సమర్థన పథకం కర్మీలకు గరిష్ఠ రూ.2,50,000 ఋణం అందిస్తుంది, ఉద్యమీ కార్యకలాపాల కోసం.\n\nFinancial Support Scheme provides collateral-free loans at subsidized interest rates with 5-year repayment flexibility.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31523, 'జాతీయ నిపుణ అభివృద్ధి మిషన్ మూల సంస్థ ఏది?\n(What is nodal agency of National Skill Development Mission?)', 'A) Ministry of Labor', 'B) Ministry of Education', 'C) Ministry of Skill Development', 'D) Ministry of Social Justice', 'C', 'జాతీయ నిపుణ అభివృద్ధి మిషన్ మూల సంస్థ నిపుణ అభివృద్ధి మరియు ఉద్యమీ పరిశ్రమ మంత్రిత్వం (MSDE).\n\nMSDE coordinates skill development across sectors. Target: train 40 crore youth by 2030 in employable skills.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31524, 'సార్వత్రిక సామాజిక సంరక్ష పథకం లక్ష్యం ఏది?\n(What is objective of Universal Social Security Scheme?)', 'A) Provide healthcare only', 'B) Provide financial security and social protection', 'C) Provide education only', 'D) Provide housing only', 'B', 'సార్వత్రిక సామాజిక సంరక్ష పథకం ఆర్థిక సంరక్ష మరియు సామాజిక సంరక్షణ అందించడం లక్ష్యం చేస్తుంది, అందరికీ.\n\nUniversal Social Security Scheme integrates healthcare, pension, disability, maternity, unemployment benefits ensuring comprehensive social security.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31525, 'ప్రధానమంత్రి జీవన జ్యోతి బీమా యోజన ఆయుష్కాల సమయ గరిష్ఠం ఎంత?\n(What is maximum age limit for Pradhan Mantri Jeevan Jyoti Bima Yojana?)', 'A) 50 years', 'B) 55 years', 'C) 60 years', 'D) 65 years', 'C', 'ప్రధానమంత్రి జీవన జ్యోతి బీమా యోజన ఆయుష్కాల సమయ గరిష్ఠం 60 సంవత్సరాలు, విమా సంరక్ష కోసం.\n\nPMJJBY provides term life insurance Rs. 2 lakh coverage. Premium Rs. 436 annually. By May 2026, ~2.75 crore beneficiaries enrolled.', 'AP_HC', 'National_Current_Affairs_2026'),
]

def main():
    print("Batch 3 MCQs (31501-31525) ready for insertion")
    print(f"Total: {len(batch3_mcqs)} MCQs")
    print("\nSample MCQ (31501):")
    mcq = batch3_mcqs[0]
    print(f"ID: {mcq[0]}")
    print(f"Question: {mcq[1][:80]}...")
    print(f"Answer: {mcq[5]}")

if __name__ == '__main__':
    main()
