# Telugu-translated MCQs 31626-31650
# Healthcare System Focus - National Current Affairs 2026

questions_batch_8 = [
    # 31626
    (31626, "సమన్విత ఆరోగ్య సరఫరా వ్యవస్థ యొక్క దృష్టిభంగం ఏమిటి? | What is the focus of the new 'Integrated Healthcare Delivery System' launched in May 2026?", 'ఆయువేదం, యోగం, యూనానీ, సిద్ధం తో ఆధునిక వైద్యం సమన్వయం (AYUSH ఇంటిగ్రేషన్) | Integration of Ayurveda, Yoga, Unani, Siddha with Allopathic medicine (AYUSH integration)', 'ప్రభుత్వ మరియు ఆర్జన్యూత ఆరోగ్య సేవల ఏకీకరణ | Unification of public and private healthcare with standardized pricing', 'ఆన్‌లైన్ దూరసంచారం మరియు ఆఫ్‌లైన్ ఆసుపత్రి సంధర్భం | Integration of online telemedicine with offline hospital infrastructure', 'కేంద్ర మరియు రాష్ట్ర ఆరోగ్య వ్యవస్థల విలీనం | Merging of central and state health systems under single administration', 'A', "సమన్విత ఆరోగ్య సరఫరా వ్యవస్థ సాంప్రదాయిక భారతీయ వ్యవస్థలు (AYUSH) ను ఆధుনిక వైద్యంతో సమన్వయం చేయడానికి దృష్టి సారించింది, 12,500 AYUSH వైద్యులను 8,500 ప్రభుత్వ ఆరోగ్య సేవా సంస్థలలో ఏకీకరించింది. | The 'Integrated Healthcare Delivery System' launched in May 2026 focuses on comprehensive integration of Traditional Indian Systems (Ayurveda, Yoga, Unani, Siddha - AYUSH) with Allopathic medicine to create a synergistic healthcare model. This initiative involved 12,500 AYUSH practitioners being credentialed and integrated into 8,500 public health facilities across India. Budget allocation reached ₹3,850 crores for establishing 2,500 AYUSH-Allopathy integrated clinics, with 85% operational by May 2026.", 'AP_HC', 'National_Current_Affairs_2026'),

    # 31627
    (31627, 'మాతృత్వ మరియు శిశు ఆరోగ్య కార్యక్రమాల కోసం బడ్జెట్ కేటాయణ ఏది? | What was the allocation for maternal and child health programs in the May 2026 Union Budget?', '₹4,200 కోట్లు MMR తగ్గింపుపై దృష్టిసారం | ₹4,200 crores with focus on reducing MMR to below 60', '₹6,800 కోట్లు సార్వత్రిక టీకాకరణ సాధనపై దృష్టిసారం | ₹6,800 crores with focus on achieving universal immunization', '₹8,500 కోట్లు రక్తహీనత నిర్మూలన మరియు శిశు పోషణపై దృష్టిసారం | ₹8,500 crores with focus on anemia elimination and child nutrition', '₹12,300 కోట్లు MCH సూచకాలకు సమన్విత చేష్టపై దృష్టిసారం | ₹12,300 crores with multi-pronged approach to MCH indicators', 'D', "మే 2026 సంఘ బడ్జెట్ మాతృత్వ మరియు శిశు ఆరోగ్య కార్యక్రమాల కోసం ₹12,300 కోట్లు కేటాయించింది, మునుపటి సంవత్సరం కేటాయణకంటే 32% పెరుగుదల. | The May 2026 Union Budget allocated ₹12,300 crores for maternal and child health programs, representing a 32% increase from previous year's allocation. This multi-pronged approach addresses Maternal Mortality Ratio (MMR), Child Mortality Ratio (CMR), and infant mortality with specific targets.", 'AP_HC', 'National_Current_Affairs_2026'),

    # 31628
    (31628, 'మే 2026 నాటికి 18-నెల సున్న సంక్రమణ మైలు రాయిని నివేదించిన సంక్రామక వ్యాధి నిర్మూలన కార్యక్రమం ఏది? | Which communicable disease eradication program reported achievement of 18-month zero transmission milestone by May 2026?', '12 అధిక భారం గల రాష్ట్రాల్లో measles నిర్మూలనం | Measles elimination in 12 high-burden states', 'జన్తువ ప్రభావ ప్రాంతాల్లో కాలజ్వరం నిర్మూలనం | Kala-azar elimination in endemic states', '280 జిల్లాల్లో ఫిలేరియా నిర్మూలనం | Filaria elimination in 280 districts', 'B మరియు C రెండూ | Both B and C', 'D', 'కాలజ్వరం నిర్మూలన కార్యక్రమం బిహార్, ఝార్‌ఖండ్, పశ్చిమ బెంగాల్‌లోని 45 ఎండెమిక్ బ్లాకుల్లో 18-నెల సున్న సంక్రమణ సాధించింది. ఫిలేరియా నిర్మూలనం 280 సుపూర్వపూర్వ జిల్లాల్లో సున్న microfilaraemia సాధించింది. | Two major communicable disease eradication programs achieved significant milestones by May 2026. Kala-azar elimination program achieved 18-month zero transmission in all 45 previously endemic blocks across Bihar, Jharkhand, and West Bengal, meeting WHO elimination criteria. Filaria (Lymphatic Filariasis) elimination achieved zero microfilaraemia in 280 previously endemic districts, benefiting 45 crore population.', 'AP_HC', 'National_Current_Affairs_2026'),

    # 31629
    (31629, 'మే 2026 నాటికి వ్యాధిరోధక ప్రతిఘటన (AMR) కు భారత ప్రతిస్పందన ఏ పరిస్థితిలో ఉంది? | What is the current status of India\'s response to antimicrobial resistance (AMR) as of May 2026?', 'జాతీయ చర్య పయోజన 2 ఆరంభం ₹3,200 కోట్ల బడ్జెట్‌తో 2026-2030కు | National Action Plan 2 launched with ₹3,200 crores budget for 2026-2030', 'ప్రతిజీవక సంరక్షణ కార్యక్రమం 85% ఆసుపత్రులకు విస్తరించినది | Antibiotic Stewardship Program expanded to 85% of hospitals', 'A మరియు B రెండూ | Both A and B', 'సాధారణ ప్రతిజీవక ఉత్పాదన 200% పెరుగుదలం | Generic antibiotic production increased by 200%', 'C', "మే 2026న భారత సంక్రామక నిరోధకతకు జాతీయ చర్య పయోజన 2 ఆరంభంతో ₹3,200 కోట్ల బడ్జెట్ మరియు ప్రతిజీవక సంరక్షణ కార్యక్రమం 85% ఆసుపత్రులకు విస్తరణ. | India's antimicrobial resistance response in May 2026 includes launch of National Action Plan 2 (2026-2030) with ₹3,200 crores budget and expansion of Antibiotic Stewardship Program to 85% of hospitals nationwide.", 'AP_HC', 'National_Current_Affairs_2026'),

    # 31630
    (31630, 'మే 2026 నాటికి దూరసంచార సంధర్భ సామర్థ్యంతో ఎన్ని గ్రామీణ మరియు సుదూర ఆరోగ్య సేవా సంస్థలు నవీకరించబడ్డాయి? | How many rural and remote health facilities were upgraded with telemedicine infrastructure by May 2026?', '25,000 సంస్థలు | 25,000 facilities', '40,000 సంస్థలు | 40,000 facilities', '55,000 సంస్థలు | 55,000 facilities', '70,000 సంస్థలు | 70,000 facilities', 'C', 'జాతీయ దూరసంచార చిత్తవృత్తి 55,000 గ్రామీణ మరియు సుదూర ఆరోగ్య సేవా సంస్థలను దూరసంచార సంధర్భ సామర్థ్యంతో నవీకరించింది, 52 కోటి గ్రామీణ జనసంఖ్యకు నిపుణ సంప్రదింపు సంస్కృతికి ప్రవేశాధికారం ఇచ్చింది. | The National Telemedicine Initiative upgraded 55,000 rural and remote health facilities with telemedicine infrastructure by May 2026, providing specialist consultation access to 52 crore rural population.', 'AP_HC', 'National_Current_Affairs_2026'),

    # 31631
    (31631, 'మే 2026న సాంఘిక వ్యాధిరోధకత నిరోధన కార్యక్రమాల కోసం ఏ కొత్త పయోజన ప్రారంభించబడింది? | What new scheme was introduced in May 2026 for prevention of non-communicable diseases (NCDs)?', 'జాతీయ NCD నిరోధన కార్యక్రమం ప్రవర్తన పరిర్తనపై దృష్టిసారం | National NCD Prevention Program with focus on behavior change', 'ఆయుష్‌మాన్ భారత్ - సుస్థిర కేంద్రాల విస్తరణ ఆరోగ్య స్క్రీనింగ్‌తో | Ayushman Bharat - Wellness Centers expansion with health screening', 'A మరియు B రెండూ | Both A and B', 'NCD రోగీల కోసం సార్వత్రిక ఆరోగ్య బీమా | Universal Health Insurance for NCD patients', 'C', 'మే 2026న జాతీయ NCD నిరోధన కార్యక్రమం మరియు ఆయుష్‌మాన్ భారత్ - సుస్థిర కేంద్రాల విస్తరణ రెండూ ప్రారంభించబడ్డాయి. | May 2026 saw launch of both National NCD Prevention Program and expansion of Ayushman Bharat - Wellness Centers.', 'AP_HC', 'National_Current_Affairs_2026'),

    # 31632
    (31632, 'మే 2026 నాటికి వ్యాధి నిఘంటన రంగంలో ప్రధాన సాధన ఏమిటి? | What was the major achievement in disease surveillance by May 2026?', 'సమీకృత వ్యాధి నిఘంటన కార్యక్రమం (IDSP) నిజ-సమయ నివేదనతో సమస్త జిల్లాలకు విస్తరణ | Integrated Disease Surveillance Program (IDSP) expanded to all districts with real-time reporting', 'AI-శక్తిచేత సంరూపిత మహమ్మారీ పూర్వాభాస వ్యవస్థ 32 రాష్ట్రాల్లో ఆపరేషనల్ | AI-powered epidemic forecasting system operational in 32 states', 'A మరియు B రెండూ | Both A and B', 'జనుద్విత్వ వరణ సామర్థ్యం 500 కేంద్రాలకు పెంచుకోవడం | Genomic sequencing capacity increased to 500 centers', 'C', 'సమీకృత వ్యాధి నిఘంటన కార్యక్రమం నిజ-సమయ కేస్ నివేదనతో సమస్త 718 జిల్లాలకు విస్తరణ, AI-శక్తిచేత సంరూపిత మహమ్మారీ పూర్వాభాస వ్యవస్థ 32 రాష్ట్రాల్లో ఆపరేషనల్. | May 2026 marked significant expansion of disease surveillance infrastructure. Integrated Disease Surveillance Program (IDSP) expanded to cover all 718 districts with real-time case reporting reducing detection-to-reporting time from 7 days to 24 hours.', 'AP_HC', 'National_Current_Affairs_2026'),

    # 31633
    (31633, 'మే 2026 నాటికి వైద్య పరికర నియంత్రణ మరియు ఉత్పాదన సుదృఢీకరణకు బడ్జెట్ కేటాయణ ఏమిటి? | What is the budget allocation for strengthening medical device regulation and manufacturing by May 2026?', 'మేక్ ఇన్ ఇండియా వైద్య పరికరాల కోసం ₹1,800 కోట్లు | ₹1,800 crores for Make in India medical devices', 'నియంత్రక చట్ట నిర్మాణం మరియు ఉత్పాదన సామర్థ్యకు ₹3,200 కోట్లు | ₹3,200 crores for regulatory framework and manufacturing capacity', 'సర్వ వైద్య పరికర జీవన చక్ర కోసం ₹5,400 కోట్లు | ₹5,400 crores for comprehensive medical device ecosystem', 'ప్రపంచ నిర్ణయ సామర్థ్యకు ₹7,800 కోట్లు | ₹7,800 crores for global competitiveness in medical devices', 'D', '2026 సంఘ బడ్జెట్ భారతదేశ వైద్య పరికర నియంత్రణ, ఉత్పాదన, ప్రపంచ నిర్ణయ సామర్థ్యకు ₹7,800 కోట్లు కేటాయించింది. | The Union Budget 2026 allocated ₹7,800 crores for strengthening India\'s medical device regulation, manufacturing, and global competitiveness.', 'AP_HC', 'National_Current_Affairs_2026'),

    # 31634
    (31634, 'మే 2026న ప్రాథమిక ఆరోగ్య సేవలకు సహాయపడటానికి ఏ కొత్త ఆరోగ్య నిధిపరికర ప్రవేశపెట్టబడింది? | What new healthcare financing mechanism was introduced to support primary healthcare in May 2026?', 'PHC కార్యక్రమాల కోసం ₹5,200 కోట్ల నిధి కార్పస్ సഹ ఆరోగ్య సేవ నిధి | Health Service Fund with ₹5,200 crores corpus for PHC operations', 'ఆరోగ్య సంధర్భ బాండ్‌లు 6.5% వడ్డీ రేటకు పౌర సంచీకరణ సంఘం | Healthcare Infrastructure Bonds allowing citizen investments at 6.5% interest', 'A మరియు B రెండూ | Both A and B', 'పేద గృహపालనకు ప్రత్యక్ష ఆర్జన్యూత బీమా సబ్సిడీ | Direct private insurance subsidies for poor households', 'C', 'మే 2026న ఆరోగ్య సేవ నిధి మరియు ఆరోగ్య సంధర్భ బాండ్‌లు రెండు కొత్త ఆరోగ్య నిధిపరికర ప్రవేశపెట్టబడ్డాయి. | May 2026 introduced two new healthcare financing mechanisms: Health Service Fund and Healthcare Infrastructure Bonds.', 'AP_HC', 'National_Current_Affairs_2026'),

    # 31635
    (31635, 'మే 2026 నాటికి COVID-19 మరియు మహమ్మారీ సన్నహత కు భారత ప్రతిస్పందన ఏ స్థితిలో ఉంది? | What is the status of India\'s COVID-19 and pandemic preparedness response by May 2026?', 'జాతీయ మహమ్మారీ సన్నహత చట్ట నిర్మాణం ₹4,800 కోట్ల కేటాయణ సహ నిర్ణయం | National Pandemic Preparedness Framework finalized with ₹4,800 crores allocation', 'సంచర అభివృద్ధి సామర్థ్యం సంవత్సరానికి 8.5 బిలియన్ మోతాదులకు పెంచుకోవడం | Vaccine development capacity increased to 8.5 billion doses/year', 'A మరియు B రెండూ | Both A and B', 'సమస్త 718 జిల్లాల్లో మహమ్మారీ ప్రతిస్పందన బృందం ఏర్పాటు | Pandemic Response Team established in all 718 districts', 'C', 'మే 2026న భారతీయ మహమ్మారీ సన్నహత జాతీయ కలకట్టిన సిద్ధాంత నిర్మాణం మరియు సంచర ఉత్పాదన సామర్థ్యం లో నిర్మాణం చేయబడింది. | India\'s pandemic preparedness by May 2026 includes National Pandemic Preparedness Framework and expanded vaccine manufacturing capacity.', 'AP_HC', 'National_Current_Affairs_2026'),

    # 31636
    (31636, 'మే 2026 నాటికి గ్రామీణ భారతదేశంలో సర్వోచ్చ ఆరోగ్య సూచకం ఏమిటీ సాధించింది? | Which health indicator showed the most improvement in rural India by May 2026?', 'సంస్థానికర ప్రసవ చేస్టలు 79% నుండి 99% గా పెరుగుదల (2015) | Institutional delivery rate increased to 99% from 79% in 2015', 'శిశు మరణ చేస్తలు 54 నుండి 28 కు కుంపటెనా (2015) | Infant mortality rate decreased to 28 from 54 in 2015', 'మాతృత్వ మరణ నిష్పత్తి 167 నుండి 95 కు కుంపటెనా (2015) | Maternal mortality ratio reduced to 95 from 167 in 2015', 'ఆ సమస్తమైనవి | All of the above', 'D', 'గ్రామీణ భారతదేశం మే 2026 నాటికి సమస్త ప్రధాన ఆరోగ్య సూచకాల్లో విశేష సుధారణ ప్రదర్శించింది. | Rural India demonstrated remarkable improvement across all major health indicators by May 2026.', 'AP_HC', 'National_Current_Affairs_2026'),

    # 31637
    (31637, 'మే 2026 నాటికి భారత జనసంఖ్య ఏ శాతం మెరుగుపరచిన జలం మరియు శుద్ధీకరణకు చేరుకుంది? | What percentage of India\'s population gained access to improved water and sanitation by May 2026?', 'స్వచ్ఛ భారత్ మిషన్ - దశ 2 ద్వారా 78% | 78% through Swachh Bharat Mission - Phase 2', 'జల జీవన మిషన్ మరియు స్వచ్ఛ భారత్ విస్తరణ ద్వారా 92% | 92% through Jal Jeevan Mission and Swachh Bharat expansion', 'గ్రామీణ సమాజ చిత్తవృత్తుల ద్వారా 68% | 68% through grassroots community initiatives', 'ప్రభుత్వ-ఆర్జన్యూత భాగస్వామ్య నమూనాల ద్వారా 85% | 85% through public-private partnership models', 'B', 'మే 2026 నాటికి, భారత జనసంఖ్య 92% జల జీవన మిషన్ మరియు స్వచ్ఛ భారత్ మిషన్ - దశ 2 సమీకృత ఆవర్తనం ద్వారా మెరుగుపరచిన జలం మరియు శుద్ధీకరణకు చేరుకుంది. | By May 2026, 92% of India\'s population gained access to improved water and sanitation through integrated implementation of Jal Jeevan Mission and Swachh Bharat Mission - Phase 2.', 'AP_HC', 'National_Current_Affairs_2026'),

    # 31638
    (31638, 'మే 2026న వృత్తిపరమైన ఆరోగ్య మరియు కార్మిక సంరక్షణకు ఏ కొత్త ముందెళ్ల ప్రారంభించబడింది? | What new initiative was launched for occupational health and worker safety in May 2026?', 'జాతీయ వృత్తిపరమైన ఆరోగ్య సంరక్షణ విధానం ₹2,200 కోట్ల ఆవర్తనం సహ | National Occupational Health & Safety Policy with ₹2,200 crores for implementation', '35,000 ఆరోగ్య సేవా సంస్థాల్లో వృత్తిపరమైన వ్యాధి నిబంధనం | Occupational Disease Registry in 35,000 health facilities', 'A మరియు B రెండూ | Both A and B', '15 కోటి కార్మికులను కవర్ చేసే కార్యక్రమ ఆరోగ్య బీమా పయోజన | Workplace Health Insurance scheme covering 15 crore workers', 'C', 'మే 2026న జాతీయ వృత్తిపరమైన ఆరోగ్య సంరక్షణ విధానం మరియు వృత్తిపరమైన వ్యాధి నిబంధనం రెండు ప్రధాన వృత్తిపరమైన ఆరోగ్య ముందెళ్ల ప్రారంభం చేయబడ్డాయి. | May 2026 witnessed launch of two major occupational health initiatives: National Occupational Health & Safety Policy and Occupational Disease Registry.', 'AP_HC', 'National_Current_Affairs_2026'),

    # 31639
    (31639, 'మే 2026న ఆరోగ్య సాంఘ్నికత నాటుకరణలో ఏ ప్రధాన సాధన నిమగ్నం చేయబడింది? | What was the major achievement in health technology innovation by May 2026?', 'స్వదేశీ నిర్ణయ సాంఘ్నికతలు 2,200 ప్రయోగశాల్లలో నమోదు | Swadeshi Diagnostic Technologies registered at 2,200 labs across India', 'సుందరమైన వెంటిలేటర్ మరియు ఆక్సిజన్ సంఘంకర ఉత్పాదన స్వయం-సిద్ధాంత సాధించింది | Affordable ventilator and oxygen concentrator manufacturing achieved self-sufficiency', 'A మరియు B రెండూ | Both A and B', '5,000 ఆసుపత్రిల్లలో క్లినికల్ నిర్ణయ సమర్థక AI వ్యవస్థ ఆవర్తనం | Clinical decision support AI systems deployed in 5,000 hospitals', 'C', 'భారతదేశం మే 2026న ఆరోగ్య సాంఘ్నికత నాటుకరణ చిర్సీయతలను సాధించింది. | India achieved significant health technology innovation milestones by May 2026.', 'AP_HC', 'National_Current_Affairs_2026'),

    # 31640
    (31640, 'మే 2026 నాటికి ప్రాథమిక ఆరోగ్య కేంద్రాల ద్వారా ఎన్ని వ్యక్తులు మానసిక ఆరోగ్య సేవలను పొందారు? | How many individuals received mental health services through primary health centers by May 2026?', 'మానసిక ఆరోగ్య సమీకరణ కార్యక్రమం ద్వారా 2.5 కోటి | 2.5 crore through Mental Health Integration Program', 'సాధన PHC సలహా సేవలు ద్వారా 4.2 కోటి | 4.2 crore through expanded PHC counseling services', 'PHC, ASHA, దూరసంచారం సమీకరణం ద్వారా 5.8 కోటి | 5.8 crore through combination of PHC, ASHA, and telemedicine', 'బహు-సరఫరా మానసిక ఆరోగ్య సేవ ద్వారా 8.2 కోటి | 8.2 crore through multi-channel mental health delivery', 'D', 'మే 2026 నాటికి, 8.2 కోటి వ్యక్తులు ప్రాథమిక ఆరోగ్య కేంద్రాల, ASHA కార్యకర్తల, దూరసంచారం, పాఠశాల ఆధారిత సేవల సమీకృత సరఫరా ద్వారా మానసిక ఆరోగ్య సేవలను పొందారు. | By May 2026, 8.2 crore individuals received mental health services through multi-channel delivery including Primary Health Centers, ASHA workers, telemedicine, and school-based services.', 'AP_HC', 'National_Current_Affairs_2026'),

    # 31641
    (31641, 'మే 2026 బడ్జెట్‌లో గిరిజన ఆరోగ్య వ్యవస్థల సుదృఢీకరణకు ఏ కేటాయణ నిమగ్నం చేయబడింది? | What was the allocation for strengthening tribal health systems in the May 2026 Budget?', 'గిరిజన-నిర్దిష్ట ఆరోగ్య కార్యక్రమాల కోసం ₹1,850 కోట్లు | ₹1,850 crores for tribal-specific health programs', 'గిరిజన ఆరోగ్య సంధర్భం మరియు సాంప్రదాయిక వైద్యం సమీకరణ కోసం ₹3,200 కోట్లు | ₹3,200 crores for tribal health infrastructure and traditional medicine integration', 'సర్వ-గిరిజన ఆరోగ్య సంక్షేమ కోసం ₹5,500 కోట్లు | ₹5,500 crores for comprehensive tribal health transformation', 'సమస్త సూచకాల్లో గిరిజన ఆరోగ్య సమానత్వం కోసం ₹7,200 కోట్లు | ₹7,200 crores for tribal health equity across all indicators', 'D', 'మే 2026 సంఘ బడ్జెట్ గిరిజన ఆరోగ్య వ్యవస్థల సుదృఢీకరణకు ₹7,200 కోట్లు కేటాయించింది. | The May 2026 Union Budget allocated ₹7,200 crores for strengthening tribal health systems.', 'AP_HC', 'National_Current_Affairs_2026'),

    # 31642
    (31642, 'మే 2026న వాయు నాణ్యత పర్యవేక్షణ మరియు శ్వాసకోశ ఆరోగ్యానికు ఏ కొత్త నియమ ప్రవేశపెట్టబడింది? | What new regulation was introduced for air quality monitoring and respiratory health in May 2026?', '450 నగరాల్లలో జాతీయ శ్వాసకోశ ఆరోగ్య నిఘంటన కార్యక్రమం | National Respiratory Health Surveillance Program in 450 cities', '250 జిల్లాల్లలో వాయు నాణ్యత-బంధిత ఆరోగ్య జోక్తి వ్యవస్థ (AQHIS) | Air Quality-Linked Health Intervention System (AQHIS) in 250 districts', 'A మరియు B రెండూ | Both A and B', '₹4,500 కోట్ల సంచీకరణ సহ తప్పనిసరి వాయు నాణ్యత ప్రమాణాల అమల్ | Mandatory air quality standards enforcement with ₹4,500 crore investment', 'C', 'మే 2026న జాతీయ శ్వాసకోశ ఆరోగ్య నిఘంటన కార్యక్రమం మరియు వాయు నాణ్యత-బంధిత ఆరోగ్య జోక్తి వ్యవస్థ రెండు ప్రధాన వాయు నాణ్యత మరియు శ్వాసకోశ ఆరోగ్య ముందెళ్ల ప్రారంభం చేయబడ్డాయి. | May 2026 introduced two major air quality and respiratory health initiatives: National Respiratory Health Surveillance Program and Air Quality-Linked Health Intervention System (AQHIS).', 'AP_HC', 'National_Current_Affairs_2026'),

    # 31643
    (31643, 'మే 2026 నాటికి ఎన్ని రోగులు అరుదైన జెనెటిక్ వ్యాధులకు చికిత్స సహాయ పొందారు? | How many patients with rare genetic diseases received treatment support by May 2026?', 'కొత్త అరుదైన వ్యాధి నిబంధనం మరియు చికిత్స కార్యక్రమం ద్వారా 1.2 లక్ష | 1.2 lakh through new Rare Disease Registry and Treatment Program', 'విస్తరిత వైద్య జెనెటిక్ సేవలు ద్వారా 2.8 లక్ష | 2.8 lakh through expanded medical genetics services', 'శ్రేష్ఠత కేంద్ర నమూనా ద్వారా 4.5 లక్ష | 4.5 lakh through Center of Excellence model', 'సర్వ-వ్యాధిజన్ వ్యవస్థ ద్వారా 6.2 లక్ష | 6.2 lakh through comprehensive rare disease ecosystem', 'D', 'మే 2026 నాటికి, 6.2 లక్ష రోగులు సర్వ సమ్మతిసహ చిక్కిన జెనెటిక్ వ్యాధుల జీవన ప్రయత్నం ద్వారా చికిత్స సహాయ పొందారు. | By May 2026, 6.2 lakh patients with rare genetic diseases received treatment support through comprehensive rare disease ecosystem.', 'AP_HC', 'National_Current_Affairs_2026'),

    # 31644
    (31644, 'మే 2026 నాటికి హెపటిటిస్ బి మరియు సి సంక్రమణ నిర్మూలనలో ఏ ప్రధాన సాధన నివేదించబడింది? | What major achievement was reported in eliminating hepatitis B and C transmission by May 2026?', 'సున్న తల్లి-శిశు సంక్రమణ సహ 95% న్యూబార్న్ హెపటిటిస్ బి టీకాకరణ కవరేజ్ | 95% coverage of newborn hepatitis B vaccination with zero mother-to-child transmission', '97% నిర్ణయ చేస్తలు సహ 88% హెపటిటిస్ సి రోగీలు ప్రత్యక్ష-చర్య ప్రతిజీవక చికిత్స | 88% of hepatitis C patients received direct-acting antiviral treatment with 97% cure rate', 'A మరియు B రెండూ | Both A and B', 'రక్త సరఫరా యొక్క ట్రాన్‌చిషన్‌ పరిగ్రహణ హెపటిటిస్‌కు సార్వత్రిక ఆయుక్తం | Universal screening of blood supply eliminating transfusion-transmitted hepatitis', 'C', 'మే 2026 నాటికి, భారతదేశం హెపటిటిస్ బి మరియు సి సంక్రమణ నిర్మూలనలో ప్రధాన మైలు రాయిలను సాధించింది. | By May 2026, India achieved major milestones in eliminating hepatitis B and C transmission.', 'AP_HC', 'National_Current_Affairs_2026'),

    # 31645
    (31645, 'మే 2026న సాంప్రదాయిక ప్రసవం సేవకర్త (TBA) సమీకరణ సుదృఢీకరణకు ఏ కొత్త నిర్మాణం ప్రవేశపెట్టబడింది? | What new framework was introduced for strengthening traditional birth attendant (TBA) integration in May 2026?', 'సాంప్రదాయిక మార్గదర్శిత సర్టిఫికేషన్ మరియు పర్యవేక్షణ కార్యక్రమాల ద్వారా TBA నియంత్రణ | Regulation of TBAs through formal certification and supervision programs', 'సంస్కృత ప్రసవం సేవకర్త సహకార సంరక్షణ నమూనా సమీకరణ | Integration of TBAs with skilled birth attendants under collaborative care model', 'A మరియు B రెండూ | Both A and B', 'సంస్కృత-ఆధారిత ప్రసవం సంపుష్టీకరణ పర్య TBA క్రమక్రమ భర్తీ | Gradual replacement of TBAs with facility-based delivery promotion only', 'C', 'మే 2026న సాంప్రదాయిక ప్రసవం సేవకర్త సమీకరణ సుదృఢీకరణ మరియు స్థిర ప్రసవం సంక్రమణ కోసం సహయోగ చట్ట నిర్మాణం ప్రవేశపెట్టబడింది. | May 2026 introduced a collaborative framework for strengthening traditional birth attendant (TBA) integration while ensuring institutional delivery transition.', 'AP_HC', 'National_Current_Affairs_2026'),

    # 31646
    (31646, 'మే 2026 నాటికి క్లినికల్ పరిశోధన మరియు ట్రయల్ సంధర్భ రంగంలో ఏ ప్రధాన అభివృద్ధి నివేదించబడింది? | What was the major development in clinical research and trial infrastructure by May 2026?', '8,500 సక్రియ ట్రయల్‌ల సహ జాతీయ క్లినికల్ ట్రయల్ నిబంధనం విస్తరణ | National Clinical Trials Registry expanded with 8,500 active trials', '150 జిల్లాల్లలో విధానభద్ధ క్లినికల్ ట్రయల్ సంధర్భం | Decentralized clinical trial infrastructure established in 150 districts', 'A మరియు B రెండూ | Both A and B', 'అంతర్జాతీయ స్థితిలో ఇండియా టాప్ 3 ర్యాంకింగ్‌లోకి చేరిన చాలిన కనిపించుకోవడం | International clinical trial attractiveness Index placed India in top 3', 'C', 'భారతదేశ క్లినికల్ పరిశోధన సంధర్భం మే 2026 నాటికి ముఖ్యమైన సిద్ధాంత విస్తరణ సందర్భీకరణ చేయబడింది. | India\'s clinical research infrastructure underwent significant expansion by May 2026.', 'AP_HC', 'National_Current_Affairs_2026'),

    # 31647
    (31647, 'మే 2026న ఆరోగ్య సేవకర్త దహనం మరియు మానసిక ఆరోగ్య సమస్యల నిరాకరణకు ఏ ముందెళ్ల ప్రారంభించబడింది? | What initiative was launched to address healthcare worker burnout and mental health by May 2026?', '8,500 సంస్థాల్లలో మానసిక ఆరోగ్య సమర్థక సేవలు సహ ఆరోగ్య సేవకర్త సుఖ కార్యక్రమం | Healthcare Worker Wellness Program with mental health support in 8,500 facilities', 'ఆసుపత్రిల్లలో వృత్తిపరమైన ఒత్తిడి పర్యవేక్షణ మరియు జోక్తి ప్రోటోకాల్‌లు | Occupational stress monitoring and intervention protocols in hospitals', 'A మరియు B రెండూ | Both A and B', 'సమస్త ఆరోగ్య సేవకర్తలకు తప్పనిసరి విశ్రాంతి కాలాలు మరియు తగ్గిన చేష్ట వ్యవధి | Mandatory rest periods and reduced shift duration for all healthcare workers', 'C', 'మే 2026న ఆరోగ్య సేవకర్త సుఖ కార్యక్రమ ఆరోగ్య సేవకర్త ఘటన సమస్య సమాధానం ప్రారంభం చేయబడింది. | May 2026 witnessed launch of comprehensive Healthcare Worker Wellness Program addressing critical burnout crisis.', 'AP_HC', 'National_Current_Affairs_2026'),

    # 31648
    (31648, 'మే 2026న ఆరోగ్య మరియు సుస్థిర చిన్న వ్యవసాయ సంస్థల నియంత్రణ మరియు సంపుష్టీకరణ కోసం ఏ నిర్మాణం స్థాపితం చేయబడింది? | What framework was established for regulating and promoting health and wellness startups by May 2026?',
' డిజిటల్ ఆరోగ్య నియంత్రక సర్కిల్ సంరక్షణ చేష్ట పర్యవేక్షణ సమర్థక | Digital Health Regulatory Sandbox allowing innovation with safety oversight', '₹1,850 కోట్ల నిధి సమీకరణ ఆరోగ్య సాంఘ్నికత సంచీకరణ కార్యక్రమం | Health Tech Incubation Program with ₹1,850 crores corpus for startup funding', 'A మరియు B రెండూ | Both A and B', 'సేవ చేష్ట నియంత్రణ సహ తప్పనిసరి సమన్వయ చట్ట నిర్మాణం | Mandatory compliance framework with tariff controls on health tech services', 'C', 'మే 2026న డిజిటల్ ఆరోగ్య నియంత్రక సర్కిల్ మరియు ఆరోగ్య సాంఘ్నికత సంచీకరణ కార్యక్రమ ద్వారా డిజిటల్ ఆరోగ్య నాటుకరణకు సర్వ-అన్నిపటిపటించిన నిర్మాణం స్థాపితం చేయబడింది. | May 2026 established comprehensive framework for digital health innovation through Digital Health Regulatory Sandbox and Health Tech Incubation Program.', 'AP_HC', 'National_Current_Affairs_2026'),

    # 31649
    (31649, 'మే 2026 నాటికి సీసం విషపూరణం మరియు ఇతర పరిసర ఆరోగ్య ప్రమాదాల నిర్మూలనలో ఏ ప్రధాన సాధన నివేదించబడింది? | What major achievement was reported in eliminating lead poisoning and other environmental health hazards by May 2026?', '8.5 కోటి శిశువుల్లలో సీసం బహిర్గతీకరణ పర్యవేక్షణ, 95% అధిక-భారం జిల్లాల్లలో నిర్మూలనం | Lead exposure screening in 8.5 crore children with elimination in 95% of high-burden districts', '2,200 జిల్లాల్లలో 85 ప్రధాన ప్రమాదాల గుర్తింపు సేవకర్త పరిసర ఆరోగ్య ప్రమాద నిఘంటనం | Environmental health hazard surveillance in 2,200 districts identifying 85 primary hazards', 'A మరియు B రెండూ | Both A and B', 'సమస్త రసాయన మరియు జీవ ప్రదూషణ నిర్మూలన సార్వత్రిక జల నాణ్యత పరీక్ష | Universal water quality testing eliminating all chemical and biological contamination', 'C', 'మే 2026న సీసం విషపూరణ నిర్మూలన మరియు పరిసర ఆరోగ్య ప్రమాద నిర్మూలనలో గణనీయ సిద్ధాంత ప్రగతి నివేదించబడింది. | May 2026 marked significant progress in eliminating lead poisoning and environmental health hazards.', 'AP_HC', 'National_Current_Affairs_2026'),

    # 31650
    (31650, 'మే 2026 నాటికి ఆరోగ్య కేంద్ర సంక్షేమ సిద్ధాంత మరియు లాభభోగీ ప్రభావం ఏమిటి? | What is the overall investment and beneficiary impact of healthcare sector transformation by May 2026?', '₹95,000 కోట్లు సంచీకరణ; 85 కోటి వ్యక్తులు మెరుగుపరచిన ఆరోగ్య సంస్కృతికి పట్టుకున్నారు | ₹95,000 crores invested; 85 crore individuals received improved healthcare access', '₹125,000 కోట్లు సంచీకరణ; 110 కోటి వ్యక్తులు ఆరోగ్య కార్యక్రమాల నుండి లాభవంతమైనవారు | ₹125,000 crores invested; 110 crore individuals benefited from health programs', '₹155,000 కోట్లు సంచీకరణ; 125 కోటి వ్యక్తులు ఆరోగ్య సిద్ధాంతుల సుధారణ సాధించిన వారు | ₹155,000 crores invested; 125 crore individuals with improved health outcomes', '₹185,000 కోట్లు సంచీకరణ; 140 కోటి వ్యక్తులు ఆరోగ్య వ్యవస్థ సంక్షేమం ద్వారా చేరుకున్నారు | ₹185,000 crores invested; 140 crore individuals across health system transformation', 'D', 'మే 2026 నాటికి, భారతదేశ ఆరోగ్య కేంద్ర సంక్షేమ సిద్ధాంత ఆశ్చర్యకరమైన సంచీకరణ మరియు జనసంఖ్య ఆందోళనను ప్రతిరూపిస్తుంది. | By May 2026, India\'s healthcare sector transformation represented unprecedented investment and population impact.', 'AP_HC', 'National_Current_Affairs_2026'),
]
