# seed_polity_ch22.py
# Chapter 22 — Constitutional Bodies
# Total Sections: 8 | Total MCQs: 64
# Sections:
#   0 — Election Commission (Art.324) (8 MCQs)
#   1 — UPSC — Union Public Service Commission (8 MCQs)
#   2 — CAG — Comptroller & Auditor General (8 MCQs)
#   3 — Finance Commission (Art.280) (8 MCQs)
#   4 — Attorney General & Solicitor General (8 MCQs)
#   5 — National Commissions — SC/ST/BC/Women (8 MCQs)
#   6 — SPSC & Joint PSC (8 MCQs)
#   7 — Miscellaneous Constitutional Bodies (8 MCQs)

_CH = 22
_SUBJECT = 'GK'
_TOPIC   = 'Indian_Polity'
_TITLE_TE = 'రాజ్యాంగ సంస్థలు'
_TITLE_EN = 'Constitutional Bodies'
_PAGES    = 'Ch.22 (Lakshmikanth)'

_SECTIONS = [
    "ఎన్నికల సంఘం — అనుచ్ఛేదం 324",
    "UPSC — సంఘం లోక్ సేవా సంఘం",
    "CAG — నియంత్రక మహాపరీక్షకుడు",
    "ఆర్థిక సంఘం — అనుచ్ఛేదం 280",
    "అటార్నీ జనరల్ & సొలిసిటర్ జనరల్",
    "జాతీయ కమిషన్లు — SC/ST/BC/మహిళలు",
    "SPSC & ఉమ్మడి లోక్ సేవా సంఘం",
    "విభిన్న రాజ్యాంగ సంస్థలు",
]

_MCQS = [    (0,
     'easy',
     'Which Article establishes the Election Commission?\nతెలుగు: భారత ఎన్నికల సంఘాన్ని నిర్దేశించే అనుచ్ఛేదం ఏది?',
     'Art.280 / అనుచ్ఛేదం 280',
     'Art.315 / అనుచ్ఛేదం 315',
     'Art.324 / అనుచ్ఛేదం 324',
     'Art.148 / అనుచ్ఛేదం 148',
     'c',
     'Art.324: Establishes ECI — superintendence of elections to Parliament, State Legislatures, President and VP. / Art.324: భారత ఎన్నికల సంఘం (ECI) ని స్థాపిస్తుంది — పార్లమెంట్, రాష్ట్ర శాసనసభ, రాష్ట్రపతి మరియు ఉపరాష్ట్రపతి ఎన్నికలను పర్యవేక్షిస్తుంది.'),
    (0,
     'easy',
     'Who appoints the Chief Election Commissioner?\nతెలుగు: ముఖ్య ఎన్నికల కమిషనర్ (CEC) ని ఎవరు నియమిస్తారు?',
     'Prime Minister / ప్రధానమంత్రి',
     'President / రాష్ట్రపతి',
     'Lok Sabha Speaker / లోక్\u200cసభ స్పీకర్',
     'CJI / భారత ప్రధాన న్యాయమూర్తి',
     'b',
     'Art.324(2): CEC and other Election Commissioners appointed by President. / Art.324(2): CEC మరియు ఇతర ఎన్నికల కమిషనర్లను రాష్ట్రపతి నియమిస్తారు.'),
    (0,
     'medium',
     'How can the CEC be removed?\nతెలుగు: ముఖ్య ఎన్నికల కమిషనర్\u200cను ఎలా తొలగించవచ్చు?',
     "By President's order alone / రాష్ట్రపతి ఉత్తర్వుతో",
     "On PM's recommendation / ప్రధానమంత్రి సిఫారసుతో",
     "Like SC judge — special majority + President's order / SC న్యాయమూర్తి మాదిరిగా పార్లమెంట్ ప్రత్యేక మెజారిటీ + రాష్ట్రపతి ఆదేశం",
     'By Cabinet decision / కేబినెట్ నిర్ణయంతో',
     'c',
     "Art.324(5): CEC removed like SC judge — special majority + President. Other ECs removed on CEC's recommendation. / Art.324(5): CEC ని SC న్యాయమూర్తి మాదిరిగా తొలగించవచ్చు — పార్లమెంట్ ప్రత్యేక మెజారిటీ + రాష్ట్రపతి ఆదేశం ద్వారా. ఇతర ఎన్నికల కమిషనర్లను CEC సిఫారసు మేరకు రాష్ట్రపతి తొలగించవచ్చు."),
    (0,
     'medium',
     'When did ECI become a three-member body?\nతెలుగు: ఎన్నికల కమిషన్ ఎప్పుడు మూడు సభ్యుల సంస్థగా మారింది?',
     '1950',
     '1965',
     '1989',
     '2000',
     'c',
     'ECI became multi-member in Oct 1989 (briefly), permanently 3-member from Oct 1993. / 1989 అక్టోబర్ వరకు ECI ఒకే CEC తో ఒక-సభ్య సంస్థగా ఉంది. 1989 అక్టోబర్ లో మొదటిసారి మూడు-సభ్య సంస్థగా మారింది (తర్వాత 1990 జనవరిలో మళ్ళీ ఒక-సభ్య సంస్థగా, 1993 అక్టోబర్\u200cలో శాశ్వతంగా మూడు-సభ్య సంస్థగా).'),
    (0,
     'medium',
     'Tenure of Election Commissioners?\nతెలుగు: ఎన్నికల కమిషనర్ల పదవీకాలం ఎంత?',
     '5 years / 5 సంవత్సరాలు',
     '6 years or age 65, whichever earlier / 6 సంవత్సరాలు లేదా 65 సంవత్సరాల వయస్సు వరకు',
     '6 years or age 62, whichever earlier / 6 సంవత్సరాలు లేదా 62 సంవత్సరాల వయస్సు వరకు',
     'No fixed tenure / పదవీకాలం నిర్ణీతం లేదు',
     'b',
     'CEC and ECs: 6 years or 65 years of age, whichever is earlier. / CEC మరియు ఎన్నికల కమిషనర్లు: 6 సంవత్సరాలు లేదా 65 సంవత్సరాల వయస్సు వరకు — ఏది ముందు వస్తే అది.'),
    (0,
     'hard',
     "Which elections are NOT under ECI's superintendence?\nతెలుగు: ఎన్నికల సంఘం ఏ ఎన్నికలను పర్యవేక్షించదు?",
     "President's election / రాష్ట్రపతి ఎన్నిక",
     'Panchayat and Municipal elections / పంచాయతీ మరియు నగర పాలక సంస్థ ఎన్నికలు',
     'Lok Sabha elections / లోక్\u200cసభ ఎన్నికలు',
     'State Legislature elections / రాష్ట్ర శాసనసభ ఎన్నికలు',
     'b',
     'Art.243K: Panchayat and municipal elections supervised by State Election Commission (SEC), not ECI. / Art.243K: పంచాయతీ మరియు నగర పాలక సంస్థ ఎన్నికలు రాష్ట్ర ఎన్నికల సంఘం (SEC) పర్యవేక్షణలో జరుగుతాయి — ECI కాదు.'),
    (0,
     'medium',
     'When does Model Code of Conduct apply?\nతెలుగు: Model Code of Conduct (MCC) ఎప్పుడు అమలవుతుంది?',
     'After election date announcement / ఎన్నికల తేదీ ప్రకటించిన తర్వాత',
     'After election schedule announced / ఎన్నికల షెడ్యూల్ ప్రకటించిన తర్వాత',
     '24 hours before polling / ఓటింగ్ తేదీ కి 24 గంటల ముందు',
     'From January 1 / జనవరి 1 నుండి',
     'b',
     'MCC comes into force from date of election schedule announcement and ends after results. / MCC (Model Code of Conduct) ఎన్నికల షెడ్యూల్ ప్రకటించిన తేదీ నుండి అమలవుతుంది మరియు ఫలితాల తర్వాత ముగుస్తుంది.'),
    (0,
     'hard',
     "What does 'superintendence, direction and control' under Art.324 include?\nతెలుగు: Art.324 కింద ఎన్నికల సంఘానికి 'Superintendence, direction and control' అంటే ఏమిటి?",
     'Only voter list management / కేవలం ఓటర్ జాబితాల నిర్వహణ',
     'All aspects — rolls, date-setting, candidacy, polling, supervision / ఎన్నికల నిర్వహణ యొక్క అన్ని అంశాలు — నమోదు, ఎన్నికల తేదీ నిర్ణయం, అభ్యర్థుల నమోదు, పోలింగ్, పర్యవేక్షణ',
     'Only polling management / కేవలం ఓటింగ్ నిర్వహణ',
     'Only symbol allocation / కేవలం పార్టీ గుర్తుల కేటాయింపు',
     'b',
     "Art.324: ECI's plenary power covers all aspects of election process — rolls, schedule, candidates, polling, counting, supervision. / Art.324: ECI కి ఎన్నికల నమోదు, ఎన్నికల షెడ్యూల్ నిర్ణయం, అభ్యర్థుల నమోదు, ఓటింగ్ నిర్వహణ, పర్యవేక్షణ వంటి అన్ని అంశాలలో అధికారం ఉంది."),
    (1,
     'easy',
     'Which Article establishes UPSC?\nతెలుగు: UPSC స్థాపనను ఏ అనుచ్ఛేదం ప్రస్తావిస్తుంది?',
     'Art.280',
     'Art.315',
     'Art.324',
     'Art.148',
     'b',
     'Art.315: Establishes Union Public Service Commission (UPSC). / Art.315: కేంద్ర లోక్ సేవా సంఘం (UPSC) ను స్థాపిస్తుంది.'),
    (1,
     'easy',
     'Who appoints UPSC Chairman and members?\nతెలుగు: UPSC అధ్యక్షుడు మరియు సభ్యులను ఎవరు నియమిస్తారు?',
     'Prime Minister / ప్రధానమంత్రి',
     'President / రాష్ట్రపతి',
     'Union Home Minister / కేంద్ర హోం మంత్రి',
     'Lok Sabha Speaker / లోక్\u200cసభ స్పీకర్',
     'b',
     'Art.316: UPSC Chairman and members appointed by President. / Art.316: UPSC అధ్యక్షుడు మరియు సభ్యులను రాష్ట్రపతి నియమిస్తారు.'),
    (1,
     'medium',
     "UPSC Chairman's tenure?\nతెలుగు: UPSC అధ్యక్షుడి పదవీకాలం ఎంత?",
     '5 years or age 65, whichever earlier / 5 సంవత్సరాలు లేదా 65 సంవత్సరాల వయస్సు వరకు',
     '6 years or age 65, whichever earlier / 6 సంవత్సరాలు లేదా 65 సంవత్సరాల వయస్సు వరకు',
     '5 years or age 62, whichever earlier / 5 సంవత్సరాలు లేదా 62 సంవత్సరాల వయస్సు వరకు',
     '4 years / 4 సంవత్సరాలు',
     'b',
     'Art.316(2): UPSC Chairman/members hold office for 6 years or until age 65, whichever is earlier. / Art.316(2): UPSC అధ్యక్షుడు/సభ్యులు 6 సంవత్సరాలు లేదా 65 సంవత్సరాల వయస్సు వరకు — ఏది ముందు వస్తే అది.'),
    (1,
     'medium',
     'How is UPSC Chairman removed?\nతెలుగు: UPSC అధ్యక్షుడి తొలగింపు విధానం ఏమిటి?',
     "President's order directly / రాష్ట్రపతి ఉత్తర్వుతో నేరుగా",
     "President's order after SC inquiry / SC విచారణ తర్వాత రాష్ట్రపతి ఆదేశంతో",
     'Parliament special majority + President / పార్లమెంట్ ప్రత్యేక మెజారిటీ + రాష్ట్రపతి ఆదేశం',
     "On PM's recommendation / ప్రధానమంత్రి సిఫారసుతో",
     'b',
     'Art.317: UPSC Chairman removed by President on SC inquiry — for misbehaviour, insolvency, disqualification, infirmity. / Art.317: UPSC అధ్యక్షుడు/సభ్యులను SC విచారణ తర్వాత రాష్ట్రపతి తొలగించవచ్చు. మతలబు మాని, దివాళా, అనర్హ కార్యకలాపాలు, శారీరక/మానసిక అసమర్థత ఆధారంగా.'),
    (1,
     'medium',
     'Main functions of UPSC?\nతెలుగు: UPSC ప్రధాన విధులు ఏమిటి?',
     'Tax collection / పన్నుల వసూలు',
     'Recruitment exams for AIS, Central Services, Defence / All India Services, Central Services, రక్షణ సేవలకు నియామకాలు, పరీక్షలు నిర్వహించడం',
     'Budget preparation / బడ్జెట్ తయారీ',
     'State elections / రాష్ట్ర ఎన్నికల నిర్వహణ',
     'b',
     'Art.320: UPSC conducts exams for AIS and Central Services; advises on appointments, disciplinary matters, transfers, promotions. / UPSC విధులు (Art.320): All India Services, Central Services పరీక్షలు నిర్వహించడం; నియామకాల విషయంలో సలహా; క్రమశిక్షణ వ్యవహారాలు; బదిలీ మరియు పదోన్నతి.'),
    (1,
     'hard',
     'One qualification prescribed for UPSC members?\nతెలుగు: UPSC సభ్యుల నియామకానికి ఒక అర్హత ఏమిటి?',
     '10 years IAS experience / 10 సంవత్సరాల IAS అనుభవం',
     'At least half must have 10 years in Union or State services / UPSC సభ్యులలో కనీసం సగం కేంద్ర/రాష్ట్ర సేవలో 10 సంవత్సరాల అనుభవం కలిగి ఉండాలి',
     'Law degree required / Law degree అవసరం',
     'Must be IPS officer / IPS అధికారి అయి ఉండాలి',
     'b',
     'Art.316(2): At least half of UPSC members must have been in Union or State government service for at least 10 years. / Art.316(2): UPSC సభ్యులలో కనీసం సగం కేంద్ర లేదా రాష్ట్ర ప్రభుత్వ సేవలో కనీసం 10 సంవత్సరాల అనుభవం కలిగి ఉండాలి.'),
    (1,
     'medium',
     'UPSC annual report submitted to?\nతెలుగు: UPSC వార్షిక నివేదిక ఎవరికి సమర్పిస్తుంది?',
     'Prime Minister / ప్రధానమంత్రికి',
     'President / రాష్ట్రపతికి',
     'Lok Sabha Speaker / లోక్\u200cసభ స్పీకర్\u200cకు',
     'CAG / CAG కి',
     'b',
     'Art.323: UPSC annual report presented to President, who lays it before Parliament. / Art.323: UPSC వార్షిక నివేదికను రాష్ట్రపతికి సమర్పిస్తుంది — ఆ నివేదికను రాష్ట్రపతి పార్లమెంట్ ముందు ఉంచుతారు.'),
    (1,
     'hard',
     'UPSC member cannot hold after retirement?\nతెలుగు: UPSC సభ్యుడు పదవీ విరమణ తర్వాత ఏ పదవి స్వీకరించలేరు?',
     'Political office / రాజకీయ పదవి',
     'Central or state government employment / కేంద్ర లేదా రాష్ట్ర ప్రభుత్వ పదవి',
     'University position / విశ్వవిద్యాలయ పదవి',
     'Judicial position / న్యాయ పదవి',
     'b',
     'Art.319: UPSC Chairman ineligible for further employment under Centre or State; members can be appointed UPSC Chairman but not any other government employment. / Art.319: UPSC అధ్యక్షుడు పదవీ విరమణ తర్వాత కేంద్ర/రాష్ట్ర ప్రభుత్వ ఉద్యోగానికి అర్హత లేదు. సభ్యులు UPSC CJ అవ్వవచ్చు కానీ వేరే ఏ ప్రభుత్వ పదవీ స్వీకరించలేరు.'),
    (2,
     'easy',
     'CAG establishment?\nతెలుగు: CAG (Comptroller & Auditor General) స్థాపన ఏ అనుచ్ఛేదం?',
     'Art.143',
     'Art.148',
     'Art.280',
     'Art.315',
     'b',
     'Art.148: Establishes the Comptroller and Auditor General of India. / Art.148: భారత నియంత్రక మహాపరీక్షకుడు (CAG) పదవిని స్థాపిస్తుంది.'),
    (2,
     'easy',
     'Who appoints the CAG?\nతెలుగు: CAG ని ఎవరు నియమిస్తారు?',
     'Prime Minister / ప్రధానమంత్రి',
     'President / రాష్ట్రపతి',
     'Finance Minister / ఆర్థిక మంత్రి',
     'Parliament / పార్లమెంట్',
     'b',
     'Art.148(1): CAG appointed by President under his hand and seal. / Art.148(1): CAG ని రాష్ట్రపతి నియమిస్తారు — ఆయన ఒక వారెంట్ ద్వారా పదవి స్వీకరిస్తారు.'),
    (2,
     'medium',
     "CAG's tenure?\nతెలుగు: CAG పదవీ కాలం ఎంత?",
     '5 years or age 65 / 5 సంవత్సరాలు లేదా 65 సంవత్సరాలు వయస్సు వరకు',
     '6 years or age 65 / 6 సంవత్సరాలు లేదా 65 సంవత్సరాలు వయస్సు వరకు',
     'As per Parliament law / పార్లమెంట్ చట్టం ప్రకారం',
     "At President's pleasure / రాష్ట్రపతి ఇష్టానుసారం",
     'b',
     'CAG: 6 years or 65 years of age, whichever is earlier. / CAG: 6 సంవత్సరాలు లేదా 65 సంవత్సరాల వయస్సు వరకు — ఏది ముందు వస్తే అది.'),
    (2,
     'medium',
     'How is CAG removed?\nతెలుగు: CAG ని ఎలా తొలగించవచ్చు?',
     "President's order directly / రాష్ట్రపతి ఉత్తర్వుతో నేరుగా",
     'Like SC judge — special majority + President / SC న్యాయమూర్తి మాదిరిగా — పార్లమెంట్ ప్రత్యేక మెజారిటీ + రాష్ట్రపతి ఆదేశం',
     "PM's recommendation / ప్రధానమంత్రి సిఫారసుతో",
     'Parliament simple majority / పార్లమెంట్ సాధారణ మెజారిటీ',
     'b',
     "Art.148(1): CAG removed same as SC judge — special majority of Parliament + President's order. / Art.148(1): CAG ని SC న్యాయమూర్తి మాదిరిగా తొలగించవచ్చు — proved misbehaviour/incapacity పై పార్లమెంట్ ప్రత్యేక మెజారిటీ + రాష్ట్రపతి ఆదేశం."),
    (2,
     'medium',
     "Who called CAG 'guardian of the public purse'?\nతెలుగు: CAG ని 'ఇండియన్ డెమోక్రసీ యొక్క రక్షకుడు' అని ఎవరు అన్నారు?",
     'B.R. Ambedkar',
     'Jawaharlal Nehru',
     'Ambedkar in Constituent Assembly / Dr. B.R. Ambedkar (రాజ్యాంగ సభలో)',
     'Alladi Krishnaswami Ayyar',
     'c',
     "Dr. Ambedkar called CAG 'most important officer in the Constitution' in the Constituent Assembly debates. / Dr. B.R. Ambedkar: రాజ్యాంగ సభలో CAG ని 'Most important officer in the Constitution' అన్నారు."),
    (2,
     'medium',
     'What reports does CAG submit to Parliament?\nతెలుగు: CAG ఏ నివేదికలు పార్లమెంట్\u200cకు సమర్పిస్తారు?',
     'Only defence audit report / కేవలం రక్షణ ఆడిట్ నివేదిక',
     'Union Revenue accounts, Expenditure audit, PSU audit reports / కేంద్ర ఆదాయ ఖాతాలు, వ్యయ ఆడిట్, ప్రభుత్వ సంస్థల ఆడిట్ నివేదికలు',
     'Only to Finance Minister / కేవలం ఆర్థిక మంత్రికి',
     'Only to PAC / కేవలం PAC కి',
     'b',
     "CAG submits 3 audit reports to President who places before Parliament's PAC (Public Accounts Committee). / CAG మూడు ఆడిట్ నివేదికలు రాష్ట్రపతికి సమర్పిస్తారు (రాష్ట్రపతి పార్లమెంట్\u200cలో PAC ముందు ఉంచుతారు): (1) Union Government (Civil) Accounts, (2) Finance Accounts, (3) Appropriation Accounts."),
    (2,
     'hard',
     'CAG cannot hold which post after retirement?\nతెలుగు: CAG పదవీ విరమణ తర్వాత ఏ పదవి స్వీకరించలేరు?',
     'Rajya Sabha membership / రాజ్యసభ సభ్యత్వం',
     'Union or State government employment / కేంద్ర లేదా రాష్ట్ర ప్రభుత్వ పదవి',
     'SC judge / SC న్యాయమూర్తి',
     'University post / విశ్వవిద్యాలయ పదవి',
     'b',
     'Art.148(4): CAG ineligible for further government employment after retirement — to protect independence. / Art.148(4): CAG పదవీ విరమణ తర్వాత కేంద్ర లేదా రాష్ట్ర ప్రభుత్వ ఉద్యోగానికి అర్హత లేదు — న్యాయిక స్వాతంత్ర్యం కాపాడటానికి.'),
    (2,
     'hard',
     'PAC is related to?\nతెలుగు: Public Accounts Committee (PAC) ఎవరికి సంబంధించింది?',
     'Defence Ministry / రక్షణ శాఖ',
     'Parliamentary committee that examines CAG reports / CAG నివేదికలను పరీక్షించే పార్లమెంట్ కమిటీ',
     'Finance Ministry / ఆర్థిక మంత్రిత్వ శాఖ',
     'UPSC',
     'b',
     'PAC: Finance committee of Parliament that examines CAG audit reports. Chair is conventionally from opposition party. / PAC (Public Accounts Committee): లోక్\u200cసభ ఆర్థిక కమిటీ — CAG ఆడిట్ నివేదికలను పరీక్షిస్తుంది. చైర్మన్ సాంప్రదాయికంగా విపక్ష నాయకుడు.'),
    (3,
     'easy',
     'Which Article establishes Finance Commission?\nతెలుగు: ఆర్థిక సంఘాన్ని ప్రస్తావించే అనుచ్ఛేదం ఏది?',
     'Art.148',
     'Art.265',
     'Art.280',
     'Art.315',
     'c',
     'Art.280: Establishes Finance Commission — distributes taxes between Centre and States. / Art.280: ఆర్థిక సంఘం (Finance Commission) ను స్థాపిస్తుంది — కేంద్ర మరియు రాష్ట్రాల మధ్య పన్నుల పంపిణీ.'),
    (3,
     'easy',
     'Who constitutes the Finance Commission?\nతెలుగు: ఆర్థిక సంఘాన్ని ఎవరు నియమిస్తారు?',
     'Prime Minister / ప్రధానమంత్రి',
     'President / రాష్ట్రపతి',
     'Lok Sabha Speaker / లోక్\u200cసభ స్పీకర్',
     'CAG',
     'b',
     'Art.280(1): President constitutes Finance Commission — every 5 years or earlier if necessary. / Art.280(1): ఆర్థిక సంఘాన్ని రాష్ట్రపతి ఏర్పాటు చేస్తారు — ప్రతి 5 సంవత్సరాలకు లేదా అవసరమైనప్పుడు.'),
    (3,
     'medium',
     'Main functions of Finance Commission?\nతెలుగు: ఆర్థిక సంఘం ప్రధాన విధులు ఏమిటి?',
     'Budget preparation / బడ్జెట్ తయారీ',
     'Tax devolution formula, grants-in-aid principles, fiscal discipline measures / అంటే: పన్ను పంచాయితీ, గ్రాంట్స్-ఇన్-ఎయిడ్ సూత్రాలు, ఆర్థిక క్రమశిక్షణ చర్యలు',
     'Approving state loans / రాష్ట్రాల అప్పులు ఆమోదించడం',
     'Implementing FRBM Act / FRBM చట్టం అమలు',
     'b',
     'Art.280(3): Distribute net tax proceeds, grants-in-aid to states, advise on any financial matter referred by President. / Art.280(3): FC విధులు: (1) కేంద్ర పన్నుల నికర ఆదాయాన్ని కేంద్ర-రాష్ట్రాల మధ్య పంచటం, (2) రాష్ట్రాలకు గ్రాంట్స్-ఇన్-ఎయిడ్ సూత్రాలు, (3) ఆర్థిక ప్రశ్నలపై రాష్ట్రపతి నిర్దేశించిన సలహా.'),
    (3,
     'medium',
     '16th Finance Commission covers which period?\nతెలుగు: 16వ ఆర్థిక సంఘం ఏ కాలానికి వర్తిస్తుంది?',
     '2020–25',
     '2021–26',
     '2026–31',
     '2025–30',
     'c',
     '16th Finance Commission (constituted 2023) covers 2026–2031. / 16వ ఆర్థిక సంఘం (2023 లో నియమించారు) 2026–2031 కాలానికి వర్తిస్తుంది.'),
    (3,
     'medium',
     'Number of members in Finance Commission?\nతెలుగు: ఆర్థిక సంఘంలో ఎంత మంది సభ్యులు ఉంటారు?',
     '3 / అధ్యక్షుడు + 2',
     '5 / అధ్యక్షుడు + 4',
     '7 / అధ్యక్షుడు + 6',
     'Parliament determines / పార్లమెంట్ నిర్ణయిస్తుంది',
     'b',
     'Finance Commission: Chairman + 4 members = 5 total. Qualifications and tenure determined by Parliament. / Finance Commission లో అధ్యక్షుడు + 4 సభ్యులు = మొత్తం 5 మంది ఉంటారు. వారి అర్హతలు, పదవీకాలం పార్లమెంట్ నిర్ణయిస్తుంది.'),
    (3,
     'hard',
     "Is Finance Commission's recommendation binding on President?\nతెలుగు: ఆర్థిక సంఘం అభిప్రాయం రాష్ట్రపతిపై బైండింగ్\u200cగా ఉంటుందా?",
     'Yes, mandatory / అవును, తప్పనిసరిగా',
     'No, only advisory / కాదు, కేవలం సలహా మాత్రమే',
     'Yes, for state matters / అవును, రాష్ట్రాల విషయాలలో',
     'Yes, with Parliament approval / అవును, పార్లమెంట్ ఆమోదంతో',
     'b',
     "Finance Commission's recommendations are advisory only — not binding on President; but in practice almost all accepted. / ఆర్థిక సంఘం అభిప్రాయాలు సలహా మాత్రమే (advisory) — రాష్ట్రపతిపై బైండింగ్ కాదు. అయితే ఆచరణలో దాదాపు అన్ని సిఫారసులు అంగీకరించబడతాయి."),
    (3,
     'hard',
     '15th FC devolution share to states?\nతెలుగు: 15వ ఆర్థిక సంఘం (NK Singh) రాష్ట్రాలకు నికర కేంద్ర పన్నుల శాతం ఎంత?',
     '38%',
     '41%',
     '42%',
     '45%',
     'b',
     "15th FC (NK Singh): recommended 41% devolution to states (reduced from 14th FC's 42% due to J&K reorganisation). / 15వ ఆర్థిక సంఘం (NK Singh, 2020–26): రాష్ట్రాలకు నికర కేంద్ర పన్నుల 41% వాటా సిఫారసు చేసింది (14వ FC లో 42% ఉండేది — J&K పునర్వ్యవస్థీకరణ కారణంగా 1% తగ్గించారు)."),
    (3,
     'medium',
     'What does FC recommend under Art.275?\nతెలుగు: ఆర్థిక సంఘం Art.275 కింద ఏమి చేయగలదు?',
     'Development loans / అభివృద్ధి అప్పులు',
     'Grants-in-aid principles to states / రాష్ట్రాలకు Grants-in-aid సూత్రాలు',
     'FRBM implementation / FRBM చట్ట అమలు',
     'State FRBM recommendations / స్టేట్ FRBMs సిఫారసు',
     'b',
     'Art.275: Grants-in-aid to states — Finance Commission recommends the principles for determining these grants. / Art.275: రాష్ట్రాలకు Grants-in-aid (అనుదానాలు). ఆర్థిక సంఘం ఈ అనుదానాల పంపిణీ సూత్రాలను నిర్ణయిస్తుంది.'),
    (4,
     'easy',
     'Which Article establishes the Attorney General of India?\nతెలుగు: భారత అటార్నీ జనరల్ (AG) ని స్థాపించే అనుచ్ఛేదం ఏది?',
     'Art.74',
     'Art.76',
     'Art.78',
     'Art.88',
     'b',
     'Art.76: Establishes Attorney General of India — highest law officer of the Union. / Art.76: భారత అటార్నీ జనరల్ పదవిని స్థాపిస్తుంది — కేంద్ర ప్రభుత్వ అత్యున్నత న్యాయ అధికారి.'),
    (4,
     'easy',
     'Who appoints the Attorney General?\nతెలుగు: అటార్నీ జనరల్\u200cని ఎవరు నియమిస్తారు?',
     'Prime Minister / ప్రధానమంత్రి',
     'President / రాష్ట్రపతి',
     'CJI',
     'Lok Sabha Speaker / లోక్\u200cసభ స్పీకర్',
     'b',
     'Art.76(1): AG appointed by President; must be qualified to be SC judge (i.e., HC advocate for 10 years). / Art.76(1): అటార్నీ జనరల్\u200cని రాష్ట్రపతి నియమిస్తారు — SC న్యాయమూర్తిగా నియమించబడటానికి అర్హుడైన వ్యక్తి.'),
    (4,
     'medium',
     'Rights of the Attorney General?\nతెలుగు: అటార్నీ జనరల్ హక్కులు ఏమిటి?',
     'Only in SC / కేవలం SC లో వాదించవచ్చు',
     'Practice in all courts; speak in Parliament / భారతదేశంలో అన్ని కోర్టులలో వాదించవచ్చు; పార్లమెంట్\u200cలో మాట్లాడవచ్చు',
     'Only SC; voting right in Parliament / SC లో మాత్రమే వాదించవచ్చు, పార్లమెంట్\u200cలో ఓటు హక్కుంది',
     'Cannot practice in any court / ఏ కోర్టులోనూ వాదించలేడు',
     'b',
     'Art.76(4): AG has right of audience in all courts in India; can speak in both Houses of Parliament but cannot vote. / Art.76(4): AG కి భారతదేశంలో అన్ని కోర్టులలో వాదించే హక్కు ఉంది. పార్లమెంట్ ఉభయ సభలలో మాట్లాడవచ్చు కానీ ఓటు హక్కు లేదు.'),
    (4,
     'medium',
     'Can AG appear against private parties?\nతెలుగు: అటార్నీ జనరల్ ప్రైవేట్ అభ్యర్థులకు వ్యతిరేకంగా వాదించవచ్చా?',
     'Yes, always / అవును, ఎల్లప్పుడూ',
     'No, not against private parties without government permission / కాదు, ప్రభుత్వ అనుమతి లేకుండా ప్రైవేట్ అభ్యర్థులకు వ్యతిరేకంగా కాదు',
     'Yes, in any case / అవున, ఏ కేసులోనైనా',
     'Only in SC cases / కేవలం SC కేసులలో',
     'b',
     'AG is a law officer of Union — advises government, represents Centre in courts. Cannot appear against Centre or represent private parties in cases against Centre. / AG ప్రభుత్వ న్యాయ అధికారి — కేంద్ర ప్రభుత్వానికి న్యాయ సలహా ఇస్తారు, అన్ని కోర్టులలో కేంద్ర ప్రభుత్వం తరపున హాజరవుతారు. ప్రైవేట్ అభ్యర్థులకు వ్యతిరేకంగా కేంద్రానికి వ్యతిరేక కేసులలో హాజరవలేరు.'),
    (4,
     'medium',
     "Solicitor General's rank vs AG?\nతెలుగు: సొలిసిటర్ జనరల్ (SG) AG కంటే హోదాలో ఎలా ఉంటారు?",
     'SG higher than AG / SG AG కంటే ఎక్కువ హోదా',
     'SG lower rank than AG / SG AG కంటే తక్కువ హోదా',
     'Both equal rank / రెండూ సమానమైన హోదా',
     'SG is state-level officer / SG రాష్ట్ర స్థాయి అధికారి',
     'b',
     'Hierarchy: AG > Solicitor General > Additional Solicitor General. SG assists the AG. / హోదా క్రమం: AG > SG (Solicitor General) > ASG (Additional Solicitor General). సొలిసిటర్ జనరల్ AG కి సహాయపడతారు.'),
    (4,
     'hard',
     "AG's tenure?\nతెలుగు: AG పదవీకాలం ఎంత?",
     '5 years / 5 సంవత్సరాలు',
     "At President's pleasure / రాష్ట్రపతి ఇష్టానుసారం",
     '6 years / 6 సంవత్సరాలు',
     'Until age 65 / 65 సంవత్సరాల వయస్సు వరకు',
     'b',
     "Art.76: AG holds office during President's pleasure — no fixed tenure. President may remove at any time. / Art.76: AG రాష్ట్రపతి ఇష్టానుసారం పదవిలో ఉంటారు — నిర్దిష్ట పదవీకాలం లేదు. రాష్ట్రపతి ఎప్పుడైనా తొలగించవచ్చు."),
    (4,
     'hard',
     'Highest law officer of a State?\nతెలుగు: రాష్ట్రాల అత్యున్నత న్యాయ అధికారి ఎవరు?',
     'Public Prosecutor / పబ్లిక్ ప్రాసిక్యూటర్',
     'State Attorney General / రాష్ట్ర అటార్నీ జనరల్',
     'Advocate General / అడ్వకేట్ జనరల్',
     'State Solicitor General / రాష్ట్ర సొలిసిటర్ జనరల్',
     'c',
     'Art.165: Advocate General of the State is the highest law officer of a state — appointed by Governor. / Art.165: రాష్ట్ర అడ్వకేట్ జనరల్ (AG of State) అత్యున్నత రాష్ట్ర న్యాయ అధికారి — గవర్నర్ నియమిస్తారు.'),
    (4,
     'medium',
     "AG's parliamentary privileges?\nతెలుగు: అటార్నీ జనరల్ పార్లమెంట్\u200cలో ఏ హక్కులు అనుభవిస్తారు?",
     'Vote + speaking right / ఓటు + మాట్లాడే హక్కు',
     'Speaking right only, no voting right / మాట్లాడే హక్కు మాత్రమే, ఓటు హక్కు లేదు',
     'No rights / ఏ హక్కులూ లేవు',
     'Only in Rajya Sabha / కేవలం Rajya Sabha లో మాట్లాడవచ్చు',
     'b',
     'Art.88: AG may speak and take part in proceedings of both Houses but not entitled to vote. / Art.88: AG పార్లమెంట్ ఉభయ సభలలో మాట్లాడవచ్చు మరియు కమిటీలలో పాల్గొనవచ్చు — కానీ ఓటు హక్కు లేదు.'),
    (5,
     'easy',
     'National Commission for Scheduled Castes — which Article?\nతెలుగు: జాతీయ ఎస్సీ కమిషన్ ఏ అనుచ్ఛేదం?',
     'Art.338',
     'Art.338A',
     'Art.340',
     'Art.341',
     'a',
     'Art.338: National Commission for Scheduled Castes. / Art.338: జాతీయ ఎస్సీ కమిషన్ (National Commission for Scheduled Castes) ని స్థాపిస్తుంది.'),
    (5,
     'easy',
     'National Commission for Scheduled Tribes — which Article?\nతెలుగు: జాతీయ ఎస్టీ కమిషన్ ఏ అనుచ్ఛేదం?',
     'Art.338',
     'Art.338A',
     'Art.340',
     'Art.342',
     'b',
     'Art.338A (added by 89th Amendment 2003): National Commission for Scheduled Tribes. / Art.338A: జాతీయ ఎస్టీ కమిషన్ (National Commission for Scheduled Tribes) ని స్థాపిస్తుంది. 89వ సవరణ (2003) ద్వారా వేరు చేశారు.'),
    (5,
     'medium',
     'What did the 89th Constitutional Amendment (2003) do?\nతెలుగు: 89వ రాజ్యాంగ సవరణ (2003) ఏమి చేసింది?',
     'Established OBC Commission / OBC కమిషన్ స్థాపన',
     'Created separate National Commissions for SC and ST / SC మరియు ST కి వేర్వేరు జాతీయ కమిషన్లు ఏర్పాటు చేసింది',
     "Constitutionalised Women's Commission / మహిళా కమిషన్ రాజ్యాంగీకరణ",
     'Established Minorities Commission / మైనారిటీ కమిషన్ స్థాపన',
     'b',
     '89th Amendment 2003: Split combined SC/ST commission into Art.338 (SC) and Art.338A (ST) separately. / 89వ సవరణ (2003): మొదట Art.338 లో SC మరియు ST కి కలిపి ఉన్న కమిషన్\u200cను విభజించి, Art.338 (SC మాత్రమే) మరియు Art.338A (ST మాత్రమే) గా చేసింది.'),
    (5,
     'medium',
     'Article for OBC Commission?\nతెలుగు: OBC (వెనుకబడిన వర్గాల) కమిషన్\u200cకు సంబంధించిన అనుచ్ఛేదం ఏది?',
     'Art.338A',
     'Art.338B',
     'Art.340',
     'Art.341',
     'c',
     'Art.340: President may appoint a commission to investigate conditions of socially and educationally backward classes. / Art.340: వెనుకబడిన వర్గాల దశ నిర్ణయించడానికి కమిషన్ వేయడానికి రాష్ట్రపతికి అధికారం ఇస్తుంది.'),
    (5,
     'hard',
     'Is National Commission for Women a Constitutional body?\nతెలుగు: జాతీయ మహిళా కమిషన్ రాజ్యాంగ సంస్థగా ఉందా?',
     'Yes, under Art.332 / అవును, Art.332 కింద',
     'No, it is a statutory body / కాదు, ఇది చట్టబద్ధ సంస్థ (National Commission for Women Act, 1990)',
     'Yes, under Art.15 / అవున, Art.15 కింద',
     'Yes, via 73rd Amendment / అవున, 73వ సవరణ ద్వారా',
     'b',
     'National Commission for Women is a statutory body under NCW Act 1990 — NOT a constitutional body. / జాతీయ మహిళా కమిషన్ National Commission for Women Act, 1990 ద్వారా స్థాపించబడింది — రాజ్యాంగ సంస్థ కాదు, చట్టబద్ధ సంస్థ.'),
    (5,
     'medium',
     'NC for SC report submitted to?\nతెలుగు: జాతీయ SC కమిషన్ అధ్యక్షుడు నివేదిక ఎవరికి సమర్పిస్తారు?',
     'Prime Minister / ప్రధానమంత్రికి',
     'President / రాష్ట్రపతికి',
     'Lok Sabha Speaker / లోక్\u200cసభ స్పీకర్\u200cకు',
     'Social Justice Minister / సామాజిక న్యాయ మంత్రికి',
     'b',
     'Art.338(6): NC for SC submits annual report to President who lays it before Parliament. / Art.338(6): జాతీయ SC కమిషన్ నివేదికను రాష్ట్రపతికి సమర్పిస్తుంది — ఆయన పార్లమెంట్\u200cలో ఉంచుతారు.'),
    (5,
     'hard',
     'Art.338B added by which amendment?\nతెలుగు: Art.338B — జాతీయ OBC కమిషన్ ఏ సవరణ ద్వారా చేర్చారు?',
     '89th Amendment 2003 / 89వ సవరణ 2003',
     '102nd Amendment 2018 / 102వ సవరణ 2018',
     '105th Amendment 2021 / 105వ సవరణ 2021',
     '91st Amendment 2003 / 91వ సవరణ 2003',
     'b',
     'Art.338B (NC for Backward Classes) was inserted by the 102nd Constitutional Amendment Act, 2018. / Art.338B (National Commission for Backward Classes) 102వ రాజ్యాంగ సవరణ చట్టం, 2018 ద్వారా జోడించబడింది.'),
    (5,
     'medium',
     'Is National Commission for Minorities a Constitutional body?\nతెలుగు: జాతీయ మైనారిటీ కమిషన్ రాజ్యాంగ సంస్థగా ఉందా?',
     'Yes, under Art.29 / అవును, Art.29 కింద',
     'No, statutory body under NCM Act 1992 / కాదు, చట్టబద్ధ సంస్థ (NCM Act, 1992)',
     'Yes, under Art.30 / అవున, Art.30 కింద',
     'Yes, via 44th Amendment / అవున, 44వ సవరణ ద్వారా',
     'b',
     'NCM established under NCM Act 1992 — NOT constitutional. Compare: NC for SC (Art.338) and NC for ST (Art.338A) ARE constitutional. / జాతీయ మైనారిటీ కమిషన్ National Minorities Commission Act, 1992 ద్వారా స్థాపించబడింది — రాజ్యాంగ సంస్థ కాదు.'),
    (6,
     'easy',
     'State Public Service Commission?\nతెలుగు: రాష్ట్ర లోక్ సేవా సంఘం (SPSC) ఏ అనుచ్ఛేదం?',
     'Art.315',
     'Art.316',
     'Art.315 (same for states) / Art.315 (రాష్ట్రాలకు కూడా అదే)',
     'Art.318',
     'c',
     'Art.315: Provides for UPSC and for SPSCs. Each state shall have a SPSC. / Art.315: UPSC మరియు SPSC లను ప్రస్తావిస్తుంది. రాష్ట్ర PSC ని రాష్ట్రానికి స్థాపిస్తుంది.'),
    (6,
     'easy',
     'SPSC Chairman and members appointed by?\nతెలుగు: రాష్ట్ర PSC అధ్యక్షుడు మరియు సభ్యులను ఎవరు నియమిస్తారు?',
     'Chief Minister / ముఖ్యమంత్రి',
     'Governor of the State / రాష్ట్ర గవర్నర్',
     'President / రాష్ట్రపతి',
     'UPSC Chairman / UPSC అధ్యక్షుడు',
     'b',
     'Art.316(1): SPSC Chairman and members appointed by the Governor of the State. / Art.316(1): రాష్ట్ర PSC అధ్యక్షుడు మరియు సభ్యులను రాష్ట్ర గవర్నర్ నియమిస్తారు.'),
    (6,
     'medium',
     'Who removes SPSC Chairman?\nతెలుగు: రాష్ట్ర PSC అధ్యక్షుడిని తొలగించే అధికారం ఎవరికి ఉంది?',
     'Chief Minister / ముఖ్యమంత్రి',
     'Governor / రాష్ట్ర గవర్నర్',
     'President (after SC inquiry) / రాష్ట్రపతి (SC విచారణ తర్వాత)',
     'State Assembly / రాష్ట్ర అసెంబ్లీ',
     'c',
     'Art.317: SPSC Chairman removed by President (after SC inquiry) — not by Governor. / Art.317: రాష్ట్ర PSC అధ్యక్షుడు/సభ్యులను రాష్ట్రపతి తొలగించవచ్చు (SC విచారణ తర్వాత) — గవర్నర్ కాదు.'),
    (6,
     'medium',
     'Joint PSC for two or more states?\nతెలుగు: రెండు లేదా అంతకు మించిన రాష్ట్రాలకు ఉమ్మడి PSC (Joint PSC) ఏ అనుచ్ఛేదం కింద?',
     'Art.315',
     'Art.316',
     'Art.315(2)/(3)',
     'Art.320',
     'c',
     'Art.315(2): Parliament by law may create Joint PSC for two or more states. Joint PSC Chairman appointed by President. / Art.315(2)&(3): పార్లమెంట్ చట్టం ద్వారా రెండు లేదా అంతకు మించిన రాష్ట్రాలకు ఉమ్మడి PSC స్థాపించవచ్చు. Joint PSC అధ్యక్షుడిని రాష్ట్రపతి నియమిస్తారు.'),
    (6,
     'hard',
     'Key difference between SPSC and UPSC?\nతెలుగు: రాష్ట్ర PSC మరియు UPSC మధ్య ముఖ్యమైన తేడా ఏమిటి?',
     'UPSC Chair appointed by Governor / UPSC అధ్యక్షుడు గవర్నర్ నియమిస్తారు',
     'Both removed by President after SC inquiry / SPSC అధ్యక్షుడు తొలగింపు: రాష్ట్రపతి (SC inquiry తర్వాత); UPSC అధ్యక్షుడు తొలగింపు: రాష్ట్రపతి (SC inquiry తర్వాత) — రెండూ ఒకే విధానం',
     'SPSC report to Governor; UPSC report to President / SPSC వార్షిక నివేదిక గవర్నర్\u200cకు; UPSC నివేదిక రాష్ట్రపతికి',
     'SPSC is not constitutional / SPSC రాజ్యాంగ సంస్థ కాదు',
     'c',
     'SPSC annual report to Governor (Art.323(2)); UPSC report to President. / SPSC వార్షిక నివేదికను గవర్నర్\u200cకు సమర్పిస్తుంది (Art.323(2)) — గవర్నర్ రాష్ట్ర అసెంబ్లీ ముందు ఉంచుతారు. UPSC నివేదిక రాష్ట్రపతికి.'),
    (6,
     'medium',
     'One mandatory qualification for SPSC members?\nతెలుగు: SPSC సభ్యుల నియామకంలో ఒక తప్పనిసరి అర్హత ఏమిటి?',
     'IAS experience / IAS అనుభవం',
     'At least half must have 10 years in state government service / కనీసం సగం మంది రాష్ట్ర ప్రభుత్వ సేవలో 10 సంవత్సరాల అనుభవం',
     'Law degree',
     'Eligible to be SC judge / SC న్యాయమూర్తిగా నియమించబడటానికి అర్హత',
     'b',
     'Art.316(2): At least half of SPSC members must have 10 years in state government service. / Art.316(2): UPSC/SPSC సభ్యులలో కనీసం సగం కేంద్ర/రాష్ట్ర ప్రభుత్వ సేవలో 10 సంవత్సరాల అనుభవం ఉండాలి.'),
    (6,
     'hard',
     'What post can SPSC Chairman take after retirement?\nతెలుగు: రాష్ట్ర PSC అధ్యక్షుడు పదవీ విరమణ తర్వాత ఏ పదవి స్వీకరించవచ్చు?',
     'Back in SPSC / SPSC లో మళ్ళీ',
     'UPSC Chairman or member / UPSC అధ్యక్షుడు లేదా సభ్యుడు',
     'Any state government post / ఏ రాష్ట్ర ప్రభుత్వ పదవి అయినా',
     'As state minister / రాష్ట్ర మంత్రిగా',
     'b',
     'Art.319(c): SPSC Chairman can be appointed UPSC Chairman or member after retirement; but not further SPSC or state government employment. / Art.319(c): SPSC అధ్యక్షుడు పదవీ విరమణ తర్వాత UPSC అధ్యక్షుడు లేదా సభ్యుడు కావచ్చు — కానీ SPSC లో మళ్ళీ చేరలేరు.'),
    (6,
     'medium',
     'Tenure of SPSC Chairman and members?\nతెలుగు: SPSC అధ్యక్షుడు మరియు సభ్యుల పదవీకాలం ఎంత?',
     '5 years or age 62 / 5 సంవత్సరాలు లేదా 62 సంవత్సరాల వయసు',
     '6 years or age 65 / 6 సంవత్సరాలు లేదా 65 సంవత్సరాల వయసు',
     '3 years or age 60 / 3 సంవత్సరాలు లేదా 60 సంవత్సరాల వయసు',
     '5 years or age 65 / 5 సంవత్సరాలు లేదా 65 సంవత్సరాల వయసు',
     'b',
     'Art.316(2): SPSC Chairman/members hold office for 6 years or until age 65, whichever is earlier. Same as UPSC. / Art.316(2): SPSC అధ్యక్షుడు/సభ్యులు 6 సంవత్సరాలు లేదా 65 సంవత్సరాల వయసు చేరుకునే వరకు (ఏది ముందైనా) పదవిలో ఉంటారు. UPSC కూడా 6 సంవత్సరాలు/65 సంవత్సరాలు.'),
    (7,
     'easy',
     'Inter-State Council under which Article?\nతెలుగు: Inter-State Council (అంతర్రాష్ట్ర మండలి) ఏ అనుచ్ఛేదం?',
     'Art.261',
     'Art.263',
     'Art.280',
     'Art.315',
     'b',
     'Art.263: Inter-State Council — President may establish for coordination between states and Centre. / Art.263: అంతర్రాష్ట్ర మండలి — రాష్ట్రాల మధ్య సమన్వయానికి రాష్ట్రపతి నియమించవచ్చు.'),
    (7,
     'medium',
     'Zonal Councils established under?\nతెలుగు: Zonal Councils (ప్రాంతీయ మండళ్ళు) ఏ చట్టం కింద ఏర్పాటయ్యాయి?',
     'Constitution directly / రాజ్యాంగం',
     'States Reorganisation Act, 1956',
     'Inter-State Councils Act, 1990',
     'Parliament special Act, 2000',
     'b',
     '5 Zonal Councils (N/S/E/W/C) established under States Reorganisation Act 1956 — statutory, not constitutional. / 5 Zonal Councils (ఉత్తర, దక్షిణ, తూర్పు, పడమర, మధ్య) States Reorganisation Act, 1956 ద్వారా ఏర్పడ్డాయి — రాజ్యాంగ సంస్థలు కాదు, చట్టబద్ధ సంస్థలు.'),
    (7,
     'medium',
     'Is NITI Aayog a constitutional body?\nతెలుగు: NITI Aayog రాజ్యాంగ సంస్థగా ఉందా?',
     'Yes, under Art.39 / అవున, Art.39 కింద',
     'No, set up by executive resolution / కాదు, ఇది కార్యనిర్వాహక తీర్మానం (Executive Resolution) ద్వారా ఏర్పడ్డ సంస్థ',
     'Yes, via 74th Amendment / అవున, 74వ సవరణ ద్వారా',
     'Yes, under Art.280 / అవున, Art.280 కింద',
     'b',
     'NITI Aayog: executive resolution (Jan 2015), replaced Planning Commission — NOT a constitutional body. / NITI Aayog 2015 జనవరి 1 న కార్యనిర్వాహక తీర్మానం ద్వారా ఏర్పడింది — Planning Commission స్థానంలో. రాజ్యాంగ సంస్థ కాదు.'),
    (7,
     'hard',
     'NHRC under which Act?\nతెలుగు: National Human Rights Commission (NHRC) ఏ చట్టం కింద?',
     'Constitutional Art.21 / రాజ్యాంగ Art.21',
     'Protection of Human Rights Act, 1993',
     'Human Rights Act, 1948',
     'UN Convention on Human Rights',
     'b',
     'NHRC: statutory body under Protection of Human Rights Act, 1993 — NOT constitutional. / NHRC: Protection of Human Rights Act, 1993 కింద స్థాపించబడింది — రాజ్యాంగ సంస్థ కాదు, చట్టబద్ధ సంస్థ.'),
    (7,
     'medium',
     'Which of the following is a Constitutional Body?\nతెలుగు: కింది వాటిలో రాజ్యాంగ సంస్థ (Constitutional Body) ఏది?',
     'NITI Aayog',
     'NHRC',
     'National Commission for Scheduled Castes / జాతీయ ఎస్సీ కమిషన్',
     'National Commission for Women / జాతీయ మహిళా కమిషన్',
     'c',
     'NC for SC (Art.338) is constitutional; NITI Aayog, NHRC, NCW are NOT constitutional. / జాతీయ SC కమిషన్ Art.338 కింద రాజ్యాంగ సంస్థ. NITI Aayog (కార్యనిర్వాహక), NHRC (చట్టబద్ధ), NCW (చట్టబద్ధ) రాజ్యాంగ సంస్థలు కావు.'),
    (7,
     'medium',
     "Who called CAG 'most important officer in the Constitution'?\nతెలుగు: Comptroller & Auditor General (CAG) 'భారత రాజ్యాంగంలో అత్యంత ముఖ్యమైన అధికారి' అని ఎవరన్నారు?",
     'Jawaharlal Nehru',
     'Dr. B.R. Ambedkar',
     'Sardar Patel',
     'Alladi Krishnaswami Ayyar',
     'b',
     "Dr. Ambedkar called CAG 'most important officer in the Constitution' in Constituent Assembly. / రాజ్యాంగ సభలో Dr. B.R. Ambedkar CAG ని 'most important officer in the Constitution' అన్నారు — ఆయన ప్రభుత్వ ఖాతాల నిర్వహణలో కీలక పాత్ర పోషిస్తారు."),
    (7,
     'hard',
     'Key difference between Constitutional and Statutory bodies?\nతెలుగు: రాజ్యాంగ సంస్థలు మరియు చట్టబద్ధ సంస్థల మధ్య ముఖ్య తేడా ఏమిటి?',
     'Both formed the same way / రెండూ ఒకే విధంగా ఏర్పడతాయి',
     'Constitutional bodies via Constitution provisions; Statutory via Parliament Acts / రాజ్యాంగ సంస్థలు రాజ్యాంగ నిబంధనల ద్వారా; చట్టబద్ధ సంస్థలు పార్లమెంట్ చట్టాల ద్వారా ఏర్పడతాయి',
     'Statutory bodies have more powers / చట్టబద్ధ సంస్థలు ఎక్కువ అధికారాలు కలిగి ఉంటాయి',
     'Only constitutional bodies appointed by President / రాజ్యాంగ సంస్థలు మాత్రమే రాష్ట్రపతి నియమిస్తారు',
     'b',
     'Constitutional bodies: directly established by Constitution (ECI Art.324, UPSC Art.315, CAG Art.148, FC Art.280). Statutory: by Parliament Acts (NHRC, NCW, NCM). / రాజ్యాంగ సంస్థలు: రాజ్యాంగంలో నేరుగా ప్రస్తావించబడిన సంస్థలు (ECI, UPSC, CAG, FC). చట్టబద్ధ సంస్థలు: పార్లమెంట్ చట్టాల ద్వారా (NHRC, NCW, NCM).'),
    (7,
     'hard',
     'When was Inter-State Council constituted under Art.263?\nతెలుగు: Art.263 కింద Inter-State Council (అంతర్రాష్ట్ర మండలి) ఏ సంవత్సరంలో ఏర్పాటయింది?',
     '1950',
     '1990',
     '1956',
     '2000',
     'b',
     'Inter-State Council constituted in 1990 (on Sarkaria Commission recommendation); chaired by PM, members include all CMs and 6 union cabinet ministers. / అంతర్రాష్ట్ర మండలి Art.263 కింద 1990 లో (Sarkaria Commission సిఫారసుపై) ఏర్పాటయింది — PM అధ్యక్షత, అన్ని CM లు, 6 Union Cabinet మంత్రులు సభ్యులు.'),
]


def _seed_polity_ch22_notes_inner(conn, db_exec_fn, row_to_dict_fn, use_postgres, force=False):
    ph = '%s' if use_postgres else '?'
    existing = db_exec_fn(conn,
        f"SELECT id FROM study_notes WHERE subject={ph} AND topic={ph} AND chapter_num={ph}",
        (_SUBJECT, _TOPIC, _CH))
    row = row_to_dict_fn(existing.fetchone())

    if row and not force:
        return row['id']

    import json
    sections_json = json.dumps(_SECTIONS, ensure_ascii=False)

    if row:
        db_exec_fn(conn,
            f"UPDATE study_notes SET chapter_title_te={ph}, chapter_title_en={ph}, "
            f"pages_ref={ph}, sections_json={ph} "
            f"WHERE subject={ph} AND topic={ph} AND chapter_num={ph}",
            (_TITLE_TE, _TITLE_EN, _PAGES, sections_json, _SUBJECT, _TOPIC, _CH))
        return row['id']
    else:
        db_exec_fn(conn,
            f"INSERT INTO study_notes (subject, topic, chapter_num, chapter_title_te, "
            f"chapter_title_en, pages_ref, sections_json) VALUES ({ph},{ph},{ph},{ph},{ph},{ph},{ph})",
            (_SUBJECT, _TOPIC, _CH, _TITLE_TE, _TITLE_EN, _PAGES, sections_json))
        cur2 = db_exec_fn(conn,
            f"SELECT id FROM study_notes WHERE subject={ph} AND topic={ph} AND chapter_num={ph}",
            (_SUBJECT, _TOPIC, _CH))
        return row_to_dict_fn(cur2.fetchone())['id']


def _seed_polity_ch22_mcqs_inner(conn, db_exec_fn, row_to_dict_fn, use_postgres):
    ph = '%s' if use_postgres else '?'
    cur = db_exec_fn(conn,
        f"SELECT id FROM study_notes WHERE subject={ph} AND topic={ph} AND chapter_num={ph}",
        (_SUBJECT, _TOPIC, _CH))
    note = row_to_dict_fn(cur.fetchone())
    if not note:
        return
    note_id = note['id']

    existing = db_exec_fn(conn,
        f"SELECT COUNT(*) FROM chapter_mcqs WHERE study_note_id={ph}", (note_id,))
    if list(existing.fetchone())[0] > 0:
        return

    diff_map = {"easy": 1, "medium": 2, "hard": 3, "toughest": 4, 1: 1, 2: 2, 3: 3, 4: 4}

    for row in _MCQS:
        sec_idx  = row[0]
        diff_str = row[1]
        q_te     = row[2]
        opt_a    = row[3]
        opt_b    = row[4]
        opt_c    = row[5]
        opt_d    = row[6]
        correct  = row[7]
        expl     = row[8]
        exam_type = row[9] if len(row) > 9 else 'General'
        if not exam_type:
            exam_type = 'General'

        diff_int = diff_map.get(diff_str, 1)
        db_exec_fn(conn,
            f"""INSERT INTO chapter_mcqs
                (study_note_id, section_idx, difficulty, exam_type,
                 q_te, opt_a, opt_b, opt_c, opt_d, correct, explanation_te)
                VALUES ({ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph})""",
            (note_id, sec_idx, diff_int, exam_type,
             q_te, opt_a, opt_b, opt_c, opt_d, correct, expl))
