"""
seed_awards_mcq.py
80 GKToday-style MCQs — Topic: Awards & Honours (2025 to May 16, 2026)
Coverage: Nobel 2025, Grammys 67th+68th, Oscars 97th+98th, BAFTA 2026,
          Golden Globes 83rd, Booker 2025, Ballon d'Or 2025,
          Khel Ratna 2025, Padma 2026, Pulitzer 2025
IDs: 23001-23080  |  Force-refresh: DELETE then INSERT
"""

import os, sqlite3

DATABASE_URL = os.environ.get("DATABASE_URL", "")
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)
USE_POSTGRES = bool(DATABASE_URL)

AWARDS_MCQS = [
    # ── Nobel Prizes 2025 (23001-23012) ──
    {"id":23001,"question_text":"The Nobel Prize in Physics 2025 was awarded for which discovery foundational to quantum computing?","option_a":"Detection of gravitational waves using LIGO","option_b":"Macroscopic quantum mechanical tunnelling and energy quantisation in electric circuits","option_c":"Observation of the Higgs boson at CERN","option_d":"Development of attosecond pulses","correct_answer":"B","explanation":"Nobel Physics 2025: John Clarke, Michel H. Devoret, and John M. Martinis — for macroscopic quantum mechanical tunnelling and energy quantisation in electric circuits. This is the foundational work for superconducting qubit-based quantum computers. Martinis led Google's team that claimed quantum supremacy in 2019. Nobel Physics 2024: Hopfield & Hinton (AI/neural networks).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23002,"question_text":"Nobel Prize in Chemistry 2025 was awarded for the development of which ultra-porous crystalline materials?","option_a":"Graphene nanoribbons","option_b":"Metal-organic frameworks (MOFs)","option_c":"Zeolite catalysts","option_d":"Carbon nanotubes","correct_answer":"B","explanation":"Nobel Chemistry 2025: Susumu Kitagawa, Richard Robson, and Omar M. Yaghi — for developing metal-organic frameworks (MOFs). MOFs have the highest surface area per gram of any known material (~7,000 m²/g). Applications: CO2 capture, hydrogen storage, water harvesting from air, drug delivery. Omar Yaghi (UC Berkeley) coined 'reticular chemistry.'","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23003,"question_text":"Nobel Prize in Physiology/Medicine 2025 was awarded for the discovery of which immune cells that prevent autoimmune diseases?","option_a":"Natural killer (NK) cells","option_b":"Dendritic cells","option_c":"Regulatory T cells (Tregs)","option_d":"B lymphocytes","correct_answer":"C","explanation":"Nobel Medicine 2025: Mary E. Brunkow, Fred Ramsdell, and Shimon Sakaguchi — for discovering regulatory T cells (Tregs) and how they prevent autoimmune diseases. Tregs express the FOXP3 transcription factor. Mutations in FOXP3 cause IPEX syndrome. Nobel Medicine 2024: Ambros & Ruvkun (microRNA discovery).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23004,"question_text":"Which Hungarian author won the Nobel Prize in Literature 2025 for 'compelling and visionary oeuvre that reaffirms the power of art amid apocalyptic terror'?","option_a":"Péter Nádas","option_b":"Imre Kertész","option_c":"László Krasznahorkai","option_d":"György Konrád","correct_answer":"C","explanation":"Nobel Literature 2025: László Krasznahorkai (Hungary) — for his 'compelling and visionary oeuvre that, in the midst of apocalyptic terror, reaffirms the power of art.' His most famous novel 'Satantango' (1985) has 12 chapters mimicking tango steps (6 forward + 6 backward). Nobel Literature 2024: Han Kang (South Korea).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23005,"question_text":"The Nobel Peace Prize 2025 was awarded to Maria Corina Machado for her democratic struggle in which country?","option_a":"Cuba","option_b":"Nicaragua","option_c":"Bolivia","option_d":"Venezuela","correct_answer":"D","explanation":"Nobel Peace Prize 2025: Maria Corina Machado (Venezuela) — for 'tireless work promoting democratic rights for the people of Venezuela and her struggle to achieve a just and peaceful transition from dictatorship to democracy.' She leads Venezuela's opposition against President Nicolás Maduro. Nobel Peace Prize 2024: Nihon Hidankyo (Japanese atomic bomb survivors).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23006,"question_text":"Nobel Prize in Economic Sciences 2025 was awarded for research on innovation-driven growth and 'creative destruction.' Who were the laureates?","option_a":"Daron Acemoglu, Simon Johnson, James Robinson","option_b":"Claudia Goldin, Lawrence Katz, Lawrence Summers","option_c":"Joel Mokyr, Philippe Aghion, Peter Howitt","option_d":"Paul Romer, Robert Lucas, Robert Barro","correct_answer":"C","explanation":"Nobel Economics 2025: Joel Mokyr, Philippe Aghion, and Peter Howitt — for innovation-driven economic growth. Mokyr studied historical conditions for technological progress; Aghion & Howitt developed the 'creative destruction' theory (new innovations replace old ones, driving long-term growth). Nobel Economics 2024: Acemoglu, Johnson, Robinson (institutions & prosperity).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23007,"question_text":"Nobel Chemistry 2025 laureate Omar M. Yaghi is known as the father of which branch of chemistry?","option_a":"Green chemistry","option_b":"Reticular chemistry","option_c":"Electrochemistry","option_d":"Supramolecular chemistry","correct_answer":"B","explanation":"Omar M. Yaghi (UC Berkeley) coined 'reticular chemistry' — linking molecular building blocks into extended porous frameworks via strong bonds. His MOFs can hold 200× more hydrogen than steel cylinders at the same pressure. Nobel Chemistry 2025 shared with Susumu Kitagawa (Kyoto University) and Richard Robson (University of Melbourne).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23008,"question_text":"László Krasznahorkai's Nobel-winning novel 'Satantango' has a unique structure. What is distinctive about its 12 chapters?","option_a":"Written entirely in one sentence","option_b":"6 forward + 6 backward chapters mimicking tango steps","option_c":"12 chapters each told by a different character","option_d":"Alternates between past and future timelines","correct_answer":"B","explanation":"Krasznahorkai's 'Satantango' (1985) has 12 chapters: 6 forward + 6 backward — mirroring the Argentine tango's 6 steps forward and 6 back. Set in a decaying Hungarian collective farm after communism. Director Béla Tarr adapted it into a 7.5-hour film (1994). Krasznahorkai won Nobel Literature 2025.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23009,"question_text":"The Nobel Peace Prize is uniquely awarded in which city, unlike the other Nobel Prizes given in Stockholm?","option_a":"Brussels, Belgium","option_b":"Oslo, Norway","option_c":"Copenhagen, Denmark","option_d":"Helsinki, Finland","correct_answer":"B","explanation":"The Nobel Peace Prize is awarded by the Norwegian Nobel Committee in Oslo — the only Nobel Prize given in Norway. All other Nobel Prizes (Physics, Chemistry, Medicine, Literature, Economics) are awarded in Stockholm, Sweden. This reflects Alfred Nobel's 1895 will. Nobel Peace 2025: Maria Corina Machado (Venezuela). Nobel Peace 2024: Nihon Hidankyo.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23010,"question_text":"Nobel Physics 2025 laureate John M. Martinis led which tech company's team to claim 'quantum supremacy' in 2019?","option_a":"IBM","option_b":"Microsoft","option_c":"Google","option_d":"Intel","correct_answer":"C","explanation":"John M. Martinis led Google's quantum computing team whose Sycamore processor claimed 'quantum supremacy' in 2019 — performing a calculation in 200 seconds that classical computers would take ~10,000 years. His Nobel Physics 2025 win (with Clarke and Devoret) is for foundational quantum tunnelling and energy quantisation work — the basis of superconducting qubits used in modern quantum computers.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23011,"question_text":"Metal-organic frameworks (MOFs) — subject of Nobel Chemistry 2025 — are being tested for which crucial climate application?","option_a":"Ocean plastic degradation","option_b":"Nuclear waste disposal","option_c":"Carbon dioxide capture and storage","option_d":"Soil decontamination","correct_answer":"C","explanation":"MOFs (Nobel Chemistry 2025) are excellent for CO2 capture — their ultra-high surface area (up to 7,000 m²/g) can adsorb large amounts of CO2 from industrial flue gases and the atmosphere. This is critical for climate change mitigation. MOFs are also used for water harvesting from desert air, hydrogen storage for fuel cells, and targeted drug delivery.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23012,"question_text":"The 2025 Nobel Prize in Economic Sciences was the Sveriges Riksbank Prize. How does it differ from the original Nobel Prizes?","option_a":"It is awarded only to European economists","option_b":"It was established in 1968 in memory of Alfred Nobel, not part of original 1895 will","option_c":"It carries no monetary prize","option_d":"It is awarded every two years","correct_answer":"B","explanation":"The Nobel Prize in Economic Sciences (Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel) was established in 1968 by Sweden's central bank — NOT part of Alfred Nobel's original 1895 will. The original Nobel Prizes (Physics, Chemistry, Medicine/Physiology, Literature, Peace) were established by Nobel's will. The Economics Prize was first awarded in 1969 to Ragnar Frisch and Jan Tinbergen.","folder":"AP_HC","topic":"International_Current_Affairs"},

    # ── Grammys 67th — February 2025 (23013-23017) ──
    {"id":23013,"question_text":"Beyoncé won Album of the Year at the 67th Grammy Awards (February 2025) for which album — her first ever AOTY win?","option_a":"Renaissance","option_b":"Cowboy Carter","option_c":"Lemonade","option_d":"4","correct_answer":"B","explanation":"67th Grammy Awards (Feb 2, 2025, Crypto.com Arena, LA): Beyoncé won Album of the Year for 'Cowboy Carter' — a country-crossover album and her FIRST Grammy for Album of the Year despite record nominations. She also won Best Country Album and Best Country Duo/Group Performance. The ceremony was delayed one day due to devastating LA wildfires of January 2025.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23014,"question_text":"Kendrick Lamar won 5 out of 5 nominations at the 67th Grammys 2025, sweeping with which diss track targeting Drake?","option_a":"Euphoria","option_b":"Meet the Grahams","option_c":"Not Like Us","option_d":"6:16 in LA","correct_answer":"C","explanation":"67th Grammys (Feb 2025): Kendrick Lamar's 'Not Like Us' (diss targeting Drake) won ALL 5 nominations: Record of the Year, Song of the Year, Best Rap Song, Best Rap Performance, Best Music Video. Lamar also performed 'Not Like Us' at Super Bowl LIX halftime show (Feb 9, 2025) in New Orleans — with Serena Williams dancing in the audience.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23015,"question_text":"Who won Best New Artist at the 67th Grammy Awards 2025?","option_a":"Sabrina Carpenter","option_b":"Chappell Roan","option_c":"Gracie Abrams","option_d":"Teddy Swims","correct_answer":"B","explanation":"67th Grammys (Feb 2025): Best New Artist: Chappell Roan — breakthrough artist of 2024 known for 'Good Luck, Babe!' and album 'The Rise and Fall of a Midwest Princess.' She delivered a political speech about artist rights and mental health. Beyoncé won Album of Year (Cowboy Carter); Kendrick Lamar swept 5 awards for 'Not Like Us.'","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23016,"question_text":"Beyoncé's 'Cowboy Carter' at the 67th Grammys 2025 was notable as she became the first Black woman to win Grammy for Best Country Album. What record does she hold overall?","option_a":"First woman to win Record of Year 3 times","option_b":"Most Grammy wins by any artist (32 wins)","option_c":"Only artist to win all 4 General Field categories","option_d":"First artist to win Album of Year 4 times","correct_answer":"B","explanation":"Beyoncé holds the all-time record for most Grammy wins by any artist — 32 wins (as of 2025). She surpassed Georg Solti's previous record of 31. Her 'Cowboy Carter' Album of Year win was her FIRST in that category despite 9 previous nominations. The 67th Grammy Awards (Feb 2, 2025) were held at Crypto.com Arena in Los Angeles.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23017,"question_text":"Kendrick Lamar performed 'Not Like Us' at the Super Bowl LIX halftime show in February 2025. Where was Super Bowl LIX held?","option_a":"Las Vegas, Nevada","option_b":"New Orleans, Louisiana","option_c":"Los Angeles, California","option_d":"Miami, Florida","correct_answer":"B","explanation":"Super Bowl LIX (February 9, 2025) was held at Caesars Superdome in New Orleans, Louisiana — the Philadelphia Eagles beat the Kansas City Chiefs 40-22. Kendrick Lamar headlined the halftime show, performing 'Not Like Us' with Serena Williams dancing. The performance was widely praised as one of the greatest Super Bowl halftime shows ever.","folder":"AP_HC","topic":"International_Current_Affairs"},

    # ── Booker Prize 2025 & Pulitzer 2025 (23018-23022) ──
    {"id":23018,"question_text":"The Booker Prize 2025 was won by which novel, announced at a London ceremony on November 10, 2025?","option_a":"James by Percival Everett","option_b":"Flesh by David Szalay","option_c":"Orbital by Samantha Harvey","option_d":"The God of the Woods by Lauren Fox","correct_answer":"B","explanation":"Booker Prize 2025: 'Flesh' by David Szalay — British-Canadian author of Hungarian descent. The prize (£50,000) was announced November 10, 2025 in London, presented by 2024 Booker winner Samantha Harvey ('Orbital'). David Szalay was previously Booker-shortlisted for 'All That Man Is' (2016). 'Flesh' explores desire and mortality.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23019,"question_text":"International Booker Prize 2025 was won by 'A Cage Went in Search of a Bird' — an anthology inspired by which author's aphorisms?","option_a":"Leo Tolstoy","option_b":"Franz Kafka","option_c":"Albert Camus","option_d":"Marcel Proust","correct_answer":"B","explanation":"International Booker Prize 2025: 'A Cage Went in Search of a Bird' — 10 stories by 10 authors, each inspired by a different Franz Kafka aphorism. The title comes from Kafka's aphorism: 'A cage went in search of a bird.' The International Booker Prize is for translated fiction published in English in UK/Ireland; prize split between author and translator (£50,000 total).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23020,"question_text":"Pulitzer Prize 2025 for Fiction went to 'James' by Percival Everett — a retelling of which classic American novel from the perspective of an enslaved man?","option_a":"To Kill a Mockingbird","option_b":"Adventures of Huckleberry Finn","option_c":"Uncle Tom's Cabin","option_d":"Beloved","correct_answer":"B","explanation":"Pulitzer Prize 2025 Fiction: 'James' by Percival Everett — retells Mark Twain's 'Adventures of Huckleberry Finn' from Jim's (enslaved man's) perspective, reimagining Jim as educated and complex. The Pulitzer Prizes are administered by Columbia University, New York. Everett also won the PEN/Faulkner Award for the same novel. Pulitzer Fiction 2024: 'James' was announced May 2025.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23021,"question_text":"Who won the Pulitzer Prize 2025 for Poetry with 'What the Earth Seemed to Say: New & Selected Poems'?","option_a":"Louise Glück","option_b":"Ocean Vuong","option_c":"Marie Howe","option_d":"Tracy K. Smith","correct_answer":"C","explanation":"Pulitzer Prize 2025 for Poetry: Marie Howe — for 'What the Earth Seemed to Say: New & Selected Poems,' a retrospective collection. Howe is known for her elegy to her brother 'What the Living Do' and 'The Kingdom of Ordinary Time.' She is also Poet Laureate of New York State. Pulitzer Music 2025: Susie Ibarra for 'Sky Islands.'","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23022,"question_text":"Pulitzer Prize 2025 for Music was won by Filipino-American Susie Ibarra for 'Sky Islands.' She is primarily known as which type of musician?","option_a":"Classical violinist","option_b":"Jazz pianist","option_c":"Composer and percussionist","option_d":"Electronic music producer","correct_answer":"C","explanation":"Pulitzer Prize 2025 for Music: Susie Ibarra (Filipino-American composer and percussionist) for 'Sky Islands' — inspired by Philippine cloud forests and indigenous Tagalog music. Ibarra bridges contemporary classical, jazz, and Filipino indigenous traditions. Pulitzer Prizes are awarded annually in journalism, letters, drama, and music by Columbia University, New York.","folder":"AP_HC","topic":"International_Current_Affairs"},

    # ── Ballon d'Or 2025 & India Sports Awards (23023-23027) ──
    {"id":23023,"question_text":"Who won the Men's Ballon d'Or 2025 after his club won a historic quadruple?","option_a":"Vinicius Jr (Real Madrid)","option_b":"Erling Haaland (Man City)","option_c":"Ousmane Dembélé (PSG)","option_d":"Kylian Mbappé (Real Madrid)","correct_answer":"C","explanation":"Men's Ballon d'Or 2025: Ousmane Dembélé (France, PSG) — won for his sensational 2024-25 season helping PSG win a historic quadruple (Ligue 1, Coupe de France, Coupe de la Ligue, UEFA Champions League). Dembélé had 30+ goals + 20+ assists. Women's Ballon d'Or 2025: Aitana Bonmatí (third consecutive). Best Coach 2025: Sarina Wiegman (England women's coach).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23024,"question_text":"Aitana Bonmatí won Women's Ballon d'Or 2025. This was her how many consecutive wins?","option_a":"First","option_b":"Second consecutive","option_c":"Third consecutive","option_d":"Fourth consecutive","correct_answer":"C","explanation":"Aitana Bonmatí (Spain, FC Barcelona) won her THIRD consecutive Women's Ballon d'Or in 2025 (also won 2023 and 2024) — a hat-trick of wins. She is widely considered the world's best women's footballer, known for technical brilliance and creative playmaking. Spain won the Women's World Cup 2023 with Bonmatí as the standout performer.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23025,"question_text":"Major Dhyan Chand Khel Ratna Award 2025 was given to four athletes on January 17, 2025. Which was NOT among the winners?","option_a":"Gukesh D (Chess)","option_b":"Manu Bhaker (Shooting)","option_c":"Neeraj Chopra (Athletics)","option_d":"Harmanpreet Singh (Hockey)","correct_answer":"C","explanation":"Khel Ratna 2025 (awarded Jan 17, 2025 at Rashtrapati Bhavan by President Droupadi Murmu): Gukesh D (Chess – youngest World Chess Champion), Harmanpreet Singh (Hockey), Praveen Kumar (Para-Athletics), Manu Bhaker (Shooting – two Paris 2024 Olympic bronze medals). Neeraj Chopra had won Khel Ratna in 2021, not 2025.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23026,"question_text":"Manu Bhaker (Khel Ratna 2025) won two bronze medals at Paris Olympics 2024 — the first Indian to win two medals in a single Olympics since whom in 1900?","option_a":"Milkha Singh","option_b":"P.T. Usha","option_c":"Norman Pritchard","option_d":"K.D. Jadhav","correct_answer":"C","explanation":"Manu Bhaker won 2 bronze medals at Paris 2024 (10m air pistol individual + 10m air pistol mixed team with Sarabjot Singh) — first Indian to win 2 medals in a single Olympics since Norman Pritchard (1900 Paris Olympics, 2 silver medals in athletics). She received Khel Ratna 2025. Bhaker is coached by Jaspal Rana and is from Jhajjar, Haryana.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23027,"question_text":"Gukesh Dommaraju (Khel Ratna 2025) became the youngest World Chess Champion in December 2024 at what age, defeating Ding Liren?","option_a":"17","option_b":"18","option_c":"19","option_d":"20","correct_answer":"B","explanation":"D. Gukesh (India) became World Chess Champion in December 2024 at age 18 — defeating China's Ding Liren in Game 14 of the World Chess Championship in Singapore. He is the youngest World Chess Champion ever, breaking Garry Kasparov's record (22 in 1985). Gukesh received Khel Ratna 2025. He is from Chennai, Tamil Nadu and trained under Vishwanathan Anand's federation.","folder":"AP_HC","topic":"International_Current_Affairs"},

    # ── 83rd Golden Globe Awards — January 11, 2026 (23028-23032) ──
    {"id":23028,"question_text":"Which film won Best Motion Picture — Drama at the 83rd Golden Globe Awards (January 11, 2026)?","option_a":"Sinners","option_b":"One Battle After Another","option_c":"Hamnet","option_d":"I'm Still Here","correct_answer":"C","explanation":"83rd Golden Globe Awards (Jan 11, 2026, Beverly Hilton): Best Picture Drama: 'Hamnet' (adaptation of Maggie O'Farrell's novel about Shakespeare's son). Best Picture Comedy/Musical: 'One Battle After Another.' Best Director + Screenplay: Paul Thomas Anderson (One Battle). Best Actress Drama: Jessie Buckley (Hamnet). The Globes were hosted by Nikki Glaser (repeat hosting after 82nd Globes 2025).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23029,"question_text":"The 83rd Golden Globes 2026 introduced which brand-new category — won by 'Good Hang with Amy Poehler'?","option_a":"Best Streaming Series","option_b":"Best Podcast","option_c":"Best AI-Generated Film","option_d":"Best International Film","correct_answer":"B","explanation":"83rd Golden Globes (Jan 2026) introduced Best Podcast as a new category — won by 'Good Hang with Amy Poehler.' This reflects the explosive growth of celebrity-led podcasts. The Golden Globes are presented annually by the Hollywood Foreign Press Association (HFPA) at the Beverly Hilton Hotel, Beverly Hills, California.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23030,"question_text":"Paul Thomas Anderson won Best Director at the 83rd Golden Globes 2026 for 'One Battle After Another.' This film is an adaptation of which Thomas Pynchon novel?","option_a":"The Crying of Lot 49","option_b":"Vineland","option_c":"Gravity's Rainbow","option_d":"Mason & Dixon","correct_answer":"C","explanation":"'One Battle After Another' (PTA, 2026) is an adaptation of Thomas Pynchon's 'Gravity's Rainbow' (1973) — one of the most celebrated and difficult American novels. PTA previously adapted Pynchon's 'Inherent Vice' (2014). 'Gravity's Rainbow' won the National Book Award in 1974. The film went on to win Best Picture at the 98th Oscars (March 2026).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23031,"question_text":"Best Original Song at the 83rd Golden Globes 2026 was 'Golden' from which animated film that later also won the Oscar?","option_a":"Zootopia 2","option_b":"KPop Demon Hunters","option_c":"Avatar: Fire and Ash","option_d":"Moana 3","correct_answer":"B","explanation":"Best Original Song at 83rd Golden Globes (Jan 2026): 'Golden' from 'KPop Demon Hunters' (Sony Pictures Animation). The same film won Best Animated Feature AND Best Original Song at the 98th Oscars (March 2026). 'KPop Demon Hunters' swept the animated film awards season of 2026.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23032,"question_text":"At the 83rd Golden Globes 2026, who hosted the ceremony for the second consecutive year?","option_a":"Jo Koy","option_b":"Jerrod Carmichael","option_c":"Quinta Brunson","option_d":"Nikki Glaser","correct_answer":"D","explanation":"Nikki Glaser hosted the 83rd Golden Globes (Jan 2026) for the second consecutive year — she had successfully hosted the 82nd Golden Globes (Jan 2025) and was invited back. Her 2025 hosting was widely praised as one of the sharpest and funniest in years. She replaced Ricky Gervais, who hosted 5 times (2010-2020). Jo Koy's 2024 hosting was widely criticized.","folder":"AP_HC","topic":"International_Current_Affairs"},

    # ── 68th Grammy Awards — February 1, 2026 (23033-23040) ──
    {"id":23033,"question_text":"Which album won Album of the Year at the 68th Grammy Awards (February 1, 2026) — the first Spanish-language album to win the category?","option_a":"El Último Tour del Mundo — Bad Bunny","option_b":"Debí Tirar Más Fotos — Bad Bunny","option_c":"Un Verano Sin Ti — Bad Bunny","option_d":"Nadie Sabe Lo Que Va a Pasar — Bad Bunny","correct_answer":"B","explanation":"68th Grammy Awards (Feb 1, 2026): Album of the Year: Bad Bunny's 'Debí Tirar Más Fotos' — first Spanish-language album to win the Grammy's top honour, and Bad Bunny the third Latino artist to win AOTY. Released January 5, 2026, the album blends Puerto Rican salsa, reggaeton, and plena, celebrating Puerto Rican cultural identity. Title means 'I Should Have Taken More Photos.'","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23034,"question_text":"Kendrick Lamar won Record of the Year at the 68th Grammys 2026 for 'Luther' (feat. SZA). This made him the first rapper to win this award consecutively — how many consecutive wins?","option_a":"First time winning","option_b":"Second consecutive","option_c":"Third consecutive","option_d":"Fourth","correct_answer":"B","explanation":"68th Grammys (Feb 2026): Kendrick Lamar won Record of the Year for 'Luther' (feat. SZA) — his SECOND consecutive Record of the Year win (after 'Not Like Us' at 67th Grammys 2025). With 5 wins at the 68th ceremony, Lamar surpassed Jay-Z to become the most-awarded hip-hop artist in Grammy history (27+ Grammys total).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23035,"question_text":"'Wildflower' won Song of the Year at the 68th Grammys 2026. Who co-wrote and performed this Grammy winner?","option_a":"Taylor Swift and Jack Antonoff","option_b":"Billie Eilish and Finneas O'Connell","option_c":"Olivia Rodrigo and Dan Nigro","option_d":"SZA and Kendrick Lamar","correct_answer":"B","explanation":"68th Grammys (Feb 2026): Song of the Year: 'Wildflower' by Billie Eilish and brother Finneas O'Connell. This was their THIRD Song of the Year win each — previously 'No Time to Die' (64th Grammys 2022) and 'What Was I Made For?' (66th Grammys 2024). Both became the most-awarded artists in the Song of the Year category in Grammy history.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23036,"question_text":"Who won Best New Artist at the 68th Grammy Awards 2026, becoming the 9th consecutive woman to win and first British winner since Dua Lipa?","option_a":"Sabrina Carpenter","option_b":"Gracie Abrams","option_c":"Doechii","option_d":"Olivia Dean","correct_answer":"D","explanation":"68th Grammys (Feb 2026): Best New Artist: Olivia Dean (British singer-songwriter) — the 9th consecutive woman to win Best New Artist, and first British winner since Dua Lipa won in 2019. Olivia Dean is known for soul-influenced pop and the album 'Messy.' She is based in London and has been compared to Amy Winehouse for her vocal style.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23037,"question_text":"Bad Bunny (Album of Year at 68th Grammys 2026) is from which Puerto Rican city?","option_a":"San Juan","option_b":"Ponce","option_c":"Vega Baja","option_d":"Bayamón","correct_answer":"C","explanation":"Bad Bunny (Benito Antonio Martínez Ocasio) is from Vega Baja, Puerto Rico — born May 10, 1994. He studied audio-visual communication at the University of Puerto Rico. His 2026 Grammy Album of Year win for 'Debí Tirar Más Fotos' celebrated Puerto Rican cultural heritage — salsa, reggaeton, and plena rhythms. He is one of the most streamed artists on Spotify globally.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23038,"question_text":"At the 68th Grammys 2026, Kendrick Lamar surpassed Jay-Z as the most-awarded hip-hop artist. Approximately how many total Grammys does Lamar hold?","option_a":"15","option_b":"22","option_c":"27","option_d":"35","correct_answer":"C","explanation":"Kendrick Lamar with 5 wins at the 68th Grammys (Feb 2026) brought his total to approximately 27 Grammys, surpassing Jay-Z (21 Grammys). Lamar's 2026 wins: Record of Year (Luther), plus 4 others. His career Grammy wins include 67th (5 wins — Not Like Us), 59th (5 wins — DAMN.), and several earlier wins. He is from Compton, California.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23039,"question_text":"'Debí Tirar Más Fotos' (Grammy Album of Year 2026) was released by Bad Bunny on January 5, 2026. Which Puerto Rican music genre is central to this album?","option_a":"Merengue and cumbia","option_b":"Salsa, reggaeton, and plena","option_c":"Bachata and dembow","option_d":"Soca and calypso","correct_answer":"B","explanation":"Bad Bunny's 'Debí Tirar Más Fotos' (Grammy Album of Year, Feb 2026) is rooted in Puerto Rican salsa, reggaeton, and plena — traditional genres native to Puerto Rico. Plena is a percussion-driven Puerto Rican folk genre. The album title means 'I Should Have Taken More Photos' — a nostalgic tribute to Puerto Rican culture and memories. Released January 5, 2026, just weeks before winning the Grammy.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23040,"question_text":"The 68th Grammy Awards 2026 were held on which date and at which venue?","option_a":"January 15, 2026 — Madison Square Garden, New York","option_b":"February 1, 2026 — Crypto.com Arena, Los Angeles","option_c":"February 8, 2026 — Staples Center, Los Angeles","option_d":"March 2, 2026 — Radio City Music Hall, New York","correct_answer":"B","explanation":"68th Grammy Awards: February 1, 2026 at Crypto.com Arena, Los Angeles. The 67th Grammys (2025) were also at Crypto.com Arena. Bad Bunny won Album of Year; Kendrick Lamar won Record of Year (Luther) — 2nd consecutive; Billie Eilish won Song of Year (Wildflower) — 3rd win; Olivia Dean won Best New Artist; Bad Bunny = first Spanish-language Album of Year.","folder":"AP_HC","topic":"International_Current_Affairs"},

    # ── 79th BAFTA Film Awards — February 22, 2026 (23041-23047) ──
    {"id":23041,"question_text":"Which film won Best Film at the 79th BAFTA Film Awards (February 22, 2026) with a leading 6 wins?","option_a":"Sinners","option_b":"Hamnet","option_c":"One Battle After Another","option_d":"Sentimental Value","correct_answer":"C","explanation":"79th BAFTA Film Awards (Feb 22, 2026, Royal Festival Hall, London): Best Film: 'One Battle After Another' (Paul Thomas Anderson) — led the night with 6 wins including Best Film, Best Director (PTA), Best Adapted Screenplay (PTA), Best Supporting Actor (Sean Penn), Best Supporting Actress (Amy Madigan). Host: Alan Cumming. Broadcast on BBC One and iPlayer.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23042,"question_text":"Robert Aramayo won Leading Actor at BAFTA 2026. He beat Timothée Chalamet for the award. Aramayo is best known for playing which character in 'The Rings of Power'?","option_a":"Aragorn","option_b":"Elrond","option_c":"Gandalf","option_d":"Legolas","correct_answer":"B","explanation":"Robert Aramayo (British actor) plays Elrond (young version) in Amazon's 'The Rings of Power' (2022-). He also played young Ned Stark in 'Game of Thrones.' He won BAFTA Leading Actor 2026 for 'I Swear,' beating Timothée Chalamet (Sinners). Leading Actress: Jessie Buckley (Hamnet). Supporting Actor: Sean Penn (One Battle). Supporting Actress: Wunmi Mosaku (Sinners).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23043,"question_text":"Wunmi Mosaku won BAFTA Supporting Actress 2026 for which Ryan Coogler film that received a record 16 Oscar nominations?","option_a":"Hamnet","option_b":"Sinners","option_c":"One Battle After Another","option_d":"Weapons","correct_answer":"B","explanation":"79th BAFTA (Feb 2026): Best Supporting Actress: Wunmi Mosaku for 'Sinners' (Ryan Coogler). 'Sinners' received a record 16 Oscar nominations at the 98th Oscars (2026). Wunmi Mosaku is a Nigerian-British actress known for 'His House' (2020). Michael B. Jordan starred in 'Sinners' and won Best Actor at the 98th Oscars. 'Sinners' won 4 Oscars from 16 nominations.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23044,"question_text":"'Hamnet' won Outstanding British Film at BAFTA 2026. The film is based on whose 2020 novel?","option_a":"Hilary Mantel","option_b":"Ian McEwan","option_c":"Maggie O'Farrell","option_d":"Zadie Smith","correct_answer":"C","explanation":"'Hamnet' (2026) is based on Maggie O'Farrell's acclaimed 2020 novel, reimagining the life of Agnes Hathaway (Shakespeare's wife) and the death of their 11-year-old son Hamnet in 1596. Jessie Buckley plays Agnes. The film won Outstanding British Film at BAFTA, Best Actress Drama at Golden Globes 2026, and Best Actress at Oscars 98th (2026) — all for Buckley.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23045,"question_text":"'Sentimental Value' won Film Not in the English Language at BAFTA 2026. This Norwegian film was directed by whom?","option_a":"Ruben Östlund","option_b":"Joachim Trier","option_c":"Thomas Vinterberg","option_d":"Roy Andersson","correct_answer":"B","explanation":"'Sentimental Value' — Norwegian film directed by Joachim Trier — won Film Not in the English Language at BAFTA 79th (Feb 2026). Trier's previous film 'The Worst Person in the World' (2021) won Best Actress at Cannes (Renate Reinsve). Trier is known for his Oslo trilogy. 'Sentimental Value' also starred Renate Reinsve. Joachim Trier is a Norwegian-Danish director.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23046,"question_text":"The 79th BAFTA Film Awards 2026 were held at which iconic London venue?","option_a":"Royal Albert Hall","option_b":"The O2 Arena","option_c":"Royal Festival Hall","option_d":"Barbican Centre","correct_answer":"C","explanation":"79th BAFTA Film Awards (Feb 22, 2026) were held at the Royal Festival Hall on London's South Bank — hosted by Alan Cumming and broadcast on BBC One and iPlayer. BAFTA = British Academy of Film and Television Arts, founded 1947. 'One Battle After Another' won 6 BAFTAs; 'Sinners' won 3 BAFTAs; 'Hamnet' won Outstanding British Film. Sean Penn won Supporting Actor.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23047,"question_text":"Sean Penn won BAFTA Supporting Actor 2026 and Oscar Supporting Actor 2026. How many total Oscars does Penn now hold?","option_a":"One","option_b":"Two","option_c":"Three","option_d":"Four","correct_answer":"C","explanation":"Sean Penn's Oscar Supporting Actor win at the 98th Oscars (2026) for 'One Battle After Another' is his THIRD Oscar: Best Actor for 'Mystic River' (2003) + Best Actor for 'Milk' (2008) + Best Supporting Actor for 'One Battle After Another' (2026). He also won BAFTA Supporting Actor 2026 for the same role. Penn is one of the most-awarded actors of his generation.","folder":"AP_HC","topic":"International_Current_Affairs"},

    # ── 98th Academy Awards — March 2026 (23048-23062) ──
    {"id":23048,"question_text":"Which film won Best Picture at the 98th Academy Awards (March 2026) with 6 Oscars total including the inaugural Casting award?","option_a":"Sinners","option_b":"Hamnet","option_c":"One Battle After Another","option_d":"Sentimental Value","correct_answer":"C","explanation":"98th Academy Awards (March 2026): Best Picture: 'One Battle After Another' (Paul Thomas Anderson) — 6 wins: Best Picture, Director, Adapted Screenplay, Supporting Actor (Sean Penn), Supporting Actress (Amy Madigan), and inaugural Best Casting. 'Sinners' had 16 nominations (record) and won 4; 'Frankenstein' won 3 craft awards; 'KPop Demon Hunters' won 2.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23049,"question_text":"Michael B. Jordan won Best Actor at the 98th Oscars 2026 for which film, in which he played twin brothers?","option_a":"One Battle After Another","option_b":"Sinners","option_c":"Creed IV","option_d":"Just Mercy 2","correct_answer":"B","explanation":"98th Oscars (March 2026): Best Actor: Michael B. Jordan for 'Sinners' (Ryan Coogler) — in which Jordan plays twin brothers. 'Sinners' received 16 Oscar nominations (record) and won 4: Best Actor (Jordan), Best Original Screenplay (Ryan Coogler), Best Cinematography, and Best Film Editing. Jordan is known for 'Black Panther' (Erik Killmonger) and the 'Creed' franchise.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23050,"question_text":"Jessie Buckley won Best Actress at the 98th Oscars 2026 for 'Hamnet.' She completed a sweep at all major awards — this is called what?","option_a":"Triple Crown","option_b":"Grand Slam","option_c":"Awards Sweep","option_d":"Clean Slate","correct_answer":"B","explanation":"Jessie Buckley's Best Actress Oscar (98th, 2026) for 'Hamnet' completed the Grand Slam — winning at all major film awards: SAG Awards + Golden Globes 83rd (Jan 2026) + BAFTA 79th (Feb 2026) + Academy Awards 98th (March 2026). A Grand Slam in acting is extremely rare. Buckley is a British-Irish actress from Killarney, Kerry, Ireland.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23051,"question_text":"Amy Madigan won Best Supporting Actress at the 98th Oscars 2026 for which film?","option_a":"Sinners","option_b":"Hamnet","option_c":"One Battle After Another","option_d":"Weapons","correct_answer":"D","explanation":"98th Oscars (March 2026): Best Supporting Actress: Amy Madigan for 'Weapons' (directed by Gabriel Abrantes). Amy Madigan is a veteran American actress known for 'Field of Dreams' (1989) and 'Roe v. Wade' (2021). Her co-winner on the same night: Sean Penn (Supporting Actor, One Battle). 'Weapons' and 'One Battle' swept the supporting categories.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23052,"question_text":"Ryan Coogler won Best Original Screenplay at the 98th Oscars 2026 for 'Sinners.' His previous directorial debut starred Michael B. Jordan in which film?","option_a":"Black Panther","option_b":"Creed","option_c":"Fruitvale Station","option_d":"Just Mercy","correct_answer":"C","explanation":"Ryan Coogler's directorial debut was 'Fruitvale Station' (2013) — starring Michael B. Jordan as Oscar Grant, a young Black man killed by police in Oakland, CA. Coogler then directed 'Creed' (2015), 'Black Panther' (2018), 'Black Panther: Wakanda Forever' (2022), and 'Sinners' (2026, 16 Oscar nominations, Best Original Screenplay win).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23053,"question_text":"The 98th Oscars 2026 introduced Best Achievement in Casting as a new category. Who won it?","option_a":"Sinners","option_b":"Hamnet","option_c":"One Battle After Another","option_d":"Frankenstein","correct_answer":"C","explanation":"Best Achievement in Casting — new category at 98th Oscars (2026) — won by 'One Battle After Another' in its inaugural year, bringing the film's total to 6 Oscars. The Academy had been considering a Casting category for years. The casting director of 'One Battle After Another' thus became the first-ever Oscar winner in this new category.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23054,"question_text":"'KPop Demon Hunters' won Best Animated Feature at the 98th Oscars 2026. Which studio produced it, known for 'Spider-Verse'?","option_a":"Pixar/Disney","option_b":"DreamWorks","option_c":"Sony Pictures Animation","option_d":"Illumination","correct_answer":"C","explanation":"'KPop Demon Hunters' (Sony Pictures Animation) won Best Animated Feature + Best Original Song ('Golden') at the 98th Oscars (2026). Sony Pictures Animation is known for the Spider-Man: Into the Spider-Verse (2018) and Across the Spider-Verse (2023) — both Oscar-winning animated films. The same song 'Golden' also won Best Original Song at the 83rd Golden Globes (Jan 2026).","folder":"AP_HC","topic":"International_Current_affairs"},
    {"id":23055,"question_text":"'Sinners' (16 Oscar nominations, 98th Oscars 2026) broke the record for most nominations. Which two films previously shared the record with 14 nominations?","option_a":"Titanic (1997) and All About Eve (1950)","option_b":"La La Land (2016) and The Favourite (2018)","option_c":"Schindler's List (1993) and Shakespeare in Love (1998)","option_d":"Avatar (2009) and The Lord of the Rings (2003)","correct_answer":"A","explanation":"'Sinners' (Ryan Coogler, 2026) received 16 Oscar nominations — breaking the previous record of 14 nominations shared by 'Titanic' (James Cameron, 1997; won 11) and 'All About Eve' (Joseph L. Mankiewicz, 1950; won 6). 'La La Land' also had 14 nominations in 2016 (won 6). 'Sinners' won 4 Oscars from its record 16 nominations.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23056,"question_text":"'One Battle After Another' (Best Picture, 98th Oscars 2026) is Paul Thomas Anderson's adaptation of which novelist's work?","option_a":"Don DeLillo","option_b":"Cormac McCarthy","option_c":"Thomas Pynchon","option_d":"David Foster Wallace","correct_answer":"C","explanation":"'One Battle After Another' is PTA's adaptation of Thomas Pynchon's 'Gravity's Rainbow' (1973) — among the most celebrated and challenging American novels. Pynchon is famously reclusive (no known photos since the 1950s). PTA previously adapted Pynchon's 'Inherent Vice' (2014). 'Gravity's Rainbow' won the National Book Award (1974) but was rejected for the Pulitzer.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23057,"question_text":"'Avatar: Fire and Ash' won Best Visual Effects at the 98th Oscars 2026. This is which entry in the Avatar franchise?","option_a":"Second (Avatar 2)","option_b":"Third (Avatar 3)","option_c":"Fourth (Avatar 4)","option_d":"First prequel","correct_answer":"B","explanation":"'Avatar: Fire and Ash' (James Cameron) is the third Avatar film — following 'Avatar' (2009, won VFX Oscar) and 'Avatar: The Way of Water' (2022, won VFX Oscar). The Avatar franchise has won the VFX Oscar three consecutive times. 'Avatar' (2009) remains the highest-grossing film of all time globally (~$2.9 billion). 'Fire and Ash' explores new biomes of Pandora including fire environments.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23058,"question_text":"'Frankenstein' won 3 Oscars at the 98th ceremony (2026) in which craft categories?","option_a":"Best VFX, Best Sound, Best Score","option_b":"Best Costume Design, Best Makeup & Hairstyling, Best Production Design","option_c":"Best Cinematography, Best Editing, Best Score","option_d":"Best VFX, Best Costume Design, Best Film Editing","correct_answer":"B","explanation":"'Frankenstein' won 3 craft Oscars at the 98th Academy Awards (2026): Best Costume Design + Best Makeup and Hairstyling + Best Production Design. These three craft categories typically reward period/monster films with elaborate visual design. 'Avatar: Fire and Ash' won Best Visual Effects; 'Sinners' won Best Cinematography and Best Film Editing.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23059,"question_text":"The 97th Oscars (March 2025) Best Picture was 'Anora' — directed by Sean Baker. Which actress won Best Actress for this film?","option_a":"Demi Moore","option_b":"Fernanda Torres","option_c":"Mikey Madison","option_d":"Cynthia Erivo","correct_answer":"C","explanation":"97th Oscars (March 2025): Best Picture: 'Anora' (Sean Baker) + Best Actress: Mikey Madison (as Anora, a New York sex worker who marries a Russian oligarch's son). 'Anora' swept 5 Oscars including Picture, Director (Baker), Actress (Madison), and Original Screenplay (Baker). Mikey Madison is also known for 'Scream' (2022) and 'Scream VI' (2023) as villain Amber Freeman.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23060,"question_text":"Adrien Brody won Best Actor at the 97th Oscars 2025 for which film, his second Best Actor Oscar?","option_a":"The Zone of Interest","option_b":"The Brutalist","option_c":"A Complete Unknown","option_d":"Emilia Pérez","correct_answer":"B","explanation":"97th Oscars (March 2025): Best Actor: Adrien Brody for 'The Brutalist' (Brady Corbet) — playing a Hungarian-Jewish architect who flees to America after WWII. This was Brody's SECOND Best Actor Oscar (first was for 'The Pianist' in 2002 — making him the youngest Best Actor winner at 29). 'The Brutalist' is a 3.5-hour epic. Brody also won BAFTA and Golden Globe for the same role.","folder":"AP_HC","topic":"International_Current_Affairs"},

    # ── Padma Awards 2026 (23061-23066) ──
    {"id":23061,"question_text":"Padma Awards 2026 announced on January 25, 2026 — how many total awards including the Padma Vibhushan, Bhushan and Shri?","option_a":"112","option_b":"119","option_c":"131","option_d":"144","correct_answer":"C","explanation":"Padma Awards 2026: Total 131 awards (including 2 duo cases): 5 Padma Vibhushan + 13 Padma Bhushan + 113 Padma Shri. Announced on January 25, 2026 (Republic Day eve). Padma Awards are India's highest civilian honours — Bharat Ratna > Padma Vibhushan > Padma Bhushan > Padma Shri — conferred by the President at Rashtrapati Bhavan.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23062,"question_text":"Which legendary Bollywood actor received Padma Vibhushan (posthumously) in Padma Awards 2026?","option_a":"Rishi Kapoor","option_b":"Dharmendra Singh Deol","option_c":"Dilip Kumar","option_d":"Rajesh Khanna","correct_answer":"B","explanation":"Padma Vibhushan 2026 (posthumous): Dharmendra Singh Deol — legendary 'He-Man of Bollywood' with a career spanning 6+ decades. Known for 'Sholay' (1975), 'Phool Aur Patthar' (1966), 'Satyakam' (1969). Also VS Achuthanandan (former Kerala CM, CPI-M leader, died 2025) received Padma Vibhushan posthumously. Vijay Amritraj (tennis) received Padma Bhushan.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23063,"question_text":"Vijay Amritraj received Padma Bhushan 2026. He is a legendary Indian sportsperson in which field?","option_a":"Cricket","option_b":"Badminton","option_c":"Tennis","option_d":"Squash","correct_answer":"C","explanation":"Vijay Amritraj received Padma Bhushan 2026 — legendary Indian tennis player who was ranked as high as world No. 18 in the 1970s-80s. He represented India in Davis Cup for over two decades. He also appeared in James Bond film 'Octopussy' (1983). Padma Bhushan is India's third highest civilian honour. Rohit Sharma, Harmanpreet Kaur, and Savita Punia (hockey) received Padma Shri 2026.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23064,"question_text":"VS Achuthanandan, who received Padma Vibhushan 2026 posthumously, served as Chief Minister of which Indian state?","option_a":"Tamil Nadu","option_b":"Karnataka","option_c":"Kerala","option_d":"Andhra Pradesh","correct_answer":"C","explanation":"VS Achuthanandan (VS) — former Chief Minister of Kerala (2006-2011), veteran CPI(M) leader — received Padma Vibhushan posthumously in 2026. Born 1923, died 2025 at age ~101. He was known for anti-corruption stand and simplicity. He served the Indian Left movement for over 70 years and was instrumental in Kerala's land reforms during his CM tenure.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23065,"question_text":"Cricket captain Rohit Sharma received which Padma Award in 2026?","option_a":"Padma Vibhushan","option_b":"Padma Bhushan","option_c":"Padma Shri","option_d":"Bharat Ratna","correct_answer":"C","explanation":"Rohit Sharma (India Test and ODI captain) received Padma Shri 2026 — India's fourth highest civilian honour. Also receiving Padma Shri 2026: Harmanpreet Kaur (India women's cricket captain) and Savita Punia (India women's hockey goalkeeper). Vijay Amritraj received Padma Bhushan. Dharmendra and VS Achuthanandan received Padma Vibhushan (posthumous).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23066,"question_text":"The Bharat Ratna 2025 was conferred on which two personalities — one being a posthumous award for India's greatest industrialist?","option_a":"MS Dhoni and Amitabh Bachchan","option_b":"Narayana Murthy and Ratan Tata (posthumous)","option_c":"Subramanian Swamy and M. Karunanidhi (posthumous)","option_d":"Lata Mangeshkar (posthumous) and Sachin Tendulkar","correct_answer":"B","explanation":"Bharat Ratna 2025: Narayana Murthy (Infosys co-founder, father of India's IT industry) and Ratan Tata (posthumous — died October 2024, Tata Group visionary who modernized Indian industry globally). Bharat Ratna is India's highest civilian honour, given to maximum 3 per year. Previous 2024 batch included LK Advani, Karpoori Thakur, PV Narasimha Rao, MS Swaminathan, Charan Singh.","folder":"AP_HC","topic":"International_Current_Affairs"},

    # ── Other Notable 2025-2026 Awards (23067-23080) ──
    {"id":23067,"question_text":"The Abel Prize 2025 (mathematics' equivalent of Nobel) was awarded to which Japanese mathematician for D-module theory?","option_a":"Masaki Izumi","option_b":"Masaki Kashiwara","option_c":"Shigeru Mochizuki","option_d":"Hideo Kojima","correct_answer":"B","explanation":"Abel Prize 2025: Masaki Kashiwara (Japan, Research Institute for Mathematical Sciences, Kyoto) — for D-module theory and the Riemann-Hilbert correspondence. Kashiwara became the first Japanese mathematician to win the Abel Prize. The Abel Prize is awarded by the Norwegian Academy of Science and Letters with NOK 7.5 million (~$700,000). Abel Prize 2024: Michel Talagrand (France, probability theory).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23068,"question_text":"The Pritzker Architecture Prize 2025 — architecture's highest honour — was awarded to which Chinese architect?","option_a":"Ma Yansong","option_b":"Wang Shu","option_c":"Liu Jiakun","option_d":"Zhu Pei","correct_answer":"C","explanation":"Pritzker Architecture Prize 2025: Liu Jiakun (China) — first Chinese national to win since Wang Shu in 2012. Known for community-centred architecture balancing tradition and modernity, including post-earthquake reconstruction work in Sichuan after the 2008 earthquake. The Pritzker Prize is awarded by the Hyatt Foundation with $100,000 prize — called 'architecture's Nobel Prize.'","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23069,"question_text":"India's Dadasaheb Phalke Award 2025 — Bollywood's highest honour — was awarded to which legendary actress?","option_a":"Hema Malini","option_b":"Rekha","option_c":"Jaya Bachchan","option_d":"Waheeda Rehman","correct_answer":"B","explanation":"Dadasaheb Phalke Award 2025: Rekha (Bhanurekha Ganesan) — legendary Bollywood actress known for 'Umrao Jaan' (1981), 'Silsila' (1981), 'Khubsoorat' (1980). The Dadasaheb Phalke Award is India's highest film honour, given at the National Film Awards. Previous winners: Asha Parekh (2024), Waheeda Rehman (2023). Dadasaheb Phalke is the father of Indian cinema.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23070,"question_text":"The Ramon Magsaysay Award — often called 'Asia's Nobel Prize' — is presented by which country?","option_a":"Japan","option_b":"South Korea","option_c":"Philippines","option_d":"Thailand","correct_answer":"C","explanation":"The Ramon Magsaysay Award is presented in Manila, Philippines — named after Philippine President Ramon Magsaysay (1907-1957, died in plane crash). Awarded annually to Asians for outstanding contributions in government, public service, community leadership, journalism, literature/creative arts, and peace/international understanding. Prize: $50,000. HQ: Ramon Magsaysay Award Foundation, Manila.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23071,"question_text":"The Turing Award 2025 (ACM A.M. Turing Award — computing's highest honour, $1 million prize) was awarded for groundbreaking work in which field?","option_a":"Invention of the internet","option_b":"Pioneering computer graphics and rendering algorithms","option_c":"Development of neural networks","option_d":"Creating the C programming language","correct_answer":"B","explanation":"ACM Turing Award 2025: Awarded for pioneering work on computer graphics and rendering algorithms — foundational work enabling modern CGI in films, games, and visual computing. The Turing Award is given annually by the Association for Computing Machinery (ACM) with $1 million prize (sponsored by Google). Named after Alan Turing. Turing Award 2024: Andrew Barto and Richard Sutton (reinforcement learning foundations).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23072,"question_text":"The FIFA Best Men's Player Award 2025 was won by the same player as the Ballon d'Or 2025. Who was it?","option_a":"Erling Haaland","option_b":"Vinicius Jr","option_c":"Ousmane Dembélé","option_d":"Kylian Mbappé","correct_answer":"C","explanation":"FIFA Best Men's Player 2025: Ousmane Dembélé (PSG) — consistent with his Ballon d'Or 2025 win after PSG's historic quadruple. FIFA Best Women's Player 2025: Aitana Bonmatí (FC Barcelona, third consecutive). FIFA Best Coach 2025: Luis Enrique (PSG, who managed PSG to the quadruple). FIFA Best Goalkeeper 2025: Gianluigi Donnarumma (PSG). FIFA Best Awards ceremony: January 2026.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23073,"question_text":"The Sakharov Prize 2025 (European Parliament's human rights prize) was awarded to defenders of which country's 'Woman, Life, Freedom' movement?","option_a":"Russia","option_b":"Iran","option_c":"Myanmar","option_d":"Afghanistan","correct_answer":"B","explanation":"Sakharov Prize 2025 (European Parliament): Awarded to Iranian women human rights defenders of the 'Woman, Life, Freedom' (Zan, Zendegi, Azadi) movement — sparked by Mahsa Amini's death in police custody in September 2022. The Sakharov Prize for Freedom of Thought has been awarded annually since 1988 with €50,000 prize. Named after Soviet physicist/dissident Andrei Sakharov.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23074,"question_text":"The Booker Prize 2025 winner David Szalay was previously shortlisted for which earlier novel?","option_a":"Spring","option_b":"London and the South-East","option_c":"All That Man Is","option_d":"The Innocent","correct_answer":"C","explanation":"David Szalay was Booker Prize shortlisted for 'All That Man Is' (2016) — a novel of 9 interconnected stories about European men at different life stages. In 2025, he won the Booker Prize for 'Flesh.' Szalay is a British-Canadian author of Hungarian descent, born in Montreal, raised in London. He writes in English about European themes and characters.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23075,"question_text":"Percival Everett, who won Pulitzer Prize 2025 for Fiction ('James'), is also a professor at which US university?","option_a":"Yale University","option_b":"University of Southern California (USC)","option_c":"Columbia University","option_d":"Howard University","correct_answer":"B","explanation":"Percival Everett is Distinguished Professor of English at the University of Southern California (USC). His Pulitzer-winning 'James' (2024) retells 'Adventures of Huckleberry Finn' from enslaved Jim's perspective. Everett is prolific — over 30 books across genres. 'James' also won the PEN/Faulkner Award, the Carnegie Medal for Excellence in Fiction, and the Kirkus Prize.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23076,"question_text":"Maria Corina Machado (Nobel Peace 2025) leads which Venezuelan political party/movement?","option_a":"Democratic Action (AD)","option_b":"Vente Venezuela","option_c":"Popular Will (Voluntad Popular)","option_d":"Justice First (Primero Justicia)","correct_answer":"B","explanation":"Maria Corina Machado leads 'Vente Venezuela' (Come Venezuela) — a Venezuelan political party she founded in 2012. She was barred from holding public office by the Maduro government despite winning the 2024 opposition primary. Nobel Peace Prize 2025 recognized her fight for democracy in Venezuela against Nicolás Maduro's autocratic rule. Venezuela's crisis has caused over 7 million refugees.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23077,"question_text":"The Golden Globe for Best Original Song went to 'Golden' from 'KPop Demon Hunters' at the 83rd Globes (Jan 2026). This song later also won the Oscar. Who performed it?","option_a":"BTS","option_b":"BLACKPINK","option_c":"The film's fictional K-pop group performed by real K-pop artists","option_d":"NCT Dream","correct_answer":"C","explanation":"'Golden' from 'KPop Demon Hunters' (2026) won both Best Original Song at the 83rd Golden Globes (Jan 2026) and the 98th Oscars (March 2026). The animated film features a fictional K-pop group whose music was created with real K-pop producers and artists. Sony Pictures Animation's 'KPop Demon Hunters' also won Best Animated Feature at the 98th Oscars, sweeping the animated/music awards of 2026.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23078,"question_text":"The 2025 Ballon d'Or Best Coach Award went to which England Women's national team coach?","option_a":"Pep Guardiola","option_b":"Carlo Ancelotti","option_c":"Sarina Wiegman","option_d":"Luis Enrique","correct_answer":"C","explanation":"Ballon d'Or 2025 Best Coach: Sarina Wiegman (Netherlands) — England Women's national team head coach. Wiegman led England to the 2022 UEFA Women's Euro title (Lionesses' first major trophy) and the 2023 Women's World Cup final. She has an unbeaten record in competitive matches as England head coach. FIFA Best Women's Coach 2025 also went to Wiegman.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23079,"question_text":"The Indira Gandhi Peace Prize 2025 was awarded to which organization for global health contributions?","option_a":"WHO (World Health Organization)","option_b":"UNICEF","option_c":"Médecins Sans Frontières (MSF/Doctors Without Borders)","option_d":"GAVI, the Vaccine Alliance","correct_answer":"D","explanation":"Indira Gandhi Peace Prize 2025: GAVI, the Vaccine Alliance — for global health contributions, particularly vaccinating over 1 billion children in low-income countries and playing a key role in the COVID-19 COVAX facility. The Indira Gandhi Prize for Peace, Disarmament and Development is awarded by the Indira Gandhi Memorial Trust, New Delhi. Previous winners: WHO (2022), Manmohan Singh (2024).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":23080,"question_text":"The Academy Awards ceremony for the 98th Oscars (March 2026) — where 'One Battle After Another' won Best Picture — was held at which venue?","option_a":"Dolby Theatre, Hollywood","option_b":"Kodak Theatre, Hollywood","option_c":"The Shrine Auditorium, Los Angeles","option_d":"TCL Chinese Theatre, Hollywood","correct_answer":"A","explanation":"The Oscars (Academy Awards) ceremony has been held at the Dolby Theatre in Hollywood, Los Angeles since 2002 — formerly called the Kodak Theatre (renamed Dolby Theatre in 2012). The 98th Oscars (March 2026) continued this tradition at Dolby Theatre. Host of the 98th Oscars: Conan O'Brien (marking his return to major hosting). The Academy of Motion Picture Arts and Sciences (AMPAS) presents the Oscars.","folder":"AP_HC","topic":"International_Current_Affairs"},
]


def seed():
    if USE_POSTGRES:
        import psycopg2
        conn = psycopg2.connect(DATABASE_URL)
        conn.autocommit = False
        cur = conn.cursor()
        delete_sql = "DELETE FROM questions WHERE id >= %s AND id <= %s"
        insert_sql = """INSERT INTO questions
            (id, question_text, option_a, option_b, option_c, option_d,
             correct_answer, explanation, topic, folder, difficulty)
            VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
            ON CONFLICT (id) DO NOTHING"""
    else:
        conn = sqlite3.connect(
            os.path.join(os.path.dirname(__file__), "database.db")
        )
        cur = conn.cursor()
        delete_sql = "DELETE FROM questions WHERE id >= ? AND id <= ?"
        insert_sql = """INSERT OR IGNORE INTO questions
            (id, question_text, option_a, option_b, option_c, option_d,
             correct_answer, explanation, topic, folder, difficulty)
            VALUES (?,?,?,?,?,?,?,?,?,?,?)"""

    cur.execute(delete_sql, (23001, 23080))

    for q in AWARDS_MCQS:
        cur.execute(insert_sql, (
            q["id"], q["question_text"],
            q["option_a"], q["option_b"], q["option_c"], q["option_d"],
            q["correct_answer"], q["explanation"],
            q["topic"], q["folder"], "M"
        ))

    conn.commit()
    conn.close()
    print(f"[seed_awards_mcq] {len(AWARDS_MCQS)} Awards 2025-2026 MCQs seeded (IDs 23001-23080).")


if __name__ == "__main__":
    seed()
