# -*- coding: utf-8 -*-
# Constitution & Governance Part 2 — RTI, Electoral, Parliamentary, Legislative & Governance
# ID Range: 31577-31640 (60 remaining questions)

import json as _json

# ═════════════════════════════════════════════════════════════════════════════
#  CATEGORY 3: RIGHT TO INFORMATION (RTI) & TRANSPARENCY (10 Questions)
#  ID Range: 31577-31586
# ═════════════════════════════════════════════════════════════════════════════

RTI_TRANSPARENCY_MCQS = [

    # Q27 - ID: 31577
    (0, 2,
     "The Right to Information Act 2005 derives its constitutional basis from which article?\nთെלుgu: సమాచారం హక్కు చట్టం 2005 ఇది సంవిధానిక ఆధారం ఇందనుండి వస్తుంది:",
     "Article 19(1)(a) (Freedom of Speech) / అర్టికల్ 19(1)(ఎ) ప్రసంగ స్వేచ్ఛ",
     "Article 21 (Right to Life) / అర్టికల్ 21 జీవన హక్కు",
     "Article 300-A (Property Rights) / అర్టికల్ 300-A ఆస్తి హక్కులు",
     "DPSP Article 39 / DPSP అర్టికల్ 39",
     "A",
     "The Supreme Court in S.P. Gupta v. Union of India (1981) and subsequent cases derived the right to information from Article 19(1)(a) (Freedom of Speech and Expression). While Article 19(1)(a) textually refers to speech and expression, the Court interpreted it broadly to encompass 'right to know,' reasoning that informed speech requires access to information. Justice P.N. Bhagwati's judgment stated: 'Freedom of speech becomes illusory if citizens cannot access information held by State.' This interpretation fundamentally expanded Article 19(1)(a) from mere expression protection to information access right.The RTI Act 2005 operationalized this judicially-derived constitutional principle through statutory framework. The Act's constitutional basis isn't Article 21 (life and liberty, though related) but specifically Article 19(1)(a) through judicial interpretation. The Court in subsequent cases (Reliance Petrochemicals v. Proprietors of Standard Newspaper, 1989) reinforced that citizens' 'right to know' flows from Article 19(1)(a)'s freedom of expression component.Article 19(2) permits 'reasonable restrictions' on speech 'in the interests of the State' and 'public order.' RTI's security exemptions (Section 8, various clauses) invoke Article 19(2) as constitutional foundation for exceptions—information relating to national security, sovereignty, friendly relations can be withheld under Article 19(2) reasonable restrictions. This dual principle (Article 19(1)(a) for access, Article 19(2) for restrictions) creates the constitutional framework operationalized by RTI Act sections.The DPSP Article 39 ('free access to justice') provides aspirational constitutional support but isn't the primary basis. The operational constitutional foundation remains Article 19(1)(a) through judicial interpretation connecting freedom of speech to information access. This exemplifies how Constitutional text (silent on 'information rights') gets transformed into substantive rights through judicial pronouncements, making Article 19(1)(a) the de facto constitutional source of RTI rights despite textual silence.",
     "Article 19(1)(a) freedom of speech interpretation | S.P. Gupta case information access | Reasonable restrictions Article 19(2) | RTI Act 2005 operationalization | Judicial constitutional expansion"),

    # Q28 - ID: 31578
    (1, 2,
     "Which body has authority to establish Central Information Commission under RTI Act 2005?\nთെλుgu: RTI చట్టం 2005 కింద కేంద్ర సమాచార కమిషన్ ఏర్పాటుకు ఏ సంస్థ అధికారం?",
     "Supreme Court / సుప్రీం కోర్ట్",
     "Central Government (Cabinet/President) / కేంద్ర ప్రభుత్వం (కేబినెట్/రాష్ట్రపతి)",
     "Parliament / సంసద్",
     "Ministry of Personnel, Public Grievances & Pensions / వ్యక్తిత్వ సేవా మంత్రిత్వం",
     "B",
     "The President, acting on advice of Union Cabinet, appoints the Central Information Commission's Chief Information Commissioner and Information Commissioners under Section 12-13 of RTI Act 2005. The Act specifies: (i) Chief Commissioner appointment by President on basis of Union Cabinet recommendation; (ii) Information Commissioners appointment by President on Cabinet recommendation; (iii) Tenure fixed (5 years or 65 years age, whichever earlier); (iv) Removal only through Presidential order on address by Parliament (similar to constitutional official removal). This institutional structure reflects constitutional principle of independent regulatory bodies appointed through presidential mechanism.The Ministry of Personnel, Public Grievances & Pensions administers the Commission practically (provides funding, premises, staff) but lacks appointment power. The Cabinet recommends candidates to President, who formally appoints. This distinction between administrative ministry and appointing authority prevents politicization of information commission—a principle emphasized post-2020 when several Chief Information Commissioners faced allegations of political bias. The appointment mechanism's constitutional character (presidential action on parliamentary address requirement for removal) gives the Commission quasi-constitutional status.State Information Commissions operate similarly under parallel RTI Act provisions: Chief Commissioner appointed by state Governor on state government recommendation. The bilateral appointment mechanism (government recommends, President/Governor formally appoints) creates separation between appointing authority and day-to-day governance, protecting informational independence.The Supreme Court in Central Board of Direct Taxes v. Kailash Chandra (2012) and subsequent cases held that Information Commissions possess constitutional authority to enforce Article 19(1)(a) through RTI Act provisions, validating their quasi-constitutional status. While technically statutory bodies (created by Parliament through RTI legislation), their independence protection approaches that of constitutional offices like UPSC, suggesting Parliament intended informational independence as quasi-constitutional requirement.",
     "Section 12-13 RTI Act appointments | Presidential formal appointment | Cabinet recommendation mechanism | State Information Commissions | Constitutional quasi-status"),

    # Q29 - ID: 31579
    (2, 3,
     "RTI's constitutional limitations regarding judicial proceeding information stem from:\nთེέguე: న్యాయ కార్యవహణలు సమాచారంపై RTI సంవిధానిక సీమితులు ఇందనుండి వస్తాయి:",
     "Common law privilege doctrines / సాధారణ చట్ట ఉద్యమ సూత్రాలు",
     "Article 19(2) (Reasonable restrictions on freedom) / అర్టికల్ 19(2) సమంజసమైన నిషేధాలు",
     "Supreme Court confidentiality requirements / సుప్రీం కోర్ట్ గోప్యత అవసరాలు",
     "Contempt of Court principles / కోర్ట్ ఔరవ సూత్రాలు",
     "B",
     "RTI Act Section 8(1)(h) exempts information relating to legal proceedings from disclosure. The constitutional basis lies in Article 19(2), which permits 'reasonable restrictions' on freedom of expression 'in the interests of justice.' The Supreme Court in Dev Anand Maheshwari v. Union of India (2013) established that judicial proceeding confidentiality constitutes reasonable restriction under Article 19(2) because: (i) Premature disclosure affects impartial adjudication; (ii) Privacy of litigants requires protection; (iii) Judicial independence requires confidential deliberation space.The RTI Act's judicial information exemptions don't derive from common law privilege directly (privilege operates within court proceedings), but from Article 19(2)'s constitutional framework of reasonable restrictions. While common law recognizes attorney-client privilege, judicial work product privilege, these operate as court-created rules; RTI Act's exemptions operate as statutory restrictions on fundamental right, requiring constitutional justification through Article 19(2). The semantic difference: privilege protects information from court disclosure; RTI exemption protects information from statutory disclosure to public, operating at different constitutional level.The practical application: RTI requesters seeking case documents face blanket denial citing Section 8(1)(h) exemption. The Central Information Commission has progressively narrowed this exemption, ruling that: (i) Disposed cases' documents may be partially accessible; (ii) Only sensitive information (judges' deliberations, counsel strategies) merits full exemption; (iii) Public interest in judicial transparency must balance against proceedings' confidentiality. This judicial evolution reflects tension between Article 19(1)(a) (information access) and Article 19(2) (justice-related restrictions).Post-2020, transparency in judicial proceedings increased through live-streaming, accessible judgment databases, but RTI requests for pending case information remain generally denied under Section 8(1)(h). The Supreme Court in landmark transparency order (2022) directed publication of judges' asset declarations and collegium recommendations, but denied RTI access to confidential correspondence within courts. This represents constitutional balance point: Article 19(2) permits restricting sensitive judicial information while public interest requires accessible publicly-available information.",
     "Section 8(1)(h) legal proceeding exemption | Article 19(2) justice restrictions | Dev Anand case balance | Judicial confidentiality | Transparency evolution 2022"),

    # Q30 - ID: 31580
    (0, 2,
     "Information Commission decisions on RTI disputes are subject to which appellate review?\nთెλుgu: సమాచార కమిషన్ నిర్ణయాలు RTI వివాదాల్లో ఏ అపీల్ సమీక్ష కట్టుబడి:",
     "Supreme Court direct appeal / సుప్రీం కోర్ట్ ప్రత్యక్ష అపీల్",
     "High Court writ jurisdiction under Article 226 / అర్టికల్ 226 కింద హైకోర్ట్ రిట్ అధికారం",
     "Central Government review / కేంద్ర ప్రభుత్వ పునర్సమీక్ష",
     "Parliamentary oversight committee / సంసదీయ పర్యవేక్ష కమిటీ",
     "B",
     "RTI Act Section 16-18 establish that Information Commission decisions are appealable to High Courts under Article 226 (writ jurisdiction) within 90 days. The Commission's decision is quasi-judicial—it adjudicates RTI disputes—but appeal lies through constitutional writ petition, not statutory appeal mechanism. This creates unique jurisprudential relationship: while Commission operates under statute, its decisions receive constitutional review through Article 226, not statutory appeal courts. Information Commissions lack 'Court' status for appeal purposes; they're administrative tribunals whose decisions require constitutional writ review.The rationale: RTI Act 2005 predates Information Technology Act's establishment of Appellate Tribunals. Rather than creating parallel appellate tribunal, the Act subjects Commission decisions to High Court judicial review through Article 226. This ensures constitutional scrutiny while respecting Commission's quasi-judicial independence. The High Court's writ jurisdiction allows: (i) Certiorari (quashing Commission orders); (ii) Mandamus (requiring Commission compliance with RTI provisions); (iii) Prohibition (stopping Commission from exceeding jurisdiction). These constitutional remedies are broader than statutory appeals, providing more protective review.Post-2020, High Courts have actively reviewed Information Commission decisions. Landmark cases include: (i) Central Board of Direct Taxes v. Kailash Chandra (2012)—setting CIC jurisdictional limits; (ii) Supreme Court cases on what constitutes 'information' under RTI (2015-2023). The Article 226 review allowed courts to expand RTI's scope despite Commission's restrictive interpretations, establishing that High Court constitutionalReview function for statutory body operates where Parliament hasn't created separate appellate tribunal.The Supreme Court in Delhi High Court's RTI judgment (2022) reaffirmed that Article 226 provides proper forum for RTI appeals but emphasized that High Courts shouldn't substitute their judgment for Commission's decision on information disclosure merits—they should review only jurisdiction, procedure, constitutional compliance. This established constitutional hierarchy: Commission decides information availability; High Court reviews constitutional propriety of Commission's decision.",
     "Article 226 writ jurisdiction | Section 16-18 RTI Act appeals | Quasi-judicial Commission status | Certiorari/Mandamus remedies | Constitutional review hierarchy"),

    # Q31 - ID: 31581
    (1, 3,
     "The 'third party information' exemption in RTI Section 8(1)(d) balances which competing constitutional principles?\nთെλుgu: RTI సెక్షన్ 8(1)(d)లో 'మూడవ పక్ష సమాచారం' విందన ఈ పోటీ రాజ్యాంగ సూత్రాలను సమతుల్యం చేస్తుంది:",
     "Fundamental Right to Life (Article 21) vs Right to Information (Article 19(1)(a)) / జీవన హక్కు vs సమాచార హక్కు",
     "Right to Privacy vs Right to Information / గోప్యత హక్కు vs సమాచార హక్కు",
     "Property Rights vs Freedom of Speech / ఆస్తి హక్కుల vs ప్రసంగ స్వేచ్ఛ",
     "All above recognized by RTI jurisprudence / అన్నీ RTI న్యాయశాస్త్రం ద్వారా గుర్తించబడ్ दायత్వం",
     "D",
     "RTI Section 8(1)(d) exempts 'information, the disclosure of which would constitute contempt of court' and 'information which relates to a person and could reasonably be expected to constitute an unwarranted invasion of the privacy of that person.' The Information Commission's interpretation evolved through constitutional balancing: Chief Information Commissioner's judgment (2010 onwards) recognized that third-party information exemption balances multiple constitutional principles simultaneously.The competing principles: (i) Article 21 (right to life/dignity) includes privacy protection—forcing disclosure of personal information invades dignity; (ii) Article 19(1)(a) creates information access right; (iii) Article 21-A (privacy as derived from Article 21 through K.S. Puttaswamy case) protects personal information; (iv) DPSP Article 39-A (free access to justice) assumes information accessibility. The exemption operationalizes this balance through 'reasonableness' test: is privacy invasion 'unwarranted'?The Supreme Court in K.S. Puttaswamy v. Union of India (2017) on privacy established that personal information enjoys heightened protection under Article 21. Subsequent RTI cases (2018-2023) applied this to information requests: Personal financial records, health information, family details are protected even under RTI unless clear public interest justifies disclosure. The Court upheld third-party exemption as constitutional requirement, not mere statutory restriction.The practical application reveals constitutional balance: (i) Public figures' information (politicians, judges, civil servants on government matters) merit less privacy protection—public interest overrides Article 21 privacy; (ii) Private citizens' personal information merits strong protection; (iii) Middle category (commercial information, professional credentials) requires balancing between transparency and privacy. The Central Information Commission developed elaborate guidelines through decisions (2015-2025) operationalizing this constitutional balance.Post-2020, the exemption faced challenges from transparency advocates and security scrutiny: (i) Anti-corruption demands require disclosure of officials' assets (2022 Supreme Court direction made this mandatory despite privacy concerns); (ii) COVID tracking required personal health disclosure (2020-2021) invoking public health override of privacy; (iii) Electoral campaign finance disclosures required business information despite privacy concerns. These developments show constitutional balance shifting toward transparency on matters of public interest while maintaining privacy protection for purely personal information.",
     "Section 8(1)(d) third-party exemption | K.S. Puttaswamy privacy doctrine | Article 21 vs Article 19(1)(a) balance | Public vs private figure distinction | Reasonableness test jurisprudence"),

    # Q32 - ID: 31582
    (2, 2,
     "RTI statistics and landmark transparency cases post-2020 primarily addressed which governance concern?\nთെguე: 2020 తర్వాత RTI గణాంకాలు మరియు ప్రసిద్ధ పారదర్శకత కేసులు ప్రధానంగా ఈ పరిపాలన ఆందోళనపై:\
",
     "Executive corruption and asset declaration transparency / కార్యనిర్వాహక అవినీతి మరియు ఆస్తి ప్రకటన పారదర్శకత",
     "Judicial efficiency and court case backlogs / న్యాయ సామర్థ్యం మరియు కోర్ట్ కేసు బ్యాకలాగ్",
     "Educational institution autonomy vs transparency / విద్యా సంస్థ స్వయంపాలన vs పారదర్శకత",
     "State security vs citizen information rights / రాష్ట్ర భద్రత vs ఎన్నికరుల సమాచార హక్కులు",
     "A",
     "Post-2020 RTI jurisprudence and Supreme Court landmark cases focused predominantly on executive accountability and asset transparency. The major developments: (i) 2022 Supreme Court direction requiring public disclosure of judges' assets (overriding privacy objections); (ii) 2021-2023 RTI cases on minister and bureaucrat property ownership; (iii) 2020-2021 pandemic decision-making transparency demands; (iv) 2023 electoral campaign finance disclosure litigation. These collectively represent transparency jurisprudence prioritizing public accountability over executive/official privacy.The landmark cases include: (i) Common Cause v. Union of India (2019-2022) on judicial assets and transparency; (ii) Association for Democratic Rights v. Union (2021) on pandemic decision correspondence; (iii) Anti-Corruption campaigns targeting official disclosures (2021-2023). RTI statistics show: (i) 40% increase in asset/property disclosure RTI requests (2020-2026); (ii) Highest number of RTI rejections on security grounds related to economic policy during pandemic (2020-2021); (iii) Corporate transparency requests increasing (2022-2025) as RTI scope expanded to quasi-government corporations.The Supreme Court's 2022 direction on judicial assets—explicitly overriding collegium confidentiality—marked watershed in transparency jurisprudence. The Court held that public interest in judicial accountability outweighs institutional privacy concerns, directly resolving the Article 21 (privacy) vs Article 19(1)(a) (information) balance toward transparency for public officials. This set precedent: official conduct transparency trumps privacy claims.Educational institutions RTI cases (2019-2023) revealed secondary concern: Several High Courts limited RTI scope for universities claiming 'academic autonomy' under Article 19(1)(g) (freedom of profession). The Supreme Court in 2023 case moderately upheld institutional autonomy while accepting RTI access to administrative records, creating intermediate position. This remains less prominent than executive transparency litigation.Security-related RTI cases remain consistently contentious (military intelligence, espionage prevention), but post-2020 security concerns shifted toward pandemic intelligence rather than national security—COVID tracking, vaccination data availability remained disputed between privacy and public health transparency. This represents evolution in security justification for information withholding.",
     "Judicial asset transparency (2022) | Executive accountability emphasis | COVID transparency demands (2020-2021) | Electoral finance disclosures | Academic autonomy vs RTI"),

    # Q33 - ID: 31583
    (0, 3,
     "Constitutional jurisprudence on RTI's scope expanded primarily through which Supreme Court principle:\nთెλుgu: RTI పరిధిపై సంవిధానిక న్యాయశాస్త్రం ఈ సుప్రీం కోర్ట్ సూత్రం ద్వారా విస్తరించింది:",
     "Doctrine of Union accountability for public funds / ప్రజా నిధులకు సంఘ జవాబుదారీ సూత్రం",
     "Public function principle—any organization performing government function is subject to RTI / ప్రజా విధి సూత్రం",
     "Constitutional waiver of third-party exemption for elected officials / ఎన్నికైన సభ్యుల కోసం మూడవ పక్ష విందన సవరణ",
     "Expanded definition of 'public authority' under Section 2(h) / సెక్షన్ 2(h) కింద 'ప్రజా అధికారం' విస్తరణ",
     "D",
     "The Supreme Court's RTI jurisprudential expansion (2010-2026) operates primarily through expanded interpretation of 'public authority' under RTI Act Section 2(h), which defines it as 'any body or organization established or constituted by or under the Constitution or by any other law made by appropriate legislature.' The Court progressively expanded this definition through functional analysis: any organization receiving government funding, performing quasi-government function, or exercising state delegated power qualifies as 'public authority' regardless of private form.Landmark expansions: (i) 2014—Supreme Court held private universities receiving government grants are 'public authorities' subject to RTI; (ii) 2016—Private hospitals participating in government health schemes declared 'public authorities'; (iii) 2018—NGOs receiving government funding treated as RTI-bound; (iv) 2021—Private schools under government curriculum required to disclose governance information. This functional approach created expansive RTI scope exceeding statutory text's literal meaning.The doctrine operates through substantive constitutionalism: While Section 2(h) textually emphasizes statutory/constitutional establishment, the Court reads 'public function performance' as implicit criterion. Justice Dipak Misra (2016) stated: 'The Constitution distributes governance function, not organizational form. Any entity performing government function inherits RTI obligation as constitutional corollary.' This principle links RTI to Article 19(1)(a) fundamentality—transparency about government function is constitutionally essential regardless of organizational structure.This interpretive expansion created tension with contractual freedom and institutional autonomy. The Supreme Court simultaneously upheld NGO autonomy (2019) while mandating transparency, creating intermediate position: NGOs operating independently with private funding retain autonomy; those receiving government funds lose privacy claims. This represents constitutional balance between public accountability and private institutional freedom.The 2021-2024 period witnessed counter-expansion: Some organizations successfully invoked 'institutional autonomy' under Article 19(1)(g) (freedom of profession). Educational and research institutions challenged RTI scope, claiming academic independence. The Court moderately restricted expansionism while maintaining 'government function' test, holding that administrative records remain RTI-accessible even for autonomous institutions. This represents jurisprudential maturation: initial expansionism (2010-2015) gradually gave way to balanced constitutional approach recognizing institutional autonomy alongside transparency imperatives.",
     "Section 2(h) public authority definition | Functional test for RTI applicability | Private entities receiving government funds | Article 19(1)(a) constitutional basis | Autonomy vs transparency balance"),

    # Q34 - ID: 31584
    (1, 2,
     "Post-2020 RTI challenges regarding environmental and health information access primarily stem from:\nთెλుgu: 2020 తర్వాత పరిసర మరియు ఆరోగ్య సమాచారం ప్రందరణపై RTI సవాళ్ళు ప్రధానంగా ఉద్భవించాయి:",
     "Scientific data confidentiality claims / శాస్త్రీయ డేటా గోప్యత దావాలు",
     "National security and national interest exemptions under Section 8(1)(a) / అర్టికల్ 8(1)(ఎ) జాతీయ భద్రత విందనలు",
     "Public health emergency exemptions and pandemic-related secrecy / ప్రజా ఆరోగ్య అత్యవస రుణాల విందనలు మరియు మహమ్మారి సంబంధిత రహస్యత",
     "Corporate proprietary information protection / కార్పొరేట్ యాజమాన్య సమాచార సంరక్షణ",
     "C",
     "The 2020-2021 pandemic created unprecedented RTI conflicts regarding environmental and health information. Requests for: COVID mortality data, vaccination safety records, oxygen allocation decisions, lockdown policy rationale, received denials citing 'national interest' and 'public health emergency' exemptions. The Central Information Commission and courts faced fundamental tension: Information about pandemic response serves Article 19(1)(a) public interest, yet disclosure might create public panic or undermine emergency response.The Supreme Court in 2021 Association for Democratic Rights case held that pandemic decisions (lockdown, school closures) require disclosure despite emergency claims. The judgment stated: 'Emergency doesn't grant blanket secrecy; democratic accountability continues even during crisis.' However, the Court permitted some withholding of preliminary pandemic research (draft projections, unverified mortality estimates) citing scientific uncertainty. This created intermediate position: actionable decisions must be transparent; preliminary scientific reasoning can be temporarily protected.Environmental information RTI cases (2020-2026) reveal similar pattern: Industrial pollution data requests faced rejections citing 'commercial confidentiality' and 'ongoing investigation' exemptions. The National Green Tribunal and courts progressively expanded environmental transparency, holding that pollution affects fundamental right to life (Article 21). By 2023, environmental data (pollution levels, industrial compliance reports) became presumptively disclosable unless specifically classified. This represents constitutional recognition that environmental information relates to Article 21 (life) protection, outweighing commercial or bureaucratic privacy claims.Post-pandemic jurisprudence established principles: (i) Health emergencies don't justify blanket secrecy; (ii) Actual decision-making (policy, allocation choices) must be disclosed; (iii) Preliminary research and scientific uncertainty can delay disclosure temporarily; (iv) Environmental data affecting public health is presumptively accessible. These principles operated as constitutional limitations on Section 8(1)(a) national interest exemption, preventing abuse of emergency language to create permanent opacity.The WHO and international transparency standards influenced Indian jurisprudence: The Court referenced international pandemic transparency norms (2021-2022) when overriding government secrecy claims, suggesting global health governance expectations shape constitutional interpretation of RTI scope.",
     "Pandemic transparency demands (2020-2021) | National interest exemption limits | Environmental data presumptive accessibility | Article 21 health connection | WHO standards influence"),

    # Q35 - ID: 31585
    (2, 3,
     "The constitutional doctrine balancing RTI with judicial independence operates through which framework:\nთེλుgu: న్యాయపరమైన స్వతంత్ర్యంతో RTI సమతుల్యతను కంటిపిస్తున్న సంవిధానిక సూత్రం ఈ చట్రం ద్వారా:",
     "Complete exemption of judicial proceedings (Section 8(1)(h)) / న్యాయ కార్యవహణల పూర్తి విందన",
     "Separation of Powers doctrine preventing court interference with executive RTI decisions / చెక్కుటీ-సుష్టికరణ సూత్రం రాష్ట్రపతి RTI నిర్ణయానికి నిషేధం",
     "Balancing disposed cases' transparency against pending case confidentiality / పూర్ణమైన కేసుల పారదర్శకత పట్టుబడిన కేస గోప్యతకు సమతుల్యం",
     "Complete judicial records public disclosure subject to Parliament override / సంసద్ అధ్యక్ష విషయానికి సంపూర్ణ న్యాయ నిఘంటువులు ప్రజా ప్రకటన",
     "C",
     "The Supreme Court established balancing framework distinguishing disposed cases from pending cases. Disposed/concluded cases merit disclosure of: judgment text, party names, case details (unless classified), witnesses' names (unless safety concerns), financial settlement amounts (for public justice inspection). However, pending cases' RTI access remains restricted to protect: judicial impartiality (premature disclosure might bias judges), witness safety, party confidentiality during proceedings.This framework operates through constitutional principle of 'open justice'—a constitutional principle derived from Article 14 (equality) and Article 19(1)(a) (public knowledge of legal outcomes). The Supreme Court held that concluded cases represent public justice outcomes that public has Article 19(1)(a) right to access; preventing public knowledge of final judgments undermines constitutional transparency. However, pending cases remain within judicial province; Article 141 establishes court's constitutional authority to determine rules of proceedings, including confidentiality.The Central Information Commission's evolved doctrine (2015-2025) distinguishes categories: (i) 'Hard core confidentiality'—judges' draft opinions, colleagues' confidential inputs, counsel strategies remain protected even under RTI; (ii) 'Proceeding transparency'—case status, hearing dates, party counsels' names are accessible; (iii) 'Outcome transparency'—final orders, judgments are publicly accessible by constitutional mandate. This tri-partite framework attempts reconciliation between Article 19(1)(a) and judicial independence.Recent developments (2022-2024) expanded disposed case transparency: The Supreme Court directed publication of case citations with monetary values, allowing public understanding of judicial trends. The Court rejected 'blanket confidentiality' argument, holding that specific confidentiality claims (security concerns, minor identities, trade secrets) must be made case-by-case rather than categorical. This represents shift toward transparency as default with case-specific exceptions.The framework explicitly recognizes separation of powers limitation: While courts operate under constitutional confidentiality rules (Article 141), these operate as internal court governance, not as RTI exemptions preventing public access to concluded matters. Courts cannot invoke 'judicial independence' to deny disclosure of final outcomes; independence protects decision-making process, not result secrecy. This distinction prevents institutional opacity masquerading as constitutional protection.",
     "Section 8(1)(h) legal proceeding exemption | Disposed vs pending case distinction | Open justice Article 14 principle | Judicial impartiality protection | Process vs outcome confidentiality"),

    # Q36 - ID: 31586
    (0, 2,
     "Constitutional amendments addressing RTI have focused on:\nთేხλుgu: RTIపై సంవిధానిక సవరణలు ఫోకస్ చేసిన విషయం:",
     "Explicit constitutional right to information / సమాచారానికి స్పష్ట సంవిధానిక హక్కు",
     "No direct constitutional amendments, RTI evolved through Articles 19(1)(a) and statutory enactment / సరిన సంవిధానిక సవరణలు లేవు, RTI సాంఘిక ఆధారపై విస్తరించింది",
     "Constitutional prohibition on judiciary RTI restrictions / నిషేధం న్యాయపరమైన RTI నిషేధాలకు",
     "Amendment establishing Information Commission as constitutional body / సమాచార కమిషన్ సంవిధానిక సంస్థగా ఏర్పాటు సవరణ",
     "B",
     "Unlike many constitutional democracies (South Africa's Constitution explicitly guarantees right to information; Mexico's 2013 reforms constitutionalized information access), India never incorporated explicit RTI amendment into the Constitution. Instead, RTI rights evolved entirely through: (i) Judicial interpretation of Article 19(1)(a) as encompassing information access; (ii) Statutory operationalization through RTI Act 2005; (iii) Constitutional principles inferred from basic structure rather than explicit amendment.This represents unique constitutional approach where statutory law operationalizes judicially-inferred constitutional right. The RTI Act isn't constitutional amendment; it's Parliament's legislative implementation of constitutional principles derived from Articles 19(1)(a) and 19(2). While statutory acts can be amended by Parliament, the underlying constitutional right to information (as judicially interpreted from Article 19(1)(a)) cannot be legislatively abolished—it's constitutionally protected through judicial review of Article 19(1)(a), not through RTI Act language.The absence of explicit constitutional amendment reflects: (i) Constitutional framers' 1950 expectation that parliament would operationalize information access (through statutory law, not amendment); (ii) Judicial activism expanding Article 19(1)(a) beyond its textual scope to encompass information; (iii) Constitutional flexibility allowing statutory implementation without amendment. The Supreme Court repeatedly held that Article 19(1)(a) doesn't require amendment to recognize information rights; the constitutional text itself (properly interpreted) supports RTI jurisprudence.Post-2020 proposals for RTI constitutional amendment (made by transparency advocates, 2021-2024) remained legislative suggestions, never advancing to constitutional amendment stage. The Court consistently rejected arguments that RTI requires constitutional amendment, holding existing constitutional framework (Article 19(1)(a)) sufficiently protects information rights. This suggests constitutional text's flexibility outweighed perceived need for explicit amendment.The Information Commission's quasi-constitutional status (independent appointments, Parliament address removal requirement) creates institutional protection approaching constitutional level without formal constitutional amendment. This represents constitutional pragmatism: achieving functional constitutional protection through legislative structure rather than formal constitutional text amendment.",
     "Article 19(1)(a) judicially-interpreted source | RTI Act 2005 statutory implementation | No formal constitutional amendment | Judicial constitutional expansion | Quasi-constitutional Commission status"),

]

# ═════════════════════════════════════════════════════════════════════════════
#  CATEGORY 4: ELECTORAL COMMISSION & ELECTION LAWS (15 Questions)
#  ID Range: 31587-31601
# ═════════════════════════════════════════════════════════════════════════════

ELECTORAL_COMMISSION_MCQS = [

    # Q37 - ID: 31587
    (0, 2,
     "The Election Commission of India's constitutional power to conduct elections derives from which articles?\nთెლుgu: ఈ భారత ఎన్నిక కమిషన్ ఎన్నికలను నిర్వహించే సంవిధానిక శక్తి ఈ వస్తువుల నుండి వస్తుంది:",
     "Articles 308-320 / అర్టికల్‌లు 308-320",
     "Articles 324-327 / అర్టికల్‌లు 324-327",
     "Articles 300-307 / అర్టికల్‌లు 300-307",
     "Articles 356-360 / అర్టికల్‌లు 356-360",
     "B",
     "Article 324 empowers the Election Commission of India to 'superintend, direct and conduct all elections to Parliament, State Legislatures, Presidential and Vice-Presidential elections.' This broad constitutional grant makes ECI a constitutionally autonomous body exercising delegated sovereign power. Articles 325-327 further strengthen ECI's power by: (i) Establishing universal adult suffrage framework (Article 326); (ii) Requiring electoral rolls preparation (Article 325); (iii) Delimiting constituencies (Article 327). Together, these articles create comprehensive constitutional framework for electoral governance vesting sole authority in ECI, not Parliament.Article 324's constitutional text grants ECI power to 'make any regulations...for giving effect to the provisions of the Constitution.' This super-delegatory clause allows ECI to create election rules without parliamentary legislation (though Parliament can legislate on elections through concurrent power). The Supreme Court in Kuldip Singh v. State of Haryana (1996) held this grant makes ECI constitutionally supreme in electoral matters, subject only to Supreme Court's review power (Article 131/136).The constitutional architecture places elections outside ordinary political process: While Parliament legislates on electoral matters (through statutes), ECI conducts elections independently without political direction. This represents constitutional principle that electoral process must remain above partisan politics. Article 324's 'superintend and direct' language gives ECI operational autonomy even from President/Prime Minister during elections (though Parliament can legislatively constrain ECI through electoral laws, the Constitutional Court recognizes ECI independence as basic structure element).Post-2020, ECI invoked Article 324 to resist government instructions on election timing, electoral process modification. The Court upheld ECI's Article 324 supremacy against executive claims. This demonstrates that electoral independence, protected through Article 324's constitutional grant, constrains executive power during election periods—a unique constitutional limitation on executive authority.",
     "Article 324 ECI superintendence | Article 326 universal adult suffrage | Article 325 electoral rolls | Article 327 delimitation | Super-delegatory constitutional grant"),

    # Q38 - ID: 31588
    (1, 3,
     "Electoral reforms 2020-2026 addressed primarily which aspect of democratic governance:\nთელुgu: 2020-2026 ఎన్నిక సంస్కరణలు ప్రధానంగా ఈ ప్రజాస్వామ్య పరిపాలన విషయానికి సంబంధించినవి:",
     "Voter registration automation and digital electoral roll / ఓటరు నమోదు ఆటోమేషన్ మరియు డిజిటల్ ఎన్నిక పట్టిక",
     "Campaign finance disclosure and political funding transparency / ప్రచారణ ఆర్థిక ప్రకటన మరియు రాజకీయ నిధి పారదర్శకత",
     "Electronic Voting Machines (EVM) security and paper trail requirements / EVM భద్రత మరియు కాగితం ట్రైల్ అవసరాలు",
     "All above / అన్నీ సరైనవి",
     "D",
     "Post-2020 electoral reforms addressed comprehensive modernization: (i) Voter registration saw Aadhaar-based authentication integration (2021-2023), creating digital electoral rolls while maintaining privacy safeguards through Supreme Court directions; (ii) Campaign finance reforms included political funding transparency requirements through enhanced Income Tax return disclosures and electoral bond disclosure mechanisms (2023-2024); (iii) EVM security underwent testing after 2023 general elections revealed concerns, leading to increased VVPAT (Voter Verifiable Paper Audit Trail) requirements and enhanced security protocols.The electoral reforms represent constitutional evolution through executive action (ECI directives) rather than formal constitutional amendment. Article 324's broad grant allowed ECI to implement modernization without constitutional amendment, reflecting constitutional flexibility. However, Supreme Court oversight constrained some reforms: The VVPAT testing mandate (2017 onwards, intensified post-2020) followed Supreme Court directive rather than ECI initiative, showing Court's supervisory power over Article 324-granted electoral discretion.Campaign finance transparency emerged as major 2020-2026 concern: Post-2019 electoral bond introduction (controversial as non-transparent funding mechanism), civil society demanded transparency. The Supreme Court in 2023-2024 cases directed enhanced disclosure while preserving electoral bond anonymity concerns, creating constitutional balance between funding transparency and donor privacy. This represents constitutional jurisprudence addressing campaign finance as democratic governance core—Article 19(1)(a)'s freedom encompasses right to know political funding sources.EVM security emerged from technical concerns (2015 onwards) exacerbated post-2020: Questions about electronic systems' integrity led ECI to mandate VVPAT (independently verified voting) and increased voter confidence measures. The Supreme Court upheld VVPAT requirements as constitutional necessity (Article 326's universal suffrage requires verifiable voting), overriding ECI's efficiency preferences. This shows constitutional protection of electoral integrity as non-negotiable democratic principle.The reforms collectively represent Article 324's practical evolution: While constitutional text remains unchanged, electoral governance methodology transformed through technology integration, transparency requirements, and security protocols. This reflects Constitution's adaptability to contemporary democracy challenges.",
     "Aadhaar electoral roll integration (2021-2023) | Electoral bond controversy (2023-2024) | VVPAT security mandate | ECI reforms under Article 324 | Supreme Court electoral supervision"),

    # Q39 - ID: 31589
    (2, 2,
     "Electoral disputes and Election Commission decisions are appealable through which mechanism:\nთేλుgu: ఎన్నిక వివాదాలు మరియు ఎన్నిక కమిషన్ నిర్ణయాలు ఈ విధానం ద్వారా అపీల్‌కు సంబంధించినవి:",
     "Election Commission's internal appellate mechanism / ఎన్నిక కమిషన్ అంతర్గత అపీల్ విధానం",
     "Election Tribunal established under Article 327 / అర్టికల్ 327 కింద ఎన్నిక ట్రిబ్యూనల్",
     "Supreme Court's constitutional jurisdiction under Articles 131 and 136 / అర్టికల్‌లు 131 మరియు 136 కింద సుప్రీం కోర్ట్ సంవిధానిక అధికారం",
     "High Court's writ jurisdiction under Article 226 / అర్టికల్ 226 కింద హైకోర్ట్ రిట్ అధికారం",
     "D",
     "Electoral disputes follow two-tier constitutional review: (i) High Courts exercise primary appellate jurisdiction through Article 226 writ petitions challenging ECI decisions on grounds of jurisdictional excess, procedural impropriety, or constitutional violation; (ii) Supreme Court exercises constitutional jurisdiction under Articles 131 and 136 to review High Court electoral decisions or directly appeal ECI orders involving constitutional interpretation. The Representation of the People (RP) Act 1951 supplements this through statutory Election Petitions (Section 100-120), but these operate under Article 226/131 constitutional framework.The constitutional hierarchy places electoral governance within constitutional courts' supervisory domain. Article 327 grants Parliament power to legislate on electoral matters (establishing statutory election tribunals for specific disputes like election finance violations), but ultimate authority remains with constitutional courts. The Supreme Court in Subramanian Swamy v. Election Commission (2013) held that while ECI exercises constitutional discretion under Article 324, Supreme Court's power under Article 131 permits constitutional review of electoral decisions affecting fundamental rights (Article 19's freedom to stand for election).Electoral petitions under RP Act Section 100 (contesting election results) are heard by Tribunals constituted under Article 327, but these Tribunals operate within constitutional framework. Appeals from Electoral Tribunals go to High Courts under Article 226, then Supreme Court under Article 131. This creates unique constitutional hierarchy where electoral governance flows through dedicated election machinery (ECI, Election Tribunals) but remains subject to constitutional court supervisory jurisdiction.Post-2020 electoral disputes (2019, 2024 general elections) brought hundreds of petitions before courts: (i) Candidate eligibility challenges (disqualification petitions); (ii) Election process disputes (polling irregularities, ballot miscount); (iii) Campaign finance violations (electoral bond disputes). These followed constitutional review pathway: ECI decides technically; courts review constitutionally through Articles 226/131. The Supreme Court in multiple post-2020 cases reaffirmed that electoral processes, while ECI's technical domain, remain subject to constitutional court supervision ensuring compliance with democratic principles enshrined in Constitution.",
     "Article 226 High Court writ jurisdiction | Articles 131/136 Supreme Court appeal | RP Act 1951 Election Petitions | Election Tribunals constitutional framework | Constitutional hierarchyof electoral review"),

    # Q40 - ID: 31590
    (0, 3,
     "Voter registration and electoral enrollment constitutional requirements stem from which article:\nთెลుgu: ఓటరు నమోదు మరియు ఎన్నిక నమోదు సంవిధానిక పర్యవేక్షణ ఈ వస్తువు నుండి ఉద్భవిస్తుంది:",
     "Article 326 only / అర్టికల్ 326",
     "Articles 325 and 326 together / అర్టికల్‌లు 325 మరియు 326",
     "Article 324 executive delegation mechanism / అర్టికల్ 324 కార్యనిర్వాహక ప్రతినిధి విధానం",
     "Representation of People Act without constitutional basis / జనప్రతినిధిత్వ చట్టం సంవిధానిక ఆధారం లేకుండా",
     "B",
     "Article 325 mandates 'nothing in this Constitution...shall require any person to pay any tax or fee for registration as an elector or for voting.' This establishes electoral registration as free constitutional right, not subject to payment barriers. Article 326 provides 'subject to the provisions of any law made by Parliament, every person who is a citizen of India and who is not less than 18 years of age on such date as may be prescribed...shall be entitled to be registered as an elector for the relevant constituency.' Together, these articles create constitutional framework: universal registration (Article 326) without fees (Article 325).The constitutional architecture requires two components: universal eligibility (Article 326—any citizen 18+ years) and universal accessibility (Article 325—without payment). Electoral Registration Officers, appointed under Article 324 (ECI's constitutional authority), must register all eligible citizens. The Supreme Court in N.G. Dastane v. S.V. Deshpande (1966) established that Article 326 creates individual's judicially-enforceable right to voter registration—citizens can petition courts to mandate registration if officials refuse.Article 324 provides operational mechanism: ECI superintends registration process through appointed officials, but Articles 325-326 constrain this power. ECI cannot restrict registration arbitrarily; it must follow constitutional eligibility criteria (citizenship, age, residency). The constitutional text emphasizes democratic access: no tax/fee barrier (Article 325) ensures poor citizens' electoral participation, reflecting democratic principle that voting is constitutional right, not privilege.The Representation of People Act 1951's electoral provisions operate within this constitutional framework. The RP Act operationalizes Articles 325-326 through statutory machinery (electoral rolls, registration procedures), but the Constitution itself provides substantive rights. Parliament cannot legislatively restrict Articles 325-326's guarantees; any statutory electoral registration law must comply with constitutional minimums.Post-2020, Aadhaar integration into electoral rolls (2021-2023) raised constitutional concerns: Does mandatory Aadhaar-based registration violate Article 326's universal accessibility? The Supreme Court in K.S. Puttaswamy case precedent held that Aadhaar doesn't violate Article 326 if alternative registration mechanisms remain available for those without Aadhaar. This preserved constitutional right while allowing technological modernization.",
     "Article 325 fee prohibition | Article 326 universal suffrage | Article 324 ECI superintendence | Aadhaar authentication challenges | Judicially-enforceable registration rights"),

    # Q41 - ID: 31591
    (1, 2,
     "The constitutional basis for Election Commission's authority to disqualify candidates rests on:\nთెლుguე: ఎన్నిక కమిషన్ అభ్యర్థులను బహిష్కరించే అధికారం ఈ సంవిధానిక ఆధారంపై ఆధారపడి ఉంది:",
     "Article 102 (MP disqualifications) and Article 191 (MLA disqualifications) combined / అర్టికల్‌లు 102 మరియు 191",
     "Article 324 (General electoral superintendence) with RP Act statutory framework / అర్టికల్ 324 మరియు RP చట్టం ఆధారం",
     "Election Commission's inherent constitutional authority / ఎన్నిక కమిషన్ అంతర్నిహిత సంవిధానిక అధికారం",
     "Parliament's legislative authority through Representation of People Act / సంసద్ చట్టం ద్వారా రాజకీయ చట్ట అధికారం",
     "B",
     "Article 324 grants Election Commission broad power to 'make any regulations...for giving effect to the provisions of...the Constitution.' This constitutional grant, combined with RP Act 1951's statutory framework (Section 33-50 specifying disqualification grounds), establishes ECI's disqualification authority. The Supreme Court in Kuldip Singh v. State of Haryana established that while Articles 102 and 191 specify disqualifications for elected Members, Article 324's constitutional grant and RP Act's statutory details empower ECI to determine disqualification eligibility before elections.The constitutional-statutory partnership: Articles 102/191 specify disqualification consequences (loss of office once elected); RP Act specifies candidacy eligibility conditions (Section 8, criminal convictions; Section 33-50, various disqualifications). ECI enforces these through Article 324 authority. Unlike parliamentary disqualifications (decided by Members under Article 102/191), electoral disqualifications (preventing candidacy) operate under ECI's Article 324 superintendence implemented through RP Act procedures.The practical distinction: (i) Article 102 applies post-election (disqualifies elected MP); (ii) RP Act Section 8 applies pre-election (prevents candidacy); (iii) ECI enforces pre-election disqualifications through Article 324 authority. Post-2020, disqualification disputes increased due to enhanced electoral finance scrutiny, tax delinquency scrutiny, criminal charge investigations. The Supreme Court consistently upheld ECI's Article 324 authority to disqualify while requiring procedural fairness (notice, hearing, evidence).However, constitutional constraints limit ECI's discretion: Articles 19(1)(d) guarantees 'right to...form associations,' which includes right to contest elections. Arbitrary disqualification without statutory basis violates Article 19(1)(d). The Court held that ECI must follow statutory criteria strictly (cannot invent new disqualification grounds); any interpretation of disqualification criteria must narrow, not expand, electoral exclusions.The Court also recognized Article 131 review power: If ECI disqualifies based on constitutional overreach, Supreme Court can intervene. In 2022 cases, Courts reviewed ECI disqualification orders for excessive interpretation of 'criminal conviction' disqualifications and 'unsound mind' determinations, protecting candidates' Article 19(1)(d) rights against arbitrary ECI action.",
     "Article 324 ECI superintendence | RP Act 1951 Section 8 disqualifications | Articles 102/191 post-election disqualifications | Article 19(1)(d) candidacy rights | Procedural fairness requirements"),

    # Q42 - ID: 31592
    (2, 3,
     "Voter registration using Aadhaar technology raised constitutional concerns primarily regarding:\nთEpiscopal: Aadhaar సాంకేతికత ఉపయోగించి ఓటరు నమోదు ఈ సంవిధానిక ఆందోళనలు లేవనెత్తింది:",
     "Article 326 universal suffrage compatibility / అర్టికల్ 326 సర్వసంక్షేమ సంగతి",
     "Article 21 privacy rights and biometric data collection / అర్టికల్ 21 గోప్యత హక్కులు మరియు బయోమెట్రిక్ సేకరణ",
     "Article 19(1)(d) association rights and digital exclusion / అర్టికల్ 19(1)(d) సంఘటన హక్కులు మరియు డిజిటల్ బర్జన",
     "All above / అన్నీ సరైనవి",
     "D",
     "Aadhaar-based electoral registration (implemented 2021-2023) raised constitutional concerns simultaneously under: (i) Article 326 (universality—can Aadhaar mandate exclude those without Aadhaar?); (ii) Article 21 (privacy—does biometric registration violate privacy rights?); (iii) Article 19(1)(d) (does digital infrastructure burden disproportionately exclude marginalized citizens?). Together, these concerns created constitutional conflict demanding reconciliation.Article 326's universality concern: The constitutional text guarantees every 18+ citizen's electoral registration. If Aadhaar becomes mandatory, citizens without Aadhaar face registration barriers. The Supreme Court addressed this in K.S. Puttaswamy reference (2019-2020 electoral registration case): Aadhaar-based registration is constitutional if alternative offline mechanisms remain for those without Aadhaar. The Court held that technology cannot become impediment to constitutional rights; it must enable rather than restrict.Article 21 privacy concerns: K.S. Puttaswamy case established privacy as Article 21 component. Compulsory biometric collection for electoral registration raised privacy questions: Does voting require biometric identification when alternative authentication suffices? The Court moderately protected privacy by permitting biometric collection only if: (i) Justifiable by security interests (preventing multiple voting); (ii) Minimal data collection (only voting-relevant biometrics); (iii) Data protection safeguards. This balanced registration needs against privacy rights.Article 19(1)(d) association concerns: Digital registration potentially excludes rural, poor, technology-illiterate citizens from electoral participation. Civil society raised concerns that Aadhaar infrastructure disparity could suppress participation. The Court required states to maintain offline registration alternatives, ensuring digital divide doesn't violate voting rights. This recognized that Article 326's universality must account for technology access disparity.Post-2020 implementation revealed practical constitutional tensions: (i) Some states aggressively enforced Aadhaar-based registration, creating de facto mandatory Aadhaar (violating K.S. Puttaswamy principle); (ii) Urban registration rates increased while rural rates stagnated, suggesting digital divide impacts; (iii) Transgender and marginalized communities faced biometric collection barriers. High Courts directed states to restore offline alternatives, operationalizing constitutional constraints on electoral technology.The constitutional resolution: Aadhaar-based electoral registration is permissible under Articles 326 and 324 if supplemented by alternative mechanisms protecting Article 21 privacy and Article 19(1)(d) accessibility. Technology cannot become constitutional barrier; it must enhance registration while maintaining universality and privacy.",
     "K.S. Puttaswamy privacy framework | Article 326 universality preservation | Article 19(1)(d) digital access concerns | Offline alternative mechanism requirement | Constitutional technology constraints"),

    # Q43 - ID: 31593
    (0, 2,
     "Electoral bond scheme introduced in 2017 created constitutional debate regarding:\nთెกு: 2017లో నిర్ధారిత ఎన్నిక బాండ్ స్కీమ్ ఈ సంవిధానిక చర్చ సృష్టించింది:",
     "Presidential electoral powers / రాష్ట్రపతి ఎన్నిక శక్తులు",
     "Campaign finance transparency vs donor privacy balance / ప్రచారణ ఆర్థిక పారదర్శకత vs దాతృ గోప్యత సమతుల్యం",
     "Election Commission enforcement mechanisms / ఎన్నిక కమిషన్ అమలు విధానం",
     "Voter education and awareness programs / ఓటరు విద్య మరియు సచేతన కార్యక్రమాలు",
     "B",
     "Electoral bond scheme (introduced 2017, modified 2018-2023) created constitutional tension between: (i) Campaign finance transparency (Article 19(1)(a) public right to know political funding sources); (ii) Donor privacy (Article 21's privacy component and freedom of association implications). The scheme permitted anonymous political donations through bonds, preventing public knowledge of political funding sources while maintaining government record.The constitutional debate centered on Article 19(1)(a) limitations: Can government restrict public's right to know political funding under Article 19(2) 'reasonable restrictions'? The government argued donor anonymity prevents electoral coercion (donors shouldn't be targeted for supporting particular parties). Civil society argued that voters have Article 19(1)(a) right to know political funding sources for informed voting. The Supreme Court in 2023-2024 cases walked careful constitutional line: upheld electoral bond anonymity as valid (Article 19(2) reasonable restriction) while directing transparency in electoral bond recipient disclosures (limiting anonymity to donor side only).This represented constitutional balance: Donors retain privacy (Article 21/association freedom), but parties receiving bonds must disclose total funding received, preventing complete opacity. The Court rejected complete transparency demand (which would violate donor privacy) and complete anonymity (which would violate Article 19(1)(a) voting awareness). The solution—selective disclosure—operated as constitutional compromise between competing rights.Post-2020 electoral finance litigation intensified as electoral bonds became largest political funding mechanism. The debate expanded to include concerns about quid pro quo arrangements: If donors remain anonymous, how can voters detect corruption (donor buying policy preferences)? The Court acknowledged this concern but held that investigation mechanisms (income tax, ED) rather than disclosure requirements protect anti-corruption interests.The 2024 general election saw renewed electoral bond debate: Opposition parties demanded complete disclosure; government maintained anonymity. The Supreme Court's 2024 judgment moderated the position: While electoral bonds remain, the Court directed enhanced reporting requirements and suggested electoral bond scheme revision, indicating constitutional discomfort with perpetual anonymity in future legislative amendments. This demonstrates ongoing constitutional tension between transparency and privacy in electoral finance.",
     "Electoral bond anonymity scheme (2017-2023) | Article 19(1)(a) transparency vs Article 21 privacy | Selective disclosure compromise | Anti-corruption investigation mechanisms | Supreme Court 2023-2024 jurisprudence"),

    # Q44 - ID: 31594
    (1, 2,
     "Constitutional restrictions on electoral spending by parties and candidates primarily derive from:\nთెguዋ: పార్టీలు మరియు అభ్యర్థుల ఎన్నిక వ్యయం పై సంవిధానిక నిషేధాలు ప్రధానంగా ఉద్భవిస్తాయి:",
     "Article 16 (Equality in public employment) / అర్టికల్ 16 సార్వజనిక ఉపాధిలో సమానత్వం",
     "Article 324 (ECI superintendence) and RP Act electoral expenditure limits / అర్టికల్ 324 మరియు RP చట్టం వ్యయ సీమితులు",
     "Article 25 (Religious freedom) and communal expenditure restrictions / అర్టికల్ 25 మతపరమైన వ్యయ నిషేధాలు",
     "DPSP Article 39 (Economic justice) and wealth redistribution / DPSP అర్టికల్ 39 సంపద పునర్విభజన",
     "B",
     "Article 324's grant of electoral superintendence to Election Commission, combined with Representation of People Act 1951's statutory expenditure limits (Section 77-79 candidates' spending limits, Section 109-110 party spending), establishes constitutional framework for electoral expenditure regulation. Article 324 provides constitutional basis; RP Act operationalizes it through statutory caps. The Supreme Court in Kuldip Singh and subsequent cases held that expenditure limits don't violate Article 19(1)(a) because Article 19(2) permits 'reasonable restrictions' to ensure 'electoral equality' and 'prevent wealthy candidates' disproportionate advantage.'The constitutional principle underlying expenditure regulation: equal political participation requires restricting spending disparity. Without limits, wealthy candidates and parties dominate electoral process through superior resources, undermining Article 326's 'equal vote' principle. Justice M. Katju articulated this: 'Electoral equality requires expenditure parity; unlimited spending violates constitutional democracy's essence.' This reasoning places expenditure limits within Article 326's fundamental democratic protection, not as restriction upon rights.The RP Act's current limits: Candidates limited to Rs. 25-100 lakh depending on state; parties face no formal ceiling but must disclose spending. Post-2020, this discrepancy (candidate limits v. party freedom) raised constitutional concerns. The Supreme Court in 2023 case acknowledged that party-candidate expenditure disparity creates constitutional tension but reluctant to impose party spending caps without legislative amendment, deferring to Parliament.Candidates challenged expenditure limits as violating Article 19(1)(d) (association/political participation freedom). The Court upheld limits as constitutional, holding that Article 19(d)'s freedom doesn't guarantee unlimited campaign spending; it guarantees opportunity to contest within constitutional equality framework. Limits ensure wealthy candidates don't monopolize political access.Post-2020 election expenditure disputes (regarding poll surveys, exit polls, media spending) raised questions about expenditure regulation's scope. The Court extended limits to media advertisements, poll agencies, and private spending supporting candidates, broadening RP Act interpretation to encompass all electoral spending, not just official campaign expenditures.",
     "Article 324 ECI superintendence | RP Act 1951 Section 77-79 expenditure caps | Article 326 electoral equality principle | Article 19(2) reasonable spending restrictions | Candidate vs party spending disparity"),

    # Q45 - ID: 31595
    (2, 3,
     "Post-2020 electoral dispute mechanisms expanded primarily through which judicial innovation:\nთెguా: 2020 తర్వాత ఎన్నిక వివాద విధానం ప్రధానంగా ఈ న్యాయ నవీకరణ ద్వారా విస్తరించింది:",
     "Establishing specialized election tribunals / ప్రత్యేక ఎన్నిక ట్రిబ్యూనల్‌ల ఏర్పాటు",
     "Supreme Court suo moto jurisdiction over electoral matters / సుప్రీం కోర్ట్ స్వప్రేరణ ఎన్నిక అధికారం",
     "Fast-track hearing procedures for electoral disputes / ఎన్నిక వివాదాల కోసం త్వరిత విచారణ విధానం",
     "Creation of election-specific writ categories under Article 32 / అర్టికల్ 32 కింద ఎన్నిక-నిర్దిష్ట రిట్ వర్గాలు",
     "B",
     "Post-2020, the Supreme Court increasingly exercised suo moto jurisdiction (initiated by Court itself, not through petitioner application) in electoral matters of constitutional significance. Cases include: (i) 2020 Supreme Court suo moto on online voting technology for remote voters; (ii) 2022 suo moto on electoral bond disclosure transparency; (iii) 2023 suo moto on EVM security following general election concerns. This represented judicial innovation where Court perceived electoral governance affecting constitutional democracy without waiting for individual petitions.The suo moto jurisdiction operated through Article 32 (fundamental rights violation directly before Supreme Court) interpreted as encompassing electoral rights disputes affecting democratic process itself. The Court held that Article 326's universal suffrage and Article 19(1)(a) information rights create judicial responsibility for electoral governance vigilance beyond individual petitioner interests. Justice Chandrachud articulated: 'When electoral process—democracy's foundation—faces constitutional challenges, Court has suo moto responsibility to intervene.'This judicial innovation faced constitutional criticism: (i) Does suo moto jurisdiction exceed judicial powers under Article 131-133, 136? (ii) Does Court effectively override Election Commission's Article 324 authority through suo moto intervention? (iii) Does suo moto jurisdiction allow courts to create electoral policy rather than adjudicate disputes? The Court responded that suo moto operates within constitutional bounds: it reviews constitutional dimensions of electoral governance, not micromanaging ECI's operational decisions. When Constitution's core—democratic process—is threatened, Court's suo moto responsibility activates.The practical effect: Post-2020 electoral governance increasingly sees Supreme Court proactive rather than reactive role. Rather than waiting for electoral petitions, Court initiated review of EVM security, electoral bond transparency, and Aadhaar registration issues. While ECI remains primary electoral authority, Supreme Court sua moto oversight represents constitutional check on electoral governance affecting democratic legitimacy.Critics argued suo moto shifted election governance toward courts, reducing ECI independence. The Court moderated this by establishing principle: suo moto intervenes only when constitutional democracy's fundamental aspects are threatened, not routine electoral administration. This maintained ECI's primary authority while asserting Court's constitutional guardianship role.",
     "Article 32 suo moto jurisdiction | Electoral rights constitutional dimension | EVM security suo moto review (2023) | Electoral bond suo moto (2022) | Judicial guardianship vs ECI autonomy balance"),

    # Q46 - ID: 31596
    (0, 2,
     "Balloting procedures and voting technology constitutional requirements stem from:\nთెguా: ఓటింగ్ విధానం మరియు సాంకేతికత సంవిధానిక అవసరాలు ఉద్భవిస్తాయి:",
     "Article 322 (Electoral procedure) / అర్టికల్ 322",
     "Article 324 (ECI superintendence) with Article 326 (suffrage protection) / అర్టికల్‌లు 324 మరియు 326",
     "Representation of People Act statutory procedures / జనప్రతినిధిత్వ చట్టం",
     "Election Commission administrative regulations / ఎన్నిక కమిషన్ నిబంధనలు",
     "B",
     "Article 324 establishes ECI's broad constitutional authority to 'make any regulations...for giving effect to the provisions of...the Constitution' regarding elections. This includes balloting procedures. Article 326 provides substantive constitutional requirement—voting must be genuinely 'free' (no coercion) and truly reflect voter's 'will.' Together, these establish constitutional framework: ECI operationalizes free and authentic voting through Article 324 authority, with Article 326 ensuring voting genuinely reflects citizens' choice.The constitutional constraint on balloting technology: Any voting procedure must protect Article 326's free voting. EVMs (Electronic Voting Machines) are constitutionally permissible if they: (i) Accurately record voter intent; (ii) Prevent coercion (secret ballot protected); (iii) Provide verification mechanisms (voters can confirm their vote recorded correctly). The Supreme Court in EVM validation cases (2014, 2017, 2023) upheld EVM constitutionality while requiring VVPAT (Voter Verifiable Paper Audit Trail), holding that voters must verify their votes were recorded accurately.The constitutional principle: technology serves voting authenticity, not replaces it. Ballots must authentically represent voter intent. The Court rejected ECI's efficiency argument (faster electronic counting) when authenticity compromised. In 2023 post-election disputes, the Court reiterated that Article 326 requires independently verifiable voting mechanism—whether paper ballots or digital with paper trail—but not purely electronic systems lacking independent verification.The RP Act operationalizes this through statutory procedure (Section 59-63), but constitutional requirements provide substantive constraints. Section 59 mandates 'secret ballot,' operationalizing Article 326's freedom requirement. ECI regulations (which Conduct of Election Rules) implement these, but must comply with constitutional Article 326 framework.Postal voting and remote voting (raised during 2020 pandemic) faced constitutional scrutiny: Can absentee voters vote through technology (video calling, digital ballot transmission)? The Court held that such remote voting must maintain Article 326's secrecy and authenticity. Digital remote voting is constitutionally permissible if it prevents coercion and accurately transmits voter intent, but ECI decided against large-scale remote voting implementation, preferring postal ballots' constitutional safety.",
     "Article 326 free and authentic voting | Article 324 ECI procedure authority | EVM constitutionality with VVPAT | Secret ballot requirement | Voting authenticity principle"),

    # Q47 - ID: 31597
    (1, 3,
     "Constitutional approach to electoral reform balances democratic participation against:\nთెguా: ఎన్నిక సంస్కారణకు సంవిధానిక దృష్టిభంగం ఈ విషయానికి సమతుల్యం చేస్తుంది:",
     "Executive efficiency in holding elections / రాష్ట్రపతి ఎన్నికల నిర్వహణ సామర్థ్యం",
     "Electoral integrity and prevention of fraud while maintaining participation access / ఎన్నిక సততం మరియు మోసం నిరోధం భాగస్వామ్య ఆందోళన",
     "Party organizational interests / పార్టీ సంస్థాగత ఆసక్తులు",
     "Government resource constraints / ప్రభుత్వ వనరుల సీమితులు",
     "B",
     "Constitutional framework for electoral reform operationalizes Article 326's 'free vote' principle against Article 324's practical electoral administration. Free voting requires accessibility (low barriers to participation), authenticity (genuine voter choice), and integrity (prevention of fraud). These principles sometimes conflict: technology enhancing integrity (fingerprint verification) might reduce accessibility (excluding those without clear fingerprints). Constitutional electoral reform requires balancing.Post-2020 reforms exemplify this balance: (i) Aadhaar electoral roll—enhances integrity (prevents multiple voting) but reduces accessibility (excludes Aadhaar-less citizens); (ii) EVM with VVPAT—maintains integrity and allows verification but increases complexity potentially confusing voters; (iii) Campaign finance transparency—prevents electoral fraud but invades donor privacy. Each reform faces constitutional scrutiny: does it violate Article 326's accessibility or Article 21's privacy?The Supreme Court established balancing principle (2020-2024): Electoral reforms must be 'constitutional necessity,' not mere efficiency. While government has right to modernize electoral procedures (Article 324), modernization cannot compromise fundamental voting rights. Courts require reforms to: (i) maintain or improve voter accessibility; (ii) demonstrate fraud-prevention necessity; (iii) provide alternative mechanisms for those disadvantaged by technology.The Court explicitly rejected efficiency-only arguments: Even if electronic voting is faster than paper ballots, efficiency doesn't justify adopting systems voters cannot independently verify (violating Article 326's voting authenticity). Similarly, while voter authentication through Aadhaar is efficient, accessibility concerns require offline alternatives. Constitutional primacy of Article 326 over administrative convenience establishes reform limits.Post-2020 electoral disputes (2019, 2024 general elections) revealed constitutional reform priorities: Integrity-focused reforms (Aadhaar, fingerprints) faced greater scrutiny than accessibility-focused reforms (urban polling booths, transportation assistance). The Court's jurisprudence suggests constitutional hierarchy: accessibility and authenticity (protecting actual voting) rank above integrity (preventing fraud), reflecting democratic principle that actual participation matters more than preventing marginal fraud.",
     "Article 326 free voting principle | Article 324 administrative authority | Accessibility vs integrity balance | Aadhaar authenticity concerns | Constitutional necessity test for reforms"),

    # Q48 - ID: 31598
    (2, 2,
     "Candidate eligibility requirements under Representation of People Act derive constitutional authority from:\nതെలుgu: జనప్రతినిధిత్వ చట్టం కింద అభ్యర్థి అర్హత అవసరాలు సంవిధానిక అధికారం ఉద్భవిస్తాయి:",
     "Articles 102/191 (Disqualifications for MPs/MLAs) / అర్టికల్‌లు 102/191",
     "Article 19(1)(d) (Association freedom) and RP Act statutory conditions / అర్టికల్ 19(1)(d) మరియు RP చట్టం",
     "Article 325 (Electoral participation eligibility) / అర్టికల్ 325 ఎన్నిక అర్హత",
     "Article 324 (ECI superintendence authority) with RP Act statutory conditions / అర్టికల్ 324 మరియు RP చట్టం నిబంధనలు",
     "D",
     "While Articles 102 and 191 specify post-election disqualifications (loss of office), candidate eligibility emerges from two sources: (i) Article 324's grant of electoral superintendence authority to ECI, allowing ECI to establish candidacy conditions within constitutional bounds; (ii) RP Act's statutory conditions specifying eligibility (Section 6-7: citizenship, age minimum, residence, educational requirements for some offices). The constitutional framework doesn't explicitly state eligibility requirements in Articles 102/191 (which address post-election disqualification); instead, Constitution delegates to ECI (Article 324) and Parliament (statutory authority) to specify candidacy conditions.The constitutional logic distinguishes disqualification (Articles 102/191, removing elected member) from ineligibility (RP Act, preventing candidacy). Articles 102/191 operate post-election; RP Act operates pre-election. ECI enforces pre-election ineligibility through Article 324 superintendence. This division ensures: (i) Parliamentary autonomy to remove elected members (Article 102/191); (ii) ECI operational authority for electoral process (Article 324); (iii) Statutory specificity of candidacy conditions (RP Act).The constitutional constraints on eligibility requirements: Article 19(1)(d)'s freedom to form associations includes freedom to contest elections. Therefore, eligibility conditions must be: (i) Statutorily specified (not arbitrary); (ii) Reasonably necessary (not pretextual); (iii) Proportionate (not excessively restrictive). The Supreme Court in various cases held that RP Act's conditions (citizenship, age, residence, education for some) satisfy these constraints. However, arbitrary or excessive conditions (e.g., absolute property requirement, unreasonable residence) would violate Article 19(1)(d).Post-2020 eligibility challenges: (i) Criminal conviction eligibility (do criminal charges prevent candidacy?); (ii) Tax delinquency eligibility (should tax arrears prevent candidacy?); (iii) Educational requirements (do they violate Article 19(1)(d)? only LS and state legislative posts require certain education under RP Act Section 173-174). The Court reviewed these as balancing Article 19(1)(d) against Article 324's electoral integrity concerns, generally upholding statutory conditions as constitutional while requiring evidence that eligibility criteria serve legitimate electoral purposes.",
     "Article 324 ECI superintendence for eligibility | RP Act Section 6-7 statutory conditions | Articles 102/191 post-election disqualifications | Article 19(1)(d) candidacy freedom | Proportionality constraints on eligibility"),

    # Q49 - ID: 31599
    (0, 3,
     "Election dispute resolution mechanisms underwent constitutional review primarily regarding:\nთელుgu: ఎన్నిక వివాద సమాధానం విధానం ప్రధానంగా సంవిధానిక సమీక్ష రూపంలో:\
",
     "Specialized tribunal jurisdiction and appeals framework / ప్రత్యేక ట్రిబ్యూనల్ అధికారం మరియు అపీల్",
     "Time-bound resolution and electoral matters' urgent nature / కాల-సంబంధిత సమాధానం మరియు ఎన్నిక అత్యవసర స్వభావం",
     "Supremacy of Article 131 Supreme Court jurisdiction over statutory election tribunals / అర్టికల్ 131 సుప్రీం కోర్ట్ అధిక్యం",
     "All above / అన్నీ సరైనవి",
     "D",
     "Post-2020 electoral dispute resolution underwent constitutional recalibration addressing: (i) Time-bound resolution—election disputes must resolve rapidly (elections occur periodically); (ii) Specialized expertise—election law requires technical election-specific knowledge beyond general courts; (iii) Constitutional supremacy—Supreme Court's Article 131 jurisdiction constrains election tribunal's authority. Together, these create constitutional framework balancing specialized electoral justice against constitutional court oversight.Time urgency represents unique constitutional concern: Unlike ordinary litigation where delay isn't unconstitutional, election dispute delay undermines electoral legitimacy. If election petition remains pending beyond election period, constitutional right to contest becomes hollow. The Supreme Court in post-2020 cases established fast-track hearing requirement: election petitions must be heard and decided before government formation (preferably during counting stage for general elections). This constitutional urgency principle doesn't exist in ordinary litigation.Specialized tribunals for election disputes (established under Article 327) address need for electoral expertise. However, constitutional courts retain ultimate jurisdiction: Article 131 permits Supreme Court direct review of election disputes of constitutional significance. The Court established principle: routine election petitions (candidate eligibility, election procedure) go through Election Tribunals; constitutional disputes affecting democratic legitimacy go to Supreme Court directly. In 2023 election, the Supreme Court reviewed tribunal decisions on candidate eligibility within days, establishing that electoral justice operates within constitutionally-compressed timeframes.The hierarchy: RP Act section 100-120 (electoral petitions) → Election Tribunals → High Court writ review → Supreme Court Article 131 appeal. However, constitutional significance fast-tracks Supreme Court intervention, collapsing this hierarchy. Cases involving Articles 326, 324, or fundamental voting rights skip tribunals and go directly to Supreme Court. This represents constitutional prioritization of democratic legitimacy over procedural ordinariness.Post-2020 developments exemplify this: (i) 2019 general election petitions resolved within months (constitutional urgency); (ii) 2023 state election disputes heard on expedited basis (electoral timeframe priority); (iii) Interim orders issued immediately during election (preventing procedural delays from affecting voting). The Court recognized that electoral disputes' constitutional character requires abandoning ordinary civil procedure timeframes, creating unique constitutional urgency doctrine for electoral matters.",
     "Time-bound electoral dispute resolution | Specialized election tribunals | Article 131 Supreme Court supremacy | Constitutional urgency doctrine | Articles 326/324 constitutional significance"),

    # Q50 - ID: 31600
    (1, 2,
     "Electoral equality principles embedded in Constitution protect against:\nთელుgu: సంవిధానంలో ఎమ్బెడ్ చేయబడిన ఎన్నిక సమానత్వ సూత్రాలు ఈ విషయానికి సంరక్షణ ఇస్తాయి:",
     "Wealthy candidates' electoral dominance through superior resources / సమృద్ధ అభ్యర్థుల సంపద ఓటింగ్ ప్రాధాన్యం",
     "Majority community's domination of electoral process / సంఖ్యాధిక జాతి ఎన్నిక కట్టుబాటు",
     "Caste-based voting patterns / జాతి-ఆధారిత ఎన్నిక నమూనాలు",
     "Regional language minorities' electoral exclusion / ఖేతర భాష సంఖ్యాలోపుల ఎన్నిక వర్జన",
     "A",
     "Article 326's electoral equality principle—'one person one vote'—protects against wealthy candidates monopolizing electoral process through superior resources. The Supreme Court established that electoral equality requires: (i) Spending limits (RP Act caps prevent wealth from dominating); (ii) Media access parity (preventing wealthy candidates buying media saturation); (iii) Campaign financing transparency (preventing hidden influence). These protections operationalize Article 326's fundamental democracy principle.Spending limits (RP Act Section 77-79) directly address wealth-based electoral dominance. Without limits, wealthy candidates campaign extensively while poor candidates struggle with minimal visibility. Electoral outcome becomes predetermined by initial wealth advantage, not voter preference. The Court recognized this as constitutional threat: democracy requires wealth-neutral electoral competition. Justice Katju articulated: 'Unlimited spending converts electoral democracy into plutocracy—rule by wealthy, not people.'The constitutional principle extends to preventing indirect wealth influence: Electoral bonds, corporate donations, anonymous funding allow wealthy individuals/corporations to purchase political influence without accountability. Campaign finance transparency laws (requiring donation disclosure) address this, though electoral bond debate (2017-2023) revealed persistent constitutional tension between disclosure transparency and donor privacy.Majority domination concerns (Caste/religion/region-based), while present, operate differently: Constitution addresses these through: (i) Reservations (Articles 330, 332) ensuring minority representation; (ii) Anti-discrimination provisions (Articles 15-16) preventing voting rights discrimination based on minority status; (iii) Communal electorate prohibition (RP Act removes separate religious electorates). These protections address majoritarian exclusion, not wealth-based dominance.However, post-2020 discourse increasingly connects wealth with majority dominance: Wealthy majority-community individuals/corporations spend disproportionately on majority-appealing campaigns, creating compounded dominance. The Supreme Court hasn't explicitly addressed this intersection, but spending limits theoretically constrain wealth-majority dominance simultaneously. Future constitutional jurisprudence may recognize spending limits as addressing both wealth-based and majority-based electoral distortions.",
     "Electoral spending limits Article 326 principle | Campaign finance transparency | Wealthy candidate electoral dominance | Reservation protections minority representation | Media access parity"),

    # Q51 - ID: 31601
    (2, 3,
     "Parliamentary electoral disputes' adjudication constitutional provisions distinguish between routine electoral petitions vs constitutional elections (Presidential/Vice-Presidential) and ordinary elections.\nసంసదీయ ఎన్నిక వివాదాల్లో నిత్య ఎన్నిక పిటికాలు వర్సెస్ రాష్ట్రపతి/ఉపరాష్ట్రపతి ఎన్నికలు మరియు సాధారణ ఎన్నికల మధ్య భేదం.",
     "Intra-parliamentary election disputes and inter-state electoral conflicts / పార్లమెంట్-లోపు ఎన్నిక వివాదాలు మరియు రాష్ట్రాంతర చర్చలు",
     "Candidate eligibility disputes and electoral process disputes vs presidential/parliamentary elections / అభ్యర్థి అర్హత వివాదాలు vs రాష్ట్రపతి ఎన్నికలు",
     "Routine electoral petitions vs constitutional elections (Presidential/Vice-Presidential) and ordinary elections / సాధారణ ఎన్నిక పిటికాలు vs రాష్ట్రపతి/ఉపరాష్ట్రపతి ఎన్నికలు",
     "State legislature elections and Union parliament elections with different dispute resolution frameworks / రాష్ట్ర ఎన్నికలు మరియు సంఘ ఎన్నికలు వేర్వేరు వివాద విధానాలతో",
     "C",
     "రాష్ట్రపతి మరియు ఉపరాష్ట్రపతి ఎన్నిక విషయమైన వివాదాలు సర్వోచ్చ న్యాయాలయానికి నేరుగా అర్టికల్ 71 ద్వారా సమర్పణ చేయబడతాయి, ఎన్నిక ట్రిబ్యూనల్‌ల ద్వారా కాదు. సాధారణ ఎన్నిక విషయాల్లో రిపబ్లిక్ చట్టం ఎన్నిక ట్రిబ్యూనల్‌లను అనుమతిస్తుంది.\nPresidential and Vice-Presidential election disputes are decided by the Supreme Court directly under Article 71, not through election tribunals. Parliamentary elections use RP Act election tribunals with High Court/Supreme Court oversight.",
     "Article 71 Presidential election jurisdiction | Article 329 RP Act petition procedures | Electoral Tribunal system | Articles 325-326 constitutional questions direct Supreme Court | Constitutional vs technical electoral disputes"),

]

QUESTIONS_PART2 = RTI_TRANSPARENCY_MCQS + ELECTORAL_COMMISSION_MCQS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             