"""
seed_summits_mcq.py
80 GKToday-style MCQs — Topic: International Current Affairs → Summits & Conferences
Coverage: 2025-2026 ONLY (no 2024/2023 data)
Folder: AP_HC | Topic: International_Current_Affairs | Sub-topic: Summits
IDs: 21001-21080
NOTE: seed() runs DELETE+INSERT to force-refresh stale data.
"""

import os, sqlite3

DATABASE_URL = os.environ.get("DATABASE_URL", "")
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)
USE_POSTGRES = bool(DATABASE_URL)

SUMMIT_MCQS = [
    # G20 South Africa 2025 (21001-21008)
    {"id":21001,"question":"The G20 Leaders' Summit 2025 was held in which city, marking the first-ever G20 hosted on the African continent?","option_a":"Cape Town, South Africa","option_b":"Nairobi, Kenya","option_c":"Johannesburg, South Africa","option_d":"Lagos, Nigeria","correct_answer":"C","explanation":"The 20th G20 Summit was held at the Johannesburg Expo Centre, South Africa on November 22-23, 2025 — first G20 ever hosted on the African continent. South Africa's G20 presidency followed Brazil (2024). USA will host G20 in Miami in 2026.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21002,"question":"What was the official theme of South Africa's G20 Presidency and Johannesburg Summit 2025?","option_a":"Building a Resilient World Together","option_b":"Solidarity, Equality, Sustainability","option_c":"Collaboration for the Intelligent Age","option_d":"A Spirit of Dialogue","correct_answer":"B","explanation":"'Solidarity, Equality, Sustainability' was South Africa's G20 2025 theme. The 122-point Johannesburg Declaration embodied Ubuntu philosophy: solidarity=cooperation, equality=fair opportunities, sustainability=long-term development.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21003,"question":"Which major G20 member was ABSENT from the G20 Johannesburg Summit 2025?","option_a":"China","option_b":"Russia","option_c":"United States","option_d":"United Kingdom","correct_answer":"C","explanation":"The USA did not participate in the G20 Johannesburg Summit 2025. Argentina was the only nation present that did not subscribe to the final declaration — FM Quirno cited missing 'geopolitical facts' on the Middle East.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21004,"question":"The Johannesburg G20 2025 Declaration referenced 'Ubuntu' philosophy. Ubuntu is a concept from which tradition?","option_a":"East Asian Confucian thought","option_b":"South American indigenous tradition","option_c":"African philosophy emphasising interconnectedness and shared humanity","option_d":"South Asian Vedantic philosophy","correct_answer":"C","explanation":"Ubuntu is an African philosophical concept meaning 'I am because we are' — emphasising interconnectedness and shared humanity. Its inclusion in G20 Johannesburg 2025 Declaration reflected South Africa's African identity and G20 host priorities.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21005,"question":"The G20 Johannesburg 2025 Declaration included a call for reform of which major international body?","option_a":"IMF","option_b":"World Bank","option_c":"UN Security Council","option_d":"WTO","correct_answer":"C","explanation":"The 122-point G20 Johannesburg Declaration called for UN Security Council (UNSC) reform — demanded by Global South. Other key outcomes: G20 Critical Minerals Framework (voluntary), AI initiative for Africa, debt sustainability for developing nations.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21006,"question":"Which country will host the G20 Summit in 2026?","option_a":"Germany","option_b":"Japan","option_c":"United States","option_d":"India","correct_answer":"C","explanation":"USA will host the G20 in 2026 at Miami. G20 2025 chairmanship handed over from South Africa to USA on January 12, 2026. Host sequence: Brazil (2024) → South Africa (2025) → USA/Miami (2026).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21007,"question":"At the G20 Johannesburg 2025, what voluntary framework was endorsed for managing critical mineral supply chains?","option_a":"G20 Strategic Minerals Accord","option_b":"G20 Critical Minerals Framework","option_c":"Global Mineral Governance Protocol","option_d":"Johannesburg Raw Materials Declaration","correct_answer":"B","explanation":"The G20 Critical Minerals Framework (voluntary) was endorsed at Johannesburg 2025 — tracking labour costs and environmental damages not normally priced in free markets. This followed similar work at G7 Kananaskis 2025.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21008,"question":"Which nation opposed the G20 Johannesburg 2025 final declaration, citing missing geopolitical context on the Middle East?","option_a":"Russia","option_b":"Argentina","option_c":"USA","option_d":"Hungary","correct_answer":"B","explanation":"Argentina was the only G20 nation that did not subscribe to the Johannesburg 2025 Declaration. Argentine FM Quirno said 'context and geopolitical facts' were missing regarding the Middle East (ongoing Iran-Israel-US war in 2026). The USA was simply absent from the summit itself.","folder":"AP_HC","topic":"International_Current_Affairs"},

    # G7 Kananaskis Canada 2025 (21009-21014)
    {"id":21009,"question":"The G7 Summit 2025 was hosted by which country, and who was the host leader?","option_a":"Italy, PM Giorgia Meloni","option_b":"USA, President Donald Trump","option_c":"Canada, PM Mark Carney","option_d":"Japan, PM Sanae Takaichi","correct_answer":"C","explanation":"Canada hosted the 51st G7 Summit at Kananaskis, Alberta (June 15-17, 2025). PM Mark Carney hosted. Trump departed early (~12 hours) citing need to deal with the Israel-Iran conflict. No formal joint communiqué was signed after Trump's exit.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21010,"question":"At which specific location in Canada was the G7 Summit 2025 held?","option_a":"Banff, Alberta","option_b":"Vancouver, British Columbia","option_c":"Quebec City, Quebec","option_d":"Kananaskis, Alberta","correct_answer":"D","explanation":"G7 Summit 2025 was held in Kananaskis, Alberta — a remote mountain resort chosen partly for security. After Trump's early departure, the remaining six leaders issued a joint statement on AI, critical minerals, wildfires, and migrant smuggling.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21011,"question":"US President Trump departed the G7 Kananaskis Summit 2025 early, citing which international crisis?","option_a":"North Korea missile launches","option_b":"Taiwan Strait tensions","option_c":"Israel-Iran conflict","option_d":"Russia-Ukraine battlefield escalation","correct_answer":"C","explanation":"Trump left G7 Kananaskis early (after ~12 hours) citing the Israel-Iran conflict — specifically the escalating June 2025 Twelve-Day War. His early exit recalled his departure from Charlevoix G7 in 2018. The remaining 6 leaders issued a joint statement without the US.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21012,"question":"What tariff threat did Trump make toward Canada after the G7 Kananaskis Summit 2025?","option_a":"10% tariff on all Canadian goods","option_b":"25% tariff on Canadian steel","option_c":"35% tariff on Canadian goods if no trade deal reached","option_d":"50% tariff on Canadian energy exports","correct_answer":"C","explanation":"Trump threatened 35% tariffs on Canadian goods (effective August 1, 2025) if Canada did not reach a prompt trade deal. Trump's tariff pressure on allies was a defining tension of Kananaskis. G7 2026 is hosted by France.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21013,"question":"The G7 Kananaskis 2025 remaining six leaders' joint statement reached consensus on which topics?","option_a":"Quantum internet standards","option_b":"Space exploration cooperation","option_c":"AI, quantum computing, and critical minerals","option_d":"5G network security","correct_answer":"C","explanation":"The six remaining G7 leaders agreed on AI, quantum computing, and critical minerals — that AI should 'grow prosperity, benefit societies, and address global challenges.' The statement emphasized AI adoption rather than just regulation, marking a shift from prior G7 AI governance focus.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21014,"question":"Which country will host the G7 Summit in 2026?","option_a":"USA","option_b":"France","option_c":"UK","option_d":"Germany","correct_answer":"B","explanation":"France will host the G7 Summit in 2026. Host sequence: Italy Puglia (2024) → Canada Kananaskis (2025) → France (2026). G7 members: USA, UK, Canada, France, Germany, Italy, Japan + EU.","folder":"AP_HC","topic":"International_Current_Affairs"},

    # NATO The Hague 2025 (21015-21020)
    {"id":21015,"question":"The NATO Summit 2025 was held in which city on June 24-25, 2025?","option_a":"Brussels, Belgium","option_b":"Warsaw, Poland","option_c":"The Hague, Netherlands","option_d":"Vilnius, Lithuania","correct_answer":"C","explanation":"NATO Summit 2025 was held at the World Forum, The Hague, Netherlands on June 24-25, 2025. Key outcomes: 5% GDP defense spending target (all except Spain), €40 billion Ukraine aid, Article 5 reaffirmed. NATO 2026 will be in Ankara, Turkey.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21016,"question":"The most significant outcome of NATO Hague Summit 2025 was a new defense spending target. What was it?","option_a":"2% of GDP","option_b":"3% of GDP","option_c":"4% of GDP","option_d":"5% of GDP","correct_answer":"D","explanation":"NATO Hague 2025 adopted 5% GDP defense spending — a massive jump from the 2014 benchmark of 2%. Breakdown: 3.5% core military + 1.5% defense-related (infrastructure, cyber). All NATO members agreed except Spain. Reflects threats from Russia and terrorism.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21017,"question":"Under NATO's 5% GDP defense spending target (The Hague 2025), how is the spending broken down?","option_a":"4% military + 1% infrastructure","option_b":"3.5% core military + 1.5% defense-related (cyber/infrastructure)","option_c":"2.5% military + 2.5% security","option_d":"All 5% directed to direct military capabilities","correct_answer":"B","explanation":"NATO's 5% GDP target (Hague 2025): 3.5% for core military capabilities + 1.5% for broader defense-related sectors including infrastructure and cyber defense. This replaces the 2014 Wales Summit target of 2% GDP.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21018,"question":"Which NATO member was the sole dissenter to the 5% defense spending target at the Hague Summit 2025?","option_a":"France","option_b":"Germany","option_c":"Italy","option_d":"Spain","correct_answer":"D","explanation":"Spain was the only NATO member that did not agree to the 5% GDP defense spending target at The Hague Summit 2025. Spain under PM Sánchez has historically resisted higher defense targets. NATO currently has 32 members (Sweden joined as 32nd in March 2024).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21019,"question":"How much financial aid did NATO allies pledge to Ukraine at the Hague Summit 2025?","option_a":"€20 billion","option_b":"€40 billion","option_c":"€60 billion","option_d":"€100 billion","correct_answer":"B","explanation":"NATO allies pledged €40 billion in defense aid to Ukraine for 2025 at the Hague Summit. The declaration did NOT include a Ukraine NATO membership invitation, timeline, or pathway — disappointing Kyiv which hoped for stronger political commitments.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21020,"question":"Where will the NATO Summit 2026 be held?","option_a":"Warsaw, Poland","option_b":"London, United Kingdom","option_c":"Ankara, Turkey","option_d":"Oslo, Norway","correct_answer":"C","explanation":"NATO Summit 2026 will be held July 7-8, 2026 at the Beştepe Presidential Complex in Ankara, Turkey. NATO Secretary-General since October 2024: Mark Rutte (Netherlands), who replaced Jens Stoltenberg. Host sequence: Washington DC (2024) → The Hague (2025) → Ankara (2026).","folder":"AP_HC","topic":"International_Current_Affairs"},

    # BRICS Brazil 2025 (21021-21028)
    {"id":21021,"question":"The 17th BRICS Summit 2025 was hosted by which country, and where?","option_a":"South Africa, Johannesburg","option_b":"Russia, Moscow","option_c":"Brazil, Rio de Janeiro","option_d":"China, Beijing","correct_answer":"C","explanation":"The 17th BRICS Summit 2025 was held in Rio de Janeiro, Brazil on July 6-7, 2025. Brazil held the BRICS chairmanship in 2025. This was the first BRICS summit to feature Indonesia as a full member (joined January 6, 2025). India hosts 18th BRICS Summit 2026.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21022,"question":"Which country joined BRICS as a full member on January 6, 2025, becoming the first Southeast Asian nation in the bloc?","option_a":"Malaysia","option_b":"Vietnam","option_c":"Thailand","option_d":"Indonesia","correct_answer":"D","explanation":"Indonesia joined BRICS as a full member on January 6, 2025 — first Southeast Asian state in BRICS and the 11th full member. Indonesia's bid was approved in 2023 but requested entry after its 2024 presidential election. BRICS now: Brazil, Russia, India, China, South Africa, Egypt, Ethiopia, Iran, UAE, Saudi Arabia, Indonesia.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21023,"question":"At BRICS Rio Summit 2025, how many new countries were admitted as BRICS 'partner countries'?","option_a":"5","option_b":"7","option_c":"10","option_d":"13","correct_answer":"C","explanation":"10 new BRICS partner countries admitted at Rio 2025: Belarus, Bolivia, Kazakhstan, Cuba, Malaysia, Nigeria, Thailand, Uganda, Uzbekistan, and Vietnam. Two-tier structure: 11 full members + 10 partner nations. BRICS now represents a major Global South coalition.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21024,"question":"After Indonesia joined in 2025, how many FULL MEMBERS does BRICS have?","option_a":"10","option_b":"11","option_c":"15","option_d":"21","correct_answer":"B","explanation":"BRICS has 11 full members: Brazil, Russia, India, China, South Africa (original 5) + Egypt, Ethiopia, Iran, UAE, Saudi Arabia (joined Jan 1, 2024) + Indonesia (Jan 6, 2025). The 10 partner countries at Rio 2025 are NOT full members. Total grouping: 11 full + 10 partners = 21 nations.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21025,"question":"Where will the 18th BRICS Summit 2026 be held?","option_a":"Moscow, Russia","option_b":"Beijing, China","option_c":"New Delhi, India","option_d":"Dubai, UAE","correct_answer":"C","explanation":"18th BRICS Summit 2026 is in New Delhi, India on September 12-13, 2026 — during India's BRICS Chairmanship. First India BRICS summit since expansion to 11 members. Host sequence: Russia Kazan (2024) → Brazil Rio (2025) → India New Delhi (2026).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21026,"question":"Which of these is NOT one of the 10 BRICS partner countries admitted at Rio de Janeiro 2025?","option_a":"Malaysia","option_b":"Vietnam","option_c":"Pakistan","option_d":"Nigeria","correct_answer":"C","explanation":"Pakistan is NOT a BRICS partner country. The 10 BRICS partners (Rio 2025): Belarus, Bolivia, Kazakhstan, Cuba, Malaysia, Nigeria, Thailand, Uganda, Uzbekistan, Vietnam. Pakistan has SCO membership but is not in BRICS. India-Pakistan tensions may also factor.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21027,"question":"BRICS was originally 'BRIC'. When did South Africa join, and when was the FIRST expansion after that?","option_a":"South Africa joined 2010; next expansion 2023","option_b":"South Africa joined 2010; next expansion January 2024","option_c":"South Africa joined 2012; next expansion 2024","option_d":"South Africa joined 2015; next expansion 2024","correct_answer":"B","explanation":"South Africa joined BRIC in 2010 (making it BRICS). Next BRICS expansion: January 1, 2024 when Egypt, Ethiopia, Iran, UAE, and Saudi Arabia joined (5 new members). Indonesia joined January 6, 2025 as the 11th member. BRICS proposed by Goldman Sachs economist Jim O'Neill in 2001.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21028,"question":"BRICS full members (11 nations) collectively represent approximately what percentage of global GDP (PPP)?","option_a":"Around 20%","option_b":"Around 30%","option_c":"Around 37%","option_d":"Around 50%","correct_answer":"C","explanation":"BRICS 11 full members represent approximately 37% of global GDP (PPP) after 2025 expansion — larger than the G7 by PPP. BRICS represents 45%+ of world population. De-dollarisation (developing alternatives to USD) is a key BRICS economic discussion point, with Brazil hosting at Rio 2025.","folder":"AP_HC","topic":"International_Current_Affairs"},

    # SCO Tianjin 2025 (21029-21034)
    {"id":21029,"question":"The 25th SCO Heads of State Summit 2025 was held in which city?","option_a":"Beijing, China","option_b":"Shanghai, China","option_c":"Tianjin, China","option_d":"Astana, Kazakhstan","correct_answer":"C","explanation":"25th SCO Heads of State Council was held in Tianjin, China on August 31-September 1, 2025 — described as the largest SCO summit in history. Key outcomes: Tianjin Declaration, SCO Development Bank established, SCO 2035 Strategy, counter-extremism programme. 20 documents signed total.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21030,"question":"A significant bilateral at SCO Tianjin 2025: PM Modi met President Xi Jinping. What made this historically notable?","option_a":"First India-China bilateral in 10 years","option_b":"First time Modi met Xi on Chinese soil in 7 years","option_c":"First meeting after India joined SCO in 2017","option_d":"First meeting since Galwan clash 2020","correct_answer":"B","explanation":"PM Modi met Xi Jinping at SCO Tianjin 2025 — first time Modi met Xi on Chinese soil in 7 years (since Wuhan 2018 informal summit). Both pledged cooperation and resolving Himalayan border disputes. Meeting coincided with broader India-China normalization post-2020 Galwan clash.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21031,"question":"What major institutional decision was taken at the SCO Tianjin Summit 2025?","option_a":"SCO military alliance treaty signed","option_b":"Establishment of the SCO Development Bank","option_c":"SCO free trade agreement","option_d":"SCO permanent peacekeeping force","correct_answer":"B","explanation":"SCO Development Bank was established at Tianjin 2025 to finance infrastructure among SCO members. China pledged 2 billion yuan ($280M) free aid + 10 billion yuan ($1.4B) in loans over three years. 20 documents signed including Tianjin Declaration and SCO 2035 Strategy.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21032,"question":"SCO Tianjin 2025 explicitly condemned which Indian security event — a rare SCO condemnation of terrorism targeting India?","option_a":"Pulwama attack 2019","option_b":"Uri attack 2016","option_c":"Pahalgam terror attack April 22, 2025","option_d":"Parliament attack 2001","correct_answer":"C","explanation":"The SCO Tianjin 2025 declaration explicitly condemned the Pahalgam terror attack (April 22, 2025, J&K — 26 tourists killed) and called for bringing perpetrators to justice. This was a diplomatic win for India as China and Pakistan are both SCO members alongside India.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21033,"question":"SCO Tianjin 2025 had 10 full members. Which of these is NOT a full SCO member?","option_a":"Iran","option_b":"Belarus","option_c":"Afghanistan","option_d":"Uzbekistan","correct_answer":"C","explanation":"Afghanistan is NOT a full SCO member (has observer status). 10 full SCO members: China, Russia, India, Pakistan, Kazakhstan, Kyrgyzstan, Tajikistan, Uzbekistan, Iran (joined 2023), Belarus (joined 2024). SCO founded 2001 in Shanghai; HQ: Beijing.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21034,"question":"PM Modi outlined India's SCO vision at Tianjin 2025 under three pillars. Which is NOT one of those three?","option_a":"Security","option_b":"Connectivity","option_c":"Opportunity","option_d":"Democracy","correct_answer":"D","explanation":"PM Modi's three SCO pillars at Tianjin 2025: Security (counter-terrorism), Connectivity (infrastructure projects), Opportunity (economic growth, Civilizational Dialogue Forum). 'Democracy' was not a pillar. Modi also proposed a new Civilizational Dialogue Forum within SCO.","folder":"AP_HC","topic":"International_Current_Affairs"},

    # ASEAN KL 2025 (21035-21040)
    {"id":21035,"question":"The 47th ASEAN Summit 2025 was held in which city, and which country chaired ASEAN in 2025?","option_a":"Bangkok, Thailand","option_b":"Kuala Lumpur, Malaysia","option_c":"Manila, Philippines","option_d":"Jakarta, Indonesia","correct_answer":"B","explanation":"47th ASEAN Summit was held in Kuala Lumpur, Malaysia on October 26-28, 2025, with Malaysia as ASEAN Chair. Key outcomes: Timor-Leste admitted as 11th member, Thailand-Cambodia KL Peace Accord, ASEAN-China FTA 3.0, chairmanship passed to Philippines.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21036,"question":"Which country became the 11th member of ASEAN at the Kuala Lumpur Summit October 2025?","option_a":"Papua New Guinea","option_b":"Timor-Leste","option_c":"Sri Lanka","option_d":"Bangladesh","correct_answer":"B","explanation":"Timor-Leste (East Timor) was formally admitted as ASEAN's 11th member at the 47th ASEAN Summit — ASEAN's first expansion since Cambodia joined in 1999 (26-year gap). Timor-Leste gained independence from Indonesia in 2002, had been seeking ASEAN membership since 2011. ASEAN HQ: Jakarta, Indonesia.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21037,"question":"The 'Kuala Lumpur Peace Accord' signed at ASEAN 47th Summit 2025 was between which two nations?","option_a":"Myanmar and Thailand","option_b":"Thailand and Cambodia","option_c":"Vietnam and Cambodia","option_d":"Philippines and China","correct_answer":"B","explanation":"Thailand and Cambodia signed the 'KL Peace Accord' at ASEAN 47th Summit 2025, with Trump and PM Anwar Ibrahim as witnesses. Committed both to a permanent ceasefire, withdrawal of heavy weapons, deployment of external observers, and Bangkok releasing 18 Cambodian detainees. Trump also signed trade deals with Malaysia and Cambodia.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21038,"question":"ASEAN KL 2025 upgraded trade architecture with China through which agreement?","option_a":"ASEAN-China Comprehensive Trade Partnership","option_b":"ASEAN-China FTA 3.0 Upgrade Protocol","option_c":"RCEP 2.0 Enhanced Protocol","option_d":"ASEAN Plus Three Trade Modernisation Pact","correct_answer":"B","explanation":"ASEAN-China FTA 3.0 Upgrade Protocol was signed at ASEAN KL 2025 — deepening regional economic integration with China (ASEAN's largest external trade partner, ~20% of ASEAN trade). ASEAN-China FTA originally signed 2002, version 2.0 in 2015, version 3.0 in 2025.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21039,"question":"After 47th ASEAN Summit 2025, Malaysia handed the ASEAN Chairmanship to which country for 2026?","option_a":"Vietnam","option_b":"Thailand","option_c":"Philippines","option_d":"Indonesia","correct_answer":"C","explanation":"Malaysia handed ASEAN Chairmanship to Philippines at close of 47th ASEAN Summit. Chair sequence: Laos (2024) → Malaysia (2025) → Philippines (2026). ASEAN founded 1967 (Bangkok Declaration); now 11 members after Timor-Leste joined 2025.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21040,"question":"The ASEAN 47th Summit 2025 reviewed implementation of 'Five-Point Consensus' related to which member country's crisis?","option_a":"Cambodia","option_b":"Thailand","option_c":"Myanmar","option_d":"Vietnam","correct_answer":"C","explanation":"ASEAN's Five-Point Consensus (adopted 2021) addresses Myanmar's crisis following the February 2021 military coup. At KL 2025, leaders reaffirmed cessation of violence must precede elections, and agreed to explore a longer-term ASEAN Special Envoy for Myanmar.","folder":"AP_HC","topic":"International_Current_Affairs"},

    # COP30 Belem 2025 (21041-21048)
    {"id":21041,"question":"COP30 was held in which city in November 2025, symbolically located in the Amazon rainforest?","option_a":"São Paulo, Brazil","option_b":"Bogotá, Colombia","option_c":"Belém, Brazil","option_d":"Buenos Aires, Argentina","correct_answer":"C","explanation":"COP30 was held in Belém, Brazil (Amazon region) on November 10-21, 2025 — first major UN climate conference in the Amazon. Key outcomes: $1.3 trillion/year climate finance target by 2035, FRLD operational, tripling adaptation finance. COP31 will be Antalya, Turkey 2026.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21042,"question":"The COP30 Belém 2025 climate finance decision sets a target to mobilise how much per year by 2035?","option_a":"$300 billion","option_b":"$500 billion","option_c":"$1 trillion","option_d":"$1.3 trillion","correct_answer":"D","explanation":"COP30 Belém adopted $1.3 trillion/year by 2035 — significantly more than COP29 Baku's NCQG of $300 billion/year (which India called 'paltry'). COP30 also called for tripling adaptation finance and operationalised the Loss & Damage Fund (FRLD).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21043,"question":"The Loss & Damage Fund (FRLD) became operational at COP30. What was its pledged amount as it opened for business?","option_a":"$1 billion","option_b":"$431 million","option_c":"$5 billion","option_d":"$10 billion","correct_answer":"B","explanation":"FRLD (Fund for Responding to Loss and Damage) became operational at COP30 with $431.52 million pledged — far short of the estimated $724 billion/year needed. The fund was agreed at COP27, operationalised at COP28, but opened for business only at COP30 Belém.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21044,"question":"COP30 Belém 2025 Belém Political Package set what target for adaptation finance by 2035?","option_a":"Double","option_b":"Triple","option_c":"Quadruple","option_d":"Maintain current levels","correct_answer":"B","explanation":"COP30 adopted a target to TRIPLE adaptation finance by 2035. Adaptation finance helps developing nations cope with climate impacts (floods, droughts, sea level rise). The COP29 NCQG ($300B/year) focused primarily on mitigation; adaptation was underfunded.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21045,"question":"Which COP was the FIRST to include 'transition away from fossil fuels' language in its final text?","option_a":"COP26 Glasgow (2021)","option_b":"COP27 Sharm el-Sheikh (2022)","option_c":"COP28 Dubai (2023)","option_d":"COP29 Baku (2024)","correct_answer":"C","explanation":"COP28 Dubai (2023) was the first COP to include 'transition away from fossil fuels' language — a historic breakthrough. COP27 created Loss & Damage Fund; COP29 Baku set $300B/year NCQG; COP30 Belém raised it to $1.3T/year by 2035.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21046,"question":"Where will COP31 be held in 2026?","option_a":"New Delhi, India","option_b":"Cairo, Egypt","option_c":"Antalya, Turkey","option_d":"Nairobi, Kenya","correct_answer":"C","explanation":"COP31 will be held in Antalya, Turkey in November 2026 (Australia sharing leadership role). COP host sequence: Dubai UAE (COP28, 2023) → Baku Azerbaijan (COP29, 2024) → Belém Brazil (COP30, 2025) → Antalya Turkey (COP31, 2026). UNFCCC Secretariat HQ: Bonn, Germany.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21047,"question":"COP30 significance: Belém is located in which Brazilian state, at the mouth of which river?","option_a":"Mato Grosso; Pantanal wetlands","option_b":"Pará; Amazon River","option_c":"Amazonas; Rio Negro River","option_d":"Bahia; São Francisco River","correct_answer":"B","explanation":"Belém is in Pará state, at the mouth of the Amazon River. Brazil's President Lula championed Belém as COP30 host to highlight Amazon deforestation and biodiversity. The Amazon absorbs ~2 billion tons of CO2/year and is critical for global climate regulation.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21048,"question":"COP30 'called on' countries to triple adaptation finance. What is the key LIMITATION noted by climate analysts?","option_a":"Applies only to G7 nations","option_b":"Doesn't specify baseline, funding sources, or target figure","option_c":"Requires unanimity to implement","option_d":"Excludes least developed countries","correct_answer":"B","explanation":"COP30's call to 'triple adaptation finance by 2035' does NOT specify: baseline for the increase, sources of funds, or a target figure. This vagueness weakens enforceability. The Belém Political Package was described as strengthening 'infrastructure of climate action' rather than a grand bargain.","folder":"AP_HC","topic":"International_Current_Affairs"},

    # WEF Davos 2025 & 2026 (21049-21052)
    {"id":21049,"question":"What was the theme of WEF Davos Annual Meeting 2025 (January 20-24, 2025)?","option_a":"Rebuilding Trust","option_b":"A Spirit of Dialogue","option_c":"Collaboration for the Intelligent Age","option_d":"Cooperation in a Fragmented World","correct_answer":"C","explanation":"'Collaboration for the Intelligent Age' was WEF Davos 2025 theme (January 20-24, 2025). AI was the central theme. Note: January 20 was also Trump's inauguration day. WEF themes: 2023='Cooperation in Fragmented World', 2024='Rebuilding Trust', 2025='Collaboration for Intelligent Age', 2026='A Spirit of Dialogue'.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21050,"question":"What was the theme of WEF Davos Annual Meeting 2026 (January 19-23, 2026)?","option_a":"Collaboration for the Intelligent Age","option_b":"A Spirit of Dialogue","option_c":"Rebuilding Global Consensus","option_d":"Solidarity for a Sustainable Future","correct_answer":"B","explanation":"'A Spirit of Dialogue' was WEF Davos 2026 theme (56th Annual Meeting, January 19-23, 2026). Record attendance: 60+ heads of state, 400+ political leaders, 830+ CEOs. Key: Zelenskyy met Trump; announced US-Ukraine-Russia trilateral talks in Abu Dhabi on January 23.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21051,"question":"At WEF Davos 2026, which significant Ukraine peace initiative was announced?","option_a":"Russia-Ukraine ceasefire signed in Davos","option_b":"US-Ukraine-Russia trilateral talks to begin in Abu Dhabi January 23","option_c":"NATO membership invitation for Ukraine","option_d":"China-mediated Ukraine peace roadmap","correct_answer":"B","explanation":"At Davos 2026, Zelenskyy met Trump and announced US-Ukraine-Russia trilateral peace talks in Abu Dhabi on January 23, 2026. This was a significant diplomatic development in the Russia-Ukraine peace process — Trump later also brokered a 3-day ceasefire in May 2026.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21052,"question":"WEF's Future of Jobs Report predicted what fraction of current jobs will change by 2030, with 39% of skills becoming obsolete?","option_a":"1 in 8 jobs","option_b":"1 in 6 jobs","option_c":"1 in 4 jobs","option_d":"1 in 2 jobs","correct_answer":"C","explanation":"WEF Future of Jobs Report: 1 in 4 jobs likely to change by 2030; 39% of current skills becoming obsolete. Technology change is the biggest driver, followed by demographic shifts and green transition. AI and automation are the primary disruptors.","folder":"AP_HC","topic":"International_Current_Affairs"},

    # QUAD 2025 (21053-21056)
    {"id":21053,"question":"What happened to the QUAD Leaders' Summit scheduled to be hosted by India in 2025?","option_a":"Held successfully in New Delhi in November 2025","option_b":"Cancelled — Trump refused to attend; no leaders' summit convened","option_c":"Shifted from India to Japan","option_d":"Held virtually due to India-Pakistan tensions","correct_answer":"B","explanation":"The QUAD Leaders' Summit 2025 in India did NOT take place — Trump cancelled due to worsening US-India ties. However, QUAD Foreign Ministers met, and initiatives continued: MAITRI, QUAD-at-Sea (operationalized June 2025), Critical Minerals Initiative, Ports of the Future Partnership (Mumbai). Leaders' summit planned for early 2026.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21054,"question":"The 'QUAD-at-Sea Ship Observer Mission' was first operationalised in which month of 2025?","option_a":"March 2025","option_b":"June 2025","option_c":"September 2025","option_d":"December 2025","correct_answer":"B","explanation":"QUAD-at-Sea Ship Observer Mission was first operationalised in June 2025 — placing rotating naval observers from India, USA, Japan, Australia on each other's naval vessels to enhance maritime interoperability. This was a major QUAD deliverable first announced at QUAD Wilmington Summit 2024.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21055,"question":"The QUAD 'Ports of the Future Partnership' was launched in 2025. Where was the conference hosted?","option_a":"New Delhi","option_b":"Tokyo","option_c":"Sydney","option_d":"Mumbai","correct_answer":"D","explanation":"QUAD Ports of the Future Partnership was launched at a transportation and logistics conference in Mumbai, India (October 2025) with Indo-Pacific partner nations. QUAD also launched the QUAD Critical Minerals Initiative (2025) and QUAD STEM Scholarships (50 Indo-Pacific students at Indian engineering institutions).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21056,"question":"MAITRI (Maritime Initiative for Training in the Indo-Pacific) — a QUAD initiative — primarily does what?","option_a":"Conducts joint naval war games","option_b":"Trains Indo-Pacific partner nation coast guards","option_c":"Monitors Chinese naval movements","option_d":"Provides humanitarian disaster relief","correct_answer":"B","explanation":"MAITRI trains Indo-Pacific partner nation coast guards to enhance maritime capabilities in the region. Launched at QUAD Wilmington Summit (September 2024); first workshop in 2025 assessed regional capability gaps. QUAD members: India, USA, Japan, Australia. QUAD revived 2017; elevated to leaders' level 2021.","folder":"AP_HC","topic":"International_Current_Affairs"},

    # India Bilateral & Others (21057-21062)
    {"id":21057,"question":"India and the UK formally signed the Comprehensive Economic and Trade Agreement (CETA) on which date in 2025?","option_a":"May 6, 2025","option_b":"July 24, 2025","option_c":"September 12, 2025","option_d":"November 15, 2025","correct_answer":"B","explanation":"India-UK CETA signed July 24, 2025. Agreement in principle reached May 6, 2025. Three years of negotiations. Eliminates tariffs on 99% of Indian exports to UK, 90% of UK exports to India. Current bilateral trade: $56 billion; target double by 2030.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21058,"question":"Under India-UK CETA 2025, what happens to UK tariffs on Indian whisky imports?","option_a":"Eliminated immediately to zero","option_b":"Halved from 150% to 75%, then reduced to 40% by year 10","option_c":"Reduced from 100% to 50% in year 5","option_d":"Maintained at current levels for strategic industries","correct_answer":"B","explanation":"India-UK CETA 2025: Whisky/gin tariffs halved from 150% to 75%, then to 40% by year 10 (India's exports). UK exports with reduced tariffs: whisky, medical devices, electrical machinery, aerospace, chocolate, salmon, lamb. UK gets 90% Indian market access; India gets 99% UK duty-free access.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21059,"question":"India-UK CETA 2025 is expected to increase bilateral trade by how much per year from 2040?","option_a":"$10 billion","option_b":"$20 billion","option_c":"$34 billion","option_d":"$56 billion","correct_answer":"C","explanation":"India-UK CETA 2025 projected to increase bilateral trade by $34 billion/year from 2040. Current trade: $56 billion; target to double by 2030. Considered the most significant FTA India has signed since India-UAE CEPA (2022). India also advancing FTAs with EU, GCC, Canada.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21060,"question":"APEC 2025 was held in which South Korean city?","option_a":"Seoul","option_b":"Busan","option_c":"Gyeongju","option_d":"Incheon","correct_answer":"C","explanation":"APEC 2025 was held in Gyeongju, South Korea — historically known as the 'museum without walls' for its Silla dynasty heritage. South Korean President Lee Jae-myung (elected June 3, 2025 after Yoon's impeachment) hosted. APEC host sequence: Lima Peru (2024) → Gyeongju South Korea (2025). APEC: 21 member economies.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21061,"question":"India-China resumed the Kailash Mansarovar Yatra in 2025 — suspended since 2020. The Yatra is a pilgrimage to which sacred site?","option_a":"Mount Kailash in Tibet, China","option_b":"Mansarovar Lake in Nepal","option_c":"Kedarnath in Uttarakhand, India","option_d":"Lhasa in Tibet Autonomous Region","correct_answer":"A","explanation":"Kailash Mansarovar Yatra: Hindu pilgrimage to Mount Kailash (sacred to Hindus, Buddhists, Jains) in Tibet, China. Suspended since 2020 (COVID + Galwan clash). Resumption in 2025 was part of broader India-China normalization including LAC patrolling agreements (Depsang, Demchok resolved 2024).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21062,"question":"EAM Jaishankar met Iranian FM Araghchi in New Delhi on May 15, 2026, during which ongoing international conflict?","option_a":"Russia-Ukraine War","option_b":"Sudan Civil War","option_c":"2026 Iran-US-Israel War","option_d":"India-Pakistan Operation Sindoor aftermath","correct_answer":"C","explanation":"EAM Jaishankar met Iranian FM Araghchi (May 15, 2026) during the 2026 Iran War (US+Israel vs Iran, started Feb 28, 2026). India maintained a neutral position — strategic Chabahar Port interest + diplomatic tradition. Ceasefire was brokered by Pakistan on April 8, 2026; May 7 Israel struck Beirut.","folder":"AP_HC","topic":"International_Current_Affairs"},

    # 2026 Upcoming Events (21063-21066)
    {"id":21063,"question":"India will host the 18th BRICS Summit in 2026. When and where is it scheduled?","option_a":"June 2026, Mumbai","option_b":"September 12-13, 2026, New Delhi","option_c":"October 2026, Hyderabad","option_d":"December 2026, Bengaluru","correct_answer":"B","explanation":"18th BRICS Summit 2026: New Delhi, September 12-13, 2026 — India's BRICS Chairmanship. India's first BRICS summit as chair since expansion to 11 members. India's priorities expected: South-South cooperation, development finance, counterterrorism.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21064,"question":"CHOGM 2026 (Commonwealth Heads of Government Meeting) will be held in which country?","option_a":"Australia","option_b":"Kenya","option_c":"Antigua and Barbuda","option_d":"Canada","correct_answer":"C","explanation":"CHOGM 2026: St. John's, Antigua and Barbuda, November 1-4, 2026. Theme: 'Accelerating Partnerships and Investment for a Prosperous Commonwealth.' Previous CHOGM 2024: Apia, Samoa (first in Pacific island state). Commonwealth Head: King Charles III. Secretariat: Marlborough House, London. 56 member nations.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21065,"question":"Where will the 2026 Asian Games be held?","option_a":"Beijing, China","option_b":"Doha, Qatar","option_c":"Aichi-Nagoya, Japan","option_d":"Seoul, South Korea","correct_answer":"C","explanation":"2026 Asian Games: Aichi-Nagoya, Japan. Other major 2026 sports events: ICC Men's T20 World Cup (India & Sri Lanka), 2026 Commonwealth Games (Glasgow, Scotland), 2026 Summer Youth Olympics (Dakar, Senegal), 2026 FIFA World Cup (USA-Canada-Mexico). India last hosted Asian Games: New Delhi 1982.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21066,"question":"The 2026 FIFA World Cup will be co-hosted by which three countries?","option_a":"USA, Canada, Mexico","option_b":"USA, Brazil, Argentina","option_c":"UK, France, Germany","option_d":"Spain, Portugal, Morocco","correct_answer":"A","explanation":"2026 FIFA World Cup: USA, Canada, Mexico — first World Cup with three host nations. Also the first 48-team World Cup (expanded from 32). 2022 FIFA World Cup was in Qatar (first in Middle East); Argentina won. 2026 will be the first World Cup in North America since USA 1994.","folder":"AP_HC","topic":"International_Current_Affairs"},

    # Mixed / Higher Order (21067-21080)
    {"id":21067,"question":"Which of the following correctly matches the 2025 summit with its HOST city?","option_a":"G20 2025 → Rio de Janeiro","option_b":"NATO 2025 → The Hague","option_c":"SCO 2025 → Astana","option_d":"ASEAN 2025 → Bangkok","correct_answer":"B","explanation":"NATO 2025 → The Hague ✓. Incorrect: G20 2025 → Johannesburg (not Rio; Rio=BRICS 2025), SCO 2025 → Tianjin (not Astana; Astana=SCO 2024), ASEAN 2025 → Kuala Lumpur (not Bangkok). Quick: G20=Johannesburg, G7=Kananaskis, NATO=The Hague, BRICS=Rio, SCO=Tianjin, ASEAN=KL, COP30=Belém.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21068,"question":"Which of the following CORRECTLY matches 2025 summit themes?","option_a":"G20='Collaboration for Intelligent Age'; WEF='Solidarity, Equality, Sustainability'","option_b":"G20='A Spirit of Dialogue'; WEF='Solidarity, Equality, Sustainability'","option_c":"G20='Solidarity, Equality, Sustainability'; WEF='Collaboration for Intelligent Age'","option_d":"G20='Solidarity, Equality, Sustainability'; WEF='A Spirit of Dialogue'","correct_answer":"C","explanation":"G20 SA 2025 theme = 'Solidarity, Equality, Sustainability'. WEF Davos 2025 = 'Collaboration for the Intelligent Age'. WEF Davos 2026 = 'A Spirit of Dialogue'. Commonly confused. Remember: G20 SA = Ubuntu-inspired 'Solidarity, Equality, Sustainability'.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21069,"question":"Which statement about NATO Hague Summit 2025 is INCORRECT?","option_a":"New defense spending target of 5% GDP was agreed","option_b":"Spain was the only dissenter to the 5% target","option_c":"Ukraine was officially invited to join NATO","option_d":"€40 billion in defense aid was pledged to Ukraine","correct_answer":"C","explanation":"Ukraine was NOT invited to join NATO at The Hague 2025 — no invitation, timeline, or upgrade in membership pathway. Correct facts: 5% GDP target agreed (all except Spain), €40 billion Ukraine aid, Article 5 reaffirmed despite earlier Trump doubts. NATO 2026: Ankara, Turkey.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21070,"question":"Which country is BOTH ASEAN's newest member AND BRICS's newest full member?","option_a":"Vietnam","option_b":"Malaysia","option_c":"No such country — they are different nations","option_d":"Indonesia","correct_answer":"C","explanation":"ASEAN's newest member = Timor-Leste (joined October 2025). BRICS's newest full member = Indonesia (joined January 6, 2025). These are DIFFERENT countries. Indonesia is a long-standing ASEAN founding member (1967) who became BRICS's 11th member. Timor-Leste joined ASEAN but is NOT in BRICS.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21071,"question":"The Russia-Ukraine war saw a Trump-brokered ceasefire in May 2026. What was its duration?","option_a":"1 day","option_b":"3 days (May 9-11, 2026)","option_c":"7 days","option_d":"30 days","correct_answer":"B","explanation":"Trump announced a 3-day Russia-Ukraine ceasefire (May 9-11, 2026), described as potentially 'the beginning of the end' of the war. Included exchange of 1,000 prisoners each side. Russia had also declared a unilateral ceasefire (May 8-9) for Victory Day. Both sides traded blame for continued violations.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21072,"question":"India-UK CETA 2025: What percentage of Indian exports to UK will get duty-free access?","option_a":"80%","option_b":"90%","option_c":"95%","option_d":"99%","correct_answer":"D","explanation":"Under India-UK CETA 2025, 99% of Indian exports to UK get duty-free access (covering ~100% of trade value). UK exports: 90% get reduced/eliminated tariffs. India's major export gains: textiles, garments, footwear, seafood, engineering goods. CETA ratification expected to come into force May 2026.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21073,"question":"After 2025 expansions, how many total nations (full members + partner countries) does BRICS represent?","option_a":"15","option_b":"18","option_c":"21","option_d":"24","correct_answer":"C","explanation":"BRICS after 2025: 11 full members + 10 partner countries = 21 nations. Full members: original 5 + Egypt, Ethiopia, Iran, UAE, Saudi Arabia, Indonesia. Partners (Rio 2025): Belarus, Bolivia, Kazakhstan, Cuba, Malaysia, Nigeria, Thailand, Uganda, Uzbekistan, Vietnam. Collective GDP (PPP): ~37% of world total.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21074,"question":"SCO was founded in which year and city?","option_a":"1996, Almaty","option_b":"2001, Shanghai","option_c":"2005, Beijing","option_d":"1997, Moscow","correct_answer":"B","explanation":"SCO (Shanghai Cooperation Organisation) founded June 15, 2001 in Shanghai — hence the name. Evolved from 'Shanghai Five' (1996: China, Russia, Kazakhstan, Kyrgyzstan, Tajikistan) when Uzbekistan joined in 2001. SCO Secretariat HQ: Beijing. India and Pakistan joined 2017. Currently 10 full members.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21075,"question":"Which countries called the COP29 NCQG of $300 billion/year 'paltry and inadequate'?","option_a":"USA and EU","option_b":"China and Russia","option_c":"India and other developing nations","option_d":"Saudi Arabia and OPEC nations","correct_answer":"C","explanation":"India and other developing nations called the COP29 Baku NCQG of $300 billion/year 'paltry' — they had demanded $1.3 trillion. COP30 Belém 2025 effectively adopted $1.3T as the new target — a major victory for the Global South. India argues for equity-based 'Common But Differentiated Responsibilities' (CBDR) in climate finance.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21076,"question":"Which summit in 2025 involved a formal chairmanship handover at its closing ceremony to a new host?","option_a":"G20 (South Africa → USA)","option_b":"ASEAN (Malaysia → Philippines)","option_c":"SCO (China → Kazakhstan)","option_d":"BRICS (Brazil → India)","correct_answer":"B","explanation":"ASEAN KL 2025: Malaysia formally handed ASEAN Chairmanship to Philippines at the closing of the 47th Summit. Note: G20 chairmanship transfer (South Africa → USA) happened January 12, 2026 — not at the summit itself. BRICS Chairmanship (Brazil → India for 2026) was also a formal transfer.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21077,"question":"The 2026 Commonwealth Games will be held in which city?","option_a":"Brisbane, Australia","option_b":"Dublin, Ireland","option_c":"Glasgow, Scotland","option_d":"Durban, South Africa","correct_answer":"C","explanation":"2026 Commonwealth Games: Glasgow, Scotland. Glasgow previously hosted 2014 Commonwealth Games. 2022 Commonwealth Games: Birmingham, UK. India hosted: New Delhi 2010. Scotland/Glasgow hosting again makes it a rare repeated Commonwealth Games host city.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21078,"question":"G7 Kananaskis 2025 was the 51st G7 Summit. Which of the following is the correct list of G7 nations?","option_a":"USA, UK, France, Germany, Italy, Japan, Canada","option_b":"USA, UK, France, Germany, Italy, Japan, Australia","option_c":"USA, UK, France, Germany, Italy, Spain, Canada","option_d":"USA, UK, France, Germany, Russia, Japan, Canada","correct_answer":"A","explanation":"G7 members: USA, UK, France, Germany, Italy, Japan, Canada + EU (as special member). Australia and Spain are NOT G7. Russia was suspended from G8 in 2014 (Crimea annexation). At Kananaskis 2025, PM Mark Carney hosted; Trump left early citing Israel-Iran conflict.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21079,"question":"BRICS Rio 2025 highlighted de-dollarisation debates. The original BRIC concept was proposed in which year by Goldman Sachs economist Jim O'Neill?","option_a":"1999","option_b":"2001","option_c":"2003","option_d":"2005","correct_answer":"B","explanation":"Goldman Sachs economist Jim O'Neill coined 'BRIC' (Brazil, Russia, India, China) in 2001 — predicting these four emerging economies would dominate global growth by 2050. The BRIC grouping first met formally in 2009; South Africa joined in 2010 (making it BRICS). De-dollarisation: BRICS exploring alternatives to USD for trade.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":21080,"question":"ASEAN's newest member Timor-Leste (joined 2025) gained independence from which country in 2002? [2025-2026 Rewrite v2]","option_a":"Portugal","option_b":"Australia","option_c":"Indonesia","option_d":"Netherlands","correct_answer":"C","explanation":"Timor-Leste (East Timor) gained independence from Indonesia on May 20, 2002. Former Portuguese colony (Portuguese is official language) occupied by Indonesia 1975-1999. After UN referendum (1999) and transitional period, became independent in 2002. Applied for ASEAN 2011; admitted October 2025 as 11th member.","folder":"AP_HC","topic":"International_Current_Affairs"},
]


def seed():
    if USE_POSTGRES:
        import psycopg2, psycopg2.extras
        conn = psycopg2.connect(DATABASE_URL)
        conn.autocommit = False
        cur = conn.cursor()
        ph = "%s"
        delete_sql = "DELETE FROM questions WHERE id >= %s AND id <= %s"
        insert_sql = """
            INSERT INTO questions
              (id, question_text, option_a, option_b, option_c, option_d,
               correct_answer, explanation, folder, topic)
            VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
            ON CONFLICT (id) DO NOTHING
        """
    else:
        conn = sqlite3.connect(
            os.path.join(os.path.dirname(__file__), "database.db")
        )
        cur = conn.cursor()
        ph = "?"
        delete_sql = "DELETE FROM questions WHERE id >= ? AND id <= ?"
        insert_sql = """
            INSERT OR IGNORE INTO questions
              (id, question_text, option_a, option_b, option_c, option_d,
               correct_answer, explanation, folder, topic)
            VALUES (?,?,?,?,?,?,?,?,?,?)
        """

    # Force-refresh: delete old stale 2024 data
    cur.execute(delete_sql, (21001, 21080))

    for q in SUMMIT_MCQS:
        cur.execute(insert_sql, (
            q["id"], q["question"],
            q["option_a"], q["option_b"], q["option_c"], q["option_d"],
            q["correct_answer"], q["explanation"],
            q["folder"], q["topic"],
        ))

    conn.commit()
    conn.close()
    print(f"[seed_summits_mcq] {len(SUMMIT_MCQS)} Summits 2025-2026 MCQs seeded (IDs 21001-21080).")


if __name__ == "__main__":
    seed()
