# seed_polity_ch24.py
# Chapter 24 — Panchayati Raj (73rd Amendment)
# (పంచాయతీ రాజ్ — 73వ సవరణ)
# Total Sections: 8 | Total MCQs: 64
# Sections:
#   0 — Historical Background & Committees (8 MCQs)
#   1 — 73rd Amendment & Art.243 (8 MCQs)
#   2 — Structure — Three-Tier System (8 MCQs)
#   3 — Gram Sabha (8 MCQs)
#   4 — Elections & Reservations (8 MCQs)
#   5 — State Finance & Election Commissions (8 MCQs)
#   6 — 11th Schedule — 29 Subjects (8 MCQs)
#   7 — Miscellaneous — Key Facts (8 MCQs)

_CH = 24
_SUBJECT = 'GK'
_TOPIC   = 'Indian_Polity'
_TITLE_TE = 'పంచాయతీ రాజ్ — 73వ సవరణ'
_TITLE_EN = 'Panchayati Raj — 73rd Amendment'
_PAGES    = 'Ch.24 (Lakshmikanth)'

_SECTIONS = [
    "చారిత్రక నేపథ్యం & కమిటీలు",
    "73వ సవరణ & అనుచ్ఛేదం 243",
    "మూడు అంచెల నిర్మాణం",
    "గ్రామసభ",
    "ఎన్నికలు & రిజర్వేషన్లు",
    "రాష్ట్ర ఆర్థిక & ఎన్నికల కమిషన్లు",
    "11వ షెడ్యూల్ — 29 అంశాలు",
    "విభిన్న కీలక అంశాలు",
]

_MCQS = [    (0,
     'easy',
     'Which committee first recommended Panchayati Raj?\nతెలుగు: పంచాయతీ రాజ్ వ్యవస్థను సిఫారసు చేసిన మొదటి కమిటీ ఏది?',
     'Ashok Mehta Committee / అశోక్ మెహతా కమిటీ',
     'Balwant Rai Mehta Committee / బల్వంత్\u200cరాయ్ మెహతా కమిటీ',
     'L.M. Singhvi Committee / L.M. సింఘ్వి కమిటీ',
     'Gadgil Committee / గాడ్గిల్ కమిటీ',
     'b',
     'Balwant Rai Mehta Committee (1957) recommended 3-tier PR. First implemented in Rajasthan in 1959. / బల్వంత్\u200cరాయ్ మెహతా కమిటీ (1957) మూడు అంచెల పంచాయతీ రాజ్ వ్యవస్థను సిఫారసు చేసింది. దాని సిఫారసు ఆధారంగా 1959లో రాజస్థాన్\u200cలో మొదట అమలైంది.'),
    (0,
     'easy',
     'Which state first introduced Panchayati Raj?\nతెలుగు: పంచాయతీ రాజ్\u200cని మొదటగా ఏ రాష్ట్రం ప్రవేశపెట్టింది?',
     'Maharashtra / మహారాష్ట్ర',
     'Kerala / కేరళ',
     'Rajasthan / రాజస్థాన్',
     'Andhra Pradesh / ఆంధ్రప్రదేశ్',
     'c',
     'Rajasthan first implemented PR on October 2, 1959 in Nagaur district. AP was second (November 1959). / రాజస్థాన్ 1959 అక్టోబర్ 2న నాగౌర్ జిల్లాలో మొదట పంచాయతీ రాజ్ అమలు చేసింది. ఆంధ్రప్రదేశ్ రెండో రాష్ట్రం (1959 నవంబర్).'),
    (0,
     'medium',
     'What did the Ashok Mehta Committee (1977) recommend?\nతెలుగు: అశోక్ మెహతా కమిటీ (1977) ఏమి సిఫారసు చేసింది?',
     'Three-tier system / మూడు అంచెల వ్యవస్థ',
     'Two-tier system / రెండు అంచెల వ్యవస్థ (District + Mandal)',
     'Four-tier system / నాలుగు అంచెల వ్యవస్థ',
     'Single tier / ఒక అంచె వ్యవస్థ',
     'b',
     "Ashok Mehta Committee (1977) recommended 2 tiers: District Panchayat + Mandal Panchayat (vs Balwant Rai's 3 tiers). / అశోక్ మెహతా కమిటీ (1977) రెండు అంచెల వ్యవస్థ సిఫారసు చేసింది: (1) జిల్లా పరిషత్ మరియు (2) మండల పంచాయత్. బల్వంత్\u200cరాయ్ మెహతా మూడు అంచెలు సిఫారసు చేశారు."),
    (0,
     'medium',
     'What did L.M. Singhvi Committee (1986) recommend?\nతెలుగు: L.M. సింఘ్వి కమిటీ (1986) ఏమి సిఫారసు చేసింది?',
     'Abolition of PR / పంచాయతీ రాజ్ రద్దు',
     'Constitutional status to Panchayati Raj / పంచాయతీ రాజ్\u200cకి రాజ్యాంగ హోదా కల్పించాలి',
     'Central control over PR / పంచాయతీ రాజ్\u200cని కేంద్ర నియంత్రణలో పెట్టాలి',
     'Police powers to Panchayats / పంచాయతీలకు పోలీస్ అధికారాలు ఇవ్వాలి',
     'b',
     'L.M. Singhvi Committee (1986) recommended constitutional status to PR — leading to the 73rd Amendment. / L.M. సింఘ్వి కమిటీ (1986) పంచాయతీ రాజ్\u200cకి రాజ్యాంగ హోదా ఇవ్వాలని సిఫారసు చేసింది — ఇది 73వ సవరణకు దారి తీసింది.'),
    (0,
     'medium',
     'In which year was the 73rd Constitutional Amendment Act passed?\nతెలుగు: 73వ రాజ్యాంగ సవరణ చట్టం ఏ సంవత్సరంలో ఆమోదించబడింది?',
     '1990',
     '1991',
     '1992',
     '1993',
     'c',
     '73rd Amendment passed in 1992; came into force on April 24, 1993. / 73వ రాజ్యాంగ సవరణ 1992లో పార్లమెంటు ఆమోదించింది; 24 ఏప్రిల్ 1993 నుండి అమలులోకి వచ్చింది.'),
    (0,
     'medium',
     'In which DPSP Article is PR mentioned?\nతెలుగు: Panchayati Raj వ్యవస్థ DPSP లో ఏ అనుచ్ఛేదంలో ప్రస్తావించబడింది?',
     'Art.40 / అనుచ్ఛేదం 40',
     'Art.43 / అనుచ్ఛేదం 43',
     'Art.45 / అనుచ్ఛేదం 45',
     'Art.48 / అనుచ్ఛేదం 48',
     'a',
     "Art.40 (DPSP): State shall organise village panchayats with powers and authority for self-governance. / అనుచ్ఛేదం 40 (DPSP): 'రాష్ట్రం గ్రామ పంచాయతీలను నిర్వహించడానికి చర్యలు తీసుకుంటుంది' — స్వయం పాలనకు అవసరమైన అధికారాలు వ్యవస్థ కల్పిస్తుంది."),
    (0,
     'hard',
     'GVK Rao Committee (1985) was related to?\nతెలుగు: జి.వి.కె. రావు కమిటీ (1985) దేనికి సంబంధించినది?',
     'Urban local bodies / పట్టణ స్థానిక సంస్థలు',
     'Development programmes and PR role / అభివృద్ధి కార్యక్రమాలు & పంచాయతీ పాత్ర',
     'Zonal Councils / జోనల్ కౌన్సిళ్లు',
     'Planning system / ప్రణాళికా వ్యవస్థ',
     'b',
     'GVK Rao Committee (1985) studied role of PRIs in development programmes. / GVK Rao Committee (1985) జిల్లా స్థాయి అభివృద్ధి ప్రణాళికలో పంచాయతీ పాత్రపై నివేదిక ఇచ్చింది.'),
    (0,
     'hard',
     'Before 73rd Amendment, PR was in which schedule/list?\nతెలుగు: 73వ సవరణకు ముందు పంచాయతీ రాజ్ ఏ జాబితాలో ఉండేది?',
     'Union List / కేంద్ర జాబితా',
     'Concurrent List / ఉభయ జాబితా',
     'State List / రాష్ట్ర జాబితా',
     'Not mentioned in constitution / రాజ్యాంగంలో ప్రస్తావన లేదు',
     'c',
     'Before 73rd Amendment, PR was in State List (7th Sch, List II, Entry 5) and was optional for states. / 73వ సవరణకు ముందు పంచాయతీ రాజ్ 7వ షెడ్యూల్ List II (State List) లో Entry 5 కింద ఉండేది. రాష్ట్రాలు ఐచ్ఛికంగా పంచాయతీలు ఏర్పాటు చేసేవి.'),
    (1,
     'easy',
     '73rd Amendment added which Articles?\nతెలుగు: 73వ సవరణ ఏ అనుచ్ఛేదాలను రాజ్యాంగంలో చేర్చింది?',
     'అను.243–243O',
     'అను.243A–243ZG',
     'అను.243–243ZG',
     'అను.243P–243ZG',
     'a',
     '73rd Amendment added Part IX with Arts 243 to 243O (15 Articles) and the 11th Schedule. / 73వ సవరణ Part IX ని చేర్చింది — అనుచ్ఛేదం 243 నుండి 243O వరకు (15 అనుచ్ఛేదాలు). 11వ షెడ్యూల్ కూడా జోడించబడింది.'),
    (1,
     'easy',
     '73rd Amendment added which schedule?\nతెలుగు: 73వ సవరణ ఏ షెడ్యూల్ జోడించింది?',
     '9th Schedule / 9వ షెడ్యూల్',
     '10th Schedule / 10వ షెడ్యూల్',
     '11th Schedule / 11వ షెడ్యూల్',
     '12th Schedule / 12వ షెడ్యూల్',
     'c',
     '73rd Amendment added the 11th Schedule with 29 subjects to be devolved to PR bodies. / 73వ సవరణ 11వ షెడ్యూల్ (29 విషయాలు) జోడించింది — పంచాయతీ రాజ్ సంస్థలకు బదిలీ చేయబడే విషయాలు.'),
    (1,
     'medium',
     'What does Art.243B provide?\nతెలుగు: అనుచ్ఛేదం 243B ఏమి నిర్దేశిస్తుంది?',
     'Gram Sabha / గ్రామ సభ',
     'Three-tier Panchayat structure / మూడు అంచెల పంచాయతీ నిర్మాణం',
     'State Finance Commission',
     'State Election Commission',
     'b',
     'Art.243B: Three-tier PR structure mandatory (middle tier optional for states with pop. below 20 lakhs). / అనుచ్ఛేదం 243B: ప్రతి రాష్ట్రంలో మూడు అంచెల పంచాయతీ రాజ్ నిర్మాణం నిర్దేశిస్తుంది. (జనాభా 20 లక్షల కంటే తక్కువ ఉంటే మధ్య అంచె తప్పనిసరి కాదు.)'),
    (1,
     'medium',
     'What does Art.243A provide?\nతెలుగు: అనుచ్ఛేదం 243A ఏమిని నిర్దేశిస్తుంది?',
     'Panchayat elections / పంచాయతీ ఎన్నికలు',
     'Gram Sabha / గ్రామ సభ',
     'Zila Parishad / జిల్లా పరిషత్',
     'State Finance Commission / రాష్ట్ర ఆర్థిక కమిషన్',
     'b',
     'Art.243A: Gram Sabha — body of all voters enrolled in the electoral roll of a village. / అనుచ్ఛేదం 243A: గ్రామ సభ నిర్వచనం — గ్రామ స్థాయి పంచాయతీ ఓటర్ల జాబితాలో నమోదైన వ్యక్తులందరూ.'),
    (1,
     'medium',
     'Tenure of Panchayat fixed by 73rd Amendment?\nతెలుగు: 73వ సవరణ పంచాయతీలకు ఎన్నికల పదవీకాలం ఎంత నిర్దేశించింది?',
     '3 years / 3 సంవత్సరాలు',
     '4 years / 4 సంవత్సరాలు',
     '5 years / 5 సంవత్సరాలు',
     '6 years / 6 సంవత్సరాలు',
     'c',
     'Art.243E: PR tenure = 5 years. If dissolved, fresh elections must be held within 6 months. / అనుచ్ఛేదం 243E: పంచాయతీ పదవీకాలం 5 సంవత్సరాలు. రద్దయిన పంచాయతీకి 6 నెలల్లోపు ఎన్నికలు జరగాలి.'),
    (1,
     'hard',
     'Which states were exempted from 73rd Amendment?\nతెలుగు: 73వ సవరణ అమలు నుండి ఏ రాష్ట్రాలను మినహాయించింది?',
     'J&K and Nagaland / జమ్మూ & కాశ్మీర్ మరియు నాగాల్యాండ్',
     'Nagaland, Meghalaya, Mizoram (5th & 6th Schedule areas) / నాగాల్యాండ్, మేఘాలయ, మిజోరాం (5వ & 6వ షెడ్యూల్ ప్రాంతాలు)',
     'Tamil Nadu, Kerala / తమిళనాడు, కేరళ',
     'J&K and Himachal Pradesh / జమ్మూ & కాశ్మీర్, హిమాచల్ ప్రదేశ్',
     'b',
     '73rd Amendment does not apply to 5th & 6th Schedule tribal areas, Nagaland, Meghalaya, Mizoram. PESA 1996 extended PR to 5th Schedule areas. / 73వ సవరణ 5వ & 6వ షెడ్యూల్ ప్రాంతాలు (tribal areas), Nagaland, Meghalaya, Mizoram కి వర్తించదు. PESA (1996) 5వ షెడ్యూల్ ప్రాంతాలకు PR వర్తింపు చేసింది.'),
    (1,
     'hard',
     'What is PESA and when was it passed?\nతెలుగు: PESA అంటే ఏమిటి మరియు ఏ సంవత్సరంలో ఆమోదించబడింది?',
     'Panchayat Extension to Scheduled Areas Act, 1996',
     'Panchayat Establishment and Special Act, 1994',
     'Public Expenditure Special Act, 1998',
     'Panchayat Empowerment Special Act, 2001',
     'a',
     'PESA 1996 extended Panchayati Raj provisions to Fifth Schedule (tribal) areas. / PESA = Provisions of the Panchayats (Extension to the Scheduled Areas) Act, 1996 — 5వ షెడ్యూల్ ప్రాంతాలలో PR అమలు కోసం.'),
    (1,
     'hard',
     'How many Articles in Part IX added by 73rd Amendment?\nతెలుగు: 73వ సవరణ ద్వారా జోడించబడిన Part IX లో ఎన్ని అనుచ్ఛేదాలు ఉన్నాయి?',
     '11',
     '13',
     '16',
     '20',
     'c',
     'Part IX: Art.243 (definitions) + Arts 243A to 243O = 16 Articles total. / Part IX లో అనుచ్ఛేదం 243 (నిర్వచనాలు) + 243A నుండి 243O = మొత్తం 16 అనుచ్ఛేదాలు.'),
    (2,
     'easy',
     'What are the three tiers of Panchayati Raj?\nతెలుగు: పంచాయతీ రాజ్ మూడు అంచెలు ఏవి?',
     'Mandal, Taluka, District / మండల్, తాలూకా, జిల్లా',
     'Gram Panchayat, Panchayat Samiti, Zila Parishad / గ్రామ పంచాయత్, పంచాయత్ సమితి, జిల్లా పరిషత్',
     'Village, Town, State / పల్లె, నగర్, రాజ్',
     'Ward, Mandal, District / వార్డ్, మండల్, జిల్లా',
     'b',
     'Three tiers: Village (Gram Panchayat), Intermediate (Panchayat Samiti), District (Zila Parishad). / పంచాయతీ రాజ్ మూడు అంచెలు: (1) గ్రామ స్థాయి — గ్రామ పంచాయత్, (2) మధ్య స్థాయి — పంచాయత్ సమితి/మండల్ పరిషత్, (3) జిల్లా స్థాయి — జిల్లా పరిషత్.'),
    (2,
     'easy',
     'What is the head of Gram Panchayat called?\nతెలుగు: గ్రామ పంచాయత్ అధ్యక్షుని పేరు ఏమిటి?',
     'Sarpanch / సర్పంచ్',
     'Chief Minister / ముఖ్యమంత్రి',
     'President / అధ్యక్షుడు',
     'Pradhan / ప్రధాన్',
     'a',
     'Head of Gram Panchayat = Sarpanch. Different states use different names: Pradhan (UP), Mukhiya (Bihar), etc. / గ్రామ పంచాయత్ అధ్యక్షుడు = సర్పంచ్. వివిధ రాష్ట్రాలలో వేరే పేర్లు వాడతారు — ప్రధాన్ (UP), ముఖియా (Bihar) మొ.'),
    (2,
     'medium',
     'What is the head of Zila Parishad called?\nతెలుగు: జిల్లా పరిషత్ అధ్యక్షుని పేరు ఏమిటి?',
     'Sarpanch / సర్పంచ్',
     'Adhyaksha / అధ్యక్షుడు',
     'Chief Minister / ముఖ్యమంత్రి',
     'District Collector / జిల్లా కలెక్టర్',
     'b',
     'Zila Pramukh). వివిధ రాష్ట్రాలలో పేర్లు వేరుగా ఉంటాయి. / Head of Zila Parishad = Adhyaksha or Zila Pramukh (varies by state). / జిల్లా పరిషత్ అధ్యక్షుడు = అధ్యక్షుడు (Adhyaksha'),
    (2,
     'medium',
     'States where intermediate tier is NOT compulsory?\nతెలుగు: మధ్య అంచె (Intermediate tier) తప్పనిసరి కాని రాష్ట్రాలు ఏవి?',
     'States with population ≤ 20 lakhs / జనాభా 20 లక్షలు లేదా అంతకన్నా తక్కువ ఉన్న రాష్ట్రాలు',
     'States with population ≤ 50 lakhs / జనాభా 50 లక్షలు లేదా అంతకన్నా తక్కువ ఉన్న రాష్ట్రాలు',
     'All states must have 3 tiers / అన్ని రాష్ట్రాలకూ మూడు అంచెలు తప్పనిసరి',
     'Only hilly states / కేవలం పర్వత రాష్ట్రాలు',
     'a',
     'Art.243B: Intermediate tier is optional for states with population below 20 lakhs. / అనుచ్ఛేదం 243B: జనాభా 20 లక్షలు (2 million) కంటే తక్కువ ఉన్న రాష్ట్రాలకు మధ్య అంచె (intermediate tier) తప్పనిసరి కాదు.'),
    (2,
     'medium',
     'Panchayat Samiti is also known as?\nతెలుగు: పంచాయత్ సమితి మరొక పేరు ఏమిటి?',
     'Zila Parishad / జిల్లా పరిషత్',
     'Block Panchayat / బ్లాక్ పంచాయత్',
     'Gram Panchayat / గ్రామ పంచాయత్',
     'Municipal Corporation / నగరపాలక సంస్థ',
     'b',
     'Panchayat Samiti = Block Panchayat (intermediate tier). Different names: Mandal Panchayat (Karnataka), Panchayat Union (TN), etc. / పంచాయత్ సమితి = Block Panchayat (మధ్య అంచె). వేరే రాష్ట్రాలలో: Mandal Panchayat (Karnataka), Panchayat Union (TN), Kshetra Panchayat (UP).'),
    (2,
     'hard',
     "Entry in State List relating to Panchayats?\nతెలుగు: పంచాయతీలకు సంబంధించి 'State List Entry' ఏది?",
     'Entry 3',
     'Entry 5',
     'Entry 7',
     'Entry 12',
     'b',
     "State List Entry 5 covers local self-government including PR bodies. / రాష్ట్ర జాబితా Entry 5: 'Local self-government, that is to say, the constitution and powers of municipal corporations, improvement trusts, districts boards, mining settlement authorities and other local authorities for the purpose of local self-government or village administration.'"),
    (2,
     'hard',
     'Which Article relates to District Planning Committees?\nతెలుగు: జిల్లా స్థాయి పంచాయతీ ప్రణాళికకు ఏ అనుచ్ఛేదం నిర్దేశిస్తుంది?',
     'Art.243ZD / అనుచ్ఛేదం 243ZD',
     'Art.243ZE / అనుచ్ఛేదం 243ZE',
     'Art.243I / అనుచ్ఛేదం 243I',
     'Art.243G / అనుచ్ఛేదం 243G',
     'a',
     'Art.243ZD: District Planning Committee — coordinates PR + ULB plans at district level (added by 74th Amendment). / అనుచ్ఛేదం 243ZD: District Planning Committee (DPC) — జిల్లా స్థాయి PR + ULB ప్రణాళికలు సమన్వయం. (74వ సవరణ ద్వారా జోడించబడింది.)'),
    (2,
     'hard',
     'Which Article enables financial autonomy for PRIs?\nతెలుగు: పంచాయతీ రాజ్ సంస్థల ఆర్థిక స్వయంప్రతిపత్తికి ఏ అనుచ్ఛేదం అవకాశం ఇస్తుంది?',
     'Art.243G / అనుచ్ఛేదం 243G',
     'Art.243H / అనుచ్ఛేదం 243H',
     'Art.243I / అనుచ్ఛేదం 243I',
     'Art.243J / అనుచ్ఛేదం 243J',
     'b',
     'Art.243H: State legislature may authorise panchayats to levy, collect and appropriate taxes, duties etc. / అనుచ్ఛేదం 243H: రాష్ట్ర శాసనమండలి పంచాయతీలకు పన్నులు వసూలు చేసే అధికారం ఇవ్వగలదు.'),
    (3,
     'easy',
     'What is Gram Sabha?\nతెలుగు: గ్రామ సభ (Gram Sabha) నిర్వచనం ఏమిటి?',
     'Members of Gram Panchayat / గ్రామ పంచాయత్ సభ్యులు',
     'Persons enrolled in electoral roll of a village / గ్రామ స్థాయి ఓటర్ల జాబితాలో నమోదైన వ్యక్తులు',
     'Assembly of village elders / గ్రామ పెద్దల సంఘం',
     'Committee appointed by Sarpanch / సర్పంచ్ నియమించిన కమిటీ',
     'b',
     'Art.243A: Gram Sabha = all persons enrolled in the electoral roll of a village-level panchayat. It is the foundation of PR democracy. / అనుచ్ఛేదం 243A: గ్రామ సభ = గ్రామ స్థాయి పంచాయతీ ఓటర్ల జాబితాలో నమోదైన వ్యక్తులందరూ. ఇది ప్రాథమిక ప్రజాస్వామ్య సంస్థ.'),
    (3,
     'easy',
     'At what level does Gram Sabha function?\nతెలుగు: గ్రామ సభ ఏ స్థాయిలో పని చేస్తుంది?',
     'District level / జిల్లా స్థాయి',
     'Block level / బ్లాక్ స్థాయి',
     'Village level / గ్రామ స్థాయి',
     'State level / రాష్ట్ర స్థాయి',
     'c',
     'Gram Sabha works at village level — it monitors Gram Panchayat performance, approves annual budget etc. / గ్రామ సభ గ్రామ స్థాయిలో పని చేస్తుంది — ఇది గ్రామ పంచాయత్ పనితీరు పర్యవేక్షిస్తుంది, వార్షిక బడ్జెట్ ఆమోదిస్తుంది.'),
    (3,
     'medium',
     'What is the significance of Gram Sabha?\nతెలుగు: గ్రామ సభ ప్రాముఖ్యత ఏమిటి?',
     'It directly elects the Sarpanch / ఇది సర్పంచ్\u200cని నేరుగా ఎన్నుకుంటుంది',
     'It is an instrument of direct democracy — people directly participate in development / ఇది ప్రత్యక్ష ప్రజాస్వామ్యం యొక్క సాధనం — ప్రజలు నేరుగా అభివృద్ధి కార్యక్రమాలలో పాల్గొంటారు',
     'It appoints members to government jobs / ఇది తన సభ్యులను ప్రభుత్వ ఉద్యోగాలకు నియమిస్తుంది',
     'It has police powers / ఇది తన పరిధిలో పోలీస్ అధికారాలు కలిగి ఉంటుంది',
     'b',
     'Gram Sabha embodies direct democracy — people directly deliberate on panchayat budgets, development schemes, and beneficiary selection. / గ్రామ సభ ప్రత్యక్ష ప్రజాస్వామ్యానికి ప్రతీక — పంచాయత్ అభివృద్ధి కార్యక్రమాలు, బడ్జెట్, లబ్ధిదారుల ఎంపిక పై ప్రజలు నేరుగా నిర్ణయం తీసుకుంటారు.'),
    (3,
     'medium',
     'Who maintains Gram Sabha records?\nతెలుగు: గ్రామ సభ రికార్డులు ఎవరు నిర్వహిస్తారు?',
     'District Collector / జిల్లా కలెక్టర్',
     'Panchayat Secretary / పంచాయత్ కార్యదర్శి',
     'Sarpanch / సర్పంచ్',
     'BDO (Block Development Officer)',
     'b',
     'Panchayat Secretary maintains records of Gram Sabha meetings. / పంచాయత్ కార్యదర్శి (Secretary) గ్రామ సభ సమావేశాల నమోదు, రికార్డులు నిర్వహిస్తారు.'),
    (3,
     'medium',
     'Under PESA 1996, what additional powers do Gram Sabhas have in 5th Schedule areas?\nతెలుగు: PESA 1996 ప్రకారం గ్రామ సభకు 5వ షెడ్యూల్ ప్రాంతాలలో ఏ అదనపు అధికారాలు ఉన్నాయి?',
     'Right to stop land acquisition / భూమి కొనుగోలు ఆపే హక్కు',
     'Control over natural resources, minor water bodies, and tribal development plans / సంప్రదాయ వనరులు, సూక్ష్మ మైనర్ నీటి వనరులు, గిరిజన ప్రణాళికలపై నియంత్రణ',
     'Special military powers / ప్రత్యేక సైనిక అధికారాలు',
     'Power to direct state legislature / రాష్ట్ర శాసనమండలికి చట్టాలు చేయమని ఆదేశించే హక్కు',
     'b',
     'Under PESA 1996, Gram Sabhas in 5th Schedule areas manage natural resources, minor water bodies, traditional laws, and approve tribal development plans. / PESA 1996 ప్రకారం 5వ షెడ్యూల్ ప్రాంతాల గ్రామ సభలకు: సంప్రదాయ వనరులు, నీటి వనరులు, సంప్రదాయ చట్టాలు, గిరిజన అభివృద్ధి ప్రణాళికలపై నియంత్రణ అధికారాలు ఉన్నాయి.'),
    (3,
     'hard',
     '73rd Amendment gave states discretion in?\nతెలుగు: 73వ సవరణ రాష్ట్రాలకు ఏ విషయంలో స్వేచ్ఛ ఇచ్చింది?',
     'Organisation of Gram Sabha / గ్రామ సభ నిర్వహణ',
     'All Panchayat functions / అన్ని పంచాయతీ విధులు',
     'Transfer of 29 subjects in 11th Schedule — not mandatory / 11వ షెడ్యూల్ 29 విషయాల బదిలీ — తప్పనిసరి కాదు',
     'Panchayat elections / పంచాయతీ ఎన్నిక నిర్వహణ',
     'c',
     "Transfer of 29 subjects (11th Schedule) is at states' discretion — NOT mandatory. States may devolve functions as they choose. / 11వ షెడ్యూల్ 29 విషయాల బదిలీ రాష్ట్ర విచక్షణపై ఆధారపడి ఉంది — తప్పనిసరి కాదు. రాష్ట్రాలు తమ ఇష్టం వచ్చినట్లు పంచాయతీలకు విధులు అప్పగించవచ్చు."),
    (3,
     'hard',
     'Minimum number of Gram Sabha meetings per year?\nతెలుగు: గ్రామ సభ సంవత్సరానికి కనీసం ఎన్నిసార్లు సమావేశమవ్వాలి?',
     '1',
     '2',
     '4',
     '6',
     'b',
     'Most state laws require Gram Sabha to meet at least twice a year. Some states mandate 4 meetings. / చాలా రాష్ట్రాల చట్టాల ప్రకారం గ్రామ సభ సంవత్సరానికి కనీసం 2 సార్లు సమావేశం అవ్వాలి. కొన్ని రాష్ట్రాలు 4 సార్లు నిర్దేశిస్తున్నాయి.'),
    (3,
     'hard',
     'What is Gram Kacheri?\nతెలుగు: గ్రామ కచేరీ (Gram Kacheri) అంటే ఏమిటి?',
     'Another name for Gram Sabha / Gram Sabha యొక్క మరో పేరు',
     'Village-level justice system in Andhra Pradesh / ఆంధ్రప్రదేశ్\u200cలో గ్రామ స్థాయి న్యాయ పంచాయతి',
     'Panchayat office / పంచాయత్ కార్యాలయం',
     'Panchayat meeting place / పంచాయత్ సమావేశ స్థలం',
     'b',
     'Gram Kacheri (AP) = village-level justice (Nyaya Panchayat). They settle minor civil and criminal disputes. / గ్రామ కచేరీ (ఆంధ్రప్రదేశ్) = గ్రామ స్థాయి న్యాయ పంచాయతి. న్యాయ పంచాయతులు చిన్న సివిల్ మరియు క్రిమినల్ వివాదాలు పరిష్కరిస్తాయి.'),
    (4,
     'easy',
     'PR elections are conducted under superintendence of?\nతెలుగు: పంచాయతీ ఎన్నికలు ఎవరి పర్యవేక్షణలో జరుగుతాయి?',
     'Central Election Commission / కేంద్ర ఎన్నికల సంఘం',
     'State Election Commission / రాష్ట్ర ఎన్నికల సంఘం',
     'State Government / రాష్ట్ర ప్రభుత్వం',
     'District Collector / జిల్లా కలెక్టర్',
     'b',
     'Art.243K: State Election Commission superintends PR elections. SEC Commissioner is appointed by Governor. / అనుచ్ఛేదం 243K: రాష్ట్ర ఎన్నికల సంఘం (State Election Commission) పంచాయతీ ఎన్నికలు పర్యవేక్షిస్తుంది. SEC = రాష్ట్ర ఎన్నికల కమిషనర్ — Governor నియమిస్తారు.'),
    (4,
     'easy',
     'How are seats reserved for SC/ST in PR bodies?\nతెలుగు: SC/ST కి పంచాయతీ స్థానాలలో రిజర్వేషన్ ఎలా నిర్ణయిస్తారు?',
     'Fixed at 33% / నిర్ణీత 33%',
     'In proportion to population / జనాభా నిష్పత్తిలో',
     "At state government's discretion / రాష్ట్ర ప్రభుత్వం ఇష్టం వచ్చినట్లు",
     'Decided by Central Government / కేంద్ర ప్రభుత్వం నిర్ణయిస్తుంది',
     'b',
     'Art.243D: SC/ST seats reserved in proportion to population. Women: at least 1/3 seats (some states have 50%). / అనుచ్ఛేదం 243D: SC/ST రిజర్వేషన్ = జనాభా నిష్పత్తిలో. మహిళలకు కనీసం 1/3 స్థానాలు (కొన్ని రాష్ట్రాలు 50%).'),
    (4,
     'medium',
     'Minimum percentage of seats reserved for women in PR?\nతెలుగు: పంచాయతీ ఎన్నికలలో మహిళలకు కనీసం ఎంత శాతం స్థానాలు రిజర్వు చేయబడ్డాయి?',
     '20%',
     '25%',
     '33.33% (1/3)',
     '50%',
     'c',
     'Art.243D(3): Minimum 1/3 seats for women. Several states including AP and Telangana provide 50% reservation. / అనుచ్ఛేదం 243D(3): మహిళలకు కనీసం 1/3 (33.33%) స్థానాలు రిజర్వు. ఆంధ్రప్రదేశ్, తెలంగాణ సహా పలు రాష్ట్రాలు 50% రిజర్వేషన్ ఇస్తున్నాయి.'),
    (4,
     'medium',
     'Is OBC reservation in PR elections mandatory?\nతెలుగు: పంచాయతీ ఎన్నికలలో OBC రిజర్వేషన్ తప్పనిసరా?',
     'Yes — mandatory under 73rd Amendment / అవును — 73వ సవరణ ప్రకారం తప్పనిసరి',
     "No — at state legislature's discretion / లేదు — రాష్ట్ర చట్టం విచక్షణ పై ఆధారపడి ఉంది",
     'Yes — mandatory under 93rd Amendment / అవును — 93వ సవరణ ప్రకారం తప్పనిసరి',
     'No — OBC reservation is prohibited in PR / లేదు — పంచాయతీలలో OBC రిజర్వేషన్ నిషేధం',
     'b',
     "OBC reservation is at state discretion (Art.243D(6)). SC's Triple Test: Dedicated Commission + empirical data + 50% ceiling. / 73వ సవరణ OBC రిజర్వేషన్ రాష్ట్ర విచక్షణపై విడిచిపెట్టింది (Art.243D(6)). SC ఇప్పుడు Triple Test నిబంధన నిర్దేశించింది: (1) Dedicated Commission, (2) Empirical data, (3) 50% ceiling."),
    (4,
     'medium',
     'Voting age for PR elections?\nతెలుగు: పంచాయతీ ఎన్నికలలో ఓటింగ్ వయస్సు ఎంత?',
     '21 years / 21 సంవత్సరాలు',
     '18 years / 18 సంవత్సరాలు',
     '25 years / 25 సంవత్సరాలు',
     'State decides / రాష్ట్రం నిర్ణయిస్తుంది',
     'b',
     'The 61st Amendment (1988) lowered voting age from 21 to 18 — applies to PR elections too. / 61వ సవరణ (1988) ఓటు హక్కు వయస్సు 21 నుండి 18 సంవత్సరాలకు తగ్గించింది — PR ఎన్నికలకూ 18 సంవత్సరాలే.'),
    (4,
     'hard',
     'How does SC/ST seat rotation work in PR?\nతెలుగు: పంచాయతీ ఎన్నికల్లో SC/ST రిజర్వేషన్ రొటేషన్ ఎలా ఉంటుంది?',
     'No rotation required / రొటేషన్ అవసరం లేదు',
     'Rotation per state law — reserved seats rotate among panchayats / రాష్ట్ర చట్టం ప్రకారం రొటేషన్ — ఒకే పంచాయత్ లో రిజర్వేషన్ రొటేట్ అవుతుంది',
     'Central govt decides / కేంద్రం నిర్ణయిస్తుంది',
     'Every 10 years / ప్రతి 10 సంవత్సరాలకు',
     'b',
     'SC/ST reserved seats rotate among panchayats per state law. Different panchayats/wards are reserved in successive elections. / 73వ సవరణ ప్రకారం SC/ST రిజర్వేషన్ స్థానాలు రొటేట్ అవుతాయి. ప్రతి ఎన్నికకు వేరే వార్డు/పంచాయత్ రిజర్వ్ అవుతుంది — రాష్ట్ర చట్టాలు నిర్ణయిస్తాయి.'),
    (4,
     'hard',
     'Where are PR election disputes settled?\nతెలుగు: పంచాయతీ ఎన్నికల వివాదాలు ఏ కోర్టులో తేల్చాలి?',
     'Central Election Commission / కేంద్ర ఎన్నికల సంఘం',
     'High Court',
     'State Election Commission / రాష్ట్ర ఎన్నికల సంఘం',
     'District Court / జిల్లా కోర్టు',
     'b',
     'Art.243O: PR election disputes settled in High Court. No court other than HC/SC can interfere in PR elections. / అనుచ్ఛేదం 243O: పంచాయతీ ఎన్నికల వివాదాలు High Court లో తేల్చాలి. SC మరియు HC తప్ప ఇతర కోర్టులు ఎన్నికలలో జోక్యం చేసుకోలేవు.'),
    (4,
     'hard',
     'Minimum age to contest PR elections?\nతెలుగు: పంచాయతీ ఎన్నికలలో పోటీ చేయడానికి కనీస వయస్సు ఎంత?',
     '18 years / 18 సంవత్సరాలు',
     '21 years / 21 సంవత్సరాలు',
     '25 years / 25 సంవత్సరాలు',
     '30 years / 30 సంవత్సరాలు',
     'b',
     'Minimum age to contest PR elections = 21 years (set by state law; most states fix 21). / పంచాయతీ ఎన్నికలలో పోటీ చేయడానికి కనీస వయస్సు = 21 సంవత్సరాలు. 73వ సవరణ రాష్ట్రాలకు ఇది నిర్ణయించే స్వేచ్ఛ ఇచ్చింది — చాలా రాష్ట్రాలు 21 నిర్ణయించాయి.'),
    (5,
     'easy',
     'State Finance Commission is provided under?\nతెలుగు: రాష్ట్ర ఆర్థిక కమిషన్ (State Finance Commission) ఏ అనుచ్ఛేదంలో నిర్దేశించబడింది?',
     'Art.243G / అనుచ్ఛేదం 243G',
     'Art.243H / అనుచ్ఛేదం 243H',
     'Art.243I / అనుచ్ఛేదం 243I',
     'Art.243J / అనుచ్ఛేదం 243J',
     'c',
     'Art.243I: State Finance Commission — recommends distribution of taxes and grants to panchayats; constituted every 5 years. / అనుచ్ఛేదం 243I: State Finance Commission — పంచాయతీలకు పన్నుల పంపిణీ, అనుదానాల సూత్రాలు సిఫారసు చేస్తుంది. ప్రతి 5 సంవత్సరాలకు నియమించబడుతుంది.'),
    (5,
     'easy',
     'Who appoints the State Election Commissioner (SEC)?\nతెలుగు: రాష్ట్ర ఎన్నికల కమిషనర్ (SEC) ని ఎవరు నియమిస్తారు?',
     'Prime Minister / ప్రధానమంత్రి',
     'President / రాష్ట్రపతి',
     'Governor / గవర్నర్',
     'Central Election Commission / కేంద్ర ఎన్నికల సంఘం',
     'c',
     'Art.243K: SEC appointed by Governor. Can be removed like HC judge (i.e., on address of state legislature). / అనుచ్ఛేదం 243K: రాష్ట్ర ఎన్నికల కమిషనర్ (SEC) ని గవర్నర్ నియమిస్తారు. SEC ని HC న్యాయమూర్తి మాదిరిగా తొలగించవచ్చు.'),
    (5,
     'medium',
     'To whom does SFC submit its report?\nతెలుగు: State Finance Commission నివేదిక ఎవరికి సమర్పించబడుతుంది?',
     'Prime Minister / ప్రధానమంత్రికి',
     'Governor / గవర్నర్\u200cకు',
     'President / రాష్ట్రపతికి',
     'Chief Minister / రాష్ట్ర ముఖ్యమంత్రికి',
     'b',
     'SFC report submitted to Governor, who lays it before the state legislature. / State Finance Commission నివేదిక గవర్నర్\u200cకు సమర్పించబడుతుంది. గవర్నర్ దానిని రాష్ట్ర శాసనమండలి ముందు పెడతారు.'),
    (5,
     'medium',
     'Besides PR, what other elections does SEC superintend?\nతెలుగు: రాష్ట్ర ఎన్నికల కమిషన్ (SEC) పంచాయతీ ఎన్నికలు తప్ప మరే ఎన్నికలు పర్యవేక్షిస్తుంది?',
     'Lok Sabha elections / లోక్\u200cసభ ఎన్నికలు',
     'State Legislature elections / రాష్ట్య శాసనసభ ఎన్నికలు',
     'Urban Local Body elections / పట్టణ స్థానిక సంస్థ (ULB) ఎన్నికలు',
     'Presidential elections / రాష్ట్రపతి ఎన్నికలు',
     'c',
     'SEC superintends both PR elections and Urban Local Body elections (Art.243K + Art.243ZA). / SEC పంచాయతీ ఎన్నికలు + పట్టణ స్థానిక సంస్థ (ULB) ఎన్నికలు రెండూ పర్యవేక్షిస్తుంది (Art.243K + Art.243ZA).'),
    (5,
     'medium',
     'What does SFC recommend regarding State Consolidated Fund?\nతెలుగు: State Finance Commission రాష్ట్ర Consolidated Fund నుండి ఎలా పంపిణీ సిఫారసు చేస్తుంది?',
     'Only to Panchayats / కేవలం పంచాయతీలకు',
     'Only to ULBs / కేవలం ULBs కి',
     'Distribution principles for both Panchayats and ULBs / పంచాయతీలు + ULBs రెండింటికీ పంపిణీ సూత్రాలు',
     'Only to Centre / కేంద్రానికి మాత్రమే',
     'c',
     'SFC recommends distribution from State CF to both Panchayats and ULBs under 73rd and 74th Amendments. / State Finance Commission పంచాయతీలు మరియు ULBs రెండింటికీ రాష్ట్ర Consolidated Fund పంపిణీ సూత్రాలు సిఫారసు చేస్తుంది — 73వ మరియు 74వ సవరణల ద్వారా.'),
    (5,
     'hard',
     'How can SEC be removed?\nతెలుగు: రాష్ట్ర ఎన్నికల కమిషనర్ (SEC) తొలగింపు ఎలా జరుగుతుంది?',
     "By Governor's order only / గవర్నర్ ఉత్తర్వు మాత్రమే",
     "CM's recommendation / రాష్ట్ర ముఖ్యమంత్రి సిఫారసు",
     'Like HC judge — by state legislature resolution / HC న్యాయమూర్తి మాదిరిగా — రాష్ట్ర శాసనమండలి తీర్మానం ద్వారా',
     'By SC order / SC ఆదేశం ద్వారా',
     'c',
     'Art.243K: SEC removed like HC judge — by resolution of state legislature addressed to Governor. / అనుచ్ఛేదం 243K: SEC ని HC న్యాయమూర్తి మాదిరిగా తొలగించవచ్చు — రాష్ట్ర శాసనమండలి తీర్మానం (address to Governor) ద్వారా.'),
    (5,
     'hard',
     'What does Art.243G provide?\nతెలుగు: 73వ సవరణ ప్రకారం అనుచ్ఛేదం 243G ఏమి నిర్దేశిస్తుంది?',
     'Gram Sabha definition / గ్రామ సభ నిర్వచనం',
     'State legislature may endow panchayats with powers and functions / రాష్ట్ర శాసనమండలి పంచాయతీలకు అధికారాలు & విధులు ఇవ్వగలదు',
     'State Finance Commission composition / రాష్ట్ర ఆర్థిక కమిషన్ నిర్మాణం',
     'Panchayat elections / పంచాయతీ ఎన్నికలు',
     'b',
     'Art.243G: State legislature may endow panchayats with powers regarding 11th Schedule subjects. / అనుచ్ఛేదం 243G: రాష్ట్ర శాసనమండలి పంచాయతీలకు 11వ షెడ్యూల్ విషయాలపై అధికారాలు, విధులు బదిలీ చేయగలదు.'),
    (5,
     'hard',
     'Which state formed the First State Finance Commission?\nతెలుగు: First SFC ఏ రాష్ట్రంలో ఏర్పాటైంది?',
     'Maharashtra',
     'Andhra Pradesh',
     'Karnataka',
     'Uttar Pradesh',
     'c',
     'Karnataka was among the first states to constitute its SFC after the 73rd Amendment. / Karnataka మొదట State Finance Commission ఏర్పాటు చేసింది.'),
    (6,
     'easy',
     'How many subjects are in the 11th Schedule?\nతెలుగు: 11వ షెడ్యూల్ లో ఎన్ని విషయాలు (subjects) ఉన్నాయి?',
     '18',
     '22',
     '29',
     '36',
     'c',
     '11th Schedule (added by 73rd Amendment) contains 29 subjects for potential devolution to panchayats. / 11వ షెడ్యూల్ (73వ సవరణ ద్వారా జోడించబడింది) లో 29 విషయాలు ఉన్నాయి — పంచాయతీలకు బదిలీ చేయగలిగే అంశాలు.'),
    (6,
     'easy',
     'Which of the following belongs to the 11th Schedule?\nతెలుగు: కింది వాటిలో 11వ షెడ్యూల్ కి చెందే అంశం ఏది?',
     'Management of arms / ఆయుధాల నిర్వహణ',
     'Agriculture extension services / వ్యవసాయ విస్తరణ సేవలు',
     'Railway transport / రైలు రవాణా',
     'Nuclear energy / అణు విద్యుత్',
     'b',
     'Agriculture extension is in the 11th Schedule. It includes: agriculture, land reforms, fishing, education, health, drinking water, rural employment schemes, etc. / వ్యవసాయ విస్తరణ సేవలు 11వ షెడ్యూల్ లో ఉంది. ఇందులో: వ్యవసాయం, భూ సంస్కరణలు, చేపలు పట్టడం, విద్య, ఆరోగ్యం, తాగు నీరు, గ్రామీణ ఉపాధి, బంగారు ప్రగతి వంటివి ఉన్నాయి.'),
    (6,
     'medium',
     'Is transfer of 11th Schedule subjects to panchayats mandatory?\nతెలుగు: 11వ షెడ్యూల్ విషయాలు పంచాయతీలకు బదిలీ తప్పనిసరా?',
     'Yes — mandatory under 73rd Amendment / అవును — 73వ సవరణ ప్రకారం తప్పనిసరి',
     "No — at state legislature's discretion / లేదు — రాష్ట్ర శాసనమండలి విచక్షణపై ఆధారపడి ఉంది",
     'Central government decides / కేంద్ర ప్రభుత్వం నిర్ణయిస్తుంది',
     'Yes — under PESA 1996 / అవును — PESA 1996 ప్రకారం',
     'b',
     "Transfer of 29 subjects is NOT mandatory — at state's discretion. Critics consider this a major limitation. / 11వ షెడ్యూల్ 29 విషయాల బదిలీ తప్పనిసరి కాదు — రాష్ట్ర శాసనమండలి విచక్షణపై ఆధారపడి ఉంది. ఇది పెద్ద పరిమితి అని విమర్శకులు చెబుతారు."),
    (6,
     'medium',
     'Education in 11th Schedule is up to which level?\nతెలుగు: 11వ షెడ్యూల్ లో విద్య (Education) ఏ స్థాయి వరకు?',
     'Primary only / ప్రాథమిక విద్య మాత్రమే',
     'Up to secondary / మాధ్యమిక విద్య వరకు',
     'Up to higher education / ఉన్నత విద్య వరకు',
     'Primary and Upper Primary / ప్రాథమిక మరియు ప్రాథమికోన్నత విద్య',
     'd',
     '11th Schedule Entry 17: Primary and Secondary education. Higher education is not included. / 11వ షెడ్యూల్ Entry 17: ప్రాథమిక మరియు ప్రాథమికోన్నత పాఠశాలలు (Primary and Secondary including high school). ఉన్నత విద్య ఇందులో లేదు.'),
    (6,
     'hard',
     'Rural Housing is in which Entry of 11th Schedule?\nతెలుగు: 11వ షెడ్యూల్ లో గ్రామీణ గృహ నిర్మాణం (Rural Housing) ఏ Entry లో ఉంది?',
     'Entry 8',
     'Entry 10',
     'Entry 13',
     'Entry 22',
     'b',
     'Entry 10 = Rural housing (NOT Entry 22 which is Markets and fairs). PMAY-Gramin links to Entry 10. / 11వ షెడ్యూల్ Entry 10 = Rural housing (గ్రామీణ గృహ నిర్మాణం). Entry 22 = Markets and fairs (మార్కెట్లు & ఫెయిర్లు). PMAY-G ఈ Entry 10 కి సంబంధించింది.'),
    (6,
     'hard',
     'Poverty alleviation programmes are in which Entry of 11th Schedule?\nతెలుగు: 11వ షెడ్యూల్ లో పేదరిక నిర్మూలన కార్యక్రమాలు (Poverty alleviation programmes) ఏ Entry లో ఉన్నాయి?',
     'Entry 16',
     'Entry 26',
     'Entry 28',
     'Entry 29',
     'a',
     'Entry 16 = Poverty alleviation (not Entry 26 which is Social welfare). MGNREGA relates to Entry 16. / 11వ షెడ్యూల్ Entry 16 = Poverty alleviation programme (పేదరిక నిర్మూలన). Entry 26 = Social welfare (సామాజిక సంక్షేమం — వికలాంగులు సహా). MGNREGA Entry 16 కి సంబంధించింది.'),
    (6,
     'hard',
     'What is Entry 29 of the 11th Schedule?\nతెలుగు: 11వ షెడ్యూల్ Entry 29 ఏది?',
     'Agriculture',
     'Non-conventional energy sources',
     'Maintenance of community assets',
     'Social welfare including welfare of the handicapped',
     'c',
     'Entry 29 of 11th Schedule: Maintenance of community assets — the last of the 29 subjects. / 11వ షెడ్యూల్ Entry 29: సమాజ ఆస్తుల నిర్వహణ (Maintenance of community assets). ఇది అన్ని 29 అంశాలలో చివరిది.'),
    (6,
     'hard',
     'How many subjects are in the 12th Schedule (74th Amendment)?\nతెలుగు: 12వ షెడ్యూల్ (74వ సవరణ) లో ఎన్ని అంశాలు ఉన్నాయి?',
     '18',
     '22',
     '29',
     '36',
     'a',
     '12th Schedule (74th Amendment, ULBs) = 18 subjects. 11th Schedule (73rd Amendment, PR) = 29 subjects. / 12వ షెడ్యూల్ (74వ సవరణ — పట్టణ స్థానిక సంస్థలు) లో 18 విషయాలు ఉన్నాయి. 11వ షెడ్యూల్ (73వ సవరణ — పంచాయతీ రాజ్) లో 29 విషయాలు ఉన్నాయి.'),
    (7,
     'easy',
     'When did the 73rd Amendment come into force?\nతెలుగు: 73వ సవరణ అమలు తేదీ ఏది?',
     'December 20, 1992 / 1992 డిసెంబర్ 20',
     'April 24, 1993 / 1993 ఏప్రిల్ 24',
     'January 26, 1993 / 1993 జనవరి 26',
     'January 1, 1994 / 1994 జనవరి 1',
     'b',
     "73rd Amendment came into force on April 24, 1993. April 24 is observed as 'Panchayati Raj Diwas'. / 73వ సవరణ 24 ఏప్రిల్ 1993 నుండి అమలులోకి వచ్చింది. ప్రతి సంవత్సరం ఏప్రిల్ 24 ని 'Panchayati Raj Diwas' (జాతీయ పంచాయతీ రాజ్ దినం) గా జరుపుకుంటారు."),
    (7,
     'easy',
     "Which Indian system is considered one of the world's largest democratic experiments?\nతెలుగు: ప్రపంచంలో అతి పెద్ద విమర్శనాత్మక ప్రజాస్వామ్య ప్రయోగంగా గుర్తించబడిన భారత వ్యవస్థ ఏది?",
     'Parliamentary system / పార్లమెంటరీ వ్యవస్థ',
     'Panchayati Raj system / పంచాయతీ రాజ్ వ్యవస్థ',
     'Federal system / ఫెడరల్ వ్యవస్థ',
     'Judicial system / జ్యుడీషియల్ సిస్టమ్',
     'b',
     "India's PR system is considered the world's largest rural democratic experiment — ~2.5 lakh panchayats, ~30 lakh elected representatives. / భారత పంచాయతీ రాజ్ వ్యవస్థ ప్రపంచంలో అతి పెద్ద గ్రామీణ ప్రజాస్వామ్య ప్రయోగంగా గుర్తించబడింది — 2.5 లక్షల పంచాయతీలు, 30 లక్షల మంది ప్రజాప్రతినిధులు."),
    (7,
     'medium',
     'What is Art.243N?\nతెలుగు: అనుచ్ఛేదం 243N అంటే ఏమిటి?',
     'Panchayat elections / పంచాయతీ ఎన్నికలు',
     'Dissolution of panchayats / పంచాయతీల రద్దు',
     'Continuance of existing PR laws before 73rd Amendment / 73వ సవరణకు ముందు ఉన్న పంచాయతీ చట్టాల కొనసాగింపు',
     'State Finance Commission / రాష్ట్ర ఆర్థిక కమిషన్',
     'c',
     'Art.243N: Existing state PR laws (before 73rd Amendment) continue until their term expires. / అనుచ్ఛేదం 243N: 73వ సవరణకు ముందు ఉన్న రాష్ట్ర పంచాయతీ చట్టాలు వాటి కాలం పూర్తయ్యే వరకు కొనసాగుతాయి.'),
    (7,
     'medium',
     'What does Art.243O provide?\nతెలుగు: అనుచ్ఛేదం 243O ఏమి నిర్దేశిస్తుంది?',
     'Gram Sabha powers / గ్రామ సభ అధికారాలు',
     'Bar on court interference in PR electoral matters / పంచాయతీ ఎన్నికల వ్యాజ్యాలలో న్యాయస్థాన జోక్యాన్ని నిషేధించడం',
     'Panchayat funds / పంచాయతీ నిధులు',
     'SFC / రాష్ట్ర ఆర్థిక కమిషన్',
     'b',
     'Art.243O: No court (other than HC) shall interfere in PR electoral matters. / అనుచ్ఛేదం 243O: పంచాయతీ ఎన్నికల వ్యాజ్యాలలో High Court తప్ప ఇతర కోర్టులు జోక్యం చేసుకోలేవు.'),
    (7,
     'medium',
     "How is 'Village' defined in Art.243?\nతెలుగు: అనుచ్ఛేదం 243 లో 'గ్రామం' (Village) ఎలా నిర్వచించారు?",
     'President decides / రాష్ట్రపతి నిర్ణయిస్తాడు',
     'Specified by Governor by public notification / రాష్ట్ర గవర్నర్ నోటిఫికేషన్ ద్వారా నిర్ణయిస్తారు',
     'As per Census / Census ప్రకారం',
     'NITI Aayog decides / NITI ఆయోగ్ నిర్ణయిస్తుంది',
     'b',
     "Art.243(g): 'Village' = area specified by Governor by public notification + a group of villages so specified. / అనుచ్ఛేదం 243(g): 'Village' = రాష్ట్ర గవర్నర్ నోటిఫికేషన్ ద్వారా గ్రామంగా నిర్ణయించబడిన ప్రాంతం, మరియు అలా నిర్ణయించబడిన గ్రామ సమూహం."),
    (7,
     'hard',
     'Who launched e-Panchayat Mission Mode Project?\nతెలుగు: e-Panchayat అభయారణ్యం (Mission) ఎవరు ప్రారంభించారు?',
     'NITI Aayog',
     'Ministry of Panchayati Raj',
     'Ministry of Electronics and IT',
     'CSC (Common Service Centre)',
     'b',
     'e-Panchayat MMP was launched by the Ministry of Panchayati Raj for digital management of panchayats. / e-Panchayat Mission Mode Project పంచాయతీ రాజ్ మంత్రిత్వ శాఖ ప్రారంభించింది — పంచాయతీల డిజిటల్ మేనేజ్\u200cమెంట్ కోసం.'),
    (7,
     'hard',
     "'No Work, No Pay' in PR law refers to?\nతెలుగు: పంచాయతీ రాజ్ చట్టాలలో 'No Work, No Pay' నిబంధన ఎందుకు ఉంది?",
     'Sarpanch disqualification / సర్పంచ్ అనర్హత',
     'Wages to MGNREGA workers / ఉపాధి కార్మికులకు వేతనాలు',
     'Fund distribution / పంచాయత్ నిధుల పంపిణీ',
     'Panchayat employees / పంచాయత్ ఉద్యోగులు',
     'b',
     "Under MGNREGA: if work is not provided, states must pay unemployment allowance. Implemented at panchayat level. / MGNREGA కింద 'No Work, No Pay' అంటే — పని అందించని రాష్ట్రాలు నిరుద్యోగ భత్యం (unemployment allowance) చెల్లించాలి. ఇది పంచాయతీ స్థాయిలో అమలవుతుంది."),
    (7,
     'hard',
     'National Panchayati Raj Day is observed on?\nతెలుగు: జాతీయ పంచాయతీ రాజ్ దినం ఏది?',
     'January 26 / జనవరి 26',
     'April 24 / ఏప్రిల్ 24',
     'November 19 / నవంబర్ 19',
     'October 2 / అక్టోబర్ 2',
     'b',
     'National Panchayati Raj Day = April 24 — commemorating the date 73rd Amendment came into force. / జాతీయ పంచాయతీ రాజ్ దినం (National Panchayati Raj Day) — ఏప్రిల్ 24 — 73వ సవరణ అమలులోకి వచ్చిన తేదీని స్మరించి.'),
]


def _seed_polity_ch24_notes_inner(conn, db_exec_fn, row_to_dict_fn, use_postgres, force=False):
    check = db_exec_fn(conn,
        "SELECT id FROM study_notes WHERE subject=? AND topic=? AND chapter_num=?",
        (_SUBJECT, _TOPIC, _CH))
    row = check.fetchone()
    if row and not force:
        return
    if row and force:
        db_exec_fn(conn, "DELETE FROM study_notes WHERE subject=? AND topic=? AND chapter_num=?",
                   (_SUBJECT, _TOPIC, _CH))
    db_exec_fn(conn,
        """INSERT INTO study_notes
           (subject, topic, chapter_num, chapter_title_te, chapter_title_en, pages_ref, sections_json)
           VALUES (?,?,?,?,?,?,?)""",
        (_SUBJECT, _TOPIC, _CH, _TITLE_TE, _TITLE_EN, _PAGES, json.dumps(_SECTIONS, ensure_ascii=False)))


def _seed_polity_ch24_mcqs_inner(conn, db_exec_fn, row_to_dict_fn, use_postgres):
    import json as _json
    cur = db_exec_fn(conn,
        "SELECT id FROM study_notes WHERE subject=? AND topic=? AND chapter_num=?",
        (_SUBJECT, _TOPIC, _CH))
    note_row = cur.fetchone()
    if not note_row:
        return
    note_id = row_to_dict_fn(note_row)['id']

    diff_map = {"easy": 1, "medium": 2, "hard": 3, "toughest": 4, 1: 1, 2: 2, 3: 3, 4: 4}

    cur2 = db_exec_fn(conn,
        "SELECT COUNT(*) FROM chapter_mcqs WHERE study_note_id=?", (note_id,))
    cnt_row = cur2.fetchone()
    if cnt_row:
        cnt = list(cnt_row)[0]
        if cnt >= len(_MCQS):
            return

    db_exec_fn(conn, "DELETE FROM chapter_mcqs WHERE study_note_id=?", (note_id,))

    for row in _MCQS:
        sec_idx   = row[0]
        diff_str  = row[1]
        q_te      = row[2]
        opt_a     = row[3]
        opt_b     = row[4]
        opt_c     = row[5]
        opt_d     = row[6]
        correct   = row[7]
        expl      = row[8]
        exam_type = row[9] if len(row) > 9 else 'General'
        if exam_type is None:
            exam_type = 'General'
        diff_int  = diff_map.get(diff_str, 2)
        db_exec_fn(conn,
            """INSERT INTO chapter_mcqs
               (study_note_id, section_idx, difficulty, exam_type,
                q_te, opt_a, opt_b, opt_c, opt_d, correct, explanation_te)
               VALUES (?,?,?,?,?,?,?,?,?,?,?)""",
            (note_id, sec_idx, diff_int, exam_type,
             q_te, opt_a, opt_b, opt_c, opt_d, correct, expl))


import json
