# seed_polity_ch20.py
# Chapter 20 — Supreme Court of India
# Total Sections: 8 | Total MCQs: 64 | PYQs: 6
# Sections:
#   0 — Establishment & Composition (8 MCQs)
#   1 — Appointment & Removal of Judges (8 MCQs)
#   2 — Original Jurisdiction (8 MCQs)
#   3 — Appellate Jurisdiction & SLP (8 MCQs)
#   4 — Advisory Jurisdiction & Writ Jurisdiction (8 MCQs)
#   5 — Law of the Land — Art.141 & Precedent (8 MCQs)
#   6 — Collegium System & Judicial Independence (8 MCQs)
#   7 — Miscellaneous / Key Articles (8 MCQs)

_CH = 20
_SUBJECT = 'GK'
_TOPIC   = 'Indian_Polity'
_TITLE_TE = 'భారత సర్వోన్నత న్యాయస్థానం'
_TITLE_EN = 'Supreme Court of India'
_PAGES    = 'Ch.20 (Lakshmikanth)'

_SECTIONS = [
    "స్థాపన & కూర్పు",
    "న్యాయమూర్తుల నియామకం & తొలగింపు",
    "మూల అధికార పరిధి",
    "అప్పీలేట్ అధికార పరిధి & SLP",
    "సలహా & రిట్ అధికార పరిధి",
    "అనుచ్ఛేదం 141 & న్యాయ శాసనం",
    "కొలీజియం వ్యవస్థ & న్యాయ స్వాతంత్ర్యం",
    "విభిన్న కీలక అనుచ్ఛేదాలు",
]

_MCQS = [    (0,
     'easy',
     'Which Article establishes the Supreme Court?\nతెలుగు: సర్వోన్నత న్యాయస్థానం స్థాపనను ప్రస్తావించే అనుచ్ఛేదం ఏది?',
     'Art.121 / అనుచ్ఛేదం 121',
     'Art.124 / అనుచ్ఛేదం 124',
     'Art.143 / అనుచ్ఛేదం 143',
     'Art.148 / అనుచ్ఛేదం 148',
     'b',
     "Art.124: 'There shall be a Supreme Court of India consisting of a Chief Justice of India…' / అనుచ్ఛేదం 124: 'భారతదేశంలో భారత సర్వోన్నత న్యాయస్థానం అనే ఒక న్యాయస్థానం ఉండాలి'."),
    (0,
     'easy',
     'How many judges did the Supreme Court originally have (1950)?\nతెలుగు: సర్వోన్నత న్యాయస్థానం ప్రారంభంలో ఎంత మంది న్యాయమూర్తులతో ప్రారంభమైంది?',
     '7 (CJI + 6)',
     '8 (CJI + 7)',
     '11 (CJI + 10)',
     '26 (CJI + 25)',
     'b',
     'Originally CJI + 7 = 8. Current strength: CJI + 33 = 34 (increased over time by Parliament). / 1950లో SC లో CJI + 7 న్యాయమూర్తులు ఉండేవారు. ప్రస్తుతం CJI + 33 (మొత్తం 34).'),
    (0,
     'medium',
     'What is the current sanctioned strength of the Supreme Court?\nతెలుగు: సర్వోన్నత న్యాయస్థానం ప్రస్తుత న్యాయమూర్తుల సంఖ్య ఎంత?',
     '25',
     '28',
     '34',
     '31',
     'c',
     'Currently 34 judges (CJI + 33), sanctioned by the 2019 Amendment. / ప్రస్తుతం SC లో CJI + 33 న్యాయమూర్తులు మొత్తం 34 (Supreme Court (Number of Judges) Amendment Act 2019).'),
    (0,
     'easy',
     'What is the retirement age of SC judges?\nతెలుగు: సర్వోన్నత న్యాయస్థాన న్యాయమూర్తుల పదవీ విరమణ వయస్సు ఎంత?',
     '60 years / 60 సంవత్సరాలు',
     '62 years / 62 సంవత్సరాలు',
     '65 years / 65 సంవత్సరాలు',
     '70 years / 70 సంవత్సరాలు',
     'c',
     'SC judges retire at 65 (Art.124(2)). HC judges retire at 62. / SC న్యాయమూర్తులు 65 సంవత్సరాల వయస్సులో పదవీ విరమణ చేస్తారు (Art.124(2)). హైకోర్టు న్యాయమూర్తులు 62 సంవత్సరాలకు.'),
    (0,
     'medium',
     'Where is the seat of the Supreme Court?\nతెలుగు: సర్వోన్నత న్యాయస్థానం సీటు ఎక్కడ ఉంది?',
     'Mumbai / ముంబై',
     'Kolkata / కోల్కతా',
     'New Delhi / నూతన ఢిల్లీ',
     'Chennai / చెన్నై',
     'c',
     "SC sits in Delhi (Art.130). CJI may appoint other places with President's approval. / భారత సర్వోన్నత న్యాయస్థానం ఢిల్లీలో ఉంది (Art.130). అయితే CJI అనుమతితో ఇతర చోట్ల కూర్చోవచ్చు."),
    (0,
     'medium',
     'Minimum HC judge experience to qualify for SC?\nతెలుగు: సర్వోన్నత న్యాయస్థానం న్యాయమూర్తిగా నియమించబడాలంటే కనీసం ఎంత కాలం హైకోర్టు న్యాయమూర్తిగా పనిచేసి ఉండాలి?',
     '3 years / 3 సంవత్సరాలు',
     '5 years / 5 సంవత్సరాలు',
     '10 years / 10 సంవత్సరాలు',
     '15 years / 15 సంవత్సరాలు',
     'b',
     'Art.124(3): Must be HC judge for 5 years OR HC advocate for 10 years OR distinguished jurist. / Art.124(3): SC న్యాయమూర్తిగా నియమించబడాలంటే కనీసం 5 సంవత్సరాలు హైకోర్టు న్యాయమూర్తిగా లేదా 10 సంవత్సరాలు HC అడ్వకేట్\u200cగా పనిచేసి ఉండాలి.'),
    (0,
     'medium',
     'Before whom does an SC judge take oath?\nతెలుగు: సర్వోన్నత న్యాయస్థాన న్యాయమూర్తి ప్రమాణ స్వీకారం ఎవరి ముందు జరుగుతుంది?',
     'Chief Justice of India / ప్రధాన న్యాయమూర్తి',
     'President of India / రాష్ట్రపతి',
     'Vice President / ఉపరాష్ట్రపతి',
     'Speaker of Lok Sabha / స్పీకర్',
     'b',
     'SC judge takes oath before the President of India (Art.124(6)). / Art.124(6): SC న్యాయమూర్తి రాష్ట్రపతి ముందు ప్రమాణ స్వీకారం చేస్తాడు.'),
    (0,
     'hard',
     'What is an ad hoc judge of the Supreme Court?\nతెలుగు: Ad hoc judge అంటే ఎవరు?',
     'Retired SC judge / పదవీ విరమణ చేసిన SC న్యాయమూర్తి',
     'HC judge appointed by CJI when quorum lacks / కోరం లేనప్పుడు CJI నియమించే HC న్యాయమూర్తి',
     'International judge / అంతర్జాతీయ న్యాయమూర్తి',
     'Inquiry commission judge / న్యాయ విచారణ కమిషన్ న్యాయమూర్తి',
     'b',
     "Art.127: When quorum lacks, CJI with President's consent may appoint HC judge as ad hoc judge of SC. / Art.127: కోరం లేనప్పుడు CJI రాష్ట్రపతి అనుమతితో HC న్యాయమూర్తిని 'ad hoc judge'గా నియమించవచ్చు."),
    (1,
     'easy',
     'Who appoints SC judges?\nతెలుగు: సర్వోన్నత న్యాయస్థాన న్యాయమూర్తిని ఎవరు నియమిస్తారు?',
     'Prime Minister / ప్రధానమంత్రి',
     'Chief Justice of India / ప్రధాన న్యాయమూర్తి',
     'President of India / రాష్ట్రపతి',
     'Parliament / పార్లమెంట్',
     'c',
     'Art.124(2): SC judges appointed by President after consultation with SC and HC judges as deemed necessary. / Art.124(2): SC న్యాయమూర్తులను రాష్ట్రపతి నియమిస్తారు. నియమించేటప్పుడు SC మరియు HC న్యాయమూర్తులను సంప్రదిస్తారు.'),
    (1,
     'medium',
     'How can an SC judge be removed?\nతెలుగు: సర్వోన్నత న్యాయస్థాన న్యాయమూర్తిని తొలగించే విధానం ఏమిటి?',
     "President's order alone / రాష్ట్రపతి ఉత్తర్వు మాత్రమే",
     'Parliament simple majority / పార్లమెంట్ సాధారణ మెజారిటీ',
     "Special majority + President's order / పార్లమెంట్ ప్రత్యేక మెజారిటీ + రాష్ట్రపతి ఆదేశం",
     'SC judgment / సుప్రీం కోర్ట్ జడ్జిమెంట్',
     'c',
     "Art.124(4): Removal on grounds of proved misbehaviour or incapacity — address by each House with special majority + President's order. / Art.124(4): Proved misbehaviour లేదా incapacity పై పార్లమెంట్ ప్రత్యేక మెజారిటీ (సభ మొత్తం సభ్యుల మెజారిటీ + హాజరైన 2/3 మెజారిటీ) + రాష్ట్రపతి ఆదేశంతో తొలగించవచ్చు."),
    (1,
     'medium',
     "SC judges' salaries are charged to?\nతెలుగు: SC న్యాయమూర్తుల జీతాలు ఏ నిధి నుండి చెల్లిస్తారు?",
     'Consolidated Fund of India / భారత ఏకీకృత నిధి',
     'Contingency Fund / ఆకస్మిక నిధి',
     'Public Account / పబ్లిక్ అకౌంట్',
     'Bharat Nirmaan Fund / భారత్ నిర్మాణ నిధి',
     'a',
     "SC judges' salaries charged to CFI (Art.125) — ensures judicial independence. / SC న్యాయమూర్తుల జీతాలు భారత ఏకీకృత నిధి (Consolidated Fund of India) నుండి చెల్లిస్తారు — ఇది వారి స్వాతంత్ర్యాన్ని కాపాడుతుంది."),
    (1,
     'medium',
     'Where can a retired SC judge practice after retirement?\nతెలుగు: పదవీ విరమణ తర్వాత SC న్యాయమూర్తి ఏ కోర్టులో వాదించవచ్చు?',
     'Any court / ఏ కోర్టులో అయినా',
     "Any court with President's approval / ఏ కోర్టులో అయినా రాష్ట్రపతి అనుమతితో",
     'No court at all / ఏ కోర్టులో అయినా కాదు',
     'Only tribunals / కేవలం ట్రిబ్యునల్స్\u200cలో',
     'c',
     'Art.124(7): Retired SC judge cannot plead or act in any court or authority in India. / Art.124(7): SC న్యాయమూర్తి పదవీ విరమణ తర్వాత భారతదేశంలో ఏ కోర్టులో అయినా వాదించడం నిషేధం.'),
    (1,
     'hard',
     'The Judges (Inquiry) Act 1968 relates to?\nతెలుగు: Judges (Inquiry) Act, 1968 ఏ విషయంలో వర్తిస్తుంది?',
     'Appointment of judges / న్యాయమూర్తుల నియామకం',
     'Procedure for removal of SC judge / SC న్యాయమూర్తి తొలగింపు విచారణ విధానం',
     'Establishment of HC / హైకోర్టు ఏర్పాటు',
     "Determination of judges' salaries / న్యాయమూర్తుల జీతాల నిర్ణయం",
     'b',
     'Judges (Inquiry) Act 1968 lays down the procedure for removal of SC/HC judges — 3-member committee investigates. / Judges (Inquiry) Act, 1968: SC/ HC న్యాయమూర్తి తొలగింపు విచారణ విధానాన్ని నిర్దేశిస్తుంది. 3 సభ్యుల కమిటీ ఏర్పాటు: CJI నామినీ, HC CJ,著名 న్యాయవాది.'),
    (1,
     'medium',
     'How is the CJI appointed?\nతెలుగు: సర్వోన్నత న్యాయస్థాన ప్రధాన న్యాయమూర్తి (CJI) నియామకం ఎలా జరుగుతుంది?',
     'By seniority alone / సీనియారిటీ ఆధారంగా మాత్రమే',
     "PM's recommendation / ప్రధానమంత్రి సిఫారసు",
     'President on collegium recommendation / కొలీజియం సిఫారసుపై రాష్ట్రపతి నియమిస్తారు',
     'Parliament election / పార్లమెంట్ ఎన్నిక',
     'c',
     'President appoints CJI on collegium recommendation; by convention the seniormost SC judge is appointed CJI. / రాష్ట్రపతి SC కొలీజియం సిఫారసుపై CJIని నియమిస్తారు. ఆచారప్రకారం అత్యంత సీనియర్ SC జడ్జి CJI అవుతారు.'),
    (1,
     'hard',
     'When was the first impeachment motion against an SC judge moved?\nతెలుగు: SC న్యాయమూర్తి తొలగింపుకు సంబంధించిన మొదటి తీర్మానం ఏ సంవత్సరంలో పార్లమెంట్\u200cలో ప్రవేశపెట్టారు?',
     '1965',
     '1978',
     '1991',
     '2004',
     'c',
     'First removal motion moved against Justice V. Ramaswami in 1991; it failed in Lok Sabha. / 1991లో Justice V. Ramaswami పై తొలిసారి తొలగింపు తీర్మానం ప్రవేశపెట్టారు — ఆ తీర్మానం వీగిపోయింది (Lok Sabha failed to pass).'),
    (1,
     'medium',
     'Who are the 3 members of the inquiry committee for SC judge removal?\nతెలుగు: SC న్యాయమూర్తి తొలగింపు విచారణ 3 సభ్యుల కమిటీ సభ్యులు ఎవరు?',
     'CJI, Attorney General, CEC / CJI, అటార్నీ జనరల్, CEC',
     'CJI nominee, HC Chief Justice, distinguished jurist / CJI నామినీ, HC CJ,著名 న్యాయవాది',
     '3 SC judges / 3 మంది SC న్యాయమూర్తులు',
     'CAG, AG, Solicitor General',
     'b',
     'Under Judges Inquiry Act: committee = SC judge/HC CJ nominated by CJI + another HC CJ + a distinguished jurist. / Judges Inquiry Act 1968: 3-సభ్య కమిటీ = (1) CJI నియమించే SC న్యాయమూర్తి లేదా HC CJ + (2) HC CJ + (3)著名 న్యాయవాది.'),
    (2,
     'easy',
     'Which Article deals with original jurisdiction of SC?\nతెలుగు: సర్వోన్నత న్యాయస్థానం మూల అధికార పరిధి (Original Jurisdiction) గురించి ఏ అనుచ్ఛేదం?',
     'Art.131 / అనుచ్ఛేదం 131',
     'Art.132 / అనుచ్ఛేదం 132',
     'Art.136 / అనుచ్ఛేదం 136',
     'Art.143 / అనుచ్ఛేదం 143',
     'a',
     'Art.131: Original jurisdiction of SC — disputes between states or between state and Centre. / Art.131: SC మూల అధికార పరిధి — రాష్ట్రాల మధ్య, రాష్ట్ర-కేంద్ర వివాదాలు.'),
    (2,
     'medium',
     'Art.131 gives exclusive original jurisdiction over?\nతెలుగు: Art.131 కింద సర్వోన్నత న్యాయస్థానానికి ప్రత్యేక అధికార పరిధి ఎలాంటి వివాదాలపై?',
     'Between individuals and Centre / వ్యక్తులు మరియు కేంద్ర ప్రభుత్వం మధ్య',
     'Between two or more states / రెండు లేదా అంతకు మించిన రాష్ట్రాల మధ్య',
     'Corporate disputes / కార్పొరేట్ వివాదాలు',
     'Patent disputes / పేటెంట్ వివాదాలు',
     'b',
     'Art.131 exclusive original jurisdiction: interstate disputes or state vs Centre (on legal rights). / Art.131: రెండు లేదు అంతకంటే ఎక్కువ రాష్ట్రాల మధ్య వివాదాలపై SC కి ప్రత్యేక మూల అధికార పరిధి ఉంది; రాష్ట్రం మరియు కేంద్రం మధ్య కూడా.'),
    (2,
     'medium',
     'Do river water disputes between states fall under Art.131?\nతెలుగు: రాష్ట్రాల మధ్య నదీ జల వివాదాలు (River water disputes) SC Art.131 కింద వస్తాయా?',
     'Yes, always / అవును, ఎల్లప్పుడూ',
     'No — Water Disputes Act 1956 Tribunal / కాదు, Inter-State Water Disputes Act 1956 కింద ట్రిబ్యునల్',
     'No — President decides / కాదు, రాష్ట్రపతి నిర్ణయిస్తారు',
     'Yes, only for AP and Telangana / అవును, కేవలం AP మరియు తెలంగాణకు',
     'b',
     'River water disputes between states are excluded from Art.131 — adjudicated by tribunal under Inter-State Water Disputes Act 1956. / Inter-State Water Disputes Act 1956 కింద ఇటువంటి వివాదాలు SC Art.131 నుండి మినహాయించబడ్డాయి — ట్రిబ్యునల్\u200cకు వెళ్తాయి.'),
    (2,
     'easy',
     'Which Article allows direct petition to SC for enforcement of Fundamental Rights?\nతెలుగు: ప్రాథమిక హక్కుల ఉల్లంఘనపై సర్వోన్నత న్యాయస్థానంలో నేరుగా విజ్ఞప్తి చేయడానికి ఏ అనుచ్ఛేదం అనుమతిస్తుంది?',
     'Art.226 / అనుచ్ఛేదం 226',
     'Art.32 / అనుచ్ఛేదం 32',
     'Art.131 / అనుచ్ఛేదం 131',
     'Art.143 / అనుచ్ఛేదం 143',
     'b',
     "Art.32: Right to move SC for enforcement of FRs — called 'heart and soul of the Constitution' by Ambedkar. / Art.32: ప్రాథమిక హక్కుల అమలు కోసం SC కి నేరుగా వెళ్ళవచ్చు — Dr. Ambedkar దీన్ని 'Constitution యొక్క హృదయం మరియు ఆత్మ' అన్నారు."),
    (2,
     'hard',
     "Which court adjudicates disputes regarding President's election?\nతెలుగు: రాష్ట్రపతి ఎన్నిక వివాదాలు ఏ కోర్టు పరిశీలిస్తుంది?",
     'High Court / హైకోర్టు',
     'Election Tribunal / ఎన్నికల ట్రిబ్యునల్',
     'Supreme Court / సర్వోన్నత న్యాయస్థానం',
     'Parliament / పార్లమెంట్',
     'c',
     'Art.71: Disputes relating to election of President and VP are inquired into by SC. / Art.71: రాష్ట్రపతి మరియు ఉపరాష్ట్రపతి ఎన్నికలకు సంబంధించిన వివాదాలను SC విచారిస్తుంది.'),
    (2,
     'medium',
     'What nature of dispute must be shown for Art.131 original jurisdiction?\nతెలుగు: రాష్ట్రాల మధ్య వివాదాలలో SC మూల అధికార పరిధి కింద స్థాపించబడాల్సిన వివాద స్వభావం ఏది?',
     'Any dispute / ఏదైనా వివాదం',
     'Dispute involving legal right / చట్టబద్ధ హక్కుల వివాదం',
     'Moral dispute / నైతిక వివాదం',
     'Financial dispute / ఆర్థిక వివాదం',
     'b',
     "Art.131: Only disputes involving legal rights (not political/policy matters) qualify. / Art.131: వివాదం అనేది 'చట్టబద్ధ హక్కుల' (legal rights) విషయంలో ఉండాలి. సాధారణ రాజకీయ వివాదాలు లేదా ఆర్థిక ఫిర్యాదులు కావు."),
    (2,
     'medium',
     "What is President's Reference under which Article?\nతెలుగు: రాష్ట్రపతి Reference అంటే ఏమిటి? ఏ అనుచ్ఛేదం?",
     'Art.131 — మూల అధికార పరిధి',
     'Art.143 — సలహా అధికార పరిధి',
     'Art.32 — రిట్ అధికార పరిధి',
     'Art.136 — SLP',
     'b',
     "Art.143: President can refer questions of law/fact to SC for advisory opinion; SC may give opinion but it's not binding. / Art.143: రాష్ట్రపతి SC అభిప్రాయాన్ని కోరవచ్చు ('Reference'). SC అభిప్రాయం ఇవ్వొచ్చు కానీ రాష్ట్రపతిపై బైండింగ్ కాదు."),
    (2,
     'hard',
     'Which matters are excluded from Art.131?\nతెలుగు: Art.131 కింద వివాదంలో ఏ విషయాలు మినహాయించబడ్డాయి?',
     'Centre-state tax disputes / కేంద్ర-రాష్ట్ర పన్ను వివాదాలు',
     'River water + treaty disputes / రాష్ట్రాల మధ్య నదీ జలాలు + Treaty/Agreement వివాదాలు',
     'Criminal matters / నేర విషయాలు',
     'Fundamental Rights / ప్రాథమిక హక్కులు',
     'b',
     'Art.131 exclusions: river water disputes (special Act) and treaty/agreement disputes. / Art.131 నుండి మినహాయింపు: (1) రాష్ట్రాల మధ్య నదీ జల వివాదాలు (ప్రత్యేక చట్టం ఉంది), (2) Treaty లేదా అంతర్జాతీయ ఒప్పందానికి సంబంధించిన వివాదాలు.'),
    (3,
     'easy',
     'Under which Article is an SLP filed?\nతెలుగు: స్పెషల్ లీవ్ పిటిషన్ (SLP) ఏ అనుచ్ఛేదం కింద దాఖలు చేస్తారు?',
     'Art.132 / అనుచ్ఛేదం 132',
     'Art.134 / అనుచ్ఛేదం 134',
     'Art.136 / అనుచ్ఛేదం 136',
     'Art.137 / అనుచ్ఛేదం 137',
     'c',
     'Art.136: SC may, in its discretion, grant SLP from any judgment of any court or tribunal. / Art.136: SLP (Special Leave to Appeal) — ఏ కోర్టు లేదా ట్రిబ్యునల్ తీర్పుపై SC అనుమతితో అప్పీల్ చేసుకోవచ్చు.'),
    (3,
     'medium',
     'Appellate jurisdiction for constitutional questions?\nతెలుగు: రాజ్యాంగ అర్థంలో చట్టపరమైన ప్రశ్న ఉంటే అప్పీలేట్ అధికార పరిధి ఏ అనుచ్ఛేదం?',
     'Art.132',
     'Art.133',
     'Art.134',
     'Art.135',
     'a',
     'Art.132: Appeal from HC judgment involving substantial question of constitutional law (with HC certificate). / Art.132: HC తీర్పు నుండి రాజ్యాంగ ప్రశ్నపై SC కి అప్పీల్ చేసుకోవచ్చు (HC సర్టిఫికేట్\u200cతో).'),
    (3,
     'medium',
     'Appellate jurisdiction in civil matters?\nతెలుగు: సివిల్ విషయాలలో అప్పీలేట్ అధికార పరిధి ఏ అనుచ్ఛేదం?',
     'Art.132',
     'Art.133',
     'Art.134',
     'Art.136',
     'b',
     'Art.133: Appeal to SC in civil matters from HC with HC certificate (substantial question of law). / Art.133: HC తీర్పు నుండి సివిల్ విషయాలలో SC కి అప్పీల్ (HC యొక్క సర్టిఫికేట్\u200cతో, రాజ్యాంగ ప్రశ్న ఉంటే).'),
    (3,
     'medium',
     'Appellate jurisdiction in criminal matters?\nతెలుగు: నేర (Criminal) విషయాలలో SC అప్పీలేట్ అధికార పరిధి ఏ అనుచ్ఛేదం?',
     'Art.132',
     'Art.133',
     'Art.134',
     'Art.136',
     'c',
     'Art.134: SC has appellate jurisdiction in criminal matters — when HC confirms death sentence or reverses acquittal and awards death. / Art.134: నేర విషయాలలో HC నిర్ణయం నుండి SC కి అప్పీల్ — మరణశిక్ష ధృవీకరించినపుడు లేదా మరణశిక్ష విధించినపుడు.'),
    (3,
     'easy',
     'SLP under Art.136 lies against?\nతెలుగు: Art.136 (SLP) కింద ఏ కోర్టుల తీర్పులపై అప్పీల్ చేయవచ్చు?',
     'Only HC judgments / కేవలం HC తీర్పులు',
     'Only tribunals / కేవలం ట్రిబ్యునల్స్',
     'Any court or tribunal in India / ఏ కోర్టు లేదా ట్రిబ్యునల్ తీర్పు అయినా',
     'Only district courts / కేవలం జిల్లా కోర్టులు',
     'c',
     'Art.136: SLP can be filed against any court or tribunal (except military tribunals) — SC has discretion to admit or reject. / Art.136: SLP ఏ కోర్టు లేదా ట్రిబ్యునల్ తీర్పుపై అయినా SC కి దాఖలు చేయవచ్చు (military tribunals మినహా).'),
    (3,
     'hard',
     "SC's power to review its own judgment?\nతెలుగు: SC తన స్వంత తీర్పును సమీక్షించే అధికారం ఏ అనుచ్ఛేదం?",
     'Art.136',
     'Art.137',
     'Art.141',
     'Art.143',
     'b',
     'Art.137: SC has power to review any judgment or order made by it, subject to law made by Parliament or rules. / Art.137: SC తన స్వంత తీర్పు లేదా ఆదేశాన్ని సమీక్షించవచ్చు (Review Petition).'),
    (3,
     'medium',
     'Which provision shows the widest appellate jurisdiction?\nతెలుగు: SC అప్పీలేట్ అధికార పరిధి యొక్క విస్తృత స్వభావాన్ని ఏ నిబంధన చూపిస్తుంది?',
     'Art.132 — రాజ్యాంగ ప్రశ్నలు',
     'Art.133 — సివిల్',
     'Art.134 — నేర',
     'Art.136 — SLP / విచక్షణ విస్తృత అధికారం',
     'd',
     'Art.136 is the widest — any court, any matter, SC has discretion to grant or refuse SLP. / Art.136 అత్యంత విస్తృతమైన అధికారం — ఏ కోర్టు లేదా ట్రిబ్యునల్ తీర్పు అయినా, ఏ విషయమైనా SC వద్దకు వచ్చే అవకాశం.'),
    (3,
     'medium',
     'What is a Curative Petition?\nతెలుగు: Curative Petition అంటే ఏమిటి?',
     'First appeal / తొలి అప్పీల్',
     'Last remedy after review petition rejected / Review Petition తిరస్కరణ తర్వాత చివరి పరిష్కారం',
     'Same as SLP / SLP తో సమానమైనది',
     'Art.143 Reference',
     'b',
     'Curative Petition: last remedy after review rejected — coined by SC in Rupa Ashok Hurra case (2002). / Curative Petition: Review Petition తిరస్కరించబడిన తర్వాత దాఖలు చేసే చివరి రక్షణ. Rupa Ashok Hurra v. Ashok Hurra (2002) తీర్పులో SC దీన్ని రూపొందించింది.'),
    (4,
     'easy',
     'SC writ jurisdiction under which Article?\nతెలుగు: SC రిట్ అధికార పరిధి ఏ అనుచ్ఛేదం?',
     'Art.32',
     'Art.131',
     'Art.226',
     'Art.143',
     'a',
     'Art.32: SC can issue 5 writs for enforcement of Fundamental Rights — it is itself a FR. / Art.32: SC కి రిట్ జారీ చేసే అధికారం ఉంది — Habeas Corpus, Mandamus, Prohibition, Certiorari, Quo Warranto.'),
    (4,
     'medium',
     'Why is HC writ jurisdiction (Art.226) wider than SC (Art.32)?\nతెలుగు: HC రిట్ అధికారం (Art.226) SC రిట్ అధికారం (Art.32) కంటే ఎందుకు విస్తృతమైంది?',
     'HC can issue more types of writs / HC ఎక్కువ రిట్స్ జారీ చేయగలదు',
     'HC can issue writs for other legal rights too / HC ప్రాథమిక హక్కులతో పాటు ఇతర చట్టపరమైన హక్కులకు కూడా రిట్ జారీ చేయగలదు',
     'HC alone issues Habeas Corpus / HC మాత్రమే Habeas Corpus జారీ చేయగలదు',
     'HC territorial jurisdiction is larger / SC కంటే HC జ్యూరిస్డిక్షన్ పెద్దది',
     'b',
     "Art.226 wider: HC issues writs for FR + any other legal right (Art.226 says 'any other purpose'); Art.32 only for FR. / Art.226: HC ప్రాథమిక హక్కులను + ఏదైనా చట్టపరమైన హక్కు (any other purpose) ఉల్లంఘనపై రిట్ జారీ చేయగలదు. Art.32: కేవలం ప్రాథమిక హక్కుల ఉల్లంఘనపై మాత్రమే."),
    (4,
     'easy',
     'Is SC bound to give advisory opinion under Art.143?\nతెలుగు: రాష్ట్రపతి Art.143 కింద SC కి reference ఇస్తే SC తప్పనిసరిగా అభిప్రాయం ఇవ్వాలా?',
     'Yes, mandatory / అవును, తప్పనిసరి',
     'No, SC may refuse / కాదు, SC స్వేచ్ఛగా నిరాకరించవచ్చు',
     'Yes but only legal questions / అవును, కానీ కేవలం చట్టపరమైన ప్రశ్నలకు మాత్రమే',
     'No, PM approval needed / కాదు, ప్రధానమంత్రి అనుమతి కావాలి',
     'b',
     "Art.143: SC 'may' give opinion — not mandatory. Opinion, if given, is advisory (not binding on President). / Art.143: SC అభిప్రాయం ఇవ్వడం తప్పనిసరి కాదు — SC తన అభిప్రాయం ఇవ్వడానికి నిరాకరించవచ్చు. ఇచ్చిన అభిప్రాయం కూడా బైండింగ్ కాదు."),
    (4,
     'medium',
     'Which writ protects personal liberty?\nతెలుగు: ఐదు రిట్\u200cలలో పర్సనల్ లిబర్టీని కాపాడే ముఖ్యమైన రిట్ ఏది?',
     'Mandamus',
     'Quo Warranto',
     'Habeas Corpus',
     'Certiorari',
     'c',
     "Habeas Corpus: directs production of the detained person before court — most important writ for personal liberty. / Habeas Corpus (Latin: 'you have the body'): నిర్బంధించబడిన వ్యక్తిని కోర్టు ముందు హాజరుపర్చాలని ఆదేశిస్తుంది — వ్యక్తిగత స్వేచ్ఛకు అత్యంత ముఖ్యమైన రిట్."),
    (4,
     'medium',
     'When is Quo Warranto issued?\nతెలుగు: Quo Warranto రిట్ ఎప్పుడు జారీ అవుతుంది?',
     'Illegal detention / చట్టవిరుద్ధ నిర్బంధం కేసులో',
     "Challenge to public office holder's authority / ప్రభుత్వ అధికారి చట్టబద్ధత సవాలు చేసినప్పుడు",
     'Quashing illegal orders / అక్రమ ఆదేశాలు రద్దు చేయడానికి',
     'Directing authority to act / సూచన జారీ చేయడానికి',
     'b',
     "Quo Warranto: challenges the authority by which a person holds a public office — 'by what authority?' / Quo Warranto: ఒక వ్యక్తి ప్రభుత్వ పదవిలో ఉండే హక్కు ఏమిటని అడుగుతుంది. పదవి చట్టబద్ధంగా ఆక్రమించారా లేదా అని తేల్చడానికి."),
    (4,
     'hard',
     'Difference between Certiorari and Prohibition?\nతెలుగు: Certiorari మరియు Prohibition రిట్\u200cల మధ్య తేడా ఏమిటి?',
     'Both are same / రెండూ ఒకే విషయం',
     'Certiorari after decision; Prohibition before / Certiorari పూర్వానికి; Prohibition ముందుకు',
     'Prohibition after decision; Certiorari before / Prohibition పూర్వానికి; Certiorari ముందుకు',
     'Both for personal liberty / రెండూ వ్యక్తిగత స్వేచ్ఛకు',
     'b',
     'Certiorari = quash illegal order (post-decision); Prohibition = stop court from exceeding jurisdiction (pre-decision). / Certiorari: ఒక అక్రమ ఆదేశాన్ని రద్దు చేయడానికి (after decision). Prohibition: దిగువ కోర్టు అధికార పరిధి మించకుండా ముందే ఆపడానికి (before decision).'),
    (4,
     'medium',
     'What did Dr. Ambedkar call Art.32?\nతెలుగు: Art.32 (SC రిట్ అధికారం) ను Dr. Ambedkar ఏమని అన్నారు?',
     'Soul of the Constitution / రాజ్యాంగ ఆత్మ',
     'Heart and soul of the Constitution / రాజ్యాంగ హృదయం మరియు ఆత్మ',
     'Pillar of democracy / ప్రజాస్వామ్య మూలస్తంభం',
     'Most important index of Constitution / రాజ్యాంగం యొక్క ముఖ్య సూచిక',
     'b',
     "Ambedkar called Art.32 'the heart and soul of the Constitution' — it is itself a FR and guarantees enforcement of FRs. / Dr. B.R. Ambedkar: Art.32 'రాజ్యాంగ హృదయం మరియు ఆత్మ' (heart and soul of the Constitution) — ఎందుకంటే ఇది ప్రాథమిక హక్కులను అమలు చేసే హామీ."),
    (4,
     'medium',
     'President may refer to SC under Art.143 for opinion on?\nతెలుగు: Art.143 (SC సలహా అధికార పరిధి) కింద రాష్ట్రపతి SC కి ఏ విషయాలు నివేదించవచ్చు?',
     'Only Supreme Court cases / సుప్రీంకోర్టు కేసులు మాత్రమే',
     'Question of law or fact of public importance / చట్టం లేదా వాస్తవం యొక్క ప్రశ్న — ప్రాముఖ్యత ఉన్నది',
     'Only disputes between states / రాష్ట్రాల మధ్య తగాదాలు మాత్రమే',
     'Only treaty questions / సంధి/ఒప్పందాలకు సంబంధించిన ప్రశ్నలు మాత్రమే',
     'b',
     'Art.143: President may refer question of law/fact of public importance to SC for advisory opinion; SC may give opinion; opinion is advisory not binding. / Art.143: రాష్ట్రపతి చట్టం లేదా వాస్తవంపై ప్రాముఖ్యత ఉన్న ప్రశ్నను SC కి సలహా కోసం నివేదించవచ్చు; SC అభిప్రాయం ఇవ్వవచ్చు కానీ రాష్ట్రపతి దానిని తప్పనిసరిగా పాటించాల్సిన అవసరం లేదు.'),
    (5,
     'easy',
     'Law declared by SC binding under?\nతెలుగు: SC ప్రకటించిన చట్టం (Law declared by SC) ఏ అనుచ్ఛేదం?',
     'Art.139',
     'Art.140',
     'Art.141',
     'Art.142',
     'c',
     'Art.141: Law declared by SC shall be binding on all courts within the territory of India. / Art.141: SC ప్రకటించిన చట్టం భారతదేశంలో అన్ని కోర్టులపై బైండింగ్.'),
    (5,
     'medium',
     'Special power of SC under Art.142?\nతెలుగు: Art.142 కింద SC ఏ ప్రత్యేక అధికారం కలిగి ఉంది?',
     'To make laws / చట్టాలు చేయడం',
     'To pass decrees to do complete justice / పూర్తి న్యాయం చేయడానికి ఆదేశాలు ఇవ్వడం',
     'To direct the President / రాష్ట్రపతిని ఆదేశించడం',
     'To approve budgets / బడ్జెట్ ఆమోదించడం',
     'b',
     "Art.142: SC may pass such decrees or orders as necessary for 'complete justice' — extraordinary power. / Art.142: SC తన అధికార పరిధి ఉపయోగించేటప్పుడు 'పూర్తి న్యాయం' (complete justice) చేయడానికి ఏ ఆదేశమైనా ఇవ్వగలదు — ఇది SC యొక్క అసాధారణ అధికారం."),
    (5,
     'medium',
     'What is the doctrine of Stare Decisis?\nతెలుగు: Stare Decisis సూత్రం అంటే ఏమిటి?',
     'SC judgments auto-expire / SC తీర్పులు ఆటోమేటిగా రద్దవుతాయి',
     'Must follow precedents / పూర్వ తీర్పులను అనుసరించాలి — precedent',
     'SC cannot change its own judgments / SC స్వంత తీర్పులను మార్చుకోలేదు',
     'All judges must agree / అన్ని న్యాయమూర్తులు ఏకగ్రీవంగా ఉండాలి',
     'b',
     "Stare Decisis: doctrine that precedents must be followed. Art.141 enforces this — SC law is binding on all courts. / Stare Decisis: 'stand by what was decided' — ముందు తీర్పులను అనుసరించే న్యాయ సూత్రం. Art.141 ప్రకారం SC తీర్పులు అన్ని కోర్టులకు బైండింగ్."),
    (5,
     'hard',
     'When can SC overrule its own earlier judgment?\nతెలుగు: SC తన స్వంత తీర్పును ఎప్పుడు రద్దు చేయగలదు?',
     'Never / ఎప్పుడూ చేయలేదు',
     "Only with President's permission / కేవలం రాష్ట్రపతి అనుమతితో",
     'At its discretion, especially in constitutional matters / వివేచన (Discretion) ఆధారంగా, ముఖ్యంగా Constitutional Bench తీర్పులలో',
     "Only on Parliament's direction / పార్లమెంట్ సూచన మేరకు మాత్రమే",
     'c',
     'SC not bound by its own decisions — unlike UK. It may overrule via a larger constitutional bench. / SC తన స్వంత తీర్పులకు కట్టుబడి ఉండవలసిన అవసరం లేదు — Stare Decisis SC పై బైండింగ్ కాదు (England వలె కాదు). SC ముఖ్యమైన రాజ్యాంగ విషయాలలో Constitutional Bench ద్వారా తన పూర్వ తీర్పులను రద్దు చేయవచ్చు.'),
    (5,
     'medium',
     'What does Art.144 state?\nతెలుగు: Art.144 అంటే ఏమిటి?',
     "SC judges' salaries / SC న్యాయమూర్తుల జీతాలు",
     'All civil and judicial authorities must act in aid of SC / SC ఆదేశాలకు అన్ని పౌర మరియు న్యాయ అధికారులు సహాయం చేయాలి',
     "SC's seat / SC సీటు",
     "SC's record keeping / SC రికార్డుల నిర్వహణ",
     'b',
     'Art.144: All civil and judicial authorities in India shall act in aid of the Supreme Court. / Art.144: భారతదేశంలో అన్ని పౌర మరియు న్యాయ అధికారులు SC ఆదేశాలకు సహాయం చేయాలి.'),
    (5,
     'medium',
     'Who determines the number of SC judges?\nతెలుగు: SC న్యాయమూర్తి సంఖ్య నిర్ణయించే అధికారం ఎవరికి ఉంది?',
     'President / రాష్ట్రపతి',
     'CJI / ప్రధాన న్యాయమూర్తి',
     'Parliament / పార్లమెంట్',
     'Union Cabinet / కేంద్ర మంత్రిమండలి',
     'c',
     'Art.124(1): Parliament by law may increase the number of SC judges. Currently 34 (CJI + 33). / Art.124(1): SC న్యాయమూర్తుల సంఖ్యను పార్లమెంట్ చట్టం ద్వారా పెంచవచ్చు. 2019 లో 34 కి పెంచారు.'),
    (5,
     'hard',
     'What is Art.129?\nతెలుగు: Art.129 అంటే ఏమిటి?',
     "Declares SC as Court of Record / SC ని 'రికార్డు కోర్టు'గా ప్రకటిస్తుంది",
     "SC's seat / SC సీటు",
     'CJI appointment / CJI నియామకం',
     'SC original jurisdiction / SC మూల అధికార పరిధి',
     'a',
     "Art.129: SC is a Court of Record — its judgments are recorded permanently and it has power of contempt of court. / Art.129: SC ఒక 'Court of Record' — దాని తీర్పులు శాశ్వతంగా నమోదవుతాయి మరియు contempt of court అధికారం ఉంది."),
    (5,
     'medium',
     'Who may make Rules of SC under Art.145?\nతెలుగు: Art.145 కింద SC Rules ఎవరు రూపొందించవచ్చు?',
     'Parliament / పార్లమెంట్',
     "SC with President's approval / రాష్ట్రపతి అనుమతితో SC",
     'CJI by own authority / CJI స్వంత అధికారం ద్వారా',
     'Union Law Minister / కేంద్ర న్యాయ మంత్రి',
     'b',
     "Art.145: SC may make rules with President's approval; Art.145(3) — minimum 5 judges to decide questions involving Constitution's interpretation. / Art.145: రాష్ట్రపతి అనుమతితో SC తన విచారణ విధానాన్ని నియంత్రించే నియమాలను రూపొందించవచ్చు. SC మైనారిటీ కేసులు, కోరం నిర్ణయం (Art.145(3) — 5 న్యాయమూర్తులు కోరం) కూడా ఇందులో ఉంది."),
    (6,
     'easy',
     'What is the Collegium System?\nతెలుగు: కొలీజియం వ్యవస్థ అంటే ఏమిటి?',
     'System where judges decide judicial appointments / SC మరియు HC న్యాయమూర్తుల నియామకానికి న్యాయమూర్తులే నిర్ణయించే వ్యవస్థ',
     'Parliament elects judges / పార్లమెంట్ న్యాయమూర్తులను ఎన్నికొనే వ్యవస్థ',
     'President appoints independently / రాష్ట్రపతి స్వతంత్రంగా నియమించే వ్యవస్థ',
     'Transparent public selection / న్యాయమూర్తుల పారదర్శక ఎంపిక',
     'a',
     'Collegium: CJI + 4 senior-most SC judges decide judicial appointments. Not in Constitution — evolved through Second Judges Case (1993). / కొలీజియం వ్యవస్థ: SC యొక్క సీనియర్ న్యాయమూర్తుల సమూహం (CJI + 4 సీనియర్ జడ్జీలు) SC మరియు HC న్యాయమూర్తులను నిర్ణయిస్తుంది. రాజ్యాంగంలో నేరుగా లేదు — Second Judges Case (1993) తీర్పు ద్వారా వచ్చింది.'),
    (6,
     'medium',
     'Collegium system established through which case?\nతెలుగు: కొలీజియం వ్యవస్థ ఏ కేసు ద్వారా స్థాపించబడింది?',
     'Kesavananda Bharati Case 1973',
     'Second Judges Case 1993',
     'S.R. Bommai Case 1994',
     'Minerva Mills Case 1980',
     'b',
     "Second Judges Case 1993: 9-judge bench — 'consultation' means 'concurrence'; established collegium supremacy. / Second Judges Case (Supreme Court Advocates-on-Record Association v. Union of India, 1993): SC 9-జడ్జీల బెంచ్ CJI 'primacy' సూత్రాన్ని నిర్ణయించింది — 'consultation' అంటే 'concurrence'."),
    (6,
     'medium',
     'What did the First Judges Case (1981) decide?\nతెలుగు: మొదటి న్యాయమూర్తుల కేసు (First Judges Case, 1981) ఏమి తేల్చింది?',
     'Collegium has primacy / కొలీజియం ప్రాధాన్యత ఉంది',
     'Executive has primacy / కార్యనిర్వాహకుడికి (Executive) ప్రాధాన్యత ఉంది',
     'CJI alone decides / CJI మాత్రమే నిర్ణయిస్తారు',
     'Parliament decides / పార్లమెంట్ నిర్ణయిస్తుంది',
     'b',
     "First Judges Case 1981: Executive primacy in appointments. Overruled by Second Judges Case 1993. / First Judges Case (1981): SC 'consultation' అంటే 'concurrence' కాదు అని తేల్చింది — అంటే ప్రభుత్వం (Executive) కి ప్రాధాన్యత ఉంది. Second Judges Case (1993) దీన్ని తిరగేసింది."),
    (6,
     'hard',
     'When did SC strike down NJAC?\nతెలుగు: NJAC (National Judicial Appointments Commission) ఏ సంవత్సరంలో SC రద్దు చేసింది?',
     '2010',
     '2013',
     '2015',
     '2018',
     'c',
     'SC struck down 99th Amendment + NJAC Act in 2015 — Fourth Judges Case — collegium system restored. / 2015లో SC 99వ రాజ్యాంగ సవరణ మరియు NJAC చట్టాన్ని రద్దు చేసింది — కొలీజియం వ్యవస్థను పునరుద్ధరించింది. Fourth Judges Case (Supreme Court Advocates-on-Record v. UOI, 2015).'),
    (6,
     'medium',
     'How many members in collegium for HC judge appointments?\nతెలుగు: HC న్యాయమూర్తుల నియామకంలో కొలీజియంలో ఎంత మంది ఉంటారు?',
     'CJI + 2 senior SC judges',
     'CJI + 4 senior SC judges',
     'CJI + Chief Justice of that HC',
     'CJI + 2 senior SC judges + Chief Justice of that HC',
     'a',
     'For HC appointments: CJI + 2 senior SC judges (3-member). For SC appointments: CJI + 4 senior SC judges (5-member). / HC న్యాయమూర్తుల నియామకానికి: CJI + 2 సీనియర్ SC న్యాయమూర్తులు (3-member collegium). SC న్యాయమూర్తుల నియామకానికి: CJI + 4 సీనియర్ SC న్యాయమూర్తులు (5-member collegium).'),
    (6,
     'hard',
     'If government returns collegium recommendation twice?\nతెలుగు: కొలీజియం సిఫారసును ప్రభుత్వం రెండుసార్లు తిరిగి పంపిస్తే ఏమవుతుంది?',
     'Recommendation lapses / సిఫారసు రద్దవుతుంది',
     'Collegium must reconsider / కొలీజియం నిర్ణయం తీసుకోవాలి',
     'Collegium gives new name / కొలీజియం సిఫారసు రద్దు చేసి కొత్త పేరు ఇవ్వాలి',
     'Government bound to appoint if collegium reiterates / కొలీజియం పునరావృతంగా సిఫారసు చేస్తే ప్రభుత్వం నియమించాలి',
     'd',
     'Per Second/Third Judges Cases: if collegium reiterates recommendation, government is bound to appoint. / Third Judges Case (1998) మరియు Second Judges Case (1993) ప్రకారం: కొలీజియం సిఫారసు పునరావృతంగా పంపినపుడు ప్రభుత్వం నియమించాల్సి ఉంటుంది.'),
    (6,
     'medium',
     'What is the Memorandum of Procedure?\nతెలుగు: Memorandum of Procedure (MoP) అంటే ఏమిటి?',
     'Removal procedure / న్యాయమూర్తుల తొలగింపు విధానం',
     'Document guiding judicial appointment procedure / SC మరియు HC న్యాయమూర్తుల నియామక విధానాన్ని నిర్దేశించే పత్రం',
     "Procedure for seeking President's opinion / రాష్ట్రపతి అభిప్రాయం కోరే విధానం",
     'SC record-keeping rules / SC రికార్డుల నిర్వహణ నిబంధనలు',
     'b',
     'MoP: document outlining procedure for judicial appointments — agreed between collegium and government. / MoP: SC మరియు HC న్యాయమూర్తుల నియామక విధానాన్ని నిర్దేశించే పత్రం — కొలీజియం మరియు ప్రభుత్వం మధ్య అంగీకారంపై ఆధారపడింది.'),
    (6,
     'hard',
     'What did the Third Judges Case (1998 Presidential Reference) clarify?\nతెలుగు: Third Judges Case (1998) ప్రెసిడెన్షియల్ రిఫరెన్స్ ఏమి స్పష్టం చేసింది?',
     'Collegium alone decides / కొలీజియం ఒక్కడే నిర్ణయిస్తారు',
     'CJI + 4 senior judges form collegium for SC appointments / SC న్యాయమూర్తుల నియామకానికి CJI + 4 సీనియర్ జడ్జీలు కొలీజియంగా పనిచేస్తారు',
     'NJAC is valid / NJAC చట్టబద్ధంగా ఉంది',
     'President has final say / రాష్ట్రపతికి తుది అధికారం',
     'b',
     'Third Judges Case 1998 (Presidential Reference): 9-judge bench — collegium for SC = CJI + 4 senior-most SC judges; for HC = CJI + 2 senior-most. / Third Judges Case (1998 Presidential Reference): SC 9-జడ్జీల బెంచ్ CJI + 4 సీనియర్ SC న్యాయమూర్తులు (5 మంది) = కొలీజియం SC న్యాయమూర్తుల నియామకానికి అని స్పష్టపరించింది. HC కి: CJI + 2 సీనియర్ జడ్జీలు.'),
    (7,
     'easy',
     'SC provisions (Art.124–147) are in which Part?\nతెలుగు: SC అనుచ్ఛేద పరిధి (Art.124 to Art.147) ఏ భాగంలో ఉంది?',
     'Part IV',
     'Part V',
     'Part VI',
     'Part VII',
     'b',
     'SC provisions (Art.124–147) in Part V (The Union). / Art.124-147 Part V లో ఉంది — The Union (Union Judiciary). Part VI = States judiciary (HC).'),
    (7,
     'medium',
     'SC Rules under Art.145 made with whose approval?\nతెలుగు: Art.145 ప్రకారం SC రూల్స్ ఎవరి అనుమతితో తయారవుతాయి?',
     'Parliament / పార్లమెంట్',
     'President / రాష్ట్రపతి',
     'Union Cabinet / కేంద్ర మంత్రిమండలి',
     'Union Law Minister / కేంద్ర న్యాయ మంత్రి',
     'b',
     "Art.145: SC may, with President's approval, make rules regulating practice and procedure of court. / Art.145: SC రాష్ట్రపతి అనుమతితో తన విచారణ విధానానికి సంబంధించిన నిబంధనలు తయారు చేయగలదు."),
    (7,
     'hard',
     'Article that finalises SC decrees?\nతెలుగు: SC తీర్పు ఖచ్చితం చేసే (Finality of SC decree) అనుచ్ఛేదం ఏది?',
     'Art.140',
     'Art.141',
     'Art.142',
     'Art.143',
     'c',
     "Art.142: SC decrees/orders enforceable throughout India; SC may pass any order for 'doing complete justice'. / Art.142: SC తీర్పులు/ఆదేశాలు అమలు కోసం దేశంలో ఎక్కడైనా అమలు చేయవచ్చు; 'complete justice' కోసం ఏ ఆదేశమైనా ఇవ్వవచ్చు."),
    (7,
     'medium',
     'SC contempt power under which Article?\nతెలుగు: SC contempt of court శిక్ష అనుచ్ఛేదం ఏది?',
     'Art.128',
     'Art.129',
     'Art.130',
     'Art.131',
     'b',
     "Art.129: As a Court of Record, SC has power to punish for contempt of court. / Art.129: SC 'Court of Record' గా contempt of court కి శిక్ష విధించే అధికారం కలిగి ఉంది."),
    (7,
     'medium',
     'SC propounded Basic Structure doctrine in which case?\nతెలుగు: SC ఏ కేసులో మౌలిక నిర్మాణం (Basic Structure) సిద్ధాంతాన్ని ప్రతిపాదించింది?',
     'Golaknath Case 1967',
     'Minerva Mills Case 1980',
     'Kesavananda Bharati Case 1973',
     'Maneka Gandhi Case 1978',
     'c',
     "Kesavananda Bharati (1973): 13-judge bench — Parliament cannot amend the Basic Structure of the Constitution. / Kesavananda Bharati v. State of Kerala (1973): 13-జడ్జీల బెంచ్ 'Basic Structure Doctrine' ప్రతిపాదించింది — పార్లమెంట్ రాజ్యాంగ మూల నిర్మాణాన్ని సవరించలేదు."),
    (7,
     'easy',
     'When was the Supreme Court of India established?\nతెలుగు: SC ను జాతీయ రాజధానిలో ఏ సంవత్సరం స్థాపించారు?',
     '1935',
     '1947',
     '1950',
     '1952',
     'c',
     'SC established on 26 January 1950 — the day the Constitution came into force. / భారత సర్వోన్నత న్యాయస్థానం 26 జనవరి 1950 న స్థాపించబడింది — భారత రాజ్యాంగం అమలులోకి వచ్చిన రోజున.'),
    (7,
     'medium',
     'Who issues the warrant of appointment for SC judges?\nతెలుగు: SC న్యాయమూర్తుల నియామక లేఖ (Warrant of Appointment) ఎవరు జారీ చేస్తారు?',
     'CJI / ప్రధాన న్యాయమూర్తి',
     'Union Law Minister / కేంద్ర న్యాయ మంత్రి',
     'President / రాష్ట్రపతి',
     'Joint Secretary / సంయుక్త కార్యదర్శి',
     'c',
     'President issues the warrant of appointment for SC judges (Art.124(2)). / SC న్యాయమూర్తుల నియామక వారెంట్ రాష్ట్రపతి జారీ చేస్తారు — Art.124(2) ప్రకారం.'),
    (7,
     'hard',
     "Who can extend SC's jurisdiction under Art.138?\nతెలుగు: Art.138 ప్రకారం SC అధికార పరిధిని ఎవరు విస్తరించవచ్చు?",
     'Union Cabinet / కేంద్ర మంత్రిమండలి',
     'Parliament / పార్లమెంట్',
     'President / రాష్ట్రపతి',
     'SC itself / SC తానే',
     'b',
     'Art.138: Parliament may by law extend the jurisdiction and powers of SC with respect to any matter. / Art.138: పార్లమెంట్ చట్టం ద్వారా SC అధికార పరిధిని విస్తరించవచ్చు.'),
]


def _seed_polity_ch20_notes_inner(conn, db_exec_fn, row_to_dict_fn, use_postgres, force=False):
    ph = '%s' if use_postgres else '?'
    existing = db_exec_fn(conn,
        f"SELECT id FROM study_notes WHERE subject={ph} AND topic={ph} AND chapter_num={ph}",
        (_SUBJECT, _TOPIC, _CH))
    row = row_to_dict_fn(existing.fetchone())

    if row and not force:
        return row['id']

    import json
    sections_json = json.dumps(_SECTIONS, ensure_ascii=False)

    if row:
        db_exec_fn(conn,
            f"UPDATE study_notes SET chapter_title_te={ph}, chapter_title_en={ph}, "
            f"pages_ref={ph}, sections_json={ph} "
            f"WHERE subject={ph} AND topic={ph} AND chapter_num={ph}",
            (_TITLE_TE, _TITLE_EN, _PAGES, sections_json, _SUBJECT, _TOPIC, _CH))
        return row['id']
    else:
        db_exec_fn(conn,
            f"INSERT INTO study_notes (subject, topic, chapter_num, chapter_title_te, "
            f"chapter_title_en, pages_ref, sections_json) VALUES ({ph},{ph},{ph},{ph},{ph},{ph},{ph})",
            (_SUBJECT, _TOPIC, _CH, _TITLE_TE, _TITLE_EN, _PAGES, sections_json))
        cur2 = db_exec_fn(conn,
            f"SELECT id FROM study_notes WHERE subject={ph} AND topic={ph} AND chapter_num={ph}",
            (_SUBJECT, _TOPIC, _CH))
        return row_to_dict_fn(cur2.fetchone())['id']


def _seed_polity_ch20_mcqs_inner(conn, db_exec_fn, row_to_dict_fn, use_postgres):
    ph = '%s' if use_postgres else '?'
    cur = db_exec_fn(conn,
        f"SELECT id FROM study_notes WHERE subject={ph} AND topic={ph} AND chapter_num={ph}",
        (_SUBJECT, _TOPIC, _CH))
    note = row_to_dict_fn(cur.fetchone())
    if not note:
        return
    note_id = note['id']

    existing = db_exec_fn(conn,
        f"SELECT COUNT(*) FROM chapter_mcqs WHERE study_note_id={ph}", (note_id,))
    if list(existing.fetchone())[0] > 0:
        return

    diff_map = {"easy": 1, "medium": 2, "hard": 3, "toughest": 4, 1: 1, 2: 2, 3: 3, 4: 4}

    for row in _MCQS:
        sec_idx  = row[0]
        diff_str = row[1]
        q_te     = row[2]
        opt_a    = row[3]
        opt_b    = row[4]
        opt_c    = row[5]
        opt_d    = row[6]
        correct  = row[7]
        expl     = row[8]
        exam_type = row[9] if len(row) > 9 else 'General'
        if not exam_type:
            exam_type = 'General'

        diff_int = diff_map.get(diff_str, 1)
        db_exec_fn(conn,
            f"""INSERT INTO chapter_mcqs
                (study_note_id, section_idx, difficulty, exam_type,
                 q_te, opt_a, opt_b, opt_c, opt_d, correct, explanation_te)
                VALUES ({ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph})""",
            (note_id, sec_idx, diff_int, exam_type,
             q_te, opt_a, opt_b, opt_c, opt_d, correct, expl))
