# seed_polity_ch17.py
# Chapter 17 — Prime Minister & Council of Ministers
# Total Sections: 8 | Total MCQs: 65 | PYQs: 6
# Sections:
#   0 — Appointment & Qualifications of PM (10 MCQs)
#   1 — Powers & Functions of PM (10 MCQs)
#   2 — Council of Ministers — Composition & Categories (8 MCQs)
#   3 — Collective Responsibility & Individual Responsibility (8 MCQs)
#   4 — Role of Cabinet (8 MCQs)
#   5 — PM & President Relationship (7 MCQs)
#   6 — Kitchen Cabinet / Inner Cabinet (7 MCQs)
#   7 — Miscellaneous / Constitutional Provisions (7 MCQs)

_CH = 17
_SUBJECT = 'GK'
_TOPIC   = 'Indian_Polity'
_TITLE_TE = 'ప్రధానమంత్రి మరియు మంత్రిమండలి'
_TITLE_EN = 'Prime Minister & Council of Ministers'
_PAGES    = 'Ch.17 (Lakshmikanth)'

_NOTES_HTML = '''<p>చాప్టర్ 17 — ప్రధానమంత్రి మరియు మంత్రిమండలి. భారత రాజ్యాంగంలో అనుచ్ఛేదాలు 74–75 కేంద్ర మంత్రిమండలికి సంబంధించినవి. PM దేశ వాస్తవిక కార్యనిర్వాహకుడు (real executive). మంత్రిమండలి సమిష్టి బాధ్యత (collective responsibility) లోక్‌సభకు ఉంటుంది.</p>'''

_SECTIONS = [
    "PM నియామకం & అర్హతలు",
    "PM అధికారాలు & విధులు",
    "మంత్రిమండలి — రకాలు & సంఖ్య",
    "సమిష్టి & వ్యక్తిగత బాధ్యత",
    "కేబినెట్ పాత్ర",
    "PM & రాష్ట్రపతి సంబంధం",
    "కిచెన్ కేబినెట్ / అంతరంగ మండలి",
    "విభిన్న రాజ్యాంగ నిబంధనలు",
]

_MCQS = [    (0,
     'easy',
     'Who appoints the Prime Minister of India?\nతెలుగు: భారత ప్రధానమంత్రిని నియమించే అధికారం ఎవరికి ఉంది?',
     'Lok Sabha Speaker / లోక్\u200cసభ స్పీకర్',
     'President / రాష్ట్రపతి',
     'Chief Justice of Supreme Court / సుప్రీం కోర్ట్ ప్రధాన న్యాయమూర్తి',
     'Chairman of Rajya Sabha / ఎగువ సభ చైర్మన్',
     'b',
     'Under Article 75(1), the Prime Minister is appointed by the President. / అనుచ్ఛేదం 75(1) ప్రకారం ప్రధానమంత్రిని రాష్ట్రపతి నియమిస్తారు.'),
    (0,
     'easy',
     'PM must be a member of which House?\nతెలుగు: ప్రధానమంత్రి అర్హత కోసం ఏ సభకు సభ్యుడిగా ఉండాలి?',
     'Only Rajya Sabha / రాజ్యసభ మాత్రమే',
     'Only Lok Sabha / లోక్\u200cసభ మాత్రమే',
     'Either House of Parliament / పార్లమెంటు ఏ సభైనా',
     'State Legislative Assembly / విధానసభ',
     'c',
     'PM can be a member of either House, though in practice they are from Lok Sabha. / ప్రధానమంత్రి పార్లమెంటు రెండు సభలలో దేనిలో అయినా సభ్యుడిగా ఉండవచ్చు, కానీ ఆచరణలో లోక్\u200cసభ సభ్యుడిగా ఉంటారు.'),
    (0,
     'medium',
     'If a non-MP is appointed PM, within how many months must they become a Parliament member?\nతెలుగు: పార్లమెంటు సభ్యుడు కాని వ్యక్తి ప్రధానమంత్రిగా నియమించబడినట్లయితే, ఎంత కాలంలో పార్లమెంటు సభ్యుడవ్వాలి?',
     '3 months / 3 నెలలు',
     '6 months / 6 నెలలు',
     '9 months / 9 నెలలు',
     '12 months / 12 నెలలు',
     'b',
     'Under Art.75(5), within 6 months else office is lost. / అనుచ్ఛేదం 75(5) ప్రకారం 6 నెలల లోపు పార్లమెంటు సభ్యుడవ్వాలి, లేదా పదవి కోల్పోతారు.'),
    (0,
     'medium',
     'What is the term of office of the Prime Minister?\nతెలుగు: ప్రధానమంత్రి పదవి కాలం ఎంత?',
     'Fixed 5 years / 5 సంవత్సరాలు నిర్ణయించబడినవి',
     'At the pleasure of President / రాష్ట్రపతి ఇష్టానుసారం',
     'As long as LS confidence exists / లోక్\u200cసభ విశ్వాసం ఉన్నంత కాలం',
     'Till RS resolution / రాజ్యసభ తీర్మానం వరకు',
     'c',
     'PM holds office as long as commanding LS majority. / PM పదవి కాలం నిర్ణయించబడలేదు — లోక్\u200cసభ విశ్వాసం ఉన్నంత కాలం పదవిలో ఉంటారు.'),
    (0,
     'medium',
     'Who administers the oath of office to the PM?\nతెలుగు: ప్రధానమంత్రి ప్రమాణ స్వీకారం చేయించే వ్యక్తి ఎవరు?',
     'Lok Sabha Speaker / లోక్\u200cసభ స్పీకర్',
     'CJI / సుప్రీం కోర్ట్ CJI',
     'President / రాష్ట్రపతి',
     'Vice-President / ఉప రాష్ట్రపతి',
     'c',
     'Under Art.75(4), President administers oath. / అనుచ్ఛేదం 75(4) ప్రకారం రాష్ట్రపతి ప్రమాణ స్వీకారం చేయిస్తారు.'),
    (0,
     'hard',
     'Under Art.75, total ministers shall not exceed what % of LS strength?\nతెలుగు: అనుచ్ఛేదం 75 ప్రకారం మంత్రుల సంఖ్య లోక్\u200cసభ బలంలో ఎంత శాతానికి మించరాదు?',
     '10%',
     '15%',
     '20%',
     '25%',
     'b',
     '91st Amendment 2003: total ministers ≤ 15% of total LS strength. / 91వ రాజ్యాంగ సవరణ చట్టం 2003 ద్వారా మొత్తం మంత్రిమండలి సభ్యులు లోక్\u200cసభ మొత్తం సభ్యుల 15%కి మించరాదు.',
     'APPSC'),
    (0,
     'hard',
     "Articles dealing with PM's position in Constitution?\nతెలుగు: రాజ్యాంగంలో ప్రధానమంత్రి హోదాను ప్రస్తావించే అనుచ్ఛేదాలు ఏవి?",
     'Art.52–54 / అనుచ్ఛేదం 52–54',
     'Art.74–75 / అనుచ్ఛేదం 74–75',
     'Art.78–79 / అనుచ్ఛేదం 78–79',
     'Art.85–86 / అనుచ్ఛేదం 85–86',
     'b',
     'Art.74: CoM constitution; Art.75: PM & ministers appointment/responsibility. / అనుచ్ఛేదం 74: మంత్రిమండలి నిర్మాణం. అనుచ్ఛేదం 75: PM నియామకం, మంత్రుల నియామకం, బాధ్యత.'),
    (0,
     'medium',
     'Can Prime Minister be a Rajya Sabha member?\nతెలుగు: ప్రధానమంత్రి రాజ్యసభ సభ్యుడిగా ఉండవచ్చా?',
     'Yes, RS is upper house / అవున, ఎందుకంటే రాజ్యసభ ఉన్నత సభ',
     'No, must be LS member / కాదు, LS సభ్యుడిగా ఉండాలి',
     "Yes, Constitution doesn't specify which House / అవున, రాజ్యాంగంలో ఏ సభకు చెందాలో పేర్కొనలేదు",
     'Yes but must contest LS within 6 months / అవున, కానీ 6 నెలల్లో LS ఎన్నికల్లో నిలబడాలి',
     'c',
     "Constitution doesn't specify LS or RS; PM must be a member of Parliament. Dr. Manmohan Singh served as PM from RS (2004–2014). / రాజ్యాంగం PM ఏ సభకు చెందాలో నిర్దేశించలేదు — పార్లమెంటు సభ్యుడిగా ఉంటే సరిపోతుంది. డా. మన్మోహన్ సింగ్ (2004–2014) రాజ్యసభ సభ్యుడిగా PM పదవిలో ఉన్నారు."),
    (1,
     'easy',
     'What role does PM play in government?\nతెలుగు: ప్రధానమంత్రి ప్రభుత్వంలో ఏ పాత్ర పోషిస్తారు?',
     'Constitutional head / రాజ్యాంగపరమైన అధిపతి',
     'Real executive / నిజమైన కార్యనిర్వాహకుడు',
     'Mere advisor / కేవలం సలహాదారు',
     'Judicial head / న్యాయ అధిపతి',
     'b',
     'President is nominal head; PM is real executive. / రాష్ట్రపతి రాజ్యాంగపరమైన అధిపతి; PM నిజమైన (real) కార్యనిర్వాహకుడు.'),
    (1,
     'medium',
     'Which article allows PM to advise summoning/proroguing Parliament?\nతెలుగు: PM అధికారాల్లో పార్లమెంటు సమావేశం (session) పెట్టే, వాయిదా వేసే సలహా ఇచ్చే అనుచ్ఛేదం ఏది?',
     'Art.74 / అనుచ్ఛేదం 74',
     'Art.85 / అనుచ్ఛేదం 85',
     'Art.108 / అనుచ్ఛేదం 108',
     'Art.110 / అనుచ్ఛేదం 110',
     'b',
     "వాయిదా వేస్తారు. / Art.85: President summons/prorogues Parliament on PM's advice. / అనుచ్ఛేదం 85: రాష్ట్రపతి PM సలహాపై పార్లమెంటు సమావేశాలు ఏర్పాటు చేస్తారు"),
    (1,
     'medium',
     "What is PM's role in appointment of Union Ministers?\nతెలుగు: ప్రధానమంత్రి కేంద్ర మంత్రుల నియామకంలో ఏ పాత్ర పోషిస్తారు?",
     'Directly appoints / నేరుగా నియమిస్తారు',
     'Appoints with Parliament approval / పార్లమెంటు ఆమోదం తో నియమిస్తారు',
     'Recommends; President appoints / మంత్రులను సిఫారసు చేస్తారు, రాష్ట్రపతి నియమిస్తారు',
     'Only power to remove / మంత్రులను తొలగించే అధికారం మాత్రమే ఉంది',
     'c',
     "Art.75(1): President appoints ministers on PM's advice. PM also allocates portfolios. / అనుచ్ఛేదం 75(1): PM సిఫారసుపై రాష్ట్రపతి మంత్రులను నియమిస్తారు. PM పోర్ట్\u200cఫోలియోలు కేటాయిస్తారు."),
    (1,
     'medium',
     'Who chairs NITI Aayog?\nతెలుగు: నీతి ఆయోగ్\u200cకు అధ్యక్షుడు ఎవరు?',
     'President / రాష్ట్రపతి',
     'Vice-President / ఉప రాష్ట్రపతి',
     'Prime Minister / ప్రధానమంత్రి',
     'Finance Minister / ఆర్థిక మంత్రి',
     'c',
     'PM is the ex-officio Chairman of NITI Aayog. / PM నీతి ఆయోగ్ (National Institution for Transforming India) అధ్యక్షుడు.'),
    (1,
     'hard',
     'Under Art.74(2), what can courts do regarding Cabinet advice to President?\nతెలుగు: అనుచ్ఛేదం 74(2) ప్రకారం మంత్రిమండలి సలహా విషయంలో కోర్టులు ఏం చేయగలవు?',
     'Can fully review / పూర్తిగా సమీక్షించగలవు',
     'Only on RS petition / కేవలం రాజ్యసభ అభ్యర్థనపై సమీక్షించగలవు',
     'Courts cannot enquire into advice tendered by ministers / మంత్రులు ఇచ్చిన సలహా విచారించే అధికారం లేదు',
     "With PM's prior permission / PM ముందస్తు అనుమతితో సమీక్షించగలవు",
     'c',
     'Art.74(2): No court shall inquire into the advice tendered by ministers to the President — CoM advice is beyond judicial review. / అనుచ్ఛేదం 74(2): రాష్ట్రపతికి మంత్రులు ఇచ్చిన సలహా విచారించే అధికారం ఏ కోర్టుకూ లేదు — మంత్రిమండలి సలహా న్యాయ సమీక్షకు అతీతం.'),
    (1,
     'easy',
     'Highest decision-making body chaired by PM?\nతెలుగు: PM అధ్యక్షతన సమావేశమయ్యే అత్యున్నత నిర్ణయాధికార సంస్థ ఏది?',
     'Coordination Committee / అనుసందాన సంఘం',
     'Cabinet / కేబినెట్',
     'National Security Council / జాతీయ భద్రతా మండలి',
     'Committee on Economic Affairs / ఆర్థిక వ్యవహారాల కమిటీ',
     'b',
     'Cabinet chaired by PM is the supreme decision-making body. / కేబినెట్ PM అధ్యక్షతన సమావేశమవుతుంది మరియు దేశంలో అత్యున్నత నిర్ణయాధికారసంస్థగా పని చేస్తుంది.'),
    (1,
     'medium',
     'Under which Article does PM advise the President?\nతెలుగు: ప్రధానమంత్రి ఏ అనుచ్ఛేదం ద్వారా రాష్ట్రపతికి సలహా ఇస్తారు?',
     'Art.74 / అనుచ్ఛేదం 74',
     'Art.75 / అనుచ్ఛేదం 75',
     'Art.76 / అనుచ్ఛేదం 76',
     'Art.77 / అనుచ్ఛేదం 77',
     'a',
     'Art.74(1): There shall be a CoM with PM at head to aid and advise President. / అనుచ్ఛేదం 74(1): రాష్ట్రపతికి సహాయం చేయడానికి మరియు సలహా ఇవ్వడానికి PM నేతృత్వంలో మంత్రిమండలి ఉంటుంది.'),
    (1,
     'hard',
     "Who described PM as 'keystone of the Cabinet arch'?\nతెలుగు: PM 'ప్రభుత్వ ముఖ్య' మరియు 'కేబినెట్ ముఖ్య' — ఈ రెండు పాత్రలు ఏ పండితుడు అభివర్ణించారు?",
     'Jawaharlal Nehru / జవహర్\u200cలాల్ నెహ్రూ',
     'Albeig / ఆల్\u200cబిగ్',
     'N.A. Palkhivala / ఎన్.ఎ. పాల్ఖీవాలా',
     'Radhakumar / రాధాకుమార్',
     'b',
     "Albeig: 'PM is the keystone of the Cabinet arch.' / Albeig అన్నారు: 'PM is the keystone of the Cabinet arch' — PM లేకుండా మంత్రిమండలి నిలబడదు."),
    (2,
     'easy',
     'How many categories of ministers are in Union CoM?\nతెలుగు: కేంద్ర మంత్రిమండలిలో ఎన్ని వర్గాల మంత్రులు ఉంటారు?',
     '2',
     '3',
     '4',
     '5',
     'b',
     'Three categories: Cabinet Ministers, Ministers of State, Deputy Ministers. / మూడు వర్గాలు: 1) కేబినెట్ మంత్రులు, 2) రాష్ట్ర మంత్రులు, 3) డిప్యూటీ మంత్రులు.'),
    (2,
     'medium',
     'Main difference between Cabinet Ministers and Ministers of State?\nతెలుగు: కేబినెట్ మంత్రులు మరియు రాష్ట్ర మంత్రులకు ప్రధాన తేడా ఏమిటి?',
     'Salaries / జీతాలు',
     'Right to attend Cabinet meetings / కేబినెట్ సమావేశాలలో పాల్గొనే హక్కు',
     'Party affiliation / పార్టీ అనుబంధం',
     'Term of office / పదవీ కాలం',
     'b',
     "Cabinet Ministers attend Cabinet meetings; MoS generally don't. / కేబినెట్ మంత్రులు కేబినెట్ సమావేశాలకు హాజరవుతారు; రాష్ట్ర మంత్రులు సాధారణంగా హాజరవ్వరు (వారి విభాగానికి సంబంధించిన అంశాలు తప్ప)."),
    (2,
     'medium',
     "Where is 'Cabinet' defined in the Constitution?\nతెలుగు: రాజ్యాంగంలో 'కేబినెట్' అనే పదాన్ని ఎక్కడ నిర్వచించారు?",
     'Art.74 / అనుచ్ఛేదం 74',
     'Art.352 / అనుచ్ఛేదం 352',
     'Art.352(3) via 44th Amendment / 44వ సవరణ చేర్పు ద్వారా అనుచ్ఛేదం 352(3)',
     'Art.356 / అనుచ్ఛేదం 356',
     'c',
     "44th Amendment 1978: 'Cabinet' defined in Art.352(3) as PM + Cabinet Ministers. / 44వ రాజ్యాంగ సవరణ 1978: అనుచ్ఛేదం 352(3)లో 'Cabinet' అనే పదాన్ని నిర్వచించారు — PM + కేబినెట్ మంత్రులు."),
    (2,
     'hard',
     '15% ceiling under 91st Amendment is based on strength of which House?\nతెలుగు: 91వ రాజ్యాంగ సవరణ 2003 కింద మంత్రిమండలి 15% పరిమితికి ఏ సభ బలం ఆధారంగా?',
     'Rajya Sabha / రాజ్యసభ',
     'Lok Sabha / లోక్\u200cసభ',
     'Total of both Houses / రెండు సభల మొత్తం',
     'Winning party members / విజయం సాధించిన పార్టీ సభ్యుల సంఖ్య',
     'b',
     '91st Amendment: total ministers ≤ 15% of total LS membership (also applies to states). / 91వ సవరణ: మొత్తం మంత్రులు లోక్\u200cసభ మొత్తం సభ్యుల 15%కి మించరాదు (ఇది రాష్ట్రాలకు కూడా వర్తిస్తుంది).'),
    (2,
     'medium',
     "Is 'Parliamentary Secretary' a constitutional post?\nతెలుగు: పార్లమెంటరీ సెక్రటరీ (Parliamentary Secretary) అనే పదవి రాజ్యాంగంలో ఉందా?",
     'Yes, in Art.75 / అవును, అనుచ్ఛేదం 75లో ఉంది',
     'Yes, in Art.77 / అవును, అనుచ్ఛేదం 77లో ఉంది',
     'No, extra-constitutional / లేదు, రాజ్యాంగేతర పదవి',
     'Yes, in Art.88 / అవును, అనుచ్ఛేదం 88లో ఉంది',
     'c',
     'Parliamentary Secretary is not a constitutional post — extra-constitutional. / Parliamentary Secretary పదవి రాజ్యాంగంలో లేదు — ఇది రాజ్యాంగేతర (extra-constitutional) పదవి.'),
    (2,
     'easy',
     'Cabinet Ministers head one ministry — their rank is?\nతెలుగు: కేబినెట్ మంత్రులు ఒక్కో మంత్రిత్వ శాఖకు అధిపతిగా ఉంటారు — వీరి హోదా ఏమిటి?',
     'Junior Minister / జూనియర్ మంత్రి',
     'Senior Minister / సీనియర్ మంత్రి',
     'Cabinet rank / కేబినెట్ రాంక్',
     'MoS level / రాష్ట్ర మంత్రి స్థాయి',
     'c',
     'Cabinet Ministers are the highest rank — independently head ministries. / కేబినెట్ మంత్రులు అత్యున్నత స్థాయి మంత్రులు; స్వతంత్రంగా మంత్రిత్వ శాఖలు నిర్వహిస్తారు.'),
    (2,
     'hard',
     'Can MoS with independent charge attend Cabinet meetings?\nతెలుగు: స్వతంత్ర బాధ్యత గల రాష్ట్ర మంత్రి (MoS independent charge) కేబినెట్ సమావేశాలకు హాజరవ్వగలరా?',
     'Never / ఎప్పుడూ హాజరవ్వలేరు',
     'Always / ఎల్లప్పుడూ హాజరవ్వగలరు',
     'Only when invited for relevant matters / తమ విభాగానికి సంబంధించిన అంశాలపై పిలిచినప్పుడు మాత్రమే',
     'With Cabinet approval / కేబినెట్ ఆమోదంతో',
     'c',
     'MoS (IC) may be invited to Cabinet meetings when their portfolio is discussed. / MoS (Independent Charge) తమ పోర్ట్\u200cఫోలియోకు సంబంధించిన అంశాలు చర్చించేటప్పుడు కేబినెట్ సమావేశాలకు పిలవబడవచ్చు.'),
    (2,
     'medium',
     "What is true about 'Deputy Minister' in Union CoM?\nతెలుగు: కేంద్ర మంత్రిమండలిలో 'Deputy Minister' పదవి గురించి ఏది నిజం?",
     'Assist Cabinet Ministers / కేబినెట్ మంత్రులకు సహాయం చేస్తారు',
     'Head independent ministry / స్వతంత్ర మంత్రిత్వ శాఖ నిర్వహిస్తారు',
     'Report directly to PM / PM కి నేరుగా నివేదిస్తారు',
     'Accountable only to RS / రాజ్యసభకు మాత్రమే జవాబుదారీ',
     'a',
     'Deputy Ministers assist Cabinet Ministers; no independent portfolio. / డిప్యూటీ మంత్రులు కేబినెట్ మంత్రులకు సహాయపడతారు; స్వతంత్ర పోర్ట్\u200cఫోలియో ఉండదు.'),
    (3,
     'easy',
     'Collective Responsibility of CoM is to which House?\nతెలుగు: మంత్రిమండలి సమిష్టి బాధ్యత (Collective Responsibility) ఏ సభకు ఉంటుంది?',
     'Rajya Sabha / రాజ్యసభ',
     'Lok Sabha / లోక్\u200cసభ',
     'Both Houses / రెండు సభలకు',
     'President / రాష్ట్రపతికి',
     'b',
     'Art.75(3): CoM is collectively responsible to Lok Sabha. / అనుచ్ఛేదం 75(3): మంత్రిమండలి సమిష్టిగా లోక్\u200cసభకు జవాబుదారీ.'),
    (3,
     'medium',
     'What does collective responsibility mean?\nతెలుగు: సమిష్టి బాధ్యత సూత్రానికి అర్థమేమిటి?',
     'Each minister expresses different policy / ప్రతి మంత్రి వేరే విధానం వ్యక్తం చేయవచ్చు',
     'All Cabinet decisions must be accepted as one / మంత్రిమండలి నిర్ణయాలన్నీ ఒకటిగా ఆమోదించాలి',
     'Only PM is responsible / ప్రధాన మంత్రి మాత్రమే జవాబుదారీ',
     'Ministers separately responsible / మంత్రులు ప్రత్యేకంగా జవాబుదారీ',
     'b',
     'Collective responsibility: all ministers bound by Cabinet decisions — disagree means resign. / సమిష్టి బాధ్యత: మంత్రిమండలి నిర్ణయాలకు అన్ని మంత్రులు బాధ్యులు; నిర్ణయంతో విభేదిస్తే రాజీనామా ఇవ్వాలి.'),
    (3,
     'medium',
     'If no-confidence motion passes in LS, what happens to CoM?\nతెలుగు: లోక్\u200cసభలో అవిశ్వాస తీర్మానం ఆమోదమైతే మంత్రిమండలికి ఏమవుతుంది?',
     'Only one minister resigns / ఒక్క మంత్రి రాజీనామా చేస్తారు',
     'Only PM resigns / PM మాత్రమే రాజీనామా చేస్తారు',
     'Entire CoM must resign / మొత్తం మంత్రిమండలి రాజీనామా చేయాలి',
     'Nothing happens / ఏమీ జరగదు',
     'c',
     'If no-confidence motion passes, entire CoM (including PM) must resign. / అవిశ్వాస తీర్మానం ఆమోదమైతే PM తో పాటు మొత్తం మంత్రిమండలి రాజీనామా చేయాలి — సమిష్టి బాధ్యత సూత్రం.'),
    (3,
     'hard',
     'Individual Responsibility of ministers is in which Article?\nతెలుగు: వ్యక్తిగత బాధ్యత (Individual Responsibility) ఏ అనుచ్ఛేదంలో పేర్కొనబడింది?',
     'Art.74 / అనుచ్ఛేదం 74',
     'Art.75(2) / అనుచ్ఛేదం 75(2)',
     'Art.76 / అనుచ్ఛేదం 76',
     'Art.78 / అనుచ్ఛేదం 78',
     'b',
     'Art.75(2): Ministers hold office during pleasure of President (individual responsibility). / అనుచ్ఛేదం 75(2): మంత్రులు రాష్ట్రపతి సంతోషం ఉన్నంత కాలం పదవిలో ఉంటారు (వ్యక్తిగత బాధ్యత).'),
    (3,
     'medium',
     'A minister who opposes Cabinet decision in public must?\nతెలుగు: మంత్రిమండలి నిర్ణయాన్ని సభలో వ్యతిరేకించే మంత్రి ఏం చేయాలి?',
     'Seek public opinion / ప్రజాభిప్రాయం అడగాలి',
     'Petition Rajya Sabha / రాజ్యసభకు పిటిషన్ వేయాలి',
     'Resign / రాజీనామా చేయాలి',
     'Oppose only in Cabinet meeting / కేబినెట్ మీటింగ్\u200cలో మాత్రమే వ్యతిరేకించాలి',
     'c',
     'Collective responsibility: minister must resign before publicly opposing Cabinet decision. / సమిష్టి బాధ్యత: కేబినెట్ నిర్ణయంతో విభేదించే మంత్రి మొదట రాజీనామా ఇవ్వాలి, తర్వాత వ్యతిరేకించవచ్చు.'),
    (3,
     'easy',
     "Collective responsibility is borrowed from which country's system?\nతెలుగు: మంత్రిమండలి సమిష్టి బాధ్యత సూత్రం ఏ దేశ ప్రభుత్వ విధానానికి చెందినది?",
     'USA / అమెరికా',
     'Britain / బ్రిటన్',
     'France / ఫ్రాన్స్',
     'Canada / కెనడా',
     'b',
     'Collective responsibility is borrowed from the British Westminster system. / సమిష్టి బాధ్యత సూత్రం బ్రిటన్ వెస్ట్\u200cమినిస్టర్ విధానం నుండి తీసుకోబడింది.'),
    (3,
     'hard',
     'Can a minister who is RS member vote in LS on no-confidence motion?\nతెలుగు: రాజ్యసభ సభ్యుడైన మంత్రి అవిశ్వాస తీర్మానంపై లోక్\u200cసభలో ఓటు వేయగలరా?',
     'Yes / అవును',
     'No / లేదు',
     'Only PM / కేవలం PM మాత్రమే',
     "With Speaker's permission / స్పీకర్ అనుమతితో",
     'b',
     'RS member cannot vote in LS — even if a minister. / రాజ్యసభ సభ్యుడు లోక్\u200cసభలో ఓటు వేయలేరు. మంత్రిగా ఉన్నా, లోక్\u200cసభలో ఓటు హక్కు లేదు.'),
    (3,
     'medium',
     'Is CoM responsible to Rajya Sabha?\nతెలుగు: మంత్రిమండలికి రాజ్యసభకు జవాబుదారీ ఉంటుందా?',
     'Yes / అవును',
     'No / లేదు',
     'Partially / కొంత మేరకు',
     'Only after constitutional amendment / రాజ్యాంగ సవరణ తర్వాత మాత్రమే',
     'b',
     'CoM is collectively responsible only to LS — not to RS. / మంత్రిమండలి కేవలం లోక్\u200cసభకు మాత్రమే సమిష్టిగా జవాబుదారీ. రాజ్యసభకు కాదు.'),
    (4,
     'easy',
     'Who presides over Cabinet meetings?\nతెలుగు: కేబినెట్ సమావేశాలకు అధ్యక్షత వహించే వ్యక్తి ఎవరు?',
     'President / రాష్ట్రపతి',
     'Vice-President / ఉప రాష్ట్రపతి',
     'Prime Minister / ప్రధానమంత్రి',
     'Lok Sabha Speaker / లోక్\u200cసభ స్పీకర్',
     'c',
     'PM chairs all Cabinet meetings. / PM కేబినెట్ అధ్యక్షుడు మరియు సమావేశాలకు అధ్యక్షత వహిస్తారు.'),
    (4,
     'medium',
     'What is the main function of the Cabinet?\nతెలుగు: కేబినెట్ యొక్క ప్రధాన విధి ఏమిటి?',
     'Making laws / చట్టాలు చేయడం',
     'Policy formulation, key decisions / విదేశాంగ నిర్ణయాలు, విధాన రూపకల్పన',
     'Resolving judicial disputes / న్యాయ వివాదాలు పరిష్కరించడం',
     'Appointing state govts / రాష్ట్ర ప్రభుత్వాలను నియమించడం',
     'b',
     'Cabinet formulates national policy, takes key decisions, recommends to President. / కేబినెట్ జాతీయ విధాన రూపకల్పన, అన్ని ముఖ్యమైన నిర్ణయాలు, రాష్ట్రపతికి సిఫారసులు చేయడం చేస్తుంది.'),
    (4,
     'hard',
     'Cabinet Committees are mentioned in which Article?\nతెలుగు: కేబినెట్ కమిటీలు (Cabinet Committees) ఏ అనుచ్ఛేదంలో ప్రస్తావించబడ్డాయి?',
     'Art.74 / అనుచ్ఛేదం 74',
     'Art.77 / అనుచ్ఛేదం 77',
     'Not specifically in Constitution / రాజ్యాంగంలో ప్రత్యేకంగా లేవు',
     'Art.352 / అనుచ్ఛేదం 352',
     'c',
     'Cabinet Committees are extra-constitutional — not specifically mentioned in Constitution. / కేబినెట్ కమిటీలు రాజ్యాంగేతర సంస్థలు — రాజ్యాంగంలో ప్రత్యేకంగా ప్రస్తావించబడలేదు.'),
    (4,
     'medium',
     'Which body is responsible for recording Cabinet decisions?\nతెలుగు: కేబినెట్ నిర్ణయాలు రికార్డు చేయడానికి బాధ్యత ఏ సంస్థకు ఉంటుంది?',
     'PMO / PMO (ప్రధానమంత్రి కార్యాలయం)',
     'Cabinet Secretariat / కేబినెట్ సెక్రటేరియట్',
     'Home Ministry / గృహ మంత్రిత్వ శాఖ',
     'Constitutional Assembly / రాజ్యాంగ సంఘం',
     'b',
     'Cabinet Secretariat records Cabinet decisions and monitors implementation. / కేబినెట్ సెక్రటేరియట్ కేబినెట్ నిర్ణయాలను రికార్డు చేయడం, అమలు పర్యవేక్షణ చేయడం బాధ్యత వహిస్తుంది.'),
    (4,
     'easy',
     "Who officially heads the PMO?\nతెలుగు: PMO (Prime Minister's Office) అధికారిక అధిపతి ఎవరు?",
     'Cabinet Secretary / కేబినెట్ సెక్రటరీ',
     'Principal Secretary to PM / ప్రధాన కార్యదర్శి (Principal Secretary to PM)',
     'Finance Minister / ఆర్థిక మంత్రి',
     'Lok Sabha Speaker / లోక్\u200cసభ స్పీకర్',
     'b',
     'PMO is officially headed by Principal Secretary to PM (or Chief of Staff). / PMO అధికారిక అధిపతి Principal Secretary to PM లేదా Chief of Staff.'),
    (4,
     'medium',
     'Why is written resolution of Cabinet required before Art.352 proclamation?\nతెలుగు: అత్యవసర పరిస్థితి (Art.352) ప్రకటనకు ముందు కేబినెట్ లిఖిత తీర్మానం అవసరం ఎందువల్ల?',
     'RS order / రాజ్యసభ ఆదేశం',
     '44th Amendment requirement / 44వ రాజ్యాంగ సవరణ సవరించింది',
     'Always required / ఎల్లప్పుడూ అవసరం',
     "PM's discretion / PM ఇష్టానుసారం",
     'b',
     '44th Amendment 1978: Art.352(3) requires written resolution of Cabinet before Emergency. / 44వ రాజ్యాంగ సవరణ 1978: అనుచ్ఛేదం 352(3): కేబినెట్ లిఖిత తీర్మానం తర్వాతే Emergency ప్రకటన చేయవచ్చు.'),
    (4,
     'hard',
     'Constitutional position of Cabinet in Indian government?\nతెలుగు: భారత కేబినెట్ ప్రభుత్వ నిర్మాణంలో రాజ్యాంగ స్థానం ఏమిటి?',
     'Constitutional body / రాజ్యాంగ సంస్థ',
     'Statutory body / చట్టబద్ధ సంస్థ',
     'Extra-constitutional body / రాజ్యాంగేతర సంస్థ',
     'Quasi-judicial body / అర్ధ న్యాయ సంస్థ',
     'a',
     'Cabinet is a constitutional body — defined in Art.352(3) after 44th Amendment. / Cabinet రాజ్యాంగ సంస్థ — 44వ సవరణ తర్వాత Art.352(3)లో నిర్వచించబడింది.'),
    (4,
     'easy',
     'Which is the most important Cabinet Committee?\nతెలుగు: కేబినెట్ కమిటీలలో ముఖ్యమైనది ఏది?',
     'Agricultural Committee / వ్యవసాయ కమిటీ',
     'Cabinet Committee on Security (CCS) / భద్రతా వ్యవహారాల కమిటీ (CCS)',
     'Education Committee / విద్యా కమిటీ',
     'Health Committee / ఆరోగ్య కమిటీ',
     'b',
     'CCS chaired by PM handles defence, foreign affairs, internal security. / CCS (Cabinet Committee on Security) PM అధ్యక్షతన — రక్షణ, విదేశాంగ, అంతర్గత భద్రత నిర్ణయాలు తీసుకుంటుంది.'),
    (5,
     'easy',
     "Can President act without PM's advice?\nతెలుగు: రాష్ట్రపతి PM సలహాను పాటించకుండా స్వంత నిర్ణయాలు తీసుకోగలరా?",
     'Yes, always / అవును, ఎల్లప్పుడూ',
     'No, after 42nd Amendment / 42వ సవరణ తర్వాత కాదు',
     'Only in emergency / అత్యవసర పరిస్థితిలో మాత్రమే',
     'With RS permission / రాజ్యసభ అనుమతితో',
     'b',
     '42nd Amendment 1976: President must act on the advice of CoM (Art.74(1) amended). / 42వ రాజ్యాంగ సవరణ 1976: అనుచ్ఛేదం 74(1) సవరణ — రాష్ట్రపతి మంత్రిమండలి సలహా ప్రకారమే పని చేయాలి.'),
    (5,
     'medium',
     'What change did 44th Amendment make to President-PM relationship?\nతెలుగు: 44వ రాజ్యాంగ సవరణ రాష్ట్రపతి-PM సంబంధంపై ఏం మార్పు చేసింది?',
     "Reduced PM's powers / PM అధికారాలు తగ్గించింది",
     'President may return advice once for reconsideration / రాష్ట్రపతి సలహాను ఒకసారి తిరిగి పంపవచ్చు',
     'PM can appoint President / రాష్ట్రపతిని PM నియమించవచ్చు',
     'PM given power to remove President / రాష్ట్రపతిని తొలగించే అధికారం PM కి ఇచ్చింది',
     'b',
     '44th Amendment: President may return advice once; must act on reconsidered advice. / 44వ రాజ్యాంగ సవరణ 1978: అనుచ్ఛేదం 74(1) — రాష్ట్రపతి మంత్రిమండలి సలహాను ఒకసారి తిరిగి పంపవచ్చు; పునఃపంపిన సలహాపై తప్పనిసరిగా పని చేయాలి.'),
    (5,
     'medium',
     'Under which Article PM must inform President of Cabinet decisions?\nతెలుగు: PM రాష్ట్రపతికి ఏ అనుచ్ఛేదం కింద మంత్రిమండలి నిర్ణయాలు తెలియజేయాలి?',
     'Art.74 / అనుచ్ఛేదం 74',
     'Art.78 / అనుచ్ఛేదం 78',
     'Art.85 / అనుచ్ఛేదం 85',
     'Art.77 / అనుచ్ఛేదం 77',
     'b',
     'Art.78: PM duties — communicate Cabinet decisions and legislative proposals to President. / అనుచ్ఛేదం 78: PM బాధ్యతలు — కేంద్ర ప్రభుత్వ నిర్ణయాలు, శాసన ప్రతిపాదనలు రాష్ట్రపతికి తెలియజేయడం.'),
    (5,
     'hard',
     'When PM post is vacant, President may on own discretion appoint?\nతెలుగు: PM పదవి ఖాళీగా ఉన్నప్పుడు రాష్ట్రపతి తన స్వంత విచక్షణతో ఎవరిని PM గా నియమించవచ్చు?',
     'Leader of RS / రాజ్యసభ నాయకుడు',
     'Leader of LS majority / లోక్\u200cసభలో మెజారిటీ నాయకుడు',
     'Senior minister / సీనియర్ మంత్రి',
     'CJI in emergency / అత్యవసరకాలంలో CJI',
     'b',
     'When PM post falls vacant, President appoints LS majority leader; discretion in hung parliament. / PM పదవి ఖాళీ అయినప్పుడు రాష్ట్రపతి లోక్\u200cసభలో మెజారిటీ నాయకుడిని PM గా నియమిస్తారు. సంకీర్ణ ప్రభుత్వంలో విచక్షణ ఉంటుంది.'),
    (5,
     'easy',
     'Whose opinion prevails in all matters between PM and President?\nతెలుగు: ప్రధానమంత్రి మరియు రాష్ట్రపతి మధ్య అన్ని విషయాలలో ఎవరి అభిప్రాయం ప్రాధాన్యత పొందుతుంది?',
     'President / రాష్ట్రపతి',
     'Prime Minister / ప్రధానమంత్రి',
     'Equally / సమానంగా',
     'Supreme Court decides / సుప్రీం కోర్ట్ నిర్ణయిస్తుంది',
     'b',
     'PM is real executive; President must act on CoM advice per Art.74(1). / వాస్తవ కార్యనిర్వాహకుడు PM. అనుచ్ఛేదం 74(1) ప్రకారం రాష్ట్రపతి CoM సలహా ప్రకారమే పని చేయాలి.'),
    (5,
     'medium',
     "Constitutional remedy if President doesn't follow PM's advice?\nతెలుగు: రాష్ట్రపతి PM సలహాను పాటించకపోతే రాజ్యాంగ పరిష్కారం ఏమిటి?",
     'Supreme Court intervention / సుప్రీం కోర్ట్ జోక్యం',
     'Impeachment in Parliament / పార్లమెంటులో అభిశంసన',
     'Constitutional convention pressure / రాజ్యాంగ సంఘట',
     'Constitutional amendment / రాజ్యాంగ సవరణ',
     'b',
     "Impeachment (Art.61) is the only constitutional remedy for President's constitutional violations. / రాష్ట్రపతి రాజ్యాంగ ఉల్లంఘన చేసినట్లయితే అభిశంసన (Art.61) ఏకైక రాజ్యాంగ పరిష్కారం."),
    (5,
     'hard',
     "Why are 'constitutional conventions' followed in PM-President relationship?\nతెలుగు: PM-రాష్ట్రపతి సంబంధంలో 'రాజ్యాంగ ఆచారాలు' (constitutional conventions) ఏ ఉద్దేశంతో అనుసరిస్తారు?",
     'Because constitutional provisions are incomplete / రాజ్యాంగ నిబంధనలు అసంపూర్ణం కాబట్టి',
     'To preserve constitutional spirit / రాజ్యాంగ స్ఫూర్తిని కాపాడటానికి',
     'Through court verdicts / న్యాయస్థానాల నిర్ణయాలతో',
     'Through amendments / రాజ్యాంగ సవరణలతో',
     'b',
     'Many conventions govern PM-President relationship — to uphold constitutional spirit. / PM-రాష్ట్రపతి సంబంధంలో అనేక ఆచారాలు (conventions) పాటించబడతాయి — రాజ్యాంగ స్ఫూర్తికి నిలబెట్టడానికి.'),
    (5,
     'medium',
     "Under Art.74(1), must President act on Cabinet's advice?\nతెలుగు: Art.74(1) ప్రకారం రాష్ట్రపతి మంత్రిమండలి సలహాపై తప్పనిసరిగా వ్యవహరించాలా?",
     'No, President can decide independently / కాదు, రాష్ట్రపతి స్వతంత్రంగా నిర్ణయించవచ్చు',
     'Yes, after 44th Amend — can return once; but must act on reconsidered advice / అవున, 44వ సవరణ తర్వాత — సలహా తిరిగి పంపవచ్చు, కానీ పునఃపరిశీలించిన సలహా పాటించాలి',
     'Yes, always and cannot return advice / అవున, ఎల్లప్పుడూ మరియు సలహా తిరిగి పంపే అవకాశం లేదు',
     'No, but should normally follow / కాదు, కానీ సాధారణంగా పాటించాలి',
     'b',
     '44th Amendment 1978: President may return CoM advice once for reconsideration; but must act on reconsidered advice. / 44వ రాజ్యాంగ సవరణ 1978: రాష్ట్రపతి మంత్రిమండలి సలహాను ఒకసారి తిరిగి పంపవచ్చు, కానీ రెండవ సారి పాటించాల్సిందే.'),
    (6,
     'easy',
     "What does 'Kitchen Cabinet' refer to?\nతెలుగు: 'కిచెన్ కేబినెట్' అనే పదం దేనిని సూచిస్తుంది?",
     'Kitchen staff / వంట గది నిర్వాహకులు',
     'Informal group of advisors around PM / PM చుట్టూ ఉండే అనధికారిక సలహాదారుల బృందం',
     'Senior Cabinet Ministers / సీనియర్ కేబినెట్ మంత్రులు',
     'National Security Council / జాతీయ భద్రతా మండలి',
     'b',
     'Kitchen Cabinet — informal group of trusted advisors around PM. / కిచెన్ కేబినెట్ — PM చుట్టూ ఉండే అనధికారిక, విశ్వాసపాత్రమైన సలహాదారుల బృందం.'),
    (6,
     'medium',
     'Which is correct about Kitchen Cabinet?\nతెలుగు: కిచెన్ కేబినెట్ లక్షణాలలో ఏది సరైనది?',
     'Constitutional body / రాజ్యాంగ సంస్థ',
     'Extra-constitutional, informal body / రాజ్యాంగేతర, అనధికారిక సంస్థ',
     'Accountable to LS / లోక్\u200cసభకు జవాబుదారీ',
     'Appointed by SC / సుప్రీం కోర్ట్ ద్వారా నియమింపబడుతుంది',
     'b',
     'Kitchen Cabinet is extra-constitutional and informal — not accountable to any House. / కిచెన్ కేబినెట్ రాజ్యాంగేతర మరియు అనధికారిక — ఇది ఏ సభకూ జవాబుదారీ కాదు.'),
    (6,
     'hard',
     "From where did 'Kitchen Cabinet' concept come to India?\nతెలుగు: భారతదేశంలో 'కిచెన్ కేబినెట్' భావన ఎక్కడ నుండి వచ్చింది?",
     'USA / అమెరికా',
     'Britain / బ్రిటన్',
     'France / ఫ్రాన్స్',
     'Canada / కెనడా',
     'a',
     "Kitchen Cabinet concept came from USA — refers to President's informal advisory group. / కిచెన్ కేబినెట్ భావన అమెరికా నుండి వచ్చింది — అమెరికన్ అధ్యక్షుల అనధికారిక సలహా బృందాన్ని సూచిస్తుంది."),
    (6,
     'easy',
     'Officers working in PMO belong to which service?\nతెలుగు: PMO (ప్రధానమంత్రి కార్యాలయం) లో పని చేసే అధికారులు ఏ సంస్థకు చెందినవారు?',
     'One specific service / ఒక నిర్దిష్ట సేవ',
     'IAS and various other services / భారత పరిపాలనా సేవ (IAS) మరియు ఇతర సేవలు',
     'Only Foreign Service / విదేశాంగ సేవ మాత్రమే',
     'Only Defence Services / రక్షణ సేవలు మాత్రమే',
     'b',
     'PMO has officials from IAS, IFS, IPS, military, technical experts — various services. / PMOలో IAS, IFS, IPS, సైనికులు, సాంకేతిక నిపుణులు — వివిధ సేవలకు చెందినవారు పని చేస్తారు.'),
    (6,
     'medium',
     'Who is the Principal Advisor to PM?\nతెలుగు: PM యొక్క ముఖ్య సలహాదారుడు (Principal Advisor) ఎవరు?',
     'Cabinet Secretary / కేబినెట్ సెక్రటరీ',
     'Principal Secretary to PM / ప్రిన్సిపల్ సెక్రటరీ',
     'Home Secretary / హోమ్ సెక్రటరీ',
     'National Security Advisor / జాతీయ భద్రతా సలహాదారు',
     'b',
     "Principal Secretary to PM (or Chief of Staff) is PM's senior official advisor. / Principal Secretary to PM (లేదా Chief of Staff) PM యొక్క ముఖ్య అధికారిక సలహాదారు."),
    (6,
     'hard',
     'NSA is directly answerable to whom?\nతెలుగు: NSA (జాతీయ భద్రతా సలహాదారు) ఎవరికి నేరుగా జవాబుదారీగా ఉంటారు?',
     'Defence Minister / రక్షణ మంత్రి',
     'Prime Minister / ప్రధానమంత్రి',
     'President / రాష్ట్రపతి',
     'CCS',
     'b',
     'NSA reports to PM-chaired CCS; directly answers to PM. / NSA PM నేతృత్వంలోని CCS (Cabinet Committee on Security) కి జవాబుదారీ; ప్రత్యక్షంగా PM కి నివేదిస్తారు.'),
    (6,
     'easy',
     "What does 'PMO' stand for?\nతెలుగు: PM కి సహాయపడే 'పీఎంఓ' అంటే ఏమిటి?",
     "Prime Minister's Organization / ప్రధానమంత్రి సంస్థ",
     "Prime Minister's Office / ప్రధానమంత్రి కార్యాలయం",
     "Parliamentary Members' Office / పార్లమెంటు సభ్యుల కార్యాలయం",
     'Public Ministry Operations / ప్రజా మంత్రిత్వ కార్యకలాపాలు',
     'b',
     "PMO = Prime Minister's Office — provides administrative support to PM. / PMO = Prime Minister's Office — PM కి పరిపాలనా సహాయం అందించే కార్యాలయం."),
    (6,
     'medium',
     "In parliamentary system, difference between Cabinet and Council of Ministers?\nతెలుగు: పార్లమెంటరీ ప్రభుత్వ వ్యవస్థలో 'Cabinet' మరియు 'Council of Ministers' మధ్య తేడా ఏమిటి?",
     'Both are same / రెండూ ఒకే విషయం',
     'Cabinet = Cabinet Ministers only; CoM = Cabinet + MoS + Deputy Ministers / Cabinet = Cabinet Ministers మాత్రమే; CoM = Cabinet + MoS + Deputy Ministers',
     'CoM = Cabinet Ministers only / CoM = Cabinet Ministers మాత్రమే',
     'Cabinet = all ministers; CoM = Cabinet Ministers only / Cabinet = అన్ని మంత్రులు; CoM = Cabinet Ministers మాత్రమే',
     'b',
     'CoM (constitutional) = all 3 categories; Cabinet = Cabinet Ministers only — the inner decision-making body. / Council of Ministers (రాజ్యాంగ సంస్థ, Art.74) = Cabinet Ministers + Ministers of State + Deputy Ministers. Cabinet = కేవలం Cabinet Ministers — అన్నింటినీ నిర్ణయించే చిన్న సమూహం.'),
    (7,
     'easy',
     "Constitutional Article for ministers' oath?\nతెలుగు: మంత్రుల ప్రమాణ స్వీకారానికి రాజ్యాంగ అనుచ్ఛేదం ఏది?",
     'Art.74 / అనుచ్ఛేదం 74',
     'Art.75(4) / అనుచ్ఛేదం 75(4)',
     'Art.76 / అనుచ్ఛేదం 76',
     'Art.99 / అనుచ్ఛేదం 99',
     'b',
     'Art.75(4): Ministers take oath before the President. / అనుచ్ఛేదం 75(4): మంత్రులు రాష్ట్రపతి ముందు ప్రమాణ స్వీకారం చేస్తారు.'),
    (7,
     'medium',
     'Ministers take oath from which Schedule?\nతెలుగు: కేంద్ర మంత్రులు ఏ షెడ్యూల్\u200cలో ఉన్న ప్రమాణ పత్రం చదువుతారు?',
     'Third Schedule / మూడో షెడ్యూల్',
     'Sixth Schedule / ఆరో షెడ్యూల్',
     'Fourth Schedule / నాల్గో షెడ్యూల్',
     'First Schedule / మొదటి షెడ్యూల్',
     'a',
     'Third Schedule contains oath forms for PM and ministers. / తృతీయ షెడ్యూల్ (Third Schedule): PM మరియు మంత్రుల ప్రమాణ పత్రాలు ఉంటాయి.'),
    (7,
     'hard',
     'Senior-most official under PM but not a minister?\nతెలుగు: మంత్రిమండలిలో సభ్యుడు కాకుండా PM కింద ఉండే అత్యుత్తమ అధికారి ఎవరు?',
     'Principal Secretary to PM',
     'Cabinet Secretary / కేబినెట్ సెక్రటరీ',
     'Home Secretary / హోమ్ సెక్రటరీ',
     'Finance Secretary / ఆర్థిక సెక్రటరీ',
     'b',
     'Cabinet Secretary is the senior-most IAS officer; heads Cabinet Secretariat. / Cabinet Secretary భారత పరిపాలనా సేవలో అత్యున్నత అధికారి; కేబినెట్ సెక్రటేరియట్ అధిపతి.'),
    (7,
     'medium',
     'Does President have discretion in PM appointment in coalition govt?\nతెలుగు: సంకీర్ణ ప్రభుత్వంలో PM నియామకంలో రాష్ట్రపతి విచక్షణ అధికారం ఉంటుందా?',
     'Never / ఎప్పుడూ లేదు',
     'Limited discretion exists / కొంత మేరకు ఉంటుంది',
     'Full discretion / పూర్తి విచక్షణ ఉంటుంది',
     'SC decides / సుప్రీం కోర్ట్ నిర్ణయిస్తుంది',
     'b',
     'In coalition with no clear majority, President has limited discretion in PM appointment. / సంకీర్ణ ప్రభుత్వంలో స్పష్టమైన మెజారిటీ లేనప్పుడు రాష్ట్రపతి PM నియామకంలో కొంత విచక్షణ వినియోగించవచ్చు.'),
    (7,
     'easy',
     "What is PM's official residence?\nతెలుగు: PM గ్రహించే అధికారిక నివాసం ఏది?",
     'Rashtrapati Bhavan / రాష్ట్రపతి భవన్',
     '7, Lok Kalyan Marg / 7, లోక్ కల్యాణ్ మార్గ్',
     'South Block / సౌత్ బ్లాక్',
     'Hyderabad House / హైదరాబాద్ హౌస్',
     'b',
     "PM's official residence is 7, Lok Kalyan Marg (formerly 7 Race Course Road), New Delhi. / PM అధికారిక నివాసం 7, లోక్ కల్యాణ్ మార్గ్ (పూర్వం 7 రేస్ కోర్స్ రోడ్) న్యూ ఢిల్లీలో ఉంది."),
    (7,
     'hard',
     "A PM who lost LS majority can serve as 'caretaker' — with what restrictions?\nతెలుగు: లోక్\u200cసభలో మెజారిటీ కోల్పోయిన PM 'caretaker' హోదాలో పని చేయవచ్చు — ఏ పరిమితులతో?",
     'All powers remain valid / అన్ని అధికారాలు చెల్లుబాటు అవుతాయి',
     'Only routine administration; no major decisions / రోజువారీ పాలన మాత్రమే; ముఖ్య నిర్ణయాలు కాదు',
     'PM office immediately vacated / PM పదవి వెంటనే ఖాళీ అవుతుంది',
     'Can function with RS approval / రాజ్యసభ ఆమోదంతో పని చేయవచ్చు',
     'b',
     "PM losing LS majority continues as caretaker for routine administration only — convention, not law. / లోక్\u200cసభ మెజారిటీ కోల్పోయిన PM రాజ్యాంగ ఆచారాన్ని అనుసరించి 'caretaker' హోదాలో రోజువారీ పాలన మాత్రమే చేయాలి."),
    (7,
     'hard',
     "PM's salary and allowances are determined under which law?\nతెలుగు: PM జీతం మరియు భత్యాలు ఏ చట్టం కింద నిర్ణయిస్తారు?",
     'Specified in Constitution / రాజ్యాంగంలో పేర్కొనబడ్డాయి',
     'Salaries and Allowances of Ministers Act, 1952',
     'Parliament Members Salary Act',
     'Decided by Finance Minister / Finance Minister నిర్ణయిస్తారు',
     'b',
     "PM's salary is determined under Salaries and Allowances of Ministers Act, 1952. / Salaries and Allowances of Ministers Act, 1952 కింద PM మరియు మంత్రుల జీతాలు నిర్ణయించబడతాయి."),
    (7,
     'medium',
     'Under Art.78, PM must inform President about which matters?\nతెలుగు: అనుచ్ఛేదం 78 కింద PM రాష్ట్రపతికి సమాచారం ఇవ్వాల్సిన విషయాలు ఏవి?',
     'All Cabinet decisions only / అన్ని మంత్రిమండలి నిర్ణయాలు మాత్రమే',
     'Decisions on Union affairs + info requested by President + individual minister decisions (even if not brought before Cabinet) / Union వ్యవహారాలకు సంబంధించిన నిర్ణయాలు + రాష్ట్రపతి అడిగిన సమాచారం + వ్యక్తిగత మంత్రి నిర్ణయాలు (కేబినెట్ ముందుకు రాకపోయినా)',
     'Only foreign policy decisions / కేవలం విదేశ విధానం నిర్ణయాలు',
     'Only Parliamentary business / పార్లమెంటు కార్యక్రమాలు మాత్రమే',
     'b',
     "Art.78: PM's 3 duties to President: (a) communicate CoM decisions; (b) furnish info requested; (c) if President requires, submit for Cabinet consideration any matter decided by a minister alone. / Art.78: PM యొక్క 3 విధులు — (a) Union వ్యవహారాల పాలనకు సంబంధించిన నిర్ణయాలు రాష్ట్రపతికి తెలియజేయడం; (b) రాష్ట్రపతి అడిగిన ఇతర సమాచారం ఇవ్వడం; (c) ఒక మంత్రి నిర్ణయించిన విషయాన్ని (కేబినెట్ ముందు పెట్టకపోయినా) రాష్ట్రపతి అడిగితే కేబినెట్ ముందు పెట్టడం."),
]


def _seed_polity_ch17_notes_inner(conn, db_exec_fn, row_to_dict_fn, use_postgres, force=False):
    ph = '%s' if use_postgres else '?'
    existing = db_exec_fn(conn,
        f"SELECT id FROM study_notes WHERE subject={ph} AND topic={ph} AND chapter_num={ph}",
        (_SUBJECT, _TOPIC, _CH))
    row = existing.fetchone()
    if row and not force:
        return

    sections_json = __import__('json').dumps(
        [{"title": s, "content": ""} for s in _SECTIONS],
        ensure_ascii=False
    )

    if row and force:
        note_id = row_to_dict_fn(row)['id']
        db_exec_fn(conn,
            f"UPDATE study_notes SET chapter_title_te={ph}, chapter_title_en={ph}, "
            f"pages_ref={ph}, sections_json={ph} WHERE id={ph}",
            (_TITLE_TE, _TITLE_EN, _PAGES, sections_json, note_id))
    else:
        db_exec_fn(conn,
            f"INSERT INTO study_notes (subject, topic, chapter_num, chapter_title_te, "
            f"chapter_title_en, pages_ref, sections_json) VALUES "
            f"({ph},{ph},{ph},{ph},{ph},{ph},{ph})",
            (_SUBJECT, _TOPIC, _CH, _TITLE_TE, _TITLE_EN, _PAGES, sections_json))


def _seed_polity_ch17_mcqs_inner(conn, db_exec_fn, row_to_dict_fn, use_postgres):
    ph = '%s' if use_postgres else '?'
    diff_map = {"easy": 1, "medium": 2, "hard": 3, "toughest": 4, 1: 1, 2: 2, 3: 3, 4: 4}

    note_cur = db_exec_fn(conn,
        f"SELECT id FROM study_notes WHERE subject={ph} AND topic={ph} AND chapter_num={ph}",
        (_SUBJECT, _TOPIC, _CH))
    note_row = note_cur.fetchone()
    if not note_row:
        return
    note_id = row_to_dict_fn(note_row)['id']

    existing = db_exec_fn(conn,
        f"SELECT COUNT(*) FROM chapter_mcqs WHERE study_note_id={ph}", (note_id,))
    count = list(existing.fetchone())[0]
    if count > 0:
        return

    for row in _MCQS:
        sec_idx  = row[0]
        diff_int = diff_map.get(row[1], 1)
        q_te     = row[2]
        opt_a    = row[3]
        opt_b    = row[4]
        opt_c    = row[5]
        opt_d    = row[6]
        correct  = str(row[7]).lower()
        expl     = row[8] if len(row) > 8 else ''
        exam_type = row[9] if len(row) > 9 else 'General'

        db_exec_fn(conn,
            f"""INSERT INTO chapter_mcqs
                (study_note_id, section_idx, difficulty, exam_type,
                 q_te, opt_a, opt_b, opt_c, opt_d, correct, explanation_te)
                VALUES ({ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph})""",
            (note_id, sec_idx, diff_int, exam_type,
             q_te, opt_a, opt_b, opt_c, opt_d, correct, expl))
