"""
seed_intl_orgs_mcq.py
86 GKToday-style MCQs — Topic: International Current Affairs → International Organisations
Coverage: 2025–2026 events + structural GK (no 2022/2023-specific questions)
Folder: AP_HC | Topic: International_Current_Affairs
IDs: 20001–20086  |  Force-refresh: DELETE then INSERT
"""

import os, sqlite3

DATABASE_URL = os.environ.get("DATABASE_URL", "")
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)
USE_POSTGRES = bool(DATABASE_URL)

INTL_MCQS = [
    # ─── UNITED NATIONS (20001-20008) ──────────────────────────────
    {
        "id": 20001,
        "question": "The headquarters of the United Nations (UN) is located in which city?",
        "option_a": "Geneva", "option_b": "New York", "option_c": "Brussels", "option_d": "Vienna",
        "correct_answer": "B",
        "explanation": "UN HQ is in New York City, USA. The UN was founded on October 24, 1945 (UN Day). Geneva hosts many UN agencies (WHO, WTO, UNHCR) but the main Secretariat HQ is New York.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20002,
        "question": "Who is the Secretary-General of the United Nations serving his second term through December 2026?",
        "option_a": "Ban Ki-moon", "option_b": "Kofi Annan", "option_c": "António Guterres", "option_d": "Tedros Adhanom",
        "correct_answer": "C",
        "explanation": "António Guterres (Portugal) is the 9th UN Secretary-General, serving since January 1, 2017. His 2nd term runs through December 2026. He is the 1st former head of government (PM of Portugal 1995-2002) to become UN SG.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20003,
        "question": "The UN Security Council has how many permanent members (P5), each with veto power?",
        "option_a": "3", "option_b": "5", "option_c": "7", "option_d": "10",
        "correct_answer": "B",
        "explanation": "UNSC has 5 permanent members (P5): USA, UK, France, Russia, China. Each holds veto power. There are 10 non-permanent elected members (2-year terms). Total UNSC = 15 members.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20004,
        "question": "How many member states does the United Nations currently have (as of 2026)?",
        "option_a": "180", "option_b": "185", "option_c": "193", "option_d": "197",
        "correct_answer": "C",
        "explanation": "The UN has 193 member states — almost every recognised sovereign nation. The Vatican (Holy See) and Palestine are UN Observer States (non-member). South Sudan (2011) was the last country to join. The UN has 6 principal organs.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20005,
        "question": "The UNGA 80th session (2025-26) marks 80 years of the UN. Which body adopted the 'Pact for the Future' at the UN Summit of the Future in September 2024?",
        "option_a": "UN Security Council", "option_b": "UN General Assembly", "option_c": "UN Secretariat", "option_d": "UN Economic and Social Council",
        "correct_answer": "B",
        "explanation": "The UN General Assembly adopted the 'Pact for the Future' at the Summit of the Future (September 22-23, 2024, New York). It included the Global Digital Compact and a Declaration on Future Generations, aimed at reforming global governance for the 21st century.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20006,
        "question": "India is currently serving as a non-permanent member of the UN Security Council for 2028-29. How many non-permanent members does the UNSC have?",
        "option_a": "5", "option_b": "8", "option_c": "10", "option_d": "12",
        "correct_answer": "C",
        "explanation": "The UNSC has 10 non-permanent members elected by the UNGA for 2-year terms. They are elected from regional groups: Africa (3), Latin America (2), Asia-Pacific (2), Western Europe (2), Eastern Europe (1). India last served as non-permanent member in 2021-2022.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20007,
        "question": "The 20th G20 Summit 2025 was held in which city, marking the first-ever G20 hosted on the African continent?",
        "option_a": "Cape Town, South Africa", "option_b": "Nairobi, Kenya", "option_c": "Johannesburg, South Africa", "option_d": "Lagos, Nigeria",
        "correct_answer": "C",
        "explanation": "The 20th G20 Summit was held at the Johannesburg Expo Centre, South Africa on November 22-23, 2025 — first G20 ever hosted on the African continent. South Africa's G20 Presidency followed Brazil's (2024). USA will host G20 2026 (Miami).",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20008,
        "question": "What was the official theme of South Africa's G20 Presidency 2025 and the Johannesburg Summit?",
        "option_a": "Building a Resilient World Together", "option_b": "Solidarity, Equality, Sustainability", "option_c": "Collaboration for the Intelligent Age", "option_d": "Vasudhaiva Kutumbakam",
        "correct_answer": "B",
        "explanation": "'Solidarity, Equality, Sustainability' was South Africa's G20 2025 theme, rooted in Ubuntu philosophy. India's G20 2023 theme was 'Vasudhaiva Kutumbakam' and Brazil's G20 2024 theme was 'Building a Just World and a Sustainable Planet.'",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ─── G20 (20009-20016) ─────────────────────────────────────────
    {
        "id": 20009,
        "question": "Which major G20 member was absent from the G20 Johannesburg Summit 2025?",
        "option_a": "China", "option_b": "Russia", "option_c": "United States", "option_d": "United Kingdom",
        "correct_answer": "C",
        "explanation": "The USA did not participate in the G20 Johannesburg Summit 2025. Argentina was the only nation present that did not subscribe to the final declaration, with FM Quirno citing 'missing geopolitical facts' on the Middle East.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20010,
        "question": "Which country will host the G20 Summit in 2026, becoming the first country to host it twice in five years?",
        "option_a": "India", "option_b": "China", "option_c": "United States", "option_d": "Germany",
        "correct_answer": "C",
        "explanation": "USA will host the G20 in 2026 (Miami Beach). The USA previously hosted in 2008 (Washington D.C.) and 2009 (Pittsburgh). South Africa handed the G20 Presidency to the USA on January 12, 2026.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20011,
        "question": "The G20 was established in 1999. Which body did it replace as the primary economic forum among major economies?",
        "option_a": "G7", "option_b": "G8", "option_c": "G22 (Dean's Group)", "option_d": "G15",
        "correct_answer": "C",
        "explanation": "G20 was established on September 26, 1999, emerging from the G22 (Dean's Group) and G33 meetings. It was created in response to the 1997-98 Asian financial crisis. G20 Finance Ministers first met in Berlin, December 1999.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20012,
        "question": "The African Union became a permanent G20 member in 2023 at the India-hosted Summit. The AU has how many member states?",
        "option_a": "44", "option_b": "50", "option_c": "55", "option_d": "58",
        "correct_answer": "C",
        "explanation": "The African Union (AU) has 55 member states — all African countries. It was admitted as a permanent G20 member at the New Delhi G20 Summit 2023, making G20 effectively G21. AU HQ is in Addis Ababa, Ethiopia.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20013,
        "question": "The G20 comprises 19 countries + the EU + which newly added permanent member?",
        "option_a": "Arab League", "option_b": "ASEAN", "option_c": "African Union", "option_d": "Commonwealth of Nations",
        "correct_answer": "C",
        "explanation": "G20 = 19 countries + European Union + African Union (joined 2023) = effectively 21 members. The 19 countries are Argentina, Australia, Brazil, Canada, China, France, Germany, India, Indonesia, Italy, Japan, South Korea, Mexico, Russia, Saudi Arabia, South Africa, Turkey, UK, USA.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20014,
        "question": "Which country hosted the G20 Summit in 2024 under the theme 'Building a Just World and a Sustainable Planet'?",
        "option_a": "India", "option_b": "Argentina", "option_c": "South Africa", "option_d": "Brazil",
        "correct_answer": "D",
        "explanation": "Brazil hosted the 19th G20 Summit in Rio de Janeiro on November 18-19, 2024. Theme: 'Building a Just World and a Sustainable Planet.' Brazilian priorities included hunger eradication (Global Alliance Against Hunger), climate finance reform, and taxing ultra-wealthy individuals.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20015,
        "question": "The G20 collectively represents approximately what percentage of world GDP?",
        "option_a": "60%", "option_b": "75%", "option_c": "85%", "option_d": "95%",
        "correct_answer": "C",
        "explanation": "G20 countries collectively account for approximately 85% of world GDP, 75% of global trade, and two-thirds of the world's population. This makes G20 the premier forum for international economic cooperation.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20016,
        "question": "Where is the 18th BRICS Summit 2025 hosted and who holds the BRICS Chairship in 2025?",
        "option_a": "Russia; Russia", "option_b": "India; India", "option_c": "Brazil; Brazil", "option_d": "China; China",
        "correct_answer": "C",
        "explanation": "Brazil holds the BRICS Chairship in 2025 and is hosting the 18th BRICS Summit. The 2025 BRICS theme is 'Strengthening South-South Cooperation for a More Inclusive and Sustainable Governance.' Russia hosted BRICS 2024 (Kazan Summit, October 2024).",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ─── BRICS (20017-20023) ────────────────────────────────────────
    {
        "id": 20017,
        "question": "Which country joined BRICS as a full member on January 6, 2025, becoming the first Southeast Asian nation in the bloc?",
        "option_a": "Malaysia", "option_b": "Vietnam", "option_c": "Thailand", "option_d": "Indonesia",
        "correct_answer": "D",
        "explanation": "Indonesia joined BRICS as a full member on January 6, 2025 — the first Southeast Asian state in BRICS and the 11th full member. BRICS now has: Brazil, Russia, India, China, South Africa, Egypt, Ethiopia, Iran, UAE, Saudi Arabia, Indonesia.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20018,
        "question": "How many countries are full members of BRICS as of 2025, following Indonesia's accession?",
        "option_a": "6", "option_b": "9", "option_c": "11", "option_d": "13",
        "correct_answer": "C",
        "explanation": "BRICS has 11 full members as of January 2025: original 5 (Brazil, Russia, India, China, South Africa) + Egypt, Ethiopia, Iran, UAE, Saudi Arabia (all joined January 1, 2024) + Indonesia (January 6, 2025). Several more countries are BRICS Partner States.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20019,
        "question": "The New Development Bank (NDB), established by BRICS, is headquartered in which city?",
        "option_a": "Beijing, China", "option_b": "New Delhi, India", "option_c": "Shanghai, China", "option_d": "Moscow, Russia",
        "correct_answer": "C",
        "explanation": "The NDB (also known as the BRICS Bank) is headquartered in Shanghai, China. It was established in 2015 to fund infrastructure and sustainable development projects in BRICS and developing countries. The NDB has expanded membership beyond BRICS nations.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20020,
        "question": "BRICS originally began as 'BRIC' (without South Africa). Who coined the term 'BRIC' in 2001?",
        "option_a": "IMF economist Olivier Blanchard", "option_b": "Goldman Sachs economist Jim O'Neill", "option_c": "World Bank President James Wolfensohn", "option_d": "WTO DG Mike Moore",
        "correct_answer": "B",
        "explanation": "Jim O'Neill of Goldman Sachs coined the term 'BRIC' in his 2001 paper 'Building Better Global Economic BRICs.' The first formal BRIC summit was held in Yekaterinburg, Russia in June 2009. South Africa joined in 2010, making it BRICS.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20021,
        "question": "Five countries joined BRICS as full members on January 1, 2024. Which country, though invited, declined BRICS membership?",
        "option_a": "Turkey", "option_b": "Nigeria", "option_c": "Argentina", "option_d": "Mexico",
        "correct_answer": "C",
        "explanation": "Argentina was invited to join BRICS in 2023 but declined in December 2023 — new President Javier Milei, an economic libertarian, reversed the previous government's decision. The five countries that did join on January 1, 2024 were Egypt, Ethiopia, Iran, UAE, and Saudi Arabia.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20022,
        "question": "The 17th BRICS Summit 2024 was held in Kazan, Russia. Which key geopolitical issue dominated discussions?",
        "option_a": "China-Taiwan tensions", "option_b": "Russia's isolation and the war in Ukraine", "option_c": "North Korea's nuclear programme", "option_d": "India-Pakistan conflict",
        "correct_answer": "B",
        "explanation": "The 17th BRICS Summit (Kazan, Russia, October 22-24, 2024) was significant for Russia hosting despite Western sanctions over the Ukraine war. The summit discussed BRICS expansion, de-dollarisation, and a new payment system alternative to SWIFT. India's PM Modi attended.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20023,
        "question": "The BRICS Contingent Reserve Arrangement (CRA) was established in 2015. What is its primary purpose?",
        "option_a": "Fund climate projects", "option_b": "Provide short-term liquidity support to members during balance-of-payment crises", "option_c": "Replace IMF loans", "option_d": "Finance infrastructure across Africa",
        "correct_answer": "B",
        "explanation": "The CRA (signed in Fortaleza, Brazil 2014, effective July 2015) provides short-term liquidity support to BRICS members facing balance-of-payment crises. Initial size: $100 billion. China contributes $41B, Brazil, Russia, India $18B each, South Africa $5B. It is separate from the NDB.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ─── G7 (20024-20029) ──────────────────────────────────────────
    {
        "id": 20024,
        "question": "Which country hosted the G7 Summit in 2025 at Kananaskis, Alberta?",
        "option_a": "Italy", "option_b": "Japan", "option_c": "Canada", "option_d": "France",
        "correct_answer": "C",
        "explanation": "Canada hosted the 51st G7 Summit in Kananaskis, Alberta on June 15-17, 2025. Canada held the G7 Presidency in 2025 under PM Mark Carney. Italy hosted G7 2024 (Puglia). USA hosts G7 2026 (which may coincide with G20 Miami).",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20025,
        "question": "The G7 consists of which seven nations?",
        "option_a": "USA, UK, France, Germany, Japan, Canada, Italy", "option_b": "USA, UK, France, Germany, Japan, Canada, Australia", "option_c": "USA, UK, France, Germany, Japan, India, Italy", "option_d": "USA, UK, France, Germany, Russia, Canada, Italy",
        "correct_answer": "A",
        "explanation": "G7 = USA, UK, France, Germany, Japan, Canada, Italy (+EU as non-enumerated member). Russia was suspended from G8 after Crimea annexation (2014) — now G7. India, Australia, and others are frequent invited partners but not full G7 members.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20026,
        "question": "Which country hosted the G7 Summit in 2024 under the theme 'For the Mediterranean, for humanity, for the future'?",
        "option_a": "Germany", "option_b": "Japan", "option_c": "Italy", "option_d": "France",
        "correct_answer": "C",
        "explanation": "Italy hosted the 50th G7 Summit in Puglia (Borgo Egnazia) on June 13-15, 2024. Theme: 'For the Mediterranean, for humanity, for the future.' India PM Modi attended. Key outcomes: Ukraine aid, AI governance, migration, and climate.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20027,
        "question": "G7 originally began as G6 in 1975 with 6 founding members. Which country joined in 1976 to make it G7?",
        "option_a": "Japan", "option_b": "Italy", "option_c": "Canada", "option_d": "Germany",
        "correct_answer": "C",
        "explanation": "G6 was founded in November 1975 (Rambouillet, France) by USA, UK, France, Germany, Japan, Italy. Canada joined in 1976 to make it G7. The EU joined as a non-enumerated member in 1977. Russia joined in 1998 making it G8, but was suspended in 2014.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20028,
        "question": "The G7 Finance Ministers agreed in 2025 to use profits from frozen Russian sovereign assets to support Ukraine. Approximately how much in Russian assets were frozen?",
        "option_a": "$50 billion", "option_b": "$100 billion", "option_c": "$300 billion", "option_d": "$500 billion",
        "correct_answer": "C",
        "explanation": "Approximately $300 billion in Russian sovereign assets were frozen by Western nations after Russia's invasion of Ukraine (February 2022). The G7 agreed in 2024-25 to use windfall profits (interest) from these assets — approximately $50B — to provide loans to Ukraine.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20029,
        "question": "The G7 communiqué from the Kananaskis 2025 Summit strongly criticised which country's trade practices that were seen as flooding global markets?",
        "option_a": "Russia", "option_b": "India", "option_c": "China", "option_d": "South Korea",
        "correct_answer": "C",
        "explanation": "The G7 Kananaskis 2025 Summit communiqué criticised China for 'non-market practices' and 'overcapacity' — particularly in electric vehicles, solar panels, and steel — that were flooding global markets and undercutting Western manufacturers. This reflected rising G7-China trade tensions.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ─── QUAD (20030-20033) ─────────────────────────────────────────
    {
        "id": 20030,
        "question": "The Quadrilateral Security Dialogue (QUAD) consists of which four countries?",
        "option_a": "USA, India, Japan, South Korea", "option_b": "USA, India, Japan, Australia", "option_c": "USA, UK, Australia, New Zealand", "option_d": "USA, India, Australia, France",
        "correct_answer": "B",
        "explanation": "QUAD (Quadrilateral Security Dialogue) = USA, India, Japan, Australia. Revived in 2017 at working-group level and elevated to Leaders' Summit level in 2021. QUAD focuses on free and open Indo-Pacific, countering China's assertiveness, supply chains, cyber, and clean energy.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20031,
        "question": "India hosted the QUAD Foreign Ministers' meeting in 2025. The QUAD Leaders' Summit in 2025 was hosted by which country?",
        "option_a": "USA", "option_b": "India", "option_c": "Japan", "option_d": "Australia",
        "correct_answer": "B",
        "explanation": "India hosted the QUAD Leaders' Summit in 2025 — the first QUAD summit held in India. Previous summits: Washington DC (2021), Tokyo (2022), Hiroshima (2023, sideline), Wilmington, USA (2024). The rotating format reflects equal weight given to all four members.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20032,
        "question": "Exercise MALABAR is a naval exercise among which nations?",
        "option_a": "India, France, UK", "option_b": "India, USA, Japan, Australia (QUAD nations)", "option_c": "India, USA, Singapore", "option_d": "SCO member navies",
        "correct_answer": "B",
        "explanation": "Exercise Malabar is a naval exercise among QUAD nations (India, USA, Japan, Australia). It began in 1992 as India-USA bilateral; Japan became permanent in 2015; Australia joined in 2020. Malabar 2025 was hosted by India in the Bay of Bengal.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20033,
        "question": "The AUKUS partnership, formed in 2021, aims to provide nuclear-powered submarines to which country?",
        "option_a": "India", "option_b": "Japan", "option_c": "Australia", "option_d": "South Korea",
        "correct_answer": "C",
        "explanation": "AUKUS = Australia, UK, USA — a security partnership announced in September 2021. Its centrepiece is providing Australia with nuclear-powered (not nuclear-armed) submarines. AUKUS Pillar II covers AI, quantum, cyber, and hypersonics. It is separate from but complementary to QUAD.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ─── NATO (20034-20040) ─────────────────────────────────────────
    {
        "id": 20034,
        "question": "How many member countries does NATO have as of 2025, following Sweden's accession?",
        "option_a": "28", "option_b": "30", "option_c": "32", "option_d": "34",
        "correct_answer": "C",
        "explanation": "NATO has 32 members as of 2025. Sweden became the 32nd member on March 7, 2024, following Finland (31st, April 2023). Both Nordic nations abandoned their long-held neutrality after Russia's full-scale invasion of Ukraine (February 2022).",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20035,
        "question": "Who became the NATO Secretary-General in October 2024, succeeding Jens Stoltenberg?",
        "option_a": "Ursula von der Leyen", "option_b": "Mark Rutte", "option_c": "Donald Tusk", "option_d": "Charles Michel",
        "correct_answer": "B",
        "explanation": "Mark Rutte (Netherlands), former PM of Netherlands (2010-2024), became NATO Secretary-General on October 1, 2024. He succeeded Jens Stoltenberg of Norway who served for 10 years (2014-2024). Rutte is the 14th NATO Secretary-General.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20036,
        "question": "The NATO Hague Summit (June 2025) set a new defence spending target. What was the target as percentage of GDP?",
        "option_a": "2% of GDP", "option_b": "3% of GDP", "option_c": "3.5% of GDP", "option_d": "5% of GDP",
        "correct_answer": "D",
        "explanation": "The NATO Hague Summit (Netherlands, June 24-25, 2025) agreed to a new defence spending target of 5% of GDP — up from the previous 2% target. The decision came under pressure from US President Trump who demanded European allies increase defence spending. Many NATO members struggled to meet even the old 2% target.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20037,
        "question": "Which country hosted the NATO Summit in June 2025?",
        "option_a": "Germany", "option_b": "Poland", "option_c": "Netherlands", "option_d": "Belgium",
        "correct_answer": "C",
        "explanation": "The NATO Summit was held at The Hague, Netherlands, on June 24-25, 2025. It was hosted by Netherlands PM Dick Schoof. Key outcomes: 5% GDP defence spending pledge, continued Ukraine support, and strengthening NATO's eastern flank against Russia.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20038,
        "question": "NATO was founded in 1949. Article 5 of the NATO Treaty is about what principle?",
        "option_a": "Freedom of navigation", "option_b": "Collective defence — an attack on one is an attack on all", "option_c": "No first use of nuclear weapons", "option_d": "Mandatory 2% GDP defence spending",
        "correct_answer": "B",
        "explanation": "NATO's Article 5 is the collective defence clause: an armed attack against one NATO member is considered an attack against all. NATO was established in April 1949 (Washington Treaty). Article 5 was invoked only once — after the September 11, 2001 attacks on the USA.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20039,
        "question": "Which city is the headquarters of NATO?",
        "option_a": "Geneva, Switzerland", "option_b": "Brussels, Belgium", "option_c": "Strasbourg, France", "option_d": "Luxembourg City, Luxembourg",
        "correct_answer": "B",
        "explanation": "NATO HQ is in Brussels, Belgium. The Supreme Headquarters Allied Powers Europe (SHAPE) is in Mons, Belgium. NATO was originally headquartered in London (1949), then Paris (1952), before moving to Brussels (1967) when France withdrew from NATO's military command structure.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20040,
        "question": "Which country became the 11th and most recent full member of ASEAN, admitted at the 47th ASEAN Summit in Kuala Lumpur in October 2025?",
        "option_a": "Timor-Leste", "option_b": "Cambodia", "option_c": "Myanmar", "option_d": "Papua New Guinea",
        "correct_answer": "A",
        "explanation": "ASEAN now has 11 full members. Timor-Leste (East Timor) was formally admitted as ASEAN's 11th member at the 47th ASEAN Summit in Kuala Lumpur, Malaysia (October 26-28, 2025) — ASEAN's first expansion since Cambodia joined in 1999 (a 26-year gap). Note: The Phnom Penh 2022 summit was the 40th ASEAN Summit, not the 47th. Brunei (1984) and Vietnam (1995) were among later joiners. ASEAN's founding members (1967) were Thailand, Malaysia, Singapore, Indonesia, Philippines.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ─── SCO (20041-20046) ─────────────────────────────────────────
    {
        "id": 20041,
        "question": "How many full member countries does the SCO have as of 2025, following Belarus's accession?",
        "option_a": "8", "option_b": "9", "option_c": "10", "option_d": "12",
        "correct_answer": "C",
        "explanation": "SCO has 10 full members: China, Russia, Kazakhstan, Kyrgyzstan, Tajikistan, Uzbekistan (founders 2001), India, Pakistan (2017), Iran (2023), Belarus (2024). Turkey, Qatar, and several others are dialogue partners or observer states.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20042,
        "question": "Where is the headquarters of the Shanghai Cooperation Organisation (SCO)?",
        "option_a": "Shanghai, China", "option_b": "Astana, Kazakhstan", "option_c": "Beijing, China", "option_d": "Moscow, Russia",
        "correct_answer": "C",
        "explanation": "SCO Secretariat is in Beijing, China. The SCO Regional Anti-Terrorist Structure (RATS) is in Tashkent, Uzbekistan. The SCO was established in 2001 in Shanghai — replacing the Shanghai Five (1996).",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20043,
        "question": "India hosted the SCO Summit in 2023. Which country hosted the SCO Summit in 2025?",
        "option_a": "Russia", "option_b": "China", "option_c": "Pakistan", "option_d": "Kazakhstan",
        "correct_answer": "B",
        "explanation": "China held the SCO Chairship and hosted the 25th SCO Summit in 2025. India hosted the SCO Summit virtually in 2023 (first virtual SCO Summit). Pakistan hosted the SCO PM/Government Heads meeting in October 2024.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20044,
        "question": "India joined the SCO as a full member in which year?",
        "option_a": "2010", "option_b": "2015", "option_c": "2017", "option_d": "2019",
        "correct_answer": "C",
        "explanation": "India (and Pakistan) became full members of the SCO in 2017 at the Astana Summit. India was previously an observer state (from 2005). Iran joined as a full member in 2023; Belarus joined in 2024.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20045,
        "question": "Which country, a SCO member, was NOT present at the SCO Heads of Government meeting in Islamabad, Pakistan in October 2024?",
        "option_a": "China", "option_b": "Russia", "option_c": "India", "option_d": "Kazakhstan",
        "correct_answer": "C",
        "explanation": "India's PM Modi did not attend the SCO meeting in Islamabad, Pakistan (October 2024) due to strained India-Pakistan relations. India was represented at a lower level. This highlighted the diplomatic complexities within SCO given that India and Pakistan are both members.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20046,
        "question": "The SCO's 'Shanghai Spirit' is based on which core principles?",
        "option_a": "Military alliance, nuclear deterrence, free trade", "option_b": "Mutual trust, mutual benefit, equality, consultation, respect for diversity, non-alignment", "option_c": "Democratic governance, human rights, rule of law", "option_d": "Common currency, open borders, free movement",
        "correct_answer": "B",
        "explanation": "The 'Shanghai Spirit' underpins SCO: mutual trust, mutual advantage, equality, consultation, respect for cultural diversity, and pursuit of common development. Unlike NATO, SCO is explicitly non-military-alliance and non-bloc — it focuses on security, economic, and cultural cooperation.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ─── IMF & WORLD BANK (20047-20053) ────────────────────────────
    {
        "id": 20047,
        "question": "Who is the current Managing Director of the International Monetary Fund (IMF) serving her second term from 2024?",
        "option_a": "Christine Lagarde", "option_b": "Kristalina Georgieva", "option_c": "Gita Gopinath", "option_d": "Raghuram Rajan",
        "correct_answer": "B",
        "explanation": "Kristalina Georgieva (Bulgaria) is the IMF MD since October 2019. Her second 5-year term began in 2024. She is the first person from an emerging-market country to lead the IMF in its history. Christine Lagarde was the previous IMF MD (now ECB President).",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20048,
        "question": "The IMF's Special Drawing Right (SDR) is based on a basket of how many currencies, and which is the latest addition?",
        "option_a": "4 currencies; Euro was latest", "option_b": "5 currencies; Chinese Renminbi (yuan) was latest", "option_c": "6 currencies; Indian Rupee was latest", "option_d": "5 currencies; Japanese Yen was latest",
        "correct_answer": "B",
        "explanation": "IMF SDR basket: 5 currencies — US Dollar, Euro, Chinese Renminbi, Japanese Yen, British Pound. China's Renminbi (yuan) was added in 2016, making it the first emerging-market currency in the basket. SDR is not a currency itself but an international reserve asset.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20049,
        "question": "Who is the current President of the World Bank Group (as of 2025)?",
        "option_a": "David Malpass", "option_b": "Jim Yong Kim", "option_c": "Ajay Banga", "option_d": "Paul Wolfowitz",
        "correct_answer": "C",
        "explanation": "Ajay Banga (Indian-American) has been World Bank President since June 2023. Born in Pune, India, he is the former CEO of Mastercard and the first person of Indian origin to lead the World Bank. He was nominated by the Biden administration.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20050,
        "question": "Where are the headquarers of the World Bank and IMF located?",
        "option_a": "New York, USA", "option_b": "Geneva, Switzerland", "option_c": "Washington D.C., USA", "option_d": "Brussels, Belgium",
        "correct_answer": "C",
        "explanation": "Both the World Bank Group and the IMF are headquartered in Washington D.C., USA — established as part of the Bretton Woods system in 1944. By convention, the World Bank President is American and the IMF MD is European (though this convention has been challenged).",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20051,
        "question": "The IMF's World Economic Outlook (WEO) 2025 projected India's GDP growth rate as which of the following?",
        "option_a": "5.2%", "option_b": "6.2%", "option_c": "6.5%", "option_d": "7.0%",
        "correct_answer": "C",
        "explanation": "The IMF World Economic Outlook (April 2025) projected India's GDP growth at approximately 6.5% for 2025-26 — making India the fastest-growing major economy globally. China's growth was projected at 4.6% and the global average at 2.8% amid trade war uncertainty.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20052,
        "question": "The World Bank's 'Ease of Doing Business' report was discontinued. Which report replaced it for measuring business environment?",
        "option_a": "Business Competitiveness Index", "option_b": "Business Ready (B-READY) Report", "option_c": "Global Business Climate Survey", "option_d": "Economic Freedom Index",
        "correct_answer": "B",
        "explanation": "The World Bank discontinued the 'Ease of Doing Business' report in 2021 following methodology concerns. It launched 'Business Ready (B-READY)' as its replacement, with the first full report in 2024. B-READY assesses business environment across 50 topics in areas like regulatory framework, public services, and operational efficiency.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20053,
        "question": "Who is the Director-General of the WTO serving her second term starting 2025?",
        "option_a": "Roberto Azevêdo", "option_b": "Pascal Lamy", "option_c": "Ngozi Okonjo-Iweala", "option_d": "Mike Moore",
        "correct_answer": "C",
        "explanation": "Ngozi Okonjo-Iweala (Nigeria) is WTO DG — first African and first woman to lead the WTO. She took office March 2021 and began her second 4-year term in 2025. She is a former Finance Minister of Nigeria. WTO has 166 members (as of 2025).",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ─── WHO & HEALTH ORGS (20054-20058) ───────────────────────────
    {
        "id": 20054,
        "question": "Which country re-withdrew from the World Health Organization (WHO) in January 2025?",
        "option_a": "Russia", "option_b": "China", "option_c": "United States", "option_d": "Brazil",
        "correct_answer": "C",
        "explanation": "The USA under President Trump signed an executive order on January 20, 2025 (his first day back in office) to withdraw from WHO, effective one year later. Trump had previously withdrawn in 2020 (Biden rejoined in January 2021). The withdrawal significantly impacted WHO's $6.8 billion budget.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20055,
        "question": "Who is the current Director-General of the World Health Organization (WHO) since 2017?",
        "option_a": "Gro Harlem Brundtland", "option_b": "Margaret Chan", "option_c": "Tedros Adhanom Ghebreyesus", "option_d": "Peter Ben Embarek",
        "correct_answer": "C",
        "explanation": "Dr Tedros Adhanom Ghebreyesus (Ethiopia) has been WHO DG since July 2017 and was re-elected for a second term in 2022 (through 2027). He is the first African to lead WHO. WHO HQ is in Geneva, Switzerland. WHO was founded on April 7, 1948 (World Health Day).",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20056,
        "question": "The 'Pandemic Accord' (Pandemic Treaty) negotiations at WHO in 2024-25 aimed at what?",
        "option_a": "Banning gain-of-function research globally", "option_b": "Creating a legally binding framework for pandemic prevention, preparedness and response", "option_c": "Establishing a permanent WHO pandemic task force", "option_d": "Requiring all countries to maintain 90-day vaccine stockpiles",
        "correct_answer": "B",
        "explanation": "Negotiations for a WHO Pandemic Accord (also called the Pandemic Treaty) ran from 2022-2025, aiming to create a legally binding international framework for pandemic prevention, preparedness, and response — informed by lessons from COVID-19. The US withdrawal complicated negotiations in 2025.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20057,
        "question": "The GAVI Alliance (Vaccine Alliance), which provides vaccine access to poor countries, is headquartered where?",
        "option_a": "New York, USA", "option_b": "Geneva, Switzerland", "option_c": "London, UK", "option_d": "Nairobi, Kenya",
        "correct_answer": "B",
        "explanation": "GAVI Alliance (now known as Gavi, the Vaccine Alliance) is headquartered in Geneva, Switzerland. Founded in 2000, it is a public-private partnership — partners include WHO, UNICEF, World Bank, Bill & Melinda Gates Foundation, and vaccine manufacturers. GAVI has helped immunise over 1 billion children.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20058,
        "question": "The IAEA (International Atomic Energy Agency) is headquartered in which city, and who has been its Director-General since 2019?",
        "option_a": "Geneva; Rafael Grossi", "option_b": "Vienna; Mohamed ElBaradei", "option_c": "Vienna; Rafael Grossi", "option_d": "New York; Yukiya Amano",
        "correct_answer": "C",
        "explanation": "IAEA HQ is in Vienna, Austria. Rafael Grossi (Argentina) has been IAEA DG since December 2019. He replaced Yukiya Amano (Japan) who served 2009-2019. The IAEA monitors nuclear activities globally and promotes peaceful use of nuclear energy.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ─── ASEAN & REGIONAL (20059-20064) ────────────────────────────
    {
        "id": 20059,
        "question": "Which country held the ASEAN Chairship in 2025?",
        "option_a": "Vietnam", "option_b": "Thailand", "option_c": "Malaysia", "option_d": "Philippines",
        "correct_answer": "C",
        "explanation": "Malaysia held the ASEAN Chairship in 2025 under the theme 'Inclusivity and Sustainability.' Malaysia previously chaired ASEAN in 2015. Laos held ASEAN Chair in 2024; Malaysia's 2025 Chairship focused on digital economy, green transition, and the South China Sea.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20060,
        "question": "ASEAN was founded in 1967. Which city and declaration marked its founding?",
        "option_a": "Kuala Lumpur Declaration", "option_b": "Bangkok Declaration", "option_c": "Jakarta Declaration", "option_d": "Singapore Declaration",
        "correct_answer": "B",
        "explanation": "ASEAN was founded on August 8, 1967 in Bangkok, Thailand, with the Bangkok Declaration. Founding members: Thailand, Malaysia, Singapore, Indonesia, Philippines. ASEAN HQ (Secretariat) is in Jakarta, Indonesia. ASEAN has 10 full members.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20061,
        "question": "India-ASEAN relations were upgraded to Comprehensive Strategic Partnership (CSP) in which year?",
        "option_a": "2019", "option_b": "2020", "option_c": "2021", "option_d": "2022",
        "correct_answer": "D",
        "explanation": "India-ASEAN relations were upgraded to Comprehensive Strategic Partnership (CSP) at the ASEAN-India Summit in Phnom Penh, Cambodia in November 2022. India became ASEAN's Dialogue Partner in 1992 and a Summit-level partner in 2002. India's Act East Policy focuses on ASEAN.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20062,
        "question": "The SAARC Secretariat is located in which city, and when was SAARC founded?",
        "option_a": "New Delhi; 1980", "option_b": "Kathmandu; 1985", "option_c": "Colombo; 1987", "option_d": "Dhaka; 1985",
        "correct_answer": "B",
        "explanation": "SAARC (South Asian Association for Regional Cooperation) Secretariat is in Kathmandu, Nepal. SAARC was founded in 1985 (Dhaka Declaration). Members: India, Pakistan, Bangladesh, Nepal, Sri Lanka, Bhutan, Maldives, Afghanistan (suspended). SAARC Summits have been stalled since 2016 due to India-Pakistan tensions.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20063,
        "question": "The Gulf Cooperation Council (GCC) has 6 member states. Which of these is NOT a GCC member?",
        "option_a": "Saudi Arabia", "option_b": "UAE", "option_c": "Jordan", "option_d": "Bahrain",
        "correct_answer": "C",
        "explanation": "GCC members: Saudi Arabia, UAE, Qatar, Kuwait, Bahrain, Oman — all Gulf Arab monarchies. Jordan is NOT a GCC member (it is a Hashemite Kingdom but not a Gulf state). GCC was founded in 1981; Secretariat in Riyadh, Saudi Arabia.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20064,
        "question": "The African Union Commission Chairperson since 2021 is from which country?",
        "option_a": "Nigeria", "option_b": "South Africa", "option_c": "Senegal", "option_d": "Kenya",
        "correct_answer": "C",
        "explanation": "Moussa Faki Mahamat (Chad) was AU Commission Chairperson from 2017-2025. Mauritania's Abdel-Fattah al-Sisi held AU Presidency in 2019. Senegal's Macky Sall was AU Chairperson in 2022. The AU Chairship rotates — held by Ethiopia's PM Abiy Ahmed in 2025.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ─── TRADE & ECONOMIC ORGS (20065-20070) ───────────────────────
    {
        "id": 20065,
        "question": "The WTO Appellate Body has been non-functional since 2019. What caused this?",
        "option_a": "China withdrew from the WTO", "option_b": "USA blocked new appointments to the Appellate Body, leaving it without quorum", "option_c": "India and Brazil boycotted WTO dispute proceedings", "option_d": "WTO reformed its dispute settlement system under the MC13 agreement",
        "correct_answer": "B",
        "explanation": "The WTO Appellate Body (the 'supreme court' of world trade) became non-functional in December 2019 when the USA blocked new judicial appointments, reducing it below quorum (minimum 3 of 7 judges needed). This is the WTO's biggest institutional crisis. The Multi-Party Interim Appeal Arbitration Arrangement (MPIA) was formed as an alternative.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20066,
        "question": "The 13th WTO Ministerial Conference (MC13) was held in February 2024 in which city?",
        "option_a": "Geneva", "option_b": "Abu Dhabi", "option_c": "Nairobi", "option_d": "Buenos Aires",
        "correct_answer": "B",
        "explanation": "MC13 was held in Abu Dhabi, UAE, in February 2024. Key outcomes included extending the e-commerce moratorium and fisheries subsidies negotiations. The MC14 is planned for 2026. Previous WTO Ministerial Conferences: Geneva (MC12, 2022), Buenos Aires (MC11, 2017).",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20067,
        "question": "The OECD (Organisation for Economic Co-operation and Development) is headquartered where, and India applied for membership in which year?",
        "option_a": "Brussels; 2023", "option_b": "Paris; 2023", "option_c": "Vienna; 2022", "option_d": "Geneva; 2024",
        "correct_answer": "B",
        "explanation": "OECD is headquartered in Paris, France (founded 1961). India applied for OECD membership in 2023 — accession talks are ongoing. OECD has 38 members (mostly wealthy democracies). India is currently a 'Key Partner' of OECD and participates in many OECD working groups.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20068,
        "question": "India and MERCOSUR (South American trade bloc) signed a Preferential Trade Agreement in which year?",
        "option_a": "2009", "option_b": "2015", "option_c": "2004", "option_d": "2019",
        "correct_answer": "C",
        "explanation": "India-MERCOSUR Preferential Trade Agreement (PTA) was signed in 2004 and came into effect in June 2009. MERCOSUR (Southern Common Market) = Brazil, Argentina, Uruguay, Paraguay. India-MERCOSUR trade has grown significantly; discussions on a more comprehensive FTA are ongoing.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20069,
        "question": "The RCEP (Regional Comprehensive Economic Partnership) trade agreement covers approximately what percentage of global GDP?",
        "option_a": "20%", "option_b": "30%", "option_c": "40%", "option_d": "50%",
        "correct_answer": "B",
        "explanation": "RCEP covers approximately 30% of global GDP and 30% of global population — making it the world's largest free trade agreement. RCEP = 15 countries: 10 ASEAN + Australia, China, Japan, South Korea, New Zealand. India decided not to join RCEP in 2019 due to concerns about Chinese goods flooding the market.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20070,
        "question": "The India-Middle East-Europe Economic Corridor (IMEC) was announced at which summit in 2023 and reconfirmed in 2025?",
        "option_a": "COP28 Dubai", "option_b": "QUAD Summit Tokyo", "option_c": "G20 New Delhi Summit", "option_d": "G7 Hiroshima Summit",
        "correct_answer": "C",
        "explanation": "IMEC (India-Middle East-Europe Economic Corridor) was announced at the G20 New Delhi Summit (September 2023). It comprises two corridors: India-Gulf (ship + rail) and Gulf-Europe (rail + ship). Partners: India, UAE, Saudi Arabia, Jordan, Israel, EU. It is a strategic counter to China's Belt and Road Initiative (BRI).",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ─── ENVIRONMENT & CLIMATE ORGS (20071-20076) ──────────────────
    {
        "id": 20071,
        "question": "The United Nations Ocean Conference 3 (UNOC3) was held in 2025. Which city hosted it?",
        "option_a": "Geneva, Switzerland", "option_b": "Rio de Janeiro, Brazil", "option_c": "Nice, France", "option_d": "Nairobi, Kenya",
        "correct_answer": "C",
        "explanation": "UNOC3 (United Nations Ocean Conference 3) was held in Nice, France, in June 2025. Co-hosted by France and Costa Rica. Key outcomes included the 'Nice Ocean Action Plan' and the Blue NDC Challenge. UNOC3 focused on SDG 14 (Life Below Water) and the High Seas Treaty.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20072,
        "question": "The UNEP (UN Environment Programme) is headquartered in which African city?",
        "option_a": "Addis Ababa, Ethiopia", "option_b": "Nairobi, Kenya", "option_c": "Cairo, Egypt", "option_d": "Johannesburg, South Africa",
        "correct_answer": "B",
        "explanation": "UNEP is headquartered in Nairobi, Kenya — the only UN agency HQ'd in a developing country. Founded in 1972 after the Stockholm Conference. Inger Andersen (Denmark) has been UNEP Executive Director since 2019. UNEP publishes the Global Environment Outlook.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20073,
        "question": "COP30 (30th UN Climate Conference) is scheduled to be held in 2025 in which Brazilian city?",
        "option_a": "Rio de Janeiro", "option_b": "São Paulo", "option_c": "Belém", "option_d": "Brasília",
        "correct_answer": "C",
        "explanation": "COP30 will be held in Belém, Brazil, in November 2025 — a city at the edge of the Amazon rainforest. The location symbolises the importance of protecting tropical forests. COP30 is considered a critical stocktake of progress since the Paris Agreement (2015). Brazil holds the G20 and BRICS presidencies in 2025.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20074,
        "question": "The IPCC Seventh Assessment Report (AR7) cycle is underway. What is the mandate of the IPCC?",
        "option_a": "Set carbon emission limits for countries", "option_b": "Assess scientific information on climate change without prescribing policy", "option_c": "Monitor countries' compliance with Paris Agreement", "option_d": "Fund climate adaptation projects in developing countries",
        "correct_answer": "B",
        "explanation": "The IPCC (Intergovernmental Panel on Climate Change) assesses and synthesises scientific research on climate change — it does NOT conduct original research or prescribe policy. Co-founded by UNEP and WMO in 1988. AR6 (2021-22) was the most comprehensive climate assessment. AR7 is underway for release ~2027.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20075,
        "question": "The 'Loss and Damage' fund agreed at COP27 (Egypt, 2022) became fully operational. Which institution is hosting this fund?",
        "option_a": "UNDP", "option_b": "World Bank", "option_c": "IMF", "option_d": "ADB",
        "correct_answer": "B",
        "explanation": "The Loss and Damage Fund (for climate-vulnerable developing countries) was agreed at COP27 (Sharm el-Sheikh, 2022) and operationalised at COP28 (Dubai, 2023) with the World Bank as interim host. The fund helps developing nations deal with climate impacts that cannot be adapted to — e.g., rising sea levels, extreme weather.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ─── INTELLIGENCE, DEFENCE & OTHER GROUPINGS (20076-20086) ─────
    {
        "id": 20076,
        "question": "The 'Five Eyes' intelligence-sharing alliance consists of which five countries?",
        "option_a": "G7 minus Japan and Italy", "option_b": "USA, UK, Canada, Australia, New Zealand", "option_c": "QUAD nations plus UK", "option_d": "NATO's founding five members",
        "correct_answer": "B",
        "explanation": "Five Eyes (FVEY) = USA, UK, Canada, Australia, New Zealand — all English-speaking nations, sharing intelligence under the UKUSA Agreement (1946). India is sometimes called a 'Sixth Eye' informal partner but is NOT a Five Eyes member.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20077,
        "question": "The Shanghai Cooperation Organisation (SCO) and the 'Shanghai Spirit' emphasise which approach to security?",
        "option_a": "Hard military power and deterrence", "option_b": "Non-alignment, no military alliances, and cooperative security", "option_c": "Western liberal democratic values", "option_d": "Nuclear deterrence and non-proliferation",
        "correct_answer": "B",
        "explanation": "The SCO and 'Shanghai Spirit' explicitly reject military blocs and alliances. SCO focuses on non-traditional security threats (terrorism, separatism, extremism — the 'Three Evils'). This distinguishes it from NATO. Despite including rival nations (India-Pakistan, India-China), SCO maintains a cooperative framework.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20078,
        "question": "The Rome-based United Nations food agencies include FAO, WFP, and IFAD. Which of these specifically focuses on providing EMERGENCY food aid?",
        "option_a": "FAO", "option_b": "WFP", "option_c": "IFAD", "option_d": "Codex Alimentarius Commission",
        "correct_answer": "B",
        "explanation": "WFP (World Food Programme) provides emergency food aid and humanitarian assistance. FAO (Food and Agriculture Organization) focuses on food security and agricultural development. IFAD (International Fund for Agricultural Development) finances rural agricultural projects. All three are based in Rome.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20079,
        "question": "The 'Global Gateway' initiative is the European Union's alternative to China's Belt and Road Initiative. What is its planned investment target?",
        "option_a": "€100 billion", "option_b": "€300 billion", "option_c": "€500 billion", "option_d": "€1 trillion",
        "correct_answer": "B",
        "explanation": "The EU's Global Gateway initiative (launched 2021) aims to mobilise €300 billion in infrastructure investments by 2027 — focusing on digital, climate, energy, transport, health, and education sectors in developing countries. It emphasises high standards, transparency, and private sector investment.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20080,
        "question": "The INTERPOL General Secretariat is located in which city?",
        "option_a": "Paris, France", "option_b": "Brussels, Belgium", "option_c": "Lyon, France", "option_d": "Geneva, Switzerland",
        "correct_answer": "C",
        "explanation": "INTERPOL (International Criminal Police Organization) General Secretariat is in Lyon, France. Founded in 1923; 195 member countries. INTERPOL issues 'Red Notices' — requests to law enforcement worldwide to locate and provisionally arrest wanted persons. India is an active INTERPOL member.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20081,
        "question": "The D-8 Organization for Economic Cooperation groups 8 developing countries. Which of the following is NOT a D-8 member?",
        "option_a": "Pakistan", "option_b": "Bangladesh", "option_c": "India", "option_d": "Indonesia",
        "correct_answer": "C",
        "explanation": "D-8 = Bangladesh, Egypt, Indonesia, Iran, Malaysia, Nigeria, Pakistan, Turkey. India is NOT a D-8 member. D-8 was established in 1997 to promote economic cooperation among 8 large developing-country Muslim-majority nations. D-8 Secretariat is in Istanbul, Turkey.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20082,
        "question": "The International Solar Alliance (ISA), co-founded by India, now has over 100 member countries. Where is the ISA Secretariat located?",
        "option_a": "New Delhi, India", "option_b": "Gurugram (Gurgaon), Haryana, India", "option_c": "Geneva, Switzerland", "option_d": "Abu Dhabi, UAE",
        "correct_answer": "B",
        "explanation": "ISA Secretariat is in Gurugram (Gurgaon), Haryana, India — adjacent to the National Solar Energy Institute campus. ISA was launched at COP21 in Paris (2015) by India's PM Modi and France's President Hollande. ISA focuses on solar energy adoption in countries between the Tropics of Cancer and Capricorn.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20083,
        "question": "The FATF (Financial Action Task Force) is the global body setting standards to combat which threats?",
        "option_a": "Cybercrime and hacking", "option_b": "Money laundering, terrorist financing, and proliferation financing", "option_c": "Drug trafficking and human smuggling", "option_d": "Tax evasion and offshore banking",
        "correct_answer": "B",
        "explanation": "FATF (est. 1989) sets international standards to combat money laundering, terrorist financing, and proliferation financing. FATF's 'grey list' (Enhanced Monitoring) and 'blacklist' (Call for Action) have serious consequences. Pakistan was on the grey list 2018-2022. FATF HQ: Paris.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20084,
        "question": "India signed the Coalition for Disaster Resilient Infrastructure (CDRI) which was launched at which summit?",
        "option_a": "COP26 Glasgow 2021", "option_b": "UNGA 74th session 2019", "option_c": "G20 Osaka 2019", "option_d": "UNFCCC COP25 Madrid 2019",
        "correct_answer": "B",
        "explanation": "CDRI was launched by India's PM Modi at UNGA 74th session in New York in September 2019. Co-launched with the UK. CDRI promotes building disaster and climate-resilient infrastructure. Secretariat: New Delhi, India. CDRI has 42 national, 7 international organisation, and 2 private sector members.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20085,
        "question": "The 'Blue NDC Challenge' launched at UNOC3 2025 in Nice primarily asks countries to do what?",
        "option_a": "Fund deep-sea mining research", "option_b": "Integrate ocean-related targets into their climate commitments (NDCs)", "option_c": "Ban deep-sea trawling globally by 2030", "option_d": "Establish a Blue Carbon trading market",
        "correct_answer": "B",
        "explanation": "The Blue NDC Challenge (launched by France and Brazil at UNOC3, Nice, June 2025) asks countries to integrate ocean-related targets into their Nationally Determined Contributions (NDCs) under the Paris Agreement — linking ocean conservation with climate action. It builds on SDG 14 (Life Below Water).",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    {
        "id": 20086,
        "question": "The India–UK Free Trade Agreement (FTA) was signed in May 2025 after several years of negotiations. Which industry did India prioritise in the FTA negotiations?",
        "option_a": "Dairy and agricultural exports", "option_b": "IT services, textiles, and pharmaceutical exports", "option_c": "Steel and automotive exports", "option_d": "Defence equipment",
        "correct_answer": "B",
        "explanation": "The India-UK FTA (signed May 6, 2025) prioritised India's IT services exports, textiles, and pharmaceuticals getting preferential access to the UK market. The UK sought tariff reductions on Scotch whisky, cars, and improved investment access. The FTA followed the UK's departure from the EU (Brexit).",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
]


def seed():
    if USE_POSTGRES:
        import psycopg2
        conn = psycopg2.connect(DATABASE_URL)
        conn.autocommit = False
        cur = conn.cursor()
        delete_sql = "DELETE FROM questions WHERE id >= %s AND id <= %s"
        insert_sql = """INSERT INTO questions
            (id, question_text, option_a, option_b, option_c, option_d,
             correct_answer, explanation, folder, topic)
            VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
            ON CONFLICT (id) DO UPDATE SET
              question_text=EXCLUDED.question_text,
              option_a=EXCLUDED.option_a, option_b=EXCLUDED.option_b,
              option_c=EXCLUDED.option_c, option_d=EXCLUDED.option_d,
              correct_answer=EXCLUDED.correct_answer,
              explanation=EXCLUDED.explanation"""
    else:
        conn = sqlite3.connect(os.path.join(os.path.dirname(__file__), "database.db"))
        cur = conn.cursor()
        delete_sql = "DELETE FROM questions WHERE id >= ? AND id <= ?"
        insert_sql = """INSERT OR REPLACE INTO questions
            (id, question_text, option_a, option_b, option_c, option_d,
             correct_answer, explanation, folder, topic)
            VALUES (?,?,?,?,?,?,?,?,?,?)"""

    cur.execute(delete_sql, (20001, 20086))
    for q in INTL_MCQS:
        cur.execute(insert_sql, (
            q["id"], q["question"],
            q["option_a"], q["option_b"], q["option_c"], q["option_d"],
            q["correct_answer"], q["explanation"],
            q["folder"], q["topic"],
        ))
    conn.commit()
    conn.close()
    print(f"[seed_intl_orgs] {len(INTL_MCQS)} International Orgs 2025-2026 MCQs seeded (IDs 20001-20086). Force-refreshed.")


if __name__ == "__main__":
    seed()
