"""
seed_summits_mcq.py
80 GKToday-style MCQs — Topic: International Current Affairs → Summits & Conferences
Coverage: 2024-2026 | International + India domestic conferences
Folder: AP_HC | Topic: International_Current_Affairs | Sub-topic: Summits
IDs: 21001–21080
"""

import os, sqlite3

DATABASE_URL = os.environ.get("DATABASE_URL", "")
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)
USE_POSTGRES = bool(DATABASE_URL)

SUMMIT_MCQS = [
    # ─── G20 (1-6) ──────────────────────────────────────────────────
    {
        "id": 21001,
        "question": "India hosted the G20 Leaders' Summit in 2023 under which theme?",
        "option_a": "One World, One Future",
        "option_b": "Vasudhaiva Kutumbakam — One Earth, One Family, One Future",
        "option_c": "Building a Sustainable World Together",
        "option_d": "Partnership for Global Peace",
        "correct_answer": "B",
        "explanation": "India's G20 2023 theme was 'Vasudhaiva Kutumbakam — One Earth, One Family, One Future', drawn from the Maha Upanishad (ancient Sanskrit text, NOT Rigveda). The 18th G20 Summit was held at Bharat Mandapam, New Delhi on September 9-10, 2023.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21002,
        "question": "Which new bloc was admitted as a permanent G20 member at India's G20 Summit in 2023?",
        "option_a": "ASEAN",
        "option_b": "African Union (AU)",
        "option_c": "Arab League",
        "option_d": "SAARC",
        "correct_answer": "B",
        "explanation": "The African Union (AU) was admitted as a permanent G20 member at India's 2023 G20 Summit — India's biggest diplomatic achievement during its Presidency. AU represents 55 African nations. Previously, only EU had similar status among regional blocs.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21003,
        "question": "The 2025 G20 Leaders' Summit was held in which country — making it the first G20 Summit held in Africa?",
        "option_a": "Nigeria",
        "option_b": "Kenya",
        "option_c": "South Africa",
        "option_d": "Egypt",
        "correct_answer": "C",
        "explanation": "South Africa hosted the G20 in 2025 (Johannesburg) — the first time Africa hosted a G20 Summit. South Africa became G20 Chair after Brazil (2024). The handover to USA (2026 host) happened on January 12, 2026.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21004,
        "question": "Which country is hosting the G20 Summit in 2026, and in which city?",
        "option_a": "UK, London",
        "option_b": "USA, Miami",
        "option_c": "France, Paris",
        "option_d": "Japan, Osaka",
        "correct_answer": "B",
        "explanation": "USA is hosting G20 in 2026 at Miami. South Africa handed over the G20 Presidency to USA on January 12, 2026. This will be the 21st G20 Leaders' Summit under Trump administration.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21005,
        "question": "Which initiative was launched by India at the G20 New Delhi Summit 2023 to promote sustainable fuels?",
        "option_a": "Green Hydrogen Alliance",
        "option_b": "Global Biofuels Alliance",
        "option_c": "IPEF (Indo-Pacific Economic Framework)",
        "option_d": "Green New Deal",
        "correct_answer": "B",
        "explanation": "Global Biofuels Alliance (GBA) was launched at G20 New Delhi Summit 2023 at India's initiative, with USA and Brazil as co-founding members. GBA promotes use of biofuels as sustainable alternatives and includes 19 member nations and 12 international organizations.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21006,
        "question": "The G20 was elevated from a Finance Ministers' forum to a Leaders' Summit level in which year — triggered by the global financial crisis?",
        "option_a": "2001",
        "option_b": "2005",
        "option_c": "2008",
        "option_d": "2010",
        "correct_answer": "C",
        "explanation": "G20 was established in 1999 as a Finance Ministers' forum but was elevated to Leaders' Summit level in 2008 — triggered by the global financial crisis. The first G20 Leaders' Summit was held in Washington DC in November 2008.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    # ─── BRICS (7-12) ───────────────────────────────────────────────
    {
        "id": 21007,
        "question": "The 16th BRICS Summit was held in Kazan, Russia in October 2024. Which landmark bilateral meeting happened on its sidelines?",
        "option_a": "Modi-Biden last bilateral",
        "option_b": "First Modi-Xi bilateral after the 2020 Galwan Valley clash",
        "option_c": "Modi-Zelensky peace talks",
        "option_d": "India-China LAC treaty signed",
        "correct_answer": "B",
        "explanation": "At the 16th BRICS Summit (Kazan, October 22-24, 2024), PM Modi and President Xi Jinping held their first formal bilateral since the 2020 Galwan Valley clash — a gap of 4 years. Both sides agreed to resume LAC patrolling at Depsang and Demchok friction points.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21008,
        "question": "India is chairing BRICS in 2026 under which theme — which cleverly embeds the BRICS acronym?",
        "option_a": "Building Bridges, Resilience, Innovation, Cooperation, Sustainability",
        "option_b": "Building for Resilience, Innovation, Cooperation and Sustainability",
        "option_c": "BRICS for Responsible, Inclusive, Connected, Sustainable world",
        "option_d": "Bold Reforms, Inclusive Growth, Cooperation and Solidarity",
        "correct_answer": "B",
        "explanation": "India's BRICS 2026 theme is 'Building for Resilience, Innovation, Cooperation and Sustainability' — the first letters (B-R-I-C-S) spell BRICS itself. The 18th BRICS Summit is scheduled in New Delhi on September 12-13, 2026.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21009,
        "question": "At the 17th BRICS Summit (Brazil, 2025), BRICS nations supported India's bid to host which future UN climate conference?",
        "option_a": "COP31 in 2026",
        "option_b": "COP32 in 2027",
        "option_c": "COP33 in 2028",
        "option_d": "COP35 in 2030",
        "correct_answer": "C",
        "explanation": "At the 17th BRICS Summit (Brazil, 2025), BRICS nations officially backed India's bid to host COP33 in 2028. China and Russia also reaffirmed support for India's permanent UNSC membership. If successful, COP33 would be India's first-ever COP hosting.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21010,
        "question": "The BRICS Foreign Ministers' Meeting under India's 2026 Chairmanship was held at which venue in New Delhi?",
        "option_a": "Vigyan Bhavan",
        "option_b": "Bharat Mandapam",
        "option_c": "Hyderabad House",
        "option_d": "Taj Palace Hotel",
        "correct_answer": "B",
        "explanation": "The BRICS Foreign Ministers' Meeting was held on May 14-15, 2026 at Bharat Mandapam, New Delhi. It was chaired by EAM S. Jaishankar — a key preparatory meeting ahead of the 18th BRICS Summit in September 2026.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21011,
        "question": "How many countries are now full BRICS members after the 2024 expansion?",
        "option_a": "5",
        "option_b": "6",
        "option_c": "9",
        "option_d": "10",
        "correct_answer": "D",
        "explanation": "BRICS expanded to 10 members on January 1, 2024 with Egypt, Ethiopia, Iran, UAE, Saudi Arabia joining. Argentina was invited but declined under new President Milei. Original 5: Brazil, Russia, India, China, South Africa (joined 2010).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21012,
        "question": "Where and when is the 18th BRICS Summit scheduled to be held?",
        "option_a": "Mumbai, October 2026",
        "option_b": "New Delhi, September 12-13, 2026",
        "option_c": "Hyderabad, August 2026",
        "option_d": "Chennai, November 2026",
        "correct_answer": "B",
        "explanation": "The 18th BRICS Summit will be held in New Delhi on September 12-13, 2026, during India's BRICS Chairmanship. It will be the first BRICS Summit in India since BRICS expanded to 10 members in 2024.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    # ─── G7 (13-16) ─────────────────────────────────────────────────
    {
        "id": 21013,
        "question": "The G7 Summit 2025 was held in which country and location?",
        "option_a": "Italy, Fasano (Puglia)",
        "option_b": "Japan, Hiroshima",
        "option_c": "Canada, Kananaskis (Alberta)",
        "option_d": "France, Évian-les-Bains",
        "correct_answer": "C",
        "explanation": "Canada hosted the G7 Summit 2025 at Kananaskis, Alberta. Kananaskis is a remote mountain resort chosen partly for security. Key issue: Trump's tariffs caused friction among G7 allies. Italy hosted G7 2024 (Puglia); France hosts G7 2026.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21014,
        "question": "The G7 Summit 2026 will be hosted by France at which venue?",
        "option_a": "Paris",
        "option_b": "Nice",
        "option_c": "Lyon",
        "option_d": "Évian-les-Bains",
        "correct_answer": "D",
        "explanation": "France is hosting G7 2026 at Évian-les-Bains (June 15-17, 2026) — a resort town on the south shore of Lake Geneva in the Haute-Savoie region. France last hosted G7 in 2019 (Biarritz). President Macron chairs the 2026 G7.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21015,
        "question": "The G7 Summit 2024 was held in which country and at what venue?",
        "option_a": "Japan, Tokyo",
        "option_b": "Italy, Fasano (Puglia)",
        "option_c": "Germany, Munich",
        "option_d": "UK, London",
        "correct_answer": "B",
        "explanation": "Italy hosted G7 2024 at Fasano, in the Puglia (Apulia) region of southern Italy. Key outcome: $50 billion loan to Ukraine using interest from frozen Russian sovereign assets. India's PM Modi was invited as outreach partner.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21016,
        "question": "Which country will host the NATO Summit in 2026, as announced at the 2025 Hague Summit?",
        "option_a": "Germany",
        "option_b": "Poland",
        "option_c": "Romania",
        "option_d": "Türkiye (Turkey)",
        "correct_answer": "D",
        "explanation": "The NATO Summit 2026 will be held in Türkiye (Turkey), as confirmed at the 2025 Hague Summit. The 2025 NATO Summit at The Hague (Netherlands) adopted a historic 5% GDP defence spending target — the highest NATO spending commitment ever.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    # ─── QUAD & SCO (17-21) ─────────────────────────────────────────
    {
        "id": 21017,
        "question": "The QUAD Leaders' Summit 2024 was held in Wilmington, USA. Which new maritime initiative was launched at this summit?",
        "option_a": "QUAD Free Navigation Agreement",
        "option_b": "Maritime Initiative for Training in the Indo-Pacific (MAITRI)",
        "option_c": "Indo-Pacific Logistics Network (IPLN) Plus",
        "option_d": "QUAD Blue Economy Fund",
        "correct_answer": "B",
        "explanation": "MAITRI (Maritime Initiative for Training in the Indo-Pacific) was launched at the QUAD Wilmington Summit (September 21, 2024, Delaware). MAITRI trains Indo-Pacific partner nation coast guards. Biden hosted this as his final QUAD Summit before leaving office.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21018,
        "question": "Which country hosted the QUAD Leaders' Summit in 2025?",
        "option_a": "USA",
        "option_b": "Japan",
        "option_c": "Australia",
        "option_d": "India",
        "correct_answer": "D",
        "explanation": "India hosted the QUAD Leaders' Summit in 2025 (New Delhi). PM Modi hosted the leaders of USA, Japan, and Australia. This was the first QUAD Summit under US President Trump's second term. India is a key QUAD host for 2025.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21019,
        "question": "The SCO Summit 2024 was held in Astana, Kazakhstan. Which country formally joined SCO as its 10th full member at this summit?",
        "option_a": "Iran",
        "option_b": "Turkey",
        "option_c": "Belarus",
        "option_d": "Saudi Arabia",
        "correct_answer": "C",
        "explanation": "Belarus formally joined SCO as its 10th full member at the Astana, Kazakhstan SCO Summit (July 3-4, 2024). Iran had joined as 9th member at the SCO Summit in 2023. India and Pakistan joined in 2017 as the 7th and 8th members.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21020,
        "question": "NATO Summit 2025 was held in The Hague, Netherlands (June 24-25). What historic defence spending target was agreed upon?",
        "option_a": "3% of GDP",
        "option_b": "4% of GDP",
        "option_c": "5% of GDP (3.5% core + 1.5% infrastructure)",
        "option_d": "2% of GDP (reaffirmed)",
        "correct_answer": "C",
        "explanation": "NATO Summit 2025 (The Hague) adopted a historic 5% GDP defence target — 3.5% for core defence needs and 1.5% for defence-related infrastructure. This replaced the earlier 2% benchmark and is the highest NATO spending commitment ever, driven by Trump's pressure.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21021,
        "question": "The NATO Summit 2024 celebrated which milestone anniversary, and where was it held?",
        "option_a": "50th anniversary, Paris",
        "option_b": "75th anniversary, Washington DC",
        "option_c": "70th anniversary, Brussels",
        "option_d": "80th anniversary, London",
        "correct_answer": "B",
        "explanation": "NATO celebrated its 75th anniversary at the Washington DC Summit (July 9-11, 2024). NATO was founded April 4, 1949. At this summit, Sweden's membership as 32nd member was in effect (joined March 7, 2024). Mark Rutte replaced Stoltenberg as Secretary-General in October 2024.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    # ─── ASEAN & COP (22-27) ────────────────────────────────────────
    {
        "id": 21022,
        "question": "Which country became the 11th member of ASEAN at the 47th ASEAN Summit held in Malaysia in 2025?",
        "option_a": "Papua New Guinea",
        "option_b": "Bangladesh",
        "option_c": "East Timor (Timor-Leste)",
        "option_d": "Sri Lanka",
        "correct_answer": "C",
        "explanation": "East Timor (Timor-Leste) became ASEAN's 11th member at the 47th ASEAN Summit, Malaysia, 2025. Malaysia's chairmanship theme was 'Inclusivity and Sustainability'. East Timor had been an observer since 2011.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21023,
        "question": "COP29 (2024) was held in Baku, Azerbaijan. What was the key climate finance decision taken — called the 'New Collective Quantified Goal' (NCQG)?",
        "option_a": "$100 billion per year by 2030",
        "option_b": "$200 billion per year by 2032",
        "option_c": "$300 billion per year by 2035",
        "option_d": "$500 billion per year by 2040",
        "correct_answer": "C",
        "explanation": "COP29 (Baku, Azerbaijan, November 11-22, 2024) adopted NCQG: $300 billion per year by 2035 from developed to developing nations. India and other developing nations had demanded $1.3 trillion, calling $300bn 'paltry' and 'inadequate'.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21024,
        "question": "COP30 (2025 UN Climate Conference) will be held in which city, making it the first COP in the Amazon region?",
        "option_a": "São Paulo",
        "option_b": "Rio de Janeiro",
        "option_c": "Brasília",
        "option_d": "Belém",
        "correct_answer": "D",
        "explanation": "COP30 will be held in Belém, Pará state, Brazil (November 10-21, 2025) — in the Amazon region. This is the first time COP is hosted in the Amazon, making it symbolically significant for biodiversity and deforestation issues. Often called the 'Amazon COP'.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21025,
        "question": "At which COP conference was the phrase 'transition away from fossil fuels' first included in the final text — a historic first?",
        "option_a": "COP26 Glasgow (2021)",
        "option_b": "COP27 Sharm El-Sheikh (2022)",
        "option_c": "COP28 Dubai (2023)",
        "option_d": "COP29 Baku (2024)",
        "correct_answer": "C",
        "explanation": "COP28 Dubai (2023) was the first time 'transition away from fossil fuels' language was included in the final COP text — a historic breakthrough. COP28 also completed the first Global Stocktake under the Paris Agreement. COP27 created the Loss & Damage Fund.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21026,
        "question": "The 'Summit of the Future' held in New York (September 22-23, 2024) adopted which key global governance document?",
        "option_a": "Global Climate Charter",
        "option_b": "Pact for the Future (with Global Digital Compact)",
        "option_c": "Declaration on AI Safety",
        "option_d": "UN Charter 2.0",
        "correct_answer": "B",
        "explanation": "The Summit of the Future (New York, September 22-23, 2024) adopted the 'Pact for the Future' — a sweeping document covering reformed multilateralism, UNSC reform commitment, and the Global Digital Compact (framework for AI governance and digital inclusion globally).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21027,
        "question": "The 'Global Digital Compact' adopted at the Summit of the Future 2024 primarily addresses which area?",
        "option_a": "International cyber warfare rules",
        "option_b": "Digital trade tariffs and WTO norms",
        "option_c": "AI governance, data flows, and digital inclusion globally",
        "option_d": "Cryptocurrency regulation",
        "correct_answer": "C",
        "explanation": "The Global Digital Compact (part of the Pact for the Future, adopted September 2024) provides a framework for AI governance, data flows, and digital inclusion globally. It addresses principles for trustworthy AI, access to the internet for all, and digital cooperation.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    # ─── India Bilateral Summits (28-33) ────────────────────────────
    {
        "id": 21028,
        "question": "When and where was the first bilateral meeting between PM Modi and US President Trump (2nd term) held?",
        "option_a": "January 20, 2025, New York",
        "option_b": "February 13, 2025, White House, Washington DC",
        "option_c": "March 1, 2025, Mar-a-Lago, Florida",
        "option_d": "April 5, 2025, New Delhi",
        "correct_answer": "B",
        "explanation": "PM Modi met US President Trump on February 13, 2025 at the White House, Washington DC — their first bilateral of Trump's 2nd term. Key outcomes: India committed to increase US oil/gas imports, defence purchases (F-35s consideration, MQ-9B drones), and $500bn bilateral trade target by 2030.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21029,
        "question": "PM Modi visited Moscow in July 2024 for the first time in 5 years and met President Putin. What was significant about this visit?",
        "option_a": "India signed a defence treaty with Russia",
        "option_b": "First India PM visit to Russia since 2019; Modi urged peace in Ukraine",
        "option_c": "India joined the CSTO alliance",
        "option_d": "India-Russia Free Trade Agreement signed",
        "correct_answer": "B",
        "explanation": "PM Modi's July 2024 Moscow visit was the first India PM visit to Russia since 2019 (5 years). Modi met Putin and urged peaceful resolution of the Ukraine conflict. India reaffirmed strategic autonomy. Modi's famous quote: 'This is not an era of war.' The visit drew western criticism but India defended it as diplomatic engagement.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21030,
        "question": "The 23rd India-Russia Annual Summit was held in New Delhi in December 2025. It marked the 25th anniversary of which agreement?",
        "option_a": "India-Russia Defence Cooperation Treaty",
        "option_b": "India-Russia Strategic Partnership (signed 2000)",
        "option_c": "India-Russia Nuclear Agreement",
        "option_d": "India-Russia Space Cooperation MOU",
        "correct_answer": "B",
        "explanation": "The 23rd India-Russia Annual Summit (New Delhi, December 2025) marked the 25th anniversary of the India-Russia Strategic Partnership signed in 2000. Bilateral trade target: $100 billion by 2030. FTA negotiations started with Eurasian Economic Union (EAEU).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21031,
        "question": "The EU-India Free Trade Agreement (FTA) was concluded on January 27, 2026. What is significant about its scale?",
        "option_a": "It covers 100 countries",
        "option_b": "It covers approximately 2 billion people — the world's largest bilateral FTA by population",
        "option_c": "It has zero tariffs on all goods",
        "option_d": "It replaces WTO for EU-India trade",
        "correct_answer": "B",
        "explanation": "The EU-India FTA (concluded January 27, 2026) covers ~450 million (EU) + ~1.4 billion (India) = approximately 2 billion people, making it the world's largest bilateral trade deal by population. It was concluded after 16 rounds of negotiations covering goods, services, investments, and digital trade.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21032,
        "question": "The QUAD Wilmington Summit 2024 launched the 'QUAD at Sea Ship Observer Programme'. What does this involve?",
        "option_a": "Joint QUAD naval base establishment",
        "option_b": "Rotating naval observers on each other's vessels for interoperability",
        "option_c": "Shared satellite surveillance of the Indo-Pacific",
        "option_d": "QUAD unified naval command structure",
        "correct_answer": "B",
        "explanation": "The QUAD at Sea Ship Observer Programme (launched Wilmington 2024) places rotating naval observers from each QUAD nation (India, USA, Japan, Australia) on each other's naval vessels to enhance maritime interoperability. Along with MAITRI, it was a key deliverable of Biden's last QUAD.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21033,
        "question": "CHOGM 2024 was held in Apia, Samoa — making it the first CHOGM hosted by a Pacific island nation. Who is the Head of the Commonwealth?",
        "option_a": "Queen Elizabeth II",
        "option_b": "King Charles III",
        "option_c": "Prince William",
        "option_d": "Prime Minister Rishi Sunak",
        "correct_answer": "B",
        "explanation": "King Charles III is Head of the Commonwealth (since 2022). CHOGM 2024 in Apia, Samoa was his first CHOGM as Head. Samoa was the first Pacific island nation to host CHOGM. Commonwealth has 54 member nations. Secretariat HQ = Marlborough House, London.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    # ─── WEF, APEC, Other International (34-38) ─────────────────────
    {
        "id": 21034,
        "question": "The World Economic Forum (WEF) Annual Meeting in Davos, January 2025, had which theme?",
        "option_a": "Rebuilding Trust",
        "option_b": "Collaboration for the Intelligent Age",
        "option_c": "Cooperation in a Fragmented World",
        "option_d": "Technology for a Better World",
        "correct_answer": "B",
        "explanation": "WEF Davos 2025 theme was 'Collaboration for the Intelligent Age' (January 20-24, 2025). Artificial Intelligence was the central theme. WEF 2024 theme was 'Rebuilding Trust'; WEF 2023 was 'Cooperation in a Fragmented World'. Note: Jan 20 was also Trump's inauguration day.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21035,
        "question": "APEC 2024 was held in Lima, Peru in November 2024. Which significant bilateral meeting happened on APEC sidelines?",
        "option_a": "Modi-Biden final bilateral",
        "option_b": "Xi Jinping-Joe Biden final bilateral before Biden's term ended",
        "option_c": "Trump-Putin ceasefire talks",
        "option_d": "India-China border agreement",
        "correct_answer": "B",
        "explanation": "The Xi Jinping-Biden final bilateral occurred on the sidelines of APEC Lima 2024 — Biden's last major bilateral with China's President before leaving office. APEC 2024 was also Biden's last APEC. APEC 2025 = Gyeongju, South Korea.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21036,
        "question": "APEC 2025 was held in which country — the first time that country hosted APEC?",
        "option_a": "Vietnam",
        "option_b": "Indonesia",
        "option_c": "South Korea (Gyeongju)",
        "option_d": "Malaysia",
        "correct_answer": "C",
        "explanation": "APEC 2025 was held in Gyeongju, South Korea (October 2025) — marking the first time APEC was hosted in South Korea. Gyeongju is South Korea's ancient capital, known for its historical heritage. APEC 2024 was in Lima, Peru.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21037,
        "question": "The International Conference on Glaciers' Preservation 2025 was held in which capital city — under the UN's International Year of Glacier Preservation?",
        "option_a": "Geneva, Switzerland",
        "option_b": "Reykjavik, Iceland",
        "option_c": "Dushanbe, Tajikistan",
        "option_d": "Oslo, Norway",
        "correct_answer": "C",
        "explanation": "The International Conference on Glaciers' Preservation 2025 was held in Dushanbe, the capital of Tajikistan. 2025 is the UN International Year of Glacier Preservation. Tajikistan hosted the conference focusing on glacier retreat and freshwater protection.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21038,
        "question": "The 6th BIMSTEC Summit was held in which city in 2025?",
        "option_a": "Dhaka, Bangladesh",
        "option_b": "Colombo, Sri Lanka",
        "option_c": "Bangkok, Thailand",
        "option_d": "Kathmandu, Nepal",
        "correct_answer": "C",
        "explanation": "The 6th BIMSTEC Summit was held in Bangkok, Thailand in 2025. BIMSTEC = Bay of Bengal Initiative for Multi-Sectoral Technical and Economic Cooperation. Its HQ is in Dhaka, Bangladesh. Members: India, Bangladesh, Myanmar, Sri Lanka, Thailand, Nepal, Bhutan (7 members).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    # ─── India DOMESTIC Summits (39-60) — GKToday Focus Zone ────────
    {
        "id": 21039,
        "question": "The 28th National Conference on e-Governance (NCeG) 2025 was held in which city — particularly relevant for AP PSC aspirants?",
        "option_a": "Hyderabad, Telangana",
        "option_b": "Visakhapatnam, Andhra Pradesh",
        "option_c": "New Delhi",
        "option_d": "Bengaluru, Karnataka",
        "correct_answer": "B",
        "explanation": "The 28th NCeG 2025 was held in Visakhapatnam, Andhra Pradesh (September 22-23, 2025), organised jointly by DARPG + MeitY + AP Government. Theme: 'Viksit Bharat: Civil Service and Digital Transformation'. Important for AP PSC as Andhra Pradesh co-hosted it.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21040,
        "question": "What is the theme of the 28th National Conference on e-Governance (NCeG) 2025 held in Visakhapatnam?",
        "option_a": "Digital India: Transforming Governance",
        "option_b": "AI for Good Governance",
        "option_c": "Viksit Bharat: Civil Service and Digital Transformation",
        "option_d": "One Nation, One Digital Platform",
        "correct_answer": "C",
        "explanation": "NCeG 2025 (Visakhapatnam, September 22-23) theme was 'Viksit Bharat: Civil Service and Digital Transformation'. Organised by DARPG (Department of Administrative Reforms & Public Grievances) + MeitY + Andhra Pradesh Government.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21041,
        "question": "The 60th All India Conference of Director Generals and Inspector Generals of Police (2025) was held at which institution?",
        "option_a": "IIT Delhi, New Delhi",
        "option_b": "IIM Raipur, Chhattisgarh",
        "option_c": "NPA Hyderabad, Telangana",
        "option_d": "IIM Ahmedabad, Gujarat",
        "correct_answer": "B",
        "explanation": "The 60th All India DGP/IGP Conference was held at IIM Raipur, Chhattisgarh (November 28-30, 2025). PM Modi attended. Theme: 'Viksit Bharat Security Dimensions for building a Surakshit Bharat'. The annual DGP Conference is chaired by the PM.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21042,
        "question": "MANTHAN 2025, organised by the Ministry of Defence, was held in which city and had what theme?",
        "option_a": "Pune — 'Make in India for Defence'",
        "option_b": "New Delhi — 'Strategic Roadmap to Aatmanirbhar Bharat @2047'",
        "option_c": "Bengaluru — 'AI in Defence'",
        "option_d": "Chennai — 'Maritime Security for Viksit Bharat'",
        "correct_answer": "B",
        "explanation": "MANTHAN 2025 was held in New Delhi (September 18, 2025), organised by Directorate General of Defence Estates. Theme: 'Strategic Roadmap to Aatmanirbhar Bharat @2047'. Inaugurated by Defence Minister Rajnath Singh. Focus: defence land management, digital tools, governance.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21043,
        "question": "The Global Food Regulators Summit (GFRS) 2025 was organised by which body and held at which venue in New Delhi?",
        "option_a": "FSSAI; Bharat Mandapam",
        "option_b": "APEDA; Vigyan Bhavan",
        "option_c": "NABARD; India International Centre",
        "option_d": "MoFPI; New Delhi Convention Centre",
        "correct_answer": "A",
        "explanation": "GFRS 2025 was organised by FSSAI (Food Safety and Standards Authority of India) and held at Bharat Mandapam, New Delhi (September 26-27, 2025). Theme: 'Evolving Food Systems – Yatha Annam Tatha Manah'. It ran alongside World Food India 2025.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21044,
        "question": "The Rising North East Investors Summit 2025 was organised by which Ministry and held in which city?",
        "option_a": "Ministry of Commerce; Guwahati",
        "option_b": "Ministry of Development of North Eastern Region (MDoNER); New Delhi",
        "option_c": "Ministry of Home Affairs; Shillong",
        "option_d": "NITI Aayog; New Delhi",
        "correct_answer": "B",
        "explanation": "Rising North East Investors Summit 2025 was organised by MDoNER (Ministry of Development of North Eastern Region) in New Delhi. PM Modi inaugurated it. Investment interests worth ₹4.48 lakh crore were attracted. Focus sectors: tourism, agro-food, textiles, healthcare, IT, energy.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21045,
        "question": "Vibrant Gujarat Summit 2025 was held in Gandhinagar in January 2025. Which edition was this?",
        "option_a": "10th edition",
        "option_b": "11th edition",
        "option_c": "12th edition",
        "option_d": "13th edition",
        "correct_answer": "D",
        "explanation": "Vibrant Gujarat Summit 2025 (January 10-12, Gandhinagar) was the 13th edition. ₹24 lakh crore investments were pledged. Delegations from 50+ countries participated. Focus areas: manufacturing, green energy, semiconductors, digital economy. PM Modi inaugurated.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21046,
        "question": "The Global Energy Leaders' Summit (GELS) 2025 was held in which Indian city/state?",
        "option_a": "Bhubaneswar, Odisha",
        "option_b": "Puri, Odisha",
        "option_c": "Hyderabad, Telangana",
        "option_d": "Visakhapatnam, Andhra Pradesh",
        "correct_answer": "B",
        "explanation": "GELS 2025 was held in Puri, Odisha (December 5-7, 2025). Organised with Tony Blair Institute (TBI) and IIT-Kanpur. Theme: 'Powering India: Sufficiency, Balance, Innovation'. Energy ministers from Malaysia, Indonesia, Singapore, Bhutan participated. Note: Puri, NOT Bhubaneswar.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21047,
        "question": "The 3rd North East Aviation Summit 2025 was held in which city of Arunachal Pradesh?",
        "option_a": "Dibrugarh",
        "option_b": "Tezpur",
        "option_c": "Itanagar",
        "option_d": "Naharlagun",
        "correct_answer": "C",
        "explanation": "The 3rd North East Aviation Summit 2025 (North East Region Ministers' Conference on Civil Aviation) was held in Itanagar, Arunachal Pradesh. Key fact: Operational airports in NE India increased from 9 (2014) to 16 (2025); UDAN scheme highlighted. Ministry of Civil Aviation organised.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21048,
        "question": "The 8th India International Tea Conference 2025 was held in which city?",
        "option_a": "Darjeeling, West Bengal",
        "option_b": "Guwahati, Assam",
        "option_c": "Ooty, Tamil Nadu",
        "option_d": "Kochi, Kerala",
        "correct_answer": "D",
        "explanation": "The 8th India International Tea Conference 2025 was held in Kochi, Kerala (September 18-20, 2025). Organised by UPASI (United Planters Association of Southern India) + Tea Board India. Theme: 'Innovating the Tea Ecosystem for Tomorrow'. 450+ delegates from 10+ countries.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21049,
        "question": "The World Summit on Disaster Management 2025 was held in which city, where upgrades to early-warning systems were announced?",
        "option_a": "Shimla, Himachal Pradesh",
        "option_b": "Gangtok, Sikkim",
        "option_c": "Dehradun, Uttarakhand",
        "option_d": "Darjeeling, West Bengal",
        "correct_answer": "C",
        "explanation": "World Summit on Disaster Management 2025 was held in Dehradun, Uttarakhand. Theme: 'Strengthening International Cooperation for Building Resilient Communities'. Dr. Jitendra Singh announced 6 new weather radars, 33 observatories, and 142 Automatic Weather Stations for Uttarakhand.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21050,
        "question": "The 2nd National Mediation Conference 2025 was held in which city?",
        "option_a": "Kolkata",
        "option_b": "Chennai",
        "option_c": "Bhubaneswar",
        "option_d": "Hyderabad",
        "correct_answer": "C",
        "explanation": "The 2nd National Mediation Conference 2025 was held in Bhubaneswar, Odisha. Chief Justice B.R. Gavai highlighted the Mediation Act, 2023. Odisha was positioned as a hub for legal innovation and ADR (Alternative Dispute Resolution). Mediation is being promoted to reduce court burden.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21051,
        "question": "The Youth Spiritual Summit 2025 was held in which city with the theme 'Nasha Mukt Yuva for Viksit Bharat'?",
        "option_a": "Ayodhya",
        "option_b": "Mathura",
        "option_c": "Prayagraj",
        "option_d": "Varanasi",
        "correct_answer": "D",
        "explanation": "The Youth Spiritual Summit 2025 was held in Varanasi at the Rudraksh International Convention Centre. Theme: 'Nasha Mukt Yuva for Viksit Bharat' (Drug-Free Youth for Developed India). The summit concluded with the 'Kashi Declaration' for a drug-free youth campaign.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21052,
        "question": "The World Bank Land Conference 2025 was held in Washington DC. India's which programme received global praise for drone-based rural land mapping?",
        "option_a": "PM-KISAN",
        "option_b": "Digital India Land Records Modernization Programme",
        "option_c": "SVAMITVA Scheme",
        "option_d": "Bhu-Aadhaar Programme",
        "correct_answer": "C",
        "explanation": "India's SVAMITVA (Survey of Villages and Mapping with Improvised Technology in Village Areas) Scheme was praised at the World Bank Land Conference 2025. SVAMITVA uses drone technology to map rural land and provide property rights cards (property cards) to rural households.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21053,
        "question": "The National Conference on AI for Empowering Persons with Disabilities 2025 was held in which city, where four AI initiatives were launched?",
        "option_a": "New Delhi",
        "option_b": "Hyderabad",
        "option_c": "Chennai",
        "option_d": "Bengaluru",
        "correct_answer": "D",
        "explanation": "The National Conference on AI for Empowering Persons with Disabilities was held in Bengaluru, Karnataka (May 30, 2025). Four initiatives launched: Mission AI Accessibility, Mission AI for Assistive Technologies, National Disability Support AI Chatbot, and United Benefits Interface (UBI). Organised by DEPwD + ALIMCO.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21054,
        "question": "The Indian Conservation Conference (ICCON) 2025 was held at which institution in Dehradun?",
        "option_a": "Forest Research Institute (FRI)",
        "option_b": "Wildlife Institute of India (WII)",
        "option_c": "Indian Institute of Remote Sensing (IIRS)",
        "option_d": "Wadia Institute of Himalayan Geology",
        "correct_answer": "B",
        "explanation": "ICCON 2025 was held at the Wildlife Institute of India (WII), Dehradun (started June 25, 2025) under MoEFCC. ICCON was first launched in 2023 during Project Tiger's 50th anniversary. ICCON 2025 featured 17 themes and a wildlife technology forum called 'TechBridge'.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21055,
        "question": "The 12th Sustainable Mountain Development Summit (SMDS-XII) was held at which institution in Dehradun?",
        "option_a": "IIT Roorkee",
        "option_b": "Wadia Institute",
        "option_c": "Doon University",
        "option_d": "Forest Research Institute",
        "correct_answer": "C",
        "explanation": "SMDS-XII was held at Doon University, Dehradun. Organised by Integrated Mountain Initiative (IMI) — a civil society-led network. Focus: ecological, economic, and social challenges of the Indian Himalayan Region (IHR). Aims to blend science with traditional wisdom.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    # ─── Theme & Outcome Questions (56-66) ──────────────────────────
    {
        "id": 21056,
        "question": "What was the theme of GLEX 2025 (Global Space Exploration Conference) held at Bharat Mandapam, New Delhi?",
        "option_a": "Exploring the Final Frontier",
        "option_b": "Space for Humanity",
        "option_c": "Reaching New Worlds: A Space Exploration Renaissance",
        "option_d": "Towards Mars: A Global Mission",
        "correct_answer": "C",
        "explanation": "GLEX 2025 theme: 'Reaching New Worlds: A Space Exploration Renaissance' (May 7-9, 2025, Bharat Mandapam, New Delhi). 12th edition. Organised by IAF + ISRO + Astronautical Society of India (ASI). 1,700+ participants from 36 countries — largest IAF Global Conference ever.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21057,
        "question": "The Global Energy Leaders' Summit (GELS) 2025 in Puri, Odisha had which theme?",
        "option_a": "Green India, Clean Energy",
        "option_b": "Powering India: Sufficiency, Balance, Innovation",
        "option_c": "Net Zero by 2070: Roadmap for India",
        "option_d": "Energy Security for Viksit Bharat",
        "correct_answer": "B",
        "explanation": "GELS 2025 (Puri, Odisha, December 5-7) theme: 'Powering India: Sufficiency, Balance, Innovation'. Organised with Tony Blair Institute and IIT-Kanpur. Supported PM Modi's Net Zero 2070 vision and cooperative federalism in energy sector.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21058,
        "question": "The Raisina Dialogue 2025 was held in New Delhi in February 2025. Which edition was this?",
        "option_a": "8th edition",
        "option_b": "9th edition",
        "option_c": "10th edition",
        "option_d": "11th edition",
        "correct_answer": "C",
        "explanation": "Raisina Dialogue 2025 (February 17-19, New Delhi) was the 10th edition — a milestone. Organised jointly by MEA (Ministry of External Affairs) and Observer Research Foundation (ORF). It is India's premier annual geopolitics conference with foreign ministers and strategists from 100+ countries.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21059,
        "question": "The 11th World Green Economy Summit 2025 was held in which city with the theme 'Innovating for Impact'?",
        "option_a": "Abu Dhabi",
        "option_b": "Riyadh",
        "option_c": "Dubai",
        "option_d": "Doha",
        "correct_answer": "C",
        "explanation": "The 11th World Green Economy Summit (WGES) was held at Dubai World Trade Centre, UAE (October 2, 2025). Theme: 'Innovating for Impact: Accelerating the Future of the Green Economy'. 3,300+ participants from 30+ countries. The Arab Foundations Forum launched the first Arab Regional Climate Commitment.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21060,
        "question": "Which city hosted the National Haj Conference 2025 to review preparations for Haj 2026?",
        "option_a": "New Delhi",
        "option_b": "Hyderabad",
        "option_c": "Mumbai",
        "option_d": "Chennai",
        "correct_answer": "C",
        "explanation": "The National Haj Conference 2025 was held at Haj House, Mumbai (November 22, 2025), inaugurated by the Secretary, Ministry of Minority Affairs. Executive Officers of all State/UT Haj Committees reviewed Haj 2026 preparations. India sends over 1,75,000 pilgrims annually.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    # ─── Tricky / Mixed (61-70) ─────────────────────────────────────
    {
        "id": 21061,
        "question": "Which of the following correctly matches the G7 host country with the summit location?",
        "option_a": "G7 2024 = Germany (Berlin)",
        "option_b": "G7 2025 = Canada (Kananaskis, Alberta)",
        "option_c": "G7 2026 = France (Paris)",
        "option_d": "G7 2023 = Italy (Rome)",
        "correct_answer": "B",
        "explanation": "G7 2025 = Canada at Kananaskis, Alberta (correct). G7 2024 = Italy at Fasano (Puglia), not Germany. G7 2026 = France at Évian-les-Bains, not Paris. G7 2023 = Japan at Hiroshima, not Italy.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21062,
        "question": "Vasudhaiva Kutumbakam — used as India's G20 theme — is taken from which ancient Indian text?",
        "option_a": "Rigveda",
        "option_b": "Atharvaveda",
        "option_c": "Maha Upanishad",
        "option_d": "Arthashastra",
        "correct_answer": "C",
        "explanation": "Vasudhaiva Kutumbakam is from the Maha Upanishad (6th Chapter) — NOT the Rigveda or other texts. The phrase means 'The world is one family'. This is a common exam trap. India's G20 2023 theme: 'Vasudhaiva Kutumbakam — One Earth, One Family, One Future'.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21063,
        "question": "COP30 will be held in Belém, Brazil. In which state of Brazil is Belém located?",
        "option_a": "Amazonas",
        "option_b": "Pará",
        "option_c": "Mato Grosso",
        "option_d": "Roraima",
        "correct_answer": "B",
        "explanation": "Belém is the capital of Pará state, Brazil — the gateway to the Amazon region. COP30 (November 10-21, 2025) is in Belém, making it the 'Amazon COP'. Common trap: candidates may say Amazonas state (capital: Manaus). Belém = Pará state.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21064,
        "question": "Which of the following is INCORRECT about the NCeG 2025 (National Conference on e-Governance)?",
        "option_a": "It was the 28th edition",
        "option_b": "It was held in Visakhapatnam",
        "option_c": "Andhra Pradesh co-hosted it",
        "option_d": "It was held in Hyderabad, Telangana",
        "correct_answer": "D",
        "explanation": "NCeG 2025 was held in Visakhapatnam, Andhra Pradesh — NOT Hyderabad (which is in Telangana). This is a key AP PSC trap. The 28th NCeG was co-organised by DARPG + MeitY + AP Government, held September 22-23, 2025.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21065,
        "question": "PM Modi met Russian President Putin twice in 2024 — once in Moscow (July 2024) and once where?",
        "option_a": "Vienna (bilateral summit)",
        "option_b": "Kazan, Russia (BRICS Summit sidelines, October 2024)",
        "option_c": "Astana (SCO Summit sidelines)",
        "option_d": "New Delhi (Putin visited India)",
        "correct_answer": "B",
        "explanation": "Modi met Putin at Moscow bilaterally in July 2024 (first India PM visit to Russia in 5 years) and again at the BRICS Kazan Summit sidelines in October 2024. The Kazan meeting also had the landmark Modi-Xi bilateral (first post-Galwan 2020).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21066,
        "question": "Which organisation hosted the GLEX 2025 alongside ISRO and ASI (Italian Space Agency)?",
        "option_a": "UNOOSA",
        "option_b": "IAF (International Astronautical Federation)",
        "option_c": "NASA",
        "option_d": "ESA (European Space Agency)",
        "correct_answer": "B",
        "explanation": "GLEX 2025 was jointly organised by IAF (International Astronautical Federation) + ISRO + Astronautical Society of India (DSA/ASI). IAF is the global federation of space agencies. GLEX = Global Space Exploration Conference, 12th edition, Bharat Mandapam, New Delhi, May 7-9, 2025.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21067,
        "question": "The Agri-Industry Summit 2025, promoting transformation of agriculture into an industry, was held in which state?",
        "option_a": "Uttar Pradesh",
        "option_b": "Gujarat",
        "option_c": "Maharashtra",
        "option_d": "Madhya Pradesh",
        "correct_answer": "D",
        "explanation": "The Agri-Industry Summit 2025 was inaugurated at Narsinghpur district, Madhya Pradesh (May 26, 2025). The summit positioned MP as a model agricultural state and promoted food processing, trade, and technology in agriculture. Support from Krishi Vigyan Kendras (ICAR) highlighted.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21068,
        "question": "The QUAD Cancer Moonshot initiative was launched by the QUAD nations. What does it aim to do?",
        "option_a": "Develop a universal cancer cure through QUAD research",
        "option_b": "Reduce cancer burden in Indo-Pacific countries through joint screening and treatment initiatives",
        "option_c": "Fund cancer hospitals in developing QUAD nations",
        "option_d": "Launch a cancer research satellite",
        "correct_answer": "B",
        "explanation": "QUAD Cancer Moonshot (announced at QUAD 2023 Hiroshima Summit, carried forward at Wilmington 2024) aims to reduce cancer burden in the Indo-Pacific through joint efforts in cancer screening, treatment, and awareness. QUAD nations = India, USA, Japan, Australia.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21069,
        "question": "The 23rd India-Russia Annual Summit (December 2025, New Delhi) set a bilateral trade target of how much by 2030?",
        "option_a": "$50 billion",
        "option_b": "$75 billion",
        "option_c": "$100 billion",
        "option_d": "$150 billion",
        "correct_answer": "C",
        "explanation": "At the 23rd India-Russia Summit (New Delhi, December 2025), both sides set a bilateral trade target of $100 billion by 2030. Current trade is $68.7 billion (2024-25). FTA negotiations with Eurasian Economic Union (EAEU) also began. Marked 25th anniversary of Strategic Partnership.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21070,
        "question": "The 'Pact for the Future' was adopted at the UN Summit of the Future (September 2024). Which two key components are part of this Pact?",
        "option_a": "Global Defence Treaty and AI Safety Charter",
        "option_b": "Global Digital Compact and Declaration on Future Generations",
        "option_c": "Pandemic Treaty and Climate Finance Agreement",
        "option_d": "UN Charter Reform and UNSC Veto Abolition",
        "correct_answer": "B",
        "explanation": "The Pact for the Future (adopted September 22-23, 2024, New York) contains the Global Digital Compact (AI governance, digital inclusion) and Declaration on Future Generations. It commits to UNSC reform and reformed multilateralism. This was the key outcome of the Summit of the Future.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    # ─── Additional India Domestic (71-80) ──────────────────────────
    {
        "id": 21071,
        "question": "The National Agriculture Conference – Rabi Campaign 2025 was held at which institution's campus in New Delhi?",
        "option_a": "ICAR HQ",
        "option_b": "NABARD New Delhi office",
        "option_c": "Bharat Ratna C. Subramaniam Auditorium, Pusa Campus",
        "option_d": "India International Centre",
        "correct_answer": "C",
        "explanation": "The National Agriculture Conference – Rabi Campaign 2025 was held at Bharat Ratna C. Subramaniam Auditorium, Pusa Campus, New Delhi (September 15-16, 2025). Chaired by Agriculture Minister Shivraj Singh Chouhan. Discussed strategies for 2025-26 Rabi season production targets.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21072,
        "question": "The 11th World Green Economy Summit (WGES) 2025 was held in Dubai. Which regional initiative was launched at this summit?",
        "option_a": "Gulf Green Deal",
        "option_b": "Arab Regional Climate Commitment (by Arab Foundations Forum)",
        "option_c": "MENA Carbon Neutrality Fund",
        "option_d": "Gulf Solar Alliance",
        "correct_answer": "B",
        "explanation": "At the 11th WGES Dubai (October 2, 2025), the Arab Foundations Forum launched the first Arab Regional Climate Commitment. The Global Alliance on Green Economy (GAGE) also unveiled its 2024-2025 flagship initiatives. Theme: 'Innovating for Impact: Accelerating the Future of the Green Economy'.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21073,
        "question": "The Shalyacon 2025 (3rd National Conference on Shalya Tantra) was held on which occasion and at which institution?",
        "option_a": "Dhanvantari Jayanti; AIIMS New Delhi",
        "option_b": "Sushruta Jayanti; All India Institute of Ayurveda (AIIA), New Delhi",
        "option_c": "World Ayurveda Day; NIA Jaipur",
        "option_d": "Charaka Jayanti; CCRAS New Delhi",
        "correct_answer": "B",
        "explanation": "Shalyacon 2025 was held on Sushruta Jayanti (July 15, 2025) at All India Institute of Ayurveda (AIIA), New Delhi. Sushruta is considered the father of surgery in ancient India. Theme: 'Innovation, Integration, and Inspiration'. Inaugurated by Ayush MoS Prataprao Jadhav.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21074,
        "question": "BIMSTEC headquarters is in which city?",
        "option_a": "Kathmandu, Nepal",
        "option_b": "Colombo, Sri Lanka",
        "option_c": "Dhaka, Bangladesh",
        "option_d": "Bangkok, Thailand",
        "correct_answer": "C",
        "explanation": "BIMSTEC Secretariat is in Dhaka, Bangladesh. Common trap: SAARC HQ = Kathmandu. BIMSTEC (Bay of Bengal Initiative for Multi-Sectoral Technical and Economic Cooperation) has 7 members: India, Bangladesh, Myanmar, Sri Lanka, Thailand, Nepal, Bhutan.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21075,
        "question": "The 'Blue NDC Challenge' launched at UNOC3 (Nice, France, June 2025) calls on countries to do what?",
        "option_a": "Pledge 30% reduction in ocean plastic waste",
        "option_b": "Integrate ocean-related targets into national climate commitments (NDCs)",
        "option_c": "Fund deep-sea biodiversity research",
        "option_d": "Ban commercial fishing in international waters",
        "correct_answer": "B",
        "explanation": "The Blue NDC Challenge (co-launched by France and Brazil at UNOC3, Nice, June 9-13, 2025) encourages countries to integrate ocean conservation targets into their Nationally Determined Contributions (NDCs) under the Paris Agreement. Links climate action (SDG 13) with ocean protection (SDG 14).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21076,
        "question": "The 'MANTHAN 2025' conference was related to which ministry's domain?",
        "option_a": "Ministry of Education",
        "option_b": "Ministry of Home Affairs",
        "option_c": "Ministry of Defence",
        "option_d": "Ministry of Rural Development",
        "correct_answer": "C",
        "explanation": "MANTHAN 2025 was organised by the Directorate General of Defence Estates under the Ministry of Defence, held in New Delhi (September 18, 2025). Theme: 'Strategic Roadmap to Aatmanirbhar Bharat @2047'. Focus: defence land management, digital tools, governance reform.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21077,
        "question": "At the NATO Hague Summit 2025, what specific GDP breakdown was decided for the new 5% defence spending target?",
        "option_a": "4% core defence + 1% infrastructure",
        "option_b": "3.5% core defence + 1.5% defence-related infrastructure",
        "option_c": "3% core defence + 2% security spending",
        "option_d": "All 5% for core military spending",
        "correct_answer": "B",
        "explanation": "NATO Hague Summit 2025 (June 24-25, Netherlands) agreed on 5% GDP target broken down as: 3.5% for core defence needs + 1.5% for defence-related infrastructure and industries. This replaced the earlier 2% benchmark. Next NATO Summit = Türkiye 2026.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21078,
        "question": "Which country hosted the International Conference on Glaciers' Preservation 2025, organised under the UN's International Year of Glacier Preservation?",
        "option_a": "Iceland",
        "option_b": "Norway",
        "option_c": "Switzerland",
        "option_d": "Tajikistan",
        "correct_answer": "D",
        "explanation": "Tajikistan hosted the International Conference on Glaciers' Preservation 2025 in Dushanbe (its capital). 2025 = UN International Year of Glacier Preservation. Tajikistan is a Central Asian nation with many glaciers in the Pamir mountains and is severely affected by glacier retreat.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21079,
        "question": "APEC 2025 was held in Gyeongju, South Korea. Gyeongju is historically significant as the ancient capital of which Korean kingdom?",
        "option_a": "Joseon Kingdom",
        "option_b": "Goryeo Kingdom",
        "option_c": "Silla Kingdom",
        "option_d": "Baekje Kingdom",
        "correct_answer": "C",
        "explanation": "Gyeongju was the ancient capital of the Silla Kingdom (57 BC – 935 AD) — one of the three kingdoms of Korea. It is a UNESCO World Heritage site known for its royal tombs, temples, and Buddhist relics. South Korea chose Gyeongju (rather than Seoul) to showcase its rich heritage during APEC 2025.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 21080,
        "question": "The 'QUAD Indo-Pacific Logistics Network (IPLN)' was discussed as part of QUAD cooperation. What is its primary purpose?",
        "option_a": "Joint military operations against China",
        "option_b": "Rapid humanitarian assistance and disaster relief coordination in the Indo-Pacific",
        "option_c": "Free trade zone creation among QUAD nations",
        "option_d": "Shared nuclear submarine patrols",
        "correct_answer": "B",
        "explanation": "The QUAD Indo-Pacific Logistics Network (IPLN) is a Logistics Network Pilot aimed at rapid humanitarian assistance and disaster relief (HADR) coordination across the Indo-Pacific. It enables QUAD nations to share logistics infrastructure for quick response to natural disasters. Announced at Wilmington QUAD 2024.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
]


def get_db():
    if USE_POSTGRES:
        import psycopg2
        return psycopg2.connect(DATABASE_URL)
    db_path = os.path.join(os.path.dirname(__file__), "database.db")
    return sqlite3.connect(db_path)


def seed():
    conn = get_db()
    ph = "%s" if USE_POSTGRES else "?"
    inserted = 0
    skipped = 0
    try:
        cur = conn.cursor()
        for q in SUMMIT_MCQS:
            cur.execute(f"SELECT COUNT(*) FROM questions WHERE id={ph}", (q["id"],))
            if cur.fetchone()[0] > 0:
                skipped += 1
                continue
            cur.execute(
                f"""INSERT INTO questions
                    (id, question, option_a, option_b, option_c, option_d,
                     correct_answer, explanation, folder, topic)
                    VALUES ({ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph})""",
                (q["id"], q["question"],
                 q["option_a"], q["option_b"], q["option_c"], q["option_d"],
                 q["correct_answer"], q["explanation"],
                 q["folder"], q["topic"]),
            )
            inserted += 1
        conn.commit()
        print(f"[seed_summits] Inserted={inserted}, Skipped={skipped}")
    finally:
        conn.close()


if __name__ == "__main__":
    seed()
