"""
seed_awards_mcq.py
80 GKToday-style MCQs — Topic: International_Current_Affairs
Sub-topic: Awards & Honours 2024-2026
Folder: AP_HC | IDs: 23001-23080
"""

import os, sqlite3

DATABASE_URL = os.environ.get("DATABASE_URL", "")
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)
USE_POSTGRES = bool(DATABASE_URL)

AWARDS_MCQS = [
    {
        "id": 23001,
        "question_text": 'The Nobel Prize in Physics 2024 was awarded for foundational discoveries enabling machine learning with artificial neural networks. Who were the recipients?',
        "option_a": 'Elon Musk and Sam Altman',
        "option_b": 'John J. Hopfield and Geoffrey E. Hinton',
        "option_c": 'Yann LeCun and Andrew Ng',
        "option_d": 'Demis Hassabis and John Jumper',
        "correct_answer": 'B',
        "explanation": "John J. Hopfield and Geoffrey E. Hinton won the 2024 Nobel Prize in Physics for foundational discoveries enabling machine learning with artificial neural networks. Hinton is often called the 'Godfather of AI'.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23002,
        "question_text": 'Geoffrey Hinton, Nobel Physics laureate 2024, is popularly known as:',
        "option_a": 'Father of the Internet',
        "option_b": 'Godfather of AI',
        "option_c": 'Father of Quantum Computing',
        "option_d": 'Pioneer of Blockchain',
        "correct_answer": 'B',
        "explanation": "Geoffrey Hinton is widely known as the 'Godfather of AI' for his pioneering work on neural networks. He previously worked at Google but resigned in 2023, citing concerns about AI safety risks.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23003,
        "question_text": 'The Nobel Prize in Chemistry 2024 was awarded for protein structure prediction using AI (AlphaFold). Which of these scientists is CEO of Google DeepMind?',
        "option_a": 'David Baker',
        "option_b": 'John M. Jumper',
        "option_c": 'Demis Hassabis',
        "option_d": 'Geoffrey Hinton',
        "correct_answer": 'C',
        "explanation": 'Demis Hassabis, co-founder and CEO of Google DeepMind, shared the 2024 Nobel Chemistry Prize for developing AlphaFold — an AI that predicted 3D structures of nearly all known proteins (~200 million).',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23004,
        "question_text": 'The Nobel Prize in Medicine/Physiology 2024 was awarded to Victor Ambros and Gary Ruvkun for their discovery of:',
        "option_a": 'CRISPR gene editing',
        "option_b": 'mRNA vaccines',
        "option_c": 'microRNA and its role in gene regulation',
        "option_d": 'Stem cell therapy',
        "correct_answer": 'C',
        "explanation": 'Victor Ambros and Gary Ruvkun won the 2024 Nobel Prize in Physiology or Medicine for discovering microRNA — tiny RNA molecules that regulate gene expression. This has major implications for understanding diseases including cancer.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23005,
        "question_text": 'Han Kang won the Nobel Prize in Literature 2024. She is from which country?',
        "option_a": 'Japan',
        "option_b": 'China',
        "option_c": 'North Korea',
        "option_d": 'South Korea',
        "correct_answer": 'D',
        "explanation": "Han Kang of South Korea won the 2024 Nobel Prize in Literature 'for her intense poetic prose that confronts historical traumas and exposes the fragility of human life.' She is the first South Korean and first Asian woman to win Nobel Literature.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23006,
        "question_text": 'Han Kang (Nobel Literature 2024) is the first Asian woman to win the Nobel Prize in Literature. Her famous works include:',
        "option_a": 'The Kite Runner and A Thousand Splendid Suns',
        "option_b": 'The Vegetarian and Human Acts',
        "option_c": 'Snow Country and The Sound of Waves',
        "option_d": 'Kitchen and Norwegian Wood',
        "correct_answer": 'B',
        "explanation": "Han Kang's internationally acclaimed works include 'The Vegetarian' (won Man Booker International Prize 2016) and 'Human Acts' — dealing with South Korea's 1980 Gwangju Uprising massacre.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23007,
        "question_text": 'The Nobel Peace Prize 2024 was awarded to Nihon Hidankyo. What is Nihon Hidankyo?',
        "option_a": 'A Japanese environmental NGO',
        "option_b": "Japan's nuclear power corporation",
        "option_c": 'Japanese grassroots organisation of atomic bomb survivors (Hibakusha) from Hiroshima and Nagasaki',
        "option_d": "Japan's disarmament ministry",
        "correct_answer": 'C',
        "explanation": 'Nihon Hidankyo is a Japanese grassroots organisation of Hibakusha — survivors of the 1945 atomic bombings of Hiroshima (Aug 6) and Nagasaki (Aug 9). They won the 2024 Nobel Peace Prize for their efforts toward a nuclear weapons-free world.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23008,
        "question_text": "'Hibakusha' — the survivors associated with 2024 Nobel Peace Prize Nihon Hidankyo — refers to survivors of:",
        "option_a": 'Japanese earthquake and tsunami (2011)',
        "option_b": 'World War II prisoner camps',
        "option_c": 'Atomic bombings of Hiroshima and Nagasaki (1945)',
        "option_d": 'Nagasaki chemical plant disaster',
        "correct_answer": 'C',
        "explanation": "'Hibakusha' (bomb-affected people) refers to survivors of the atomic bomb attacks on Hiroshima (Aug 6, 1945) and Nagasaki (Aug 9, 1945). Nihon Hidankyo represents these survivors in their mission for nuclear abolition.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23009,
        "question_text": 'The Nobel Economics Prize 2024 was awarded to Acemoglu, Johnson, and Robinson. They are best known for the book:',
        "option_a": 'The Wealth of Nations',
        "option_b": 'Why Nations Fail',
        "option_c": 'Capital in the Twenty-First Century',
        "option_d": 'The General Theory of Employment',
        "correct_answer": 'B',
        "explanation": "Daron Acemoglu and James A. Robinson wrote 'Why Nations Fail' — arguing that inclusive political and economic institutions (not geography or culture) determine why some nations prosper and others don't. They won Nobel Economics 2024 for research on colonisation and global inequality.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23010,
        "question_text": 'The Nobel Economics 2024 researched how colonisation shaped which outcome?',
        "option_a": 'Military power of nations',
        "option_b": 'Global trade patterns',
        "option_c": 'Global inequality between nations',
        "option_d": 'Agricultural productivity',
        "correct_answer": 'C',
        "explanation": 'Acemoglu, Johnson, and Robinson (Nobel Economics 2024) showed how colonisation shaped persistent global inequality — nations with extractive colonial institutions remained poor, while those with inclusive institutions prospered.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23011,
        "question_text": 'The Nobel Prize in Physics 2025 was awarded for discoveries related to:',
        "option_a": 'Gravitational waves detection',
        "option_b": 'Macroscopic quantum mechanical tunnelling and energy quantisation in superconducting circuits',
        "option_c": 'Higgs boson discovery',
        "option_d": 'Quantum entanglement teleportation',
        "correct_answer": 'B',
        "explanation": 'The 2025 Nobel Physics Prize went to John Clarke, Michel H. Devoret, and John M. Martinis for discovering macroscopic quantum mechanical tunnelling and energy quantisation in superconducting electric circuits — foundations of quantum computing.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23012,
        "question_text": 'The Nobel Prize in Chemistry 2025 was awarded for creating Metal-Organic Frameworks (MOFs). MOFs can be used to:',
        "option_a": 'Replace fossil fuels directly',
        "option_b": 'Harvest water from desert air, capture CO₂, and store gases',
        "option_c": 'Create superconducting materials',
        "option_d": 'Generate nuclear fusion energy',
        "correct_answer": 'B',
        "explanation": 'Metal-Organic Frameworks (MOFs) — molecular structures with large internal spaces — can harvest water from desert air, capture CO₂ from atmosphere, store hydrogen/methane, and catalyse chemical reactions. The 2025 Chemistry Nobel was for their creation.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23013,
        "question_text": "Nobel Medicine 2025 was awarded for discoveries in 'peripheral immune tolerance' involving FOXP3 gene. This prevents:",
        "option_a": 'HIV infection',
        "option_b": 'Cancer cell growth',
        "option_c": 'Autoimmune diseases (immune system attacking own body)',
        "option_d": 'Antibiotic resistance',
        "correct_answer": 'C',
        "explanation": "Brunkow, Ramsdell, and Sakaguchi (Nobel Medicine 2025) discovered how regulatory T cells (Tregs) expressing FOXP3 gene prevent the immune system from attacking the body's own tissues — preventing autoimmune diseases like Type 1 diabetes, MS, and rheumatoid arthritis.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23014,
        "question_text": 'The Nobel Prize in Literature 2025 was awarded to László Krasznahorkai. He is a writer from:',
        "option_a": 'Poland',
        "option_b": 'Czech Republic',
        "option_c": 'Hungary',
        "option_d": 'Romania',
        "correct_answer": 'C',
        "explanation": "László Krasznahorkai is a Hungarian author who won the 2025 Nobel Prize in Literature 'for his compelling and visionary oeuvre that, in the midst of apocalyptic terror, reaffirms the power of art.'",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23015,
        "question_text": 'The Nobel Peace Prize 2025 was awarded to María Corina Machado for promoting democratic rights in:',
        "option_a": 'Cuba',
        "option_b": 'Nicaragua',
        "option_c": 'Bolivia',
        "option_d": 'Venezuela',
        "correct_answer": 'D',
        "explanation": "María Corina Machado won the 2025 Nobel Peace Prize for her tireless efforts to promote democratic rights in Venezuela — where President Nicolás Maduro's government has suppressed opposition.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23016,
        "question_text": "Nobel Economics 2025 was awarded for work on innovation-driven growth and Schumpeterian 'creative destruction.' Who received it?",
        "option_a": 'Thomas Piketty, Angus Deaton, Esther Duflo',
        "option_b": 'Joel Mokyr, Philippe Aghion, Peter Howitt',
        "option_c": 'Milton Friedman, Paul Krugman, Robert Lucas',
        "option_d": 'Eugene Fama, Lars Hansen, Robert Shiller',
        "correct_answer": 'B',
        "explanation": "Joel Mokyr, Philippe Aghion, and Peter Howitt won Nobel Economics 2025 for innovation-driven growth theory. Aghion and Howitt developed Schumpeterian 'creative destruction' theory — new innovations replacing old to drive long-term growth.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23017,
        "question_text": 'Which statement about Nobel 2024 is CORRECT?',
        "option_a": 'Nobel Physics 2024 = protein structure prediction',
        "option_b": 'Nobel Chemistry 2024 = machine learning/neural networks',
        "option_c": 'Nobel Literature 2024 = Han Kang, first Asian woman to win',
        "option_d": 'Nobel Peace 2024 = María Corina Machado',
        "correct_answer": 'C',
        "explanation": 'Nobel Literature 2024 = Han Kang (South Korea) — first Asian woman to win Nobel in Literature. Physics 2024 = AI/neural networks (Hopfield+Hinton). Chemistry 2024 = protein prediction (Baker+Hassabis+Jumper). Peace 2025 = María Corina Machado.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23018,
        "question_text": 'Which Nobel laureate resigned from Google in 2023 over concerns about artificial intelligence safety risks?',
        "option_a": 'John Hopfield',
        "option_b": 'Geoffrey Hinton',
        "option_c": 'Demis Hassabis',
        "option_d": 'Yann LeCun',
        "correct_answer": 'B',
        "explanation": "Geoffrey Hinton (Nobel Physics 2024) resigned from Google in May 2023, saying he regretted his life's work due to AI safety concerns. He wanted to freely speak about AI risks without embarrassing Google.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23019,
        "question_text": 'How many Bharat Ratna awards were announced in 2024 — the largest single-year batch?',
        "option_a": '3',
        "option_b": '4',
        "option_c": '5',
        "option_d": '7',
        "correct_answer": 'C',
        "explanation": 'In 2024, PM Modi announced 5 Bharat Ratna awards — the largest number given in a single year. Recipients: Karpoori Thakur, L.K. Advani, P.V. Narasimha Rao, M.S. Swaminathan, and Chaudhary Charan Singh.',
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 23020,
        "question_text": "Which Bharat Ratna 2024 recipient is known as the 'Father of India's Green Revolution'?",
        "option_a": 'Karpoori Thakur',
        "option_b": 'Chaudhary Charan Singh',
        "option_c": 'P.V. Narasimha Rao',
        "option_d": 'M.S. Swaminathan',
        "correct_answer": 'D',
        "explanation": "M.S. Swaminathan was awarded Bharat Ratna 2024 (posthumously). He is called the 'Father of India's Green Revolution' for introducing high-yielding wheat and rice varieties in the 1960s-70s, making India self-sufficient in food. He died on September 28, 2023.",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 23021,
        "question_text": 'Karpoori Thakur, who received Bharat Ratna 2024 (posthumously), was associated with:',
        "option_a": 'National security and defence',
        "option_b": "OBC rights and social justice; twice Bihar Chief Minister; called 'Jan Nayak'",
        "option_c": 'Space research and ISRO',
        "option_d": 'Economic liberalisation reforms',
        "correct_answer": 'B',
        "explanation": "Karpoori Thakur was Bihar's Chief Minister twice (1970-71, 1977-79) and a champion of OBC (Other Backward Classes) rights. Called 'Jan Nayak' (People's Hero), the Bharat Ratna was announced on his birth anniversary (January 24, 2024).",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 23022,
        "question_text": 'P.V. Narasimha Rao (Bharat Ratna 2024, posthumous) is best known for:',
        "option_a": 'Conducting Pokhran nuclear tests',
        "option_b": "1991 economic liberalisation reforms as India's 9th Prime Minister",
        "option_c": 'Green Revolution in agriculture',
        "option_d": 'Leading the Non-Aligned Movement',
        "correct_answer": 'B',
        "explanation": "P.V. Narasimha Rao served as India's 9th PM (1991-96) and, along with Finance Minister Manmohan Singh, launched the 1991 LPG (Liberalisation, Privatisation, Globalisation) reforms that transformed India's economy.",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 23023,
        "question_text": "Which Bharat Ratna 2024 recipient served as India's 5th Prime Minister and was known as a champion of farmers?",
        "option_a": 'P.V. Narasimha Rao',
        "option_b": 'L.K. Advani',
        "option_c": 'Chaudhary Charan Singh',
        "option_d": 'Karpoori Thakur',
        "correct_answer": 'C',
        "explanation": "Chaudhary Charan Singh served as India's 5th Prime Minister (1979-80) for a short period. He was a staunch advocate for farmers' rights and rural India. Bharat Ratna 2024 was awarded posthumously.",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 23024,
        "question_text": 'L.K. Advani, recipient of Bharat Ratna 2024, was the oldest living recipient. He is associated with:',
        "option_a": 'Indian National Congress and Nehruvian socialism',
        "option_b": 'BJP co-founding, Rath Yatra (1990), and served as Deputy PM (1999-2004)',
        "option_c": 'Communist Party of India',
        "option_d": 'Janata Dal and agricultural reforms',
        "correct_answer": 'B',
        "explanation": 'L.K. Advani co-founded the Bharatiya Janata Party (BJP) and was a key figure in the Ram Janmabhoomi movement. His 1990 Rath Yatra mobilised the Hindu nationalist movement. He served as Deputy PM under PM Vajpayee (1999-2004). Received Bharat Ratna 2024 at age 96.',
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 23025,
        "question_text": "Which is India's highest civilian honour?",
        "option_a": 'Padma Vibhushan',
        "option_b": 'Bharat Ratna',
        "option_c": 'Padma Bhushan',
        "option_d": 'Param Vir Chakra',
        "correct_answer": 'B',
        "explanation": "Bharat Ratna is India's highest civilian honour. Hierarchy: Bharat Ratna > Padma Vibhushan > Padma Bhushan > Padma Shri. Param Vir Chakra is the highest military gallantry award (different category).",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 23026,
        "question_text": 'The Bharat Ratna 2024 announced for Karpoori Thakur was on which occasion?',
        "option_a": "India's Republic Day",
        "option_b": 'His birth anniversary (January 24)',
        "option_c": 'Independence Day',
        "option_d": 'Gandhi Jayanti',
        "correct_answer": 'B',
        "explanation": 'PM Modi announced Bharat Ratna for Karpoori Thakur on January 24, 2024 — his birth anniversary. This was a politically significant move ahead of Bihar elections, as Thakur is revered by OBC communities.',
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 23027,
        "question_text": 'Which sportsperson received Padma Bhushan in 2025 — the second hockey player after Major Dhyan Chand (1956)?',
        "option_a": 'Neeraj Chopra',
        "option_b": 'P.R. Sreejesh',
        "option_c": 'Manu Bhaker',
        "option_d": 'Harmanpreet Singh',
        "correct_answer": 'B',
        "explanation": "P.R. Sreejesh, India's legendary hockey goalkeeper, received Padma Bhushan in 2025 — the second hockey player after Major Dhyan Chand (1956) to receive this award. Sreejesh retired after Paris Olympics 2024 where India won bronze.",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 23028,
        "question_text": 'Arijit Singh received which Padma award in 2025?',
        "option_a": 'Padma Vibhushan',
        "option_b": 'Padma Bhushan',
        "option_c": 'Padma Shri',
        "option_d": 'Bharat Ratna',
        "correct_answer": 'C',
        "explanation": "Arijit Singh, India's most-streamed playback singer, received Padma Shri in 2025. Note: Padma Shri is the third tier — Padma Vibhushan (highest) > Padma Bhushan > Padma Shri.",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 23029,
        "question_text": 'Which legendary Malayalam writer/filmmaker received Padma Vibhushan 2025 posthumously?',
        "option_a": 'O.N.V. Kurup',
        "option_b": 'Kamala Das',
        "option_c": 'M.T. Vasudevan Nair',
        "option_d": 'Thakazhi Sivasankara Pillai',
        "correct_answer": 'C',
        "explanation": "M.T. Vasudevan Nair (popularly 'MT'), legendary Malayalam writer and filmmaker, received Padma Vibhushan 2025 posthumously. He is known for classics like 'Naalukettu', 'Randamoozham', and screenplays for many Malayalam films.",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 23030,
        "question_text": 'Which ghazal singer received Padma Bhushan 2025 posthumously?',
        "option_a": 'Ghulam Ali',
        "option_b": 'Jagjit Singh',
        "option_c": 'Pankaj Udhas',
        "option_d": 'Mehdi Hassan',
        "correct_answer": 'C',
        "explanation": "Pankaj Udhas received Padma Bhushan 2025 posthumously — he passed away on February 26, 2024. Known for iconic ghazals like 'Chitthi Aayi Hai' (from film 'Naam', 1986).",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 23031,
        "question_text": 'Dr. D. Nageshwar Reddy, who received Padma Vibhushan 2025, is associated with which field?',
        "option_a": 'Nuclear Physics',
        "option_b": 'Gastroenterology and Endoscopy (AIG Hospitals, Hyderabad)',
        "option_c": 'Space research (ISRO)',
        "option_d": 'Organic Chemistry',
        "correct_answer": 'B',
        "explanation": "Dr. D. Nageshwar Reddy, founder of AIG Hospitals Hyderabad, received Padma Vibhushan 2025 for his pioneering contributions to gastroenterology and endoscopy. He is one of the world's most cited gastroenterologists.",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 23032,
        "question_text": 'The Padma Award hierarchy from highest to lowest is:',
        "option_a": 'Padma Shri > Padma Bhushan > Padma Vibhushan',
        "option_b": 'Padma Vibhushan > Padma Bhushan > Padma Shri',
        "option_c": 'Padma Bhushan > Padma Vibhushan > Padma Shri',
        "option_d": 'Bharat Ratna > Padma Shri > Padma Vibhushan',
        "correct_answer": 'B',
        "explanation": "Correct hierarchy (within Padma family): Padma Vibhushan (highest) > Padma Bhushan > Padma Shri. Bharat Ratna sits above all Padma awards as India's supreme civilian honour.",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 23033,
        "question_text": 'D. Gukesh became the youngest World Chess Champion in history on which date?',
        "option_a": 'November 12, 2024',
        "option_b": 'December 12, 2024',
        "option_c": 'January 12, 2025',
        "option_d": 'October 14, 2024',
        "correct_answer": 'B',
        "explanation": 'Gukesh Dommaraju became the youngest World Chess Champion on December 12, 2024, in Singapore. He beat defending champion Ding Liren (China) in Game 14 of the FIDE World Championship 2024.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23034,
        "question_text": 'Gukesh Dommaraju broke whose record to become the youngest World Chess Champion?',
        "option_a": 'Bobby Fischer (USA)',
        "option_b": 'Viswanathan Anand (India)',
        "option_c": 'Magnus Carlsen (Norway)',
        "option_d": 'Garry Kasparov (USSR)',
        "correct_answer": 'D',
        "explanation": "Gukesh (age 18) broke Garry Kasparov's record — Kasparov became world champion at age 22 in 1985. Magnus Carlsen opted not to defend his title (retired from championship format). Anand won multiple championships but was not the youngest.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23035,
        "question_text": 'Gukesh beat which player to become World Chess Champion 2024?',
        "option_a": 'Magnus Carlsen (Norway)',
        "option_b": 'Fabiano Caruana (USA)',
        "option_c": 'Ian Nepomniachtchi (Russia)',
        "option_d": 'Ding Liren (China)',
        "correct_answer": 'D',
        "explanation": 'Gukesh Dommaraju defeated Ding Liren (China) — the defending World Chess Champion — in the FIDE World Championship 2024 held in Singapore. The match went to all 14 games.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23036,
        "question_text": 'Gukesh Dommaraju is from which Indian city?',
        "option_a": 'Mumbai',
        "option_b": 'Kolkata',
        "option_c": 'Chennai, Tamil Nadu',
        "option_d": 'Bengaluru',
        "correct_answer": 'C',
        "explanation": 'Gukesh Dommaraju was born in Chennai, Tamil Nadu on May 29, 2006. He became an International Grandmaster at age 12, making him the youngest Indian to achieve the GM title at the time.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23037,
        "question_text": 'Manu Bhaker won how many medals at the Paris Olympics 2024?',
        "option_a": '1 (gold)',
        "option_b": '1 (silver)',
        "option_c": '2 (both bronze)',
        "option_d": '3 (gold, silver, bronze)',
        "correct_answer": 'C',
        "explanation": "Manu Bhaker won 2 bronze medals at Paris 2024: (1) Women's 10m Air Pistol (individual) and (2) 10m Air Pistol Mixed Team (with Sarabjot Singh). She was the first Indian to win 2 medals in a single Olympic edition in the modern era.",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 23038,
        "question_text": 'The Khel Ratna Award 2024 was presented on January 17, 2025 by which authority?',
        "option_a": 'Prime Minister of India',
        "option_b": 'Sports Minister',
        "option_c": 'President of India at Rashtrapati Bhavan',
        "option_d": 'Chief Justice of India',
        "correct_answer": 'C',
        "explanation": 'The Major Dhyan Chand Khel Ratna Award 2024 was presented on January 17, 2025, at Rashtrapati Bhavan by President Droupadi Murmu. Recipients: Gukesh, Manu Bhaker, Harmanpreet Singh, and Praveen Kumar.',
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 23039,
        "question_text": 'Praveen Kumar, who received Khel Ratna 2024, won gold at Paris 2024 Paralympics in which event?',
        "option_a": 'Sprinting (100m T44)',
        "option_b": 'High Jump (T64 category)',
        "option_c": 'Discus Throw',
        "option_d": 'Wheelchair Basketball',
        "correct_answer": 'B',
        "explanation": "Praveen Kumar won gold in High Jump (T64 category — below-knee amputation) at the Paris 2024 Paralympics, earning him the Khel Ratna 2024 (India's highest sports honour).",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 23040,
        "question_text": 'Harmanpreet Singh received Khel Ratna 2024 as captain of which Indian sports team?',
        "option_a": 'Cricket',
        "option_b": 'Football',
        "option_c": "Men's Hockey",
        "option_d": 'Kabaddi',
        "correct_answer": 'C',
        "explanation": "Harmanpreet Singh, captain of the Indian men's hockey team, received Khel Ratna 2024. India won bronze at Paris Olympics 2024 in hockey — their second consecutive Olympic bronze (after Tokyo 2020).",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 23041,
        "question_text": 'Neeraj Chopra won which medal at the Paris Olympics 2024 in javelin throw?',
        "option_a": 'Gold',
        "option_b": 'Silver',
        "option_c": 'Bronze',
        "option_d": 'Did not qualify',
        "correct_answer": 'B',
        "explanation": 'Neeraj Chopra won the Silver medal at Paris Olympics 2024. Gold went to Arshad Nadeem of Pakistan with a world record throw of 92.97m. Neeraj had won gold at Tokyo 2020.',
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 23042,
        "question_text": "India's total medal count at the Paris Olympics 2024 was:",
        "option_a": '4 medals',
        "option_b": '6 medals',
        "option_c": '7 medals',
        "option_d": '10 medals',
        "correct_answer": 'B',
        "explanation": "India won 6 medals at Paris 2024: 0 Gold, 1 Silver (Neeraj Chopra), 5 Bronze (Manu Bhaker ×2, Hockey team, Aman Sehrawat-wrestling, Swapnil Kusale-shooting). This equalled India's best Olympic haul.",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 23043,
        "question_text": "Which award is India's highest sports honour (renamed after Major Dhyan Chand in 2021)?",
        "option_a": 'Arjuna Award',
        "option_b": 'Dronacharya Award',
        "option_c": 'Major Dhyan Chand Khel Ratna Award',
        "option_d": 'Rajiv Gandhi Khel Ratna',
        "correct_answer": 'C',
        "explanation": "The award was originally named Rajiv Gandhi Khel Ratna. In 2021, it was renamed 'Major Dhyan Chand Khel Ratna Award' — after India's greatest hockey player, Major Dhyan Chand ('The Wizard').",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 23044,
        "question_text": 'Which shooter made history at Paris 2024 as the first Indian to win two medals in a single Olympic Games (modern era)?',
        "option_a": 'Saurabh Chaudhary',
        "option_b": 'Manu Bhaker',
        "option_c": 'Chinki Yadav',
        "option_d": 'Apurvi Chandela',
        "correct_answer": 'B',
        "explanation": "Manu Bhaker made history at Paris Olympics 2024 by winning 2 bronze medals — Women's 10m Air Pistol (individual) + 10m Air Pistol Mixed Team (with Sarabjot Singh). First Indian in modern Olympics to win 2 medals at single Games.",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 23045,
        "question_text": 'Which film won Best Picture at the 97th Academy Awards (Oscars 2025)?',
        "option_a": 'The Brutalist',
        "option_b": 'Emilia Pérez',
        "option_c": 'Anora',
        "option_d": 'Conclave',
        "correct_answer": 'C',
        "explanation": "'Anora' directed by Sean Baker won Best Picture at the 97th Academy Awards (March 2, 2025, Dolby Theatre, Hollywood). It also won Best Director, Best Actress, and other awards — 5 total Oscars.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23046,
        "question_text": "Who won Best Actor at the 97th Oscars (2025) for 'The Brutalist'?",
        "option_a": 'Timothée Chalamet',
        "option_b": 'Colman Domingo',
        "option_c": 'Daniel Craig',
        "option_d": 'Adrien Brody',
        "correct_answer": 'D',
        "explanation": "Adrien Brody won Best Actor at the 97th Academy Awards (2025) for his role as architect László Tóth in 'The Brutalist.' This was his second Oscar (first was 'The Pianist', 2003).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23047,
        "question_text": 'Who won Best Actress at the 97th Academy Awards (Oscars 2025)?',
        "option_a": 'Demi Moore (The Substance)',
        "option_b": 'Mikey Madison (Anora)',
        "option_c": 'Cynthia Erivo (Wicked)',
        "option_d": "Fernanda Torres (I'm Still Here)",
        "correct_answer": 'B',
        "explanation": "Mikey Madison won Best Actress at the 2025 Oscars for 'Anora' — a surprise upset over heavy favourite Demi Moore (The Substance). Madison plays a NYC sex worker who marries a Russian oligarch's son.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23048,
        "question_text": "Sean Baker, director of Oscar-winning 'Anora' (2025), made history by winning how many awards for the same film?",
        "option_a": '2',
        "option_b": '3',
        "option_c": '4',
        "option_d": '5',
        "correct_answer": 'C',
        "explanation": "Sean Baker made history at the 97th Oscars by winning FOUR awards for the same film 'Anora': Best Picture (producer), Best Director, Best Original Screenplay, and Best Film Editing — the first person to achieve this.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23049,
        "question_text": 'Which film won Best International Feature Film at the 97th Oscars 2025?',
        "option_a": 'Zone of Interest (Germany)',
        "option_b": "I'm Still Here (Brazil)",
        "option_c": 'Emilia Pérez (France/Mexico)',
        "option_d": 'All We Imagine as Light (India)',
        "correct_answer": 'C',
        "explanation": "'Emilia Pérez' (France/Mexico) won Best International Feature Film at the 97th Oscars 2025. It was a Spanish-language French production about a Mexican cartel boss and was heavily nominated across categories.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23050,
        "question_text": 'Best Picture at the 98th Academy Awards (Oscars 2026) was won by:',
        "option_a": 'Sinners',
        "option_b": 'Hamnet',
        "option_c": 'One Battle After Another',
        "option_d": 'Frankenstein',
        "correct_answer": 'C',
        "explanation": "'One Battle After Another' directed by Paul Thomas Anderson won Best Picture at the 98th Academy Awards (March 15, 2026). It also won Best Director and Best Adapted Screenplay — 6 total awards.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23051,
        "question_text": 'Who won Best Actor at the 98th Oscars (2026)?',
        "option_a": 'Paul Thomas Anderson',
        "option_b": 'Ryan Coogler',
        "option_c": 'Michael B. Jordan (Sinners)',
        "option_d": 'Tim Roth',
        "correct_answer": 'C',
        "explanation": "Michael B. Jordan won Best Actor at the 98th Oscars (2026) for 'Sinners' — in which he played twin brothers. 'Sinners' was directed by Ryan Coogler.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23052,
        "question_text": 'The 98th Academy Awards (2026) introduced a new Oscar category — the first since Best Animated Feature (2001). This new category is:',
        "option_a": 'Best Streaming Film',
        "option_b": 'Best Visual Effects',
        "option_c": 'Best Casting',
        "option_d": 'Best Stunt Coordination',
        "correct_answer": 'C',
        "explanation": "The 98th Academy Awards (2026) introduced 'Best Casting' — the first new Oscar category since Best Animated Feature was introduced in 2001. 'One Battle After Another' was the inaugural recipient.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23053,
        "question_text": "The Booker Prize 2024 was won by Samantha Harvey for her novel 'Orbital'. What is notable about this book?",
        "option_a": 'It is set during World War II',
        "option_b": 'It is the longest Booker winner ever',
        "option_c": 'It is set in space (International Space Station) and is the second shortest Booker winner',
        "option_d": 'It is written in verse form',
        "correct_answer": 'C',
        "explanation": "'Orbital' by Samantha Harvey is set aboard the International Space Station (ISS) — the first Booker winner set in space. At 136 pages, it is the second shortest book to ever win the Booker Prize.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23054,
        "question_text": "The Booker Prize 2025 was won by David Szalay for 'Flesh'. He is notable as:",
        "option_a": 'First American author to win Booker',
        "option_b": 'First British-Hungarian author to win Booker Prize',
        "option_c": 'Youngest Booker winner',
        "option_d": 'First author to win twice',
        "correct_answer": 'B',
        "explanation": "David Szalay won the 2025 Booker Prize for 'Flesh' — making him the first British-Hungarian author to win the Booker Prize. Announced November 10, 2025, at Old Billingsgate, London.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23055,
        "question_text": 'Which artist won the Grammy Award for Album of the Year at the 67th Grammy Awards (2025)?',
        "option_a": 'Taylor Swift',
        "option_b": 'Billie Eilish',
        "option_c": 'Sabrina Carpenter',
        "option_d": 'Beyoncé',
        "correct_answer": 'C',
        "explanation": "Sabrina Carpenter's album 'Short n' Sweet' won Album of the Year at the 67th Grammy Awards (2025). Carpenter also won Best Pop Vocal Album and other awards — her breakthrough mainstream moment.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23056,
        "question_text": 'The Pulitzer Prize was established in which year and is administered by which university?',
        "option_a": '1900; Harvard University',
        "option_b": '1917; Columbia University',
        "option_c": '1945; Yale University',
        "option_d": '1930; Princeton University',
        "correct_answer": 'B',
        "explanation": 'The Pulitzer Prize was established in 1917 and is administered by Columbia University in New York. It awards achievements in journalism, literature, drama, music, and other fields. Named after publisher Joseph Pulitzer.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23057,
        "question_text": "The Pritzker Architecture Prize (often called 'Architecture's Nobel') for 2025 was awarded to:",
        "option_a": 'Bjarke Ingels (Denmark)',
        "option_b": 'Balkrishna Doshi (India)',
        "option_c": 'Liu Jiakun (China)',
        "option_d": 'Kengo Kuma (Japan)',
        "correct_answer": 'C',
        "explanation": 'Liu Jiakun of China won the 2025 Pritzker Architecture Prize — the highest honour in architecture. He is known for buildings that blend modernism with Chinese cultural heritage and local materials.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23058,
        "question_text": "The Abel Prize 2025 (Norway's highest mathematics award) was won by Masaki Kashiwara, a mathematician from:",
        "option_a": 'China',
        "option_b": 'South Korea',
        "option_c": 'Japan',
        "option_d": 'India',
        "correct_answer": 'C',
        "explanation": 'Masaki Kashiwara of Japan won the 2025 Abel Prize for his foundational contributions to algebraic analysis, particularly the development of D-modules theory. The Abel Prize is considered equivalent to the Nobel Prize for mathematics.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23059,
        "question_text": 'Which of these Nobel Prize pairings from 2024 is CORRECTLY matched?',
        "option_a": 'Physics — Protein structure prediction (AlphaFold)',
        "option_b": 'Chemistry — Machine learning / Neural networks',
        "option_c": 'Medicine — Discovery of microRNA (gene regulation)',
        "option_d": 'Peace — László Krasznahorkai (Hungary)',
        "correct_answer": 'C',
        "explanation": 'Nobel Medicine 2024 = Ambros + Ruvkun for microRNA discovery ✓. Physics 2024 = Neural networks (NOT protein). Chemistry 2024 = Protein/AlphaFold (NOT neural networks). Peace 2025 = Krasznahorkai is Literature (NOT Peace).',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23060,
        "question_text": "Time magazine's Person of the Year 2024 was:",
        "option_a": 'Volodymyr Zelensky',
        "option_b": 'Taylor Swift',
        "option_c": 'Donald Trump',
        "option_d": 'Elon Musk',
        "correct_answer": 'C',
        "explanation": "Donald Trump was named Time Magazine's Person of the Year 2024, following his election victory as the 47th President of the United States. Taylor Swift won the 2023 Person of the Year.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23061,
        "question_text": "The Booker Prize 2024 winner 'Orbital' is set primarily aboard:",
        "option_a": 'A nuclear submarine',
        "option_b": 'The International Space Station',
        "option_c": 'A spacecraft heading to Mars',
        "option_d": 'An Antarctic research station',
        "correct_answer": 'B',
        "explanation": "'Orbital' by Samantha Harvey (Booker 2024) is set aboard the International Space Station (ISS) — six astronauts observe Earth over one day. It is the first Booker winner set in space.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23062,
        "question_text": 'Gukesh became World Chess Champion at age 18, held in Singapore 2024. The venue was:',
        "option_a": 'Singapore National Library',
        "option_b": 'Sentosa Island Resort',
        "option_c": 'Marina Bay Sands',
        "option_d": 'Resorts World Sentosa',
        "correct_answer": 'C',
        "explanation": 'The FIDE World Chess Championship 2024 was held at Marina Bay Sands, Singapore. Gukesh defeated Ding Liren in Game 14 on December 12, 2024, to become the youngest world chess champion.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23063,
        "question_text": "Which Bharat Ratna 2024 recipient is called 'Jan Nayak' (People's Hero)?",
        "option_a": 'P.V. Narasimha Rao',
        "option_b": 'Chaudhary Charan Singh',
        "option_c": 'Karpoori Thakur',
        "option_d": 'M.S. Swaminathan',
        "correct_answer": 'C',
        "explanation": "Karpoori Thakur was popularly called 'Jan Nayak' (People's Hero). He was Bihar's CM twice and a champion of OBC rights. 'Loknayak' (different title) refers to Jayaprakash Narayan — don't confuse.",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 23064,
        "question_text": 'Nobel Chemistry 2024 laureate Demis Hassabis is also known as CEO of:',
        "option_a": 'OpenAI',
        "option_b": 'Meta AI Research',
        "option_c": 'Google DeepMind',
        "option_d": 'Microsoft Research',
        "correct_answer": 'C',
        "explanation": 'Demis Hassabis is the co-founder and CEO of Google DeepMind. He won Nobel Chemistry 2024 for AlphaFold — an AI system that predicted the 3D structures of virtually all known proteins (~200 million).',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23065,
        "question_text": 'Who was Arshad Nadeem — who beat Neeraj Chopra for gold in javelin at Paris 2024?',
        "option_a": 'An Indian-origin Canadian athlete',
        "option_b": 'Pakistani athlete who set an Olympic record',
        "option_c": 'Chinese javelin thrower',
        "option_d": 'Kenyan athlete',
        "correct_answer": 'B',
        "explanation": 'Arshad Nadeem of Pakistan won gold in javelin throw at Paris 2024 with a throw of 92.97m — an Olympic record. Neeraj Chopra won silver with 89.45m. This was a significant sporting rivalry moment.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23066,
        "question_text": "Nobel Peace Prize 2024 Nihon Hidankyo represents survivors called 'Hibakusha.' These are survivors of bombings in which two cities?",
        "option_a": 'Tokyo and Osaka',
        "option_b": 'Hiroshima and Nagasaki',
        "option_c": 'Kyoto and Kobe',
        "option_d": 'Fukushima and Sendai',
        "correct_answer": 'B',
        "explanation": "Hibakusha are survivors of the atomic bombings of Hiroshima (August 6, 1945 — 'Little Boy') and Nagasaki (August 9, 1945 — 'Fat Man'). Nihon Hidankyo represents these survivors in their campaign for nuclear abolition.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23067,
        "question_text": 'P.R. Sreejesh retired from international hockey after which event?',
        "option_a": 'Tokyo Olympics 2020',
        "option_b": 'Asian Games 2023',
        "option_c": 'Paris Olympics 2024',
        "option_d": 'Hockey World Cup 2023',
        "correct_answer": 'C',
        "explanation": "P.R. Sreejesh, India's star goalkeeper, announced his retirement after the Paris Olympics 2024 — where India won the bronze medal. He received Padma Bhushan 2025 in recognition of his legendary career.",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 23068,
        "question_text": 'The 2024 Booker Prize winner Samantha Harvey is from which country?',
        "option_a": 'USA',
        "option_b": 'Australia',
        "option_c": 'UK',
        "option_d": 'Canada',
        "correct_answer": 'C',
        "explanation": "Samantha Harvey is a British author. 'Orbital' (2024 Booker winner) is her fourth novel. She is a creative writing professor at Bath Spa University, UK.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23069,
        "question_text": 'Which Khel Ratna 2024 awardee won a Para-Athletics gold at Paris 2024 Paralympics?',
        "option_a": 'Manu Bhaker',
        "option_b": 'Gukesh Dommaraju',
        "option_c": 'Harmanpreet Singh',
        "option_d": 'Praveen Kumar',
        "correct_answer": 'D',
        "explanation": 'Praveen Kumar won a gold medal in High Jump (T64 category) at Paris 2024 Paralympics. He received the Khel Ratna 2024 award on January 17, 2025, for this historic achievement.',
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 23070,
        "question_text": "MS Swaminathan (Bharat Ratna 2024) is associated with which of India's major achievements?",
        "option_a": 'Nuclear weapons programme',
        "option_b": 'Space programme (ISRO)',
        "option_c": 'Green Revolution in agriculture',
        "option_d": 'White Revolution in dairy',
        "correct_answer": 'C',
        "explanation": "M.S. Swaminathan is called the 'Father of India's Green Revolution' — introducing high-yielding varieties of wheat and rice in the 1960s-70s that ended India's food scarcity. White Revolution (dairy) is associated with Verghese Kurien.",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 23071,
        "question_text": 'Which Nobel Prize 2025 is linked to research that may help treat autoimmune diseases like Type 1 diabetes and Multiple Sclerosis?',
        "option_a": 'Nobel Physics 2025',
        "option_b": 'Nobel Chemistry 2025',
        "option_c": 'Nobel Medicine 2025',
        "option_d": 'Nobel Economics 2025',
        "correct_answer": 'C',
        "explanation": 'Nobel Medicine 2025 (Brunkow, Ramsdell, Sakaguchi) discovered regulatory T cells (Tregs) and FOXP3 gene controlling immune tolerance. This prevents autoimmune diseases where the immune system attacks its own body — like Type 1 diabetes, MS, and rheumatoid arthritis.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23072,
        "question_text": 'Best Actress at the 98th Oscars (2026) went to Jessie Buckley for which film?',
        "option_a": 'Sinners',
        "option_b": 'One Battle After Another',
        "option_c": 'Hamnet',
        "option_d": 'Frankenstein',
        "correct_answer": 'C',
        "explanation": "Jessie Buckley won Best Actress at the 98th Academy Awards (2026) for 'Hamnet' — a film about the life of Shakespeare's son and family. The 98th Oscars were held on March 15, 2026.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23073,
        "question_text": 'Which award is given annually in mathematics and is equivalent in prestige to the Nobel Prize?',
        "option_a": 'Fields Medal',
        "option_b": 'Abel Prize',
        "option_c": 'Turing Award',
        "option_d": 'Wolf Prize',
        "correct_answer": 'B',
        "explanation": 'The Abel Prize (Norway) is awarded annually and is often considered equivalent to a Nobel Prize for mathematics. The Fields Medal, while prestigious, is awarded only every 4 years and only to mathematicians under 40. Abel Prize 2025 went to Masaki Kashiwara (Japan).',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23074,
        "question_text": 'Sharda Sinha (Padma Vibhushan 2025, posthumous) was famous for which music genre?',
        "option_a": 'Carnatic classical music',
        "option_b": 'Hindustani classical music',
        "option_c": 'Bhojpuri and Maithili folk music',
        "option_d": 'Ghazal singing',
        "correct_answer": 'C',
        "explanation": "Sharda Sinha, known as 'Bihar Kokila' (Bihar's Nightingale), was famous for Bhojpuri and Maithili folk music — especially Chhath Puja songs. She received Padma Vibhushan 2025 posthumously.",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 23075,
        "question_text": 'Who won the Nobel Peace Prize 2025 and is an opposition leader against which government?',
        "option_a": 'Aung San Suu Kyi against Myanmar military junta',
        "option_b": "María Corina Machado against Nicolás Maduro's Venezuela government",
        "option_c": "Alexei Navalny against Putin's Russia",
        "option_d": "Wei Jingsheng against China's Communist Party",
        "correct_answer": 'B',
        "explanation": "María Corina Machado won Nobel Peace 2025 for promoting democratic rights in Venezuela against President Nicolás Maduro's authoritarian government. She had been banned from holding office and faced repeated arrest threats.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23076,
        "question_text": 'Metal-Organic Frameworks (MOFs), the subject of Nobel Chemistry 2025, are notable for which application relevant to climate change?',
        "option_a": 'Generating solar energy',
        "option_b": 'Capturing CO₂ from the atmosphere',
        "option_c": 'Creating biofuels',
        "option_d": 'Producing green hydrogen through splitting',
        "correct_answer": 'B',
        "explanation": 'MOFs (Nobel Chemistry 2025) have vast internal surface areas that can capture CO₂ from the atmosphere — a key climate change solution. They can also harvest water from desert air, store toxic gases safely, and catalyse reactions.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23077,
        "question_text": "Which year's Nobel Prize in Literature was won by a South Korean author, and who was it?",
        "option_a": '2023 — Jon Fosse (Norway)',
        "option_b": '2024 — Han Kang (South Korea)',
        "option_c": '2025 — László Krasznahorkai (Hungary)',
        "option_d": '2022 — Annie Ernaux (France)',
        "correct_answer": 'B',
        "explanation": 'Nobel Literature 2024 = Han Kang (South Korea). Jon Fosse won Literature 2023 (Norway). Krasznahorkai won Literature 2025 (Hungary). Annie Ernaux won Literature 2022 (France).',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23078,
        "question_text": 'The FIDE World Chess Championship 2024 (where Gukesh won) was held in which country?',
        "option_a": 'India',
        "option_b": 'Russia',
        "option_c": 'USA',
        "option_d": 'Singapore',
        "correct_answer": 'D',
        "explanation": 'The FIDE World Chess Championship 2024 was held in Singapore (Marina Bay Sands). Gukesh Dommaraju (India) defeated Ding Liren (China) in Game 14 on December 12, 2024, to become the youngest world chess champion ever.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23079,
        "question_text": 'Which statement is INCORRECT about Nobel Prize 2024?',
        "option_a": 'Han Kang = first Asian woman Nobel Literature laureate',
        "option_b": 'Nihon Hidankyo = Japanese atomic bomb survivors',
        "option_c": "Geoffrey Hinton = Nobel Physics = 'Godfather of AI'",
        "option_d": 'Nobel Peace 2024 = María Corina Machado (Venezuela)',
        "correct_answer": 'D',
        "explanation": 'María Corina Machado won Nobel PEACE 2025 (not 2024). Nobel Peace 2024 = Nihon Hidankyo (Japan). Options A, B, C are all correct about Nobel 2024.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 23080,
        "question_text": 'Swapnil Kusale won a medal at Paris Olympics 2024 in which shooting event?',
        "option_a": '10m Air Pistol',
        "option_b": '25m Rapid Fire Pistol',
        "option_c": '50m Rifle 3 Positions',
        "option_d": '10m Air Rifle',
        "correct_answer": 'C',
        "explanation": "Swapnil Kusale won bronze in 50m Rifle 3 Positions at Paris Olympics 2024 — India's first-ever Olympic medal in this event. He was one of India's 6 medal winners at Paris 2024.",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 24001,
        "question_text": 'The 59th Jnanpith Award (2024) was given to Vinod Kumar Shukla. He is the first recipient from which state?',
        "option_a": 'Madhya Pradesh',
        "option_b": 'Bihar',
        "option_c": 'Chhattisgarh',
        "option_d": 'Jharkhand',
        "correct_answer": 'C',
        "explanation": "Vinod Kumar Shukla, eminent Hindi poet and writer from Raipur, Chhattisgarh, received the 59th Jnanpith Award 2024 — the first from Chhattisgarh and the 12th Hindi writer to win India's highest literary honour. Born 1937, he is 88 years old.",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 24002,
        "question_text": 'The 58th Jnanpith Award (2023) was jointly awarded to which two literary figures?',
        "option_a": 'Gulzar (Urdu) and Jagadguru Rambhadracharyaji (Sanskrit)',
        "option_b": 'Amitav Ghosh (English) and Javed Akhtar (Urdu)',
        "option_c": 'Mahasweta Devi (Bengali) and Ashokamitran (Tamil)',
        "option_d": 'Sitanshu Yashaschandra (Gujarati) and Rahman Rahi (Kashmiri)',
        "correct_answer": 'A',
        "explanation": "The 58th Jnanpith Award 2023 was given to Gulzar (for Urdu) and Jagadguru Rambhadracharyaji (for Sanskrit). The Jnanpith Award is India's highest literary honour, given by Bharatiya Jnanpith Trust.",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 24003,
        "question_text": "Sri Lanka honoured PM Narendra Modi with its highest civilian award 'Mithra Vibhushana' in 2025. This was his how-manyth international honour from a foreign nation?",
        "option_a": '15th',
        "option_b": '18th',
        "option_c": '22nd',
        "option_d": '28th',
        "correct_answer": 'C',
        "explanation": "Sri Lanka's President Anura Kumara Dissanayake conferred the 'Mithra Vibhushana' award on PM Modi in Colombo — India-Sri Lanka's highest civilian honour. It was the 22nd international award given to PM Modi by a foreign nation.",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 24004,
        "question_text": 'Dr. K. Kasturirangan, who passed away recently, was best known as:',
        "option_a": 'Former RBI Governor and architect of banking reforms',
        "option_b": "Former ISRO Chairman and key architect of India's National Education Policy (NEP 2020)",
        "option_c": 'Former DRDO chief who developed the Agni missile',
        "option_d": 'Former Election Commissioner who reformed electoral rolls',
        "correct_answer": 'B',
        "explanation": "Dr. K. Kasturirangan (1940-2025) was ISRO Chairman for over 9 years (1994-2003), during which PSLV became India's most reliable rocket. He also chaired the committee that drafted National Education Policy (NEP) 2020. He died in Bengaluru.",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 24005,
        "question_text": 'Anju Rathi Rana made history in March 2025 by becoming the first woman Secretary of which department?',
        "option_a": 'Department of Home Affairs',
        "option_b": 'Department of Legal Affairs, Ministry of Law and Justice',
        "option_c": 'Department of External Affairs',
        "option_d": 'Department of Science and Technology',
        "correct_answer": 'B',
        "explanation": 'Dr. Anju Rathi Rana became the first woman Secretary of the Department of Legal Affairs, Ministry of Law and Justice in March 2025. She has represented India at international forums including the BRICS Ministers of Justice Meeting.',
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 24006,
        "question_text": 'The Ramnath Goenka Excellence in Journalism Award is instituted by which organisation?',
        "option_a": 'Press Trust of India',
        "option_b": 'Indian Express Group',
        "option_c": 'Times of India Group',
        "option_d": 'Hindustan Times Media',
        "correct_answer": 'B',
        "explanation": 'The Ramnath Goenka Award for Excellence in Journalism is instituted by the Indian Express Group (2005). Named after founder Ramnath Goenka, it honours journalists for excellence despite political and economic pressures. The 19th edition was held in March 2025.',
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 24007,
        "question_text": 'Daripalli Ramaiah (1937-2025), who passed away recently, was a famous environmentalist from Telangana. He was known as:',
        "option_a": "'Vana Purusha' for afforestation in Rajasthan",
        "option_b": "'Chetla Ramaiah' (Tree Man) who planted 1 crore saplings",
        "option_c": "Father of India's watershed management",
        "option_d": 'Pioneer of organic farming in Andhra Pradesh',
        "correct_answer": 'B',
        "explanation": 'Daripalli Ramaiah (Chetla Ramaiah / Vanajeevi) from Telangana planted over 1 crore (10 million) saplings in his lifetime. Awarded Padma Shri 2017. He passed away in 2025 at age 88.',
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 24008,
        "question_text": 'The Jnanpith Award is administered by which trust?',
        "option_a": 'Sahitya Akademi',
        "option_b": 'Sangeet Natak Akademi',
        "option_c": 'Bharatiya Jnanpith Trust',
        "option_d": 'National Book Trust',
        "correct_answer": 'C',
        "explanation": "The Jnanpith Award — India's highest literary honour — is administered by the Bharatiya Jnanpith Trust, established in 1944. The first Jnanpith Award was given to G.S. Kurup (Malayalam) in 1965.",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 24009,
        "question_text": 'The 59th Jnanpith Award winner Vinod Kumar Shukla is a writer in which language?',
        "option_a": 'Hindi',
        "option_b": 'Chhattisgarhi dialect only',
        "option_c": 'Marathi',
        "option_d": 'Bhojpuri',
        "correct_answer": 'A',
        "explanation": "Vinod Kumar Shukla writes in Hindi. He is the 12th Hindi writer to receive the Jnanpith Award. His works include poetry collection 'Lagbhag Jai Hind' (1971) and novels like 'Naukar ki Kameez.'",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 24010,
        "question_text": 'Which institution presents the Major Dhyan Chand Khel Ratna and other national sports awards?',
        "option_a": 'Sports Authority of India (SAI)',
        "option_b": 'Ministry of Youth Affairs and Sports, Government of India',
        "option_c": 'Indian Olympic Association',
        "option_d": 'BCCI (for cricket) and respective federations',
        "correct_answer": 'B',
        "explanation": "National sports awards including the Major Dhyan Chand Khel Ratna, Arjuna Award, Dronacharya Award, and Dhyan Chand Award are presented by the Ministry of Youth Affairs and Sports, Government of India — typically on National Sports Day (August 29, Major Dhyan Chand's birthday).",
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 24011,
        "question_text": 'National Sports Day in India (when sports awards are conferred) is celebrated on which date?',
        "option_a": 'January 26',
        "option_b": 'August 15',
        "option_c": 'August 29',
        "option_d": 'November 14',
        "correct_answer": 'C',
        "explanation": 'National Sports Day is celebrated on August 29 every year — the birth anniversary of hockey legend Major Dhyan Chand (1905-1979). The Khel Ratna, Arjuna, Dronacharya awards are typically announced on/around this date, though the 2024 awards ceremony was held January 17, 2025.',
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
    {
        "id": 24012,
        "question_text": 'Which award specifically recognises lifetime contribution to sports development/coaching — given to coaches, NOT players?',
        "option_a": 'Arjuna Award',
        "option_b": 'Khel Ratna Award',
        "option_c": 'Dronacharya Award',
        "option_d": 'Rajiv Gandhi Khel Ratna',
        "correct_answer": 'C',
        "explanation": 'The Dronacharya Award recognises coaches who have produced medallists at Olympic/Paralympic/Asian/Commonwealth Games or world championships. Named after Dronacharya — the legendary archery guru from Mahabharata. Arjuna Award is for outstanding sporting performance by athletes.',
        "folder": "AP_HC",
        "topic": "National_Current_Affairs",
    },
]

def get_db():
    if USE_POSTGRES:
        import psycopg2
        return psycopg2.connect(DATABASE_URL)
    db_path = os.path.join(os.path.dirname(__file__), "database.db")
    return sqlite3.connect(db_path)

def seed():
    conn = get_db()
    ph = "%s" if USE_POSTGRES else "?"
    inserted = 0; skipped = 0
    try:
        cur = conn.cursor()
        for q in AWARDS_MCQS:
            cur.execute(f"SELECT COUNT(*) FROM questions WHERE id={ph}", (q["id"],))
            if cur.fetchone()[0] > 0:
                skipped += 1; continue
            cur.execute(
                f"""INSERT INTO questions
                    (id, question_text, option_a, option_b, option_c, option_d,
                     correct_answer, explanation, folder, topic)
                    VALUES ({ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph})""",
                (q["id"], q["question_text"], q["option_a"], q["option_b"],
                 q["option_c"], q["option_d"], q["correct_answer"],
                 q["explanation"], q["folder"], q["topic"])
            )
            inserted += 1
        conn.commit()
        print(f"[seed_awards] Inserted={inserted}, Skipped={skipped}")
    finally:
        conn.close()

if __name__ == "__main__":
    seed()