"""
seed_intl_events_mcq.py
100 GKToday-style MCQs — Topic: National_Current_Affairs
Sub-topic: International Events & Appointments 2025-2026 ONLY
Folder: AP_HC | IDs: 29001-29100
NOTE: seed() runs DELETE+INSERT to force-refresh stale 2024 data.
Last audit: 2026-05-19. Gap-fill additions at 29081-29100 cover Tarique Rahman/Bangladesh,
Min Aung Hlaing/Myanmar, El-Enany/UNESCO, Botchwey/Commonwealth, Youssouf/AU, Iwasawa/ICJ,
Costa/EUCo, Rutte/NATO, Cormann/OECD, Sheinbaum/Mexico, Prabowo/Indonesia, AKD/Sri Lanka,
Merz-India Jan 2026, Lee-India Apr 2026, Ramaphosa GNU, Modi-Trump Feb 2025, UAE Jan 2026,
Banga/World Bank, Trump tariffs Aug 2025. Also fixed: 29014 Sushila Karki was first female
Chief Justice (not Anti-Corruption Commission head).
"""

import os, sqlite3

DATABASE_URL = os.environ.get("DATABASE_URL", "")
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)
USE_POSTGRES = bool(DATABASE_URL)

INTL_EVENTS_MCQS = [
    # WORLD LEADERS & NEW ELECTIONS 2025-2026 (29001-29018)
    {"id":29001,"question_text":"Sanae Takaichi became Japan's Prime Minister on October 21, 2025. What historic distinction does she hold?","option_a":"Japan's youngest PM ever","option_b":"Japan's first female Prime Minister","option_c":"First PM from Osaka","option_d":"First PM from Nikkei background","correct_answer":"B","explanation":"Sanae Takaichi became Japan's 104th Prime Minister on October 21, 2025 — Japan's FIRST EVER female PM. She won the LDP leadership election defeating Shinjirō Koizumi. She formed a coalition with the Japan Innovation Party. Known as Japan's 'Iron Lady' (Thatcher admirer), she is an ultraconservative: opposes same-sex marriage, China hawk, supports stronger military.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29002,"question_text":"Mark Carney became Prime Minister of Canada on March 14, 2025. He was previously head of which international institution?","option_a":"IMF","option_b":"World Bank","option_c":"Bank of Canada and Bank of England","option_d":"WTO","correct_answer":"C","explanation":"Mark Carney (Liberal Party) became Canada's PM on March 14, 2025 after Justin Trudeau resigned. Carney is a renowned economist who served as Governor of the Bank of Canada (2008-2013) and Bank of England (2013-2020). He hosted G7 Kananaskis (June 2025). Canada faces Trump's tariff threats (35% on Canadian goods from Aug 1, 2025).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29003,"question_text":"Friedrich Merz became Chancellor of Germany after federal elections on February 23, 2025. Which political party does he lead?","option_a":"SPD (Social Democratic Party)","option_b":"CDU (Christian Democratic Union)","option_c":"AfD (Alternative for Germany)","option_d":"FDP (Free Democratic Party)","correct_answer":"B","explanation":"Friedrich Merz led the CDU (Christian Democratic Union) to victory in Germany's federal elections (February 23, 2025), becoming Chancellor. Merz succeeded Olaf Scholz (SPD). The CDU won but needed a coalition (CDU/CSU + SPD). Merz is a conservative who took a harder stance on immigration and defense.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29004,"question_text":"Pope Francis died on April 21, 2025. Who was elected as the new Pope on May 8, 2025?","option_a":"Cardinal Pietro Parolin","option_b":"Cardinal Robert Prevost — Pope Leo XIV","option_c":"Cardinal Luis Tagle","option_d":"Cardinal Matteo Zuppi","correct_answer":"B","explanation":"Pope Leo XIV — born Robert Prevost (Chicago, USA) — was elected Pope on May 8, 2025, becoming the FIRST AMERICAN POPE in history. He took the name Leo XIV. Pope Francis (Jorge Mario Bergoglio, Argentine) died on April 21, 2025 at age 88, after 12 years as Pope. Pope Leo XIV chose his papal name after Leo XIII (social justice encyclicals).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29005,"question_text":"Lee Jae-myung won the South Korean presidential election and became President on June 3, 2025. He replaced which president?","option_a":"Moon Jae-in","option_b":"Yoon Suk-yeol","option_c":"Park Geun-hye","option_d":"Roh Moo-hyun","correct_answer":"B","explanation":"Lee Jae-myung (Democratic Party) became South Korean President on June 3, 2025 after winning the snap election following Yoon Suk-yeol's impeachment. Yoon had declared martial law on December 3, 2024, was impeached by the National Assembly (December 14, 2024), and removed by the Constitutional Court (April 4, 2025). Lee also hosted APEC 2025 in Gyeongju.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29006,"question_text":"Péter Magyar became Prime Minister of Hungary on April 12, 2026 after defeating which long-serving PM?","option_a":"Gyurcsány Ferenc","option_b":"Viktor Orbán","option_c":"Gordon Bajnai","option_d":"Péter Medgyessy","correct_answer":"B","explanation":"Péter Magyar (Tisza Party) became Hungary's PM on April 12, 2026, defeating Viktor Orbán who had been PM since 2010 (16 years). Magyar's Tisza Party had gained momentum after winning nearly 30% of the vote in 2024 European Parliament elections. Orbán was known for 'illiberal democracy' and close ties with Russia — policies Magyar opposed.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29007,"question_text":"Balendra Shah became Prime Minister of Nepal on March 27, 2026. His rise was preceded by which protest movement?","option_a":"Anti-corruption movement 2024","option_b":"Gen Z-led protests (September 2025) that toppled PM KP Sharma Oli","option_c":"Maoist insurgency 2024","option_d":"Monarchy restoration movement","correct_answer":"B","explanation":"Balendra Shah became Nepal's PM on March 27, 2026. His rise followed Gen Z-led protests in September 2025 that toppled PM KP Sharma Oli over corruption and economic frustration — similar to Bangladesh's student protests (2024) that removed Sheikh Hasina. Nepal's political instability continued with rapid PM changes.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29008,"question_text":"Robert Prevost, who became Pope Leo XIV on May 8, 2025, is from which US city?","option_a":"New York","option_b":"Chicago","option_c":"Boston","option_d":"Los Angeles","correct_answer":"B","explanation":"Pope Leo XIV (Robert Prevost) was born in Chicago, Illinois, USA — making him the first American pope. He served as a missionary in Peru for many years and was made a Cardinal by Pope Francis. Before becoming Pope, he led the Dicastery for Bishops in Rome. He is the 267th Pope of the Catholic Church.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29009,"question_text":"Japan's PM Sanae Takaichi (October 2025) named Japan's first female Finance Minister. Who was she?","option_a":"Seiko Noda","option_b":"Yoko Kamikawa","option_c":"Satsuki Katayama","option_d":"Akie Abe","correct_answer":"C","explanation":"Sanae Takaichi named Satsuki Katayama as Japan's first female Finance Minister, and Kimi Onoda as Economic Security Minister. Takaichi's LDP-Japan Innovation Party coalition was Japan's first since the Koizumi era. Her priorities: tackling inflation, strengthening Japan's military (JSDF), and maintaining the US-Japan alliance.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29010,"question_text":"Donald Trump was inaugurated as the 47th US President on January 20, 2025 with which running mate?","option_a":"Mike Pence","option_b":"Ron DeSantis","option_c":"JD Vance","option_d":"Marco Rubio","correct_answer":"C","explanation":"Donald Trump (Republican) was inaugurated as the 47th US President on January 20, 2025 with JD Vance as Vice President. Trump won the November 2024 election against Democratic candidate Kamala Harris. Key Trump appointments: Marco Rubio (Secretary of State), Pete Hegseth (Defense Secretary), Robert F. Kennedy Jr. (HHS Secretary).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29011,"question_text":"Keir Starmer became UK Prime Minister after Labour's landslide victory in July 2024. Which key India-related agreement did he oversee in 2025?","option_a":"India-UK Defense Partnership Treaty","option_b":"India-UK Comprehensive Economic and Trade Agreement (CETA/FTA)","option_c":"India-UK Nuclear Cooperation Agreement","option_d":"India-UK Climate Alliance","correct_answer":"B","explanation":"UK PM Keir Starmer (Labour, since July 2024) oversaw the India-UK CETA (Comprehensive Economic and Trade Agreement/FTA) — concluded in principle May 6, 2025, signed July 24, 2025. This was a landmark achievement: 99% of Indian exports get duty-free UK access; 90% of UK exports to India get reduced tariffs. Target: double trade to $112 billion by 2030.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29012,"question_text":"Who became Bangladesh's Chief Advisor (head of interim government) after Sheikh Hasina fled in August 2024, continuing in 2025-2026?","option_a":"Khaleda Zia","option_b":"Muhammad Yunus","option_c":"Mirza Fakhrul Islam","option_d":"Abdul Hamid","correct_answer":"B","explanation":"Muhammad Yunus (Nobel Peace Prize 2006 for micro-finance/Grameen Bank) became Bangladesh's Chief Advisor heading the interim government after Sheikh Hasina fled to India (August 5, 2024) following student-led mass protests. In 2025-2026, Yunus led Bangladesh's transition, navigating relations with India which remained strained due to the Hasina factor.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29013,"question_text":"Ahmed al-Sharaa (formerly known as Abu Mohammad al-Jolani) became Syria's head of state after Assad fled in December 2024. What position does he hold as of 2025-2026?","option_a":"President of Syrian Arab Republic","option_b":"Prime Minister and transitional leader","option_c":"Head of interim/transitional government","option_d":"Military Commander-in-Chief","correct_answer":"C","explanation":"Ahmed al-Sharaa (real name of Abu Mohammad al-Jolani, HTS leader) became Syria's head of the transitional government after Bashar al-Assad fled to Russia (December 8, 2024). In 2025-2026, he led Syria's transition — seeking to shed the jihadist image and normalize with international community. The HTS (Hayat Tahrir al-Sham) was delisted from terrorist designation by some Western nations.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29014,"question_text":"Sushila Karki became Nepal's first female (interim) Prime Minister in September 2025. Which institution had she earlier headed as its first woman?","option_a":"Nepal Rastra Bank","option_b":"Nepal Supreme Court (as Chief Justice 2016-17)","option_c":"Anti-Corruption Commission","option_d":"Nepal Army","correct_answer":"B","explanation":"Sushila Karki was Nepal's FIRST FEMALE CHIEF JUSTICE of the Supreme Court (July 2016 - June 2017), known for her anti-corruption stance and integrity. She was sworn in as interim PM on September 12, 2025 — Nepal's FIRST FEMALE head of government — after Gen Z-led protests forced KP Sharma Oli to resign. Her name was uniquely chosen via a Discord poll by protesters. She stepped down for Balen Shah in March 2026.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29015,"question_text":"To Lam became Vietnam's Communist Party General Secretary in 2024 and continued through 2025-2026. Vietnam's political system is:","option_a":"Multi-party democracy","option_b":"Constitutional monarchy","option_c":"Single-party socialist state led by Communist Party","option_d":"Federal republic","correct_answer":"C","explanation":"Vietnam is a single-party socialist state led by the Communist Party of Vietnam (CPV). To Lam became CPV General Secretary in 2024 after Nguyen Phu Trong died. The General Secretary is Vietnam's most powerful position. Vietnam is a key trade partner for India and has growing cooperation with QUAD countries amid South China Sea tensions with China.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29016,"question_text":"María Corina Machado of Venezuela won the Nobel Peace Prize 2025. What was she recognized for?","option_a":"Founding a regional climate coalition","option_b":"Tireless work promoting democratic rights and peaceful transition from dictatorship","option_c":"Negotiating drug cartel peace agreements","option_d":"Establishing the Latin American Human Rights Court","correct_answer":"B","explanation":"María Corina Machado won the Nobel Peace Prize 2025 for 'her tireless work promoting democratic rights for the people of Venezuela and her struggle to achieve a just and peaceful transition from dictatorship to democracy.' She is the leader of Venezuela's opposition against Nicolás Maduro's government. Maduro was reportedly captured by the US on January 3, 2026.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29017,"question_text":"Romuald Wadagni was appointed President of Benin on April 12, 2026. Benin is located in which region of Africa?","option_a":"East Africa","option_b":"Southern Africa","option_c":"West Africa","option_d":"North Africa","correct_answer":"C","explanation":"Benin is in West Africa, bordered by Togo, Burkina Faso, Niger, Nigeria, and the Atlantic Ocean. Capital: Porto-Novo (official)/Cotonou (economic). Benin is historically significant as the Kingdom of Dahomey — known for the slave trade era. It is a constitutional republic. Benin is not to be confused with Benin City in Nigeria.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29018,"question_text":"The 2025 South Korean presidential election was a snap election called after President Yoon was removed. The Constitutional Court upheld Yoon's impeachment on which date?","option_a":"January 14, 2025","option_b":"February 28, 2025","option_c":"April 4, 2025","option_d":"May 15, 2025","correct_answer":"C","explanation":"South Korea's Constitutional Court upheld Yoon Suk-yeol's impeachment on April 4, 2025 — permanently removing him from office. This triggered the snap presidential election won by Lee Jae-myung (Democratic Party) on June 3, 2025. Yoon had declared martial law on December 3, 2024 (retracted after 6 hours) and was impeached by National Assembly on December 14, 2024.","folder":"AP_HC","topic":"International_Current_Affairs"},

    # KEY GLOBAL EVENTS 2025-2026 (29019-29038)
    {"id":29019,"question_text":"Operation Sindoor (India, May 7, 2025) was in retaliation for which terrorist attack?","option_a":"Uri attack 2016","option_b":"Pulwama attack 2019","option_c":"Pahalgam terror attack April 22, 2025","option_d":"Gurdaspur attack","correct_answer":"C","explanation":"Operation Sindoor (May 7, 2025) was India's retaliation for the Pahalgam terror attack (April 22, 2025) — where 26 tourists were killed at Baisaran Valley, Anantnag, J&K by The Resistance Front (LeT proxy). India struck 9 terrorist camps of JeM and LeT in Pakistan and PoK. Ceasefire on May 10, 2025.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29020,"question_text":"The Twelve-Day War (June 13-24, 2025) was between Israel and Iran. Which country's military also directly participated by bombing Iranian nuclear sites on June 22?","option_a":"Saudi Arabia","option_b":"United States","option_c":"UK","option_d":"France","correct_answer":"B","explanation":"The USA directly bombed 3 Iranian nuclear sites on June 22, 2025 during the Twelve-Day War — the most direct US military action against Iran's nuclear program ever. Israel had launched the war on June 13. Iran retaliated (Operation True Promise III: 550+ missiles + 1,000+ drones). Ceasefire: June 24, 2025 under US pressure.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29021,"question_text":"The 2026 Iran War (February 28, 2026) resulted in the death of which Iranian leader — the Supreme Leader since 1989?","option_a":"Masoud Pezeshkian","option_b":"Ali Larijani","option_c":"Ali Khamenei","option_d":"Mohammad Bagheri","correct_answer":"C","explanation":"Ali Khamenei — Iran's Supreme Leader since June 1989 — was killed in the coordinated US-Israel strikes on February 28, 2026. He had been Supreme Leader for 37 years. Also killed: Ali Larijani, multiple army commanders. Iran closed the Strait of Hormuz in response; struck US bases in Bahrain, Jordan, Kuwait, Qatar, Saudi Arabia, UAE.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29022,"question_text":"Indonesia joined BRICS as its 11th full member on January 6, 2025. BRICS's 17th Summit was held in which city and country in July 2025?","option_a":"São Paulo, Brazil","option_b":"Rio de Janeiro, Brazil","option_c":"Brasília, Brazil","option_d":"Bogotá, Colombia","correct_answer":"B","explanation":"BRICS 17th Summit: Rio de Janeiro, Brazil, July 6-7, 2025 (Brazil held 2025 chairmanship). Indonesia was present as BRICS's 11th full member (joined Jan 6, 2025 — first Southeast Asian BRICS member). 10 new BRICS partner countries were also announced (Belarus, Bolivia, Kazakhstan, Cuba, Malaysia, Nigeria, Thailand, Uganda, Uzbekistan, Vietnam).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29023,"question_text":"Russia became the first country to officially recognize the Taliban government of Afghanistan on:","option_a":"January 15, 2025","option_b":"March 7, 2025","option_c":"July 3, 2025","option_d":"October 15, 2025","correct_answer":"C","explanation":"Russia officially recognized the Taliban government of Afghanistan on July 3, 2025 — first country to do so. Taliban have ruled Afghanistan since August 2021 (US withdrawal). No country had recognized them until Russia's move in July 2025. Russia sought to expand Central Asian influence and countered US-NATO regional positioning.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29024,"question_text":"India's EAM Jaishankar met Iranian FM Araghchi in New Delhi on May 15, 2026. Which of the following best describes India's stance in the 2026 Iran War?","option_a":"India fully supported US-Israel coalition","option_b":"India supported Iran's position","option_c":"India maintained neutrality, engaged diplomatically with both sides","option_d":"India had no engagement with either side","correct_answer":"C","explanation":"India maintained neutrality in the 2026 Iran War — strategic Chabahar Port in Iran, energy imports, 8 million Indian diaspora in Gulf states all demanded caution. EAM Jaishankar met Iranian FM Araghchi (May 15, 2026) while maintaining defense ties with Israel. India abstained from relevant UN votes. India's 'Vasudhaiva Kutumbakam' foreign policy guides such balanced diplomacy.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29025,"question_text":"The Gaza ceasefire Phase 1 (January 15, 2025) was mediated by three countries. Which combination is correct?","option_a":"USA, Turkey, and Egypt","option_b":"Qatar, Egypt, and USA","option_c":"Saudi Arabia, UAE, and USA","option_d":"Jordan, Egypt, and USA","correct_answer":"B","explanation":"Qatar, Egypt, and USA mediated the Gaza ceasefire Phase 1 (January 15, 2025) — a 42-day humanitarian pause with hostage releases. Qatar (Hamas political bureau host), Egypt (borders Gaza via Rafah), and USA (Israel's key ally) formed the consistent mediation troika. The Gaza conflict had started October 7, 2023 with Hamas's surprise attack.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29026,"question_text":"Sudan's civil war saw the RSF (Rapid Support Forces) capture El Fasher on October 27, 2025. Who leads the RSF?","option_a":"General Abdel Fattah al-Burhan","option_b":"Mohamed Hamdan Dagalo ('Hemeti')","option_c":"Omar al-Bashir","option_d":"Ibrahim Gambari","correct_answer":"B","explanation":"Mohamed Hamdan Dagalo ('Hemeti') leads the RSF (Rapid Support Forces) fighting against Sudan's official army (SAF) led by General al-Burhan. RSF captured El Fasher (last major SAF-held city in Darfur) on October 27, 2025, after an 18-month siege. Sudan's civil war (started April 2023) has caused the world's worst humanitarian crisis: 10M+ internally displaced.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29027,"question_text":"Myanmar's military (Tatmadaw) has been fighting the People's Defence Force (PDF) and ethnic armed groups since the February 2021 coup. Who leads Myanmar's military government (SAC)?","option_a":"Aung San Suu Kyi","option_b":"Senior General Min Aung Hlaing","option_c":"Thein Sein","option_d":"General Shwe Mann","correct_answer":"B","explanation":"Senior General Min Aung Hlaing leads Myanmar's State Administration Council (SAC) — the military junta that seized power in the February 1, 2021 coup. Aung San Suu Kyi (NLD) was detained and remains imprisoned. Myanmar's civil war: 90,000+ killed, 3M+ internally displaced, 1M+ fled abroad by 2025. ASEAN's Five-Point Consensus (2021) remains largely unimplemented.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29028,"question_text":"Japan enacted an AI law in May 2025. Japan's approach to AI regulation is different from the EU AI Act. How?","option_a":"Japan's law is stricter with mandatory compliance","option_b":"Japan's law encourages coordination and voluntary responsibility — flexible model vs EU's mandatory risk-based approach","option_c":"Japan banned AI development entirely","option_d":"Japan only regulates AI for military use","correct_answer":"B","explanation":"Japan enacted an AI law in May 2025 focusing on coordination and voluntary responsibility — a flexible model. Unlike the EU AI Act (2024) which divides AI into risk levels with strict mandatory rules, Japan's approach encourages self-regulation and industry cooperation. This reflects Japan's economic strategy of not over-regulating emerging tech while ensuring societal safety.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29029,"question_text":"Hawaii became the first US state to implement a 'Green Fee' on tourists. This fee funds:","option_a":"State military defense","option_b":"Conservation and environmental protection","option_c":"Infrastructure development","option_d":"Healthcare","correct_answer":"B","explanation":"Hawaii became the first US state to implement a 'Green Fee' on tourists — a per-night charge to fund conservation and environmental protection of Hawaii's fragile ecosystems. Hawaii faces mass tourism pressure on its coral reefs, forests, and wildlife. Hawaii is also the state with the US's highest renewable energy commitment (100% by 2045).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29030,"question_text":"Pope Francis died on April 21, 2025, at age 88. He was the first Pope from which country?","option_a":"Brazil","option_b":"Spain","option_c":"Argentina","option_d":"Mexico","correct_answer":"C","explanation":"Pope Francis (born Jorge Mario Bergoglio, December 17, 1936, Buenos Aires, Argentina) was the first Pope from Latin America and the first Jesuit Pope. He died April 21, 2025 at age 88 after 12 years as Pope (elected March 13, 2013). He succeeded Pope Benedict XVI (who resigned — rare in papal history). Pope Leo XIV was elected on May 8, 2025.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29031,"question_text":"Timor-Leste became the 11th member of ASEAN in October 2025. It was the first ASEAN expansion since which year?","option_a":"1995","option_b":"1997","option_c":"1999","option_d":"2002","correct_answer":"C","explanation":"Timor-Leste's admission (October 2025) was ASEAN's first expansion since Cambodia joined in 1999 — a 26-year gap. ASEAN had 10 members from 1999-2025. The previous round of expansions: Vietnam (1995), Myanmar + Laos (1997), Cambodia (1999). ASEAN was founded in 1967 with 5 members (Thailand, Malaysia, Singapore, Philippines, Indonesia).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29032,"question_text":"The 2026 Thailand-Cambodia conflict was resolved by the 'Kuala Lumpur Peace Accord' at ASEAN 2025. US President Trump and which Malaysian PM witnessed the signing?","option_a":"Mahathir Mohamad","option_b":"Ismail Sabri Yaakob","option_c":"Anwar Ibrahim","option_d":"Najib Razak","correct_answer":"C","explanation":"Malaysian PM Anwar Ibrahim (and Trump) witnessed the Thailand-Cambodia 'Kuala Lumpur Peace Accord' at the 47th ASEAN Summit (October 2025). Anwar Ibrahim became Malaysia's PM in November 2022. He chaired ASEAN in 2025. The accord involved ceasefire, weapon withdrawal, and release of 18 Cambodian detainees by Bangkok.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29033,"question_text":"Which major international health crisis emerged in 2025 when WHO declared a polio outbreak in Papua New Guinea?","option_a":"Ebola","option_b":"Polio","option_c":"Monkeypox","option_d":"Cholera","correct_answer":"B","explanation":"Papua New Guinea (PNG) had a WHO-declared polio outbreak in 2025. Polio (poliovirus) was nearly eradicated globally — with only Afghanistan and Pakistan as endemic countries — making outbreaks elsewhere concerning. PNG is in the Western Pacific region. WHO declared PNG's outbreak a Public Health Emergency of International Concern (PHEIC) requiring global vaccination response.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29034,"question_text":"Saudi Arabia launched which digital tourism platform in 2025 to enhance its global tourism sector?","option_a":"TOURVISION","option_b":"TOURISE","option_c":"Saudi Experience","option_d":"Visit Arabia","correct_answer":"B","explanation":"Saudi Arabia launched the TOURISE platform in 2025 — a digital tourism enhancement platform as part of Saudi Vision 2030. Saudi Arabia has been rapidly developing its tourism sector: NEOM (futuristic city), AlUla (heritage), Red Sea Project (luxury tourism). Saudi Arabia aims to attract 150 million tourists/year by 2030.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29035,"question_text":"Jakarta, Indonesia was described as the world's most populous urban area in 2025 with approximately 42 million people. Why is Jakarta facing an existential crisis?","option_a":"Earthquake risk","option_b":"Flooding and sinking due to excessive groundwater extraction","option_c":"Air pollution","option_d":"Extreme heat","correct_answer":"B","explanation":"Jakarta faces an existential crisis: it is sinking at 1-25 cm/year due to excessive groundwater extraction — making it the world's fastest-sinking major city. Parts of North Jakarta are already below sea level. Indonesia began building a new capital city 'Nusantara' in Borneo to reduce Jakarta's administrative burden. Jakarta remains Indonesia's economic and cultural capital.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29036,"question_text":"The Indonesia-based volcano Mount Lewotobi Laki-laki erupted in 2025. It is located on which island?","option_a":"Java","option_b":"Bali","option_c":"Flores island","option_d":"Sumatra","correct_answer":"C","explanation":"Mount Lewotobi Laki-laki erupted in 2025 on Flores island, East Nusa Tenggara province, Indonesia. 'Laki-laki' means 'male' in Indonesian — there is a paired peak Lewotobi Perempuan ('female'). Indonesia has 127 active volcanoes — the world's most. Indonesia sits on the 'Ring of Fire' — the Pacific tectonic plate boundary.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29037,"question_text":"Typhoon Danas struck which region of Taiwan in 2025?","option_a":"Taipei Metropolitan Area","option_b":"Kaohsiung in southern Taiwan","option_c":"Chiayi County","option_d":"Hualien County","correct_answer":"C","explanation":"Typhoon Danas struck Chiayi County in southwestern Taiwan in 2025, causing floods and landslides. Taiwan faces 3-5 typhoons annually due to its location in the Western Pacific typhoon belt. Taiwan's semiconductor industry (TSMC) facilities in Hsinchu and Tainan were on high alert. Taiwan is also a major geopolitical flashpoint amid China-US tensions.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29038,"question_text":"China's Tianwen-2 mission (2025-2026) targets which near-Earth asteroid for a sample-return mission?","option_a":"Bennu","option_b":"Ryugu","option_c":"2016HO3 (Kamo'oalewa)","option_d":"Apophis","correct_answer":"C","explanation":"China's Tianwen-2 is a dual-mission: (1) Sample-return from near-Earth asteroid 2016HO3 (also called Kamo'oalewa — a quasi-satellite of Earth), then (2) rendezvous with main-belt comet 311P/PanSTARRS. Launched in 2025. Compare: NASA's OSIRIS-REx sampled asteroid Bennu (samples returned 2023); Japan's Hayabusa2 sampled Ryugu (2020).","folder":"AP_HC","topic":"International_Current_Affairs"},

    # INDIA'S INTERNATIONAL ENGAGEMENT 2025-2026 (29039-29055)
    {"id":29039,"question_text":"India signed a MoU with UAE on May 15, 2026 for cooperation in which strategic energy sector?","option_a":"Nuclear energy","option_b":"Strategic petroleum reserves and LPG supplies","option_c":"Solar power cooperation","option_d":"Green hydrogen","correct_answer":"B","explanation":"India-UAE signed an MoU on May 15, 2026 for cooperation in strategic petroleum reserves and increased LPG (liquefied petroleum gas) supplies. India's Strategic Petroleum Reserve (SPR) program maintains reserves at Vishakhapatnam, Mangaluru, and Padur. UAE is one of India's top crude oil suppliers.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29040,"question_text":"India resumed the Kailash Mansarovar Yatra in 2025 after it was suspended since 2020. Why was it suspended?","option_a":"Nepal-India border dispute","option_b":"COVID-19 pandemic and India-China Galwan Valley clash","option_c":"Pakistan's objection","option_d":"Tibet Autonomous Region closure","correct_answer":"B","explanation":"Kailash Mansarovar Yatra was suspended from 2020 due to: (1) COVID-19 pandemic and (2) India-China Galwan Valley clash (June 2020) — which led to military standoff at LAC. Resumption in 2025 was part of broader India-China normalization (LAC patrolling at Depsang/Demchok friction points resolved October 2024). Mount Kailash is sacred in Hinduism, Buddhism, Jainism, and Bön.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29041,"question_text":"India became the first country to secure TWO deep-sea polymetallic sulphide exploration contracts from ISA. ISA stands for:","option_a":"International Space Agency","option_b":"International Seabed Authority","option_c":"Indian Scientific Affiliation","option_d":"International Submarine Association","correct_answer":"B","explanation":"India secured 2 polymetallic sulphide exploration contracts from ISA (International Seabed Authority) — the first country with 2 contracts for polymetallic sulphides. ISA regulates mineral exploration in international seabed (the 'Area'). Polymetallic sulphides contain copper, zinc, gold, silver. ISA is headquartered in Kingston, Jamaica.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29042,"question_text":"India dispatched BHISHM (Bike-mounted Hospital System) to which country on its 60th Independence Day, demonstrating medical diplomacy?","option_a":"Sri Lanka","option_b":"Nepal","option_c":"Maldives","option_d":"Bhutan","correct_answer":"C","explanation":"India gifted BHISHM (Bike-mounted Hospital System) to Maldives on its 60th Independence Day as part of India's 'Neighbourhood First' medical diplomacy. BHISHM is a compact, portable field hospital that can be transported on bikes — developed under Project Arogya Maitri. India-Maldives relations had tensions in 2024 but improved in 2025.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29043,"question_text":"Operation Sagar Bandhu was India's operation to help which neighboring country during Cyclone Ditwah in November 2025?","option_a":"Myanmar","option_b":"Bangladesh","option_c":"Sri Lanka","option_d":"Maldives","correct_answer":"C","explanation":"Operation Sagar Bandhu was India's operation to assist Sri Lanka during Cyclone Ditwah (November 27, 2025) — demonstrating India's 'First Responder' role in the Indian Ocean. India provided disaster relief including NDRF teams, essential supplies, and naval vessels. India-Sri Lanka relations have improved with Indian assistance in Sri Lanka's economic recovery.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29044,"question_text":"India-China resumed the Kailash Mansarovar Yatra in 2025. Earlier, India-China had also resolved LAC patrolling issues at which two friction points in October 2024?","option_a":"Pangong Tso and Hot Springs","option_b":"Depsang Plains and Demchok","option_c":"Gogra and Galwan","option_d":"Chushul and Daulat Beg Oldi","correct_answer":"B","explanation":"India-China resolved LAC patrolling at Depsang Plains and Demchok friction points in October 2024 — a major step in de-escalation after the June 2020 Galwan Valley clash (20 Indian soldiers killed). This was followed by the first Modi-Xi bilateral at BRICS Kazan (October 2024). In 2025, Modi met Xi at SCO Tianjin — first time on Chinese soil in 7 years.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29045,"question_text":"India was elected to the Executive Committee of ICAO's Part II category. ICAO's main function is:","option_a":"International trade regulation","option_b":"Global civil aviation safety and standards","option_c":"Maritime shipping regulations","option_d":"Telecommunications standards","correct_answer":"B","explanation":"ICAO (International Civil Aviation Organization) regulates global civil aviation safety, standards, and procedures. HQ: Montreal, Canada. Founded: 1944 (Chicago Convention/Convention on International Civil Aviation). India was elected to ICAO Executive Committee Part II — significant for India's growing aviation market (3rd largest domestic market; UDAN regional connectivity scheme).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29046,"question_text":"India hosted the 89th IEC General Meeting at Bharat Mandapam, New Delhi in September 2025. IEC stands for:","option_a":"Indian Engineering Council","option_b":"International Electrotechnical Commission","option_c":"International Energy Commission","option_d":"Indian Economic Committee","correct_answer":"B","explanation":"IEC (International Electrotechnical Commission) — founded 1906 — is the global body for international standards in electrical, electronic, and related technologies. HQ: Geneva, Switzerland. India hosted IEC's 89th General Meeting at Bharat Mandapam, New Delhi (September 2025) — a prestigious global standardization event. India's standards body is BIS (Bureau of Indian Standards).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29047,"question_text":"The CBI was re-designated as India's national bureau for Interpol. What does CBI's Interpol national bureau role involve?","option_a":"International cybercrime only","option_b":"Coordinating with Interpol for cross-border crime investigation and extradition requests","option_c":"Monitoring Indian nationals abroad","option_d":"Financial intelligence gathering","correct_answer":"B","explanation":"India's CBI (Central Bureau of Investigation) serves as India's national bureau for Interpol — coordinating international crime investigation requests, extraditions, and information sharing with 196 Interpol member countries. India was elected to Interpol's Asian Committee in Singapore. Interpol HQ: Lyon, France. Founded: 1923.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29048,"question_text":"The LeadIT initiative (Leadership Group for Industry Transition) was co-founded by India and which country in 2019?","option_a":"USA","option_b":"Germany","option_c":"Sweden","option_d":"France","correct_answer":"C","explanation":"LeadIT (Leadership Group for Industry Transition) was co-founded by India and Sweden in 2019 at COP25 to decarbonize heavy industries (steel, cement, chemicals, aluminium) that are difficult to decarbonize. HQ: Sweden. LeadIT connects government and private sector to develop net-zero heavy industry pathways. India's heavy industry sector makes up ~30% of national GHG emissions.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29049,"question_text":"ICAR Maitri 2.0 is an agri-tech cooperation initiative between India and which country?","option_a":"USA","option_b":"Brazil","option_c":"Australia","option_d":"Israel","correct_answer":"B","explanation":"ICAR Maitri 2.0 is an agricultural technology cooperation initiative between ICAR (Indian Council of Agricultural Research) and Brazil — building on the original Maitri collaboration. India-Brazil cooperation focuses on: tropical agriculture, ethanol/biofuels (Brazil leads global sugar-ethanol), digital agriculture, and genomics. Brazil also co-sponsored the Blue NDC Challenge with France.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29050,"question_text":"India-UK FTA was officially named CETA. What does CETA stand for in this context?","option_a":"Cooperative Economic and Trade Alliance","option_b":"Comprehensive Economic and Trade Agreement","option_c":"Continental Economic Trade Architecture","option_d":"Cross-border Economic Treaty Agreement","correct_answer":"B","explanation":"India-UK CETA = Comprehensive Economic and Trade Agreement (signed July 24, 2025). This eliminates/reduces tariffs on 99% of Indian exports to UK and 90% of UK exports to India. Target: increase bilateral trade by $34 billion/year from 2040. Note: Canada-EU also has a CETA (Comprehensive Economic and Trade Agreement) — the same acronym used differently.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29051,"question_text":"Iran's Bushehr Nuclear Power Plant was built with technical assistance from which country and when was it completed?","option_a":"China, 2008","option_b":"Russia, 2011","option_c":"Pakistan, 2005","option_d":"France, 2000","correct_answer":"B","explanation":"Iran's Bushehr Nuclear Power Plant (Bushehr-1) was built with Russian technical assistance and became operational in 2011. Russia's Rosatom constructed it. South Pars/North Dome Gas Field (world's largest natural gas reservoir) is jointly held by Iran and Qatar. Bushehr is separate from Iran's controversial enrichment facilities (Natanz, Fordow).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29052,"question_text":"The EU's CBAM (Carbon Border Adjustment Mechanism) entered full enforcement in 2026. It is part of which EU climate policy package?","option_a":"Green Deal 2030","option_b":"Fit for 55","option_c":"REPowerEU","option_d":"European Climate Law","correct_answer":"B","explanation":"CBAM (Carbon Border Adjustment Mechanism) full enforcement began in 2026, as part of EU's 'Fit for 55' package targeting 55% GHG reduction by 2030 (vs 1990 levels). CBAM taxes carbon-intensive imports (steel, cement, aluminium, fertilisers, electricity, hydrogen) to prevent carbon leakage. India has expressed deep reservations about CBAM's trade impact on Indian exports to EU.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29053,"question_text":"The Blue NDC Challenge was launched by France and Brazil for ocean conservation at which forum?","option_a":"COP28 Dubai","option_b":"UNOC3 (UN Ocean Conference 3)","option_c":"UNCLOS meeting","option_d":"G20 Brazil 2024","correct_answer":"B","explanation":"France and Brazil launched the Blue NDC Challenge at UNOC3 (Third UN Ocean Conference) to integrate ocean-related commitments into Nationally Determined Contributions (NDCs) under the Paris Agreement. Blue NDCs recognize oceans as carbon sinks and biodiversity hotspots requiring climate protection. Small Island Developing States (SIDS) are the biggest supporters.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29054,"question_text":"MERCOSUR's headquarters is in which South American city?","option_a":"Buenos Aires, Argentina","option_b":"Brasília, Brazil","option_c":"Montevideo, Uruguay","option_d":"Santiago, Chile","correct_answer":"C","explanation":"MERCOSUR (Southern Common Market) HQ is in Montevideo, Uruguay. Founded by the Treaty of Asunción (1991, in Asunción, Paraguay). Full members: Argentina, Brazil, Paraguay, Uruguay, Bolivia (since 2024). Venezuela was suspended. MERCOSUR is the world's 5th largest economy by GDP. Brazil-India's ICAR Maitri 2.0 strengthens MERCOSUR-South Asia agricultural links.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29055,"question_text":"SICA (Central American Integration System) was established by which treaty in 1991?","option_a":"Tegucigalpa Protocol","option_b":"Treaty of Asunción","option_c":"Cartagena Agreement","option_d":"Bogotá Protocol","correct_answer":"A","explanation":"SICA (Sistema de la Integración Centroamericana / Central American Integration System) was established by the Tegucigalpa Protocol in December 1991. Members: Guatemala, El Salvador, Honduras, Nicaragua, Costa Rica, Panama, Belize, Dominican Republic. HQ: San Salvador, El Salvador. SICA promotes Central American political, economic, and social integration.","folder":"AP_HC","topic":"International_Current_Affairs"},

    # INTERNATIONAL BODIES, SCIENCE, MISC 2025-2026 (29056-29070)
    {"id":29056,"question_text":"The Nobel Peace Prize 2025 went to María Corina Machado of Venezuela. Where is the Nobel Peace Prize awarded (unlike other Nobel Prizes which are awarded in Stockholm)?","option_a":"Geneva, Switzerland","option_b":"Oslo, Norway","option_c":"Brussels, Belgium","option_d":"Vienna, Austria","correct_answer":"B","explanation":"The Nobel Peace Prize is awarded in Oslo, Norway (at Oslo City Hall) — unlike other Nobel Prizes (Physics, Chemistry, Medicine, Literature, Economics) which are awarded in Stockholm, Sweden. This was stipulated by Alfred Nobel's will (1895). The Norwegian Nobel Committee selects the Peace Prize laureate. Other 2025 Nobel winners: Literature = László Krasznahorkai (Hungary).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29057,"question_text":"László Krasznahorkai won the Nobel Prize in Literature 2025. He is from which country?","option_a":"Romania","option_b":"Czech Republic","option_c":"Hungary","option_d":"Poland","correct_answer":"C","explanation":"László Krasznahorkai (born 1954) won the Nobel Prize in Literature 2025 — Hungary's first Nobel in Literature. Awarded 'for his compelling and visionary oeuvre that, in the midst of apocalyptic terror, reaffirms the power of art.' His major works: Satantango, The Melancholy of Resistance, War and War. Nobel Literature 2024: Han Kang (South Korea).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29058,"question_text":"The 2025 Nobel Prize in Physiology or Medicine was awarded for discoveries relating to:","option_a":"CRISPR gene editing","option_b":"Peripheral immune tolerance","option_c":"MicroRNA regulation","option_d":"Protein structure prediction","correct_answer":"B","explanation":"Nobel Medicine 2025: Mary Brunkow, Fred Ramsdell, and Shimon Sakaguchi won for fundamental discoveries relating to peripheral immune tolerance — how the immune system avoids attacking the body's own cells. This has major implications for autoimmune diseases and cancer immunotherapy. Nobel Medicine 2024: Victor Ambros and Gary Ruvkun (microRNA discovery).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29059,"question_text":"Nobel Physics 2025 was awarded for which discovery related to quantum mechanics?","option_a":"Higgs boson confirmation","option_b":"Macroscopic quantum mechanical tunnelling and energy quantisation in electric circuits","option_c":"Gravitational waves detection","option_d":"AI-enabled neural networks","correct_answer":"B","explanation":"Nobel Physics 2025: John Clarke, Michel Devoret, and John Martinis won for the discovery of macroscopic quantum mechanical tunnelling and energy quantisation in electric circuits — foundational work for quantum computing. Nobel Physics 2024: Hopfield and Hinton (AI/neural networks). The 2025 Nobel connects to quantum computing hardware development.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29060,"question_text":"Nobel Chemistry 2025 was awarded for pioneering metal-organic frameworks (MOFs). What are MOFs used for?","option_a":"Nuclear reactor construction","option_b":"Harvesting water from air, capturing CO2, storing gases, and catalysing reactions","option_c":"Semiconductor manufacturing","option_d":"Food preservation","correct_answer":"B","explanation":"Nobel Chemistry 2025: Susumu Kitagawa, Richard Robson, and Omar Yaghi won for metal-organic frameworks (MOFs) — molecular constructions that can harvest water from desert air, capture CO2, store toxic gases, or catalyse chemical reactions. MOFs are highly porous materials. Nobel Chemistry 2024: Hassabis, Baker, Jumper (protein structure prediction/AlphaFold).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29061,"question_text":"Nobel Economics 2025 was awarded for explaining how innovation creates economic growth. Which economist who also wrote a book about long-run economic growth won it?","option_a":"Daron Acemoglu alone","option_b":"Joel Mokyr, Philippe Aghion, and Peter Howitt","option_c":"Paul Romer","option_d":"Abhijit Banerjee","correct_answer":"B","explanation":"Nobel Economics 2025: Joel Mokyr (Northwestern), Philippe Aghion (Harvard/Collège de France), and Peter Howitt (Brown) — for explaining how innovation creates economic growth, advances society, and improves quality of life. Aghion and Howitt developed the 'Schumpeterian growth' model. Nobel Economics 2024: Acemoglu, Johnson, Robinson (colonisation and global inequality).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29062,"question_text":"Banu Mushtaq won the International Booker Prize 2025 — making her the first winner from which language?","option_a":"Telugu","option_b":"Tamil","option_c":"Kannada","option_d":"Malayalam","correct_answer":"C","explanation":"Bengaluru-based Banu Mushtaq won the International Booker Prize 2025 for 'Heart Lamp' (translated by Deepa Bhasthi from Kannada) — the first Kannada author to win the International Booker, and the first short story collection to win the prize. India has a rich tradition of regional language literature; previous Indian Booker wins were in English.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29063,"question_text":"Ousmane Dembélé won the Men's Ballon d'Or 2025. He plays for which club?","option_a":"Barcelona, Spain","option_b":"Real Madrid, Spain","option_c":"Paris Saint-Germain (PSG), France","option_d":"Manchester City, England","correct_answer":"C","explanation":"Ousmane Dembélé (France) won the Men's Ballon d'Or 2025 playing for Paris Saint-Germain (PSG). He beat Lamine Yamal (Barcelona) by 321 points. Women's Ballon d'Or: Aitana Bonmatí (Barcelona, Spain) won for the 3rd consecutive year. Ballon d'Or ceremony: September 22, 2025 at Théâtre du Châtelet, Paris. Previous men's winner: Rodri (Manchester City, 2024).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29064,"question_text":"The 67th Grammy Awards (2025) saw which hip-hop artist's song 'Not Like Us' win Record and Song of the Year?","option_a":"Drake","option_b":"Kendrick Lamar","option_c":"Jay-Z","option_d":"Travis Scott","correct_answer":"B","explanation":"Kendrick Lamar's 'Not Like Us' (a diss track targeting Drake) won Record of the Year and Song of the Year at the 67th Grammy Awards (2025). Beyoncé's Cowboy Carter won Album of the Year; Chappell Roan won Best New Artist. Kendrick Lamar was also selected to perform at Super Bowl LIX halftime show (February 2025).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29065,"question_text":"The film 'Anora' swept the Oscars 2025. Who directed this film?","option_a":"Christopher Nolan","option_b":"Martin Scorsese","option_c":"Sean Baker","option_d":"Guillermo del Toro","correct_answer":"C","explanation":"'Anora' directed by Sean Baker swept the 97th Academy Awards (Oscars 2025) — winning Best Picture, Best Director (Sean Baker), and Best Actress (Mikey Madison). The film tells the story of a sex worker who marries the son of a Russian oligarch. Sean Baker is known for 'Tangerine' (2015) and 'The Florida Project' (2017).","folder":"AP_HC","topic":"International_Current_Affairs"},

    # HIGHER ORDER / MIXED (29066-29080)
    {"id":29066,"question_text":"Which of the following 2025 world leaders is CORRECTLY matched with their role?","option_a":"Mark Carney = UK PM","option_b":"Friedrich Merz = French President","option_c":"Sanae Takaichi = Japan's 104th PM (first female)","option_d":"Péter Magyar = Czech PM","correct_answer":"C","explanation":"Correct: Sanae Takaichi = Japan's 104th PM (first female, October 21, 2025) ✓. Incorrect: Mark Carney = Canada's PM (not UK; UK PM is Keir Starmer), Friedrich Merz = Germany's Chancellor (not French President; French President remains Macron), Péter Magyar = Hungary's PM (became PM April 12, 2026, not Czech PM).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29067,"question_text":"Pope Leo XIV (Robert Prevost) is historically significant as:","option_a":"First Pope from Asia","option_b":"First American Pope and first Pope from the Order of Augustine","option_c":"First Pope from a Protestant country","option_d":"Youngest Pope in 200 years","correct_answer":"B","explanation":"Pope Leo XIV is historically significant as: (1) First American Pope ever (from Chicago, USA), (2) First Pope from the Order of Saint Augustine (Augustinian order). He was elected May 8, 2025 after Pope Francis died April 21, 2025. He chose 'Leo XIV' after Pope Leo XIII known for social justice encyclicals. Pope Leo XIV speaks English, Spanish, Italian, and French.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29068,"question_text":"BRICS admitted Indonesia (January 2025) and 10 partner countries (July 2025). Which Nobel Prize winner (Peace 2025) is from a country that is a BRICS full member?","option_a":"László Krasznahorkai (Hungary) — BRICS member","option_b":"María Corina Machado (Venezuela) — BRICS partner","option_c":"Joel Mokyr (USA) — BRICS member","option_d":"None of the above — their countries are not BRICS members","correct_answer":"D","explanation":"None of the options match: László Krasznahorkai (Hungary) — Hungary is NOT a BRICS member; María Corina Machado (Venezuela) — Venezuela is NOT a BRICS member (was a MERCOSUR member, suspended); Joel Mokyr (USA) — USA is NOT a BRICS member (BRICS was founded partly as an alternative to US-led order). The 11 BRICS full members are Brazil, Russia, India, China, South Africa, Egypt, Ethiopia, Iran, UAE, Saudi Arabia, Indonesia.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29069,"question_text":"Match the 2025 Nobel Prize with the correct field: Nobel Peace Prize winner (Maria Corina Machado) vs. Nobel Literature winner (László Krasznahorkai) — which statement is CORRECT?","option_a":"Machado is Venezuelan; Krasznahorkai is Romanian","option_b":"Machado is Venezuelan; Krasznahorkai is Hungarian","option_c":"Machado is Colombian; Krasznahorkai is Czech","option_d":"Machado is Brazilian; Krasznahorkai is Polish","correct_answer":"B","explanation":"Nobel Peace 2025: María Corina Machado — Venezuelan opposition leader, democratic rights activist. Nobel Literature 2025: László Krasznahorkai — Hungarian author, 'compelling and visionary oeuvre.' Nobel Medicine: Brunkow, Ramsdell, Sakaguchi (immune tolerance). Nobel Physics: Clarke, Devoret, Martinis (quantum circuits). Nobel Chemistry: Kitagawa, Robson, Yaghi (MOFs). Nobel Economics: Mokyr, Aghion, Howitt (innovation+growth).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29070,"question_text":"Which summit-related statement from 2025 is CORRECT?","option_a":"COP30 raised climate finance target to $300B/year by 2035","option_b":"G7 Kananaskis produced a joint communiqué signed by all 7 leaders","option_c":"ASEAN KL 2025 admitted Timor-Leste as its 11th member","option_d":"SCO 2025 was held in Astana, Kazakhstan","correct_answer":"C","explanation":"ASEAN KL 2025 admitted Timor-Leste as its 11th member ✓. Incorrect: COP30 raised climate finance to $1.3T/year by 2035 (not $300B — that was COP29); G7 Kananaskis had NO full communiqué (Trump left early; remaining 6 issued joint statement); SCO 2025 was in Tianjin, China (not Astana — Astana was SCO 2024).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29071,"question_text":"Which country's university (ETH Zürich) published an assessment on India's air superiority in Operation Sindoor 2025?","option_a":"Germany","option_b":"Austria","option_c":"Switzerland","option_d":"Netherlands","correct_answer":"C","explanation":"ETH Zürich (Eidgenössische Technische Hochschule Zürich / Swiss Federal Institute of Technology) is in Switzerland. Its Center for Security Studies (CSS) published analysis on India's air superiority in Operation Sindoor. ETH Zürich is consistently ranked among the world's top universities (alongside MIT, Cambridge, Oxford). Notable alumni: Albert Einstein.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29072,"question_text":"The India-UK FTA (CETA 2025) will come into force in May 2026. What is the current bilateral trade value between India and UK?","option_a":"$20 billion","option_b":"$35 billion","option_c":"$56 billion","option_d":"$80 billion","correct_answer":"C","explanation":"India-UK bilateral trade: $56 billion (as of 2025). Target under CETA: double by 2030 (approx $112 billion). Projected $34 billion/year increase from 2040. India-UK trade: India exports textiles, pharmaceuticals, engineering goods, IT services to UK; UK exports whisky, aerospace, machinery, medical devices to India.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29073,"question_text":"In the context of Iran's nuclear program, uranium enriched to what percentage purity is considered 'near weapons-grade'?","option_a":"20%","option_b":"60%","option_c":"90% (weapons-grade)","option_d":"45%","correct_answer":"C","explanation":"Weapons-grade uranium: 90%+ enrichment. Iran had enriched to 60% purity (near weapons-grade) before the Twelve-Day War (June 2025). Low Enriched Uranium (LEU, <5%): power reactors. HEU (20-90%): research reactors. Weapons-grade (90%+): nuclear weapons. JCPOA had capped Iran's enrichment at 3.67%. The IAEA resolution (June 12, 2025) declaring Iran non-compliant triggered the Twelve-Day War.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29074,"question_text":"The Comprehensive and Progressive Agreement for Trans-Pacific Partnership (CPTPP) — which India has not joined — was signed in 2018 without the USA. Which country chairs CPTPP in 2025?","option_a":"Japan","option_b":"Vietnam","option_c":"Australia","option_d":"Canada","correct_answer":"A","explanation":"Japan chairs CPTPP in 2025. CPTPP (signed 2018) has 11 members: Japan, Canada, Australia, New Zealand, Singapore, Vietnam, Malaysia, Brunei, Mexico, Peru, Chile. UK joined in 2023 as 12th member. India has not joined CPTPP. China applied for membership (2021). CPTPP was originally TPP (Trans-Pacific Partnership) until the USA withdrew in 2017.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29075,"question_text":"Which of the following is CORRECTLY matched — an Indian government scheme with its purpose?","option_a":"MAITRI → maritime training initiative for Indo-Pacific (QUAD)","option_b":"BHISHM → India's coastal surveillance system","option_c":"LeadIT → India-USA clean energy partnership","option_d":"Sagar Bandhu → India's deep-sea mining program","correct_answer":"A","explanation":"MAITRI (Maritime Initiative for Training in the Indo-Pacific) is a QUAD initiative that trains Indo-Pacific coast guards ✓. Incorrect: BHISHM = Bike-mounted Hospital System (portable field hospital — given to Maldives); LeadIT = India-Sweden (NOT India-USA) initiative for heavy industry decarbonization; Sagar Bandhu = India's operation to assist Sri Lanka during Cyclone Ditwah (not a deep-sea program).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29076,"question_text":"South Korea held a snap presidential election on June 3, 2025. Who was the new President-elect who defeated the conservative candidate?","option_a":"Yoon Suk-yeol","option_b":"Han Duck-soo","option_c":"Lee Jae-myung","option_d":"Ahn Cheol-soo","correct_answer":"C","explanation":"Lee Jae-myung (Democratic Party) won South Korea's June 3, 2025 snap presidential election, defeating conservative candidate Han Duck-soo. Lee had previously narrowly lost the 2022 election to Yoon. He also became President as Yoon's Constitutional Court impeachment (April 4, 2025) paved the way. Lee also hosted APEC 2025 in Gyeongju.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29077,"question_text":"In Japan's political system, the PM is selected by both chambers of the National Diet. Sanae Takaichi led which coalition?","option_a":"LDP + Komeito","option_b":"LDP + Japan Innovation Party","option_c":"DPJ + LDP","option_d":"LDP alone (majority)","correct_answer":"B","explanation":"Sanae Takaichi became Japan's PM leading an LDP (Liberal Democratic Party) + Japan Innovation Party coalition. The LDP had traditionally partnered with Komeito, but following the 2025 LDP leadership changes, Takaichi secured the Japan Innovation Party as coalition partner instead. She won the LDP leadership election defeating Shinjirō Koizumi.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29078,"question_text":"The 2026 FIFA World Cup will feature 48 teams for the first time. How many teams played in previous World Cups (since 1998)?","option_a":"24 teams","option_b":"32 teams","option_c":"36 teams","option_d":"40 teams","correct_answer":"B","explanation":"Previous FIFA World Cups (1998-2022) featured 32 teams. The 2026 World Cup (USA-Canada-Mexico) expands to 48 teams — with 16 groups of 3 teams (or 12 groups of 4). India's football team has never qualified for the FIFA World Cup. FIFA World Cup 2022: Qatar (first in Middle East, first in winter); Argentina won (3rd title).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29079,"question_text":"Which Indian city was ranked as the world's most populous urban area in 2025 by the United Nations?","option_a":"Mumbai","option_b":"Delhi","option_c":"Kolkata","option_d":"Bengaluru","correct_answer":"B","explanation":"Delhi (National Capital Region) was ranked as the world's most populous urban area in 2025 by UN Habitat — surpassing Tokyo. Delhi's population: 33+ million in city, 35+ million in NCR. The question mentions Jakarta at 42 million (which was Jakarta Greater area including suburban zones — methodologies differ). UN World Cities Report 2025 confirms Delhi NCR as world's most populated urban area.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29080,"question_text":"WTO Director-General Ngozi Okonjo-Iweala is from which country and represents which milestone? [2025-2026 Rewrite v2]","option_a":"Ghana, first African DG","option_b":"Nigeria, first woman and first African DG of WTO","option_c":"South Africa, first female DG","option_d":"Kenya, first from Sub-Saharan Africa","correct_answer":"B","explanation":"Ngozi Okonjo-Iweala (Nigeria) is WTO DG — first woman AND first African to hold this position (appointed March 2021, re-appointed 2025). She previously served as Nigeria's Finance Minister (twice) and World Bank Managing Director. WTO (World Trade Organization) HQ: Geneva, Switzerland. Founded: 1995 (successor to GATT 1947). WTO has 166 member nations.","folder":"AP_HC","topic":"International_Current_Affairs"},

    # GAP-FILL ADDITIONS 2025-2026 (29081-29100) — New global leaders, multilateral appointments, India bilaterals
    {"id":29081,"question_text":"Tarique Rahman is set to become Bangladesh's Prime Minister after the February 12, 2026 election. His party (BNP) won how many of the declared seats?","option_a":"150 of 297","option_b":"180 of 297","option_c":"209 of 297","option_d":"250 of 297","correct_answer":"C","explanation":"The BNP (Bangladesh Nationalist Party), led by Tarique Rahman, won 209 of 297 declared seats in the February 12, 2026 election (59.88% turnout) — a landslide. Jamaat-e-Islami was principal opposition (68 seats). It was Bangladesh's first election after the 2024 student uprising removed Sheikh Hasina (Awami League). Tarique returned in Dec 2025 after 17 years of exile in London, succeeding his mother Khaleda Zia (died Dec 2025) as BNP leader.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29082,"question_text":"Senior General Min Aung Hlaing was sworn in as Myanmar's 11th President on April 10, 2026. He was elected by parliament with how many votes?","option_a":"300 of 584","option_b":"429 of 584","option_c":"500 of 584","option_d":"550 of 584","correct_answer":"B","explanation":"Min Aung Hlaing — Myanmar's military coup leader since Feb 1, 2021 — was elected the country's 11th President on April 3, 2026 with 429 of 584 votes from the pro-military parliament. Inaugurated April 10, 2026 in Naypyidaw. He stepped down as Tatmadaw Commander-in-Chief on March 30, 2026 to qualify constitutionally. Vice Presidents: Nyo Saw and Nan Ni Ni Aye. Aung San Suu Kyi (NLD) remains imprisoned. Democracy watchdogs decried the election as a farce.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29083,"question_text":"Khaled El-Enany, who took oath as UNESCO Director-General on November 15, 2025, represents which historic milestone?","option_a":"First African DG of UNESCO","option_b":"First DG from an Arab country","option_c":"First DG with Egyptology background","option_d":"First DG elected unanimously","correct_answer":"B","explanation":"Khaled El-Enany (Egypt) was elected UNESCO's 12th Director-General on November 6, 2025 with 172 of 174 votes; took oath November 15, 2025. He is the FIRST DG FROM AN ARAB COUNTRY, and the second from Africa (after Senegal's Amadou Mahtar Mbow, 1974-87). An Egyptologist and Helwan University professor, he served as Egypt's Antiquities/Tourism Minister and led the National Museum of Egyptian Civilization. He succeeded Audrey Azoulay (France).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29084,"question_text":"Shirley Ayorkor Botchwey became Commonwealth Secretary-General on April 1, 2025. Which country and earlier role does she represent?","option_a":"Nigeria — former UN Ambassador","option_b":"Ghana — former Foreign Affairs Minister","option_c":"Kenya — former Justice Minister","option_d":"South Africa — former Trade Minister","correct_answer":"B","explanation":"Shirley Ayorkor Botchwey (Ghana) became the 7th Commonwealth Secretary-General on April 1, 2025 — the FIRST AFRICAN WOMAN to hold this office. She was Ghana's Minister for Foreign Affairs and Regional Integration (Jan 2017 - Jan 2024) and a member of Ghana's National Security Council. Appointed by Commonwealth Heads of Government at CHOGM Apia, Samoa (2024). Priorities: youth/women empowerment, Commonwealth trade revival, climate emergency. She succeeded Patricia Scotland (UK).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29085,"question_text":"Mahmoud Ali Youssouf was elected Chairperson of the African Union Commission on February 15-16, 2025. He is from which country?","option_a":"Chad","option_b":"Ethiopia","option_c":"Djibouti","option_d":"Kenya","correct_answer":"C","explanation":"Mahmoud Ali Youssouf (Djibouti) was elected AU Commission Chairperson on Feb 15-16, 2025 at the 38th AU Summit in Addis Ababa, after 7 rounds of voting. He defeated Madagascar's Richard Randriamandranto and Kenya's Raila Odinga. Youssouf was Djibouti's Foreign Affairs Minister (2005-2025) — a career diplomat fluent in French, English, Arabic. He succeeded Moussa Faki Mahamat (Chad). Deputy: Selma Malika Haddadi (Algeria). 4-year renewable term.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29086,"question_text":"Yuji Iwasawa (Japan) was elected President of the International Court of Justice (ICJ) on March 3, 2025. He succeeded which previous President?","option_a":"Joan Donoghue (USA)","option_b":"Nawaf Salam (Lebanon)","option_c":"Ronny Abraham (France)","option_d":"Peter Tomka (Slovakia)","correct_answer":"B","explanation":"Judge Yuji Iwasawa (Japan) became ICJ President on March 3, 2025, succeeding Nawaf Salam (Lebanon) who resigned to become Lebanon's PM. Iwasawa, ICJ judge since June 2018, was earlier professor of international law at University of Tokyo and chair of the UN Human Rights Committee. His ICJ presidency runs to February 5, 2027. ICJ HQ: Peace Palace, The Hague, Netherlands. Established 1945 — principal judicial organ of the UN.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29087,"question_text":"Antonio Costa (Portugal) became President of the European Council on December 1, 2024. He succeeded which Belgian politician?","option_a":"Herman Van Rompuy","option_b":"Donald Tusk","option_c":"Charles Michel","option_d":"Guy Verhofstadt","correct_answer":"C","explanation":"Antonio Costa (Portugal, former PM 2015-2024) became President of the European Council on Dec 1, 2024 — succeeding Charles Michel (Belgium, 2019-2024). The European Council represents EU heads of state/government. Other EU 'top jobs' renewed in 2024: Ursula von der Leyen (Germany) — re-elected Commission President for 2nd term; Kaja Kallas (Estonia) — EU High Representative for Foreign Affairs and Security. Costa's term: 2.5 years, renewable once.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29088,"question_text":"Mark Rutte became NATO Secretary-General on October 1, 2024. He was previously Prime Minister of which country (longest-serving PM in its history)?","option_a":"Belgium","option_b":"Denmark","option_c":"Netherlands","option_d":"Norway","correct_answer":"C","explanation":"Mark Rutte (Netherlands) — Dutch PM 2010-2024 (longest-serving Dutch PM ever, ~14 years) — became NATO's 14th Secretary-General on Oct 1, 2024, succeeding Jens Stoltenberg (Norway). NATO HQ: Brussels, Belgium. Founded 1949 by Washington Treaty. NATO has 32 members (Finland 2023, Sweden Mar 2024 = latest). Rutte's main challenges: Russia-Ukraine war, supporting Ukraine, US burden-sharing demands under Trump 47, 5% GDP defence spending target.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29089,"question_text":"Mathias Cormann was re-elected OECD Secretary-General for a 2nd 5-year term (2026-2031). He is a former Finance Minister of which country?","option_a":"Germany","option_b":"Australia","option_c":"Canada","option_d":"Belgium","correct_answer":"B","explanation":"Mathias Cormann (Australia) — Australia's former Finance Minister (2013-2020) — was re-elected OECD Secretary-General for his 2nd term (June 1, 2026 - May 31, 2031). He first took office June 1, 2021. OECD (Organisation for Economic Co-operation and Development) HQ: Paris, France. Founded 1961. 38 member countries. Cormann is Belgian-Australian (born Belgium, migrated to Australia). India is an OECD 'Key Partner' (not full member).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29090,"question_text":"Claudia Sheinbaum was sworn in as Mexico's President on October 1, 2024. Which historic milestone does she represent?","option_a":"Youngest Mexican President","option_b":"First woman President of Mexico (and first of Jewish descent)","option_c":"First indigenous Mexican President","option_d":"First President to serve a 4-year term","correct_answer":"B","explanation":"Claudia Sheinbaum (Morena party) was sworn in as Mexico's first female President on October 1, 2024 — also Mexico's first president of Jewish descent. A climate scientist (PhD in energy engineering), she was former Head of Government of Mexico City (2018-2023). She succeeded Andrés Manuel López Obrador (AMLO). Key challenge in 2025-26: managing Trump's tariffs on Mexico (drug trafficking/migration pressure) and the USMCA review.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29091,"question_text":"Prabowo Subianto was sworn in as Indonesia's 8th President on October 20, 2024. He was previously Defence Minister and the running mate in 2024 was the son of the previous president. Who?","option_a":"Joko Widodo Jr.","option_b":"Gibran Rakabuming Raka (son of Jokowi)","option_c":"Megawati's son","option_d":"Anies Baswedan","correct_answer":"B","explanation":"Prabowo Subianto (Gerindra party) was sworn in as Indonesia's 8th President on October 20, 2024. His VP is Gibran Rakabuming Raka, the eldest son of outgoing President Joko Widodo (Jokowi). A controversial Constitutional Court ruling lowered the age requirement allowing 36-year-old Gibran to qualify. Prabowo, ex-Defence Minister (2019-2024) and ex-army general, oversaw Indonesia's January 2025 entry into BRICS as 11th full member.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29092,"question_text":"Anura Kumara Dissanayake (AKD) became Sri Lanka's President in September 2024. His party-coalition NPP won a parliamentary supermajority. NPP stands for:","option_a":"National Patriotic Party","option_b":"National People's Power","option_c":"Nationalist Peace Pact","option_d":"New Progressive Party","correct_answer":"B","explanation":"Anura Kumara Dissanayake (AKD) of the JVP-led NPP (National People's Power) coalition was elected Sri Lanka's 9th Executive President on September 21, 2024. In the November 14, 2024 snap parliamentary election, NPP won a 2/3 supermajority (159/225 seats) — the first true leftist supermajority in Sri Lanka's history. AKD has pursued anti-corruption reforms, IMF programme continuation, and balanced India-China ties. He visited India (Dec 2024) — first foreign visit.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29093,"question_text":"Friedrich Merz visited India on January 12-13, 2026 — his first official Asian visit. How many MoUs/pacts were signed and what was Germany's GSDP funding announcement?","option_a":"10 MoUs, EUR 500 million","option_b":"19 MoUs, EUR 1.24 billion fresh under GSDP","option_c":"25 MoUs, EUR 2 billion","option_d":"15 MoUs, EUR 800 million","correct_answer":"B","explanation":"Chancellor Friedrich Merz's India visit (Jan 12-13, 2026) saw 19 MoUs/agreements signed, including a Defence Industrial Cooperation Roadmap, semiconductor partnership, critical minerals, and a green-ammonia deal (AM Green - Uniper). Germany announced EUR 1.24 billion fresh under GSDP (Green and Sustainable Development Partnership) — part of broader EUR 10 billion commitment. Also: visa-free airport transit for Indians at German airports, battery storage working group, India-Germany skilling centre at Hyderabad NSTI.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29094,"question_text":"Lee Jae-myung made a State Visit to India on April 19-21, 2026 as the first South Korean President to visit since taking office in June 2025. Which major agreement was a centerpiece?","option_a":"India-Korea Nuclear Cooperation Pact","option_b":"Joint Strategic Vision for the India-Republic of Korea Special Strategic Partnership","option_c":"Korea-India Free Trade Agreement signed","option_d":"Korea offers $50 billion infrastructure loan","correct_answer":"B","explanation":"President Lee Jae-myung's India State Visit (April 19-21, 2026) produced the Joint Strategic Vision for the India-Republic of Korea Special Strategic Partnership covering shipbuilding, semiconductors, AI, and arms co-production. Key outcomes: HD Korea Shipbuilding MoU for a greenfield shipyard in Tamil Nadu; India-Korea Digital Bridge launched; talks to upgrade the 2009 India-Korea CEPA; target $54 billion bilateral trade by 2030. Lee was accompanied by First Lady Kim Hea Kyung.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29095,"question_text":"Cyril Ramaphosa retained South Africa's presidency in 2024-2026 by forming a 'Government of National Unity' (GNU). Which party became ANC's key coalition partner after ANC lost its majority for first time since 1994?","option_a":"Economic Freedom Fighters (EFF)","option_b":"Democratic Alliance (DA)","option_c":"Inkatha Freedom Party (IFP)","option_d":"MK Party (uMkhonto we Sizwe)","correct_answer":"B","explanation":"After May 29, 2024 elections — ANC won only 40% (down from 57%), losing its outright majority for the first time since 1994 (end of apartheid). Cyril Ramaphosa formed a Government of National Unity (GNU) with the Democratic Alliance (DA, John Steenhuisen) as the key coalition partner. The GNU also included IFP, Patriotic Alliance, and smaller parties. EFF (Malema) and MK Party (Jacob Zuma) remained in opposition. South Africa chaired G20 in 2025 (Johannesburg Summit Nov 2025).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29096,"question_text":"PM Modi visited Washington DC on February 12-13, 2025 — meeting President Trump in Trump's 2nd term. Which initiative for India-US relations was launched at this summit?","option_a":"QUAD 2.0","option_b":"COMPACT — Catalyzing Opportunities for Military Partnership, Accelerated Commerce & Technology","option_c":"India-US Climate Initiative","option_d":"US-India Free Trade Pact","correct_answer":"B","explanation":"At the Modi-Trump summit in Washington DC (Feb 12-13, 2025), 'COMPACT' (Catalyzing Opportunities for Military Partnership, Accelerated Commerce & Technology) was launched as the new framework for India-US ties replacing iCET. The joint statement included: India to import more US oil/LNG, F-35 fighter jet offer, target $500 billion bilateral trade by 2030 ('Mission 500'), TRUST initiative (Tech for Strategic Trade), and extradition of 26/11 Mumbai attack accused Tahawwur Rana to India (executed in 2025).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29097,"question_text":"UAE Vice President and PM Sheikh Mohammed bin Rashid Al Maktoum made a state visit to India in January 2026. He is also the ruler of which emirate?","option_a":"Abu Dhabi","option_b":"Dubai","option_c":"Sharjah","option_d":"Ras Al Khaimah","correct_answer":"B","explanation":"Sheikh Mohammed bin Rashid Al Maktoum is Vice President & Prime Minister of the UAE (since 2006) AND the Ruler of Dubai (since 2006). He visited India in January 2026 to deepen India-UAE Comprehensive Strategic Partnership (CEPA in force since May 2022). UAE President: Sheikh Mohamed bin Zayed Al Nahyan (MBZ — Abu Dhabi ruler since 2022). UAE was a chief guest at India's 2024 Republic Day. UAE is India's 3rd largest trade partner (~$85 billion).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29098,"question_text":"Ajay Banga continued as President of the World Bank Group through 2025-2026. He is the first person of Indian origin to head the World Bank. He took office in:","option_a":"April 2022","option_b":"June 2023","option_c":"January 2024","option_d":"March 2025","correct_answer":"B","explanation":"Ajay Banga (Indian-American) became the 14th President of the World Bank Group on June 2, 2023 — first Indian-origin and first naturalized American (Sikh) to lead the World Bank. Former CEO of Mastercard. His 5-year term runs to 2028. World Bank HQ: Washington DC. India is World Bank's largest cumulative borrower. Compare: Kristalina Georgieva (Bulgaria) — IMF Managing Director (re-elected for 2nd term, 2024-2029). Both Bretton Woods institutions founded 1944.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29099,"question_text":"In a major Aug 2025 Trump executive action, the US imposed a 50% reciprocal tariff on Indian goods citing two specific grievances. Which were they?","option_a":"India's currency manipulation and farm subsidies","option_b":"India's Russian oil purchases and trade barriers","option_c":"India's data localization and tech regulations","option_d":"India's military exports to Iran","correct_answer":"B","explanation":"Trump's executive order (Aug 6, 2025) imposed 50% reciprocal tariffs on Indian goods, citing: (1) India's continued purchase of Russian crude oil (~35-40% of India's imports post-Ukraine war) and (2) India's perceived 'high tariff barriers' against US goods. Effective Aug 27, 2025. India responded with diplomatic engagement, and an India-US trade deal was being negotiated in 2025-26 alongside Mission 500 ($500B bilateral trade by 2030).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":29100,"question_text":"Match: Which combination of 2025-2026 multilateral appointments is FULLY CORRECT?","option_a":"UNESCO DG = El-Enany (Egypt); NATO SG = Rutte (Netherlands); AU Commission = Youssouf (Djibouti); Commonwealth SG = Botchwey (Ghana)","option_b":"UNESCO DG = Azoulay (France); NATO SG = Stoltenberg (Norway); AU = Faki (Chad); Commonwealth = Scotland (UK)","option_c":"UNESCO DG = Botchwey (Ghana); NATO SG = Costa (Portugal); AU = Rutte; Commonwealth = El-Enany","option_d":"UNESCO DG = El-Enany; NATO SG = Costa; AU = Botchwey; Commonwealth = Rutte","correct_answer":"A","explanation":"Correct (Option A): UNESCO DG = Khaled El-Enany (Egypt, since Nov 15, 2025); NATO SG = Mark Rutte (Netherlands, since Oct 1, 2024); AU Commission Chair = Mahmoud Ali Youssouf (Djibouti, since Feb 2025); Commonwealth SG = Shirley Botchwey (Ghana, since Apr 1, 2025). Option B lists the outgoing predecessors. Also relevant 2024-26: ICJ President = Iwasawa (Japan, Mar 2025); European Council President = Costa (Portugal, Dec 2024); EC President = von der Leyen (2nd term).","folder":"AP_HC","topic":"International_Current_Affairs"},
]


def seed():
    if USE_POSTGRES:
        import psycopg2
        conn = psycopg2.connect(DATABASE_URL)
        conn.autocommit = False
        cur = conn.cursor()
        ph = "%s"
        delete_sql = "DELETE FROM questions WHERE id >= %s AND id <= %s"
        insert_sql = """
            INSERT INTO questions
              (id, question_text, option_a, option_b, option_c, option_d,
               correct_answer, explanation, folder, topic)
            VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
            ON CONFLICT (id) DO NOTHING
        """
    else:
        conn = sqlite3.connect(
            os.path.join(os.path.dirname(__file__), "database.db")
        )
        cur = conn.cursor()
        ph = "?"
        delete_sql = "DELETE FROM questions WHERE id >= ? AND id <= ?"
        insert_sql = """
            INSERT OR IGNORE INTO questions
              (id, question_text, option_a, option_b, option_c, option_d,
               correct_answer, explanation, folder, topic)
            VALUES (?,?,?,?,?,?,?,?,?,?)
        """

    # Force-refresh: delete stale 2024 data in this range (now extended to 29100)
    cur.execute(delete_sql, (29001, 29100))

    for q in INTL_EVENTS_MCQS:
        cur.execute(insert_sql, (
            q["id"], q["question_text"],
            q["option_a"], q["option_b"], q["option_c"], q["option_d"],
            q["correct_answer"], q["explanation"],
            q["folder"], q["topic"],
        ))

    conn.commit()
    conn.close()
    print(f"[seed_intl_events_mcq] {len(INTL_EVENTS_MCQS)} Intl Events 2025-2026 MCQs seeded (IDs 29001-29100).")


if __name__ == "__main__":
    seed()
