"""
seed_conflicts_mcq.py
80 GKToday-style MCQs — Topic: International_Current_Affairs
Sub-topic: Global Conflicts & Geopolitics 2025-2026
Folder: AP_HC | IDs: 22001-22080
"""

import os, sqlite3

DATABASE_URL = os.environ.get("DATABASE_URL", "")
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)
USE_POSTGRES = bool(DATABASE_URL)

CONFLICTS_MCQS = [
    {
        "id": 22001,
        "question_text": "On which date did India launch 'Operation Sindoor' against terrorist camps in Pakistan and PoK?",
        "option_a": 'May 7, 2025',
        "option_b": 'April 22, 2025',
        "option_c": 'May 15, 2025',
        "option_d": 'March 7, 2025',
        "correct_answer": 'A',
        "explanation": "Operation Sindoor was launched on May 7, 2025 — India's precision missile strikes on 9 terrorist camps across Pakistan and Pakistan-Occupied Kashmir.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22002,
        "question_text": 'The Pahalgam terror attack (April 22, 2025) occurred at which specific location in Jammu & Kashmir?',
        "option_a": 'Amarnath shrine',
        "option_b": 'Gulmarg ski resort',
        "option_c": 'Baisaran meadow, Pahalgam',
        "option_d": 'Dal Lake, Srinagar',
        "correct_answer": 'C',
        "explanation": "The attack occurred at Baisaran meadow near Pahalgam, J&K — 26 tourists (mostly Hindu) were killed. Baisaran is sometimes called 'Mini Switzerland of India'.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22003,
        "question_text": 'How many terrorist camps were targeted by India during Operation Sindoor?',
        "option_a": '5',
        "option_b": '7',
        "option_c": '9',
        "option_d": '12',
        "correct_answer": 'C',
        "explanation": 'Operation Sindoor targeted 9 terrorist camps — located in both Pakistan and Pakistan-Occupied Kashmir (PoK), targeting Lashkar-e-Taiba and Jaish-e-Mohammed infrastructure.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22004,
        "question_text": "What is the symbolic significance of the name 'Operation Sindoor'?",
        "option_a": 'Reference to red colour of Indian flag',
        "option_b": 'Named after a river in PoK',
        "option_c": 'Sindoor (vermilion) worn by married Hindu women — tribute to widows of Pahalgam victims',
        "option_d": 'Named after an Indian missile system',
        "correct_answer": 'C',
        "explanation": "'Sindoor' (vermilion) is worn by married Hindu women. The name symbolised the blood of the widows whose husbands were killed in the Pahalgam terror attack on April 22, 2025.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22005,
        "question_text": 'Which terror group was directly responsible for the Pahalgam attack of April 22, 2025?',
        "option_a": 'Jaish-e-Mohammed',
        "option_b": 'The Resistance Front (TRF) — a Lashkar-e-Taiba proxy',
        "option_c": 'Al-Qaeda',
        "option_d": 'ISIS-K',
        "correct_answer": 'B',
        "explanation": 'The Resistance Front (TRF), a shadow group of Lashkar-e-Taiba (LeT), claimed responsibility for the Pahalgam attack. Both LeT and JeM camps were targeted in Operation Sindoor.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22006,
        "question_text": 'How many tourists were killed in the Pahalgam terror attack on April 22, 2025?',
        "option_a": '16',
        "option_b": '21',
        "option_c": '26',
        "option_d": '32',
        "correct_answer": 'C',
        "explanation": '26 tourists, mostly Hindu, were killed in the Pahalgam terror attack at Baisaran meadow, Jammu & Kashmir on April 22, 2025.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22007,
        "question_text": 'Which water treaty did India suspend with Pakistan following the Pahalgam attack?',
        "option_a": 'Ganges Water Treaty',
        "option_b": 'Indus Waters Treaty (1960)',
        "option_c": 'Rann of Kutch Agreement',
        "option_d": 'Shimla Agreement',
        "correct_answer": 'B',
        "explanation": "India suspended the Indus Waters Treaty (1960) as a diplomatic response to the Pahalgam attack. The treaty was originally signed between Nehru and Pakistan's Ayub Khan.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22008,
        "question_text": 'Which border crossing did India close following the Pahalgam terror attack in 2025?',
        "option_a": 'Nathu La (Sikkim)',
        "option_b": 'Wagah-Attari (Punjab)',
        "option_c": 'Moreh (Manipur)',
        "option_d": 'Lipulekh (Uttarakhand)',
        "correct_answer": 'B',
        "explanation": 'India closed the Wagah-Attari border crossing in Punjab as part of diplomatic measures following the April 22, 2025 Pahalgam terror attack.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22009,
        "question_text": 'In which year was the Indus Waters Treaty originally signed between India and Pakistan?',
        "option_a": '1947',
        "option_b": '1955',
        "option_c": '1960',
        "option_d": '1972',
        "correct_answer": 'C',
        "explanation": 'The Indus Waters Treaty was signed in 1960 between Indian PM Jawaharlal Nehru and Pakistani President Ayub Khan, with World Bank as guarantor. India suspended it in 2025 after the Pahalgam attack.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22010,
        "question_text": 'Operation Sindoor (May 2025) targeted camps of which terror organisations?',
        "option_a": 'Al-Qaeda, ISIS, and Taliban',
        "option_b": 'Lashkar-e-Taiba (LeT), Jaish-e-Mohammed (JeM), and Hizbul Mujahideen (HuM)',
        "option_c": 'Haqqani Network, TTP, and JeM',
        "option_d": 'LeT, JeM, and Al-Qaeda',
        "correct_answer": 'B',
        "explanation": 'Operation Sindoor targeted THREE groups: LeT (Markaz Taiba/Muridke, Shawai Nallah/Muzaffarabad, Barnala/Bhimber), JeM (Bahawalpur HQ, Kotli, Muzaffarabad), and Hizbul Mujahideen (Sialkot, Kotli). 9 camps total.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22011,
        "question_text": 'In which region of Pakistan/PoK did Operation Sindoor strikes take place? (Choose most accurate)',
        "option_a": 'Only in PoK',
        "option_b": 'Only inside Pakistan',
        "option_c": 'Both in Pakistan and Pakistan-Occupied Kashmir (PoK)',
        "option_d": 'In Balochistan only',
        "correct_answer": 'C',
        "explanation": 'Operation Sindoor strikes hit 9 camps located BOTH inside Pakistan and Pakistan-Occupied Kashmir (PoK) — not limited to PoK alone.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22012,
        "question_text": 'Which statement about Operation Sindoor is CORRECT?',
        "option_a": 'India used nuclear weapons',
        "option_b": 'India conducted precision missile strikes on terrorist infrastructure',
        "option_c": 'India sent ground troops into Pakistan',
        "option_d": 'The operation was joint India-USA',
        "correct_answer": 'B',
        "explanation": 'Operation Sindoor was a precision conventional (non-nuclear) missile strike operation targeting terrorist camps. India did NOT deploy ground troops or nuclear weapons.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22013,
        "question_text": 'On which date did Russia begin its full-scale invasion of Ukraine?',
        "option_a": 'February 24, 2021',
        "option_b": 'February 24, 2022',
        "option_c": 'March 1, 2022',
        "option_d": 'April 7, 2022',
        "correct_answer": 'B',
        "explanation": "Russia launched its full-scale invasion of Ukraine on February 24, 2022. Russia called it a 'Special Military Operation.' It triggered Europe's largest land war since WWII.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22014,
        "question_text": 'Which four Ukrainian regions did Russia claim to annex in September 2022?',
        "option_a": 'Kyiv, Kharkiv, Odessa, Crimea',
        "option_b": 'Donetsk, Luhansk, Zaporizhzhia, Kherson',
        "option_c": 'Mariupol, Dnipro, Lviv, Mykolaiv',
        "option_d": 'Donbas, Crimea, Odessa, Kherson',
        "correct_answer": 'B',
        "explanation": 'Russia illegally annexed Donetsk, Luhansk, Zaporizhzhia, and Kherson in Sept 2022. Note: Crimea was already annexed in 2014. The annexations are not internationally recognised.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22015,
        "question_text": "Ukraine's surprise military incursion into Russia's Kursk Oblast in August 2024 was significant because:",
        "option_a": "It was Ukraine's first major offensive",
        "option_b": 'It was the first time since WWII that foreign troops entered Russian soil',
        "option_c": 'It recaptured all of eastern Ukraine',
        "option_d": 'It triggered NATO direct intervention',
        "correct_answer": 'B',
        "explanation": "Ukraine's Kursk incursion (Aug 2024) was historically significant — the first time since World War II that foreign troops had entered and held Russian sovereign territory.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22016,
        "question_text": 'Which country sent approximately 10,000 troops to support Russia in the Ukraine war (confirmed Oct 2024)?',
        "option_a": 'China',
        "option_b": 'Iran',
        "option_c": 'North Korea (DPRK)',
        "option_d": 'Belarus',
        "correct_answer": 'C',
        "explanation": 'North Korea (DPRK) sent approximately 10,000 troops to assist Russia in the Ukraine war, confirmed by US, NATO, and Ukraine in October 2024. Russia and DPRK signed a mutual defence treaty in June 2024.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22017,
        "question_text": "The Zaporizhzhia Nuclear Power Plant (Europe's largest) in Ukraine is currently:",
        "option_a": 'Controlled by Ukraine',
        "option_b": 'Destroyed by Russian strikes',
        "option_c": 'Under Russian military control',
        "option_d": 'Under UN administration',
        "correct_answer": 'C',
        "explanation": "The Zaporizhzhia Nuclear Power Plant — Europe's largest — has been under Russian military control since March 2022, raising international safety concerns throughout the war.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22018,
        "question_text": "What was Russia's oil price cap set by G7 nations?",
        "option_a": '$40 per barrel',
        "option_b": '$50 per barrel',
        "option_c": '$60 per barrel',
        "option_d": '$80 per barrel',
        "correct_answer": 'C',
        "explanation": "G7 nations set a $60 per barrel price cap on Russian oil exports in December 2022 to limit Russia's war revenues, while allowing Russia to sell oil at or below that price.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22019,
        "question_text": "Russia-DPRK 'Comprehensive Strategic Partnership' mutual defence treaty was signed in:",
        "option_a": 'March 2023',
        "option_b": 'October 2023',
        "option_c": 'June 2024',
        "option_d": 'January 2025',
        "correct_answer": 'C',
        "explanation": "During Putin's visit to Pyongyang (North Korea) in June 2024, Russia and DPRK signed the Comprehensive Strategic Partnership mutual defence treaty — deepening military cooperation.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22020,
        "question_text": 'Which Iranian drone type was extensively used by Russia against Ukrainian cities?',
        "option_a": 'Shahed',
        "option_b": 'Karrar',
        "option_c": 'Mohajer',
        "option_d": 'Ababil',
        "correct_answer": 'A',
        "explanation": 'Russia used Iranian-made Shahed drones (one-way attack drones) extensively against Ukrainian cities and infrastructure. Iran initially denied supplying them but evidence was conclusive.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22021,
        "question_text": 'On which date did Hamas launch its surprise attack on Israel, triggering the Gaza War?',
        "option_a": 'October 7, 2022',
        "option_b": 'October 7, 2023',
        "option_c": 'November 7, 2023',
        "option_d": 'September 7, 2023',
        "correct_answer": 'B',
        "explanation": 'Hamas launched a massive surprise attack on Israel on October 7, 2023 — killing ~1,200 Israelis and taking ~250 hostages. It was the deadliest attack on Jews since the Holocaust.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22022,
        "question_text": 'The Gaza ceasefire (Phase 1) of January 2025 was brokered by which countries?',
        "option_a": 'USA and Saudi Arabia',
        "option_b": 'Qatar and Egypt',
        "option_c": 'Turkey and Jordan',
        "option_d": 'UN and France',
        "correct_answer": 'B',
        "explanation": 'The Gaza ceasefire Phase 1 (January 19, 2025) was brokered by Qatar and Egypt, with US mediation. It lasted 6 weeks — 33 hostages released in exchange for ~1,900 Palestinian prisoners.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22023,
        "question_text": 'Which country filed a genocide case against Israel at the International Court of Justice (ICJ) in 2024?',
        "option_a": 'Turkey',
        "option_b": 'Iran',
        "option_c": 'South Africa',
        "option_d": 'Indonesia',
        "correct_answer": 'C',
        "explanation": "South Africa filed a genocide case against Israel at the ICJ in January 2024, alleging Israel's military actions in Gaza violated the Genocide Convention. The ICJ ordered Israel to prevent genocide and allow aid.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22024,
        "question_text": 'Hamas political leader Ismail Haniyeh was assassinated in which city in July 2024?',
        "option_a": 'Gaza City',
        "option_b": 'Doha',
        "option_c": 'Tehran',
        "option_d": 'Beirut',
        "correct_answer": 'C',
        "explanation": 'Hamas political leader Ismail Haniyeh was assassinated in Tehran, Iran on July 31, 2024. Israel was widely believed responsible. His successor as Hamas political chief was Yahya Sinwar (who was also killed in Oct 2024).',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22025,
        "question_text": 'Hamas military chief Yahya Sinwar — the architect of the October 7 attack — was killed in:',
        "option_a": 'July 2024 in Beirut',
        "option_b": 'August 2024 in Rafah',
        "option_c": 'October 2024 in Gaza',
        "option_d": 'January 2025 in Egypt',
        "correct_answer": 'C',
        "explanation": 'Yahya Sinwar, Hamas military chief and mastermind of the Oct 7 attack, was killed by Israeli forces in Gaza in October 2024.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22026,
        "question_text": 'Which Palestinian group governs the West Bank (distinct from Hamas which governs Gaza)?',
        "option_a": 'Fatah / Palestinian Authority (PA)',
        "option_b": 'Islamic Jihad',
        "option_c": 'PFLP',
        "option_d": 'Hezbollah',
        "correct_answer": 'A',
        "explanation": 'The West Bank is governed by the Palestinian Authority (PA), controlled by Fatah party under President Mahmoud Abbas. Gaza has been controlled by Hamas since 2007. These are two distinct entities.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22027,
        "question_text": 'Hezbollah chief Hassan Nasrallah was killed by Israel in which month/year?',
        "option_a": 'July 2024',
        "option_b": 'August 2024',
        "option_c": 'September 2024',
        "option_d": 'November 2024',
        "correct_answer": 'C',
        "explanation": 'Hezbollah Secretary-General Hassan Nasrallah was killed in an Israeli airstrike in Beirut on September 27, 2024 — a major blow to Hezbollah after decades of leadership.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22028,
        "question_text": 'The US-brokered ceasefire between Israel and Hezbollah (Lebanon) was announced on:',
        "option_a": 'September 27, 2024',
        "option_b": 'October 15, 2024',
        "option_c": 'November 27, 2024',
        "option_d": 'January 19, 2025',
        "correct_answer": 'C',
        "explanation": 'A US-brokered 60-day ceasefire between Israel and Hezbollah in Lebanon was announced on November 27, 2024, following months of cross-border strikes after the Oct 7 attack.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22029,
        "question_text": 'The ICC issued arrest warrants for Israeli PM Benjamin Netanyahu in November 2024 for alleged:',
        "option_a": 'Corruption and financial crimes',
        "option_b": 'War crimes in Gaza',
        "option_c": 'Nuclear treaty violations',
        "option_d": 'Cyber attacks on Iran',
        "correct_answer": 'B',
        "explanation": 'The International Criminal Court (ICC) issued arrest warrants for PM Netanyahu and ex-Defence Minister Yoav Gallant in November 2024 for alleged war crimes and crimes against humanity in Gaza.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22030,
        "question_text": 'How many hostages did Hamas take during the October 7, 2023 attack on Israel?',
        "option_a": '~100',
        "option_b": '~150',
        "option_c": '~250',
        "option_d": '~400',
        "correct_answer": 'C',
        "explanation": 'Hamas took approximately 250 hostages during the October 7, 2023 attack. They were taken to Gaza. Some were released in ceasefire deals; others were killed or remained captive.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22031,
        "question_text": "On which date did Bashar al-Assad's regime fall in Syria?",
        "option_a": 'November 26, 2024',
        "option_b": 'December 8, 2024',
        "option_c": 'January 1, 2025',
        "option_d": 'October 7, 2024',
        "correct_answer": 'B',
        "explanation": "Bashar al-Assad's regime collapsed on December 8, 2024, when rebel group HTS captured Damascus. Assad fled to Russia, ending 54 years of Assad family rule over Syria.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22032,
        "question_text": 'Which rebel group led by Ahmad al-Sharaa (Abu Mohammad al-Jolani) captured Damascus in December 2024?',
        "option_a": 'Free Syrian Army (FSA)',
        "option_b": 'ISIS (Islamic State)',
        "option_c": 'HTS — Hayat Tahrir al-Sham',
        "option_d": 'Kurdish SDF',
        "correct_answer": 'C',
        "explanation": "HTS (Hayat Tahrir al-Sham), led by Ahmad al-Sharaa (also known as Abu Mohammad al-Jolani), swept through Syria and captured Damascus on December 8, 2024, ending Assad's rule.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22033,
        "question_text": 'To which country did Bashar al-Assad flee after his regime fell in December 2024?',
        "option_a": 'Turkey',
        "option_b": 'UAE',
        "option_c": 'Russia',
        "option_d": 'Iran',
        "correct_answer": 'C',
        "explanation": "Assad fled to Russia after Damascus fell on December 8, 2024. Russia had been Assad's main military backer throughout the civil war (since 2015).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22034,
        "question_text": "How long did the Assad family rule Syria (combining Hafez and Bashar al-Assad's tenures)?",
        "option_a": '30 years',
        "option_b": '40 years',
        "option_c": '54 years',
        "option_d": '62 years',
        "correct_answer": 'C',
        "explanation": 'Hafez al-Assad ruled Syria from 1971–2000 (29 years); Bashar al-Assad from 2000–2024 (24 years) = total ~54 years of Assad family rule.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22035,
        "question_text": 'Iran launched its first-ever direct attack on Israel on which date?',
        "option_a": 'March 13, 2024',
        "option_b": 'April 13-14, 2024',
        "option_c": 'October 7, 2024',
        "option_d": 'January 1, 2025',
        "correct_answer": 'B',
        "explanation": 'Iran launched its first-ever direct attack on Israel on April 13-14, 2024 — firing 300+ drones and missiles (mostly intercepted). Israel retaliated on April 19, 2024.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22036,
        "question_text": "Who became Iran's President after Ebrahim Raisi died in a helicopter crash in May 2024?",
        "option_a": 'Ali Khamenei',
        "option_b": 'Hassan Rouhani',
        "option_c": 'Masoud Pezeshkian',
        "option_d": 'Mohsen Rezaei',
        "correct_answer": 'C',
        "explanation": "Masoud Pezeshkian won Iran's snap presidential election in July 2024 after President Ebrahim Raisi died in a helicopter crash near the Azerbaijan border on May 19, 2024.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22037,
        "question_text": "Iran's uranium enrichment level (as of 2024-25) stands at approximately:",
        "option_a": '20%',
        "option_b": '40%',
        "option_c": '60%',
        "option_d": '90%',
        "correct_answer": 'C',
        "explanation": 'Iran has enriched uranium to ~60% purity as of 2024-25. Weapons-grade uranium requires ~90%. The JCPOA (2015 Iran nuclear deal) limited enrichment to 3.67% — US withdrew from JCPOA in 2018 under Trump.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22038,
        "question_text": "The JCPOA (Joint Comprehensive Plan of Action) — Iran's nuclear deal — was abandoned by the USA in which year?",
        "option_a": '2016',
        "option_b": '2017',
        "option_c": '2018',
        "option_d": '2019',
        "correct_answer": 'C',
        "explanation": "President Trump withdrew the USA from JCPOA in May 2018, calling it a 'bad deal.' This led to Iran gradually exceeding JCPOA limits on uranium enrichment and centrifuge use.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22039,
        "question_text": 'South Korean President Yoon Suk-yeol declared martial law on Dec 3, 2024. What was the sequence of events?',
        "option_a": 'Military backed him; he remained in power for 3 months',
        "option_b": 'He resigned voluntarily the next morning',
        "option_c": 'National Assembly lifted martial law within 6 hours; impeached Dec 14; arrested Jan 15, 2025; sentenced to life Feb 2026',
        "option_d": 'ICC issued arrest warrant against him',
        "correct_answer": 'C',
        "explanation": 'Timeline: Dec 3, 2024 — Yoon declared martial law at 22:27. Within 6 hours National Assembly voted to lift it. Dec 14 — impeached by National Assembly. Jan 15, 2025 — arrested. Apr 4, 2025 — Constitutional Court upheld removal. Feb 19, 2026 — sentenced to life in prison for insurrection (first South Korean president convicted).',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22040,
        "question_text": "Russia and North Korea (DPRK) signed a 'Comprehensive Strategic Partnership' mutual defence treaty in:",
        "option_a": 'March 2023, Seoul',
        "option_b": 'June 2024, Pyongyang',
        "option_c": 'October 2024, Moscow',
        "option_d": 'January 2025, Beijing',
        "correct_answer": 'B',
        "explanation": "During Putin's visit to Pyongyang in June 2024, Russia and DPRK signed the Comprehensive Strategic Partnership treaty with a mutual defence clause — deepening their military alliance.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22041,
        "question_text": "North Korea's Hwasong-18 is classified as what type of weapon?",
        "option_a": 'Submarine-launched cruise missile',
        "option_b": 'Solid-fuel Intercontinental Ballistic Missile (ICBM)',
        "option_c": 'Hypersonic glide vehicle',
        "option_d": 'Nuclear torpedo',
        "correct_answer": 'B',
        "explanation": "Hwasong-18 is North Korea's solid-fuel ICBM, tested in 2023. Solid-fuel ICBMs are more dangerous as they can be launched faster (no fuelling time) and are harder to detect.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22042,
        "question_text": "Kim Jong-un in January 2024 declared which country North Korea's 'principal enemy', scrapping reunification policy?",
        "option_a": 'USA',
        "option_b": 'Japan',
        "option_c": 'South Korea',
        "option_d": 'China',
        "correct_answer": 'C',
        "explanation": "Kim Jong-un in January 2024 designated South Korea as DPRK's 'principal enemy' and abandoned the long-standing reunification policy, calling it futile. He also ordered the demolition of the Reunification Arch in Pyongyang.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22043,
        "question_text": 'Approximately how many North Korean troops were sent to assist Russia in the Ukraine war (2024)?',
        "option_a": '1,000',
        "option_b": '5,000',
        "option_c": '10,000',
        "option_d": '50,000',
        "correct_answer": 'C',
        "explanation": 'Approximately 10,000 North Korean troops were deployed to support Russia in the Ukraine war — confirmed by the USA, NATO, South Korea, and Ukraine in October 2024.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22044,
        "question_text": 'What is the official/full name of the Houthi movement in Yemen?',
        "option_a": 'Islamic Front for Yemen',
        "option_b": 'Ansar Allah',
        "option_c": 'Jamaat al-Houthi',
        "option_d": 'Yemen Liberation Army',
        "correct_answer": 'B',
        "explanation": "The Houthis' official name is 'Ansar Allah' (Supporters of God). They control Sana'a and much of northwest Yemen. They are backed by Iran and have been fighting a Saudi-led coalition since 2015.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22045,
        "question_text": 'The Bab-el-Mandeb strait, targeted by Houthi attacks, connects:',
        "option_a": 'Persian Gulf and Arabian Sea',
        "option_b": 'Red Sea and Gulf of Aden',
        "option_c": 'Mediterranean Sea and Red Sea',
        "option_d": 'Gulf of Oman and Indian Ocean',
        "correct_answer": 'B',
        "explanation": "Bab-el-Mandeb (Gate of Tears) connects the Red Sea to the Gulf of Aden — one of the world's most critical shipping chokepoints. Houthi attacks here disrupted ~12% of global trade.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22046,
        "question_text": 'Ships avoiding Houthi attacks on the Red Sea were rerouted via which alternative?',
        "option_a": 'Suez Canal via a new lane',
        "option_b": 'Strait of Hormuz',
        "option_c": 'Cape of Good Hope (South Africa)',
        "option_d": 'Malacca Strait',
        "correct_answer": 'C',
        "explanation": 'Ships rerouted via Cape of Good Hope (southern tip of South Africa) to avoid the Houthi-threatened Red Sea. This added ~10-14 days to voyages and significantly raised shipping costs globally.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22047,
        "question_text": 'The US-led naval operation to protect Red Sea shipping from Houthi attacks was called:',
        "option_a": 'Operation Guardian of the Gulf',
        "option_b": 'Operation Prosperity Guardian',
        "option_c": 'Operation Red Shield',
        "option_d": 'Operation Maritime Dawn',
        "correct_answer": 'B',
        "explanation": "The US launched 'Operation Prosperity Guardian' in December 2023 — a multinational naval coalition to protect commercial ships in the Red Sea from Houthi attacks.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22048,
        "question_text": "Yemen's internationally recognised government is based in which city?",
        "option_a": "Sana'a",
        "option_b": 'Taiz',
        "option_c": 'Aden',
        "option_d": 'Marib',
        "correct_answer": 'C',
        "explanation": "Yemen's internationally recognised government (Saudi-backed) is based in Aden. Sana'a (the capital) is controlled by the Houthis (Ansar Allah) since 2015.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22049,
        "question_text": "China's territorial claim over the South China Sea is represented by which concept/line?",
        "option_a": 'Seven-Dash Line',
        "option_b": 'Nine-Dash Line',
        "option_c": 'Ten-Dash Line',
        "option_d": 'Maritime Sovereignty Boundary',
        "correct_answer": 'B',
        "explanation": "China claims ~90% of the South China Sea through the 'Nine-Dash Line.' This claim was rejected by the Permanent Court of Arbitration (PCA) in 2016 in a case filed by the Philippines.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22050,
        "question_text": 'The BRP Sierra Madre at Second Thomas Shoal is a:',
        "option_a": 'Chinese coast guard vessel',
        "option_b": 'US military ship on patrol',
        "option_c": 'Philippine warship deliberately grounded as a territorial outpost',
        "option_d": 'UN humanitarian ship',
        "correct_answer": 'C',
        "explanation": 'BRP Sierra Madre is a Philippine warship deliberately grounded at Second Thomas Shoal (Ayungin Shoal) in 1999 to assert Philippine sovereignty. Philippines regularly resupplies it; China blocks these missions.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22051,
        "question_text": 'Which treaty obligates the USA to defend the Philippines against armed attack in the South China Sea?',
        "option_a": 'Manila Pact',
        "option_b": 'US-Philippines Mutual Defense Treaty',
        "option_c": 'SEATO Agreement',
        "option_d": 'AUKUS extension',
        "correct_answer": 'B',
        "explanation": 'The US-Philippines Mutual Defense Treaty (1951) — reaffirmed in 2023 — commits the USA to defend the Philippines if attacked in the South China Sea, including at Second Thomas Shoal.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22052,
        "question_text": "Taiwan's President elected in January 2024 is:",
        "option_a": 'Tsai Ing-wen',
        "option_b": 'Ma Ying-jeou',
        "option_c": 'Lai Ching-te',
        "option_d": 'William Lai Qingde',
        "correct_answer": 'C',
        "explanation": "Lai Ching-te (also written as William Lai) was elected Taiwan's President in January 2024 and inaugurated in May 2024. He is seen as pro-Taiwan independence, prompting Chinese military drills.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22053,
        "question_text": 'AUKUS — the security partnership between Australia, UK, and USA — primarily involves:',
        "option_a": 'Nuclear-armed submarines for Australia',
        "option_b": 'Nuclear-powered (non-nuclear armed) submarines for Australia',
        "option_c": 'Joint nuclear weapons development',
        "option_d": 'Space weapons cooperation only',
        "correct_answer": 'B',
        "explanation": 'AUKUS (formed Sept 2021) involves providing Australia with nuclear-POWERED submarines (conventionally armed — no nuclear weapons). France lost its $90 billion submarine contract with Australia due to AUKUS.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22054,
        "question_text": 'How many members does NATO have as of 2024?',
        "option_a": '28',
        "option_b": '30',
        "option_c": '31',
        "option_d": '32',
        "correct_answer": 'D',
        "explanation": 'NATO has 32 members as of March 2024, when Sweden joined as the 32nd member. Finland joined in April 2023 as the 31st member.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22055,
        "question_text": 'Finland joined NATO as the 31st member in:',
        "option_a": 'February 2022',
        "option_b": 'April 2023',
        "option_c": 'March 2024',
        "option_d": 'June 2024',
        "correct_answer": 'B',
        "explanation": 'Finland joined NATO on April 4, 2023 as the 31st member, ending its post-WWII neutrality and adding a 1,340 km border with Russia to the NATO alliance.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22056,
        "question_text": 'Sweden joined NATO as the 32nd member, ending how many years of military neutrality?',
        "option_a": '75 years',
        "option_b": '100 years',
        "option_c": '150 years',
        "option_d": '200+ years',
        "correct_answer": 'D',
        "explanation": 'Sweden joined NATO on March 7, 2024 as the 32nd member, ending over 200 years of military neutrality (since the Napoleonic Wars era).',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22057,
        "question_text": 'Who is the current NATO Secretary-General (as of late 2024)?',
        "option_a": 'Jens Stoltenberg',
        "option_b": 'Mark Rutte',
        "option_c": 'Josep Borrell',
        "option_d": 'Ursula von der Leyen',
        "correct_answer": 'B',
        "explanation": 'Mark Rutte (former Dutch Prime Minister) became NATO Secretary-General in October 2024, succeeding Jens Stoltenberg (Norway) who served from 2014–2024.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22058,
        "question_text": 'The NATO Summit at The Hague (June 2025) agreed to increase defence spending target to what percentage of GDP?',
        "option_a": '2%',
        "option_b": '3%',
        "option_c": '4%',
        "option_d": '5%',
        "correct_answer": 'D',
        "explanation": 'The NATO The Hague Summit (June 2025) agreed to raise the defence spending target from 2% to 5% of GDP — reflecting the heightened security environment due to Russia-Ukraine war and other threats.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22059,
        "question_text": 'Which country will host the NATO Summit in 2026?',
        "option_a": 'Poland',
        "option_b": 'UK',
        "option_c": 'Turkey',
        "option_d": 'Germany',
        "correct_answer": 'C',
        "explanation": 'Turkey will host the 2026 NATO Summit, as decided at the The Hague Summit in 2025.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22060,
        "question_text": 'AUKUS was announced in September 2021. Which country lost a major submarine contract due to AUKUS?',
        "option_a": 'Germany',
        "option_b": 'Japan',
        "option_c": 'France',
        "option_d": 'Spain',
        "correct_answer": 'C',
        "explanation": 'France lost a $90 billion submarine contract with Australia when AUKUS was formed in September 2021. France recalled its ambassadors from Washington and Canberra in protest.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22061,
        "question_text": 'The Alliance of Sahel States (AES) was formed by which three countries?',
        "option_a": 'Nigeria, Ghana, Senegal',
        "option_b": 'Mali, Burkina Faso, Niger',
        "option_c": 'Chad, Sudan, Cameroon',
        "option_d": "Guinea, Côte d'Ivoire, Togo",
        "correct_answer": 'B',
        "explanation": 'Mali, Burkina Faso, and Niger formed the Alliance of Sahel States (AES) after their military coups. They withdrew from ECOWAS in January 2025 and are all aligned with Russia (Wagner/Africa Corps).',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22062,
        "question_text": 'Mali, Burkina Faso, and Niger officially withdrew from ECOWAS (Economic Community of West African States) in:',
        "option_a": 'March 2024',
        "option_b": 'July 2024',
        "option_c": 'January 2025',
        "option_d": 'March 2025',
        "correct_answer": 'C',
        "explanation": 'Mali, Burkina Faso, and Niger — which had formed the Alliance of Sahel States (AES) — officially withdrew from ECOWAS in January 2025, dealing a blow to West African regional integration.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22063,
        "question_text": "Wagner Group, which operated in Mali and other African countries, was rebranded as what after Prigozhin's death in August 2023?",
        "option_a": 'Russia Special Forces Africa',
        "option_b": 'Africa Corps',
        "option_c": 'Russian Expeditionary Forces',
        "option_d": 'Sahel Security Group',
        "correct_answer": 'B',
        "explanation": "After Wagner Group founder Yevgeny Prigozhin died in a plane crash in August 2023, Wagner's African operations were rebranded as 'Africa Corps' under Russian military control.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22064,
        "question_text": 'The Sudan civil war (April 2023-present) is between which two factions?',
        "option_a": 'Sudan Liberation Army vs Government',
        "option_b": 'Sudan Armed Forces (SAF) vs Rapid Support Forces (RSF)',
        "option_c": 'SPLM vs Khartoum Government',
        "option_d": 'Islamists vs Secularists',
        "correct_answer": 'B',
        "explanation": "Sudan's civil war (from April 2023) is between the Sudan Armed Forces (SAF) led by Gen. al-Burhan and the Rapid Support Forces (RSF) led by Gen. Dagalo (Hemedti). RSF was accused of genocide in Darfur.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22065,
        "question_text": "Niger's military coup in July 2023 was particularly significant because Niger expelled troops of which two countries?",
        "option_a": 'UK and Germany',
        "option_b": 'France and USA',
        "option_c": 'China and India',
        "option_d": 'Saudi Arabia and UAE',
        "correct_answer": 'B',
        "explanation": "After Niger's coup (July 2023), the military junta expelled both French troops and US forces from the country. Niger also banned uranium exports to France — significant as Niger is a major uranium supplier.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22066,
        "question_text": 'Rwanda-backed rebel group M23 captured the city of Goma in eastern DRC (Congo) in:',
        "option_a": 'March 2024',
        "option_b": 'October 2024',
        "option_c": 'January 2025',
        "option_d": 'April 2025',
        "correct_answer": 'C',
        "explanation": 'The M23 rebel group, allegedly backed by Rwanda, captured Goma — the main city in eastern DRC — in January 2025, escalating the long-running eastern Congo conflict.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22067,
        "question_text": 'The ICC issued an arrest warrant for Russian President Vladimir Putin in March 2023 for:',
        "option_a": 'Invasion of Ukraine',
        "option_b": 'Nuclear threats against NATO',
        "option_c": 'Unlawful deportation of Ukrainian children to Russia',
        "option_d": 'War crimes in Chechnya',
        "correct_answer": 'C',
        "explanation": 'The ICC arrest warrant for Putin (March 2023) specifically charges him with unlawful deportation and transfer of Ukrainian children to Russia — a war crime under the Rome Statute.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22068,
        "question_text": 'Where are both the ICC (International Criminal Court) and ICJ (International Court of Justice) located?',
        "option_a": 'Geneva, Switzerland',
        "option_b": 'New York, USA',
        "option_c": 'Vienna, Austria',
        "option_d": 'The Hague, Netherlands',
        "correct_answer": 'D',
        "explanation": 'Both the ICC and ICJ are located in The Hague, Netherlands, though they are different courts. ICJ resolves disputes between states; ICC prosecutes individuals for war crimes/genocide/crimes against humanity.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22069,
        "question_text": 'Which of the following countries is NOT a member of the ICC (International Criminal Court)?',
        "option_a": 'Germany',
        "option_b": 'South Africa',
        "option_c": 'India',
        "option_d": 'Australia',
        "correct_answer": 'C',
        "explanation": 'India, USA, Russia, and China are NOT members of the ICC. India signed but never ratified the Rome Statute. The ICC has ~124 member states (State Parties to the Rome Statute).',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22070,
        "question_text": 'The ICJ (International Court of Justice) differs from the ICC in that the ICJ:',
        "option_a": 'Prosecutes individual war criminals',
        "option_b": 'Is based in Geneva',
        "option_c": 'Resolves disputes between nation-states',
        "option_d": 'Was created after the ICC',
        "correct_answer": 'C',
        "explanation": 'ICJ (International Court of Justice) resolves legal disputes BETWEEN STATES — e.g., South Africa vs Israel genocide case. ICC (International Criminal Court) prosecutes INDIVIDUALS for war crimes, genocide, and crimes against humanity.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22071,
        "question_text": 'ICC also issued an arrest warrant for former Israeli Defence Minister Yoav Gallant in November 2024. He was replaced as Defence Minister by:',
        "option_a": 'Benny Gantz',
        "option_b": 'Israel Katz',
        "option_c": 'Avigdor Lieberman',
        "option_d": 'Naftali Bennett',
        "correct_answer": 'B',
        "explanation": 'Israel Katz replaced Yoav Gallant as Defence Minister in November 2024 — the same month the ICC issued warrants for both Netanyahu and Gallant for alleged war crimes in Gaza.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22072,
        "question_text": 'The ICC was established under which treaty/statute?',
        "option_a": 'Geneva Convention',
        "option_b": 'Rome Statute',
        "option_c": 'UN Charter',
        "option_d": 'Versailles Treaty',
        "correct_answer": 'B',
        "explanation": 'The ICC was established under the Rome Statute (1998, entered into force 2002). It is a permanent international court — unlike the Nuremberg/Tokyo tribunals which were ad hoc (temporary).',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22073,
        "question_text": 'Which conflict involves Bab-el-Mandeb, Cape of Good Hope rerouting, and Iran-backed militants?',
        "option_a": 'Russia-Ukraine War',
        "option_b": 'Israel-Gaza War',
        "option_c": "Yemen's Houthi Red Sea Crisis",
        "option_d": 'Sudan Civil War',
        "correct_answer": 'C',
        "explanation": 'The Houthi (Ansar Allah) attacks in the Red Sea — near the Bab-el-Mandeb strait — forced ships to reroute via Cape of Good Hope. Houthis are backed by Iran.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22074,
        "question_text": "Which country has been simultaneously involved in: sending troops to Russia, conducting missile tests, and declared South Korea as 'principal enemy' in 2024?",
        "option_a": 'Iran',
        "option_b": 'China',
        "option_c": 'North Korea',
        "option_d": 'Syria',
        "correct_answer": 'C',
        "explanation": "North Korea in 2024: sent ~10,000 troops to Russia, tested Hwasong-18 ICBMs, and Kim Jong-un declared South Korea 'principal enemy' — scrapping reunification policy.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22075,
        "question_text": 'The Nagorno-Karabakh conflict ended in September 2023 when Azerbaijan regained full control. This region had been disputed between Azerbaijan and which country?',
        "option_a": 'Georgia',
        "option_b": 'Armenia',
        "option_c": 'Turkey',
        "option_d": 'Iran',
        "correct_answer": 'B',
        "explanation": 'Nagorno-Karabakh was a disputed enclave — controlled by ethnic Armenians but within Azerbaijan. Azerbaijan launched a decisive military operation in September 2023, regaining full control. ~100,000 ethnic Armenians fled to Armenia.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22076,
        "question_text": 'Which conflict has displaced the most people (10+ million) and seen a UN-declared famine as of 2024?',
        "option_a": 'Ukraine war',
        "option_b": 'Gaza war',
        "option_c": 'Sudan civil war',
        "option_d": 'Syria conflict',
        "correct_answer": 'C',
        "explanation": "Sudan's civil war (SAF vs RSF, since April 2023) has caused one of the world's worst humanitarian disasters — 10+ million displaced and famine declared in parts of Sudan by the UN in 2024.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22077,
        "question_text": "The phrase 'Axis of Resistance' refers to which grouping in Middle East geopolitics?",
        "option_a": 'USA, Israel, Saudi Arabia, UAE',
        "option_b": 'Iran, Hezbollah, Hamas, Houthis, Syria',
        "option_c": 'Turkey, Qatar, Muslim Brotherhood',
        "option_d": 'Russia, China, Iran, North Korea',
        "correct_answer": 'B',
        "explanation": "'Axis of Resistance' is Iran's term for its regional proxy network: Iran + Hezbollah (Lebanon) + Hamas (Gaza) + Houthis (Yemen) + Syrian militias. All are backed by Iran against Israel/USA.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22078,
        "question_text": "India's diplomatic response to Pahalgam attack included suspending which 1960 treaty with Pakistan?",
        "option_a": 'Treaty of Peace and Friendship',
        "option_b": 'Simla Agreement',
        "option_c": 'Indus Waters Treaty',
        "option_d": 'Lahore Declaration',
        "correct_answer": 'C',
        "explanation": "India suspended the Indus Waters Treaty (signed 1960, Nehru-Ayub Khan) following the April 22, 2025 Pahalgam attack. The treaty governs the use of the Indus river system — critical for Pakistan's agriculture.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22079,
        "question_text": 'Who brokered the January 19, 2025 Gaza ceasefire as the key US envoy?',
        "option_a": 'Antony Blinken',
        "option_b": 'John Kerry',
        "option_c": 'Steve Witkoff',
        "option_d": 'Jake Sullivan',
        "correct_answer": 'C',
        "explanation": 'Steve Witkoff served as the key US Special Envoy who helped broker the Gaza ceasefire Phase 1 on January 19, 2025, working with Qatar and Egypt as mediators.',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 22080,
        "question_text": 'Which of these is CORRECTLY matched?',
        "option_a": 'Operation Sindoor — April 22, 2025',
        "option_b": 'Hamas Oct 7 attack — October 7, 2022',
        "option_c": 'Assad fell — December 8, 2024',
        "option_d": 'Sweden joins NATO — March 2023',
        "correct_answer": 'C',
        "explanation": 'Assad fell on December 8, 2024 ✓. Operation Sindoor = May 7, 2025 (NOT April 22). Hamas attack = October 7, 2023 (NOT 2022). Sweden joined NATO = March 7, 2024 (NOT 2023).',
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
]

def get_db():
    if USE_POSTGRES:
        import psycopg2
        return psycopg2.connect(DATABASE_URL)
    db_path = os.path.join(os.path.dirname(__file__), "database.db")
    return sqlite3.connect(db_path)

def seed():
    conn = get_db()
    ph = "%s" if USE_POSTGRES else "?"
    inserted = 0; skipped = 0
    try:
        cur = conn.cursor()
        for q in CONFLICTS_MCQS:
            cur.execute(f"SELECT COUNT(*) FROM questions WHERE id={ph}", (q["id"],))
            if cur.fetchone()[0] > 0:
                skipped += 1; continue
            cur.execute(
                f"""INSERT INTO questions
                    (id, question_text, option_a, option_b, option_c, option_d,
                     correct_answer, explanation, folder, topic)
                    VALUES ({ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph})""",
                (q["id"], q["question_text"], q["option_a"], q["option_b"],
                 q["option_c"], q["option_d"], q["correct_answer"],
                 q["explanation"], q["folder"], q["topic"])
            )
            inserted += 1
        conn.commit()
        print(f"[seed_conflicts] Inserted={inserted}, Skipped={skipped}")
    finally:
        conn.close()

if __name__ == "__main__":
    seed()