"""
seed_intl_orgs_mcq.py
75 GKToday-style MCQs — Topic: International Current Affairs → International Organisations
Coverage: 2025-2026 events + static GK
Folder: AP_HC | Topic: International_Current_Affairs
IDs: 20001–20075
"""

import os, sqlite3

DATABASE_URL = os.environ.get("DATABASE_URL", "")
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)
USE_POSTGRES = bool(DATABASE_URL)

INTL_MCQS = [
    # ─── UN (1-6) ───────────────────────────────────────────────────
    {
        "id": 20001,
        "question": "The headquarters of the United Nations (UN) is located in which city?",
        "option_a": "Geneva",
        "option_b": "New York",
        "option_c": "Brussels",
        "option_d": "Vienna",
        "correct_answer": "B",
        "explanation": "UN HQ is in New York City, USA. The UN was founded on October 24, 1945 (celebrated as UN Day). Geneva hosts many UN agencies but the main HQ is New York.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20002,
        "question": "Who is the current Secretary-General of the United Nations (as of 2026)?",
        "option_a": "Ban Ki-moon",
        "option_b": "Kofi Annan",
        "option_c": "António Guterres",
        "option_d": "Tedros Adhanom",
        "correct_answer": "C",
        "explanation": "António Guterres (Portugal) is the 9th UN Secretary-General, serving since January 1, 2017. His 2nd term runs till December 2026. Tedros is WHO DG, not UN SG.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20003,
        "question": "The UN Security Council has how many permanent members (P5), each holding veto power?",
        "option_a": "3",
        "option_b": "5",
        "option_c": "7",
        "option_d": "10",
        "correct_answer": "B",
        "explanation": "UNSC has 5 permanent members (P5): USA, UK, France, Russia, China. Each has veto power. There are also 10 non-permanent elected members, serving 2-year terms. Total UNSC = 15 members.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20004,
        "question": "How many member states does the United Nations currently have?",
        "option_a": "191",
        "option_b": "192",
        "option_c": "193",
        "option_d": "195",
        "correct_answer": "C",
        "explanation": "UN has 193 member states. The most recent full member is South Sudan (2011). Palestine and Vatican City have observer status but are not full members.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20005,
        "question": "In the UN General Assembly (UNGA), how are votes distributed among member states?",
        "option_a": "Proportional to population",
        "option_b": "Each country has one equal vote",
        "option_c": "Based on economic contribution",
        "option_d": "Only P5 countries vote",
        "correct_answer": "B",
        "explanation": "In UNGA, every member state has one equal vote — a small nation like Maldives and the USA both have one vote. UNGA resolutions are generally non-binding (unlike UNSC Chapter VII resolutions).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20006,
        "question": "Which of the following is the only major UN body whose headquarters is located in Africa (the Global South)?",
        "option_a": "FAO",
        "option_b": "UNESCO",
        "option_c": "UNEP",
        "option_d": "IAEA",
        "correct_answer": "C",
        "explanation": "UNEP (UN Environment Programme) HQ is in Nairobi, Kenya — the only major UN body headquartered in Africa/Global South. FAO is in Rome, UNESCO in Paris, IAEA in Vienna.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    # ─── G20 (7-12) ─────────────────────────────────────────────────
    {
        "id": 20007,
        "question": "Which country is hosting the G20 Summit in 2026?",
        "option_a": "South Africa",
        "option_b": "Brazil",
        "option_c": "USA",
        "option_d": "Indonesia",
        "correct_answer": "C",
        "explanation": "The USA is hosting the G20 in 2026 (Miami). South Africa handed over the G20 Presidency to the USA on January 12, 2026. India hosted G20 in 2023, Brazil in 2024, South Africa in 2025.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20008,
        "question": "India hosted the G20 Summit 2023 under which theme?",
        "option_a": "One World, One Future",
        "option_b": "Vasudhaiva Kutumbakam — One Earth, One Family, One Future",
        "option_c": "Building a Sustainable World Together",
        "option_d": "Peace, Progress and Prosperity",
        "correct_answer": "B",
        "explanation": "India's G20 2023 theme was 'Vasudhaiva Kutumbakam — One Earth, One Family, One Future' (from Maha Upanishad). The 18th G20 Summit was held at Bharat Mandapam, New Delhi on September 9-10, 2023.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20009,
        "question": "Which country hosted the G20 Summit in 2025?",
        "option_a": "Indonesia",
        "option_b": "Mexico",
        "option_c": "South Africa",
        "option_d": "Turkey",
        "correct_answer": "C",
        "explanation": "South Africa hosted G20 in 2025. The G20 Presidency rotates among members. Sequence: India (2023) → Brazil (2024) → South Africa (2025) → USA (2026).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20010,
        "question": "The G20 was originally established in which year, primarily as a forum for Finance Ministers?",
        "option_a": "1994",
        "option_b": "1999",
        "option_c": "2004",
        "option_d": "2008",
        "correct_answer": "B",
        "explanation": "G20 was established in 1999 as a forum for Finance Ministers and Central Bank Governors, following the 1997 Asian financial crisis. It was elevated to Leaders' Summit level in 2008 during the global financial crisis.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20011,
        "question": "Which of the following is NOT a member of the G20?",
        "option_a": "Argentina",
        "option_b": "Norway",
        "option_c": "South Korea",
        "option_d": "Turkey",
        "correct_answer": "B",
        "explanation": "Norway is not a G20 member. G20 = 19 countries + EU + African Union (AU). The 19 countries include Argentina, Australia, Brazil, Canada, China, France, Germany, India, Indonesia, Italy, Japan, Mexico, Russia, Saudi Arabia, South Africa, South Korea, Turkey, UK, USA.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20012,
        "question": "Which new bloc was added as a full member of G20 in 2023?",
        "option_a": "ASEAN",
        "option_b": "African Union (AU)",
        "option_c": "Arab League",
        "option_d": "SAARC",
        "correct_answer": "B",
        "explanation": "The African Union (AU) was admitted as a permanent G20 member at the India-hosted G20 Summit 2023 in New Delhi. This was a key outcome pushed by India during its G20 Presidency.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    # ─── BRICS (13-20) ───────────────────────────────────────────────
    {
        "id": 20013,
        "question": "Which country holds the BRICS Chairmanship in 2026?",
        "option_a": "China",
        "option_b": "Brazil",
        "option_c": "India",
        "option_d": "Russia",
        "correct_answer": "C",
        "explanation": "India holds the BRICS Chairmanship in 2026. The 18th BRICS Summit will be held in New Delhi on September 12-13, 2026. India's BRICS Chair theme is embedded in the BRICS acronym itself.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20014,
        "question": "What is India's official theme for the BRICS Chairmanship 2026?",
        "option_a": "Building Bridges, Sustaining Development",
        "option_b": "Building for Resilience, Innovation, Cooperation and Sustainability",
        "option_c": "BRICS for a Better World",
        "option_d": "Partnership for Global Peace and Prosperity",
        "correct_answer": "B",
        "explanation": "India's BRICS 2026 theme is 'Building for Resilience, Innovation, Cooperation and Sustainability' — cleverly embedding the BRICS acronym (B-R-I-C-S) in the theme. This was a deliberate choice by India.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20015,
        "question": "Where was the BRICS Foreign Ministers' Meeting held in May 2026?",
        "option_a": "Vigyan Bhavan, New Delhi",
        "option_b": "Bharat Mandapam, New Delhi",
        "option_c": "Taj Diplomatic Enclave, Mumbai",
        "option_d": "Hyderabad House, New Delhi",
        "correct_answer": "B",
        "explanation": "The BRICS Foreign Ministers' Meeting was held on May 14-15, 2026 at Bharat Mandapam, New Delhi, chaired by EAM S. Jaishankar. This was a key preparatory meeting ahead of the 18th BRICS Summit.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20016,
        "question": "The 18th BRICS Summit 2026 is scheduled to be held in which city and on what dates?",
        "option_a": "Mumbai, October 2026",
        "option_b": "New Delhi, September 12-13, 2026",
        "option_c": "Hyderabad, August 2026",
        "option_d": "Chennai, November 2026",
        "correct_answer": "B",
        "explanation": "The 18th BRICS Summit is scheduled for September 12-13, 2026 in New Delhi, India. India holds the BRICS Chairmanship in 2026 — the first time India chairs BRICS after the 2024 expansion to 10 members.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20017,
        "question": "Where is the headquarters of the New Development Bank (NDB), established by BRICS nations?",
        "option_a": "New Delhi",
        "option_b": "Moscow",
        "option_c": "Beijing",
        "option_d": "Shanghai",
        "correct_answer": "D",
        "explanation": "NDB (New Development Bank) HQ is in Shanghai, China. NDB was established in 2014 with initial authorized capital of $100 billion. Its current President is Dilma Rousseff (former Brazilian President, since 2023).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20018,
        "question": "How many countries are currently full members of BRICS (as of 2025), after the 2024 expansion?",
        "option_a": "5",
        "option_b": "6",
        "option_c": "9",
        "option_d": "10",
        "correct_answer": "D",
        "explanation": "BRICS expanded to 10 members in 2024 adding Egypt, Ethiopia, Iran, UAE, Saudi Arabia. Argentina was invited but declined under President Milei. The original 5 were: Brazil, Russia, India, China, South Africa (joined 2010).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20019,
        "question": "Which country declined the BRICS membership invitation offered at the 15th BRICS Summit (2023)?",
        "option_a": "Saudi Arabia",
        "option_b": "Indonesia",
        "option_c": "Argentina",
        "option_d": "Turkey",
        "correct_answer": "C",
        "explanation": "Argentina was invited to join BRICS at the 15th Summit (South Africa, 2023) but declined. New President Javier Milei, an economic libertarian, declined the invitation in December 2023. The other five invitees (Egypt, Ethiopia, Iran, UAE, Saudi Arabia) joined on January 1, 2024.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20020,
        "question": "BRICS originally began as 'BRIC' without South Africa. Which body/report first coined the term 'BRIC'?",
        "option_a": "World Bank Report 2001",
        "option_b": "Goldman Sachs Report by Jim O'Neill (2001)",
        "option_c": "UN Development Report 2000",
        "option_d": "IMF Outlook 2003",
        "correct_answer": "B",
        "explanation": "The term 'BRIC' was coined by economist Jim O'Neill of Goldman Sachs in a 2001 paper titled 'Building Better Global Economic BRICs.' South Africa joined in 2010 to form BRICS. The first BRIC Summit was held in Yekaterinburg, Russia (2009).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    # ─── G7 (21-24) ─────────────────────────────────────────────────
    {
        "id": 20021,
        "question": "Which country is hosting the G7 Summit in 2026, and at which location?",
        "option_a": "Germany, Berlin",
        "option_b": "Japan, Hiroshima",
        "option_c": "France, Évian-les-Bains",
        "option_d": "Italy, Venice",
        "correct_answer": "C",
        "explanation": "France is hosting the G7 Summit 2026 at Évian-les-Bains (June 15-17, 2026). Évian-les-Bains is a resort town on the south shore of Lake Geneva. Italy hosted G7 2024 (Puglia); Canada hosted G7 2025 (Kananaskis).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20022,
        "question": "Which of the following countries is NOT a member of the G7?",
        "option_a": "Canada",
        "option_b": "Italy",
        "option_c": "Russia",
        "option_d": "Japan",
        "correct_answer": "C",
        "explanation": "Russia is not in G7. Russia was suspended from G8 in 2014 following its annexation of Crimea, reducing it back to G7. G7 = Canada, France, Germany, Italy, Japan, UK, USA. The EU participates as a non-enumerated member.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20023,
        "question": "Which country hosted the G7 Summit in 2025?",
        "option_a": "Italy",
        "option_b": "UK",
        "option_c": "Canada",
        "option_d": "USA",
        "correct_answer": "C",
        "explanation": "Canada hosted the G7 Summit in 2025 at Kananaskis, Alberta. The G7 Presidency rotates: Italy (2024) → Canada (2025) → France (2026) → USA (2027).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20024,
        "question": "G7 originally began as G6 in 1975. Which country joined in 1976 to make it G7?",
        "option_a": "Italy",
        "option_b": "Japan",
        "option_c": "Canada",
        "option_d": "Germany",
        "correct_answer": "C",
        "explanation": "G7 began as G6 in 1975 (France, USA, UK, West Germany, Japan, Italy) at the Rambouillet Summit. Canada joined in 1976 to make it G7. Russia joined in 1997 to make G8 but was suspended in 2014.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    # ─── QUAD (25-28) ────────────────────────────────────────────────
    {
        "id": 20025,
        "question": "The Quadrilateral Security Dialogue (QUAD) consists of which four countries?",
        "option_a": "India, USA, Japan, South Korea",
        "option_b": "India, USA, Japan, Australia",
        "option_c": "India, USA, Australia, New Zealand",
        "option_d": "India, France, Japan, Australia",
        "correct_answer": "B",
        "explanation": "QUAD = India, USA, Japan, Australia. It was first formed in 2007 (Shinzo Abe's initiative), revived in 2017, and elevated to Leaders' Summit in 2021. Focus: free and open Indo-Pacific, vaccines, clean energy, critical tech.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20026,
        "question": "Which country hosted the QUAD Leaders' Summit in 2025?",
        "option_a": "USA (Wilmington)",
        "option_b": "Japan (Tokyo)",
        "option_c": "India (New Delhi)",
        "option_d": "Australia (Sydney)",
        "correct_answer": "C",
        "explanation": "India hosted the QUAD Leaders' Summit in 2025 in New Delhi. PM Modi hosted the leaders of USA, Japan and Australia. The previous QUAD Summit was in Wilmington, USA (2024).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20027,
        "question": "Exercise MALABAR is a naval exercise conducted primarily among the nations of which grouping?",
        "option_a": "BRICS",
        "option_b": "QUAD",
        "option_c": "NATO",
        "option_d": "SCO",
        "correct_answer": "B",
        "explanation": "Exercise Malabar is a naval exercise among QUAD nations (India, USA, Japan, Australia). It began in 1992 as India-US bilateral exercise; Japan became permanent member in 2015; Australia joined in 2020, completing the QUAD quartet.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20028,
        "question": "QUAD primarily focuses on which geographical region's security and stability?",
        "option_a": "Atlantic Ocean and Mediterranean",
        "option_b": "Arctic and Antarctic regions",
        "option_c": "Indo-Pacific region",
        "option_d": "South China Sea only",
        "correct_answer": "C",
        "explanation": "QUAD is primarily focused on the Indo-Pacific region, promoting a free, open, and prosperous Indo-Pacific. All four QUAD members (India, USA, Japan, Australia) are Indo-Pacific nations. QUAD is seen as a counterbalance to China's assertiveness in the region.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    # ─── SCO (29-33) ─────────────────────────────────────────────────
    {
        "id": 20029,
        "question": "The headquarters of the Shanghai Cooperation Organisation (SCO) is in which city?",
        "option_a": "Shanghai",
        "option_b": "Moscow",
        "option_c": "Beijing",
        "option_d": "Tashkent",
        "correct_answer": "C",
        "explanation": "SCO Secretariat HQ is in Beijing, China. The Regional Anti-Terrorist Structure (RATS) of SCO is in Tashkent, Uzbekistan. SCO was founded in 2001. Note: it is named after Shanghai where the original 'Shanghai Five' met in 1996.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20030,
        "question": "India became a full member of the SCO in which year?",
        "option_a": "2001",
        "option_b": "2015",
        "option_c": "2017",
        "option_d": "2019",
        "correct_answer": "C",
        "explanation": "India (along with Pakistan) became a full member of SCO at the Astana Summit, Kazakhstan in June 2017. India had been an SCO observer since 2005 and dialogue partner since 2012.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20031,
        "question": "How many full member countries does the SCO currently have (as of 2025)?",
        "option_a": "6",
        "option_b": "8",
        "option_c": "9",
        "option_d": "10",
        "correct_answer": "D",
        "explanation": "SCO has 10 full members: China, Russia, Kazakhstan, Kyrgyzstan, Tajikistan, Uzbekistan (founders 2001), India, Pakistan (2017), Iran (2023), Belarus (2024). Turkey and several Central Asian nations are dialogue partners.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20032,
        "question": "Which country hosted the SCO Summit in 2025?",
        "option_a": "Russia",
        "option_b": "India",
        "option_c": "China",
        "option_d": "Kazakhstan",
        "correct_answer": "C",
        "explanation": "China hosted the SCO Summit in 2025. The SCO Presidency/Summit rotates among member states. India hosted the SCO Summit virtually in 2023 (first virtual SCO Summit).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20033,
        "question": "The SCO was originally born from which grouping of nations in 1996?",
        "option_a": "Shanghai Five",
        "option_b": "Central Asian Four",
        "option_c": "CSTO members",
        "option_d": "CIS nations",
        "correct_answer": "A",
        "explanation": "SCO evolved from the 'Shanghai Five' — China, Russia, Kazakhstan, Kyrgyzstan, Tajikistan — formed in 1996. Uzbekistan joined in 2001, and the group was reconstituted as the SCO at the Shanghai Summit (June 15, 2001).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    # ─── NATO (34-38) ────────────────────────────────────────────────
    {
        "id": 20034,
        "question": "NATO headquarters is located in which city?",
        "option_a": "London",
        "option_b": "Brussels",
        "option_c": "Washington DC",
        "option_d": "Paris",
        "correct_answer": "B",
        "explanation": "NATO HQ is in Brussels, Belgium. The military command (SHAPE — Supreme Headquarters Allied Powers Europe) is in Mons, Belgium. NATO was founded April 4, 1949 with the Washington Treaty.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20035,
        "question": "How many member countries does NATO have as of 2024?",
        "option_a": "28",
        "option_b": "30",
        "option_c": "31",
        "option_d": "32",
        "correct_answer": "D",
        "explanation": "NATO has 32 members as of 2024. Sweden became the 32nd member on March 7, 2024. Finland joined as 31st in April 2023. Both joined following Russia's invasion of Ukraine (February 2022).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20036,
        "question": "NATO's Article 5 refers to which principle?",
        "option_a": "Nuclear weapons sharing",
        "option_b": "Collective defence — an attack on one member is an attack on all",
        "option_c": "Mandatory 2% GDP defence spending",
        "option_d": "Freedom of navigation in international waters",
        "correct_answer": "B",
        "explanation": "Article 5 of the North Atlantic Treaty is the collective defence clause — an armed attack against one NATO member is considered an attack against all. It has been invoked only once: after the September 11, 2001 terrorist attacks on the USA.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20037,
        "question": "Which country became the newest (32nd) member of NATO in March 2024?",
        "option_a": "Finland",
        "option_b": "Ukraine",
        "option_c": "Sweden",
        "option_d": "Georgia",
        "correct_answer": "C",
        "explanation": "Sweden became NATO's 32nd member on March 7, 2024, after Turkey and Hungary lifted their vetoes. Finland had joined as 31st member in April 2023. Both Nordic nations abandoned their decades-long neutrality due to Russia's war in Ukraine.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20038,
        "question": "NATO celebrated its 75th anniversary in which year, and at which Summit?",
        "option_a": "2023, Vilnius Summit",
        "option_b": "2024, Washington DC Summit",
        "option_c": "2025, The Hague Summit",
        "option_d": "2022, Madrid Summit",
        "correct_answer": "B",
        "explanation": "NATO celebrated its 75th anniversary at the Washington DC Summit in July 2024. NATO was founded on April 4, 1949. The Washington Summit also saw the 5% GDP defence spending target discussed (up from 2%).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    # ─── ASEAN (39-44) ───────────────────────────────────────────────
    {
        "id": 20039,
        "question": "The ASEAN Secretariat is headquartered in which city?",
        "option_a": "Bangkok",
        "option_b": "Singapore",
        "option_c": "Jakarta",
        "option_d": "Kuala Lumpur",
        "correct_answer": "C",
        "explanation": "ASEAN Secretariat HQ is in Jakarta, Indonesia. ASEAN was founded on August 8, 1967 with the Bangkok Declaration (signed in Bangkok, Thailand). The founding five members were Indonesia, Malaysia, Philippines, Singapore, Thailand.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20040,
        "question": "Which country became the 11th member of ASEAN, admitted at the 47th ASEAN Summit in 2025?",
        "option_a": "Papua New Guinea",
        "option_b": "East Timor (Timor-Leste)",
        "option_c": "Bangladesh",
        "option_d": "Sri Lanka",
        "correct_answer": "B",
        "explanation": "East Timor (Timor-Leste) became ASEAN's 11th member at the 47th ASEAN Summit held in Malaysia, 2025. East Timor has been an observer since 2011 and received in-principle approval at the 40th/41st ASEAN Summit in 2022.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20041,
        "question": "Which country hosted the 47th ASEAN Summit in 2025, and what was its chairmanship theme?",
        "option_a": "Indonesia — 'Unity in Diversity'",
        "option_b": "Thailand — 'Open, Connected, Balanced'",
        "option_c": "Malaysia — 'Inclusivity and Sustainability'",
        "option_d": "Vietnam — 'Cohesive and Responsive'",
        "correct_answer": "C",
        "explanation": "Malaysia hosted the 47th ASEAN Summit in 2025 with the chairmanship theme 'Inclusivity and Sustainability.' Malaysia also chairs ASEAN in 2025. East Timor's admission as 11th member was a landmark event at this Summit.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20042,
        "question": "ASEAN was founded in which year by the Bangkok Declaration?",
        "option_a": "1960",
        "option_b": "1963",
        "option_c": "1967",
        "option_d": "1971",
        "correct_answer": "C",
        "explanation": "ASEAN was founded on August 8, 1967 with the signing of the Bangkok Declaration. Founding members: Indonesia, Malaysia, Philippines, Singapore, Thailand. August 8 is celebrated as ASEAN Day.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20043,
        "question": "India-ASEAN relations were upgraded to which level of partnership in 2022?",
        "option_a": "Strategic Partnership",
        "option_b": "Enhanced Partnership",
        "option_c": "Comprehensive Strategic Partnership",
        "option_d": "Full Alliance",
        "correct_answer": "C",
        "explanation": "India-ASEAN relations were upgraded to Comprehensive Strategic Partnership (CSP) at the ASEAN-India Summit in Phnom Penh, Cambodia in November 2022. India became ASEAN's Dialogue Partner in 1992 and Summit-level partner in 2002.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20044,
        "question": "The year 2026 has been designated as which special year between India and ASEAN?",
        "option_a": "ASEAN-India Technology Year",
        "option_b": "ASEAN-India Year of Maritime Cooperation",
        "option_c": "ASEAN-India Cultural Year",
        "option_d": "ASEAN-India Digital Economy Year",
        "correct_answer": "B",
        "explanation": "2026 is designated as the ASEAN-India Year of Maritime Cooperation, highlighting Blue Economy, maritime connectivity, and Indo-Pacific collaboration. India and ASEAN share the Indian Ocean and South China Sea region.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    # ─── IMF & World Bank (45-50) ────────────────────────────────────
    {
        "id": 20045,
        "question": "The IMF and World Bank are both headquartered in which city?",
        "option_a": "New York",
        "option_b": "Geneva",
        "option_c": "Washington DC",
        "option_d": "London",
        "correct_answer": "C",
        "explanation": "Both IMF and World Bank are headquartered in Washington DC, USA. They were both established at the Bretton Woods Conference (1944) in Bretton Woods, New Hampshire, USA, and began operations in 1945/1946.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20046,
        "question": "Who is the current Managing Director of the IMF (as of 2025)?",
        "option_a": "Christine Lagarde",
        "option_b": "Gita Gopinath",
        "option_c": "Kristalina Georgieva",
        "option_d": "Janet Yellen",
        "correct_answer": "C",
        "explanation": "Kristalina Georgieva (Bulgaria) is IMF MD since October 2019, with a 2nd term from 2024. By convention, IMF MD is a European (Georgieva is from Bulgaria). By convention, World Bank President is an American.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20047,
        "question": "What GDP growth rate did the IMF project for India in FY 2025-26?",
        "option_a": "5.8%",
        "option_b": "6.2%",
        "option_c": "6.6%",
        "option_d": "7.2%",
        "correct_answer": "C",
        "explanation": "IMF projected India's GDP growth at 6.6% for FY 2025-26 (adjusted under prolonged US tariff scenario). India remains the fastest-growing major economy, outpacing China (4.8% projected). India's status as fastest grower was retained in 2025.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20048,
        "question": "The IMF-World Bank Spring Meetings 2026 were held where and when?",
        "option_a": "Geneva, March 2026",
        "option_b": "Washington DC, April 13-18, 2026",
        "option_c": "New York, May 2026",
        "option_d": "London, April 2026",
        "correct_answer": "B",
        "explanation": "The IMF-World Bank Spring Meetings 2026 were held in Washington DC from April 13-18, 2026. Key issues: Iran-Israel conflict impact on oil prices, US tariff uncertainty, and India highlighted as a top AI/digital productivity performer.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20049,
        "question": "Who became the World Bank President in June 2023, becoming the first person of Indian origin to lead the institution?",
        "option_a": "Raghuram Rajan",
        "option_b": "Arvind Subramanian",
        "option_c": "Ajay Banga",
        "option_d": "Kaushik Basu",
        "correct_answer": "C",
        "explanation": "Ajay Banga (Indian-American) became World Bank President in June 2023. He was nominated by the Biden administration. Born in Pune, India, Banga is the former CEO of Mastercard. He is the first person of Indian origin to head the World Bank.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20050,
        "question": "The IMF's Special Drawing Right (SDR) is based on a basket of how many currencies?",
        "option_a": "3",
        "option_b": "4",
        "option_c": "5",
        "option_d": "7",
        "correct_answer": "C",
        "explanation": "SDR basket has 5 currencies: US Dollar, Euro, Chinese Yuan (Renminbi), British Pound, Japanese Yen. China's Renminbi was added to the SDR basket in 2016. SDR is an international reserve asset created by IMF in 1969.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    # ─── WTO (51-55) ─────────────────────────────────────────────────
    {
        "id": 20051,
        "question": "The WTO is headquartered in which city?",
        "option_a": "New York",
        "option_b": "Brussels",
        "option_c": "Geneva",
        "option_d": "Zurich",
        "correct_answer": "C",
        "explanation": "WTO HQ is in Geneva, Switzerland. WTO was established on January 1, 1995, replacing GATT (General Agreement on Tariffs and Trade, 1947). It has 164 member countries.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20052,
        "question": "Who is the Director-General of the WTO, and what historic firsts does she represent?",
        "option_a": "Pascal Lamy — first Frenchman",
        "option_b": "Ngozi Okonjo-Iweala — first African and first woman",
        "option_c": "Roberto Azevêdo — first Latin American",
        "option_d": "Supachai Panitchpakdi — first Asian",
        "correct_answer": "B",
        "explanation": "Ngozi Okonjo-Iweala (Nigeria) became WTO DG in March 2021 — making her the first African and first woman to lead the WTO. She is a former Finance Minister of Nigeria. Her 2nd term started in 2025. WTO has 164 members.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20053,
        "question": "The 13th WTO Ministerial Conference (MC13) was held in which city in February 2024?",
        "option_a": "Geneva",
        "option_b": "Nairobi",
        "option_c": "Abu Dhabi",
        "option_d": "Buenos Aires",
        "correct_answer": "C",
        "explanation": "MC13 was held in Abu Dhabi, UAE in February 2024. Key outcomes included progress on fisheries subsidies and e-commerce moratorium extension. India strongly defended agricultural subsidies and MSP programme at MC13.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20054,
        "question": "WTO replaced which earlier international trade arrangement, which was signed in 1947?",
        "option_a": "UNCTAD",
        "option_b": "GATT",
        "option_c": "ITO",
        "option_d": "TRIPS Agreement",
        "correct_answer": "B",
        "explanation": "WTO replaced GATT (General Agreement on Tariffs and Trade), signed in 1947 as a temporary arrangement after the ITO (International Trade Organization) failed to get ratified. WTO became permanent on January 1, 1995 after the Uruguay Round (1986-1994).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20055,
        "question": "Which WTO body has been non-functional since 2019 due to the USA blocking new appointments?",
        "option_a": "General Council",
        "option_b": "Trade Policy Review Body",
        "option_c": "Appellate Body",
        "option_d": "Committee on Agriculture",
        "correct_answer": "C",
        "explanation": "The WTO Appellate Body (the final appeals court for trade disputes) has been non-functional since December 2019 because the USA blocked appointment of new judges. This has undermined WTO dispute settlement. India has supported reform of the DSB.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    # ─── ILO (56-60) ─────────────────────────────────────────────────
    {
        "id": 20056,
        "question": "What makes the ILO unique in its governance structure compared to all other international organisations?",
        "option_a": "Only elected democracies can join",
        "option_b": "Tripartite structure: governments + employers + workers all vote",
        "option_c": "Security Council-style veto for founding members",
        "option_d": "Decisions require 90% supermajority",
        "correct_answer": "B",
        "explanation": "ILO has a unique tripartite structure where each member state sends representatives from government, employers (industry) AND workers (trade unions) — all three have voting rights. This makes ILO the only international body where non-governmental actors vote with equal weight.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20057,
        "question": "ILO was founded in which year, making it the world's oldest surviving international organisation?",
        "option_a": "1905",
        "option_b": "1919",
        "option_c": "1929",
        "option_d": "1944",
        "correct_answer": "B",
        "explanation": "ILO was founded in 1919 under the Treaty of Versailles (post-World War I) as part of the League of Nations. It became a UN specialised agency in 1946 and won the Nobel Peace Prize in 1969. HQ is in Geneva.",
        "folder": "AP_HC",
        "question_type": "MCQ",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20058,
        "question": "The 113th International Labour Conference (ILC) adopted which landmark Convention in June 2025?",
        "option_a": "C190 on Violence and Harassment",
        "option_b": "C192 on Biological Hazards at Work",
        "option_c": "C188 on Work in Fishing",
        "option_d": "C189 on Domestic Workers",
        "correct_answer": "B",
        "explanation": "The 113th ILC (June 2-13, 2025, Geneva) adopted Convention C192 on Occupational Safety and Health — Biological Hazards, along with Recommendation R209. This was prompted by lessons from COVID-19 pandemic and addresses biological agents in workplaces.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20059,
        "question": "The ILO won the Nobel Peace Prize in which year, on its 50th anniversary?",
        "option_a": "1949",
        "option_b": "1955",
        "option_c": "1969",
        "option_d": "1975",
        "correct_answer": "C",
        "explanation": "ILO (International Labour Organization) won the Nobel Peace Prize in 1969, marking its 50th anniversary. ILO is headquartered in Geneva, Switzerland and has 187 member states. Its Director-General is Gilbert Houngbo (Togo, since 2022).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20060,
        "question": "ILO's headquarters is in which city, along with WHO and WTO?",
        "option_a": "Brussels",
        "option_b": "Vienna",
        "option_c": "New York",
        "option_d": "Geneva",
        "correct_answer": "D",
        "explanation": "ILO, WHO, and WTO are all headquartered in Geneva, Switzerland — often called the 'Capital of Peace.' Other Geneva-based bodies: UNHCR, WIPO, ITU, WMO, ICRC (Red Cross). Geneva hosts the most international organisations in the world.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    # ─── IAEA (61-64) ────────────────────────────────────────────────
    {
        "id": 20061,
        "question": "IAEA headquarters is located in which city, often called the 'City of Music'?",
        "option_a": "Geneva",
        "option_b": "Brussels",
        "option_c": "Vienna",
        "option_d": "Berlin",
        "correct_answer": "C",
        "explanation": "IAEA HQ is in Vienna, Austria ('City of Music'). IAEA was established in 1957 under the 'Atoms for Peace' initiative by US President Eisenhower. Other Vienna-based organizations: UNIDO, OSCE, OPEC. Vienna is also the UN's 4th HQ city.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20062,
        "question": "Who is the current Director-General of the IAEA (as of 2025)?",
        "option_a": "Yukiya Amano",
        "option_b": "Mohamed ElBaradei",
        "option_c": "Rafael Mariano Grossi",
        "option_d": "Hans Blix",
        "correct_answer": "C",
        "explanation": "Rafael Mariano Grossi (Argentina) has been IAEA DG since December 2019. He is the first Latin American to head the IAEA. Mohamed ElBaradei (Egypt) and Yukiya Amano (Japan) were previous DGs who both won Nobel Peace Prizes during their tenures.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20063,
        "question": "In 2026, India's Defence Minister Rajnath Singh called for which specific international action regarding Pakistan?",
        "option_a": "Pakistan's suspension from the UN Security Council",
        "option_b": "IAEA inspections/oversight of Pakistan's nuclear arsenal",
        "option_c": "Pakistan's removal from SCO membership",
        "option_d": "International economic sanctions on Pakistan",
        "correct_answer": "B",
        "explanation": "In 2026, Defence Minister Rajnath Singh called for IAEA oversight/inspection of Pakistan's nuclear arsenal, raising concerns about the safety and security of Pakistan's nuclear weapons. This came in the context of heightened India-Pakistan tensions in 2026.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20064,
        "question": "The IAEA–Pakistan Country Programme Framework (CPF) signed in 2026 covers which period?",
        "option_a": "2025–2030",
        "option_b": "2026–2031",
        "option_c": "2027–2032",
        "option_d": "2024–2029",
        "correct_answer": "B",
        "explanation": "The IAEA–Pakistan CPF for 2026–2031 was signed in 2026, outlining cooperation in nuclear technology for peaceful purposes — including agriculture, medicine, water management, and energy. CPFs are standard IAEA agreements with member states.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    # ─── WHO (65-69) ─────────────────────────────────────────────────
    {
        "id": 20065,
        "question": "The 78th World Health Assembly (WHA) adopted which historic international agreement in May 2025?",
        "option_a": "International Health Regulations (IHR) 2025 Amendment",
        "option_b": "WHO Global Pandemic Agreement (Pandemic Treaty)",
        "option_c": "Universal Health Coverage Charter",
        "option_d": "Global Antimicrobial Resistance Framework",
        "correct_answer": "B",
        "explanation": "The 78th WHA (May 19-27, 2025, Geneva) adopted the first-ever WHO Pandemic Agreement — a binding international treaty to prevent, prepare for, and respond to future pandemics. This was a landmark achievement in global health governance post-COVID-19.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20066,
        "question": "Which country re-withdrew from WHO in January 2025 under President Trump?",
        "option_a": "Russia",
        "option_b": "Brazil",
        "option_c": "USA",
        "option_d": "UK",
        "correct_answer": "C",
        "explanation": "USA under President Trump signed an executive order on January 20, 2025 (his 1st day in office) to withdraw from WHO, effective 2026. This was Trump's second WHO withdrawal — he withdrew in 2020 too, but Biden rejoined in January 2021. The withdrawal significantly impacted WHO's $4.2 billion budget.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20067,
        "question": "World Health Day is celebrated annually on which date — the founding anniversary of WHO?",
        "option_a": "March 7",
        "option_b": "April 7",
        "option_c": "May 7",
        "option_d": "June 7",
        "correct_answer": "B",
        "explanation": "World Health Day is April 7 every year — the anniversary of WHO's founding on April 7, 1948. WHO HQ is in Geneva. WHO has 194 member states. Director-General: Dr. Tedros Adhanom Ghebreyesus (Ethiopia, since 2017).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20068,
        "question": "The 78th WHA (2025) added which category of diseases to the Non-Communicable Disease (NCD) global agenda?",
        "option_a": "Eye diseases",
        "option_b": "Dental diseases",
        "option_c": "Skin diseases",
        "option_d": "Ear diseases",
        "correct_answer": "C",
        "explanation": "The 78th WHA (2025) adopted a resolution adding skin diseases (dermatological conditions) to WHO's NCD agenda. It also adopted resolutions on rare diseases. Skin conditions affect over 1.8 billion people globally and are often neglected in health systems.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20069,
        "question": "Which country reported a concerning polio outbreak in 2025, alarming global health officials?",
        "option_a": "Afghanistan",
        "option_b": "Sudan",
        "option_c": "Papua New Guinea",
        "option_d": "Democratic Republic of Congo",
        "correct_answer": "C",
        "explanation": "Papua New Guinea (PNG) reported a polio outbreak in 2025, alarming WHO and UNICEF. PNG was previously considered polio-free. WHO activated emergency vaccination campaigns. The incident highlighted risks of re-emergence in under-vaccinated populations.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    # ─── ICAO (70-72) ────────────────────────────────────────────────
    {
        "id": 20070,
        "question": "ICAO (International Civil Aviation Organization) is headquartered in which city — a common exam trap?",
        "option_a": "Chicago",
        "option_b": "London",
        "option_c": "Geneva",
        "option_d": "Montreal",
        "correct_answer": "D",
        "explanation": "ICAO HQ is in Montreal, Canada — NOT Chicago (where its founding convention was signed) and NOT Geneva. ICAO was founded by the Chicago Convention (December 7, 1944). The convention is signed in Chicago but the organization is headquartered in Montreal.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20071,
        "question": "India's performance in the ICAO Universal Safety Oversight Audit Programme (USOAP) in 2025 was described as:",
        "option_a": "Below global average",
        "option_b": "At exactly the global average",
        "option_c": "Above the global average",
        "option_d": "India was exempted from the audit",
        "correct_answer": "C",
        "explanation": "India's civil aviation safety rating was above the global average in the ICAO USOAP (Universal Safety Oversight Audit Programme) audit in 2025. This reflects improvements under DGCA and India's rapidly growing aviation sector.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20072,
        "question": "The Chicago Convention (1944) laid the foundation for international civil aviation. Which organisation was created by this convention?",
        "option_a": "IMO",
        "option_b": "ICAO",
        "option_c": "ITU",
        "option_d": "WMO",
        "correct_answer": "B",
        "explanation": "The Chicago Convention on International Civil Aviation (signed December 7, 1944) established ICAO and set the framework for international air travel, including the Five Freedoms of the Air, safety standards, and air traffic procedures. ICAO has 193 member states.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    # ─── INTERPOL (73-75) ────────────────────────────────────────────
    {
        "id": 20073,
        "question": "INTERPOL headquarters is in which city — a frequent exam trap where candidates confuse it with Paris?",
        "option_a": "Paris",
        "option_b": "Brussels",
        "option_c": "Lyon",
        "option_d": "Geneva",
        "correct_answer": "C",
        "explanation": "INTERPOL HQ is in Lyon, France — NOT Paris. This is a classic exam trap. INTERPOL (International Criminal Police Organization) was established in 1923. It has 196 member countries — more members than even the UN (193).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20074,
        "question": "INTERPOL has 196 member countries — making it the international organisation with the most members in the world. What is INTERPOL's highest-priority international alert called?",
        "option_a": "Blue Notice",
        "option_b": "Yellow Notice",
        "option_c": "Orange Notice",
        "option_d": "Red Notice",
        "correct_answer": "D",
        "explanation": "INTERPOL Red Notice is the highest-priority alert — a request to law enforcement worldwide to locate and provisionally arrest a fugitive pending extradition. India has issued Red Notices for economic fugitives like Mehul Choksi, Nirav Modi, Lalit Modi.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20075,
        "question": "The EU-India Free Trade Agreement (FTA) was concluded on which date, making it one of the world's largest bilateral trade deals?",
        "option_a": "December 15, 2025",
        "option_b": "January 27, 2026",
        "option_c": "March 5, 2026",
        "option_d": "April 1, 2026",
        "correct_answer": "B",
        "explanation": "The EU-India FTA was concluded on January 27, 2026 after 16 rounds of negotiations. It covers approximately 2 billion people (EU ~450 million + India ~1.4 billion), making it the world's largest bilateral trade deal by population. It covers goods, services, investments, GI products, and digital trade.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    # ─── MERCOSUR (76-78) ────────────────────────────────────────────
    {
        "id": 20076,
        "question": "MERCOSUR (Southern Common Market) is headquartered in which city?",
        "option_a": "Buenos Aires, Argentina",
        "option_b": "Brasília, Brazil",
        "option_c": "Montevideo, Uruguay",
        "option_d": "Asunción, Paraguay",
        "correct_answer": "C",
        "explanation": "MERCOSUR Administrative Secretariat is in Montevideo, Uruguay. Exam trap: many guess Buenos Aires (largest city) or Asunción (where the founding treaty was signed). MERCOSUR was founded by the Treaty of Asunción (March 26, 1991).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20077,
        "question": "India and MERCOSUR signed a Preferential Trade Agreement (PTA) in which year?",
        "option_a": "2004",
        "option_b": "2007",
        "option_c": "2009",
        "option_d": "2014",
        "correct_answer": "C",
        "explanation": "India-MERCOSUR Preferential Trade Agreement (PTA) was signed in 2009, offering reduced tariffs on selected goods. Full members of MERCOSUR: Argentina, Brazil, Uruguay, Paraguay. Venezuela was suspended in 2016.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    # ─── GLEX 2025 (79-81) ───────────────────────────────────────────
    {
        "id": 20078,
        "question": "The 12th GLEX (Global Space Exploration Conference) 2025 was held in which Indian city, at which venue?",
        "option_a": "Bengaluru, ISRO HQ",
        "option_b": "Hyderabad, Hi-Tex Centre",
        "option_c": "New Delhi, Bharat Mandapam",
        "option_d": "Chennai, IIT Madras",
        "correct_answer": "C",
        "explanation": "GLEX 2025 was held at Bharat Mandapam, New Delhi from May 7-9, 2025. It attracted 1,700+ participants from 36 countries — the largest IAF Global Conference ever held. Organised by IAF + ISRO + DSA + ASI (Italy).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20079,
        "question": "What was the official theme of GLEX 2025 (Global Space Exploration Conference) held in New Delhi?",
        "option_a": "Exploring the Final Frontier",
        "option_b": "Space for All: A Sustainable Future",
        "option_c": "Reaching New Worlds: A Space Exploration Renaissance",
        "option_d": "Towards Mars: Humanity's Next Giant Leap",
        "correct_answer": "C",
        "explanation": "GLEX 2025 theme was 'Reaching New Worlds: A Space Exploration Renaissance.' India showcased Gaganyaan mission, Chandrayaan-4 and Bharatiya Antariksha Station (BAS) plans at this conference. 1,700+ participants from 36 countries attended.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20080,
        "question": "GLEX 2025 (New Delhi) was organised jointly by which three space agencies/bodies?",
        "option_a": "ISRO, NASA, and ESA",
        "option_b": "IAF, ISRO, and ASI (Italian Space Agency)",
        "option_c": "ISRO, CNSA, and Roscosmos",
        "option_d": "IAF, JAXA, and ISRO",
        "correct_answer": "B",
        "explanation": "GLEX 2025 was organised by IAF (International Astronautical Federation), ISRO (India), Department of Space Activities (DSA), and ASI — Agenzia Spaziale Italiana (Italian Space Agency). IAF is the global federation of space agencies and industry bodies.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    # ─── UNOC3 (81-82) ───────────────────────────────────────────────
    {
        "id": 20081,
        "question": "The Third United Nations Ocean Conference (UNOC3) was held in which city in June 2025?",
        "option_a": "Paris",
        "option_b": "Lisbon",
        "option_c": "Monaco",
        "option_d": "Nice",
        "correct_answer": "D",
        "explanation": "UNOC3 was held in Nice, France from June 9-13, 2025. It was co-hosted by France and Costa Rica. The conference addressed SDG 14 (Life Below Water) and launched the Blue NDC Challenge to integrate ocean goals into countries' climate commitments.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20082,
        "question": "UNOC3 primarily addresses which UN Sustainable Development Goal (SDG)?",
        "option_a": "SDG 13 — Climate Action",
        "option_b": "SDG 14 — Life Below Water",
        "option_c": "SDG 15 — Life on Land",
        "option_d": "SDG 6 — Clean Water and Sanitation",
        "correct_answer": "B",
        "explanation": "UNOC3 focused on SDG 14 — Life Below Water. Key outcomes: Blue NDC Challenge (France+Brazil — integrate ocean commitments into NDCs), progress on BBNJ (High Seas) Treaty ratification, and establishing a permanent UN Ocean Conference mechanism.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    # ─── Tricky/Mixed (83-86) ─────────────────────────────────────────
    {
        "id": 20083,
        "question": "Which city hosts the most number of international organisations in the world?",
        "option_a": "Brussels",
        "option_b": "New York",
        "option_c": "Geneva",
        "option_d": "Vienna",
        "correct_answer": "C",
        "explanation": "Geneva hosts the most international organisations, including WHO, WTO, ILO, UNHCR, WIPO, WMO, ITU, Red Cross (ICRC), and many UN offices. Geneva is often called the 'Capital of International Peace.' Brussels comes 2nd (NATO, EU HQ).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20084,
        "question": "Rome hosts three international food-related agencies. Which of the following is NOT one of them?",
        "option_a": "FAO (Food and Agriculture Organization)",
        "option_b": "WFP (World Food Programme)",
        "option_c": "IFAD (International Fund for Agricultural Development)",
        "option_d": "CGIAR (Consultative Group on International Agricultural Research)",
        "correct_answer": "D",
        "explanation": "Rome hosts FAO, WFP, and IFAD — the three UN food-related agencies. CGIAR is not a UN body in Rome. The Rome-based trio: FAO (promotes food security), WFP (food aid), IFAD (agricultural investment in developing countries).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20085,
        "question": "The 'Five Eyes' intelligence-sharing alliance consists of which five countries?",
        "option_a": "G7 minus Japan and Italy",
        "option_b": "USA, UK, Canada, Australia, New Zealand",
        "option_c": "QUAD nations plus UK",
        "option_d": "NATO's founding five members",
        "correct_answer": "B",
        "explanation": "Five Eyes (FVEY) = USA, UK, Canada, Australia, New Zealand — all English-speaking countries sharing intelligence since the UKUSA Agreement (1946). India is not a Five Eyes member but cooperates with the alliance. India is sometimes referred to as a 'Sixth Eye' partner.",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
    {
        "id": 20086,
        "question": "The 'Blue NDC Challenge' launched at UNOC3 2025 (Nice) primarily calls on countries to do what?",
        "option_a": "Fund deep-sea mining research",
        "option_b": "Integrate ocean-related targets into their climate commitments (NDCs)",
        "option_c": "Ban deep-sea trawling globally",
        "option_d": "Establish a Blue Carbon trading market",
        "correct_answer": "B",
        "explanation": "The Blue NDC Challenge (launched by France and Brazil at UNOC3, Nice 2025) calls on countries to integrate ocean-related targets into their Nationally Determined Contributions (NDCs) under the Paris Agreement. This links climate action with ocean conservation (SDG 14).",
        "folder": "AP_HC",
        "topic": "International_Current_Affairs",
    },
]


def get_db():
    if USE_POSTGRES:
        import psycopg2
        return psycopg2.connect(DATABASE_URL)
    db_path = os.path.join(os.path.dirname(__file__), "database.db")
    return sqlite3.connect(db_path)


def seed():
    conn = get_db()
    ph = "%s" if USE_POSTGRES else "?"
    inserted = 0
    skipped = 0
    try:
        cur = conn.cursor()
        for q in INTL_MCQS:
            cur.execute(
                f"SELECT COUNT(*) FROM questions WHERE id={ph}", (q["id"],)
            )
            if cur.fetchone()[0] > 0:
                skipped += 1
                continue
            cur.execute(
                f"""INSERT INTO questions
                    (id, question, option_a, option_b, option_c, option_d,
                     correct_answer, explanation, folder, topic)
                    VALUES ({ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph})""",
                (
                    q["id"], q["question"],
                    q["option_a"], q["option_b"], q["option_c"], q["option_d"],
                    q["correct_answer"], q["explanation"],
                    q["folder"], q["topic"],
                ),
            )
            inserted += 1
        conn.commit()
        print(f"[seed_intl_orgs] Inserted={inserted}, Skipped(existing)={skipped}")
    finally:
        conn.close()


if __name__ == "__main__":
    seed()
