# seed_polity_ch18.py
# Chapter 18 — Governor
# Total Sections: 8 | Total MCQs: 57 | PYQs: 5
# Sections:
#   0 — Appointment & Qualifications (8 MCQs)
#   1 — Term & Removal (8 MCQs)
#   2 — Executive Powers (8 MCQs)
#   3 — Legislative Powers (8 MCQs)
#   4 — Financial & Judicial Powers (7 MCQs)
#   5 — Discretionary Powers (6 MCQs)
#   6 — Governor vs President Comparison (6 MCQs)
#   7 — Miscellaneous / Constitutional Provisions (6 MCQs)

_CH = 18
_SUBJECT = 'GK'
_TOPIC   = 'Indian_Polity'
_TITLE_TE = 'గవర్నర్'
_TITLE_EN = 'Governor'
_PAGES    = 'Ch.18 (Lakshmikanth)'

_SECTIONS = [
    "నియామకం & అర్హతలు",
    "పదవీ కాలం & తొలగింపు",
    "కార్యనిర్వాహక అధికారాలు",
    "శాసన అధికారాలు",
    "ఆర్థిక & న్యాయ అధికారాలు",
    "విచక్షణ అధికారాలు",
    "గవర్నర్ vs రాష్ట్రపతి పోలిక",
    "విభిన్న రాజ్యాంగ నిబంధనలు",
]

_MCQS = [    (0,
     'easy',
     'Who appoints the Governor of a State?\nతెలుగు: రాష్ట్ర గవర్నర్\u200cను నియమించే అధికారం ఎవరికి ఉంది?',
     'Chief Minister / ముఖ్యమంత్రి',
     'President / రాష్ట్రపతి',
     'Prime Minister / ప్రధానమంత్రి',
     'Supreme Court / సుప్రీం కోర్ట్',
     'b',
     'Art.155: Governor is appointed by the President. / అనుచ్ఛేదం 155: గవర్నర్\u200cను రాష్ట్రపతి నియమిస్తారు.'),
    (0,
     'easy',
     'Minimum age for Governor?\nతెలుగు: గవర్నర్ అర్హతలలో వయస్సు పరిమితి ఎంత?',
     '25 years / 25 సంవత్సరాలు',
     '30 years / 30 సంవత్సరాలు',
     '35 years / 35 సంవత్సరాలు',
     '40 years / 40 సంవత్సరాలు',
     'c',
     'Art.157: Governor must be at least 35 years of age. / అనుచ్ఛేదం 157: గవర్నర్ కనీసం 35 సంవత్సరాల వయస్సు ఉండాలి.'),
    (0,
     'medium',
     "Which is correct about Governor's qualifications?\nతెలుగు: గవర్నర్ అర్హతలలో ఏది నిజం?",
     'Must be MP / పార్లమెంటు సభ్యుడిగా ఉండాలి',
     'Indian citizen and 35 years / భారత పౌరుడు మరియు 35 ఏళ్ళు',
     'Must be IAS officer / IAS అధికారిగా ఉండాలి',
     'Must be legal expert / న్యాయ నిపుణుడుగా ఉండాలి',
     'b',
     'Art.157: Governor must be Indian citizen and not less than 35 years. / అనుచ్ఛేదం 157: గవర్నర్ భారత పౌరుడు మరియు 35 సంవత్సరాలకు పైగా వయస్సు ఉండాలి.'),
    (0,
     'hard',
     'If Governor-appointee is MP/MLA, what must happen?\nతెలుగు: గవర్నర్ పార్లమెంటు/రాష్ట్ర శాసనసభ సభ్యుడుగా ఉంటే నియామకానికి ముందు ఏం జరగాలి?',
     'Resign after appointment / నియామకానంతర రాజీనామా',
     'No resignation needed / నియామకానికి ముందు రాజీనామా అవసరం లేదు',
     'Must resign before appointment / నియామకానికి ముందే రాజీనామా చేయాలి',
     'Resign within 6 months / 6 నెలల్లో రాజీనామా',
     'c',
     'రాష్ట్ర శాసనసభ సభ్యత్వం తనంతట తానే రద్దవుతుంది; ఆచరణలో ముందే రాజీనామా. / Membership auto-terminates; in practice, resign before appointment. / గవర్నర్ నియామక తేదీ నుండి పార్లమెంటు'),
    (0,
     'medium',
     "Who is disqualified for Governor's post?\nతెలుగు: గవర్నర్ పదవికి అర్హుడు కానివాడు ఎవరు?",
     'Retired IAS officer / రిటైర్డ్ IAS అధికారి',
     'Judge / న్యాయమూర్తి',
     'Resident of that state / ఆ రాష్ట్ర నివాసి',
     'Retired General / రిటైర్డ్ జనరల్',
     'c',
     'Convention: Governor should not be from the same state (outsider convention). / అనుచ్ఛేదం 158(1) ప్రకారం గవర్నర్ నియామకమయ్యే రాష్ట్రానికి చెందినవాడు కాకుండా వేరే రాష్ట్రానికి చెందినవాడు అయి ఉండాలి (ఆచారం).'),
    (0,
     'medium',
     "Which Commission recommended consulting CM before Governor's appointment?\nతెలుగు: గవర్నర్ నియామకంలో ఆచారం ప్రకారం ముఖ్యమంత్రికి ముందుగా సంప్రదించాలని ఏ సంఘం సిఫారసు చేసింది?",
     'Sarkaria Commission / సర్కారియా కమిషన్',
     'Punchhi Commission / పుంఛి కమిషన్',
     'Rajamannar Committee / రాజమన్నార్ కమిటీ',
     'Venkatachalaiah Commission / వెంకటాచలయ్య కమిషన్',
     'a',
     "Sarkaria Commission (1988): Recommended CM consultation before Governor's appointment. / సర్కారియా కమిషన్ (1988): గవర్నర్ నియామకానికి ముందు రాష్ట్ర ముఖ్యమంత్రిని సంప్రదించాలని సిఫారసు చేసింది."),
    (0,
     'hard',
     'Can same person serve as Governor of two states simultaneously?\nతెలుగు: ఒకే వ్యక్తి ఒకేసారి రెండు రాష్ట్రాలకు గవర్నర్\u200cగా పని చేయవచ్చా?',
     'Never / ఎప్పుడూ కాదు',
     'Yes, if President assigns additional charge / అవును, రాష్ట్రపతి అదనపు బాధ్యత అప్పగిస్తే',
     'Only for neighbouring states / కేవలం పొరుగు రాష్ట్రాలకు మాత్రమే',
     'Only with RS approval / రాజ్యసభ ఆమోదంతో మాత్రమే',
     'b',
     'Art.153 proviso: Same person can be Governor of two+ states (7th Amendment 1956). / అనుచ్ఛేదం 153 నిబంధన: ఒకే వ్యక్తి రెండు రాష్ట్రాలకు గవర్నర్\u200cగా పని చేయవచ్చు (7వ సవరణ 1956 ద్వారా).'),
    (0,
     'easy',
     'Before whom does Governor take oath?\nతెలుగు: గవర్నర్ ప్రమాణ స్వీకారం ఎవరి ముందు చేస్తారు?',
     'President / రాష్ట్రపతి',
     'Chief Minister / ముఖ్యమంత్రి',
     'Chief Justice of High Court / హైకోర్టు ప్రధాన న్యాయమూర్తి',
     'Speaker / స్పీకర్',
     'c',
     'Art.159: Governor takes oath before the Chief Justice of the concerned High Court. / అనుచ్ఛేదం 159: గవర్నర్ ఆ రాష్ట్ర హైకోర్టు ప్రధాన న్యాయమూర్తి ముందు ప్రమాణం చేస్తారు.'),
    (1,
     'easy',
     'What is the term of a Governor?\nతెలుగు: గవర్నర్ పదవీ కాలం ఎంత?',
     '3 years / 3 సంవత్సరాలు',
     '4 years / 4 సంవత్సరాలు',
     '5 years / 5 సంవత్సరాలు',
     '6 years / 6 సంవత్సరాలు',
     'c',
     'Art.156(1): Governor holds office for a term of 5 years. / అనుచ్ఛేదం 156(1): గవర్నర్ 5 సంవత్సరాల పదవీ కాలం పాటు పని చేస్తారు.'),
    (1,
     'medium',
     'Who can remove a Governor?\nతెలుగు: గవర్నర్\u200cను ఎవరు తొలగించవచ్చు?',
     'State Legislature / రాష్ట్ర శాసనసభ',
     'President / రాష్ట్రపతి',
     'PM directly / ప్రధానమంత్రి నేరుగా',
     'Supreme Court / సుప్రీం కోర్ట్',
     'b',
     "Art.156(1): Governor holds office at President's pleasure — President can remove. / అనుచ్ఛేదం 156(1): గవర్నర్ రాష్ట్రపతి సంతోషం ఉన్నంత కాలం పదవిలో ఉంటారు. రాష్ట్రపతి తొలగించవచ్చు."),
    (1,
     'hard',
     'Constitutional constraints on removing a Governor?\nతెలుగు: గవర్నర్ తొలగింపులో రాజ్యాంగ పరిమితులు ఏమిటి?',
     'Can be removed without reason / కారణం చెప్పకుండా తొలగించవచ్చు',
     'Impeachment required / అభిశంసన ప్రక్రియ అవసరం',
     'Reasons to President — no specific grounds in Constitution / రాష్ట్రపతికి కారణాలు చెప్పాలి — రాజ్యాంగంలో నిర్దిష్ట నిబంధనలు లేవు',
     'HC judgment required / హైకోర్టు తీర్పు అవసరం',
     'a',
     'No specific grounds in Constitution; SC in B.P. Singhal case ruled reasons must exist. / రాజ్యాంగం తొలగింపుకు నిర్దిష్ట కారణాలు చెప్పలేదు. రాష్ట్రపతి సంతోషం ఆధారంగా తొలగించవచ్చు — అయితే B.P. Singhal కేసులో SC కారణాలు ఉండాలని తీర్పు.'),
    (1,
     'medium',
     'To whom does Governor submit resignation?\nతెలుగు: గవర్నర్ రాజీనామా ఎవరికి ఇస్తారు?',
     'Chief Minister / ముఖ్యమంత్రికి',
     'President / రాష్ట్రపతికి',
     'LS Speaker / లోక్\u200cసభ స్పీకర్\u200cకు',
     'HC Chief Justice / హైకోర్టు CJకి',
     'b',
     'Art.156(2): Governor resigns by writing to the President. / అనుచ్ఛేదం 156(2): గవర్నర్ రాజీనామాను రాష్ట్రపతికి ఇస్తారు.'),
    (1,
     'easy',
     "Can Lieutenant Governor discharge Governor's functions?\nతెలుగు: గవర్నర్ పదవి ఖాళీగా ఉంటే 'లెఫ్టినెంట్ గవర్నర్' పని చేయగలరా?",
     'Yes / అవును',
     'No / లేదు',
     'Only partially / పరిమితంగా మాత్రమే',
     'With state assembly approval / రాష్ట్ర అసెంబ్లీ ఆమోదంతో',
     'b',
     'No LG for states; HC CJ or another Governor given additional charge. / గవర్నర్ పదవి ఖాళీగా ఉంటే రాష్ట్రపతి హైకోర్టు CJని లేదా ఇతర గవర్నర్\u200cని అదనపు బాధ్యత ఇస్తారు — Lieutenant Governor అనే పదవి రాష్ట్రాల్లో లేదు (UT లో మాత్రమే).'),
    (1,
     'hard',
     "When does Governor's office fall vacant?\nతెలుగు: గవర్నర్ పదవి ఎప్పుడు ఖాళీ అవుతుంది?",
     'Only after 5 years / 5 సంవత్సరాల తర్వాత మాత్రమే',
     'Death, resignation, removal or expiry of term / మరణం, రాజీనామా, తొలగింపు లేదా పదవీ కాలం ముగిసినప్పుడు',
     'When LS dissolves / లోక్\u200cసభ రద్దు అయినప్పుడు',
     'When CM changes / ముఖ్యమంత్రి మారినప్పుడు',
     'b',
     "Governor's office vacates on death, resignation, removal by President, or term expiry. / గవర్నర్ పదవి మరణం, రాజీనామా, రాష్ట్రపతి తొలగింపు లేదా 5 సంవత్సరాల పదవీ కాలం ముగిసినప్పుడు ఖాళీ అవుతుంది."),
    (1,
     'medium',
     'How long can Governor continue after term expiry?\nతెలుగు: పదవీ కాలం ముగిసిన తర్వాత గవర్నర్ ఎంత కాలం పని చేయగలరు?',
     '3 more months / మరో 3 నెలలు',
     '6 more months / మరో 6 నెలలు',
     'Until successor takes charge / వారసుడు పదవి చేపట్టే వరకు',
     'Not even one day / ఒక్క రోజు కూడా కాదు',
     'c',
     'Art.156(1) proviso: Governor continues until successor assumes charge. / అనుచ్ఛేదం 156(1) నిబంధన: వారసుడు పదవి చేపట్టే వరకు గవర్నర్ పదవిలో కొనసాగవచ్చు.'),
    (1,
     'easy',
     'Convention: A Governor should not hold office in same state for more than?\nతెలుగు: గవర్నర్ నియామకంలో ఆచారం ప్రకారం ఒక వ్యక్తి ఒక రాష్ట్రంలో ఎంత కాలానికంటే ఎక్కువ గవర్నర్\u200cగా ఉండకూడదు?',
     '1 term / 1 పదవీ కాలం',
     '2 terms / 2 పదవీ కాలాలు',
     '3 terms / 3 పదవీ కాలాలు',
     'No constitutional limit / రాజ్యాంగ పరిమితి లేదు',
     'd',
     'No constitutional limit on terms — can be reappointed. / రాజ్యాంగంలో పదవీ కాల పరిమితి లేదు — ఒకే రాష్ట్రంలో పదే పదే గవర్నర్\u200cగా ఉండవచ్చు.'),
    (2,
     'easy',
     'Does Governor appoint Chief Minister?\nతెలుగు: రాష్ట్ర ముఖ్యమంత్రిని నియమించే అధికారం గవర్నర్\u200cకు ఉందా?',
     'No / లేదు',
     'Yes / అవును',
     "With President's approval / రాష్ట్రపతి ఆమోదంతో",
     'Vidhan Sabha elects / విధానసభ ఎన్నిక చేస్తుంది',
     'b',
     "Art.164(1): Governor appoints CM; on CM's advice appoints other ministers. / అనుచ్ఛేదం 164(1): గవర్నర్ ముఖ్యమంత్రిని నియమిస్తారు; ముఖ్యమంత్రి సలహాపై ఇతర మంత్రులను నియమిస్తారు."),
    (2,
     'medium',
     'Art. for Governor appointing Advocate General of State?\nతెలుగు: గవర్నర్ రాష్ట్ర అడ్వకేట్ జనరల్\u200cను నియమించే అధికారం ఏ అనుచ్ఛేదంలో ఉంది?',
     'Art.161 / అనుచ్ఛేదం 161',
     'Art.165 / అనుచ్ఛేదం 165',
     'Art.167 / అనుచ్ఛేదం 167',
     'Art.170 / అనుచ్ఛేదం 170',
     'b',
     'Art.165: Governor appoints the Advocate General of the State. / అనుచ్ఛేదం 165: గవర్నర్ రాష్ట్ర అడ్వకేట్ జనరల్\u200cను నియమిస్తారు.'),
    (2,
     'easy',
     'Who appoints Chairman of State PSC?\nతెలుగు: రాష్ట్ర పబ్లిక్ సర్వీస్ కమిషన్ అధ్యక్షుడిని నియమించే వ్యక్తి ఎవరు?',
     'Chief Minister / ముఖ్యమంత్రి',
     'Governor / గవర్నర్',
     'President / రాష్ట్రపతి',
     'UPSC Chairman',
     'b',
     'Art.316: Governor appoints Chairman of State PSC. / అనుచ్ఛేదం 316: గవర్నర్ రాష్ట్ర పబ్లిక్ సర్వీస్ కమిషన్ అధ్యక్షుడిని నియమిస్తారు.'),
    (2,
     'medium',
     "Who reports to President for imposing President's Rule (Art.356)?\nతెలుగు: రాష్ట్రంలో రాష్ట్రపతి పాలన (Art.356) విధించమని రాష్ట్రపతికి నివేదించే వ్యక్తి ఎవరు?",
     'Chief Minister / ముఖ్యమంత్రి',
     'HC CJ / హైకోర్టు CJ',
     'Governor / గవర్నర్',
     'RS leader / రాజ్యసభ నాయకుడు',
     'c',
     "Art.356: President imposes President's Rule based on Governor's report. / అనుచ్ఛేదం 356: గవర్నర్ నివేదిక ఆధారంగా రాష్ట్రపతి రాష్ట్రపతి పాలన విధిస్తారు."),
    (2,
     'hard',
     "Which Art states that civil servants hold office at 'pleasure' of Governor?\nతెలుగు: గవర్నర్ అధికారులు 'రాష్ట్రపతి సంతోషం వద్ద' (pleasure doctrine) కింద ఉంటారు — ఇది ఏ అనుచ్ఛేదం?",
     'Art.154 / అనుచ్ఛేదం 154',
     'Art.162 / అనుచ్ఛేదం 162',
     'Art.309 / అనుచ్ఛేదం 309',
     'Art.310 / అనుచ్ఛేదం 310',
     'd',
     'Art.310: Civil servants hold office during pleasure of President/Governor. / అనుచ్ఛేదం 310: కేంద్ర-రాష్ట్ర పౌర సేవకులు రాష్ట్రపతి/గవర్నర్ సంతోషం వద్ద పదవిలో ఉంటారు.'),
    (2,
     'medium',
     "Who described the Governor as 'Constitutional Sentinel'?\nతెలుగు: గవర్నర్\u200cను 'రాజ్యాంగ కాపలాదారు' (Constitutional Sentinel) అని అభివర్ణించిన పండితుడు ఎవరు?",
     'B.R. Ambedkar / బి.ఆర్. అంబేడ్కర్',
     'Nehru / జవహర్\u200cలాల్ నెహ్రూ',
     'K.M. Munshi / కె.ఎం. మున్షీ',
     'Sir Alladi / సర్ అలాడి కృష్ణస్వామి అయ్యర్',
     'c',
     "K.M. Munshi described Governor as 'Constitutional Sentinel' — guardian of constitutional values. / K.M. Munshi: గవర్నర్ 'రాజ్యాంగ కాపలాదారు' (Constitutional Sentinel) — రాజ్యాంగ విలువలు కాపాడే బాధ్యత గవర్నర్\u200cకు ఉంటుంది. B.R. Ambedkar గవర్నర్\u200cను Centre-State link గా చూశారు."),
    (2,
     'easy',
     'All executive actions of state government are taken in whose name?\nతెలుగు: రాష్ట్ర ప్రభుత్వ అన్ని కార్యనిర్వాహక చర్యలు ఏ పేరిట తీసుకోబడతాయి?',
     'Chief Minister / ముఖ్యమంత్రి',
     'Governor / గవర్నర్',
     'President / రాష్ట్రపతి',
     'State CoM / రాష్ట్ర మంత్రిమండలి',
     'b',
     "Art.154: Executive power of state vested in Governor; all actions taken in Governor's name. / అనుచ్ఛేదం 154: రాష్ట్ర కార్యనిర్వాహక అధికారం గవర్నర్\u200cకు ఉంటుంది; అన్ని చర్యలు గవర్నర్ పేరిట."),
    (2,
     'hard',
     'In case of hung assembly, whom should Governor invite to form government?\nతెలుగు: గవర్నర్ హంగ్ అసెంబ్లీలో ప్రభుత్వ ఏర్పాటు ఆహ్వానించేటప్పుడు ఎవరిని పిలవాలి?',
     'Single largest party / అతిపెద్ద పార్టీ',
     'Pre-poll alliance / ముందుగా ఏర్పాటైన కూటమి',
     'Person most likely to command majority in House / అసెంబ్లీలో అత్యధిక మద్దతు నిరూపించగలిగే వ్యక్తి',
     'Previous CM / అంతకు ముందు ముఖ్యమంత్రి',
     'c',
     'S.R. Bommai 1994: Invite person most likely to command Assembly majority — test on floor. / S.R. బొమ్మై కేసు (1994): గవర్నర్ అసెంబ్లీలో అత్యధిక మద్దతు నిరూపించగలిగిన వ్యక్తిని ఆహ్వానించాలి — ఊహ ఆధారంగా కాదు.'),
    (3,
     'easy',
     'Can Governor summon state legislature sessions?\nతెలుగు: గవర్నర్ రాష్ట్ర శాసనసభ సమావేశాలు ఏర్పాటు చేయగలరా?',
     'No / లేదు',
     'Yes / అవును',
     "Only with President's approval / రాష్ట్రపతి ఆమోదంతో మాత్రమే",
     'Only CM / ముఖ్యమంత్రి మాత్రమే',
     'b',
     'Art.174: Governor summons, prorogues, dissolves state legislature. / అనుచ్ఛేదం 174: గవర్నర్ రాష్ట్ర శాసనసభ సమావేశాలు ఏర్పాటు చేయడం, వాయిదా వేయడం, రద్దు చేయడం చేయవచ్చు.'),
    (3,
     'medium',
     'How many members can Governor nominate to Vidhan Parishad?\nతెలుగు: గవర్నర్ రాష్ట్ర శాసనసభకు ఎన్ని సభ్యులను నామినేట్ చేయగలరు (విధానపరిషత్\u200cకు)?',
     '6 / 6 మంది',
     '1/6th / 1/6 వంతు',
     '12 / 12 మంది',
     'Number decided by President / రాష్ట్రపతి నిర్ణయించే సంఖ్య',
     'b',
     'Art.171(5): Governor nominates 1/6th of Vidhan Parishad members. / అనుచ్ఛేదం 171(5): గవర్నర్ విధానపరిషత్ (Legislative Council) సభ్యుల 1/6 వంతు నామినేట్ చేయగలరు.'),
    (3,
     'easy',
     'What can Governor do with a Bill passed by state legislature?\nతెలుగు: రాష్ట్ర శాసనసభ ఆమోదించిన బిల్లుకు గవర్నర్ ఏమి చేయవచ్చు?',
     'Only assent or refer to President / ఆమోదించడం లేదా రాష్ట్రపతికి సూచించడం మాత్రమే',
     'Assent, withhold, return or reserve for President / ఆమోదించడం, తిరస్కరించడం, తిరిగి పంపడం లేదా రాష్ట్రపతి పరిశీలనకు నివేదించడం',
     'Only assent / ఆమోదించడం మాత్రమే',
     'Only reject / తిరస్కరించడం మాత్రమే',
     'b',
     'Art.200: Governor may assent, withhold assent, return (except Money Bill), or reserve for President. / అనుచ్ఛేదం 200: గవర్నర్ బిల్లుకు ఆమోదం ఇవ్వవచ్చు, ఆమోదం నిలిపివేయవచ్చు, తిరిగి పంపవచ్చు, లేదా రాష్ట్రపతి పరిశీలనకు నివేదించవచ్చు.'),
    (3,
     'hard',
     'Can Governor return a Money Bill?\nతెలుగు: గవర్నర్ మనీ బిల్లును తిరిగి పంపవచ్చా?',
     'Yes / అవును',
     'No / లేదు',
     "With President's permission / రాష్ట్రపతి అనుమతితో",
     'Only in emergency / అత్యవసరంలో మాత్రమే',
     'b',
     'Art.200: Governor cannot return a Money Bill — must either assent or reserve for President. / అనుచ్ఛేదం 200: Money Bill ని గవర్నర్ తిరిగి పంపే అధికారం లేదు — ఆమోదించాలి లేదా రాష్ట్రపతికి నివేదించాలి.'),
    (3,
     'medium',
     'Which Article empowers Governor to promulgate Ordinance?\nతెలుగు: గవర్నర్ ఆర్డినెన్స్ జారీ చేయగల అనుచ్ఛేదం ఏది?',
     'Art.123 / అనుచ్ఛేదం 123',
     'Art.213 / అనుచ్ఛేదం 213',
     'Art.200 / అనుచ్ఛేదం 200',
     'Art.174 / అనుచ్ఛేదం 174',
     'b',
     'Art.213: Governor can promulgate Ordinances when legislature is not in session. / అనుచ్ఛేదం 213: శాసనసభ సమావేశంలో లేనప్పుడు గవర్నర్ ఆర్డినెన్స్ జారీ చేయగలరు.',
     'APPSC'),
    (3,
     'medium',
     'Within how long must an Ordinance be approved after legislature assembles?\nతెలుగు: గవర్నర్ ఆర్డినెన్స్ శాసనసభ సమావేశమైన తర్వాత ఎంత కాలంలో ఆమోదం పొందాలి?',
     '3 months / 3 నెలలు',
     '6 weeks / 6 వారాలు',
     '2 months / 2 నెలలు',
     '1 month / 1 నెల',
     'b',
     'Art.213(2)(a): Ordinance must be approved within 6 weeks of legislature reassembling. / అనుచ్ఛేదం 213(2)(a): ఆర్డినెన్స్ శాసనసభ సమావేశమైన తర్వాత 6 వారాల లోపు ఆమోదం పొందాలి.'),
    (3,
     'easy',
     "How is Governor's Ordinance power compared to President's?\nతెలుగు: గవర్నర్ ఆర్డినెన్స్ జారీ చేయడంలో రాష్ట్రపతితో పోలిక ఏమిటి?",
     "Governor's power is greater / గవర్నర్ అధికారం ఎక్కువ",
     'Only State List matters / రాష్ట్రపతి అధికారానికి సంబంధించిన State List మాత్రమే',
     'President Art.123 similar; Governor Art.213 — for State List only / రాష్ట్రపతి Art.123 వంటిదే; గవర్నర్ Art.213 — రాష్ట్ర జాబితాకు మాత్రమే',
     'Governor cannot issue Ordinances / గవర్నర్ ఆర్డినెన్స్ జారీ చేయలేరు',
     'c',
     'President: Art.123 (Union List); Governor: Art.213 (State List). Governor needs Presidential sanction in some cases. / రాష్ట్రపతి Art.123 — Union List; గవర్నర్ Art.213 — State List. కొన్ని మాత్రల్లో గవర్నర్ రాష్ట్రపతి అనుమతి అవసరం.'),
    (3,
     'hard',
     'In which cases does Governor need prior Presidential sanction for Ordinance?\nతెలుగు: గవర్నర్ ఆర్డినెన్స్ జారీ చేయడానికి రాష్ట్రపతి పూర్వ అనుమతి ఏ విషయాల్లో అవసరం?',
     'Never required / ఎప్పుడూ అవసరం లేదు',
     'Matters requiring Presidential assent for Bills / అసెంబ్లీ ఆమోదం అవసరమయ్యే అంశాలు',
     'State List matters only / రాష్ట్ర జాబితా అంశాలు',
     'Always required / ఎల్లప్పుడూ అవసరం',
     'b',
     'Art.213(1) proviso: Presidential sanction required for Ordinances on matters needing Presidential assent for Bills. / Art.213(1) నిబంధన: బిల్లుకు రాష్ట్రపతి ఆమోదం అవసరమయ్యే విషయాల్లో ఆర్డినెన్స్\u200cకు రాష్ట్రపతి పూర్వ అనుమతి అవసరం.'),
    (4,
     'easy',
     'Whose recommendation is needed to introduce State Budget in legislature?\nతెలుగు: రాష్ట్ర బడ్జెట్\u200cను శాసనసభలో ప్రవేశపెట్టేందుకు ఎవరి సిఫారసు అవసరం?',
     'Chief Minister / ముఖ్యమంత్రి',
     'Finance Minister / ఆర్థిక మంత్రి',
     'Governor / గవర్నర్',
     'President / రాష్ట్రపతి',
     'c',
     "Art.202(1): Annual Financial Statement (Budget) laid before legislature by Governor's direction. / అనుచ్ఛేదం 202(1): రాష్ట్ర వార్షిక ఆర్థిక నివేదిక (బడ్జెట్) గవర్నర్ సిఫారసుపై శాసనసభలో ప్రవేశపెట్టబడుతుంది."),
    (4,
     'medium',
     'Under which Article does Governor grant Pardon?\nతెలుగు: క్షమాభిక్ష (Pardon) గవర్నర్ ఏ అనుచ్ఛేదం కింద ఇస్తారు?',
     'Art.72 / అనుచ్ఛేదం 72',
     'Art.161 / అనుచ్ఛేదం 161',
     'Art.163 / అనుచ్ఛేదం 163',
     'Art.165 / అనుచ్ఛేదం 165',
     'b',
     "Art.161: Governor's pardoning powers for offences against state laws. / అనుచ్ఛేదం 161: గవర్నర్ రాష్ట్ర చట్టాలకు సంబంధించిన నేరాలకు క్షమాభిక్ష, జరిమానా తగ్గింపు మొదలైన అధికారాలు ఉంటాయి."),
    (4,
     'hard',
     'Key difference between Governor (Art.161) and President (Art.72) pardoning powers?\nతెలుగు: గవర్నర్ (Art.161) మరియు రాష్ట్రపతి (Art.72) క్షమాభిక్ష అధికారాల మధ్య తేడా ఏమిటి?',
     'Governor can pardon death sentences / గవర్నర్ మరణ శిక్షలను మాఫీ చేయగలరు',
     'Only President can pardon death sentences / రాష్ట్రపతి మాత్రమే మరణ శిక్షలను మాఫీ చేయగలరు',
     'Both equal / రెండూ సమానం',
     'Governor has court martial power / గవర్నర్ కోర్ట్ మార్షల్ అధికారం ఉంది',
     'b',
     'President alone can: pardon death sentence, court martial offences, Union law offences. Governor lacks these two. / తేడాలు: రాష్ట్రపతి మాత్రమే (1) మరణ శిక్ష మాఫీ (2) కోర్ట్ మార్షల్ (3) Union చట్టాలు పరిధి. గవర్నర్ వీటిలో మొదటి రెండు అధికారాలు లేవు.'),
    (4,
     'medium',
     "Governor's role in HC judges' appointment?\nతెలుగు: రాష్ట్ర హైకోర్టు న్యాయమూర్తుల నియామకంలో గవర్నర్ పాత్ర ఏమిటి?",
     'Directly appoints / నేరుగా నియమిస్తారు',
     'Consulted by President / రాష్ట్రపతికి సంప్రదించబడతారు',
     'Nominates / నామినేట్ చేస్తారు',
     'No role / ఎలాంటి పాత్ర లేదు',
     'b',
     'Art.217: President appoints HC judges after consulting CJI and Governor. / అనుచ్ఛేదం 217: రాష్ట్ర హైకోర్టు న్యాయమూర్తులను రాష్ట్రపతి CJI మరియు గవర్నర్\u200cతో సంప్రదించి నియమిస్తారు.'),
    (4,
     'easy',
     'State Finance Commission is constituted on whose order?\nతెలుగు: రాష్ట్ర ఆర్థిక సంఘం (State Finance Commission) ఎవరి ఆదేశంపై ఏర్పాటవుతుంది?',
     'Chief Minister / ముఖ్యమంత్రి',
     'Governor / గవర్నర్',
     'President / రాష్ట్రపతి',
     'Union Finance Minister / కేంద్ర ఆర్థిక మంత్రి',
     'b',
     'Art.243-I: Governor constitutes State Finance Commission for Panchayati Raj finance. / అనుచ్ఛేదం 243-I: గవర్నర్ రాష్ట్ర ఆర్థిక సంఘాన్ని ఏర్పాటు చేస్తారు — పంచాయతీ సంస్థలకు నిధుల కేటాయింపు.'),
    (4,
     'medium',
     'Can Governor withhold assent to a Money Bill passed by state legislature?\nతెలుగు: రాష్ట్ర శాసనసభ ఆమోదించిన మనీ బిల్లుకు గవర్నర్ ఆమోదం నిరాకరించగలరా?',
     'Yes / అవును',
     'No / లేదు',
     "Only on President's instruction / రాష్ట్రపతి ఆజ్ఞతో మాత్రమే",
     'Can only reserve for President / కేవలం రాష్ట్రపతికి నివేదించవచ్చు',
     'd',
     'Art.200: Governor cannot return Money Bill — must assent or reserve for Presidential consideration. / అనుచ్ఛేదం 200: గవర్నర్ మనీ బిల్లును తిరిగి పంపలేరు; ఆమోదించాలి లేదా రాష్ట్రపతికి నివేదించవచ్చు.'),
    (4,
     'hard',
     'Art. enabling Governor to reserve a Bill for Presidential consideration on own discretion?\nతెలుగు: గవర్నర్ విచక్షణతో రాష్ట్రపతి పరిశీలనకు బిల్లు నివేదించగల అనుచ్ఛేదం ఏది?',
     'Art.200 / అనుచ్ఛేదం 200',
     'Art.201 / అనుచ్ఛేదం 201',
     'Art.213 / అనుచ్ఛేదం 213',
     'Art.163 / అనుచ్ఛేదం 163',
     'a',
     'Art.200: Governor may reserve (on own discretion) Bills affecting HC powers for Presidential consideration. / అనుచ్ఛేదం 200: గవర్నర్ కొన్ని బిల్లులను (ముఖ్యంగా HC అధికారాలను ప్రభావితం చేసే) విచక్షణతో రాష్ట్రపతికి నివేదించవచ్చు.'),
    (4,
     'medium',
     "Governor's pardon powers are under which Article?\nతెలుగు: గవర్నర్ క్షమాభిక్ష (pardon) అధికారాలు ఏ అనుచ్ఛేదం?",
     'Art.72 / అనుచ్ఛేదం 72',
     'Art.161 / అనుచ్ఛేదం 161',
     'Art.165 / అనుచ్ఛేదం 165',
     'Art.166 / అనుచ్ఛేదం 166',
     'b',
     "Art.161: Governor's pardon power for offences against state laws. Art.72 = President's broader powers including death sentence and court martial. / అనుచ్ఛేదం 161: గవర్నర్ రాష్ట్ర చట్టాల కింద శిక్షలు అనుభవిస్తున్న నేరస్థులకు క్షమాభిక్ష, తగ్గింపు, మార్పు ఇవ్వవచ్చు. Art.72 = రాష్ట్రపతి పార్డన్ (అన్ని కేసులు + మరణశిక్ష + కోర్ట్ మార్షల్); Art.161 = గవర్నర్ పార్డన్ (రాష్ట్ర చట్టాలు మాత్రమే)."),
    (5,
     'easy',
     "Governor's discretionary powers are in which Article?\nతెలుగు: గవర్నర్ విచక్షణ (discretionary) అధికారాలు ఏ అనుచ్ఛేదంలో ఉన్నాయి?",
     'Art.154 / అనుచ్ఛేదం 154',
     'Art.163 / అనుచ్ఛేదం 163',
     'Art.165 / అనుచ్ఛేదం 165',
     'Art.174 / అనుచ్ఛేదం 174',
     'b',
     'Art.163(1): Governor may act in his discretion in certain matters. / అనుచ్ఛేదం 163(1): గవర్నర్ కొన్ని విషయాల్లో విచక్షణతో పని చేయవచ్చు.'),
    (5,
     'medium',
     'What type of power does Governor exercise in appointing CM in hung assembly?\nతెలుగు: హంగ్ అసెంబ్లీలో గవర్నర్ ముఖ్యమంత్రిని నియమించేటప్పుడు ఏ విధమైన అధికారం వినియోగిస్తారు?',
     'Conventional power / సాంప్రదాయిక అధికారం',
     'Discretionary power / విచక్షణ అధికారం',
     'Normal power / సాధారణ అధికారం',
     'Judicial power / న్యాయ అధికారం',
     'b',
     'In a hung assembly, Governor exercises discretion to determine who commands majority. / హంగ్ అసెంబ్లీలో మెజారిటీ నిర్ణయించడంలో గవర్నర్ విచక్షణ వినియోగిస్తారు.'),
    (5,
     'hard',
     "What can courts do with Governor's discretion under Art.163(2)?\nతెలుగు: రాజ్యాంగ అనుచ్ఛేదం 163(2) ప్రకారం గవర్నర్ విచక్షణపై కోర్టు ఏం చేయగలదు?",
     'Can fully review / పూర్తిగా పరిశీలించవచ్చు',
     'Cannot review at all / అసలు పరిశీలించలేరు',
     'Only mala fide decisions challenged / కేవలం మాల్\u200cఫైడ్ నిర్ణయాలు మాత్రమే సవాలు',
     'Only on Presidential direction / రాష్ట్రపతి ఆదేశంతో మాత్రమే',
     'b',
     'Art.163(2): Court cannot inquire into whether Governor should have acted on discretion. / అనుచ్ఛేదం 163(2): గవర్నర్ విచక్షణ వినియోగం సరైనదా కాదా అని పరీక్షించే అధికారం కోర్టులకు లేదు.'),
    (5,
     'medium',
     "Under 6th Schedule, Governor's special discretionary powers are in which states?\nతెలుగు: గవర్నర్ 6వ షెడ్యూల్ కింద విచక్షణ అధికారాలు ఏ రాష్ట్రంలో ఉన్నాయి?",
     'UP & Maharashtra / ఉత్తరప్రదేశ్ & మహారాష్ట్ర',
     'Assam, Meghalaya, Tripura, Mizoram / అసోం, మేఘాలయ, త్రిపుర, మిజోరాం',
     'J&K only / జమ్మూ & కాశ్మీర్ మాత్రమే',
     'All NE states / అన్ని ఈశాన్య రాష్ట్రాలు',
     'b',
     '6th Schedule: Governors of Assam, Meghalaya, Tripura, Mizoram have special tribal area discretionary powers. / 6వ షెడ్యూల్: అసోం, మేఘాలయ, త్రిపుర, మిజోరాంలో గవర్నర్\u200cకు గిరిజన ప్రాంత నిర్వహణలో ప్రత్యేక విచక్షణ అధికారాలు ఉన్నాయి.'),
    (5,
     'easy',
     'Who is responsible for communicating state cabinet decisions to Governor?\nతెలుగు: రాష్ట్ర మంత్రిమండలి నిర్ణయాలను గవర్నర్\u200cకు తెలియజేయాలని ఎవరు బాధ్యత వహిస్తారు?',
     'Speaker / స్పీకర్',
     'Chief Minister / ముఖ్యమంత్రి',
     'Advocate General / అడ్వకేట్ జనరల్',
     'Chief Secretary / ముఖ్య కార్యదర్శి',
     'b',
     'Art.167: CM must communicate to Governor all decisions of state cabinet and legislative proposals. / అనుచ్ఛేదం 167: ముఖ్యమంత్రి రాష్ట్ర వ్యవహారాలు మరియు శాసన ప్రతిపాదనలు గవర్నర్\u200cకు తెలియజేయాలి.'),
    (5,
     'hard',
     "Per Sarkaria Commission, which are Governor's discretionary powers?\nతెలుగు: గవర్నర్ విచక్షణ అధికారాల పట్టికలో (సర్కారియా కమిషన్ వర్గీకరణ) ఏవి ఉంటాయి?",
     'Only financial powers / ఆర్థిక అధికారాలు మాత్రమే',
     'CM appointment (hung), CM resignation, Art.356 report, reserving Bills / CM నియామకం (హంగ్ అసెంబ్లీ), CM రాజీనామా, Art.356 నివేదిక, బిల్లు రాష్ట్రపతికి నివేదించడం',
     'Only dissolution / కేవలం అసెంబ్లీ రద్దు',
     'Only judicial appointments / న్యాయ నియామకాలు మాత్రమే',
     'b',
     'Sarkaria: CM appointment (hung assembly), CM resignation, Art.356 report, dismissal of ministry, dissolution. / సర్కారియా కమిషన్: గవర్నర్ విచక్షణ అధికారాలు — హంగ్ అసెంబ్లీలో CM నియామకం, CM రాజీనామా, Art.356 నివేదిక పంపడం, అసెంబ్లీ రద్దు.'),
    (5,
     'medium',
     "Under Art.163(2), what can courts inquire regarding Governor's discretion?\nతెలుగు: గవర్నర్ Art.163(2) కింద విచక్షణ వ్యాయమం గురించి కోర్టులు ఏమి విచారించగలవు?",
     'Fully subject to judicial review / గవర్నర్ విచక్షణ విషయాలు పూర్తిగా కోర్టు సమీక్షకు లోబడతాయి',
     'Courts cannot inquire into whether a matter is within discretion / గవర్నర్ విచక్షణ వ్యాయమం సరైనదా అని విచారించలేరు',
     'Only SC can inquire / కేవలం SC విచారించగలదు',
     "Only with President's permission / రాష్ట్రపతి అనుమతితో మాత్రమే విచారించగలరు",
     'b',
     'Art.163(2): No inquiry in any court as to whether any and if so what advice was tendered by ministers to Governor. / Art.163(2): గవర్నర్ విచక్షణ వ్యాయమం చేయవలసిన విషయంలో కోర్టు విచారణ చేయలేదు. గవర్నర్ చర్య మంత్రులు సలహాపై చేసిందా లేదా విచక్షణతో చేసిందా అని కూడా కోర్టు విచారించలేదు.'),
    (5,
     'hard',
     "If CM doesn't resign before Art.356 rule, what should Governor do?\nతెలుగు: అసెంబ్లీలో మెజారిటీ రాష్ట్రపతి పాలనకు ముందు CM రాజీనామా చేయలేదు అంటే గవర్నర్ ఏమి చేయాలి?",
     'Forcibly remove CM / CM ని బలవంతంగా తొలగించాలి',
     'CM automatically loses office after Art.356 / Art.356 నివేదిక పంపిన తర్వాత CM స్వయంగా పదవి కోల్పోతారు',
     'Remove and appoint new CM / CM ని తొలగించి కొత్త CM నియమించాలి',
     'Seek SC advice / SC సలహా తీసుకోవాలి',
     'b',
     "When President's Rule is proclaimed under Art.356, the CM and CoM automatically cease to hold office. / Art.356 ద్వారా రాష్ట్రపతి పాలన విధించినప్పుడు, రాజ్యాంగ యంత్రం విఫలమైనట్లు పరిగణించి, CM సహా మంత్రిమండలి స్వయంగా పదవి కోల్పోతుంది."),
    (6,
     'easy',
     'In which aspect are Governor and President similar?\nతెలుగు: గవర్నర్ మరియు రాష్ట్రపతి ఇద్దరూ ఏ అంశంలో సమానం?',
     'Elections / ఎన్నికలు',
     'Constitutional head / రాజ్యాంగపరమైన (nominal) అధిపతి',
     'Term / అధికార కాలం',
     'Income / పదవి ఆదాయం',
     'b',
     'Both are constitutional (nominal) heads — President for Union, Governor for State. / రాష్ట్రపతి కేంద్రానికి రాజ్యాంగపరమైన అధిపతి; గవర్నర్ రాష్ట్రానికి రాజ్యాంగపరమైన అధిపతి — ఇద్దరూ nominal heads.'),
    (6,
     'hard',
     "Is there an 'Electoral College' for Governor's appointment like for President?\nతెలుగు: గవర్నర్ ఎన్నికలో రాష్ట్రపతి ఎన్నికకు ఉన్న 'ఎలక్టోరల్ కాలేజ్' వ్యవస్థ ఉందా?",
     'Yes, elected by MLAs / అవును, MLAs ఎన్నుకుంటారు',
     'Yes, MPs and MLAs / అవును, MPs & MLAs ఎన్నుకుంటారు',
     'No, directly appointed by President / లేదు, రాష్ట్రపతి నేరుగా నియమిస్తారు',
     'Yes, elected by state legislature / అవును, రాష్ట్ర శాసనసభ ఎన్నుకుంటుంది',
     'c',
     'No elections for Governor — President directly appoints. President has Electoral College. / గవర్నర్\u200cకు ఎన్నికలు ఉండవు — రాష్ట్రపతి నేరుగా నియమిస్తారు. రాష్ట్రపతికి Electoral College ఉంటుంది.'),
    (6,
     'medium',
     'Can Governor pardon death sentence under Art.161?\nతెలుగు: రాష్ట్రపతి Art.72 కింద మరణ శిక్ష మాఫీ చేయగలరు — గవర్నర్ Art.161 కింద చేయగలరా?',
     'Yes / అవును',
     'No / లేదు',
     'Only state law offences / కేవలం రాష్ట్ర చట్టాలకు సంబంధించినవి మాత్రమే',
     'With Presidential sanction / రాష్ట్రపతి అనుమతితో',
     'b',
     'Difference: President (Art.72) can pardon death sentence; Governor (Art.161) cannot. / తేడా: రాష్ట్రపతి Art.72 కింద మరణ శిక్ష మాఫీ చేయగలరు; గవర్నర్ Art.161 కింద ఈ అధికారం లేదు.'),
    (6,
     'medium',
     "How do Governor's veto powers compare with President's?\nతెలుగు: గవర్నర్\u200cకు 'వీటో' అధికారాలు రాష్ట్రపతికి పోలితే ఎలా ఉంటాయి?",
     'Governor has more powers / గవర్నర్ అధికారాలు ఎక్కువ',
     'President has more powers / రాష్ట్రపతి అధికారాలు ఎక్కువ',
     'Both equal / రెండూ సమానం',
     'Governor has no veto / గవర్నర్\u200cకు వీటో లేదు',
     'b',
     "President has Pocket Veto; Governor doesn't — must report to President. President has broader veto. / రాష్ట్రపతికి Pocket Veto ఉంది; గవర్నర్\u200cకు లేదు (రాష్ట్రపతి నివేదించాలి). రాష్ట్రపతి అన్ని రకాల బిల్లులు వీటో చేయగలరు."),
    (6,
     'hard',
     "In which Article Governor acts as 'agent of President'?\nతెలుగు: గవర్నర్ 'రాష్ట్రపతి ఏజెంట్' గా పని చేసే విధి ఏ అనుచ్ఛేదంలో?",
     'Art.155 / అనుచ్ఛేదం 155',
     'Art.239 / అనుచ్ఛేదం 239',
     'Art.200 / అనుచ్ఛేదం 200',
     'Not explicitly mentioned / రాజ్యాంగంలో ప్రత్యేకంగా పేర్కొనబడలేదు',
     'd',
     "Constitution doesn't use 'agent'; Governor's dual role as state head + Centre's representative is based on convention and interpretation. / రాజ్యాంగంలో 'agent' పదం లేదు — 'dual role' (రాష్ట్ర రాజ్యాంగ అధిపతి + కేంద్ర ప్రతినిధి) సూత్రం ఆచారం మరియు వ్యాఖ్యాన ఆధారంగా."),
    (6,
     'easy',
     "MLAs participate in Presidential election — who decides Governor's appointment?\nతెలుగు: రాష్ట్రపతి ఎన్నికలో రాష్ట్రాల శాసనసభ సభ్యులు పాల్గొంటారు — గవర్నర్ నియామకంలో ఎవరు పాల్గొంటారు?",
     'MLAs & MPs / ఎమ్మెల్యేలు & ఎంపీలు',
     'President alone / రాష్ట్రపతి మాత్రమే',
     'Both Houses of Parliament / పార్లమెంటు ఉభయ సభలు',
     'PM recommendation mandatory / PM సిఫారసు అవసరం తప్పనిసరి',
     'b',
     "Governor's appointment is President's prerogative; in practice on PM's advice. / గవర్నర్ నియామకం రాష్ట్రపతి ప్రత్యేక హక్కు. ఆచారంలో PM సలహాపై నియమిస్తారు."),
    (6,
     'medium',
     "President and Governor are both nominal heads — what is one key difference?\nతెలుగు: రాష్ట్రపతి మరియు గవర్నర్ ఇద్దరూ 'రాజ్యాంగ అధిపతులు' — కానీ ఒక ముఖ్యమైన తేడా ఏమిటి?",
     'President is elected; Governor is appointed / రాష్ట్రపతి ఎన్నుకోబడతారు; గవర్నర్ నియమించబడతారు',
     'Governor has more powers / గవర్నర్ ఎక్కువ అధికారాలు కలిగి ఉంటారు',
     'President 4 years; Governor 5 / రాష్ట్రపతి పదవీకాలం 4 సంవత్సరాలు; గవర్నర్ 5 సంవత్సరాలు',
     'SC can impeach Governor / గవర్నర్ ను SC అభిశంసించగలదు',
     'a',
     "President is elected via Electoral College (Art.54); Governor appointed by President (Art.155). Both 5-year terms but Governor serves 'at pleasure' of President. / రాష్ట్రపతి ఎన్నుకోబడతారు (Art.54 — Electoral College); గవర్నర్ రాష్ట్రపతి చేత నియమించబడతారు (Art.155). రాష్ట్రపతి 5 సంవత్సరాలు; గవర్నర్ 5 సంవత్సరాలు (కానీ రాష్ట్రపతి ఇష్టం వరకు)."),
    (6,
     'hard',
     'Governor using personal discretion without CoM advice follows which principle?\nతెలుగు: గవర్నర్ వ్యక్తిగత విచక్షణతో (personally) ఉపయోగించే అధికారాలు మంత్రులు సలహా అవసరం లేదు — ఇది ఏ సూత్రం?',
     'Constitutional convention only / రాజ్యాంగపరమైన ఆచారం',
     'Art.163(1) — in functions where Constitution specifically requires Governor to act in discretion / Art.163(1) — రాజ్యాంగం గవర్నర్ విచక్షణకు ప్రత్యేకంగా నిర్ణయించిన సందర్భాల్లో సలహా అవసరం లేదు',
     'Art.154 — Governor is independent in everything / Art.154 — అన్నింటిలో గవర్నర్ స్వతంత్రుడు',
     'Art.200 — Governor can decide all bills by discretion / Art.200 — గవర్నర్ అన్ని బిల్లులను విచక్షణతో నిర్ణయించవచ్చు',
     'b',
     'Art.163(1): Governor acts on CoM advice EXCEPT in functions where Constitution requires him to act in his discretion. / Art.163(1): రాజ్యాంగం గవర్నర్ విచక్షణ ప్రకారం పనిచేయవలసిందని నిర్ణయించిన కార్యకలాపాల్లో మాత్రమే — CoM సలహా అవసరం లేదు. మిగతా అన్ని కార్యాలలో CoM సలహాపై వ్యవహరించాలి.'),
    (7,
     'easy',
     "Governor's oath is in which Schedule?\nతెలుగు: గవర్నర్ ప్రమాణ స్వీకారం ఏ షెడ్యూల్\u200cలో ఉంటుంది?",
     'First Schedule / మొదటి షెడ్యూల్',
     'Third Schedule / మూడో షెడ్యూల్',
     'Fourth Schedule / నాల్గో షెడ్యూల్',
     'Fifth Schedule / ఐదో షెడ్యూల్',
     'b',
     "Third Schedule: contains Governor's oath form. / తృతీయ షెడ్యూల్ (Third Schedule): గవర్నర్ ప్రమాణ పత్రం ఇందులో ఉంటుంది."),
    (7,
     'medium',
     'Can Governor nominate members to Vidhan Sabha (lower house)?\nతెలుగు: రాష్ట్ర శాసనసభ కింది సభ (Vidhan Sabha) సభ్యులను నామినేట్ చేసే అధికారం గవర్నర్\u200cకు ఉందా?',
     'Yes, 12 members / అవును, 12 మంది',
     'Yes, 1 Anglo-Indian (until abolished) / అవును, ఆంగ్లో-ఇండియన్ కమ్యూనిటీకి 1 మంది (రద్దు వరకు)',
     'No / లేదు',
     'Yes, 6 members / అవును, 6 మంది',
     'b',
     'Art.333: Governor could nominate one Anglo-Indian to Vidhan Sabha — abolished by 104th Amendment 2020. / అనుచ్ఛేదం 333: గవర్నర్ Vidhan Sabha కి ఒక ఆంగ్లో-ఇండియన్\u200cను నామినేట్ చేయవచ్చు (104వ సవరణ 2020 ద్వారా రద్దయింది).'),
    (7,
     'hard',
     'Which Article requires Governor to address legislature at the start?\nతెలుగు: గవర్నర్ రాష్ట్ర శాసనసభ సమావేశానికి ముందు ప్రత్యేక ప్రసంగం చేసే అనుచ్ఛేదం ఏది?',
     'Art.176 / అనుచ్ఛేదం 176',
     'Art.174 / అనుచ్ఛేదం 174',
     'Art.177 / అనుచ్ఛేదం 177',
     'Art.172 / అనుచ్ఛేదం 172',
     'a',
     'Art.176: Governor addresses legislature at the first session each year and after general elections. / అనుచ్ఛేదం 176: గవర్నర్ ప్రతి సంవత్సరం మొదటి సమావేశంలో మరియు సాధారణ ఎన్నికల తర్వాత శాసనసభ/పరిషత్ ఉభయ సభలను ఉద్దేశించి ప్రసంగిస్తారు.'),
    (7,
     'easy',
     'What is the official residence of a State Governor called?\nతెలుగు: రాష్ట్ర గవర్నర్ అధికారిక నివాసాన్ని ఏమని పిలుస్తారు?',
     'Rashtrapati Bhavan / రాష్ట్రపతి భవన్',
     'Raj Bhavan / రాజ్\u200cభవన్',
     'Governor House / గవర్నర్ హౌస్',
     'Raja Geham / రాజ గేహం',
     'b',
     'Official residence of State Governor is called Raj Bhavan. / రాష్ట్ర గవర్నర్ అధికారిక నివాసాన్ని రాజ్\u200cభవన్ (Raj Bhavan) అని పిలుస్తారు.'),
    (7,
     'medium',
     "Governor's salary and allowances are charged to which fund?\nతెలుగు: గవర్నర్ అధికారిక జీతం & భత్యాలు ఏ నిధి నుండి ఇస్తారు?",
     'Consolidated Fund of India / కేంద్ర ఏకీకృత నిధి',
     'Consolidated Fund of State / రాష్ట్ర ఏకీకృత నిధి',
     'Contingency Fund / ఆకస్మిక నిధి',
     'Public Account / ప్రజా ఖాతా',
     'b',
     "Art.158(3): Governor's emoluments charged to the Consolidated Fund of the State. / అనుచ్ఛేదం 158(3): గవర్నర్ జీతాలు రాష్ట్ర ఏకీకృత నిధి (Consolidated Fund of State) నుండి ఇవ్వబడతాయి."),
    (7,
     'hard',
     'What protection does Governor have while in office?\nతెలుగు: గవర్నర్ పదవిలో ఉన్నప్పుడు ఏ రక్షణ ఉంటుంది?',
     'Cases only after leaving office / పదవి మారిన తర్వాత మాత్రమే కేసులు దాఖలు',
     'Full immunity while in office — no civil or criminal cases / పదవిలో ఉండగా పూర్తి రక్షణ — సివిల్ & క్రిమినల్ కేసులు దాఖలు కాదు',
     'Only from civil cases / కేవలం సివిల్ కేసుల నుండి రక్షణ',
     'No immunity / ఎలాంటి రక్షణ లేదు',
     'b',
     'Art.361: Governor has immunity — no criminal proceedings during term; civil case notice required. / అనుచ్ఛేదం 361: గవర్నర్ పదవిలో ఉండగా ఏ కోర్టులో నేరారోపణలు చేయలేరు (సివిల్ & క్రిమినల్).'),
    (7,
     'medium',
     'Art. for Governor summoning/proroguing Assembly?\nతెలుగు: గవర్నర్ అసెంబ్లీ సమావేశాలు ఏర్పాటు చేయడం/వాయిదా వేయడానికి అనుచ్ఛేదం ఏది?',
     'Art.174 / అనుచ్ఛేదం 174',
     'Art.175 / అనుచ్ఛేదం 175',
     'Art.176 / అనుచ్ఛేదం 176',
     'Art.177 / అనుచ్ఛేదం 177',
     'a',
     'Art.174: Governor summons, prorogues the state legislature and dissolves the Assembly. Gap between sessions ≤ 6 months. / అనుచ్ఛేదం 174: గవర్నర్ రాష్ట్ర శాసనసభ సమావేశాలు ఏర్పాటు చేయడం, వాయిదా వేయడం, లోక్\u200cసభ రద్దు చేయడం. రెండు సమావేశాల మధ్య 6 నెలలు మించరాదు.'),
    (7,
     'hard',
     "President can dissolve State Assembly under Art.356 — on what basis?\nతెలుగు: రాష్ట్రపతి 'రాష్ట్రపతి పాలన' (Art.356) కింద రాష్ట్ర అసెంబ్లీని రద్దు చేయవచ్చు — ఇందుకు ఏ ప్రాతిపదికన?",
     "On PM's decision alone / ప్రధానమంత్రి నిర్ణయం మేరకు",
     "On Governor's report or otherwise that constitutional machinery has failed / గవర్నర్ నివేదిక లేదా ఇతర విధంగా రాజ్యాంగ యంత్రం విఫలమైన విషయం తెలిసినప్పుడు",
     'After RS resolution / రాజ్యసభ తీర్మానం తర్వాత',
     'On SC advice / SC సలహా మేరకు',
     'b',
     "Art.356: President may proclaim on Governor's report or otherwise if convinced that government cannot be carried on in accordance with Constitution. / Art.356: రాష్ట్ర గవర్నర్ నివేదిక ఆధారంగా లేదా ఇతర విధంగా రాష్ట్రంలో రాజ్యాంగ ప్రభుత్వం నడపడం సాధ్యం కాదని రాష్ట్రపతికి నిర్ధారణ అయినపుడు President's Rule విధించవచ్చు."),
]


def _seed_polity_ch18_notes_inner(conn, db_exec_fn, row_to_dict_fn, use_postgres, force=False):
    ph = '%s' if use_postgres else '?'
    existing = db_exec_fn(conn,
        f"SELECT id FROM study_notes WHERE subject={ph} AND topic={ph} AND chapter_num={ph}",
        (_SUBJECT, _TOPIC, _CH))
    row = existing.fetchone()
    if row and not force:
        return

    sections_json = __import__('json').dumps(
        [{"title": s, "content": ""} for s in _SECTIONS],
        ensure_ascii=False
    )

    if row and force:
        note_id = row_to_dict_fn(row)['id']
        db_exec_fn(conn,
            f"UPDATE study_notes SET chapter_title_te={ph}, chapter_title_en={ph}, "
            f"pages_ref={ph}, sections_json={ph} WHERE id={ph}",
            (_TITLE_TE, _TITLE_EN, _PAGES, sections_json, note_id))
    else:
        db_exec_fn(conn,
            f"INSERT INTO study_notes (subject, topic, chapter_num, chapter_title_te, "
            f"chapter_title_en, pages_ref, sections_json) VALUES "
            f"({ph},{ph},{ph},{ph},{ph},{ph},{ph})",
            (_SUBJECT, _TOPIC, _CH, _TITLE_TE, _TITLE_EN, _PAGES, sections_json))


def _seed_polity_ch18_mcqs_inner(conn, db_exec_fn, row_to_dict_fn, use_postgres):
    ph = '%s' if use_postgres else '?'
    diff_map = {"easy": 1, "medium": 2, "hard": 3, "toughest": 4, 1: 1, 2: 2, 3: 3, 4: 4}

    note_cur = db_exec_fn(conn,
        f"SELECT id FROM study_notes WHERE subject={ph} AND topic={ph} AND chapter_num={ph}",
        (_SUBJECT, _TOPIC, _CH))
    note_row = note_cur.fetchone()
    if not note_row:
        return
    note_id = row_to_dict_fn(note_row)['id']

    existing = db_exec_fn(conn,
        f"SELECT COUNT(*) FROM chapter_mcqs WHERE study_note_id={ph}", (note_id,))
    count = list(existing.fetchone())[0]
    if count > 0:
        return

    for row in _MCQS:
        sec_idx  = row[0]
        diff_int = diff_map.get(row[1], 1)
        q_te     = row[2]
        opt_a    = row[3]
        opt_b    = row[4]
        opt_c    = row[5]
        opt_d    = row[6]
        correct  = str(row[7]).lower()
        expl     = row[8] if len(row) > 8 else ''
        exam_type = row[9] if len(row) > 9 else 'General'

        db_exec_fn(conn,
            f"""INSERT INTO chapter_mcqs
                (study_note_id, section_idx, difficulty, exam_type,
                 q_te, opt_a, opt_b, opt_c, opt_d, correct, explanation_te)
                VALUES ({ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph})""",
            (note_id, sec_idx, diff_int, exam_type,
             q_te, opt_a, opt_b, opt_c, opt_d, correct, expl))
