"""
Seed: App Ch90 = Book Ch87 — Landmark Judgements and Their Impact
64 MCQs × 8 sections, 8 per section
"""

def seed_polity_ch90(conn, db_exec_fn, row_to_dict_fn, use_postgres=False, force=False):
    _seed_polity_ch90_notes_inner(conn, db_exec_fn, row_to_dict_fn, use_postgres, force)
    conn.commit()
    _seed_polity_ch90_mcqs_inner(conn, db_exec_fn, row_to_dict_fn, use_postgres)
    conn.commit()


def _seed_polity_ch90_notes_inner(conn, db_exec_fn, row_to_dict_fn, use_postgres=False, force=False):
    import datetime as _dt
    ph = "%s" if use_postgres else "?"
    existing = row_to_dict_fn(db_exec_fn(conn,
        f"SELECT id FROM study_notes WHERE topic={ph} AND chapter_num={ph}",
        ('Indian_Polity', 90)).fetchone() or {})
    if existing and not force:
        return existing.get('id')
    if existing:
        db_exec_fn(conn,
            f"DELETE FROM study_notes WHERE topic={ph} AND chapter_num={ph}",
            ('Indian_Polity', 90))
    now = _dt.datetime.utcnow().isoformat()
    cur = db_exec_fn(conn,
        f"""INSERT INTO study_notes
            (subject, topic, chapter_num, chapter_title_te, chapter_title_en,
             pages_ref, sections_json, created_at)
            VALUES ({ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph})""",
        ('GK', 'Indian_Polity', 90,
         'చారిత్రాత్మక తీర్పులు',
         'Landmark Judgements and Their Impact',
         'Lakshmikanth Ch.90',
         '[]', now))
    return cur.lastrowid
def _seed_polity_ch90_mcqs_inner(conn, db_exec_fn, row_to_dict_fn, use_postgres=False, force=False):
    import datetime as _dt
    ph = "%s" if use_postgres else "?"
    _TOPIC = 'Indian_Polity'
    _CH = 90
    note_id = row_to_dict_fn(db_exec_fn(conn,
        f"SELECT id FROM study_notes WHERE topic={ph} AND chapter_num={ph}",
        (_TOPIC, _CH)).fetchone() or {}).get('id')
    if not note_id:
        return
    existing = list(db_exec_fn(conn,
        f"SELECT COUNT(*) FROM chapter_mcqs WHERE study_note_id={ph}",
        (note_id,)).fetchone() or [0])[0]
    if existing and not force:
        return
    if existing:
        db_exec_fn(conn, f"DELETE FROM chapter_mcqs WHERE study_note_id={ph}", (note_id,))
    now = _dt.datetime.utcnow().isoformat()


    mcqs = [
        # ── Section 0: Basic Structure & Constitutional Supremacy ──
        (0,'medium',
         'Basic Structure సిద్ధాంతం ఏది? / In which landmark case did the Supreme Court propound the doctrine of Basic Structure of the Constitution?',
         'Golaknath v. State of Punjab (1967)',
         'Kesavananda Bharati v. State of Kerala (1973)',
         'Minerva Mills v. Union of India (1980)',
         'Waman Rao v. Union of India (1981)',
         'b',
         'Kesavananda Bharati v. State of Kerala 1973 (13-judge bench, 7:6) held Parliament cannot amend the basic structure of the Constitution.'),
        (0,'easy',
         'ప్రాథమిక హక్కులు సవరణ ఏది? / Which case held that Parliament has UNLIMITED power to amend the Constitution including Fundamental Rights?',
         'Shankari Prasad case 1951',
         'Golaknath v. State of Punjab 1967',
         'Kesavananda Bharati 1973',
         'Sajjan Singh case 1964',
         'a',
         'Shankari Prasad v. Union of India 1951 held that Parliament has unlimited power to amend the Constitution including Fundamental Rights, and Art.13 does not apply to constitutional amendments. Golaknath 1967 reversed this by holding FRs CANNOT be amended. Kesavananda 1973 then held Parliament can amend FRs but not the basic structure.'),
        (0,'medium',
         'Minerva Mills కేసు ఏది? / The Minerva Mills v. Union of India (1980) case struck down which constitutional amendments?',
         '38th and 39th Amendments',
         '41st and 42nd Amendments',
         'Clauses 4 and 5 of Article 368 inserted by 42nd Amendment',
         '44th Amendment entirely',
         'c',
         'Minerva Mills 1980 struck down clauses 4 and 5 of Art.368 (inserted by 42nd Amendment 1976) that gave Parliament unlimited amending power — reaffirming basic structure.'),
        (0,'hard',
         'Kesavananda Bharati కేసు ఏమిటి? / What was the specific ratio (vote split) in the Kesavananda Bharati case?',
         '9:4',
         '8:5',
         '7:6',
         '10:3',
         'c',
         'Kesavananda Bharati 1973 was decided 7:6 by a 13-judge constitutional bench — the largest bench in Indian SC history.'),
        (0,'medium',
         'Waman Rao కేసు ఏది? / In Waman Rao v. Union of India (1981), the Supreme Court clarified that the basic structure doctrine applies from which date?',
         'January 26, 1950 (Constitution commencement)',
         'April 24, 1973 (date of Kesavananda judgment)',
         'June 12, 1975 (Emergency declaration)',
         'November 26, 1949 (Constitution adoption)',
         'b',
         'Waman Rao 1981 clarified that laws and amendments placed in 9th Schedule after April 24, 1973 (Kesavananda date) are subject to basic structure judicial review.'),
        (0,'easy',
         'Basic Structure సిద్ధాంతం ఏది? / The concept of "basic structure" means Parliament cannot amend which of the following?',
         'Schedules to the Constitution',
         'Directive Principles of State Policy',
         'Supremacy of the Constitution, federal character, separation of powers, judicial review, and FRs',
         'Preamble alone',
         'c',
         'Basic structure includes: supremacy of Constitution, republican democratic form, secularism, separation of powers, judicial review, fundamental rights — Parliament cannot destroy these.'),
        (0,'hard',
         'చారిత్రక తీర్పు ఏది? / Which case first held that "Constitutional amendments are not laws" and thus outside Art.13?',
         'Shankari Prasad v. Union of India 1951',
         'Sajjan Singh v. State of Rajasthan 1964',
         'Golaknath v. State of Punjab 1967',
         'Kesavananda Bharati 1973',
         'a',
         'Shankari Prasad 1951 first held that Art.13 does not apply to constitutional amendments — i.e., Parliament can amend Fundamental Rights. This was overruled by Golaknath 1967, then partially restored by Kesavananda 1973.'),
        (0,'medium',
         'Waman Rao కేసు ఎప్పుడు? / The 9th Schedule of the Constitution was added by which amendment, and when did it come under judicial review per Waman Rao?',
         '1st Amendment 1951; laws added after 1973 are reviewable',
         '4th Amendment 1955; laws added after 1967 are reviewable',
         '42nd Amendment 1976; all laws in Schedule are reviewable',
         '44th Amendment 1978; laws added after 1978 are reviewable',
         'a',
         '9th Schedule added by 1st Amendment 1951 to protect land reform laws. Per Waman Rao 1981, laws placed in 9th Schedule AFTER April 24, 1973 (Kesavananda) are subject to basic structure review.'),

        # ── Section 1: Fundamental Rights — Art.21 Expansion ──
        (1,'easy',
         'అధికరణ 21 జీవన హక్కు ఏది? / Which case expanded Article 21 (right to life) to include the right to travel abroad?',
         'A.K. Gopalan v. State of Madras 1950',
         'Maneka Gandhi v. Union of India 1978',
         'Olga Tellis v. Bombay Municipal Corporation 1985',
         'Francis Coralie Mullin v. Union Territory of Delhi 1981',
         'b',
         'Maneka Gandhi v. Union of India 1978 overruled A.K. Gopalan; held Art.21 must be interpreted broadly, procedure must be just fair and reasonable, and Art.14/19/21 are interconnected.'),
        (1,'medium',
         'చారిత్రక తీర్పు ఏమిటి? / In A.K. Gopalan v. State of Madras (1950), the Supreme Court interpreted Art.21 in what manner?',
         'Art.21 protects both substantive and procedural due process',
         'Art.21 is linked with Art.19 and both must be satisfied',
         'Art.21 requires only compliance with procedure established by law — even an arbitrary law suffices',
         'Art.21 includes right to livelihood',
         'c',
         'A.K. Gopalan 1950 held Art.21 requires only procedure established by law — even arbitrary procedure suffices. Maneka Gandhi 1978 overruled this, requiring procedure to be just, fair, reasonable.'),
        (1,'easy',
         'అధికరణ 21 జీవన హక్కు ఏది? / Which landmark case held that the right to livelihood is part of the right to life under Article 21?',
         'Maneka Gandhi v. UOI 1978',
         'Francis Coralie Mullin v. UT Delhi 1981',
         'Olga Tellis v. Bombay Municipal Corporation 1985',
         'Bandhua Mukti Morcha v. UOI 1984',
         'c',
         'Olga Tellis 1985 (Pavement Dwellers case) held that right to life includes right to livelihood — evicting pavement dwellers without alternative must comply with Art.21.'),
        (1,'medium',
         'చారిత్రక తీర్పు ఏమిటి? / In Francis Coralie Mullin v. Union Territory of Delhi (1981), the Supreme Court held that Art.21 includes right to:',
         'Education up to 18 years',
         'Live with human dignity, including bare necessities of food, clothing, shelter, reading, and writing',
         'Vote in elections',
         'Property',
         'b',
         'Francis Coralie Mullin 1981: Art.21 includes right to live with basic human dignity — bare necessities such as food, clothing, shelter, and facilities for reading, writing, and expressing oneself.'),
        (1,'hard',
         'చారిత్రక తీర్పు ఏది? / Which case held that the right to health is a fundamental right under Art.21 of the Constitution?',
         'Parmanand Katara v. Union of India 1989',
         'Consumer Education & Research Centre v. UOI 1995',
         'Vincent Panikurlangara v. UOI 1987',
         'All of the above',
         'd',
         'Multiple cases — Parmanand Katara (emergency treatment), CERC v. UOI (occupational health of workers), Vincent (no harmful drugs) — together established right to health under Art.21.'),
        (1,'medium',
         'విద్య హక్కు తీర్పు ఏది? / In which case did the Supreme Court hold that the right to education is a fundamental right under Art.21?',
         'Unni Krishnan v. State of AP 1993',
         'TMA Pai Foundation v. State of Karnataka 2002',
         'P.A. Inamdar v. State of Maharashtra 2005',
         'Society for Un-Aided Private Schools v. UOI 2012',
         'a',
         'Unni Krishnan v. State of AP 1993 first held that the right to free education up to 14 years flows from Art.21 read with Art.45 (DPSP). Later, 86th Amendment 2002 made Art.21A explicit.'),
        (1,'easy',
         'చారిత్రక తీర్పు ఏది? / Which case held that "procedure established by law" under Art.21 must be just, fair, and reasonable — not arbitrary?',
         'A.K. Gopalan v. State of Madras 1950',
         'Rustom Cavasjee Cooper v. UOI 1970',
         'Maneka Gandhi v. Union of India 1978',
         'Bachan Singh v. State of Punjab 1980',
         'c',
         'Maneka Gandhi 1978 overruled Gopalan; held procedure under Art.21 must satisfy Art.14 (non-arbitrariness) and Art.19 (reasonableness) — the "golden triangle" of Arts.14, 19, 21.'),
        (1,'hard',
         'చారిత్రక తీర్పు ఏది? / In Bachan Singh v. State of Punjab (1980), the Supreme Court upheld the death penalty but laid down which test?',
         'The "rarest of rare" test for imposing death sentence',
         'The "beyond reasonable doubt" test only',
         'The "shock the conscience" test',
         'Death penalty cannot be imposed for any crime',
         'a',
         'Bachan Singh 1980 upheld constitutional validity of death penalty (S.302 IPC) but mandated it be imposed only in the "rarest of rare" cases — creating a judicial check on capital punishment.'),

        # ── Section 2: Equality, Social Justice & Reservations ──
        (2,'easy',
         'చారిత్రక తీర్పు ఏది? / Which case held that reservations cannot exceed 50% of total seats/posts?',
         'State of Madras v. Champakam Dorairajan 1951',
         'M.R. Balaji v. State of Mysore 1963',
         'Indra Sawhney v. Union of India 1992',
         'Nagaraj v. Union of India 2006',
         'c',
         'Indra Sawhney v. UOI 1992 (Mandal case) — 9-judge bench upheld 27% OBC reservation, laid the 50% ceiling rule, excluded creamy layer, and ruled no reservation in promotions.'),
        (2,'medium',
         'చారిత్రక తీర్పు ఏది? / Which case first struck down communal GO reserving seats in medical colleges as violative of Art.29(2)?',
         'Champakam Dorairajan v. State of Madras 1951',
         'Balaji v. State of Mysore 1963',
         'T. Devadasan v. Union of India 1964',
         'State of Kerala v. N.M. Thomas 1976',
         'a',
         'Champakam Dorairajan 1951 — first SC case on reservations — struck down Madras communal GO as violating Art.29(2) (no discrimination in education on grounds of religion/race/caste). Led to 1st Amendment adding Art.15(4).'),
        (2,'easy',
         'చారిత్రక తీర్పు ఏది? / In the Mandal Commission case (Indra Sawhney 1992), which concept did the SC introduce to exclude affluent OBCs from reservation?',
         'Dominant caste exclusion',
         'Creamy layer exclusion',
         'Economic status test',
         'Forward block test',
         'b',
         'Indra Sawhney 1992 introduced the "creamy layer" concept — advanced sections among OBCs (based on economic/social advancement) cannot avail reservations.'),
        (2,'medium',
         'చారిత్రక తీర్పు ఏది? / Which constitutional amendment was necessitated by the Champakam Dorairajan judgment to allow reservations in education?',
         'First Amendment 1951 — added Art.15(4)',
         'Fourth Amendment 1955',
         'Seventh Amendment 1956',
         'Seventeenth Amendment 1964',
         'a',
         'First Amendment 1951 added Art.15(4) enabling state to make special provisions for socially and educationally backward classes or SC/ST — a direct response to Champakam Dorairajan.'),
        (2,'hard',
         'చారిత్రక తీర్పు ఏది? / In M. Nagaraj v. Union of India (2006), the SC upheld reservations in promotions with quantifiable data requirement. Which amendment was challenged?',
         '77th Amendment 1995 (Art.16(4A))',
         '85th Amendment 2001 (consequential seniority)',
         'Both 77th and 85th Amendments (Arts.16(4A) and 16(4B))',
         '93rd Amendment 2005',
         'c',
         'Nagaraj 2006 upheld Arts.16(4A) and 16(4B) (promotion reservations for SC/ST) inserted by 77th, 81st, 82nd, 85th amendments — but required states to show: backwardness, inadequate representation, and administrative efficiency.'),
        (2,'easy',
         'విశాఖ మార్గదర్శకాలు ఏది? / The Vishaka v. State of Rajasthan (1997) case laid down guidelines against which issue?',
         'Child labour in factories',
         'Sexual harassment of women at the workplace',
         'Caste discrimination in educational institutions',
         'Bonded labour',
         'b',
         'Vishaka 1997 — Supreme Court laid down the Vishaka Guidelines against sexual harassment at the workplace, treating it as violation of Art.14, 15, 19(1)(g) and 21. Led to POSH Act 2013.'),
        (2,'medium',
         'చారిత్రక తీర్పు ఏది? / In Jarnail Singh v. Lachhmi Narain Gupta (2018), the Supreme Court modified which test from the Nagaraj case?',
         'Removed the requirement to show administrative efficiency',
         'Removed the requirement to collect quantifiable data to show backwardness of SC/ST',
         'Extended 50% ceiling to SC/ST promotions',
         'Introduced creamy layer for SC/ST',
         'b',
         'Jarnail Singh 2018 modified Nagaraj: states need NOT collect quantifiable data on backwardness of SC/ST for promotion reservations (SC/ST are already presumed backward), but must show inadequate representation.'),
        (2,'hard',
         'చారిత్రక తీర్పు ఏది? / Which 2022 Supreme Court judgment upheld the 103rd Constitutional Amendment providing 10% EWS reservation?',
         'Janhit Abhiyan v. Union of India 2022',
         'Neil Aurelio Nunes v. Union of India 2022',
         'B.K. Pavitra v. Union of India 2022',
         'EWS Reservation case (5-judge bench) 2022',
         'a',
         'Janhit Abhiyan v. Union of India 2022 — 5-judge bench (3:2) upheld 103rd Amendment providing 10% EWS reservation for economically weaker sections not covered by existing reservations. EWS can exceed 50% ceiling.'),

        # ── Section 3: Personal Liberty, Criminal Law & Habeas Corpus ──
        (3,'easy',
         'జీవన హక్కు ఏది? / In which case did the Supreme Court\'s majority hold that the right to life (Art.21) CAN be suspended during a National Emergency — a ruling widely criticised as the Court\'s "darkest hour"?',
         'ADM Jabalpur v. Shivkant Shukla 1976',
         'Maneka Gandhi v. UOI 1978',
         'Hamdard Dawakhana v. UOI 1960',
         'Nandini Satpathy v. P.L. Dani 1978',
         'a',
         'ADM Jabalpur v. Shivkant Shukla 1976 (Habeas Corpus case during the Emergency): majority 4:1 held Art.21 CAN be suspended during Emergency. Justice H.R. Khanna alone dissented, arguing no one can be deprived of life without authority of law. This ruling was overruled by Puttaswamy 2017, which held privacy (and Art.21) cannot be suspended.'),
        (3,'medium',
         'ADM జబల్పూర్ కేసు ఏమిటి? / Justice H.R. Khanna\'s dissent in ADM Jabalpur 1976 argued that even during Emergency:',
         'Preventive detention is unconstitutional',
         'The right to life cannot be taken away by executive action without legal authority',
         'Parliament has no power to amend Art.21',
         'Art.359 cannot suspend Art.21',
         'b',
         'Justice Khanna held that even without Art.21, no one can be deprived of life without authority of law — based on common law and rule of law. His dissent is celebrated as one of the finest in Indian judicial history.'),
        (3,'easy',
         'ADM జబల్పూర్ కేసు ఏది? / In which case did the Supreme Court overrule ADM Jabalpur and hold that right to privacy is a fundamental right?',
         'K.S. Puttaswamy v. Union of India 2017',
         'Shreya Singhal v. UOI 2015',
         'Suresh Kumar Koushal v. Naz Foundation 2013',
         'Justice K.S. Puttaswamy (Retd.) v. UOI 2018 (Aadhaar)',
         'a',
         'K.S. Puttaswamy v. UOI 2017 (9-judge bench, unanimous) held privacy is a fundamental right under Art.21. Also overruled ADM Jabalpur on the point that Art.21 cannot be suspended.'),
        (3,'medium',
         'Navtej Johar కేసు ఏది? / Which case decriminalized homosexuality in India by reading down S.377 IPC?',
         'Naz Foundation v. Government of NCT Delhi 2009 (Delhi HC)',
         'Suresh Kumar Koushal v. Naz Foundation 2013 (SC)',
         'Navtej Singh Johar v. Union of India 2018 (SC)',
         'Both (a) and (c) together',
         'c',
         'Navtej Singh Johar v. UOI 2018 — 5-judge SC bench unanimously read down S.377 IPC to decriminalise consensual same-sex relations among adults in private. Overruled Suresh Kumar Koushal 2013.'),
        (3,'hard',
         'K.S. Puttaswamy గోప్యత హక్కు ఏది? / In the Aadhaar judgment (Puttaswamy 2018), the Supreme Court upheld Aadhaar but struck down which provisions?',
         'Mandatory Aadhaar for bank accounts and mobile SIMs (S.57 of Aadhaar Act)',
         'Aadhaar for filing income tax returns',
         'Aadhaar for PDS and welfare schemes',
         'UIDAI itself as unconstitutional',
         'a',
         'Puttaswamy 2018 (Aadhaar) — upheld Aadhaar for welfare schemes/income tax; struck down S.57 (allowing private entities to use Aadhaar) and mandatory Aadhaar for bank accounts and mobile SIMs as violating proportionality.'),
        (3,'easy',
         'చారిత్రక తీర్పు ఏది? / Which landmark case upheld the right of arrested persons to be informed of grounds of arrest and right to consult a lawyer?',
         'D.K. Basu v. State of West Bengal 1997',
         'Khatri v. State of Bihar 1981',
         'Hussainara Khatoon v. State of Bihar 1979',
         'Joginder Kumar v. State of UP 1994',
         'a',
         'D.K. Basu v. State of West Bengal 1997 — SC laid down detailed guidelines on arrest procedures, including informing the arrested person of grounds, right to lawyer, informing family, medical examination, and creation of arrest memo.'),
        (3,'medium',
         'చారిత్రక తీర్పు ఏమిటి? / In Hussainara Khatoon v. State of Bihar (1979), the Supreme Court held that speedy trial is:',
         'A DPSP and not enforceable',
         'A fundamental right under Article 21',
         'Only guaranteed during trial, not investigation',
         'Available only in sessions courts',
         'b',
         'Hussainara Khatoon 1979 — released undertrial prisoners who had been in jail longer than the maximum sentence for their alleged offence; held speedy trial is an integral part of Art.21 right to life and personal liberty.'),
        (3,'hard',
         'చారిత్రక తీర్పు ఏది? / Which case related to sedition (S.124A IPC) saw the Supreme Court stay all pending sedition trials in 2022?',
         'S.G. Vombatkere v. Union of India 2022',
         'Kedar Nath Singh v. State of Bihar 1962',
         'Balwant Singh v. State of Punjab 1995',
         'Shreya Singhal v. UOI 2015',
         'a',
         'S.G. Vombatkere v. UOI 2022 — SC put S.124A (sedition) on hold; asked government to reconsider the provision. Kedar Nath Singh 1962 had upheld sedition but narrowed it to incitement to violence.'),

        # ── Section 4: Freedom of Speech, Religion & Minority Rights ──
        (4,'easy',
         'చారిత్రక తీర్పు ఏది? / Which case struck down S.66A of the IT Act as unconstitutional for being vague and chilling free speech?',
         'Avnish Bajaj v. State 2008',
         'Shreya Singhal v. Union of India 2015',
         'Anuradha Bhasin v. Union of India 2020',
         'Foundation for Media Professionals v. UT of J&K 2020',
         'b',
         'Shreya Singhal v. UOI 2015 — SC struck down S.66A IT Act (offensive online speech) as unconstitutionally vague, creating a chilling effect on free speech under Art.19(1)(a).'),
        (4,'medium',
         'Shah Bano కేసు ఏది? / The Shah Bano case (1985) involved which legal controversy?',
         'Triple talaq being declared unconstitutional',
         'Muslim woman\'s right to maintenance after divorce under S.125 CrPC',
         'Uniform Civil Code being made mandatory',
         'Muslim Personal Law being brought under fundamental rights',
         'b',
         'Shah Bano 1985 — SC held a divorced Muslim woman is entitled to maintenance from her husband under S.125 CrPC. Parliament reversed it by Muslim Women (Protection of Rights on Divorce) Act 1986.'),
        (4,'easy',
         'ట్రిపుల్ తలాక్ తీర్పు ఏది? / Which Supreme Court judgment in 2017 declared instant triple talaq (talaq-e-biddat) unconstitutional?',
         'Shayara Bano v. Union of India 2017',
         'Danial Latifi v. Union of India 2001',
         'Sarla Mudgal v. Union of India 1995',
         'John Vallamattom v. Union of India 2003',
         'a',
         'Shayara Bano v. UOI 2017 — 5-judge bench (3:2) declared instant triple talaq (talaq-e-biddat) unconstitutional. Led to Muslim Women (Protection of Rights on Marriage) Act 2019.'),
        (4,'medium',
         'చారిత్రక తీర్పు ఏమిటి? / In S.R. Bommai v. Union of India (1994), the Supreme Court held that secularism is:',
         'A directive principle, not fundamental to the Constitution',
         'A basic feature of the Constitution and President\'s Rule must have prior parliamentary approval',
         'Only applicable to the Central Government, not states',
         'Means state can give preference to majority religion',
         'b',
         'S.R. Bommai 1994 — 9-judge bench held secularism is a basic feature of the Constitution; Art.356 President\'s Rule must be approved by Parliament; courts can judicially review proclamation.'),
        (4,'easy',
         'చారిత్రక తీర్పు ఏమిటి? / In TMA Pai Foundation v. State of Karnataka (2002), the SC held that for minority institutions:',
         'State has absolute control over admissions',
         'Minority institutions have the right to administer but not the right to maladminister',
         'Non-minorities cannot be admitted',
         'Government grants can be refused to minority institutions',
         'b',
         'TMA Pai Foundation 2002 (11-judge bench) clarified Art.30 rights: minority institutions have right to establish and administer, but not to maladminister. State can regulate to ensure standards.'),
        (4,'hard',
         'Basic Structure సిద్ధాంతం ఏది? / In which case did the SC hold that the Preamble is a part of the Constitution and can be amended but cannot destroy basic structure?',
         'Berubari Union case 1960',
         'Kesavananda Bharati 1973',
         'LIC of India v. Consumer Education & Research Centre 1995',
         'In Re: The Special Courts Bill 1979',
         'b',
         'Kesavananda Bharati 1973 settled that the Preamble is part of the Constitution (overruling Berubari 1960) and can be amended, but its basic features (democracy, secularism, socialism, republic) are part of basic structure.'),
        (4,'medium',
         'చారిత్రక తీర్పు ఏది? / Which case established that the right to know about electoral candidates\' criminal antecedents is part of freedom of speech?',
         'People\'s Union for Civil Liberties v. UOI 2003',
         'Common Cause v. Union of India 2018',
         'Lily Thomas v. Union of India 2013',
         'ADR v. UOI 2002',
         'a',
         'PUCL v. UOI 2003 — SC held voters have right to know antecedents of candidates (criminal records, assets). ECI issued Model Code; later mandated by SC. ADR v. UOI 2002 was the initial direction.'),
        (4,'easy',
         'చారిత్రక తీర్పు ఏది? / In which case did the Supreme Court hold that the right to internet access is protected under Art.19(1)(a)?',
         'Shreya Singhal v. UOI 2015',
         'Anuradha Bhasin v. Union of India 2020',
         'Foundation for Media Professionals v. UT of J&K 2020',
         'Faheema Shirin v. State of Kerala 2019 (Kerala HC)',
         'b',
         'Anuradha Bhasin v. UOI 2020 — SC held internet access is protected under Art.19(1)(a) and Art.19(1)(g); internet shutdown orders must satisfy proportionality; indefinite shutdowns are impermissible.'),

        # ── Section 5: Environment, Federalism & Governance ──
        (5,'easy',
         'చారిత్రక తీర్పు ఏది? / In M.C. Mehta v. Union of India (Oleum Gas Leak case 1987), the Supreme Court introduced which new rule of liability?',
         'Absolute liability (no exceptions)',
         'Strict liability (Rylands v. Fletcher rule)',
         'Contributory negligence',
         'Vicarious liability',
         'a',
         'M.C. Mehta 1987 (Oleum Gas Leak) — SC introduced Absolute Liability: enterprises engaged in hazardous activity are absolutely liable for any escape of harm with NO exceptions — stricter than the English rule in Rylands v. Fletcher.'),
        (5,'medium',
         'చారిత్రక తీర్పు ఏది? / The "Polluter Pays Principle" and "Precautionary Principle" were given constitutional backing in which case?',
         'Vellore Citizens Welfare Forum v. UOI 1996',
         'Indian Council for Enviro-Legal Action v. UOI 1996',
         'A.P. Pollution Control Board v. M.V. Nayudu 1999',
         'Both (a) and (b)',
         'd',
         'Vellore Citizens 1996 (tanneries) and Indian Council for Enviro-Legal Action 1996 (H-acid industries) both applied and constitutionalised Polluter Pays Principle and Precautionary Principle as part of Indian environmental law.'),
        (5,'easy',
         'చారిత్రక తీర్పు ఏది? / Which case led to the Supreme Court ordering closure of polluting industries in Delhi and relocation to CNG buses?',
         'M.C. Mehta v. UOI (Vehicular Pollution) 1998',
         'Almitra Patel v. UOI 2000',
         'Subhash Kumar v. State of Bihar 1991',
         'Rural Litigation and Entitlement Kendra v. State of UP 1985',
         'a',
         'M.C. Mehta v. UOI (Vehicular Pollution cases 1990s-2002) — SC ordered Delhi to switch to CNG for public transport, imposed Bharat Stage emission norms, and ordered closure of polluting industries in Delhi-NCR.'),
        (5,'medium',
         'చారిత్రక తీర్పు ఏమిటి? / In S.R. Bommai v. UOI (1994), the SC held that dissolution of State Assembly under Art.356 before parliamentary approval is:',
         'Valid as a preventive measure',
         'Invalid — the Assembly should only be kept in suspended animation until Parliament approves',
         'A matter of presidential discretion not subject to judicial review',
         'Justified during political crisis',
         'b',
         'S.R. Bommai 1994 — SC held State Assembly cannot be dissolved before Parliament approves Art.356 proclamation. If Parliament does not approve, Assembly is restored. President\'s Rule is subject to judicial review.'),
        (5,'hard',
         'చారిత్రక తీర్పు ఏమిటి? / In Kihoto Hollohan v. Zachillhu (1992), the Supreme Court by a 3:2 majority held regarding the Tenth Schedule (anti-defection):',
         'Tenth Schedule is unconstitutional as it violates freedom of speech of legislators',
         'Para 7 (which barred judicial review) is unconstitutional but rest of schedule upheld; Speaker\'s decision is subject to judicial review after the final order',
         'Entire Tenth Schedule violates basic structure',
         'Only SC can decide defection cases, not Speaker',
         'b',
         'Kihoto Hollohan 1992 — 5-judge bench (3:2) upheld Tenth Schedule; struck down Para 7 (which barred courts from examining proceedings); held Speaker\'s decision is a quasi-judicial order subject to JR after final order, not during.'),
        (5,'medium',
         'ప్రజాహిత వ్యాజ్యం ఏది? / Which case held that Public Interest Litigation (PIL) is a legitimate tool and laid down guidelines to prevent its misuse?',
         'S.P. Gupta v. UOI 1981',
         'Hussainara Khatoon v. Bihar 1979',
         'Bandhua Mukti Morcha v. UOI 1984',
         'All of the above, with Gupta case broadening locus standi',
         'd',
         'Hussainara Khatoon 1979 is considered first PIL; S.P. Gupta 1981 (Judges Transfer case) broadened locus standi to allow any public-spirited person to file PIL; Bandhua Mukti Morcha 1984 extended it to bonded labour.'),
        (5,'easy',
         'ఆహార హక్కు ఏది? / In which case did the Supreme Court hold that "right to food" is a fundamental right under Art.21?',
         'Chameli Singh v. State of UP 1996',
         'People\'s Union for Civil Liberties v. UOI 2001 (Right to Food)',
         'Shantisar Builders v. Narayan Totame 1990',
         'Paschim Banga Khet Mazdoor Samity v. State of WB 1996',
         'b',
         'PUCL v. UOI 2001 (Right to Food case) — SC held right to food is a component of Art.21 right to life; issued interim orders converting food schemes into legal entitlements, leading to National Food Security Act 2013.'),
        (5,'hard',
         'చారిత్రక తీర్పు ఏమిటి? / In the Second Judges case (Supreme Court Advocates-on-Record Association v. UOI 1993), the SC held:',
         'CJI\'s recommendation is not binding on the President',
         'CJI has primacy in judicial appointments; President can return advice once but must accept on reconsideration — establishing the collegium',
         'Parliament can legislate on judicial appointments',
         'Executive has final say in judicial appointments',
         'b',
         'Second Judges case 1993 — 9-judge bench established the collegium system: CJI (in consultation with 2 seniormost SC judges) has primacy in appointment of SC and HC judges. Overruled S.P. Gupta 1981 (First Judges case).'),

        # ── Section 6: Recent Landmark Cases (Post-2010) ──
        (6,'easy',
         'చారిత్రక తీర్పు ఏది? / In which case did the Supreme Court strike down the National Judicial Appointments Commission (NJAC) as unconstitutional?',
         'Supreme Court Advocates-on-Record Association v. UOI 2015 (Fourth Judges case)',
         'Centre for PIL v. UOI 2011',
         'Rojer Mathew v. South Indian Bank 2019',
         'Madras Bar Association v. UOI 2021',
         'a',
         'Supreme Court Advocates-on-Record Association v. UOI 2015 — 5-judge bench (4:1) struck down 99th Amendment and NJAC Act; held NJAC violated independence of judiciary — a basic structure element; restored collegium.'),
        (6,'medium',
         'చారిత్రక తీర్పు ఏమిటి? / The Sabarimala case (Indian Young Lawyers Association v. State of Kerala 2018) held:',
         'Women aged 10-50 years can be barred from Sabarimala temple as a religious custom',
         'Exclusion of women aged 10-50 from Sabarimala violates Art.14, 15, 17, and 25; all women have right to worship',
         'Temple entry is a state subject, not covered by fundamental rights',
         'Art.26 protects religious denomination rights over Art.25',
         'b',
         'Sabarimala 2018 — 5-judge bench (4:1) held restriction on women aged 10-50 violates Art.14 (equality), Art.15 (no sex discrimination), Art.17 (untouchability), and Art.25 (right to religion). Referred to 9-judge bench in 2019.'),
        (6,'easy',
         'చారిత్రక తీర్పు ఏమిటి? / In Lily Thomas v. Union of India (2013), the Supreme Court held that:',
         'Criminal MPs/MLAs must pay enhanced security deposit',
         'Convicted MPs/MLAs are immediately disqualified from membership and cannot contest elections',
         'Criminal antecedents must be disclosed in nomination forms',
         'Political parties must debar members convicted of heinous crimes',
         'b',
         'Lily Thomas 2013 — SC struck down S.8(4) of RPA 1951 (which allowed convicted MPs/MLAs to continue during appeal); held conviction under S.8(1)-(3) immediately disqualifies a legislator from membership.'),
        (6,'medium',
         'చారిత్రక తీర్పు ఏమిటి? / The Shreya Singhal v. UOI (2015) case struck down S.66A IT Act on grounds of:',
         'Procedural unreasonableness',
         'Vagueness, overbreadth, and chilling effect on Art.19(1)(a)',
         'Violation of Art.21',
         'Conflict with IPC provisions',
         'b',
         'Shreya Singhal 2015 — S.66A (criminalising online speech causing annoyance/inconvenience) was struck down as vague (no definition of "grossly offensive"), overbroad, and having chilling effect on freedom of speech.'),
        (6,'hard',
         'చారిత్రక తీర్పు ఏమిటి? / In Electoral Bonds case (Association for Democratic Reforms v. UOI 2024), the Supreme Court held:',
         'Electoral bonds are constitutional as they ensure anonymous corporate donations',
         'Electoral bonds scheme violates Art.19(1)(a) (right to information); all bond data must be disclosed by ECI',
         'Electoral bonds are valid but capped at Rs. 1 crore per donor',
         'SBI can continue issuing bonds under RBI oversight',
         'b',
         'Electoral Bonds case 2024 — 5-judge bench unanimously struck down Electoral Bonds Scheme; held it violates voters\' right to information (Art.19(1)(a)); directed SBI to stop issuance and ECI to publish all data received.'),
        (6,'medium',
         'చారిత్రక తీర్పు ఏది? / In Common Cause v. Union of India (2018), the Supreme Court recognized which right as part of Art.21?',
         'Right to marry a person of choice',
         'Right to die with dignity (passive euthanasia and advance directives)',
         'Right to bear children',
         'Right to free legal aid',
         'b',
         'Common Cause v. UOI 2018 — 5-judge bench recognised right to die with dignity as part of Art.21; upheld passive euthanasia; validated "advance directives" (living will) allowing a person to refuse life support.'),
        (6,'easy',
         'K.S. Puttaswamy గోప్యత హక్కు ఏమిటి? / In Justice K.S. Puttaswamy v. UOI 2017 (Privacy case), the Supreme Court held that right to privacy:',
         'Is not a fundamental right but a common law right',
         'Is a fundamental right under Art.21 and is intrinsic to life and dignity',
         'Applies only to prevent physical surveillance, not data collection',
         'Can be curtailed by ordinary legislation without Art.21 scrutiny',
         'b',
         'Puttaswamy 2017 — 9-judge bench unanimously held privacy is a fundamental right under Art.21; it includes informational privacy, bodily integrity, and dignity; restrictions must satisfy proportionality test.'),
        (6,'hard',
         'చారిత్రక తీర్పు ఏది? / Which 2023 Supreme Court judgment held that the power under Art.142 cannot be used to dissolve marriages by mutual consent bypassing procedural requirements?',
         'Shilpa Sailesh v. Varun Sreenivasan 2023',
         'Abhiram Singh v. C.D. Commachen 2017',
         'X v. Principal Secretary Health 2022',
         'Joseph Shine v. UOI 2018',
         'a',
         'Shilpa Sailesh 2023 — SC held Art.142 power can be used to grant divorce on irretrievable breakdown even without HMA S.13B (mutual consent after cooling period); also clarified waiver of 6-month cooling period is permissible.'),

        # ── Section 7: Key Facts for Revision ──
        (7,'easy',
         'అత్యవసర పరిస్థితి హేబియస్ కార్పస్ ఏది? / Which case is known as the "Habeas Corpus case" decided during the Emergency (1976)?',
         'Maneka Gandhi v. UOI',
         'ADM Jabalpur v. Shivkant Shukla',
         'Nandini Satpathy v. P.L. Dani',
         'Hamdard Dawakhana v. UOI',
         'b',
         'ADM Jabalpur v. Shivkant Shukla 1976 is the famous Habeas Corpus case; majority held Art.21 suspended during Emergency (widely criticized); Justice Khanna\'s dissent became a landmark.'),
        (7,'medium',
         'చారిత్రక తీర్పు ఏది? / In Joseph Shine v. Union of India (2018), the Supreme Court struck down which provision?',
         'S.377 IPC (unnatural offences)',
         'S.497 IPC (adultery)',
         'S.124A IPC (sedition)',
         'S.66A IT Act (online speech)',
         'b',
         'Joseph Shine 2018 — 5-judge bench unanimously struck down S.497 IPC (adultery) as unconstitutional; held it violates Art.14, 15(1), and 21; treats women as husband\'s property; adultery is no longer a criminal offence.'),
        (7,'easy',
         'విశాఖ మార్గదర్శకాలు ఏది? / The Vishaka Guidelines (1997) on workplace sexual harassment were eventually codified into law by which legislation?',
         'Prevention of Atrocities Act Amendment 2015',
         'Protection of Women from Domestic Violence Act 2005',
         'Sexual Harassment of Women at Workplace (Prevention, Prohibition and Redressal) Act 2013',
         'Criminal Law Amendment Act 2013',
         'c',
         'Vishaka 1997 guidelines were finally codified into POSH Act 2013 (Protection of Women against Sexual Harassment at Workplace) — made Internal Complaints Committees mandatory in all organizations.'),
        (7,'medium',
         'చారిత్రక తీర్పు ఏది? / Which case established that the right to marry a person of one\'s choice is a fundamental right?',
         'Hadiya case (Shafin Jahan v. Asokan K.M. 2018)',
         'Lata Singh v. State of UP 2006',
         'Shakti Vahini v. UOI 2018',
         'All of the above affirmed this right',
         'd',
         'Multiple cases affirmed right to choose partner as fundamental: Lata Singh 2006 (inter-caste/inter-religion marriage), Shakti Vahini 2018 (against honour killings), Shafin Jahan 2018 (Hadiya — right to marry and convert). All uphold Art.21.'),
        (7,'hard',
         'చారిత్రక తీర్పు ఏది? / In which case did the SC hold that a candidate contesting election has a fundamental right to know about rival candidates under Art.19?',
         'PUCL v. UOI 2003',
         'ADR v. UOI 2002',
         'Both (a) and (b) together read with ECI Model Code',
         'CEC v. State of Kerala 2019',
         'b',
         'ADR (Association for Democratic Reforms) v. UOI 2002 — SC directed ECI to collect affidavits from candidates disclosing criminal record, assets, and educational qualifications. PUCL 2003 extended it to all voters\' right to know.'),
        (7,'easy',
         'చారిత్రక తీర్పు ఏమిటి? / What is the significance of the Rural Litigation and Entitlement Kendra v. State of UP (1985) case?',
         'First case on air pollution in India',
         'First instance of the Supreme Court ordering closure of industrial units on environmental grounds under Art.21',
         'Established the right to clean water as a fundamental right',
         'First PIL on forest conservation',
         'b',
         'RLEK v. State of UP 1985 (Doon Valley case) — SC ordered closure of limestone quarries in Mussoorie hills damaging ecology; first instance of SC using Art.21 to order industry closure on environmental grounds.'),
        (7,'medium',
         'చారిత్రక తీర్పు ఏది? / Which case is associated with the phrase "the right to die with dignity" and passive euthanasia in India?',
         'Aruna Shanbaug v. UOI 2011',
         'Common Cause v. UOI 2018',
         'Both (a) as the first case and (b) as the definitive ruling',
         'P. Rathinam v. UOI 1994',
         'c',
         'Aruna Shanbaug 2011 — SC permitted passive euthanasia under strict guidelines (first recognition). Common Cause 2018 — 5-judge bench definitively upheld passive euthanasia and advance directives as part of Art.21 right to die with dignity.'),
        (7,'hard',
         'చారిత్రక తీర్పు ఏది? / The phrase "checks and balances" in Indian constitutional jurisprudence is best reflected in which series of cases on judicial appointments?',
         'First Judges case (S.P. Gupta 1981) — executive primacy; Second Judges case 1993 — judicial primacy/collegium; Third Judges case 1998 — expanded collegium; Fourth Judges case 2015 — struck down NJAC',
         'Kesavananda 1973, Minerva Mills 1980, Waman Rao 1981 — basic structure trilogy',
         'Bommai 1994, Kihoto 1992, Nabam Rebia 2016 — federalism trilogy',
         'Maneka Gandhi 1978, Puttaswamy 2017, Navtej Johar 2018 — rights trilogy',
         'a',
         'The four Judges cases chart the evolution of judicial appointments: Gupta 1981 (executive primacy), Second Judges 1993 (collegium established), Third Judges 1998 (expanded to 5-judge collegium), Fourth Judges/NJAC 2015 (struck down NJAC, restored collegium).'),
    ]
    for (si, diff, q, oa, ob, oc, od, cor, expl) in mcqs:
        db_exec_fn(conn,
            f"""INSERT INTO chapter_mcqs
                (study_note_id, section_idx, difficulty, exam_type,
                 q_te, opt_a, opt_b, opt_c, opt_d, correct, explanation_te, created_at)
                VALUES ({ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph})""",
            (note_id, si, diff, 'General', q, oa, ob, oc, od, cor, expl, now))

