# seed_polity_ch19.py
# Chapter 19 — State Legislature
# Total Sections: 8 | Total MCQs: 56 | PYQs: 5
# Sections:
#   0 — Constitution of State Legislature (8 MCQs)
#   1 — Vidhan Sabha — Composition & Duration (8 MCQs)
#   2 — Vidhan Parishad — Composition & Features (7 MCQs)
#   3 — Speaker & Chairman (7 MCQs)
#   4 — Legislative Procedure in States (7 MCQs)
#   5 — Powers & Privileges of State Legislature (7 MCQs)
#   6 — Disqualification & 10th Schedule (6 MCQs)
#   7 — Miscellaneous / Key Articles (6 MCQs)

_CH = 19
_SUBJECT = 'GK'
_TOPIC   = 'Indian_Polity'
_TITLE_TE = 'రాష్ట్ర శాసనమండలి'
_TITLE_EN = 'State Legislature'
_PAGES    = 'Ch.19 (Lakshmikanth)'

_SECTIONS = [
    "రాష్ట్ర శాసనమండలి నిర్మాణం",
    "విధానసభ — కూర్పు & కాలవ్యవధి",
    "విధానపరిషత్ — కూర్పు & లక్షణాలు",
    "స్పీకర్ & చైర్మన్",
    "రాష్ట్రంలో శాసన ప్రక్రియ",
    "రాష్ట్ర శాసనమండలి అధికారాలు & హక్కులు",
    "అనర్హత & 10వ షెడ్యూల్",
    "విభిన్న కీలక అనుచ్ఛేదాలు",
]

_MCQS = [    (0,
     'easy',
     'Which Article deals with constitution of state legislatures?\nతెలుగు: భారత రాష్ట్రాల శాసనమండలి నిర్మాణాన్ని ప్రస్తావించే అనుచ్ఛేదం ఏది?',
     'Art.154 / అనుచ్ఛేదం 154',
     'Art.168 / అనుచ్ఛేదం 168',
     'Art.170 / అనుచ్ఛేదం 170',
     'Art.172 / అనుచ్ఛేదం 172',
     'b',
     'Art.168: Constitution of legislatures in states — Governor + Legislative Assembly (+ Legislative Council where it exists). / అనుచ్ఛేదం 168: ప్రతి రాష్ట్రంలో గవర్నర్ + విధానసభ (+ విధానపరిషత్ ఉంటే) అని ప్రస్తావిస్తుంది.'),
    (0,
     'medium',
     'Which states have bicameral legislature (Vidhan Parishad) as of 2024?\nతెలుగు: 2024 నాటికి ఏ రాష్ట్రాలకు ద్విసభ శాసనమండలి (Vidhan Parishad) ఉంది?',
     'Maharashtra, UP, Bihar, AP, Telangana, Karnataka / మహారాష్ట్ర, UP, బిహార్, AP, తెలంగాణ, కర్ణాటక',
     'Only 3 states / కేవలం 3 రాష్ట్రాలు',
     'All states / అన్ని రాష్ట్రాలూ',
     'Only 4 states / కేవలం 4 రాష్ట్రాలు',
     'a',
     'As of 2024: 6 states have Vidhan Parishad — Maharashtra, UP, Bihar, AP, Telangana, Karnataka. / 2024 నాటికి 6 రాష్ట్రాలకు విధానపరిషత్ ఉంది: మహారాష్ట్ర, UP, బిహార్, ఆంధ్రప్రదేశ్, తెలంగాణ, కర్ణాటక.'),
    (0,
     'medium',
     'రద్దు చేయడానికి ఏ అనుచ్ఛేదం అనుమతిస్తుంది? / Which Article allows creation/abolition of Legislative Council?\nతెలుగు: విధానపరిషత్ ఏర్పాటు చేయడానికి',
     'Art.168 / అనుచ్ఛేదం 168',
     'Art.169 / అనుచ్ఛేదం 169',
     'Art.171 / అనుచ్ఛేదం 171',
     'Art.172 / అనుచ్ఛేదం 172',
     'b',
     'Art.169: Parliament can create or abolish LC on resolution passed by LA. / అనుచ్ఛేదం 169: విధానసభ తీర్మానం ఆధారంగా పార్లమెంటు విధానపరిషత్\u200cను ఏర్పాటు చేయవచ్చు లేదా రద్దు చేయవచ్చు.'),
    (0,
     'hard',
     'What majority does Parliament need to create/abolish Vidhan Parishad?\nతెలుగు: విధానపరిషత్ ఏర్పాటు/రద్దు విధానంలో పార్లమెంటు ఏ మెజారిటీ అవసరం?',
     'Simple majority / సాధారణ మెజారిటీ',
     'Special majority / ప్రత్యేక మెజారిటీ',
     'Constitutional amendment / రాజ్యాంగ సవరణ',
     'Simple legislation / సాధారణ చట్టం',
     'a',
     'Art.169: Parliament passes simple majority law — not a constitutional amendment. / అనుచ్ఛేదం 169: విధానపరిషత్ ఏర్పాటు/రద్దుకు పార్లమెంటు సాధారణ మెజారిటీతో చట్టం చేయవచ్చు — ఇది రాజ్యాంగ సవరణ కాదు.'),
    (0,
     'easy',
     'Who is responsible for summoning state legislature sessions?\nతెలుగు: రాష్ట్ర శాసనమండలి సమావేశాలు ఏర్పాటు చేయడానికి బాధ్యత ఎవరిది?',
     'Chief Minister / ముఖ్యమంత్రి',
     'Speaker / స్పీకర్',
     'Governor / గవర్నర్',
     'President / రాష్ట్రపతి',
     'c',
     'Art.174: Governor summons, prorogues, dissolves state legislature. / అనుచ్ఛేదం 174: గవర్నర్ రాష్ట్ర శాసనమండలి సమావేశాలు ఏర్పాటు చేయడం, వాయిదా వేయడం, రద్దు చేయడం అధికారం.'),
    (0,
     'medium',
     'Maximum gap between two sessions of state legislature?\nతెలుగు: రాష్ట్ర శాసనమండలి రెండు సమావేశాల మధ్య గరిష్ట అంతరం ఎంత?',
     '3 months / 3 నెలలు',
     '4 months / 4 నెలలు',
     '6 months / 6 నెలలు',
     '1 year / 1 సంవత్సరం',
     'c',
     'Maximum gap between two sessions of state legislature is 6 months. / రాష్ట్ర శాసనమండలి రెండు సమావేశాల మధ్య 6 నెలలకు మించి అంతరం ఉండకూడదు.'),
    (0,
     'hard',
     'Can state legislature sit without quorum?\nతెలుగు: కోరమ్ లేకుండా రాష్ట్ర శాసనమండలి సమావేశం జరపవచ్చా?',
     'Yes / అవును',
     'No / లేదు',
     "With Speaker's permission / స్పీకర్ అనుమతితో",
     'Only in emergency / అత్యవసరంలో మాత్రమే',
     'a',
     'Quorum = 1/10 of total members; Speaker notices absence but sitting can continue. / కోరమ్ లేకపోవడాన్ని గమనించడం స్పీకర్/చైర్మన్ బాధ్యత — కానీ కోరమ్ లేకుండా సమావేశం జరగవచ్చు. రాష్ట్ర శాసనమండలి కోరమ్ = 1/10 మొత్తం సభ్యులు.'),
    (0,
     'medium',
     'Which Article deals with voting in state legislature houses?\nతెలుగు: రాష్ట్ర శాసనమండలిలో ఓటింగ్\u200cను ప్రస్తావించే అనుచ్ఛేదం ఏది?',
     'Art.187 / అనుచ్ఛేదం 187',
     'Art.189 / అనుచ్ఛేదం 189',
     'Art.191 / అనుచ్ఛేదం 191',
     'Art.194 / అనుచ్ఛేదం 194',
     'b',
     'Art.189: Questions decided by majority; casting vote of Speaker/Chairman in tie. / అనుచ్ఛేదం 189: రాష్ట్ర శాసనమండలి సభల్లో ఓటింగ్ — మెజారిటీ ఓట్లతో నిర్ణయం; సమాన ఓట్లైతే స్పీకర్/చైర్మన్ కాస్టింగ్ ఓటు.'),
    (1,
     'easy',
     'Maximum members in Vidhan Sabha?\nతెలుగు: విధానసభలో గరిష్ట సభ్యుల సంఖ్య ఎంత?',
     '250',
     '350',
     '500',
     '600',
     'c',
     'Art.170: Max 500, Min 60 members in Vidhan Sabha. / అనుచ్ఛేదం 170: విధానసభలో గరిష్టంగా 500, కనిష్టంగా 60 సభ్యులు ఉంటారు.'),
    (1,
     'easy',
     'What is the duration of Vidhan Sabha?\nతెలుగు: విధానసభ కాలవ్యవధి ఎంత?',
     '3 years / 3 సంవత్సరాలు',
     '4 years / 4 సంవత్సరాలు',
     '5 years / 5 సంవత్సరాలు',
     '6 years / 6 సంవత్సరాలు',
     'c',
     'Art.172(1): Vidhan Sabha has 5-year term (extendable during National Emergency). / అనుచ్ఛేదం 172(1): విధానసభ 5 సంవత్సరాల కాలవ్యవధి పాటు ఉంటుంది (అత్యవసర పరిస్థితిలో పొడిగించవచ్చు).'),
    (1,
     'medium',
     'By how much can Vidhan Sabha duration be extended during National Emergency?\nతెలుగు: జాతీయ అత్యవసర పరిస్థితిలో విధానసభ కాలవ్యవధిని ఎంతకాలం పొడిగించవచ్చు?',
     '6 months / 6 నెలలు',
     '1 year / 1 సంవత్సరం',
     '2 years / 2 సంవత్సరాలు',
     'Until Emergency ends / అత్యవసర పరిస్థితి ముగిసే వరకు',
     'b',
     'Art.172: During national emergency, Parliament can extend Vidhan Sabha term by 1 year at a time. / అనుచ్ఛేదం 172: జాతీయ అత్యవసర పరిస్థితి ఉన్నప్పుడు పార్లమెంటు విధానసభ కాలవ్యవధిని ఒక్కో సారి 1 సంవత్సరం చొప్పున పొడిగించవచ్చు.'),
    (1,
     'medium',
     'Minimum age for Vidhan Sabha membership?\nతెలుగు: విధానసభ సభ్యత్వానికి కనీస వయస్సు ఎంత?',
     '18 years / 18 సంవత్సరాలు',
     '21 years / 21 సంవత్సరాలు',
     '25 years / 25 సంవత్సరాలు',
     '30 years / 30 సంవత్సరాలు',
     'c',
     'Art.173: Minimum age for Vidhan Sabha membership is 25 years. / అనుచ్ఛేదం 173: విధానసభ సభ్యత్వానికి కనీస వయస్సు 25 సంవత్సరాలు.'),
    (1,
     'hard',
     'Must a Vidhan Sabha candidate be registered voter in that state?\nతెలుగు: విధానసభ సభ్యత్వానికి అర్హత — ఆ రాష్ట్రంలో ఓటరుగా నమోదు కావాలా?',
     'Yes, in the same constituency / అవును, అదే నియోజకవర్గంలో',
     'Yes, anywhere in that state / అవును, ఆ రాష్ట్రంలో ఎక్కడైనా',
     'No, anywhere in India / లేదు, దేశంలో ఎక్కడైనా',
     'No need to be voter / లేదు, ఓటరు కావాల్సిన అవసరం లేదు',
     'b',
     'Must be registered voter anywhere in that state — not necessarily in the same constituency. / విధానసభ సభ్యత్వానికి ఆ రాష్ట్రంలో ఎక్కడైనా ఓటరుగా నమోదై ఉండాలి — అదే నియోజకవర్గంలో అవసరం లేదు.'),
    (1,
     'easy',
     'A Vidhan Sabha candidate must not be a member of?\nతెలుగు: విధానసభ అర్హత కోసం వ్యక్తి ఏ సభకు చెందినవాడు అయి ఉండకూడదు?',
     'Rajya Sabha / రాజ్యసభ',
     'Any state legislature / రాష్ట్రసభ (దేశంలో ఏ రాష్ట్రానికైనా)',
     'Two Houses simultaneously / ఒకేసారి రెండు సభలకు',
     'Any House of Parliament / ఏ పార్లమెంటు సభకైనా',
     'c',
     'Cannot be member of two houses simultaneously; must vacate one if elected to another. / ఒకేసారి రెండు సభలకు (పార్లమెంటు లేదా రాష్ట్రం) సభ్యుడుగా ఉండలేరు; ఒక సభ ఎన్నికైతే మరో సభ నుండి నిష్క్రమించాలి.'),
    (1,
     'medium',
     'Goa Vidhan Sabha has how many members? (below constitutional minimum exception)\nతెలుగు: గోవా విధానసభలో సభ్యుల సంఖ్య ఎంత? (రాజ్యాంగం నిర్ణయించిన కనిష్ట సంఖ్య అపవాదు)',
     '32',
     '40',
     '45',
     '60',
     'b',
     'Goa has 40 seats — exception to the constitutional minimum of 60 for small states. / గోవా విధానసభకు 40 సభ్యులు ఉంటారు — రాజ్యాంగ కనిష్ట సంఖ్య 60 కానీ చిన్న రాష్ట్రాలకు మినహాయింపు ఉంది.'),
    (1,
     'hard',
     'Who decides disqualification of Vidhan Sabha members?\nతెలుగు: విధానసభ సభ్యత్వానికి అనర్హత నిర్ణయించే అధికారం ఎవరికి ఉంది?',
     'Speaker / స్పీకర్',
     'High Court / హైకోర్టు',
     "Governor (on EC's opinion) / గవర్నర్ (ఎన్నికల కమిషన్ అభిప్రాయంతో)",
     'Supreme Court / సుప్రీం కోర్ట్',
     'c',
     "Art.192: Disqualification question referred to Governor; decides on EC's opinion. / అనుచ్ఛేదం 192: అనర్హత ప్రశ్న గవర్నర్\u200cకు నివేదించబడుతుంది; గవర్నర్ ఎన్నికల కమిషన్ అభిప్రాయం మేరకు నిర్ణయిస్తారు."),
    (2,
     'easy',
     'What is the duration of Vidhan Parishad?\nతెలుగు: విధానపరిషత్ కాలవ్యవధి ఎంత?',
     '5 years / 5 సంవత్సరాలు',
     '6 years / 6 సంవత్సరాలు',
     'Permanent body / శాశ్వత సంస్థ',
     'Co-terminus with Vidhan Sabha / విధానసభ కాలవ్యవధి వరకు',
     'c',
     'Vidhan Parishad is a permanent body — cannot be dissolved. 1/3 retire every 2 years. / విధానపరిషత్ శాశ్వత సంస్థ — రద్దు చేయలేరు. 1/3 సభ్యులు ప్రతి 2 సంవత్సరాలకు పదవీ విరమణ చేస్తారు.'),
    (2,
     'medium',
     'Minimum age for Vidhan Parishad membership?\nతెలుగు: విధానపరిషత్ సభ్యుల కనీస వయస్సు ఎంత?',
     '21 years / 21 సంవత్సరాలు',
     '25 years / 25 సంవత్సరాలు',
     '30 years / 30 సంవత్సరాలు',
     '35 years / 35 సంవత్సరాలు',
     'c',
     'Art.173: Minimum age for Legislative Council membership is 30 years. / అనుచ్ఛేదం 173: విధానపరిషత్ సభ్యత్వానికి కనీస వయస్సు 30 సంవత్సరాలు.'),
    (2,
     'hard',
     'What fraction does Governor nominate to Vidhan Parishad?\nతెలుగు: విధానపరిషత్ కూర్పులో గవర్నర్ నామినేట్ చేసే వారి శాతం ఎంత?',
     '1/12',
     '1/6',
     '1/3',
     '1/4',
     'b',
     'Art.171(5): Governor nominates 1/6th — persons of expertise in arts, literature, science, social service. / అనుచ్ఛేదం 171(5): గవర్నర్ విధానపరిషత్ మొత్తం సభ్యుల 1/6 వంతు — కళలు, సాహిత్యం, విజ్ఞానం, సమాజసేవ నిపుణులను నామినేట్ చేస్తారు.'),
    (2,
     'medium',
     'Share elected by Vidhan Sabha in Vidhan Parishad?\nతెలుగు: విధానపరిషత్ మొత్తం సభ్యులలో విధానసభ ఎన్నుకునే వారి వాటా ఎంత?',
     '1/12',
     '1/6',
     '1/3',
     '1/4',
     'c',
     'VP composition: 1/3 by LA; 1/3 local bodies; 1/12 graduates; 1/12 teachers; 1/6 by Governor. / విధానపరిషత్ కూర్పు: 1/3 — విధానసభ ఎన్నుకుంటుంది; 1/3 — స్థానిక సంస్థలు; 1/12 — పట్టభద్రులు; 1/12 — ఉపాధ్యాయులు; 1/6 — గవర్నర్ నామినేషన్.'),
    (2,
     'medium',
     'Maximum members in Vidhan Parishad?\nతెలుగు: విధానపరిషత్ గరిష్ట సభ్యుల సంఖ్య ఎంత?',
     '1/2 of Vidhan Sabha / విధానసభ సంఖ్యకు 1/2',
     '1/3 of Vidhan Sabha or 40 (whichever greater) / విధానసభ సంఖ్యకు 1/3 లేదా 40 (ఏది ఎక్కువైతే)',
     '250',
     '100',
     'b',
     'Art.171(1): Not more than 1/3 of Vidhan Sabha or less than 40 members. / అనుచ్ఛేదం 171(1): విధానపరిషత్ సభ్యుల సంఖ్య విధానసభ మొత్తం సంఖ్యకు 1/3 కంటే ఎక్కువ కాకూడదు; కానీ 40 కంటే తక్కువ కాకూడదు.'),
    (2,
     'easy',
     'Term of Vidhan Parishad members?\nతెలుగు: విధానపరిషత్ సభ్యుల పదవీ కాలం ఎంత?',
     '3 years / 3 సంవత్సరాలు',
     '4 years / 4 సంవత్సరాలు',
     '5 years / 5 సంవత్సరాలు',
     '6 years / 6 సంవత్సరాలు',
     'd',
     'VP members serve 6-year term — like Rajya Sabha. 1/3 retire every 2 years. / విధానపరిషత్ సభ్యుల పదవీ కాలం 6 సంవత్సరాలు — రాజ్యసభ వలె. 1/3 సభ్యులు ప్రతి 2 సంవత్సరాలకు విరమిస్తారు.'),
    (2,
     'hard',
     'Pre-requisite for Parliament to create Vidhan Parishad in a state?\nతెలుగు: విధానపరిషత్ లేని రాష్ట్రంలో లెజిస్లేటివ్ కౌన్సిల్ ఏర్పాటు చేయడానికి పార్లమెంటు ముందు ఏ పూర్వ అవసరం ఉంది?',
     "President's approval / రాష్ట్రపతి ఆమోదం",
     'Special majority resolution by Vidhan Sabha / విధానసభ ప్రత్యేక మెజారిటీ తీర్మానం',
     'Simple majority resolution by Vidhan Sabha / విధానసభ సాధారణ మెజారిటీ తీర్మానం',
     "Governor's recommendation / గవర్నర్ సిఫారసు",
     'c',
     'Art.169: Vidhan Sabha resolution by total majority + 2/3 of members present & voting required. / అనుచ్ఛేదం 169: విధానసభ మొత్తం సభ్యుల మెజారిటీ మరియు హాజరైన-ఓటు వేసిన సభ్యుల 2/3 తీర్మానం తర్వాతే పార్లమెంటు చట్టం చేయగలదు.'),
    (2,
     'medium',
     'What is the tenure of Vidhan Parishad members?\nతెలుగు: విధానపరిషత్ (Vidhan Parishad) సభ్యత్వ కాలవ్యవధి ఎంత?',
     '5 years / 5 సంవత్సరాలు',
     '6 years / 6 సంవత్సరాలు',
     'Governor decides / గవర్నర్ నిర్ణయం',
     'No fixed tenure / కాలవ్యవధి లేదు',
     'b',
     'Vidhan Parishad is permanent; 1/3 retire every 2 years; each member serves 6 years. Modelled on Rajya Sabha. / విధానపరిషత్ శాశ్వత సంస్థ; ప్రతి 2 సంవత్సరాలకు 1/3 సభ్యులు పదవీ విరమణ చేస్తారు; ప్రతి సభ్యుడి పదవీకాలం 6 సంవత్సరాలు. రాజ్యసభ నమూనాలో రూపొందించబడింది.'),
    (3,
     'easy',
     'Who elects the Speaker of Vidhan Sabha?\nతెలుగు: విధానసభ స్పీకర్\u200cను ఎవరు ఎన్నుకుంటారు?',
     'Governor / గవర్నర్',
     'Chief Minister / ముఖ్యమంత్రి',
     'Members of Vidhan Sabha / విధానసభ సభ్యులు',
     'President / రాష్ట్రపతి',
     'c',
     'Art.178: Speaker and Deputy Speaker of Vidhan Sabha are elected by members of the House. / అనుచ్ఛేదం 178: విధానసభ స్పీకర్ మరియు డిప్యూటీ స్పీకర్\u200cలను సభ్యులే ఎన్నుకుంటారు.'),
    (3,
     'medium',
     'Speaker of Vidhan Sabha submits resignation to whom?\nతెలుగు: విధానసభ స్పీకర్ తన రాజీనామాను ఎవరికి ఇవ్వాలి?',
     'Governor / గవర్నర్',
     'Chief Minister / ముఖ్యమంత్రి',
     'Deputy Speaker / డిప్యూటీ స్పీకర్',
     'HC CJ / హైకోర్టు CJ',
     'c',
     'Art.179: Speaker resigns to Deputy Speaker; Deputy Speaker resigns to Speaker. / అనుచ్ఛేదం 179: విధానసభ స్పీకర్ రాజీనామాను డిప్యూటీ స్పీకర్\u200cకు ఇవ్వాలి; డిప్యూటీ స్పీకర్ స్పీకర్\u200cకు ఇవ్వాలి.'),
    (3,
     'medium',
     'Who elects Chairman of Vidhan Parishad?\nతెలుగు: విధానపరిషత్ చైర్మన్\u200cను ఎవరు ఎన్నుకుంటారు?',
     'Governor / గవర్నర్',
     'Members of Vidhan Parishad / విధానపరిషత్ సభ్యులు',
     'Members of Vidhan Sabha / విధానసభ సభ్యులు',
     'Members of both Houses / ఉభయ సభల సభ్యులు',
     'b',
     'Art.182: Chairman and Deputy Chairman of VP are elected by members of VP. / అనుచ్ఛేదం 182: విధానపరిషత్ చైర్మన్ మరియు డిప్యూటీ చైర్మన్\u200cలను పరిషత్ సభ్యులే ఎన్నుకుంటారు.'),
    (3,
     'easy',
     "What is Speaker's role when removal resolution is under consideration?\nతెలుగు: విధానసభ స్పీకర్\u200cను తొలగించే తీర్మానం చర్చలో ఉండగా స్పీకర్ పాత్ర ఏమిటి?",
     'Presides / అధ్యక్షత వహిస్తారు',
     'Can vote but not preside / ఓటు వేయవచ్చు కానీ అధ్యక్షత వహించలేరు',
     'Cannot preside but may be present / అధ్యక్షత వహించలేరు కానీ సభలో ఉండవచ్చు',
     'Must resign immediately / వెంటనే రాజీనామా ఇవ్వాలి',
     'b',
     'Art.181: Speaker cannot preside during resolution for own removal — but can vote (unlike LS Speaker). / అనుచ్ఛేదం 181: తన తొలగింపు తీర్మానం పెండింగ్\u200cలో ఉన్నప్పుడు స్పీకర్ అధ్యక్షత వహించలేరు — కానీ ఆ తీర్మానంపై ఓటు వేయవచ్చు (ఇది లోక్\u200cసభ నుండి భిన్నం).'),
    (3,
     'hard',
     "How many days' notice is required before moving removal resolution of Speaker?\nతెలుగు: విధానసభ స్పీకర్\u200cను తొలగించే తీర్మానానికి ముందు ఎంత నోటీసు అవసరం?",
     '7 days / 7 రోజులు',
     '10 days / 10 రోజులు',
     '14 days / 14 రోజులు',
     '30 days / 30 రోజులు',
     'c',
     "14 days' notice required before a resolution to remove the Speaker (same as LS). / విధానసభ స్పీకర్ తొలగింపు తీర్మానానికి 14 రోజుల ముందస్తు నోటీసు అవసరం (లోక్\u200cసభ వలె)."),
    (3,
     'medium',
     'How long does Speaker continue after Vidhan Sabha is dissolved?\nతెలుగు: ఒక రాష్ట్రంలో విధానసభ రద్దు అయినా స్పీకర్ ఎంత కాలం పదవిలో ఉంటారు?',
     'Immediately loses office / వెంటనే పదవి కోల్పోతారు',
     '6 months / 6 నెలలు',
     'Until new Vidhan Sabha meets / కొత్త విధానసభ సమావేశమయ్యే వరకు',
     'Until term expires / పదవీ కాలం ముగిసే వరకు',
     'c',
     'Speaker continues until new Vidhan Sabha holds its first sitting after dissolution. / విధానసభ రద్దు అయినా స్పీకర్ కొత్త విధానసభ మొదటి సమావేశం వరకు పదవిలో ఉంటారు.'),
    (3,
     'easy',
     'Chairman of Vidhan Parishad resembles which national officer?\nతెలుగు: విధానపరిషత్ చైర్మన్ పాత్ర ఏ జాతీయ స్థాయి అధికారిని పోలి ఉంటుంది?',
     'Lok Sabha Speaker / లోక్\u200cసభ స్పీకర్',
     'Rajya Sabha Chairman (VP) / రాజ్యసభ చైర్మన్ (ఉప రాష్ట్రపతి)',
     'President / రాష్ట్రపతి',
     'CJI',
     'b',
     "VP's Chairman resembles RS Chairman (Vice-President) — both preside over upper houses. / విధానపరిషత్ చైర్మన్ పాత్ర రాజ్యసభ చైర్మన్ (ఉప రాష్ట్రపతి) వలె ఉంటుంది — రెండూ ఎగువ సభల అధ్యక్షులు."),
    (3,
     'medium',
     'What resolution is needed to remove the Vidhan Sabha Speaker?\nతెలుగు: విధానసభ స్పీకర్\u200cని తొలగించడానికి ఏ తీర్మానం అవసరం?',
     'Simple majority resolution / మెజారిటీ తీర్మానం',
     'Two-thirds special majority / 2/3 ప్రత్యేక మెజారిటీ',
     "Effective majority of total members — with 14 days' notice / విధానసభ మొత్తం సభ్యుల ప్రభావ మెజారిటీ — 14 రోజుల ముందస్తు నోటీసుతో",
     "Needs Governor's approval / గవర్నర్ ఆమోదం అవసరం",
     'c',
     "Art.179: Speaker removal requires effective majority (majority of all members) — with 14 days' advance notice. LS Speaker same procedure. / అనుచ్ఛేదం 179: స్పీకర్ తొలగింపుకు విధానసభ మొత్తం సభ్యుల ప్రభావ మెజారిటీ తీర్మానం కావాలి — 14 రోజుల ముందస్తు నోటీసు అవసరం. సాధారణ మెజారిటీ సరిపోదు."),
    (4,
     'easy',
     'State Money Bill can be introduced only in which House?\nతెలుగు: రాష్ట్ర మనీ బిల్లు ఏ సభలో మాత్రమే ప్రవేశపెట్టవచ్చు?',
     'Vidhan Parishad / విధానపరిషత్',
     'Vidhan Sabha / విధానసభ',
     'Either House / రెండు సభల్లో',
     "Either House with Governor's approval / గవర్నర్ ఆమోదంతో ఏ సభలోనైనా",
     'b',
     'Art.198: State Money Bill can be introduced only in Vidhan Sabha. / అనుచ్ఛేదం 198: రాష్ట్ర మనీ బిల్లు విధానసభలో మాత్రమే ప్రవేశపెట్టవచ్చు.'),
    (4,
     'medium',
     'What can Vidhan Parishad do with a Money Bill sent by Vidhan Sabha?\nతెలుగు: రాష్ట్ర మనీ బిల్లు విధానసభ ఆమోదించిన తర్వాత విధానపరిషత్\u200cకు పంపితే పరిషత్ ఏమి చేయగలదు?',
     'Can amend / సవరణలు చేయవచ్చు',
     'Can reject / తిరస్కరించవచ్చు',
     'Return within 14 days; only recommendations / 14 రోజుల్లో తిరిగి పంపాలి; సిఫారసులు మాత్రమే',
     'Can withhold for 6 months / 6 నెలలు నిలిపివేయవచ్చు',
     'c',
     'Art.198: VP must return within 14 days with recommendations only; Vidhan Sabha need not accept them. / అనుచ్ఛేదం 198: విధానపరిషత్ మనీ బిల్లును 14 రోజుల్లో తిరిగి పంపాలి; కేవలం సిఫారసులు మాత్రమే చేయగలదు; విధానసభ వాటిని పట్టించుకోవాల్సిన అవసరం లేదు.'),
    (4,
     'medium',
     'What happens if Vidhan Parishad rejects a Bill passed by Vidhan Sabha?\nతెలుగు: విధానసభ ఆమోదించిన సాధారణ బిల్లు విధానపరిషత్ తిరస్కరిస్తే ఏమవుతుంది?',
     'Bill lapses / బిల్లు రద్దవుతుంది',
     'Joint session called / జాయింట్ సెషన్ పిలుస్తారు',
     'After 3 months if VA passes again, can send to Governor / విధానసభ 3 నెలల తర్వాత మళ్ళీ పాస్ చేస్తే గవర్నర్\u200cకు పంపవచ్చు',
     "Governor's assent suffices / గవర్నర్ ఆమోదం సరిపోతుంది",
     'c',
     'Art.197: Vidhan Sabha can override VP by passing bill again after 3 months. / అనుచ్ఛేదం 197: విధానపరిషత్ బిల్లు తిరస్కరించినా, 3 నెలలు నిలిపినా, లేదా సవరణలు విధానసభ అంగీకరించకుండా పంపినా — విధానసభ మళ్ళీ ఆమోదిస్తే గవర్నర్\u200cకు పంపవచ్చు.'),
    (4,
     'hard',
     'Is there a provision for joint sitting in state legislature?\nతెలుగు: రాష్ట్ర శాసనమండలిలో జాయింట్ సెషన్ అవకాశం ఉందా?',
     'Yes, like Lok Sabha / అవును, లోక్\u200cసభ వలె',
     'No / లేదు',
     'Only with Presidential approval / కేవలం రాష్ట్రపతి ఆమోదంతో',
     'Only for financial bills / కేవలం ఆర్థిక బిల్లులకు',
     'b',
     'No joint sitting provision for state legislature — Art.108 applies only to Parliament. / రాష్ట్ర శాసనమండలిలో జాయింట్ సెషన్ అవకాశం లేదు — అనుచ్ఛేదం 108 కేవలం పార్లమెంటుకు మాత్రమే వర్తిస్తుంది.'),
    (4,
     'easy',
     'Who certifies a bill as State Money Bill?\nతెలుగు: రాష్ట్ర మనీ బిల్లు అని ఎవరు ధృవీకరిస్తారు?',
     'Governor / గవర్నర్',
     'Speaker of Vidhan Sabha / విధానసభ స్పీకర్',
     'Chief Minister / ముఖ్యమంత్రి',
     'President / రాష్ట్రపతి',
     'b',
     'Art.199: Speaker of Vidhan Sabha certifies a bill as Money Bill. / అనుచ్ఛేదం 199: విధానసభ స్పీకర్ బిల్లును మనీ బిల్లుగా ధృవీకరిస్తారు.'),
    (4,
     'medium',
     "No-confidence motion against CM can be moved in which house?\nతెలుగు: రాష్ట్ర శాసనసభ 'అవిశ్వాస తీర్మానం' (No-confidence motion) ఏ సభలో పెట్టవచ్చు?",
     'Vidhan Parishad / విధానపరిషత్',
     'Only Vidhan Sabha / విధానసభ మాత్రమే',
     'Both Houses / రెండు సభల్లోనూ',
     'Governor decides / గవర్నర్ నిర్ణయిస్తారు',
     'b',
     'No-confidence only in Vidhan Sabha — state CoM responsible only to Vidhan Sabha. / అవిశ్వాస తీర్మానం విధానసభలో మాత్రమే పెట్టవచ్చు — రాష్ట్ర మంత్రిమండలి విధానసభకు మాత్రమే జవాబుదారీ.'),
    (4,
     'hard',
     'Can Governor withhold assent to Money Bill passed by Vidhan Sabha?\nతెలుగు: విధానసభ ఆమోదించిన మనీ బిల్లుకు గవర్నర్ ఆమోదం నిలిపివేయవచ్చా?',
     'Yes / అవును',
     'No / లేదు',
     "With President's permission / రాష్ట్రపతి అనుమతితో",
     'Can reserve for President / రాష్ట్రపతికి నివేదించవచ్చు',
     'd',
     'Art.200: Governor cannot return Money Bill — must assent or reserve for President. / అనుచ్ఛేదం 200: గవర్నర్ మనీ బిల్లును తిరిగి పంపలేరు; ఆమోదించాలి లేదా రాష్ట్రపతి పరిశీలనకు నివేదించవచ్చు.'),
    (4,
     'medium',
     'If Vidhan Parishad delays ordinary Bill for 3 months, what happens?\nతెలుగు: విధానపరిషత్ ఉన్న రాష్ట్రంలో సాధారణ బిల్లు గురించి విధానపరిషత్ 3 నెలలు ఆలస్యం చేస్తే ఏమవుతుంది?',
     'Bill lapses / బిల్లు రద్దవుతుంది',
     'If Vidhan Sabha passes it again, Bill is deemed passed / విధానసభ రెండవ సారి ఆమోదిస్తే బిల్లు ఆమోదించినట్లు',
     'Governor mediates / గవర్నర్ మధ్యవర్తిత్వం చేస్తారు',
     'Joint session is held / సంయుక్త సమావేశం ఏర్పాటవుతుంది',
     'b',
     '3 నెలలు నిలిపివేసినా / సవరణలతో ఆమోదించినా — విధానసభ మళ్ళీ ఆమోదిస్తే (అదే సవరణలతో లేదా లేకుండా) ఆమోదించినట్లు. / Art.197(1): If Vidhan Parishad rejects/delays (3 months)/passes with amendments — Vidhan Sabha can pass again; deemed to have passed both Houses. / Art.197(1): విధానసభ ఆమోదించిన బిల్లును విధానపరిషత్ తిరస్కరించినా'),
    (5,
     'easy',
     'State legislature powers and privileges are in which Article?\nతెలుగు: రాష్ట్ర శాసనమండలి సభ్యుల అధికారాలు & హక్కులు ఏ అనుచ్ఛేదంలో ఉన్నాయి?',
     'Art.191 / అనుచ్ఛేదం 191',
     'Art.194 / అనుచ్ఛేదం 194',
     'Art.197 / అనుచ్ఛేదం 197',
     'Art.200 / అనుచ్ఛేదం 200',
     'b',
     'Art.194: Powers, privileges and immunities of state legislature houses, members and committees. / అనుచ్ఛేదం 194: రాష్ట్ర శాసనమండలి సభలు, వాటి సభ్యులు, కమిటీల అధికారాలు, హక్కులు మరియు మినహాయింపులు.'),
    (5,
     'medium',
     'Can courts inquire into proceedings of state legislature?\nతెలుగు: రాష్ట్ర శాసనమండలి కార్యవిధానపై న్యాయస్థానాలు పరిశీలించగలవా?',
     'Yes / అవును',
     'No / లేదు',
     'HC only / హైకోర్టు మాత్రమే',
     'SC only / సుప్రీం కోర్టు మాత్రమే',
     'b',
     'Art.212: Courts cannot inquire into proceedings of state legislature. / అనుచ్ఛేదం 212: కోర్టులు రాష్ట్ర శాసనమండలి కార్యవిధానాన్ని పరిశీలించే అధికారం లేదు.'),
    (5,
     'medium',
     'Salaries and allowances of state legislature members are in which Article?\nతెలుగు: రాష్ట్ర శాసనమండలి సభ్యుల జీతాలు, భత్యాలు ఏ అనుచ్ఛేదంలో ప్రస్తావించబడ్డాయి?',
     'Art.193 / అనుచ్ఛేదం 193',
     'Art.195 / అనుచ్ఛేదం 195',
     'Art.196 / అనుచ్ఛేదం 196',
     'Art.194 / అనుచ్ఛేదం 194',
     'b',
     'Art.195: Members of state legislature receive salaries and allowances as state legislature determines. / అనుచ్ఛేదం 195: రాష్ట్ర శాసనమండలి సభ్యులు రాష్ట్ర శాసనమండలి నిర్ణయించే జీతాలు, భత్యాలు పొందుతారు.'),
    (5,
     'hard',
     'Penalty for sitting/voting without oath in state legislature?\nతెలుగు: రాష్ట్ర శాసనమండలి సభ్యుడు ప్రమాణం చేయకుండా కూర్చుని ఓటు వేస్తే శిక్ష ఏమిటి?',
     'Membership cancelled / సభ్యత్వం రద్దు',
     'Rs.500 fine / రూ.500 జరిమానా',
     'Rs.500 fine per day / రూ.500 జరిమానా ప్రతి రోజుకు',
     '6 months imprisonment / 6 నెలల జైలు',
     'c',
     'Art.193: Penalty for sitting and voting before oath — Rs.500 per day. / అనుచ్ఛేదం 193: ప్రమాణం చేయకుండా కూర్చుని ఓటు వేస్తే రోజుకు రూ.500 జరిమానా.'),
    (5,
     'easy',
     'Which Article prohibits state legislature discussion on sub-judice matters?\nతెలుగు: రాష్ట్ర శాసనమండలి అదివేష పరిమితులు (కార్యవిధాన నిరోధం) ఏ అనుచ్ఛేదంలో ఉన్నాయి?',
     'Art.208 / అనుచ్ఛేదం 208',
     'Art.211 / అనుచ్ఛేదం 211',
     'Art.212 / అనుచ్ఛేదం 212',
     'Art.213 / అనుచ్ఛేదం 213',
     'b',
     'Art.211: Prohibits discussion on conduct of judges and sub-judice matters. / అనుచ్ఛేదం 211: న్యాయమూర్తుల ప్రవర్తనపై, న్యాయస్థానాల పరిశీలనలో ఉన్న విషయాలపై చర్చించడాన్ని నిషేధిస్తుంది.'),
    (5,
     'medium',
     'State Annual Financial Statement is laid in which House?\nతెలుగు: రాష్ట్ర శాసనమండలి వార్షిక ఆర్థిక నివేదిక (State Budget) ఏ సభలో సమర్పించబడుతుంది?',
     'Vidhan Parishad / విధానపరిషత్',
     'Vidhan Sabha / విధానసభ',
     'Both Houses simultaneously / రెండు సభల్లోనూ ఒకేసారి',
     'Either House / ఏ సభలోనైనా',
     'b',
     'Art.202: Annual Financial Statement (Budget) of state is laid before Vidhan Sabha. / అనుచ్ఛేదం 202: రాష్ట్ర వార్షిక ఆర్థిక నివేదిక విధానసభలో సమర్పించబడుతుంది.'),
    (5,
     'hard',
     "Members' speech freedom in state legislature — cannot be questioned in court — which Article?\nతెలుగు: రాష్ట్ర శాసనమండలి సభ్యులు 'ఉపన్యాస స్వేచ్ఛ' కింద ఏ కోర్టులోనూ విచారించబడరు — ఈ హక్కు ఏ అనుచ్ఛేదంలో?",
     'Art.191 / అనుచ్ఛేదం 191',
     'Art.193 / అనుచ్ఛేదం 193',
     'Art.194(2) / అనుచ్ఛేదం 194(2)',
     'Art.212 / అనుచ్ఛేదం 212',
     'c',
     'Art.194(2): No proceedings of member in state legislature shall be questioned in any court. / అనుచ్ఛేదం 194(2): రాష్ట్ర శాసనమండలిలో సభ్యుడు చేసిన ఉపన్యాసాలు లేదా ఓటుపై ఏ కోర్టులోనూ విచారించరాదు.'),
    (5,
     'medium',
     'Who determines salaries and allowances of state legislature members?\nతెలుగు: రాష్ట్ర శాసనమండలి సభ్యుల జీతభత్యాలు ఎవరు నిర్ణయిస్తారు?',
     'Governor / గవర్నర్',
     'Chief Minister / ముఖ్యమంత్రి',
     'State legislature by law / రాష్ట్ర శాసనమండలి చట్టం ద్వారా',
     'Union Finance Ministry / కేంద్ర ఆర్థిక మంత్రిత్వ శాఖ',
     'c',
     'Art.195: Salaries/allowances of state legislature members = as fixed by state legislature by law; until then as President determines. / అనుచ్ఛేదం 195: రాష్ట్ర శాసనమండలి సభ్యుల జీతాలు, భత్యాలు రాష్ట్ర శాసనమండలి చట్టం ద్వారా నిర్ణయించబడతాయి — మరియు అటువంటి చట్టం చేయబడే వరకు రాష్ట్రపతి నిర్దేశించే విధంగా ఉంటాయి.'),
    (6,
     'easy',
     'Anti-defection provisions for state legislature members are in which Schedule?\nతెలుగు: రాష్ట్ర శాసనమండలి సభ్యుల పార్టీ ఫిరాయింపు వ్యతిరేక నిబంధనలు ఏ షెడ్యూల్\u200cలో ఉన్నాయి?',
     '8th Schedule / 8వ షెడ్యూల్',
     '9th Schedule / 9వ షెడ్యూల్',
     '10th Schedule / 10వ షెడ్యూల్',
     '11th Schedule / 11వ షెడ్యూల్',
     'c',
     '10th Schedule (52nd Amendment 1985): Anti-defection — applies to Parliament and state legislatures. / 10వ షెడ్యూల్ (52వ సవరణ 1985): పార్టీ ఫిరాయింపు వ్యతిరేక చట్టం — పార్లమెంటు మరియు రాష్ట్ర శాసనమండలులకు వర్తిస్తుంది.'),
    (6,
     'medium',
     'Who decides disqualification under 10th Schedule?\nతెలుగు: 10వ షెడ్యూల్ కింద అనర్హత నిర్ణయించే అధికారం ఎవరికి ఉంది?',
     'High Court / హైకోర్టు',
     'Supreme Court / సుప్రీం కోర్టు',
     'Presiding Officer (Speaker/Chairman) / సభాపతి (స్పీకర్/చైర్మన్)',
     'Election Commission / ఎన్నికల కమిషన్',
     'c',
     '10th Schedule: Speaker/Chairman decides defection disqualification; but SC review permitted per Kihoto case 1992. / 10వ షెడ్యూల్: పార్టీ ఫిరాయింపు అనర్హత నిర్ణయం స్పీకర్/చైర్మన్ అధికారం. అయితే కిహోతో హొల్లోహన్ కేసు (1992) ప్రకారం న్యాయ సమీక్షకు అర్హమే.'),
    (6,
     'hard',
     "Minimum % of members required for 'Merger' under 10th Schedule?\nతెలుగు: 10వ షెడ్యూల్ కింద విలీనానికి (Merger) అనుమతించే సభ్యుల కనిష్ట శాతం ఎంత?",
     '50%',
     '2/3',
     '3/4',
     '4/5',
     'b',
     '10th Schedule: Merger valid if 2/3 of original legislature party agrees — exempt from disqualification. / 10వ షెడ్యూల్: పార్టీ మూల శాసనసభా పక్షంలో 2/3 సభ్యులు విలీనానికి అంగీకరిస్తే అది అనర్హత నుండి మినహాయింపు.'),
    (6,
     'medium',
     "MLA becomes disqualified for holding 'office of profit' — which Article?\nతెలుగు: శాసనసభ సభ్యుడు 'లాభదాయక పదవి' (office of profit) పొందితే అనర్హుడవుతారు — ఏ అనుచ్ఛేదం?",
     'Art.191(1)(a) / అనుచ్ఛేదం 191(1)(a)',
     'Art.192 / అనుచ్ఛేదం 192',
     'Art.193 / అనుచ్ఛేదం 193',
     '10th Schedule / 10వ షెడ్యూల్',
     'a',
     'Art.191(1)(a): Disqualification if holding office of profit under Union or State government. / అనుచ్ఛేదం 191(1)(a): కేంద్ర లేదా రాష్ట్ర ప్రభుత్వం కింద లాభదాయక పదవి పొందిన వ్యక్తి విధానసభ/పరిషత్ సభ్యత్వానికి అనర్హుడు.'),
    (6,
     'easy',
     'MLA declared of unsound mind is disqualified — which Article?\nతెలుగు: శాసనసభ సభ్యుడు మానసికంగా అస్వస్థుడని ప్రకటించబడితే అనర్హుడవుతాడు — ఏ అనుచ్ఛేదం?',
     'Art.191(1)(b) / అనుచ్ఛేదం 191(1)(b)',
     'Art.191(1)(c) / అనుచ్ఛేదం 191(1)(c)',
     'Art.192 / అనుచ్ఛేదం 192',
     'Art.194 / అనుచ్ఛేదం 194',
     'a',
     'Art.191(1)(b): Person declared of unsound mind by competent court is disqualified. / అనుచ్ఛేదం 191(1)(b): సక్షమ న్యాయస్థానం మానసిక అస్వస్థతగా ప్రకటించిన వ్యక్తి అనర్హుడు.'),
    (6,
     'hard',
     'Which Constitutional Amendment added the 10th Schedule?\nతెలుగు: 10వ షెడ్యూల్ చేర్చబడిన రాజ్యాంగ సవరణ ఏది?',
     '44th Amendment / 44వ సవరణ',
     '52nd Amendment / 52వ సవరణ',
     '73rd Amendment / 73వ సవరణ',
     '91st Amendment / 91వ సవరణ',
     'b',
     '52nd Constitutional Amendment 1985: Added the anti-defection 10th Schedule. / 52వ రాజ్యాంగ సవరణ 1985: పార్టీ ఫిరాయింపు వ్యతిరేక చట్టం రూపకల్పన — 10వ షెడ్యూల్ రాజ్యాంగంలో చేర్చబడింది.'),
    (6,
     'medium',
     'If state legislature member voluntarily gives up membership or votes against party whip — who decides disqualification?\nతెలుగు: రాష్ట్ర శాసనమండలి సభ్యుడు స్వచ్ఛంద రాజీనామా లేదా విప్ ఉల్లంఘిస్తే — అనర్హత నిర్ణయం ఎవరు తీసుకుంటారు?',
     'Speaker or Chairman / స్పీకర్ లేదా చైర్మన్',
     'High Court / హైకోర్టు',
     'Governor / గవర్నర్',
     'Election Commission / ఎన్నికల కమిషన్',
     'a',
     '10th Schedule Para 6: Disqualification on defection decided by Speaker (Vidhan Sabha) or Chairman (Vidhan Parishad). / 10వ షెడ్యూల్ పారా 6: పార్టీ ఫిరాయింపు అనర్హత — స్పీకర్ (విధానసభకు) లేదా చైర్మన్ (విధానపరిషత్\u200cకు) నిర్ణయిస్తారు.'),
    (6,
     'hard',
     "If a Vidhan Sabha member wins as independent and then joins a party?\nతెలుగు: విధానసభ సభ్యుడు 'నిర్దల' (independent) అభ్యర్థిగా గెలిస్తే పార్టీలో చేరవచ్చా?",
     'Can join within 6 months / 6 నెలలలో చేరవచ్చు',
     'Disqualified — independent cannot join any party / అనర్హత వర్తిస్తుంది — నిర్దల అభ్యర్థి ఏ పార్టీలోనూ చేరలేరు',
     'Can join anytime / ఎప్పుడైనా చేరవచ్చు',
     "Can join with Speaker's permission / స్పీకర్ అనుమతితో చేరవచ్చు",
     'b',
     '10th Schedule Para 2(2): Independent elected member who joins any political party after election becomes disqualified. / 10వ షెడ్యూల్ పారా 2(2): నిర్దల అభ్యర్థిగా ఎన్నికైన తర్వాత ఏదైనా రాజకీయ పార్టీలో చేరినట్లయితే అనర్హత వర్తిస్తుంది. ఎన్నికైన తర్వాత ఎప్పుడూ పార్టీలో చేరలేరు.'),
    (7,
     'easy',
     'Qualifications for Vidhan Sabha membership are in which Article?\nతెలుగు: విధానసభ సభ్యత్వానికి అర్హతలు ఏ అనుచ్ఛేదంలో ఉన్నాయి?',
     'Art.170 / అనుచ్ఛేదం 170',
     'Art.173 / అనుచ్ఛేదం 173',
     'Art.175 / అనుచ్ఛేదం 175',
     'Art.177 / అనుచ్ఛేదం 177',
     'b',
     'Art.173: Qualifications for membership of state legislature. / అనుచ్ఛేదం 173: రాష్ట్ర శాసనమండలి సభ్యత్వానికి అర్హతలు — పౌరుడు, వయస్సు, ఓటరు నమోదు, అనర్హతలు లేకుండా ఉండటం.'),
    (7,
     'medium',
     'What happens if MLA absent without permission for one year?\nతెలుగు: విధానసభ సభ్యుడు ఒక సంవత్సరం పాటు అనుమతి లేకుండా సభకు హాజరు కాకుంటే ఏమవుతుంది?',
     'Seat declared vacant / సభ్యత్వం రద్దవుతుంది',
     'Fine imposed / జరిమానా విధిస్తారు',
     'Seat held / ఆ స్థానం హోల్డ్ అవుతుంది',
     'EC decides / ఎన్నికల కమిషన్ నిర్ణయిస్తుంది',
     'a',
     'Art.190(4): Seat vacated if member absent without permission for 60 days. / అనుచ్ఛేదం 190(4): సభ్యుడు 60 రోజులకు మించి అనుమతి లేకుండా సభకు హాజరు కాకుంటే సభ్యత్వం రద్దవుతుంది.'),
    (7,
     'hard',
     'Oath form for state legislature members is in which Schedule?\nతెలుగు: రాష్ట్ర శాసనమండలి సభ్యుల ప్రమాణ పత్రం ఏ షెడ్యూల్\u200cలో ఉంటుంది?',
     '2nd Schedule / రెండో షెడ్యూల్',
     '3rd Schedule / మూడో షెడ్యూల్',
     '4th Schedule / నాల్గో షెడ్యూల్',
     '6th Schedule / ఆరో షెడ్యూల్',
     'b',
     'Third Schedule contains oath forms for state legislature members too. / తృతీయ షెడ్యూల్ (Third Schedule): రాష్ట్ర శాసనమండలి సభ్యుల ప్రమాణ పత్రాలు కూడా ఇందులోనే ఉంటాయి.'),
    (7,
     'easy',
     "State Appropriation Bill introduced in which House?\nతెలుగు: విధానసభ 'ఆప్రోప్రియేషన్ బిల్లు' (Appropriation Bill) ఏ సభలో ప్రవేశపెట్టాలి?",
     'Vidhan Parishad / విధానపరిషత్',
     'Vidhan Sabha / విధానసభ',
     'Both simultaneously / రెండు సభల్లో ఒకేసారి',
     'Either House / ఏ సభలోనైనా',
     'b',
     'Art.204: State Appropriation Bill introduced only in Vidhan Sabha — it has Money Bill character. / అనుచ్ఛేదం 204: రాష్ట్ర ఆప్రోప్రియేషన్ బిల్లు విధానసభలోనే ప్రవేశపెట్టాలి — ఇది మనీ బిల్లు స్వభావం కలిగి ఉంటుంది.'),
    (7,
     'medium',
     'Which Article deals with language to be used in state legislature?\nతెలుగు: రాష్ట్ర శాసనమండలి భాషను ఏ అనుచ్ఛేదం నిర్ణయిస్తుంది?',
     'Art.208 / అనుచ్ఛేదం 208',
     'Art.210 / అనుచ్ఛేదం 210',
     'Art.211 / అనుచ్ఛేదం 211',
     'Art.212 / అనుచ్ఛేదం 212',
     'b',
     "Art.210: Hindi or official language of state used; other language with Speaker's/Chairman's permission. / అనుచ్ఛేదం 210: రాష్ట్ర శాసనమండలిలో హిందీ లేదా రాష్ట్ర అధికారిక భాష వినియోగించాలి. స్పీకర్/చైర్మన్ అనుమతితో ఇతర భాష వాడవచ్చు."),
    (7,
     'hard',
     'Can abolition of Vidhan Parishad be challenged in court?\nతెలుగు: విధానపరిషత్ రద్దు చేయబడిన తర్వాత ఆ చర్యపై న్యాయస్థానంలో సవాలు చేయవచ్చా?',
     'Yes / అవును',
     "No — Parliament's power / లేదు — పార్లమెంటు అధికారం",
     'Only in HC / హైకోర్టులో మాత్రమే',
     'Only in SC / సుప్రీం కోర్టులో మాత్రమే',
     'b',
     "Parliament's law under Art.169 is ordinary legislation; SC review technically possible but Parliament's power generally upheld. / అనుచ్ఛేదం 169 ప్రకారం పార్లమెంటు చేసే చట్టానికి రాజ్యాంగ సవరణ హోదా లేదు — సాధారణ చట్టం. SC సమీక్ష సాంకేతికంగా సాధ్యం, ఆచరణలో పార్లమెంటు అధికారాన్ని సమర్థిస్తారు."),
    (7,
     'medium',
     'Qualifications for state legislature membership are in which Article?\nతెలుగు: రాష్ట్ర శాసనమండలి సభ్యుల అర్హతలు ఏ అనుచ్ఛేదంలో ఉన్నాయి?',
     'Art.173 / అనుచ్ఛేదం 173',
     'Art.191 / అనుచ్ఛేదం 191',
     'Art.192 / అనుచ్ఛేదం 192',
     'Art.172 / అనుచ్ఛేదం 172',
     'a',
     'Art.173: Qualifications — Indian citizen; 25 years for Vidhan Sabha; 30 years for Vidhan Parishad. Disqualifications in Art.191. / అనుచ్ఛేదం 173: రాష్ట్ర శాసనమండలి సభ్యత్వానికి అర్హతలు — భారత పౌరుడు, విధానసభకు 25 సంవత్సరాలు మరియు విధానపరిషత్\u200cకు 30 సంవత్సరాలు. అనర్హతలు Art.191 లో ఉన్నాయి.'),
    (7,
     'hard',
     'Art.208 deals with what in state legislature?\nతెలుగు: అనుచ్ఛేదం 208 రాష్ట్ర శాసనమండలిలో ఏ విషయాన్ని నిర్ణయిస్తుంది?',
     'Rules of procedure / వ్యాపార నిర్వహణ నియమాలు',
     "Members' salaries / సభ్యుల జీతాలు",
     'Quorum / కోరం',
     'Definition of Money Bill / మనీ బిల్లు నిర్వచనం',
     'a',
     'Art.208: State legislature may make rules for regulation of procedure. Quorum = 1/10 of total members (Art.189(3)). / అనుచ్ఛేదం 208: రాష్ట్ర శాసనమండలి తన వ్యాపారం నిర్వహణకు నియమాలు తయారు చేసుకోవచ్చు. రాష్ట్రపతి ఆమోదం లేకుండా. Art.100(3) = కోరం (1/10 సభ్యులు).'),
]


def _seed_polity_ch19_notes_inner(conn, db_exec_fn, row_to_dict_fn, use_postgres, force=False):
    ph = '%s' if use_postgres else '?'
    existing = db_exec_fn(conn,
        f"SELECT id FROM study_notes WHERE subject={ph} AND topic={ph} AND chapter_num={ph}",
        (_SUBJECT, _TOPIC, _CH))
    row = existing.fetchone()
    if row and not force:
        return
    sections_json = __import__('json').dumps(
        [{"title": s, "content": ""} for s in _SECTIONS], ensure_ascii=False)
    if row and force:
        note_id = row_to_dict_fn(row)['id']
        db_exec_fn(conn,
            f"UPDATE study_notes SET chapter_title_te={ph}, chapter_title_en={ph}, "
            f"pages_ref={ph}, sections_json={ph} WHERE id={ph}",
            (_TITLE_TE, _TITLE_EN, _PAGES, sections_json, note_id))
    else:
        db_exec_fn(conn,
            f"INSERT INTO study_notes (subject, topic, chapter_num, chapter_title_te, "
            f"chapter_title_en, pages_ref, sections_json) VALUES ({ph},{ph},{ph},{ph},{ph},{ph},{ph})",
            (_SUBJECT, _TOPIC, _CH, _TITLE_TE, _TITLE_EN, _PAGES, sections_json))


def _seed_polity_ch19_mcqs_inner(conn, db_exec_fn, row_to_dict_fn, use_postgres):
    ph = '%s' if use_postgres else '?'
    diff_map = {"easy": 1, "medium": 2, "hard": 3, "toughest": 4, 1: 1, 2: 2, 3: 3, 4: 4}
    note_cur = db_exec_fn(conn,
        f"SELECT id FROM study_notes WHERE subject={ph} AND topic={ph} AND chapter_num={ph}",
        (_SUBJECT, _TOPIC, _CH))
    note_row = note_cur.fetchone()
    if not note_row:
        return
    note_id = row_to_dict_fn(note_row)['id']
    existing = db_exec_fn(conn,
        f"SELECT COUNT(*) FROM chapter_mcqs WHERE study_note_id={ph}", (note_id,))
    if list(existing.fetchone())[0] > 0:
        return
    for row in _MCQS:
        sec_idx = row[0]; diff_int = diff_map.get(row[1], 1)
        q_te = row[2]; opt_a = row[3]; opt_b = row[4]; opt_c = row[5]; opt_d = row[6]
        correct = str(row[7]).lower(); expl = row[8] if len(row) > 8 else ''
        exam_type = row[9] if len(row) > 9 else 'General'
        db_exec_fn(conn,
            f"""INSERT INTO chapter_mcqs (study_note_id, section_idx, difficulty, exam_type,
                 q_te, opt_a, opt_b, opt_c, opt_d, correct, explanation_te)
                VALUES ({ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph})""",
            (note_id, sec_idx, diff_int, exam_type, q_te, opt_a, opt_b, opt_c, opt_d, correct, expl))
