import sqlite3, os

SOURCE = 'Science_Set15B_Living_GK_Ext'
DB = os.path.join(os.path.dirname(__file__), 'database.db')

questions = [
    ('What is an ecosystem?\\nతెలుగు: పర్యావరణ వ్యవస్థ అంటే ఏమిటి?', 'Community of organisms and their physical environment / జీవుల సమూహం మరియు వాటి భౌతిక పర్యావరణం', 'Only living organisms / కేవలం జీవులు', 'Only the physical environment / కేవలం భౌతిక పర్యావరణం', 'A food web / ఆహార జాలం', 'A', 'M', '', 1),
    ('Producers in an ecosystem are?\\nతెలుగు: పర్యావరణ వ్యవస్థలో ఉత్పత్తిదారులు ఎవరు?', 'Green plants (autotrophs) / పచ్చని మొక్కలు (ఆటోట్రోఫ్లు)', 'Animals / జంతువులు', 'Decomposers / కుళ్ళించేవి', 'Omnivores / సర్వభక్షకులు', 'A', 'M', '', 2),
    ('What is a food chain?\\nతెలుగు: ఆహార శృంఖలం అంటే ఏమిటి?', 'Linear sequence of organisms eating each other / ఒకదానిని ఒకటి తినే జీవుల రేఖీయ వరుస', 'A web of food sources / ఆహార వనరుల జాలం', 'Decomposition process / కుళ్ళు ప్రక్రియ', 'Nutrient cycle / పోషక చక్రం', 'A', 'M', '', 3),
    ('Primary consumers in a food chain eat?\\nతెలుగు: ఆహార శృంఖలంలో ప్రాథమిక వినియోగదారులు ఏమి తింటారు?', 'Producers (plants) / ఉత్పత్తిదారులు (మొక్కలు)', 'Secondary consumers / ద్వితీయ వినియోగదారులు', 'Other animals / ఇతర జంతువులు', 'Decomposers / కుళ్ళించేవి', 'A', 'M', '', 4),
    ('What is biodiversity?\\nతెలుగు: జీవవైవిధ్యం అంటే ఏమిటి?', 'Variety of life on Earth / భూమిపై జీవిత వైవిధ్యం', 'Number of plants only / కేవలం మొక్కల సంఖ్య', 'Genetic variation in one species / ఒక జాతిలో జన్యు వైవిధ్యం', 'Ocean species only / సముద్ర జాతులు మాత్రమే', 'A', 'M', '', 5),
    ('Which layer of atmosphere contains the ozone layer?\\nతెలుగు: ఓజోన్ పొర వాతావరణం యొక్క ఏ పొరలో ఉంటుంది?', 'Stratosphere / స్ట్రాటోస్పియర్', 'Troposphere / ట్రోపోస్పియర్', 'Mesosphere / మెసోస్పియర్', 'Thermosphere / థర్మోస్పియర్', 'A', 'M', '', 6),
    ('Greenhouse gases include?\\nతెలుగు: గ్రీన్‌హౌస్ వాయువులు ఏవి?', 'CO₂, methane, water vapor / CO₂, మీథేన్, నీటి ఆవిరి', 'Only oxygen / కేవలం ఆక్సిజన్', 'Only nitrogen / కేవలం నైట్రోజన్', 'Argon and helium / ఆర్గాన్ మరియు హీలియం', 'A', 'M', '', 7),
    ('What is the nitrogen cycle?\\nతెలుగు: నైట్రోజన్ చక్రం అంటే ఏమిటి?', 'Circulation of nitrogen through ecosystems / పర్యావరణ వ్యవస్థల ద్వారా నైట్రోజన్ చలన చక్రం', 'Photosynthesis process / కిరణజన్య సంయోగ ప్రక్రియ', 'Decomposition of proteins / ప్రోటీన్ల కుళ్ళు', 'Oxygen production / ఆక్సిజన్ ఉత్పత్తి', 'A', 'M', '', 8),
    ('Which biome is characterized by permafrost?\\nతెలుగు: శాశ్వత మంచుతో వర్గీకరించబడిన బయోమ్ ఏది?', 'Tundra / టుండ్రా', 'Desert / ఎడారి', 'Rainforest / వర్షారణ్యం', 'Grassland / గడ్డి భూమి', 'A', 'M', '', 9),
    ('Symbiosis refers to?\\nతెలుగు: సహజీవనం అంటే ఏమిటి?', 'Close relationship between two species / రెండు జాతుల మధ్య సన్నిహిత సంబంధం', 'Competition between species / జాతుల మధ్య పోటీ', 'Predator-prey relationship only / మాంసాహారి-ఆహారం సంబంధం మాత్రమే', 'Seasonal migration / కాలానుగుణ వలస', 'A', 'M', '', 10),
    ('Darwin\'s theory is based on?\\nతెలుగు: డార్విన్ సిద్ధాంతం దేనిపై ఆధారపడింది?', 'Natural selection / సహజ ఎంపిక', 'Artificial selection / కృత్రిమ ఎంపిక', 'Genetic engineering / జన్యు ఇంజినీరింగ్', 'Spontaneous generation / స్వయంజాత ఉత్పత్తి', 'A', 'M', '', 11),
    ('What is the theory of evolution?\\nతెలుగు: పరిణామ సిద్ధాంతం అంటే ఏమిటి?', 'Species change over time through natural selection / జాతులు సహజ ఎంపిక ద్వారా కాలక్రమేణా మారతాయి', 'All species were created at once / అన్ని జాతులు ఒకేసారి సృష్టించబడ్డాయి', 'Only plants evolve / కేవలం మొక్కలు పరిణమిస్తాయి', 'Evolution stops with modern species / ఆధునిక జాతులతో పరిణామం ఆగిపోతుంది', 'A', 'M', '', 12),
    ('Fossils provide evidence for?\\nతెలుగు: శిలాజాలు దేనికి సాక్ష్యం అందిస్తాయి?', 'Evolution of organisms / జీవుల పరిణామం', 'Climate change / వాతావరణ మార్పు', 'Soil composition / మట్టి కూర్పు', 'Ocean depth / సముద్ర లోతు', 'A', 'M', '', 13),
    ('Natural selection favors traits that?\\nతెలుగు: సహజ ఎంపిక ఏ లక్షణాలకు అనుకూలంగా ఉంటుంది?', 'Increase survival and reproduction / మనుగడ మరియు పునరుత్పత్తిని పెంచేవి', 'Are the largest / అతి పెద్దవి', 'Are the most colorful / అత్యంత రంగురంగులైనవి', 'Are inherited from parents / తల్లిదండ్రుల నుండి వారసత్వంగా వచ్చినవి', 'A', 'M', '', 14),
    ('Who wrote "On the Origin of Species"?\\nతెలుగు: "On the Origin of Species" ఎవరు రాశారు?', 'Charles Darwin / చార్లెస్ డార్విన్', 'Gregor Mendel / గ్రెగర్ మెండెల్', 'Jean-Baptiste Lamarck / జీన్-బాప్టిస్ట్ లామార్క్', 'Alfred Wallace / ఆల్‌ఫ్రెడ్ వాలేస్', 'A', 'M', '', 15),
    ('Who invented the microscope?\\nతెలుగు: మైక్రోస్కోప్ ఎవరు కనుగొన్నారు?', 'Antonie van Leeuwenhoek / యాంటోనీ వాన్ లీవెన్‌హుక్', 'Robert Hooke / రాబర్ట్ హుక్', 'Louis Pasteur / లూయీ పాశ్చర్', 'Robert Koch / రాబర్ట్ కాక్', 'A', 'M', '', 16),
    ('Which microorganism causes malaria?\\nతెలుగు: మలేరియాకు కారణమయ్యే సూక్ష్మజీవి ఏది?', 'Plasmodium (protozoa) / ప్లాస్మోడియం (ప్రోటోజోవా)', 'Bacteria / బాక్టీరియా', 'Virus / వైరస్', 'Fungi / ఫంగై', 'A', 'M', '', 17),
    ('Penicillin is derived from?\\nతెలుగు: పెన్సిలిన్ దేనినుండి తీసుకోబడింది?', 'Penicillium (fungus) / పెన్సిలియం (ఫంగస్)', 'Bacteria / బాక్టీరియా', 'Plant extract / మొక్క సారం', 'Virus / వైరస్', 'A', 'M', '', 18),
    ('Yogurt is made by action of?\\nతెలుగు: పెరుగు దేని పనితీరు ద్వారా తయారవుతుంది?', 'Lactic acid bacteria / లాక్టిక్ యాసిడ్ బాక్టీరియా', 'Yeast / ఈస్ట్', 'Virus / వైరస్', 'Moulds / మోల్డ్లు', 'A', 'M', '', 19),
    ('What is the full form of WHO?\\nతెలుగు: WHO పూర్తి రూపం ఏమిటి?', 'World Health Organization / ప్రపంచ ఆరోగ్య సంస్థ', 'World Hygiene Office / ప్రపంచ పరిశుభ్రత కార్యాలయం', 'World Habitat Organization / ప్రపంచ నివాస సంస్థ', 'Wildlife and Human Organization / వన్యప్రాణులు మరియు మానవ సంస్థ', 'A', 'M', '', 20),
    ('Viruses cannot grow without?\\nతెలుగు: వైరస్లు దేని లేకుండా పెరగలేవు?', 'A host cell / హోస్ట్ కణం', 'Water / నీరు', 'Sunlight / సూర్యకాంతి', 'Oxygen / ఆక్సిజన్', 'A', 'M', '', 21),
    ('Bacteria reproduce primarily by?\\nతెలుగు: బాక్టీరియా ప్రధానంగా ఎలా పునరుత్పత్తి చేస్తుంది?', 'Binary fission / ద్విభాజనం', 'Sexual reproduction / లైంగిక పునరుత్పత్తి', 'Budding / మొగ్గ వేయడం', 'Sporulation only / కేవలం స్పొరులేషన్', 'A', 'M', '', 22),
    ('Which disease is caused by the bacterium Mycobacterium tuberculosis?\\nతెలుగు: మైకోబాక్టీరియం ట్యూబర్క్యులోసిస్ బాక్టీరియం వల్ల ఏ వ్యాధి వస్తుంది?', 'Tuberculosis / క్షయవ్యాధి', 'Cholera / కలరా', 'Typhoid / టైఫాయిడ్', 'Pneumonia / న్యుమోనియా', 'A', 'M', '', 23),
    ('Fermentation is a process involving?\\nతెలుగు: పులియడం దేన్ని కలిగి ఉన్న ప్రక్రియ?', 'Microorganisms breaking down sugars / సూక్ష్మజీవులు చక్కెరలను విచ్ఛిన్నం చేయడం', 'Photosynthesis / కిరణజన్య సంయోగం', 'DNA replication / DNA ప్రతిరూపణ', 'Protein synthesis / ప్రోటీన్ సంశ్లేషణ', 'A', 'M', '', 24),
    ('Antibiotic resistance in bacteria is due to?\\nతెలుగు: బాక్టీరియాలో యాంటీబయోటిక్ నిరోధకత దేని వల్ల వస్తుంది?', 'Mutation and natural selection / మ్యుటేషన్ మరియు సహజ ఎంపిక', 'Overuse of vaccines / వ్యాక్సిన్ల అతి వినియోగం', 'Lack of nutrition / పోషణ లేమి', 'Viral infection / వైరల్ సంక్రమణ', 'A', 'M', '', 25),
    ('Which gas do plants absorb during photosynthesis?\\nతెలుగు: మొక్కలు కిరణజన్య సంయోగం సమయంలో ఏ వాయువు శోషిస్తాయి?', 'Carbon dioxide / కార్బన్ డయాక్సైడ్', 'Oxygen / ఆక్సిజన్', 'Nitrogen / నైట్రోజన్', 'Methane / మీథేన్', 'A', 'M', '', 26),
    ('Deforestation leads to?\\nతెలుగు: అటవీ నిర్మూలన దేనికి దారితీస్తుంది?', 'Loss of biodiversity and soil erosion / జీవవైవిధ్యం కోల్పోవడం మరియు నేల కోత', 'Increase in rainfall / వర్షపాతం పెరగడం', 'Decrease in temperature / ఉష్ణోగ్రత తగ్గడం', 'Increase in oxygen / ఆక్సిజన్ పెరగడం', 'A', 'M', '', 27),
    ('What is the carbon cycle?\\nతెలుగు: కార్బన్ చక్రం అంటే ఏమిటి?', 'Movement of carbon through living and non-living systems / జీవ మరియు నిర్జీవ వ్యవస్థల ద్వారా కార్బన్ కదలిక', 'Burning of fossil fuels only / కేవలం శిలాజ ఇంధనాల దహనం', 'Photosynthesis alone / కేవలం కిరణజన్య సంయోగం', 'Decomposition alone / కేవలం కుళ్ళు', 'A', 'M', '', 28),
    ('Which organism breaks down dead matter?\\nతెలుగు: చనిపోయిన పదార్థాన్ని విచ్ఛిన్నం చేసే జీవి ఏది?', 'Decomposer (bacteria/fungi) / కుళ్ళించేవి (బాక్టీరియా/ఫంగై)', 'Producer / ఉత్పత్తిదారు', 'Primary consumer / ప్రాథమిక వినియోగదారు', 'Top predator / పై శ్రేణి వేటగాడు', 'A', 'M', '', 29),
    ('Commensalism is a relationship where?\\nతెలుగు: కమన్సలిజం అంటే ఏ సంబంధం?', 'One benefits, other unaffected / ఒకటి లాభపడుతుంది, మరొకటి ప్రభావం లేకుండా ఉంటుంది', 'Both benefit / రెండూ లాభపడతాయి', 'Both are harmed / రెండూ హాని చెందుతాయి', 'One benefits, other is harmed / ఒకటి లాభపడి, మరొకటి హాని చెందుతుంది', 'A', 'M', '', 30),
    ('Which layer of rainforest receives most sunlight?\\nతెలుగు: వర్షారణ్యంలో ఏ పొర అత్యధిక సూర్యకాంతి పొందుతుంది?', 'Canopy / మేలుపొర', 'Forest floor / అడవి నేల', 'Understory / అండర్‌స్టోరీ', 'Emergent layer / ఎమర్జెంట్ పొర', 'D', 'M', '', 31),
    ('The term "ecology" was coined by?\\nతెలుగు: "ఎకాలజీ" అనే పదాన్ని ఎవరు సృష్టించారు?', 'Ernst Haeckel / ఎర్న్స్ట్ హేకెల్', 'Charles Darwin / చార్లెస్ డార్విన్', 'Louis Pasteur / లూయీ పాశ్చర్', 'Robert Hooke / రాబర్ట్ హుక్', 'A', 'M', '', 32),
    ('Parasitism is a relationship where?\\nతెలుగు: పరాన్నభోజనం అంటే ఏ సంబంధం?', 'One benefits at expense of other / ఒకటి మరొక దాని ఖర్చుతో లాభపడుతుంది', 'Both organisms benefit / రెండు జీవులు లాభపడతాయి', 'Both are harmed / రెండూ హాని చెందుతాయి', 'No benefit or harm / లాభమూ లేదు హానీ లేదు', 'A', 'M', '', 33),
    ('Adaptation means?\\nతెలుగు: అనుకూలన అంటే ఏమిటి?', 'Traits that help an organism survive in its environment / జీవి తన పర్యావరణంలో బతికేందుకు సహాయపడే లక్షణాలు', 'Random changes in DNA / DNA లో యాదృచ్ఛిక మార్పులు', 'Learned behaviors only / నేర్చుకున్న ప్రవర్తనలు మాత్రమే', 'Size increase over time / కాలక్రమేణా పరిమాణం పెరగడం', 'A', 'M', '', 34),
    ('Which microorganism is used in bread making?\\nతెలుగు: రొట్టె తయారీలో ఉపయోగించే సూక్ష్మజీవి ఏది?', 'Yeast (Saccharomyces cerevisiae) / ఈస్ట్ (సాకరోమైసెస్ సెరివిసియే)', 'Bacteria / బాక్టీరియా', 'Virus / వైరస్', 'Algae / ఆల్గే', 'A', 'M', '', 35),
    ('The study of ecosystems is called?\\nతెలుగు: పర్యావరణ వ్యవస్థల అధ్యయనాన్ని ఏమంటారు?', 'Ecology / ఎకాలజీ', 'Taxonomy / వర్గీకరణ శాస్త్రం', 'Genetics / జెనెటిక్స్', 'Microbiology / మైక్రోబయాలజీ', 'A', 'M', '', 36),
    ('Endangered species means?\\nతెలుగు: అంతరించిపోతున్న జాతులు అంటే ఏమిటి?', 'Species at risk of extinction / అంతరించిపోయే ప్రమాదంలో ఉన్న జాతులు', 'Extinct species / అంతరించిపోయిన జాతులు', 'Invasive species / దురాక్రమణ జాతులు', 'Domestic species / పెంపుడు జాతులు', 'A', 'M', '', 37),
    ('Louis Pasteur is known for?\\nతెలుగు: లూయీ పాశ్చర్ దేనికి ప్రసిద్ధి?', 'Germ theory and pasteurization / జెర్మ్ సిద్ధాంతం మరియు పాశ్చరైజేషన్', 'Theory of evolution / పరిణామ సిద్ధాంతం', 'Discovery of penicillin / పెన్సిలిన్ కనుగొనడం', 'Cell theory / కణ సిద్ధాంతం', 'A', 'M', '', 38),
    ('Homeostasis means?\\nతెలుగు: హోమియోస్టాసిస్ అంటే ఏమిటి?', 'Maintaining stable internal body conditions / స్థిరమైన అంతర్గత శరీర పరిస్థితులను నిర్వహించడం', 'Growing larger / పెద్దగా పెరగడం', 'Reproducing faster / వేగంగా పునరుత్పత్తి చేయడం', 'Responding to light / వెలుతురుకు స్పందించడం', 'A', 'M', '', 39),
    ('Which is the most abundant gas in Earth\'s atmosphere?\\nతెలుగు: భూమి వాతావరణంలో అత్యంత సమృద్ధిగా ఉన్న వాయువు ఏది?', 'Nitrogen / నైట్రోజన్', 'Oxygen / ఆక్సిజన్', 'Carbon dioxide / కార్బన్ డయాక్సైడ్', 'Argon / ఆర్గాన్', 'A', 'M', '', 40),
    ('What is a keystone species?\\nతెలుగు: కీస్టోన్ జాతి అంటే ఏమిటి?', 'A species that greatly affects its ecosystem / తన పర్యావరణ వ్యవస్థను ఎక్కువగా ప్రభావితం చేసే జాతి', 'The most abundant species / అత్యంత సమృద్ధిగా ఉన్న జాతి', 'The largest species / అతిపెద్ద జాతి', 'An invasive species / దురాక్రమణ జాతి', 'A', 'M', '', 41),
    ('What percentage of Earth is covered by water?\\nతెలుగు: భూమిలో నీరు ఎంత శాతం ఉంటుంది?', 'About 71% / సుమారు 71%', 'About 50% / సుమారు 50%', 'About 90% / సుమారు 90%', 'About 30% / సుమారు 30%', 'A', 'M', '', 42),
    ('Fleming discovered penicillin in which year?\\nతెలుగు: ఫ్లెమింగ్ పెన్సిలిన్‌ని ఏ సంవత్సరంలో కనుగొన్నాడు?', '1928 / 1928', '1905 / 1905', '1945 / 1945', '1953 / 1953', 'A', 'M', '', 43),
    ('Species that enter new regions and cause harm are called?\\nతెలుగు: కొత్త ప్రాంతాలలో ప్రవేశించి హాని కలిగించే జాతులను ఏమంటారు?', 'Invasive species / దురాక్రమణ జాతులు', 'Native species / స్వదేశీ జాతులు', 'Keystone species / కీస్టోన్ జాతులు', 'Pioneer species / మార్గదర్శక జాతులు', 'A', 'M', '', 44),
    ('Food web is more realistic than food chain because?\\nతెలుగు: ఆహార జాలం ఆహార శృంఖలం కంటే మరింత వాస్తవమైనది ఎందుకు?', 'Shows multiple feeding relationships / అనేక ఆహార సంబంధాలు చూపిస్తుంది', 'Is simpler / సరళంగా ఉంటుంది', 'Has fewer organisms / తక్కువ జీవులు ఉంటాయి', 'Shows only primary consumers / కేవలం ప్రాథమిక వినియోగదారులను చూపిస్తుంది', 'A', 'M', '', 45),
    ('The ozone layer protects Earth from?\\nతెలుగు: ఓజోన్ పొర భూమిని దేనినుండి రక్షిస్తుంది?', 'Ultraviolet radiation / అతినీలలోహిత వికిరణం', 'Acid rain / ఆమ్ల వర్షం', 'Greenhouse gases / గ్రీన్‌హౌస్ వాయువులు', 'Cosmic rays / కాస్మిక్ రేలు', 'A', 'M', '', 46),
    ('Succession in ecology refers to?\\nతెలుగు: ఎకాలజీలో వరుసక్రమం అంటే ఏమిటి?', 'Change of species over time in an area / ఒక ప్రాంతంలో కాలక్రమేణా జాతుల మార్పు', 'Reproduction of species / జాతుల పునరుత్పత్తి', 'Competition between species / జాతుల మధ్య పోటీ', 'Migration of organisms / జీవుల వలస', 'A', 'M', '', 47),
    ('Which type of reproduction produces genetically identical offspring?\\nతెలుగు: ఏ రకమైన పునరుత్పత్తి జన్యుపరంగా సమానమైన సంతానాన్ని ఉత్పత్తి చేస్తుంది?', 'Asexual reproduction / అలైంగిక పునరుత్పత్తి', 'Sexual reproduction / లైంగిక పునరుత్పత్తి', 'Both types / రెండు రకాలు', 'Neither type / ఏ రకమూ కాదు', 'A', 'M', '', 48),
    ('Tuberculosis is spread through?\\nతెలుగు: క్షయవ్యాధి ఎలా వ్యాపిస్తుంది?', 'Airborne droplets / గాలిద్వారా చుక్కలు', 'Contaminated water / కలుషిత నీరు', 'Insect bite / కీటక కాటు', 'Direct skin contact / ప్రత్యక్ష చర్మ సంపర్కం', 'A', 'M', '', 49),
    ('Which microorganism fixes nitrogen in soil?\\nతెలుగు: మట్టిలో నైట్రోజన్‌ని స్థిరపరిచే సూక్ష్మజీవి ఏది?', 'Rhizobium bacteria / రైజోబియం బాక్టీరియా', 'Yeast / ఈస్ట్', 'Penicillium / పెన్సిలియం', 'Virus / వైరస్', 'A', 'M', '', 50),
]

def seed():
    con = sqlite3.connect(DB); cur = con.cursor()
    cur.execute("DELETE FROM questions WHERE source_file=?", (SOURCE,))
    cur.executemany(
        """INSERT INTO questions (folder,topic,source_file,question_text,option_a,option_b,option_c,option_d,correct_answer,difficulty,explanation,question_order)
           VALUES ('GK','General_Science',?,?,?,?,?,?,?,?,?,?)""",
        [(SOURCE, *q) for q in questions])
    con.commit()
    n = cur.execute("SELECT COUNT(*) FROM questions WHERE source_file=?",(SOURCE,)).fetchone()[0]
    con.close(); print(f"Inserted {n} from {SOURCE}")

if __name__ == '__main__': seed()