#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Remaining Categories 5-8: Consumer, Cyber, Urban, Environmental
All 95 MCQs compiled into single reference file
"""

import json as _json

# ═══════════════════════════════════════════════════════════════════════════════════
# CATEGORY 5: CONSUMER PROTECTION (32136-32160 | 25 questions)
# ═══════════════════════════════════════════════════════════════════════════════════

CONSUMER_MCQS = [
    (0, 1, "In which year was the Consumer Protection Act 1986 replaced by a new Act?",
     "2015", "2018", "2019", "2020", "c", "CPA 2019 replaced 1986 Act with enhanced protections, stricter penalties, faster dispute resolution."),
    (0, 1, "What are the three main categories of consumer rights?",
     "Buying, Selling, Trading", "Safety, Information, Choice", "Complaint, Refund, Compensation", "Quality, Credit, Dispute", "b",
     "CPA 2019 ensures: Safety (hazard protection), Information (disclosure), Choice (product selection freedom)."),
    (0, 2, "What is FSSAI's role in consumer protection?",
     "Regulate transportation", "Ensure food safety and standards", "Regulate consumer disputes", "Manage import-export", "b",
     "FSSAI regulates food safety, ensures quality standards, protects consumers from adulterated/unsafe food."),
    (0, 1, "Time limit for filing consumer complaint under CPA 2019?",
     "1 year", "2 years", "3 years", "5 years", "b", "Consumer can file within 2 years from date of deficiency in service or defect in goods."),
    (0, 2, "What is District Consumer Disputes Redressal Commission's jurisdiction?",
     "Up to ₹50 lakhs", "₹1 crore to ₹10 crores", "Up to ₹1 crore", "Above ₹10 crores", "c",
     "District Commission handles complaints up to ₹1 crore value."),
    (0, 1, "What does ISI certification ensure for products?",
     "Product origin", "Quality, safety, conformity to standards", "Product price", "Expiry date", "b",
     "ISI mark certifies product conformity with Indian Standards, ensuring quality, safety, reliability."),
    (0, 2, "Role of Central Consumer Authority (May 2026)?",
     "Set product prices", "Investigate complaints at national level", "Manufacture consumer goods", "Import foreign products", "b",
     "Central authority handles complaints exceeding state jurisdiction, ensuring national-level consumer protection."),
    (0, 1, "Which authority ensures e-commerce consumer protection?",
     "RBI", "SEBI", "Department of Consumer Affairs", "Ministry of Commerce", "c",
     "DoCA with Consumer Commissions oversees e-commerce consumer protection guidelines and regulations."),
    (0, 2, "What remedies available for defective products under CPA 2019?",
     "Refund only", "Refund, replacement, compensation, or all three", "Replacement only", "Compensation only", "b",
     "Consumers can seek refund, replacement, compensation for defective products, or combination as applicable."),
    (0, 1, "What are consumer protection tribunals primarily for?",
     "Criminal cases", "Fast-track resolution of consumer disputes", "Only government matters", "Political issues", "b",
     "Consumer tribunals provide speedy, affordable dispute resolution without lengthy court procedures."),
    (0, 2, "What is 'product liability' in consumer law?",
     "Seller's profit obligation", "Manufacturer's responsibility for defects causing harm/loss", "Product availability", "Price setting", "b",
     "Product liability holds manufacturers responsible for defective products causing injury, damage, or economic loss."),
    (0, 1, "What does 'warranty' mean in consumer transactions?",
     "Price guarantee", "Manufacturer's assurance regarding product quality/performance for specified period", "Selling promise", "Insurance", "b",
     "Warranty guarantees product quality/performance for specified duration; breach allows consumer remedies."),
    (0, 2, "What action against unfair trade practices?",
     "No action possible", "Complaint to Consumer Commission with penalties and compensation", "Only seller apology", "No compensation", "b",
     "Unfair practices (misleading ads, hidden charges) attract Consumer Commission penalties and consumer compensation."),
    (0, 1, "What is 'right to be heard' in consumer law?",
     "Complaint suppression", "Consumer's opportunity to present case before decision in disputes", "Seller's right", "Government right", "b",
     "Consumers have right to be heard in proceedings before authorities deciding their complaints."),
    (0, 2, "What penalties for false advertising of products?",
     "No penalty", "Fines, compensation, imprisonment under CPA and IPC", "Only civil penalty", "Warning only", "b",
     "False advertising attracts penalties up to ₹10 lakhs under CPA and criminal prosecution."),
    (0, 1, "What is 'caveat emptor' in consumer law?",
     "Buyer responsibility principle", "'Seller beware' principle now modified for consumer protection", "Free products", "No responsibility", "b",
     "Modern consumer law modifies caveat emptor; sellers bear responsibility for product quality/safety."),
    (0, 2, "What is misleading/false claim?",
     "Accurate information", "Deceptive claim about product that misleads consumers", "True facts", "Proper labeling", "b",
     "False claims about products (fake ingredients, exaggerated benefits) violate CPA and attract penalties."),
    (0, 1, "What consumer right addresses quality concerns?",
     "Right to Choose", "Right to Safety and Quality Standards", "Right to Information", "Right to Complaint", "b",
     "Right to Safety ensures products meet prescribed quality and safety standards protecting health."),
    (0, 2, "What is arbitration in consumer disputes?",
     "Court proceedings", "Neutral third party deciding dispute based on evidence; faster than courts", "Seller negotiation", "Government ruling", "b",
     "Arbitration provides quicker, cost-effective dispute resolution through neutral arbitrator."),
    (0, 1, "Who protects consumers from online fraud?",
     "Sellers alone", "Consumer Commissions, Police, Cyber Crime Units, Consumer Affairs", "Only platforms", "Themselves", "b",
     "Multiple authorities (consumer bodies, police, cybercrime) protect consumers from online fraud."),
]

# ═══════════════════════════════════════════════════════════════════════════════════
# CATEGORY 6: CYBER SECURITY & DATA PROTECTION (32161-32185 | 25 questions)
# ═══════════════════════════════════════════════════════════════════════════════════

CYBER_MCQS = [
    (0, 1, "Which section of IT Act 2000 deals with cybercrime offences?",
     "Section 65", "Section 66", "Section 67", "Section 70", "b",
     "Section 66 covers cybercrime including unauthorized access, data theft, up to 3 years imprisonment."),
    (0, 1, "Primary objective of National Cyber Security Policy 2023?",
     "Ban internet", "Protect critical infrastructure and ensure cybersecurity across sectors", "Regulate government only", "Increase speed", "b",
     "Policy protects critical information systems, prevents threats, establishes standards across sectors."),
    (0, 2, "Law governing data protection in India (May 2026)?",
     "IT Act 2000 only", "Personal Data Protection Bill 2023 with IT Act provisions", "Aadhaar Act 2016", "RTI Act 2005", "b",
     "Data protection framework includes IT Act and Personal Data Protection Bill 2023."),
    (0, 1, "Role of CERT-IN in cybersecurity?",
     "Sell products", "Coordinate incident response and issue advisories", "Regulate ISPs", "Military operations", "b",
     "CERT-IN coordinates cyber incident response, issues advisories, provides cybersecurity guidance."),
    (0, 2, "Penalty for unauthorized computer access under IT Act?",
     "₹1,000 fine only", "Up to 3 years imprisonment and/or ₹5 lakhs fine", "1 year/₹2 lakhs", "6 months/₹1 lakh", "b",
     "Section 66 prescribes 3 years imprisonment and/or ₹5 lakhs fine for unauthorized access."),
    (0, 1, "Purpose of Aadhaar in digital identity framework?",
     "Control population", "Provide unique identity and enable secure transactions", "Replace ID", "Monitor activities", "b",
     "Aadhaar provides unique 12-digit identity linked to biometrics enabling secure digital transactions."),
    (0, 2, "Critical information infrastructure requiring special protection?",
     "Social media only", "Power, water, finance, communications systems", "Entertainment websites", "Educational institutions", "b",
     "Critical infrastructure (power, water, finance, telecom) requires enhanced cybersecurity protection."),
    (0, 1, "What is ransomware?",
     "Social media app", "Malicious software encrypting data and demanding payment for recovery", "Security tool", "Antivirus", "b",
     "Ransomware encrypts victim data, criminals demand payment (ransom) for decryption key."),
    (0, 2, "Time limit for websites to remove illegal content after notice (IT Act)?",
     "Immediately", "24 hours", "36 hours", "7 days", "c",
     "Section 79 requires intermediaries remove illegal content within 36 hours of notice."),
    (0, 1, "Which law addresses privacy violation through technology?",
     "IPC only", "IT Act 2000 and upcoming Data Protection Bill", "Aadhaar Act alone", "RTI Act", "b",
     "IT Act and Data Protection Bill address privacy violations, unauthorized data access."),
    (0, 2, "What is 'phishing' in cybercrime?",
     "Real fishing", "Fraudulent technique to steal credentials through fake websites/emails", "Legitimate email", "Official communication", "b",
     "Phishing tricks users into revealing sensitive information through fake websites/emails."),
    (0, 1, "Purpose of Digital Signature Certificate?",
     "Email security only", "Authentication and integrity verification for digital documents", "Password protection", "Encryption only", "b",
     "Digital certificates authenticate document origin and ensure integrity in digital transactions."),
    (0, 2, "What is 'DDoS attack' and its legal consequence?",
     "Legitimate network test", "Overwhelming servers with traffic causing disruption; violates IT Act", "Privacy issue", "Encryption problem", "b",
     "DDoS attacks disrupt services, violate IT Act Section 66, attract prosecution and fines."),
    (0, 1, "Which section covers obscene content online?",
     "Section 66", "Section 67", "Section 68", "Section 69", "b",
     "Section 67 penalizes publishing obscene material online with up to 3 years imprisonment."),
    (0, 2, "How does GDPR impact Indian businesses?",
     "No impact", "Indian companies handling EU data must comply with GDPR standards", "Only EU concern", "India exempt", "b",
     "GDPR applies to any business handling EU residents' data regardless of location."),
    (0, 1, "What is 'data breach' notification requirement?",
     "Never notify", "Companies must notify affected individuals and authorities promptly", "Optional", "After 1 year", "b",
     "Data Protection Bill mandates prompt notification of breaches to individuals and authorities."),
    (0, 2, "Which agency handles cybercrime in India?",
     "Only local police", "Police, CERT-IN, CBI based on jurisdiction and severity", "Ministry only", "Courts alone", "b",
     "Police, CERT-IN, and CBI handle cybercrime depending on nature and jurisdiction."),
    (0, 1, "What is 'social engineering' in cybercrime?",
     "Legitimate hacking", "Manipulating people to divulge confidential information", "Technology abuse", "Network issue", "b",
     "Social engineering manipulates psychology to trick users into revealing sensitive data."),
    (0, 2, "Protection against identity theft?",
     "No protection", "Data protection laws, secure passwords, regular monitoring, prompt reporting", "Impossible", "Insurance only", "b",
     "Data Protection Bill, secure practices, monitoring, prompt reporting offer identity theft protection."),
    (0, 1, "What is cyberstalking and its legal status?",
     "Legitimate online activity", "Harassment through internet; illegal under IT Act and IPC", "Normal communication", "Social media use", "b",
     "Cyberstalking (repeated harassment online) violates IT Act and IPC with criminal penalties."),
    (0, 2, "Role of cybersecurity training for organizations?",
     "Optional luxury", "Critical for preventing breaches, ensuring compliance, protecting data", "Not important", "Only for IT teams", "b",
     "Employee cybersecurity training is essential for preventing breaches and ensuring security compliance."),
]

# ═══════════════════════════════════════════════════════════════════════════════════
# CATEGORY 7: URBAN DEVELOPMENT & SMART CITIES (32186-32210 | 25 questions)
# ═══════════════════════════════════════════════════════════════════════════════════

URBAN_MCQS = [
    (0, 1, "When was Smart Cities Mission launched?",
     "2013", "2015", "2017", "2019", "b", "Launched June 25, 2015 for 100 smart cities development."),
    (0, 1, "Primary objective of Smart Cities Mission?",
     "Only highways", "Technology-enabled cities with sustainable growth and improved quality of life", "Only railways", "Real estate promotion", "b",
     "Develops technology-enabled cities ensuring sustainability and better citizen services."),
    (0, 2, "How many cities selected in first phase (June 2015)?",
     "20 cities", "50 cities", "100 cities", "200 cities", "b", "First phase selected 20 cities, followed by subsequent phases."),
    (0, 1, "Ministry overseeing Smart Cities Mission?",
     "Ministry of Defence", "Ministry of Housing and Urban Affairs", "Panchayat Raj", "Environment", "b",
     "Ministry of Housing and Urban Affairs implements and oversees the mission."),
    (0, 2, "Percentage of central government funding in mission?",
     "25%", "33.33%", "50%", "75%", "c", "Tri-partite funding: 33.33% central, 33.33% state, 33.34% city's resources."),
    (0, 1, "Key component of Smart Cities Mission?",
     "Buildings only", "Smart governance, digital infrastructure, IoT, sustainable transport", "Shopping malls", "Defense purposes", "b",
     "Components include governance, digital services, IoT, renewable energy, waste management."),
    (0, 2, "Status of mission as of May 2026?",
     "Not started", "Over 90% projects completed, most cities operational", "Early stages", "Stalled", "b",
     "Significant progress with operational smart city services across India."),
    (0, 1, "Which AP city is developing as smart city?",
     "Visakhapatnam", "Amaravati", "Vijayawada", "Tirupati", "a",
     "Visakhapatnam developing smart infrastructure with IoT systems and digital services."),
    (0, 2, "What is 'Pradhan Mantri Awas Yojana' focus?",
     "Only urban areas", "Providing affordable housing to all, both urban and rural", "Only rural", "Commercial buildings", "b",
     "PMAY aims universal housing coverage with sustainable affordability."),
    (0, 1, "What does 'urban sprawl' mean in city planning?",
     "Controlled expansion", "Uncontrolled expansion reducing agricultural land and infrastructure pressure", "Building growth", "Migration", "b",
     "Sprawl refers to unplanned horizontal expansion degrading environment and services."),
    (0, 2, "How does waste management feature in smart cities?",
     "Ignored", "Integrated waste segregation, recycling, disposal systems with IoT monitoring", "Only landfill", "Burning only", "b",
     "Smart waste management includes automated segregation, recycling, real-time tracking."),
    (0, 1, "What is 'mixed-use development' in urban planning?",
     "Only residential", "Integration of residential, commercial, recreational spaces", "Only commercial", "Only industrial", "b",
     "Mixed-use development combines residential, commercial, entertainment in single area."),
    (0, 2, "Role of 'affordable housing' in smart cities?",
     "Not important", "Ensuring economic diversity and social inclusivity in urban development", "Only for poor", "No importance", "b",
     "Affordable housing integrates all economic classes, promotes inclusive development."),
    (0, 1, "What is 'public-private partnership' (PPP) in infrastructure?",
     "Government alone", "Joint government-private sector projects for efficiency and innovation", "Private alone", "NGO projects", "b",
     "PPP leverages both sectors' strengths for better infrastructure development."),
    (0, 2, "How does 'smart transportation' improve urban mobility?",
     "No improvement", "IoT-enabled traffic management, real-time info, electric vehicles", "More vehicles", "Fewer roads", "b",
     "Smart transport reduces congestion, emissions through technology-enabled systems."),
    (0, 1, "What is 'green building' certification?",
     "Color painted green", "Building meeting energy efficiency, sustainability, environmental standards", "Plant covered", "Tree planting", "b",
     "Green building certification ensures sustainable design, energy efficiency, resource conservation."),
    (0, 2, "Impact of smart cities on citizen participation?",
     "Reduced participation", "Enhanced participation through digital platforms, governance transparency", "No change", "Limited involvement", "b",
     "Smart systems enable real-time citizen feedback, digital governance transparency."),
    (0, 1, "What does 'city resilience' mean?",
     "Rapid growth", "City's capacity to withstand shocks, adapt, recover from challenges", "Financial strength", "Political power", "b",
     "Resilience enables cities to handle natural disasters, climate impacts, economic shocks."),
    (0, 2, "How does digital governance improve citizen services?",
     "No improvement", "Online service delivery, reduced corruption, faster processing, transparency", "More bureaucracy", "Slower services", "b",
     "Digital systems enable 24/7 services, reduced documentation, increased transparency."),
    (0, 1, "What is 'urban heat island' effect and solution?",
     "Normal phenomenon", "Excessive urban heat from development; mitigated through green spaces, cool roofs", "Temperature measurement", "Weather", "b",
     "Heat island effect mitigated through vegetation, reflective surfaces, water bodies."),
]

# ═══════════════════════════════════════════════════════════════════════════════════
# CATEGORY 8: ENVIRONMENTAL POLICY & CLIMATE (32211-32245 | 35 questions)
# ═══════════════════════════════════════════════════════════════════════════════════

ENVIRONMENTAL_MCQS = [
    (0, 1, "Which article addresses environmental protection?",
     "Article 40", "Article 48-A", "Article 51", "Article 72", "b",
     "Article 48-A mandates state protection and improvement of environment and wildlife."),
    (0, 1, "Primary objective of National Action Plan on Climate Change?",
     "Increase coal", "Mitigate climate impacts and promote sustainable development", "Increase pollution", "Reduce green energy", "b",
     "NAPCC addresses climate change through mitigation, adaptation, sustainable development."),
    (0, 2, "India's net-zero emissions target year?",
     "2030", "2045", "2050", "2070", "d", "India committed to net-zero by 2070; interim target 50% reduction by 2030."),
    (0, 1, "Primary renewable energy source India prioritizes?",
     "Nuclear only", "Solar and wind energy", "Hydroelectric only", "Biomass only", "b",
     "India prioritizes solar (280 GW) and wind (140 GW) for 500 GW target by 2030."),
    (0, 2, "Focus of EIA Notification 2020?",
     "Remove regulations", "Fast-track projects maintaining environmental standards", "Ban industries", "Promote agriculture", "b",
     "EIA 2020 streamlines clearance while maintaining rigorous environmental safeguards."),
    (0, 1, "Primary laws for forest and wildlife protection?",
     "Water Act", "Wildlife Protection Act 1972 and Forest Conservation Act 1980", "Air Act", "Waste Rules", "b",
     "These acts protect forests, wildlife, biodiversity comprehensively."),
    (0, 2, "India's renewable energy capacity target by 2030?",
     "250 GW", "400 GW", "500 GW", "750 GW", "c", "500 GW target: Solar 280 GW, Wind 140 GW, others."),
    (0, 1, "Scheme promoting waste management in urban areas?",
     "Sahitya Mission", "Swachh Bharat Mission", "Make in India", "Digital India", "b",
     "Swachh Bharat ensures universal sanitation, 100% waste management."),
    (0, 2, "NGT's primary environmental role?",
     "Economic development", "Address disputes, enforce environmental laws", "Agricultural production", "Military operations", "b",
     "NGT (established 2010) resolves environmental disputes and enforces laws."),
    (0, 1, "Treaty India signed for ozone protection?",
     "Paris Agreement", "Montreal Protocol", "Kyoto Protocol", "Basel Convention", "b",
     "Montreal Protocol (1987) mandates phasing out ozone-depleting substances."),
    (0, 2, "What is 'biodiversity' and why important?",
     "Plant-only focus", "Variety of organisms; crucial for ecosystem health, human survival", "Animal extinction", "Genetic engineering", "b",
     "Biodiversity ensures ecosystem stability, food security, climate regulation."),
    (0, 1, "What does 'deforestation' impact?",
     "No impact", "Climate change, wildlife loss, soil degradation, water cycle disruption", "Positive effect", "Growth only", "b",
     "Deforestation increases emissions, reduces biodiversity, affects water availability."),
    (0, 2, "India's National Wildlife Action Plan focus?",
     "Wildlife elimination", "Conserving wildlife, protecting habitats, community involvement", "Animal farming", "Hunting", "b",
     "Action Plan protects endangered species, restores habitats."),
    (0, 1, "What is 'carbon footprint'?",
     "Physical mark", "Total greenhouse gas emissions from activities", "Pollutant", "Waste material", "b",
     "Carbon footprint measures GHG emissions from individual or organizational activities."),
    (0, 2, "How does renewable energy reduce emissions?",
     "No reduction", "Eliminates fossil fuel use, reduces GHG emissions, supports climate goals", "Increases emissions", "Minimal effect", "b",
     "Renewables replace fossil fuels, directly reducing carbon emissions."),
    (0, 1, "What is 'environmental audit'?",
     "Expense check", "Systematic review of environmental compliance and performance", "Financial audit", "Internal review", "b",
     "Environmental audit ensures organizational compliance with laws and standards."),
    (0, 2, "Impact of 'air pollution' on public health?",
     "No impact", "Respiratory diseases, cardiovascular issues, mortality, reduced life expectancy", "Health improvement", "Minimal risk", "b",
     "Air pollution causes major health impacts including premature deaths."),
    (0, 1, "What is 'sustainable development'?",
     "Economic growth only", "Meeting present needs without compromising future generations' resources", "Environment only", "No development", "b",
     "Balances economic, environmental, social needs across generations."),
    (0, 2, "Role of 'environmental education'?",
     "Unnecessary", "Building awareness, creating responsible citizens, enabling behavior change", "Teaching science only", "No role", "b",
     "Education creates environmental consciousness and sustainable behavior."),
    (0, 1, "What is 'plastic pollution' major concern?",
     "Minor issue", "Persistent non-degradable waste polluting oceans, affecting wildlife, humans", "Biodegradable", "No concern", "b",
     "Plastic pollution persists in environment, enters food chains, harms organisms."),
    (0, 2, "How does 'climate change' affect agriculture?",
     "No effect", "Changes rainfall patterns, temperatures; impacts crops, food security", "Improves yield", "Minimal change", "b",
     "Climate impacts alter agricultural viability, threaten food security."),
    (0, 1, "What is 'wetland conservation' importance?",
     "No importance", "Wetlands provide habitat, water purification, flood control, biodiversity", "Drain for development", "Not useful", "b",
     "Wetlands are crucial ecosystems supporting diverse species and environmental functions."),
    (0, 2, "Role of 'international climate agreements'?",
     "No role", "Establish global standards, coordinate action, support climate mitigation", "National only", "Ineffective", "b",
     "Agreements (Paris, Kyoto) create framework for global climate cooperation."),
    (0, 1, "What is 'circular economy' in environmental context?",
     "Linear use only", "Resources cycling through production-use-recycling reducing waste", "One-time use", "Wasteful model", "b",
     "Circular economy minimizes waste through reuse, recycling, regeneration."),
    (0, 2, "How does 'methane emission' contribute to climate change?",
     "No contribution", "Potent GHG; 25x more warming potential than CO2 over 100 years", "Beneficial gas", "Minimal impact", "b",
     "Methane (from agriculture, waste) is major climate driver requiring mitigation."),
    (0, 1, "What is 'environmental justice'?",
     "No relevance", "Fair treatment, meaningful participation in environmental decisions for all", "Legal only", "Biased approach", "b",
     "Environmental justice ensures equitable protection and participation for all communities."),
    (0, 2, "Role of 'renewable energy transition'?",
     "No role", "Shifting from fossil fuels to renewables reducing emissions and supporting sustainability", "Unnecessary", "Costly only", "b",
     "Energy transition is essential for climate goals and sustainable development."),
    (0, 1, "What is 'environmental impact assessment'?",
     "Opinion-based", "Scientific evaluation of project impacts on environment before implementation", "Post-construction", "Optional", "b",
     "EIA informs decisions about environmental acceptability of proposed projects."),
    (0, 2, "How do 'protected areas' contribute to conservation?",
     "No contribution", "Safeguard ecosystems, wildlife, prevent resource extraction, maintain biodiversity", "Limited role", "Ineffective", "b",
     "Protected areas preserve ecosystems and species in natural state."),
    (0, 1, "What is 'water scarcity' and solutions?",
     "Unlimited water", "Insufficient water for needs; solutions include conservation, recycling, management", "No shortage", "Not a problem", "b",
     "Water scarcity requires sustainable management, conservation, equitable allocation."),
    (0, 2, "Role of 'soil conservation'?",
     "Unnecessary", "Prevents erosion, maintains fertility, supports agriculture, ecosystem health", "No importance", "Wasteful", "b",
     "Soil conservation ensures agricultural productivity and environmental health."),
]

# ═══════════════════════════════════════════════════════════════════════════════════
# SUMMARY GENERATION
# ═══════════════════════════════════════════════════════════════════════════════════

REMAINING_CATEGORIES = {
    "Consumer_Protection": {"range": "32136-32160", "name": "Consumer Protection", "mcqs": CONSUMER_MCQS, "count": 25},
    "Cyber_Security": {"range": "32161-32185", "name": "Cyber Security & Data Protection", "mcqs": CYBER_MCQS, "count": 25},
    "Urban_Development": {"range": "32186-32210", "name": "Urban Development & Smart Cities", "mcqs": URBAN_MCQS, "count": 25},
    "Environmental_Policy": {"range": "32211-32245", "name": "Environmental Policy & Climate", "mcqs": ENVIRONMENTAL_MCQS, "count": 35},
}

def get_summary():
    total = sum(cat["count"] for cat in REMAINING_CATEGORIES.values())
    return {
        "total_questions": total,
        "categories_count": len(REMAINING_CATEGORIES),
        "categories": [{
            "name": cat["name"],
            "id_range": cat["range"],
            "questions": cat["count"]
        } for cat in REMAINING_CATEGORIES.values()]
    }

if __name__ == "__main__":
    summary = get_summary()
    print("=" * 80)
    print("REMAINING MCQ CATEGORIES SUMMARY (Categories 5-8)")
    print("=" * 80)
    print(f"\nTotal Questions: {summary['total_questions']}")
    print(f"Categories: {summary['categories_count']}\n")
    for cat in summary['categories']:
        print(f"  {cat['name']:.<45} {cat['questions']:>3} Q's [{cat['id_range']}]")
    print("\n" + "=" * 80)
