# seed_polity_ch25.py
# Chapter 25 — Urban Local Bodies (74th Amendment)
# (పట్టణ స్థానిక సంస్థలు — 74వ సవరణ)
# Total Sections: 8 | Total MCQs: 56
# Sections:
#   0 — Historical Background & 74th Amendment (7 MCQs)
#   1 — Art.243P–ZG & 12th Schedule (7 MCQs)
#   2 — Types of ULBs (7 MCQs)
#   3 — Municipal Corporation (7 MCQs)
#   4 — Ward Committees & Metropolitan Planning (7 MCQs)
#   5 — Finance & Elections (7 MCQs)
#   6 — 12th Schedule — 18 Subjects (7 MCQs)
#   7 — Miscellaneous Key Facts (7 MCQs)

_CH = 25
_SUBJECT = 'GK'
_TOPIC   = 'Indian_Polity'
_TITLE_TE = 'పట్టణ స్థానిక సంస్థలు — 74వ సవరణ'
_TITLE_EN = 'Urban Local Bodies — 74th Amendment'
_PAGES    = 'Ch.25 (Lakshmikanth)'

_SECTIONS = [
    "చారిత్రక నేపథ్యం & 74వ సవరణ",
    "అనుచ్ఛేదం 243P–ZG & 12వ షెడ్యూల్",
    "పట్టణ స్థానిక సంస్థల రకాలు",
    "నగరపాలక సంస్థ (Municipal Corporation)",
    "వార్డ్ కమిటీలు & మెట్రోపాలిటన్ ప్రణాళిక",
    "ఆర్థిక వ్యవస్థ & ఎన్నికలు",
    "12వ షెడ్యూల్ — 18 అంశాలు",
    "విభిన్న కీలక అంశాలు",
]

_MCQS = [    (0,
     'easy',
     '74th Constitutional Amendment relates to?\nతెలుగు: 74వ రాజ్యాంగ సవరణ దేనికి సంబంధించినది?',
     'Panchayati Raj / పంచాయతీ రాజ్',
     'Urban Local Bodies / పట్టణ స్థానిక సంస్థలు',
     'Right to Education / విద్య హక్కు',
     'Armed Forces / సాయుధ దళాలు',
     'b',
     '74th Amendment 1992 (effective June 1, 1993) gave constitutional status to ULBs. 73rd = PR, 74th = ULBs. / 74వ రాజ్యాంగ సవరణ 1992 (అమలు: 1 జూన్ 1993) పట్టణ స్థానిక సంస్థలకు (ULBs) రాజ్యాంగ హోదా కల్పించింది. 73వ సవరణ పంచాయతీ రాజ్\u200cకి, 74వ సవరణ ULBs కి.'),
    (0,
     'easy',
     'When did the 74th Amendment come into force?\nతెలుగు: 74వ సవరణ ఏ తేదీ నుండి అమలులోకి వచ్చింది?',
     'December 20, 1992 / 1992 డిసెంబర్ 20',
     'April 24, 1993 / 1993 ఏప్రిల్ 24',
     'June 1, 1993 / 1993 జూన్ 1',
     'January 1, 1994 / 1994 జనవరి 1',
     'c',
     '74th Amendment came into force on June 1, 1993. 73rd Amendment (PR) came into force on April 24, 1993. / 74వ సవరణ 1 జూన్ 1993 నుండి అమలులోకి వచ్చింది. 73వ సవరణ (PR) 24 ఏప్రిల్ 1993 నుండి అమలైంది.'),
    (0,
     'medium',
     '74th Amendment added which Part to the Constitution?\nతెలుగు: 74వ సవరణ రాజ్యాంగంలో ఏ Part జోడించింది?',
     'Part VIII',
     'Part IX',
     'Part IX-A',
     'Part IX-B',
     'c',
     '74th Amendment added Part IX-A (Arts 243P to 243ZG) and the 12th Schedule. / 74వ సవరణ Part IX-A (అనుచ్ఛేదం 243P నుండి 243ZG) మరియు 12వ షెడ్యూల్ జోడించింది. Part IX (PR) 73వ సవరణ జోడించింది.'),
    (0,
     'medium',
     'What status did ULBs have before 74th Amendment?\nతెలుగు: 74వ సవరణకు ముందు ULBs ఏ అర్హత పొందాయి?',
     'Union List / కేంద్ర జాబితా',
     'State List / రాష్ట్ర జాబితా',
     'Concurrent List / ఉభయ జాబితా',
     'Non-constitutional status / రాజ్యాంగేతర స్థానం',
     'b',
     'Before 74th Amendment, ULBs were under State List (Entry 5). No constitutional status. / 74వ సవరణకు ముందు ULBs రాష్ట్ర జాబితా (List II, Entry 5) కింద ఉండేవి. రాజ్యాంగ హోదా లేదు.'),
    (0,
     'medium',
     "Where was India's first Municipal Corporation established?\nతెలుగు: మొదటి Municipal Corporation భారతదేశంలో ఎక్కడ ఏర్పాటైంది?",
     'Mumbai / ముంబై',
     'Kolkata / కోల్కతా',
     'Chennai / చెన్నై',
     'Delhi / దిల్లీ',
     'c',
     "India's first Municipal Corporation was established in Madras (now Chennai) in 1688 by the British. / భారతదేశంలో మొదటి Municipal Corporation 1688లో మద్రాస్ (ఇప్పుడు చెన్నై)లో బ్రిటీష్ వారు స్థాపించారు."),
    (0,
     'hard',
     'Key committee on ULBs before 74th Amendment?\nతెలుగు: 74వ సవరణకి ముందు ULBs పై నిర్దేశించిన ముఖ్య కమిటీ ఏది?',
     'Balwant Rai Mehta Committee',
     'Ashok Mehta Committee',
     'P.K. Thornton Committee',
     'National Commission on Urbanisation (NCU) 1988',
     'd',
     'National Commission on Urbanisation (NCU) 1988 recommended constitutional status to ULBs, leading to 74th Amendment. / National Commission on Urbanisation (NCU) 1988 పట్టణ స్థానిక సంస్థలకు రాజ్యాంగ హోదా ఇవ్వాలని సిఫారసు చేసింది — 74వ సవరణకు దారి తీసింది.'),
    (0,
     'hard',
     'How many Articles are in Part IX-A of 74th Amendment?\nతెలుగు: 74వ సవరణ Part IX-A లో ఎన్ని అనుచ్ఛేదాలు ఉన్నాయి?',
     '12',
     '16',
     '18',
     '21',
     'c',
     'Part IX-A contains Arts 243P to 243ZG = 18 Articles in total. / Part IX-A లో అనుచ్ఛేదం 243P నుండి 243ZG వరకు మొత్తం 18 అనుచ్ఛేదాలు ఉన్నాయి.'),
    (0,
     'medium',
     '74th Amendment came into force in which year?\nతెలుగు: 74వ సవరణ ఏ సంవత్సరంలో అమలులోకి వచ్చింది?',
     '1992',
     '1993',
     '1994',
     '1995',
     'b',
     '74th Constitutional Amendment Act passed December 20, 1992 and came into force on June 1, 1993. / 74వ రాజ్యాంగ సవరణ చట్టం 1992 డిసెంబర్ 20న పార్లమెంటు ఆమోదించింది; 1993 జూన్ 1న అమలులోకి వచ్చింది.'),
    (1,
     'easy',
     'Articles relating to ULBs?\nతెలుగు: పట్టణ స్థానిక సంస్థలను నిర్దేశించే అనుచ్ఛేదాల పరిధి ఏమిటి?',
     'అను. 243A–243O',
     'అను. 243P–243ZG',
     'అను. 243–243N',
     'అను. 244–250',
     'b',
     'ULBs: Art.243P to 243ZG (Part IX-A). PR: Art.243 to 243O (Part IX). / ULBs Part IX-A కింద అనుచ్ఛేదం 243P నుండి 243ZG వరకు నిర్దేశించబడ్డాయి. PR Part IX కింద అను. 243–243O.'),
    (1,
     'easy',
     'What does Art.243Q provide?\nతెలుగు: అనుచ్ఛేదం 243Q ఏమి నిర్దేశిస్తుంది?',
     'ULB elections / ULB ఎన్నికలు',
     'Constitution of Municipalities / Municipalities నిర్మాణం',
     'Ward committees',
     'Metropolitan Planning Committee',
     'b',
     'Art.243Q: Constitution of Municipalities — Nagar Panchayat, Municipal Council, Municipal Corporation. / అనుచ్ఛేదం 243Q: ప్రతి రాష్ట్రంలో Municipalities నిర్మాణం — Nagar Panchayat, Municipal Council, Municipal Corporation.'),
    (1,
     'medium',
     'What does Art.243S provide?\nతెలుగు: అనుచ్ఛేదం 243S ఏమి నిర్దేశిస్తుంది?',
     'Municipal elections',
     'Ward Committees',
     'State Finance Commission',
     'Metropolitan Planning Committee',
     'b',
     'Art.243S: Ward Committees mandatory in Municipalities with population 3 lakhs and above. / అనుచ్ఛేదం 243S: 3 లక్షలు లేదా అంతకంటే ఎక్కువ జనాభా ఉన్న Municipalities లో Ward Committees ఏర్పాటు తప్పనిసరి.'),
    (1,
     'medium',
     'What does Art.243ZD provide?\nతెలుగు: అనుచ్ఛేదం 243ZD ఏమి నిర్దేశిస్తుంది?',
     'ULB financial autonomy / ULB ఆర్థిక స్వయంప్రతిపత్తి',
     'District Planning Committee',
     'Ward Committees',
     'State Finance Commission',
     'b',
     'Art.243ZD: District Planning Committee coordinates PR + ULB plans at district level; 4/5 members from elected PR + ULB bodies. / అనుచ్ఛేదం 243ZD: District Planning Committee (DPC) — జిల్లా స్థాయిలో PR + ULB ప్రణాళికలు సమన్వయం. 4/5 వంతు సభ్యులు PR + ULB సభ్యులు.'),
    (1,
     'medium',
     'What does Art.243ZE provide?\nతెలుగు: అనుచ్ఛేదం 243ZE ఏమి నిర్దేశిస్తుంది?',
     'District Planning Committee',
     'Metropolitan Planning Committee',
     'Ward committees',
     'ULB elections',
     'b',
     'Art.243ZE: Metropolitan Planning Committee (MPC) — for metro areas with pop. 10 lakh+; 2/3 members to be elected. / అనుచ్ఛేదం 243ZE: Metropolitan Planning Committee (MPC) — 10 లక్షలు లేదా అంతకంటే ఎక్కువ జనాభా ఉన్న Metropolitan areas కు. 2/3 వంతు సభ్యులు ఎన్నికైన వారు.'),
    (1,
     'hard',
     'What does Art.243ZA provide?\nతెలుగు: అనుచ్ఛేదం 243ZA ఏమి నిర్దేశిస్తుంది?',
     'Ward committees',
     'ULB ఆర్థిక సంఘం',
     'SEC superintendence of ULB elections / State Election Commission — ULB ఎన్నికల పర్యవేక్షణ',
     'Municipal Corporation నిర్మాణం',
     'c',
     'Art.243ZA: State Election Commission superintends elections to Municipalities. / అనుచ్ఛేదం 243ZA: రాష్ట్ర ఎన్నికల సంఘం (SEC) ULB ఎన్నికలు పర్యవేక్షిస్తుంది.'),
    (1,
     'hard',
     'What does Art.243ZG provide?\nతెలుగు: అనుచ్ఛేదం 243ZG ఏమి నిర్దేశిస్తుంది?',
     'Metropolitan Planning Committee',
     'Bar on court interference in ULB elections / ULB ఎన్నికల వ్యాజ్యాలలో న్యాయస్థాన జోక్యాన్ని నిషేధించడం',
     'ULB dissolution / ULB రద్దు',
     'Ward committees',
     'b',
     'Art.243ZG: No court (except HC) can interfere in ULB electoral matters (parallel to Art.243O for PR). / అనుచ్ఛేదం 243ZG: ULB ఎన్నికల వ్యాజ్యాలలో High Court తప్ప ఇతర కోర్టులు జోక్యం చేసుకోలేవు. (Art.243O తో సమానం — PR కి.)'),
    (1,
     'medium',
     'State Finance Commission under Art.243X recommends regarding ULBs?\nతెలుగు: Art.243X కింద రాష్ట్ర ఆర్థిక సంఘం ULBలకు సంబంధించి ఏమి సిఫారసు చేస్తుంది?',
     'Approves ULB budget / ULB బడ్జెట్ ఆమోదిస్తుంది',
     'Distribution of taxes, grants between State and ULBs / పన్నులు, రుసుములు, ఆర్థిక సహాయం పంపిణీ — రాష్ట్రం-ULB మధ్య',
     'Dissolves ULBs / ULBలను రద్దు చేయడం',
     'Issues Municipal bonds / Municipal bonds జారీ',
     'b',
     'Art.243X: State Finance Commission every 5 years recommends distribution of taxes, duties, grants from state consolidated fund to municipalities. / Art.243X (యూర్బన్): రాష్ట్ర ఆర్థిక సంఘం ప్రతి 5 సంవత్సరాలకు పన్నులు, సుంకాలు, రుసుముల పంపిణీ గురించి సిఫారసు చేస్తుంది — రాష్ట్ర ఏకీకృత నిధి నుండి ULBలకు గ్రాంట్లు సిఫారసు చేస్తుంది.'),
    (2,
     'easy',
     'How many types of ULBs are provided in Art.243Q?\nతెలుగు: పట్టణ స్థానిక సంస్థలు ఎన్ని రకాలు?',
     '2',
     '3',
     '4',
     '5',
     'b',
     'Art.243Q provides 3 types: Nagar Panchayat, Municipal Council, Municipal Corporation. / అనుచ్ఛేదం 243Q 3 రకాల Municipalities నిర్దేశిస్తుంది: (1) Nagar Panchayat (పట్టణ సంత), (2) Municipal Council (పురపాలక సంఘం), (3) Municipal Corporation (నగరపాలక సంస్థ).'),
    (2,
     'easy',
     'Municipal Corporation is generally for?\nతెలుగు: నగరపాలక సంస్థ (Municipal Corporation) సాధారణంగా ఏ నగరాలలో ఉంటుంది?',
     'Small towns / చిన్న పట్టణాలు',
     'Transitional areas / పరివర్తన ప్రాంతాలు',
     'Large cities / పెద్ద నగరాలు',
     'Villages / పల్లెలు',
     'c',
     'Municipal Corporation: large cities. Municipal Council: medium towns. Nagar Panchayat: transitional areas. / Municipal Corporation = పెద్ద నగరాలు (like Mumbai, Delhi, Hyderabad). Municipal Council = మధ్యస్థ పట్టణాలు. Nagar Panchayat = గ్రామం నుండి పట్టణంగా మారుతున్న ప్రాంతాలు.'),
    (2,
     'medium',
     'Nagar Panchayat applies to?\nతెలుగు: Nagar Panchayat (నగర పంచాయతి) ఏ ప్రాంతాలకు వర్తిస్తుంది?',
     'Large cities / పెద్ద నగరాలు',
     'Rural areas / గ్రామీణ ప్రాంతాలు',
     'Transitional areas (rural to urban) / గ్రామం నుండి పట్టణంగా పరివర్తన చెందుతున్న ప్రాంతాలు',
     'Industrial areas / పారిశ్రామిక ప్రాంతాలు',
     'c',
     'Nagar Panchayat: transitional (rural-to-urban) areas. Municipal Council: medium-sized towns. / Nagar Panchayat (Notified Area Committee) = గ్రామీణ నుండి పట్టణ పరివర్తన ప్రాంతాలు. Municipal Council = మధ్యస్థ పట్టణాలు.'),
    (2,
     'medium',
     'Supreme governing body in a Municipal Corporation?\nతెలుగు: Municipal Corporation లో అత్యున్నత పాలక సంస్థ ఏది?',
     'Mayor',
     'Municipal Commissioner',
     'General Body',
     'State Government',
     'c',
     'Highest governing body: General Body/Council of elected councillors. Mayor chairs it. / Municipal Corporation లో అత్యున్నత పాలక సంస్థ = General Body (Council) — ఎన్నికైన councillors నిర్మించిన సభ. Mayor దీని Chairman.'),
    (2,
     'medium',
     'How is Mayor elected in Municipal Corporation?\nతెలుగు: Municipal Corporation లో Mayor ఎన్నికవడం ఎలా?',
     'Directly appointed by Governor / రాజ్యపాలకుడు నేరుగా నియమిస్తారు',
     'Elected by Councillors OR direct election (as per state law) / Councillors ఎన్నుకుంటారు లేదా ప్రత్యక్ష ఎన్నిక',
     'Appointed by State Government / State Government నియమిస్తుంది',
     'Nominated by CM / Chief Minister నామినేట్ చేస్తారు',
     'b',
     'Mayor election is per state law: indirect (by councillors) in some states; direct election in others. / Mayor ఎన్నిక రాష్ట్ర చట్టం ప్రకారం ఉంటుంది — కొన్ని రాష్ట్రాలలో councillors ఎన్నుకుంటారు; కొన్నిచోట్ల ప్రత్యక్ష ఎన్నికలు జరుగుతాయి.'),
    (2,
     'hard',
     'Cantonment Board is under which Ministry?\nతెలుగు: Cantonment Board ఏ మంత్రిత్వ శాఖ కింద ఉంటుంది?',
     'Home Ministry / హోం మంత్రిత్వ శాఖ',
     'Ministry of Defence / రక్షణ మంత్రిత్వ శాఖ',
     'Ministry of Urban Development / పట్టణాభివృద్ధి మంత్రిత్వ శాఖ',
     'State Government / రాష్ట్ర ప్రభుత్వం',
     'b',
     'Cantonment Boards function in military areas (cantonments) under the Ministry of Defence. / Cantonment Board సైనిక ప్రాంతాలలో (cantonments) పని చేస్తుంది — రక్షణ మంత్రిత్వ శాఖ (Ministry of Defence) కింద.'),
    (2,
     'hard',
     'Township municipalities are set up for?\nతెలుగు: Township municipality ఏ ప్రాంతాలకు ఏర్పాటు చేస్తారు?',
     'Tourist areas / పర్యాటక ప్రాంతాలు',
     'For needs of large industrial corporations / పారిశ్రామిక కార్పొరేషన్ల అవసరాల కోసం',
     'Hilly areas / పర్వత ప్రాంతాలు',
     'University areas / విశ్వవిద్యాలయ ప్రాంతాలు',
     'b',
     'Township municipalities: for large PSU townships (Bokaro, Bhilai, Rourkela steel plant townships etc.). / Township municipalities పెద్ద పారిశ్రామిక సంస్థలు (PSUs) వారి ఆవాసాలు మరియు సౌకర్యాల నిర్వహణ కోసం ఏర్పాటు చేస్తాయి. (Ex: Bokaro, Bhilai, Rourkela townships)'),
    (2,
     'hard',
     'Role of SPVs in Smart City Mission?\nతెలుగు: Special Purpose Vehicles (SPVs) స్మార్ట్ సిటీ మిషన్ లో ఏం పాత్ర పోషిస్తాయి?',
     'Special company set up alongside municipal corp to plan, finance, implement Smart City projects / Municipal corporation కి అదనంగా ఏర్పాటు చేసిన ప్రత్యేక కంపెనీ',
     'State government departments',
     'Central PSUs',
     'Housing Development Corporations',
     'a',
     'Under Smart City Mission, SPV = Special Purpose Company (50% Central + 50% State) to plan, finance, and implement Smart City projects. / స్మార్ట్ సిటీ మిషన్ కింద SPV (Special Purpose Vehicle) = ప్రత్యేక కంపెనీ (50% Central + 50% State) — స్మార్ట్ సిటీ ప్రాజెక్టులు ప్రణాళిక, నిధులు, అమలు నిర్వహిస్తుంది.'),
    (3,
     'easy',
     'Highest executive officer of Municipal Corporation?\nతెలుగు: Municipal Corporation (నగరపాలక సంస్థ) కి అత్యున్నత కార్యనిర్వాహక అధికారి ఎవరు?',
     'Mayor',
     'Municipal Commissioner',
     'Deputy Mayor',
     'Ward Councillor',
     'b',
     'Municipal Commissioner = highest executive officer (usually IAS). Mayor = chairman of the governing body (council). / Municipal Commissioner = Municipal Corporation కి అత్యున్నత కార్యనిర్వాహక అధికారి — సాధారణంగా IAS అధికారి. Mayor = పాలక సంస్థ (council) అధ్యక్షుడు.'),
    (3,
     'easy',
     'What is the Hyderabad Municipal Corporation called?\nతెలుగు: Hyderabad Municipal Corporation పేరు ఏమిటి?',
     'Greater Hyderabad Municipal Corporation',
     'Hyderabad City Corporation',
     'Greater Hyderabad Urban Authority',
     'Hyderabad Metro Corporation',
     'a',
     'Hyderabad MC = Greater Hyderabad Municipal Corporation (GHMC), renamed in 2007. / హైదరాబాద్ నగరపాలక సంస్థ పేరు: Greater Hyderabad Municipal Corporation (GHMC) — 2007లో GHMC గా పేరు మార్చారు.'),
    (3,
     'medium',
     'Minimum age to be a Municipal Councillor?\nతెలుగు: నగరపాలక సంస్థలో ఒక Councillor ఎన్నికవడానికి కనీస వయస్సు ఎంత?',
     '18 years / 18 సంవత్సరాలు',
     '21 years / 21 సంవత్సరాలు',
     '25 years / 25 సంవత్సరాలు',
     '30 years / 30 సంవత్సరాలు',
     'b',
     'Minimum age to contest as Municipal Councillor = 21 years (per most state laws). / Municipal Councillor పదవికి పోటీ చేయడానికి కనీస వయస్సు = 21 సంవత్సరాలు (రాష్ట్ర చట్టాల ప్రకారం).'),
    (3,
     'medium',
     'Largest Municipal Corporation in India (by area)?\nతెలుగు: భారతదేశంలో అతి పెద్ద Municipal Corporation ఏది?',
     'Mumbai',
     'Delhi',
     'Ahmedabad',
     'Bengaluru',
     'b',
     "BMC Mumbai is often cited as largest. By area, BBMP Bengaluru is one of the largest. / Greater Mumbai Municipal Corporation (MCGM/BMC) బజెట్ పరంగా అతి పెద్దది. విస్తీర్ణం పరంగా BBMP (Bengaluru) అతి పెద్దది. ముంబై BMC is often cited as India's richest/largest urban body."),
    (3,
     'medium',
     "Women's reservation in ULBs under 74th Amendment?\nతెలుగు: 74వ సవరణ మహిళలకు ULBs లో ఎంత రిజర్వేషన్ నిర్దేశించింది?",
     '20%',
     '25%',
     '33.33% (1/3)',
     '50%',
     'c',
     'Art.243T: Minimum 1/3 seats reserved for women in ULBs. Some states provide 50%. / అనుచ్ఛేదం 243T: ULBs లో మహిళలకు కనీసం 1/3 (33.33%) స్థానాలు రిజర్వు. కొన్ని రాష్ట్రాలు 50% నిర్దేశించాయి.'),
    (3,
     'hard',
     'Key factors for Municipal Corporation status?\nతెలుగు: Municipal Corporation యొక్క స్థాయి ఏర్పాటులో కింది అంశాలలో ఏది ముఖ్యమైనది?',
     'Only state government decision / రాష్ట్ర ప్రభుత్వ నిర్ణయం మాత్రమే',
     'Population (usually 10 lakhs+), revenue, administrative needs / జనాభా (సాధారణంగా 10 లక్షలు లేదా అంతకంటే ఎక్కువ), ఆదాయం, పాలనా అవసరాలు',
     'Central Govt permission / కేంద్ర ప్రభుత్వ అనుమతి',
     'Parliament Act / పార్లమెంట్ చట్టం',
     'b',
     'Municipal Corporation status is decided by state govt — usually for cities with 10 lakh+ population, revenue capacity, etc. / Municipal Corporation హోదా రాష్ట్ర ప్రభుత్వం నిర్ణయిస్తుంది — సాధారణంగా జనాభా 10 లక్షలు లేదా అంతకంటే ఎక్కువ, ఆదాయ సామర్థ్యం పరిగణలోకి తీసుకుని.'),
    (3,
     'hard',
     'What is the relationship of Municipal Commissioner with State Government?\nతెలుగు: Municipal Commissioner రాష్ట్ర ప్రభుత్వానికి సంబంధించి ఎలాంటి హోదా కలిగి ఉంటారు?',
     'Under State Government control (usually IAS) / రాష్ట్ర ప్రభుత్వ నియంత్రణలో',
     'Under Central Government / కేంద్ర ప్రభుత్వ నియంత్రణలో',
     'Directly appointed by Council / Municipal Council నేరుగా నియమిస్తుంది',
     'Appointed by Mayor / Mayor నియమిస్తారు',
     'a',
     'Municipal Commissioner usually an IAS officer appointed by state govt. Council + Mayor = governing; Commissioner = executive. / Municipal Commissioner సాధారణంగా IAS అధికారి — రాష్ట్ర ప్రభుత్వం నియమిస్తుంది. Municipal Council (Mayor) పాలక సంస్థ; Commissioner కార్యనిర్వాహక.'),
    (3,
     'medium',
     'Ward Committees are mandatory in which Municipalities under Art.243S?\nతెలుగు: Art.243S కింద Ward Committees ఏ Municipalities లో తప్పనిసరి?',
     'All Municipalities / అన్ని Municipalities లో',
     'Municipalities with 3 lakh+ population / 3 లక్షల లేదా అంతకంటే ఎక్కువ జనాభా ఉన్న Municipalities లో',
     'Only Municipal Corporations / Municipal Corporations లో మాత్రమే',
     'State govt decides / రాష్ట్ర ప్రభుత్వం నిర్ణయిస్తుంది',
     'b',
     'Art.243S: Ward Committees mandatory in Municipalities with 3 lakh+ population — analogous to Gram Sabha in 73rd Amendment. / Art.243S: 3 లక్షల లేదా అంతకంటే ఎక్కువ జనాభా ఉన్న Municipalities లో Ward Committees తప్పనిసరి. 73వ సవరణ Gram Sabhas కు సమానం.'),
    (4,
     'easy',
     'Ward Committees are mandatory in Municipalities with population of?\nతెలుగు: Ward Committees ఏ జనాభా ఉన్న Municipalities లో తప్పనిసరి?',
     '1 lakh and above / 1 లక్ష లేదా అంతకంటే ఎక్కువ',
     '3 lakhs and above / 3 లక్షలు లేదా అంతకంటే ఎక్కువ',
     '5 lakhs and above / 5 లక్షలు లేదా అంతకంటే ఎక్కువ',
     '10 lakhs and above / 10 లక్షలు లేదా అంతకంటే ఎక్కువ',
     'b',
     'Art.243S: Ward Committees mandatory in Municipalities with population 3 lakhs and above. / అనుచ్ఛేదం 243S: 3 లక్షలు (3 million కాదు — 3 lakh) లేదా అంతకంటే ఎక్కువ జనాభా ఉన్న Municipalities లో Ward Committees తప్పనిసరి.'),
    (4,
     'easy',
     'MPC is for areas with population?\nతెలుగు: Metropolitan Planning Committee (MPC) ఏ జనాభా ఉన్న ప్రాంతాలకు?',
     '5 lakhs+ / 5 లక్షలు లేదా అంతకంటే ఎక్కువ',
     '10 lakhs+ / 10 లక్షలు లేదా అంతకంటే ఎక్కువ',
     '50 lakhs+ / 50 లక్షలు లేదా అంతకంటే ఎక్కువ',
     '1 crore+ / 1 కోటి లేదా అంతకంటే ఎక్కువ',
     'b',
     'Art.243ZE: MPC = for metropolitan areas with population 10 lakhs (1 million) and above. / అనుచ్ఛేదం 243ZE: Metropolitan Planning Committee = 10 లక్షలు (1 million) లేదా అంతకంటే ఎక్కువ జనాభా ఉన్న metropolitan areas కు.'),
    (4,
     'medium',
     'What fraction of MPC members must be elected?\nతెలుగు: Metropolitan Planning Committee లో ఎంత భాగం సభ్యులు ఎన్నికైన వారు?',
     '1 / 2 (సగం)',
     '2/3',
     '3/4',
     'All / అందరూ',
     'b',
     'Art.243ZE(2): Not less than 2/3 members of MPC must be elected from PR bodies and ULBs. / అనుచ్ఛేదం 243ZE(2): MPC లో 2/3 వంతు సభ్యులు ఎన్నికైన PR సభ్యులు మరియు ULB councillors.'),
    (4,
     'medium',
     'What fraction of DPC members must be elected?\nతెలుగు: District Planning Committee (DPC) లో ఎంత భాగం సభ్యులు ఎన్నికైన వారు?',
     '1/2',
     '2/3',
     '3/4',
     '4/5',
     'd',
     'Art.243ZD(2): Not less than 4/5 members of DPC must be from elected PR + ULB bodies. / అనుచ్ఛేదం 243ZD(2): DPC లో 4/5 వంతు సభ్యులు ఎన్నికైన PR + ULB సభ్యులు.'),
    (4,
     'medium',
     'Who chairs the Ward Committee?\nతెలుగు: Ward Committee అధ్యక్షత వహించేది ఎవరు?',
     'Mayor',
     'Ward Councillor',
     'Municipal Commissioner',
     'State Government nominee',
     'b',
     'The Ward Councillor (elected representative of that ward) chairs the Ward Committee. / Ward Committee కి సంబంధిత Ward Councillor అధ్యక్షత వహిస్తారు.'),
    (4,
     'hard',
     'What is AMRUT scheme?\nతెలుగు: AMRUT పథకం ఏమిటి?',
     'Rural water supply scheme / గ్రామీణ నీటిసరఫరా పథకం',
     'Urban infrastructure scheme / Atal Mission for Rejuvenation and Urban Transformation — పట్టణ మౌలిక సదుపాయాల అభివృద్ధి',
     'Agricultural credit scheme / వ్యవసాయ పరపతి పథకం',
     'Digital India scheme / Digital India పథకం',
     'b',
     'AMRUT (2015): urban infrastructure development in 500 cities — water, sewage, parks, transport. / AMRUT (Atal Mission for Rejuvenation and Urban Transformation) — 2015లో ప్రారంభమైంది; 500 పట్టణాలలో నీరు, మురుగు, పార్కులు, వాహన సౌకర్యాలు మెరుగుపరచడం.'),
    (4,
     'hard',
     'Smart Cities Mission launched in?\nతెలుగు: Smart Cities Mission ఏ సంవత్సరంలో ప్రారంభమైంది?',
     '2014',
     '2015',
     '2016',
     '2017',
     'b',
     'Smart Cities Mission launched in June 2015; 100 cities selected for development. / Smart Cities Mission 2015 జూన్\u200cలో ప్రారంభమైంది. 100 స్మార్ట్ సిటీలు ఎంపిక చేయబడ్డాయి.'),
    (4,
     'hard',
     'After ULB dissolution, elections must be held within?\nతెలుగు: 74వ సవరణ ప్రకారం ULBs ని రద్దు చేసిన తర్వాత ఎంత కాలంలో ఎన్నికలు జరగాలి?',
     '3 months / 3 నెలలు',
     '6 months / 6 నెలలు',
     '1 year / 1 సంవత్సరం',
     '2 years / 2 సంవత్సరాలు',
     'b',
     'Art.243U: Elections must be held within 6 months of ULB dissolution (same as PR — Art.243E). / అనుచ్ఛేదం 243U: ULB రద్దు జరిగిన తర్వాత 6 నెలల్లోపు ఎన్నికలు జరగాలి. (PR కి కూడా 6 నెలలు — Art.243E)'),
    (5,
     'easy',
     'Who recommends principles for fund distribution to ULBs?\nతెలుగు: ULBs కి నిధుల పంపిణీ సూత్రాలు ఎవరు సిఫారసు చేస్తారు?',
     'Central Finance Commission / కేంద్ర ఆర్థిక సంఘం',
     'State Finance Commission / రాష్ట్ర ఆర్థిక సంఘం',
     'NITI Aayog',
     'RBI',
     'b',
     'SFC (Art.243Y) recommends principles for fund distribution from State Consolidated Fund to ULBs. / State Finance Commission (Art.243Y) ULBs కి రాష్ట్ర Consolidated Fund నుండి నిధుల పంపిణీ సూత్రాలు సిఫారసు చేస్తుంది.'),
    (5,
     'easy',
     'Tenure of ULBs?\nతెలుగు: ULB ఎన్నికల పదవీకాలం ఎంత?',
     '3 years / 3 సంవత్సరాలు',
     '4 years / 4 సంవత్సరాలు',
     '5 years / 5 సంవత్సరాలు',
     '6 years / 6 సంవత్సరాలు',
     'c',
     'Art.243U: ULB tenure = 5 years (same as PR under Art.243E). / అనుచ్ఛేదం 243U: ULB పదవీకాలం 5 సంవత్సరాలు (PR తో సమానం — Art.243E).'),
    (5,
     'medium',
     'Role of Central Finance Commission (CFC) regarding ULBs?\nతెలుగు: కేంద్ర ఆర్థిక సంఘం (Central Finance Commission) ULBs పై పాత్ర ఏమిటి?',
     'Directly funds ULBs / ULBs కి నేరుగా నిధులు ఇస్తుంది',
     'Reviews SFC reports and recommends grants to states for ULBs / SFC నివేదికను పరిశీలించి రాష్ట్రాలకు ULB గ్రాంట్లు సిఫారసు చేస్తుంది',
     'Conducts ULB elections / ULB ఎన్నికలు నిర్వహిస్తుంది',
     'Approves ULB budget / ULB బడ్జెట్ ఆమోదిస్తుంది',
     'b',
     'CFC reviews SFC reports and recommends grants to states for ULBs; 15th FC recommended ₹4.36 lakh crore for ULBs. / Central Finance Commission SFC నివేదికలు పరిశీలించి రాష్ట్రాలకు ULBs కి గ్రాంట్లు సిఫారసు చేస్తుంది. 15వ FC ULBs కి ₹4.36 లక్షల కోట్లు సిఫారసు చేసింది.'),
    (5,
     'medium',
     'How is SC/ST reservation determined in ULB elections?\nతెలుగు: ULB ఎన్నికలలో SC/ST రిజర్వేషన్ ఎలా నిర్ణయిస్తారు?',
     'Fixed at 20% / 20% నిర్ణీతం',
     'Fixed at 33% / 33% నిర్ణీతం',
     'In proportion to population / జనాభా నిష్పత్తిలో',
     'State government discretion / రాష్ట్ర ప్రభుత్వ విచక్షణ',
     'c',
     'Art.243T: SC/ST reservation in proportion to population (same as PR under Art.243D). / అనుచ్ఛేదం 243T: SC/ST రిజర్వేషన్ = జనాభా నిష్పత్తిలో (PR తో సమానం — Art.243D).'),
    (5,
     'hard',
     'Who empowers ULBs to levy taxes?\nతెలుగు: ULBs కి పన్ను విధించే అధికారం ఎవరు ఇస్తారు?',
     'Central Government / కేంద్ర ప్రభుత్వం',
     'State Legislature / రాష్ట్ర శాసనమండలి',
     'State Finance Commission',
     'Municipal Commissioner',
     'b',
     'Art.243X: State legislature may authorise ULBs to levy/collect taxes. (Parallel to Art.243H for PR). / అనుచ్ఛేదం 243X: రాష్ట్ర శాసనమండలి ULBs కి పన్నులు వసూలు చేసే అధికారం ఇవ్వగలదు. (PR కి Art.243H)'),
    (5,
     'hard',
     'Is OBC reservation mandatory in ULB elections?\nతెలుగు: ULB ఎన్నికలలో OBC రిజర్వేషన్ తప్పనిసరా?',
     'Yes / అవును',
     'No — State discretion (Art.243T(6)) / లేదు — రాష్ట్ర విచక్షణ',
     'Yes — under 73rd Amendment / అవును — 73వ సవరణ ప్రకారం',
     'Yes — under 102nd Amendment / అవును — 102వ సవరణ ప్రకారం',
     'b',
     "Art.243T(6): OBC reservation is discretionary. SC's Triple Test applies (same as PR). / Art.243T(6): OBC reservation at state's discretion (same as PR Art.243D(6)). SC Triple Test వర్తిస్తుంది."),
    (5,
     'hard',
     'Property tax is a major ULB revenue — in which list?\nతెలుగు: Property tax ULBs కి ముఖ్య ఆదాయ వనరు — ఇది ఏ List లో ఉంది?',
     'Union List',
     'State List',
     'Concurrent List',
     'Local List',
     'b',
     'Property tax is in the State List (List II). ULBs collect it under authority given by state legislature. / Property tax రాష్ట్ర జాబితా (List II) లో ఉంది. ULBs రాష్ట్ర శాసనమండలి అనుమతితో property tax వసూలు చేస్తాయి.'),
    (5,
     'medium',
     'Art.243Y — role of State Finance Commission for ULBs?\nతెలుగు: Art.243Y — రాష్ట్ర ఆర్థిక సంఘం (State Finance Commission) ULBలకు సంబంధించి ఏ పని చేస్తుంది?',
     'Appoints ULB officials / ULB అధికారులను నియమిస్తుంది',
     'Reviews ULB finances every 5 years and recommends tax devolution / 5 సంవత్సరాలకొకసారి ULB ఆర్థిక పరిస్థితి సమీక్షించి పన్నుల పంపిణీ సిఫారసు చేస్తుంది',
     'Conducts ULB elections / ULBల ఎన్నికలు నిర్వహిస్తుంది',
     'Approves Municipal bonds / Municipal bonds ఆమోదిస్తుంది',
     'b',
     'Art.243Y: SFC (constituted under Art.243I) also reviews finances of Municipalities and recommends devolution of taxes and grants from state. / Art.243Y: రాష్ట్ర ఆర్థిక సంఘం (Art.243I లో ఏర్పాటు) Panchayats కి మాదిరిగా Municipalities కి కూడా ఆర్థిక సిఫారసులు చేస్తుంది — పన్నుల పంపిణీ, రాష్ట్ర నిధి గ్రాంట్లు.'),
    (6,
     'easy',
     'How many subjects are in the 12th Schedule?\nతెలుగు: 12వ షెడ్యూల్ లో ఎన్ని అంశాలు ఉన్నాయి?',
     '12',
     '16',
     '18',
     '22',
     'c',
     '12th Schedule (74th Amendment): 18 subjects for ULBs. 11th Schedule (73rd Amendment, PR): 29 subjects. / 12వ షెడ్యూల్ (74వ సవరణ) లో 18 అంశాలు ఉన్నాయి — ULBs కి బదిలీ చేయగలిగే విషయాలు. 11వ షెడ్యూల్ (73వ సవరణ — PR) లో 29 అంశాలు ఉన్నాయి.'),
    (6,
     'easy',
     'Which is a 12th Schedule subject?\nతెలుగు: కింది వాటిలో 12వ షెడ్యూల్\u200cకి చెందే అంశం ఏది?',
     'Agricultural extension / వ్యవసాయ విస్తరణ',
     'Urban planning and land use regulation / పట్టణ ప్రణాళిక & భూ వినియోగ నియంత్రణ',
     'Village development / పల్లె అభివృద్ధి',
     'Forest conservation / అటవీ సంరక్షణ',
     'b',
     '12th Schedule Entry 1: Urban planning and land use regulation. Others: water supply (5), solid waste (6), street lighting (Entry 17), urban poverty alleviation (Entry 11) etc. / 12వ షెడ్యూల్ Entry 1: పట్టణ ప్రణాళిక & భూ వినియోగ నియంత్రణ. పట్టణ నీరు (Entry 5), గ్లోబల్ వేస్ట్ మేనేజ్\u200cమెంట్ (Entry 6), వీధి దీపాలు (Entry 17) మొ.'),
    (6,
     'medium',
     'What is Entry 2 of 12th Schedule?\nతెలుగు: 12వ షెడ్యూల్ Entry 2 ఏది?',
     'Urban forestry',
     'Regulation of land use and construction of buildings',
     'Slum improvement',
     'Urban poverty alleviation',
     'b',
     'Entry 2 of 12th Schedule: Regulation of land use and construction of buildings. / 12వ షెడ్యూల్ Entry 2: Regulation of land use and construction of buildings (భూ వినియోగం నియంత్రణ మరియు భవన నిర్మాణ నిబంధనలు).'),
    (6,
     'medium',
     'Slum improvement and upgradation is in which Entry of 12th Schedule?\nతెలుగు: 12వ షెడ్యూల్ లో slum improvement మరియు upgradation ఏ Entry లో ఉంది?',
     'Entry 9',
     'Entry 10',
     'Entry 7',
     'Entry 12',
     'b',
     'Entry 10 of 12th Schedule: Slum improvement and upgradation. / 12వ షెడ్యూల్ Entry 10: Slum improvement and upgradation (మురికివాడల అభివృద్ధి).'),
    (6,
     'hard',
     'What is Entry 18 of 12th Schedule?\nతెలుగు: 12వ షెడ్యూల్ Entry 18 ఏది?',
     'Urban poverty alleviation',
     'Regulation of slaughter houses and tanneries',
     'Cattle pounds',
     'Vital statistics including registration of births and deaths',
     'b',
     'Entry 18 of 12th Schedule: Regulation of slaughter houses and tanneries (NOT vital statistics which is Entry 16). / 12వ షెడ్యూల్ Entry 18 = వధశాలలు & తన్నెరీల నిబంధన (Regulation of slaughter houses and tanneries). Entry 16 = Vital statistics.'),
    (6,
     'hard',
     'Is transfer of 12th Schedule subjects mandatory in 74th Amendment?\nతెలుగు: 74వ సవరణలో 12వ షెడ్యూల్ అంశాల బదిలీ తప్పనిసరా?',
     'Yes — all 18 are mandatory / అవును — అన్ని 18 అంశాలూ తప్పనిసరి',
     "No — at state legislature's discretion (like 11th Schedule for PR) / లేదు — రాష్ట్ర శాసనమండలి విచక్షణ",
     'Yes — central govt decides / అవును — కేంద్రం నిర్ణయిస్తుంది',
     'Only water supply is mandatory / కేవలం నీటి సరఫరా మాత్రమే తప్పనిసరి',
     'b',
     "12th Schedule transfer NOT mandatory — state legislature's discretion (same as 11th Schedule for PR). / 12వ షెడ్యూల్ 18 అంశాల బదిలీ తప్పనిసరి కాదు — రాష్ట్ర శాసనమండలి విచక్షణ. ఇది PR 11వ షెడ్యూల్ మాదిరిగా ఉంది."),
    (6,
     'hard',
     'What is Entry 11 of 12th Schedule?\nతెలుగు: 12వ షెడ్యూల్ Entry 11 ఏది?',
     'Urban poverty alleviation',
     'Public health, sanitation, conservancy and solid waste management',
     'Street lighting and public amenities',
     'Slaughter houses',
     'a',
     'Entry 11 = Urban poverty alleviation (NOT street lighting which is Entry 17). / 12వ షెడ్యూల్ Entry 11 = పట్టణ పేదరిక నిర్మూలన (Urban poverty alleviation). Entry 6 = Public health & solid waste. Entry 17 = Street lighting & parking.'),
    (6,
     'medium',
     "'Vital Statistics' (birth-death records) is which Entry in the 12th Schedule?\nతెలుగు: 12వ షెడ్యూల్ లో 'Vital Statistics' (జనన-మరణ వివరాలు) ఏ Entry నంబర్?",
     'Entry 5',
     'Entry 9',
     'Entry 12',
     'Entry 16',
     'b',
     '12th Schedule Entry 9 = Vital statistics including registration of births and deaths. / 12వ షెడ్యూల్ Entry 9 = Vital Statistics including registration of births and deaths. Entry 5 = Public amenities (parks, playgrounds). Entry 12 = Public health.'),
    (7,
     'easy',
     '74th Amendment is what type of amendment?\nతెలుగు: 74వ సవరణ ఏ రకమైన సవరణ?',
     'Simple majority amendment / సాధారణ సవరణ (Simple majority)',
     'Special majority amendment / రాజ్యాంగ సవరణ (Special majority)',
     'Emergency amendment / జాతీయ అత్యవసర సవరణ',
     'Inter-state amendment / అంతర్రాష్ట్ర సవరణ',
     'b',
     '74th Amendment is a constitutional amendment (Special majority under Art.368), adding Arts 243P–ZG and 12th Schedule. / 74వ సవరణ Special majority (Art.368) రాజ్యాంగ సవరణ. అనుచ్ఛేదాలు 243P–ZG మరియు 12వ షెడ్యూల్ జోడించింది.'),
    (7,
     'easy',
     'JNNURM was launched in?\nతెలుగు: JNNURM (జవహర్\u200cలాల్ నెహ్రూ నేషనల్ అర్బన్ రెన్యువల్ మిషన్) ఏ సంవత్సరంలో ప్రారంభమైంది?',
     '2000',
     '2003',
     '2005',
     '2008',
     'c',
     'JNNURM launched in 2005 for urban infrastructure. Succeeded by AMRUT (2015). / JNNURM (Jawaharlal Nehru National Urban Renewal Mission) 2005లో ప్రారంభమైంది — పట్టణ మౌలిక సదుపాయాల అభివృద్ధి కోసం. ఇప్పుడు AMRUT దాని స్థానంలో ఉంది.'),
    (7,
     'medium',
     'PM SVANidhi scheme is for?\nతెలుగు: PM SVANidhi పథకం దేనికోసం?',
     'Rural housing / గ్రామీణ ఇళ్ళ నిర్మాణం',
     'Micro credit for street vendors / వీధి వ్యాపారులకు (Street vendors) మైక్రో క్రెడిట్',
     'Urban schools / పట్టణ స్కూళ్ళు',
     'Municipal bonds',
     'b',
     "PM SVANidhi (2020): micro-credit of ₹10,000 for street vendors post-COVID. Implemented through ULBs. / PM SVANidhi (PM Street Vendor's AtmaNirbhar Nidhi) 2020లో ప్రారంభమైంది — COVID-19 తర్వాత వీధి వ్యాపారులకు రూ.10,000 పని మూలధనం రుణం. ULBs ద్వారా అమలు."),
    (7,
     'medium',
     'Articles added in Part IX-A by 74th Amendment?\nతెలుగు: 74వ సవరణ ద్వారా జోడించిన Part IX-A లో అనుచ్ఛేదాల పరిధి?',
     '243A నుండి 243O',
     '243P నుండి 243ZG',
     '243 నుండి 243N',
     '244 నుండి 260',
     'b',
     'Part IX-A: Art.243P to 243ZG (18 Articles). Part IX (PR): Art.243 to 243O (16 Articles). / Part IX-A: అనుచ్ఛేదం 243P నుండి 243ZG వరకు (18 అనుచ్ఛేదాలు). Part IX (PR): 243 నుండి 243O (16 అనుచ్ఛేదాలు).'),
    (7,
     'hard',
     'What are Parastatal bodies in urban governance?\nతెలుగు: Parastatal bodies (అర్ధ-స్వతంత్ర సంస్థలు) అంటే ఏమిటి?',
     'Municipal corporations',
     'Urban development authorities like BDA, HUDA that work parallel to ULBs / BDA, HUDA వంటి పట్టణాభివృద్ధి సంస్థలు — ULBs కి సమాంతరంగా పని చేస్తాయి',
     'Central government departments / కేంద్ర ప్రభుత్వ విభాగాలు',
     'Ward committees',
     'b',
     'Parastatal bodies: BDA, HUDA, HMDA etc. work parallel to ULBs, often diluting municipal authority. / Parastatal bodies = BDA (Bengaluru Development Authority), HUDA, HMDA వంటి పట్టణాభివృద్ధి సంస్థలు — Municipal corporations కి సమాంతరంగా పని చేసి వాటి అధికారాలు తగ్గిస్తాయి.'),
    (7,
     'hard',
     'Which states/areas are exempted from 74th Amendment?\nతెలుగు: 74వ సవరణ ఏ రాష్ట్రాలకు వర్తించదు?',
     'Schedule V Areas (Tribal areas)',
     'Schedule VI areas / హిల్ districts of Darjeeling, Nagaland, Meghalaya, Mizoram',
     'All northeastern states',
     'J&K only',
     'b',
     '74th Amendment does NOT apply to Nagaland, Meghalaya, Mizoram, and 6th Schedule tribal area districts. / 74వ సవరణ Nagaland, Meghalaya, Mizoram మరియు 6వ షెడ్యూల్ tribal area districts (Darjeeling, Gorkhaland) కి వర్తించదు.'),
    (7,
     'hard',
     'First Indian city to issue Municipal bonds?\nతెలుగు: India మొట్టమొదటి ULB Municipal bonds ఏ నగరం జారీ చేసింది?',
     'Mumbai',
     'Bengaluru',
     'Ahmedabad',
     'Pune',
     'c',
     "Ahmedabad Municipal Corporation issued India's first Municipal Bond in 1998. / Ahmedabad Municipal Corporation 1998లో భారతదేశంలో మొదటి Municipal Bond జారీ చేసింది."),
    (7,
     'medium',
     'Metropolitan Planning Committee constituted under which Article?\nతెలుగు: Metropolitan Planning Committee (MPC) ఏ అనుచ్ఛేదం కింద ఏర్పాటవుతుంది?',
     'Art.243ZD',
     'Art.243ZE',
     'Art.243ZF',
     'Art.243ZG',
     'b',
     'Art.243ZE: Metropolitan Planning Committee for metro areas with 10 lakh+ population — coordinates development planning across municipal and panchayat bodies. / Art.243ZE: 10 లక్షల లేదా అంతకంటే ఎక్కువ జనాభా ఉన్న Metro ప్రాంతాలకు Metropolitan Planning Committee — జిల్లా, మేయర్, పంచాయత్ పరిధిలో ప్రణాళిక సమన్వయం.'),
]


def _seed_polity_ch25_notes_inner(conn, db_exec_fn, row_to_dict_fn, use_postgres, force=False):
    check = db_exec_fn(conn,
        "SELECT id FROM study_notes WHERE subject=? AND topic=? AND chapter_num=?",
        (_SUBJECT, _TOPIC, _CH))
    row = check.fetchone()
    if row and not force:
        return
    if row and force:
        db_exec_fn(conn, "DELETE FROM study_notes WHERE subject=? AND topic=? AND chapter_num=?",
                   (_SUBJECT, _TOPIC, _CH))
    db_exec_fn(conn,
        """INSERT INTO study_notes
           (subject, topic, chapter_num, chapter_title_te, chapter_title_en, pages_ref, sections_json)
           VALUES (?,?,?,?,?,?,?)""",
        (_SUBJECT, _TOPIC, _CH, _TITLE_TE, _TITLE_EN, _PAGES, json.dumps(_SECTIONS, ensure_ascii=False)))


def _seed_polity_ch25_mcqs_inner(conn, db_exec_fn, row_to_dict_fn, use_postgres):
    import json as _json
    cur = db_exec_fn(conn,
        "SELECT id FROM study_notes WHERE subject=? AND topic=? AND chapter_num=?",
        (_SUBJECT, _TOPIC, _CH))
    note_row = cur.fetchone()
    if not note_row:
        return
    note_id = row_to_dict_fn(note_row)['id']

    diff_map = {"easy": 1, "medium": 2, "hard": 3, "toughest": 4, 1: 1, 2: 2, 3: 3, 4: 4}

    cur2 = db_exec_fn(conn,
        "SELECT COUNT(*) FROM chapter_mcqs WHERE study_note_id=?", (note_id,))
    cnt_row = cur2.fetchone()
    if cnt_row:
        cnt = list(cnt_row)[0]
        if cnt >= len(_MCQS):
            return

    db_exec_fn(conn, "DELETE FROM chapter_mcqs WHERE study_note_id=?", (note_id,))

    for row in _MCQS:
        sec_idx   = row[0]
        diff_str  = row[1]
        q_te      = row[2]
        opt_a     = row[3]
        opt_b     = row[4]
        opt_c     = row[5]
        opt_d     = row[6]
        correct   = row[7]
        expl      = row[8]
        exam_type = row[9] if len(row) > 9 else 'General'
        if exam_type is None:
            exam_type = 'General'
        diff_int  = diff_map.get(diff_str, 2)
        db_exec_fn(conn,
            """INSERT INTO chapter_mcqs
               (study_note_id, section_idx, difficulty, exam_type,
                q_te, opt_a, opt_b, opt_c, opt_d, correct, explanation_te)
               VALUES (?,?,?,?,?,?,?,?,?,?,?)""",
            (note_id, sec_idx, diff_int, exam_type,
             q_te, opt_a, opt_b, opt_c, opt_d, correct, expl))


import json
