import sqlite3, os

SOURCE = 'Science_Set13B_Human_System4_Ext'
DB = os.path.join(os.path.dirname(__file__), 'database.db')

questions = [
    ('What are the two main types of immunity?\\nతెలుగు: రోగనిరోధక శక్తి యొక్క రెండు ప్రధాన రకాలు ఏవి?', 'Innate and Adaptive / సహజ మరియు అనుకూల', 'Active and Passive / క్రియాశీల మరియు నిష్క్రియ', 'Natural and Artificial / సహజ మరియు కృత్రిమ', 'Humoral and Cell-mediated / హ్యూమోరల్ మరియు సెల్-మీడియేటెడ్', 'A', 'M', '', 1),
    ('Which cells are known as the soldiers of the immune system?\\nతెలుగు: రోగనిరోధక వ్యవస్థ యొక్క సైనికులు అని పిలువబడే కణాలు ఏవి?', 'White blood cells / తెలుపు రక్త కణాలు', 'Red blood cells / ఎర్రు రక్త కణాలు', 'Platelets / ప్లేట్‌లెట్లు', 'Stem cells / స్టెమ్ కణాలు', 'A', 'M', '', 2),
    ('What are antibodies made of?\\nతెలుగు: యాంటీబాడీలు దేనితో తయారవుతాయి?', 'Proteins / ప్రోటీన్లు', 'Carbohydrates / కార్బోహైడ్రేట్లు', 'Lipids / లిపిడ్లు', 'Nucleic acids / న్యూక్లియిక్ యాసిడ్లు', 'A', 'M', '', 3),
    ('Vaccination provides which type of immunity?\\nతెలుగు: వ్యాక్సినేషన్ ఏ రకమైన రోగనిరోధకతను అందిస్తుంది?', 'Active artificial immunity / క్రియాశీల కృత్రిమ రోగనిరోధకత', 'Passive natural immunity / నిష్క్రియ సహజ రోగనిరోధకత', 'Innate immunity / సహజ రోగనిరోధకత', 'Herd immunity only / గ్రూప్ రోగనిరోధకత మాత్రమే', 'A', 'M', '', 4),
    ('Which organ produces T lymphocytes?\\nతెలుగు: T లింఫోసైట్లు ఏ అవయవంలో పరిపక్వం చెందుతాయి?', 'Thymus / థైమస్', 'Spleen / ప్లీహం', 'Bone marrow / ఎముక మజ్జ', 'Lymph node / లింఫ్ నోడ్', 'A', 'M', '', 5),
    ('What does HIV stand for?\\nతెలుగు: HIV అంటే ఏమిటి?', 'Human Immunodeficiency Virus / హ్యూమన్ ఇమ్యునోడెఫిషియెన్సీ వైరస్', 'Human Influenza Virus / హ్యూమన్ ఇన్‌ఫ్లూయెంజా వైరస్', 'High Immunity Virus / హై ఇమ్యూనిటీ వైరస్', 'Human Infective Virus / హ్యూమన్ ఇన్‌ఫెక్టివ్ వైరస్', 'A', 'M', '', 6),
    ('Allergies are caused by an overreaction of which system?\\nతెలుగు: అలెర్జీలు ఏ వ్యవస్థ అతిప్రతిచర్య వల్ల వస్తాయి?', 'Immune system / రోగనిరోధక వ్యవస్థ', 'Nervous system / నాడీ వ్యవస్థ', 'Endocrine system / ఎండోక్రైన్ వ్యవస్థ', 'Digestive system / జీర్ణ వ్యవస్థ', 'A', 'M', '', 7),
    ('Where do B lymphocytes mature?\\nతెలుగు: B లింఫోసైట్లు ఎక్కడ పరిపక్వం చెందుతాయి?', 'Bone marrow / ఎముక మజ్జ', 'Thymus / థైమస్', 'Spleen / ప్లీహం', 'Lymph nodes / లింఫ్ నోడ్లు', 'A', 'M', '', 8),
    ('What is the first line of defense against pathogens?\\nతెలుగు: వ్యాధికారకాలకు వ్యతిరేకంగా మొదటి రక్షణ మార్గం ఏమిటి?', 'Skin and mucous membranes / చర్మం మరియు శ్లేష్మ పొరలు', 'Antibodies / యాంటీబాడీలు', 'White blood cells / తెలుపు రక్త కణాలు', 'Fever / జ్వరం', 'A', 'M', '', 9),
    ('Autoimmune disease occurs when?\\nతెలుగు: స్వయం రోగనిరోధక వ్యాధి ఎప్పుడు వస్తుంది?', 'Immune system attacks own body / రోగనిరోధక వ్యవస్థ తన శరీరాన్ని దాడి చేసినప్పుడు', 'Pathogen escapes immune system / వ్యాధికారకం తప్పించుకున్నప్పుడు', 'Vaccines fail / వ్యాక్సిన్లు విఫలమైనప్పుడు', 'Antibodies are absent / యాంటీబాడీలు లేనప్పుడు', 'A', 'M', '', 10),
    ('The retina is part of which sense organ?\\nతెలుగు: రెటీనా ఏ ఇంద్రియ అవయవంలో భాగం?', 'Eye / కన్ను', 'Ear / చెవి', 'Nose / ముక్కు', 'Skin / చర్మం', 'A', 'M', '', 11),
    ('What are the photoreceptors in the retina?\\nతెలుగు: రెటీనాలో ఫోటోరిసెప్టర్లు ఏవి?', 'Rods and cones / రాడ్స్ మరియు కోన్స్', 'Neurons and dendrites / న్యూరాన్లు మరియు డెండ్రైట్లు', 'Cilia and flagella / సిలియా మరియు ఫ్లాజెల్లా', 'Muscles and tendons / కండరాలు మరియు టెండాన్లు', 'A', 'M', '', 12),
    ('Which part of the ear is responsible for balance?\\nతెలుగు: చెవిలో సమతుల్యతకు బాధ్యత వహించే భాగం ఏది?', 'Semicircular canals / సెమీసర్క్యులర్ కెనాల్స్', 'Cochlea / కాక్లియా', 'Eardrum / చెవి పొర', 'Ossicles / ఆసికల్స్', 'A', 'M', '', 13),
    ('The cornea is transparent to allow?\\nతెలుగు: కార్నియా పారదర్శకంగా ఉంటుంది దేనికోసం?', 'Light to enter the eye / కన్నులోకి వెలుతురు ప్రవేశించడానికి', 'Blood to flow / రక్తం ప్రవహించడానికి', 'Tears to drain / కన్నీళ్ళు వెళ్ళడానికి', 'Air to circulate / గాలి చుట్టూ తిరగడానికి', 'A', 'M', '', 14),
    ('What fluid fills the middle ear?\\nతెలుగు: మధ్య చెవిలో ఏ ద్రవం నిండి ఉంటుంది?', 'Air / గాలి', 'Perilymph / పెరిలింఫ్', 'Endolymph / ఎండోలింఫ్', 'Blood plasma / రక్త ప్లాస్మా', 'A', 'M', '', 15),
    ('Taste buds are mainly located on which structure?\\nతెలుగు: రుచి మొగ్గలు ప్రధానంగా ఏ నిర్మాణంపై ఉంటాయి?', 'Tongue papillae / నాలుక పాపిల్లే', 'Lips / పెదవులు', 'Palate / అంగిట', 'Gums / చిగుళ్ళు', 'A', 'M', '', 16),
    ('How many basic tastes can humans detect?\\nతెలుగు: మానవులు ఎన్ని ప్రాథమిక రుచులను గుర్తించగలరు?', 'Five / అయిదు (sweet, sour, salty, bitter, umami)', 'Three / మూడు', 'Four / నాలుగు', 'Seven / ఏడు', 'A', 'M', '', 17),
    ('What is the function of the iris in the eye?\\nతెలుగు: కన్నులో ఐరిస్ యొక్క పని ఏమిటి?', 'Controls amount of light entering / ప్రవేశించే వెలుతురు మొత్తాన్ని నియంత్రిస్తుంది', 'Focuses light on retina / వెలుతురును రెటీనాపై దృష్టి కేంద్రీకరిస్తుంది', 'Produces tears / కన్నీళ్ళు ఉత్పత్తి చేస్తుంది', 'Converts light to signals / వెలుతురును సంకేతాలుగా మారుస్తుంది', 'A', 'M', '', 18),
    ('Which bone vibrates to transmit sound in the ear?\\nతెలుగు: చెవిలో శబ్దాన్ని ప్రసారం చేయడానికి వణికే ఎముక ఏది?', 'Ossicles (malleus, incus, stapes) / ఆసికల్స్', 'Cochlea / కాక్లియా', 'Eardrum / చెవి పొర', 'Semicircular canal / సెమీసర్క్యులర్ కెనాల్', 'A', 'M', '', 19),
    ('What is the blind spot in the eye?\\nతెలుగు: కన్నులో బ్లైండ్ స్పాట్ అంటే ఏమిటి?', 'Area where optic nerve exits, no photoreceptors / ఆప్టిక్ నరం బయటపడే ప్రదేశం', 'Center of the retina / రెటీనా మధ్యభాగం', 'Edge of the cornea / కార్నియా అంచు', 'Pupil area / పుపిల్ ప్రాంతం', 'A', 'M', '', 20),
    ('Olfactory receptors are responsible for which sense?\\nతెలుగు: ఆల్ఫాక్టరీ రిసెప్టర్లు ఏ ఇంద్రియానికి బాధ్యత వహిస్తాయి?', 'Smell / వాసన', 'Taste / రుచి', 'Touch / స్పర్శ', 'Hearing / వినికిడి', 'A', 'M', '', 21),
    ('Cataracts affect which part of the eye?\\nతెలుగు: కంటి తెర ఏ భాగాన్ని ప్రభావితం చేస్తుంది?', 'Lens / కంటి లెన్స్', 'Retina / రెటీనా', 'Cornea / కార్నియా', 'Iris / ఐరిస్', 'A', 'M', '', 22),
    ('The outer ear collects sound and funnels it to the?\\nతెలుగు: బాహ్య చెవి శబ్దాన్ని సేకరించి దేనికి ఫన్నెల్ చేస్తుంది?', 'Eardrum / చెవి పొర', 'Cochlea / కాక్లియా', 'Ossicles / ఆసికల్స్', 'Auditory nerve / శ్రవణ నరం', 'A', 'M', '', 23),
    ('Which cells in the retina are responsible for color vision?\\nతెలుగు: రెటీనాలో రంగు దృష్టికి బాధ్యత వహించే కణాలు ఏవి?', 'Cone cells / కోన్ కణాలు', 'Rod cells / రాడ్ కణాలు', 'Bipolar cells / బైపోలార్ కణాలు', 'Ganglion cells / గాంగ్లియాన్ కణాలు', 'A', 'M', '', 24),
    ('Color blindness is more common in which gender?\\nతెలుగు: వర్ణాంధత్వం ఏ లింగంలో ఎక్కువగా ఉంటుంది?', 'Males / పురుషులు', 'Females / స్త్రీలు', 'Both equally / రెండూ సమానంగా', 'Neither / ఏదీ కాదు', 'A', 'M', '', 25),
    ('Which vitamin is essential for good vision?\\nతెలుగు: మంచి దృష్టికి ఏ విటమిన్ అవసరం?', 'Vitamin A / విటమిన్ A', 'Vitamin B / విటమిన్ B', 'Vitamin C / విటమిన్ C', 'Vitamin D / విటమిన్ D', 'A', 'M', '', 26),
    ('Night blindness is caused by deficiency of?\\nతెలుగు: రాత్రి అంధత్వం దేని లోపం వల్ల వస్తుంది?', 'Vitamin A / విటమిన్ A', 'Vitamin B12 / విటమిన్ B12', 'Vitamin C / విటమిన్ C', 'Iron / ఇనుము', 'A', 'M', '', 27),
    ('Histamine is released during which process?\\nతెలుగు: హిస్టమైన్ ఏ ప్రక్రియలో విడుదల అవుతుంది?', 'Allergic reaction / అలెర్జీ ప్రతిచర్య', 'Normal digestion / సాధారణ జీర్ణక్రియ', 'Blood clotting / రక్తం గడ్డకట్టడం', 'Bone repair / ఎముక మరమ్మతు', 'A', 'M', '', 28),
    ('Which immunoglobulin is most abundant in blood?\\nతెలుగు: రక్తంలో అత్యంత సమృద్ధిగా ఉండే ఇమ్యునోగ్లోబ్యులిన్ ఏది?', 'IgG / IgG', 'IgM / IgM', 'IgA / IgA', 'IgE / IgE', 'A', 'M', '', 29),
    ('What is the function of tears beyond lubrication?\\nతెలుగు: కన్నీళ్ళ పని లూబ్రికేషన్ మినహా ఏమిటి?', 'Antibacterial protection / యాంటీబాక్టీరియల్ రక్షణ', 'Light refraction / వెలుతురు వక్రీభవనం', 'Blood supply / రక్త సరఫరా', 'Hormone secretion / హార్మోన్ స్రావం', 'A', 'M', '', 30),
    ('Glaucoma is caused by increased pressure in?\\nతెలుగు: గ్లాకోమా ఎక్కడ పెరిగిన పీడనం వల్ల వస్తుంది?', 'Eye / కన్ను', 'Brain / మెదడు', 'Ear / చెవి', 'Spine / వెన్నెముక', 'A', 'M', '', 31),
    ('Memory cells in the immune system provide?\\nతెలుగు: రోగనిరోధక వ్యవస్థలో జ్ఞాపక కణాలు ఏమి అందిస్తాయి?', 'Long-term immunity / దీర్ఘకాలిక రోగనిరోధకత', 'Short-term protection / తాత్కాలిక రక్షణ', 'Immediate response / తక్షణ ప్రతిచర్య', 'Inflammation / మంట', 'A', 'M', '', 32),
    ('The eustachian tube connects the middle ear to?\\nతెలుగు: యూస్టేషియన్ ట్యూబ్ మధ్య చెవిని దేనికి కలుపుతుంది?', 'Throat/nasopharynx / గొంతు/నాసోఫారింక్స్', 'Outer ear / బాహ్య చెవి', 'Inner ear / అంతర చెవి', 'Nose / ముక్కు', 'A', 'M', '', 33),
    ('Phagocytosis is the process by which?\\nతెలుగు: ఫాగోసైటోసిస్ ఏ ప్రక్రియ?', 'Cells engulf and destroy pathogens / కణాలు వ్యాధికారకాలను మింగి నాశనం చేస్తాయి', 'Cells divide rapidly / కణాలు వేగంగా విభజించబడతాయి', 'Antibodies are produced / యాంటీబాడీలు ఉత్పత్తి అవుతాయి', 'Inflammation occurs / మంట వస్తుంది', 'A', 'M', '', 34),
    ('Tinnitus refers to a condition affecting?\\nతెలుగు: టిన్నిటస్ ఏ పరిస్థితిని సూచిస్తుంది?', 'Ears (ringing sound) / చెవులు (గంట శబ్దం)', 'Eyes / కళ్ళు', 'Nose / ముక్కు', 'Throat / గొంతు', 'A', 'M', '', 35),
    ('The cochlea in the inner ear is involved in?\\nతెలుగు: అంతర చెవిలో కాక్లియా దేనికి సంబంధించింది?', 'Hearing / వినికిడి', 'Balance / సమతుల్యత', 'Both hearing and balance / రెండూ', 'Pressure equalization / పీడన సమీకరణ', 'A', 'M', '', 36),
    ('Natural killer cells are part of which immunity?\\nతెలుగు: నేచురల్ కిల్లర్ కణాలు ఏ రోగనిరోధకతలో భాగం?', 'Innate immunity / సహజ రోగనిరోధకత', 'Adaptive immunity / అనుకూల రోగనిరోధకత', 'Passive immunity / నిష్క్రియ రోగనిరోధకత', 'Herd immunity / గ్రూప్ రోగనిరోధకత', 'A', 'M', '', 37),
    ('Which sense is detected by Meissner\'s corpuscles?\\nతెలుగు: మేస్నర్ కార్పస్కిల్స్ ఏ ఇంద్రియాన్ని గుర్తిస్తాయి?', 'Touch / స్పర్శ', 'Pain / నొప్పి', 'Temperature / ఉష్ణోగ్రత', 'Pressure / పీడనం', 'A', 'M', '', 38),
    ('Which part of the eye adjusts focus for near and far objects?\\nతెలుగు: దగ్గర మరియు దూర వస్తువులకు దృష్టిని సర్దుబాటు చేసే కన్ను భాగం ఏది?', 'Lens / లెన్స్', 'Cornea / కార్నియా', 'Retina / రెటీనా', 'Iris / ఐరిస్', 'A', 'M', '', 39),
    ('Asthma involves inflammation of which structures?\\nతెలుగు: ఆస్తమా ఏ నిర్మాణాల మంటను కలిగి ఉంటుంది?', 'Airways/bronchioles / శ్వాస మార్గాలు/బ్రాంకియోల్స్', 'Alveoli only / అల్వియోలై మాత్రమే', 'Lung pleura / ఊపిరితిత్తుల ప్లూరా', 'Trachea only / ట్రాకియా మాత్రమే', 'A', 'M', '', 40),
    ('Which protein acts as an antigen on the surface of pathogens?\\nతెలుగు: వ్యాధికారకాల ఉపరితలంపై యాంటిజెన్‌గా పనిచేసే ప్రోటీన్ ఏది?', 'Surface proteins/glycoproteins / ఉపరితల ప్రోటీన్లు/గ్లైకోప్రోటీన్లు', 'Hemoglobin / హిమోగ్లోబిన్', 'Enzymes / ఎంజైమ్లు', 'Hormones / హార్మోన్లు', 'A', 'M', '', 41),
    ('Rods in the retina are sensitive to?\\nతెలుగు: రెటీనాలో రాడ్స్ దేనికి సంవేదనశీలంగా ఉంటాయి?', 'Low light / తక్కువ వెలుతురు', 'Color / రంగు', 'Bright light / ప్రకాశవంతమైన వెలుతురు', 'UV light / UV వెలుతురు', 'A', 'M', '', 42),
    ('Sneezing is controlled by which part of the nervous system?\\nతెలుగు: తుమ్ము నాడీ వ్యవస్థ యొక్క ఏ భాగం ద్వారా నియంత్రించబడుతుంది?', 'Brain stem reflex / మెదడు కాండం రిఫ్లెక్స్', 'Cerebrum / సెరిబ్రమ్', 'Spinal cord only / వెన్నుపాము మాత్రమే', 'Cerebellum / సెరెబెల్లమ్', 'A', 'M', '', 43),
    ('Which sense organ detects changes in head position?\\nతెలుగు: తల స్థానంలో మార్పులను గుర్తించే ఇంద్రియ అవయవం ఏది?', 'Ear (vestibular system) / చెవి (వెస్టిబ్యులర్ వ్యవస్థ)', 'Eye / కన్ను', 'Skin / చర్మం', 'Nose / ముక్కు', 'A', 'M', '', 44),
    ('What is the function of cerumen (earwax)?\\nతెలుగు: సెరుమెన్ (చెవి మైనం) యొక్క పని ఏమిటి?', 'Protect ear canal from dust and bacteria / దుమ్ము మరియు బాక్టీరియా నుండి చెవి కాలువను రక్షించడం', 'Improve hearing / వినికిడి మెరుగుపరచడం', 'Produce sound / శబ్దం ఉత్పత్తి చేయడం', 'Balance maintenance / సమతుల్యత నిర్వహణ', 'A', 'M', '', 45),
    ('Fever is an immune response that?\\nతెలుగు: జ్వరం ఒక రోగనిరోధక ప్రతిచర్య అది ఏమి చేస్తుంది?', 'Kills pathogens by raising temperature / ఉష్ణోగ్రత పెంచడం ద్వారా వ్యాధికారకాలను చంపుతుంది', 'Cools the body / శరీరాన్ని చల్లబరుస్తుంది', 'Reduces inflammation / మంటను తగ్గిస్తుంది', 'Speeds digestion / జీర్ణాన్ని వేగవంతం చేస్తుంది', 'A', 'M', '', 46),
    ('Which type of WBC produces antibodies?\\nతెలుగు: యాంటీబాడీలు ఉత్పత్తి చేసే WBC రకం ఏది?', 'B lymphocytes / B లింఫోసైట్లు', 'T lymphocytes / T లింఫోసైట్లు', 'Neutrophils / న్యూట్రోఫిల్స్', 'Monocytes / మోనోసైట్లు', 'A', 'M', '', 47),
    ('Aqueous humor is found in which part of the eye?\\nతెలుగు: అక్వస్ హ్యూమర్ కన్నులో ఏ భాగంలో ఉంటుంది?', 'Anterior chamber (front of eye) / ముందు గది', 'Posterior chamber / వెనుక గది', 'Vitreous chamber / విట్రియస్ గది', 'Retina / రెటీనా', 'A', 'M', '', 48),
    ('Which immunization schedule is given at birth in India?\\nతెలుగు: భారతదేశంలో పుట్టినప్పుడు ఇచ్చే టీకా షెడ్యూల్ ఏమిటి?', 'BCG and Hepatitis B / BCG మరియు హెపటైటిస్ B', 'Polio only / పోలియో మాత్రమే', 'DPT / DPT', 'MMR / MMR', 'A', 'M', '', 49),
    ('The pupil dilates to allow more light in which condition?\\nతెలుగు: ఏ పరిస్థితిలో మరింత వెలుతురు అనుమతించడానికి పుపిల్ విస్తరిస్తుంది?', 'Low light / తక్కువ వెలుతురు', 'Bright light / ప్రకాశవంతమైన వెలుతురు', 'Looking at near objects / దగ్గర వస్తువులు చూసేటప్పుడు', 'Reading / చదవడం', 'A', 'M', '', 50),
]

def seed():
    con = sqlite3.connect(DB); cur = con.cursor()
    cur.execute("DELETE FROM questions WHERE source_file=?", (SOURCE,))
    cur.executemany(
        """INSERT INTO questions (folder,topic,source_file,question_text,option_a,option_b,option_c,option_d,correct_answer,difficulty,explanation,question_order)
           VALUES ('GK','General_Science',?,?,?,?,?,?,?,?,?,?)""",
        [(SOURCE, *q) for q in questions])
    con.commit()
    n = cur.execute("SELECT COUNT(*) FROM questions WHERE source_file=?",(SOURCE,)).fetchone()[0]
    con.close(); print(f"Inserted {n} from {SOURCE}")

if __name__ == '__main__': seed()