"""
seed_conflicts_mcq.py
80 GKToday-style MCQs — Topic: International_Current_Affairs
Sub-topic: Global Conflicts & Geopolitics 2025-2026 ONLY
Folder: AP_HC | IDs: 22001-22080
NOTE: seed() runs DELETE+INSERT to force-refresh stale 2024/2023 data.
"""

import os, sqlite3

DATABASE_URL = os.environ.get("DATABASE_URL", "")
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)
USE_POSTGRES = bool(DATABASE_URL)

CONFLICTS_MCQS = [
    # OPERATION SINDOOR & INDIA-PAKISTAN 2025 (22001-22016)
    {"id":22001,"question_text":"On which date did India launch 'Operation Sindoor' against terrorist camps in Pakistan and PoK?","option_a":"May 7, 2025","option_b":"April 22, 2025","option_c":"May 15, 2025","option_d":"March 7, 2025","correct_answer":"A","explanation":"Operation Sindoor was launched on May 7, 2025 — India's precision missile strikes on 9 terrorist camps across Pakistan and Pakistan-Occupied Kashmir, in retaliation for the Pahalgam terror attack (April 22, 2025).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22002,"question_text":"The Pahalgam terror attack (April 22, 2025) occurred at which specific location in Jammu & Kashmir?","option_a":"Dal Lake, Srinagar","option_b":"Baisaran Valley, Anantnag district","option_c":"Gulmarg ski resort","option_d":"Betaab Valley, Pahalgam","correct_answer":"B","explanation":"The Pahalgam terror attack occurred at Baisaran Valley (a meadow near Pahalgam) in the Anantnag district of J&K on April 22, 2025. 26 tourists were killed; 20+ injured. TRF (The Resistance Front, a Lashkar-e-Taiba proxy) was blamed. This triggered Operation Sindoor on May 7, 2025.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22003,"question_text":"How many tourists were killed in the Pahalgam terror attack of April 22, 2025?","option_a":"12","option_b":"18","option_c":"26","option_d":"33","correct_answer":"C","explanation":"26 tourists were killed in the Pahalgam terror attack (April 22, 2025) at Baisaran Valley, Anantnag, J&K — the worst terrorist attack on civilians in India since 2008 Mumbai attacks. 20+ more were injured. The attack was linked to Pakistan-based Lashkar-e-Taiba (through its proxy TRF).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22004,"question_text":"Operation Sindoor targeted 9 terrorist camps. Which two Pakistan-based militant groups' infrastructure was specifically targeted?","option_a":"Al-Qaeda and ISIS","option_b":"Jaish-e-Mohammed and Lashkar-e-Taiba","option_c":"Haqqani Network and TTP","option_d":"LeT and Al-Badr","correct_answer":"B","explanation":"Operation Sindoor (May 7, 2025) targeted infrastructure of Jaish-e-Mohammed (JeM) and Lashkar-e-Taiba (LeT) — Pakistan's two most dangerous terrorist groups. 9 sites were struck across Pakistan and Pakistan-Occupied Kashmir using precision missiles by the Indian Air Force. The operation lasted 23 minutes.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22005,"question_text":"Pakistan's retaliatory operation against India (launched May 10, 2025) was codenamed:","option_a":"Operation Bunyan-um-Marsoos","option_b":"Operation Thunder Shield","option_c":"Operation Black Eagle","option_d":"Operation Iron Sword","correct_answer":"A","explanation":"Pakistan launched 'Operation Bunyan-um-Marsoos' on May 10, 2025 — a retaliatory operation after India's Operation Sindoor. Military hostilities continued until a ceasefire was reached on May 10, 2025 (effective 5:00 PM IST). 'Bunyan-um-Marsoos' is an Arabic phrase from the Quran meaning 'solid structure/wall.'","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22006,"question_text":"The India-Pakistan ceasefire of May 10, 2025 (following Operation Sindoor) was effective from what time?","option_a":"12:00 noon IST","option_b":"3:00 PM IST","option_c":"5:00 PM IST","option_d":"11:59 PM IST","correct_answer":"C","explanation":"The India-Pakistan ceasefire after Operation Sindoor was effective from 5:00 PM IST / 4:30 PM PKT on May 10, 2025. While Pakistan acknowledged American involvement in brokering the ceasefire, Indian officials maintained the agreement was reached directly between the two countries.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22007,"question_text":"Operation Sindoor was India's precision strike response. How long did the initial operation last?","option_a":"5 minutes","option_b":"23 minutes","option_c":"1 hour 15 minutes","option_d":"4 hours","correct_answer":"B","explanation":"Operation Sindoor lasted 23 minutes — a highly precise, swift strike on 9 terrorist infrastructure targets in Pakistan and PoK. Indian Air Force jets launched precision missiles. The operation was designed to minimize civilian casualties while destroying terrorist camps of JeM and LeT.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22008,"question_text":"After Operation Sindoor, India took several diplomatic measures against Pakistan. Which of the following is correct?","option_a":"India closed the Wagah-Attari border permanently","option_b":"India suspended the Indus Waters Treaty with Pakistan","option_c":"India expelled the Pakistani High Commissioner","option_d":"India banned all Pakistani goods imports and suspended the Indus Waters Treaty","correct_answer":"D","explanation":"Following the Pahalgam attack and Operation Sindoor, India took multiple measures against Pakistan: suspended the Indus Waters Treaty (1960), banned Pakistani goods imports, halted SAARC Visa Exemption Scheme for Pakistani nationals, and expelled the Pakistani High Commissioner. India also closed Indian airspace to Pakistani airlines.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22009,"question_text":"The Pahalgam attack was attributed to which group — a proxy of Lashkar-e-Taiba?","option_a":"Al-Badr","option_b":"Hizbul Mujahideen","option_c":"The Resistance Front (TRF)","option_d":"Indian Mujahideen","correct_answer":"C","explanation":"The Resistance Front (TRF) — a proxy of Lashkar-e-Taiba (LeT) — claimed responsibility for the Pahalgam terror attack (April 22, 2025). TRF was formed in 2019 after Article 370 revocation and uses digital platforms for radicalization. Pakistan-based LeT is banned as a terrorist organization by USA, EU, India, and UN.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22010,"question_text":"Operation Sindoor targeted terrorist camps in which two regions of Pakistan?","option_a":"Pakistan and Pakistan-Occupied Kashmir (PoK)","option_b":"Pakistan and Balochistan","option_c":"Sindh and Balochistan","option_d":"KPK and FATA","correct_answer":"A","explanation":"Operation Sindoor struck 9 terrorist camps in Pakistan (Punjab province, including Bahawalpur — JeM HQ, and Muridke — LeT HQ) and Pakistan-Occupied Kashmir (PoK). The strikes were deep inside Pakistani territory — a significant escalation from previous Indian counter-terrorism operations.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22011,"question_text":"The SCO Summit 2025 in Tianjin explicitly condemned which terrorism incident — marking a diplomatic win for India?","option_a":"Uri attack 2016","option_b":"Pulwama attack 2019","option_c":"Pahalgam attack April 22, 2025","option_d":"Parliament attack 2001","correct_answer":"C","explanation":"SCO Tianjin 2025 declaration explicitly condemned the Pahalgam terror attack (April 22, 2025) and called for bringing perpetrators to justice. This was a significant win for India since Pakistan and China — both SCO members — joined the condemnation, weakening Pakistan's narrative.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22012,"question_text":"India suspended which major water-sharing treaty with Pakistan after the Pahalgam attack 2025?","option_a":"Simla Agreement","option_b":"Lahore Declaration","option_c":"Indus Waters Treaty","option_d":"Tashkent Agreement","correct_answer":"C","explanation":"India suspended the Indus Waters Treaty (IWT, 1960) with Pakistan after the Pahalgam attack. The IWT was brokered by World Bank and gives Pakistan rights to western rivers (Indus, Jhelum, Chenab) and India to eastern rivers. Suspension was India's most severe diplomatic measure — the treaty had survived 3 wars and 65 years.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22013,"question_text":"What was the Indian government's code name for the rescue operation that evacuated Indian nationals from conflict zones during the India-Pakistan standoff 2025?","option_a":"Operation Dost","option_b":"Operation Kaveri","option_c":"Operation Sagar Bandhu","option_d":"Operation Ganga","correct_answer":"C","explanation":"Operation Sagar Bandhu was India's operation to evacuate Indian nationals from Sri Lanka during Cyclone Ditwah (November 27, 2025). During the India-Pakistan standoff (May 2025), India conducted diplomatic and consular evacuations. Note: Operations Dost (Turkey 2023), Kaveri (Sudan 2023), Ganga (Ukraine 2022) were other evacuation operations.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22014,"question_text":"After Operation Sindoor, which US official was reportedly involved in brokering the India-Pakistan ceasefire of May 10, 2025?","option_a":"Secretary of State Marco Rubio","option_b":"National Security Advisor","option_c":"Vice President JD Vance","option_d":"CIA Director","correct_answer":"A","explanation":"US Secretary of State Marco Rubio was reportedly involved in diplomatic communications around the India-Pakistan ceasefire (May 10, 2025). Pakistan acknowledged American involvement; India maintained the ceasefire was reached bilaterally. Marco Rubio is Trump's Secretary of State (from January 20, 2025).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22015,"question_text":"What was India's stated strategic objective of Operation Sindoor?","option_a":"Permanent occupation of PoK","option_b":"Destroy terrorist infrastructure and deter future attacks","option_c":"Regime change in Pakistan","option_d":"Capture of Gilgit-Baltistan","correct_answer":"B","explanation":"India's stated objective of Operation Sindoor: destroy terrorist infrastructure of JeM and LeT in Pakistan/PoK and deter future attacks. India emphasized it was NOT targeting Pakistani military or civilian infrastructure — only terrorist camps. The operation's name 'Sindoor' refers to the vermilion worn by married Hindu women — symbolic of the attack's victims.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22016,"question_text":"Which Swiss think tank reported that 'India's air superiority during Operation Sindoor forced Pakistan to seek ceasefire'?","option_a":"Geneva Centre for Security Policy","option_b":"International Institute for Strategic Studies","option_c":"Center for Security Studies (CSS) ETH Zürich","option_d":"Stockholm International Peace Research Institute","correct_answer":"C","explanation":"The Center for Security Studies (CSS) at ETH Zürich (Swiss Federal Institute of Technology) published analysis that India's demonstrated air superiority during Operation Sindoor forced Pakistan to seek a ceasefire. This independent assessment supported India's claims of operational success in the 3-day India-Pakistan standoff.","folder":"AP_HC","topic":"International_Current_Affairs"},

    # TWELVE-DAY WAR (ISRAEL-IRAN JUNE 2025) (22017-22026)
    {"id":22017,"question_text":"The 'Twelve-Day War' between Israel and Iran took place during which period in 2025?","option_a":"March 1-12, 2025","option_b":"June 13-24, 2025","option_c":"August 5-16, 2025","option_d":"October 7-18, 2025","correct_answer":"B","explanation":"The Twelve-Day War (Israel-Iran) lasted from June 13 to June 24, 2025. Israel launched a surprise attack on Iran's nuclear facilities. Iran retaliated with Operation True Promise III (550+ ballistic missiles + 1,000+ suicide drones). US bombed 3 Iranian nuclear sites on June 22. Ceasefire June 24 under US pressure.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22018,"question_text":"Which Israeli action on the day before the Twelve-Day War started was a significant trigger?","option_a":"Israel bombed Iranian oil refineries","option_b":"Israel struck Iran's consulate in Beirut","option_c":"IAEA declared Iran non-compliant with nuclear obligations (June 12, 2025)","option_d":"Israel blockaded Iranian shipping in Hormuz","correct_answer":"C","explanation":"On June 12, 2025 — the day before the Twelve-Day War — the IAEA Board of Governors adopted a resolution (sponsored by US, UK, France, Germany) declaring Iran non-compliant with its nuclear obligations. Israel used this as diplomatic cover to launch surprise attacks on Iranian nuclear sites on June 13, 2025.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22019,"question_text":"During the Twelve-Day War, which Iranian nuclear facilities were targeted by Israel?","option_a":"Arak, Qom, and Bushehr","option_b":"Natanz, Isfahan, and Fordow","option_c":"Tehran Research Reactor, Arak, and Khondab","option_d":"Bandar Abbas, Bushehr, and Chabahar","correct_answer":"B","explanation":"Israel targeted Iran's key nuclear facilities during the Twelve-Day War: Natanz (uranium enrichment centrifuges), Isfahan (UCF and conversion facility), and Fordow (underground enrichment facility). The US separately bombed 3 nuclear sites on June 22, 2025. After the war, Iran suspended IAEA cooperation.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22020,"question_text":"Iran's retaliation during the Twelve-Day War was called 'Operation True Promise III.' How many ballistic missiles and drones were launched?","option_a":"100 missiles + 200 drones","option_b":"300 missiles + 500 drones","option_c":"550+ ballistic missiles + 1,000+ suicide drones","option_d":"200 missiles + 400 drones","correct_answer":"C","explanation":"Iran's Operation True Promise III (Twelve-Day War, June 2025) involved 550+ ballistic missiles + 1,000+ suicide drones targeting Israel. Iran also struck Al Udeid Air Base in Qatar (US's largest Middle East air base). This was Iran's third major direct attack on Israel (after True Promise I: April 2024, True Promise II: October 2024).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22021,"question_text":"Iran struck which major US military base in Qatar during the Twelve-Day War?","option_a":"Camp Arifjan","option_b":"Al Udeid Air Base","option_c":"NSA Bahrain","option_d":"Camp As Sayliyah","correct_answer":"B","explanation":"Iran struck Al Udeid Air Base in Qatar during the Twelve-Day War — the US military's largest air base in the Middle East, hosting the US Air Forces Central Command (AFCENT). Qatar hosts both US military and has historically maintained ties with Hamas. Al Udeid hosted ~10,000 US personnel.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22022,"question_text":"Which senior IRGC (Islamic Revolutionary Guard Corps) commander was killed in the Twelve-Day War, 2025?","option_a":"Mohammad Bagheri only","option_b":"Hossein Salami only","option_c":"Hossein Salami (IRGC Commander), Amir Ali Hajizadeh (IRGC Aerospace), Mohammad Bagheri (Army Chief)","option_d":"Ali Larijani and Aziz Nasirzadeh","correct_answer":"C","explanation":"Twelve-Day War (June 2025) killed multiple top Iranian military commanders: Hossein Salami (IRGC Commander-in-Chief), Amir Ali Hajizadeh (IRGC Aerospace Force Commander), Mohammad Bagheri (Armed Forces Chief of Staff), and Gholam Ali Rashid. 10+ nuclear scientists also killed. Masoud Pezeshkian (Iranian President) was wounded.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22023,"question_text":"How many Mossad (Israeli intelligence) agents were reported arrested by Iran following the Twelve-Day War?","option_a":"50","option_b":"150","option_c":"700+, with 5 executed","option_d":"1,200","correct_answer":"C","explanation":"Iran arrested 700+ alleged Mossad agents following the Twelve-Day War, executing 5 of them. Iran also suspended IAEA cooperation after the war — the most severe action short of full withdrawal from the NPT (Non-Proliferation Treaty). Iran had been enriching uranium to 60% purity before the war.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22024,"question_text":"The Twelve-Day War ceasefire (June 24, 2025) was achieved under pressure from which country?","option_a":"Russia","option_b":"China","option_c":"United States","option_d":"Turkey","correct_answer":"C","explanation":"The Twelve-Day War ceasefire (June 24, 2025) was achieved under US pressure. The US had itself bombed 3 Iranian nuclear sites on June 22 — the most direct US military action against Iran's nuclear program ever. Trump left G7 Kananaskis early (June 15-17) citing the need to deal with the conflict.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22025,"question_text":"What did Iran do to IAEA (International Atomic Energy Agency) cooperation after the Twelve-Day War?","option_a":"Expelled IAEA inspectors and suspended cooperation","option_b":"Invited IAEA for full inspection","option_c":"Agreed to halt all enrichment permanently","option_d":"Transferred nuclear materials to Russia","correct_answer":"A","explanation":"Iran suspended IAEA cooperation after the Twelve-Day War — expelling inspectors and halting all monitoring. Iran had been enriching uranium to 60% purity (near weapons-grade of 90%). The IAEA's June 12 resolution declaring Iran non-compliant had been the trigger for the war. The IAEA is headquartered in Vienna, Austria.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22026,"question_text":"Iranian President Masoud Pezeshkian was injured (WIA) during the Twelve-Day War. He became President of Iran in which year?","option_a":"2021","option_b":"2023","option_c":"2024","option_d":"2025","correct_answer":"C","explanation":"Masoud Pezeshkian became President of Iran in July 2024, winning the presidential election after Ibrahim Raisi died in a helicopter crash in May 2024. Pezeshkian was a moderate reformist. He was wounded (WIA) during the Twelve-Day War (June 2025). Supreme Leader Ali Khamenei was subsequently killed in the 2026 Iran War (Feb 28, 2026).","folder":"AP_HC","topic":"International_Current_Affairs"},

    # 2026 IRAN WAR (22027-22040)
    {"id":22027,"question_text":"The 2026 Iran War started on which date, with US and Israel launching coordinated strikes?","option_a":"January 15, 2026","option_b":"February 28, 2026","option_c":"March 15, 2026","option_d":"April 1, 2026","correct_answer":"B","explanation":"The 2026 Iran War began on February 28, 2026 when the US and Israel launched coordinated strikes on Iran — notably DURING active nuclear negotiations. Iran's Supreme Leader Ali Khamenei was killed in these strikes, along with other senior officials including Ali Larijani and multiple military commanders.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22028,"question_text":"Who was killed when the 2026 Iran War began with US-Israel coordinated strikes on February 28, 2026?","option_a":"Iranian President Pezeshkian","option_b":"Supreme Leader Ali Khamenei","option_c":"IRGC Commander Hossein Salami","option_d":"Hezbollah leader Naim Qassem","correct_answer":"B","explanation":"Ali Khamenei — Iran's Supreme Leader since 1989 — was killed in the opening US-Israel strikes on February 28, 2026. Also killed: Ali Larijani (influential political figure), Abdolrahim Mousavi (Army Commander), Aziz Nasirzadeh (Air Force Commander), Alireza Tangsiri (IRGC Navy). Mojtaba Khamenei (son) was wounded.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22029,"question_text":"Iran's response to the 2026 War included closing which critical international waterway through which 20% of global oil passes?","option_a":"Suez Canal","option_b":"Bab el-Mandeb Strait","option_c":"Strait of Hormuz","option_d":"Strait of Malacca","correct_answer":"C","explanation":"Iran closed the Strait of Hormuz in response to the 2026 Iran War — through which ~20% of global oil (17-18 million barrels/day) passes. The Strait of Hormuz connects the Persian Gulf to the Gulf of Oman and is the world's most important oil chokepoint. Closure triggered global oil price surges.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22030,"question_text":"During the 2026 Iran War, Iran struck US military bases in multiple countries. Which of the following was NOT struck by Iran?","option_a":"Bahrain","option_b":"Jordan","option_c":"Egypt","option_d":"Kuwait","correct_answer":"C","explanation":"Iran struck US military bases in: Bahrain (NSA Bahrain/5th Fleet HQ), Jordan (Al-Tanf area), Kuwait (Camp Arifjan), Qatar (Al Udeid), Saudi Arabia (Prince Sultan Air Base), and UAE (Al Dhafra). Egypt was NOT struck — Egypt hosts Sinai peacekeepers and maintains separate diplomatic relations. UK's Akrotiri base in Cyprus was also struck by drone.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22031,"question_text":"The 2026 Lebanon War ran parallel to the Iran War. How many Hezbollah fighters were killed in the 2026 Lebanon War?","option_a":"100-200","option_b":"500-800","option_c":"1,000-1,900","option_d":"3,000-4,000","correct_answer":"C","explanation":"The 2026 Lebanon War (concurrent with 2026 Iran War) resulted in 1,000-1,900 Hezbollah fighters killed and 2,000+ total casualties. Hezbollah fired rockets at Israel from Lebanon. Israel struck Beirut again on May 7, 2026 — killing the then-current Hezbollah leader. Hezbollah SG Naim Qassem had taken over after Nasrallah's death in September 2024.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22032,"question_text":"Who mediated the April 8, 2026 conditional ceasefire between Iran and the US-Israel coalition?","option_a":"China","option_b":"Russia","option_c":"Turkey","option_d":"Pakistan","correct_answer":"D","explanation":"Pakistan mediated the conditional ceasefire on April 8, 2026 between Iran and the US-Israel coalition — a significant diplomatic role for Pakistan. This came after 40 days of the 2026 Iran War (started Feb 28, 2026). The ceasefire was 'conditional,' with tensions remaining. May 7, 2026: Israel struck Beirut, violating the spirit of the ceasefire.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22033,"question_text":"US casualties in the 2026 Iran War were:","option_a":"5 killed, 100 wounded","option_b":"15 killed, 538 wounded","option_c":"50 killed, 1,000 wounded","option_d":"100 killed, 2,000 wounded","correct_answer":"B","explanation":"US casualties in the 2026 Iran War: 15 soldiers killed, 538 wounded (as of ceasefire, April 8, 2026). Iran casualties (HRANA human rights group): 3,636 killed, 26,500 wounded; $270 billion to $1 trillion economic damage. Israel: 18 soldiers + 28 civilians killed; $50 billion economic damage.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22034,"question_text":"What was the scale of US military deployment during the 2026 Iran War — described as the largest Middle East buildup since 2003?","option_a":"1 aircraft carrier strike group","option_b":"2 aircraft carrier strike groups","option_c":"3 aircraft carrier strike groups","option_d":"Full Pacific Fleet deployment","correct_answer":"B","explanation":"US deployed 2 aircraft carrier strike groups for the 2026 Iran War — the largest Middle East military buildup since the 2003 Iraq invasion. US military leadership: Pete Hegseth (Defense Secretary), Michael Kurilla (CENTCOM Commander), Dan Caine (Joint Chiefs Chairman). US and Israel coordinated strikes starting February 28, 2026.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22035,"question_text":"Who was Israel's Defense Minister during the 2026 Iran War?","option_a":"Yoav Gallant","option_b":"Benny Gantz","option_c":"Israel Katz","option_d":"Avigdor Lieberman","correct_answer":"C","explanation":"Israel's key leaders during the 2026 Iran War: PM Benjamin Netanyahu, Defense Minister Israel Katz, IDF Chief Eyal Zamir. US Defense Secretary: Pete Hegseth (appointed by Trump). Iran's Revolutionary Guard was severely weakened after Twelve-Day War (June 2025) commanders killed.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22036,"question_text":"Ali Khamenei had been Iran's Supreme Leader since which year?","option_a":"1979","option_b":"1985","option_c":"1989","option_d":"1993","correct_answer":"C","explanation":"Ali Khamenei became Iran's Supreme Leader in 1989 following the death of Ayatollah Khomeini (the founder of Islamic Republic). Before becoming Supreme Leader, Khamenei was Iran's President (1981-1989). He held the Supreme Leader position for 37 years until killed in the 2026 Iran War (February 28, 2026).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22037,"question_text":"The 2026 Iran War caused Iran to close the Strait of Hormuz. What percentage of global LNG (Liquefied Natural Gas) also passes through the Strait?","option_a":"5%","option_b":"10%","option_c":"20%","option_d":"30%","correct_answer":"C","explanation":"The Strait of Hormuz carries ~20% of global oil AND approximately 20% of global LNG — including major exports from Qatar (world's top LNG exporter). Closure impacted global energy markets, driving oil prices above $100/barrel. India's Chabahar Port (in Iran) was also strategically affected.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22038,"question_text":"Iran's economic damage from the 2026 Iran War was estimated at:","option_a":"$10-50 billion","option_b":"$100-200 billion","option_c":"$270 billion to $1 trillion","option_d":"$5 trillion","correct_answer":"C","explanation":"Iran's economic damage from the 2026 Iran War: $270 billion to $1 trillion (wide range due to ongoing conflict and estimation difficulties). Includes: infrastructure destruction, Strait of Hormuz closure economic impact, sanctions, oil revenue loss. Israel's damage: $50 billion. US deployed 2 carrier strike groups in the largest Middle East buildup since 2003 Iraq invasion.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22039,"question_text":"US Secretary of Defense Pete Hegseth was appointed under which president, and when did he take office?","option_a":"Trump, January 20, 2025","option_b":"Biden, January 2024","option_c":"Trump, November 2024","option_d":"Harris, January 2025","correct_answer":"A","explanation":"Pete Hegseth was appointed US Secretary of Defense by President Donald Trump, taking office January 20, 2025 (Trump's inauguration day). Hegseth was a Fox News host and Army National Guard veteran before becoming Defense Secretary. He led US military decisions during Operation Sindoor (India-Pakistan), the Twelve-Day War, and the 2026 Iran War.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22040,"question_text":"Israel struck Beirut on May 7, 2026 — killing a Hezbollah leader. Who had become Hezbollah's Secretary-General after Nasrallah was killed in September 2024?","option_a":"Hashem Safieddine","option_b":"Naim Qassem","option_c":"Ibrahim Aqil","option_d":"Fuad Shukr","correct_answer":"B","explanation":"Naim Qassem became Hezbollah's Secretary-General after Hassan Nasrallah was killed in an Israeli airstrike on September 27, 2024. Qassem had been Hezbollah's Deputy Secretary-General for many years. He was killed in Israel's May 7, 2026 Beirut strike. The Hezbollah-Israel ceasefire of November 2024 broke down with the 2026 Lebanon War.","folder":"AP_HC","topic":"International_Current_Affairs"},

    # UKRAINE-RUSSIA WAR 2025-2026 (22041-22052)
    {"id":22041,"question_text":"In the Russia-Ukraine War, which country launched a historic surprise military incursion into Russia's Kursk Oblast in 2024, and what was its 2025 status?","option_a":"Ukraine incursed Kursk August 2024; Russian forces recaptured most by early 2025","option_b":"Russia incursed Ukraine's Sumy Oblast in 2024","option_c":"Belarus invaded Ukraine's Zhytomyr Oblast","option_d":"Ukraine launched missiles at Moscow in August 2024","correct_answer":"A","explanation":"Ukraine's surprise incursion into Russia's Kursk Oblast (August 2024) — first time since WWII that foreign troops held Russian sovereign territory. By early 2025, Russian and North Korean forces had recaptured most of Kursk Oblast. Ukraine used the Kursk gambit as leverage in peace negotiations.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22042,"question_text":"North Korea sent approximately 10,000-12,000 troops to support Russia in the Ukraine war. How were these troops deployed?","option_a":"Defensive positions in Russia's western border","option_b":"Direct combat in Kursk Oblast against Ukrainian forces","option_c":"Logistics and supply chain support only","option_d":"Intelligence gathering in Belarus","correct_answer":"B","explanation":"North Korea sent ~10,000-12,000 troops to Russia who were deployed in direct combat roles in Kursk Oblast against Ukrainian forces (2024-2025). North Korea also supplied artillery shells and missiles. Russia and DPRK signed a Comprehensive Strategic Partnership (mutual defense treaty) when Kim Jong-un visited Moscow and Putin visited Pyongyang.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22043,"question_text":"Trump announced a 3-day Russia-Ukraine ceasefire in May 2026. What prisoner exchange was included?","option_a":"100 prisoners each","option_b":"500 prisoners each","option_c":"1,000 prisoners each","option_d":"All POWs simultaneously","correct_answer":"C","explanation":"Trump's 3-day Russia-Ukraine ceasefire (May 9-11, 2026) included an exchange of 1,000 prisoners each side — a significant humanitarian element. Trump called it potentially 'the beginning of the end' of the war. US Secretary of State Rubio struck a somber tone, saying US mediation had not led to a 'fruitful outcome' and efforts had 'stagnated.'","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22044,"question_text":"Russia declared a unilateral ceasefire in Ukraine for May 8-9, 2026 to mark which occasion?","option_a":"Easter celebrations","option_b":"Russia's National Day","option_c":"World War II Victory Day","option_d":"Putin's birthday","correct_answer":"C","explanation":"Russia declared a unilateral ceasefire for May 8-9, 2026 for its annual WWII Victory Day commemorations. Ukraine declared its own truce for May 5-6, calling Russia's ceasefire 'not serious' (overlap only on May 8). Trump then brokered the 3-day joint ceasefire (May 9-11). The WWII Victory Day (May 9) is Russia's most important national holiday.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22045,"question_text":"According to ACLED 2025 data, which conflict was the world's deadliest in 2025 with almost 78,000 fatalities?","option_a":"Sudan Civil War","option_b":"Gaza conflict","option_c":"Ukraine War","option_d":"Myanmar civil war","correct_answer":"C","explanation":"Ukraine was the world's deadliest conflict in 2025 with almost 78,000 fatalities (ACLED data). Top 10 deadliest: Ukraine, Sudan, Israel-Palestine, Myanmar, Nigeria, Somalia, Syria, Mexico, Brazil, DRC. Russian indiscriminate targeting of Ukrainian civilian areas killed 2,000+ civilians in 2025.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22046,"question_text":"US-Ukraine-Russia trilateral talks were announced at WEF Davos 2026 to begin in which city?","option_a":"Geneva","option_b":"Istanbul","option_c":"Abu Dhabi","option_d":"Vienna","correct_answer":"C","explanation":"At WEF Davos 2026, Zelenskyy met Trump and announced US-Ukraine-Russia trilateral peace talks to begin in Abu Dhabi on January 23, 2026. Abu Dhabi (UAE) was chosen as a neutral location. The talks followed multiple failed ceasefire attempts. US Secretary of State Rubio acknowledged negotiations had 'stagnated.'","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22047,"question_text":"In the Russia-Ukraine conflict, Ukraine has used which NATO nation's F-16 fighter jets, delivered in 2024-2025?","option_a":"USA directly","option_b":"Poland and Czech Republic","option_c":"Netherlands and Denmark (transferred with US approval)","option_d":"Germany and France","correct_answer":"C","explanation":"Netherlands and Denmark transferred F-16 fighter jets to Ukraine (with US approval) in 2024-2025 — a major boost to Ukraine's air force. The F-16s required Ukrainian pilot training in Romania. Germany supplied Leopard 2 tanks; UK supplied Storm Shadow cruise missiles. Russia condemned F-16 deliveries as NATO escalation.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22048,"question_text":"Russia's war in Ukraine began on February 24, 2022. How many years had the conflict lasted by May 2026?","option_a":"2 years","option_b":"3 years","option_c":"4 years, 3 months","option_d":"5 years","correct_answer":"C","explanation":"Russia's full-scale invasion of Ukraine began February 24, 2022. By May 2026, the conflict had lasted over 4 years and 3 months. The conflict was preceded by Russia's annexation of Crimea (2014) and support for Donbas separatists. By 2025, it was the world's deadliest conflict with 78,000+ fatalities.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22049,"question_text":"NATO pledged €40 billion in defense aid to Ukraine in 2025 (at The Hague Summit). What controversial issue regarding Ukraine's NATO membership remained unresolved?","option_a":"Language requirements for Ukrainian military","option_b":"Ukraine's nuclear disarmament","option_c":"No NATO membership pathway, timeline, or invitation offered","option_d":"Ukraine's constitution amendment requirement","correct_answer":"C","explanation":"Despite €40 billion in aid, NATO's Hague Summit 2025 offered Ukraine NO membership invitation, NO timeline, NO significant upgrade in membership language — deeply disappointing Kyiv. NATO's position was that Ukrainian NATO membership must be considered after the war ends. Meanwhile, NATO's defense spending was raised to 5% GDP.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22050,"question_text":"The Gaza ceasefire 'Phase 1' was agreed on January 15, 2025. Who mediated this ceasefire?","option_a":"USA alone","option_b":"Qatar, Egypt, and USA","option_c":"UN and Arab League","option_d":"Turkey and Iran","correct_answer":"B","explanation":"The Gaza ceasefire Phase 1 (January 15, 2025) was mediated by Qatar, Egypt, and the USA — the same troika that mediated all Gaza ceasefire talks. Phase 1 involved a 42-day pause and hostage releases. The conflict had started on October 7, 2023 with Hamas's attack on Israel. By 2025, Gaza rebuilding faced immense challenges.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22051,"question_text":"Which country was described as having the 'world's worst humanitarian crisis' in terms of absolute numbers of displaced persons by mid-2025?","option_a":"Syria","option_b":"Ukraine","option_c":"Sudan","option_d":"Myanmar","correct_answer":"C","explanation":"Sudan's civil war (started April 2023: SAF vs RSF) caused the 'world's worst humanitarian crisis' by mid-2025 — 10 million internally displaced + 3 million fled to neighboring countries; 2/3 of Sudan's 50 million people needed assistance. RSF captured El Fasher (North Darfur capital) on October 27, 2025 after an 18-month siege.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22052,"question_text":"Sudan's civil war (2023-2025) is between the Sudanese Armed Forces (SAF) and which rebel group?","option_a":"SPLM/A-North","option_b":"Rapid Support Forces (RSF)","option_c":"Justice and Equality Movement (JEM)","option_d":"Sudan Liberation Army","correct_answer":"B","explanation":"Sudan's civil war: SAF (Sudanese Armed Forces) vs. RSF (Rapid Support Forces) — started April 2023. RSF was led by Mohamed Hamdan Dagalo ('Hemeti'). RSF captured El Fasher in October 2025. Sudan's conflict was rated the most likely to escalate in 2026 by International Crisis Group. Casualty estimates: 150,000+ killed.","folder":"AP_HC","topic":"International_Current_Affairs"},

    # GLOBAL GEOPOLITICS 2025-2026 (22053-22066)
    {"id":22053,"question_text":"Nicaragua's Maduro was captured by the United States on January 3, 2026. Who became acting president of Venezuela?","option_a":"María Corina Machado","option_b":"Rodríguez (acting president)","option_c":"Juan Guaidó","option_d":"Leopoldo López","correct_answer":"B","explanation":"According to reports, Nicolás Maduro of Venezuela was extracted to the US on January 3, 2026, after which Rodríguez became acting president of Venezuela. María Corina Machado, Venezuelan opposition leader, won the Nobel Peace Prize 2025 for her work promoting democratic rights and peaceful transition from dictatorship.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22054,"question_text":"Myanmar's civil war since 2021 has caused how many deaths and displacements by 2025?","option_a":"10,000 deaths, 500,000 displaced","option_b":"90,000+ deaths, 3+ million internally displaced and 1 million fled","option_c":"20,000 deaths, 1 million displaced","option_d":"150,000 deaths, 5 million displaced","correct_answer":"B","explanation":"Myanmar's civil war (since February 2021 coup): 90,000+ deaths, 3+ million internally displaced, 1 million fled abroad — by 2025. The conflict is described as 'under the radar' globally. ASEAN's Five-Point Consensus (2021) remains largely unimplemented. At ASEAN KL 2025, leaders reviewed Myanmar's crisis.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22055,"question_text":"Russia was the FIRST country to officially recognise the Taliban government of Afghanistan. When did this happen?","option_a":"January 2024","option_b":"July 3, 2025","option_c":"March 2025","option_d":"October 2025","correct_answer":"B","explanation":"Russia became the FIRST country to officially recognize the Taliban government of Afghanistan on July 3, 2025 — breaking a 3.5-year international consensus of non-recognition. Russia established formal diplomatic relations with the Taliban-led Islamic Emirate of Afghanistan. This was seen as Russia's strategy to expand influence in Central Asia.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22056,"question_text":"The Houthi group (Yemen) has been led by which figure, conducting attacks on Red Sea shipping since 2023?","option_a":"Ali Abdullah Saleh","option_b":"Mohammed al-Houthi","option_c":"Abdul-Malik al-Houthi","option_d":"Hassan al-Houthi","correct_answer":"C","explanation":"Abdul-Malik al-Houthi leads the Houthi movement (Ansar Allah) in Yemen and has been behind attacks on Red Sea commercial shipping since late 2023 — in solidarity with Gaza. US-UK launched Operation Poseidon Archer against Houthi targets in early 2025. Houthis disrupted 15-20% of global shipping through the Red Sea/Bab el-Mandeb Strait.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22057,"question_text":"The New START nuclear arms control treaty between USA and Russia expired in February 2026. What was Russia's decision regarding the treaty?","option_a":"Russia agreed to extend for 5 more years","option_b":"Russia suspended participation in 2023 and treaty lapsed","option_c":"Russia signed a replacement treaty with China","option_d":"Russia unilaterally withdrew in 2025","correct_answer":"B","explanation":"Russia suspended participation in the New START treaty in February 2023 (in response to US support for Ukraine). The treaty, which capped US and Russian deployed nuclear warheads at 1,550 each, lapsed in February 2026 when it expired — leaving no nuclear arms control framework between the two largest nuclear powers for the first time since 1972.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22058,"question_text":"'Operation Poseidon Archer' was conducted by which countries against Houthi targets in Yemen in 2025?","option_a":"USA and Israel","option_b":"USA and UK","option_c":"Saudi Arabia and UAE","option_d":"USA, UK, and France","correct_answer":"B","explanation":"Operation Poseidon Archer: US and UK conducted airstrikes against Houthi (Ansar Allah) military targets in Yemen in response to Houthi attacks on Red Sea commercial shipping. Houthis targeted ships claiming solidarity with Gaza. The Red Sea disruptions cost global shipping tens of billions in additional costs (rerouting via Cape of Good Hope).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22059,"question_text":"The IRGC (Islamic Revolutionary Guard Corps) is Iran's elite military force. Which component specifically manages Iran's missile and drone programs?","option_a":"IRGC Ground Forces","option_b":"IRGC Aerospace Force","option_c":"Quds Force","option_d":"IRGC Navy","correct_answer":"B","explanation":"IRGC Aerospace Force manages Iran's ballistic missile and drone programs — including the Shahed-136 suicide drones and Fateh/Zulfiqar ballistic missiles. IRGC Aerospace Force Commander Amir Ali Hajizadeh was killed in the Twelve-Day War (June 2025). Quds Force (external operations) is a separate IRGC branch. IRGC is designated a terrorist organization by USA.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22060,"question_text":"Which of the following is the correct IRGC component that conducts Iran's foreign proxy operations?","option_a":"IRGC Aerospace Force","option_b":"IRGC Ground Forces","option_c":"IRGC Quds Force","option_d":"IRGC Navy","correct_answer":"C","explanation":"IRGC Quds Force conducts Iran's external operations — supporting proxies including Hezbollah (Lebanon), Hamas (Gaza), Houthis (Yemen), and PMF (Iraq). Qasem Soleimani, legendary Quds Force commander, was killed by US drone strike on January 3, 2020 at Baghdad airport. His successor, Esmail Qaani, became Quds Force commander.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22061,"question_text":"Which country in the Middle East hosts the largest US air base (Al Udeid) that was struck by Iran during the 2026 Iran War?","option_a":"Bahrain","option_b":"Saudi Arabia","option_c":"Qatar","option_d":"Kuwait","correct_answer":"C","explanation":"Al Udeid Air Base — the US's largest Middle East air base — is in Qatar, hosting ~10,000 US personnel and the US Air Forces Central Command (AFCENT). Qatar also hosts the HQ of Hamas political bureau. Iran struck Al Udeid during both the Twelve-Day War (June 2025) and the 2026 Iran War. Qatar also mediated the Gaza ceasefire.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22062,"question_text":"The 'Axis of Resistance' — Iran's network of regional proxies — includes which of the following groups?","option_a":"Hezbollah, Hamas, Houthis, and PMF (Iraqi militias)","option_b":"Al-Qaeda, ISIS, Taliban, and Hezbollah","option_c":"Hamas, PLO, Fatah, and PA","option_d":"Al-Shabaab, Boko Haram, and Hezbollah","correct_answer":"A","explanation":"Iran's 'Axis of Resistance': Hezbollah (Lebanon), Hamas (Gaza), Houthis/Ansar Allah (Yemen), and PMF (Popular Mobilization Forces) in Iraq. These groups receive funding, weapons, and training from Iran's IRGC Quds Force. The 2026 Iran War significantly degraded the Axis of Resistance as Iran's own military was severely weakened.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22063,"question_text":"Iran's Natanz nuclear facility is located in which Iranian province?","option_a":"Tehran Province","option_b":"Bushehr Province","option_c":"Isfahan Province","option_d":"Khuzestan Province","correct_answer":"C","explanation":"Natanz uranium enrichment facility is in Isfahan Province, Iran — about 250 km south of Tehran. It is Iran's main uranium enrichment site with thousands of centrifuges. Isfahan also hosts the UCF (Uranium Conversion Facility). Both Natanz and Isfahan were targeted by Israel in the Twelve-Day War (June 2025). Fordow is in Qom Province.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22064,"question_text":"India's strategic interest in the 2026 Iran War context involves which Iranian port under India's development?","option_a":"Bandar Abbas","option_b":"Chabahar Port","option_c":"Kish Island","option_d":"Bushehr Port","correct_answer":"B","explanation":"Chabahar Port (in southeastern Iran, on the Gulf of Oman) is India's strategic interest — India has invested $500M+ in developing it. Chabahar gives India access to Afghanistan and Central Asia bypassing Pakistan. During the 2026 Iran War, India maintained its neutral stance partly to protect the Chabahar strategic investment. EAM Jaishankar met Iranian FM Araghchi on May 15, 2026.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22065,"question_text":"The Samson Option refers to Israel's:","option_a":"Conventional military doctrine of preemptive strikes","option_b":"Massive nuclear retaliation deterrence strategy","option_c":"Intelligence infiltration of enemy states","option_d":"Iron Dome missile defense protocol","correct_answer":"B","explanation":"The Samson Option is Israel's undeclared nuclear deterrence strategy — the threat of massive nuclear retaliation if Israel's existence is threatened (named after the biblical Samson who destroyed himself and his enemies). Israel maintains a policy of 'nuclear ambiguity' (neither confirming nor denying nuclear weapons). SIPRI estimates Israel has ~90 nuclear warheads.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22066,"question_text":"Which country has the 'Iron Dome,' 'Arrow,' and 'David's Sling' missile defense systems — all activated during the Twelve-Day War 2025?","option_a":"Saudi Arabia","option_b":"UAE","option_c":"Israel","option_d":"USA","correct_answer":"C","explanation":"Israel operates a multi-layer missile defense: Iron Dome (short-range, 4-70 km rockets/mortars), David's Sling (medium-range, 40-300 km), and Arrow 2/3 (long-range, 100-2,400 km, ballistic missiles). During the Twelve-Day War (June 2025), all three layers were activated against Iran's Operation True Promise III (550+ ballistic missiles + 1,000+ drones). US also provided Patriot interceptors.","folder":"AP_HC","topic":"International_Current_Affairs"},

    # HIGHER ORDER / MIXED (22067-22080)
    {"id":22067,"question_text":"Which statement about India-Pakistan 2025 conflict is CORRECT?","option_a":"India attacked Pakistan's regular army bases","option_b":"Operation Sindoor targeted only JeM and LeT terrorist infrastructure","option_c":"The ceasefire was mediated by China","option_d":"Pakistan launched its operation before India did","correct_answer":"B","explanation":"Operation Sindoor (May 7, 2025) specifically targeted terrorist infrastructure of JeM and LeT — NOT Pakistani military or civilian targets. India emphasized this distinction. Pakistan's Operation Bunyan-um-Marsoos was a retaliation AFTER India's Sindoor. The ceasefire was reached on May 10, 2025, with US Secretary of State Rubio involved diplomatically.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22068,"question_text":"Which of the following chronological sequences of Iran-related conflicts is CORRECT?","option_a":"True Promise I → Twelve-Day War → True Promise III → 2026 Iran War","option_b":"True Promise I (Apr 2024) → True Promise II (Oct 2024) → Twelve-Day War (Jun 2025) → 2026 Iran War (Feb 2026)","option_c":"Twelve-Day War → True Promise III → True Promise I → 2026 Iran War","option_d":"True Promise I → True Promise III → Twelve-Day War → 2026 Iran War","correct_answer":"B","explanation":"Correct sequence: Operation True Promise I (Iran's first direct attack on Israel, April 13-14, 2024) → Operation True Promise II (Iran's second attack, October 2024) → Twelve-Day War / Operation True Promise III (June 13-24, 2025) → 2026 Iran War (February 28, 2026 - ongoing with Pakistan-mediated ceasefire April 8, 2026).","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22069,"question_text":"The JCPOA (Joint Comprehensive Plan of Action) — Iran nuclear deal — was signed in 2015. When did the USA withdraw?","option_a":"2016 under Obama","option_b":"2018 under Trump","option_c":"2020 under Trump","option_d":"2022 under Biden","correct_answer":"B","explanation":"The JCPOA (Iran nuclear deal, P5+1 + EU + Iran) was signed in 2015 under Obama. Trump withdrew the USA in 2018 ('maximum pressure' policy). Iran then gradually exceeded JCPOA limits — enriching to 60% uranium purity (near weapons-grade of 90%). Biden tried but failed to revive JCPOA. JCPOA collapse led to escalation culminating in the Twelve-Day War (2025) and 2026 Iran War.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22070,"question_text":"Which Swiss think tank assessed India's air superiority in Operation Sindoor forced Pakistan to seek ceasefire — and which institution tracks global nuclear arsenals?","option_a":"CSS ETH Zürich (air superiority); SIPRI (nuclear arsenals)","option_b":"IISS (air superiority); SIPRI (nuclear arsenals)","option_c":"Chatham House (air superiority); IAEA (nuclear arsenals)","option_d":"Rand Corporation (air superiority); UN (nuclear arsenals)","correct_answer":"A","explanation":"CSS ETH Zürich (Center for Security Studies at Swiss Federal Institute of Technology) assessed India's air superiority in Operation Sindoor. SIPRI (Stockholm International Peace Research Institute) tracks global nuclear arsenals — as of 2025: Russia 5,459 warheads, USA 5,177, China ~500, Pakistan ~170, India ~172, Israel ~90, North Korea ~50.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22071,"question_text":"The 2026 Iran War (started Feb 28, 2026) was described as starting DURING which process?","option_a":"Iran-Saudi normalization talks","option_b":"Iran-US nuclear negotiations","option_c":"IAEA inspection visit","option_d":"UN Security Council deliberations","correct_answer":"B","explanation":"The 2026 Iran War notably began on February 28, 2026 DURING active Iran-US nuclear negotiations — making the timing highly controversial. Critics argued the attack violated diplomatic norms. The US and Israel launched coordinated strikes killing Supreme Leader Khamenei and multiple senior officials. Iran accused the US of 'bad faith' in negotiations.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22072,"question_text":"India's stance during the Iran-US-Israel conflict was characterized as:","option_a":"Strong support for USA and Israel","option_b":"Support for Iran","option_c":"Neutral — engaging diplomatically with both sides","option_d":"Complete non-engagement","correct_answer":"C","explanation":"India maintained a neutral stance during the Iran-US-Israel conflict — using diplomacy to engage both sides. EAM Jaishankar met Iranian FM Araghchi in New Delhi (May 15, 2026) while India also maintained defense cooperation with Israel. India's interests: Chabahar Port (Iran), 8 million Indian diaspora in Gulf, energy imports. India abstained from UN votes on the conflict.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22073,"question_text":"Which is the CORRECT match of military operation → date?","option_a":"Operation Sindoor → April 22, 2025","option_b":"Twelve-Day War → June 13-24, 2025","option_c":"2026 Iran War began → March 15, 2026","option_d":"Gaza Phase 1 ceasefire → March 2025","correct_answer":"B","explanation":"Correct: Twelve-Day War → June 13-24, 2025 ✓. Incorrect: Operation Sindoor → May 7, 2025 (not April 22 which was the Pahalgam attack), 2026 Iran War → February 28, 2026 (not March), Gaza Phase 1 ceasefire → January 15, 2025 (not March). Key dates to remember for AP HC exam.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22074,"question_text":"Pakistan mediated the April 8, 2026 Iran-US ceasefire. What motivated Pakistan to take this role despite being under nuclear tension with India?","option_a":"Pakistan is a NATO ally","option_b":"Pakistan has historically mediated all Middle East conflicts","option_c":"Pakistan shares borders with Iran and has common Muslim identity plus interest in regional stability","option_d":"China directed Pakistan to mediate","correct_answer":"C","explanation":"Pakistan mediated the Iran-US ceasefire partly because: Pakistan shares a 900 km border with Iran, has common Muslim identity and historical ties, and benefits from regional stability (energy imports, trade). Pakistan also sought to project global diplomatic relevance after the India-Pakistan standoff of May 2025 weakened its international image.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22075,"question_text":"Sudan's civil war (SAF vs RSF): Which major city fell to the RSF on October 27, 2025, after an 18-month siege?","option_a":"Khartoum","option_b":"Omdurman","option_c":"El Fasher","option_d":"Port Sudan","correct_answer":"C","explanation":"El Fasher — capital of North Darfur state and the last major city under government (SAF) control in Darfur — fell to the RSF (Rapid Support Forces) on October 27, 2025, after an 18-month siege. This was a major RSF victory, extending their control over most of Darfur. ICG rated Sudan as the most likely conflict to escalate in 2026.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22076,"question_text":"The Ukraine war saw Trump broker a 3-day ceasefire (May 9-11, 2026). US Secretary of State Rubio described the peace process as having:","option_a":"Made significant progress with a permanent deal imminent","option_b":"Stagnated — US mediation has not led to a fruitful outcome","option_c":"Successfully achieved permanent ceasefire terms","option_d":"Resulted in China joining as co-mediator","correct_answer":"B","explanation":"US Secretary of State Marco Rubio said US mediation efforts on Ukraine have 'stagnated' and have not led to a 'fruitful outcome.' This contrasted with Trump's optimism ('the beginning of the end'). Putin suggested the war was 'coming to an end' (May 2026). The Institute for the Study of War (ISW) noted that ceasefires without enforcement mechanisms are unlikely to hold.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22077,"question_text":"Russia officially recognized the Taliban government in Afghanistan on July 3, 2025 — becoming the first country to do so. What was Russia's strategic motivation?","option_a":"Expanding military bases in Afghanistan","option_b":"Countering US influence and expanding Russian influence in Central Asia","option_c":"Trade in Afghan lithium resources","option_d":"Russian Orthodox Church expansion in Afghanistan","correct_answer":"B","explanation":"Russia recognized the Taliban (July 3, 2025) primarily to expand Russian influence in Central Asia and counter US interests. Russia sees Afghanistan as key to Central Asian geopolitics. Russia also wanted to prevent Afghanistan from becoming a safe haven for anti-Russian groups, and sought economic benefits including trade routes and energy projects.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22078,"question_text":"Israel's PM during the Twelve-Day War (2025) and 2026 Iran War was:","option_a":"Naftali Bennett","option_b":"Yair Lapid","option_c":"Benny Gantz","option_d":"Benjamin Netanyahu","correct_answer":"D","explanation":"Benjamin Netanyahu was Israel's PM during both the Twelve-Day War (June 2025) and the 2026 Iran War. Israel's key leaders: Netanyahu (PM), Israel Katz (Defense Minister), Eyal Zamir (IDF Chief of Staff). Netanyahu had been indicted by ICC in November 2024 for alleged war crimes in Gaza. He remained in office despite legal challenges.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22079,"question_text":"The CENTCOM (US Central Command) commander during the 2026 Iran War was:","option_a":"General Kenneth McKenzie","option_b":"General Lloyd Austin","option_c":"General Michael Kurilla","option_d":"General Mark Milley","correct_answer":"C","explanation":"General Michael Kurilla commanded CENTCOM (US Central Command — responsible for Middle East, Central Asia, South Asia) during the 2026 Iran War. US chain of command: Pete Hegseth (Defense Secretary) → Dan Caine (Joint Chiefs Chairman) → Michael Kurilla (CENTCOM). CENTCOM HQ: Tampa, Florida with forward HQ at Al Udeid, Qatar.","folder":"AP_HC","topic":"International_Current_Affairs"},
    {"id":22080,"question_text":"The Houthi attacks on Red Sea shipping (2023-2025) primarily targeted ships going through which waterway, disrupting global trade? [2025-2026 Rewrite v2]","option_a":"Suez Canal","option_b":"Red Sea and Bab el-Mandeb Strait","option_c":"Persian Gulf","option_d":"Gulf of Aden only","correct_answer":"B","explanation":"Houthis targeted commercial shipping in the Red Sea and Bab el-Mandeb Strait — between Yemen (Africa-Arabian Peninsula) — disrupting 12-15% of global trade. Ships rerouted around Africa's Cape of Good Hope, adding 10-14 days and $1M+ per voyage. The Red Sea connects Suez Canal to Indian Ocean. Operation Poseidon Archer (US-UK) struck Houthi targets in Yemen in response.","folder":"AP_HC","topic":"International_Current_Affairs"},
]


def seed():
    if USE_POSTGRES:
        import psycopg2
        conn = psycopg2.connect(DATABASE_URL)
        conn.autocommit = False
        cur = conn.cursor()
        ph = "%s"
        delete_sql = "DELETE FROM questions WHERE id >= %s AND id <= %s"
        insert_sql = """
            INSERT INTO questions
              (id, question_text, option_a, option_b, option_c, option_d,
               correct_answer, explanation, folder, topic)
            VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
            ON CONFLICT (id) DO NOTHING
        """
    else:
        conn = sqlite3.connect(
            os.path.join(os.path.dirname(__file__), "database.db")
        )
        cur = conn.cursor()
        ph = "?"
        delete_sql = "DELETE FROM questions WHERE id >= ? AND id <= ?"
        insert_sql = """
            INSERT OR IGNORE INTO questions
              (id, question_text, option_a, option_b, option_c, option_d,
               correct_answer, explanation, folder, topic)
            VALUES (?,?,?,?,?,?,?,?,?,?)
        """

    # Force-refresh: delete stale 2023/2024 data
    cur.execute(delete_sql, (22001, 22080))

    for q in CONFLICTS_MCQS:
        cur.execute(insert_sql, (
            q["id"], q["question_text"],
            q["option_a"], q["option_b"], q["option_c"], q["option_d"],
            q["correct_answer"], q["explanation"],
            q["folder"], q["topic"],
        ))

    conn.commit()
    conn.close()
    print(f"[seed_conflicts_mcq] {len(CONFLICTS_MCQS)} Conflicts 2025-2026 MCQs seeded (IDs 22001-22080).")


if __name__ == "__main__":
    seed()
