import sqlite3, os

SOURCE = 'Science_Set17_Plants_2'
DB = os.path.join(os.path.dirname(__file__), 'database.db')

questions = [
    (
        'The substance that can be synthesized by plants and not by animals is\nతెలుగు: మొక్కల ద్వారా మాత్రమే సంశ్లేషణ చేయబడి, జంతువులచే చేయబడని పదార్థం',
        'Fats / కొవ్వులు',
        'Proteins / ప్రోటీన్లు',
        'Urea / యూరియా',
        'Cellulose / సెల్యులోజ్ (Cellulose — only plants)',
        'D',
        'M',
        '',
        1
    ),
    (
        'To what phylum does a blood-sucking leech belong\nతెలుగు: రక్తాన్ని పీల్చే జలగ ఏ వర్గానికి చెందుతుంది',
        'Aschelminthes / ఆస్కెల్మింథిస్',
        'Cnidaria / నిడేరియా',
        'Platyhelminthes / ప్లాటీహెల్మింథిస్',
        'Annelida / అనెలిడా (Annelida — segmented worms)',
        'D',
        'M',
        '',
        2
    ),
    (
        'Translocation of food materials in plants takes place through\nతెలుగు: మొక్కలలో ఆహార పదార్థాల రవాణా దేని ద్వారా జరుగుతుంది',
        'Cortex / వల్కలం',
        'Xylem / దారువు (water transport)',
        'Epidermis / బాహ్యచర్మం',
        'Phloem / పోషక కణజాలం (Phloem — food translocation)',
        'D',
        'M',
        '',
        3
    ),
    (
        'A seed can germinate in the absence of\nతెలుగు: కింది వాటిలో ఏది లేకపోయినా విత్తనం మొలకెత్తగలదు',
        'Suitable moisture / తగినంత తేమ',
        'Suitable temperature / తగిన ఉష్ణోగ్రత',
        'Adequate light / తగినంత కాంతి (light not required for most seeds)',
        'Supply of oxygen / ఆక్సిజన్ సరఫరా',
        'C',
        'M',
        '',
        4
    ),
    (
        'Under the electron microscope, which cell organelle is visible as either clusters or single small dots floating freely in the cytoplasm\nతెలుగు: ఎలక్ట్రాన్ మైక్రోస్కోప్ కింద కణద్రవ్యంలో స్వేచ్ఛగా తేలియాడే చిన్న చుక్కల సముదాయంగా కనిపించే కణాంగం',
        'Golgi apparatus / గొల్గీ సంక్లిష్టం',
        'Ribosomes / రైబోజోములు (Ribosomes — protein synthesis sites)',
        'Vesicles / వెసికిల్స్',
        'Peroxisomes / పెరాక్సిజోములు',
        'B',
        'M',
        '',
        5
    ),
    (
        'Under all atmospheric conditions, the maximum capacity of resistance will be shown by\nతెలుగు: అన్ని వాతావరణ పరిస్థితులలో గరిష్ట ప్రతిఘటన సామర్థ్యం దేనికి ఉంటుంది',
        'Leaf / ఆకు',
        'Flower / పువ్వు',
        'Seed / విత్తనం (Seed — dormant + protective seed coat)',
        'Fruit / పండు',
        'C',
        'M',
        '',
        6
    ),
    (
        'Fruit trees are generally propagated by\nతెలుగు: పండ్ల చెట్లను సాధారణంగా ఏ పద్ధతి ద్వారా వ్యాప్తి చేస్తారు',
        'Cutting / కటింగ్',
        'Grafting / అంటుకట్టడం (Grafting — preserves traits)',
        'Budding / మొగ్గ తొడగడం',
        'Gamete formation / సంయోగబీజ ఏర్పాటు',
        'B',
        'M',
        '',
        7
    ),
    (
        'Natural rubber is a plant product chemically known as\nతెలుగు: సహజ రబ్బరును రసాయనికంగా ఏమని పిలుస్తారు',
        'Resin / రెసిన్',
        'Gum / గమ్ (జిగురు)',
        'Latex / లేటెక్స్ (Latex — milky sap of Hevea)',
        'Mucilage / మ్యూసిలేజ్',
        'C',
        'M',
        '',
        8
    ),
    (
        'Which of the following colors is not absorbed by chlorophyll\nతెలుగు: కింది ఏ రంగు కాంతిని క్లోరోఫిల్ గ్రహించదు',
        'Red / ఎరుపు',
        'Yellow / పసుపు',
        'Green / ఆకుపచ్చ (Green — reflected, not absorbed)',
        'Blue / నీలం',
        'C',
        'M',
        '',
        9
    ),
    (
        'A great deal of emphasis is laid on the cultivation of soybean nowadays because\nతెలుగు: ఈ రోజుల్లో సోయాబీన్ సాగుకు ఎక్కువ ప్రాధాన్యత ఇస్తున్నారు, ఎందుకంటే',
        'It is rich in vitamins / విటమిన్లు సమృద్ధం',
        'It is cheap and easier to cook / చౌక + వండడం సులభం',
        'It is a source of high-quality protein / అధిక-నాణ్యత ప్రోటీన్‌కు మూలం (40% protein)',
        'It can be used as a staple food / ప్రధాన ఆహారంగా ఉపయోగించవచ్చు',
        'C',
        'M',
        '',
        10
    ),
    (
        'The tree that has become the centre of controversy (heavy water-uptake) is\nతెలుగు: భూగర్భ జలాలను బాగా పీల్చుకోవడం వలన వివాదానికి కేంద్ర బిందువు అయిన చెట్టు',
        'Bamboo / వెదురు',
        'Soybean / సోయాబీన్',
        'Coconut palm / కొబ్బరి చెట్టు',
        'Eucalyptus / యూకలిప్టస్ (Eucalyptus — drains groundwater)',
        'D',
        'M',
        '',
        11
    ),
    (
        'Regarding the carrot, it is true to say that\nతెలుగు: క్యారెట్‌కు సంబంధించి ఏది చెప్పడం నిజం',
        'Main root is modified for food storage / ప్రధాన వేరు ఆహార నిల్వ కోసం రూపాంతరం (taproot)',
        'Main stem is modified for food storage / ప్రధాన కాండం రూపాంతరం',
        'Stem and root store food / రెండూ నిల్వ చేస్తాయి',
        'Root hairs are modified to hold soil / మూలకేశాలు రూపాంతరం',
        'A',
        'M',
        '',
        12
    ),
    (
        'Plants bearing flowers are known as\nతెలుగు: పువ్వులు పూసే మొక్కలను ఏమంటారు',
        'Phanerogams / ఫానెరోగమ్స్ (Phanerogams — flowering plants)',
        'Gymnosperms / జిమ్నోస్పెర్మ్స్',
        'Cryptogams / క్రిప్టోగమ్స్',
        'Bryophytes / బ్రయోఫైట్స్',
        'A',
        'M',
        '',
        13
    ),
    (
        'A fruit formed without fertilization is known as\nతెలుగు: ఫలదీకరణం జరగకుండానే ఏర్పడే పండును ఏమంటారు',
        'Amitosis / అమిటోసిస్',
        'Parthenogenesis / పార్థినోజెనిసిస్ (animal egg dev w/o fertiln)',
        'Oogenesis / ఓజెనిసిస్',
        'Parthenocarpy / పార్థినోకార్పి (Parthenocarpy — seedless fruit)',
        'D',
        'M',
        '',
        14
    ),
    (
        'Cross-pollination — deposition of pollen on the stigma of another flower — is\nతెలుగు: పరాగరేణువులను వేరొక పువ్వు కీలాగ్రంపై నిక్షేపించే ప్రక్రియ',
        'Autogamy / ఆటోగామి (self)',
        'Allogamy / అల్లోగామి (Allogamy — cross-pollination)',
        'Cleistogamy / క్లైస్టోగామి (closed flower)',
        'Chasmogamy / ఛాస్మోగామి (open flower)',
        'B',
        'M',
        '',
        15
    ),
    (
        'All the following are constituents of chlorophyll, except\nతెలుగు: కింది వాటిలో క్లోరోఫిల్‌లో ఒక భాగం కానిది ఏది',
        'Carbon / కార్బన్',
        'Hydrogen / హైడ్రోజన్',
        'Calcium / కాల్షియం (Calcium — NOT in chlorophyll)',
        'Magnesium / మెగ్నీషియం (central metal)',
        'C',
        'M',
        '',
        16
    ),
    (
        'From which tree is quinine obtained\nతెలుగు: క్వినైన్ ఏ చెట్టు నుండి పొందబడుతుంది',
        'Eucalyptus / యూకలిప్టస్',
        'Rauwolfia Serpentina / రావుల్ఫియా (సర్పగంధ — reserpine)',
        'Walnut / వాల్నట్',
        'Cinchona / సింకోనా (Cinchona — quinine from bark)',
        'D',
        'M',
        '',
        17
    ),
    (
        'Correct sequence of crop rotation to increase soil fertility\nతెలుగు: నేల సారాన్ని పెంచే ఉద్దేశ్యంతో పంట మార్పిడి సరైన క్రమం',
        'Potato, Wheat, Pea, Barley',
        'Wheat, Potato, Barley, Pea',
        'Pea, Barley, Wheat, Potato (Pea = legume first to fix N)',
        'Barley, Pea, Wheat, Potato',
        'C',
        'M',
        'Best to start with legume (pea) to fix nitrogen, then heavy feeders.',
        18
    ),
    (
        'In agriculture, best fruit quality is maintained and propagated by\nతెలుగు: పండ్ల ఉత్తమ నాణ్యతను నిర్వహించి పెంచే పద్ధతి',
        'Chemical treatment of seeds / విత్తన రసాయన చికిత్స',
        'Vegetative methods / శాఖీయ పద్ధతులు (Vegetative — preserves traits)',
        'Hybridization and selection / హైబ్రిడైజేషన్',
        'Seed protection and selection / విత్తన రక్షణ',
        'B',
        'M',
        '',
        19
    ),
    (
        'Which fruit is given by a herb (non-woody plant)\nతెలుగు: మూలిక (కాండం కలప కానిది) ద్వారా లభించే పండు ఏది',
        'Mango / మామిడి',
        'Banana / అరటి (Banana — pseudostem; world\'s largest herb)',
        'Apple / ఆపిల్',
        'Jack-fruit / పనస',
        'B',
        'M',
        '',
        20
    ),
    (
        'Plant hormone that induces cell division is\nతెలుగు: కణ విభజనను ప్రేరేపించే మొక్కల హార్మోన్',
        'Auxins / ఆక్సిన్లు (cell elongation)',
        'Gibberellins / గిబ్బరెల్లిన్లు',
        'Dormins / డార్మిన్లు',
        'Kinins / కైనిన్లు (Kinins/Cytokinins — cell division)',
        'D',
        'M',
        '',
        21
    ),
    (
        'It will not be of any advantage to produce seedless fruits in (per source key)\nతెలుగు: విత్తనం లేకుండా ఉత్పత్తి చేయడం వల్ల పెద్దగా ప్రయోజనం ఉండని పండు (కీ ప్రకారం)',
        'Oranges / నారింజ',
        'Watermelons / పుచ్చకాయ',
        'Grapes / ద్రాక్ష',
        'Mangoes / మామిడి (Mangoes — per source key)',
        'D',
        'M',
        'Per source key. Mango pulp is firmly attached to large stone seed; seedless cultivation difficult and not commercially advantageous.',
        22
    ),
    (
        'Chlorophyll is a chelate compound; the central metal is\nతెలుగు: క్లోరోఫిల్ కీలేట్ సమ్మేళనంలో కేంద్ర లోహం',
        'Calcium / కాల్షియం',
        'Magnesium / మెగ్నీషియం (Magnesium — central Mg ion)',
        'Iron / ఇనుము (haemoglobin)',
        'Copper / రాగి (haemocyanin)',
        'B',
        'M',
        '',
        23
    ),
    (
        'Potato is an underground modified stem referred to as\nతెలుగు: బంగాళదుంప భూగర్భ రూపాంతర కాండాన్ని ఏమని పిలుస్తారు',
        'Rhizomes / రైజోములు (ginger, turmeric)',
        'Bulbs / బల్బులు (onion)',
        'Tubers / దుంపలు (Tubers — swollen underground stem)',
        'Corms / కార్మ్స్ (colocasia)',
        'C',
        'M',
        '',
        24
    ),
    (
        'The tree which does not have the potential to absorb sulfur dioxide from the atmosphere is\nతెలుగు: SO2ను గ్రహించే సామర్థ్యం లేని చెట్టు',
        'Nerium / నేరియం / గన్నేరు (Nerium — does NOT absorb SO2)',
        'Ilex / ఐలెక్స్',
        'Jhar / ఝార్',
        'Neem / వేప',
        'A',
        'M',
        '',
        25
    ),
    (
        'Flower colors are due to\nతెలుగు: పువ్వులకు రంగులు దేనివల్ల వస్తాయి',
        'Chlorophyll / క్లోరోఫిల్',
        'Melanin / మెలనిన్ (animal pigment)',
        'Phytochromes / ఫైటోక్రోములు (light receptor)',
        'Anthocyanins / ఆంథోసైనిన్లు (Anthocyanins — flower pigments)',
        'D',
        'M',
        '',
        26
    ),
    (
        'Rod-shaped bacteria are called\nతెలుగు: కడ్డీ ఆకారంలో ఉండే బ్యాక్టీరియాను ఏమంటారు',
        'Bacillus / బాసిల్లస్ (Bacillus — rod)',
        'Spirillum / స్పిరిల్లమ్ (spiral)',
        'Coccus / కాకస్ (sphere)',
        'Coma / కోమా (కామా / vibrio)',
        'A',
        'M',
        '',
        27
    ),
    (
        'Which of the following is not required for seed germination\nతెలుగు: విత్తనం మొలకెత్తడానికి కింది వాటిలో ఏది అవసరం లేదు',
        'Water / నీరు',
        'Air / గాలి (oxygen)',
        'Sunlight / సూర్యరశ్మి (Sunlight — most seeds germinate in dark soil)',
        'Suitable temperature / తగిన ఉష్ణోగ్రత',
        'C',
        'M',
        '',
        28
    ),
    (
        'Which components of light are absorbed by chlorophyll\nతెలుగు: క్లోరోఫిల్ ద్వారా కాంతిలోని ఏ రంగులు ఎక్కువగా గ్రహించబడతాయి',
        'Violet and red / వైలెట్ + ఎరుపు',
        'Indigo and orange / ఇండిగో + ఆరెంజ్',
        'Blue and red / నీలం + ఎరుపు (Blue + Red absorbed)',
        'Violet and yellow / వైలెట్ + పసుపు',
        'C',
        'M',
        '',
        29
    ),
    (
        'Ferns, horsetails and lycophytes belong to\nతెలుగు: ఫెర్న్‌లు, హార్స్‌టైల్స్, లైకోఫైట్‌లు ఏ సమూహానికి చెందుతాయి',
        'Bryophyta / బ్రయోఫైటా (mosses)',
        'Pteridophyta / టెరిడోఫైటా (Pteridophyta — first vascular plants)',
        'Algae / శైవలాలు',
        'Fungi / శిలీంధ్రాలు',
        'B',
        'M',
        '',
        30
    ),
    (
        'Oldest metazoan group still existing on the planet (Phylum Porifera)\nతెలుగు: పోరిఫెరా వర్గానికి చెందిన అత్యంత పురాతన మెటాజోవాన్',
        'Anemones / అనిమోన్స్ (Cnidaria)',
        'Sponges / స్పంజికలు (Sponges — Porifera; ~580 my old)',
        'Sycon / సైకాన్ (a sponge genus)',
        'Hydra / హైడ్రా (Cnidaria)',
        'B',
        'M',
        '',
        31
    ),
    (
        'Excess water absorbed by plants is liberated by\nతెలుగు: మొక్కలు గ్రహించిన అదనపు నీరు దేని ద్వారా బయటకు విడుదలవుతుంది',
        'Evaporation / బాష్పీభవనం',
        'Osmosis / ద్రవాభిసరణం',
        'Diffusion / వ్యాపనం',
        'Transpiration / భాష్పోత్సేకం (Transpiration — water vapour from stomata)',
        'D',
        'M',
        '',
        32
    ),
    (
        'Red, orange and yellow colours of leaves are due to\nతెలుగు: ఆకులలో ఎరుపు/ఆరెంజ్/పసుపు రంగులకు కారణం',
        'Aldehydes / ఆల్డిహైడ్స్',
        'Starch / పిండిపదార్థం',
        'Lignins / లిగ్నిన్స్',
        'Carotenoid / కెరోటినాయిడ్ (Carotenoids — autumn colours)',
        'D',
        'M',
        '',
        33
    ),
    (
        'Which is an insectivorous plant\nతెలుగు: కీటకాహార మొక్క ఏది',
        'Balanophora / బలానోఫోరా (parasitic)',
        'Rafflesia / రఫ్లీషియా (parasitic, biggest flower)',
        'Orobanche / ఒరోబాంచే (parasitic)',
        'Drosera / డ్రోసిరా (Drosera — sundew, traps insects)',
        'D',
        'M',
        '',
        34
    ),
    (
        '"Table sugar" is which type of sugar\nతెలుగు: టేబుల్ షుగర్ (పంచదార) ఏ రకమైన చక్కెర',
        'Fructose / ఫ్రక్టోజ్ (fruit sugar)',
        'Galactose / గెలాక్టోజ్ (milk)',
        'Glucose / గ్లూకోజ్',
        'Sucrose / సుక్రోజ్ (Sucrose — common table sugar = glu+fru)',
        'D',
        'M',
        '',
        35
    ),
    (
        'Plants which grow well only in light are known as\nతెలుగు: కాంతిలో మాత్రమే బాగా పెరిగే మొక్కలను ఏమంటారు',
        'Sciophilous / సియోఫిలస్ (shade plants)',
        'Xerophytes / జెరోఫైట్స్ (desert)',
        'Heliophytes / హీలియోఫైట్స్ (Heliophytes — sun-loving)',
        'Epiphytes / ఎపిఫైట్స్ (on other plants)',
        'C',
        'M',
        '',
        36
    ),
    (
        'Phototropic movement is controlled by\nతెలుగు: కాంతి అనువర్తన చలనం దేని ద్వారా నియంత్రించబడుతుంది',
        'Auxin / ఆక్సిన్ (Auxin — bends shoot toward light)',
        'Gibberellin / గిబ్బరెల్లిన్',
        'Cytokinin / సైటోకైనిన్',
        'Ethylene / ఇథిలీన్',
        'A',
        'M',
        '',
        37
    ),
    (
        'Maximum fixation of solar energy is done by\nతెలుగు: సౌర శక్తిని అత్యధికంగా స్థిరీకరించేది ఏవి',
        'Protozoa / ప్రోటోజోవా',
        'Bacteria / బ్యాక్టీరియా',
        'Fungi / శిలీంధ్రాలు',
        'Green Plants / ఆకుపచ్చ మొక్కలు (Green Plants — chlorophyll fixes CO2)',
        'D',
        'M',
        '',
        38
    ),
    (
        'Azolla increases soil fertility for which crop\nతెలుగు: అజొల్లా ఏ పంట సాగుకు నేల సారాన్ని పెంచుతుంది',
        'Maize / మొక్కజొన్న',
        'Wheat / గోధుమ',
        'Barley / బార్లీ',
        'Rice / వరి (Rice — Azolla-Anabaena fixes N in paddy water)',
        'D',
        'M',
        '',
        39
    ),
    (
        'Which light is least effective in photosynthesis\nతెలుగు: కిరణజన్య సంయోగక్రియలో ఏ కాంతి తక్కువ ప్రభావవంతం',
        'Blue light / నీలం కాంతి',
        'Green light / ఆకుపచ్చ కాంతి (Green — least effective; reflected)',
        'Red light / ఎరుపు కాంతి',
        'Sunlight / సూర్యకాంతి',
        'B',
        'M',
        '',
        40
    ),
    (
        'Plants which can survive in very less water are called\nతెలుగు: అతి తక్కువ నీటిలో మనుగడ సాగించగల మొక్కలను ఏమంటారు',
        'Halophytes / హాలోఫైట్స్ (salt soils)',
        'Xerophytes / జెరోఫైట్స్ (Xerophytes — drought-tolerant)',
        'Heliophytes / హీలియోఫైట్స్',
        'Saprophytes / సాప్రోఫైట్స్ (decomposers)',
        'B',
        'M',
        '',
        41
    ),
    (
        'Which part of the plant gives saffron\nతెలుగు: కుంకుమపువ్వు మొక్కలోని ఏ భాగం నుండి వస్తుంది',
        'Roots / వేర్లు',
        'Petals / ఆకర్షణ పత్రాలు',
        'Stem / కాండం',
        'Stigma / కీలాగ్రం (Stigma — saffron from Crocus sativus stigma)',
        'D',
        'M',
        '',
        42
    ),
    (
        'Cinnamon is obtained from which part of the plant\nతెలుగు: దాల్చిన చెక్క మొక్కలోని ఏ భాగం నుండి వస్తుంది',
        'Stem / కాండం',
        'Bark / బెరడు (Bark — Cinnamomum verum)',
        'Roots / వేర్లు',
        'Fruits / పండ్లు',
        'B',
        'M',
        '',
        43
    ),
    (
        'The male sex organ in a flower is\nతెలుగు: పువ్వులో ఉండే పురుష లైంగిక అవయవం',
        'Zoospores / జూస్పోర్స్',
        'Stamen / కేసరం (Stamen — anther + filament; produces pollen)',
        'Pistil / అండకోశం (female organ)',
        'Chlorophyceae / క్లోరోఫైసి (algae class)',
        'B',
        'M',
        '',
        44
    ),
    (
        'Carbohydrate is stored in the body (animal/human) as\nతెలుగు: శరీరంలో కార్బోహైడ్రేట్ ఏ రూపంలో నిల్వ చేయబడుతుంది',
        'Glucose / గ్లూకోజ్ (free, in blood)',
        'Starch / పిండిపదార్థం (in plants)',
        'Glycogen / గ్లైకోజెన్ (Glycogen — animal storage form)',
        'Sucrose / సుక్రోజ్',
        'C',
        'M',
        '',
        45
    ),
    (
        'Ripe grapes contain (per source key)\nతెలుగు: పండిన ద్రాక్షలో ఏముంటుంది (కీ ప్రకారం)',
        'Fructose / ఫ్రక్టోజ్',
        'Sucrose / సుక్రోజ్',
        'Galactose / గెలాక్టోజ్',
        'Glucose / గ్లూకోజ్ (Glucose — "grape sugar"; per key)',
        'D',
        'M',
        'Note: ripe grapes contain BOTH glucose and fructose. Source key picks Glucose ("grape sugar"/dextrose).',
        46
    ),
    (
        'Reagent used to test starch in leaves\nతెలుగు: ఆకులలో పిండిపదార్థం (starch) పరీక్షకు ఉపయోగించే కారకం',
        'Fehling\'s solution / ఫెహ్లింగ్స్ ద్రావణం (sugars)',
        'Iodine solution / అయోడిన్ ద్రావణం (Iodine — turns blue-black with starch)',
        'Million\'s reagent / మిలియన్స్ కారకం (proteins)',
        'Benedict\'s solution / బెనెడిక్ట్స్ (sugars)',
        'B',
        'M',
        '',
        47
    ),
    (
        'The element rich in most leafy vegetables\nతెలుగు: చాలా ఆకుకూరలలో సమృద్ధిగా ఉండే మూలకం',
        'Phosphorus / భాస్వరం',
        'Zinc / జింక్',
        'Iron / ఇనుము (Iron — spinach, drumstick leaves rich)',
        'Calcium / కాల్షియం',
        'C',
        'M',
        '',
        48
    ),
    (
        'Which is a micronutrient for plants\nతెలుగు: మొక్కలకు సూక్ష్మ పోషకం ఏది',
        'Carbon / కార్బన్ (macronutrient)',
        'Oxygen / ఆక్సిజన్ (macro)',
        'Nitrogen / నైట్రోజన్ (macro)',
        'Boron / బోరాన్ (Boron — micronutrient)',
        'D',
        'M',
        '',
        49
    ),
    (
        'The first stable product of photosynthesis is\nతెలుగు: కిరణజన్య సంయోగక్రియలో ఏర్పడే మొదటి స్థిరమైన ఉత్పత్తి',
        'Starch / పిండిపదార్థం',
        'Sucrose / సుక్రోజ్',
        'Phosphoglyceric acid / ఫాస్ఫోగ్లిసరిక్ ఆమ్లం (PGA — first stable; 3-C in C3)',
        'Glucose / గ్లూకోజ్',
        'C',
        'M',
        '',
        50
    ),
]
