"""
seed_awards_mcq.py – Awards & Recognitions 2025-2026 MCQs (IDs 23001-23080)
All questions strictly 2025 to 16 May 2026. Force-refresh: deletes old range first.
"""
import os, sqlite3

USE_POSTGRES = bool(os.environ.get("DATABASE_URL"))

if USE_POSTGRES:
    import psycopg2, urllib.parse as _up
    def _get_conn():
        u = _up.urlparse(os.environ["DATABASE_URL"])
        return psycopg2.connect(
            host=u.hostname, port=u.port or 5432,
            database=u.path.lstrip("/"),
            user=u.username, password=u.password,
            sslmode="require"
        )
else:
    def _get_conn():
        base = os.path.dirname(__file__)
        return sqlite3.connect(os.path.join(base, "database.db"))

def _fv(row):
    if row is None: return 0
    return row[0] if not isinstance(row[0], (list, dict)) else 0

def seed():
    conn = _get_conn()
    cur = conn.cursor()
    ph = "%s" if USE_POSTGRES else "?"

    # Force-refresh: delete stale data in this ID range
    cur.execute(f"DELETE FROM questions WHERE id>={ph} AND id<={ph}", (23001, 23080))
    conn.commit()

    questions = [
        # ─── Nobel Physics 2025 (23001-23006) ───
        {
            "id": 23001,
            "question_text": "The Nobel Prize in Physics 2025 was awarded for discoveries related to which phenomenon in electric circuits?",
            "option_a": "Macroscopic quantum mechanical tunnelling and energy quantisation",
            "option_b": "Superconductivity in high-temperature materials",
            "option_c": "Photon entanglement and Bell inequality violations",
            "option_d": "Quantum Hall effect in two-dimensional materials",
            "correct_answer": "A",
            "explanation": "The 2025 Nobel Physics Prize honoured John Clarke, Michel H. Devoret and John M. Martinis for their discovery of macroscopic quantum mechanical tunnelling and energy quantisation in an electric circuit — foundational work that underpins modern quantum computing.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23002,
            "question_text": "Which scientist shared the 2025 Nobel Prize in Physics for his research on superconducting qubits and quantum computing at Google?",
            "option_a": "Michel H. Devoret",
            "option_b": "John Clarke",
            "option_c": "John M. Martinis",
            "option_d": "David Wineland",
            "correct_answer": "C",
            "explanation": "John M. Martinis, known for leading Google's quantum supremacy experiments, shared the 2025 Nobel Physics Prize with John Clarke and Michel H. Devoret for macroscopic quantum tunnelling and energy quantisation in electric circuits.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23003,
            "question_text": "How many laureates shared the Nobel Prize in Physics 2025?",
            "option_a": "One",
            "option_b": "Two",
            "option_c": "Three",
            "option_d": "Four",
            "correct_answer": "C",
            "explanation": "The 2025 Nobel Prize in Physics was awarded jointly to three scientists: John Clarke (USA), Michel H. Devoret (France/USA) and John M. Martinis (USA) for their discoveries in macroscopic quantum mechanics in electric circuits.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "easy",
            "marks": 1
        },
        # ─── Nobel Chemistry 2025 (23004-23007) ───
        {
            "id": 23004,
            "question_text": "The Nobel Prize in Chemistry 2025 was awarded for the development of which class of porous materials?",
            "option_a": "Metal-organic frameworks (MOFs)",
            "option_b": "Zeolites and silicate networks",
            "option_c": "Carbon nanotubes and fullerenes",
            "option_d": "Covalent organic frameworks (COFs) only",
            "correct_answer": "A",
            "explanation": "The 2025 Nobel Chemistry Prize was awarded for creating metal-organic frameworks (MOFs) — porous molecular constructions that can harvest water from desert air, capture CO₂, store toxic gases or catalyse chemical reactions.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23005,
            "question_text": "Which Jordan-American chemist shared the 2025 Nobel Prize in Chemistry for pioneering work on metal-organic frameworks (MOFs)?",
            "option_a": "Ahmed Zewail",
            "option_b": "Omar Yaghi",
            "option_c": "Susumu Kitagawa",
            "option_d": "Richard Robson",
            "correct_answer": "B",
            "explanation": "Omar Yaghi (Jordan-American, UC Berkeley), along with Susumu Kitagawa (Japan) and Richard Robson (Australia), won the 2025 Nobel Chemistry Prize for the development of metal-organic frameworks (MOFs).",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "hard",
            "marks": 1
        },
        {
            "id": 23006,
            "question_text": "Which practical application of metal-organic frameworks (MOFs), the basis of the 2025 Nobel Chemistry Prize, is most relevant for combating climate change?",
            "option_a": "Nuclear waste containment",
            "option_b": "Carbon dioxide capture and storage",
            "option_c": "Hydrogen bomb miniaturisation",
            "option_d": "Rare-earth metal synthesis",
            "correct_answer": "B",
            "explanation": "A key real-world application of MOFs highlighted by the 2025 Nobel Chemistry Committee is carbon dioxide capture — these materials have enormous surface areas capable of adsorbing CO₂, crucial for climate mitigation, along with water harvesting from arid air.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        # ─── Nobel Medicine/Physiology 2025 (23007-23011) ───
        {
            "id": 23007,
            "question_text": "The 2025 Nobel Prize in Physiology or Medicine was awarded for discoveries about which type of immune cell?",
            "option_a": "Natural killer (NK) cells",
            "option_b": "Regulatory T cells (Tregs)",
            "option_c": "B-lymphocytes and antibody production",
            "option_d": "Dendritic cells and antigen presentation",
            "correct_answer": "B",
            "explanation": "Mary E. Brunkow, Fred Ramsdell and Shimon Sakaguchi won the 2025 Nobel Medicine Prize for revealing the crucial role of regulatory T cells (Tregs) in maintaining immune balance and preventing autoimmune diseases.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23008,
            "question_text": "Which Japanese immunologist, a pioneer in regulatory T cell research, was among the 2025 Nobel laureates in Physiology or Medicine?",
            "option_a": "Tasuku Honjo",
            "option_b": "Yoshinori Ohsumi",
            "option_c": "Shimon Sakaguchi",
            "option_d": "Satoshi Omura",
            "correct_answer": "C",
            "explanation": "Shimon Sakaguchi (Osaka University, Japan), along with Mary E. Brunkow and Fred Ramsdell, won the 2025 Nobel Prize in Medicine for groundbreaking discoveries on regulatory T cells (Tregs) and immune tolerance.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "hard",
            "marks": 1
        },
        {
            "id": 23009,
            "question_text": "What disease category is most directly addressed by the 2025 Nobel Medicine Prize discoveries on regulatory T cells?",
            "option_a": "Infectious diseases caused by bacteria",
            "option_b": "Autoimmune diseases",
            "option_c": "Genetic disorders and chromosomal abnormalities",
            "option_d": "Prion diseases",
            "correct_answer": "B",
            "explanation": "Regulatory T cells (Tregs) prevent the immune system from attacking the body's own tissues. Dysfunction of Tregs leads to autoimmune diseases. The 2025 Nobel Medicine laureates revealed how Tregs maintain immune tolerance.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "easy",
            "marks": 1
        },
        # ─── Nobel Literature 2025 (23010-23012) ───
        {
            "id": 23010,
            "question_text": "The 2025 Nobel Prize in Literature was awarded to which author?",
            "option_a": "Olga Tokarczuk",
            "option_b": "László Krasznahorkai",
            "option_c": "Peter Nadas",
            "option_d": "Milan Kundera",
            "correct_answer": "B",
            "explanation": "László Krasznahorkai, a Hungarian author, won the 2025 Nobel Prize in Literature 'for his compelling and visionary oeuvre that, in the midst of apocalyptic terror, reaffirms the power of art.'",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23011,
            "question_text": "From which country was the 2025 Nobel Laureate in Literature, László Krasznahorkai?",
            "option_a": "Poland",
            "option_b": "Czech Republic",
            "option_c": "Hungary",
            "option_d": "Romania",
            "correct_answer": "C",
            "explanation": "László Krasznahorkai is a Hungarian author. His novels, including Satantango and The Melancholy of Resistance, are often set against backdrops of social decay and existential dread.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "easy",
            "marks": 1
        },
        {
            "id": 23012,
            "question_text": "Which phrase from the 2025 Nobel Literature citation describes László Krasznahorkai's thematic focus?",
            "option_a": "Celebrates pastoral tranquility and rural nostalgia",
            "option_b": "Reaffirms the power of art amid apocalyptic terror",
            "option_c": "Explores colonial legacies through magical realism",
            "option_d": "Champions urban modernism and technological optimism",
            "correct_answer": "B",
            "explanation": "The Swedish Academy cited Krasznahorkai 'for his compelling and visionary oeuvre that, in the midst of apocalyptic terror, reaffirms the power of art' — capturing his characteristic blend of doom-laden atmosphere and artistic transcendence.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        # ─── Nobel Peace Prize 2025 (23013-23016) ───
        {
            "id": 23013,
            "question_text": "Who won the Nobel Peace Prize 2025?",
            "option_a": "Alexei Navalny (posthumous)",
            "option_b": "María Corina Machado",
            "option_c": "Greta Thunberg",
            "option_d": "UNHCR",
            "correct_answer": "B",
            "explanation": "María Corina Machado of Venezuela won the 2025 Nobel Peace Prize for her tireless efforts in promoting democratic rights in Venezuela, uniting the political opposition to peacefully strive for free elections and transition from dictatorship.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "easy",
            "marks": 1
        },
        {
            "id": 23014,
            "question_text": "For which cause was the 2025 Nobel Peace Prize winner María Corina Machado recognised?",
            "option_a": "Climate change activism in Latin America",
            "option_b": "Nuclear disarmament in South Asia",
            "option_c": "Promoting democratic rights and free elections in Venezuela",
            "option_d": "Indigenous land rights in the Amazon basin",
            "correct_answer": "C",
            "explanation": "The Nobel Committee recognised Machado for her courageous leadership in uniting Venezuela's divided political opposition, campaigning peacefully for free elections and a just democratic transition from the Maduro dictatorship.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "easy",
            "marks": 1
        },
        # ─── Nobel Economics 2025 (23015-23018) ───
        {
            "id": 23015,
            "question_text": "The Nobel Prize in Economic Sciences 2025 was awarded for groundbreaking work on which economic concept?",
            "option_a": "Auction theory and mechanism design",
            "option_b": "Innovation-driven economic growth and creative destruction",
            "option_c": "Inequality and poverty measurement in developing nations",
            "option_d": "Behavioural economics and cognitive biases",
            "correct_answer": "B",
            "explanation": "Joel Mokyr, Philippe Aghion and Peter Howitt won the 2025 Nobel Economics Prize for their work on innovation-driven growth; Aghion and Howitt developed the theory of 'creative destruction' showing how innovations replace older products to drive long-run growth.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23016,
            "question_text": "Which Canadian economist shared the 2025 Nobel Prize in Economic Sciences for the Schumpeterian growth theory of creative destruction?",
            "option_a": "Joel Mokyr",
            "option_b": "Philippe Aghion",
            "option_c": "Peter Howitt",
            "option_d": "Daron Acemoglu",
            "correct_answer": "C",
            "explanation": "Peter Howitt (Canadian economist) and Philippe Aghion jointly developed the Schumpeterian creative destruction model of growth, while Joel Mokyr studied historical conditions for technological progress. All three shared the 2025 Nobel Economics Prize.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "hard",
            "marks": 1
        },
        {
            "id": 23017,
            "question_text": "Which Nobel Economics 2025 laureate is known for his historical analysis of the conditions necessary for sustained technological progress?",
            "option_a": "Peter Howitt",
            "option_b": "Philippe Aghion",
            "option_c": "Joel Mokyr",
            "option_d": "Simon Johnson",
            "correct_answer": "C",
            "explanation": "Joel Mokyr (Northwestern University, USA), a historian of technology and economic history, studied why some nations achieved sustained technological progress while others stagnated, contributing to the 2025 Nobel Economics Prize.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "hard",
            "marks": 1
        },
        {
            "id": 23018,
            "question_text": "Which of the following correctly pairs the 2025 Nobel Prize category with its winner(s)?",
            "option_a": "Peace – Greta Thunberg; Literature – Salman Rushdie",
            "option_b": "Physics – Clarke, Devoret, Martinis; Peace – María Corina Machado",
            "option_c": "Chemistry – Jennifer Doudna; Medicine – Katalin Karikó",
            "option_d": "Economics – Esther Duflo; Literature – Haruki Murakami",
            "correct_answer": "B",
            "explanation": "In 2025: Physics → Clarke/Devoret/Martinis (quantum circuits); Peace → María Corina Machado (Venezuela democracy). The other options list previous Nobel winners incorrectly mapped to 2025.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        # ─── Ballon d'Or & FIFA Best 2025 (23019-23025) ───
        {
            "id": 23019,
            "question_text": "Who won the Ballon d'Or 2025 (men's category)?",
            "option_a": "Vinicius Jr. (Real Madrid)",
            "option_b": "Erling Haaland (Manchester City)",
            "option_c": "Ousmane Dembélé (Paris Saint-Germain)",
            "option_d": "Kylian Mbappé (Real Madrid)",
            "correct_answer": "C",
            "explanation": "Ousmane Dembélé (PSG, France) won the 69th Ballon d'Or on 22 September 2025 at the Théâtre du Châtelet, Paris. He scored 35 goals and provided 16 assists in 53 games as PSG completed a historic quadruple.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "easy",
            "marks": 1
        },
        {
            "id": 23020,
            "question_text": "The 2025 Ballon d'Or ceremony was held at which venue in Paris?",
            "option_a": "Stade de France",
            "option_b": "Palais Garnier Opera House",
            "option_c": "Théâtre du Châtelet",
            "option_d": "Louvre Pyramid",
            "correct_answer": "C",
            "explanation": "The 69th Ballon d'Or ceremony took place on 22 September 2025 at the Théâtre du Châtelet in Paris, where Ousmane Dembélé was named the world's best player.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "hard",
            "marks": 1
        },
        {
            "id": 23021,
            "question_text": "Who won the Women's Ballon d'Or 2025, claiming the award for the third consecutive time?",
            "option_a": "Alexia Putellas (Barcelona)",
            "option_b": "Sam Kerr (Chelsea)",
            "option_c": "Caroline Graham Hansen (Barcelona)",
            "option_d": "Aitana Bonmatí (Barcelona)",
            "correct_answer": "D",
            "explanation": "Aitana Bonmatí (FC Barcelona, Spain) won the Women's Ballon d'Or for the third consecutive year in 2025, after driving Barcelona to a domestic treble and reaching the UEFA Women's Champions League final, where she won UWCL Player of the Season for the third time.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "easy",
            "marks": 1
        },
        {
            "id": 23022,
            "question_text": "Where was the 2025 FIFA Best Football Awards ceremony held?",
            "option_a": "Zurich, Switzerland",
            "option_b": "Doha, Qatar",
            "option_c": "Paris, France",
            "option_d": "Dubai, UAE",
            "correct_answer": "B",
            "explanation": "The Best FIFA Football Awards 2025 were presented on December 16, 2025, at Fairmont Katara Hall in Doha, Qatar. Both Ousmane Dembélé (men's) and Aitana Bonmatí (women's) won The Best FIFA Player awards.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23023,
            "question_text": "Ousmane Dembélé's 2025 Ballon d'Or win was notable because he was the first French player to win the award while playing for which club?",
            "option_a": "Olympique Lyonnais",
            "option_b": "AS Monaco",
            "option_c": "Paris Saint-Germain",
            "option_d": "Olympique de Marseille",
            "correct_answer": "C",
            "explanation": "Ousmane Dembélé became the first French player to win the Ballon d'Or while wearing a Paris Saint-Germain shirt. His exceptional 2024-25 season included 35 goals and 16 assists as PSG won a historic quadruple.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        # ─── Grammy Awards 2025 (67th) (23024-23028) ───
        {
            "id": 23024,
            "question_text": "Which song by Kendrick Lamar won both Record of the Year and Song of the Year at the 67th Grammy Awards (2025)?",
            "option_a": "\"euphoria\"",
            "option_b": "\"Not Like Us\"",
            "option_c": "\"Luther\"",
            "option_d": "\"tv off\"",
            "correct_answer": "B",
            "explanation": "Kendrick Lamar's diss track 'Not Like Us' won both Record of the Year and Song of the Year at the 67th Grammy Awards held on February 2, 2025.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "easy",
            "marks": 1
        },
        {
            "id": 23025,
            "question_text": "Which album won Album of the Year at the 67th Grammy Awards (2025)?",
            "option_a": "Short n' Sweet – Sabrina Carpenter",
            "option_b": "Radical Optimism – Dua Lipa",
            "option_c": "Cowboy Carter – Beyoncé",
            "option_d": "Bright Future – Adrianne Lenker",
            "correct_answer": "C",
            "explanation": "Beyoncé's country-influenced album 'Cowboy Carter' won Album of the Year at the 2025 Grammys, making her the first Black woman to win in this category since Lauryn Hill in 1999 and the first Black artist to win Best Country Album.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "easy",
            "marks": 1
        },
        {
            "id": 23026,
            "question_text": "Who won Best New Artist at the 67th Grammy Awards (February 2025)?",
            "option_a": "Sabrina Carpenter",
            "option_b": "Gracie Abrams",
            "option_c": "Sierra Ferrell",
            "option_d": "Chappell Roan",
            "correct_answer": "D",
            "explanation": "Chappell Roan won Best New Artist at the 67th Grammy Awards on February 2, 2025. Sierra Ferrell swept the American roots categories, winning all four of her nominations.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "easy",
            "marks": 1
        },
        {
            "id": 23027,
            "question_text": "At the 2025 Grammy Awards, Beyoncé winning Album of the Year for 'Cowboy Carter' was historic because she was the first Black woman to win that category since which artist?",
            "option_a": "Whitney Houston",
            "option_b": "Lauryn Hill (1999)",
            "option_c": "Alicia Keys (2002)",
            "option_d": "Mary J. Blige (1995)",
            "correct_answer": "B",
            "explanation": "Beyoncé's Grammy win for Album of the Year ('Cowboy Carter') in 2025 made her the first Black woman to win in that category since Lauryn Hill's 'The Miseducation of Lauryn Hill' triumphed in 1999.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        # ─── Oscars 2025 (97th Academy Awards) (23028-23034) ───
        {
            "id": 23028,
            "question_text": "Which film won Best Picture at the 97th Academy Awards (Oscars 2025)?",
            "option_a": "The Brutalist",
            "option_b": "Conclave",
            "option_c": "Emilia Pérez",
            "option_d": "Anora",
            "correct_answer": "D",
            "explanation": "'Anora', directed by Sean Baker, swept the 97th Academy Awards (March 2, 2025) winning Best Picture, Best Director, Best Actress (Mikey Madison) and more — five Oscars in total.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "easy",
            "marks": 1
        },
        {
            "id": 23029,
            "question_text": "Who won the Best Actor (Leading Role) Oscar at the 97th Academy Awards 2025?",
            "option_a": "Timothée Chalamet (A Complete Unknown)",
            "option_b": "Adrien Brody (The Brutalist)",
            "option_c": "Kieran Culkin (A Real Pain)",
            "option_d": "Colman Domingo (Sing Sing)",
            "correct_answer": "B",
            "explanation": "Adrien Brody won the Oscar for Best Actor in a Leading Role for his performance in 'The Brutalist' at the 97th Academy Awards on March 2, 2025.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "easy",
            "marks": 1
        },
        {
            "id": 23030,
            "question_text": "Zoe Saldaña's Best Supporting Actress Oscar win at the 2025 ceremony for 'Emilia Pérez' was historic because she became the first American of what descent to win an Oscar?",
            "option_a": "Cuban-American",
            "option_b": "Puerto Rican descent",
            "option_c": "Dominican descent",
            "option_d": "Haitian-American",
            "correct_answer": "C",
            "explanation": "Zoe Saldaña became the first American of Dominican descent to win an Oscar when she won Best Supporting Actress for 'Emilia Pérez' at the 97th Academy Awards (2025).",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23031,
            "question_text": "Which designer won the Oscar for Best Costume Design at the 2025 ceremony for 'Wicked', becoming the first Black male winner in that category?",
            "option_a": "Ruth Carter",
            "option_b": "Sandy Powell",
            "option_c": "Paul Tazewell",
            "option_d": "Mark Bridges",
            "correct_answer": "C",
            "explanation": "Paul Tazewell won the 2025 Academy Award for Costume Design for 'Wicked', making him the first Black male to win in that category in Oscar history.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "hard",
            "marks": 1
        },
        {
            "id": 23032,
            "question_text": "The 97th Academy Awards (Oscars 2025) were held at which venue?",
            "option_a": "Shrine Auditorium, Los Angeles",
            "option_b": "Dolby Theatre at Ovation Hollywood",
            "option_c": "Kodak Theatre, Hollywood",
            "option_d": "Staples Center, Los Angeles",
            "correct_answer": "B",
            "explanation": "The 97th Academy Awards were held on March 2, 2025, at the Dolby Theatre at Ovation Hollywood, Los Angeles.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        # ─── Literature Awards 2025 (23033-23039) ───
        {
            "id": 23033,
            "question_text": "Who won the International Booker Prize 2025 for the book 'Heart Lamp'?",
            "option_a": "Arundhati Roy",
            "option_b": "Banu Mushtaq (translated by Deepa Bhasthi)",
            "option_c": "Perumal Murugan (translated by N. Kalyan Raman)",
            "option_d": "Jenny Erpenbeck (translated by Michael Hofmann)",
            "correct_answer": "B",
            "explanation": "Banu Mushtaq's 'Heart Lamp', translated by Deepa Bhasthi, won the International Booker Prize 2025. It was the first collection of short stories and the first Kannada-language work to win the prize. Deepa Bhasthi was the first Indian translator to win the award.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "easy",
            "marks": 1
        },
        {
            "id": 23034,
            "question_text": "What was historically significant about 'Heart Lamp' winning the International Booker Prize 2025?",
            "option_a": "It was the first autobiography to win the prize",
            "option_b": "It was the first graphic novel shortlisted for the prize",
            "option_c": "It was the first collection of short stories to win the prize",
            "option_d": "It was the first book translated from Persian to win",
            "correct_answer": "C",
            "explanation": "'Heart Lamp' by Banu Mushtaq was the first collection of short stories to win the International Booker Prize 2025. It is written in Kannada and chronicles 12 stories of women in patriarchal communities in southern India, spanning 30 years.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23035,
            "question_text": "Who won the Booker Prize 2025 (for fiction written in English)?",
            "option_a": "Richard Powers",
            "option_b": "David Szalay",
            "option_c": "Rachel Cusk",
            "option_d": "Kazuo Ishiguro",
            "correct_answer": "B",
            "explanation": "David Szalay won the Booker Prize 2025 for his novel 'Flesh', announced at a ceremony in London on November 10, 2025. He became the first Hungarian-British author to win the Booker Prize and received £50,000.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23036,
            "question_text": "Which novel by Percival Everett won the 2025 Pulitzer Prize for Fiction?",
            "option_a": "Erasure",
            "option_b": "James",
            "option_c": "The Trees",
            "option_d": "Dr. No",
            "correct_answer": "B",
            "explanation": "'James' by Percival Everett (Doubleday) won the 2025 Pulitzer Prize for Fiction. It is an accomplished reconsideration of Huckleberry Finn that gives agency to the character Jim to illustrate racial absurdity and the search for family and freedom.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23037,
            "question_text": "The 2025 Pulitzer Prize for Drama was awarded to which play?",
            "option_a": "Hamilton (revival)",
            "option_b": "Topdog/Underdog",
            "option_c": "Purpose by Branden Jacobs-Jenkins",
            "option_d": "Stereophonic by David Adjmi",
            "correct_answer": "C",
            "explanation": "'Purpose' by Branden Jacobs-Jenkins won the 2025 Pulitzer Prize for Drama. The play explores the complex dynamics and legacy of an upper middle-class African-American family whose patriarch was a key figure in the Civil Rights Movement.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "hard",
            "marks": 1
        },
        {
            "id": 23038,
            "question_text": "Who translated 'Heart Lamp' from Kannada to English for the International Booker Prize 2025 win, becoming the first Indian translator to win the award?",
            "option_a": "N. Kalyan Raman",
            "option_b": "Deepa Bhasthi",
            "option_c": "V. Geetha",
            "option_d": "Arunava Sinha",
            "correct_answer": "B",
            "explanation": "Deepa Bhasthi translated Banu Mushtaq's 'Heart Lamp' from Kannada, winning the International Booker Prize 2025. She became the first Indian translator to win this prize.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        # ─── Science & Technology Awards 2025 (23039-23044) ───
        {
            "id": 23039,
            "question_text": "Who won the Abel Prize 2025 in mathematics?",
            "option_a": "Terence Tao",
            "option_b": "Masaki Kashiwara",
            "option_c": "Ngô Bảo Châu",
            "option_d": "Karen Uhlenbeck",
            "correct_answer": "B",
            "explanation": "Masaki Kashiwara (Kyoto University, RIMS, Japan) won the Abel Prize 2025 for fundamental contributions to algebraic analysis and representation theory, particularly the development of the theory of D-modules and the discovery of crystal bases.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "hard",
            "marks": 1
        },
        {
            "id": 23040,
            "question_text": "The 2025 ACM Turing Award was given to Charles H. Bennett and Gilles Brassard for their contributions to which field?",
            "option_a": "Artificial intelligence and deep learning",
            "option_b": "Quantum information science and quantum cryptography",
            "option_c": "Database query optimisation",
            "option_d": "Operating systems and distributed computing",
            "correct_answer": "B",
            "explanation": "Charles H. Bennett (IBM Research, USA) and Gilles Brassard (Université de Montréal, Canada) received the 2025 ACM Turing Award for establishing the foundations of quantum information science, including the pioneering BB84 quantum key distribution protocol.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23041,
            "question_text": "Who won the 2025 Pritzker Architecture Prize, often called the 'Nobel of architecture'?",
            "option_a": "Bjarke Ingels",
            "option_b": "Tadao Ando",
            "option_c": "Liu Jiakun",
            "option_d": "Kengo Kuma",
            "correct_answer": "C",
            "explanation": "Liu Jiakun, based in Chengdu, China, won the 2025 Pritzker Architecture Prize. He is the 54th laureate and founder of Jiakun Architecture (established 1999). He is the 9th laureate from Asia.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23042,
            "question_text": "The 2025 Turing Award winners Charles H. Bennett and Gilles Brassard are best known for developing which quantum protocol?",
            "option_a": "Shor's algorithm for prime factorisation",
            "option_b": "Grover's search algorithm",
            "option_c": "BB84 quantum key distribution protocol",
            "option_d": "Deutsch-Jozsa algorithm",
            "correct_answer": "C",
            "explanation": "Bennett and Brassard (BB84 protocol, 1984) invented the first quantum key distribution (QKD) scheme, enabling theoretically unbreakable encryption based on quantum mechanics. This foundational work earned them the 2025 ACM Turing Award.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "hard",
            "marks": 1
        },
        {
            "id": 23043,
            "question_text": "Masaki Kashiwara, the 2025 Abel Prize winner, is primarily known for developing the theory of what mathematical objects?",
            "option_a": "Prime number distributions (Riemann hypothesis approach)",
            "option_b": "D-modules in algebraic analysis",
            "option_c": "Elliptic curves and modular forms",
            "option_d": "Topological quantum field theories",
            "correct_answer": "B",
            "explanation": "Masaki Kashiwara's primary mathematical contribution is the development of D-modules (differential equation modules) and crystal bases in representation theory, recognised by the 2025 Abel Prize from the Norwegian Academy of Science and Letters.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "hard",
            "marks": 1
        },
        # ─── India Sports Awards 2024-25 (23044-23050) ───
        {
            "id": 23044,
            "question_text": "The Major Dhyan Chand Khel Ratna Award for 2024 (conferred January 2025) was given to how many athletes?",
            "option_a": "Two",
            "option_b": "Three",
            "option_c": "Four",
            "option_d": "Five",
            "correct_answer": "C",
            "explanation": "Four athletes received the Major Dhyan Chand Khel Ratna Award 2024 at a ceremony at Rashtrapati Bhavan on January 17, 2025: Manu Bhaker (shooting), D. Gukesh (chess), Harmanpreet Singh (hockey) and Praveen Kumar (para athletics).",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "easy",
            "marks": 1
        },
        {
            "id": 23045,
            "question_text": "Which chess player received the Khel Ratna Award 2024 (January 2025), having become the youngest World Chess Champion in 2024?",
            "option_a": "Praggnanandhaa Rameshbabu",
            "option_b": "Viswanathan Anand",
            "option_c": "D. Gukesh",
            "option_d": "Arjun Erigaisi",
            "correct_answer": "C",
            "explanation": "D. Gukesh received the Khel Ratna Award 2024 (conferred January 17, 2025) at Rashtrapati Bhavan. He became the youngest FIDE World Chess Champion in December 2024, defeating Ding Liren.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "easy",
            "marks": 1
        },
        {
            "id": 23046,
            "question_text": "Which Indian hockey player received the Khel Ratna Award 2024 (January 2025) along with Manu Bhaker, D. Gukesh and Praveen Kumar?",
            "option_a": "P.R. Sreejesh",
            "option_b": "Harmanpreet Singh",
            "option_c": "Manpreet Singh",
            "option_d": "Dilpreet Singh",
            "correct_answer": "B",
            "explanation": "Harmanpreet Singh, captain of the Indian men's hockey team, received the Khel Ratna Award 2024 (January 2025). He led India to a bronze medal at the Paris Olympics 2024.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "easy",
            "marks": 1
        },
        {
            "id": 23047,
            "question_text": "How many para-athletes were included among the Arjuna Award 2024 recipients, setting an unprecedented record?",
            "option_a": "10",
            "option_b": "13",
            "option_c": "17",
            "option_d": "20",
            "correct_answer": "C",
            "explanation": "An unprecedented 17 para-athletes were named among the 32 Arjuna Award 2024 recipients (conferred January 2025) to honour their outstanding performance at the Paris Paralympics 2024.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23048,
            "question_text": "Who received the Dronacharya Award 2024 (lifetime category) in January 2025, as a former Indian football manager?",
            "option_a": "S. Muralidharan",
            "option_b": "Subhash Rana",
            "option_c": "Deepali Deshpande",
            "option_d": "Armando Colaco",
            "correct_answer": "D",
            "explanation": "Armando Colaco, a legendary Indian football manager known for developing Goa's football talent, received the lifetime Dronacharya Award 2024 at Rashtrapati Bhavan in January 2025.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "hard",
            "marks": 1
        },
        # ─── Padma Awards 2025 (23049-23055) ───
        {
            "id": 23049,
            "question_text": "How many Padma Awards were conferred in the Republic Day 2025 list?",
            "option_a": "80",
            "option_b": "113",
            "option_c": "139",
            "option_d": "156",
            "correct_answer": "C",
            "explanation": "A total of 139 Padma Awards were announced in 2025, comprising 7 Padma Vibhushan, 19 Padma Bhushan and 113 Padma Shri. Among them 23 were women, 10 were from abroad and 13 were posthumous.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23050,
            "question_text": "Which eminent Malayalam writer received the Padma Vibhushan 2025 posthumously for Literature?",
            "option_a": "O.V. Vijayan",
            "option_b": "M.T. Vasudevan Nair",
            "option_c": "Kamala Das",
            "option_d": "K.J. Yesudas",
            "correct_answer": "B",
            "explanation": "M.T. Vasudevan Nair (M.T.), the legendary Malayalam author and screenplay writer, received the Padma Vibhushan 2025 posthumously. He passed away in December 2024 and was widely regarded as one of the greatest Malayalam literary figures.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23051,
            "question_text": "Ghazal singer Pankaj Udas was among the Padma Vibhushan 2025 recipients (posthumous). For which art form was he recognised?",
            "option_a": "Hindustani classical vocal",
            "option_b": "Ghazal singing",
            "option_c": "Carnatic instrumental music",
            "option_d": "Folk music of Rajasthan",
            "correct_answer": "B",
            "explanation": "Pankaj Udas received the Padma Vibhushan 2025 posthumously for his outstanding contribution to Ghazal singing. He passed away in February 2024 and was known for popularising the Ghazal genre for mainstream audiences.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "easy",
            "marks": 1
        },
        {
            "id": 23052,
            "question_text": "Dr. Duvvur Nageshwar Reddy was among the Padma Vibhushan 2025 recipients. In which field did he make his notable contributions?",
            "option_a": "Cardiology – pioneering bypass surgery",
            "option_b": "Gastroenterology – pioneer of therapeutic endoscopy",
            "option_c": "Neurosurgery – robotic brain surgery",
            "option_d": "Oncology – targeted cancer immunotherapy",
            "correct_answer": "B",
            "explanation": "Dr. Duvvur Nageshwar Reddy, Chairman of Asian Institute of Gastroenterology, Hyderabad, received Padma Vibhushan 2025 for his pioneering work in gastroenterology and therapeutic endoscopy, making advanced GI care accessible in India.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23053,
            "question_text": "Which singer received the Padma Bhushan 2025 for his contributions to Indian popular music?",
            "option_a": "Shreya Ghoshal",
            "option_b": "Sonu Nigam",
            "option_c": "Arijit Singh",
            "option_d": "Armaan Malik",
            "correct_answer": "C",
            "explanation": "Arijit Singh received the Padma Bhushan 2025 for Music. He is one of India's most celebrated playback singers known for soulful performances across multiple languages in Indian cinema.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "easy",
            "marks": 1
        },
        # ─── International Awards & Recognition 2025-26 (23054-23064) ───
        {
            "id": 23054,
            "question_text": "The 2025 Pritzker Architecture Prize laureate Liu Jiakun is based in which Chinese city?",
            "option_a": "Beijing",
            "option_b": "Shanghai",
            "option_c": "Chengdu",
            "option_d": "Shenzhen",
            "correct_answer": "C",
            "explanation": "Liu Jiakun is based in Chengdu, Sichuan Province, China. He founded Jiakun Architecture in 1999 and became the 54th Pritzker Prize laureate in 2025, recognised for humanist architecture informed by Chinese culture.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "hard",
            "marks": 1
        },
        {
            "id": 23055,
            "question_text": "Which French football legend won the Ballon d'Or Masculine 2025, breaking Messi-Ronaldo dominance patterns again?",
            "option_a": "Thierry Henry",
            "option_b": "Zinedine Zidane",
            "option_c": "Kylian Mbappé",
            "option_d": "Ousmane Dembélé",
            "correct_answer": "D",
            "explanation": "Ousmane Dembélé (PSG, France) won the Ballon d'Or 2025. While not as long a legend as Henry or Zidane, he is a French international who had a record-breaking season with PSG winning four trophies in 2024-25.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "easy",
            "marks": 1
        },
        {
            "id": 23056,
            "question_text": "The 2025 International Booker Prize winner Banu Mushtaq writes in which Indian language?",
            "option_a": "Tamil",
            "option_b": "Telugu",
            "option_c": "Kannada",
            "option_d": "Malayalam",
            "correct_answer": "C",
            "explanation": "Banu Mushtaq writes in Kannada. Her short story collection 'Heart Lamp' (translated by Deepa Bhasthi) became the first Kannada work to win the International Booker Prize 2025.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "easy",
            "marks": 1
        },
        {
            "id": 23057,
            "question_text": "Which Pulitzer-winning fiction (2025) reimagines the character Jim from Mark Twain's 'Adventures of Huckleberry Finn' and won the 2025 Pulitzer Prize for Fiction?",
            "option_a": "The God of Small Things",
            "option_b": "James by Percival Everett",
            "option_c": "Beloved by Toni Morrison",
            "option_d": "The Underground Railroad by Colson Whitehead",
            "correct_answer": "B",
            "explanation": "'James' by Percival Everett (2025 Pulitzer Fiction) is described as an 'accomplished reconsideration of Huckleberry Finn that gives agency to Jim to illustrate the absurdity of racial supremacy and provide a new take on the search for family and freedom.'",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23058,
            "question_text": "Which organisation awarded the 2025 Nobel Prize in Literature to László Krasznahorkai?",
            "option_a": "The Norwegian Academy of Science and Letters",
            "option_b": "The Royal Swedish Academy of Sciences",
            "option_c": "The Swedish Academy (Svenska Akademien)",
            "option_d": "The French Académie Française",
            "correct_answer": "C",
            "explanation": "The Nobel Prize in Literature is awarded by the Swedish Academy (Svenska Akademien) in Stockholm. The Swedish Academy announced László Krasznahorkai (Hungary) as the 2025 Nobel Literature laureate.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23059,
            "question_text": "Former Chief Justice of India Jagdish Singh Khehar was honoured with which Padma Award in 2025?",
            "option_a": "Padma Shri",
            "option_b": "Padma Bhushan",
            "option_c": "Padma Vibhushan",
            "option_d": "Bharat Ratna",
            "correct_answer": "C",
            "explanation": "Justice (Retd.) Jagdish Singh Khehar, former Chief Justice of India, received the Padma Vibhushan 2025 in the category of Public Affairs — India's second-highest civilian honour.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23060,
            "question_text": "At the 2025 Oscars, which animated film (not from a major Hollywood studio) won Best Animated Feature Film?",
            "option_a": "Inside Out 2",
            "option_b": "The Wild Robot",
            "option_c": "Flow",
            "option_d": "Memoir of a Snail",
            "correct_answer": "C",
            "explanation": "'Flow', a Latvian animated film directed by Gints Zilbalodis, won the Best Animated Feature Film award at the 97th Academy Awards (2025) — a historic win for a small-budget, dialogue-free European animation.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        # ─── Mixed / Higher-Order Awards (23061-23080) ───
        {
            "id": 23061,
            "question_text": "Which documentary film, about a Palestinian-Israeli co-direction team, won Best Documentary Feature at the 2025 Oscars?",
            "option_a": "20 Days in Mariupol",
            "option_b": "Four Daughters",
            "option_c": "No Other Land",
            "option_d": "Navalny",
            "correct_answer": "C",
            "explanation": "'No Other Land', co-directed by a Palestinian-Israeli team including Basel Adra and Yuval Abraham, won Best Documentary Feature at the 97th Academy Awards (Oscars 2025).",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23062,
            "question_text": "Which Booker Prize 2025 winner's nationality was historically notable as the first of that background to win the prize?",
            "option_a": "African-British",
            "option_b": "Hungarian-British",
            "option_c": "Indian-British",
            "option_d": "Chinese-British",
            "correct_answer": "B",
            "explanation": "David Szalay, winner of the Booker Prize 2025 for 'Flesh', is of Hungarian-British background — he became the first Hungarian-British author to win the Booker Prize, which awards fiction written in English.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23063,
            "question_text": "Manu Bhaker received the Khel Ratna Award (2024, conferred January 2025) for which sport?",
            "option_a": "Athletics (javelin throw)",
            "option_b": "Badminton",
            "option_c": "Shooting (pistol)",
            "option_d": "Wrestling",
            "correct_answer": "C",
            "explanation": "Manu Bhaker won the Khel Ratna Award 2024 (January 2025) for shooting. She won two bronze medals in shooting at the Paris Olympics 2024 — the first Indian woman to win two Olympic medals in a single Games.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "easy",
            "marks": 1
        },
        {
            "id": 23064,
            "question_text": "Which para-athlete received the Khel Ratna Award 2024 (January 2025) after winning Paralympic gold at Paris 2024?",
            "option_a": "Sumit Antil",
            "option_b": "Murlikant Petkar",
            "option_c": "Devendra Jhajharia",
            "option_d": "Praveen Kumar",
            "correct_answer": "D",
            "explanation": "Praveen Kumar (para high jump) won the Khel Ratna Award 2024 (January 2025) after his gold medal performance at the Paris 2024 Paralympics. He competes in the T64 category.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23065,
            "question_text": "Which Nobel Prize 2025 laureate's work on MOFs is directly relevant to achieving India's net-zero 2070 targets?",
            "option_a": "László Krasznahorkai (Literature)",
            "option_b": "Omar Yaghi, Susumu Kitagawa, Richard Robson (Chemistry – MOFs for CO₂ capture)",
            "option_c": "John Martinis (Physics – quantum computing for energy optimisation)",
            "option_d": "María Corina Machado (Peace – democratic energy governance)",
            "correct_answer": "B",
            "explanation": "Metal-organic frameworks (MOFs), the basis of the 2025 Nobel Chemistry Prize (Yaghi/Kitagawa/Robson), enable direct air capture of CO₂ and water harvesting in arid regions — technologies directly relevant to India's net-zero 2070 commitments.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "hard",
            "marks": 1
        },
        {
            "id": 23066,
            "question_text": "Shimon Sakaguchi, a 2025 Nobel Medicine laureate, is affiliated with which Japanese university?",
            "option_a": "University of Tokyo",
            "option_b": "Osaka University",
            "option_c": "Kyoto University",
            "option_d": "Tohoku University",
            "correct_answer": "B",
            "explanation": "Shimon Sakaguchi is a professor at Osaka University, Japan. His foundational research on regulatory T cells (Tregs) at Osaka University contributed to the 2025 Nobel Prize in Physiology or Medicine, shared with Mary E. Brunkow and Fred Ramsdell.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "hard",
            "marks": 1
        },
        {
            "id": 23067,
            "question_text": "The FIFA Best Men's Player Award 2025 was presented in Doha and won by the same player as the Ballon d'Or 2025. Who is this player?",
            "option_a": "Kylian Mbappé",
            "option_b": "Erling Haaland",
            "option_c": "Vinicius Jr.",
            "option_d": "Ousmane Dembélé",
            "correct_answer": "D",
            "explanation": "Ousmane Dembélé won both the Ballon d'Or 2025 (September 22, Paris) and the FIFA Best Men's Player 2025 (December 16, Doha, Qatar) — a clean sweep of football's two most prestigious individual awards in 2025.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "easy",
            "marks": 1
        },
        {
            "id": 23068,
            "question_text": "Which Scandinavian institution awards the Abel Prize in Mathematics, which was won by Masaki Kashiwara in 2025?",
            "option_a": "The Royal Swedish Academy of Sciences",
            "option_b": "The Norwegian Academy of Science and Letters",
            "option_c": "The Danish Royal Academy",
            "option_d": "The Finnish Academy of Science and Letters",
            "correct_answer": "B",
            "explanation": "The Abel Prize is awarded by the Norwegian Academy of Science and Letters (Oslo) to recognise outstanding contributions to mathematics. Masaki Kashiwara of Kyoto University received the 2025 Abel Prize.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23069,
            "question_text": "Gilles Brassard, co-winner of the 2025 Turing Award, is a professor at which university?",
            "option_a": "Massachusetts Institute of Technology",
            "option_b": "ETH Zürich",
            "option_c": "Université de Montréal",
            "option_d": "University of Waterloo",
            "correct_answer": "C",
            "explanation": "Gilles Brassard is a Canadian computer scientist and professor at the Université de Montréal. Along with Charles H. Bennett (IBM Research), he received the 2025 ACM Turing Award for founding quantum information science.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "hard",
            "marks": 1
        },
        {
            "id": 23070,
            "question_text": "Kieran Culkin won Best Supporting Actor at the 2025 Oscars for which film?",
            "option_a": "Conclave",
            "option_b": "A Real Pain",
            "option_c": "Nickel Boys",
            "option_d": "The Brutalist",
            "correct_answer": "B",
            "explanation": "Kieran Culkin won the Academy Award for Best Supporting Actor at the 97th Oscars (2025) for his role in 'A Real Pain', a film about two cousins who travel to Poland to honour their grandmother.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23071,
            "question_text": "Which actress won Best Actress (Leading Role) at the 97th Academy Awards 2025 for her role in 'Anora'?",
            "option_a": "Demi Moore",
            "option_b": "Cynthia Erivo",
            "option_c": "Mikey Madison",
            "option_d": "Fernanda Torres",
            "correct_answer": "C",
            "explanation": "Mikey Madison won Best Actress in a Leading Role at the 97th Oscars (2025) for her performance in 'Anora', directed by Sean Baker. The film swept five Oscar categories including Best Picture.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23072,
            "question_text": "The Nobel Peace Prize 2025 winner María Corina Machado is a political leader from which country?",
            "option_a": "Colombia",
            "option_b": "Cuba",
            "option_c": "Venezuela",
            "option_d": "Nicaragua",
            "correct_answer": "C",
            "explanation": "María Corina Machado is a Venezuelan opposition leader and engineer who won the 2025 Nobel Peace Prize for her tireless efforts to promote democratic rights and peaceful democratic transition in Venezuela under the Maduro government.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "easy",
            "marks": 1
        },
        {
            "id": 23073,
            "question_text": "Which singer's country music-influenced album 'Cowboy Carter' earned her the Grammy for Album of the Year 2025, finally breaking her four-time shutout?",
            "option_a": "Dolly Parton",
            "option_b": "Rihanna",
            "option_c": "Taylor Swift",
            "option_d": "Beyoncé",
            "correct_answer": "D",
            "explanation": "Beyoncé finally won the coveted Album of the Year Grammy at the 67th Grammys (February 2025) for 'Cowboy Carter', after being shut out on her previous four nominations for the top prize. She also became the first Black artist to win Best Country Album.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "easy",
            "marks": 1
        },
        {
            "id": 23074,
            "question_text": "The ACM Turing Award is often described as the 'Nobel Prize of Computing'. What is the prize money for the Turing Award (2025)?",
            "option_a": "$500,000",
            "option_b": "$750,000",
            "option_c": "$1,000,000",
            "option_d": "$250,000",
            "correct_answer": "C",
            "explanation": "The ACM A.M. Turing Award carries a prize of $1,000,000 (one million US dollars), funded by Google. The 2025 award was given to Charles H. Bennett and Gilles Brassard for quantum information science.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23075,
            "question_text": "Which sport-wise award category was added for the first time in the Arjuna Awards 2024 (conferred 2025)?",
            "option_a": "Kabaddi",
            "option_b": "Yogasana",
            "option_c": "Kho-Kho",
            "option_d": "Mallakhamba",
            "correct_answer": "B",
            "explanation": "Aarti Pal, the reigning national and Asian yogasana champion, became the first yogasana athlete to be recommended for the Arjuna Award in 2024 (conferred January 2025), marking the sport's first inclusion in the national sports awards.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "hard",
            "marks": 1
        },
        {
            "id": 23076,
            "question_text": "Which veteran Indian para-swimmer received the Arjuna Award (Lifetime) in January 2025, becoming India's first Paralympic gold medallist?",
            "option_a": "Devendra Jhajharia",
            "option_b": "Murlikant Petkar",
            "option_c": "Deepa Malik",
            "option_d": "N.S. Thillai Govindaraj",
            "correct_answer": "B",
            "explanation": "Murlikant Petkar, who won India's first Paralympic gold medal at Heidelberg 1972 in swimming (50m freestyle), received the Arjuna Award (Lifetime) in January 2025, recognising his historic contribution to Indian para-sports.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "hard",
            "marks": 1
        },
        {
            "id": 23077,
            "question_text": "Which 2025 Nobel Chemistry laureate is affiliated with the University of California, Berkeley, and has pioneered the design of reticular chemistry?",
            "option_a": "Susumu Kitagawa",
            "option_b": "Richard Robson",
            "option_c": "Omar Yaghi",
            "option_d": "George Whitesides",
            "correct_answer": "C",
            "explanation": "Omar Yaghi (Jordan-American, UC Berkeley) is credited with inventing reticular chemistry — the design of materials with ordered molecular structure by linking molecular building blocks with strong bonds — fundamental to MOF development for which he won the 2025 Nobel Chemistry Prize.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "hard",
            "marks": 1
        },
        {
            "id": 23078,
            "question_text": "Across the Nobel Prizes 2025, which domain had the most laureates sharing the award?",
            "option_a": "Literature",
            "option_b": "Peace",
            "option_c": "Physics (three laureates)",
            "option_d": "Economics (three laureates)",
            "correct_answer": "C",
            "explanation": "Both Physics (Clarke/Devoret/Martinis) and Economics (Mokyr/Aghion/Howitt) had three laureates sharing the award in 2025. Literature and Peace each had a single recipient. The maximum allowed by Nobel statutes is three laureates per prize.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23079,
            "question_text": "The 2025 Grammy for Record of the Year was awarded to 'Not Like Us' — what was the context of this song's creation?",
            "option_a": "A tribute to Hurricane Katrina victims",
            "option_b": "A diss track in the Kendrick Lamar vs. Drake feud",
            "option_c": "An anthem for the Black Lives Matter movement",
            "option_d": "A collaboration with Taylor Swift",
            "correct_answer": "B",
            "explanation": "'Not Like Us' by Kendrick Lamar was a diss track directed at Drake, released during their high-profile rap feud in 2024. The track won Grammy Record of the Year and Song of the Year at the 67th Grammy Awards (February 2025).",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "medium",
            "marks": 1
        },
        {
            "id": 23080,
            "question_text": "Which correct combination links major 2025 awards to their respective winners?",
            "option_a": "Abel Prize 2025 → Terence Tao; Ballon d'Or 2025 → Vinicius Jr.; International Booker 2025 → Arundhati Roy",
            "option_b": "Nobel Peace 2025 → Machado (Venezuela); Grammy Album 2025 → Beyoncé 'Cowboy Carter'; International Booker 2025 → Banu Mushtaq 'Heart Lamp'",
            "option_c": "Nobel Literature 2025 → Haruki Murakami; Oscar Best Picture 2025 → The Brutalist; FIFA Best 2025 → Haaland",
            "option_d": "Pritzker Prize 2025 → Kengo Kuma; Turing Award 2025 → Yann LeCun; Khel Ratna 2025 → Neeraj Chopra",
            "correct_answer": "B",
            "explanation": "Option B correctly states: Nobel Peace 2025 → María Corina Machado (Venezuela); 67th Grammy Album of Year → Beyoncé 'Cowboy Carter'; International Booker 2025 → Banu Mushtaq 'Heart Lamp'. All others are incorrect.",
            "topic": "National_Current_Affairs",
            "folder": "General_Science",
            "difficulty": "hard",
            "marks": 1
        }
    ]

    if USE_POSTGRES:
        sql = """
            INSERT INTO questions
                (id, question_text, option_a, option_b, option_c, option_d,
                 correct_answer, explanation, topic, folder, difficulty)
            VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
            ON CONFLICT (id) DO NOTHING
        """
    else:
        sql = """
            INSERT OR IGNORE INTO questions
                (id, question_text, option_a, option_b, option_c, option_d,
                 correct_answer, explanation, topic, folder, difficulty)
            VALUES (?,?,?,?,?,?,?,?,?,?,?)
        """

    for q in questions:
        cur.execute(sql, (
            q["id"], q["question_text"],
            q["option_a"], q["option_b"], q["option_c"], q["option_d"],
            q["correct_answer"], q["explanation"],
            q["topic"], q["folder"], q["difficulty"]
        ))

    conn.commit()
    cur.close()
    conn.close()
    print(f"[seed_awards_mcq] Inserted {len(questions)} Awards 2025-2026 questions (IDs 23001-23080).")

if __name__ == "__main__":
    seed()
