# seed_polity_ch23.py
# Chapter 23 — Non-Constitutional Bodies
# (రాజ్యాంగేతర సంస్థలు)
# Total Sections: 8 | Total MCQs: 64
# Sections:
#   0 — NITI Aayog (8 MCQs)
#   1 — National Development Council (8 MCQs)
#   2 — Central Vigilance Commission (8 MCQs)
#   3 — Lokpal & Lokayukta (8 MCQs)
#   4 — CBI — Central Bureau of Investigation (8 MCQs)
#   5 — NHRC & NCW (8 MCQs)
#   6 — Zonal Councils & Inter-State Council (8 MCQs)
#   7 — Miscellaneous Non-Constitutional Bodies (8 MCQs)

_CH = 23
_SUBJECT = 'GK'
_TOPIC   = 'Indian_Polity'
_TITLE_TE = 'రాజ్యాంగేతర సంస్థలు'
_TITLE_EN = 'Non-Constitutional Bodies'
_PAGES    = 'Ch.23 (Lakshmikanth)'

_SECTIONS = [
    "NITI ఆయోగ్",
    "జాతీయ అభివృద్ధి మండలి (NDC)",
    "కేంద్రీయ అప్రమత్తత సంఘం (CVC)",
    "లోక్‌పాల్ & లోకాయుక్త",
    "సెంట్రల్ బ్యూరో ఆఫ్ ఇన్వెస్టిగేషన్ (CBI)",
    "NHRC & NCW — మానవ హక్కులు & మహిళా సంఘం",
    "జోనల్ కౌన్సిళ్లు & అంతర్-రాష్ట్ర మండలి",
    "వివిధ రాజ్యాంగేతర సంస్థలు",
]

_MCQS = [    (0,
     'easy',
     'When was NITI Aayog established?\nతెలుగు: NITI ఆయోగ్ ఏర్పాటు తేదీ ఏది?',
     'January 1, 1950 / 1950 జనవరి 1',
     'January 1, 2015 / 2015 జనవరి 1',
     'May 26, 2014 / 2014 మే 26',
     'January 1, 2016 / 2016 జనవరి 1',
     'b',
     'NITI Aayog was set up on January 1, 2015 by executive resolution, replacing the Planning Commission. / NITI (National Institution for Transforming India) Aayog — 1 జనవరి 2015న ప్రారంభించబడింది; ప్రణాళికా సంఘం (Planning Commission) స్థానంలో వచ్చింది.'),
    (0,
     'easy',
     'When was the Planning Commission dissolved?\nతెలుగు: ప్రణాళికా సంఘం (Planning Commission) ఎప్పుడు రద్దు చేయబడింది?',
     '2013',
     '2014',
     '2015',
     '2016',
     'b',
     'Planning Commission dissolved in 2014; NITI Aayog formed in its place on January 1, 2015. / ప్రణాళికా సంఘం (Planning Commission) 2014లో రద్దు చేయబడింది — దాని స్థానంలో 2015 జనవరి 1న NITI ఆయోగ్ ఏర్పాటైంది.'),
    (0,
     'medium',
     'Who is the ex-officio Chairman of NITI Aayog?\nతెలుగు: NITI ఆయోగ్ యొక్క అధ్యక్షుడు ఎవరు?',
     'President / రాష్ట్రపతి',
     'Vice President / ఉపరాష్ట్రపతి',
     'Prime Minister / ప్రధానమంత్రి',
     'Union Finance Minister / కేంద్ర ఆర్థిక మంత్రి',
     'c',
     'PM is the ex-officio Chairman of NITI Aayog. The CEO is appointed by the government. / NITI ఆయోగ్ Chairman = ప్రధానమంత్రి (ex officio). CEO (Chief Executive Officer) ప్రభుత్వం నియమిస్తుంది.'),
    (0,
     'medium',
     'How does NITI Aayog differ from Planning Commission?\nతెలుగు: NITI ఆయోగ్ ప్రణాళికా సంఘం కంటే ఎలా భిన్నంగా ఉంటుంది?',
     'NITI Aayog allocates funds / NITI ఆయోగ్ నిధులు కేటాయించే అధికారం కలిగి ఉంది',
     'NITI Aayog does not allocate funds; it is only a Think Tank / NITI ఆయోగ్ రాష్ట్రాలకు నిధులు మంజూరు చేయదు; ఇది Think Tank మాత్రమే',
     'Planning Commission was constitutional / ప్రణాళికా సంఘం రాజ్యాంగ సంస్థ',
     'NITI Aayog has constitutional status / NITI ఆయోగ్ కి రాజ్యాంగ హోదా ఉంది',
     'b',
     'Planning Commission had fund allocation power. NITI Aayog is a think tank — it does NOT allocate funds. States are partners, not recipients. / ప్రణాళికా సంఘానికి నిధులు కేటాయించే అధికారం ఉండేది. NITI ఆయోగ్ ఒక Think Tank మాత్రమే — నిధులు కేటాయించదు. అది రాష్ట్రాలకు భాగస్వాములుగా వ్యవహరిస్తుంది.'),
    (0,
     'medium',
     'Does NITI Aayog have constitutional status?\nతెలుగు: NITI ఆయోగ్ కి రాజ్యాంగ హోదా ఉందా?',
     'Yes — under Art.263 / అవును — అనుచ్ఛేదం 263 కింద',
     'Yes — under 44th Amendment / అవును — 44వ సవరణ కింద',
     'No — it is set up by executive resolution / లేదు — ఇది కార్యనిర్వాహక తీర్మానం ద్వారా ఏర్పాటైంది',
     'No — set up by Act of Parliament / లేదు — ఇది పార్లమెంట్ చట్టం ద్వారా ఏర్పాటైంది',
     'c',
     'NITI Aayog is NOT constitutional — set up by executive (cabinet) resolution, just like the Planning Commission was in 1950. / NITI ఆయోగ్ రాజ్యాంగ సంస్థ కాదు — ఇది కార్యనిర్వాహక తీర్మానం (Cabinet Resolution) ద్వారా ఏర్పాటైంది. ప్రణాళికా సంఘం కూడా అదే విధంగా ఏర్పాటైంది (1950).'),
    (0,
     'hard',
     "Who are members of NITI Aayog's Governing Council?\nతెలుగు: NITI ఆయోగ్ Governing Council లో ఎవరు సభ్యులు?",
     'Only Union Ministers / కేంద్ర మంత్రులు మాత్రమే',
     'CMs of all states and LG/Administrators of UTs / అన్ని రాష్ట్రాల ముఖ్యమంత్రులు మరియు కేంద్రపాలిత ప్రాంతాల పాలకులు',
     'Experts nominated by President / రాష్ట్రపతి నామినేట్ చేసిన నిపుణులు',
     'Leaders of all parties in Lok Sabha / లోక్\u200cసభ అన్ని పార్టీల నాయకులు',
     'b',
     'Governing Council includes CMs of all states and LGs/Administrators of UTs — promotes cooperative federalism. / NITI Aayog Governing Council లో అన్ని రాష్ట్రాల ముఖ్యమంత్రులు మరియు కేంద్రపాలిత ప్రాంతాల LG/Administrators సభ్యులు. ఇది సహకార సమాఖ్యవాదాన్ని (Cooperative Federalism) ప్రోత్సహిస్తుంది.'),
    (0,
     'medium',
     'Who is the Vice-Chairman of NITI Aayog?\nతెలుగు: NITI ఆయోగ్ లో Vice-Chairman ఎవరు?',
     'Appointed by President / President నియమిస్తారు',
     'Appointed by PM / PM నియమిస్తారు',
     'Elected by Parliament / Parliament ఎన్నుకుంటుంది',
     'Decided by Cabinet Committee / Cabinet committee నిర్ణయిస్తుంది',
     'b',
     'Vice-Chairman of NITI Aayog is appointed by PM and holds the rank of a Cabinet Minister. / NITI Aayog Vice-Chairman ని ప్రధానమంత్రి నియమిస్తారు. VC కి Cabinet Minister హోదా ఉంటుంది. Full-time members కూడా PM నియమిస్తారు.'),
    (0,
     'hard',
     'When was the Planning Commission established?\nతెలుగు: ప్రణాళికా సంఘం ఎప్పుడు ఏర్పాటైంది?',
     '1947',
     '1950',
     '1952',
     '1956',
     'b',
     'Planning Commission was set up in March 1950 by an executive resolution; Nehru was its first Chairman. / ప్రణాళికా సంఘం 1950 మార్చిలో కార్యనిర్వాహక తీర్మానం ద్వారా ఏర్పాటైంది. Jawaharlal Nehru దాని మొదటి Chairman.'),
    (1,
     'easy',
     'When was NDC established?\nతెలుగు: జాతీయ అభివృద్ధి మండలి (NDC) ఎప్పుడు ఏర్పాటైంది?',
     '1950',
     '1952',
     '1956',
     '1960',
     'b',
     'NDC was set up on August 6, 1952 by an executive resolution — not a constitutional body. / NDC (National Development Council) 1952 ఆగస్టు 6న కార్యనిర్వాహక తీర్మానం ద్వారా ఏర్పాటైంది.'),
    (1,
     'easy',
     'Who presides over the NDC?\nతెలుగు: జాతీయ అభివృద్ధి మండలి (NDC) అధ్యక్షత వహించేది ఎవరు?',
     'President / రాష్ట్రపతి',
     'Vice President / ఉపరాష్ట్రపతి',
     'Prime Minister / ప్రధానమంత్రి',
     'NITI Aayog CEO / నీతి ఆయోగ్ CEO',
     'c',
     'PM chairs the NDC. After NITI Aayog was set up, the NDC role was largely taken over by the Governing Council. / NDC అధ్యక్షత ప్రధానమంత్రి వహిస్తారు. NITI ఆయోగ్ Secretary ఇందులో Secretary పాత్ర పోషిస్తారు.'),
    (1,
     'medium',
     'Who are members of NDC?\nతెలుగు: NDC సభ్యులు ఎవరు?',
     'Only Union Ministers / కేంద్ర మంత్రులు మాత్రమే',
     'CMs of all states + Union Cabinet members / అన్ని రాష్ట్రాల ముఖ్యమంత్రులు మరియు కేంద్ర మంత్రిమండలి సభ్యులు',
     'Rajya Sabha members / రాజ్యసభ సభ్యులు',
     'Nominees of Lok Sabha Speaker / లోక్\u200cసభ స్పీకర్ నామినేట్ చేసిన వారు',
     'b',
     'NDC: PM (chair) + Union Cabinet + all State CMs + UTs + NITI Aayog members. / NDC సభ్యులు: ప్రధానమంత్రి (Chairman) + కేంద్ర మంత్రిమండలి + అన్ని రాష్ట్రాల ముఖ్యమంత్రులు + కేంద్రపాలిత ప్రాంతాల పాలకులు + NITI Aayog సభ్యులు.'),
    (1,
     'medium',
     'What is the primary function of NDC?\nతెలుగు: NDC యొక్క ప్రాథమిక విధి ఏమిటి?',
     'To approve economic policies / ఆర్థిక విధానాలు ఆమోదించడం',
     'To approve national plans and review resource mobilisation / జాతీయ ప్రణాళికలు ఆమోదించడం మరియు వనరుల సమీకరణ పరిశీలన',
     'To formulate foreign trade policy / విదేశీ వాణిజ్య విధానాలు రూపొందించడం',
     'To allocate funds to states / రాష్ట్రాలకు నిధులు కేటాయించడం',
     'b',
     "NDC approves national plans; reviews resource mobilisation; NITI Aayog's Governing Council now performs this role. / NDC జాతీయ అభివృద్ధి ప్రణాళికలు ఆమోదిస్తుంది; వనరుల సమీకరణ పరిశీలిస్తుంది; జాతీయ ప్రణాళికపై సిఫారసులు ఇస్తుంది. NITI Aayog రాకతో NDC పాత్ర Governing Council కి బదిలీ అయింది."),
    (1,
     'medium',
     'Does NDC have constitutional status?\nతెలుగు: NDC కి రాజ్యాంగ హోదా ఉందా?',
     'Yes — under Art.263 / అవును — అనుచ్ఛేదం 263 కింద',
     'Yes — under 7th Schedule / అవును — 7వ షెడ్యూల్ కింద',
     'No — it is set up by executive resolution / లేదు — ఇది కార్యనిర్వాహక తీర్మానం ద్వారా ఏర్పాటైంది',
     'Yes — under 86th Amendment / అవును — 86వ సవరణ కింద',
     'c',
     'NDC is NOT constitutional — set up by executive resolution in 1952, just like NITI Aayog. / NDC రాజ్యాంగ సంస్థ కాదు — ఇది 1952లో కార్యనిర్వాహక తీర్మానం ద్వారా ఏర్పాటైంది. NITI Aayog కూడా అదే విధంగా ఏర్పాటైంది.'),
    (1,
     'hard',
     'Which period did the 12th Five Year Plan cover?\nతెలుగు: 12వ పంచవర్ష ప్రణాళిక ఏ కాలానికి?',
     '2007–12',
     '2012–17',
     '2017–22',
     '2022–27',
     'b',
     '12th Five Year Plan: 2012–17. With NITI Aayog (2015), five-year plans were discontinued; 12th Plan was the last. / 12వ పంచవర్ష ప్రణాళిక 2012–17 కాలానికి. NITI Aayog రాకతో 5-year plans రద్దయ్యాయి. 12వ ప్రణాళిక చివరిది.'),
    (1,
     'medium',
     'Which period did the First Five Year Plan cover?\nతెలుగు: మొదటి పంచవర్ష ప్రణాళిక ఏ కాలానికి?',
     '1950–55',
     '1951–56',
     '1952–57',
     '1947–52',
     'b',
     'First FYP: 1951–56 (agriculture & irrigation focused). Nehru was instrumental in its planning. / మొదటి పంచవర్ష ప్రణాళిక 1951–56 కాలానికి. జవహర్\u200cలాల్ నెహ్రూ దీనిని రూపొందించారు. వ్యవసాయం మరియు నీటిపారుదలపై దృష్టి సారించింది.'),
    (1,
     'hard',
     'What is NDC also known as?\nతెలుగు: NDC యొక్క మరో పేరు ఏమిటి?',
     'Cabinet Committee on Economic Affairs',
     'Super Cabinet',
     'Finance Council',
     'Economic Advisory Board',
     'b',
     "NDC is called 'Super Cabinet' as it includes both Union Cabinet ministers and State CMs who deliberate on national planning. / NDC ని 'Super Cabinet' అని కూడా అంటారు ఎందుకంటే ఇందులో కేంద్ర మంత్రులు మరియు రాష్ట్ర ముఖ్యమంత్రులు ఉంటారు — జాతీయ ప్రణాళికపై నిర్ణయాలు తీసుకుంటుంది."),
    (2,
     'easy',
     'When was CVC established?\nతెలుగు: కేంద్రీయ అప్రమత్తత సంఘం (CVC) ఎప్పుడు ఏర్పాటైంది?',
     '1957',
     '1964',
     '1991',
     '2003',
     'b',
     'CVC set up on Feb 11, 1964 on Santhanam Committee recommendations; became statutory in 2003 (CVC Act). / CVC (Central Vigilance Commission) 1964 ఫిబ్రవరి 11న కార్యనిర్వాహక తీర్మానం ద్వారా ఏర్పాటైంది — Santhanam Committee సిఫారసుల మేరకు. 2003లో Statutory body గా మారింది.'),
    (2,
     'easy',
     'Under which Act did CVC become a statutory body?\nతెలుగు: CVC ని ఏ చట్టం ద్వారా Statutory body చేశారు?',
     'CVC Act 1999',
     'CVC Act 2003',
     'Prevention of Corruption Act 1988',
     'CBI Act 1946',
     'b',
     'CVC became a statutory body under the CVC Act 2003, following the Supreme Court directive in the Vineet Narain case (1997). / CVC Act 2003 ద్వారా కేంద్రీయ అప్రమత్తత సంఘాన్ని Statutory body చేశారు. ఇది Supreme Court దిల్లీ హైకోర్టు న్యాయవాది సంఘం కేసు (1997) తర్వాత జరిగింది.'),
    (2,
     'medium',
     'Who appoints the CVC Chairman?\nతెలుగు: CVC Chairman ని ఎవరు నియమిస్తారు?',
     'Prime Minister / ప్రధానమంత్రి',
     'President / రాష్ట్రపతి',
     'Lok Sabha Speaker / లోక్\u200cసభ స్పీకర్',
     'Union Home Minister / కేంద్ర హోం మంత్రి',
     'b',
     'CVC Chairman and 2 VCs appointed by President on recommendation of a committee: PM + Home Minister + LOP (Lok Sabha). / CVC Chairman మరియు ఇద్దరు Vigilance Commissioners ని రాష్ట్రపతి నియమిస్తారు — committee (PM + Home Minister + Lok Sabha Leader of Opposition) సిఫారసు మేరకు.'),
    (2,
     'medium',
     'What is the tenure of CVC Chairman?\nతెలుగు: CVC Chairman పదవీకాలం ఎంత?',
     '4 years or age 60 / 4 సంవత్సరాలు లేదా 60 వయస్సు',
     '4 years or age 65 / 4 సంవత్సరాలు లేదా 65 వయస్సు',
     '5 years or age 65 / 5 సంవత్సరాలు లేదా 65 వయస్సు',
     '6 years or age 65 / 6 సంవత్సరాలు లేదా 65 వయస్సు',
     'b',
     'CVC Chairman tenure: 4 years or age 65, whichever is earlier. / CVC Chairman పదవీకాలం = 4 సంవత్సరాలు లేదా 65 వయస్సు, ఏది ముందు వస్తే అది.'),
    (2,
     'medium',
     "What is CVC's primary function?\nతెలుగు: CVC యొక్క ప్రాథమిక విధి ఏమిటి?",
     'To conduct judicial trials in corruption cases / అవినీతి కేసులలో న్యాయవిచారణ',
     'Superintendence over anti-corruption work in Central Govt / కేంద్ర ప్రభుత్వంలో అవినీతి వ్యతిరేక పర్యవేక్షణ',
     'To investigate state government corruption / రాష్ట్ర ప్రభుత్వాల అవినీతి విచారణ',
     'To manage CBI / CBI నిర్వహణ',
     'b',
     'CVC superintends anti-corruption work in Central Govt and exercises superintendence over CBI (in corruption cases). Not applicable to states. / CVC కేంద్ర ప్రభుత్వంలో అవినీతి వ్యతిరేక పని పర్యవేక్షిస్తుంది; CBI ని పర్యవేక్షిస్తుంది (corruption cases లో). రాష్ట్రాలకు వర్తించదు.'),
    (2,
     'hard',
     'To whom does CVC submit its annual report?\nతెలుగు: CVC తన నివేదికను ఎవరికి సమర్పిస్తుంది?',
     'Prime Minister / ప్రధానమంత్రికి',
     'President / రాష్ట్రపతికి',
     'Lok Sabha Speaker / లోక్\u200cసభ స్పీకర్\u200cకు',
     'Home Minister / హోం మంత్రికి',
     'b',
     'CVC submits its annual report to the President, who lays it before Parliament. / CVC వార్షిక నివేదిక రాష్ట్రపతికి సమర్పించబడుతుంది. రాష్ట్రపతి దానిని Parliament ముందు పెడతారు.'),
    (2,
     'hard',
     'Santhanam Committee was related to?\nతెలుగు: Santhanam Committee దేనికి సంబంధించినది?',
     'Electoral reforms / ఎన్నికల సంస్కరణలు',
     'Prevention of corruption in government / ప్రభుత్వంలో అవినీతి నిరోధం',
     'Panchayati Raj reforms / పంచాయతీ రాజ్ సంస్కరణలు',
     'Civil service reforms / పౌర సేవా సంస్కరణలు',
     'b',
     'K. Santhanam Committee (1962–64) on prevention of corruption in govt recommended CVC, which was set up in 1964. / Santhanam Committee (1962–64) కేంద్ర ప్రభుత్వంలో అవినీతి నిరోధంపై నివేదిక ఇచ్చింది — దాని సిఫారసు మేరకు CVC 1964లో ఏర్పాటైంది.'),
    (2,
     'hard',
     'What type of body is CVC?\nతెలుగు: CVC ఏ రకమైన సంస్థ?',
     'Constitutional body / రాజ్యాంగ సంస్థ',
     'Judicial body / న్యాయిక సంస్థ',
     'Statutory independent body / చట్టబద్ధ సంస్థ — స్వతంత్ర',
     'Executive body / కార్యనిర్వాహక సంస్థ',
     'c',
     'CVC is a statutory independent body (since CVC Act 2003), NOT a constitutional body. / CVC 2003 నుండి Statutory independent body. ఇది Constitutional body కాదు (అనుచ్ఛేదంలో ప్రస్తావన లేదు).'),
    (3,
     'easy',
     'In which year was the Lokpal Act passed?\nతెలుగు: లోక్\u200cపాల్ చట్టం ఏ సంవత్సరంలో ఆమోదించబడింది?',
     '2011',
     '2012',
     '2013',
     '2014',
     'c',
     'The Lokpal and Lokayuktas Act was passed in 2013 and came into force in January 2014. / లోక్\u200cపాల్ మరియు లోకాయుక్తల చట్టం, 2013 (Lokpal and Lokayuktas Act, 2013) — జనవరి 2014లో అమలులోకి వచ్చింది.'),
    (3,
     'easy',
     'At what level does Lokpal function in India?\nతెలుగు: లోక్\u200cపాల్ భారతదేశంలో ఏ స్థాయిలో పని చేస్తుంది?',
     'State level / రాష్ట్ర స్థాయి',
     'District level / జిల్లా స్థాయి',
     'Central level / కేంద్ర స్థాయి',
     'Panchayat level / పంచాయతీ స్థాయి',
     'c',
     'Lokpal works at the central level; Lokayukta works at the state level. / లోక్\u200cపాల్ కేంద్ర స్థాయిలో పని చేస్తుంది; లోకాయుక్త రాష్ట్ర స్థాయిలో పని చేస్తుంది.'),
    (3,
     'medium',
     'What are the qualifications for Lokpal Chairperson?\nతెలుగు: లోక్\u200cపాల్ అధ్యక్షుని అర్హతలు ఏమిటి?',
     'Must be a MP / పార్లమెంట్ సభ్యుడై ఉండాలి',
     'Former CJI or former SC judge or an eminent person / SC మాజీ ప్రధాన న్యాయమూర్తి లేదా SC మాజీ న్యాయమూర్తి లేదా ప్రముఖ వ్యక్తి',
     'IAS officer / IAS అధికారి',
     'Any HC judge / ఏదైనా High Court న్యాయమూర్తి',
     'b',
     'Lokpal Chairperson: former CJI, former SC judge, or a person of eminence with integrity. / లోక్\u200cపాల్ Chairperson = SC మాజీ ప్రధాన న్యాయమూర్తి లేదా SC మాజీ న్యాయమూర్తి లేదా ప్రముఖ వ్యక్తి (eminent person with impeccable integrity).'),
    (3,
     'medium',
     'Maximum members in Lokpal?\nతెలుగు: లోక్\u200cపాల్\u200cలో గరిష్టంగా ఎంత మంది సభ్యులు ఉంటారు?',
     '5',
     '7',
     '8',
     '10',
     'c',
     'Lokpal: 1 Chairperson + max 8 members = 9 total; half judicial, at least half from SC/ST/OBC/minorities/women. / లోక్\u200cపాల్ లో 1 Chairman + గరిష్టంగా 8 సభ్యులు (total 9). సగం న్యాయిక సభ్యులు; సగం లేదా అంతకంటే ఎక్కువ SC/ST/OBC/minority/women.'),
    (3,
     'medium',
     'Who can Lokpal investigate?\nతెలుగు: లోక్\u200cపాల్ ఎవరి మీద దర్యాప్తు చేయగలదు?',
     'Only central govt employees / కేవలం కేంద్ర ప్రభుత్వ ఉద్యోగులు',
     'PM, ministers, MPs and Groups A-D central employees / PM సహా మంత్రులు, MPs, Group A-D కేంద్ర అధికారులు',
     'Only Ministers / కేవలం Ministers మాత్రమే',
     'Including judges / న్యాయమూర్తులు కూడా',
     'b',
     'Lokpal covers PM (with exceptions), ministers, MPs, Group A–D central officers, PSUs, and govt-funded NGOs. / లోక్\u200cపాల్ అధికార పరిధి: PM (కొన్ని మినహాయింపులతో), Ministers, MPs, కేంద్ర ప్రభుత్వ Group A–D అధికారులు, PSUs, NGOs (govt funded).'),
    (3,
     'hard',
     'Who was the first Lokpal of India?\nతెలుగు: మొదటి లోక్\u200cపాల్ ఎవరు?',
     'Justice P. Sathasivam',
     'Justice Pinaki Chandra Ghose',
     'Justice Ruma Pal',
     'Justice J. S. Verma',
     'b',
     "Justice Pinaki Chandra Ghose was appointed India's first Lokpal in March 2019 under the Lokpal and Lokayuktas Act 2013. / Justice Pinaki Chandra Ghose భారత మొదటి లోక్\u200cపాల్ — మార్చి 2019లో నియమించబడ్డారు (Lokpal & Lokayuktas Act 2013 ప్రకారం)."),
    (3,
     'hard',
     'Who enacts Lokayukta laws?\nతెలుగు: లోకాయుక్త చట్టాలు ఎవరు చేయాలి?',
     'Central government / కేంద్ర ప్రభుత్వం',
     'Parliament',
     'State legislatures / రాష్ట్ర శాసనమండళ్లు',
     'President / రాష్ట్రపతి',
     'c',
     'State legislatures enact Lokayukta laws. Maharashtra was the first (1971). 2013 Act mandates states to establish Lokayukta. / లోకాయుక్త చట్టాలు రాష్ట్ర శాసనమండళ్లు చేస్తాయి. 2013 చట్టం రాష్ట్రాలకు లోకాయుక్త నిర్మించమని నిర్దేశిస్తుంది. మహారాష్ట్ర మొదటి రాష్ట్రం (1971).'),
    (3,
     'hard',
     'What is the tenure of Lokpal Chairperson?\nతెలుగు: లోక్\u200cపాల్ Chairman పదవీకాలం ఎంత?',
     '3 years or age 65 / 3 సంవత్సరాలు లేదా 65 వయస్సు',
     '5 years or age 70 / 5 సంవత్సరాలు లేదా 70 వయస్సు',
     '4 years or age 70 / 4 సంవత్సరాలు లేదా 70 వయస్సు',
     '6 years or age 70 / 6 సంవత్సరాలు లేదా 70 వయస్సు',
     'b',
     'Lokpal Chairperson tenure: 5 years or age 70, whichever is earlier. Not eligible for reappointment. / లోక్\u200cపాల్ Chairman పదవీకాలం = 5 సంవత్సరాలు లేదా 70 వయస్సు, ఏది ముందు వస్తే అది.'),
    (4,
     'easy',
     'Under which law was CBI established?\nతెలుగు: CBI ఏ చట్టం కింద ఏర్పాటైంది?',
     'CBI Act 1946',
     'DSPE Act 1946',
     'Prevention of Corruption Act 1988',
     'Police Act 1861',
     'b',
     'CBI was set up under the DSPE Act 1946. It is NOT a constitutional body — it is a statutory body. / CBI (Central Bureau of Investigation) Delhi Special Police Establishment (DSPE) Act 1946 కింద ఏర్పాటైంది. ఇది రాజ్యాంగ సంస్థ కాదు — చట్టబద్ధ సంస్థ.'),
    (4,
     'easy',
     'Under which ministry does CBI function?\nతెలుగు: CBI ఏ మంత్రిత్వ శాఖ పర్యవేక్షణలో ఉంటుంది?',
     'Home Ministry / హోం మంత్రిత్వ శాఖ',
     'Law Ministry / న్యాయ మంత్రిత్వ శాఖ',
     'Ministry of Personnel / సిబ్బంది మంత్రిత్వ శాఖ',
     'Finance Ministry / ఆర్థిక మంత్రిత్వ శాఖ',
     'c',
     'CBI functions under the Ministry of Personnel, Public Grievances and Pensions. / CBI సిబ్బంది, ప్రజా ఫిర్యాదులు మరియు పెన్షన్ మంత్రిత్వ శాఖ (Ministry of Personnel, Public Grievances and Pensions) పర్యవేక్షణలో ఉంటుంది.'),
    (4,
     'medium',
     'What is the tenure of CBI Director?\nతెలుగు: CBI డైరెక్టర్ పదవీకాలం ఎంత?',
     '2 years minimum / 2 సంవత్సరాలు (minimum)',
     '3 years / 3 సంవత్సరాలు',
     '5 years / 5 సంవత్సరాలు',
     "President's discretion / రాష్ట్రపతి విచక్షణ",
     'a',
     'CBI Director: minimum 2-year tenure, extendable to max 5 years (CVC Amendment Act 2021). Fixed tenure established post-Vineet Narain case 1997. / CVC (Amendment) Act 2021 ప్రకారం CBI Director పదవీకాలం కనిష్టంగా 2 సంవత్సరాలు (maximum 5 సంవత్సరాలు వరకు పొడిగించవచ్చు). Vineet Narain కేసు (1997) తర్వాత 2 సంవత్సరాల నిర్ణీత పదవీకాలం ఏర్పాటైంది.'),
    (4,
     'medium',
     'How is CBI Director appointed?\nతెలుగు: CBI డైరెక్టర్ నియామకం ఎలా జరుగుతుంది?',
     'President directly appoints / రాష్ట్రపతి నేరుగా నియమిస్తారు',
     'PM directly appoints / PM నేరుగా నియమిస్తారు',
     'By committee: PM + CJI + LOP (Lok Sabha) / Committee (PM + CJI + LOP Lok Sabha) సిఫారసు మేరకు',
     'Union Home Minister appoints / కేంద్ర హోం మంత్రి నియమిస్తారు',
     'c',
     'CBI Director: appointed by committee — PM + CJI + LOP (Lok Sabha). Lokpal Act 2013 introduced this provision. / CBI Director నియామకం: కమిటీ (ప్రధానమంత్రి + CJI + లోక్\u200cసభలో ప్రతిపక్ష నాయకుడు) సిఫారసు మేరకు. Lokpal Act 2013 ఈ నిబంధన జోడించింది.'),
    (4,
     'medium',
     'What does CBI need to investigate in a state?\nతెలుగు: CBI విచారణ రాష్ట్రంలో జరపాలంటే ఏమి అవసరం?',
     'Central Govt permission / కేంద్ర ప్రభుత్వ అనుమతి',
     'State Govt general or specific consent / రాష్ట్ర ప్రభుత్వ సాధారణ అనుమతి లేదా ప్రత్యేక అనుమతి',
     'No consent needed / అనుమతి అవసరం లేదు',
     'SC order / SC ఆదేశం',
     'b',
     'Under DSPE Act Sec.6, CBI needs state govt consent (general or specific) to operate in a state. Some states have withdrawn general consent. / DSPE Act Sec.6 ప్రకారం రాష్ట్రంలో CBI విచారణకు రాష్ట్ర ప్రభుత్వ అనుమతి (general or specific consent) అవసరం. కొన్ని రాష్ట్రాలు సాధారణ అనుమతి ఉపసంహరించుకున్నాయి.'),
    (4,
     'hard',
     "Which case described CBI as a 'caged parrot'?\nతెలుగు: CBI ని ఏ కేసు 'నిఘా పంజరంలో చిలుక (Caged Parrot)' అని వర్ణించింది?",
     'Vineet Narain Case 1997',
     'Coal Scam Case 2013 (SC observation)',
     'Hawala Case 1996',
     '2G Spectrum Case 2012',
     'b',
     "SC described CBI as a 'caged parrot speaking its master's voice' in 2013 Coal Scam Case, highlighting its lack of independence. / 2013లో Coal Scam Case లో సుప్రీం కోర్టు CBI ని 'నిఘా పంజరంలో చిలుక (Caged Parrot)' అని వర్ణించింది — ప్రభుత్వ నిర్ణయాలను CBI అనుసరిస్తుందని విమర్శించింది."),
    (4,
     'hard',
     'CBI has jurisdiction over:\nతెలుగు: CBI కింది సంస్థల మీద అధికారం కలిగి ఉంటుంది?',
     'All state govt corruption cases / అన్ని రాష్ట్ర ప్రభుత్వ అవినీతి కేసులు',
     'Central List offences, PSU corruption, SC/HC directed cases / Central List లోని నేరాలు, PSU అవినీతి, SC/ST ఆదేశ కేసులు',
     'All cases / అన్ని కేసులు',
     'Only murder cases / కేవలం హత్య కేసులు',
     'b',
     'CBI jurisdiction: central law offences, PSU corruption, court-directed cases, and other notified offences. / CBI అధికార పరిధి: (1) Central Acts కింద నేరాలు, (2) PSU అవినీతి, (3) SC లేదా HC ఆదేశ కేసులు, (4) DSPE Act లో నిర్దేశించిన ఇతర నేరాలు.'),
    (4,
     'hard',
     "What is CBI's anti-corruption unit called?\nతెలుగు: CBI 'Interference with Crime' విచారణ యూనిట్ పేరు ఏమిటి?",
     'ACB — Anti-Corruption Branch',
     'AC — Anti-Corruption Division',
     'BSF Unit',
     'Special Crimes Division',
     'b',
     "CBI's Anti-Corruption Division (AC Division) investigates corruption cases involving central govt officials and PSU employees. / CBI లో Anti-Corruption Division (AC Division) ఉంటుంది — ఇది కేంద్ర ప్రభుత్వ అధికారులు మరియు PSU ఉద్యోగులకు సంబంధించిన అవినీతి కేసులు దర్యాప్తు చేస్తుంది."),
    (5,
     'easy',
     'NHRC was set up under which Act?\nతెలుగు: NHRC ఏ చట్టం కింద ఏర్పాటైంది?',
     'Human Rights Act 1990',
     'Protection of Human Rights Act 1993',
     'Fundamental Rights Act 1950',
     'NHRC Act 2000',
     'b',
     'NHRC was set up under the Protection of Human Rights (PHR) Act 1993 on October 12, 1993. It is statutory, NOT constitutional. / NHRC (National Human Rights Commission) Protection of Human Rights Act 1993 కింద ఏర్పాటైంది — 12 అక్టోబర్ 1993న స్థాపించబడింది. ఇది చట్టబద్ధ సంస్థ — రాజ్యాంగ సంస్థ కాదు.'),
    (5,
     'easy',
     'Who can be NHRC Chairperson?\nతెలుగు: NHRC Chairman అర్హత ఏమిటి?',
     'Retired SC judge / SC మాజీ న్యాయమూర్తి',
     'Retired Chief Justice of India / భారత మాజీ ప్రధాన న్యాయమూర్తి',
     'Retired Chief Justice of HC / High Court మాజీ ప్రధాన న్యాయమూర్తి',
     "PM's discretion / PM నిర్ణయం",
     'b',
     "NHRC Chairperson = retired CJI (before 2019 amendment). Post-2019, any eminent person may be considered. / NHRC Chairperson = భారత మాజీ ప్రధాన న్యాయమూర్తి (Retired CJI). 2019 సవరణ తర్వాత 'eminent persons' కూడా Chairman కాగలరు."),
    (5,
     'medium',
     'NCW was set up under:\nతెలుగు: NCW (National Commission for Women) ఏ చట్టం కింద ఏర్పాటైంది?',
     'NCW Act 1988',
     'NCW Act 1990',
     "Women's Rights Act 1992",
     'Protection of Women Act 1993',
     'b',
     'NCW set up under NCW Act 1990, established January 31, 1992. Statutory, NOT constitutional. / NCW (National Commission for Women) National Commission for Women Act 1990 కింద ఏర్పాటైంది — 31 జనవరి 1992న స్థాపించబడింది. ఇది చట్టబద్ధ సంస్థ — రాజ్యాంగ సంస్థ కాదు.'),
    (5,
     'medium',
     'Can NHRC enforce its recommendations?\nతెలుగు: NHRC తన సిఫారసులను అమలు చేయగలదా?',
     'Yes — can directly enforce / అవును — తన తీర్పులు నేరుగా అమలు చేయగలదు',
     'No — recommendations are advisory; Govt must implement / లేదు — NHRC సిఫారసులు advisory మాత్రమే; Govt అమలు చేయాలి',
     'Yes — but only after SC approval / అవును — కానీ కేవలం SC ఆమోదం తర్వాత',
     'No — NHRC has no recommendation power / లేదు — NHRC కి సిఫారసు అధికారం లేదు',
     'b',
     'NHRC recommendations are advisory only — not court verdicts. If ignored, govt must explain why. / NHRC సిఫారసులు advisory మాత్రమే — court verdicts కావు. ప్రభుత్వం వాటిని అమలు చేయకపోతే, ప్రభుత్వం కారణాలు వివరించాలి.'),
    (5,
     'medium',
     'Within what time period must complaints be filed with NHRC?\nతెలుగు: NHRC Human Rights violations పట్ల ఏ సంవత్సరం వరకు ఫిర్యాదు చేయవచ్చు?',
     '6 months of violation / violation తర్వాత 6 నెలల్లో',
     '1 year of violation / violation తర్వాత 1 సంవత్సరంలో',
     '2 years of violation / violation తర్వాత 2 సంవత్సరాల్లో',
     'No time limit / సమయ పరిమితి లేదు',
     'b',
     'NHRC complaints must be filed within 1 year of the violation. NHRC does NOT investigate complaints against armed forces. / NHRC కి ఫిర్యాదు = violation జరిగిన 1 సంవత్సరం లోపు. NHRC సైనిక దళాలకు సంబంధించిన violations విచారించదు.'),
    (5,
     'hard',
     'Who heads the State Human Rights Commission?\nతెలుగు: State Human Rights Commission (SHRC) Chairman ఎవరు?',
     'Retired CJI / SC మాజీ ప్రధాన న్యాయమూర్తి',
     'Retired Chief Justice of HC / HC మాజీ ప్రధాన న్యాయమూర్తి',
     'Governor / రాష్ట్రపాలకుడు',
     'Chief Minister / రాష్ట్ర ముఖ్యమంత్రి',
     'b',
     'SHRC Chairperson = retired Chief Justice of a HC; appointed by Governor. / SHRC Chairman = రాష్ట్ర HC మాజీ ప్రధాన న్యాయమూర్తి. SHRC రాష్ట్ర స్థాయిలో పని చేస్తుంది; Governor నియమిస్తారు.'),
    (5,
     'hard',
     'Under PHR Act 1993, NHRC CANNOT investigate complaints against:\nతెలుగు: మానవ హక్కుల చట్టం 1993 ప్రకారం NHRC దర్యాప్తు చేయలేని సంస్థ ఏది?',
     'Central Armed Forces / కేంద్ర సాయుధ దళాలు',
     'State Police / రాష్ట్ర పోలీస్',
     'Prison authorities / జైలు అధికారులు',
     'PSU employees / PSU ఉద్యోగులు',
     'a',
     'NHRC cannot investigate armed forces violations — but can seek a report from the Central Govt. / NHRC సాయుధ దళాలకు (armed forces) సంబంధించిన violations విచారించదు — కానీ ఆ విషయంలో ప్రభుత్వానికి నివేదిక పంపవచ్చు.'),
    (5,
     'hard',
     'Who was the first Chairperson of NHRC?\nతెలుగు: NHRC యొక్క మొదటి Chairman ఎవరు?',
     'Justice V. R. Krishna Iyer',
     'Justice Ranganath Misra',
     'Justice M. N. Venkatachaliah',
     'Justice J. S. Verma',
     'b',
     'Justice Ranganath Misra (former CJI) was the first Chairman of NHRC (1993–96). / Justice Ranganath Misra (మాజీ ప్రధాన న్యాయమూర్తి) NHRC మొదటి Chairman — 1993–96 వరకు.'),
    (6,
     'easy',
     'How many Zonal Councils are there in India?\nతెలుగు: భారతదేశంలో ఎన్ని జోనల్ కౌన్సిళ్లు ఉన్నాయి?',
     '3',
     '4',
     '5',
     '6',
     'c',
     'There are 5 Zonal Councils: North, South, East, West, and Central. A Northeast Council exists separately (not one of the 5). / భారతదేశంలో 5 జోనల్ కౌన్సిళ్లు ఉన్నాయి: ఉత్తర, దక్షిణ, తూర్పు, పశ్చిమ, మధ్య. వాటిలో తూర్పు ఈశాన్య జోన్ అదనంగా ఉంది (6వది కాదు).'),
    (6,
     'easy',
     'Zonal Councils were set up under:\nతెలుగు: జోనల్ కౌన్సిళ్లు ఏ చట్టం కింద ఏర్పాటయ్యాయి?',
     'Constitution / రాజ్యాంగం',
     'States Reorganisation Act 1956',
     'Parliament Act 1962',
     'Inter-State Council Act 1990',
     'b',
     'Zonal Councils were set up under the States Reorganisation Act 1956 — hence statutory bodies, NOT constitutional. / జోనల్ కౌన్సిళ్లు States Reorganisation Act 1956 ద్వారా ఏర్పాటయ్యాయి — అందువల్ల ఇవి రాజ్యాంగ సంస్థలు కావు.'),
    (6,
     'medium',
     'Who chairs the Zonal Councils?\nతెలుగు: జోనల్ కౌన్సిళ్ల అధ్యక్షత వహించేది ఎవరు?',
     'CM of a state in the zone / సంబంధిత జోన్ ముఖ్యమంత్రి',
     "President's nominee / రాష్ట్రపతి నామినీ",
     'Union Home Minister / కేంద్ర హోం మంత్రి',
     'Governor of largest state in zone / జోన్\u200cలోని అతి పెద్ద రాష్ట్రం గవర్నర్',
     'c',
     'Union Home Minister is the Chairman of ALL 5 Zonal Councils. / జోనల్ కౌన్సిళ్ల Chairman = కేంద్ర హోం మంత్రి (అన్ని 5 కి).'),
    (6,
     'medium',
     'Which Article provides for Inter-State Council?\nతెలుగు: అంతర్-రాష్ట్ర మండలి (Inter-State Council) ని ఏ అనుచ్ఛేదం నిర్దేశిస్తుంది?',
     'Art.261 / అనుచ్ఛేదం 261',
     'Art.262 / అనుచ్ఛేదం 262',
     'Art.263 / అనుచ్ఛేదం 263',
     'Art.264 / అనుచ్ఛేదం 264',
     'c',
     'Art.263: Provision for Inter-State Council. Established in 1990 by Presidential Order. / అనుచ్ఛేదం 263: Inter-State Council నిర్మాణం. రాష్ట్రపతి ఆదేశం ద్వారా 1990లో స్థాపించబడింది.'),
    (6,
     'medium',
     'Who chairs the Inter-State Council?\nతెలుగు: Inter-State Council అధ్యక్షత వహించేది ఎవరు?',
     'President / రాష్ట్రపతి',
     'Vice President / ఉపరాష్ట్రపతి',
     'Prime Minister / ప్రధానమంత్రి',
     'Union Home Minister / కేంద్ర హోం మంత్రి',
     'c',
     'PM chairs the Inter-State Council. Members: all State CMs + Union Cabinet Ministers. / Inter-State Council Chairman = ప్రధానమంత్రి. సభ్యులు: అన్ని రాష్ట్రాల ముఖ్యమంత్రులు + కేంద్ర మంత్రులు.'),
    (6,
     'hard',
     'The North Eastern Council comes under:\nతెలుగు: ఈశాన్య జోన్ కౌన్సిల్ ఏ చట్టం కింద?',
     'States Reorganisation Act 1956',
     'North Eastern Council Act 1971',
     'Inter-State Council Act 1990',
     'Special Area Act 1963',
     'b',
     'NEC set up under NEC Act 1971; covers 8 northeastern states. / North Eastern Council (NEC) North Eastern Council Act 1971 కింద ఏర్పాటైంది. ఇందులో 8 ఈశాన్య రాష్ట్రాలు (Arunachal, Assam, Manipur, Meghalaya, Mizoram, Nagaland, Sikkim, Tripura) ఉన్నాయి.'),
    (6,
     'hard',
     'Function of ISC under Art.263?\nతెలుగు: అనుచ్ఛేదం 263 కింద Inter-State Council యొక్క విధి ఏమిటి?',
     'Judicially settle disputes between states / రాష్ట్రాల మధ్య వివాదాలు పరిష్కరించడం (judicial)',
     'Discuss and recommend on interstate matters, coordinate policy / రాష్ట్రాల మధ్య చర్చలు, సమన్వయం, సిఫారసులు',
     'Allocate funds to states / రాష్ట్రాలకు నిధులు కేటాయించడం',
     'Determine state boundaries / రాష్ట్రాల సరిహద్దులు నిర్ణయించడం',
     'b',
     'ISC functions: inquire into & advise on interstate disputes, coordinate policy on matters of common interest. / ISC విధులు (Art.263): (1) రాష్ట్రాల మధ్య వివాదాలు చర్చించడం, (2) ఉమ్మడి ఆసక్తి విషయాలు సమన్వయించడం, (3) విధాన సిఫారసులు. ఇది న్యాయ సంస్థ కాదు.'),
    (6,
     'hard',
     'Telangana and Andhra Pradesh are in which Zonal Council?\nతెలుగు: ఏ జోనల్ కౌన్సిల్ లో తెలంగాణ మరియు ఆంధ్రప్రదేశ్ ఉన్నాయి?',
     'North Zone',
     'West Zone',
     'East Zone',
     'South Zone',
     'd',
     'AP and Telangana are in the Southern Zonal Council, along with Karnataka, Kerala, Tamil Nadu, and Puducherry. / తెలంగాణ మరియు ఆంధ్రప్రదేశ్ దక్షిణ జోనల్ కౌన్సిల్ లో ఉన్నాయి. దక్షిణ జోన్: AP, Telangana, Karnataka, Kerala, Tamil Nadu, Puducherry.'),
    (7,
     'easy',
     'Which of these are non-constitutional anti-corruption bodies?\nతెలుగు: భారతదేశంలో ప్రధాన అవినీతి నిరోధక సంస్థలు ఏవి రాజ్యాంగేతరమైనవి?',
     'CAG and UPSC / CAG మరియు UPSC',
     'CVC and CBI / CVC మరియు CBI',
     'ECI and Finance Commission / ECI మరియు Finance Commission',
     'AG and CAG / AG మరియు CAG',
     'b',
     'CVC and CBI are both non-constitutional (statutory) bodies. CAG and UPSC are constitutional bodies. / CVC మరియు CBI రెండూ రాజ్యాంగేతర (non-constitutional) సంస్థలు — statutory bodies. CAG మరియు UPSC రాజ్యాంగ సంస్థలు.'),
    (7,
     'easy',
     "Which is NOT a constitutional body?\nతెలుగు: ఏ సంస్థ 'రాజ్యాంగ సంస్థ' కాదు?",
     'ECI',
     'UPSC',
     'NITI Aayog',
     'Finance Commission',
     'c',
     'NITI Aayog is NOT constitutional — it is by executive resolution. ECI, UPSC, Finance Commission are constitutional. / NITI Aayog రాజ్యాంగ సంస్థ కాదు — ఇది కార్యనిర్వాహక తీర్మానం ద్వారా ఏర్పాటైంది. ECI (Art.324), UPSC (Art.315), Finance Commission (Art.280) రాజ్యాంగ సంస్థలు.'),
    (7,
     'medium',
     'Which body organises the Conference of Governors?\nతెలుగు: భారత రాయబారి సమావేశం ఏ సంస్థ నిర్వహిస్తుంది?',
     'NITI Aayog',
     "President's Secretariat / రాష్ట్రపతి సచివాలయం",
     'PMO',
     'Ministry of External Affairs / విదేశాంగ మంత్రిత్వ శాఖ',
     'b',
     "Conference of Governors is organized by the President's Secretariat with the President presiding. / Conference of Governors రాష్ట్రపతి సచివాలయం నిర్వహిస్తుంది. రాష్ట్రపతి అధ్యక్షత వహిస్తారు."),
    (7,
     'medium',
     "Which of the following is a 'Statutory body'?\nతెలుగు: కింది వాటిలో ఏది 'Statutory body'?",
     'NITI Aayog',
     'NDC',
     'CVC',
     'Planning Commission',
     'c',
     'CVC is statutory (CVC Act 2003). NITI Aayog and NDC are by executive resolution. Planning Commission was also by executive resolution. / CVC Statutory body (CVC Act 2003). NITI Aayog మరియు NDC కార్యనిర్వాహక తీర్మానం ద్వారా, Planning Commission కార్యనిర్వాహక తీర్మానం (1950) ద్వారా ఏర్పాటయ్యాయి.'),
    (7,
     'medium',
     'NDMA is set up under which Act?\nతెలుగు: National Disaster Management Authority (NDMA) ఏ చట్టం కింద?',
     'Disaster Management Act 2003',
     'Disaster Management Act 2005',
     'Environmental Protection Act 1986',
     'Civil Defence Act 1968',
     'b',
     'NDMA is set up under the Disaster Management Act 2005. PM is the ex-officio Chairman. / NDMA (National Disaster Management Authority) Disaster Management Act 2005 కింద ఏర్పాటైంది. PM ex-officio Chairman.'),
    (7,
     'hard',
     'SEBI became statutory in:\nతెలుగు: Securities and Exchange Board of India (SEBI) ఏ సంవత్సరం నుండి Statutory body?',
     '1988',
     '1990',
     '1992',
     '1995',
     'c',
     'SEBI was set up in 1988 by executive order; it became a statutory body under the SEBI Act 1992. / SEBI 1988లో executive order ద్వారా ఏర్పాటైంది; 1992లో SEBI Act ద్వారా Statutory body అయింది.'),
    (7,
     'hard',
     'Enforcement Directorate (ED) works under:\nతెలుగు: Enforcement Directorate (ED) ఏ చట్టం కింద పని చేస్తుంది?',
     'DSPE Act 1946',
     'FEMA 1999 and PMLA 2002 / FEMA 1999 మరియు PMLA 2002',
     'CVC Act 2003',
     'Prevention of Corruption Act 1988',
     'b',
     'ED works primarily under FEMA 1999 and PMLA 2002, under the Revenue Department. / ED (Enforcement Directorate) ముఖ్యంగా FEMA 1999 (Foreign Exchange Management) మరియు PMLA 2002 (Prevention of Money Laundering) కింద పని చేస్తుంది. ఇది Revenue Department కింద ఉంటుంది.'),
    (7,
     'hard',
     'Who appoints SEBI Chairman?\nతెలుగు: SEBI Chairman ని ఎవరు నియమిస్తారు?',
     'President / రాష్ట్రపతి',
     'Central Government / కేంద్ర ప్రభుత్వం',
     'SC',
     'Finance Commission',
     'b',
     'SEBI Chairman is appointed by the Central Government (on recommendation of Finance Ministry). / SEBI Chairman ని కేంద్ర ప్రభుత్వం నియమిస్తుంది (Finance Ministry సిఫారసు మేరకు).'),
]


def _seed_polity_ch23_notes_inner(conn, db_exec_fn, row_to_dict_fn, use_postgres, force=False):
    check = db_exec_fn(conn,
        "SELECT id FROM study_notes WHERE subject=? AND topic=? AND chapter_num=?",
        (_SUBJECT, _TOPIC, _CH))
    row = check.fetchone()
    if row and not force:
        return
    if row and force:
        db_exec_fn(conn, "DELETE FROM study_notes WHERE subject=? AND topic=? AND chapter_num=?",
                   (_SUBJECT, _TOPIC, _CH))
    db_exec_fn(conn,
        """INSERT INTO study_notes
           (subject, topic, chapter_num, chapter_title_te, chapter_title_en, pages_ref, sections_json)
           VALUES (?,?,?,?,?,?,?)""",
        (_SUBJECT, _TOPIC, _CH, _TITLE_TE, _TITLE_EN, _PAGES, json.dumps(_SECTIONS, ensure_ascii=False)))


def _seed_polity_ch23_mcqs_inner(conn, db_exec_fn, row_to_dict_fn, use_postgres):
    import json as _json
    cur = db_exec_fn(conn,
        "SELECT id FROM study_notes WHERE subject=? AND topic=? AND chapter_num=?",
        (_SUBJECT, _TOPIC, _CH))
    note_row = cur.fetchone()
    if not note_row:
        return
    note_id = row_to_dict_fn(note_row)['id']

    diff_map = {"easy": 1, "medium": 2, "hard": 3, "toughest": 4, 1: 1, 2: 2, 3: 3, 4: 4}

    cur2 = db_exec_fn(conn,
        "SELECT COUNT(*) FROM chapter_mcqs WHERE study_note_id=?", (note_id,))
    cnt_row = cur2.fetchone()
    if cnt_row:
        cnt = list(cnt_row)[0]
        if cnt >= len(_MCQS):
            return

    db_exec_fn(conn, "DELETE FROM chapter_mcqs WHERE study_note_id=?", (note_id,))

    for row in _MCQS:
        sec_idx   = row[0]
        diff_str  = row[1]
        q_te      = row[2]
        opt_a     = row[3]
        opt_b     = row[4]
        opt_c     = row[5]
        opt_d     = row[6]
        correct   = row[7]
        expl      = row[8]
        exam_type = row[9] if len(row) > 9 else 'General'
        if exam_type is None:
            exam_type = 'General'
        diff_int  = diff_map.get(diff_str, 2)
        db_exec_fn(conn,
            """INSERT INTO chapter_mcqs
               (study_note_id, section_idx, difficulty, exam_type,
                q_te, opt_a, opt_b, opt_c, opt_d, correct, explanation_te)
               VALUES (?,?,?,?,?,?,?,?,?,?,?)""",
            (note_id, sec_idx, diff_int, exam_type,
             q_te, opt_a, opt_b, opt_c, opt_d, correct, expl))


import json
