import sqlite3, os

SOURCE = 'Science_Set16_Plants'
DB = os.path.join(os.path.dirname(__file__), 'database.db')

questions = [
    (
        'Which of the following statements provides the correct classification of Plant Kingdom\nతెలుగు: కింది వాక్యాలలో ఏది వృక్ష రాజ్యం యొక్క సరైన వర్గీకరణను అందిస్తుంది',
        'Plants can make their own food using CO2 and water in sunlight / మొక్కలు సూర్యరశ్మిలో CO2 మరియు నీటిని ఉపయోగించి తమ స్వంత ఆహారాన్ని తయారు చేసుకోగలవు',
        'Plants are fixed / మొక్కలు స్థిరంగా ఉంటాయి',
        'Plant cells have a firm cell wall made up of cellulose / వృక్ష కణాలు సెల్యులోజ్‌తో తయారైన దృఢమైన కణ కవచాన్ని కలిగి ఉంటాయి (cellulose cell wall)',
        'Plant cells have vacuoles / వృక్ష కణాలు రిక్తికలను కలిగి ఉంటాయి',
        'C',
        'M',
        '',
        1
    ),
    (
        'Which unit is used to measure the concentration of contaminants in soil and sediment\nతెలుగు: నేల మరియు అవక్షేపాలలో కాలుష్య కారకాల గాఢతను కొలవడానికి ఏ యూనిట్‌ను ఉపయోగిస్తారు',
        'PPBB / PPBB (Parts Per Billion by mass)',
        'TDS / TDS (మొత్తం కరిగిన ఘన పదార్థాలు)',
        'DPMO / DPMO',
        'PPM / PPM (Parts Per Million)',
        'A',
        'M',
        '',
        2
    ),
    (
        'Which species of green algae, commonly known as stonewort, is often mistaken for a plant\nతెలుగు: \'స్టోన్‌వోర్ట్\' అని పిలువబడే ఏ ఆకుపచ్చ శైవలం జాతి తరచుగా మొక్కగా పొరబడుతుంది',
        'Chara / కారా (Chara — stonewort)',
        'Kelp / కెల్ప్',
        'Gracilaria / గ్రాసిలేరియా',
        'Sargassum / సర్గస్సం',
        'A',
        'M',
        '',
        3
    ),
    (
        'Photosynthesis involves\nతెలుగు: కిరణజన్య సంయోగక్రియలో ఇమిడి ఉండేది ఏది',
        'Oxidation of H2O and release of O2 / H2O ఆక్సీకరణ మరియు O2 విడుదల',
        'Reduction of CO2 and oxidation of H2O / CO2 క్షయకరణ మరియు H2O ఆక్సీకరణ',
        'Reduction of CO2 and release of O2 / CO2 క్షయకరణ మరియు O2 విడుదల (Reduction of CO2 + release of O2)',
        'Reduction of CO2 oxidation of H2O and release of O2 / CO2 క్షయకరణ, H2O ఆక్సీకరణ మరియు O2 విడుదల',
        'C',
        'M',
        '',
        4
    ),
    (
        'Wood is the common name for\nతెలుగు: కలప అనేది దేనికి సాధారణ పేరు',
        'Vascular bundle / నాళికా పుంజం',
        'Cambium / కాంబియం',
        'Secondary xylem / ద్వితీయ దారువు (secondary xylem)',
        'Secondary phloem / ద్వితీయ పోషక కణజాలం',
        'C',
        'M',
        '',
        5
    ),
    (
        'The stable plant dye is\nతెలుగు: స్థిరమైన వృక్ష రంగు ఏది',
        'Anthocyanin / ఆంథోసైనిన్',
        'Phenol / ఫినాల్',
        'Indigo / ఇండిగో (నీలిమందు / Indigo)',
        'Flavanole / ఫ్లేవనాల్',
        'C',
        'M',
        '',
        6
    ),
    (
        'Eyes of potato are useful for\nతెలుగు: బంగాళదుంప కన్నులు దేనికి ఉపయోగపడతాయి',
        'Nutrition / పోషణ',
        'Respiration / శ్వాసక్రియ',
        'Reproduction / పునరుత్పత్తి',
        'Vegetative propagation / శాఖీయ వ్యాప్తి (vegetative propagation)',
        'D',
        'M',
        '',
        7
    ),
    (
        'Which of the following has been called man\'s most useful tree (per source key)\nతెలుగు: కింది వాటిలో మనిషికి అత్యంత ఉపయోగకరమైన చెట్టుగా దేనిని పిలుస్తారు (కీ ప్రకారం)',
        'Neem / వేప',
        'Walnut / వాల్నట్',
        'Teak / టేకు (Teak — per source key)',
        'Coconut / కొబ్బరి (కల్పవృక్షం)',
        'C',
        'M',
        'Source key marks Teak; many references call Coconut "Kalpavriksha" — most useful tree.',
        8
    ),
    (
        'Which of the following grows under the soil (under the plant)\nతెలుగు: కింది వాటిలో ఏది భూమిలోపల పెరుగుతుంది',
        'Castor / ఆముదం',
        'Peanuts / వేరుశెనగ (Peanuts — geocarpic)',
        'Bengal gram / శెనగలు',
        'Cabbage / క్యాబేజీ',
        'B',
        'M',
        '',
        9
    ),
    (
        'Jaggery, a source of sugar, is a liquid obtained from the developing flower bud of\nతెలుగు: తాటి బెల్లం దేని అభివృద్ధి చెందుతున్న పూల మొగ్గ నుండి లభిస్తుంది',
        'Sugar beet / షుగర్ బీట్',
        'Sugar cane / చెరకు',
        'Palm tree / తాటి చెట్టు (palm tree)',
        'Sugar maple / షుగర్ మాపుల్',
        'C',
        'M',
        '',
        10
    ),
    (
        'The age of a tree can be determined more or less accurately by\nతెలుగు: చెట్టు వయస్సును దాదాపుగా కచ్చితంగా దేని ద్వారా నిర్ణయించవచ్చు',
        'Measuring the diameter of the trunk / మొండెపు వ్యాసాన్ని కొలవడం',
        'Measuring the height of the tree / చెట్టు ఎత్తును కొలవడం',
        'Counting the number of annual rings in the trunk / వార్షిక వలయాల సంఖ్యను లెక్కించడం (annual rings)',
        'Counting the number of branches / కొమ్మల సంఖ్యను లెక్కించడం',
        'C',
        'M',
        '',
        11
    ),
    (
        'The biotic relationship between insects and plants with reference to pollination is termed as\nతెలుగు: పరాగసంపర్కానికి సంబంధించి కీటకాలు మరియు మొక్కల మధ్య ఉండే జీవ సంబంధాన్ని ఏమంటారు',
        'Saprophytism / పూతికాహారత్వం',
        'Parasitism / పరాన్నజీవత్వం',
        'Mutualism / అన్యోన్యాశ్రయం (Mutualism)',
        'Commensalism / కమెన్సలిజం',
        'C',
        'M',
        '',
        12
    ),
    (
        'If all plants of the world die, then all the animals will die due to\nతెలుగు: ప్రపంచంలోని మొక్కలన్నీ చనిపోతే, జంతువులన్నీ దేని కారణంగా చనిపోతాయి',
        'Shortage of air / గాలి కొరత',
        'Shortage of food / ఆహార కొరత',
        'Shortage of oxygen / ఆక్సిజన్ కొరత (shortage of oxygen)',
        'Excess of carbon dioxide / కార్బన్ డైయాక్సైడ్ అధికం',
        'C',
        'M',
        'Per source key. Note: shortage of food (B) is also a defensible answer.',
        13
    ),
    (
        'Which of the following chemicals is directly responsible for the shedding of a leaf from a plant\nతెలుగు: మొక్క నుండి ఆకు రాలిపోవడానికి కింది ఏ రసాయనం ప్రత్యక్షంగా కారణమవుతుంది',
        'Acetic Acid / ఎసిటిక్ ఆమ్లం',
        'Indole-3-Acetic Acid / ఇండోల్-3-ఎసిటిక్ ఆమ్లం (IAA = ఆక్సిన్)',
        'Abscisic Acid / అబ్సిసిక్ ఆమ్లం (Abscisic Acid — leaf abscission)',
        'Carbonic Acid / కార్బోనిక్ ఆమ్లం',
        'C',
        'M',
        '',
        14
    ),
    (
        'Flowerless plants, naked seeds, needle-like leaves and cones as reproductive structure are characteristics of\nతెలుగు: పూలు పూయని మొక్కలు, నగ్న విత్తనాలు, సూది లాంటి ఆకులు మరియు శంకువులు ఉండటం వేటి లక్షణాలు',
        'Angiosperms / ఆవృతబీజాలు',
        'Pteridophyta / టెరిడోఫైటా',
        'Gymnosperms / వివృతబీజాలు (Gymnosperms — naked seeds + cones)',
        'Bryophyta / బ్రయోఫైటా',
        'C',
        'M',
        '',
        15
    ),
    (
        'Which of the following is not a tuber crop\nతెలుగు: కింది వాటిలో దుంప పంట కానిది ఏది',
        'Groundnut / వేరుశెనగ (Groundnut — legume, not tuber)',
        'Sugar beet / షుగర్ బీట్',
        'Tapioca / కర్రపెండలం',
        'Sweet potato / చిలగడదుంప',
        'A',
        'M',
        '',
        16
    ),
    (
        'Which of the following pests attack(s) rice crop\nతెలుగు: కింది ఏ తెగుళ్ళు వరి పంటను ఆశిస్తాయి',
        'Stem borer / కాండం తొలిచే పురుగు',
        'Gundhi Bug / గుంధి బగ్',
        'American bollworm / అమెరికన్ బోల్‌వార్మ్',
        'Both (a) and (b) / (a) మరియు (b) రెండూ (Stem borer + Gundhi bug)',
        'D',
        'M',
        '',
        17
    ),
    (
        'Plants that grow on salty soils are\nతెలుగు: ఉప్పు నేలల్లో పెరిగే మొక్కలను ఏమంటారు',
        'Homophytes / హోమోఫైట్స్',
        'Hydrophytes / హైడ్రోఫైట్స్ (నీటి మొక్కలు)',
        'Xerophytes / జెరోఫైట్స్ (ఎడారి మొక్కలు)',
        'Halophytes / హాలోఫైట్స్ (Halophytes — salt-tolerant)',
        'D',
        'M',
        '',
        18
    ),
    (
        'Which of the following elements is not essential for plant growth\nతెలుగు: మొక్కల పెరుగుదలకు కింది వాటిలో ఏ మూలకం అవసరం లేదు',
        'Sodium / సోడియం (Sodium — not essential for most plants)',
        'Potassium / పొటాషియం',
        'Magnesium / మెగ్నీషియం',
        'Calcium / కాల్షియం',
        'A',
        'M',
        '',
        19
    ),
    (
        'A plant can grow where there are\nతెలుగు: ఏవి ఉన్నచోట మొక్క పెరగగలదు',
        'Light and water / కాంతి మరియు నీరు',
        'Light, water, and air / కాంతి, నీరు మరియు గాలి (light + water + air)',
        'Light and air / కాంతి మరియు గాలి',
        'Light, water, and soil / కాంతి, నీరు మరియు నేల',
        'B',
        'M',
        'Plants can grow in hydroponics without soil — needs light, water, air. Soil is not strictly required.',
        20
    ),
    (
        'Which of the following plants is effective in reducing water pollution and is also useful for producing biogas\nతెలుగు: కింది వాటిలో ఏ మొక్క నీటి కాలుష్యాన్ని తగ్గించడంలో ప్రభావవంతం, బయోగ్యాస్ ఉత్పత్తికి కూడా ఉపయోగపడుతుంది',
        'Lotus / తామర',
        'Eucalyptus / యూకలిప్టస్',
        'Salvinia / సాల్వినియా',
        'Water hyacinth / గుర్రపుడెక్క (Water hyacinth)',
        'D',
        'M',
        '',
        21
    ),
    (
        'Which of the following are the primary elements required by plants to complete their growth\nతెలుగు: మొక్కల పెరుగుదల పూర్తి కావడానికి అవసరమైన ప్రాథమిక మూలకాలు ఏవి',
        'Oxygen, phosphorus, potassium / O, P, K',
        'Sulphur, iron, magnesium / S, Fe, Mg',
        'Nitrogen, phosphorus, potassium / N, P, K (NPK = primary)',
        'Hydrogen, oxygen, phosphorus / H, O, P',
        'C',
        'M',
        '',
        22
    ),
    (
        'Plants are killed in winter by frost because\nతెలుగు: శీతాకాలంలో మంచు కారణంగా మొక్కలు చనిపోతాయి, ఎందుకంటే',
        'There is no transpiration / భాష్పోత్సేకం జరగదు',
        'No photosynthesis takes place at such low temperatures / తక్కువ ఉష్ణోగ్రతల వద్ద కిరణజన్య సంయోగక్రియ జరగదు',
        'Respiration ceases at such low temperatures / తక్కువ ఉష్ణోగ్రతల వద్ద శ్వాసక్రియ ఆగుతుంది',
        'Of desiccation and mechanical damage to tissues / కణజాలాల ఎండిపోవడం మరియు యాంత్రిక నష్టం (desiccation + mechanical damage)',
        'D',
        'M',
        '',
        23
    ),
    (
        'Which of the following fertilizers contains all the nutrients essential for crops\nతెలుగు: కింది ఎరువులలో ఏది పంటలకు అవసరమైన అన్ని పోషకాలను కలిగి ఉంటుంది',
        'DAP (Diammonium phosphate) / డైఅమ్మోనియం ఫాస్ఫేట్ (N+P only)',
        'Urea / యూరియా (N only)',
        'Superphosphate / సూపర్ ఫాస్ఫేట్ (P only)',
        'Compost / కంపోస్ట్ (Compost — all nutrients)',
        'D',
        'M',
        '',
        24
    ),
    (
        'Veins in a leaf are\nతెలుగు: ఆకులోని ఈనెలు',
        'As the skeleton of the leaf / ఆకు అస్థిపంజరంగా',
        'For the protection of vascular bundles / నాళికా పుంజాల రక్షణకు',
        'For the conduction of food / ఆహార ప్రసరణకు',
        'All of these / ఇవన్నీ (All — skeleton + protection + conduction)',
        'D',
        'M',
        '',
        25
    ),
    (
        'Plants absorb from the soil\nతెలుగు: మొక్కలు నేల నుండి దేనిని గ్రహిస్తాయి',
        'Capillary water / కేశనాళికా జలం (Capillary water)',
        'Gravitational water / గురుత్వాకర్షణ జలం',
        'Hygroscopic water / హైగ్రోస్కోపిక్ నీరు',
        'None of these / ఇవేవీ కావు',
        'A',
        'M',
        '',
        26
    ),
    (
        'Which of the following plants bears seeds but no fruits\nతెలుగు: కింది వాటిలో విత్తనాలను కలిగి ఉండి, పండ్లను ఇవ్వని మొక్క ఏది',
        'Eucalyptus / యూకలిప్టస్',
        'Peepal / రావి చెట్టు',
        'Pine / పైన్ చెట్టు (Pine — gymnosperm)',
        'Cotton / పత్తి',
        'C',
        'M',
        '',
        27
    ),
    (
        'The fastest growing tree (per source key) is\nతెలుగు: అత్యంత వేగంగా పెరిగే చెట్టు ఏది (కీ ప్రకారం)',
        'Arecanut / వక్క',
        'Mango / మామిడి',
        'Eucalyptus / యూకలిప్టస్ (Eucalyptus — per key)',
        'Coconut / కొబ్బరి',
        'C',
        'M',
        'Bamboo (a grass) is fastest among plants overall, but among given trees Eucalyptus is fastest.',
        28
    ),
    (
        'The largest flower in the world is that of\nతెలుగు: ప్రపంచంలోనే అతిపెద్ద పువ్వు దేనిది',
        'Lotus / తామర',
        'Rafflesia / రఫ్లీషియా (Rafflesia — up to 1 m diameter)',
        'Giant cactus / జెయింట్ కాక్టస్',
        'None of these / ఇవేవీ కావు',
        'B',
        'M',
        '',
        29
    ),
    (
        'Pineapple is a\nతెలుగు: పైనాపిల్ (అనాస పండు) అనేది',
        'Single fruit / ఒకే పండు',
        'Collection of fruits / పండ్ల సమూహం (సంయుక్త ఫలం / multiple fruit)',
        'Single seed / ఒకే విత్తనం',
        'Collection of leaves / ఆకుల సమూహం',
        'B',
        'M',
        '',
        30
    ),
    (
        'The part of the cinchona plant which yields quinine is\nతెలుగు: క్వినైన్ ను ఉత్పత్తి చేసే సింకోనా మొక్క భాగం ఏది',
        'Root / వేరు',
        'Leaf / ఆకు',
        'Flower / పువ్వు',
        'Bark / బెరడు (Bark — yields quinine)',
        'D',
        'M',
        '',
        31
    ),
    (
        'Nitrogen is utilized by the plant in the form of\nతెలుగు: నైట్రోజన్‌ను మొక్క ఏ రూపంలో వినియోగించుకుంటుంది',
        'Free nitrogen / స్వేచ్ఛా నైట్రోజన్',
        'Nitrite / నైట్రైట్',
        'Nitrate / నైట్రేట్ (Nitrate — main absorbed form)',
        'Ammonia / అమ్మోనియా',
        'C',
        'M',
        '',
        32
    ),
    (
        'Which of the following is an epiphytic plant\nతెలుగు: కింది వాటిలో వృక్షోపజీవి (ఎపిఫైటిక్) ఏది',
        'Mould / బూజు',
        'Mushroom / పుట్టగొడుగు',
        'Orchid / ఆర్కిడ్ (Orchid — epiphyte on tree bark)',
        'Bacteria / బ్యాక్టీరియా',
        'C',
        'M',
        '',
        33
    ),
    (
        'The unit of classification of plants and animals is\nతెలుగు: మొక్కలు మరియు జంతువుల వర్గీకరణకు ప్రాథమిక ప్రమాణం ఏది',
        'Class / తరగతి',
        'Genus / ప్రజాతి',
        'Order / క్రమం',
        'Species / జాతి (Species — basic unit)',
        'D',
        'M',
        '',
        34
    ),
    (
        'For plant metabolism, calcium, magnesium, and sulphur are (per source key)\nతెలుగు: కాల్షియం, మెగ్నీషియం మరియు సల్ఫర్ అనేవి (కీ ప్రకారం)',
        'Macro nutrients / స్థూల పోషకాలు (per source key)',
        'Micro nutrients / సూక్ష్మ పోషకాలు',
        'Trace nutrients / అతిసూక్ష్మ పోషకాలు',
        'Secondary nutrients / ద్వితీయ పోషకాలు',
        'A',
        'M',
        'Technically Ca, Mg, S are SECONDARY macronutrients. Source key marks them as macro nutrients.',
        35
    ),
    (
        'Bamboo is a\nతెలుగు: వెదురు అనేది',
        'Grass / గడ్డి (Grass — Poaceae family)',
        'Herb / మూలిక',
        'Shrub / పొద',
        'Tree / చెట్టు',
        'A',
        'M',
        '',
        36
    ),
    (
        'Which crop has the highest photosynthetic activity\nతెలుగు: అత్యధిక కిరణజన్య సంయోగక్రియ కార్యకలాపం కలిగిన పంట ఏది',
        'Rice / వరి',
        'Wheat / గోధుమ',
        'Cotton / పత్తి',
        'Sugarcane / చెరకు (Sugarcane — C4 plant)',
        'D',
        'M',
        '',
        37
    ),
    (
        'The first step in the photosynthetic process is\nతెలుగు: కిరణజన్య సంయోగక్రియ ప్రక్రియలో మొదటి దశ ఏమిటి',
        'Release of oxygen from water / నీటి నుండి O2 విడుదల',
        'Excitation of chlorophyll by sunlight / సూర్యరశ్మి ద్వారా క్లోరోఫిల్ ఉత్తేజితం (chlorophyll excitation)',
        'Fixation of CO2 / CO2 స్థిరీకరణ',
        'Formation of carbohydrates / కార్బోహైడ్రేట్ల ఏర్పాటు',
        'B',
        'M',
        '',
        38
    ),
    (
        'Match: A. Sclerenchyma  B. Xylem  C. Phloem  D. Meristem with 1. Conduction of water  2. Transport of food  3. Mechanical strength  4. Cell division  5. Carbon assimilation\nతెలుగు: A. దృఢ కణజాలం  B. దారువు  C. పోషక కణజాలం  D. విభాజ్య కణజాలం — 1.నీటి ప్రసరణ 2.ఆహార రవాణా 3.యాంత్రిక బలం 4.కణ విభజన',
        'A-1, B-4, C-3, D-5',
        'A-2, B-5, C-4, D-1',
        'A-3, B-1, C-2, D-4 (Sclerenchyma=strength, Xylem=water, Phloem=food, Meristem=division)',
        'A-4, B-2, C-5, D-3',
        'C',
        'M',
        '',
        39
    ),
    (
        'The tree requiring minimum water for its growth is\nతెలుగు: పెరగడానికి అతి తక్కువ నీరు అవసరమయ్యే చెట్టు ఏది',
        'Babul / తుమ్మ చెట్టు (Babul — desert/arid tolerant)',
        'Eucalyptus / యూకలిప్టస్',
        'Mango / మామిడి',
        'Guava / జామ',
        'A',
        'M',
        '',
        40
    ),
    (
        'Which components of light are absorbed by chlorophyll\nతెలుగు: క్లోరోఫిల్ ద్వారా కాంతిలోని ఏ రంగులు గ్రహించబడతాయి',
        'Violet and red / వైలెట్ మరియు ఎరుపు',
        'Indigo and orange / ఇండిగో మరియు ఆరెంజ్',
        'Blue and red / నీలం మరియు ఎరుపు (Blue + Red absorbed; reflects green)',
        'Violet and yellow / వైలెట్ మరియు పసుపు',
        'C',
        'M',
        '',
        41
    ),
    (
        'Gases (oxygen and carbon dioxide) reach aquatic animals and plants from the atmosphere through\nతెలుగు: వాతావరణం నుండి O2/CO2 వాయువులు జలచరాలకు దేని ద్వారా చేరుతాయి',
        'Condensation / సాంద్రీకరణం',
        'Evaporation / బాష్పీభవనం',
        'Sublimation / ఉత్పతనం',
        'Diffusion / వ్యాపనం (Diffusion — gases dissolve into water)',
        'D',
        'M',
        '',
        42
    ),
    (
        'If pollination takes place without opening of the flower, it is referred to as\nతెలుగు: పువ్వు విచ్చుకోకుండానే పరాగసంపర్కం జరిగితే దానిని ఏమంటారు',
        'Autogamy / ఆటోగామి (self-pollination general)',
        'Cleistogamy / క్లైస్టోగామి (Cleistogamy — flower stays closed)',
        'Allogamy / అల్లోగామి (cross-pollination)',
        'Chasmogamy / ఛాస్మోగామి (open flower self-pollination)',
        'B',
        'M',
        '',
        43
    ),
    (
        'From which part of the plant is turmeric obtained\nతెలుగు: మొక్క యొక్క ఏ భాగం నుండి పసుపును పొందుతారు',
        'Stem / కాండం (Stem — rhizome / underground stem)',
        'Root / వేరు',
        'Flower / పువ్వు',
        'Fruit / పండు',
        'A',
        'M',
        '',
        44
    ),
    (
        'Identify the element that helps to trap light energy essential for photosynthesis\nతెలుగు: కిరణజన్య సంయోగక్రియకు అవసరమైన కాంతి శక్తిని గ్రహించడంలో సహాయపడేది ఏది',
        'Cristae / క్రిస్టే',
        'Amyloplasts / అమిలోప్లాస్ట్స్',
        'Carotenoid / కెరోటినాయిడ్ (Carotenoid — accessory pigment)',
        'Vacuoles / రిక్తికలు',
        'C',
        'M',
        '',
        45
    ),
    (
        'The process of photosynthesis is most active in\nతెలుగు: కిరణజన్య సంయోగక్రియ ఏ కాంతిలో అత్యంత చురుకుగా జరుగుతుంది',
        'White light / తెలుపు కాంతి',
        'Green light / ఆకుపచ్చ కాంతి',
        'Red light / ఎరుపు కాంతి (Red light — peak absorption in red)',
        'Blue light / నీలం కాంతి',
        'C',
        'M',
        '',
        46
    ),
    (
        'Which of the following plants bears non-endospermous seeds (per source key)\nతెలుగు: అంకురచ్ఛద రహిత విత్తనాలు కలిగిన మొక్క ఏది (కీ ప్రకారం)',
        'Coconut / కొబ్బరి (endospermous)',
        'Pea / బఠానీ (also non-endospermous)',
        'Mustard / ఆవాలు (Mustard — per source key)',
        'Groundnut / వేరుశెనగ (also non-endospermous)',
        'C',
        'M',
        'Pea, Mustard, Groundnut are all dicots with non-endospermous seeds. Source key picks Mustard.',
        47
    ),
    (
        'Plant which yields fiber as well as edible fruits is\nతెలుగు: ఫైబర్‌తో పాటు తినదగిన పండ్లను ఇచ్చే మొక్క ఏది',
        'Cotton / పత్తి',
        'Sunflower / పొద్దుతిరుగుడు',
        'Papaya / బొప్పాయి',
        'Banana / అరటి (Banana — fiber + edible fruit)',
        'D',
        'M',
        '',
        48
    ),
    (
        'Ginger is a stem and not a root because\nతెలుగు: అల్లం వేరు కాదు, ఒక కాండం, ఎందుకంటే',
        'It stores food material / ఆహార పదార్థాన్ని నిల్వ చేస్తుంది',
        'It grows horizontally in the soil / మట్టిలో అడ్డంగా పెరుగుతుంది',
        'It has nodes and internodes / కణుపులు మరియు కణుపు మధ్యమాలు ఉన్నాయి (nodes and internodes)',
        'It lacks chlorophyll / దీనిలో క్లోరోఫిల్ ఉండదు',
        'C',
        'M',
        '',
        49
    ),
    (
        'Match algae types: A. Blue-green algae  B. Red algae  C. Green algae  D. Brown algae with I. Sargassum  II. Chlamydomonas  III. Rhodophyta  IV. Cyanobacteria\nతెలుగు: A.నీలి-ఆకుపచ్చ B.ఎర్ర C.ఆకుపచ్చ D.గోధుమ — I.సర్గస్సం II.క్లామిడోమోనాస్ III.రోడోఫైటా IV.సైనోబ్యాక్టీరియా',
        'A-I, B-II, C-III, D-IV',
        'A-I, B-III, C-II, D-IV',
        'A-IV, B-III, C-II, D-I (BGA=Cyanobacteria, Red=Rhodophyta, Green=Chlamydomonas, Brown=Sargassum)',
        'A-III, B-IV, C-II, D-I',
        'C',
        'M',
        '',
        50
    ),
]
