# seed_polity_ch21.py
# Chapter 21 — High Courts & Subordinate Courts
# Total Sections: 8 | Total MCQs: 56
# Sections:
#   0 — Establishment & Composition of High Courts (7 MCQs)
#   1 — Appointment & Removal of HC Judges (8 MCQs)
#   2 — Original Jurisdiction of HC (7 MCQs)
#   3 — Appellate Jurisdiction of HC (7 MCQs)
#   4 — Writ Jurisdiction — Art.226 (7 MCQs)
#   5 — Supervisory & Other Powers (7 MCQs)
#   6 — Subordinate Courts (6 MCQs)
#   7 — Miscellaneous / Key Articles (7 MCQs)

_CH = 21
_SUBJECT = 'GK'
_TOPIC   = 'Indian_Polity'
_TITLE_TE = 'హైకోర్టులు & అధీన న్యాయస్థానాలు'
_TITLE_EN = 'High Courts & Subordinate Courts'
_PAGES    = 'Ch.21 (Lakshmikanth)'

_SECTIONS = [
    "హైకోర్టుల స్థాపన & కూర్పు",
    "HC న్యాయమూర్తుల నియామకం & తొలగింపు",
    "HC మూల అధికార పరిధి",
    "HC అప్పీలేట్ అధికార పరిధి",
    "రిట్ అధికార పరిధి — అనుచ్ఛేదం 226",
    "పర్యవేక్షణ & ఇతర అధికారాలు",
    "అధీన న్యాయస్థానాలు",
    "విభిన్న కీలక అనుచ్ఛేదాలు",
]

_MCQS = [    (0,
     'easy',
     'Which Article establishes High Courts?\nతెలుగు: హైకోర్టుల స్థాపనను ప్రస్తావించే అనుచ్ఛేదం ఏది?',
     'Art.212 / అనుచ్ఛేదం 212',
     'Art.214 / అనుచ్ఛేదం 214',
     'Art.226 / అనుచ్ఛేదం 226',
     'Art.231 / అనుచ్ఛేదం 231',
     'b',
     'Art.214: There shall be a High Court for each State. / Art.214: ప్రతి రాష్ట్రానికి హైకోర్టు ఉంటుంది.'),
    (0,
     'easy',
     'Retirement age of HC judges?\nతెలుగు: హైకోర్టు న్యాయమూర్తుల పదవీ విరమణ వయస్సు ఎంత?',
     '60 years / 60 సంవత్సరాలు',
     '62 years / 62 సంవత్సరాలు',
     '65 years / 65 సంవత్సరాలు',
     '70 years / 70 సంవత్సరాలు',
     'b',
     'HC judges retire at 62; SC judges at 65. / HC న్యాయమూర్తులు 62 సంవత్సరాలకు పదవీ విరమణ చేస్తారు; SC న్యాయమూర్తులు 65 సంవత్సరాలకు.'),
    (0,
     'medium',
     'HC provisions are in which Articles?\nతెలుగు: రాజ్యాంగం ప్రకారం హైకోర్టుల పరిధి (Part VI) ఏ అనుచ్ఛేదాల నుండి?',
     'Art.200 నుండి Art.215 వరకు',
     'Art.214 నుండి Art.231 వరకు',
     'Art.124 నుండి Art.147 వరకు',
     'Art.168 నుండి Art.212 వరకు',
     'b',
     'HC provisions: Part VI (States), Art.214–231. / HC కి సంబంధించిన అంశాలు Part VI లో Art.214 నుండి Art.231 వరకు ఉంటాయి.'),
    (0,
     'medium',
     'Which Article allows common HC for two or more states?\nతెలుగు: రెండు రాష్ట్రాలకు ఉమ్మడి హైకోర్టు ఏర్పాటు చేయడానికి ఏ అనుచ్ఛేదం?',
     'Art.214',
     'Art.231',
     'Art.226',
     'Art.222',
     'b',
     'Art.231: Parliament may establish a common HC for two or more states (e.g., Guwahati HC for NE states). / Art.231: పార్లమెంట్ రెండు లేదా అంతకు మించిన రాష్ట్రాలకు ఉమ్మడి హైకోర్టు స్థాపించవచ్చు.'),
    (0,
     'medium',
     "Which Article declares HC as Court of Record?\nతెలుగు: హైకోర్టు 'Court of Record' అని ఏ అనుచ్ఛేదం చెప్తుంది?",
     'Art.214',
     'Art.215',
     'Art.216',
     'Art.217',
     'b',
     "Art.215: HC is a Court of Record with power of contempt of court. / Art.215: హైకోర్టు 'Court of Record' — దాని తీర్పులు శాశ్వతంగా నమోదవుతాయి మరియు contempt of court అధికారం ఉంది."),
    (0,
     'hard',
     'Who determines the strength of HC judges?\nతెలుగు: హైకోర్టు న్యాయమూర్తుల సంఖ్యను ఎవరు నిర్ణయిస్తారు?',
     'Chief Minister / రాష్ట్ర ముఖ్యమంత్రి',
     'HC Chief Justice / హైకోర్టు ప్రధాన న్యాయమూర్తి',
     'President of India / రాష్ట్రపతి',
     'Parliament / పార్లమెంట్',
     'c',
     'Art.216: President determines the strength of each HC. / హైకోర్టు న్యాయమూర్తుల సంఖ్యను రాష్ట్రపతి నిర్ణయిస్తారు (Art.216).'),
    (0,
     'medium',
     'HC Chief Justice takes oath before?\nతెలుగు: హైకోర్టు ప్రధాన న్యాయమూర్తి ప్రమాణ స్వీకారం ఎవరి ముందు జరుగుతుంది?',
     'Chief Minister / ముఖ్యమంత్రి',
     'President / రాష్ట్రపతి',
     'Governor / గవర్నర్',
     'CJI / భారత ప్రధాన న్యాయమూర్తి',
     'c',
     'Art.219: HC judges take oath before the Governor of the state. / Art.219: HC న్యాయమూర్తులు గవర్నర్ ముందు ప్రమాణ స్వీకారం చేస్తారు.'),
    (0,
     'hard',
     'HCs existing under HC Acts continue under Constitution — which Article?\nతెలుగు: HC Acts (పాత HC చట్టాలు) కింద ఉన్న HCలు రాజ్యాంగం ద్వారా కొనసాగుతున్నాయి — ఏ అనుచ్ఛేదం?',
     'Art.214',
     'Art.215',
     'Art.225',
     'Art.231',
     'c',
     "Art.225: Jurisdiction, powers, authority and law administered by existing HCs shall continue subject to Parliament's law. / Art.225: హైకోర్టు ప్రస్తుతం ఉన్న అధికార పరిధి, అధికారాలు మరియు విధానం కొనసాగుతాయి (Letters Patent Acts మరియు పాత HC చట్టాలు కింద)."),
    (1,
     'easy',
     'Who appoints HC judges?\nతెలుగు: హైకోర్టు న్యాయమూర్తులను ఎవరు నియమిస్తారు?',
     'Governor / గవర్నర్',
     'Chief Minister / ముఖ్యమంత్రి',
     'President / రాష్ట్రపతి',
     'CJI / భారత ప్రధాన న్యాయమూర్తి',
     'c',
     'Art.217: HC judges appointed by President after consulting CJI, Governor, and HC Chief Justice. / Art.217: హైకోర్టు న్యాయమూర్తులను రాష్ట్రపతి నియమిస్తారు — CJI, రాష్ట్ర గవర్నర్, HC ప్రధాన న్యాయమూర్తిని సంప్రదించిన తర్వాత.'),
    (1,
     'medium',
     'Collegium for HC judge appointment?\nతెలుగు: HC న్యాయమూర్తి నియామకానికి కొలీజియంలో ఎంత మంది ఉంటారు?',
     'CJI + 4 SC judges / CJI + 4 SC న్యాయమూర్తులు',
     'CJI + 2 senior SC judges / CJI + 2 SC సీనియర్ న్యాయమూర్తులు',
     'CJI + HC CJ + constitutional judge / CJI + HC CJ + రాజ్యాంగ న్యాయమూర్తి',
     'CJI alone / CJI మాత్రమే',
     'b',
     'For HC appointments: CJI + 2 senior SC judges (3-member collegium). / HC న్యాయమూర్తుల నియామకానికి: CJI + 2 సీనియర్ SC న్యాయమూర్తులు (3-member collegium). SC నియామకానికి 5-member.'),
    (1,
     'medium',
     'Qualifications for HC judge appointment (Art.217)?\nతెలుగు: హైకోర్టు న్యాయమూర్తి నియామకానికి అర్హతలు ఏమిటి?',
     '25 సంవత్సరాల వయస్సు; 5 సంవత్సరాల HC అనుభవం',
     'భారత పౌరుడు; HC న్యాయమూర్తిగా 10 సం. లేదా HC అడ్వకేట్\u200cగా 10 సం.',
     'భారత పౌరుడు; HC అడ్వకేట్\u200cగా 5 సం.',
     '30 సంవత్సరాల వయస్సు; జిల్లా జడ్జి అనుభవం',
     'b',
     'Art.217: Must be citizen + HC judge for 10 years OR HC advocate for 10 years. / Art.217: (1) భారత పౌరుడు; (2) HC న్యాయమూర్తిగా 10 సంవత్సరాలు లేదా HC అడ్వకేట్\u200cగా 10 సంవత్సరాలు. వయస్సు పరిమితి లేదు.'),
    (1,
     'medium',
     'Transfer of HC judge between HCs?\nతెలుగు: HC న్యాయమూర్తిని ఒక HC నుండి మరొక HC కి బదిలీ చేయడానికి ఏ అనుచ్ఛేదం?',
     'Art.218',
     'Art.220',
     'Art.222',
     'Art.224',
     'c',
     'Art.222: President may transfer HC judge to another HC after consulting CJI. / Art.222: CJI సంప్రదింపు తర్వాత రాష్ట్రపతి HC న్యాయమూర్తిని ఒక HC నుండి మరొక HC కి బదిలీ చేయగలరు.'),
    (1,
     'hard',
     'Where can a retired HC judge practice?\nతెలుగు: పదవీ విరమణ తర్వాత HC న్యాయమూర్తి ఏ కోర్టులో వాదించవచ్చు?',
     'Any court / ఏ కోర్టులో అయినా',
     'Only in SC / కేవలం SC లో',
     'Not in that HC or subordinate courts; may in SC/other HCs / ఆ రాష్ట్ర HC లేదా దాని అధీన కోర్టులలో కాదు; కానీ SC లో లేదా ఇతర HCలలో వాదించవచ్చు',
     'Cannot practice anywhere / ఎక్కడా వాదించలేదు',
     'c',
     'Art.220: Retired HC judge cannot plead in that HC or its subordinate courts; may in SC or other HCs. / Art.220: HC న్యాయమూర్తి పదవీ విరమణ తర్వాత తాను పనిచేసిన HC లో లేదా దాని అధీన కోర్టులలో వాదించలేరు. SC లో లేదా ఇతర HCలలో వాదించవచ్చు.'),
    (1,
     'medium',
     'Removal of HC judge — same as SC judge?\nతెలుగు: HC న్యాయమూర్తి తొలగింపు విధానం SC న్యాయమూర్తి వలె ఉంటుందా?',
     'No, through state assembly / కాదు, రాష్ట్ర అసెంబ్లీ ద్వారా',
     'Yes, same procedure / అవును, అదే విధానం',
     'No, Governor removes / కాదు, గవర్నర్ తొలగిస్తారు',
     'No, on SC order / కాదు, SC ఆదేశంపై',
     'b',
     "HC judge removal same as SC — special majority of Parliament + President's order. / HC న్యాయమూర్తి తొలగింపు SC న్యాయమూర్తి వలె అదే — పార్లమెంట్ ప్రత్యేక మెజారిటీ + రాష్ట్రపతి ఆదేశం (Art.217 read with Art.124(4))."),
    (1,
     'hard',
     'Who decides age dispute of HC judge (Art.217(3))?\nతెలుగు: HC న్యాయమూర్తి నియామకానికి Art.217(3) ప్రకారం వయస్సు వివాదం ఎవరు నిర్ణయిస్తారు?',
     'SC',
     'President / రాష్ట్రపతి',
     'CJI',
     'HC Chief Justice / HC ప్రధాన న్యాయమూర్తి',
     'c',
     "Art.217(3): If dispute arises as to age of HC judge, CJI's decision is final. / Art.217(3): HC న్యాయమూర్తి వయస్సు గురించి ఏదైనా వివాదం తలెత్తితే CJI నిర్ణయం తుది నిర్ణయం."),
    (1,
     'medium',
     'When is an Acting CJ appointed for HC?\nతెలుగు: Acting Chief Justice HC లో ఎప్పుడు నియమించబడతారు?',
     'When CJ dies / CJ మరణించినప్పుడు',
     'When CJ is absent/unable to perform / CJ అనారోగ్యం, సెలవు లేదా ఇతర కారణాలతో లేనప్పుడు',
     'When HC is dissolved / HC మసిలిపోయినప్పుడు',
     "On Law Minister's direction / చట్ట మంత్రి ఆదేశంపై",
     'b',
     "Art.223: President may appoint HC judge as Acting CJ when CJ's office is vacant or CJ is absent/unable to perform. / Art.223: CJ అందుబాటులో లేనప్పుడు రాష్ట్రపతి HC న్యాయమూర్తులలో ఒకరిని Acting CJ గా నియమించవచ్చు."),
    (2,
     'easy',
     'HC original jurisdiction?\nతెలుగు: హైకోర్టు మూల అధికార పరిధి (Original Jurisdiction) దేనిపై?',
     'Only criminal matters / కేవలం నేర విషయాలు',
     'Only tax disputes / కేవలం పన్ను వివాదాలు',
     'Matrimonial, probate, insolvency, admiralty, constitutional matters / వివాహం, వీలునామా, దివాళా, నౌకాయానం, రాజ్యాంగ విషయాలు',
     'Only SC appeals / కేవలం SC కి అప్పీల్',
     'c',
     'HC original jurisdiction varies by state; Calcutta, Bombay, Madras HCs have original jurisdiction in matrimonial, probate, insolvency, admiralty, constitutional matters. / HC మూల అధికార పరిధి రాష్ట్రం బట్టి మారుతుంది — ముఖ్యంగా Calcutta, Bombay, Madras HCలు వివాహ, వీలునామా, దివాళా, నౌకాయానం విషయాలలో మూల అధికార పరిధి కలిగి ఉన్నాయి.'),
    (2,
     'medium',
     'Does HC have original jurisdiction in election matters?\nతెలుగు: హైకోర్టుకు ఎన్నికల విషయాలలో మూల అధికార పరిధి ఉంటుందా?',
     'No / కాదు',
     'Yes — MPs, MLAs elections / అవును — MP, MLA ఎన్నికలపై',
     'Only President election / కేవలం రాష్ట్రపతి ఎన్నికపై',
     'Only local body elections / కేవలం స్థానిక సంస్థ ఎన్నికలపై',
     'b',
     'Art.329: Election disputes regarding MPs and MLAs are heard by HC through election petitions. / Art.329: MP మరియు MLA ఎన్నికలకు సంబంధించిన వివాదాలు HC లో Election Petition ద్వారా పరిష్కారమవుతాయి.'),
    (2,
     'medium',
     'Is Art.226 writ jurisdiction part of HC original jurisdiction?\nతెలుగు: Art.226 కింద రిట్ అధికార పరిధి HC మూల అధికార పరిధిలో భాగమా?',
     'No / కాదు',
     'Yes / అవును',
     'Partially / కొంత భాగం మాత్రమే',
     'Only on SC direction / SC ఆదేశం మేరకు మాత్రమే',
     'b',
     "Art.226 writ power is part of HC's original jurisdiction — wider than SC's (Art.32). / Art.226 కింద రిట్ జారీ చేసే అధికారం HC మూల అధికార పరిధిలో భాగం — ఇది ప్రాథమిక హక్కులతో పాటు ఇతర చట్టపరమైన హక్కులకూ వర్తిస్తుంది."),
    (2,
     'hard',
     'Which HCs have original commercial jurisdiction?\nతెలుగు: ఏ రాష్ట్రాల HCలు వాణిజ్య (Commercial) విషయాలలో మూల అధికార పరిధి కలిగి ఉన్నాయి?',
     'All High Courts / అన్ని హైకోర్టులు',
     'Calcutta, Bombay, Madras / Calcutta, Bombay, Madras (ఆంగ్లో చట్టంపై ఆధారపడి)',
     'Delhi and Bombay HCs / ఢిల్లీ మరియు Bombay HCలు',
     'None / ఏ హైకోర్టుకూ లేదు',
     'b',
     'Calcutta, Bombay, Madras HCs have original commercial jurisdiction based on their Letters Patent/Charter. / Calcutta, Bombay, Madras HCలు చారిత్రకంగా (Letters Patent) మూల వాణిజ్య అధికార పరిధి కలిగి ఉన్నాయి.'),
    (2,
     'medium',
     'What does Art.228 provide?\nతెలుగు: Art.228 ప్రకారం HC ఏ అధికారాన్ని కలిగి ఉంది?',
     'HC అప్పీలేట్ అధికార పరిధి',
     'HC సూపర్వైజరీ అధికారం',
     'రాజ్యాంగ ప్రశ్న ఉంటే దిగువ కోర్టు కేసులను HC కి బదిలీ చేయడం',
     'HC contempt అధికారం',
     'c',
     'Art.228: HC may withdraw case from subordinate court involving constitutional question and decide it or return it after deciding the constitutional issue. / Art.228: దిగువ కోర్టులో విచారణలో ఉన్న కేసులో రాజ్యాంగ ప్రశ్న తలెత్తితే HC ఆ కేసును తన దగ్గరికి తీసుకోవచ్చు లేదా రాజ్యాంగ ప్రశ్నను నిర్ణయించి వాపసు పంపవచ్చు.'),
    (2,
     'medium',
     'HC contempt power?\nతెలుగు: హైకోర్టు contempt of court అధికారం ఏ అనుచ్ఛేదం?',
     'Art.214',
     'Art.215',
     'Art.226',
     'Art.227',
     'b',
     "Art.215: As a Court of Record, HC has power to punish for contempt. / Art.215: HC 'Court of Record' హోదా ప్రకారం contempt of court అధికారం కలిగి ఉంది."),
    (2,
     'hard',
     'What are Letters Patent Appeals?\nతెలుగు: Letters Patent Appeals (LPAs) అంటే ఏమిటి?',
     'Appeals from SC to HC / SC నుండి HC కి అప్పీళ్ళు',
     'Appeal from single HC judge to division bench within same HC / HC single judge నిర్ణయానికి వ్యతిరేకంగా HC division bench కి అప్పీల్',
     'SC appeals / SC అప్పీళ్ళు',
     'Appeal from HC to Admin tribunal / HC నుండి అడ్మినిస్ట్రేటివ్ ట్రిబ్యునల్\u200cకు అప్పీల్',
     'b',
     'LPAs: Appeal from single HC judge to HC division bench within same HC (mainly in Calcutta, Bombay, Madras, Allahabad). / LPAs: HC single judge తీర్పుపై అదే HC division bench కి అప్పీల్ — ముఖ్యంగా Calcutta, Bombay, Madras, Allahabad HCలలో.'),
    (2,
     'medium',
     'Does HC have original jurisdiction in revenue matters?\nతెలుగు: రెవిన్యూ విషయాలలో HC కి మూల అధికార పరిధి ఉంటుందా?',
     'Yes, in all HCs / అవున, అన్ని HCలలో',
     'No — Constitution does not give this / కాదు — రాజ్యాంగం ప్రత్యేకంగా ఇవ్వలేదు',
     'Yes under Art.226 / అవున, Art.226 కింద',
     'Yes under Art.131 / అవున, Art.131 కింద',
     'b',
     'Art.225 proviso: Original jurisdiction of HCs (other than Letters Patent HCs) in Revenue matters is not preserved by Constitution. / Art.225: రాజ్యాంగ ప్రభావంతో HC లకు రెవిన్యూ విషయాలలో మూల అధికార పరిధి తొలగించబడింది — ఉన్న Letters Patent HCలకు తప్ప (Calcutta, Bombay, Madras).'),
    (3,
     'easy',
     'HC appellate jurisdiction covers?\nతెలుగు: హైకోర్టు అప్పీలేట్ అధికార పరిధి ఏ విషయాలలో ఉంది?',
     'Only criminal matters / కేవలం నేర విషయాలు',
     'Civil and criminal matters / సివిల్ మరియు నేర విషయాలలో',
     'Only tax matters / కేవలం పన్ను విషయాలు',
     'Only constitutional matters / కేవలం రాజ్యాంగ విషయాలు',
     'b',
     'HC appellate jurisdiction covers both civil and criminal matters — from subordinate courts. / HC అప్పీలేట్ అధికార పరిధి సివిల్ మరియు నేర విషయాలలో ఉంది — దిగువ కోర్టుల తీర్పులపై.'),
    (3,
     'medium',
     'Criminal appeals to HC?\nతెలుగు: HC కి నేర (Criminal) అప్పీల్\u200cలో ఏ విషయాలు వస్తాయి?',
     'Only cases with 7+ year imprisonment / 7 సంవత్సరాల కంటే ఎక్కువ జైలు శిక్ష కేసులు మాత్రమే',
     'Sessions court judgments + death sentence orders / Sessions court తీర్పులపై + మరణ శిక్ష నిర్ణయాలు',
     'All magistrate judgments / అన్ని మేజిస్ట్రేట్ తీర్పులు',
     'Only from SC / కేవలం SC నుండి అప్పీళ్ళు',
     'b',
     'HC criminal appellate: appeals from Sessions courts; HC must confirm death sentences. / HC నేర అప్పీలేట్ అధికార పరిధి: Sessions court తీర్పులపై, మరణ శిక్ష నిర్ణయాలను ధృవీకరించడానికి HC విచారిస్తుంది.'),
    (3,
     'medium',
     'Civil appeals to HC from?\nతెలుగు: HC సివిల్ అప్పీల్ ఏ కోర్టుల తీర్పులపై?',
     'Only from District Courts / కేవలం జిల్లా కోర్టుల నుండి',
     'All civil courts / అన్ని సివిల్ కోర్టుల నుండి',
     'Only from tribunals / కేవలం ట్రిబ్యునల్స్ నుండి',
     'From District and subordinate civil courts / జిల్లా కోర్టులు మరియు జిల్లా స్థాయి సివిల్ కోర్టుల నుండి',
     'd',
     'HC civil appellate: from District Court and subordinate civil courts. / HC సివిల్ అప్పీలేట్ అధికార పరిధి: జిల్లా కోర్టులు మరియు దాని దిగువ సివిల్ కోర్టుల తీర్పులపై.'),
    (3,
     'medium',
     'When can HC judgment be appealed to SC?\nతెలుగు: HC తీర్పుకు వ్యతిరేకంగా SC కి ఎప్పుడు అప్పీల్ చేయవచ్చు?',
     'Always / ఎల్లప్పుడూ',
     'With HC certificate or SLP (Art.136) / HC ఇచ్చే ధృవీకరణ పత్రం (Certificate) తో లేదా SLP (Art.136) ద్వారా',
     'Without SC permission / SC అనుమతి లేకుండా',
     "Only on President's order / రాష్ట్రపతి ఆదేశంతో మాత్రమే",
     'b',
     'From HC to SC: with HC certificate (Art.132/133/134) or SLP under Art.136. / HC తీర్పు నుండి SC కి అప్పీల్ HC certificate (Art.132, 133, 134) తో లేదా SC వద్ద SLP (Art.136) దాఖలు చేయవచ్చు.'),
    (3,
     'hard',
     'If HC refuses certificate, what is the remedy?\nతెలుగు: HC తీర్పుపై SC కి Certificate of Appeal ఇవ్వడానికి HC నిరాకరిస్తే ఏమి చేయాలి?',
     'No appeal possible / అప్పీల్ సాధ్యం కాదు',
     'Petition to President / రాష్ట్రపతికి పిటిషన్',
     'File SLP under Art.136 / Art.136 కింద SLP దాఖలు',
     'Complain to Parliament / పార్లమెంట్\u200cకు ఫిర్యాదు',
     'c',
     'If HC refuses certificate, party may file SLP under Art.136 — SC has discretion to admit or reject. / HC Certificate నిరాకరించినా SC Art.136 కింద SLP దాఖలు చేయవచ్చు — SC స్వంత విచక్షణతో అప్పీల్ అంగీకరించవచ్చు లేదా తిరస్కరించవచ్చు.'),
    (3,
     'medium',
     'Automatic appeal to SC when HC sentences death?\nతెలుగు: HC మొదటిసారి నేరం నిరూపించి మరణ శిక్ష విధిస్తే SC కి ఆటోమేటిగ్ అప్పీల్ ఉంటుందా?',
     'Yes under Art.134 / అవును, Art.134 కింద',
     'No, only SLP / కాదు, SLP మాత్రమే',
     'Yes under Art.132 / అవును, Art.132 కింద',
     'No, HC certificate needed / కాదు, HC Certificate కావాలి',
     'a',
     'Art.134(1)(a): Automatic appeal to SC when HC reverses acquittal and awards death sentence. / Art.134: HC Sessions Court నిర్ణయాన్ని తిప్పికొట్టి నేరంగా మరణ శిక్ష విధించినప్పుడు SC కి ఆటోమేటిగ్ అప్పీల్ ఉంటుంది.'),
    (3,
     'medium',
     'Standard for civil appeal to SC under Art.133?\nతెలుగు: Art.133 కింద సివిల్ అప్పీల్ SC కి వెళ్ళడానికి ఏ ప్రమాణం?',
     'HC certificate only / HC ఆమోదం మాత్రమే',
     'HC certifies substantial question of law / HC చట్టం యొక్క ముఖ్యమైన ప్రశ్న అని ధ్రువీకరిస్తే',
     'Based on amount involved / విచారణలో ఎంత మొత్తం ఉంటే',
     'Always can appeal / ఎల్లప్పుడూ SC కి వెళ్ళవచ్చు',
     'b',
     "Art.133: Civil appeals to SC require HC certificate that it involves a substantial question of law of general importance. / Art.133: సివిల్ అప్పీళ్ళు — HC ధ్రువీకరిస్తే SC కి వెళ్ళవచ్చు — 'substantial question of law of general importance' అని నిరూపించాలి."),
    (3,
     'hard',
     'What is needed for Art.132 appeal from HC to SC?\nతెలుగు: Art.132 కింద HC నుండి SC అప్పీల్\u200cకు ఏ ప్రమాణం అవసరం?',
     'Religious question / మతపరమైన ప్రశ్న',
     'Constitutional interpretation question in judgment — HC certification / రాజ్యాంగపరమైన అర్థ నిర్వచన ప్రశ్న తీర్పు — HC ధ్రువీకరణ',
     'State interests involved / విచారణలో రాష్ట్ర ప్రయోజనాలు ఉంటే',
     'Amount over 2 lakhs / 2 లక్షలకు మించిన మొత్తం',
     'b',
     "Art.132: Appeal to SC from HC if HC certifies that the case involves a substantial question of law as to interpretation of the Constitution. / Art.132: సివిల్, నేర, లేదా ఇతర కేసుల్లో HC తీర్పు 'రాజ్యాంగ అర్థ నిర్వచనం' యొక్క ముఖ్యమైన ప్రశ్నకు సంబంధించినదని HC ధ్రువీకరిస్తే SC కి అప్పీల్ వెళ్ళవచ్చు."),
    (4,
     'easy',
     'HC writ jurisdiction?\nతెలుగు: హైకోర్టు రిట్ అధికార పరిధి ఏ అనుచ్ఛేదం కింద?',
     'Art.32',
     'Art.224',
     'Art.226',
     'Art.227',
     'c',
     "Art.226: HC may issue writs for FR enforcement + any other purpose (wider than SC's Art.32). / Art.226: HC ప్రాథమిక హక్కులకు + ఇతర చట్టపరమైన హక్కులకు కూడా రిట్ జారీ చేయగలదు."),
    (4,
     'medium',
     'Key difference between Art.226 and Art.32?\nతెలుగు: Art.226 (HC రిట్) మరియు Art.32 (SC రిట్) లో మూలభూత తేడా ఏమిటి?',
     'HC issues more types of writs / HC ఎక్కువ రిట్ రకాలు జారీ చేయగలదు',
     'Art.226 for FR + other legal rights; Art.32 only for FR / Art.226 ప్రాథమిక హక్కులతో పాటు ఇతర చట్టపరమైన హక్కులకు కూడా వర్తిస్తుంది; Art.32 ప్రాథమిక హక్కులకు మాత్రమే',
     'Only HC issues Habeas Corpus / HC మాత్రమే Habeas Corpus జారీ చేయగలదు',
     'Art.32 is wider / Art.32 విస్తృతమైనది',
     'b',
     "Art.226 wider: HC issues writs for FR + any other purpose; Art.32 only for FR violations. / Art.226 విస్తృతమైనది: ప్రాథమిక హక్కులతో పాటు 'ఏ ఇతర ప్రయోజనానికైనా' రిట్ జారీ చేయగలదు. Art.32 కేవలం ప్రాథమిక హక్కుల ఉల్లంఘనపై మాత్రమే."),
    (4,
     'medium',
     'Can HC issue writs against private individuals under Art.226?\nతెలుగు: HC Art.226 కింద ప్రైవేట్ వ్యక్తులపై రిట్ జారీ చేయగలదా?',
     'Yes, always / అవును, ఎల్లప్పుడూ',
     'No, only against govt authorities / కాదు, కేవలం ప్రభుత్వ అధికారులపై మాత్రమే',
     'Limited — specific writs like Quo Warranto / కొంత మేరకు — Quo Warranto వంటి నిర్దిష్ట సందర్భాలలో',
     'No, must go to tribunal / కాదు, ట్రిబ్యునల్\u200cకు వెళ్ళాలి',
     'c',
     'Writs generally against state/govt authorities; Quo Warranto can extend to private individuals holding public office. / సాధారణంగా రిట్లు ప్రభుత్వ అధికారులు మరియు సంస్థలపై జారీ అవుతాయి. Quo Warranto మాత్రం ప్రభుత్వ పదవిలో ఉన్న ప్రైవేట్ వ్యక్తులపై కూడా వర్తించవచ్చు.'),
    (4,
     'hard',
     'Can HC issue writs against authorities outside its territorial jurisdiction?\nతెలుగు: Art.226(2) ప్రకారం HC అధికార పరిధి లేని ప్రభుత్వ అధికారులపై రిట్ జారీ చేయగలదా?',
     'No, impossible / కాదు, అసాధ్యం',
     "Yes, if cause of action arose within HC's jurisdiction / అవును, కారణ సంఘటన HC అధికార పరిధిలో జరిగితే",
     'Yes, always / అవును, ఎల్లప్పుడూ',
     'No, only SC / కాదు, SC మాత్రమే చేయగలదు',
     'b',
     'Art.226(2): HC may issue writs even against authorities outside its territory if cause of action arose (wholly or partly) within its jurisdiction. / Art.226(2): రిట్ కారణం (cause of action) HC అధికార పరిధిలో పూర్తిగా లేదా పాక్షికంగా జరిగితే HC ఆ అధికార పరిధి వెలుపల ఉన్న అధికారులపై కూడా రిట్ జారీ చేయగలదు.'),
    (4,
     'medium',
     'Who can petition for Habeas Corpus?\nతెలుగు: Habeas Corpus రిట్ ఎవరికి జారీ అవుతుంది?',
     'Only the detained person / కేవలం నిర్బంధించబడిన వ్యక్తి',
     'Anyone on behalf of detainee (relative, friend, PIL) / ఎవరైనా (బంధువు, స్నేహితుడు, ప్రజా ప్రయోజన వ్యాజ్యం)',
     'Only a lawyer / కేవలం న్యాయవాది',
     'Only government / కేవలం ప్రభుత్వం',
     'b',
     'Habeas Corpus: can be filed by anyone on behalf of the detainee — relative, friend, or via PIL. / Habeas Corpus: నిర్బంధించబడిన వ్యక్తి తరపున ఎవరైనా కోర్టుకు వెళ్ళవచ్చు — బంధువులు, స్నేహితులు లేదా PIL ద్వారా.'),
    (4,
     'medium',
     'If HC rejects writ petition, remedy in SC?\nతెలుగు: రిట్ పిటిషన్ HC తిరస్కరిస్తే SC కి ఏ మార్గం ఉంది?',
     'No remedy / ఏ మార్గమూ లేదు',
     'Can go directly to SC under Art.32 / Art.32 కింద SC కి నేరుగా వెళ్ళవచ్చు',
     'Appeal to President / రాష్ట్రపతికి అప్పీల్',
     'Only Art.136 SLP / Art.136 SLP మాత్రమే',
     'b',
     'If HC rejects writ, can still file under Art.32 in SC (for FR) or SLP under Art.136. / HC రిట్ పిటిషన్ తిరస్కరించినా Art.32 కింద SC కి నేరుగా వెళ్ళవచ్చు (ప్రాథమిక హక్కుల విషయంలో) లేదా Art.136 SLP దాఖలు చేయవచ్చు.'),
    (4,
     'medium',
     'Does filing writ in HC bar direct SC petition?\nతెలుగు: రిట్ కోసం HC లో దాఖలు చేయడం SC ని నేరుగా సంప్రదించే హక్కును తొలగిస్తుందా?',
     'Yes, cannot file in both / అవును, ఒకే విషయంపై రెండూ కాదు',
     'No, can still file in SC / కాదు, ఒకే సమయంలో SC కి Art.32 కింద కూడా వెళ్ళవచ్చు',
     'Yes, SC permission needed / అవును, SC అనుమతి అవసరం',
     'Yes but only Art.136 SLP / అవును, కానీ Art.136 SLP మాత్రమే',
     'b',
     "Filing in HC does not bar SC petition — SC may ask party to exhaust HC remedy first but it's not mandatory. / పార్టీ HC లో రిట్ దాఖలు చేసినా SC Art.32 కింద లేదా Art.136 SLP ద్వారా వేరుగా వెళ్ళవచ్చు — SC ముందుగా HC ని ప్రయత్నించమని చెప్పవచ్చు (exhaustion of remedies)."),
    (4,
     'hard',
     'HC writ under Art.226 can be issued against whom?\nతెలుగు: Art.226 కింద HC రిట్ — ఏ సంస్థలకు వ్యతిరేకంగా జారీ చేయవచ్చు?',
     'Only government officials / ప్రభుత్వ అధికారులకు మాత్రమే',
     'Government authorities AND any person or authority / ప్రభుత్వ అధికారులు మరియు ఏ వ్యక్తి లేదా సంస్థకైనా',
     'Only state government / కేవలం రాష్ట్ర ప్రభుత్వానికి',
     'Only in FR violation cases / ప్రాథమిక హక్కుల ఉల్లంఘన కేసుల్లో మాత్రమే',
     'b',
     "Art.226 is wider — HC can issue writs to any person/authority for any purpose; Art.32 (SC) only for enforcement of Fundamental Rights. / Art.226: SC Art.32 కన్నా విస్తృతమైనది — HC ఏ వ్యక్తి లేదా అధికారానికైనా (ప్రభుత్వ అధికారి కాకపోయినా) 'ఏ ప్రయోజనం కోసమైనా' రిట్ జారీ చేయవచ్చు. Art.32 ప్రాథమిక హక్కుల అమలు మాత్రమే."),
    (5,
     'easy',
     'HC supervisory jurisdiction?\nతెలుగు: హైకోర్టు పర్యవేక్షణ అధికారం (Supervisory Jurisdiction) ఏ అనుచ్ఛేదం కింద?',
     'Art.224',
     'Art.225',
     'Art.226',
     'Art.227',
     'd',
     'Art.227: HC has superintendence over all courts and tribunals in its territory (except military courts). / Art.227: HC దాని పరిధిలోని అన్ని కోర్టులు మరియు ట్రిబ్యునల్స్ పై (military courts మినహా) పర్యవేక్షణ అధికారం కలిగి ఉంది.'),
    (5,
     'medium',
     'Difference between Art.227 and Art.226?\nతెలుగు: Art.227 మరియు Art.226 మధ్య తేడా ఏమిటి?',
     'Both are same / రెండూ ఒకే విషయం',
     'Art.227 = supervisory; Art.226 = writ / Art.227 పర్యవేక్షణ అధికారం; Art.226 రిట్ అధికారం',
     'Art.226 = supervisory; Art.227 = writ / Art.226 పర్యవేక్షణ; Art.227 రిట్',
     'Art.227 = appellate; Art.226 = original / Art.227 అప్పీలేట్; Art.226 మూల',
     'b',
     'Art.226 = writ jurisdiction; Art.227 = superintendence over subordinate courts and tribunals. / Art.226: రిట్ జారీ చేసే అధికారం. Art.227: అన్ని దిగువ కోర్టులు మరియు ట్రిబ్యునల్స్ పై పర్యవేక్షణ మరియు నియంత్రణ.'),
    (5,
     'hard',
     'What comes under Art.227 superintendence?\nతెలుగు: Art.227 కింద HC పర్యవేక్షణలో ఏ సంస్థలు వస్తాయి?',
     'Only District Courts / కేవలం జిల్లా కోర్టులు',
     'All courts + civil tribunals (except military) / అన్ని కోర్టులు + సివిల్ ట్రిబ్యునల్స్ (military మినహా)',
     'SC and HCs / SC మరియు HC లు',
     'Only tribunals / కేవలం ట్రిబ్యునల్స్',
     'b',
     'Art.227: superintendence over all courts and tribunals (except military) within its territorial jurisdiction. / Art.227: HC అన్ని దిగువ కోర్టులు మరియు ట్రిబ్యునల్స్ పై (military tribunals మినహా) పర్యవేక్షణ అధికారం కలిగి ఉంది.'),
    (5,
     'medium',
     'Can HC issue instructions to judicial officers?\nతెలుగు: HC న్యాయమూర్తులు న్యాయ అధికారులకు సూచనలు ఇవ్వవచ్చా?',
     'No, absolutely prohibited / కాదు, పూర్తిగా నిషేధం',
     'Yes, under Art.227 superintendence / అవును, Art.227 కింద పర్యవేక్షణ అధికారంతో',
     'Only with SC permission / కేవలం SC అనుమతితో',
     "Only on President's direction / కేవలం రాష్ట్రపతి ఆదేశంపై",
     'b',
     'Under Art.227, HC can issue guidelines, instructions to subordinate judicial officers. / Art.227 కింద HC న్యాయ అధికారులకు సూచనలు, నిర్దేశాలు ఇవ్వగలదు మరియు ప్రక్రియలు నిర్దేశించగలదు.'),
    (5,
     'medium',
     'Who appoints HC officers and staff (Art.229)?\nతెలుగు: Art.229 ప్రకారం HC అధికారులు మరియు సిబ్బంది నియామకం ఎవరి అధికారం?',
     'State Government / రాష్ట్ర ప్రభుత్వం',
     'Central Government / కేంద్ర ప్రభుత్వం',
     'HC Chief Justice / HC ప్రధాన న్యాయమూర్తి',
     'State PSC / రాష్ట్ర PSC',
     'c',
     'Art.229: Officers and servants of HC appointed by CJ (or such judge as CJ directs); HC CJ may make rules exempting from State PSC. / Art.229: HC అధికారులు మరియు సిబ్బంది నియామకం HC ప్రధాన న్యాయమూర్తి అధికారంలో ఉంటుంది. రాష్ట్ర PSC నుండి మినహాయింపు కూడా CJ ఇవ్వవచ్చు.'),
    (5,
     'hard',
     'What does Art.230 say?\nతెలుగు: Art.230 ఏమి చెప్తుంది?',
     'HC ఏర్పాటు',
     'HC పరిధిని కేంద్రపాలిత ప్రాంతాలకు పొడిగించే అధికారం పార్లమెంట్\u200cకు ఉంది',
     'HC కి advisory jurisdiction ఉంది',
     'HC అప్పీలేట్ పరిధి',
     'b',
     'Art.230: Parliament may by law extend the jurisdiction of HC to a Union Territory or exclude it. / Art.230: పార్లమెంట్ చట్టం ద్వారా HC పరిధిని కేంద్రపాలిత ప్రాంతాలకు పొడిగించవచ్చు లేదా మినహాయించవచ్చు.'),
    (5,
     'medium',
     'What is an HC Vacation Judge?\nతెలుగు: HC Vacation Judge (వెకేషన్ జడ్జి) అంటే ఏమిటి?',
     'Judge appointed after retirement / పదవీ విరమణ తర్వాత నియమించిన జడ్జి',
     'Judge handling urgent matters during court vacation / సెలవుల సమయంలో అత్యవసర విషయాలు చూసే జడ్జి',
     'Ad hoc appointed judge / Ad hoc నియమించిన జడ్జి',
     'Tribunal judge / ట్రిబ్యునల్ జడ్జి',
     'b',
     'Vacation Judge: HC judge designated to hear urgent matters (habeas corpus, bail, injunctions) during court vacations. / వెకేషన్ జడ్జి: న్యాయస్థానం సెలవులలో అత్యవసర విషయాలను (Habeas Corpus, బెయిల్ మొదలైనవి) పరిశీలించడానికి నియమించబడిన జడ్జి.'),
    (5,
     'hard',
     'HC supervisory jurisdiction under Art.227 extends to which courts?\nతెలుగు: Art.227 కింద HC పర్యవేక్షణ అధికారం ఏ కోర్టులకు వర్తిస్తుంది?',
     'Only district courts / కేవలం జిల్లా కోర్టులు',
     'All courts and tribunals within HC territory (except military tribunals) / HC అధికార పరిధిలో ఉన్న అన్ని కోర్టులు మరియు ట్రిబ్యునళ్ళు (సైనిక ట్రిబ్యునళ్ళు మినహా)',
     'Only lower criminal courts / కేవలం దిగువ నేర కోర్టులు',
     'Only civil courts / కేవలం సివిల్ కోర్టులు',
     'b',
     'Art.227: HC superintendence over all courts and tribunals within its territory except military tribunals — supervisory not appellate. / Art.227: HC అన్ని కోర్టులు మరియు ట్రిబ్యునళ్ళపై పర్యవేక్షణ అధికారం కలిగి ఉంటుంది — సైనిక ట్రిబ్యునళ్ళు మినహా. ఇది అప్పీల్ కాదు — పర్యవేక్షణ (supervisory).'),
    (6,
     'easy',
     'Appointment of District Judges?\nతెలుగు: జిల్లా న్యాయమూర్తుల నియామకం గురించి ఏ అనుచ్ఛేదం?',
     'Art.233',
     'Art.235',
     'Art.237',
     'Art.229',
     'a',
     'Art.233: District judges appointed by Governor in consultation with HC. / Art.233: జిల్లా న్యాయమూర్తుల నియామకం గవర్నర్ చేస్తారు — HC తో సంప్రదించిన తర్వాత.'),
    (6,
     'medium',
     'Qualification for District Judge (Art.233)?\nతెలుగు: జిల్లా న్యాయమూర్తి అర్హత ఏమిటి?',
     'HC advocate for 7 years / HC అడ్వకేట్\u200cగా 7 సం.',
     'Law degree + 5 years experience / Law degree + 5 సం. అనుభవం',
     '7 years advocate or judicial officer in union/state service / 7 సంవత్సరాల న్యాయ అభ్యాసకుడు లేదా కేంద్ర/రాష్ట్ర సేవలో న్యాయాధికారి',
     'IPS officer / IPS అధికారి',
     'c',
     'Art.233: District Judge must be advocate for 7 years or serving judicial officer in central/state service. / Art.233: జిల్లా న్యాయమూర్తి కాలేయందుకు: (1) 7 సంవత్సరాల అడ్వకేట్ అనుభవం లేదా (2) ఇప్పటికే కేంద్ర/రాష్ట్ర న్యాయ సేవలో ఉన్నవారు.'),
    (6,
     'medium',
     'HC control over district courts?\nతెలుగు: జిల్లా కోర్టుల నియంత్రణ ఏ అనుచ్ఛేదం కింద HC కి ఉంది?',
     'Art.233',
     'Art.234',
     'Art.235',
     'Art.236',
     'c',
     'Art.235: HC has control over district courts and courts subordinate to district courts. / Art.235: జిల్లా న్యాయమూర్తుల నియంత్రణ (Control) HC కి ఉంటుంది — పోస్టింగ్, పదోన్నతి, సెలవు మొదలైనవి.'),
    (6,
     'hard',
     "Art.236 definition of 'District Judge' includes?\nతెలుగు: Art.236 లో 'District Judge' నిర్వచనంలో ఏ అధికారులు వస్తారు?",
     'Only District and Sessions Judge / కేవలం జిల్లా మరియు సెషన్స్ జడ్జి',
     'Includes Chief Presidency Magistrate, Sessions Judge, Addl. District Judge, Asst. Sessions Judge / Chief Presidency Magistrate, Sessions Judge, Addl. District Judge, Asst. Sessions Judge సహా',
     'Only Civil Judge / కేవలం Civil Judge',
     'District Collector / జిల్లా కలెక్టర్',
     'b',
     "Art.236: 'District Judge' includes Sessions Judge, Chief Presidency Magistrate, Addl. District Judge, etc. / Art.236: 'District Judge' అంటే — Sessions Judge, Addl. Sessions Judge, Asst. Sessions Judge, Chief Presidency Magistrate, Addl. Chief Presidency Magistrate, Sessions Judges of City Civil Courts, మొదలైనవారు."),
    (6,
     'medium',
     'How are judicial officers below District Judge recruited?\nతెలుగు: న్యాయాధికారుల (Judicial Officers) నియామకం ఏ విధంగా జరుగుతుంది?',
     'CM directly / ముఖ్యమంత్రి నేరుగా',
     'Governor in consultation with State PSC and HC / గవర్నర్ రాష్ట్ర PSC మరియు HC సంప్రదింపుతో',
     'HC alone / HC మాత్రమే',
     'Through UPSC / UPSC ద్వారా',
     'b',
     'Art.234: Persons other than district judges to judicial service appointed by Governor in consultation with State PSC and HC. / Art.234: జిల్లా జడ్జి కంటే దిగువ న్యాయాధికారుల నియామకం గవర్నర్ చేస్తారు — రాష్ట్ర PSC మరియు HC సంప్రదింపు తర్వాత.'),
    (6,
     'hard',
     'Difference between Magistrate and Civil Judge?\nతెలుగు: Magistrate (మేజిస్ట్రేట్) మరియు Civil Judge (సివిల్ జడ్జి) మధ్య అధికార పరిధి తేడా ఏమిటి?',
     'Both handle same matters / రెండూ ఒకే విషయాలు చూస్తారు',
     'Magistrate — criminal; Civil Judge — civil / Magistrate — నేర విషయాలు; Civil Judge — సివిల్ విషయాలు',
     'Civil Judge — criminal; Magistrate — civil / Civil Judge — నేర విషయాలు; Magistrate — సివిల్ విషయాలు',
     'Both unrelated / రెండూ సంబంధం లేదు',
     'b',
     'Magistrate handles criminal matters (under CrPC); Civil Judge handles civil matters (under CPC). / Magistrate (మేజిస్ట్రేట్) నేర విషయాలు (CrPC కింద) పరిశీలిస్తారు. Civil Judge సివిల్ విషయాలు (CPC కింద) పరిశీలిస్తారు.'),
    (6,
     'medium',
     'HC consultation is required for District Judge appointment under which Article?\nతెలుగు: జిల్లా న్యాయమూర్తి నియామకంలో ఏ అనుచ్ఛేదం ప్రకారం HC సంప్రదించాలి?',
     'Art.233',
     'Art.234',
     'Art.235',
     'Art.237',
     'a',
     'Art.233(1): District Judges appointed by Governor in consultation with HC. Art.234: Other judicial service members appointed in consultation with SPSC and HC. / Art.233(1): జిల్లా న్యాయమూర్తుల నియామకం — గవర్నర్ HC తో సంప్రదించి నియమిస్తారు. Art.234: న్యాయ సేవలలో ఇతర సభ్యుల నియామకం — రాష్ట్ర PSC మరియు HC తో సంప్రదించి.'),
    (6,
     'hard',
     'What control does HC have over district judges under Art.235?\nతెలుగు: Art.235 కింద HC జిల్లా న్యాయమూర్తులు మరియు దిగువ న్యాయస్థానాలపై ఎలాంటి నియంత్రణ కలిగి ఉంటుంది?',
     'Only appointments / నియామకాలు మాత్రమే',
     'Postings, promotions, leave — all control with HC / పోస్టింగులు, ప్రమోషన్లు, సెలవులు — అన్ని నియంత్రణ HC కి',
     'Removal of district judge / జిల్లా న్యాయమూర్తి తొలగింపు',
     'Determination of salaries / జీతాల నిర్ణయం',
     'b',
     'Art.235: HC controls district courts and subordinate courts regarding postings, promotions, leave. Removal under Art.311 procedural safeguards. / Art.235: HC జిల్లా న్యాయమూర్తులు మరియు దిగువ న్యాయస్థానాలపై నియంత్రణ కలిగి ఉంటుంది — పోస్టింగులు, ప్రమోషన్లు, సెలవులు. కానీ జిల్లా న్యాయమూర్తి తొలగింపు Art.311 ద్వారా.'),
    (7,
     'easy',
     'Cause of action for HC writ (Art.226)?\nతెలుగు: HC Art.226 కింద రిట్ జారీ చేయడానికి కారణం అంటే ఏమిటి?',
     'Only events in that state / కేవలం రాష్ట్రంలో జరిగిన సంఘటనలు',
     "Wholly or partly within HC's territorial jurisdiction / HC అధికార పరిధిలో పూర్తిగా లేదా పాక్షికంగా జరిగిన సంఘటన",
     'Only events in Delhi / కేవలం ఢిల్లీలో జరిగిన సంఘటనలు',
     'Only with SC permission / కేవలం SC అనుమతితో',
     'b',
     'Art.226(2): HC can issue writs where cause of action arose wholly or partly within its territorial jurisdiction. / Art.226(2): Cause of action అంటే HC అధికార పరిధిలో పూర్తిగా లేదా పాక్షికంగా జరిగి ఉండాలి.'),
    (7,
     'medium',
     'What does Art.225 say?\nతెలుగు: HC Art.225 ఏమి చెప్తుంది?',
     'Establishment of HC / HC ఏర్పాటు',
     'Existing jurisdiction, laws continue in HC / HC లో ముందున్న అధికార పరిధి, చట్టాలు కొనసాగుతాయి',
     'HC writ power / HC రిట్ అధికారం',
     "HC judges' salaries / HC న్యాయమూర్తుల జీతాలు",
     'b',
     'Art.225: Jurisdiction of existing HC continues as before — until altered by Parliament or Constitution. / Art.225: సంవిధాన రచనకు ముందు ఉన్న HC అధికార పరిధి కొనసాగుతుంది — రాజ్యాంగంలో లేదా పార్లమెంట్ చట్టం ద్వారా మార్పు అయ్యే వరకు.'),
    (7,
     'hard',
     "HC judges' salaries charged to?\nతెలుగు: HC న్యాయమూర్తి జీతాలు ఏ నిధి నుండి?",
     'Consolidated Fund of State / రాష్ట్ర ఏకీకృత నిధి',
     'Consolidated Fund of India / భారత ఏకీకృత నిధి',
     'State Contingency Fund / రాష్ట్ర ఆకస్మిక నిధి',
     'కేంద్ర Votable appropriation',
     'a',
     "HC judges' salaries: Consolidated Fund of State (Art.221); pensions: CFI. / HC న్యాయమూర్తుల జీతాలు రాష్ట్ర ఏకీకృత నిధి నుండి చెల్లిస్తారు (Art.221). అయితే పదవీ విరమణ పెన్షన్లు కేంద్ర ఏకీకృత నిధి నుండి."),
    (7,
     'medium',
     'Who appoints Advocate General of State?\nతెలుగు: HC లో Advocate General (రాష్ట్ర ప్రభుత్వ అడ్వకేట్ జనరల్) నియమించే అధికారం ఎవరికి?',
     'Chief Minister / ముఖ్యమంత్రి',
     'HC Chief Justice / HC ప్రధాన న్యాయమూర్తి',
     'Governor of the State / రాష్ట్ర గవర్నర్',
     'President / రాష్ట్రపతి',
     'c',
     'Art.165: AG of State appointed by Governor; must be qualified to be HC judge. / Art.165: రాష్ట్ర Advocate General ని గవర్నర్ నియమిస్తారు. అతడు HC జడ్జి పదవికి అర్హుడైన వ్యక్తి అయి ఉండాలి.'),
    (7,
     'medium',
     'Where can a HC establish circuit bench?\nతెలుగు: ఒక HC తన సర్క్యూట్ బెంచ్\u200cను ఎక్కడ ఏర్పాటు చేయగలదు?',
     'Only in state capital / కేవలం రాజధానిలో',
     "Other cities — with President's approval / ఇతర నగరాలలో — రాష్ట్రపతి అనుమతితో",
     'Any state / ఏ రాష్ట్రంలో అయినా',
     'Only with SC permission / SC అనుమతితో మాత్రమే',
     'b',
     "HC circuit bench may be established in other cities within the state with President's approval. / HC సర్క్యూట్ బెంచ్ రాష్ట్రపతి అనుమతితో రాష్ట్రంలోని వేరే నగరాలలో ఏర్పాటు చేయవచ్చు."),
    (7,
     'medium',
     '44th Amendment (1978) deleted which article related to HC?\nతెలుగు: Art.226A (ప్రకారం రద్దు) — Art.226లో ఏమి చేర్చారు?',
     'Deleted Art.226A / Art.226A అనే వేరే అనుచ్ఛేదం రద్దు చేశారు',
     'Art.31C provision suspending HC jurisdiction / Art.31C (National emergency) HC అప్పీల్ ఆగే నిబంధన',
     'Deleted Art.226A that suspended HC writ power during state emergency / రాష్ట్ర అత్యవసర పరిస్థితిలో HC రిట్ అధికారాన్ని తాత్కాలికంగా నిలిపే Art.226A రద్దు',
     'Deletion of Art.220A / Art.220A రద్దు',
     'c',
     '44th Amendment 1978 deleted Art.226A which allowed suspension of HC writ power during national emergency under Art.359. / 44వ సవరణ (1978): Art.226A రద్దు చేసింది — ఇది Art.359 కింద జాతీయ అత్యవసర పరిస్థితిలో HC రిట్ అధికారాన్ని తాత్కాలికంగా నిలిపేది.'),
    (7,
     'hard',
     'Can there be two HCs for one state?\nతెలుగు: ఒకే రాష్ట్రంలో రెండు హైకోర్టులు ఏర్పాటు చేయవచ్చా?',
     'Yes, by Parliament / అవును, పార్లమెంట్ చట్టం ద్వారా',
     'No, one state one HC / కాదు, ఒక రాష్ట్రానికి ఒక HC మాత్రమే',
     "Yes, on President's order / అవున, రాష్ట్రపతి ఆదేశంతో",
     'Yes, with constitutional amendment / అవున, రాజ్యాంగ సవరణతో',
     'b',
     'Art.214: One HC per state. Two states may share one HC (Art.231), but one state cannot have two HCs. / Art.214: ప్రతి రాష్ట్రానికి కేవలం ఒక్క HC మాత్రమే ఉంటుంది. రెండు రాష్ట్రాలకు ఒక్క HC ఉండవచ్చు (Art.231) కానీ ఒక రాష్ట్రానికి రెండు HCలు ఉండవు.'),
    (7,
     'medium',
     'After retirement, HC judge cannot practice in which court?\nతెలుగు: HC న్యాయమూర్తి పదవీ విరమణ తర్వాత ఏ న్యాయస్థానంలో వకీలు చేయలేరు?',
     'Cannot practice in any court / ఏ కోర్టులోనూ చేయలేరు',
     'Cannot practice in own HC / సొంత HC లో చేయలేరు',
     'Cannot practice in SC / SC లో చేయలేరు',
     'Cannot practice in any tribunal / ఏ ట్రిబ్యునల్\u200cలోనూ చేయలేరు',
     'b',
     'Art.220: After retirement, HC judge cannot practice in that particular HC; can practice in SC or other HCs. / Art.220: HC న్యాయమూర్తి పదవీ విరమణ తర్వాత తాను న్యాయమూర్తిగా పనిచేసిన HC లో వకీలు చేయలేరు — ఇతర HCలలో లేదా SC లో చేయవచ్చు.'),
]


def _seed_polity_ch21_notes_inner(conn, db_exec_fn, row_to_dict_fn, use_postgres, force=False):
    ph = '%s' if use_postgres else '?'
    existing = db_exec_fn(conn,
        f"SELECT id FROM study_notes WHERE subject={ph} AND topic={ph} AND chapter_num={ph}",
        (_SUBJECT, _TOPIC, _CH))
    row = row_to_dict_fn(existing.fetchone())

    if row and not force:
        return row['id']

    import json
    sections_json = json.dumps(_SECTIONS, ensure_ascii=False)

    if row:
        db_exec_fn(conn,
            f"UPDATE study_notes SET chapter_title_te={ph}, chapter_title_en={ph}, "
            f"pages_ref={ph}, sections_json={ph} "
            f"WHERE subject={ph} AND topic={ph} AND chapter_num={ph}",
            (_TITLE_TE, _TITLE_EN, _PAGES, sections_json, _SUBJECT, _TOPIC, _CH))
        return row['id']
    else:
        db_exec_fn(conn,
            f"INSERT INTO study_notes (subject, topic, chapter_num, chapter_title_te, "
            f"chapter_title_en, pages_ref, sections_json) VALUES ({ph},{ph},{ph},{ph},{ph},{ph},{ph})",
            (_SUBJECT, _TOPIC, _CH, _TITLE_TE, _TITLE_EN, _PAGES, sections_json))
        cur2 = db_exec_fn(conn,
            f"SELECT id FROM study_notes WHERE subject={ph} AND topic={ph} AND chapter_num={ph}",
            (_SUBJECT, _TOPIC, _CH))
        return row_to_dict_fn(cur2.fetchone())['id']


def _seed_polity_ch21_mcqs_inner(conn, db_exec_fn, row_to_dict_fn, use_postgres):
    ph = '%s' if use_postgres else '?'
    cur = db_exec_fn(conn,
        f"SELECT id FROM study_notes WHERE subject={ph} AND topic={ph} AND chapter_num={ph}",
        (_SUBJECT, _TOPIC, _CH))
    note = row_to_dict_fn(cur.fetchone())
    if not note:
        return
    note_id = note['id']

    existing = db_exec_fn(conn,
        f"SELECT COUNT(*) FROM chapter_mcqs WHERE study_note_id={ph}", (note_id,))
    if list(existing.fetchone())[0] > 0:
        return

    diff_map = {"easy": 1, "medium": 2, "hard": 3, "toughest": 4, 1: 1, 2: 2, 3: 3, 4: 4}

    for row in _MCQS:
        sec_idx  = row[0]
        diff_str = row[1]
        q_te     = row[2]
        opt_a    = row[3]
        opt_b    = row[4]
        opt_c    = row[5]
        opt_d    = row[6]
        correct  = row[7]
        expl     = row[8]
        exam_type = row[9] if len(row) > 9 else 'General'
        if not exam_type:
            exam_type = 'General'

        diff_int = diff_map.get(diff_str, 1)
        db_exec_fn(conn,
            f"""INSERT INTO chapter_mcqs
                (study_note_id, section_idx, difficulty, exam_type,
                 q_te, opt_a, opt_b, opt_c, opt_d, correct, explanation_te)
                VALUES ({ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph},{ph})""",
            (note_id, sec_idx, diff_int, exam_type,
             q_te, opt_a, opt_b, opt_c, opt_d, correct, expl))
