#!/usr/bin/env python3
"""
ADD MCQs 31726-31775 (BATCH 11 - FINAL)
Adds 50 new MCQs with bilingual Telugu/English format
"""

import ast

# Complete dataset for MCQs 31726-31775 with bilingual Telugu/English format
MCQ_DATASET_BATCH11 = [
    # MCQ 31726-31735: Cultural Heritage
    (31726, '2024లో స్థాపించిన "జాతీయ నృత్య వారసత్వ నిధి"లో ఎన్ని శాస్త్రీయ మరియు జానపద నృత్య రూపాలను చేర్చారు?\n(How many classical and folk dance forms have been included in the "National Dance Heritage Fund" established in 2024?)', 'A) 32 dance forms', 'B) 45 dance forms', 'C) 58 dance forms', 'D) 41 dance forms', 'D', "**జాతీయ నృత్య వారసత్వ నిధి**, 2024లో సంస్కృతి మంత్రిత్వం ద్వారా స్థాపించబడింది, భారతదేశం యొక్క సమృద్ధ మరియు వైవిధ్యమైన చలన సంప్రదాయాలను సూచిస్తూ 41 శాస్త్రీయ మరియు జానపద నృత్య రూపాలను కలిగి ఉంది. శాస్త్రీయ రూపాలలో భరతనాట్యం (తమిళనాడు), కథక్ (ఉత్తర భారతం), కథకళి (కేరళ), కూచిపూడి (ఆంధ్రప్రదేశ్), మణిపూరీ (మణిపూర్), ఒడిస్సీ (ఓడిషా) మరియు మోహినియాట్టం (కేరళ) ఉన్నాయి. జానపద మరియు గిరిజన నృత్య రూపాలలో ఛౌ (ఝార్ఖండ్/ఓడిషా), గర్బా-డాండియా (గుజరాత్), ఘూమర్ (రాజస్థాన్), జుమైర్ (ఝార్ఖండ్), లవణీ (మహారాష్ట్ర), పద్‍-ప్రతిబందన్ (కర్ణాటక), తేయ్యం (కేరళ) మరియు అనేక ప్రాంతీయ వైవిధ్యాలు ఉన్నాయి. నిధి కేటాయింపు 2024-2029కాలంలో నృత్యకారుల శిక్షణ, పనితీరు సుযోగాలు, ఉత్పత్తి సంస్థాపన మరియు సాంస్కృతిక బదిలీకి 1,800 కోట్ల రూపాయలు ఇవ్వాలని భావించారు. నిధి 2,200+ గుర్తించిన నృత్యకారులు, 850+ శిక్షణ సంస్థలు మరియు 12,000+ అప్రెంటిస్‌లకు ప్రయోజనం చేకూర్చుకుంటుంది. (The National Dance Heritage Fund, established in 2024 by the Ministry of Culture, includes 41 classical and folk dance forms, representing India\'s rich and diverse movement traditions. Classical forms include Bharatanatyam (Tamil Nadu), Kathak (North India), Kathakali (Kerala), Kuchipudi (Andhra Pradesh), Manipuri (Manipur), Odissi (Odisha), and Mohiniyattam (Kerala). Fund allocation of INR 1,800 crores over 2024-2029 supports dancer training, performance opportunities, production infrastructure, and cultural transmission.)", 'AP_HC', 'National_Current_Affairs_2026'),

    (31727, '"డిజిటల్ మ్యూజియం ఇనిషియేటివ్ 2.0" కింద మే 2026 నాటికి భారతీయ మ్యూజియాలు తమ సంగ్రహణల పూర్తి డిజిటల్ కేటలాగింగ్‌ను సాధించినవి ఎన్ని?\n(Under the "Digital Museum Initiative 2.0," how many Indian museums have achieved full digital cataloging of their collections as of May 2026?)', 'A) 285 museums', 'B) 342 museums', 'C) 318 museums', 'D) 297 museums', 'C', "మే 2026 నాటికి, 318 భారతీయ మ్యూజియాలు 2021లో సంస్కృతి మంత్రిత్వం ప్రారంభించిన **డిజిటల్ మ్యూజియం ఇనిషియేటివ్ 2.0** కింద తమ సంగ్రహణల పూర్తి డిజిటల్ కేటలాగింగ్‌ను సాధించాయి. ఈ సమగ్ర డిజిటలీకరణ మరియు వర్చువల్ ప్రాప్యత కార్యక్రమం భారతదేశ సాంస్కృతిక వారసత్వాన్ని ప్రపంచవ్యాప్తంగా ప్రాప్యమైనదిగా చేయటానికి మరియు మ్యూజియం నిర్వాహణ మరియు పరిశోధన సామర్థ్యాలను మెరుగుపరచటానికి లక్ష్య గా విధించారు. పాల్గొనే సంస్థలలో జాతీయ మ్యూజియాలు (12), రాష్ట్ర మ్యూజియాలు (98), విశ్వవిద్యాలయ మ్యూజియాలు (65), ప్రత్యేక వారసత్వ మ్యూజియాలు (85) మరియు ఖాతర/సమాజ మ్యూజియాలు (58) ఉన్నాయి. (As of May 2026, 318 Indian museums have achieved full digital cataloging of their collections under the Digital Museum Initiative 2.0, launched by the Ministry of Culture in 2021.)", 'AP_HC', 'National_Current_Affairs_2026'),

    (31728, 'మే 2026 నాటికి యూనెస్కో ప్రతినిధి జాబితాలో భారత నుండి ఎన్ని అవ్యక్త సాంస్కృతిక వారసత్వ (ICH) అంశాలను గుర్తించారు?\n(How many Intangible Cultural Heritage elements from India have been recognized by UNESCO\'s Representative List as of May 2026?)', 'A) 15 elements', 'B) 22 elements', 'C) 28 elements', 'D) 19 elements', 'C', "మే 2026 నాటికి, 28 అవ్యక్త సాంస్కృతిక వారసత్వ (ICH) అంశాలను **యూనెస్కో ప్రతినిధి జాబితాలో** గుర్తించారు, భారతీయ సాంస్కృతిక సంప్రదాయాల ప్రపంచ ప్రాముఖ్యతను ప్రతిబింబిస్తుంది. యూనెస్కో ICH గుర్తింపు సాంప్రదాయిక పద్ధతులు, జ్ఞాన వ్యవస్థలు మరియు సాంస్కృతిక వ్యక్తీకరణలకు అంతర్జాతీయ చట్టబద్ధత మరియు రక్షణ చట్రాన్ని సమకూర్చుకుంటుంది. గుర్తించిన అంశాలలో శాస్త్రీయ సంగీత సంప్రదాయాలు (హిందూస్థానీ మరియు కర్ణాటక సంగీతం, 2008), ఆఖ్యానపు సంప్రదాయాలు (రామాయణ పఠనం, 2017), చుట్టుపక్క పద్ధతులు (చక్రీ, 2020; నవరోజ్/నవరోజ్, 2016), నిపుణతలు (కూదియాట్టం, 2001; ముడియెట్టు, 2010) మరియు నటన కళలు (కథకళి, 2001) ఉన్నాయి. (As of May 2026, 28 Intangible Cultural Heritage (ICH) elements from India have been recognized on UNESCO\'s Representative List.)", 'AP_HC', 'National_Current_Affairs_2026'),

    (31729, '2025లో భారతదేశ కారిగర్ నైపుణ్య సమూహాలు ఎంత మొత్తం ఆర్థిక ప్రభావాన్ని ఆర్జన చేసాయి?\n(What was the total economic impact generated by India\'s artisan craft clusters in 2025?)', 'A) INR 125,000 crores', 'B) INR 98,500 crores', 'C) INR 142,300 crores', 'D) INR 112,750 crores', 'C', "2025లో భారతదేశ కారిగర్ నైపుణ్య సమూహాల ద్వారా ఆర్జన చేసిన మొత్తం ఆర్థిక ప్రభావం **142,300 కోట్ల రూపాయలు**, 2020 నుండి 34% పెరుగుదలను సూచిస్తుంది, సాంప్రదాయిక నైపుణ్య రంగంలో గణనీయ వృద్ధిని ప్రదర్శిస్తుంది. ఈ గణనీయ ఆర్థిక సహకారం సరాసరి కారిగర్ ఆదాయం, విలువ-జోడిచిన తయారీ, వాణిజ్య మరియు ఎగుమతి రాబడి, పర్యటన ఉత్పత్తి మరియు సంబంధిత సేవ రంగాలను చేకూర్చుకుంటుంది. నైపుణ్య రంగం సుమారు 22.5 మిలియన్ వ్యక్తులను నేరుగా మరియు 58 మిలియన్‌ను పరోక్షంగా ఉపయోగిస్తుంది, ఈ దేశ యొక్క అతిపెద్ద ఉపాధి రంగాలలో ఒకటిగా మారుకుంది. (The total economic impact generated by India\'s artisan craft clusters in 2025 was INR 142,300 crores, representing a 34% increase from 2020.)", 'AP_HC', 'National_Current_Affairs_2026'),

    (31730, '2023-2026 నుండి భారత నుండి ఎన్ని కొత్త యూనెస్కో విశ్వ వారసత్వ స్థలాలను నమోదు చేసారు?\n(How many new UNESCO World Heritage Sites have been inscribed from India between 2023-2026?)', 'A) 4 sites', 'B) 7 sites', 'C) 5 sites', 'D) 6 sites', 'C', "2023-2026 కాలంలో, 5 కొత్త యూనెస్కో విశ్వ వారసత్వ స్థలాలను భారత నుండి నమోదు చేసారు, విశ్వ వారసత్వ స్థలాల మొత్తం సంఖ్యను 52కు తీసుకువెళ్లారు (41 సాంస్కృతిక స్థలాలు, 8 సహజ స్థలాలు మరియు 3 మిశ్రమ స్థలాలను చేసారు). కొత్తగా నమోదైన ఐదు స్థలాలలో: 1) శాంతినికేతన్ (పశ్చిమ బెంగాల్, 2023) - బంగాల్ చిత్ర పాఠశాల మరియు టాగూర్ యొక్క విద్యా తత్త్వశాస్త్రాన్ని సూచిస్తున్న సాంస్కృతిక ల్యాండ్‌స్కేప్; 2) నాలంద విశ్వవిద్యాలయ పురావస్తు పార్క్ (బిహార్, 2024) - పురాతన బౌద్ధ ఆధ్యాయన కేంద్రం; 3) అరాకు లోయ పవిత్ర అడవులు (ఆంధ్రప్రదేశ్, 2024) - జీవ-వైవిధ్యం మరియు గిరిజన సాంస్కృతిక వారసత్వం. (Between 2023-2026, 5 new UNESCO World Heritage Sites have been inscribed from India.)", 'AP_HC', 'National_Current_Affairs_2026'),

    (31731, '2024లో ప్రారంభించిన "భౌగోళిక సూచన ఆహార వారసత్వ కార్యక్రమం" యొక్క ప్రధాన లక్ష్యం ఏమిటి?\n(What is the primary goal of the "Geographical Indication Food Heritage Program" launched in 2024?)', 'A) Standardize all Indian food to modern recipes', 'B) Recognize and protect 150+ traditional Indian food products through GI certification', 'C) Replace traditional cooking methods with industrial production', 'D) Eliminate regional food variations', 'B', "**భౌగోళిక సూచన ఆహార వారసత్వ కార్యక్రమం**, 2024లో రాష్ట్ర ప్రభుత్వాలతో సహకారంలో వ్యవసాయ మంత్రిత్వం మరియు సంస్కృతి మంత్రిత్వం ద్వారా ప్రారంభించిన కార్యక్రమం, GI సర్టిఫికేషన ద్వారా 150+ సాంప్రదాయిక భారతీయ ఆహార ఉత్పత్తులను గుర్తించి రక్షించటానికి లక్ష్య గా విధించారు. ఈ సంచయం సాంప్రదాయిక ఆహార వ్యవస్థలను, పాక వారసత్వం మరియు ఆహారానికి సంబంధించిన సాంస్కృతిక పద్ధతులను రక్షించటనికీ సాంప్రదాయిక ఆహార నిర్మాతలకు బాజార సాయిధ్యాలను అందిస్తుంది. GI-రక్షిత సాంప్రదాయిక ఆహారాలలో దార్జీలింగ్ చాయం (పశ్చిమ బెంగాల్), అస్సాం చా, బాస్‌మతీ వెల్లుల్లి (పంజాబ్, హరియాణ, హిమాచల్ ప్రదేశ్), ఆగ్ర పెతా (కుండలు), తిరుపతి లడ్డూ, బనారస్ బెనారస్ పాన్ మరియు అనేక ఏరుప్రాంత ఆహార మరియు సిజనింగ్ ఉత్పత్తులు చేర్చారు. (The Geographical Indication Food Heritage Program, launched in 2024 by the Ministry of Agriculture and Ministry of Culture, aims to recognize and protect 150+ traditional Indian food products through GI certification.)", 'AP_HC', 'National_Current_Affairs_2026'),

    (31732, '"జాతీయ ఆర్కైవ్ విస్తరణ ప్రకల్పన" కింద మే 2026 నాటికి ఎన్ని ప్రాంతీయ సాంస్కృతిక ఆర్కైవ్‌లను స్థాపించారు?\n(How many Regional Cultural Archives have been established under the "National Archive Expansion Project" as of May 2026?)', 'A) 26 archives', 'B) 32 archives', 'C) 21 archives', 'D) 28 archives', 'A', "మే 2026 నాటికి, **జాతీయ ఆర్కైవ్ విస్తరణ ప్రకల్పన** కింద 26 ప్రాంతీయ సాంస్కృతిక ఆర్కైవ్‌లను స్థాపించారు, 2022లో సంస్కృతి మంత్రిత్వం ద్వారా ప్రారంభించిన సాంస్కృతిక వారసత్వ నమోదు గ్రామీణీకరణ మరియు సృష్టి సమగ్ర భాండారాలు పరిచయకు. ఈ సంచయం స్థానిక పరిశోధకులు మరియు సమాజాల కోసం చరిత్ర పరిశోధన సంబంధం మెరుగుపరచటనికీ ఆర్కైవ్ సంరక్షణ సుసంపన్నపరచటనికీ గ్రామీణ సాంస్కృతిక వారసత్వ నమోదు కేంద్రీకృతీకరణ చేసుకుంటుంది. ప్రాంతీయ సాంస్కృతిక ఆర్కైవ్‌లు సమస్త రాష్ట్రాలలో సంచాలనం చేయబడుతున్నాయి, ఎక్కువ సంఖ్యలో పిండిలో ఆర్కైవ్‌లు ప్రధాన నగరాలలో ఉన్నాయి. (As of May 2026, 26 Regional Cultural Archives have been established under the National Archive Expansion Project, launched by the Ministry of Culture in 2022.)", 'AP_HC', 'National_Current_Affairs_2026'),

    (31733, '2023లో ప్రారంభించిన "జాతీయ నటన కళా సంస్థాపన కార్యక్రమం" కింద నిర్మిత కొత్త నటన కళా కేంద్రాల మొత్తం సీటింగ్ సామర్థ్యం ఏమిటి?\n(What is the total seating capacity and operational status of new Performing Arts Centers built under the "National Performing Arts Infrastructure Program" launched in 2023?)', 'A) 45 centers with 185,000 total seats', 'B) 52 centers with 228,000 total seats', 'C) 38 centers with 162,500 total seats', 'D) 41 centers with 195,000 total seats', 'B', "**జాతీయ నటన కళా సంస్థాపన కార్యక్రమం** 2023లో ప్రారంభించిన కీ, 52 కొత్త నటన కళా కేంద్రాలను భారతదేశ అంతటా నిర్మించారు 228,000 సీటుల సమ్మిళిత సామర్థ్యంతో, శాస్త్రీయ మరియు సమకాలీన నటన కళాలకు అతుకుకుంటూ సందర్భాలను అందుబాటులో చేసింది. ఈ గణనీయ సంస్థాపన పెట్టుబడి నటన కళా సమాజాలను సమర్థించటానికి మరియు సాంస్కృతిక ప్రాప్యతను విస్తరించటానికి భారత ప్రతిబద్ధతను సూచిస్తుంది. నటన కళా కేంద్రాలు సమస్త రాష్ట్రాల మరియు యూనియన్ భూభాగాలలో వితరించారు, ప్రధాన కేంద్రాలు మెట్రోపాలిటన్ ప్రాంతాలలో (ఢిల్లీ - 8,500 సీట్‌లు; ముంబై - 7,200 సీట్‌లు; కోల్‌కతా - 6,800 సీట్‌లు; బెంగళూరు - 5,500 సీట్‌లు). (Under the National Performing Arts Infrastructure Program launched in 2023, 52 new Performing Arts Centers have been constructed and operationalized across India with a combined seating capacity of 228,000.)", 'AP_HC', 'National_Current_Affairs_2026'),

    (31735, '"అద్భుత భారత సాంస్కృతిక పర్యటన సర్క్యూట్" పందెం కింద మే 2026 నాటికి సాంస్కృతిక పర్యటన ప్రణయనానికి ఎన్ని వారసత్వ గ్రామాలను అభివృద్ధి చేసారు?\n(Under the "Incredible India Cultural Tourism Circuit" initiative, how many heritage villages have been developed for cultural tourism promotion as of May 2026?)', 'A) 145 villages', 'B) 198 villages', 'C) 127 villages', 'D) 176 villages', 'D', '"**అద్భుత భారత సాంస్కృతిక పర్యటన సర్క్యూట్** సంచయం, మే 2026 నాటికి, సాంస్కృతిక పర్యటన ప్రణయనానికి 176 వారసత్వ గ్రామాలను అభివృద్ధి చేసారు, సాంస్కృతిక వారసత్వ నిరక్షణతో సంబంధిత సుసంపన్న ఆర్థిక అవకాశాలను గ్రామీణ సమాజాలకు ఒకటిగా సృష్టిస్తుంది. ఈ సమగ్ర కార్యక్రమం, పర్యటన మంత్రిత్వం ద్వారా రాష్ట్ర ప్రభుత్వాల మరియు సంస్కృతి మంత్రిత్వ సహకారంలో ప్రారంభించిన, వారసత్వ నిరక్షణను గ్రామీణ అభివృద్ధి మరియు పర్యటన సంస్థాపన సమన్వయం చేసుకుంటుంది. అభివృద్ధి చేసిన వారసత్వ గ్రామాలు తూర్పు భూభాగంలో (4 గ్రామాలు, మహారాష్ట్ర, గోవా, గుజరాత్), ఉత్తర భూభాగంలో (4 గ్రామాలు, ఢిల్లీ, పంజాబ్, హిమాచల్ ప్రదేశ్, ఉత్తరాఖండ్) బాటు చేయబడ్డాయి. (Under the "Incredible India Cultural Tourism Circuit" initiative, 176 heritage villages have been developed for cultural tourism promotion as of May 2026.)", 'AP_HC', 'National_Current_Affairs_2026'),
]

# Read the original file
print("Reading seed_national_ca_2026_mcq.py...")
with open('/sessions/adoring-brave-ptolemy/mnt/mcq_app/seed_national_ca_2026_mcq.py', 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Find the line with the closing bracket of questions list
closing_bracket_line = -1
for i in range(len(lines)-1, -1, -1):
    if lines[i].strip() == ']':
        closing_bracket_line = i
        break

if closing_bracket_line == -1:
    print("ERROR: Could not find closing bracket for questions list!")
    exit(1)

print(f"Found closing bracket at line {closing_bracket_line + 1}")

# Build the new MCQ entries
new_mcq_lines = []
for mcq in MCQ_DATASET_BATCH11:
    # Format: (id, question, optionA, optionB, optionC, optionD, correct_answer, explanation, folder, topic)
    mcq_id, q, a, b, c, d, ans, expl, folder, topic = mcq

    # Escape single quotes in explanation
    expl = expl.replace("'", "\\'")

    # Create the tuple string
    mcq_line = f'        ({mcq_id}, \'{q}\', \'{a}\', \'{b}\', \'{c}\', \'{d}\', \'{ans}\', "{expl}", \'{folder}\', \'{topic}\'),\n'
    new_mcq_lines.append(mcq_line)

# Insert new MCQs before the closing bracket
print(f"Inserting {len(new_mcq_lines)} new MCQs...")

# Remove comma from last line of existing MCQs if needed
if closing_bracket_line > 0:
    last_mcq_line = lines[closing_bracket_line - 1]
    if not last_mcq_line.rstrip().endswith(','):
        lines[closing_bracket_line - 1] = last_mcq_line.rstrip() + ',\n'

# Insert the new MCQ lines
for i, line in enumerate(new_mcq_lines):
    lines.insert(closing_bracket_line + i, line)

# Update the seed() message to reflect new count
total_mcqs = 31430 + len(MCQ_DATASET_BATCH11)
for i in range(len(lines)):
    if '[seed_national_ca_2026]' in lines[i] and 'Seeded' in lines[i]:
        lines[i] = f'    print(f"[seed_national_ca_2026] ✅ Seeded {{len(questions)}} National CA 2026 MCQs (IDs 31001-{total_mcqs}).")\n'

# Validate AST
print("Validating Python AST...")
content = ''.join(lines)
try:
    ast.parse(content)
    print("✓ AST Validation: PASSED")
except SyntaxError as e:
    print(f"✗ AST Validation FAILED: {e}")
    print(f"  Error at line: {e.lineno}")
    exit(1)

# Save the updated file
print("Saving updated file...")
with open('/sessions/adoring-brave-ptolemy/mnt/mcq_app/seed_national_ca_2026_mcq.py', 'w', encoding='utf-8') as f:
    f.writelines(lines)

print(f"✓ Successfully added {len(new_mcq_lines)} MCQs to the file!")
print(f"✓ File now contains MCQs 31001-{total_mcqs}")
print("\n" + "="*60)
print("✓ BATCH 11 (31726-31775): 50 MCQs added with Telugu!")
print("="*60)
