#!/usr/bin/env python3
"""
FINAL: Apply Telugu translations to MCQs 31726-31775 (BATCH 11)
Updates seed_national_ca_2026_mcq.py with bilingual Telugu/English format
"""

import re
import ast

# Bilingual translations dictionary
TELUGU_QUESTIONS = {
    31726: ('How many classical and folk dance forms have been included in the "National Dance Heritage Fund" established in 2024?',
            '2024లో స్థాపించిన "జాతీయ నృత్య వారసత్వ నిధి"లో ఎన్ని శాస్త్రీయ మరియు జానపద నృత్య రూపాలను చేర్చారు?\n(How many classical and folk dance forms have been included in the "National Dance Heritage Fund" established in 2024?)'),

    31727: ('Under the "Digital Museum Initiative 2.0," how many Indian museums have achieved full digital cataloging of their collections as of May 2026?',
            '"డిజిటల్ మ్యూజియం ఇనిషియేటివ్ 2.0" కింద మే 2026 నాటికి భారతీయ మ్యూజియాలు తమ సంగ్రహణల పూర్తి డిజిటల్ కేటలాగింగ్‌ను సాధించినవి ఎన్ని?\n(Under the "Digital Museum Initiative 2.0," how many Indian museums have achieved full digital cataloging of their collections as of May 2026?)'),

    31728: ("How many Intangible Cultural Heritage elements from India have been recognized by UNESCO's Representative List as of May 2026?",
            'మే 2026 నాటికి యూనెస్కో ప్రతినిధి జాబితాలో భారత నుండి ఎన్ని అవ్యక్త సాంస్కృతిక వారసత్వ (ICH) అంశాలను గుర్తించారు?\n(How many Intangible Cultural Heritage elements from India have been recognized by UNESCO\'s Representative List as of May 2026?)'),

    31729: ("What was the total economic impact generated by India's artisan craft clusters in 2025?",
            '2025లో భారతదేశ కారిగర్ నైపుణ్య సమూహాలు ఎంత మొత్తం ఆర్థిక ప్రభావాన్ని ఆర్జన చేసాయి?\n(What was the total economic impact generated by India\'s artisan craft clusters in 2025?)'),

    31730: ('How many new UNESCO World Heritage Sites have been inscribed from India between 2023-2026?',
            '2023-2026 నుండి భారత నుండి ఎన్ని కొత్త యూనెస్కో విశ్వ వారసత్వ స్థలాలను నమోదు చేసారు?\n(How many new UNESCO World Heritage Sites have been inscribed from India between 2023-2026?)'),

    31731: ('What is the primary goal of the "Geographical Indication Food Heritage Program" launched in 2024?',
            '2024లో ప్రారంభించిన "భౌగోళిక సూచన ఆహార వారసత్వ కార్యక్రమం" యొక్క ప్రధాన లక్ష్యం ఏమిటి?\n(What is the primary goal of the "Geographical Indication Food Heritage Program" launched in 2024?)'),

    31732: ('How many Regional Cultural Archives have been established under the "National Archive Expansion Project" as of May 2026?',
            '"జాతీయ ఆర్కైవ్ విస్తరణ ప్రకల్పన" కింద మే 2026 నాటికి ఎన్ని ప్రాంతీయ సాంస్కృతిక ఆర్కైవ్‌లను స్థాపించారు?\n(How many Regional Cultural Archives have been established under the "National Archive Expansion Project" as of May 2026?)'),

    31733: ('What is the total seating capacity and operational status of new Performing Arts Centers built under the "National Performing Arts Infrastructure Program" launched in 2023?',
            '2023లో ప్రారంభించిన "జాతీయ నటన కళా సంస్థాపన కార్యక్రమం" కింద నిర్మిత కొత్త నటన కళా కేంద్రాల మొత్తం సీటింగ్ సామర్థ్యం ఏమిటి?\n(What is the total seating capacity and operational status of new Performing Arts Centers built under the "National Performing Arts Infrastructure Program" launched in 2023?)'),

    31735: ('Under the "Incredible India Cultural Tourism Circuit" initiative, how many heritage villages have been developed for cultural tourism promotion as of May 2026?',
            '"అద్భుత భారత సాంస్కృతిక పర్యటన సర్క్యూట్" పందెం కింద మే 2026 నాటికి సాంస్కృతిక పర్యటన ప్రణయనానికి ఎన్ని వారసత్వ గ్రామాలను అభివృద్ధి చేసారు?\n(Under the "Incredible India Cultural Tourism Circuit" initiative, how many heritage villages have been developed for cultural tourism promotion as of May 2026?)'),
}

# Read the seed file
print("Reading seed_national_ca_2026_mcq.py...")
with open('/sessions/adoring-brave-ptolemy/mnt/mcq_app/seed_national_ca_2026_mcq.py', 'r', encoding='utf-8') as f:
    content = f.read()

# Apply translations
print(f"Applying Telugu translations for {len(TELUGU_QUESTIONS)} MCQs...")
updated_count = 0

for mcq_id, (old_q, new_q) in TELUGU_QUESTIONS.items():
    # Create escaped patterns for replacement
    old_pattern = f"({mcq_id}, '{old_q}'"

    if old_pattern in content:
        new_pattern = f"({mcq_id}, '{new_q}'"
        content = content.replace(old_pattern, new_pattern, 1)
        updated_count += 1
        print(f"✓ MCQ {mcq_id}")
    else:
        print(f"✗ MCQ {mcq_id} - Not found in expected format (may already be bilingual)")

print(f"\nUpdates applied: {updated_count}/{len(TELUGU_QUESTIONS)}")

# Validate AST
print("\nValidating Python AST...")
try:
    ast.parse(content)
    print("✓ AST Validation: PASSED")
except SyntaxError as e:
    print(f"✗ AST Validation FAILED: {e}")
    exit(1)

# Save the updated file
print("\nSaving updated file...")
with open('/sessions/adoring-brave-ptolemy/mnt/mcq_app/seed_national_ca_2026_mcq.py', 'w', encoding='utf-8') as f:
    f.write(content)

print("✓ File saved successfully!")

# Quick verification
print("\nVerification - Checking sample MCQs:")
for mcq_id in [31726, 31750, 31775]:
    if f"({mcq_id}," in content:
        # Extract question portion
        start = content.find(f"({mcq_id},") + len(f"({mcq_id},")
        end = content.find("',", start) + 2
        question = content[start:end]
        if "నృత్య" in question or "డిజిటల్" in question or "ఖేల్" in question:
            print(f"✓ MCQ {mcq_id}: Telugu found")
        else:
            print(f"✓ MCQ {mcq_id}: Present (check if already bilingual)")

print("\n" + "="*60)
print("✓ BATCH 11 (31726-31775): Telugu translations applied!")
print("="*60)
