"""
Archive of deleted MCQs from seed_intl_events_mcq.py
Curation date: 2026-05-23
"""

ARCHIVED_EVENTS_MCQS = [
    # ID 29011
    {"id":29011,"question_text":"Keir Starmer became UK Prime Minister after Labour's landslide victory in July 2024. Which key India-related agreement did he oversee in 2025?","option_a":"India-UK Defense Partnership Treaty","option_b":"India-UK Comprehensive Economic and Trade Agreement (CETA/FTA)","option_c":"India-UK Nuclear Cooperation Agreement","option_d":"India-UK Climate Alliance","correct_answer":"B","explanation":"UK PM Keir Starmer (Labour, since July 2024) oversaw the India-UK CETA (Comprehensive Economic and Trade Agreement/FTA) — concluded in principle May 6, 2025, signed July 24, 2025. This was a landmark achievement: 99% of Indian exports get duty-free UK access; 90% of UK exports to India get reduced tariffs. Target: double trade to $112 billion by 2030.","folder":"AP_HC","topic":"International_Current_Affairs"},
    # ID 29015
    {"id":29015,"question_text":"To Lam became Vietnam's Communist Party General Secretary in 2024 and continued through 2025-2026. Vietnam's political system is:","option_a":"Multi-party democracy","option_b":"Constitutional monarchy","option_c":"Single-party socialist state led by Communist Party","option_d":"Federal republic","correct_answer":"C","explanation":"Vietnam is a single-party socialist state led by the Communist Party of Vietnam (CPV). To Lam became CPV General Secretary in 2024 after Nguyen Phu Trong died. The General Secretary is Vietnam's most powerful position. Vietnam is a key trade partner for India and has growing cooperation with QUAD countries amid South China Sea tensions with China. Strategic significance for India: To Lam's CPV leadership (2024-26) pursued careful balancing between China and the US-led bloc. Vietnam, a QUAD partner and India's crucial Indo-Pacific ally, is at the frontline of the US-China strategic competition in the South China Sea. India-Vietnam bilateral trade reached $17 billion by 2025, with defense cooperation (naval exercises, submarine transfer, tech partnerships). Vietnam's strategic autonomy concerns align with India's non-aligned foreign policy. To Lam's emphasis on economic opening (FDI inflows, manufacturing diversification away from China) supports India-Vietnam joint ventures in semiconductors, textiles, and defense manufacturing. Vietnam's balancing act between China and the US-India-Japan coalition requires India's diplomatic support at ASEAN forums where India is a Dialogue Partner.","folder":"AP_HC","topic":"International_Current_Affairs"},
    # ID 29017
    {"id":29017,"question_text":"Romuald Wadagni was appointed President of Benin on April 12, 2026. Benin is located in which region of Africa?","option_a":"East Africa","option_b":"Southern Africa","option_c":"West Africa","option_d":"North Africa","correct_answer":"C","explanation":"Benin is in West Africa, bordered by Togo, Burkina Faso, Niger, Nigeria, and the Atlantic Ocean. Capital: Porto-Novo (official)/Cotonou (economic). Benin is historically significant as the Kingdom of Dahomey — known for the slave trade era and contemporary palace of kings. It is a constitutional republic with multi-party democracy, the most politically stable West African nation. Benin is not to be confused with Benin City in Nigeria. Strategic significance for India: Benin is strategically positioned on the Gulf of Guinea (critical global shipping lane for ~4% of global seaborne trade, oil shipments to Europe, and container traffic). For India, West Africa is part of India's maritime focus encompassing African Union HQ in Addis Ababa and critical Indian Ocean trade routes connecting India to Europe via Cape of Good Hope. India-Benin bilateral trade is currently minimal (~$50 million) but represents significant untapped potential. India has strategic interests in West Africa through: (1) Indian Ocean Rim Association (IORA) partnerships involving 23 nations across Africa, Asia, Middle East (India chairs IORA maritime security initiatives), (2) African Union engagement through India's advocacy for UN Security Council permanent seat expansion requiring African coalition support, (3) Diaspora presence in West Africa (Indians in Senegal, Ghana, Nigeria total 100K+ professionals in healthcare, education, commerce). Wadagni's presidency (2026+) coincides with West Africa's intensifying counter-terrorism agenda (Sahel security crises, terrorism spreading from Burkina Faso to Benin, ISIS-linked groups threatening Gulf of Guinea stability). India's counter-terrorism expertise in asymmetric warfare and maritime security capabilities (through Indian Navy's Gulf of Guinea patrols against piracy, African Patrol programs) position India as a valuable strategic partner for Benin. India-Benin cooperation on maritime security, intelligence-sharing on terrorism networks, and capacity-building support India's broader African strategic partnership agenda. India's advocacy for AU reforms and UN Security Council permanent seat aspirations directly depends on coalition-building with African nations like Benin, making bilateral relationship-strengthening a priority for India's multilateral diplomacy.","folder":"AP_HC","topic":"International_Current_Affairs"},
    # ID 29018
    {"id":29018,"question_text":"The 2025 South Korean presidential election was a snap election called after President Yoon was removed. The Constitutional Court upheld Yoon's impeachment on which date?","option_a":"January 14, 2025","option_b":"February 28, 2025","option_c":"April 4, 2025","option_d":"May 15, 2025","correct_answer":"C","explanation":"South Korea's Constitutional Court upheld Yoon Suk-yeol's impeachment on April 4, 2025 — permanently removing him from office. This triggered the snap presidential election won by Lee Jae-myung (Democratic Party) on June 3, 2025. Yoon had declared martial law on December 3, 2024 (retracted after 6 hours) and was impeached by National Assembly on December 14, 2024. Strategic significance for India: South Korea's constitutional crisis tested its democratic institutions. For India, South Korea is critical for: (1) QUAD cooperation (US-Japan-SK intelligence alliance), (2) Semiconductor and tech partnerships (SK's Samsung, SK Hynix), (3) Defense cooperation (Korean shipbuilding JVs, fighter aircraft co-development). Lee Jae-myung's victory (Democratic Party, more centrist than Yoon) shifted SK toward less confrontational approach to North Korea but maintained US alliance. Lee visited India April 19-21, 2026 as first SK President post-inauguration, launching India-Korea Special Strategic Partnership worth $54 billion bilateral trade by 2030. For India, SK's political stability (despite martial law crisis) demonstrated robust constitutional safeguards — unlike some democracies facing democratic backsliding. India-SK cooperation on semiconductors (Taiwan contingency planning, supply chain diversification) gained urgency in 2025-26 amid US-China semiconductor competition.","folder":"AP_HC","topic":"International_Current_Affairs"},
    # ID 29029
    {"id":29029,"question_text":"Hawaii became the first US state to implement a 'Green Fee' on tourists. This fee funds:","option_a":"State military defense","option_b":"Conservation and environmental protection","option_c":"Infrastructure development","option_d":"Healthcare","correct_answer":"B","explanation":"Hawaii became the first US state to implement a 'Green Fee' on tourists — a per-night charge (revenue estimated $25-30 million/year) to fund conservation and environmental protection of Hawaii's fragile ecosystems, marine biodiversity, and watershed restoration. Hawaii faces mass tourism pressure (9+ million annual visitors) straining its coral reefs, native forests, and endemic wildlife. Hawaii is also the state with the US's highest renewable energy commitment (100% clean energy by 2045). Strategic significance for India: Hawaii's environmental taxation model is relevant for India's tourism and conservation strategy. For India: (1) India's coastal tourism — Goa, Maldives, Andaman & Nicobar Islands face similar overtourism pressures; Hawaii's 'Green Fee' model inspired India's tourism boards to propose environmental levies on beach tourists (Goa implemented 2% tourism tax 2026 for coastal cleanup), (2) Marine conservation — India's coral reefs (Andaman, Lakshadweep, Gujarat coast) face bleaching from climate change (35%+ mortality in 2025); Hawaii's conservation model validated India's push for marine protected areas and eco-tourism zoning, (3) Renewable energy alignment — Hawaii's 100% clean energy target by 2045 aligns with India's 2070 net-zero commitment; India-Hawaii clean energy cooperation expanded in 2025 through bilateral MoUs on solar technology and grid storage (critical for island communities facing climate risks). For India's sustainable tourism and climate leadership, Hawaii's Green Fee model strengthened India's domestic advocacy for environmental taxation and circular economy principles in tourism, positioning India as a leader in linking tourism revenue to conservation outcomes.","folder":"AP_HC","topic":"International_Current_Affairs"},
    # ID 29030
    {"id":29030,"question_text":"Pope Francis died on April 21, 2025, at age 88. He was the first Pope from which country?","option_a":"Brazil","option_b":"Spain","option_c":"Argentina","option_d":"Mexico","correct_answer":"C","explanation":"Pope Francis (born Jorge Mario Bergoglio, December 17, 1936, Buenos Aires, Argentina) was the first Pope from Latin America, the first Jesuit Pope, and the first pope from the Global South in over 1,500 years of papal history. He died April 21, 2025 at age 88 after 12 years as Pope (elected March 13, 2013). He succeeded Pope Benedict XVI (who resigned — rare in papal history, only 2nd pope to resign). Strategic significance for India: Pope Francis's papacy (2013-2025) shaped Vatican's Global South engagement, directly affecting India-Vatican relations. For India: (1) Minority protections — Francis prioritized Catholic minority protection in Hindu-majority regions; his advocacy for interfaith dialogue strengthened India's secular fabric and Vatican-India cooperation on religious freedom issues, (2) Climate leadership — Francis's environmental encyclicals (Laudato Si, 2015) aligned with India's climate ambitions; he supported India's climate finance demands at UN conferences, validating India's voice on climate justice for developing nations, (3) Poverty advocacy — Francis's 'preferential option for the poor' resonated with India's anti-poverty programs (Ayushman Bharat, MGNREGA); Vatican-India joint statements on poverty reduction reinforced India's development narrative globally, (4) Geopolitical positioning — Francis maintained Vatican's independence from US hegemony (criticized Iraq War, supported Palestine rights), aligning with India's non-aligned foreign policy traditions. India-Vatican relations under Francis improved through: official state visits (Modi visited Pope in 2014, Pope visited India 2017, Mattarella-Pope exchanges), establishment of diplomatic presence, and joint work on education/healthcare in India. With Pope Leo XIV (American, elected May 8, 2025), India's Vatican engagement faces uncertain recalibration toward potential US alignment, requiring India's careful diplomatic navigation to maintain religious freedom advocacy and climate leadership platforms within the Vatican's evolving geopolitical positioning under American papal leadership.","folder":"AP_HC","topic":"International_Current_Affairs"},
    # ID 29034
    {"id":29034,"question_text":"Saudi Arabia launched which digital tourism platform in 2025 to enhance its global tourism sector?","option_a":"TOURVISION","option_b":"TOURISE","option_c":"Saudi Experience","option_d":"Visit Arabia","correct_answer":"B","explanation":"Saudi Arabia launched the TOURISE platform in 2025 — a digital tourism enhancement platform as part of Saudi Vision 2030. Saudi Arabia has been rapidly developing its tourism sector: NEOM (futuristic city), AlUla (heritage), Red Sea Project (luxury tourism). Saudi Arabia aims to attract 150 million tourists/year by 2030. Strategic significance for India: Saudi Arabia's Vision 2030 pivot toward tourism diversification (away from oil-dependency) creates opportunities for India-Saudi cooperation. For India: (1) Saudi Arabia's tourism infrastructure investments (NEOM, Red Sea resorts) use Indian contractors (Larsen & Toubro, HCC), creating $2-3 billion/year in project contracts, (2) Indian tourists (3.5M+ visitors to Saudi Arabia in 2025) increasingly use digital platforms like TOURISE for visa applications and tourism bookings — standardized digital access benefits Indian travelers, (3) India's tourism ministry's partnership with Saudi Arabia on Hajj/Umrah pilgrimage logistics was enhanced through TOURISE platform's booking integration. India's tech companies (TCS, Infosys) participated in developing TOURISE's backend systems. For India's economic engagement, Saudi Arabia's tourism boom indirectly benefited Indian businesses through hotel/airline partnerships and construction contracts.","folder":"AP_HC","topic":"International_Current_Affairs"},
    # ID 29035
    {"id":29035,"question_text":"Jakarta, Indonesia was described as the world's most populous urban area in 2025 with approximately 42 million people. Why is Jakarta facing an existential crisis?","option_a":"Earthquake risk","option_b":"Flooding and sinking due to excessive groundwater extraction","option_c":"Air pollution","option_d":"Extreme heat","correct_answer":"B","explanation":"Jakarta faces an existential crisis: it is sinking at 1-25 cm/year due to excessive groundwater extraction — making it the world's fastest-sinking major city. Parts of North Jakarta are already below sea level. Indonesia began building a new capital city 'Nusantara' in Borneo to reduce Jakarta's administrative burden. Jakarta remains Indonesia's economic and cultural capital. Strategic significance for India: Jakarta's sinking threatens $1.2 trillion+ of economic infrastructure and 42M people — one of humanity's largest urban crises. For India: (1) Indian companies (Tata, Birla, Reliance) have investments in Jakarta's manufacturing and port facilities — sinking threatens asset values, (2) India-Indonesia bilateral trade (~$17 billion in 2025) depends on Jakarta's port stability; sinking reduces cargo throughput capacity, (3) Indonesian diaspora includes 200K+ Indians working in Jakarta; the sinking crisis created brain drain as Indian expats relocated to safer cities. Indonesia's decision to relocate capital to Nusantara (Borneo, 2024-2035) was driven by Jakarta's existential crisis — a megaproject costing $32+ billion. India's infrastructure expertise (DMRC metro systems) was considered for Nusantara's transport planning, providing Indian tech companies contracting opportunities. The Jakarta sinking crisis highlighted climate change impacts on megacities — a concern for India's coastal cities (Mumbai, Chennai) facing similar sea-level rise and subsidence threats.","folder":"AP_HC","topic":"International_Current_Affairs"},
    # ID 29036
    {"id":29036,"question_text":"The Indonesia-based volcano Mount Lewotobi Laki-laki erupted in 2025. It is located on which island?","option_a":"Java","option_b":"Bali","option_c":"Flores island","option_d":"Sumatra","correct_answer":"C","explanation":"Mount Lewotobi Laki-laki erupted in 2025 on Flores island, East Nusa Tenggara province, Indonesia. 'Laki-laki' means 'male' in Indonesian — there is a paired peak Lewotobi Perempuan ('female'). Indonesia has 127 active volcanoes — the world's most. Indonesia sits on the 'Ring of Fire' — the Pacific tectonic plate boundary. Strategic significance for India: Mount Lewotobi's 2025 eruption (killing 100+ people, displacing 10K+) demonstrated the vulnerability of volcanic regions to natural disasters. For India: (1) India has 37 active volcanoes (Barren Island, Andaman and Nicobar Islands) — Lewotobi eruption reminded India of volcanic monitoring needs, (2) India's geological surveys were called to assist Indonesia in volcanic risk assessment — strengthening India-Indonesia scientific cooperation, (3) Indian disaster relief (NDRF) was considered for deployment if eruption worsened — demonstrating India's first-responder role in the Indian Ocean. Flores island's eruption highlighted the Ring of Fire's seismic/volcanic hazards — a concern for India's Andaman & Nicobar Islands sitting on similar tectonic plate boundaries. India's volcanic monitoring agency (CSIR-NGRI) increased surveillance of Indian volcanoes post-Lewotobi eruption, allocating $50M+ for enhanced monitoring systems.","folder":"AP_HC","topic":"International_Current_Affairs"},
    # ID 29037
    {"id":29037,"question_text":"Typhoon Danas struck which region of Taiwan in 2025?","option_a":"Taipei Metropolitan Area","option_b":"Kaohsiung in southern Taiwan","option_c":"Chiayi County","option_d":"Hualien County","correct_answer":"C","explanation":"Typhoon Danas struck Chiayi County in southwestern Taiwan in 2025, causing floods and landslides. Taiwan faces 3-5 typhoons annually due to its location in the Western Pacific typhoon belt. Taiwan's semiconductor industry (TSMC) facilities in Hsinchu and Tainan were on high alert. Taiwan is also a major geopolitical flashpoint amid China-US tensions. Strategic significance for India: Typhoon Danas's disruption of Taiwan's semiconductor production spiked global chip prices by 8-12%, directly affecting India's tech industry. For India: (1) Taiwan supplies 60%+ of India's semiconductor imports; typhoon-induced shortages created $200M+ supply chain disruptions in Indian IT, consumer electronics, automobile sectors, (2) TSMC's production halt (even 2-day closure) caused cascading delays in India's semiconductor manufacturing initiatives (ISMC Bengaluru, Micron fab in Gujarat), (3) Indian IT companies (TCS, Infosys, Wipro) operating in Taiwan or serving TSMC faced operational challenges during Typhoon Danas. The 2025 typhoon demonstrated Taiwan's critical role in global semiconductor supply chains — a concern for India's tech sovereignty. For India's strategic planning: (1) India accelerated domestic semiconductor manufacturing to reduce Taiwan dependency, (2) India's partnerships with South Korea (Samsung), Japan (Sony) for chip production were strengthened as backup suppliers. India's push for semiconductor self-reliance under National Semiconductor Policy gained urgency post-Typhoon Danas.","folder":"AP_HC","topic":"International_Current_Affairs"},
    # ID 29055
    {"id":29055,"question_text":"SICA (Central American Integration System) was established by which treaty in 1991?","option_a":"Tegucigalpa Protocol","option_b":"Treaty of Asunción","option_c":"Cartagena Agreement","option_d":"Bogotá Protocol","correct_answer":"A","explanation":"SICA (Sistema de la Integración Centroamericana / Central American Integration System) was established by the Tegucigalpa Protocol (signed December 13, 1991 in Tegucigalpa, Honduras) replacing the earlier General Treaty on Central American Economic Integration (SIECA, 1960). SICA Members: Guatemala, El Salvador, Honduras, Nicaragua, Costa Rica, Panama, Belize, Dominican Republic (8 countries). HQ: San Salvador, El Salvador. Established 1993, operational since 1995. Strategic significance for India: SICA represents Central America's regional integration aspirations. For India: (1) Cultural/developmental engagement — India has growing diaspora in Central America (Costa Rica, Panama ~50,000 Indians); SICA partnerships strengthen India's engagement with the Western Hemisphere Latin America bloc, (2) Trade potential — India-Central America trade (~$2B/year) is underdeveloped; SICA-India cooperation (through forums like India-CELAC — Community of Latin American and Caribbean States) could expand to technology partnerships, agri-tech, pharmaceuticals, (3) Climate finance — SICA nations are climate-vulnerable (hurricanes, flooding); India's advocacy in UN climate negotiations for climate finance benefits Central American nations; India-SICA climate adaptation partnerships could grow, (4) Multilateral positioning — SICA's integration model demonstrates South-South cooperation principles India advocates; India recognizes SICA as a peer bloc in advocating for developing nations' interests in global governance. For India's Latin America strategy, SICA represents a consolidating Central American bloc that India can engage on trade, climate, and development issues, reducing fragmentation and increasing bargaining power.","folder":"AP_HC","topic":"International_Current_Affairs"},
    # ID 29067
    {"id":29067,"question_text":"Pope Leo XIV (Robert Prevost) is historically significant as:","option_a":"First Pope from Asia","option_b":"First American Pope and first Pope from the Order of Augustine","option_c":"First Pope from a Protestant country","option_d":"Youngest Pope in 200 years","correct_answer":"B","explanation":"Pope Leo XIV (Robert Prevost, born Chicago 1952) is historically significant as: (1) First American Pope ever in Church history (elected May 8, 2025) — surpassing all 265 previous popes, (2) First Pope from the Augustinian order (Order of Saint Augustine) — most popes are from Jesuit or Dominican orders. He was elected 4 days after Pope Francis died (April 21, 2025). He chose 'Leo XIV' deliberately, referencing Pope Leo XIII (1878-1903) known for groundbreaking social justice encyclicals ('Rerum Novarum' on labor rights). Pope Leo XIV's multilingual abilities (English, Spanish, Italian, French) and missionary background (Peru) position him to engage Global South constituencies effectively. Strategic significance for India: An American pope represents Vatican's geopolitical recalibration. For India: (1) Vatican-US relations — An American pope may tilt Vatican foreign policy more favorably toward US interests than Pope Francis (who maintained independence), affecting Vatican's stances on China, Russia, Middle East, (2) India-Vatican ties — India has 19M+ Catholics; Leo XIV's pastoral style (emphasizing social justice, seen in Peru missionary work) could align with India's development priorities and poverty alleviation focus, (3) Religious dialogue — Leo XIV's openness to interfaith dialogue (demonstrated through Peru work with indigenous Catholics) could strengthen India-Vatican cooperation on Hindu-Christian-Sikh dialogue and minority protection. For India's diplomacy, monitoring Leo XIV's early papal decisions on geopolitical issues (Middle East wars, China relations, India-Pakistan tensions) is important for recalibrating India's Vatican engagement strategy.","folder":"AP_HC","topic":"International_Current_Affairs"},
    # ID 29071
    {"id":29071,"question_text":"Which country's university (ETH Zürich) published an assessment on India's air superiority in Operation Sindoor 2025?","option_a":"Germany","option_b":"Austria","option_c":"Switzerland","option_d":"Netherlands","correct_answer":"C","explanation":"ETH Zürich (Eidgenössische Technische Hochschule Zürich / Swiss Federal Institute of Technology) is in Zurich, Switzerland. Its Center for Security Studies (CSS) published detailed technical analysis on India's air superiority tactics and precision strike capabilities demonstrated in Operation Sindoor (May 7, 2025) against terrorist camps in Pakistan/PoK. ETH Zürich is consistently ranked among the world's top universities (along with MIT, Cambridge, Oxford, Stanford). Notable alumni: Albert Einstein (1896-1900), 21 Nobel Prize winners. Strategic significance for India: International academic recognition of India's military capabilities enhances India's strategic credibility. For India: (1) CSS analysis validated Operation Sindoor's technical success — India's precision targeting of 9 camps, rapid execution (16 days from Pahalgam attack to strikes), and ceasefire restraint demonstrated modern air power management, (2) Geopolitical messaging — ETH Zürich's neutral, scholarly assessment (vs. geopolitical think-tanks with bias) carries weight in international policy circles; India's demonstration of capability influences QUAD allies' confidence in India's defense readiness, (3) Technology expertise — ETH Zürich's engineering faculty (robotics, AI, aerospace) increasingly collaborates with India on dual-use technologies relevant to defense (TUSAS-India drone partnerships, satellite systems), (4) Soft power — Switzerland's neutrality and academic prestige lend credibility; when Swiss institutions publish India-positive assessments, it validates India's narratives in international media. For India's military modernization, Operation Sindoor and its international analysis demonstrate the value of precision strike capabilities as deterrents against terrorism — influencing India's defense budgeting priorities and QUAD coordination on drone/AI technologies.","folder":"AP_HC","topic":"International_Current_Affairs"},
    # ID 29076
    {"id":29076,"question_text":"South Korea held a snap presidential election on June 3, 2025. Who was the new President-elect who defeated the conservative candidate?","option_a":"Yoon Suk-yeol","option_b":"Han Duck-soo","option_c":"Lee Jae-myung","option_d":"Ahn Cheol-soo","correct_answer":"C","explanation":"Lee Jae-myung (Democratic Party, centrist-progressive) won South Korea's June 3, 2025 snap presidential election with 50.7% of vote, defeating conservative candidate Han Duck-soo (31.4%). Lee had previously narrowly lost the 2022 presidential election to Yoon Suk-yeol (Conservative party). Lee became President following Yoon Suk-yeol's Constitutional Court impeachment removal on April 4, 2025 (triggered by Yoon's illegal December 3, 2024 martial law declaration). Lee also hosted APEC 2025 Summit in Gyeongju, South Korea (November 2025). Strategic significance for India: South Korea's political transition affects QUAD dynamics and Indo-Pacific strategy. For India: (1) QUAD coordination — Lee's Democratic Party is traditionally less hawkish on North Korea than conservatives; Lee's inauguration (May 10, 2025) meant the first Democratic president in QUAD in years. However, Lee maintained US alliance and QUAD commitment, (2) Defense cooperation — Lee visited India April 19-21, 2026, launching India-Korea Special Strategic Partnership with $54B bilateral trade target, semiconductor/shipbuilding MoUs, showcasing Lee's commitment to India ties despite his centrist positioning, (3) North Korea policy — Lee's more dialogue-oriented North Korea approach (vs. conservative hawkishness) potentially eases Korean Peninsula tensions, benefiting India's regional stability interests and energy security (Korean Peninsula conflict could disrupt regional supply chains). For India-South Korea partnership, Lee's presidency opened new opportunities in AI, green energy, and defense manufacturing cooperation announced during his India visit.","folder":"AP_HC","topic":"International_Current_Affairs"},
    # ID 29079
    {"id":29079,"question_text":"Which Indian city was ranked as the world's most populous urban area in 2025 by the United Nations?","option_a":"Mumbai","option_b":"Delhi","option_c":"Kolkata","option_d":"Bengaluru","correct_answer":"B","explanation":"Delhi National Capital Region (NCR) was ranked the world's most populous urban area in 2025 by UN Habitat — surpassing Tokyo (previous #1). Delhi NCR's metropolitan population: 33+ million in city proper (within Delhi municipal corporation), 35+ million in Greater Delhi NCR (including suburban districts in Haryana, Uttar Pradesh). Tokyo's population declined to ~32M due to Japan's shrinking demographics. Note: Jakarta's measurement at ~42M reflects Greater Jakarta (Jabodetabek) including suburban zones; different methodologies (city proper vs. metropolitan area) produce variations in rankings. Strategic significance for India: Delhi's status as world's most populous urban area reflects India's demographic scale and urbanization pace. For India: (1) Infrastructure pressure — Delhi's 35M+ population strains water supply (Yamuna depletion, groundwater extraction dropping aquifers 2-3m/year), transport (metro expansion ongoing, pollution crises in winter), waste management (landfill crisis), housing (migrant slums proliferating), (2) Climate vulnerability — Delhi faces heat stress intensifying (52°C+ summer peaks by 2025); rapid urbanization in semi-arid region exacerbates heat island effects. Delhi's ranking validates India's climate action urgency — urban heat mitigation becomes critical for 35M people's survival, (3) Development model — Delhi as world's largest metropolitan area by population (not GDP or economic output) reveals India's development challenge: massive population without proportional GDP/job generation. Policy priority shifts to job creation, skills training, livelihood diversification for Delhi's labor-surplus, capital-sparse economy. For India's urbanization strategy, Delhi's #1 global ranking validates investment in metro systems, smart city infrastructure, affordable housing — critical for managing growth humanely. Delhi's ranking also strengthens India's voice in global urban development forums, positioning India as a leader in addressing megacity challenges.","folder":"AP_HC","topic":"International_Current_Affairs"},
    # ID 29081
    {"id":29081,"question_text":"Tarique Rahman is set to become Bangladesh's Prime Minister after the February 12, 2026 election. His party (BNP) won how many of the declared seats?","option_a":"150 of 297","option_b":"180 of 297","option_c":"209 of 297","option_d":"250 of 297","correct_answer":"C","explanation":"The BNP (Bangladesh Nationalist Party), led by Tarique Rahman, won 209 of 297 declared seats in the February 12, 2026 election (59.88% turnout) — a landslide. Jamaat-e-Islami was principal opposition (68 seats). It was Bangladesh's first election after the 2024 student uprising removed Sheikh Hasina (Awami League). Tarique returned in Dec 2025 after 17 years of exile in London, succeeding his mother Khaleda Zia (died Dec 2025) as BNP leader. Strategic significance for India: Tarique's BNP represents a pro-Pakistan, anti-India tilt compared to Hasina's Awami League which maintained close India ties. BNP's landslide shifts Bangladesh away from India's sphere — a critical geopolitical loss for India's South Asia dominance. Key concerns for India: (1) Rohingya repatriation — Tarique may coordinate with Pakistan on Rohingya camps (~900K in Cox's Bazar), affecting India's stance; (2) Border disputes — the 1974 Indus Waters Treaty equivalent (Ganges Water Sharing Treaty 1996) may face pressure for renegotiation; (3) China-Bangladesh infrastructure — BNP may accelerate Chinese Belt & Road projects (Padma Bridge, power plants) over India's interests; (4) Terrorism — historically BNP had weak counter-terrorism measures, risking LeT/JeM resurgence affecting India's Northeast security. India's strategic challenge: rebuilding ties with Tarique after supporting Hasina, while managing a fundamental shift in Bangladesh's geopolitical alignment from India toward Pakistan-China partnership.","folder":"AP_HC","topic":"International_Current_Affairs"},
    # ID 29088
    {"id":29088,"question_text":"Mark Rutte became NATO Secretary-General on October 1, 2024. He was previously Prime Minister of which country (longest-serving PM in its history)?","option_a":"Belgium","option_b":"Denmark","option_c":"Netherlands","option_d":"Norway","correct_answer":"C","explanation":"Mark Rutte (Netherlands) — Dutch PM 2010-2024 (~14 years) — became NATO's 14th Secretary-General on Oct 1, 2024, succeeding Jens Stoltenberg. NATO HQ: Brussels. Founded 1949. Has 32 members (Finland 2023, Sweden Mar 2024). Rutte's main challenges: Russia-Ukraine, US burden-sharing under Trump. Strategic significance for India: Rutte's NATO leadership (2024-28) impacts India's strategic positioning. NATO's focus on Russia containment directly affects: (1) NATO's expansion toward Indo-Pacific (partnerships with Japan, South Korea, Australia); (2) European arms supply to India and Indo-Pacific partners (artillery, air defense systems for Taiwan, Philippines); (3) NATO's cyber security standards influence India's defense modernization. Rutte's pragmatic approach to US burden-sharing aligns with India's appeals for burden-sharing in regional security — particularly in Indo-Pacific where India faces dual challenges from China and Pakistan. NATO's Indo-Pacific focus (through India partnerships) supports India's multipolarity narrative against Chinese hegemony.","folder":"AP_HC","topic":"International_Current_Affairs"},
    # ID 29090
    {"id":29090,"question_text":"Claudia Sheinbaum was sworn in as Mexico's President on October 1, 2024. Which historic milestone does she represent?","option_a":"Youngest Mexican President","option_b":"First woman President of Mexico (and first of Jewish descent)","option_c":"First indigenous Mexican President","option_d":"First President to serve a 4-year term","correct_answer":"B","explanation":"Claudia Sheinbaum (Morena party) was sworn in as Mexico's first female President on October 1, 2024 — also Mexico's first president of Jewish descent. A climate scientist (PhD), she was former Head of Mexico City (2018-2023). Key challenge in 2025-26: managing Trump's tariffs. Strategic significance for India: Sheinbaum's presidency represents Latin America's democratic evolution toward gender representation — a trend that strengthens India's advocacy for women in global governance. For India-Mexico relations: (1) Climate cooperation — Sheinbaum's expertise aligns with India's climate leadership (India chairs COP29, UN climate initiatives); (2) Tech and renewable energy — Mexico-India partnerships on solar manufacturing and lithium mining (critical for EV batteries) expand; (3) Geopolitical significance — Mexico's position in the US-China-India competition affects Indian tech exports through USMCA. Sheinbaum's independence from Trump's tariff pressures signals Latin America's strategic autonomy, supporting India's multipolarity narrative.","folder":"AP_HC","topic":"International_Current_Affairs"},
    # ID 29091
    {"id":29091,"question_text":"Prabowo Subianto was sworn in as Indonesia's 8th President on October 20, 2024. He was previously Defence Minister and the running mate in 2024 was the son of the previous president. Who?","option_a":"Joko Widodo Jr.","option_b":"Gibran Rakabuming Raka (son of Jokowi)","option_c":"Megawati's son","option_d":"Anies Baswedan","correct_answer":"B","explanation":"Prabowo Subianto (Gerindra party) was sworn in as Indonesia's 8th President on October 20, 2024. VP: Gibran Rakabuming Raka (Jokowi's eldest son). Court ruling lowered age requirement for 36-year-old Gibran. Prabowo, ex-Defence Minister (2019-2024) and ex-general, oversaw Indonesia's January 2025 entry into BRICS as 11th full member. Strategic significance for India: Prabowo's presidency (2024-29) marks critical shift in Indonesia's positioning — from Jokowi's balancing act to more nationalist, military-influenced approach. For India: (1) BRICS membership — Indonesia's accession on Prabowo's watch strengthens India-Indonesia-BRICS alignment on multipolarism, de-dollarization; (2) Defence cooperation — Prabowo prioritizes defense modernization — India-Indonesia defense partnerships deepen (ship-building, defense manufacturing; $1B trade target); (3) South China Sea — Prabowo's military background signals firm stance against Chinese assertiveness, supporting India's FOIP strategy; (4) ASEAN coordination — Indonesia, ASEAN chair 2024, works with India on counter-terrorism, maritime security, supply chain resilience in Indo-Pacific.","folder":"AP_HC","topic":"International_Current_Affairs"},
    # ID 29092
    {"id":29092,"question_text":"Anura Kumara Dissanayake (AKD) became Sri Lanka's President in September 2024. His party-coalition NPP won a parliamentary supermajority. NPP stands for:","option_a":"National Patriotic Party","option_b":"National People's Power","option_c":"Nationalist Peace Pact","option_d":"New Progressive Party","correct_answer":"B","explanation":"Anura Kumara Dissanayake (AKD) of the JVP-led NPP coalition was elected Sri Lanka's 9th President on September 21, 2024. In November 14, 2024 snap parliamentary election, NPP won 2/3 supermajority (159/225 seats) — first true leftist supermajority in Sri Lanka's history. Pursued anti-corruption reforms, IMF continuation, and balanced India-China ties. Visited India (Dec 2024) — first foreign visit. Strategic significance for India: AKD's NPP landslide represents historic political realignment in Sri Lanka — from family dynasties to left-leaning anti-corruption coalition. For India: (1) Anti-corruption agenda — AKD's reforms target corruption that earlier weakened India's projects (ports, railways); (2) Debt restructuring — Sri Lanka's IMF program (post-April 2022 bankruptcy) affects India's BD port stakes (Colombo Port); (3) Strategic autonomy — AKD balances India-China ties (rejects Chinese debt-trap accusations, maintains Chinese investment) while strengthening India ties; (4) India-Sri Lanka relations — AKD's Dec 2024 India visit signaled commitment to regional partnership (fisheries, Tamil minority concerns, religious harmony). India navigates NPP's socialist leanings while securing Sri Lankan waters (critical for Indian Ocean naval operations).","folder":"AP_HC","topic":"International_Current_Affairs"},
]


ARCHIVED_ORGS_MCQS = [
    # ID 20011
    {
        "id": 20011,
        "question": "The G20 was established in 1999. Which body did it replace as the primary economic forum among major economies?",
        "option_a": "G7", "option_b": "G8", "option_c": "G22 (Dean's Group)", "option_d": "G15",
        "correct_answer": "C",
        "explanation": "G20 was established on September 26, 1999, emerging from the G22 (Dean's Group) and G33 meetings. It was created in response to the 1997-98 Asian financial crisis. G20 Finance Ministers first met in Berlin, December 1999.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ID 20014
    {
        "id": 20014,
        "question": "Which country hosted the G20 Summit in 2024 under the theme 'Building a Just World and a Sustainable Planet'?",
        "option_a": "India", "option_b": "Argentina", "option_c": "South Africa", "option_d": "Brazil",
        "correct_answer": "D",
        "explanation": "Brazil hosted the 19th G20 Summit in Rio de Janeiro on November 18-19, 2024. Theme: 'Building a Just World and a Sustainable Planet.' Brazilian priorities included hunger eradication (Global Alliance Against Hunger), climate finance reform, and taxing ultra-wealthy individuals.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ID 20020
    {
        "id": 20020,
        "question": "BRICS originally began as 'BRIC' (without South Africa). Who coined the term 'BRIC' in 2001?",
        "option_a": "IMF economist Olivier Blanchard", "option_b": "Goldman Sachs economist Jim O'Neill", "option_c": "World Bank President James Wolfensohn", "option_d": "WTO DG Mike Moore",
        "correct_answer": "B",
        "explanation": "Jim O'Neill of Goldman Sachs coined the term 'BRIC' in his 2001 paper 'Building Better Global Economic BRICs.' The first formal BRIC summit was held in Yekaterinburg, Russia in June 2009. South Africa joined in 2010, making it BRICS.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ID 20021
    {
        "id": 20021,
        "question": "Five countries joined BRICS as full members on January 1, 2024. Which country, though invited, declined BRICS membership?",
        "option_a": "Turkey", "option_b": "Nigeria", "option_c": "Argentina", "option_d": "Mexico",
        "correct_answer": "C",
        "explanation": "Argentina was invited to join BRICS in 2023 but declined in December 2023 — new President Javier Milei, an economic libertarian, reversed the previous government's decision. The five countries that did join on January 1, 2024 were Egypt, Ethiopia, Iran, UAE, and Saudi Arabia.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ID 20022
    {
        "id": 20022,
        "question": "The 17th BRICS Summit 2024 was held in Kazan, Russia. Which key geopolitical issue dominated discussions?",
        "option_a": "China-Taiwan tensions", "option_b": "Russia's isolation and the war in Ukraine", "option_c": "North Korea's nuclear programme", "option_d": "India-Pakistan conflict",
        "correct_answer": "B",
        "explanation": "The 17th BRICS Summit (Kazan, Russia, October 22-24, 2024) was significant for Russia hosting despite Western sanctions over the Ukraine war. The summit discussed BRICS expansion, de-dollarisation, and a new payment system alternative to SWIFT. India's PM Modi attended.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ID 20026
    {
        "id": 20026,
        "question": "Which country hosted the G7 Summit in 2024 under the theme 'For the Mediterranean, for humanity, for the future'?",
        "option_a": "Germany", "option_b": "Japan", "option_c": "Italy", "option_d": "France",
        "correct_answer": "C",
        "explanation": "Italy hosted the 50th G7 Summit in Puglia (Borgo Egnazia) on June 13-15, 2024. Theme: 'For the Mediterranean, for humanity, for the future.' India PM Modi attended. Key outcomes: Ukraine aid, AI governance, migration, and climate.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ID 20027
    {
        "id": 20027,
        "question": "G7 originally began as G6 in 1975 with 6 founding members. Which country joined in 1976 to make it G7?",
        "option_a": "Japan", "option_b": "Italy", "option_c": "Canada", "option_d": "Germany",
        "correct_answer": "C",
        "explanation": "G6 was founded in November 1975 (Rambouillet, France) by USA, UK, France, Germany, Japan, Italy. Canada joined in 1976 to make it G7. The EU joined as a non-enumerated member in 1977. Russia joined in 1998 making it G8, but was suspended in 2014.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ID 20045
    {
        "id": 20045,
        "question": "Which country, a SCO member, was NOT present at the SCO Heads of Government meeting in Islamabad, Pakistan in October 2024?",
        "option_a": "China", "option_b": "Russia", "option_c": "India", "option_d": "Kazakhstan",
        "correct_answer": "C",
        "explanation": "India's PM Modi did not attend the SCO meeting in Islamabad, Pakistan (October 2024) due to strained India-Pakistan relations. India was represented at a lower level. This highlighted the diplomatic complexities within SCO given that India and Pakistan are both members.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ID 20064
    {
        "id": 20064,
        "question": "The African Union Commission Chairperson since 2021 is from which country?",
        "option_a": "Nigeria", "option_b": "South Africa", "option_c": "Senegal", "option_d": "Kenya",
        "correct_answer": "C",
        "explanation": "Moussa Faki Mahamat (Chad) was AU Commission Chairperson from 2017-2025. Mauritania's Abdel-Fattah al-Sisi held AU Presidency in 2019. Senegal's Macky Sall was AU Chairperson in 2022. The AU Chairship rotates — held by Ethiopia's PM Abiy Ahmed in 2025.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ID 20066
    {
        "id": 20066,
        "question": "The 13th WTO Ministerial Conference (MC13) was held in February 2024 in which city?",
        "option_a": "Geneva", "option_b": "Abu Dhabi", "option_c": "Nairobi", "option_d": "Buenos Aires",
        "correct_answer": "B",
        "explanation": "MC13 was held in Abu Dhabi, UAE, in February 2024. Key outcomes included extending the e-commerce moratorium and fisheries subsidies negotiations. The MC14 is planned for 2026. Previous WTO Ministerial Conferences: Geneva (MC12, 2022), Buenos Aires (MC11, 2017).",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ID 20068
    {
        "id": 20068,
        "question": "India and MERCOSUR (South American trade bloc) signed a Preferential Trade Agreement in which year?",
        "option_a": "2009", "option_b": "2015", "option_c": "2004", "option_d": "2019",
        "correct_answer": "C",
        "explanation": "India-MERCOSUR Preferential Trade Agreement (PTA) was signed in 2004 and came into effect in June 2009. MERCOSUR (Southern Common Market) = Brazil, Argentina, Uruguay, Paraguay. India-MERCOSUR trade has grown significantly; discussions on a more comprehensive FTA are ongoing.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ID 20070
    {
        "id": 20070,
        "question": "The India-Middle East-Europe Economic Corridor (IMEC) was announced at which summit in 2023 and reconfirmed in 2025?",
        "option_a": "COP28 Dubai", "option_b": "QUAD Summit Tokyo", "option_c": "G20 New Delhi Summit", "option_d": "G7 Hiroshima Summit",
        "correct_answer": "C",
        "explanation": "IMEC (India-Middle East-Europe Economic Corridor) was formally launched at the G20 New Delhi Summit on September 9, 2023, with PM Modi, US President Biden, Saudi Arabia's Crown Prince, UAE President, and EU representatives. The initiative comprises two interconnected corridors: (1) India-Gulf Corridor linking Indian ports (Mumbai, Jawaharlal Nehru Port Trust) via maritime and rail to Gulf states (UAE, Saudi Arabia), facilitating export of Indian goods, (2) Gulf-Europe Corridor extending from Gulf through Jordan/Israel to Europe (via ports, rail, digitized logistics). Partners: India, UAE, Saudi Arabia, Jordan, Israel, USA, EU. Financing: World Bank, major development banks. Strategic objectives: (1) counter China's Belt and Road Initiative (BRI) dominance in Asia-Europe trade, (2) diversify trade routes beyond Suez Canal dependency, (3) boost India's role as crucial link between Asia-Europe commerce, (4) strengthen India-Arab ties and Israel normalization (controversial given Palestinian concerns), (5) enhance supply-chain resilience post-COVID. IMEC complements India's multipolarity strategy: combining QUAD security partnership with economic corridors reducing China's leverage. By 2025, IMEC feasibility studies progressed; formal construction timelines discussed for port modernization, rail electrification, and digital customs integration—critical for India's trade competitiveness.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ID 20075
    {
        "id": 20075,
        "question": "The 'Loss and Damage' fund agreed at COP27 (Egypt, 2022) became fully operational. Which institution is hosting this fund?",
        "option_a": "UNDP", "option_b": "World Bank", "option_c": "IMF", "option_d": "ADB",
        "correct_answer": "B",
        "explanation": "Loss and Damage (L&D) Fund, negotiated over 30+ years at COPs, was finally agreed at COP27 (Sharm el-Sheikh, Egypt, November 2022) and operationalized at COP28 (Dubai, December 2023) with World Bank as interim trustee. L&D Fund addresses 'unavoidable' climate impacts beyond mitigation/adaptation scope: sea-level rise threatening small island states, extreme weather destroying infrastructure, drought causing famines. Fund size: initial $700 million pledged (COP28); target $100 billion+ annually (unfunded gap). Allocation: 50% for vulnerable countries, 25% for LDCs/SIDs, 25% for Africa. Governance: 50-member board with developing-country majority (reflecting equity principle). For India: L&D Fund critical because: (1) India's extreme climate vulnerability (monsoons, glacial melts, sea-level rise affecting 7,500km coastline), (2) India's development-rights advocacy (climate change caused by developed nations' historical emissions), (3) India's large poor population exposed to climate shocks (agriculture-dependent, monsoon-reliant). India negotiated hard at COP27-28 for: (1) L&D Fund without conditionalities, (2) differentiation (developed countries contribute more), (3) accessible financing (minimal red-tape disbursement). World Bank hosting reflects compromise: accessible institution but developed-country institutional bias concerns. India pushes for dedicated L&D governance structure independent of climate mitigation/adaptation frameworks by 2030.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ID 20078
    {
        "id": 20078,
        "question": "The Rome-based United Nations food agencies include FAO, WFP, and IFAD. Which of these specifically focuses on providing EMERGENCY food aid?",
        "option_a": "FAO", "option_b": "WFP", "option_c": "IFAD", "option_d": "Codex Alimentarius Commission",
        "correct_answer": "B",
        "explanation": "WFP (World Food Programme) provides emergency food aid and humanitarian assistance. FAO (Food and Agriculture Organization) focuses on food security and agricultural development. IFAD (International Fund for Agricultural Development) finances rural agricultural projects. All three are based in Rome.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ID 20089
    {
        "id": 20089,
        "question": "Approximately how many aircraft did the US deploy in 'Operation Absolute Strike' against Venezuela on January 3, 2026?",
        "option_a": "50", "option_b": "100", "option_c": "150", "option_d": "250",
        "correct_answer": "C",
        "explanation": "About 150 US aircraft — including F-22 Raptor and F-35 Lightning II stealth fighters and B-1 Lancer bombers — were deployed in Operation Absolute Strike (Jan 3, 2026) targeting military bases around Caracas. President Maduro was captured and flown to New York.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ID 20095
    {
        "id": 20095,
        "question": "How many attacks on Hindus have been recorded in Bangladesh since August 2024, as reported during the January 2026 unrest?",
        "option_a": "Over 600", "option_b": "Over 1,200", "option_c": "Over 2,600", "option_d": "Over 5,000",
        "correct_answer": "C",
        "explanation": "More than 2,600 attacks on Hindus have been recorded in Bangladesh since August 2024 (when the Sheikh Hasina government fell). Incidents include the lynching of Hindu Dipu Chandra Das in Mymensingh on December 18, 2025, and the killing of Inquilab Manch leader Sharif Osman Hadi on December 12, 2025.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ID 20106
    {
        "id": 20106,
        "question": "In which year did Somaliland — formally recognised by Israel in December 2025 — declare its separation from Somalia?",
        "option_a": "1977", "option_b": "1991", "option_c": "2001", "option_d": "2011",
        "correct_answer": "B",
        "explanation": "Somaliland declared independence from Somalia in 1991 following the collapse of the Siad Barre regime. After 34 years without international recognition, Israel became the first country to formally recognise Somaliland on December 26, 2025.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ID 20108
    {
        "id": 20108,
        "question": "In which year did Pakistan cede the Shaksgam Valley to China — a cession India refuses to recognise and reiterated in its January 2026 protest?",
        "option_a": "1948", "option_b": "1963", "option_c": "1971", "option_d": "1989",
        "correct_answer": "B",
        "explanation": "Pakistan ceded the Shaksgam Valley (~5,180 sq km) to China under the 1963 Sino-Pakistan Boundary Agreement. India does not recognise the transfer as Pakistan-occupied Kashmir is claimed by India. India also rejects the China-Pakistan Economic Corridor (CPEC) passing through PoK.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ID 20117
    {
        "id": 20117,
        "question": "In Japan's mid-term election on February 8, 2026, how many of the 465 lower-house seats did the Liberal Democratic Party (LDP) win?",
        "option_a": "233", "option_b": "278", "option_c": "316", "option_d": "402",
        "correct_answer": "C",
        "explanation": "The Liberal Democratic Party (LDP) won 316 of 465 seats in Japan's lower house mid-term election on February 8, 2026, giving it a two-thirds supermajority. Sanae Takaichi was then sworn in as Japan's first female Prime Minister.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ID 20122
    {
        "id": 20122,
        "question": "The Kashiwazaki-Kariwa restart on February 3, 2026, was significant because it was Japan's first such restart since which event?",
        "option_a": "1995 Kobe earthquake", "option_b": "2011 Fukushima Daiichi disaster", "option_c": "2016 Kumamoto earthquakes", "option_d": "2018 Hokkaido earthquake",
        "correct_answer": "B",
        "explanation": "The Kashiwazaki-Kariwa restart (Feb 3, 2026) was Japan's first nuclear plant restart since the March 11, 2011 Fukushima Daiichi disaster, which had led to a nationwide shutdown of nuclear power. Japan has been gradually reviving nuclear energy amid energy security concerns.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ID 20123
    {
        "id": 20123,
        "question": "On January 27, 2026, France voted (180-21) to ban social media for under-15s, becoming the second country in the world to do so. Which was the first?",
        "option_a": "United Kingdom", "option_b": "Norway", "option_c": "Australia", "option_d": "Germany",
        "correct_answer": "C",
        "explanation": "Australia was the first country to legislate a social-media ban for minors (under-16) in late 2024. France's National Assembly voted 180-21 on January 27, 2026, to ban social media for under-15s, becoming the second country to enact such a ban.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ID 20124
    {
        "id": 20124,
        "question": "On January 27, 2026, which country, bucking the US/EU trend, voted to grant legal status to undocumented migrants?",
        "option_a": "Italy", "option_b": "Portugal", "option_c": "Spain", "option_d": "Ireland",
        "correct_answer": "C",
        "explanation": "Spain voted on January 27, 2026, to grant legal status to undocumented migrants — moving against the broader US and EU trend of tightening migration policy. PM Pedro Sánchez's coalition cited demographic and labour-market needs.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ID 20131
    {
        "id": 20131,
        "question": "The Genome Valley Excellence Award at the 23rd BioAsia at Hyderabad (Feb 17-18, 2026), themed 'TechBio Unleashed', was presented to whom?",
        "option_a": "Dr. Soumya Swaminathan", "option_b": "Dr. Bruce L. Levine", "option_c": "Dr. Gagandeep Kang", "option_d": "Dr. Krishna Ella",
        "correct_answer": "B",
        "explanation": "Dr. Bruce L. Levine (University of Pennsylvania, pioneer of CAR-T cell therapy) received the Genome Valley Excellence Award at the 23rd BioAsia, held in Hyderabad on February 17-18, 2026. The theme was 'TechBio Unleashed', focusing on the convergence of biology and technology.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
    # ID 20133
    {
        "id": 20133,
        "question": "In which year was the New START Treaty originally signed before it expired in February 2026?",
        "option_a": "1991", "option_b": "2002", "option_c": "2010", "option_d": "2017",
        "correct_answer": "C",
        "explanation": "The New START Treaty was signed in Prague on April 8, 2010, by US President Barack Obama and Russian President Dmitry Medvedev, entering into force in 2011. It capped each side's deployed strategic nuclear warheads at 1,550 and expired on February 5, 2026.",
        "folder": "AP_HC", "topic": "International_Current_Affairs",
    },
]
