#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Insert batch 8 MCQs 31626-31650 before batch 9"""

with open('seed_national_ca_2026_mcq.py', 'r', encoding='utf-8') as f:
    content = f.read()

# Find the insertion point - before "# ── BATCH 9: Education & Skills (31651-31675) ──"
insert_marker = "\n        # ── BATCH 9: Education & Skills (31651-31675) ──"
pos = content.find(insert_marker)

if pos == -1:
    print("ERROR: Could not find batch 9 marker")
    exit(1)

# MCQs in simple format - one per line for clarity
batch_8_mcqs = """
        # ── BATCH 8: Healthcare & AYUSH Integration (31626-31650) ──
        (31626, "సమన్విత ఆరోగ్య సరఫరా వ్యవస్థ యొక్క దృష్టిభంగం ఏమిటి? | What is the focus of the new 'Integrated Healthcare Delivery System' launched in May 2026?", 'ఆయువేదం, యోగం, యూనానీ, సిద్ధం తో ఆధునిక వైద్యం సమన్వయం (AYUSH ఇంటిగ్రేషన్) | Integration of Ayurveda, Yoga, Unani, Siddha with Allopathic medicine (AYUSH integration)', 'ప్రభుత్వ మరియు ఆర్జన్యూత ఆరోగ్య సేవల ఏకీకరణ | Unification of public and private healthcare with standardized pricing', 'ఆన్‌లైన్ దూరసంచారం మరియు ఆఫ్‌లైన్ ఆసుపత్రి సంధర్భం | Integration of online telemedicine with offline hospital infrastructure', 'కేంద్ర మరియు రాష్ట్ర ఆరోగ్య వ్యవస్థల విలీనం | Merging of central and state health systems under single administration', 'A', "సమన్విత ఆరోగ్య సరఫరా వ్యవస్థ సాంప్రదాయిక భారతీయ వ్యవస్థలు (AYUSH) ను ఆధునిక వైద్యంతో సమన్వయం చేయడానికి దృష్టి సారించింది. | The 'Integrated Healthcare Delivery System' launched in May 2026 focuses on comprehensive integration of Traditional Indian Systems (Ayurveda, Yoga, Unani, Siddha - AYUSH) with Allopathic medicine to create a synergistic healthcare model.", 'AP_HC', 'National_Current_Affairs_2026'),
        (31627, 'మాతృత్వ మరియు శిశు ఆరోగ్య కార్యక్రమాల కోసం బడ్జెట్ కేటాయణ ఏది? | What was the allocation for maternal and child health programs in the May 2026 Union Budget?', '₹4,200 కోట్లు | ₹4,200 crores with focus on reducing MMR to below 60', '₹6,800 కోట్లు | ₹6,800 crores with focus on achieving universal immunization', '₹8,500 కోట్లు | ₹8,500 crores with focus on anemia elimination and child nutrition', '₹12,300 కోట్లు | ₹12,300 crores with multi-pronged approach to MCH indicators', 'D', "మే 2026 సంఘ బడ్జెట్ ₹12,300 కోట్లు కేటాయించింది. | The May 2026 Union Budget allocated ₹12,300 crores for maternal and child health programs.", 'AP_HC', 'National_Current_Affairs_2026'),
        (31628, 'మే 2026 నాటికి 18-నెల సున్న సంక్రమణ మైలు రాయిని నివేదించిన సంక్రామక వ్యాధి నిర్మూలన కార్యక్రమం ఏది? | Which communicable disease eradication program reported achievement of 18-month zero transmission milestone by May 2026?', '12 అధిక భారం | Measles elimination in 12 high-burden states', 'కాలజ్వరం | Kala-azar elimination in endemic states', '280 జిల్లాలు | Filaria elimination in 280 districts', 'B మరియు C | Both B and C', 'D', 'రెండు కార్యక్రమాలు మైలు రాయిలను సాధించాయి. | Two major communicable disease eradication programs achieved significant milestones by May 2026.', 'AP_HC', 'National_Current_Affairs_2026'),
        (31629, 'మే 2026 నాటికి వ్యాధిరోధక ప్రతిఘటన (AMR) కు భారత ప్రతిస్పందన? | What is the current status of India\'s response to antimicrobial resistance (AMR) as of May 2026?', 'NAP-2 ₹3,200 కోట్ల సహ | National Action Plan 2 launched with ₹3,200 crores budget for 2026-2030', '85% ఆసుపత్రులు | Antibiotic Stewardship Program expanded to 85% of hospitals', 'A మరియు B | Both A and B', '200% పెరుగుదల | Generic antibiotic production increased by 200%', 'C', "NAP-2 ఆరంభం మరియు ASP విస్తరణ. | India's antimicrobial resistance response in May 2026 includes launch of National Action Plan 2 (2026-2030) and expansion of Antibiotic Stewardship Program to 85% of hospitals.", 'AP_HC', 'National_Current_Affairs_2026'),
        (31630, 'మే 2026 నాటికి దూరసంచార నవీకరించిన సంస్థలు? | How many rural and remote health facilities were upgraded with telemedicine infrastructure by May 2026?', '25,000 | 25,000 facilities', '40,000 | 40,000 facilities', '55,000 | 55,000 facilities', '70,000 | 70,000 facilities', 'C', '55,000 సంస్థలు నవీకరించాయి. | The National Telemedicine Initiative upgraded 55,000 rural and remote health facilities with telemedicine infrastructure by May 2026.', 'AP_HC', 'National_Current_Affairs_2026'),
        (31631, 'మే 2026న NCD నిరోధన? | What new scheme was introduced in May 2026 for prevention of non-communicable diseases (NCDs)?', 'NCD నిరోధన | National NCD Prevention Program with focus on behavior change', 'ఆయుష్‌మాన్ భారత్ | Ayushman Bharat - Wellness Centers expansion with health screening', 'A మరియు B | Both A and B', 'సార్వత్రిక బీమా | Universal Health Insurance for NCD patients', 'C', 'రెండూ ప్రారంభం. | May 2026 saw launch of both National NCD Prevention Program and expansion of Ayushman Bharat - Wellness Centers.', 'AP_HC', 'National_Current_Affairs_2026'),
        (31632, 'మే 2026 నాటికి వ్యాధి నిఘంటన సాధన? | What was the major achievement in disease surveillance by May 2026?', 'IDSP నిజ-సమయం | Integrated Disease Surveillance Program (IDSP) expanded to all districts with real-time reporting', 'AI-మహమ్మారీ 32 రాష్ట్రాలు | AI-powered epidemic forecasting system operational in 32 states', 'A మరియు B | Both A and B', 'జనుద్విత్వ 500 | Genomic sequencing capacity increased to 500 centers', 'C', 'సమీకృత IDSP మరియు AI విస్తరణ. | May 2026 marked significant expansion of disease surveillance infrastructure.', 'AP_HC', 'National_Current_Affairs_2026'),
        (31633, 'మే 2026 వైద్య పరికర బడ్జెట్? | What is the budget allocation for strengthening medical device regulation and manufacturing by May 2026?', '₹1,800 | ₹1,800 crores for Make in India medical devices', '₹3,200 | ₹3,200 crores for regulatory framework and manufacturing capacity', '₹5,400 | ₹5,400 crores for comprehensive medical device ecosystem', '₹7,800 | ₹7,800 crores for global competitiveness in medical devices', 'D', '₹7,800 కోట్లు కేటాయించాయి. | The Union Budget 2026 allocated ₹7,800 crores for strengthening India\'s medical device regulation.', 'AP_HC', 'National_Current_Affairs_2026'),
        (31634, 'మే 2026 ఆరోగ్య నిధిపరికర? | What new healthcare financing mechanism was introduced to support primary healthcare in May 2026?', 'ఆరోగ్య సేవ నిధి | Health Service Fund with ₹5,200 crores corpus for PHC operations', 'బాండ్‌లు 6.5% | Healthcare Infrastructure Bonds allowing citizen investments at 6.5% interest', 'A మరియు B | Both A and B', 'ఆర్జన్యూత సబ్సిడీ | Direct private insurance subsidies for poor households', 'C', 'నిధి మరియు బాండ్‌లు ప్రవేశం. | May 2026 introduced two new healthcare financing mechanisms.', 'AP_HC', 'National_Current_Affairs_2026'),
        (31635, 'మే 2026 COVID-19 సన్నహత? | What is the status of India\'s COVID-19 and pandemic preparedness response by May 2026?', 'జాతీయ చట్ట ₹4,800 | National Pandemic Preparedness Framework finalized with ₹4,800 crores allocation', 'సంచర 8.5 బిలియన్ | Vaccine development capacity increased to 8.5 billion doses/year', 'A మరియు B | Both A and B', '718 జిల్లాలు బృందం | Pandemic Response Team established in all 718 districts', 'C', 'చట్ట నిర్మాణం మరియు సంచర సామర్థ్యం. | India\'s pandemic preparedness by May 2026 includes National Pandemic Preparedness Framework and expanded vaccine manufacturing capacity.', 'AP_HC', 'National_Current_Affairs_2026'),
        (31636, 'మే 2026 గ్రామీణ సూచకం? | Which health indicator showed the most improvement in rural India by May 2026?', '99% ప్రసవం | Institutional delivery rate increased to 99% from 79% in 2015', '28 శిశువు | Infant mortality rate decreased to 28 from 54 in 2015', '95 మాతృత్వం | Maternal mortality ratio reduced to 95 from 167 in 2015', 'ఆ సమస్తమైనవి | All of the above', 'D', 'సమస్త సూచకాలు సుధారణ. | Rural India demonstrated remarkable improvement across all major health indicators by May 2026.', 'AP_HC', 'National_Current_Affairs_2026'),
        (31637, 'మే 2026 జలం శుద్ధీకరణ శాతం? | What percentage of India\'s population gained access to improved water and sanitation by May 2026?', '78% స్వచ్ఛ | 78% through Swachh Bharat Mission - Phase 2', '92% జల | 92% through Jal Jeevan Mission and Swachh Bharat expansion', '68% సమాజ | 68% through grassroots community initiatives', '85% ప్రభుత్వ | 85% through public-private partnership models', 'B', '92% జల జీవన. | By May 2026, 92% of India\'s population gained access to improved water and sanitation.', 'AP_HC', 'National_Current_Affairs_2026'),
        (31638, 'మే 2026 వృత్తిపరమైన ఆరోగ్య? | What new initiative was launched for occupational health and worker safety in May 2026?', 'జాతీయ విధానం ₹2,200 | National Occupational Health & Safety Policy with ₹2,200 crores for implementation', '35,000 నిబంధనం | Occupational Disease Registry in 35,000 health facilities', 'A మరియు B | Both A and B', '15 కోటి బీమా | Workplace Health Insurance scheme covering 15 crore workers', 'C', 'విధానం మరియు నిబంధనం ప్రారంభం. | May 2026 witnessed launch of two major occupational health initiatives.', 'AP_HC', 'National_Current_Affairs_2026'),
        (31639, 'మే 2026 ఆరోగ్య సాంఘ్నికత? | What was the major achievement in health technology innovation by May 2026?', 'స్వదేశీ 2,200 | Swadeshi Diagnostic Technologies registered at 2,200 labs across India', 'వెంటిలేటర్ స్వయం | Affordable ventilator and oxygen concentrator manufacturing achieved self-sufficiency', 'A మరియు B | Both A and B', '5,000 AI | Clinical decision support AI systems deployed in 5,000 hospitals', 'C', 'సాంఘ్నికత సాధనలు. | India achieved significant health technology innovation milestones by May 2026.', 'AP_HC', 'National_Current_Affairs_2026'),
        (31640, 'మే 2026 మానసిక ఆరోగ్య సేవలు? | How many individuals received mental health services through primary health centers by May 2026?', '2.5 కోటి | 2.5 crore through Mental Health Integration Program', '4.2 కోటి | 4.2 crore through expanded PHC counseling services', '5.8 కోటి | 5.8 crore through combination of PHC, ASHA, and telemedicine', '8.2 కోటి | 8.2 crore through multi-channel mental health delivery', 'D', '8.2 కోటి సేవలు పొందారు. | By May 2026, 8.2 crore individuals received mental health services through multi-channel delivery.', 'AP_HC', 'National_Current_Affairs_2026'),
        (31641, 'మే 2026 గిరిజన ఆరోగ్య బడ్జెట్? | What was the allocation for strengthening tribal health systems in the May 2026 Budget?', '₹1,850 నిర్దిష్ట | ₹1,850 crores for tribal-specific health programs', '₹3,200 సంధర్భం | ₹3,200 crores for tribal health infrastructure and traditional medicine integration', '₹5,500 సర్వ | ₹5,500 crores for comprehensive tribal health transformation', '₹7,200 సమానత్వం | ₹7,200 crores for tribal health equity across all indicators', 'D', '₹7,200 కోట్లు కేటాయించాయి. | The May 2026 Union Budget allocated ₹7,200 crores for strengthening tribal health systems.', 'AP_HC', 'National_Current_Affairs_2026'),
        (31642, 'మే 2026 వాయు నాణ్యత? | What new regulation was introduced for air quality monitoring and respiratory health in May 2026?', '450 నగరాలు | National Respiratory Health Surveillance Program in 450 cities', '250 జిల్లాలు | Air Quality-Linked Health Intervention System (AQHIS) in 250 districts', 'A మరియు B | Both A and B', '₹4,500 ప్రమాణాలు | Mandatory air quality standards enforcement with ₹4,500 crore investment', 'C', 'నిఘంటన మరియు AQHIS రెండూ. | May 2026 introduced two major air quality and respiratory health initiatives.', 'AP_HC', 'National_Current_Affairs_2026'),
        (31643, 'మే 2026 అరుదైన జెనెటిక్ చికిత్స? | How many patients with rare genetic diseases received treatment support by May 2026?', '1.2 లక్ష | 1.2 lakh through new Rare Disease Registry and Treatment Program', '2.8 లక్ష | 2.8 lakh through expanded medical genetics services', '4.5 లక్ష | 4.5 lakh through Center of Excellence model', '6.2 లక్ష | 6.2 lakh through comprehensive rare disease ecosystem', 'D', '6.2 లక్ష చికిత్స సహాయ. | By May 2026, 6.2 lakh patients with rare genetic diseases received treatment support.', 'AP_HC', 'National_Current_Affairs_2026'),
        (31644, 'మే 2026 హెపటిటిస్ సంక్రమణ? | What major achievement was reported in eliminating hepatitis B and C transmission by May 2026?', '95% టీకాకరణ | 95% coverage of newborn hepatitis B vaccination with zero mother-to-child transmission', '88% చికిత్స | 88% of hepatitis C patients received direct-acting antiviral treatment with 97% cure rate', 'A మరియు B | Both A and B', 'రక్త సరఫరా | Universal screening of blood supply eliminating transfusion-transmitted hepatitis', 'C', 'హెపటిటిస్ సాధనలు. | By May 2026, India achieved major milestones in eliminating hepatitis B and C transmission.', 'AP_HC', 'National_Current_Affairs_2026'),
        (31645, 'మే 2026 సాంప్రదాయిక ప్రసవం నిర్మాణం? | What new framework was introduced for strengthening traditional birth attendant (TBA) integration in May 2026?', 'సర్టిఫికేషన్ | Regulation of TBAs through formal certification and supervision programs', 'సంస్కృత నమూనా | Integration of TBAs with skilled birth attendants under collaborative care model', 'A మరియు B | Both A and B', 'సంస్కృత-ఆధారిత | Gradual replacement of TBAs with facility-based delivery promotion only', 'C', 'సహయోగ నిర్మాణం ప్రవేశ. | May 2026 introduced a collaborative framework for strengthening traditional birth attendant (TBA) integration.', 'AP_HC', 'National_Current_Affairs_2026'),
        (31646, 'మే 2026 క్లినికల్ పరిశోధన? | What was the major development in clinical research and trial infrastructure by May 2026?', '8,500 నిబంధనం | National Clinical Trials Registry expanded with 8,500 active trials', '150 జిల్లాలు | Decentralized clinical trial infrastructure established in 150 districts', 'A మరియు B | Both A and B', 'టాప్ 3 ర్యాంకింగ్ | International clinical trial attractiveness Index placed India in top 3', 'C', 'పరిశోధన సంధర్భం విస్తరణ. | India\'s clinical research infrastructure underwent significant expansion by May 2026.', 'AP_HC', 'National_Current_Affairs_2026'),
        (31647, 'మే 2026 సేవకర్త దహనం? | What initiative was launched to address healthcare worker burnout and mental health by May 2026?', '8,500 సుఖ సేవలు | Healthcare Worker Wellness Program with mental health support in 8,500 facilities', 'వృత్తిపరమైన పర్యవేక్షణ | Occupational stress monitoring and intervention protocols in hospitals', 'A మరియు B | Both A and B', 'తప్పనిసరి విశ్రాంతి | Mandatory rest periods and reduced shift duration for all healthcare workers', 'C', 'సుఖ కార్యక్రమ ఆరంభం. | May 2026 witnessed launch of comprehensive Healthcare Worker Wellness Program.', 'AP_HC', 'National_Current_Affairs_2026'),
        (31648, 'మే 2026 ఆరోగ్య చిన్న సంస్థ నిర్మాణం? | What framework was established for regulating and promoting health and wellness startups by May 2026?', 'డిజిటల్ సర్కిల్ | Digital Health Regulatory Sandbox allowing innovation with safety oversight', '₹1,850 సంచీకరణ | Health Tech Incubation Program with ₹1,850 crores corpus for startup funding', 'A మరియు B | Both A and B', 'తప్పనిసరి చట్ట | Mandatory compliance framework with tariff controls on health tech services', 'C', 'సర్కిల్ మరియు సంచీకరణ నిర్మాణం. | May 2026 established comprehensive framework for digital health innovation.', 'AP_HC', 'National_Current_Affairs_2026'),
        (31649, 'మే 2026 సీసం విషపూరణం నిర్మూలన? | What major achievement was reported in eliminating lead poisoning and other environmental health hazards by May 2026?', '8.5 కోటి పర్యవేక్షణ | Lead exposure screening in 8.5 crore children with elimination in 95% of high-burden districts', '2,200 జిల్లాలు 85 | Environmental health hazard surveillance in 2,200 districts identifying 85 primary hazards', 'A మరియు B | Both A and B', 'సార్వత్రిక జల నాణ్యత | Universal water quality testing eliminating all chemical and biological contamination', 'C', 'సీసం నిర్మూలన ప్రగతి. | May 2026 marked significant progress in eliminating lead poisoning and environmental health hazards.', 'AP_HC', 'National_Current_Affairs_2026'),
        (31650, 'మే 2026 ఆరోగ్య సంక్షేమ ప్రభావం? | What is the overall investment and beneficiary impact of healthcare sector transformation by May 2026?', '₹95,000 85 కోటి | ₹95,000 crores invested; 85 crore individuals received improved healthcare access', '₹125,000 110 కోటి | ₹125,000 crores invested; 110 crore individuals benefited from health programs', '₹155,000 125 కోటి | ₹155,000 crores invested; 125 crore individuals with improved health outcomes', '₹185,000 140 కోటి | ₹185,000 crores invested; 140 crore individuals across health system transformation', 'D', 'ఆశ్చర్యకరమైన సంచీకరణ ప్రభావం. | By May 2026, India\'s healthcare sector transformation represented unprecedented investment and population impact.', 'AP_HC', 'National_Current_Affairs_2026'),
"""

# Insert before batch 9
updated = content[:pos] + batch_8_mcqs + content[pos:]

# Write back
with open('seed_national_ca_2026_mcq.py', 'w', encoding='utf-8') as f:
    f.write(updated)

print("✓ Batch 8 (31626-31650) inserted successfully")
print("Validating syntax...")

# Validate AST
try:
    import ast
    ast.parse(updated)
    print("✓ AST validation PASSED")
except SyntaxError as e:
    print(f"✗ AST FAILED: {e}")
    exit(1)
