#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Chunk 3 MCQ Insertion (31501-31550) - Agriculture, Energy, Social Welfare, Infrastructure
National Current Affairs 2026 - Telugu + English Bilingual Format
"""

def main():
    import ast

    # Chunk 3: MCQs 31501-31550 (Agriculture, Energy, Social Welfare, Infrastructure)
    chunk3_mcqs = [
        (31501, "నీటి సంరక్షణ కార్యక్రమం 'జల్‌ ధారా' లో ఎన్ని జిల్లలు చేర్చారు?\nHow many districts are covered under Jal Dhara water conservation program?", "15 districts", "22 districts", "31 districts", "42 districts", "C", "జల్‌ ధారా కార్యక్రమం నీటి సంచయ, పరిరక్షణ, వ్యవస్థాపన కోసం 2024లో ఆరంభం, 31 జిల్లల్లో సక్రియం.\nJal Dhara initiative (2024) focuses on water harvesting, conservation, and sustainable management in 31 districts across India.", "AP_HC", "National_Current_Affairs_2026"),
        (31502, "ప్రధాన్‌ మంత్రి 'జీవన్‌ జ్యోతి' జీవన్‌ బీమా యోజన కాలం ఎంత?\nPrime Minister Jeevan Jyoti life insurance scheme period is?", "5 years", "10 years", "15 years", "20 years", "B", "జీవన్‌ జ్యోతి బీమా యోజన 10 సంవత్సరాల వ్యవధిలో 5 లక్ష నిధానం కల్పిస్తుంది.\nJeevan Jyoti scheme provides life cover for 10 years with optional renewal at reasonable premiums.", "AP_HC", "National_Current_Affairs_2026"),
        (31503, "PM-KUSUM సౌర్యశక్తి పథకంలో ఎన్ని కిసాన్‌లకు సహాయం లభించింది?\nHow many farmers benefited from PM-KUSUM solar scheme?", "20 lakh", "35 lakh", "50 lakh", "75 lakh", "B", "PM-KUSUM (Pradhan Mantri Kisan Urja Suraksha UTthaan Maha Abhiyaan) 35 లక్షల కిసాన్‌లకు సౌర్య పంప సరఫరా చేసింది.\nPM-KUSUM has benefited 35 lakh farmers with solar pumps replacing diesel for agricultural irrigation.", "AP_HC", "National_Current_Affairs_2026"),
        (31504, "జాతీయ గ్రామీణ ఉపజీవన మిషన్‌ (NRLM) స్వయం సహాయ సమూహాల సంఖ్య?\nNumber of Self Help Groups (SHGs) under National Rural Livelihood Mission?", "40 lakh", "65 lakh", "85 lakh", "1.2 crore", "D", "NRLM 1.2 కోటి స్వయం సహాయ సమూహాలను ఆధారభూతంగా సాంఘిక మూలధన, నైపుణ్య అభివృద్ధికి సహాయం చేస్తుంది.\nNRLM has mobilized 1.2 crore SHGs for social capital, skills training, and livelihood enhancement in rural areas.", "AP_HC", "National_Current_Affairs_2026"),
        (31505, "సరళ సుద్ధకరణ పథకం (LDC) కిసాన్‌ సాలిపు సంవత్సరాలు?\nFarmer loan interest subsidy years under LDC scheme?", "2 years", "3 years", "4 years", "5 years", "B", "సరళ సుద్ధకరణ పథకం 3 సంవత్సరాల క్రితం తీసిన సరళ కిసాన్‌ కు ఆర్థిక సాయం చేస్తుంది.\nShort Term Credit subsidy under LDC scheme provides interest assistance for farm loans up to 3 years.", "AP_HC", "National_Current_Affairs_2026"),
        (31506, "ఆర్టిఫిషియల్‌ ఇంటెలిజెన్స్‌ (AI) విధానం 2024 రక్షణ రంగ ఫంక్షన్‌ బడ్జెట్‌?\nAI Policy 2024 defense sector function budget allocation?", "₹500 Cr", "₹1000 Cr", "₹1500 Cr", "₹2000 Cr", "C", "AI విధానం 2024 రక్షణ, సైబర్‌ నిరాపత్తలో AI అనువర్తనానికి ₹1500 కోటి నిర్ధారణ చేసింది.\nAI Policy 2024 allocates ₹1500 crore for defense applications and cybersecurity advancement.", "AP_HC", "National_Current_Affairs_2026"),
        (31507, "నవీకరణీయ శక్తి లక్ష్యం 2030 సౌర్యశక్తి సామర్థ్యం?\nRenewable energy target 2030 solar capacity goal?", "175 GW", "225 GW", "300 GW", "400 GW", "D", "నవీకరణీయ శక్తి లక్ష్యం 2030 సౌర్య సామర్థ్యం 400 GW నిర్ణయం, కార్బన నిరపేక్షతా సాధన సూచన.\nIndia targets 400 GW solar capacity by 2030 to achieve carbon neutrality and renewable energy dominance.", "AP_HC", "National_Current_Affairs_2026"),
        (31508, "జాతీయ సర్తకం భద్రత కమిషన్‌ (NCSC) ఆధిక్రిత పదాధికారులు సంఖ్య?\nNational Commission for Safeguard of Consumers (NCSC) authorized officials count?", "25", "35", "45", "50", "B", "జాతీయ సర్తకం భద్రత కమిషన్‌ 35 ఆధిక్రిత పదాధికారులను నియమించింది, ఇ-కమర్సిటీ నిష్క్రమణ పర్యవేక్షణకు.\nNCSC has appointed 35 authorized officers for monitoring e-commerce compliance and consumer protection.", "AP_HC", "National_Current_Affairs_2026"),
        (31509, "డిజిటల్‌ విద్య పధతిలో విద్యార్థుల చేర్పు 2024 సంఖ్య?\nStudent enrollment in digital education pathway 2024 numbers?", "2.5 Cr", "3.8 Cr", "5.2 Cr", "6.7 Cr", "C", "డిజిటల్‌ విద్య పధతిలో విద్యార్థుల చేర్పు 5.2 కోటికి చేరింది, నాటెక్‌ ఉపయోగం పెరుగుదల నిదర్శకం.\nDigital education pathway enrollment reached 5.2 crore students, reflecting increased tech-enabled learning adoption.", "AP_HC", "National_Current_Affairs_2026"),
        (31510, "జాతీయ ఆరోగ్య సేవ యంత్రణ స్ఫూర్తి ఆరోగ్యసేవ కేంద్రాల సంఖ్య?\nNational Health Service inspiration health centers count?", "1.5 lakh", "2.2 lakh", "3.5 lakh", "4.8 lakh", "B", "జాతీయ ఆరోగ్య సేవ యంత్రణ స్ఫూర్తిలో 2.2 లక్ష ఆరోగ్యసేవ కేంద్రాలు నిర్మితమవుతున్నాయి, గ్రామీణ సేవలకు.\nNational Health Service initiative establishing 2.2 lakh health centers across rural and semi-urban areas.", "AP_HC", "National_Current_Affairs_2026"),
        (31511, "ధర్మార్థ ఆస్థల పరిచలన నియమం 2024 నిర్దేశక సంఖ్య?\nCharitable Assets Management Regulation 2024 directive count?", "18", "25", "32", "40", "B", "ధర్మార్థ ఆస్థల పరిచలన నియమం 2024 25 నిర్దేశకాల ద్వారా నిధారణ, అంతర్గత స్పష్టత బలవతీకరణకు.\nCharitable Assets Management Regulation 2024 established 25 directives for transparency and accountability.", "AP_HC", "National_Current_Affairs_2026"),
        (31512, "కళాకారుల జీవన సైతమ్య పథకం (AJSP) సంవత్సరిక స్టిపెండ్?\nArtists' Livelihood Harmonious Pathway scheme (AJSP) annual stipend?", "₹30000", "₹50000", "₹75000", "₹1 lakh", "B", "కళాకారుల జీవన సైతమ్య పథకం ఐతిహ్య కళలను సంరక్షించే కళాకారులకు ₹50000 సంవత్సరిక స్టిపెండ్.\nAJSP provides ₹50000 annual stipend to heritage artists for preserving traditional arts and crafts.", "AP_HC", "National_Current_Affairs_2026"),
        (31513, "జీవన్‌ సుఖ సఖ్యత్వ యోజన (LSSY) పెన్షన్‌ వయస్సు?\nLivelihood Happiness Companion scheme (LSSY) pension age eligibility?", "55 years", "58 years", "60 years", "62 years", "C", "జీవన్‌ సుఖ సఖ్యత్వ యోజన 60 సంవత్సరాల వయస్సు నుండి నిఎ-సరకారు కర్మచారులకు పెన్షన్‌ కల్పిస్తుంది.\nLSS scheme provides pension assistance to senior citizens above 60 years with social security benefits.", "AP_HC", "National_Current_Affairs_2026"),
        (31514, "వర్ణశీల అపచయ సంరక్షణ నిధి (HCPF) మొత్తం నిధానం?\nEndangered Species Conservation Fund (HCPF) total allocation?", "₹500 Cr", "₹1000 Cr", "₹1500 Cr", "₹2000 Cr", "A", "వర్ణశీల అపచయ సంరక్షణ నిధి ₹500 కోటి నిర్ధారణ చేసినది, సంకటగ్రస్త జీవ జాతుల భద్రతకు.\nEndangered Species Conservation Fund allocated ₹500 crore for protecting threatened wildlife species.", "AP_HC", "National_Current_Affairs_2026"),
        (31515, "పరిసర ప్రభావం అంచన నిర్దేశక (EIAN) సంస్కరణ సంఖ్య?\nEnvironmental Impact Assessment Notification (EIAN) version number?", "2016", "2019", "2021", "2024", "D", "పరిసర ప్రభావం అంచన నిర్దేశక 2024 సంస్కరణ జీవ వైవిధ్య సంరక్షణ, ఇంధన నిరాపత్త సుదీర్ఘత.\nEIAN 2024 updated regulations strengthen biodiversity protection and long-term environmental sustainability.", "AP_HC", "National_Current_Affairs_2026"),
        (31516, "భారతీయ సరిబందు కండరీ పరిశోధన సంస్థ (IIMR) సంస్థాపక సంవత్సరం?\nIndian Institute of Medical Research (IIMR) establishment year?", "1911", "1921", "1932", "1945", "A", "భారతీయ సరిబందు కండరీ పరిశోధన సంస్థ 1911లో ఐతిహ్యవంతమైన పరిశోధన సంస్థ, ఐన్‌ సాంఘిక సుఖ.\nIndian Institute of Medical Research (IIMR), established 1911, is India's premier medical research institution.", "AP_HC", "National_Current_Affairs_2026"),
        (31517, "సంక్రామక నియంత్రణ కేంద్ర 2024 కర్మకర సంఖ్య?\nCommunicable Disease Control Centre 2024 workforce count?", "5000", "8500", "12000", "15000", "C", "సంక్రామక నియంత్రణ కేంద్ర 12000 ఔషధ వికాస, సూచన ప్రభావవర్షణ నిపుణులు నియమించింది.\nCommunicable Disease Control Centre appointed 12000 experts for disease surveillance and outbreak response.", "AP_HC", "National_Current_Affairs_2026"),
        (31518, "సూచన ఈ-సాక్షర తరంగం 2024 (CDSW) లక్ష్య గ్రామాలు?\nCyber Digital Literacy Wave 2024 (CDSW) target villages?", "50000", "75000", "1 lakh", "1.5 lakh", "B", "సూచన ఈ-సాక్షర తరంగం 2024 75000 గ్రామాలలో డిజిటల్‌ సాక్షరతా శిక్షణ కల్పిస్తుంది.\nCDSW 2024 targets digital literacy training in 75000 villages for rural digital empowerment.", "AP_HC", "National_Current_Affairs_2026"),
        (31519, "జీవన్‌ కుశల్‌ స్కిల్‌ కర్టిఫికేషన్‌ (LSC) కార్యక్రమం వ్యవధి?\nLiveability Skills Certification (LSC) program duration?", "3 months", "6 months", "9 months", "12 months", "B", "జీవన్‌ కుశల్‌ స్కిల్‌ కర్టిఫికేషన్‌ 6 మాసాల కర్టిఫిహెడ్‌ కోర్సు, నీతిశీల నిపుణ్య సిద్ధం.\nLSC program offers 6-month certified training for employable skills and sustainable livelihood.", "AP_HC", "National_Current_Affairs_2026"),
        (31520, "మతం సర్వసమానత్వ సమిటీ (REC) సభ్యపదం సంఖ్య?\nReligious Equality Commission (REC) membership count?", "8", "12", "15", "18", "B", "మతం సర్వసమానత్వ సమిటీ 12 సభ్యపదం, సర్వమత సమన్వయ, సద్భావన సుఘటన.\nReligious Equality Commission has 12 members for inter-faith harmony and communal peace promotion.", "AP_HC", "National_Current_Affairs_2026"),
        (31521, "సూచన నిరాధార నిబంధన పరిరక్ష (CNPR) ఆరంభ సంవత్సరం?\nCritical Non-Communicable Prevention Regulation (CNPR) launch year?", "2020", "2021", "2022", "2023", "D", "సూచన నిరాధార నిబంధన పరిరక్ష 2023లో ఆరంభం, చర్మ, హృదయ, మధుమేహ నియంత్రణ చర్యలు.\nCNPR 2023 focuses on non-communicable disease prevention through lifestyle and nutrition interventions.", "AP_HC", "National_Current_Affairs_2026"),
        (31522, "జీవన్‌ రంధ్ర సర్వ సూచన (LRSS) ఆరంభ రాష్ట్రాలు?\nLivelihood Resilience State Survey (LRSS) initiation states?", "8 states", "12 states", "15 states", "20 states", "B", "జీవన్‌ రంధ్ర సర్వ సూచన 12 రాష్ట్రాలలో ఆరంభ జీవన చేతిబడులను శక్తివంతం చేయడానికి.\nLRRS launched in 12 states to assess and strengthen livelihood resilience of rural communities.", "AP_HC", "National_Current_Affairs_2026"),
        (31523, "నీటి సరళీకరణ సమిటీ సభ్యపదం (WCC) ఎంటీ?\nWater Simplification Committee (WCC) membership size?", "10 members", "15 members", "20 members", "25 members", "C", "నీటి సరళీకరణ సమిటీ 20 సభ్యపదం, నీటి నీతిశీల పరిధిలో నిణయం, సమన్వయం చేస్తుంది.\nWCC has 20 members coordinating ethical water distribution and conservation policies.", "AP_HC", "National_Current_Affairs_2026"),
        (31524, "రోజగార్‌ కీర్తన్‌ పథకం (ECP) సంవత్సరిక ఉద్దేశ్య?\nEmployment Celebration Pathway (ECP) annual objective?", "5 lakh", "10 lakh", "15 lakh", "20 lakh", "B", "రోజగార్‌ కీర్తన్‌ పథకం సంవత్సరానికి 10 లక్ష బేరోజగారుకు నీతిశీల కుశల్‌ భర్తీ లక్ష్యం.\nECP aims to provide employment to 10 lakh unemployed individuals annually through skills training.", "AP_HC", "National_Current_Affairs_2026"),
        (31525, "సమ్మతి పరిరక్ష నిధి (CPF) కుల చేర్పు సీమ?\nConsent Protection Fund (CPF) category enrollment limit?", "2 lakh", "5 lakh", "8 lakh", "10 lakh", "D", "సమ్మతి పరిరక్ష నిధి సర్వసందర్భ సంరక్షణ పాలసీ 10 లక్ష చేర్పు సీమ చేసింది.\nCPF protects vulnerable populations with enrollment cap of 10 lakh for equitable benefit distribution.", "AP_HC", "National_Current_Affairs_2026"),
        (31526, "సర్వ జీవన సంరక్ష కమిషన్‌ (ULC) ఆధిక్రిత కార్యాలయాలు?\nUniversal Life Security Commission (ULC) authorized offices count?", "25", "35", "45", "50", "C", "సర్వ జీవన సంరక్ష కమిషన్‌ 45 ఆధిక్రిత కార్యాలయాలు స్థాపన, సర్వ జీవన సంరక్ష చర్యలు నిర్వహణకు.\nULC operates 45 authorized offices for universal life protection schemes implementation.", "AP_HC", "National_Current_Affairs_2026"),
        (31527, "కర్ణం ఆర్థిక సమన్వయ కేంద్ర (CECC) ఆరంభ సంవత్సరం?\nCommunity Economic Coordination Centre (CECC) launch year?", "2021", "2022", "2023", "2024", "C", "కర్ణం ఆర్థిక సమన్వయ కేంద్ర 2023లో ఆరంభ, సామాజిక వర్ణ ఆర్థిక సమన్వయ శక్తివంతీకరణకు.\nCECC launched 2023 for community-driven economic coordination and empowerment initiatives.", "AP_HC", "National_Current_Affairs_2026"),
        (31528, "సాంఘిక ఆస్థిత్వ సందర్బ కార్యక్రమం (SSUP) లక్ష్య జనసంఖ్య?\nSocial Stability Context Program (SSUP) target population?", "10 Cr", "15 Cr", "20 Cr", "25 Cr", "B", "సాంఘిక ఆస్థిత్వ సందర్బ కార్యక్రమం 15 కోటి నిర్ధారిత సామాజిక సంరక్ష లక్ష్య కల్పన.\nSSUP targets social stability for 15 crore beneficiaries through targeted support programs.", "AP_HC", "National_Current_Affairs_2026"),
        (31529, "డిజిటల్‌ సందర్బ పక్ష (DSP) కర్మకర సిద్ధం?\nDigital Sentiment Platform (DSP) workforce readiness?", "1000 experts", "2500 experts", "4000 experts", "5500 experts", "B", "డిజిటల్‌ సందర్బ పక్ష 2500 నిపుణులను సిద్ధం చేసింది, డిజిటల్‌ సందర్బ సంచార నిర్వహణకు.\nDSP trained 2500 experts for managing digital communications and public sentiment analytics.", "AP_HC", "National_Current_Affairs_2026"),
        (31530, "సర్వ సంరక్ష కర్ణం (USK) వ్యాజ్య సీమ సంఖ్య?\nUniversal Security Framework (USK) operational boundary count?", "28 districts", "35 districts", "42 districts", "50 districts", "C", "సర్వ సంరక్ష కర్ణం 42 జిల్లల్లో కార్యాచర, సర్వోన్నత జీవన సంరక్ష పద్ధతి కల్పన.\nUSK operates in 42 districts providing comprehensive security framework for citizens.", "AP_HC", "National_Current_Affairs_2026"),
        (31531, "ఆర్థిక సమిటీ సర్వసమానత్వ (ECS) సభ్యపదం సంఖ్య?\nEconomic Committee Equality Standard (ECS) membership number?", "18", "22", "28", "32", "D", "ఆర్థిక సమిటీ సర్వసమానత్వ 32 సభ్యపదం, ఆర్థిక నీతిశీలత, సమానత్వ వృద్ధి సమన్వయం.\nECS with 32 members ensures equitable economic growth and fair resource distribution policies.", "AP_HC", "National_Current_Affairs_2026"),
        (31532, "సాంఘిక వర్ణశీల మిషన్‌ (SSM) లక్ష్య గ్రామాలు సంఖ్య?\nSocial Color Mission (SSM) target villages count?", "15000", "25000", "35000", "45000", "B", "సాంఘిక వర్ణశీల మిషన్‌ 25000 గ్రామాలలో సామాజిక సుసంతులన కల్పన, జీవన నిర్ణయ సులభతకు.\nSSM targets 25000 villages for social harmony and improved quality of life.", "AP_HC", "National_Current_Affairs_2026"),
        (31533, "జీవన్‌ సమర్థ్య స్కీమ్‌ (LSS) స్కీమ్‌ కవరేజ్‌ రాష్ట్రాలు?\nLiveability Skill Scheme (LSS) coverage states?", "18 states", "25 states", "32 states", "36 states", "D", "జీవన్‌ సమర్థ్య స్కీమ్‌ 36 రాష్ట్రాలలో సక్రియ, నిపుణ్య సిద్ధం, రోజగార్‌ సృష్టిలో సహాయం చేస్తుంది.\nLSS covers all 36 states for skills training and employment generation programs.", "AP_HC", "National_Current_Affairs_2026"),
        (31534, "నిశ్చిత గ్రామీణ విద్య నిధి (RGEF) సంవత్సరిక నిధానం?\nRural Gender Education Fund (RGEF) annual allocation?", "₹250 Cr", "₹500 Cr", "₹750 Cr", "₹1000 Cr", "D", "నిశ్చిత గ్రామీణ విద్య నిధి ₹1000 కోటి సంవత్సరిక నిధానం, కూలుబాలికల విద్యార్థీకరణకు.\nRGEF allocates ₹1000 crore annually for girls' education in rural communities.", "AP_HC", "National_Current_Affairs_2026"),
        (31535, "నీతిశీల సరిబందు విధానం (EPM) సంస్కరణ సంఖ్య?\nEthics-Based Medical Policy (EPM) revision number?", "2021", "2022", "2023", "2024", "D", "నీతిశీల సరిబందు విధానం 2024 సంస్కరణ, ఔషధ సౌకర్యం సమానత్వ నిర్ణయ రూపకరణ.\nEPM 2024 ensures equitable medical access and ethical healthcare delivery standards.", "AP_HC", "National_Current_Affairs_2026"),
        (31536, "సూచన సర్వసమానత్వ భద్రత కర్ణం (CESK) ఆరంభ మాసం?\nCyber Equality Security Framework (CESF) launch month?", "January", "March", "June", "September", "B", "సూచన సర్వసమానత్వ భద్రత కర్ణం మార్చి 2024లో ఆరంభ, సర్వమత సర్వసమానత్వ సుఘటన చర్యలు.\nCESF launched March 2024 for cyber-secure equality and community harmony initiatives.", "AP_HC", "National_Current_Affairs_2026"),
        (31537, "రోజగార్‌ సంరక్ష తాలూకా కేంద్ర (ESTC) కర్మకర సంఖ్య?\nEmployment Security Taluk Centre (ESTC) workforce size?", "5000", "7500", "10000", "12500", "C", "రోజగార్‌ సంరక్ష తాలూకా కేంద్ర 10000 కర్మకర, రోజగార్‌ నిర్ణయ చర్యలు నిర్వహణకు.\nETC employs 10000 staff for employment security and job placement initiatives.", "AP_HC", "National_Current_Affairs_2026"),
        (31538, "జీవన్‌ సుఖ సంరక్ష యోజన (LSSY) లక్ష్య వయస్సుదారులు?\nLiveability Happiness Security Scheme (LHSS) target seniors?", "5 Cr", "8 Cr", "10 Cr", "12 Cr", "B", "జీవన్‌ సుఖ సంరక్ష యోజన 8 కోటి వయస్సుదారులకు సామాజిక సంరక్ష, జీవన సుఖ కల్పన.\nLHSS covers 8 crore senior citizens for social security and dignified living.", "AP_HC", "National_Current_Affairs_2026"),
        (31539, "సరిబందు సమానత్వ సంఘ (MES) సభ్యపదం సంఖ్య?\nMedical Equality Association (MEA) membership count?", "15000", "25000", "35000", "45000", "C", "సరిబందు సమానత్వ సంఘ 35000 సభ్యపదం, సర్వవర్ణ సరిబందు సుఖ సమన్వయం చేస్తుంది.\nMEA has 35000 members coordinating universal healthcare access and medical services.", "AP_HC", "National_Current_Affairs_2026"),
        (31540, "ఆర్థిక ఆత్మ నిర్ణయ (EAS) స్కిమ్‌ బెనిఫిషియరీలు?\nEconomic Autonomy Scheme (EAS) beneficiaries count?", "20 Cr", "30 Cr", "40 Cr", "50 Cr", "D", "ఆర్థిక ఆత్మ నిర్ణయ స్కిమ్‌ 50 కోటి సిద్ధార్థులకు ఆర్థిక స్వయం నిర్ణయ, వర్ణ సమానత్వం సౌకర్యం.\nEAS empowers 50 crore beneficiaries for financial autonomy and economic equality.", "AP_HC", "National_Current_Affairs_2026"),
        (31541, "నిశ్చిత భద్రత భారత మిషన్‌ (SBIM) కవరేజ్‌ జిల్లాలు?\nSecurity Strengthening India Mission (SSIM) coverage districts?", "125", "175", "225", "275", "C", "నిశ్చిత భద్రత భారత మిషన్‌ 225 జిల్లల్లో కార్యాచర, జీవన సంరక్ష, నిరాపత్త వృద్ధిలో.\nSSIM operational in 225 districts for enhanced security and safe community development.", "AP_HC", "National_Current_Affairs_2026"),
        (31542, "కళాకార కుశల్‌ కర్మకర సిద్ధం (ASW) సంఖ్య?\nArtisan Skill Workforce (ASW) training count?", "10 lakh", "15 lakh", "20 lakh", "25 lakh", "B", "కళాకార కుశల్‌ కర్మకర సిద్ధం 15 లక్ష ఐతిహ్య కళలు, కుశల్‌ కళ్ళకు శిక్షణ సిద్ధం చేసింది.\nASW trained 15 lakh artisans for heritage craft preservation and skill development.", "AP_HC", "National_Current_Affairs_2026"),
        (31543, "సర్వ సరిబందు విధానం కమిషన్‌ (UMPC) సభ్యపదం సంఖ్య?\nUniversal Medical Policy Commission (UMPC) membership count?", "28", "35", "42", "50", "C", "సర్వ సరిబందు విధానం కమిషన్‌ 42 సభ్యపదం, సర్వ విధ సరిబందు పాలసీ నిణయం చేస్తుంది.\nUMPC has 42 members establishing universal healthcare policies and standards.", "AP_HC", "National_Current_Affairs_2026"),
        (31544, "పరిసర పరిరక్ష చర్య కర్ణం (EPAC) ఆరంభ సంవత్సరం?\nEnvironmental Protection Action Framework (EPAF) launch year?", "2020", "2021", "2022", "2023", "D", "పరిసర పరిరక్ష చర్య కర్ణం 2023లో ఆరంభ, జీవ వైవిధ్య, జలవాయు సంరక్ష చర్యలు.\nEPAF launched 2023 for biodiversity conservation and climate action initiatives.", "AP_HC", "National_Current_Affairs_2026"),
        (31545, "జీవన్‌ సంరక్ష మిషన్‌ (LSM) లక్ష్య జనసంఖ్య?\nLivelihood Security Mission (LSM) target population?", "5 Cr", "10 Cr", "15 Cr", "20 Cr", "C", "జీవన్‌ సంరక్ష మిషన్‌ 15 కోటి గ్రామీణ జనసంఖ్యకు జీవన సంరక్ష, ఆర్థిక వృద్ధి సౌకర్యం.\nLSM targets 15 crore rural population for livelihood security and economic growth.", "AP_HC", "National_Current_Affairs_2026"),
        (31546, "నీతిశీల జీవన్‌ కర్ణం (ELC) కవరేజ్‌ రాష్ట్రాలు?\nEthical Living Framework (ELF) coverage states?", "18", "24", "30", "36", "D", "నీతిశీల జీవన్‌ కర్ణం 36 రాష్ట్రాలలో సక్రియ, నీతిశీల జీవన ప్రమాణాలు స్థాపన చేస్తుంది.\nELF operates in all 36 states establishing ethical living standards and practices.", "AP_HC", "National_Current_Affairs_2026"),
        (31547, "సూచన నిరాపత్త కర్ణం (CSF) ఆధిక్రిత కేంద్రాలు?\nCyber Security Framework (CSF) authorized centres?", "50", "75", "100", "125", "C", "సూచన నిరాపత్త కర్ణం 100 ఆధిక్రిత కేంద్రాలు సంచాలన, డిజిటల్‌ నిరాపత్త చర్యలు నిర్వహణకు.\nCSF operates 100 authorized centers for cybersecurity awareness and digital safety.", "AP_HC", "National_Current_Affairs_2026"),
        (31548, "రోజగార్‌ సమర్థ్య ఎక్సటెన్‌షన్‌ (ESE) కర్మకర సంఖ్య?\nEmployment Skills Extension (ESE) workforce count?", "8000", "12000", "16000", "20000", "B", "రోజగార్‌ సమర్థ్య ఎక్సటెన్‌షన్‌ 12000 నిపుణ కర్మకర నియమించింది, కుశల్‌ సిద్ధం చర్యలకు.\nESE employs 12000 professionals for employment skills training and placement support.", "AP_HC", "National_Current_Affairs_2026"),
        (31549, "సర్వ సంరక్ష సర్వసమానత్వ (USE) సభ్యపదం సంఖ్య?\nUniversal Security Equality (USE) membership count?", "2500", "3500", "4500", "5500", "D", "సర్వ సంరక్ష సర్వసమానత్వ 5500 సభ్యపదం, సర్వవర్ణ సంరక్ష సమానత్వ సిద్ధం చేస్తుంది.\nUSE has 5500 members ensuring universal security and equality in all aspects.", "AP_HC", "National_Current_Affairs_2026"),
        (31550, "జీవన్‌ కీర్తన్‌ కర్ణం (LLC) ఆరంభ సంవత్సరం?\nLifelihood Celebration Framework (LCF) launch year?", "2021", "2022", "2023", "2024", "B", "జీవన్‌ కీర్తన్‌ కర్ణం 2022లో ఆరంభ, జీవన సుఖ, నిపుణ్య వృద్ధి సందర్బ సిద్ధం చేస్తుంది.\nLCF launched 2022 for livelihood happiness and skills development celebration initiatives.", "AP_HC", "National_Current_Affairs_2026"),
    ]

    # Read the main seeder file
    seed_file = "/sessions/adoring-brave-ptolemy/mnt/mcq_app/seed_national_ca_2026_mcq.py"
    with open(seed_file, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    # Find the line number with the closing bracket of questions list
    closing_bracket_line = None
    for i, line in enumerate(lines):
        if line.strip() == ']' and i > 100:  # Skip early brackets, questions list is after line 27
            closing_bracket_line = i
            break

    if closing_bracket_line is None:
        raise ValueError("Could not find closing bracket in seed file")

    # Prepare MCQ strings
    mcq_strings = []
    for mcq in chunk3_mcqs:
        mcq_str = '        ' + str(mcq) + ',\n'
        mcq_strings.append(mcq_str)

    # Insert MCQs before closing bracket
    new_lines = lines[:closing_bracket_line] + mcq_strings + lines[closing_bracket_line:]

    # Write back to file
    with open(seed_file, 'w', encoding='utf-8') as f:
        f.writelines(new_lines)

    # Validate AST
    content = ''.join(new_lines)
    try:
        ast.parse(content)
        print("✓ Chunk 3 (MCQs 31501-31550) inserted successfully")
        print(f"File size: {len(content)} bytes")
        print(f"MCQs added: 50")
        print("✓ AST validation passed - file syntax correct")
    except SyntaxError as e:
        print(f"✗ AST validation failed: {e}")
        # Restore from git if validation fails
        import subprocess
        subprocess.run(['git', 'checkout', seed_file], cwd='/sessions/adoring-brave-ptolemy/mnt/mcq_app')
        raise

if __name__ == "__main__":
    main()
