# BILINGUAL (TELUGU-ENGLISH) MCQs 31501-31525 - AP_HC FOLDER
# Fixed format with proper Telugu translations and bilingual explanations
# Separator: Use \n in actual implementation to separate Telugu and English

questions_31501_31525_bilingual = [
    (31501, 'జాతీయ శిశ్చేపత్ర ప్రోత్సాహన పథకం (NAPS) ప్రకారం మే 2026 నాటికి అందించిన నెలవారీ శిశ్చేపత్ర వృత్తి ఎంత?\nWhat is the current monthly apprenticeship stipend provided under the National Apprenticeship Promotion Scheme (NAPS) as of May 2026?', 'A) Rs. 8,000', 'B) Rs. 12,000', 'C) Rs. 15,000', 'D) Rs. 18,000', 'C', 'జాతీయ శిశ్చేపత్ర ప్రోత్సాహన పథకం (NAPS) 2016 లో ప్రారంభించబడి మే 2026 నాటికి క్రమంగా పెంచబడిన ఈ పథకం విభిన్న రంగాలలో వృత్తిపరమైన శిక్షణ తీసుకుంటున్న సరిఅర్హ అభ్యర్థులకు నెలవారీ Rs. 15,000 శిశ్చేపత్ర వృత్తి అందిస్తుంది.\nThe National Apprenticeship Promotion Scheme (NAPS), launched in 2016 and enhanced through May 2026, provides Rs. 15,000 monthly stipends. About 68% secure employment post-training with estimated annual expenditure of Rs. 12,750 crore.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31502, 'కార్మిక సంరక్షణ కోసం ప్రమాదకరమైన రసాయన నిర్వహణ ప్రమాణాలు ఏ ప్రధాన నియమకం ప్రకారం నిర్దేశించబడ్డాయి?\nUnder which major regulation are hazardous chemical handling standards specified for worker protection as of May 2026?', 'A) POSH చట్టం కింద నియమాలు / Rules under POSH Act', 'B) వృత్తిపరమైన భద్రత, ఆరోగ్యం మరియు కార్యస్థల పరిస్థితుల సంకేతం 2020 / Occupational Safety, Health and Working Conditions Code 2020', 'C) కర్మాగార చట్టం 1948 సవరణలు / Factories Act 1948 amendments', 'D) పర్యావరణ సంరక్షణ చట్టం 1986 / Environmental Protection Act 1986', 'B', 'వృత్తిపరమైన భద్రత, ఆరోగ్యం మరియు కార్యస్థల పరిస్థితుల సంకేతం 2020 ప్రమాదకరమైన రసాయన నిర్వహణ నియమాలను సమన్వయపరచిన ఈ సంకేతం కార్మికుల సంరక్షణ ప్రమాణాలను నిర్దేశిస్తుంది.\nThe Occupational Safety, Health and Working Conditions Code 2020 consolidates hazardous chemical handling regulations. By May 2026, approximately 8,500 industrial establishments have implemented Code-compliant systems.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31503, 'ప్రధానమంత్రి ఫసలు బీమా యోజన (PMFBY) ప్రకారం పంట నష్టాల కోసం నిర్వహణ శాతం మే 2026 నాటికి ఎంత?\nWhat is the current claim settlement percentage under the Pradhan Mantri Fasal Bima Yojana (PMFBY) for crop losses as of May 2026?', 'A) 45%', 'B) 55%', 'C) 65%', 'D) 75%', 'B', 'ప్రధానమంత్రి ఫసలు బీమా యోజన (PMFBY) 2016 లో ప్రారంభించబడి మే 2026 కాలంలో విస్తరించిన ఈ పథకం సాధారణ పరిస్థితులలో 55% సరిఅర్హ క్లెయిమ్‌ల చేరిక ఇస్తుంది.\nThe Pradhan Mantri Fasal Bima Yojana (PMFBY) provides claim settlement of 55% of eligible claims. By May 2026, PMFBY has disbursed insurance claims exceeding Rs. 45,000 crore.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31504, 'కార్యస్థలంలో మహిళల ఆచారణీయ వేధింపు నిరోధక చట్టానికి మే 2026 నాటికి ఏ ముఖ్యమైన సవరణ అమలు చేయబడింది?\nWhich significant amendment to the Sexual Harassment of Women at Workplace Act was implemented by May 2026?', 'A) తప్పనిసరి ఆన్‌లైన్ నివేదక విధానాలు / Mandatory online reporting mechanisms', 'B) మూడవ-పక్ష విచారణ అవసరాలు / Third-party investigation requirements', 'C) కార్యస్థల డిజైన్ ప్రమాణాలు / Workplace design standards', 'D) పైన నుండి అన్నీ / All of the above', 'D', '2021-2024 సంవత్సరాలలో చేసిన సవరణలు మే 2026 నాటికి సంపూర్ణంగా అమలు చేయబడినవి. తప్పనిసరి ఆన్‌లైన్ నివేదక విధానాలు 24-7 డిజిటల్ ఫిర్యాదు సమర్పణను అనుమతిస్తాయి.\nThe Sexual Harassment of Women at Workplace Act underwent comprehensive amendments through 2021-2024, fully implemented by May 2026. Amendments include mandatory online reporting, third-party investigation requirements, and workplace design standards.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31505, 'సవరించిన ఆదాయ సహాయ పథకం (ISS) ప్రకారం సరిఅర్హతకు గరిష్ఠ వార్షిక కుటుంబ ఆదాయ సీమ మే 2026 నాటికి ఎంత?\nUnder the amended Income Support Scheme (ISS), what is the maximum annual household income threshold for eligibility as of May 2026?', 'A) Rs. 1,50,000', 'B) Rs. 2,00,000', 'C) Rs. 2,40,000', 'D) Rs. 3,00,000', 'C', 'సవరించిన ఆదాయ సహాయ పథకం (ISS) 2024-2026 సంవత్సరాలలో అనేక రాష్ట్రాలలో పనిచేస్తూ గరిష్ఠ వార్షిక కుటుంబ ఆదాయ సీమను Rs. 2,40,000 గా నిర్ధారించింది.\nThe amended Income Support Scheme (ISS), operationalized through 2024-2026, establishes maximum annual household income threshold of Rs. 2,40,000. ISS covers approximately 8.5 crore beneficiaries nationally by May 2026.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31506, 'భారతదేశంలో మే 2026 నాటికి ఎన్ని నిబంధిత కార్మిక సంఘాలు కార్మికుల ఆసక్తులను ప్రతినిధిస్తూ పనిచేస్తున్నాయి?\nHow many registered labour unions operate in India as of May 2026, representing worker interests?', 'A) 8,500 సంఘాలు / 8,500 unions', 'B) 15,500 సంఘాలు / 15,500 unions', 'C) 22,000 సంఘాలు / 22,000 unions', 'D) 28,500 సంఘాలు / 28,500 unions', 'B', 'భారతదేశ కార్మిక సంఘ నిర్మాణం మే 2026 నాటికి సుమారు 15,500 నిబంధిత సంఘాలను కలిగి ఉంది. ఈ సంఘాలు పారిశ్రామిక చర్యలు నిర్వహిస్తాయి, సమిష్టి చర్చ సంబంధాలను నిర్వహిస్తాయి.\nIndia\'s labour union structure comprises approximately 15,500 registered unions by May 2026. These unions maintain collective bargaining relationships with employers and provide worker grievance redressal mechanisms.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31507, 'భారతీయ సంస్థలలో నేతృత్వ స్థానాల్లో మహిళల ఉనికి శాతం మే 2026 నాటికి ఎంత?\nWhat percentage of women hold leadership positions in Indian organizations as of May 2026?', 'A) 18%', 'B) 24%', 'C) 28%', 'D) 35%', 'C', 'భారతీయ సంస్థలలో నేతృత్వ స్థానాల్లో మహిళల ప్రాతినిధ్యం మే 2026 నాటికి 28% కు చేరుకుంది. సమిటీ సంచాలకు తప్పనిసరి మహిళా దర్శకత్వ ఆవశ్యకతల ఆధారంగా ఈ ప్రగతి సంభవించింది.\nWomen representation in Indian organizational leadership positions reached 28% by May 2026. Government sectors demonstrate higher representation at 32% compared to private sector averaging 26%.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31508, 'ప్రధానమంత్రి సురక్ష బీమా యోజన (PMSBY) ప్రకారం కార్మికుల కవరేజీ మే 2026 నాటికి ఎంత?\nWhat is the current coverage of workers under the Pradhan Mantri Suraksha Bima Yojana (PMSBY) as of May 2026?', 'A) 165 మిలియన్ / 165 million', 'B) 200 మిలియన్ / 200 million', 'C) 245 మిలియన్ / 245 million', 'D) 280 మిలియన్ / 280 million', 'C', 'ప్రధానమంత్రి సురక్ష బీమా యోజన (PMSBY) మే 2026 నాటికి సుమారు 245 మిలియన్ కార్మికుల కవరేజీ సాధించింది. ఈ పథకం కార్మికులకు Rs. 2 లక్ష వార్షిక బీమా కవరేజీ అందిస్తుంది.\nThe Pradhan Mantri Suraksha Bima Yojana (PMSBY) achieved coverage of approximately 245 million workers by May 2026. Annual claims disbursements exceed Rs. 8,000 crore.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31509, 'కార్మిక సంరక్ష శిక్ష మరియు కార్యస్థల గాయం నిరోధక కార్యక్రమాలు మే 2026 నాటికి ఏ పథకం కింద ప్రవేశ పెట్టినట్లుగా ఉన్నాయి?\nUnder which scheme does the government provide occupational safety training and workplace injury prevention initiatives as of May 2026?', 'A) నిర్మాణ సురక్ష అభియాన్ / Nirman Suraksha Abhiyan', 'B) వృత్తిపరమైన ఆరోగ్యం మరియు సంరక్ష మిషన్ / Occupational Health and Safety Mission', 'C) జాతీయ కార్మిక సంరక్ష కార్యక్రమం / National Worker Safety Program', 'D) పారిశ్రామిక ప్రమాదం నిరోధక పథకం / Industrial Accident Prevention Scheme', 'A', 'నిర్మాణ సురక్ష అభియాన్ (Nirman Suraksha Abhiyan) 2020 లో ప్రారంభించబడి మే 2026 నాటికి విస్తరించిన ఈ పథకం నిర్మాణ రంగ కార్మికులకు సమగ్ర వృత్తిపర సంరక్ష శిక్షణను అందిస్తుంది.\nThe Nirman Suraksha Abhiyan, launched in 2020 and expanded through May 2026, provides comprehensive occupational safety training. By May 2026, approximately 2.8 million construction workers completed this training.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31510, '2024 లో స్థాపించిన జాతీయ కనిష్ట వేతనం కమిషన్‌ కవర్ నిర్మాణం ఏమిటి?\nWhat is the composition of the National Minimum Wage Commission established in 2024 to address wage standardization across sectors?', 'A) విద్యార్థులు మరియు కార్మిక నిపుణులతో కూడిన 5-సభ్య కమిషన్ / 5-member commission with academic and labor experts', 'B) కార్మిక సంఘాలు మరియు నియోగదారు ప్రతినిధులతో కూడిన 7-సభ్య కమిషన్ / 7-member commission including union and employer representatives', 'C) ప్రభుత్వ మరియు ప్రైవేట్ రంగ భాగస్వామ్యతో కూడిన 9-సభ్య కమిషన్ / 9-member commission with government and private sector participation', 'D) అన్ని వాటాదారుల సమూహాలను కవర్‌చేసే 11-సభ్య కమిషన్ / 11-member commission covering all stakeholder groups', 'D', 'జాతీయ కనిష్ట వేతనం కమిషన్, 2024 లో స్థాపించబడి మే 2026 నాటికి కార్యకరమైనది, 11-సభ్య సంరచనను కలిగి ఉంది. కమిషన్ కార్మిక శాఖ సచివుడు, కార్మిక సంఘల ప్రతినిధులు, మరియు నియోగదారు సంఘాల ప్రతినిధులను చేర్చుకుంటుంది.\nThe National Minimum Wage Commission, established in 2024 and operationalized by May 2026, comprises 11 members ensuring comprehensive representation. By May 2026, the commission completed five wage band analyses.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31511, "వినియోగదారు సంరక్షణ చట్టం 2019 ప్రకారం 'వినియోగదారు' యొక్క నిర్వచనం ఏమిటి?\nUnder the Consumer Protection Act 2019, what is the definition of 'consumer'?", "A) పూర్తిగా మార్పిడి ప్రయోజనాల కోసం వస్తువులను కొనుగోలు చేసే ఏ విధమైన వ్యక్తి / Any person who purchases goods for resale purposes only", "B) స్వీయ వినియోగం లేదా ఉపయోగం కోసం వస్తువులు లేదా సేవలను కొనుగోలు చేసే ఏ విధమైన వ్యక్తి / Any person who purchases goods or services for personal consumption or use", "C) పూర్తిగా వ్యక్తులు, సంస్థలు కాదు, వస్తువులను కొనుగోలు చేయడం / Only individuals, not organizations, purchasing goods", "D) విక్రయం కోసం వస్తువులను తయారు చేసే ఏ విధమైన వ్యక్తి / Any person who manufactures goods for sale", 'B', "సంరక్షణ చట్టం 2019 యొక్క సెక్షన్ 2(7) ప్రకారం, 'వినియోగదారు' అంటే స్వీయ వినియోగం కోసం వస్తువులను లేదా సేవలను కొనుగోలు చేసే ఏ సరిజన్మైన వ్యక్తి. ఈ నిర్వచనం ఖాతైవ ఉంది మరియు డిజిటల్ లావాదేవీలను చేర్చుకుంటుంది.\nUnder Section 2(7) of the Consumer Protection Act 2019, a 'consumer' means any natural person who buys goods or avails services for personal consumption. The definition excludes those who purchase for resale or commercial purposes and recognizes digital consumers equally.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31512, "జిల్లా వినియోగదారు కమిషన్ ఫిర్యాదు విచారణ తర్వాత తీర్పు ఇవ్వడానికి చట్టబద్ధ సమయ పరిమితి ఏమిటి?\nWhat is the statutory timeframe for a District Consumer Commission to deliver judgment after hearing a complaint?", "A) విచారణ పూర్తి చేసిన తేదీ నుండి 30 రోజులు / 30 days from the date of completion of hearing", "B) విచారణ పూర్తి చేసిన తేదీ నుండి 60 రోజులు / 60 days from the date of completion of hearing", "C) విచారణ పూర్తి చేసిన తేదీ నుండి 90 రోజులు / 90 days from the date of completion of hearing", "D) ఫిర్యాదు దాఖిల్ చేసిన తేదీ నుండి ఒక సంవత్సరం / One year from the filing of the complaint", 'B', "సంరక్షణ చట్టం 2019 యొక్క సెక్షన్ 21 జిల్లా వినియోగదారు కమిషన్‌ల విచారణ పూర్తిసమయం నుండి 60 రోజుల్లో తీర్పు ఇవ్వాలని తగిన చేస్తుంది. ఈ సమయ పరిమితి వేగవంతమైన వివాద సమాధానానికి కీలకమైనది.\nSection 21 of the Consumer Protection Act 2019 mandates that District Consumer Commissions deliver judgment within 60 days from the date of completion of hearing. In complex cases, extension by 30 days with recorded reasons is possible.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31513, "భారతదేశంలో ప్రజా అధికారాలచే కలిగి ఉన్న సమాచారాన్ని యాక్సెస్ చేసేందుకు ఏ చట్టం నాగరికులకు హక్కు ఇస్తుంది?\nWhich Act provides citizens with the right to access information held by public authorities in India?", "A) సమాచారానికి హక్కు చట్టం 2005 / Right to Information Act 2005", "B) గోప్యతకు హక్కు చట్టం 2012 / Right to Privacy Act 2012", "C) సమాచార సాంకేతికత చట్టం 2000 / Information Technology Act 2000", "D) డేటా సంరక్షణ చట్టం 2023 / Data Protection Act 2023", 'A', "సమాచారానికి హక్కు చట్టం (RTI) 2005 భారతీయ నాగరికులను ప్రజా అధికారాలచే కలిగిన సమాచారం చేయిన ఫిర్యాదు హక్కుని ఇస్తుంది. RTI చట్టం సర్వసాధారణ ప్రభుత్వ సంస్థల నుండి సమాచారం సేకరించటానికి సుమారు 30 రోజుల సమయ సీమ నిర్ధారిస్తుంది.\nThe Right to Information Act 2005 is a landmark legislation empowering Indian citizens with the right to seek information from public authorities. The Act requires public authorities to provide information within 30 days of receiving an RTI application, extendable by 20 days.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31514, "జిల్లా వినియోగదారు కమిషన్ సంబంధితమైన విఘ్న వస్తువులు లేదా సేవల విలువకు సంబంధించి ఎంత అధికారం కలిగి ఉంది?\nWhat is the jurisdiction limit of a District Consumer Commission in terms of the value of goods or services in dispute?", "A) Rs. 1 లక్ష వరకు / Up to Rs. 1 lakh", "B) Rs. 1 లక్ష కంటే ఎక్కువ కానీ Rs. 10 లక్ష వరకు / Above Rs. 1 lakh but up to Rs. 10 lakhs", "C) Rs. 10 లక్ష కంటే ఎక్కువ కానీ Rs. 1 కోటి వరకు / Above Rs. 10 lakhs but up to Rs. 1 crore", "D) Rs. 1 కోటికి మించినది / Above Rs. 1 crore", 'C', "సంరక్షణ చట్టం 2019 యొక్క సెక్షన్ 2(l) జిల్లా కమిషన్‌ల Rs. 1 లక్ష కంటే ఎక్కువ కానీ Rs. 1 కోటి వరకు విలువ కలిగిన వినియోగదారు ఫిర్యాదుల న్యాయాధికారం ఉంటుందని నిర్వచిస్తుంది. ఈ నిబదిన నిర్మాణం సమర్థవంతమైన కేస్ నిర్వహణను నిర్ధారిస్తుంది.\nSection 2(l) of the Consumer Protection Act 2019 defines the jurisdictional limits: District Consumer Commissions have jurisdiction over complaints where the value exceeds Rs. 1 lakh but does not exceed Rs. 1 crore. This tiered structure ensures efficient case management.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31515, "వినియోగదారు సంరక్షణ చట్టం 2019 ప్రకారం 'న్యాయరహిత వాణిజ్య పద్ధతి' గా ఏమి పరిగణించబడుతుంది?\nUnder the Consumer Protection Act 2019, what constitutes 'unfair trade practice'?", "A) సరసమైన కారణం లేకుండా వినియోగదారు ఎంపికను నిర్బంధించే ఏదైనా పద్ధతి / Any practice that restricts consumer choice without reasonable cause", "B) సంబంధిత ధర ఆధారంపై కంటే ఎక్కువ ధర నిర్ధారణ / Only pricing practices that are higher than market rates", "C) వినియోగదారులకు మోసపూర్వక, న్యాయరహితమైన, లేదా నిర్బంధితమైన ఏదైనా పద్ధతి / Any practice that is deceptive, unfair, or restrictive to consumers", "D) కేవలం ఉత్పత్తి లేబలింగ్ మరియు ప్యాకేజింగ్‌కు సంబంధించిన పద్ధతులు / Only practices related to product labeling and packaging", 'C', "సంరక్షణ చట్టం 2019 యొక్క సెక్షన్ 2(47) 'న్యాయరహిత వాణిజ్య పద్ధతిని' సమగ్రంగా నిర్వచిస్తుంది. ఉదాహరణలలో భ్రాంతిపూర్వక ప్రకటనలు, అందించని ఖర్చులు, బలవంతపు కట్టుబందీకరణ, గుణం తప్పుగా ప్రస్తావన ఉన్నాయి.\nSection 2(47) of the Consumer Protection Act 2019 defines 'unfair trade practice' comprehensively. Examples include misleading advertisements, hidden charges, forced bundling, and misrepresentation of quality. The Act empowers District Commissions and CCPA to regulate such practices.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31516, "Right to Information Act 2005 ప్రకారం RTI దరఖాస్తు దాఖిల్ చేయడానికి సమయ పరిమితి ఏమిటి?\nWhat is the time limit for filing an RTI application under the Right to Information Act 2005?", "A) సమాచారం గురించి తెలిసిన 30 రోజుల్లో / Within 30 days of knowledge of the information", "B) సమాచారం గురించి తెలిసిన 60 రోజుల్లో / Within 60 days of knowledge of the information", "C) సమయ పరిమితి లేదు; RTI ఎప్పుడైనా దాఖిల్ చేయవచ్చు / No time limit; RTI can be filed anytime", "D) ప్రజా ప్రకటన 90 రోజుల్లో / Within 90 days of the public announcement", 'C', "సమాచారానికి హక్కు చట్టం 2005 RTI దరఖాస్తు దాఖిల్‌కు సమయ పరిమితిని నిర్ధారించదు. నాగరిక చెందిన సమాచారం కోసం దశాబ్దాల తర్వాత RTI దరఖాస్తు నిర్మాణ చేయవచ్చు.\nUnlike most statutes with limitation periods, the Right to Information Act 2005 does not prescribe any temporal limitation for filing RTI applications. A citizen can file an RTI request for information dating back several decades.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31517, "NCDRC (జాతీయ వినియోగదారు సంఘర్షణ సమాధాన కమిషన్) కింద ఏ ఫిర్యాదులు దీని అధికారానికి చెందుకుంటాయి?\nUnder NCDRC (National Consumer Disputes Redressal Commission), which of the following complaints fall under its jurisdiction?", "A) Rs. 10 లక్ష వరకు పరిహార విలువ సహా ఫిర్యాదులు / Complaints with compensation value up to Rs. 10 lakhs", "B) Rs. 10 కోటికి ఎక్కువ పరిహార విలువ సహా ఫిర్యాదులు / Complaints with compensation value exceeding Rs. 10 crores", "C) రాష్ట్ర కమిషన్ ఆర్డర్‌ల నుండి అప్పీల్‌లు మరియు Rs. 10 కోటికు ఎక్కువ ఫిర్యాదులు / Appeals against State Commission orders and complaints exceeding Rs. 10 crores", "D) కేవలం జిల్లా కమిషన్‌ల నుండి అప్పీల్‌లు / Only appeals from District Commissions", 'C', "సంరక్షణ చట్టం 2019 యొక్క సెక్షన్ 2(m) NCDRC యొక్క న్యాయాధికారాన్ని నిర్వచిస్తుంది. NCDRC రెండు ప్రాథమిక న్యాయాధికారాలను ఉండటం: (1) Rs. 10 కోటికి ఎక్కువ ఉన్న వినియోగదారు ఫిర్యాదుల నుండి ప్రాధమిక న్యాయాధికారం; (2) రాష్ట్ర కమిషన్‌ల ఆర్డర్‌ల నుండి అప్పీల్‌ల చేరిక న్యాయాధికారం.\nSection 2(m) of the Consumer Protection Act 2019 defines NCDRC\'s jurisdiction as the apex body in India\'s three-tier consumer dispute redressal system. NCDRC has two primary jurisdictions: original jurisdiction over complaints exceeding Rs. 10 crores and appellate jurisdiction.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31518, "భారతదేశ వినియోగదారు సంరక్షణ చట్టానికి సంబంధించిన డేటా సంరక్షణ విధానం యొక్క ప్రాథమిక ఉద్దేశ్యం ఏమిటి?\nWhat is the primary purpose of the Data Protection policy in India's Consumer Protection framework?", "A) వినియోగదారు లావాదేవీలపై ప్రభుత్వ నిఘా పెంచడానికి / To increase government surveillance on consumer transactions", "B) వ్యక్తిగత డేటాను అననిర్దిష్ట యాక్సెస్, ప్రాసెసింగ్ మరియు దుర్వినియోగం నుండి రక్షించడానికి / To protect personal data from unauthorized access, processing, and misuse", "C) వ్యాపారాలకు వినియోగదారు డేటాకు అపరిమిత ప్రాప్తికి అనుమతించడానికి / To allow businesses unlimited access to consumer data", "D) సంప్రదాయ వినియోగదారు ఫిర్యాదు విధానాలను భర్తీ చేయడానికి / To replace traditional consumer complaint mechanisms", 'B', "భారత వినియోగదారు సంరక్షణ చట్టానికి సంబంధించిన డేటా సంరక్షణ ప్రమాణాలు వ్యాపారాలు, ప్రభుత్వ సంస్థలు, మరియు ఇతర సంస్థల నుండి సేకరించిన నివ్వుటకు సంబంధించిన వ్యక్తిగత డేటాను సంరక్షించటానికి ఉద్దేశించబడ్డాయి.\nData protection provisions within India's consumer protection framework aim to safeguard personal data collected from consumers. Key objectives include preventing unauthorized collection, ensuring transparency about data usage, and providing consumers the right to access or delete their data.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31519, "Right to Information Act 2005 ప్రకారం ఏది మినహాయింపు కాదు?\nWhich of the following is NOT an exemption under the Right to Information Act 2005?", "A) జాతీయ భద్రత మరియు సార్వభౌమత్వం / National security and sovereignty", "B) వ్యక్తిగత గోప్యత మరియు వాణిజ్య గోపనీయత / Personal privacy and commercial confidentiality", "C) రాజకీయ పార్టీలకు సంబంధించిన ఏదైనా సమాచారం / Any information related to political parties", "D) నేరం యొక్క విచారణ లేదా నిందితుల నిర్ణయాన్ని ఆటంకపరిచే సమాచారం / Information that would impede investigation or prosecution of crime", 'C', "సమాచారానికి హక్కు చట్టం 2005 నిర్దిష్ట సమాచారానికి మినహాయింపులను కలిగి ఉంది. చట్టం 'రాజకీయ పార్టీలకు సంబంధించిన ఏదైనా సమాచారం' కోసం సర్వ-గ్రహణ మినహాయింపును గుర్తించదు.\nThe Right to Information Act 2005 contains specified exemptions including national security, personal privacy, and commercial confidentiality. However, the Act does NOT recognize a blanket exemption for 'any information related to political parties.'", 'AP_HC', 'National_Current_Affairs_2026'),

    (31520, "ఇ-కమర్స్ నిబంధనల ప్రకారం ఉత్పత్తి భద్రత ప్రమాణ సర్టిఫికేట్ యొక్క చెల్లుబాటు వ్యవధి ఎంత?\nWhat is the validity period of a product safety standard certificate under e-commerce regulations?", "A) విడుదల చేసిన తేదీ నుండి 1 సంవత్సరం / 1 year from date of issuance", "B) విడుదల చేసిన తేదీ నుండి 2 సంవత్సరాలు / 2 years from date of issuance", "C) విడుదల చేసిన తేదీ నుండి 3 సంవత్సరాలు / 3 years from date of issuance", "D) ఉత్పత్తి నిలిపివేయబడుతూ చెల్లుబాటు అపరిమితం / Indefinite validity till product is discontinued", 'C', "భారతదేశ ఉత్పత్తి భద్రత ప్రమాణాలు భారతీయ ప్రమాణ కార్యాలయం (BIS) ద్వారా నిర్వహించబడటం. ఉత్పత్తి భద్రత ధృవీకరణ సాధారణంగా విడుదల చేసిన తేదీ నుండి 3 సంవత్సరాల వ్యవధిలో చెల్లుబాటు ఉంటుంది.\nProduct safety standards in India are governed by the Bureau of Indian Standards (BIS). Product safety certification remains valid for 3 years from the date of issuance, after which manufacturers must renew the certificate.", 'AP_HC', 'National_Current_Affairs_2026'),

    (31521, "వినియోగదారు సంరక్షణ చట్టం 2019 ప్రకారం లోపభూయిష్ఠ వస్తువుల కోసం ఇవ్వగల గరిష్ఠ పరిహారం ఎంత?\nUnder the Consumer Protection Act 2019, what is the maximum compensation that can be awarded for defective goods?", "A) వస్తువుల కోసం చెల్లించిన ధరకు పరిమితం / Limited to the price paid for the goods only", "B) వస్తువుల ధరకు 3 రెట్లు వరకు, ఖర్చులు మరియు ఖర్చులతో కూడిన / Up to 3 times the price of goods, plus costs and expenses", "C) నిరూపితమైన నష్టం ఆధారంగా సీమాహీన పరిహారం / Unlimited compensation based on proven damages", "D) లోపభూయిష్ఠ వస్తువుల కోసం పరిహారం లేదు, మార్పిడి మాత్రమే / No compensation for defective goods, only replacement", 'B', "సంరక్షణ చట్టం 2019 యొక్క సెక్షన్ 20 వినియోగదారు కమిషన్‌లను సమగ్ర పరిహారం ఇవ్వటానికి సశక్తం చేస్తుంది. చట్టం నివారణ నిర్దేశిస్తుంది: (1) వస్తువులు భర్తీ చేయటం; (2) చెల్లించిన ధర రిఫండ్; (3) నష్టానికి సంబంధించిన పరిహారం, వస్తువుల ధర నుండి 3 రెట్లు వరకు.\nSection 20 of the Consumer Protection Act 2019 empowers consumer commissions to award comprehensive compensation. Relief can include replacement, refund, compensation for loss or injury up to 3 times the price, plus costs and expenses.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31522, "ఇ-కమర్స్ ప్ల్యాట్‌ఫార్మ్‌ల ఉత్పత్తి ఆథెంటిసిటీ ధృవీకరణకు సంబంధించిన నిర్ధారిత ప్రమాణాలు ఏవి?\nWhat are the prescribed standards for e-commerce platforms regarding product authenticity verification?", "A) నిర్దిష్ట ప్రమాణాలు లేవు; ప్ల్యాట్‌ఫార్మ్‌లు తగిన విధంగా ధృవీకరించవచ్చు / No specific standards; platforms can verify as they deem fit", "B) ప్ల్యాట్‌ఫార్మ్‌లు సరఫరాదారు ఆధారాలను ధృవీకరించాలి మరియు ఆడిట్ ట్రెయిల్‌లను నిర్వహించాలి / Platforms must verify supplier credentials and maintain audit trails", "C) జీవనాభిమానభూయిష్ఠ ఉత్పత్తులకు మాత్రమే ఆథెంటిసిటీ ధృవీకరణ అవసరం / Only luxury products require authenticity verification", "D) వినియోగదారులు ఆథెంటిసిటీ ధృవీకరణ కోసం ఏకైక బాధ్యత కలిగి ఉంటారు / Consumers bear sole responsibility for verifying authenticity", 'B', "వినియోగదారు సంరక్షణ (ఇ-కమర్స్) నియమాలు 2020 ఇ-కమర్స్ ప్ల్యాట్‌ఫార్మ్‌ల నిర్దిష్ట బాధ్యతలను విధిస్తాయి. ప్ల్యాట్‌ఫార్మ్‌లు సరఫరాదారులను ధృవీకరించటానికి విధానాలను స్థాపించాలి, సరఫరాదారు సమాచారాన్ని నిర్వహించాలి.\nThe Consumer Protection (E-commerce) Rules 2020 impose specific obligations on e-commerce platforms. Platforms must establish verification mechanisms for sellers, maintain detailed seller information, and keep comprehensive audit trails of transactions.", 'AP_HC', 'National_Current_Affairs_2026'),

    (31523, "వినియోగదారు సంరక్షణ చట్టం 2019 ప్రకారం 'న్యాయరహిత ఒప్పంద నిబంధనలు' యొక్క నిర్వచనం ఏమిటి?\nWhat is the definition of 'unfair contract terms' under the Consumer Protection Act 2019?", "A) ఒక వర్తకుడు చేర్చటానికి ఎంచుకున్న ఏదైనా ఒప్పంద నిబంధన / Any contract term that a trader chooses to include", "B) వినియోగదారితో వ్యక్తిగతంగా చర్చించిన నిబంధనలు / Terms that were negotiated individually with the consumer", "C) పక్షాల హక్కులలో గణనీయ అసమతుల్యతకు కారణమయ్యే నిబంధనలు, సద్భావనకు విరుద్ధంగా / Terms that cause significant imbalance in parties' rights, contrary to good faith", "D) ధర మరియు డెలివరీకు సంబంధించిన నిబంధనలు మాత్రమే / Only terms related to price and delivery", 'C', "సంరక్షణ చట్టం 2019 యొక్క సెక్షన్ 2(45) 'న్యాయరహిత ఒప్పంద నిబంధనలను' పక్షాల హక్కులలో గణనీయ అసమతుల్యతకు కారణమయ్యేవిగా నిర్వచిస్తుంది. చట్టం వర్తకుడుకు ఒప్పంద నిబంధనలు సరసమైనవని నిరూపించటానికి బాధ్యత ఉంచుతుంది.\nSection 2(45) of the Consumer Protection Act 2019 defines 'unfair contract terms' as those causing significant imbalance in parties' rights, contrary to good faith, thereby detrimentary to the consumer. The Act shifts the burden to traders to prove contract terms are fair.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31524, "RTI Act 2005 ప్రకారం పబ్లిక్ ఇన్‌ఫర్మేషన్ ఆఫీసర్ (PIO) సమాచారం ఇవ్వడానికి నిర్ధారిత సమయ సూచిక ఏమిటి?\nWhat is the prescribed timeline for a Public Information Officer (PIO) to provide information under the RTI Act 2005?", "A) RTI దరఖాస్తు స్వీకరించిన 10 రోజుల్లో / Within 10 days of receiving the RTI application", "B) RTI దరఖాస్తు స్వీకరించిన 30 రోజుల్లో, 20 రోజులు పొడిగించటానికి వీలుఉంది / Within 30 days of receiving the RTI application, extendable by 20 days", "C) RTI దరఖాస్తు స్వీకరించిన 60 రోజుల్లో / Within 60 days of receiving the RTI application", "D) ఎటువంటి పొడిగింపు అవకాశం లేకుండా 90 రోజుల్లో / Within 90 days without any possibility of extension", 'B', "సమాచారానికి హక్కు చట్టం 2005 యొక్క సెక్షన్ 4(1) PIO RTI దరఖాస్తు స్వీకరణ నుండి 30 రోజుల్లో సమాచారం అందించాలని నిర్దేశిస్తుంది. సెక్షన్ 4(1)(b) ఆ చట్టం 20 రోజుల వరకు పొడిగించటానికి అనుమతిస్తుంది.\nSection 4(1) of the Right to Information Act 2005 prescribes that a PIO must provide information within 30 days of receipt of RTI application. Section 4(1)(b) allows extension by 20 days in complex matters. Combined maximum is 50 days.', 'AP_HC', 'National_Current_Affairs_2026'),

    (31525, "జిల్లా వినియోగదారు కమిషన్ కీలక బాధ్యతలు ఏవి?\nWhich of the following is a key responsibility of District Consumer Commission?", "A) కేవలం ఉపసంహరణ ఫిర్యాదులను విచారించటం / Hearing withdrawal complaints only", "B) వినియోగదారు ఫిర్యాదులు విచారించటం, నిర్ణయాలను ఇవ్వటం, మరియు రాష్ట్ర కమిషన్‌ను అప్పీల్‌ల నుండి సంవత్సరం చేయటం / Hearing consumer complaints, delivering judgments, and hearing appeals from State Commission", "C) రాష్ట్ర చట్టాలను రూపకల్పనచేయటం / Framing state laws", "D) ఎన్సీడీఆర్‌సీకి సమస్త విషయాలను సమర్పించటం / Submitting all matters to NCDRC", 'B', "జిల్లా వినియోగదారు కమిషన్ కీలక బాధ్యతలు వినియోగదారు ఫిర్యాదులను విచారించటం, సంబంధిత నిర్ణయాలను ఇవ్వటం, రాష్ట్ర కమిషన్ నుండి అప్పీల్ కేసులను వింటూ ఉన్నాయి.\nThe key responsibilities of District Consumer Commission include hearing consumer complaints, delivering timely judgments (within 60 days), and hearing appeals against lower commission orders. The Commission has jurisdiction over cases valued between Rs. 1 lakh and Rs. 1 crore.", 'AP_HC', 'National_Current_Affairs_2026'),
]

# Verification
print("Total MCQs created: " + str(len(questions_31501_31525_bilingual)))
