"""baseline_15_tables

Revision ID: c68decc8a6c3
Revises: 
Create Date: 2026-05-27 06:21:59.472115+00:00
"""
from alembic import op
import sqlalchemy as sa


revision = 'c68decc8a6c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('question_ids', sa.JSON(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('confidences', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_sessions_device_id'), 'exam_sessions', ['device_id'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=False),
    sa.Column('name_te', sa.String(length=128), nullable=False),
    sa.Column('conducting_body', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('nav_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surface', sa.String(length=8), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('label_en', sa.String(length=128), nullable=False),
    sa.Column('label_te', sa.String(length=128), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('action_type', sa.String(length=32), nullable=True),
    sa.Column('action_ref', sa.String(length=256), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['nav_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nav_items_parent_id'), 'nav_items', ['parent_id'], unique=False)
    op.create_index(op.f('ix_nav_items_surface'), 'nav_items', ['surface'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('title_en', sa.String(length=256), nullable=False),
    sa.Column('title_te', sa.String(length=256), nullable=False),
    sa.Column('body_en', sa.Text(), nullable=True),
    sa.Column('body_te', sa.Text(), nullable=True),
    sa.Column('page_type', sa.String(length=32), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('passages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_en', sa.Text(), nullable=True),
    sa.Column('text_te', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=False),
    sa.Column('name_te', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('chapter_num', sa.Integer(), nullable=False),
    sa.Column('title_en', sa.String(length=256), nullable=False),
    sa.Column('title_te', sa.String(length=256), nullable=False),
    sa.Column('est_read_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'chapter_num')
    )
    op.create_index(op.f('ix_chapters_subject_id'), 'chapters', ['subject_id'], unique=False)
    op.create_table('exam_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('paper_num', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=False),
    sa.Column('name_te', sa.String(length=128), nullable=False),
    sa.Column('total_marks', sa.Integer(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'paper_num')
    )
    op.create_index(op.f('ix_exam_papers_exam_id'), 'exam_papers', ['exam_id'], unique=False)
    op.create_table('study_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('subject_ids', sa.JSON(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_plans_device_id'), 'study_plans', ['device_id'], unique=False)
    op.create_table('chapter_progress',
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_section', sa.Integer(), nullable=True),
    sa.Column('marked_complete_at', sa.DateTime(), nullable=True),
    sa.Column('last_opened_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id', 'chapter_id')
    )
    op.create_table('exam_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('section_label', sa.String(length=8), nullable=True),
    sa.Column('name_en', sa.String(length=256), nullable=False),
    sa.Column('name_te', sa.String(length=256), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['exam_papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_sections_paper_id'), 'exam_sections', ['paper_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('section_num', sa.Integer(), nullable=False),
    sa.Column('heading_en', sa.String(length=256), nullable=True),
    sa.Column('heading_te', sa.String(length=256), nullable=True),
    sa.Column('body_en', sa.Text(), nullable=True),
    sa.Column('body_te', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', 'section_num')
    )
    op.create_index(op.f('ix_notes_chapter_id'), 'notes', ['chapter_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('pyq_year', sa.String(length=8), nullable=True),
    sa.Column('pyq_paper', sa.String(length=64), nullable=True),
    sa.Column('difficulty', sa.String(length=2), nullable=True),
    sa.Column('question_en', sa.Text(), nullable=True),
    sa.Column('question_te', sa.Text(), nullable=True),
    sa.Column('options_en', sa.JSON(), nullable=True),
    sa.Column('options_te', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.String(length=1), nullable=False),
    sa.Column('explanation_en', sa.Text(), nullable=True),
    sa.Column('explanation_te', sa.Text(), nullable=True),
    sa.Column('passage_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.ForeignKeyConstraint(['passage_id'], ['passages.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_chapter_id'), 'questions', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_questions_source_type'), 'questions', ['source_type'], unique=False)
    op.create_index(op.f('ix_questions_subject_id'), 'questions', ['subject_id'], unique=False)
    op.create_table('exam_syllabus_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('weight_marks', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['exam_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'chapter_id')
    )
    op.create_index(op.f('ix_exam_syllabus_items_chapter_id'), 'exam_syllabus_items', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_exam_syllabus_items_section_id'), 'exam_syllabus_items', ['section_id'], unique=False)
    op.create_table('user_question_state',
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('seen_count', sa.Integer(), nullable=True),
    sa.Column('wrong_count', sa.Integer(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=True),
    sa.Column('saved', sa.Boolean(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_confidence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id', 'question_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_question_state')
    op.drop_index(op.f('ix_exam_syllabus_items_section_id'), table_name='exam_syllabus_items')
    op.drop_index(op.f('ix_exam_syllabus_items_chapter_id'), table_name='exam_syllabus_items')
    op.drop_table('exam_syllabus_items')
    op.drop_index(op.f('ix_questions_subject_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_source_type'), table_name='questions')
    op.drop_index(op.f('ix_questions_chapter_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_notes_chapter_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_exam_sections_paper_id'), table_name='exam_sections')
    op.drop_table('exam_sections')
    op.drop_table('chapter_progress')
    op.drop_index(op.f('ix_study_plans_device_id'), table_name='study_plans')
    op.drop_table('study_plans')
    op.drop_index(op.f('ix_exam_papers_exam_id'), table_name='exam_papers')
    op.drop_table('exam_papers')
    op.drop_index(op.f('ix_chapters_subject_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_table('subjects')
    op.drop_table('passages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_nav_items_surface'), table_name='nav_items')
    op.drop_index(op.f('ix_nav_items_parent_id'), table_name='nav_items')
    op.drop_table('nav_items')
    op.drop_table('exams')
    op.drop_index(op.f('ix_exam_sessions_device_id'), table_name='exam_sessions')
    op.drop_table('exam_sessions')
    # ### end Alembic commands ###
