"""Reviewed DRAFT mapping of the 225 AP History note sections (source chapters 1-12) to the canonical structure.

Key: (source chapter, section) -> (canonical chapter number or 'supp-...' slug, subtopic suffix or None, confidence, reason, secondaries)
* subtopic None  = mapped at chapter level (study aid, framework, or no matching subtopic).
* secondaries    = [(canonical chapter number, subtopic suffix or None), ...]
* confidence     = high | medium | low. Anything medium/low, or combining two subtopics, is also listed in the review sheet.
Headings alone were not trusted: the section text was spot-checked for every ambiguous section (see ``reason``).
Sections not listed here are generic study aids (see GENERIC_HEADINGS) and map at chapter level with high confidence.
"""
SUPP = "supp-dynasties-overview"
DEFAULT_CHAPTER = {1: 2, 2: 1, 3: 3, 4: SUPP, 5: 4, 6: 5, 7: 6, 8: 7, 9: 8, 10: 9, 11: 10, 12: 11}

GENERIC_HEADINGS = (
    "Introduction", "Introduction — Why a Three-Dynasty Chapter", "Terminology Primer", "Glossary", "Revision", "MCQs — Practice", "Practice MCQs",
    "Previous Year Question Patterns — APPSC Group 1/2", "Summary & Exam Tips", "Legacy & Chapter Summary",
)
GENERIC_REASON = "Study-aid section (introduction, glossary, revision, practice or summary) that covers the whole source chapter; mapped at chapter level."

H, M, L = "high", "medium", "low"
SPEC = {
    # ── source ch1 Prehistoric -> canonical 2 ─────────────────────────
    (1, 3): (2, None, H, "Three-age/periodisation framework spanning all prehistoric periods.", [(2, "tools-technology")]),
    (1, 4): (2, "tools-technology", M, "Movius Line contrasts Acheulian handaxe and chopper-chopping-tool traditions (technology); also a Palaeolithic topic.", [(2, "palaeolithic")]),
    (1, 5): (2, None, L, "Mixes evidence types with pioneer researchers; no single subtopic fits. Ambiguous.", [(1, "archaeological-evidence")]),
    (1, 6): (2, "palaeolithic", H, "Lower Palaeolithic / Acheulian.", []),
    (1, 7): (2, "palaeolithic", H, "Middle Palaeolithic.", []),
    (1, 8): (2, "palaeolithic", H, "Upper Palaeolithic.", []),
    (1, 9): (2, "mesolithic", H, "Mesolithic period.", []),
    (1, 10): (2, "neolithic", H, "Neolithic period and Southern Neolithic complex.", []),
    (1, 11): (2, "megalithic-iron-age", H, "Megalithic / Iron Age culture; burial types also appear here.", [(2, "burial-practices")]),
    (1, 12): (2, "important-sites", H, "District-wise prehistoric sites table.", []),
    (1, 13): (2, None, M, "Researchers of AP prehistory; no researcher subtopic exists.", []),
    (1, 14): (2, None, M, "Recent discoveries across several periods (e.g. Jwalapuram/Toba); multi-period, so chapter level.", [(2, "important-sites")]),
    # ── source ch2 Introduction and sources -> canonical 1 ────────────
    (2, 3): (1, None, H, "Classification tree of all source types; framework for the chapter.", []),
    (2, 4): (1, "literary-sources", H, "Indian literary sources.", []),
    (2, 5): (1, "foreign-accounts", H, "Foreign accounts (Greek, Roman, Chinese).", []),
    (2, 6): (1, "archaeological-evidence", H, "Overview of archaeological sources.", []),
    (2, 7): (1, "inscriptions", H, "Epigraphy.", []),
    (2, 8): (1, "coins", H, "Numismatics.", []),
    (2, 9): (1, "archaeological-evidence", M, "Monuments and sculpture as physical evidence.", [(1, "important-sites")]),
    (2, 10): (1, "people-name-origin", H, "Name and origin of the Andhras: five theories.", []),
    (2, 11): (1, "people-name-origin", M, "Chronological list of earliest references to Andhras; overlaps Chapter 3 'Early Andhra references'. Ambiguous.", [(3, "early-andhra-references")]),
    (2, 12): (1, "telugu-identity-language", H, "Origin of Telugu / Andhra language.", []),
    (2, 13): (1, "people-name-origin", L, "Pre-Aryan tribal background (Andhra, Pundra, Shabara); ancient ethnography, not Chapter 26's modern tribal culture. Ambiguous.", []),
    (2, 14): (1, "important-sites", H, "District-wise historical-source sites.", []),
    (2, 15): (1, "archaeological-evidence", M, "Recent excavations and discoveries 2018-2026.", [(1, "important-sites")]),
    # ── source ch3 Pre-Satavahana -> canonical 3 ──────────────────────
    (3, 3): (3, None, H, "Chronological framework for the whole chapter.", []),
    (3, 4): (3, "early-andhra-references", H, "Andhra identity in early literature.", [(1, "people-name-origin")]),
    (3, 5): (3, None, M, "Sources for the period; overlaps Chapter 1 sources.", [(1, "literary-sources"), (1, "inscriptions")]),
    (3, 6): (3, "assaka-asmaka", H, "Assaka Mahajanapada.", []),
    (3, 7): (3, "assaka-asmaka", M, "Mulaka is paired with Assaka in the sources; no separate subtopic. Propose adding one. Ambiguous.", []),
    (3, 8): (3, "nandas-mauryas", H, "Mauryan rule in Andhra; Ashokan edicts are covered here.", [(3, "ashoka-inscriptions"), (3, "erragudi-rajulamandagiri")]),
    (3, 9): (3, "early-andhra-references", M, "Megasthenes' Indica on the Andhras; also a foreign account.", [(1, "foreign-accounts")]),
    (3, 10): (3, "bhattiprolu", H, "Bhattiprolu / Kuberaka kingdom.", [(3, "early-local-rulers")]),
    (3, 11): (3, "early-local-rulers", M, "Post-Mauryan transition, c. 232-200 BCE.", [(3, "nandas-mauryas")]),
    (3, 12): (3, "early-buddhism", H, "Early Buddhist sites in Andhra.", [(3, "amaravati-dhanyakataka-beginnings")]),
    (3, 13): (3, None, M, "Society, economy and religion together; no matching subtopic.", []),
    (3, 14): (3, None, H, "District-wise pre-Satavahana sites.", [(1, "important-sites")]),
    (3, 15): (3, None, M, "Historical figures and researchers.", []),
    # ── source ch4 Dynasties overview -> supplementary reference ──────
    (4, 2): (SUPP, None, H, "Master table of all dynasties; cross-cutting reference.", []),
    (4, 3): (SUPP, None, H, "Master chronology diagram.", []),
    (4, 4): (SUPP, None, H, "Dynasty succession tree.", []),
    (4, 5): (SUPP, None, H, "Capital cities map; some capitals lie outside present AP.", []),
    (4, 6): (SUPP, None, H, "Greatest king of each dynasty.", []),
    (4, 7): (SUPP, None, H, "'Firsts' in Andhra history.", []),
    (4, 8): (SUPP, None, M, "Religious patronage by dynasty across all periods; only part falls in 11th-16th c.", [(14, "religious-movements")]),
    (4, 9): (SUPP, None, M, "Telugu literature growth timeline across periods.", [(1, "telugu-identity-language"), (14, "growth-of-telugu")]),
    (4, 10): (SUPP, None, H, "King mnemonics.", []),
    (4, 11): (SUPP, None, M, "Key inscriptions reference across dynasties.", [(1, "inscriptions")]),
    (4, 12): (SUPP, None, H, "Complete king lists.", []),
    # ── source ch5 Satavahanas -> canonical 4 ─────────────────────────
    (5, 3): (4, "chronology", H, "Satavahana chronology.", []),
    (5, 4): (4, "origin-homeland", H, "Origin debate.", []),
    (5, 5): (4, "political-history", M, "The capital debate (Pratishthana / Dhanyakataka); no capital subtopic. Ambiguous.", [(4, "origin-homeland")]),
    (5, 6): (4, None, M, "Sources of Satavahana history (literary, inscriptions, coins).", [(4, "inscriptions"), (4, "coinage")]),
    (5, 7): (4, "political-history", H, "Foundation phase under the early Satavahanas.", [(4, "important-rulers")]),
    (5, 8): (4, "important-rulers", H, "Other notable kings.", []),
    (5, 9): (4, "important-rulers", H, "Gautamiputra Satakarni.", [(4, "political-history")]),
    (5, 10): (4, "inscriptions", H, "Key Satavahana inscriptions.", []),
    (5, 11): (4, "political-history", H, "Territorial extent of the empire.", []),
    (5, 12): (4, "coinage", H, "Satavahana coinage.", []),
    (5, 13): (4, "society", M, "Society and economy in one section; should be split at content level. Ambiguous.", [(4, "economy-trade")]),
    (5, 14): (4, "religion", H, "Religion under the Satavahanas.", []),
    (5, 15): (4, "art-architecture", M, "Art and literature in one section; should be split. Ambiguous.", [(4, "literature")]),
    (5, 16): (4, None, H, "District-wise Satavahana sites.", [(1, "important-sites")]),
    (5, 17): (4, None, M, "Key figures and researchers.", []),
    # ── source ch6 Ikshvakus -> canonical 5 ───────────────────────────
    (6, 3): (5, "origin-chronology", H, "Origins; Suryavamsha claim.", []),
    (6, 4): (5, "vijayapuri-nagarjunakonda", H, "Capital Vijayapuri.", []),
    (6, 5): (5, None, M, "Historical sources of the Ikshvakus.", [(5, "inscriptions")]),
    (6, 6): (5, "important-rulers", H, "The four kings.", []),
    (6, 7): (5, "important-rulers", H, "Founder, Chamtamula I.", [(5, "origin-chronology")]),
    (6, 8): (5, "important-rulers", H, "Greatest king, Virapurushadatta.", []),
    (6, 9): (5, "important-rulers", H, "Ehuvula Chamtamula II, temple builder.", [(5, "brahmanism")]),
    (6, 10): (5, "important-rulers", H, "Last king, Rudrapurushadatta.", [(5, "decline")]),
    (6, 11): (5, "inscriptions", H, "Ikshvaku inscriptions.", []),
    (6, 12): (5, "royal-women", H, "Queens as Buddhist patrons.", [(5, "buddhism")]),
    (6, 13): (5, "administration", H, "Administration.", []),
    (6, 14): (5, "socio-economic-conditions", H, "Society and economy.", []),
    (6, 15): (5, "buddhism", M, "Dual Buddhist/Brahmanical religious structure in one section. Ambiguous.", [(5, "brahmanism")]),
    (6, 16): (5, "vijayapuri-nagarjunakonda", H, "Vijayapuri city plan.", []),
    (6, 17): (5, "art-architecture", M, "The Great Stupa (Mahachaitya) at Nagarjunakonda.", [(5, "vijayapuri-nagarjunakonda"), (5, "buddhism")]),
    (6, 18): (5, "art-architecture", H, "Ikshvaku art, 'Later Amaravati' style.", []),
    (6, 19): (5, None, H, "Ikshvaku sites in AP.", [(1, "important-sites")]),
    (6, 20): (5, "decline", H, "Decline and successors.", []),
    # ── source ch7 Minor dynasties -> canonical 6 ─────────────────────
    (7, 3): (6, None, H, "Comparative overview of the three dynasties.", []),
    (7, 4): (6, "brihatphalayanas", H, "Brihatphalayanas.", []),
    (7, 5): (6, "ananda-gotrikas", H, "Anandagotras.", []),
    (7, 6): (6, "art-architecture", M, "Chejarla Kapoteshvara apsidal temple, discussed under the Ananda Gotra.", [(6, "ananda-gotrikas")]),
    (7, 7): (6, "salankayanas", H, "Salankayanas: introduction and founder.", []),
    (7, 8): (6, "salankayanas", H, "Hastivarman and Samudragupta's southern campaign (Allahabad pillar).", [(6, "political-conditions")]),
    (7, 9): (6, "salankayanas", H, "Later Salankayana kings.", []),
    (7, 10): (6, "salankayanas", M, "Vengi (Pedavegi) as Salankayana capital; name overlaps the Eastern Chalukya Vengi of Chapter 8.", [(8, "vengi-foundation")]),
    (7, 11): (6, "religion", H, "Salankayana religion, Shaiva to Vaishnava.", []),
    (7, 12): (6, "religion", M, "Bull seal and tutelary deity Chitrarathasvamin; religion and emblem together.", [(6, "salankayanas")]),
    (7, 13): (6, "inscriptions", M, "Prakrit-to-Sanskrit language shift traced through copper plates.", [(7, "sanskrit-telugu-development")]),
    (7, 14): (6, "religion", H, "Buddhism to Brahmanism transformation.", []),
    (7, 15): (6, None, H, "Sites map of the three dynasties.", [(1, "important-sites")]),
    (7, 16): (6, "political-conditions", M, "Bridge to the Vishnukundins: fate of each dynasty.", [(7, "origin-chronology")]),
    # ── source ch8 Vishnukundins -> canonical 7 ───────────────────────
    (8, 3): (7, "origin-chronology", H, "Origin and name.", []),
    (8, 4): (7, "political-expansion", M, "Four capitals; no capitals subtopic. Ambiguous.", [(7, "origin-chronology")]),
    (8, 5): (7, None, M, "Historical sources.", [(7, "inscriptions")]),
    (8, 6): (7, "origin-chronology", H, "Dynasty chronology.", []),
    (8, 7): (7, "important-rulers", H, "Early kings Madhavavarman I and Govindavarman I.", []),
    (8, 8): (7, "important-rulers", H, "Madhavavarman II, eleven Ashvamedhas.", [(7, "political-expansion")]),
    (8, 9): (7, "political-expansion", M, "Vakataka marriage alliance.", [(7, "important-rulers")]),
    (8, 10): (7, "important-rulers", H, "Later kings.", []),
    (8, 11): (7, "religion", H, "Religion.", []),
    (8, 12): (7, "inscriptions", H, "Tummalagudem plates.", []),
    (8, 13): (7, "inscriptions", H, "Chikkulla and Polamuru plates.", []),
    (8, 14): (7, "cave-temple-architecture", H, "Undavalli caves.", []),
    (8, 15): (7, "cave-temple-architecture", H, "Mogalrajapuram and Bhairavakonda caves.", []),
    (8, 16): (7, "sanskrit-telugu-development", H, "Literature; Janashrayi Chandovichiti.", []),
    (8, 17): (7, "coins", H, "Coinage and lion emblem.", []),
    (8, 18): (7, None, H, "Vishnukundin sites in AP.", [(1, "important-sites")]),
    (8, 19): (7, "decline", H, "Chalukya conquest and decline.", []),
    (8, 20): (7, "decline", M, "Bridge to the Eastern Chalukyas.", [(8, "vengi-foundation")]),
    # ── source ch9 Eastern Chalukyas -> canonical 8 ───────────────────
    (9, 3): (8, "vengi-foundation", H, "Founding of the dynasty; why 624.", []),
    (9, 4): (8, "vengi-foundation", M, "Three capitals; no capitals subtopic.", []),
    (9, 5): (8, None, M, "Historical sources.", [(8, "inscriptions")]),
    (9, 6): (8, "political-chronology", H, "30 kings over 500 years.", []),
    (9, 7): (8, "important-rulers", H, "Kubja Vishnuvardhana.", [(8, "vengi-foundation")]),
    (9, 8): (8, "important-rulers", H, "Vijayaditya II.", []),
    (9, 9): (8, "important-rulers", H, "Gunaga Vijayaditya III.", []),
    (9, 10): (8, "important-rulers", H, "Chalukya Bhima I, Pancharama builder.", [(8, "temples-pancharamas")]),
    (9, 11): (8, "important-rulers", H, "Amma II.", []),
    (9, 12): (8, "important-rulers", H, "Vimaladitya, Jain patron.", [(8, "religion")]),
    (9, 13): (8, "important-rulers", H, "Rajaraja Narendra.", [(8, "telugu-nannaya-literature")]),
    (9, 14): (8, "telugu-nannaya-literature", H, "Nannaya and the Andhra Mahabharatam.", [(1, "telugu-identity-language")]),
    (9, 15): (8, "temples-pancharamas", H, "Pancharama kshetras.", []),
    (9, 16): (8, "temples-pancharamas", M, "General art and architecture; the chapter has no general art subtopic. Propose adding one.", []),
    (9, 17): (8, "religion", M, "Religion and administration in one section. Ambiguous.", [(8, "administration")]),
    (9, 18): (8, None, H, "Eastern Chalukya sites.", [(1, "important-sites")]),
    (9, 19): (8, "chola-chalukya-relations", H, "Kulottunga I and the Chola merger.", []),
    (9, 20): (8, "decline-transition", H, "End of the dynasty; Velanati Chodas rise in the last phase.", [(8, "velanati-chodas")]),
    # ── source ch10 Kakatiyas -> canonical 9 ──────────────────────────
    (10, 3): (9, "origin-early-rulers", H, "Origins and founding.", []),
    (10, 4): (9, "political-expansion", M, "Three capitals; no capitals subtopic.", []),
    (10, 5): (9, None, M, "Historical sources.", []),
    (10, 6): (9, None, H, "Table of the five sovereigns; whole-dynasty overview.", []),
    (10, 7): (9, "rudradeva", H, "Rudradeva (Prataparudra I).", []),
    (10, 8): (9, "mahadeva", H, "Mahadeva.", []),
    (10, 9): (9, "ganapatideva", H, "Ganapati Deva.", []),
    (10, 10): (9, "rudramadevi", H, "Rudrama Devi.", []),
    (10, 11): (9, "prataparudra", H, "Prataparudra II.", [(9, "delhi-sultanate-invasions")]),
    (10, 12): (9, "art-architecture", H, "Thousand Pillar Temple.", []),
    (10, 13): (9, "art-architecture", H, "Warangal Fort and Kakatiya Thoranam.", []),
    (10, 14): (9, "art-architecture", H, "Ramappa temple.", []),
    (10, 15): (9, "telugu-literature", M, "Literature and arts together. Ambiguous.", [(9, "dance-music"), (9, "art-architecture")]),
    (10, 16): (9, "administration-nayankara", H, "Nayankara system and administration.", []),
    (10, 17): (9, "crafts-trade-motupalli", H, "Economy and Motupalli Abhayasasana.", [(9, "irrigation-agriculture")]),
    (10, 18): (9, "religion", M, "Religion and social history together. Ambiguous.", [(9, "society")]),
    (10, 19): (9, None, H, "Kakatiya sites in AP.", []),
    (10, 20): (9, "delhi-sultanate-invasions", H, "The five sieges, 1303-1323.", [(9, "decline")]),
    # ── source ch11 Reddys, Musunuris -> canonical 10 ─────────────────
    (11, 3): (10, "post-kakatiya-conditions", H, "Post-Kakatiya vacuum, 1323-1336.", []),
    (11, 4): (10, None, H, "Comparison of the three successor dynasties.", []),
    (11, 5): (10, None, M, "Historical sources.", []),
    (11, 6): (10, "musunuri-nayakas", H, "Musunuri Nayakas overview.", []),
    (11, 7): (10, "musunuri-nayakas", H, "Prolaya and Kapaya Nayaka.", []),
    (11, 8): (10, "kondavidu-reddys", H, "Kondaveedu Reddi overview.", []),
    (11, 9): (10, "kondavidu-reddys", H, "Prolaya Vema Reddi.", []),
    (11, 10): (10, "kondavidu-reddys", H, "Anavema, Komati Vema and Pedakomati Vema.", []),
    (11, 11): (10, "rajahmundry-reddys", H, "Rajamahendravaram Reddi branch.", []),
    (11, 12): (10, "rajahmundry-reddys", M, "Placed under Rajamahendravaram as the section title states; the Kondavidu-vs-Rajahmundry attribution of Kataya Vema should be checked in review.", []),
    (11, 13): (10, "recharla-velamas", H, "Recharla Velamas of Rachakonda and Devarakonda.", []),
    (11, 14): (10, "telugu-literature", H, "Srinatha.", [(14, "authors-works")]),
    (11, 15): (10, "telugu-literature", H, "Other literary figures.", [(14, "authors-works")]),
    (11, 16): (10, "art-architecture", H, "Forts and monuments.", [(14, "forts")]),
    (11, 17): (10, "administration", M, "Administration and economy together. Ambiguous.", [(10, "society-economy")]),
    (11, 18): (10, "religion", M, "Religion and social history together. Ambiguous.", [(10, "society-economy")]),
    (11, 19): (10, None, H, "Sites in AP.", []),
    (11, 20): (10, "regional-conflicts", M, "Decline through Vijayanagara and Gajapati conquests.", [(12, "gajapati-rule-influence")]),
    # ── source ch12 Vijayanagara -> canonical 11 ──────────────────────
    (12, 3): (11, "foundation", H, "Foundation and the Vidyaranya debate.", []),
    (12, 4): (11, "four-dynasties", H, "Four dynasties overview.", []),
    (12, 5): (11, None, M, "Historical sources.", []),
    (12, 6): (11, "four-dynasties", M, "The Sangama dynasty.", [(11, "important-rulers")]),
    (12, 7): (11, "important-rulers", H, "Devaraya I and II.", []),
    (12, 8): (11, "four-dynasties", H, "Saluva and Tuluva transitions.", [(11, "important-rulers")]),
    (12, 9): (11, "krishnadevaraya", H, "Krishnadevaraya as emperor.", []),
    (12, 10): (11, "andhra-campaigns-gajapati-bahmani", H, "Krishnadevaraya's campaigns.", [(11, "krishnadevaraya"), (12, "gajapati-rule-influence")]),
    (12, 11): (11, "telugu-literature-ashtadiggajas", H, "Amuktamalyada and the Ashtadiggajas.", [(14, "authors-works")]),
    (12, 12): (11, "important-rulers", H, "Achyutadevaraya, Sadashiva and Aliya Ramaraya.", [(11, "four-dynasties")]),
    (12, 13): (11, "battle-of-talikota", H, "Battle of Talikota, 1565.", []),
    (12, 14): (11, "decline", M, "Aravidu dynasty and AP-located capitals after 1565.", [(11, "four-dynasties")]),
    (12, 15): (11, "art-architecture", H, "Hampi monuments.", []),
    (12, 16): (11, "administration-nayankara", M, "Administration and economy together. Ambiguous.", [(11, "economy-trade")]),
    (12, 17): (11, "religion", H, "Religion and the Wagoner 'Hindu Sultanate' thesis.", []),
    (12, 18): (11, "telugu-literature-ashtadiggajas", M, "Literature and arts together. Ambiguous.", [(11, "art-architecture")]),
    (12, 19): (11, None, H, "Vijayanagara sites in AP.", []),
    (12, 20): (11, "decline", H, "Decline and successor states.", []),
}
