"""Reviewer findings for the DRAFT subtopic taxonomy. Keyed by (chapter number, subtopic slug suffix). Data only.

Flag vocabulary (a subtopic may carry several, separated by ';'):
  overlap          overlaps another subtopic (the partner is named in the note)
  duplicate        the same concept under a different name; one should be dropped or merged
  narrow           a single person/event/paper that is better as a tag or as part of a broader subtopic
  note_driven      exists mainly because one current note heading needs a home
  no_source        no note section in the current source maps here (gap in the notes, or a subtopic that is not needed)
  telugu_review    the Telugu wording needs a reviewer decision (evidence in TELUGU_ISSUES)
  by_design        overlap is deliberate (thematic chapter 14, or the one-primary-chapter rule)
"""
FINDINGS = {
    (21, "drama-organisations"): ("duplicate;overlap", "Same concept as `nataka-samasthalu` in this chapter (drama societies). Keep one."),
    (21, "nataka-samasthalu"): ("duplicate;overlap", "Same concept as `drama-organisations`; the Telugu term Nataka Samajalu is the one used in the notes."),
    (21, "praja-natya-mandali"): ("narrow", "One organisation; consider folding into a broader 'People's theatre and IPTA-style groups' subtopic. Maa Bhoomi is a play, not a topic."),
    (21, "maa-bhoomi"): ("narrow", "A single play; better as a tag under people's theatre."),
    (27, "potti-sriramulu"): ("duplicate;overlap", "Overlaps `fast-and-death` (his fast and death are the event). Keep either a person subtopic or the event."),
    (27, "fast-and-death"): ("duplicate;overlap", "See `potti-sriramulu`."),
    (27, "swami-sitaram"): ("narrow", "One person. Candidate to merge into a 'Leaders of the Andhra State agitation' subtopic."),
    (27, "tanguturi-prakasam"): ("narrow;note_driven", "One person; maps one note section."),
    (17, "womens-reform"): ("overlap", "Overlaps ch22 `women-reformers`. Chapter 17 should hold reform as a social movement; ch22 women's participation in the freedom struggle."),
    (22, "women-reformers"): ("overlap", "Overlaps ch17 `womens-reform`."),
    (17, "veeresalingam"): ("narrow", "One person; could be one subtopic 'Major reformers' covering Veeresalingam, Raghupati Venkataratnam Naidu, Gurajada."),
    (17, "raghupati-venkataratnam-naidu"): ("narrow", "See `veeresalingam`."),
    (17, "gurajada-apparao"): ("narrow", "See `veeresalingam`."),
    (23, "major-resolutions"): ("duplicate;overlap", "Same concept as ch24 `resolutions` (Andhra Mahasabha resolutions). Decide which chapter owns resolutions."),
    (24, "resolutions"): ("duplicate;overlap", "See ch23 `major-resolutions`."),
    (23, "important-conferences"): ("overlap", "Overlaps ch24 `origin-sessions` (the Mahasabha sessions are the conferences)."),
    (24, "origin-sessions"): ("overlap", "See ch23 `important-conferences`."),
    (15, "revenue-systems"): ("overlap", "Overlaps ch16 `zamindari-ryotwari` and `administrative-economic-effects`."),
    (16, "zamindari-ryotwari"): ("overlap", "Overlaps ch15 `revenue-systems`. Suggest ch15 = Company-era revenue, ch16 = permanent settlement and ryotwari."),
    (16, "thomas-munro"): ("narrow", "One person; ryotwari is already a subtopic."),
    (16, "arthur-cotton"): ("narrow", "One person; irrigation works would be the broader subtopic."),
    (25, "krishna-patrika"): ("narrow", "One newspaper; `andhra-patrika` and `other-newspapers` sit beside it. Consider 'Major Telugu newspapers'."),
    (25, "andhra-patrika"): ("narrow", "See `krishna-patrika`."),
    (25, "ayyanki-venkata-ramanayya"): ("narrow", "One person; overlaps `andhra-desa-library-association` and `library-movement`."),
    (25, "andhra-desa-library-association"): ("overlap", "Overlaps `library-movement` and `libraries-public-awakening`."),
    (25, "libraries-public-awakening"): ("overlap;duplicate", "Three library subtopics in one chapter (library-movement, andhra-desa-library-association, libraries-public-awakening)."),
    (26, "harikatha"): ("narrow", "One art form; fine as a tag, consider a single 'Folk performing arts' subtopic."),
    (26, "burrakatha"): ("narrow", "See `harikatha`."),
    (26, "tholu-bommalata"): ("narrow", "See `harikatha`."),
    (26, "folk-traditions"): ("overlap", "Overlaps the three art-form subtopics and `regional-dance-performance`."),
    (30, "negotiations"): ("overlap", "Negotiations, signatories and provisions are aspects of one document."),
    (30, "signatories"): ("overlap;narrow", "Aspect of the agreement; consider a tag."),
    (30, "provisions"): ("overlap", "See `negotiations`."),
    (30, "regional-safeguards"): ("overlap", "Overlaps `provisions` (the safeguards are the provisions)."),
    (28, "andhra-telangana-merger-debate"): ("overlap", "Overlaps ch29 `conditions-for-merger` and ch30 `merger-process`."),
    (29, "conditions-for-merger"): ("overlap", "See ch28 `andhra-telangana-merger-debate`."),
    (30, "merger-process"): ("overlap", "See ch28 `andhra-telangana-merger-debate`."),
    (31, "regional-identity-movements"): ("overlap", "Overlaps `telangana-movement-1969` and `jai-andhra-1972`, which are subsets."),
    (31, "telangana-movement-1969"): ("overlap", "Subset of `regional-identity-movements`; fine if that one is made generic."),
    (31, "jai-andhra-1972"): ("overlap", "See `telangana-movement-1969`."),
    (31, "cultural-developments-to-2014"): ("overlap;note_driven", "Catch-all that overlaps literature, theatre, cinema, visual-performing-arts."),
    (31, "theatre"): ("overlap", "Overlaps ch21 `drama-organisations` for the pre-1956 period; the date boundary needs a rule."),
    (20, "kisan-sabhas"): ("overlap", "Overlaps `peasant-organisation`."),
    (20, "regional-agrarian-struggles"): ("overlap", "Overlaps `anti-zamindari-struggles`."),
    (22, "swadeshi-home-rule"): ("overlap", "Overlaps ch19 `swadeshi-vandemataram` and `home-rule`; by design, women's angle only."),
    (22, "gandhian-movements"): ("overlap", "Overlaps ch19 non-cooperation, civil-disobedience, quit-india; by design, women's angle only."),
    (19, "chirala-perala-pedanandipadu"): ("narrow", "One local episode; keep as a tag or as part of non-cooperation/civil disobedience."),
    (19, "prominent-leaders"): ("overlap", "Overlaps ch18 `important-leaders`; and ch25/ch27 person subtopics."),
    (18, "important-leaders"): ("overlap", "See ch19 `prominent-leaders`."),
    (14, "comparative-administration"): ("by_design", "Thematic chapter: overlaps chapters 8-13 by design. Questions get one primary chapter (the dynasty chapter) unless the question is genuinely comparative."),
    (14, "social-structure"): ("by_design", "See `comparative-administration`."),
    (14, "economic-conditions"): ("by_design;overlap", "Overlaps `agriculture-irrigation` and `trade` in the same chapter."),
    (14, "agriculture-irrigation"): ("by_design", "See `comparative-administration`."),
    (14, "trade"): ("by_design", "See `comparative-administration`."),
    (14, "religious-movements"): ("by_design", "See `comparative-administration`."),
    (14, "growth-of-telugu"): ("by_design", "See `comparative-administration`."),
    (14, "authors-works"): ("by_design", "See `comparative-administration`."),
    (14, "sculpture"): ("by_design;overlap", "Overlaps `temple-architecture` and the art-architecture subtopics of chapters 8-13."),
    (14, "temple-architecture"): ("by_design", "See `sculpture`."),
    (14, "forts"): ("by_design", "See `comparative-administration`."),
    (14, "music-dance"): ("by_design", "See `comparative-administration`."),
    (6, "pallava-influence"): ("no_source", "No note section maps here; fine if the source is thin."),
    (6, "other-transitional-dynasties"): ("no_source;overlap", "Catch-all; overlaps `political-conditions`."),
    (6, "society-economy"): ("no_source", ""),
    (2, "chalcolithic"): ("no_source;telugu_review", "No note section; the topic is a standard exam item."),
    (2, "pottery"): ("no_source;overlap", "Overlaps `tools-technology` and `burial-practices` (megalithic pottery)."),
    (3, "kharavela-hathigumpha"): ("no_source;telugu_review", "A standard exam item with no note section."),
    (3, "punch-marked-local-coinage"): ("no_source;overlap", "Overlaps ch1 `coins` and ch4 `coinage`."),
    (3, "amaravati-dhanyakataka-beginnings"): ("overlap;narrow", "Overlaps ch4 satavahana art and the Amaravati subtopics."),
    (3, "erragudi-rajulamandagiri"): ("narrow", "Two sites; overlaps `ashoka-inscriptions`."),
    (3, "ashoka-inscriptions"): ("overlap", "See `erragudi-rajulamandagiri`."),
    (5, "royal-women"): ("narrow;note_driven", "Maps one note section."),
    (5, "buddhism"): ("overlap", "Overlaps `vijayapuri-nagarjunakonda`, which is itself a Buddhist centre."),
    (7, "sanskrit-telugu-development"): ("note_driven;telugu_review", "One note section."),
    (7, "cave-temple-architecture"): ("overlap", "Overlaps the chapter-level art-and-architecture pattern used elsewhere; keep or rename for consistency."),
    (8, "chola-chalukya-relations"): ("note_driven", "One note section."),
    (8, "temples-pancharamas"): ("narrow;overlap", "Narrow; the broader `art-architecture` subtopic was added for the rest."),
    (8, "art-architecture"): ("overlap", "NEW since phase 1: broad material (Eastern Chalukya temples, sculpture, painting) had only the narrow Pancharamas home."),
    (8, "important-rulers"): ("overlap", "Seven sections map here; `political-chronology` and `vengi-foundation` cover the same ground."),
    (8, "velanati-chodas"): ("no_source", "Candidates for the Telugu Choda and Palnadu gaps are in chapter 8's unmapped list."),
    (8, "nellore-telugu-chodas"): ("no_source", ""),
    (8, "palnadu-war"): ("no_source;narrow", "One episode."),
    (9, "origin-early-rulers"): ("overlap", "Overlaps the per-ruler subtopics."),
    (9, "rudradeva"): ("narrow", "Per-ruler subtopics: six rulers in one chapter. Consider 'Early rulers' + 'Ganapatideva' + 'Rudramadevi' + 'Prataparudra'."),
    (9, "mahadeva"): ("narrow", "See `rudradeva`."),
    (9, "ganapatideva"): ("narrow", "Major ruler; keep if exams ask per-ruler."),
    (9, "rudramadevi"): ("narrow", "Major ruler; keep."),
    (9, "prataparudra"): ("narrow", "See `rudradeva`."),
    (9, "political-expansion"): ("overlap", "Overlaps the ruler subtopics."),
    (9, "crafts-trade-motupalli"): ("note_driven", "Motupalli is the note heading; the subtopic is broader in intent."),
    (11, "andhra-campaigns-gajapati-bahmani"): ("note_driven;overlap", "Overlaps ch12 subtopics."),
    (11, "four-dynasties"): ("overlap", "Overlaps `important-rulers`."),
    (11, "telugu-literature-ashtadiggajas"): ("narrow", "One literary group; broader `telugu-literature` would hold it."),
    (11, "battle-of-talikota"): ("overlap", "Overlaps `decline`."),
    (10, "kondavidu-reddys"): ("overlap", "Three Reddy-family subtopics; `rajahmundry-reddys` is where Kataya Vema (unapproved) is placed."),
    (10, "regional-conflicts"): ("overlap", "Overlaps the dynasty subtopics and ch12."),
    (12, "gajapati-rule-influence"): ("overlap", "Overlaps ch11 `andhra-campaigns-gajapati-bahmani`."),
    (12, "bahmani-vijayanagara-rivalry"): ("overlap", "Overlaps ch11 (same rivalry from the other side)."),
    (12, "coastal-andhra-conflicts"): ("no_source", ""),
    (12, "minor-regional-powers"): ("no_source", ""),
    (12, "forts-political-centres"): ("no_source", ""),
    (12, "socio-cultural-influence"): ("no_source", ""),
    (12, "political-transition"): ("no_source", ""),
    (13, "expansion-into-andhra"): ("no_source;overlap", "Overlaps `establishment` and `sixteenth-century-rulers`."),
    (1, "geography-extent"): ("no_source", "No note section maps as primary."),
    (1, "important-sites"): ("overlap", "Used as a secondary for 8 sections: a candidate for a tag rather than a subtopic."),
    (1, "coins"): ("overlap", "Overlaps ch3 `punch-marked-local-coinage`, ch4 `coinage`, ch7 `coins`; chapter-level coin subtopics repeat per dynasty."),
    (1, "inscriptions"): ("overlap", "Same pattern: `inscriptions` repeats in chapters 4-7 and 8 (as a gap)."),
    (15, "portuguese"): ("no_source;narrow", "Four per-nation subtopics; none has a note section yet."),
    (15, "dutch"): ("no_source;narrow", "See `portuguese`."),
    (15, "english"): ("no_source;narrow", "See `portuguese`. Consider one subtopic 'Portuguese, Dutch and French' plus 'English'."),
    (15, "french"): ("no_source;narrow", "See `portuguese`."),
    (28, "linguistic-political-arguments"): ("overlap", "Overlaps ch23 `linguistic-identity-roots`."),
    (29, "arguments-separate-telangana"): ("no_source;overlap", "Overlaps `andhra-telangana-evidence`."),
    (31, "official-language-telugu"): ("overlap", "Overlaps `literature` and `education-universities`."),
    (31, "womens-movements"): ("overlap", "Overlaps ch22 for the earlier period; the date boundary needs a rule."),
}

# Telugu terms: (subtopic chapter, slug suffix, current Telugu, issue, suggestion for the reviewer). Evidence counts are from the
# app notes (chapters 1-12) and the local HTML chapters 13-19 (see variants in the review file).
TELUGU_ISSUES = [
    (2, "palaeolithic", "పురా శిలాయుగం", "The notes use 'దిగువ శిలాయుగం' (10 times), 'పాషాణయుగం' (1); 'పురా శిలాయుగం' appears 0 times. Pick one term for the Palaeolithic and apply it to Mesolithic/Neolithic/Chalcolithic too.", "Decide: దిగువ/మధ్య/ఎగువ శిలాయుగం, or పాత రాతి యుగం."),
    (2, "chalcolithic", "తామ్ర శిలాయుగం", "0 occurrences of this form or 'తామ్ర యుగం' or 'చాల్కోలిథిక్' in the notes; term to be confirmed.", "Reviewer to choose."),
    (2, "megalithic-iron-age", "మహాశిలా (మెగాలిథిక్) మరియు ఇనుప యుగ సంస్కృతులు", "The notes use 'మెగాలిథిక్' (72) not 'మహాశిలా' (0); 'బృహత్శిలా' 2.", "Prefer the form learners see in the notes."),
    (3, "kharavela-hathigumpha", "ఖారవేలుడు మరియు హాథీగుంఫా శాసనం", "Notes spell 'హాతిగుంఫా' (8) and 'ఖారవేల' (11) / 'ఖారవేలుడు' (9); the subtopic uses 'హాథీగుంఫా' (0).", "Use 'హాతిగుంఫా' if the notes are the standard."),
    (3, "punch-marked-local-coinage", "ఆహత (పంచ్-మార్క్డ్) మరియు స్థానిక నాణేలు", "'ఆహత' is a rare form (0 in notes); notes use 'పంచ్‌మార్క్' (7) / 'పంచ్-మార్క్డ్' (4).", "Drop the 'ఆహత' gloss or keep both."),
    (8, "temples-pancharamas", "దేవాలయాలు మరియు పంచారామాలు", "Consistent ('పంచారామ' 50). No issue.", ""),
    (9, "administration-nayankara", "పరిపాలన మరియు నాయంకర వ్యవస్థ", "'నాయంకర' 79 vs 'నాయకత్వ' 58 (the latter is a different word, not a variant).", "No change; keep 'నాయంకర'."),
    (10, "musunuri-nayakas", "ముసునూరి ప్రోలయ నాయకుడు, కాపయ నాయకుడు మరియు ఓరుగల్లు విముక్తి", "Notes spell Musunuri three ways: 'మూసూరి' 42, 'మునుసూరి' 23, 'ముసునూరి' 16. The subtopic uses the spelling in the minority.", "Choose one spelling for the whole bank; 'ముసునూరి' is the established Telugu spelling but the notes disagree."),
    (11, "battle-of-talikota", "తళ్ళికోట యుద్ధం", "Notes use 'తాలికోట' 40, 'తాళికోట' 38, 'తళ్ళికోట' 8. The subtopic uses the rarest form.", "Choose one; 'తళ్ళికోట' is common in Telugu textbooks but the notes use others."),
    (13, "establishment", "కుతుబ్‌షాహీ అధికార స్థాపన", "Notes: 'కుతుబ్ షాహీ' 77, 'కుతుబ్షాహీ' 11, 'కుతుబ్ షాహి' 2. The subtopic uses a zero-width joiner form.", "Use 'కుతుబ్ షాహీ' with a space; avoid ZWJ in slugs/search."),
    (13, "telugu-dakhni-patronage", "తెలుగు మరియు దక్కనీ భాషల పోషణ", "Notes: 'డఖ్ఖనీ' 14, 'దక్కనీ' 7, 'దక్కని' 3.", "Choose one."),
    (15, "northern-circars", "ఉత్తర సర్కారులు", "Notes: 'ఉత్తర సర్కార్' 32, 'ఉత్తర సర్కార్లు' 16, 'ఉత్తర సర్కారులు' 1.", "Use 'ఉత్తర సర్కార్లు'."),
    (15, "ceded-districts", "దత్త మండలాలు", "Notes use 'సీడెడ్' 34 / 'సీడెడ్ డిస్ట్రిక్ట్స్' 27 and 'దత్త మండలాలు' 0-1.", "Use the learner-facing 'రాయలసీమ (దత్త మండలాలు)' or the notes' term."),
    (16, "zamindari-ryotwari", None, "Notes: 'రయొత్వారీ' 23, 'రైత్వారీ' 2, 'రయత్వారీ' 1.", "Use 'రయత్వారీ' or 'రైత్వారీ' consistently."),
    (23, "sri-bagh-pact", "శ్రీబాగ్ ఒడంబడిక", "Notes use 'శ్రీబాగ్ ఒప్పందం' 16 and 'ఒడంబడిక' 0.", "Use 'శ్రీబాగ్ ఒప్పందం'."),
    (30, "(chapter)", None, "Notes use 'జెంటిల్మెన్స్ అగ్రిమెంట్' 42 and 'పెద్దమనుషుల ఒప్పందం' 0.", "Pick the learner-facing form for the title and subtopics."),
    (27, "dhar-commission", None, "'ధార్ కమిషన్' 1 vs 'ధార్ కమీషన్' 0.", "Keep, once the spelling is confirmed."),
    (27, "jvp-committee", None, "The notes write 'JVP' in Latin letters 7 times; the Telugu form 'జె.వి.పి' has 0.", "Decide the transliteration for the committee name."),
    (29, "(chapter)", None, "'SRC' appears in Latin letters 81 times and 'రాష్ట్రాల పునర్వ్యవస్థీకరణ' 9 times.", "Decide whether the learner-facing name uses the abbreviation."),
    (19, "home-rule", None, "'హోమ్ రూల్' 0 vs 'స్వపరిపాలన' 5 in the notes.", "Reviewer to choose."),
]
CHAPTER_NOTES = {
    9: "Highest count; six per-ruler subtopics could be reduced.",
    8: "Includes the new `art-architecture`; several subtopics overlap and some have no source.",
    12: "Thin source coverage: most subtopics have no note section.",
    24: "Low count and overlaps chapter 23.",
    28: "Low count; the merger debate also lives in chapters 29 and 30.",
    29: "Several subtopics have no source.",
    31: "Spans 58 years; subtopics overlap with chapters 21, 22 and 25.",
    14: "Thematic chapter: no_source is expected because questions keep one primary dynasty chapter.",
}
